### ISSUE TITLE
SELECT statement increasing uncommitted transactions

### ISSUE THREAD

**Issue by ap-pauloafonso** [dbeaver/dbeaver#8070] opened 2020-03-03 16:47 UTC
![image](https://user-images.githubusercontent.com/26802978/75798128-e347f000-5d54-11ea-9c74-faf4e12583ce.png)

Dbeaver version:  7.0 Windows 64
Database: Oracle

**Comment by JGLee-KR** [comment] 2020-03-03 23:58
ROLLBACK increasing uncommitted transactions too
![image](https://user-images.githubusercontent.com/61763909/75831234-505f9200-5df6-11ea-85b8-c8413d76f99a.png)

**Comment by uslss** [comment] 2020-03-04 10:00
thanks for the bug report

**Comment by serge-rider** [comment] 2020-03-04 11:32
It is not a bug. Once you are in transaction mode every SQL query is transactional. SELECT query locks resources/tables/rows. That's why we show it there.

You can use Smart-commit mode. In this case dbeaver will switch back to auto-commit after transacton end.

**Comment by ap-pauloafonso** [comment] 2020-03-04 13:16
![image](https://user-images.githubusercontent.com/26802978/75882716-7c801080-5e00-11ea-9e3a-68f7020ed99a.png)
@serge-rider with smart-commit i should the get the same feature as before right? (eg show uncomitted transactions) and it seems that its not working, can anybody confirm this? that is a big feature for me ;)

**Comment by serge-rider** [comment] 2020-03-12 16:14
@ap-pauloafonso please check https://github.com/dbeaver/dbeaver/wiki/Auto-and-Manual-Commit-Modes

**Comment by ap-pauloafonso** [comment] 2020-03-12 16:45
@serge-rider i still dont know why i'm getting empty transaction log screen ,even with pending transactions ;(

**Comment by p91paul** [comment] 2020-03-14 22:24
I think this is a regression in 7.0...
Some releases ago you modified the behavior so that commit and rollback were always enabled in manual commit mode, which is fine. However, select statements did not increase transaction count. 7.0 broke this, and now select is increasing count again.

**Comment by p91paul** [comment] 2020-03-14 22:40
Here is the relevant decision https://github.com/dbeaver/dbeaver/issues/6618#issuecomment-526191526

**Comment by uslss** [comment] 2020-04-20 15:17
fixed in scope of #8416

**Closed by uslss** 2020-04-20 15:17 UTC
Labels: question
