### ISSUE TITLE
Problem with the diagram image

### ISSUE THREAD

**Issue by WalexNet** [dbeaver/dbeaver#7648] opened 2020-01-15 19:42 UTC
Hi, I have had a problem with the image of the diagram for a long time, when I give it to save image "of the diagram" the image that it saves is not correct.

Thank you
![diagrama](https://user-images.githubusercontent.com/29197384/72464899-7c876b00-37d6-11ea-9965-aadb73e29aa6.png)

#### System information: 
- Operating system (distribution) and version -> **OS: Ubuntu 19.10 x86_64 Kernel: 5.3.0-26-generic**
- DBeaver version -> **Versión6.3.2.202001051908**
- Additional extensions -> **No extensions**

#### Connection specification:
- Database name and version -> **Server version: 10.4.11-MariaDB-1:10.4.11+maria~eoan-log**
- Driver name -> **MariaDB**
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  **No**

**Comment by uslss** [comment] 2020-01-16 15:05
Seems to be a duplicate of #7300 
Issue will be closed.
Anyway, thanks for the bug report

**Closed by uslss** 2020-01-16 15:05 UTC
Labels: bug
