### ISSUE TITLE
Invalid thread access

### ISSUE THREAD

**Issue by djigitlike** [dbeaver/dbeaver#23467] opened 2024-04-18 14:16 UTC
### Description

I'getting the Invalid thread access error every time when I try to connect to Postgres DB

### DBeaver Version

24.02

### Operating System

ubuntu

### Database and driver

PostgreSQL JDBC Driver

### Steps to reproduce

1. I try to connect to Postgres database
2. The error appears 
3. 
![image](https://github.com/dbeaver/dbeaver/assets/140714256/87dfd1a5-403a-41b6-926a-5c88682d7b40)

### Additional context

org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:565)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:481)
	at org.eclipse.swt.custom.CLabel.setText(CLabel.java:934)
	at org.jkiss.dbeaver.ui.controls.StatusLineContributionItemEx.setText(StatusLineContributionItemEx.java:93)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationActionBarAdvisor.updateTimezoneItem(ApplicationActionBarAdvisor.java:354)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationActionBarAdvisor.lambda$0(ApplicationActionBarAdvisor.java:366)
	at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:47)
	at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:37)
	at org.jkiss.dbeaver.model.impl.preferences.BundlePreferenceStore.setValue(BundlePreferenceStore.java:255)
	at org.jkiss.dbeaver.registry.timezone.TimezoneRegistry.setDefaultZone(TimezoneRegistry.java:46)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:590)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:120)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:276)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:171)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:106)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:115)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1366)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1243)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1033)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:117)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2505)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:89)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:73)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by E1izabeth** [comment] 2024-04-18 14:46
Thank you for bug report. It's a duplicate of #23352
Fix will be included in version 24.0.3 and already available in the Early Access version https://dbeaver.io/files/ea/

**Closed as not planned by E1izabeth** 2024-04-18 14:46 UTC
Labels: duplicate, xf:connection
