### ISSUE TITLE
Unable to open Dbeaver community after installation

### ISSUE THREAD

**Issue by SSPSSP109** [dbeaver/dbeaver#35897] opened 2024-10-10 04:33 UTC
### Description

Unable to open Dbeaver community after installation.
Nothing is appearing when I double click on the icon.

### DBeaver Version

 dbeaver-ce-24.2.1-win32.win32.x86_64

### Operating System

Windows Server 2019

**Comment by E1izabeth** [comment] 2024-10-10 09:29
Please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files) Thank you.

**Comment by alenvukelic** [comment] 2024-10-11 08:24
Same here, looks like some issue with java SWT library:
```
!SESSION 2024-10-11 10:13:46.497 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\user\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2024-10-11 10:13:48.617
!MESSAGE An error occurred while automatically activating bundle org.eclipse.ui.ide (164).
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start() of bundle org.eclipse.ui.ide.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:854)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:775)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1057)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:387)
	at org.eclipse.osgi.container.Module.doStart(Module.java:639)
	at org.eclipse.osgi.container.Module.start(Module.java:498)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:528)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:122)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:620)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:348)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getRecentWorkspaces(DBeaverApplication.java:377)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.setIDEWorkspace(DBeaverApplication.java:353)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:192)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:650)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:610)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1461)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	C:\Program Files\DBeaver\swt-win32-4966r5.dll: The specified procedure could not be found
	no swt-win32 in java.library.path: C:\Program Files\DBeaver;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\PHP\v7.4;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;.
	no swt in java.library.path: C:\Program Files\DBeaver;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\PHP\v7.4;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;.
	Can't load library: C:\Users\user\.swt\lib\win32\x86_64\swt-win32-4966r5.dll
	Can't load library: C:\Users\user\.swt\lib\win32\x86_64\swt-win32.dll
	Can't load library: C:\Users\user\.swt\lib\win32\x86_64\swt.dll
```
Indeed, folder C:\Users\user\.swt\lib\win32\x86_64 was empty, found & copied swt-win32-4966r5.dll to that dir, but can't find other two anywhere on system (Win Server 2019, and was upgrading from previous version, now I can't start no matter what (as Admin, as current user, installed for all users and tried for current user also)

**Comment by Phillipus** [comment] 2024-10-11 08:57
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1500

**Comment by E1izabeth** [comment] 2024-10-14 09:22
Thank you for the bug report.
I'm closing it as it's a duplicate of https://github.com/dbeaver/dbeaver/issues/35694

The issue comes from the platform on which DBeaver is based.
Here are two options that might help:
- Downgrade DBeaver to 24.2.0
- Try upgrading Windows. If no additional minor upgrades are available, upgrade to a higher major release of Windows. Experiments show that at least Windows Server 2022 works.

**Closed as not planned by E1izabeth** 2024-10-14 09:22 UTC
Labels: duplicate, xo:windows, xo:eclipse, third party issue
