### ISSUE TITLE
app can not run by 'openjdk 14' on Mac

### ISSUE THREAD

**Issue by TyouSF** [dbeaver/dbeaver#8229] opened 2020-03-20 07:03 UTC
After upgrading the java to 'openjdk 14', the application can not run with the error "Failed to create the Java Virtual Machine."

**Comment by mmoehring** [comment] 2020-03-20 11:30
This might be an upstream bug:
https://bugs.openjdk.java.net/browse/JDK-8238225

> One problem reported is when trying to launch Eclipse IDE bundles. The VM cannot be created when using the new bundle structure.

**Comment by Strat1987** [comment] 2020-03-20 19:32
I'm experiencing a similar issue

**Comment by TyouSF** [comment] 2020-03-21 15:53
> Trying from command line with forced VM:
> 
> ```
> ./dbeaver -vm /Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/bin/java
> Error: could not find libjava.dylib
> Failed to GetJREPath()
> ```
> 
> This might be an upstream bug:
> https://bugs.openjdk.java.net/browse/JDK-8238225
> 
> > One problem reported is when trying to launch Eclipse IDE bundles. The VM cannot be created when using the new bundle structure.
> 
> resp. related also this one:
> https://bugs.openjdk.java.net/browse/JDK-8213362

How can I find the location of "./dbeaver" to excute command line?
Message: I installed the dbeaver by 'brew cask'.

**Comment by cbertelli** [comment] 2020-03-22 21:58
me too. Are there workarounds? Where should I put the reference to another JRE?

**Comment by serge-rider** [comment] 2020-03-22 22:03
dbeaver runs with JDK 8, 9, 10, 11, 12.
Workaround: use dbeaver mak installer (pkg) which comes with bundled JDK 11.

Hopefully this issue will be addressed in the new Eclipse platform.

**Comment by livelazily** [comment] 2020-03-23 07:48
@cbertelli Workarounds:
Edit `/Applications/DBeaver.app/Contents/Info.plist` file, and add jdk path like this:  
![image](https://user-images.githubusercontent.com/449935/77293636-a9e41e00-6d1d-11ea-935d-8ac7f5231a68.png)

**Comment by mmoehring** [comment] 2020-03-23 08:40
At least on my system it runs fine one JDK13 too.

**Comment by cbertelli** [comment] 2020-03-23 13:54
Thank you very much. It was already in a comment of the parameter file, but I didn't see.
It runs like a charm with JDK13 as well.

**Comment by weyderfs** [comment] 2020-03-24 20:04
> @cbertelli Workarounds:
> Edit `/Applications/DBeaver.app/Contents/Info.plist` file, and add jdk path like this:
> ![image](https://user-images.githubusercontent.com/449935/77293636-a9e41e00-6d1d-11ea-935d-8ac7f5231a68.png)

Here I will need change the path of OpenJDK

<img width="417" alt="image" src="https://user-images.githubusercontent.com/1542315/77471644-707ce280-6df1-11ea-8272-fdafbc3c2946.png">

**Comment by cbertelli** [comment] 2020-03-24 20:57
Sorry, I didn't mention what I did before, which seems obvious to me, but it's not; I found out other JRE/JDKs, issuing this:
`$ sudo find /  -executable -type f -name java`
And I choose from the output list the right java command with its path to put there.
If the version is compatible, It should work. In don't like having a lot of wasted disk space with multiple uncontrolled java versions (inside applications), but in this case it's an advantage! Sometimes it's better wasting than sparing.

**Comment by ijuanfe** [comment] 2020-03-26 21:38
For those like me who installed these two apps through Homebrew cask:

1. Dbeaver 7.0.1 (brew cask install dbeaver-community)
2. adoptopenjdk 14 (brew cask install adoptopenjdk)

this was my solution:

1. Uninstall adoptopenjdk 14: `brew cask uninstall adoptopenjdk`
2. Install another adoptopenjdk version: `brew tap AdoptOpenJDK/openjdk`
3. Install adoptopenjdk 13: `brew cask install adoptopenjdk13`

now everything is working like a charm, let's just wait for the Dbeaver team to solve this issue.

**Comment by wkuckro** [comment] 2020-03-29 17:19
@ijuanfe this didn't work for me, even after doing `brew cask reinstall dbeaver-community`  and a machine restart. 

using the latest download from https://dbeaver.io/download/ was my workaround until we can get the homebrew workflow working again

**Comment by SunMar** [comment] 2020-03-29 17:24
@wkuckro it initially also didn't work for me because it turned out my default java in /usr/bin/java was still pointing to a 14 JRE. Check if you have any other JREs installed already (f.ex. the non-cask java/openjdk package or the Oracle JDK). `brew search java` and `brew search jdk`.

What does running `java --version` tell you?

**Comment by SunMar** [comment] 2020-03-29 17:28
@wkuckro @ijuanfe also I suggest using a JRE between 8 and 12 as those are the official supported versions mentioned by @serge-rider. version 13 is not one of them. version 11 is for DBeaver probably the best choice as that is the version it comes normally bundled with

**Comment by ijuanfe** [comment] 2020-03-29 17:45
@wkuckro look at what @SunMar just said, you are probably running a 14 JRE. Check the screenshot of my terminal output when running `brew search jdk` and `brew search java`:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/23366614/77855843-bef6fc00-71b8-11ea-83d4-c8841d7dc77b.png">

As you can see, there is only one package installed 'adoptopenjdk13' (by the way JDK includes JRE) and this is the information about the installed version:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/23366614/77856007-ed290b80-71b9-11ea-9888-e3e02a811bb8.png">

@wkuckro I've been using the 13 JDK version and no problems so far, but people should consider what you said about using the official supported versions.

**Comment by serge-rider** [comment] 2020-03-30 13:14
https://www.eclipse.org/forums/index.php?t=msg&th=1102885&goto=1823113&#msg_1823113.

**Comment by serge-rider** [comment] 2020-04-05 06:48
Official Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559482

The problem is in the way AdopOpenJDK packages Java for Mac (symlink issue).

Workaround: install dbeaver from pkg package (from https://dbeaver.io/download) as it contains properly configured Java.

I'm not sure who should fix the bug: AdopOpenJDK or Eclipse. 
Unfortunately I don't see how can we fix this from dbeaver side.

**Comment by antoniuslin** [comment] 2020-04-09 20:26
Bump the topic with additional notes to share.

I've got a similar issue. I'm not sure the version I have is from the AdoptOpenJDK package or not. I don't remember exactly when I installed it or what required it. But here's what I have:

MacOS Catalina
```
$ sw_vers -productVersion
10.15.4
```

OpenJDK (doesn't show AdoptOpenJDK version description)
```
$ java -version
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

$ javac -version
javac 14
```

Brew cask install list (**does** show AdoptOpenJDK version) and point to the same version above
```
$ brew cask list
adoptopenjdk
...
$ brew cask info adoptopenjdk
adoptopenjdk: 14,36
https://adoptopenjdk.net/
/usr/local/Caskroom/adoptopenjdk/14,36 (149B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/adoptopenjdk.rb
==> Name
AdoptOpenJDK Java Development Kit
==> Artifacts
jdk-14+36 -> /Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk (Generic Artifact)
==> Caveats
More versions are available in the AdoptOpenJDK tap:
  https://github.com/AdoptOpenJDK/homebrew-openjdk

  brew tap adoptopenjdk/openjdk
```

Maybe it's still subject to the same symlink issue a few others have mentioned here re: the AdoptOpenJDK package install effects.

I will try the suggested workaround using the dbeaver installation package.

> Official Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559482
> 
> The problem is in the way AdopOpenJDK packages Java for Mac (symlink issue).
> 
> Workaround: install dbeaver from pkg package (from https://dbeaver.io/download) as it contains properly configured Java.
> 
> I'm not sure who should fix the bug: AdopOpenJDK or Eclipse.
> Unfortunately I don't see how can we fix this from dbeaver side.

My question is:

Does the phrase "it contains properly configured Java" mean it's installing additional JDK into the machine or bundled with the `dbeaver.app` structure?

I would like to be able to easily drop the `dbeaver.app` and replace it with the `brew cask install dbeaver-community` again in the future when the symlink issue is fixed.

Thank you.

**Comment by serge-rider** [comment] 2020-04-17 13:41
This issue will be fixed in the next AdopOpenJDK 11 and 14 releases. See https://www.eclipse.org/eclipse/development/readme_eclipse_4.15.php:

```
Eclipse fails to start on macOS with Java 14
Eclipse fails to launch with OpenJDK 14 and OpenJDK 11.0.6 
on macOS (bug 561273) with the following error message: 
Error: could not find libjava.dylib Failed to GetJREPath(). 
The problem has been fixed in OpenJDK and is expected to 
be available in the next update of OpenJDK 11 (11.0.7) and OpenJDK 14 (14.0.1).
```

Fixed in https://bugs.eclipse.org/bugs/show_bug.cgi?id=561273.

**Closed** 2020-04-17 13:42 UTC
Labels: bug, xo:macos, xp:major

**Comment by sunsear** [comment] 2020-04-22 08:57
Works for me with Oracle-jdk-14.0.1. The AdoptJDK version 14.0.1 is not out through brew at this moment, but at least I can use DBeaver again.

**Comment by antoniuslin** [comment] 2020-07-08 03:43
> Bump the topic with additional notes to share.
> 
> I've got a similar issue. I'm not sure the version I have is from the AdoptOpenJDK package or not. I don't remember exactly when I installed it or what required it. But here's what I have:


My issue seems to have disappeared (resolved?) after updating the next `adoptopenjdk` (14.0.1) and `dbeaver-community` (7.1.2). Not sure which one actually fixes it, but all good on my end. Thank you.

```
$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```

```
$ javac -version
javac 14.0.1
```

```
$ brew cask info dbeaver-community
dbeaver-community: 7.1.2
```

**Comment by aint** [comment] 2020-11-07 13:52
It looks like DBeaver doesn't work with Java installed via [Sdkman](https://sdkman.io/).
I set a java path in `Info.plist`:
`<string>-vm</string><string>~/.sdkman/candidates/java/14.0.2.hs-adpt/bin/java</string>`

and get this
```
/Applications/DBeaver.app/Contents/MacOS/dbeaver                                                               
WARNING: Using incubator modules: jdk.incubator.jpackage, jdk.incubator.foreign
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.2.4.202011011603]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.200.v20200205-1503]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.700.v20200106-1020]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.17.0.v20200217-1511]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.2.4.202011011603]
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
No Java runtime present, requesting install.
```
![image](https://user-images.githubusercontent.com/3179252/98442982-10814500-2111-11eb-8ac1-7d9bc71237d5.png)
