### ISSUE TITLE
gray rectangle instead of data

### ISSUE THREAD

**Issue by Niccolum** [dbeaver/dbeaver#5854] opened 2019-05-06 08:11 UTC
#### System information: 
- Operating system (distribution) and version: Debian 9
- DBeaver version: 6.04 ce
- Java version:
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

#### Connection specification:
- Database name and version: SQLite
- Driver name: 
sqlite-jdbc-3.27.2.1.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc): I use connection on sftp, like
/run/user/1000/gvfs/sftp:host=192.168.1.90,port=4772/opt/file.db

#### Describe the problem you're observing:
When i trying to see data in Grid view, i see gray empty place, but when i switching view to Text - a see all data correct
Also, when i choose Grid - i see data correct, but for a few milliseconds, after that, i see only gray place
![Screenshot from 2019-05-06 11-11-26](https://user-images.githubusercontent.com/32839735/57213513-bbcaae80-6fef-11e9-8ae6-62604251ef6d.png)
![Screenshot from 2019-05-06 11-11-17](https://user-images.githubusercontent.com/32839735/57213514-bbcaae80-6fef-11e9-8344-0f79d4b84161.png)

#### Steps to reproduce, if exist:
Open any table > Data > Grid

#### Include any warning/errors/backtraces from the logs

[.log](https://github.com/dbeaver/dbeaver/files/3147023/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3147024/dbeaver-debug.log)

**Comment by serge-rider** [comment] 2019-05-06 09:11
This looks like an issue with GTK version.
Could you try to execute
```sh
export GTK_IM_MODULE="ibus"
```
before running DBeaver.

**Comment by Niccolum** [comment] 2019-05-07 06:48
No, this doesn't help.
My exports
[exports.txt](https://github.com/dbeaver/dbeaver/files/3151133/exports.txt)

**Comment by Niccolum** [comment] 2019-05-17 18:08
Anyone?

**Comment by serge-rider** [comment] 2019-05-26 19:17
Generally this caused by the final migration to GTK3 in latest Eclipse platform versions (GTK2 is no longer supported).
I don't see any log entries related to data viewer (in spreadsheet mode) and thus I have no clue how to handle this so far. But I see a lot of log records related to connection editor opening.

This issue seems to be caused by this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=542675 (which was actually closed as duplicate of https://bugs.eclipse.org/bugs/show_bug.cgi?id=517671)
At the moment the only suggested workaround is to use IM module `ibus`.

If this doesn't help then there is very little I can do.

You could try to switch to classic UI theme (Preferences->General->Appearance->Theme) which should consume less UI resources. But honestly I doubt it will help..

Anyway, any extra details would be helpful.

**Comment by megabait1212** [comment] 2019-06-13 12:10
How I fixed it:
Created file "Dbeaver.desktop" on the desktop with this content
```
#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=env GTK_IM_MODULE=ibus /var/lib/flatpak/app/io.dbeaver.DBeaverCommunity/current/active/files/dbeaver/dbeaver
Path=/var/lib/flatpak/app/io.dbeaver.DBeaverCommunity/current/active/files/dbeaver
Name=Dbeaver with ibus
GenericName=SQL Database Client
Comment=Universal Database Manager and SQL Client.
WM_CLASS=DBeaver
StartupWMClass=Dbeaver
StartupNotify=true
Icon=/var/lib/flatpak/app/io.dbeaver.DBeaverCommunity/current/active/files/dbeaver/dbeaver.png
Categories=TextEditor;Development;
```
**Icon, Path and Exec path could be different.**
Then made the file executable
`chmod +x Dbeaver.desktop`

**Comment by slamtrooper** [comment] 2019-07-26 14:20
I'd like to confirm that the above solution by @megabait1212 worked for me, as well (dbeaver-ce 6.1.3, Debian 9). In my case, the default desktop file is `/usr/share/applications/dbeaver.desktop`. Prepending with the ENV required a single line change:

```
#Exec=/usr/share/dbeaver/dbeaver
Exec=env GTK_IM_MODULE=ibus /usr/share/dbeaver/dbeaver
```

**Comment by juarezr** [comment] 2019-10-02 16:10
> I'd like to confirm that the above solution by @megabait1212 worked for me, as well (dbeaver-ce 6.1.3, Debian 9). In my case, the default desktop file is `/usr/share/applications/dbeaver.desktop`. Prepending with the ENV required a single line change:
> ```
> #Exec=/usr/share/dbeaver/dbeaver
> Exec=env GTK_IM_MODULE=ibus /usr/share/dbeaver/dbeaver
> ```

:+1:  The fix from @megabait1212 and @slamtrooper works well for Ubuntu 19.04. Thanks!
 :-1: Without this DBeaver becomes unusable! 

Any chance of this dbeaver.desktop file being fixed definitively in some release?

All instalation bundles for linux have this problem:

- https://dbeaver.io/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
- http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu
- snap install dbeaver-ce

**Closed** 2019-11-21 13:27 UTC
Labels: bug, question, xo:eclipse, xo:linux
