### ISSUE TITLE
Auto format for upper case not working since version 22.2.4

### ISSUE THREAD

**Issue by dahmmme** [dbeaver/dbeaver#18144] opened 2022-11-08 09:13 UTC
### Description

**H**ello :)

Since the latest DBeaver upgrade (22.2.4), the keyword automatic upper case formatting for SQL does not seem to be working anymore.

My settings have not changed, and it did work with the prior version.

**Settings**
Preferences > SQL Editor > Formatting > Settings: Keyword case > upper
Preferences > SQL Editor > Code Editor > Auto format > Convert keyword case checked

### DBeaver Version

22.2.4

### Operating System

Windows 10

### Database and driver

- Postgres Version: 10.22
- JDBC: 42.2.20

### Steps to reproduce

1. Open a PostgreSQL connection
2. Use the mentioned settings.
3. Write a random query.

**Comment by LonwoLonwo** [comment] 2022-11-08 09:37
Hello @dahmmme 

Please check this setting:

![2022-11-08 12_35_17-DBeaver 22 2 4 - NULLID](https://user-images.githubusercontent.com/45152336/200529340-09940988-5355-4f0d-9aba-5f0cc1086284.png)

Maybe you need to set it to UPPER

**Comment by dahmmme** [comment] 2022-11-08 09:54
Hello @LonwoLonwo 

It was set to **standard** and I changed it to **upper** — unfortunately, it is still not working.
The behavior I had in the prior version was the keywords automatically being formatted to uppercase whenever I wrote them, which also made the code a lot more easier to read!

**Comment by LonwoLonwo** [comment] 2022-11-08 09:59
Ok, thanks for the answer @dahmmme

**Comment by LonwoLonwo** [comment] 2022-11-08 10:00
Closed as duplicate of: https://github.com/dbeaver/dbeaver/issues/18131

**Closed as not planned by LonwoLonwo** 2022-11-08 10:00 UTC
Labels: duplicate, xf:sql

**Comment by LonwoLonwo** [comment] 2022-11-08 10:09
And ok, I see, keyword formatting does not work if I use space after the word, but it works if I use Enter during the keyword auto-completion.

![mfgvXNgZBS](https://user-images.githubusercontent.com/45152336/200536743-8d70517f-68d9-4459-8b71-1680cf25150d.gif)
