### ISSUE TITLE
Native Client Path

### ISSUE THREAD

**Issue by mbnoimi** [dbeaver/dbeaver#10320] opened 2020-11-12 09:47 UTC
#### System information: 
- Operating system: Linux Mint 20.1 xfce
- DBeaver version: Version 7.3.3.202101161839

#### Connection specification:
- Database: PostgreSQL 13.1
- Driver name: PostgreSQL

#### Describe the problem you're observing:
Unable to create Backup/Restore because of invalid native client path

#### Steps to reproduce, if exist:
1. Edit Connection
2. Edit Driver Settings
3. Native Client (tab)
4. Add Home (button)
5. Select Native Client path which is in my case `/usr/` but the path showed as `/run/user/1000/doc/6112140e/usr` (this is wrong I think)
6. Tried to make a backup, but I got this error:
```
Error executing process
  Cannot run program "/run/user/1000/doc/6112140e/usr/bin/pg_dump" (in directory "/run/user/1000/doc/6112140e/usr/bin"): error=2, No such file or directory
  Cannot run program "/run/user/1000/doc/6112140e/usr/bin/pg_dump" (in directory "/run/user/1000/doc/6112140e/usr/bin"): error=2, No such file or directory
    error=2, No such file or directory
    error=2, No such file or directory
```
Terminal log:
```
$ ls -lh /usr/bin/pg_*
lrwxrwxrwx 1 root root   37 Nov 12 14:37 /usr/bin/pg_archivecleanup -> ../share/postgresql-common/pg_wrapper
lrwxrwxrwx 1 root root   37 Nov 12 14:37 /usr/bin/pg_basebackup -> ../share/postgresql-common/pg_wrapper
-rwxr-xr-x 1 root root  14K Oct 14 00:03 /usr/bin/pg_buildext
-rwxr-xr-x 1 root root 1.3K Nov  5  2018 /usr/bin/pg_config
-rwxr-xr-x 1 root root 6.3K Nov 10 15:45 /usr/bin/pg_config.libpq-dev
-rwxr-xr-x 1 root root 6.2K Jun 29  2017 /usr/bin/pg_conftool
-rwxr-xr-x 1 root root  35K Sep 29 15:24 /usr/bin/pg_createcluster
-rwxr-xr-x 1 root root  24K Nov 12 14:37 /usr/bin/pg_ctlcluster
-rwxr-xr-x 1 root root 7.6K Mar  2  2020 /usr/bin/pg_dropcluster
lrwxrwxrwx 1 root root   37 Nov 12 14:37 /usr/bin/pg_dump -> ../share/postgresql-common/pg_wrapper
lrwxrwxrwx 1 root root   37 Nov 12 14:37 /usr/bin/pg_dumpall -> ../share/postgresql-common/pg_wrapper
lrwxrwxrwx 1 root root   37 Nov 12 14:37 /usr/bin/pg_isready -> ../share/postgresql-common/pg_wrapper
-rwxr-xr-x 1 root root 5.2K Feb 24  2020 /usr/bin/pg_lsclusters
lrwxrwxrwx 1 root root   37 Nov 12 14:37 /usr/bin/pg_receivewal -> ../share/postgresql-common/pg_wrapper
lrwxrwxrwx 1 root root   37 Nov 12 14:37 /usr/bin/pg_receivexlog -> ../share/postgresql-common/pg_wrapper
lrwxrwxrwx 1 root root   37 Nov 12 14:37 /usr/bin/pg_recvlogical -> ../share/postgresql-common/pg_wrapper
-rwxr-xr-x 1 root root 5.8K Mar  1  2019 /usr/bin/pg_renamecluster
lrwxrwxrwx 1 root root   37 Nov 12 14:37 /usr/bin/pg_restore -> ../share/postgresql-common/pg_wrapper
-rwxr-xr-x 1 root root  34K Oct 22 15:16 /usr/bin/pg_upgradecluster
-rwxr-xr-x 1 root root 9.1K Oct 13 21:37 /usr/bin/pg_virtualenv

$ pg_dump --version
pg_dump (PostgreSQL) 13.1 (Ubuntu 13.1-1.pgdg20.04+1)
```
The other software able execute `pg_dump` without any problem.

**Comment by uslss** [comment] 2020-11-23 14:02
thanks for the report

**Comment by mbnoimi** [comment] 2020-11-23 14:08
I could reproduce the same bug for MySQL/MariaDB client.

**Comment by ShadelessFox** [comment] 2020-11-24 09:27
Hello, @mbnoimi, I cannot reproduce your issue. Can you try EA version? https://dbeaver.io/files/ea/

**Comment by mbnoimi** [comment] 2020-11-24 13:47
> Hello, @mbnoimi, I cannot reproduce your issue. Can you try EA version? https://dbeaver.io/files/ea/

Version 7.3.0.202011232112 works fine with PostgreSQL while I get the following error message for MariaDB:
```
/opt/lampp/bin/mysqldump --routines --add-drop-table --disable-keys --extended-insert -u root --host=localhost --port=3306 todolist
Task 'MySQL dump' started at Tue Nov 24 16:45:00 TRT 2020
mysqldump: Couldn't execute 'SHOW FUNCTION STATUS WHERE Db = 'todolist'': Column count of mysql.proc is wrong. Expected 21, found 20. Created with MariaDB 100108, now running 100416. Please use mysql_upgrade to fix this error (1558)

Task 'MySQL dump' finished at Tue Nov 24 16:45:00 TRT 2020
2020-11-24 16:45:00.982 - IO error: Process failed (exit code = 2). See error log.
2020-11-24 16:45:00.982 - java.io.IOException: Process failed (exit code = 2). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:208)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:188)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:248)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by mbnoimi** [comment] 2020-11-24 14:07
I'm able to run the following command through the terminal without any error message:
```
$ /opt/lampp/bin/mysqldump -u root --host=localhost --port=3306 todolist > ~/dump.sql
```

**Comment by ShadelessFox** [comment] 2020-11-24 14:14
This problem is not related to DBeaver nor ticket but native client itself. I can't really help you.
If the problem described in the ticket was solved, you can close it.

**Comment by mbnoimi** [comment] 2020-11-24 14:20
Works fine with Version 7.3.0.202011232112 thanks you

**Comment by mbnoimi** [comment] 2020-12-02 15:44
This bug continues to occur in **flatpak** Version 7.3.0.202011291229 while it doesn't occur in **gz** Version 7.3.0.202011291229 (dbeaver-ce-7.3.0-linux.gtk.x86_64.tar.gz)

**Comment by ShadelessFox** [comment] 2020-12-21 12:16
Hi again, @mbnoimi, is your problem still occurs on newer version (7.3.1)?

**Comment by mbnoimi** [comment] 2020-12-21 12:39
> Hi again, @mbnoimi, is your problem still occurs on newer version (7.3.1)?

I replaced the flatpak version with PPA version. The bug doesn't occur in PPA version 7.3.0

**Comment by ShadelessFox** [comment] 2020-12-21 12:48
> I replaced the flatpak version with PPA version. The bug doesn't occur in PPA version 7.3.0 (Version 7.3.0.202012062025)
Okay, if you will have any other problems related to local database clients, feel free to reopen this ticket or open a new one.

**Comment by mbnoimi** [comment] 2021-01-25 07:01
I can reproduce same bug with flatpak Version 7.3.3.202101161839 (I forced to use flatpak version because PPA version always outdated)

```ini
$ flatpak info --show-permissions io.dbeaver.DBeaverCommunity
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;ssh-auth;
devices=dri;
filesystems=home;host-os;host;

[Session Bus Policy]
org.freedesktop.Notifications=talk

[Environment]
PATH=/app/clients/bin:/app/jre/bin:/usr/bin
```

**Comment by mbnoimi** [comment] 2021-03-13 09:40
The bug still occurs with flatpak version `21.0.0.202102281712`
```ini
$ flatpak info --show-permissions io.dbeaver.DBeaverCommunity
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;ssh-auth;
devices=dri;
filesystems=home;host-os;host;

[Session Bus Policy]
org.freedesktop.Notifications=talk

[Environment]
PATH=/app/clients/bin:/app/jre/bin:/usr/bin
```

**Comment by regulator-g** [comment] 2021-05-30 02:38
same issue here can't restore a database because the cilent can't find pg_restore, I cant even manually type the /usr/bin path it just always selects /run/user/1000/doc/6112140e/usr. had to switch to the .deb package to be able to restore my database

**Comment by netdragonboberb** [comment] 2021-08-16 03:43
Install flatseal as described here https://github.com/dbeaver/dbeaver/issues/5008

**Comment by Destrolaric** [comment] 2022-01-26 08:07
This issue can't be fixed on the DBeaver side. Flatpak restricts executions outside its directory, you can change it manually by using Flatseal to change permissions.

**Closed** 2022-02-07 11:16 UTC
Labels: bug, won't fix, xo:linux, third party issue, sp:3, xf:flatpak

**Comment by gcclinux** [comment] 2023-03-18 11:14
> This issue can't be fixed on the DBeaver side. Flatpak restricts executions outside its directory, you can change it manually by using Flatseal to change permissions.

All permission set and I still have the issue:

I've set permission with 

$ sudo flatpak override io.dbeaver.DBeaverCommunity --filesystem=/usr/bin

$ flatpak info --show-permissions io.dbeaver.DBeaverCommunity
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;ssh-auth;
devices=dri;
filesystems=home;host-etc;/usr/bin;host-os;host;

[Session Bus Policy]
org.freedesktop.Notifications=talk
org.freedesktop.FileManager1=talk

[Environment]
PATH=/app/clients/bin:/app/jre/bin:/usr/bin


Issue still there and I am not sure how to fix this...

**Comment by ila-embsys** [comment] 2025-09-08 23:07
Another solution:

Install client `flatpak install io.dbeaver.DBeaverCommunity.Client.pgsql` or `flatpak install io.dbeaver.DBeaverCommunity.Client.mariadb`
Check binaries `flatpak run --command="ls" io.dbeaver.DBeaverCommunity -l /app/clients/bin`
Open `~/.local/share/DBeaverData/workspace6/.metadata/.config/drivers.xml`
Add `<clientHome id="/app/clients/bin" path="/app/clients/bin"/>`

Maybe the path `/app/clients/bin` could be added somewhere here?
https://github.com/dbeaver/dbeaver/blob/c9aea5706de32581b24faaf041d90e7178022ecb/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/connection/NativeClientLocationUtils.java#L90-L107
