### ISSUE TITLE
Cannot install DBeaver 6.0.5 into Eclipse IDE

### ISSUE THREAD

**Issue by xcariba** [dbeaver/dbeaver#5969] opened 2019-05-22 08:24 UTC
#### System information: 

- Fedora 30
- Trying to install 6.0.5
- 1.8
- Eclipse PDE, Xtext, DevStyle

#### Describe the problem you're observing:

Can`t install DBeaver plugin neither from p2 repository nor from marketplace.

#### Steps to reproduce, if exist:

1. Open **Install New Software** menu
2. Add url `https://dbeaver.io/update/latest/`
3. Check DBeaver
4. During install error occures

#### Include any warning/errors/backtraces from the logs

```Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver IDE 6.0.5.201905192156 (org.jkiss.dbeaver.ide.feature.feature.group 6.0.5.201905192156)
  Missing requirement: DBeaver GIS Support 1.0.33.201905192156 (org.jkiss.dbeaver.data.gis 1.0.33.201905192156) requires 'osgi.bundle; org.jkiss.bundle.gis 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver Databases 1.0.0.201905192156 (org.jkiss.dbeaver.db.feature.feature.group 1.0.0.201905192156)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ext.mysql [2.1.94.201905192156,2.1.94.201905192156]
  Cannot satisfy dependency:
    From: DBeaver MySQL Support 2.1.94.201905192156 (org.jkiss.dbeaver.ext.mysql 2.1.94.201905192156)
    To: osgi.bundle; org.jkiss.dbeaver.data.gis 0.0.0
  Cannot satisfy dependency:
    From: DBeaver IDE 6.0.5.201905192156 (org.jkiss.dbeaver.ide.feature.feature.group 6.0.5.201905192156)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.db.feature.feature.group [1.0.0.201905192156,1.0.0.201905192156]```

**Comment by famod** [comment] 2019-05-22 17:39
Same here, Eclipse 2019-03.

PS: I am also using `org.jkiss.dbeaver.ext.oracle` which was a "feature" until 6.0.5, now it is a "plugin".
I have yet to find out how to install this via Oomph, but for now I have to fall back to 6.0.4 anyway.

**Comment by cvgaviao** [comment] 2019-05-23 13:16
Seems that **DBeaver GIS Support** is not being provided in the latest p2 repository.

**Comment by serge-rider** [comment] 2019-05-26 17:20
Duplicate of #5991 (although this ticket was created earlier I have found it later).
Please see #5991 comments

**Closed by serge-rider** 2019-05-26 17:20 UTC
Labels: bug, duplicate, ready for qa, xo:eclipse
