### ISSUE TITLE
unable to filer processlist using MySQL

### ISSUE THREAD

**Issue by amirAtWork** [dbeaver/dbeaver#24971] opened 2024-04-22 09:41 UTC
### Description

If you run "show processlist" and then in the results pane filter on "is not null" the following is created and errors 

SELECT * FROM (
show processlist

) z_q WHERE Info IS

What I expect to happen is the null columns are excluded. I can do this in SQLYog for example to remove the noise.

### DBeaver Version

Community Edition Version 24.0.3.202404211624

### Operating System

Win 10

### Database and driver

Mysql  5.7
Driver 8.2.0

### Steps to reproduce

execute "show processlist"
right click in result pane on null value
select filter "is not null"

**Comment by LonwoLonwo** [comment] 2024-04-22 12:59
Hello @amirAtWork 

Thanks for the report.
This is a duplicate of https://github.com/dbeaver/dbeaver/issues/9968.
You can subscribe on the original ticket.

**Closed as completed** 2024-04-22 13:25 UTC
Labels: x:mysql, duplicate, xf:filters
