### ISSUE TITLE
Table data is not visible

### ISSUE THREAD

**Issue by megabait1212** [dbeaver/dbeaver#6003] opened 2019-05-26 18:27 UTC
Hi, I am using Linux Mint 19.1 Cinnamon window manager. And table data is not visible
![image](https://user-images.githubusercontent.com/5767396/58385705-27a3a400-7ffd-11e9-99e2-6d42bd7dc291.png). Little bit visible only in places where is scroll located, and when I am scrolling, I see that data is changed.
But if change the view from Grid to text become visible.
![image](https://user-images.githubusercontent.com/5767396/58385753-e65fc400-7ffd-11e9-9905-152e30c1a182.png)

Also, I had the same problem on ubuntu 18.04 with the mate window manager.
DB mysql, driver mysql-connector-java-5.1.44.jar
DBeaver version 6.0.5 Community edition

**Comment by megabait1212** [comment] 2019-05-26 18:48
When it starting it flashing data in the table.
Also, I doesn't allow to enter any data in the input (show nothing)
![image](https://user-images.githubusercontent.com/5767396/58385855-7f430f00-7fff-11e9-99de-8f422442d790.png)
And don't work "properties" (click in menu or shortcut Alt + Enter)

**Comment by serge-rider** [comment] 2019-05-26 19:04
Duplicate of #5854
Thanks for the details anyway.

**Closed by serge-rider** 2019-05-26 19:04 UTC
Labels: bug, duplicate, xo:eclipse, xo:linux
