### ISSUE TITLE
Generate SQL - >DDL for procedures and functions will script out cached version, not what the actual definition is on the database

### ISSUE THREAD

**Issue by waskelton4** [dbeaver/dbeaver#11198] opened 2021-02-03 01:59 UTC
#### System information: 
- Windows 10
- DBeaver 7.3.4
- Additional extensions: none

#### Connection specification:
- Postgresql 13
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When scripting out Create statements for functions and procedures, if the function or procedure has been changed on the database since the connection has been last refreshed, the Generate SQL feature will return the cached script, and not the script that has been run on the database.

#### Steps to reproduce, if exist:
1. Create new function or procedure
2. right click the Functions folder and click refresh.
3. right click the new function and Generate SQL -> DLL.
4. update the new function with a change.  
5. right click the new function and Generate SQL ->DLL.
6. Observe the change is not in the Generated DLL.
7. Right click on the database and choose refresh
8. Right click the new function and Generate SQL ->
9. Observe that the change is now scripted.

This issue has caused me to lose a good bit of work when I develop a function/procedure and then script it out to commit it. 
Thank you for your consideration of this bug and all the work you do to support this tool which is my clear choice for development in Postgresql.

**Comment by kseniiaguzeeva** [comment] 2021-02-03 06:17
I can reproduce it when update the function via SQL Editor. You need to press Refresh to see the changes, like you do in step 2 for the created function.
As a workaround you can edit the function in the editor.
![dbeaver_nfV86VLsBE](https://user-images.githubusercontent.com/51405061/106706317-8efe5d80-6600-11eb-8a55-770eb758c2d3.png)

**Comment by waskelton4** [comment] 2021-02-03 14:46
I have the same outcome when using the editor (Right click -> view function -> Source)  The DDL is still not current without the refresh.

Thanks for your help!

**Comment by kseniiaguzeeva** [comment] 2021-02-11 07:46
I close this ticket as a duplicate, because similar issues already exist. We will add automatic refresh in future releases in https://github.com/dbeaver/dbeaver/issues/6398.

**Closed as completed by kseniiaguzeeva** 2021-02-11 07:46 UTC
Labels: x:postgresql
