### ISSUE TITLE
Reserved word current_date is not being quoted in generated SQL for MariaDB

### ISSUE THREAD

**Issue by stringfold** [dbeaver/dbeaver#21617] opened 2023-10-20 23:44 UTC
### Description

As the title says, if you have a database table column with the name "current_date", you cannot perform any operations in DBeaver that includes that column in the generated SQL.

It looks like other column names that use reserve words, like "length" are quoted correctly in the SQL, but "current_date" is not quoted, which makes it impossible to do things like modify the column definition or export data from the table containing a column of that name directly.

I checked to see if anyone else has flagged this particular error, but didn't see an issue. Other reserved word issues were resolved several years ago.

### DBeaver Version

Community Edition 23.2.2.202310081633

### Operating System

Windows 11

### Database and driver

MariaDB version 10.3.38

### Steps to reproduce

1. Using the UI, create a new database table and add a column named current_date.
2. When you attempt to persist the change, the operation fails with the following error:

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'current_date varchar(100) NULL) 
> ENGINE=InnoDB
> DEFAULT CHARSET=utf8mb4
> COLLA...' at line 2

Exporting a table with a column of that name also fails.

**Comment by E1izabeth** [comment] 2023-10-21 19:25
Thank you for bug report.

**Comment by LonwoLonwo** [comment] 2023-10-23 11:01
CURRENT_TIMESTAMP and current_time are also reserved. Probably, as other functions.

**Comment by LonwoLonwo** [comment] 2024-02-26 09:32
I can't reproduce it against DBeaver 23.3.5

![2024-02-26 11_02_10-Window](https://github.com/dbeaver/dbeaver/assets/45152336/e809c537-79e1-4ae8-bd63-f300253d8a82)

Driver update helped, probably.
I'm closing this issue.

**Closed as completed by LonwoLonwo** 2024-02-26 09:32 UTC
Labels: x:mysql, xf:sql, xf:metadata, xp:normal
