### ISSUE TITLE
Unable to copy MSSQL data to table if IDENTITY_INSERT off

### ISSUE THREAD

**Issue by HappyMiner** [dbeaver/dbeaver#2193] opened 2017-09-21 05:23 UTC
Hi,

Today I was trying to import some data to a local docker MSSQL DB and found that there appears to be a bug when the table has IDENTITY_INSERT set to "off". Please find the article for solution of the access issue at the end. However, DBeaver will not allow implementation of the solution. 

When I enter the **command SET IDENTITY_INSERT [dbo].[my_ex_table] ON**, DBeaver responds with an error message: "Cannot find the object because it does not exist or you do not have permissions , error in SQL Server".

The object exists as a primary key, that has auto increment, auto generated, not null.

There is only one user for this local DB and that is the admin.

When I try to do the same with MSSQL PRO for Mac, set identity passes without any problem and I can then import my data.

This issue exists both for the MSSQL driver and the JDBC driver, not sure if related at all though.

https://stackoverflow.com/questions/1334012/cannot-insert-explicit-value-for-identity-column-in-table-table-when-identity

Many thanks in advance!

**Comment by serge-rider** [comment] 2017-09-24 21:15
Could you pose an example snippet (table DDL + SQL which reproduces the problem)?

Perhaps the problem is in some JDBC-specific behavior.

**Comment by HappyMiner** [comment] 2017-09-25 03:25
There is no code available for this from my end. I used the "export and import to" functions that are available in DBeaver. The wizard basically exited with an error message telling me that I cannot update the table since IDENTITY_INSERT [dbo].[my_ex_table] OFF. Trying to set it to on through a query window would result in "Cannot find the object because it does not exist or you do not have permissions, error in SQL Server".

To reproduce, I would think having a (native) MSSQL table with SET IDENTITY_INSERT [dbo].[my_ex_table] OFF should do the trick. In my case I am using docker and if I go through MSSQL Pro, it works without any issues. There I can just execute SET IDENTITY_INSERT [dbo].[my_ex_table] ON, insert my data thought the CSV import function and then SET IDENTITY_INSERT [dbo].[my_ex_table] OFF again.

**Comment by vstokesjr** [comment] 2017-11-03 11:28
Similar issue here. I was attempting to import a CSV into an empty table but get the IDENTITY_INSERT error message. Need and option to enter pre-sql and post-sql statements to be executed whem importing orexporting data via CVS (or any connection).

**Comment by serge-rider** [comment] 2017-11-12 16:50
Should be tracked in #810

**Comment by Foorack** [comment] 2019-03-20 08:37
Any update on this? Would love a simple checkbox "Enable identity insert when inserting data" when using the Export>Database tool.

**Comment by pfurini** [comment] 2019-05-21 15:28
Even if #810 is marked as closed, this issue is still current in DBeaver 6.0
I tried to import data from various sources in a SQL Server table with an identity column, with no success.

The only way to work around this (using only the UI) is to copy the source table as TSV in the clipboard, then pasting it in DBeaver, and finally transforming the inserted data in a script. Then you can copy the script and paste it a new SQL editor, add the `SET IDENTITY_INSERT mytable ON` at the top and execute the script...

Not so much convenient ;)

**Comment by serge-rider** [comment] 2019-07-25 11:44
Done.
1. You can disable identity (auto-generated) columns migration at all:
![image](https://user-images.githubusercontent.com/6398845/61871783-f1da4900-aee1-11e9-9ef4-5cf1100ff2b6.png)

2. If auto-generated column migration is enabled (it is enabled by default) then SQL Server extension will  execute  SET IDENTITY_INSERT ... before and after data transfer procedure.

**Comment by uslss** [comment] 2019-07-30 04:38
verified

**Closed by uslss** 2019-07-30 04:38 UTC
Labels: enhancement, x:mssql
