### ISSUE TITLE
Newly created database not showing up in pull-down

### ISSUE THREAD

**Issue by Taariqq** [dbeaver/dbeaver#7536] opened 2020-01-06 07:02 UTC
#### System information: 
- Operating system (distribution) and version = Linux Mint
- DBeaver version = 6.3.2
- Additional extensions = none

#### Connection specification:
- Database name and version = MySQL 
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? = no

#### Describe the problem you're observing:
Newly created databases, using CREATE DATABASE ...  command, are not showing up in the top toolbar pull-down menu and the schema and table names are not showing up in the intellisense either. If I run SHOW DATABASES command the database shows up and I can use/see the tables with the commands.
Restarting DBeaver resolves the issue, [edit] in that the ones created before the restart show up but ones after the restart have same problem.

**Comment by kseniiaguzeeva** [comment] 2020-01-06 07:47
Thank you for the bug report. It is actual for Win 10 too.

**Comment by serge-rider** [comment] 2020-04-27 16:26
Duplicate of #7924

**Closed by serge-rider** 2020-04-27 16:26 UTC
Labels: bug, duplicate
