### ISSUE TITLE
Error "Internal error when opening new connection wizard"

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#20983] opened 2023-08-24 08:03 UTC
### Description

Trying to open a "New Connection" wizard, error as in screenshot appears

### DBeaver Version

Version 23.1.5.202308201919

### Operating System

Ubuntu 20.04.6 LTS

### Database and driver

N/A

### Steps to reproduce

Just open dbe, and try to create a new connection

### Additional context

![image](https://github.com/dbeaver/dbeaver/assets/3930671/cf17890b-5150-4b4c-9c19-5c814428fbeb)

**Comment by LonwoLonwo** [comment] 2023-08-24 10:53
Hello @wiwwo 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by wiwwo** [comment] 2023-08-24 11:18
Hi @LonwoLonwo ,
link is broken, i think you mean 
https://dbeaver.com/docs/dbeaver/Log-files/
Also, documentation is broken, since env var '$XDG_DATA_HOME' is not set in my case.
Anyway,
those are the logs you might be refering to :
[dbeaver-debug-1692875535849.log](https://github.com/dbeaver/dbeaver/files/12428804/dbeaver-debug-1692875535849.log)
[dbeaver-debug-1692862412492.log](https://github.com/dbeaver/dbeaver/files/12428815/dbeaver-debug-1692862412492.log)
[dbeaver-debug-1692869073553.log](https://github.com/dbeaver/dbeaver/files/12428817/dbeaver-debug-1692869073553.log)

**Comment by LonwoLonwo** [comment] 2023-08-24 11:29
Ok, thanks. It looks like a duplicate of https://github.com/dbeaver/dbeaver/issues/20931

Could you please check the latest Early Access version https://dbeaver.io/files/ea/?

Does this issue still happen there?

**Closed as not planned** 2023-08-27 11:24 UTC
Labels: duplicate, xf:ui

**Comment by wiwwo** [comment] 2023-09-04 13:33
I can confirm the fixing with the latest version 23.2.0

**Comment by E1izabeth** [comment] 2023-09-04 13:34
Thank you for update
