### ISSUE TITLE
Navigate to a column in the data grid.

### ISSUE THREAD

**Issue by z1hou** [dbeaver/dbeaver#21019] opened 2023-08-28 13:05 UTC
While examining data for SQLs that return a large number of columns, it would be convenient to navigate to the column by specifying a column name off the context menu on the grid - maybe under Navigate and a suboption "column name"? It is somewhat possible by sorting the columns in the record view and switching back to the column view. But again for SQLs that return a large number of columns, it is still not the easiest way of doing so. This feature is available in a few other tools including SQL Workbench/J.
Thank you.

**Comment by E1izabeth** [comment] 2023-08-28 13:07
Thank you for the idea!

**Comment by E1izabeth** [comment] 2023-08-29 10:21
I'm closing this issue as it's a duplicate of #3052. You can vote for the mentioned issue with 👍🏻 under the issue description.

**Closed as not planned by E1izabeth** 2023-08-29 10:21 UTC
Labels: duplicate, xf:data

**Comment by z1hou** [comment] 2023-08-29 15:07
Used Metadata (Ctrl-Alt-F4) and chose the column there. It moved the cursor to the column in the grid. Did not have to TAB to the column value pair representation for this. Good enough for now. Thanks.
