### ISSUE TITLE
6.1.3 migration, lost opened SQL editors

### ISSUE THREAD

**Issue by cerebel** [dbeaver/dbeaver#6333] opened 2019-07-23 15:04 UTC
#### System information: 
w10 x64  (as clean workspace), w7x64(as custom workspace)
dbeaver ce:  6.1.2->6.1.3  
jdk1.8.0_212_x64

#### Describe the problem you're observing: 
After migrating, the "sql editors" are not loaded ..

#### Steps to reproduce, if exist:
As clean *profile (no any workspace)
1.1. start dbeaver 6.1.2 
 1.2 click twice icon "new sql editor (ctrl+])" -> as result 2 editors: "Script" and "Script-1"
 1.3  window-> open in new window
 1.4 repeat  (1.2) ..  -> as result 2 editors: "Script-2" and "Script-3"
 1.5 close dbeaver : file>Exit
2.1 start  dbeaver 6.1.3 , allow Migration
2.2  the sql editors are not loaded ("Script" .. "Script-3")
   (notes: but in tab 'Projects:General/Scripts' - the scripts are presented)
2.3 click "new sql editor (ctrl+])" -> as result "Script-4"
2.4 close dbeaver 
2.5 open dbeaver 6.1.3 - only Script-4 is opened ..

No any Error/Warnings in c:\Users\root\AppData\Roaming\DBeaverData\workspace6\.metadata\dbeaver-debug.log
 
I have found reference to "script-1 .. script-3" only in "DBeaverData\workspace6\.metadata\.plugins\org.eclipse.core.resources\.root\*.tree"
but not found in
"DBeaverData\workspace6\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi" .

Notes: in P

#### Describe the problem you're observing: 
 should be shows the message of Migration ? 

#### Steps to reproduce, if exist:
 3.1  start dbeaver 6.1.3 with specific workspace - the old workspace
   > dbeaver.exe -data c:\Users\root\.dbeaver4\
   a) -> no any message with proposal of Migrating.
   b) -> the all 4 editors,  created during 1.3 and 1.4 ("script" .. "script-3") are opened.

So, the problem is in Migration.

**Comment by ThysMarais** [comment] 2019-07-23 17:14
I can confirm this. After migration there was no way to register a connection. I had to uninstall and after installing again, I did not choose Migration and could register a connection successfully.

**Comment by serge-rider** [comment] 2019-07-24 17:47
Duplicate of #6321 
See comments for workaround.

**Closed** 2019-07-25 09:34 UTC
Labels: bug, duplicate

**Comment by SylwesterZarebski** [comment] 2019-08-13 09:57
Upgraded to 6.1.4 and open tabs was not migrated at all.
I had set project before migration.

**Comment by cerebel** [comment] 2019-08-13 18:13
https://github.com/dbeaver/dbeaver/blob/master/plugins/org.jkiss.dbeaver.core.application/src/org/jkiss/dbeaver/core/application/DBeaverSettingsImporter.java

private static final String[] COPY_PLUGINS = { ... "org.eclipse.ui.workbench",  ...   };

.migrateWorkspace() { .. copyWorkspaceFiles() .. }  

.copyWorkspaceFiles() {  ...
   if (parentDirType == DIR_TYPE.PLUGINS) {
                    if (!fileName.contains("dbeaver") && !ArrayUtils.contains(COPY_PLUGINS, fileName)) {
                        skippedFiles += countWorkspaceFiles(file);
                        continue;
                    }
                }
...

* I cannot "a permanent link to a code snippet" from browser

The list of opened editors are stored in  \.plugins\org.eclipse.e4.workbench\workbench.xmi , 
and on migration - this list is not copied, and is not processed* in goal to create another *migrated workbench.xmi.

So, the question - the migration* affects the logical structure of workbench.xmi  ? 
if not, is it safe to make a simple copy of workbench.xmi into workspace6 ?

**Comment by serge-rider** [comment] 2019-08-13 19:58
It was made on purpose. workbench.xmi become messy after numerous version upgrades. New Eclispse version usually isn't fully compatible with previous version settings. So it is much safer to just drop these configs. Yes, we loose UI state (open editors and some other settings) but there is nothing viable in workbench.xmi.

**Comment by SylwesterZarebski** [comment] 2019-08-14 06:14
Migrating UI state is crucial when updating within minor versions and is not expected to behave other way. Maybe it should be not 6.1.3 version, but at least 6.2 or 7 (major) with clear statement:
**UI (open tabs and other [which?] settings] is not migrated when upgraded**.

**Comment by cerebel** [comment] 2019-08-14 12:50
Then it is possible to add some new logic of migration - checks the list of opened editors (and the related DB linked with each editor) - and open these in dbeaver 6.1.3+ ? and as result, the new workbench.xmi will be automatically generated on dbeaver:exit() .

The full list is stored as (i make online url decode, so some of ["] was wrong placed )
```xml
  <persistedState key="memento" value="<?xml version="1.0" encoding="UTF-8"?>
		<workbench>
			<mruList>
				<file factoryID="org.eclipse.ui.part.FileEditorInputFactory" id="org.jkiss.dbeaver.ui.editors.sql.SQLEditor" name="Script-211.sql" tooltip="General/Scripts/Script-1.sql">
					<persistable path="/General/Scripts/Script-211.sql"/>
				</file> 
				...
			</mruList>
		</workbench>"/>
```
the list of opened windows  as xsi:type="basic:TrimmedWindow" 
```xml
<children xsi:type="basic:TrimmedWindow" xmi:id="_hcl3sb3uEema-dTDAPJKrg" elementId="IDEWindow" contributorURI="platform:/plugin/org.jkiss.dbeaver.core.application" selectedElement="_hodwgL3uEema-dTDAPJKrg" label="%trimmedwindow.label.dbeaver" x="66" y="66" width="1440" height="900">		
 ..
 <sharedElements xsi:type="advanced:Area" xmi:id="_hynyEL3uEema-dTDAPJKrg" elementId="org.eclipse.ui.editorss" selectedElement="_hynyEb3uEema-dTDAPJKrg">
	<children xsi:type="basic:PartStack" xmi:id="_hynyEb3uEema-dTDAPJKrg" elementId="org.eclipse.e4.primaryDataStack" selectedElement="_r-qvUL3uEema-dTDAPJKrg">
		<tags>org.eclipse.e4.primaryDataStack</tags>
		<tags>EditorStack</tags>
		<tags>active</tags>
		<children xsi:type="basic:Part" xmi:id="_qnCOAL3uEema-dTDAPJKrg" elementId="org.eclipse.e4.ui.compatibility.editor" contributionURI="bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor" label="dbXYZ:Script-1" iconURI="platform:/plugin/org.jkiss.dbeaver.ui/icons/sql/sql_script.png" closeable="true">
			<persistedState key="memento" value="<?xml version="1.0" encoding="UTF-8"?>
					<editor id="org.jkiss.dbeaver.ui.editors.sql.SQLEditor" name="Script-1.sql" partName="dbXYZ:Script-1" title="dbXYZ:Script-1" tooltip="Script: /General/Scripts/Script-1.sql &#x0A;Connection: dbXY1 &#x0A;Type: Oracle &#x0A;URL: ..someDbParamsURL..">
						<input factoryID="org.eclipse.ui.part.FileEditorInputFactory" path="/General/Scripts/Script-1.sql"/>
						<editorState selectionHorizontalPixel="0" selectionLength="0" selectionOffset="0" selectionTopPixel="0"/>
					</editor>"/>
			<tags>Editor</tags>
			<tags>org.jkiss.dbeaver.ui.editors.sql.SQLEditor</tags>
			<tags>removeOnHide</tags>
		</children>
```
