### ISSUE TITLE
New version of Dbeaver (Community Edition 5.1.5) crash on elementary os (CPU peaking)

### ISSUE THREAD

**Issue by AntonioMalatesta** [dbeaver/dbeaver#4065] opened 2018-08-23 08:58 UTC
Hi, 
the new version of Dbeaver not working on elementary os.
At the startup the gui of the application not working good and the cpu has peaking.
I have found this problem in more than one installations.
Here my enviroment details:
**Dbeaver version: ** Community Edition 5.1.5,
**System info: ** Linux antonio-dev 4.4.0-133-generic #159-Ubuntu SMP Fri Aug 10 07:31:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**Distro**: elementary OS 0.4.1 Loki, Linux 4.4.0-133-generic, GTK+ 3.18.9

Thanks.

**Comment by serge-rider** [comment] 2018-08-23 09:28
Duplicate of #4041
Please check for workaround in comments.

**Closed by serge-rider** 2018-08-23 09:28 UTC
Labels: question, xo:linux
