### ISSUE TITLE
if I use F4 I cant get the data about Partition

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#29306] opened 2024-05-01 23:19 UTC
### Description

Hi,

For some tables I have a strange problem. For some tables if i get info with F4 i can see the Partition info so great. But for many tables i try the Partition info but cant get info. Strange but Toad for Oracle do ok for every tables.

Thanks

### DBeaver Version

24.0.3

### Operating System

windows 10

**Comment by E1izabeth** [comment] 2024-05-02 10:38
Please provide steps to reproduce your issue.

**Comment by E1izabeth** [comment] 2024-05-02 10:39
What database do you use? What driver version?
You can check it by pressing `Test Connection` button in the Connection configuration dialog.

**Comment by Yigitttttttt** [comment] 2024-05-02 15:05
Oracle Database 19 Enterprise Ed. Rel. 19.0.0.0.0 prod.ver 19.18.0.0.0  Oracle JDBC driver 23.2.0.0 0 0 interesting Toad for Oracle always fine in F4 partition info

**Comment by E1izabeth** [comment] 2024-05-02 15:27
I can't reproduce it. Could you figure out some minimal example to reproduce it?
You say: "i try the Partition info but cant get info". How does it look like? Any error or just empty list?

**Comment by Yigitttttttt** [comment] 2024-05-02 16:12
Ok, for some security reasons i erased a little bit infos. İ will send dbeaver and Toad photos and you will see the difference. Thanks.

![20240502_190827](https://github.com/dbeaver/dbeaver/assets/168306503/5409aa9e-3b12-4001-b9eb-c4d6aaf2eee7)
![20240502_190540](https://github.com/dbeaver/dbeaver/assets/168306503/1278bf3e-3634-4328-9eb8-f7efb754935d)

**Comment by E1izabeth** [comment] 2024-05-02 18:47
Thank you

**Comment by Yigitttttttt** [comment] 2024-05-02 18:57
You're welcome!

2 May 2024 Per 21:47 tarihinde Elizabeth ***@***.***> şunu
yazdı:

**Comment by Yigitttttttt** [comment] 2024-05-02 23:27
I can't see 'SNPST_DT' info in Dbeaver

**Comment by Yigitttttttt** [comment] 2024-05-07 23:23
Hi,
Is there any progress?

**Comment by E1izabeth** [comment] 2024-05-08 05:29
No progress yet.
You say that you don't see this info "sometimes". Does it mean that sometimes you see it?

**Comment by Yigitttttttt** [comment] 2024-05-08 07:48
Hi again,

I saw it's written on 'Comment' section. So i will change my word to 'Never'. Because someone (i think) write it to comment section.
 
![test](https://github.com/dbeaver/dbeaver/assets/168306503/5e74f75c-6337-421f-8a7c-c4aa90a51b8f)

**Comment by Yigitttttttt** [comment] 2024-05-08 07:51
so it changes to a feature req....

**Comment by E1izabeth** [comment] 2024-05-08 07:52
OK

**Comment by Yigitttttttt** [comment] 2024-05-08 08:07
Actually it's a bug :) bcoz there is a Partition section and there is no Partition info.
Can we solve that?

**Comment by E1izabeth** [comment] 2024-05-08 08:10
I think it's an enhancement :)
It's doable, of course, just haven't implemented yet.

**Comment by Yigitttttttt** [comment] 2024-05-08 08:22
It is a very important enhancement for us, can we at least have a chance to process it in 2 or 4 weeks?

**Comment by E1izabeth** [comment] 2024-05-08 08:43
We can give guaranties only to our customers. Their requests are the priority. So, I can't give any estimations.
We have similar enhancement in progress now, maybe it will fulfill your needs.

**Comment by E1izabeth** [comment] 2024-05-12 20:20
Is it what you're looking for?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/7da7d73c-c3cb-4ef1-9263-ddf04b4a659a)

**Comment by Yigitttttttt** [comment] 2024-05-13 01:19
if the info 'Partition Keys' on the right panel includes always the Partition column(s) (Here, I see TIME_ID for your example) It's OK. 
if it's so, could be better on 'Partitions' section instead of 'Statistics /...(Partitioning)' section.

**Comment by E1izabeth** [comment] 2024-05-17 13:04
I agree

**Comment by Yigitttttttt** [comment] 2024-05-17 15:25
Thank you.

17 May 2024 Cum 16:04 tarihinde Elizabeth ***@***.***> şunu
yazdı:

**Comment by arhayka** [comment] 2024-05-22 12:17
We discussed this issue with the team and decided to improve partition creation in Oracle:
- Collect all partition information in one tab. If this is not possible, add an additional 'Partitions config' tab and collect all partition settings there.
- In the future, we want to add the ability to select a column when creating a partition.

**Comment by Yigitttttttt** [comment] 2024-05-22 22:34
Thank you so much :) I wonder in which version it can be?

**Comment by E1izabeth** [comment] 2024-05-23 04:01
If it's planned to some version, you can see it here
![image](https://github.com/dbeaver/dbeaver/assets/28875055/97c81644-d44b-44da-b9f8-1c121c2604f7)

**Comment by Yigitttttttt** [comment] 2024-08-11 00:43
Hi, why I can't see milestone info? is something happened?

**Comment by E1izabeth** [comment] 2024-08-11 08:39
Currently, it's not planned to any milestone.

**Comment by E1izabeth** [comment] 2024-08-28 08:58
Please don't close it. We still want to improve user experience as described here https://github.com/dbeaver/dbeaver/issues/29306#issuecomment-2124651477

**Comment by Yigitttttttt** [comment] 2024-08-28 09:42
I saw in 24.1.5 partition info, and I think you've already done it.

**Comment by Yigitttttttt** [comment] 2024-10-27 13:18
Hi, I use 24.2.2 and now I have full partition info. So we can close this issue actually. :)

**Closed as completed** 2024-11-22 17:00 UTC
Labels: enhancement, x:oracle, xf:metadata, xf:ui, pkg:EE
