### ISSUE TITLE
SQL Editor doesn't convert table names to hyperlinks if a fully-qualified name is used

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13393] opened 2021-08-02 06:12 UTC
#### System information: 
- Operating system (distribution) and version Win 10
- DBeaver version 21.1.4

#### Connection specification:
- Database name and version: Exasol

#### Steps to reproduce, if exist:
1. Write a full table name in SQL editor
2. Press <kbd>Ctrl</kbd> and hover over that name

**Expected:** Name can be clicked to open a table in separate window
**Actual:** Nothing happens

![ch4SSrEX4Q](https://user-images.githubusercontent.com/82543000/127812247-9b3cd0f9-9352-48af-82bb-905fee948eba.gif)

**Comment by ShadelessFox** [comment] 2021-08-02 08:15
Duplicate of #12043

**Closed as completed by ShadelessFox** 2021-08-02 08:15 UTC
Labels: x:exasol, xf:sql, xf:metadata, xf:ui
