### ISSUE TITLE
Map Popup format

### ISSUE THREAD

**Issue by Jnb2387** [dbeaver/dbeaver#9233] opened 2020-07-10 19:20 UTC
#### System information: 
- Operating system (distribution) and version 
Mint 19.3
- DBeaver version
7.1.2

#### Connection specification:
- Database name and Version
PostgreSQL 12

#### Describe the problem you're observing:
When clicking a feature in the spatial tab it list all the attributes one letter at a time. 
![Screenshot from 2020-07-10 13-19-43](https://user-images.githubusercontent.com/17630656/87190643-0e68c000-c2b0-11ea-893c-ca1500c62738.png)

Any spatial type(points, polygons, lines) renders the same

**Comment by serge-rider** [comment] 2020-07-10 19:22
Duplicate of #9160

**Closed by serge-rider** 2020-07-10 19:22 UTC
Labels: bug, duplicate
