### ISSUE TITLE
GPKG Support

### ISSUE THREAD

**Issue by Gis-kost** [dbeaver/dbeaver#21964] opened 2023-11-23 12:06 UTC
### Description

Hi!
I strongly need to support use GPKG in Dbeaver!
But i cant find driver!
Can you help???

### DBeaver Version

23.1.3

### Operating System

win 10

**Comment by ShadelessFox** [comment] 2023-11-23 12:12
Duplicate of #21963

**Closed as not planned by ShadelessFox** 2023-11-23 12:12 UTC
Labels: duplicate
