### ISSUE TITLE
Diagram entity manual resizing is not saved

### ISSUE THREAD

**Issue by arctrong** [dbeaver/dbeaver#34377] opened 2024-06-17 09:08 UTC
### Description

When I manually resize an entity block on an ERD diagram I want this resizing to be saved.

### DBeaver Version

Community, version 24.1.0.202406091028

### Operating System

Windows, macOS

### Database and driver

Postgress, MySQL

### Steps to reproduce

Create a diagram with at least one entity and manually resize at least one entity:
![image](https://github.com/dbeaver/dbeaver/assets/63712011/fdfe4d21-8195-4800-ba11-e6bda38d2907)
Save the diagram, close it and open it again.
Expected behavior: the manual resizing must preserve.
Actual behavior: the manual resizing is ignored:
![image](https://github.com/dbeaver/dbeaver/assets/63712011/3640406f-addf-425c-966d-4f93409a4879)

**Comment by E1izabeth** [comment] 2024-06-17 09:29
Thank you for request.
It's a duplicate of #14988. 
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-06-17 09:29 UTC
Labels: duplicate, xf:erd
