### ISSUE TITLE
Lots of CSV Import Questions

### ISSUE THREAD

**Issue by Eddie-Hartman** [dbeaver/dbeaver#9756] opened 2020-09-13 17:50 UTC
#### System information: 
- Operating system (distribution) and version
Windows 10 latest
- DBeaver version
7.2.0 EE
#### Connection specification:
- Database name and version
SQLServer Express 
#### Describe your question:
I apologize in advanced for the lengthy ticket.

1. **What is the best way to perform an import of data from csv to sqlServer database to table I already have?** I'm assuming right clicking on the table, import data, then selecting my csv file and going through there. I've had numerous problems with this though. The csv file is 50+ columns long. I've already defined all of these in my table.
    - **So I need to manually map each column in the csv to each db column?** A feature suggestion would be to add an "auto assign" feature that would map column 1 in csv to column 1 in table and go all the way down so I don't have to map each of them manually. Mine just so happen to be in this order, so I could avoid mapping all of these out.
    - After doing this, I need to map each DATA TYPE NOW? That's 100s of clicks through menus to map these things up, but I did it.
    - After I did this, I saved the task (assuming these column matches would be saved) and then ran the import. It failed. One of my columns was char when it apparently needed to be varchar(2) darn. So I load up the task and just change the column type after updating my table right? Well when I loaded up my task, the columns are no longer matched up. It's trying to create new columns for each of the ones that I had matched up before. **Is this a bug?** This was easily my biggest frustration because mapping those columns took a very long time.
    - I have one column that I am adding to my database that is NOT in the csv file. Year of import. Just an int that will be set to a fixed value for all data being imported. Very similar to: https://dbeaver.com/docs/wiki/Data-transfer/#importing-data-from-csv-format step 4. Unfortunately, the ui has changed and it doesn't appear that I have the option to add "custom value". **Was this intentionally removed or is this a bug?** (My workaround was to modify the ends of the csv files and add the data I wanted to each file, but if dbeaver could handle this that would be great.)
    - There are now TWO column mapping views. First one: 
![image](https://user-images.githubusercontent.com/14089997/93024664-f79f5c00-f5c5-11ea-9305-fb537f5ae38d.png) Second one: 
![image](https://user-images.githubusercontent.com/14089997/93024674-0d148600-f5c6-11ea-89b9-7884ecaca490.png) The problem here is that the first view allows you to map to "existing" columns, but if you then go to the second view, you'll see that it is changing the target type. In my case, the first column is an int and mapping it to my existing state_code int column will try to make the target type for the column a varchar, which I'm assuming the script cannot do, so I think it then falls back to creating a new column anyway. If I am mapping data to existing columns, it should keep the existing data type in tact. This is surprisingly even true for existing varchar data types. It will try to change the data type from say varchar(2000) to varchar(1).

My end goal here is to get all this data imported, then create the insert into scripts with dbeaver to share with the team since the don't all use dbeaver. Fortunately, all of this data is available to the public:

CSV download link: https://www.fhwa.dot.gov/bridge/nbi/1992hwybronlyonefile.zip
Download location (in case you don't want a direct link): https://www.fhwa.dot.gov/bridge/nbi/ascii1992.cfm#del
My table schema (so far):
```
create table bridge3(
	state int foreign key references state_codes(code), --1
	struct_num varchar(15), --8
	record_type char, --5a
	route_sign_prefix int, --5B
	desig_level_service int, --5C
	route_number varchar(5), --5D
	directional_suffix int, --5E
	highway_agency_district varchar(2), --2
	county_code int, --3
	place_code int, --4
	features_intersected varchar(24), --6A
	critical_facility_indicator char, --6B
	facility_carried_structure varchar(18), --7
	location varchar(25), --9
	min_vert_clearance int, --10
	kilometerpoint int, --11
	base_highway_network int, --12
	lrs_inv_route varchar(10), --13A
	subroute int, --13B
	latitude int, --16
	longitude int, --17
	detour_length int, --19
	toll int, --20
	maintenance_responsibility int, --21
	owner int, --22
	route_class int, --26
	year_built int, --27
	lanes_on int, --28A
	lanes_under int, --28B
	average_daily_traffic int, --29
	year_average_daily_traffic int, --30
	design_load int, --31
	approach_roadway_width int, --32
	bridge_median int, --33
	skew int, --34
	structure_flared int, --35
	bridge_railings char, --36A
	transitions char, --36B
	approach_guardrail char, --36C
	approach_guardrail_ends char, --36D
	historical_significance int, --37
	navigation_control char, --38
	navigation_vertical_clearance int, --39
	navigation_horizontal_clearance int, --40
	structure_open_posted_closed char, --41
	type_service_on int, --42A
	type_service_under int, --42B
	kind_of_material_main int, --43A
	type_of_design_main int, --43B
	kind_of_material_spans int, --44A
	type_of_design_spans int, --44B
	main_spans_number int, --45
	approach_spans_number int, --46
	route_horizontal_clearance int, --47
	maximum_span int, --48
	length int, --49
	left_curb_width int, --50A
	right_curb_width int, --50B
	bridge_roadway_width int, --51
	deck_width int, --52
	min_vert_clearance_bridge_roadway int, --53
	min_vert_under_reference char, --54A
	min_vert_under int, --54B
	min_lat_under_right_reference char, --55A
	min_lat_under_right int, --55B
	min_lat_under_left int, --56
	deck char, --58
	superstructure char, --69
	substructure char, --60
	channel char, --61
	culverts char, --62
	operating_method_rating int, --63
	operating_rating int, --64
	inventory_rating_method int, --65
	inventory_rating int, --66
	structural_evaluation char, --67
	deck_geometry char, --68
	underclear char, --69
	bridge_posting int, --70
	waterway_adequacy char, --71
	approach_roadway_alignment char, --72
	type_of_work_proposed int, --75A
	type_of_work_done_by char, --75B
	length_structure_improvement int, --76
	inspection_date int, --90
	inspection_frequency int, --91
	fracture_critical_details varchar(3), --92A
	underwater_inspection varchar(3), --92B
	special_inspection varchar(3), --92C
	fracture_critical_details_date varchar(4), --93A
	underwater_inspection_date varchar(4), --93B
	special_inspection_date varchar(4), --93C
	bridge_improvement_cost int, --94
	roadway_improvement_cost int, --95
	total_project_cost int, --96
	improvement_cost_estimate int, --97
	neighboring_state_code varchar(3), --98A
	percent_responsibility int, --98B
	border_bridge_structure_number varchar(15), --99
	strahnet_highway_designation int, --100
	parallel_structure_designation char, --101
	traffic_direction int, --102
	temp_structure_designation char, --103
	highway_system_inv_route int, --104
	fed_lands_highways int, --105
	year_reconstructed int, --106
	deck_structure_type char, --107
	type_wearing_surface char, --108A
	type_membrane char, --108B
	deck_protection char, --108C
	average_daily_truck_traffic int, --109
	designated_national_network int, --110
	pier_protection int, --111
	nbis_bridge_length char, --112
	scour_critical_bridges char, --113
	future_average_daily_traffic int, --114
	year_future_average_daily_traffic int, --115
	minimum_nav_vertical_clearance int, --116
	--bridge_condition char,
	--bridge_condition_code char,
	--nbi_deck_area int,
	FED_AGENCY char,
	DATE_LAST_UPDATE date,
	TYPE_LAST_UPDATE char,
	DEDUCT_CODE varchar(2), --unknown max length/data type
	REMARKS varchar(2000), --unkown max length
	PROGRAM_CODE varchar(4), --unknown max length
	PROJ_NO varchar(20), --unknown max length
	PROJ_SUFFIX char, --unknown max length/data type
	NBI_TYPE_OF_IMP int,
	DTL_TYPE_OF_IMP int,
	SPECIAL_CODE int, --unknown max length/data type
	STEP_CODE int, --unknown max length/data type
	STATUS_WITH_10YR_RULE int,
	SUFFICIENCY_ASTERC char,
	SUFFICIENCY_RATING numeric(2,1),
	STATUS_NO_10YR_RULE char,
	year_submitted int, -- Eddie created this field for determining which nbi submittal year the data was taken from
	primary key (state, struct_num, year_submitted)
);
```

**Comment by Eddie-Hartman** [comment] 2020-09-13 19:21
Update: For the saving of columns and data types issue, I'm getting consistent issues with me changing values and saving the task, but the values not actually saving. This is not completely consistent. If I can reproduce regularly I'll update, but there is certainly something strange happening there.

**Comment by Eddie-Hartman** [comment] 2020-09-13 21:45
I just spent a lot of hours refining my data and clearing out the data for the task to at some point again revert back to having no columns tied to values. Let me know if there is some miracle of a way for me to get a task configuration back. I'm not going to set up these 50+ columns again, so I'll probably look for an alternative from dbeaver for this specific task.

**Comment by kseniiaguzeeva** [comment] 2020-09-14 12:26
Thank you for the detailed description and your ideas.

**Comment by guardiande** [comment] 2020-09-18 11:19
Same here:

* Import dialog does not save changes directly made in the "Tables mapping" dialog. You have to use the "Columns..." button and map the columns there. Then the changes get saved. 

* Missing the old way of auto column mapping: First CSV column maps to first table column, second to the second and so on.

* No way to add default values (other than implicitly NULL) for not mapped columns.

**Comment by kseniiaguzeeva** [comment] 2020-10-09 13:54
Separate FRs are created based on your ticket:

1. https://github.com/dbeaver/dbeaver/issues/10033  Auto-assign function when importing from CSV
2. https://github.com/dbeaver/dbeaver/issues/10034  Data type auto-assigning when importing from CSV to an existed table
3. https://github.com/dbeaver/dbeaver/issues/10035  Ability to add a column with a custom value through the import wizard
4. I could not reproduce the issue "After I did this, I saved the task (assuming these column matches would be saved) and then ran the import. It failed. One of my columns was char when it apparently needed to be varchar(2) darn. ". It works as expected for me. Is it possible to writesteps to reproduce?

Please tell, if something were not included in the list above. Thank you one more time for your ideas to make import better. The tickets above will be implemented in future releases.

**Comment by E1izabeth** [comment] 2023-05-25 15:40
Does this issue still actual for the latest DBeaver version?

**Comment by Eddie-Hartman** [comment] 2023-05-25 16:03
@E1izabeth It's been two and a half years and I'm well past anything related to this issue at this point. Super happy to see some suggestions get implemented though.

It seems like the only remaining portion would be the saving of a task and then trying to re-import, which required mapping again. If you'd like to trim that as a separate issue then fine, but I'm also fine with just closing this at this point. Leaving that up to you.

**Comment by E1izabeth** [comment] 2023-05-25 16:08
Thanks!

**Comment by E1izabeth** [comment] 2023-05-31 17:54
Changed data types mapping for columns are preserved between task runs for me, so I'm closing this issue.
If you meet some bugs again, please feel free to create a new issue.

**Closed by E1izabeth** 2023-05-31 17:54 UTC
Labels: feature request, xf:datatransfer, wait for review
