### ISSUE TITLE
When I updated the application from 6.1.2 to16.1.3, I can't create new database connection anymore. No any tips messages.

### ISSUE THREAD

**Issue by conero** [dbeaver/dbeaver#6335] opened 2019-07-24 02:13 UTC
#### System information: 
- Community Edition 6.1.3; Windows 64 bit (installer + JRE)
- 6.1.3

#### Connection specification:
- MySQL 5.7

#### Describe your question:
When I updated the application from 6.1.2 to16.1.3, I can't create new database connection anymore. No any tips messages. Even I enter wrong password still no any message, but 6.1.2 is ok.

![m1](https://user-images.githubusercontent.com/19564821/61759675-99c91700-adfb-11e9-857b-b4d30397a309.png)
![m2](https://user-images.githubusercontent.com/19564821/61759684-9f266180-adfb-11e9-978f-4f117200d2ae.png)
![m3](https://user-images.githubusercontent.com/19564821/61759688-a2b9e880-adfb-11e9-8ab1-58bb8b8fcaf6.png)

**Comment by serge-rider** [comment] 2019-07-24 17:48
Seems to be duplicate of #6321 .
Workaround: switch to "Projects" view and set some project active (right click on a project element->Set active).

**Closed** 2019-07-25 12:07 UTC
Labels: bug, duplicate

**Comment by serge-rider** [comment] 2019-07-27 16:43
Perhaps it is the same problem as in #6358.
Culd you also attach log error/debug log files?
