### ISSUE TITLE
Duplicate current row - PostgreSQL

### ISSUE THREAD

**Issue by cyrusjoudieh** [dbeaver/dbeaver#10125] opened 2020-10-21 10:12 UTC
#### System information: 
- WIndows 10 Pro - Version 2004 (OS Build 19041.572)
- DBeaver Version 7.2.3.202010191702
- No Additional extensions

#### Connection specification:
- PostgreSQL
- PostgreSQL JDBC Driver

#### Describe the problem you're observing:
Can't use the option "Duplicate current row". It was working in version 7.2.2

#### Steps to reproduce, if exist:
1. Open the table and select tab "Data"
2. Select the row to duplicate
3. Select the option "Duplicate current row"
4. The Primary Key column now contains a value instead of **NULL** 
5. Right click on the new row that was created and select Generate SQL -> Insert or Update
   PK ID column is included in the SQL command
   The column of type "text" is not being set inside single quotes and the single quotes in the text are not being escaped

#### Include any warning/errors/backtraces from the logs

 binding not supported

**Comment by kseniiaguzeeva** [comment] 2020-10-21 10:51
Am I correct that you have uuid column type? It duplicates https://github.com/dbeaver/dbeaver/issues/9964#issuecomment-713126342

The issue will be fixed in 7.2.4. You can try early access   https://dbeaver.io/files/ea/

**Comment by cyrusjoudieh** [comment] 2020-10-21 11:13
Yes It seems a duplicate.
But there is a another issue when column type is Text as described in step 5 part 2
The column of type "text" is not being set inside single quotes and the single quotes in the text are not being escaped
when generating SQL

**Comment by cyrusjoudieh** [comment] 2020-10-21 11:22
No its not UUID
The column type is int8 in 7.2.2 and in version 7.2.3 its bigserial
The default is nextval('dwh.dwh_scripts_id_seq'::regclass) and in 7.2.3 there is no default

**Comment by kseniiaguzeeva** [comment] 2020-10-21 20:15
Thank you for the clarifying. Is it possible to send DDL example?

**Comment by cyrusjoudieh** [comment] 2020-10-22 06:13
The command is of type text, as you can see there are no quotes.

![ddl](https://user-images.githubusercontent.com/1870894/96832033-9e7ce080-142d-11eb-9d50-3ba43c444170.PNG)

The below picture shows the id of type int8 in 7.2.2 with defaults and bigserial in 7.2.3 with no defaults.
![id](https://user-images.githubusercontent.com/1870894/96831791-375f2c00-142d-11eb-97c4-8c97ca88a4ad.png)

**Comment by kseniiaguzeeva** [comment] 2020-10-23 07:30
Thank you. Possible it has common reason with https://github.com/dbeaver/dbeaver/issues/10148.

**Comment by LonwoLonwo** [comment] 2020-10-23 10:14
> The Primary Key column now contains a value instead of NULL

will be resolved in #10148 

> The column of type "text" is not being set inside single quotes and the single quotes in the text are not being escaped

will be resolved in next releases

**Comment by LonwoLonwo** [comment] 2020-11-02 16:21
@cyrusjoudieh can't reproduce in 7.2.4 text column issue
![2020-11-02 18_12_38-Window](https://user-images.githubusercontent.com/45152336/97891783-45238400-1d40-11eb-9ffe-8b497399fa1f.png)
any thoughts? may be PostgreSQL version? Can you please test version 7.2.4?

**Comment by cyrusjoudieh** [comment] 2020-11-02 16:27
@LonwoLonwo The text issue was in version 7.2.3 and it has been fixed in 7.2.4.

I have tested 7.2.4 and all the issues that I had were fixed in 7.2.4.

Thank you!

**Comment by LonwoLonwo** [comment] 2020-11-02 16:34
@cyrusjoudieh nice to hear! Thanks for testing

**Closed by LonwoLonwo** 2020-11-02 16:34 UTC
Labels: bug, wait for response, x:postgresql
