### ISSUE TITLE
DBeaver 6.1.1 does not load user privileges for Postgresql

### ISSUE THREAD

**Issue by glw** [dbeaver/dbeaver#6288] opened 2019-07-16 16:42 UTC
#### System information: 
- Operating system (distribution) and version
Ubuntu Xenial
- DBeaver version
6.1.2
- Java version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

- Additional extensions

#### Connection specification:
- Database name and version
PostgreSQL 10.9 on x86_64-pc-linux-gnu, compiled by gcc, 64-bit
- Driver name
org.postgresql.Driver (Release 42.2.5)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
SSH

#### Describe the problem you're observing:
User privileges are not reflected consistently in the Permission list within the properties window for some roles. 

More specifically I created 2 roles recently. One a read only role with access to materialized views - in this role you can not see its select permissions on the materialized views. I also created a second write role with update privileges to an actual table, as well as select privileges to the same materialized views as the read only role. For the write role you can see the privileges it has to update the table, but not the select privileges it has for the materialized view.

#### Steps to reproduce, if exist:
I created a read only role with usage and select permission on a schema with materialized views.

```
create role readonly;
grant connect on database mydb to readonly;
grant usage on schema myschema to readonly;
grant select on all tables in schema myschema to readonly;
```

Then I created a write role the the same privileges as the read only, with the addition of write privileges to a specific table.
```
create role writespecific;
grant connect on database mydb to writespecific;
grant usage on schema myschema to writespecific;
grant select on all tables in schema myschema to writespecific;
-- grants to write to a table
grant usage on schema myschema2 to writespecific;
grant select, insert, update, delete on table myschema2.mytable to writespecific;
GRANT USAGE ON SEQUENCE mytable_id_seq TO writespecific;
```

**Comment by serge-rider** [comment] 2019-07-19 10:09
I still can't reproduce this (by following your steps).
In which editor do you manager permissions (table editor or role editor)?

Could you post a screenshot with wrong permissions?

**Comment by glw** [comment] 2019-07-22 15:58
This would be the after double clicking on a role and looking at the properties of a role. Since Ive granted select permissions, shouldnt that be check marked here?

![image](https://user-images.githubusercontent.com/556205/61646449-66f21800-ac6f-11e9-9545-117f452c9d10.png)

**Comment by serge-rider** [comment] 2020-02-07 19:50
We improved permission management in 6.3.4
However we still don'\t read schema permissions (in role editor)

At the moment we read role permissions from `table_privileges` and `routine_privileges` information_schema views.
Probably we need to use pg_catalog.* tables and parse acl directly.
But I'm not sure how to do this efficiently.

**Comment by glw** [comment] 2020-02-13 21:38
Sorry for the delayed response. @serge-rider thanks for the update on this. I have noticed the improvement permissions on roles. should we close this for now?

**Comment by serge-rider** [comment] 2020-03-04 10:03
Yep, let's close it.
Please create new ticket for further permission management improvements.

**Closed by serge-rider** 2020-03-04 10:03 UTC
Labels: bug, wait for response, x:postgresql
