### ISSUE TITLE
Dbeaver doesn't clear transaction log after 'COMMIT;' query

### ISSUE THREAD

**Issue by Renarde-dev** [dbeaver/dbeaver#21263] opened 2023-09-21 09:37 UTC
### Description

I'm using the manual commit mode on an oracle database and when I use the `COMMIT;` query it doesn't clear the transaction log, the statement counter stays green with the number of statement increment.

### DBeaver Version

Flatpak Community Edition Version 23.2.0.202309041200

### Operating System

Linux, Fedora 38 

### Database and driver

Database : Oracle 12.1.0.2.0

Drivers : com.oracle.database.jdbc:ojdbc8:RELEASE Version 12.2.0.1

### Steps to reproduce

Connect to the database,

Run queries and commit 
```SQL
SELECT * FROM ...
UPDATE ...

COMMIT;
```

The statement counter doesn't reset to zero or display 'none'

### Additional context

Using a VPN (open-connect juniper) outside Dbeaver

**Comment by ShadelessFox** [comment] 2023-09-21 12:43
Thanks for the feature request. Duplicate of #7760

**Closed as not planned by ShadelessFox** 2023-09-21 12:43 UTC
Labels: duplicate
