### ISSUE TITLE
Why is the Chinese display of query results messy with dbeaver?

### ISSUE THREAD

**Issue by jieguolove** [dbeaver/dbeaver#21223] opened 2023-09-15 02:36 UTC
### Description

I used the latest version of dbeaver23.2 to connect heavydb6.4, why is the Chinese display of query results messy? How to solve it, thank you!

### DBeaver Version

Community 23.2

### Operating System

windows10

### Database and driver

1.HeavyDB Server Version: 6.4.0-20230201-87f6fa37b4
2.heavyai-jdbc-6.4.0.jar

### Steps to reproduce

![image](https://github.com/dbeaver/dbeaver/assets/96612712/de789c2e-c7b9-4652-b384-020b8adaf744)
![image](https://github.com/dbeaver/dbeaver/assets/96612712/fe78fc0e-841c-4da7-ae41-8a0fef7416f9)
![image](https://github.com/dbeaver/dbeaver/assets/96612712/624ce638-ddf4-4954-942e-363805ebee81)
![image](https://github.com/dbeaver/dbeaver/assets/96612712/a05f47bf-83bc-447d-969f-338c4e67e7b0)

**Comment by E1izabeth** [comment] 2023-09-15 08:51
Thank you for bug report. It's a duplicate of #20392

**Closed as not planned by E1izabeth** 2023-09-15 08:52 UTC
Labels: duplicate

**Comment by E1izabeth** [comment] 2023-10-23 08:47
We expect that it may be solved it with #21513
However, if the issue is still reproducible, please let me know.
