### ISSUE TITLE
5.2.3 - MySQL filtering schema tables generates a bad syntax SQL command

### ISSUE THREAD

**Issue by RuiDores** [dbeaver/dbeaver#4612] opened 2018-11-14 12:41 UTC
Hi,
I started getting this error message when refreshing the table list after updating to 5.2.3 from the Kali repo. When I try to hide (filter->hide) a table from showing in the Databases sidebar list, I get this message:
```
Error refreshing node

Reason:
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'databasesNOT ( LIKE 'performance_schema')' at line 1
```
Looks like you're generating a bad syntax SQL command here... It seems to have a space is missing there before the 'NOT'.
I don't know about other drivers, but this happens to me on MySQL 5.6, using the just downloaded connector mysql-connector-java-5.1.44...

p.s. I just noticed version 5.2.4 is already out, It might have been corrected already! I haven't tried that one yet but I didn't find anything about this on the change logs from that version.

**Comment by serge-rider** [comment] 2018-11-14 13:06
Duplicate of #4500
Thanks for the bug report anyway.

**Closed by serge-rider** 2018-11-14 13:06 UTC
Labels: bug, duplicate
