### ISSUE TITLE
ER Diagram Export Bug

### ISSUE THREAD

**Issue by felangga** [dbeaver/dbeaver#7680] opened 2020-01-18 15:15 UTC
I'm using Dbeaver 6.3.2 on linux. When I'm trying to save ER diagram that I just worked, the output image is crooked like the sample below
![ER](https://user-images.githubusercontent.com/14814984/72665961-0dad4a80-3a40-11ea-9e3e-9d35a5099f20.png)

**Comment by serge-rider** [comment] 2020-01-18 15:18
Duplicate of #7300

**Closed by serge-rider** 2020-01-18 15:18 UTC
Labels: bug, duplicate
