### ISSUE TITLE
Date Format in Result of SQL Query

### ISSUE THREAD

**Issue by sovittyagi** [dbeaver/dbeaver#9331] opened 2020-07-21 10:24 UTC
Hi Team,

When I generate Insert statements using Dbeaver, the date fields are in the format yyyy-mm-dd hh.mm.ss.ss. 
Do you know how to change to the usual insert statement format (dd-mmm-yyyy) OR (01-JAN-2020). Please Advise!

If we cannot change then can we add this into new Release of Community Edition.

Thanks
Sovit

**Comment by kseniiaguzeeva** [comment] 2020-07-21 10:58
Which database do you use? SQL syntax can recognize it as a mistake. But you can change data format in Data Editor (Connection settings>Data viewer>Data Formatting

**Comment by sovittyagi** [comment] 2020-07-21 11:15
Hi - We are using VMS_RDB through JDBC connections and in viewer mode we can see what we need but when we try to pull Insert Query using SQL Generator option it always giving in 01-01-2019 format not in 01-JAN-2019 but in our DB only support 01-JAN-2019 so we are not able to perform Insert task with query generated by SQL Generator in tool. We have lots of insert Operations for Insert on daily basis and we need to manually manipulate query which is not good. Please Help!

**Comment by sovittyagi** [comment] 2020-07-21 14:00
![Expected](https://user-images.githubusercontent.com/68591302/88064080-6f35a980-cb88-11ea-91f6-03845d415479.PNG)

Kindly have a look as we need exact same timestamp format in Insert Command for our DB work. Kindly help! In Display we are fine but in Insert SQL Query also we need exact same format "21-Jul-2020 19:30:21".

**Comment by kseniiaguzeeva** [comment] 2020-07-22 07:25
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/9293. It is going to be implemented in 7.1.5 release

**Closed by kseniiaguzeeva** 2020-07-22 07:25 UTC
Labels: question, wait for response

**Comment by sovittyagi** [comment] 2020-08-28 18:50
Hi Team,

I have installed 7.1.5 and still having same issue with date Format. When we are running query then result displayed in correct format as requested DD-MMM-YYYY but when we try to use Generate SQL feature for Insert/Update then still timestamp coming DD-MM-YYYY format but we need into DD-MMM-YYYY as this ticket was raised for same. Can you take a look and help me out.

**Results of Insert Command**
VALUES('22', 1, '092121', 'UV0', 'H0609', 804, 0, '2019-01-01 00:00:00.000', '2019-12-31 00:00:00.000', 6000, '2019-09-25 01:47:35.050'

Expected Results :--
VALUES('22', 1, '092121', 'UV0', 'H0609', 804, 0, '01-JAN-2019 00:00:00.000', '12-DEC-2019 00:00:00.000', 6000, '25-SEP-2019 01:47:35.050'

**Comment by sovittyagi** [comment] 2020-08-31 12:13
# @kseniiaguzeeva  Can you please take a look as i think we need to re-open this ticket as its still not fixed in new version 7.1.5.

**Comment by kseniiaguzeeva** [comment] 2020-08-31 12:19
Thank you for testing. It really was not implemented as planned. The ticket  duplicates 9293, so there is no need to reopen it.

**Comment by sovittyagi** [comment] 2020-08-31 12:26
Thanks for quick response. Is there any plan to implement in future release. As we are looking forward to have this enhancement asap in latest version. So kindly share with me if you have info with you. Thanks!

**Comment by kseniiaguzeeva** [comment] 2020-09-07 08:26
It is going to be implemented in 7.2.1 release.

**Comment by sovittyagi** [comment] 2020-09-07 08:48
> It is going to be implemented in 7.2.1 release.

@kseniiaguzeeva  Thanks for response. Do we have timelines for this release. If yes please confirm!

**Comment by kseniiaguzeeva** [comment] 2020-09-07 08:50
September 21, 2020

**Comment by sovittyagi** [comment] 2020-09-07 08:55
Good to hear. We really need this feature to work on Mass Data activity so please include this feature in this release. Thanks for help!

**Comment by sovittyagi** [comment] 2020-09-18 17:01
> It is going to be implemented in 7.2.1 release.

Hi @kseniiaguzeeva  Are we still on Target to add this timestamp feature in 7.2.1 Release which is scheduled on 21 September. Please Advise!
