### ISSUE TITLE
[Oracle] ORA-00933 in update statement with the semicolon at end

### ISSUE THREAD

**Issue by raptr55** [dbeaver/dbeaver#7752] opened 2020-01-28 12:04 UTC
**System information:**

- Operating system (distribution) and version - Windows 10
- DBeaver version - 6.3.3.202001191557

**Connection specification:**

- Database name and version - Oracle 11g

**Describe the problem you're observing:**
when I try to update a table with the semicolon at the end you get an error ORA-00933

**Comment by uslss** [comment] 2020-01-28 12:46
hi @raptr55 ,
it seems this issue is duplicate of #7701 .
could you try if your problem is solved in EA version (https://dbeaver.io/files/ea/) and write back if it solved or not?

**Comment by uslss** [comment] 2020-01-28 13:15
so the problem will be fixed in 6.3.4 version :)

**Closed by uslss** 2020-01-28 13:15 UTC
Labels: bug, duplicate, wait for response
