### ISSUE TITLE
The list of table partitions is not updated using the "Refresh" when the "Partitions" folder is selected

### ISSUE THREAD

**Issue by bomuva** [dbeaver/dbeaver#26854] opened 2024-04-26 09:46 UTC
### Description

The list of table partitions  in the Database Navigator is not updated using the "Refresh" drop-down menu item when the "Partitions" folder is selected. Update is possible only when "table schema" is selected

### DBeaver Version

Community Edition 24.0.3

### Operating System

Windows 11

### Database and driver

1. Database PostgreSQL ver 15
2. PostgreSQL JDBC Driver 

### Steps to reproduce

Create a table with partitions
Open Database Navigator to display the list of table partitions
Add partition to the table using any tool
Right click on the folder "Partitions" in the table's tree branch and choose "Refresh"
The list of partitions remains unchanged

**Comment by E1izabeth** [comment] 2024-04-26 13:58
Have you tried refreshing the parent branch of "Partitions" in the navigator tree?

**Comment by LonwoLonwo** [comment] 2024-04-26 17:49
Thanks for the report.
Actually, this is a duplicate of https://github.com/dbeaver/dbeaver/issues/9408.
You can subscribe to the original issue.

**Closed as completed by LonwoLonwo** 2024-04-26 17:49 UTC
Labels: x:postgresql, duplicate, xf:navigator, xf:metadata

**Comment by bomuva** [comment] 2024-04-27 09:54
> Have you tried refreshing the parent branch of "Partitions" in the navigator tree?

The paretn branch is the "Table" branch, but in doesn't work also. Temporary workaround is pressing Refresh on the "Schema" branch but it is not good solutionit results in querying redundant information from the database
The most correct (and the most logical) common rule is **to update that part of the tree whose parent node is selected** when selecting the Refresh drop-down menu item. In my opinion, this is not difficult, since you can easily get a list of the table partitions from the Postgres data dictionary

**Comment by E1izabeth** [comment] 2024-04-29 08:00
You can vote for the issue with 👍 under the https://github.com/dbeaver/dbeaver/issues/9408 issue description to promote it to a higher priority.
