### ISSUE TITLE
MySQL : Grouping all ALTER TABLE clauses into one when creating foreign keys or indexes using the GUI

### ISSUE THREAD

**Issue by lagarrueal** [dbeaver/dbeaver#22344] opened 2024-01-05 10:41 UTC
**Describe the solution you'd like**
Grouping multiple ALTER TABLE clauses into one when creating foreign keys or indexes.  
Let's say I want to add two foreign keys to my table from there : 
![image](https://github.com/dbeaver/dbeaver/assets/86953370/3eb22782-fd09-409e-9971-eef5c0096af3)
![image](https://github.com/dbeaver/dbeaver/assets/86953370/8bd725a4-b42f-430c-9d9d-942c4c2f1ad7)

Upon saving the queries, DBeaver creates two queries : 
![image](https://github.com/dbeaver/dbeaver/assets/86953370/9f9f4f19-f4b2-41db-81fa-8d602c2971b8)

It would be nice if DBeaver could concatenate the two queries into one, since you can put multiple operations in one ALTER TABLE clause, or give the ability to enable/disable grouping of multiple clauses into one.  
Due to the way that MySQL works whe altering tables, it would be a nice feature to have.  

### DBeaver version : 
DBeaver 23.3.1.202312241705

**Comment by E1izabeth** [comment] 2024-01-08 12:21
Thank you for the idea.
I'm closing it as a duplicate of #18501. 
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-01-08 12:22 UTC
Labels: duplicate, xf:metadata
