### ISSUE TITLE
 Context menu translation error.

### ISSUE THREAD

**Issue by xfzhaoxd** [dbeaver/dbeaver#21153] opened 2023-09-07 16:42 UTC
### Description

Use the menu to set the UI Interface language of the program to Simplified Chinese.

On the application interface, when multiple datasheets are opened, right-click the mouse, and close all datasheet panels, the right-click menu item is "Close All". When using Simplified Chinese language, it is translated as "Close Close".关闭关闭

### DBeaver Version

Community Edition 21.1.4

### Operating System

windows 10

### Database and driver

MySQL 8.0

### Steps to reproduce

1.Set the interface of the application to use Simplified Chinese language.
2.On the application interface, when multiple datasheets are opened, right-click the mouse, and close all datasheet panels, the right-click menu item is "Close All". When using Simplified Chinese language, it is translated as "Close Close".关闭关闭

### Additional context

None

**Comment by LonwoLonwo** [comment] 2023-09-07 17:01
Hello @xfzhaoxd 

Thanks for the report.

And I'm closing this ticket as a duplicate of https://github.com/dbeaver/dbeaver/issues/17697

You can read more info about translation there.

**Closed as completed by LonwoLonwo** 2023-09-07 17:01 UTC
Labels: duplicate, xf:i18n
