### ISSUE TITLE
Row Highlight is broken after new added row.

### ISSUE THREAD

**Issue by MrRoiz01** [dbeaver/dbeaver#12336] opened 2021-05-03 16:09 UTC
When I try to add a new row, the current highlight does not match with the correct row.

![Screenshot_268](https://user-images.githubusercontent.com/61702317/116901677-d7c5b280-abff-11eb-8c65-4582fc190ffa.png)

**Comment by LonwoLonwo** [comment] 2021-05-03 19:58
Hello @MrRoiz01 
Thanks for the bug report!
Can reproduce with new added row.
![2021-05-03 22_54_48-DBeaver Enterprise 21 0 4 - airports_data](https://user-images.githubusercontent.com/45152336/116926279-dc6f8280-ac62-11eb-8e12-a53ca6dbca52.png)

Is this ("Highlight rows with selected cells") setting enable?
![2021-05-03 22_55_17-Preferences](https://user-images.githubusercontent.com/45152336/116926191-c5c92b80-ac62-11eb-9f6a-0519c82bb9ac.png)

**Comment by MrRoiz01** [comment] 2021-05-03 20:05
Yes, it is
![image](https://user-images.githubusercontent.com/61702317/116927172-ec667280-ac20-11eb-926e-c86a6e1030f6.png)

**Comment by MrRoiz01** [comment] 2021-05-03 20:06
Yes, it is
![image](https://user-images.githubusercontent.com/61702317/116927260-0d2ec800-ac21-11eb-994d-95669e752800.png)

**Comment by serge-rider** [comment] 2021-05-03 20:19
Duplicate of #12286
Fixed

**Closed as completed by serge-rider** 2021-05-03 20:19 UTC
Labels: duplicate, xf:data

**Comment by MrRoiz01** [comment] 2021-05-03 20:33
Sorry, but I don't get it, if the bug was fixed, why is that happening to me?

**Comment by serge-rider** [comment] 2021-05-03 20:37
The bug was assigned to the milestone and was fixed in the source code. 
You can evaluate the fix after the next DBeaver release (21.0.5) or in the Early Access version.
