### ISSUE TITLE
Import Task Creation (Step 2: "Create a task" Wizard: Source type and format) Table - Fail [D19]

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7150] opened 2019-11-03 09:43 UTC
Import task (from database table) run fails if it was reopened for editing.

Steps:

1\. Create Import task (from database table). It is created and run properly fot the first time

2\. Reopen it for editing (Context menu of Task Bar) and go through Wizard

Expected result: the task runs successfully

Actual result Import wizard converts to export wizard after first step

<br>

Note:

1\. CSV import doesn't have such problem.

2\. If to fill first Wizard step for export, press Next, then to come back to first step (press Back) and change task type on "Data import", next wizard steps will be for export.

![null](<blob:https://dbeaver.testquality.com/79aa1dd5-09e8-4fbe-90a2-0af520e765ff>)[.log](<blob:https%3A//dbeaver.testquality.com/80522fbf-fb4e-4d38-839a-07d74c4cfd1c>)

<br>

**Comment by kseniiaguzeeva** [comment] 2019-11-03 09:43
`Created by TestQuality - Linked to TestQuality.com defect D19. Do not remove or edit.` [D19](https://dbeaver.testquality.com/project/8805/result/1598641/defect/5760)

**Comment by serge-rider** [comment] 2019-12-07 12:33
Probably duplicate of #7385

**Closed by serge-rider** 2019-12-07 12:33 UTC
Labels: Low, TestQuality, bug, duplicate
