### ISSUE TITLE
Bug createCachedImageDataProvider under Eclipse Neon

### ISSUE THREAD

**Issue by cniweb** [dbeaver/dbeaver#3451] opened 2018-05-09 12:03 UTC
An error occurs with version 5.0.4 with Eclipse Neon (4.6.1):
![dbeaver-error](https://user-images.githubusercontent.com/2334906/39813697-f3b4faee-5380-11e8-984a-7490ba94881f.png)

I think this code change is responsible for this:
https://github.com/dbeaver/dbeaver/commit/075555a6bccd193f05d6d18d2d47618aa4535785#diff-ccbc979cff26b9d2e81050db4a82f928

**Comment by serge-rider** [comment] 2018-05-09 16:49
Duplicate of #3414
Thanks for report anyway

**Closed by serge-rider** 2018-05-09 16:49 UTC
Labels: bug, duplicate
