### ISSUE TITLE
Snowflake Connection After Mac OS Update

### ISSUE THREAD

**Issue by daveackermanSPS** [dbeaver/dbeaver#21547] opened 2023-10-16 21:52 UTC
### Description

I recently upgraded to Mac OS Sonoma 14.0. Since the upgrade connecting to Snowflake is very slow and returning the list of databases is very slow. I’ve updated to the current version of DBeaver and also updated the driver.

### DBeaver Version

Community Edition 23.2.2

### Operating System

macOS Sonoma 14.0

### Database and driver

Database:Snowflake
Driver Type: Snowflake
Driver. Name: Snowflake

### Steps to reproduce

The snowflake connection I' connecting to has a lot of databases. When scrolling down on the projects page the spinner spins. Before I upgraded my MacOs I didn't have that issue. Scroll was fast and smooth.

**Comment by E1izabeth** [comment] 2023-10-17 12:10
Sounds like a duplicate of #21341

**Comment by E1izabeth** [comment] 2023-10-17 12:11
I'm closing it as a duplicate of #21341. If you think that your issue is different and has nothing to do with the mentioned one please let me know.

**Closed as not planned by E1izabeth** 2023-10-17 12:11 UTC
Labels: duplicate, xo:macos, xf:ui

**Comment by clemlaugit** [comment] 2023-11-14 20:48
this is not a dupe of 21341

**Comment by E1izabeth** [comment] 2023-11-14 20:52
Seems like I mentioned the wrong issue. I believe it's closed as a duplicate of #21214. Thank you for noticed
