### ISSUE TITLE
Can't change language under Windows 10

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#4630] opened 2018-11-18 19:22 UTC
Hi Serge,

using the current version 5.2.4 on Windows 10, I am not able to change the language of the IDE.

I can switch to english in the preferences, but after reopening DBeaver everything is in german. 
Because the German translation is a little spooky, it would be great if switching languages would work.
I have already installed DBeaver under c:\dbeaver\ to overcome potential access right issues, but that didn't solve it.

On Mac OS X everything is working fine and I can switch to english.

Greetings from Germany

James

**Comment by tchibatron** [comment] 2018-11-19 07:14
I have the same issue with russian language on Windows 10. Looks like DBeaver uses system locale instead of configured locale in settings.

**Comment by serge-rider** [comment] 2018-11-19 07:17
This issue may happen on Windows if you install DBeaver in program files directory and on Linux if you are using deb installer.

Please see #2838 for workaround.

**Comment by tchibatron** [comment] 2018-11-19 11:29
I dont install it. I downloaded zip archive and run from the directory. Is it a bug?

**Comment by serge-rider** [comment] 2018-11-19 20:15
Perhaps. Changing language in preferences chnges dbeaver.ini file (adds or changes -nl parameter). If this doesn't happen then this is abug.

Could you check this? I can't reproduce this problem on Windows.

**Comment by tchibatron** [comment] 2018-11-20 10:22
Steps to reproduce:
1. Open DBeaver.
2. Go to Window -> Preferences -> Database
3. Change language to any different from current.
4. Click Apply and Close button.
5. Click Yes button in Restart confirmation dialog.

DBeaver restarts with the same language as was before. But if you close it and open again language will be changed to selected in step 3.
@JamesInform Do you observe the same behavior?

By the way it does not depend on OS. On linux I see the same issue.

**Comment by GeriZ** [comment] 2019-01-08 10:53
When I want to switch the language from my default German to English I receive this error message(as a normal user not as admin). The reason is that dbeaver.ini is located in C:\Program Files\DBeaver which is write protected for non-admins. I think this language setting should not be saved in dbeaver.ini to avoid this problem

Message:

Can't switch language to en

Ursache:
Can't save startup configuration - access denied.
You could try to change national locale manually in 'C:\Program Files\Dbeaver\dbeaver.ini'. Refer to readme.txt file for details.

**Comment by idontwannarock** [comment] 2019-04-17 03:13
I had the same problem. I am using Windows 7 with DBeaver 6.0.1 installing from Chocolatey. So I didn't get a chance to choose a language and DBeaver was naturally installed in C:\Program Files\DBeaver folder which caused access problem to change the language from Preference. Furthermore adding `-nl XX` in dbeaver.ini somehow didn't work for me at the time.

But I managed to solve this problem. I added `-nl XX` to the path of a shortcut, opened from it, and voila! 

Just for your reference.

**Comment by ridcully99** [comment] 2019-04-25 06:29
For me, the shortcut that was created by the installer (in C:\ProgramData\Microsoft\Windows\Start Menu\Programs\DBeaver Community) had a -nl de appended. I removed that and now it takes the language from the ini file.

**Comment by lusorio** [comment] 2019-09-18 12:07
I've just executed DBeaver as admin and was able to change the language

**Closed** 2019-10-03 12:28 UTC
Labels: question

**Comment by tobwen** [comment] 2019-10-29 19:20
Problem still exists on my Windows 7 machine. I'm using v6.2.3.291810211155

![image](https://user-images.githubusercontent.com/1864057/67801483-84622980-fa89-11e9-886e-9cdd4d2ee9eb.png)

**Comment by ubellavance** [comment] 2020-01-08 15:51
I found that the shortcut created by the installer had an -nl in it. I had to remove it so that my language change applies.

**Comment by iurijacob** [comment] 2020-06-24 13:44
> For me, the shortcut that was created by the installer (in C:\ProgramData\Microsoft\Windows\Start Menu\Programs\DBeaver Community) had a -nl de appended. I removed that and now it takes the language from the ini file.

Same here! Problem solved! Thanks @ridcully99

**Comment by andriimazur93** [comment] 2022-05-13 09:48
as on March 2022, DBeaver 22.0.4, I can confirm that deleting -n xx from the path in the shortcut solves the issue

**Comment by Teett** [comment] 2022-06-22 17:21
Just a thought, Why is this -nl hardcoded into the default shortcut? People should't have to come to this thread to change their language, most wouldn't probably even find it. Thanks for the fix @ridcully99

**Comment by llagerlof** [comment] 2022-08-01 11:53
Although this issue is already closed, this happened to me in Fedora 36, but I managed to solve the problem using another workaround instead the `-nl` option.

My system is in `pt_BR` and after I installed `DBeaver-CE 22.1.3` as a normal user, the application configured itself to `pt_BR` and didn't let me change to `en_US` in DBeaver preferences (the exactly issue informed by @JamesInform).

In my case the interface language is an eclipse configuration file located in `~/.eclipse/org.jkiss.dbeaver.product_22.1.3_302967072_linux_gtk_x86_64/configuration/config.ini` (of course, the full path name depends on your DBeaver version.

In this config file there is a line `osgi.nl=pt_BR`. I changed it to `osgi.nl=en_US`, open dbeaver and the interface language changed to english.

I hope this helps someone.

**Comment by dreamflasher** [comment] 2022-12-04 14:31
@serge-rider This issue should be reopened. The shortcut is being created with `-nl` flag, so the language can't be changed without googling, finding this issue and fixing the shortcut.

**Comment by mbrembati** [comment] 2023-05-05 13:26
Same issue here on version 23.0.2 trying to switch to English from Italian due to poor translation and to be able to take advantage of English tutorials and documentation.

**Comment by sangshuduo** [comment] 2023-06-26 03:08
23.1.1 still has this issue

**Comment by danilomourelle** [comment] 2023-07-10 14:57
Hi!

On windows I notice that shortcuts (work area on Start menu) has a destiny path on properties like `...AppData\Local\DBeaver\dbeaver.exe -nl pt_BR` and just after changing this I was able to boot it in english.

**Comment by dreamflasher** [comment] 2023-07-10 14:59
@serge-rider

**Comment by sweihub** [comment] 2023-10-27 02:05
> I've just executed DBeaver as admin and was able to change the language

Not working with latest `23.2.3.202310221533`, canno change the interface language.

**Comment by sweihub** [comment] 2023-10-27 02:08
> Hi!
> 
> On windows I notice that shortcuts (work area on Start menu) has a destiny path on properties like `...AppData\Local\DBeaver\dbeaver.exe -nl pt_BR` and just after changing this I was able to boot it in english.

Find the launcher shortcut, and change the command line, the issue was the language was hard-coded in command line after installation.

```
D:\DBeaver\dbeaver.exe -nl zh
```

Remove the `-nl zh` argument will let you set the language on the preference.

Now it works!

**Comment by dluca22** [comment] 2023-11-08 09:08
> Find the launcher shortcut, and change the command line, the issue was the language was hard-coded in command line after installation.
> 
> ```
> D:\DBeaver\dbeaver.exe -nl zh
> ```
> 
> Remove the `-nl zh` argument will let you set the language on the preference.
> 
> Now it works!

Can confirm, this solution worked for me

**Comment by akarim-ofc-outlook** [comment] 2023-11-15 08:42
Hey @ShadelessFox, 

Cannot switch languages, care so share why, please?

I first installed using Choco, uninstalled using Choco, directly no cache is there.
The installed new version from the website still contains the buggy language, why?

If you are making something please do some QA testing.

![image](https://github.com/dbeaver/dbeaver/assets/142506278/26d4010e-972b-4409-aa1b-101d2d812a12)
![image](https://github.com/dbeaver/dbeaver/assets/142506278/aa3da732-6c7b-4fe2-9667-372350d6434b)
![image](https://github.com/dbeaver/dbeaver/assets/142506278/bccfc0ee-55cf-402b-a541-df991b820939)

Share your workaround to make it to the English.

**Comment by ShadelessFox** [comment] 2023-11-15 11:50
Hello @akarim-ofc-outlook,

This is a third-party issue. It's not like we don't want to fix it - we just can't.

- Have you tried changing the main font (or resetting it) in<br><kbd>Preferences -> User Interface -> Appearance -> Colors and Fonts -> DBeaver Fonts -> Main font</kbd> ?
- Have you tried switching to the Basic or Classic theme in<br><kbd>Preferences -> User Interface -> Appearance -> Theme</kbd> ?

**Comment by palerme** [comment] 2023-11-23 03:02
> Hello @akarim-ofc-outlook,
> 
> This is a third-party issue. It's not like we don't want to fix it - we just can't.
> 
> * Have you tried changing the main font (or resetting it) inPreferences -> User Interface -> Appearance -> Colors and Fonts -> DBeaver Fonts -> Main font ?
> * Have you tried switching to the Basic or Classic theme inPreferences -> User Interface -> Appearance -> Theme ?

This only occurs in Dark mode, in classic mode, it's normal! And it is not possible to change the colors in classic mode, no matter how much you make any changes, they will not be noticed.

**Comment by bralbral** [comment] 2023-12-07 17:03
> > Hi!
> > On windows I notice that shortcuts (work area on Start menu) has a destiny path on properties like `...AppData\Local\DBeaver\dbeaver.exe -nl pt_BR` and just after changing this I was able to boot it in english.
> 
> Find the launcher shortcut, and change the command line, the issue was the language was hard-coded in command line after installation.
> 
> ```
> D:\DBeaver\dbeaver.exe -nl zh
> ```
> 
> Remove the `-nl zh` argument will let you set the language on the preference.
> 
> Now it works!

Thanks you! You saved my day.

**Comment by gruz** [comment] 2024-05-17 16:54
I'm at linux. And met the problem. My desktop shorctut command is

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/dbeaver/dbeaver io.dbeaver.DBeaverCommunity`

So no `-nl` arguement.

I managed to change the language only by adding a language env variable to the shortcut:

`env LANG=en-GB.utf8 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/dbeaver/dbeaver io.dbeaver.DBeaverCommunity`

**Comment by rainbyte** [comment] 2025-01-21 04:56
Hello, I'm still having this issue on Arch Linux + Flatpak when trying to change from Spanish (my system language) to English

@gruz provided workaround allowed me to indicate English as preferred language for DBeaver
