### ISSUE TITLE
Missing Dependencies in Deb Pkg Cause GLIBC Errors

### ISSUE THREAD

**Issue by mlozturk** [dbeaver/dbeaver#36023] opened 2024-10-22 06:57 UTC
### Description

Hi,

After installing DBeaver (v24.2.3) from the deb pkg, I get the following error when trying to run it:
```
dbeaver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by dbeaver)
dbeaver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by dbeaver)
```
This error occurs because the deb pkg is missing dependency information. To fix this,  **debian/control** file should include:

`Depends: ${shlibs:Depends}, ${misc:Depends}
`

### DBeaver Version

24.2.3

### Operating System

Pardus 21

**Comment by lchevall** [comment] 2024-10-22 08:09
Hello,

Same problem here with Ubuntu 20.04.
I had to revert back to version 24.2.2.

**Comment by pfiadDi** [comment] 2024-10-22 08:22
Same on Ubuntu 22.04.5 LTS with the -ce version installed via snap
Br

**Comment by E1izabeth** [comment] 2024-10-22 09:19
Thanks for the bug report.
I'm closing it as a duplicate of #36006

**Closed as not planned by E1izabeth** 2024-10-22 09:19 UTC
Labels: duplicate, xo:linux
