### ISSUE TITLE
Execution plan is saved without extension

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13952] opened 2021-09-20 07:39 UTC
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.1
- Additional extensions

#### Steps to reproduce, if exist:
1. Open an execution plan for a query
2. Click <kbd>Save plan</kbd>
3. Enter a name and select .dbplan extension

**Expected:** Plan is saved as `plan_name.dbplan`
**Actual:** Plan is saved as `plan_name`

The same behavior is observed when saving custom ER diagrams

**Comment by serge-rider** [comment] 2021-11-10 14:24
Duplicate of #14013

**Closed as completed by serge-rider** 2021-11-10 14:24 UTC
Labels: xo:windows
