### ISSUE TITLE
Query Tabs Closing Upon Save

### ISSUE THREAD

**Issue by thepratshow** [dbeaver/dbeaver#19847] opened 2023-05-02 00:33 UTC
### Description

For the past several version updates, some of my open query tabs have been, for some reason, closing themselves when I click on the Save button. I've attached a screenshot below showing the very simple setup I use when preparing to insert new rows.

![dbeaver](https://user-images.githubusercontent.com/132313012/235552669-8314f65a-cfb8-475d-b320-55ff9155d317.png)

The issue does not occur consistently and seems to be more likely to occur the first couple of times changes are saved during a session.

### DBeaver Version

Community Edition 23.0.3

### Operating System

Windows 10 Version 21H2 (OS Build 19044.2846)

### Database and driver

1. Database Name and Version; MySQL 8
2. Database Driver Name and Version: JDBC Driver for MySQL 8 (Connector/J)

### Steps to reproduce

1. Connect to database
2. Run script with 3 SELECT queries to open up the tables into which new data will be inserted into 3 new tabs
3. Add any number of new rows to any of the tables
4. Click Save
5. One or more of the open tabs closes

**Comment by uslss** [comment] 2023-05-02 10:04
Thanks for the report.
Closed as a duplicate of #19839

**Closed as completed by uslss** 2023-05-02 10:04 UTC
Labels: duplicate
