### ISSUE TITLE
Right clicking database navigator does not always open menu

### ISSUE THREAD

**Issue by GammaGames** [dbeaver/dbeaver#6776] opened 2019-09-18 15:00 UTC
#### System information: 
- Ubuntu 18.04.2 LTS
- DBeaver Version 6.2.0.201909081341

#### Describe the problem you're observing:
When the database navigator is not in focus, right clicking a database to open the properties menu does not work. Sometimes, even if it is focused, it does not open (but that appears to only be an issue in about the first minute that the program has started).

Right clicking every other panel always opens a menu, so this is an inconsistency against what users would expect to happen.

#### Steps to reproduce, if exist:
This is right after opening, every click on the left panel was a right click:
![Screen record from 2019-09-18 08 44 16](https://user-images.githubusercontent.com/7832163/65159807-de36f480-d9f1-11e9-9df8-7c547fba1cb9.gif)

**Comment by serge-rider** [comment] 2019-09-18 20:17
Duplicate of #6489

**Closed by serge-rider** 2019-09-18 20:17 UTC
Labels: bug, duplicate
