### ISSUE TITLE
Error again

### ISSUE THREAD

**Issue by vsg68** [dbeaver/dbeaver#2664] opened 2017-12-20 11:39 UTC
Hi, try in oracle java-8 - lanching ok. Trying java-9...  
Error:

> Caused by: java.lang.ClassNotFoundException: javax.annotation.PreDestroy cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418

Config dbeaver 4.3.0
> root@dep-PC:/usr/share/dbeaver# cat dbeaver.ini 
> -startup
> plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
> --launcher.library
> plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.550.v20170928-1359
> -showsplash
> --launcher.GTK_version
> 2
> -vmargs
> -XX:+IgnoreUnrecognizedVMOptions
> --add-modules=ALL-SYSTEM
> -Xms64m
> -Xmx1024m

Java version^
> root@dep-PC:/usr/share/dbeaver# java -version
> java version "9.0.1"
> Java(TM) SE Runtime Environment (build 9.0.1+11)
> Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
> root@dep-PC:/usr/share/dbeaver#

**Comment by serge-rider** [comment] 2017-12-20 18:42
I can't reproduce that but it looks like this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=526438
And https://bugs.eclipse.org/bugs/show_bug.cgi?id=526606

They say that it was fixed in the recent platform version. If so then next DBeaver version will fix this.

**Comment by tati-kru** [comment] 2018-01-19 11:08
hi @vsg68 
Do you have a chance to check it on the latest DBeaver version?

**Comment by serge-rider** [comment] 2018-06-15 13:47
Please check with latest version. 
DBeaver 5.x is fully Java 9 compatible .

**Closed by serge-rider** 2018-06-15 13:47 UTC
Labels: bug, can't reproduce, question
