### ISSUE TITLE
Need option in Layout to resize column but fit column name

### ISSUE THREAD

**Issue by daevidvincent** [dbeaver/dbeaver#6045] opened 2019-06-03 18:47 UTC
There are two options for `Layout` in Data grid view. You can "pack to fit screen" or "pack to fit values". Great. The issue is that the column name is often truncated! There should be a separate toggle to force the column name to not truncate (despite whatever pack mode you choose). There are times you may want the column name truncated as it is now too (to save space or whatever). But there are times you want the full name there too, especially if you have similarly named colunns like `is_enabled`, `is_optional`, `is_deprecated`, ... 

![image](https://user-images.githubusercontent.com/20825058/58826374-6933e080-85f5-11e9-9ee1-afddad8f5e46.png)

**Comment by serge-rider** [comment] 2019-06-05 16:16
I can't reproduce the issue with truncated column names (which actually looks like a bug).
What database do you use?

**Comment by daevidvincent** [comment] 2019-06-05 19:06
That's Postgres, but seems the RDBMS shouldn't be a factor?! I wouldn't go as far as 🐛  since it does have it's usefulness to compress space. I think it just needs a "feature" to expand upon it (no pun intended) as described. I could see cases where I'd want them truncated and other cases where I want them to be expanded (despite the width of the data values themselves)

**Comment by chriszrc** [comment] 2019-09-19 15:32
On dbeaver 6.1.3 on a mac with postgres, when fitting to values, it respects the length of the column name. I actually want the option of actually fitting to data, so I can have two tables side by side on the same screen :)

**Comment by tommai78101** [comment] 2020-02-19 18:49
@chriszrc That's already in there I believed.

![Peek 2020-02-13 13-32](https://user-images.githubusercontent.com/6444116/74865127-a7f1fe00-531e-11ea-8525-9c6b90302af4.gif)

**Comment by daevidvincent** [comment] 2020-02-19 19:04
You guys aren't getting what I'm saying. Let me try to illustrate. There is no setting (fit screen or fit values) where the COLUMN HEADINGS are ALL NOT truncated... This is especially apparent in the case of integer or booleans where the row data is very "slim" but the table's property/column is "long"... 

![image](https://user-images.githubusercontent.com/20825058/74866178-43777480-5307-11ea-84ac-8f2913543080.png)

![image](https://user-images.githubusercontent.com/20825058/74866221-5db15280-5307-11ea-9c90-75c1ec550f4c.png)

Not that in either choice, the red arrows show the heading is truncated! 

I want a 3rd option or something that always ensures the FULL column name is shown, regardless of the other two "fit screen" / "fit values" setting

**Comment by tommai78101** [comment] 2020-02-20 16:01
@daevidvincent 

Yes.  It's just that @chriszrc was mentioning something else unrelated to your issue, and I clarified to @chriszrc that his issue is already implemented.

**Comment by chriszrc** [comment] 2020-02-21 21:05
@tommai78101 @daevidvincent Well, I think we're seeing different behavior here on different platforms. On MacOS, when I click "Column widths: fit value", it does respect the title widths, which is actually what I wasn't wanting in that last comment:

![Screen Recording 2020-02-21 at 3 58 29 PM](https://user-images.githubusercontent.com/25695785/75071646-c3e2d480-54c3-11ea-8253-b038be9a3d0c.gif)

I was hoping for the following options:
- fit to values, which would fit to values and ignore everything else
- fit to header/title which would fit to the header/title width
- fit to screen (I think that one does what we all think it does)

**Comment by tommai78101** [comment] 2020-02-22 02:05
@chriszrc  Huh, interesting how in Ubuntu, it doesn't do what Mac OS X does.  :-(

In that case, I do agree wholeheartedly that we need the 3 options, and the behaviors need to be consistent across the supported platforms.

**Comment by armandoclasslife** [comment] 2021-02-21 07:53
Hi guys, I want to twist the twister.

What I would like to have is to fit the longest one between column and content.

I am on Linux. If you fit to the content and the column name is longer than the content, the column name is truncated. So I would like to fit to the longest one between the column name and the content, so that I would always see the column name and the column content entirely.

Is it possible? Feature request? If last, it should be simple to add that option.

**Comment by BRCHDN** [comment] 2021-02-21 09:01
I am out of the office until 01/03/2021.




Note: This is an automated response to your message  "Re: [dbeaver/dbeaver]
Need option in Layout to resize column but fit column name (#6045)" sent on
21/02/2021 08:53:56.

This is the only notification you will receive while this person is away.
Unless otherwise specified, this e-mail message (including its attachments) contains confidential information and is intended to be conveyed only to the designated recipient(s). If you are not an intended recipient of this message, please notify in the shortest delay the sender by replying to this message and then delete it from your system. The Centre Hospitalier du Nord is not liable for any direct or indirect damage arising from errors, inaccuracies or any loss in the message, from unauthorized use, disclosure, copying or alteration of it or as a result of any virus being passed on. Use or disclose of this message and the personal data it may contain by unintended recipients is not authorised and may be unlawful.

**Comment by Horizon-cmchugh** [comment] 2021-06-25 17:22
Just wanted to reiterate this request. Having a "fit column name/headers" for the column width would be greatly preferred here and/or having some setting that did it automatically. I turned off the filtering and sort buttons as those further obfuscate the headers.

**Comment by kingwrcy** [comment] 2021-07-14 09:59
Please add this feature,We need it,Now the filed name is truncated.

Please add something like blow:

```
column_with = max(column_field_name,column_value)
```

**Comment by uslss** [comment] 2021-11-18 08:34
will be fixed in 21.3.0
![A8evZCT8P0](https://user-images.githubusercontent.com/31996417/142380104-c6d232c3-0bfb-4b5f-86b3-cffa1f20a750.gif)

**Closed by uslss** 2021-11-18 08:34 UTC
Labels: feature request

**Comment by daevidvincent** [comment] 2022-04-22 17:32
Can this bug please get fixed... I'm in `22.0.3` and it's **still not working correctly on Windows 10**. How do we re-open this bug @uslss ?
![image](https://user-images.githubusercontent.com/20825058/164765147-7e6eba4a-fe61-4fee-9ba9-a766e2543ea5.png)

**Comment by Walker555** [comment] 2022-07-19 06:15
Hi, I'm new to dbeaver. I'm also missing the feature wanted by @daevidvincent . The tool "SQL Workbench/J" can do it. Look at the attached screenshot. Column header isn't truncated and it contains all the useful information. Can you implement it?
![2022-07-19_08-09](https://user-images.githubusercontent.com/11910822/179678468-a1be25eb-c46c-46b3-87cb-ba0f141a5383.png)
Notice: I have installed the dbeaver-ce-22.1.2-linux.gtk.x86_64.tar.gz on Linux Mint. The option "column width: fit screen / values" isn't working at all. Useless.

**Comment by mousey92** [comment] 2022-09-29 09:38
I believe this issue was indeed fixed, even for Windows, a few subversions ago. I recently updated to 22.2.1(.202209251341) and I'm seeing this issue arise again, especially on columns with integer values:
![image](https://user-images.githubusercontent.com/26246536/192997567-4ede9698-16cc-4da2-9e3c-bacf349ea0f4.png)

**Comment by BRCHDN** [comment] 2022-09-29 14:02
I am out of the office until 10/10/2022.




Note: This is an automated response to your message  "Re: [dbeaver/dbeaver]
Need option in Layout to resize column but fit column name (#6045)" sent on
29/09/2022 11:38:45.

This is the only notification you will receive while this person is away.
Unless otherwise specified, this e-mail message (including its attachments) contains confidential information and is intended to be conveyed only to the designated recipient(s). If you are not an intended recipient of this message, please notify in the shortest delay the sender by replying to this message and then delete it from your system. The Centre Hospitalier du Nord is not liable for any direct or indirect damage arising from errors, inaccuracies or any loss in the message, from unauthorized use, disclosure, copying or alteration of it or as a result of any virus being passed on. Use or disclose of this message and the personal data it may contain by unintended recipients is not authorised and may be unlawful.

**Comment by josephf11** [comment] 2023-02-09 14:45
I am using 22.3.4 and the headers are truncated. To note, the issue here is directly related to the width of the header titles NOT the data. The option to autofit to the length of the data works fine, but I can't read my header columns if they are longer than the data.

**Comment by tsdevau** [comment] 2023-02-14 20:21
I am also having this issue running 22.3.4 on MacOS Ventura 13.2.  Fit values and Fit screen seem to do exactly the same thing for me.  Which is fitting to the width of the cell content and ignoring the column label.  I can't see a difference in the result between the two options.

<img width="1728" alt="Screenshot 2023-02-15 at 06 22 59" src="https://user-images.githubusercontent.com/93500023/218853673-8d95fab6-cf4f-4738-91f5-cc64a7aae80b.png">

**Comment by tsdevau** [comment] 2023-02-16 01:19
In case anyone stumbles across this issue from a google search in the future ... I was able to resolve my issue by ***unchecking*** the `Calculate column width by cell values` option in `Preferences > Editors > Data Editors > Appearance`.

<img width="621" alt="Screenshot 2023-02-16 at 11 01 10" src="https://user-images.githubusercontent.com/93500023/219234729-cc60e43a-5613-48d6-932c-265be09e210e.png">

Then when selecting the option to adjust `columns width: fit values` it will respect the column header/label.

**Comment by anthonykamarflores** [comment] 2023-09-08 16:13
> In case anyone stumbles across this issue from a google search in the future ... I was able to resolve my issue by _**unchecking**_ the `Calculate column width by cell values` option in `Preferences > Editors > Data Editors > Appearance`.
> 
> <img alt="Screenshot 2023-02-16 at 11 01 10" width="621" src="https://user-images.githubusercontent.com/93500023/219234729-cc60e43a-5613-48d6-932c-265be09e210e.png">
> 
> Then when selecting the option to adjust `columns width: fit values` it will respect the column header/label.

This solution doesn't appear to work for Windows 10... 

I'm using DBeaver Community Version 23.2.0.202309041200 on Windows Version 10.0.19045 Build 19045. Seems like the bug is still persistent even after unchecking the box and attempting to use `columns width: fit values`
