### ISSUE TITLE
SQL Editors briefly hang and throw error when clicked in after idle, repeat query results not fresh, manual invalidation fixes both

### ISSUE THREAD

**Issue by D3SL** [dbeaver/dbeaver#9713] opened 2020-09-07 13:41 UTC
#### System information: 
- Win10 Pro 19041.450
- 7.2.0 CE
- none

#### Connection specification:
- Mysql
- Built-in Mysql
- Sometimes a VPN

#### Describe the problem you're observing:
Prior to the last few updates I could connect to a mysql server, open a few sql editors, and it would "just work". If I went to do something else for a while and came back it would "just work". If I re-ran a query to get fresh results it would "just work".

Since approximately version 7.1.5 dbeaver now requires that I constantly manually invalidate or disconnect/reconnect to even use the user interface. If I do something else for even a brief period and return to dbeaver the UI will hang the moment I click inside a SQL editor window and then give Error 08003 saying "No operations allowed after connection is closed". 

Additionally even if I use dbeaver regularly enough to not run into that error, I still need to manually invalidate or disconnect/reconnect on a regular basis or the results I get are inaccurate and out of date. I can't run a query and then however much time later rerun the same query to see the latest results, I'll just get the old results again.

I haven't changed any settings within dbeaver, all I did was upgrade to about 7.1.5 and start having these issues where I never did before.

#### Steps to reproduce, if exist:
Use dbeaver with a mysql database.

#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Warning
Sun Sep 06 15:37:25 IDT 2020
org.jkiss.dbeaver.DBException: SQL Error [08003]: No operations allowed after connection closed.

eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Warning
Sun Sep 06 15:34:13 IDT 2020
org.jkiss.dbeaver.DBException: SQL Error [08S01]: Communications link failure
The last packet successfully received from the server was 7,596,143 milliseconds ago.  The last packet sent successfully to the server was 7,596,168 milliseconds ago.

**Comment by uslss** [comment] 2020-09-09 09:41
Hi @D3SL ,
could you try to change Keep-Alive option to non-null and write back if it helps? Thanks in advance
![image](https://user-images.githubusercontent.com/31996417/92582512-b93e3000-f299-11ea-84da-9d91a9beb028.png)

**Comment by uslss** [comment] 2020-09-10 11:57
closed as duplicate of #9716

**Closed by uslss** 2020-09-10 11:57 UTC
Labels: bug, duplicate
