### ISSUE TITLE
some bug——but not important

### ISSUE THREAD

**Issue by lxkplus** [dbeaver/dbeaver#11654] opened 2021-03-09 03:03 UTC
Hello. I found some bugs.

My screen is lit up, so I set a look (dark).

Then I exported the settings. When I imported them, I found that they didn't change the appearance.

I opened the file and looked at it

The contents are as follows:

#Sat Mar 06 00:21:49 CST 2021

\!/=

/instance/ org.eclipse.ui .workbench/ org.eclipse.ui .commands=<?xml version\="1.0" encoding\="UTF-8"?>\r\n< org.eclipse.ui .commands/>

@ org.eclipse.ui .workbench=3.122.0.v20201122-1345

file_ export_ version=3.0

Obviously, there is no appearance.

It's not important, but it's just a bug.

There is also a small problem

The system default minimum varchar is 0 (I think the default value is 255, because it is varchar).

When I import, it will read the number of rows I set (but not the maximum number), and then select the maximum number of rows as the width of varchar.

But this is not reasonable - the database always needs to expand, if one more character will crash, it is not appropriate.

In my opinion, the default value should be twice the width value—— or 1.5 . Now varchar doesn't take up much of the hard disk.

It's just a suggestion.

**Comment by uslss** [comment] 2021-03-18 09:59
Hi @lxkplus ,
could you provide more clear steps to reproduce? Probably, with screenshots/video.
Thanks in advance

**Comment by lxkplus** [comment] 2021-03-24 06:20
![图片](https://user-images.githubusercontent.com/78188981/112264337-b4782100-8cab-11eb-8a88-88ed286a1f91.png)
the text and background is all white 。and i cannot change it by Appearance settings

**Comment by uslss** [comment] 2021-04-20 11:15
seems the issue is fixed in 21.0.3

**Closed as completed by uslss** 2021-04-20 11:15 UTC
Labels: wait for response
