### ISSUE TITLE
Shortcut Key Captured in Wrong Context

### ISSUE THREAD

**Issue by alexkoay** [dbeaver/dbeaver#8537] opened 2020-04-24 05:18 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.0.3
- Additional extensions: None

#### Describe the problem you're observing:
When I use Ctrl+Backspace in the text editor, the results set current active field gets set to default instead.

#### Steps to reproduce, if exist:
1. Run a query.
2. Navigate around in the results set.
3. Click back to the SQL editor and type some text.
4. Press Ctrl+Backspace to delete last word.
5. **Expected:** Word in the SQL editor gets deleted. Active results set remains untouched.
**Actual:** Active results set cell will be set to default. Word in the SQL editor does not get deleted.

**Comment by uslss** [comment] 2020-04-24 14:36
hi @alexkoay ,
unfortunately cannot reproduce.
Please check if i do it right?
![2020-04-24_17h35_19](https://user-images.githubusercontent.com/31996417/80224251-1e2e1c00-8652-11ea-8dc6-1537185ae17f.gif)

**Comment by alexkoay** [comment] 2020-04-28 03:43
@uslss I deleted the .metadata folder from my workspace and it seems to be working as expected now. Might have been some issues with upgrading from earlier versions.

**Comment by alexkoay** [comment] 2020-04-29 03:06
@uslss I've been encountering it again, and it seems to only happen after I cancel a long-running query, causing a small text editor to pop up at the Value / Grouping panels area on the right side of the results set.
Once that happens, any form of text editing seems to be in the results set context.

**Comment by alexkoay** [comment] 2020-05-11 02:57
Found a simple reproduction on PostgreSQL from a fresh start:

1. Execute `select pg_sleep(30);`
2. Cancel the query.
2. Execute `select 1,2,3;`
3. Shortcuts that have both Text Editor and Resultset bindings will use the resultset capture in all situations. (e.g. Ctrl-Backspace, Ctrl-Delete)

![error](https://user-images.githubusercontent.com/3108237/81520172-21294c00-9376-11ea-80b8-7df8d533c526.gif)

**Comment by alexkoay** [comment] 2020-05-25 15:23
@uslss ping

**Comment by uslss** [comment] 2020-06-26 13:02
@alexkoay thanks for the clarification.
Sorry for the late response

**Comment by serge-rider** [comment] 2020-07-09 14:54
I think it was fixed in #8887

**Comment by uslss** [comment] 2020-07-10 13:47
verified

**Closed by uslss** 2020-07-10 13:47 UTC
Labels: bug
