### ISSUE TITLE
Can't edit data in Data Editor for SQLite conections

### ISSUE THREAD

**Issue by phbuss** [dbeaver/dbeaver#7350] opened 2019-12-03 16:24 UTC
#### System information: 
- Operating system: Windows 10
- DBeaver version: 6.3.0.201912021731
- Java version: 1.8.0_221 

#### Connection specification:
- Database name and version: SQLite
- Driver name: SQLite JDBC driver by Taro L. Saito (extension of Zentus driver) 3.28.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No, SQLite files are local

#### Describe the problem you're observing:
I cannot edit the data in the "Data Editor" on any SQLite connection. On another computer running DBeaver version 5.2.1 with driver in version 3.25-2 I can edit normally. I have already tried to change the driver version in DBeaver 6 but the problem persists.

#### Steps to reproduce, if exist:
1. Create a connection to any SQLite database;
2. Run an SQL and in the "Data Editor" panel try to edit any value;
3. The message "Column <ColumnName> is read only" is sent to any changed column;

Thank's!

Paulo H. Buss

**Comment by serge-rider** [comment] 2019-12-03 21:35
I can't reproduce it.

Check connection settings:
![image](https://user-images.githubusercontent.com/6398845/70091805-f94af500-162d-11ea-8893-7a82bfe0ed95.png)

**Comment by phbuss** [comment] 2019-12-17 17:34
Thanks for the feedback and sorry for the delay in replying.

As you can see in the picture, my connection is not set to read only.

![1  Connection Settings](https://user-images.githubusercontent.com/33836478/71019892-f34b1e80-20d9-11ea-800b-61449ab194ab.png)
![2  Data Editor](https://user-images.githubusercontent.com/33836478/71019893-f34b1e80-20d9-11ea-9911-03b64ee87a1d.png)

Any other ideas on how to solve this problem?

Thank's!

Paulo H. Buss

**Comment by ajpuerta** [comment] 2019-12-30 13:54
Same problema here. Works with Oracle but not with SQL Server. 
Working with SQL Server only works in table view (data tab).

The problem appears since I updated to the last version (6.3.1)

**Comment by uphlewis** [comment] 2020-02-10 17:53
Im getting this randomly on a mysql connection on Ubuntu 19.10 on a tinyint (bool) column.

I've tried invalidating the connection (it was intially established to my local VM a few days ago), closing the table and re-opening it, but to no avail.

I think it could be a bug related to schema changes since dbeaver queried (and cached?) the schema for this table.

Completely restarting Dbeaver solved it for me.

**Closed** 2020-04-20 23:03 UTC
Labels: can't reproduce, question

**Comment by nobicycle** [comment] 2021-03-22 13:57
This problem now occurs under:

Version 21.0.0.202103152349
Linux tower 5.10.23-1-MANJARO #1 SMP PREEMPT Thu Mar 11 18:47:18 UTC 2021 x86_64 GNU/Linux

![Screenshot_2021-03-22_21-56-50](https://user-images.githubusercontent.com/1372447/112001069-8edb0280-8b59-11eb-8908-e1c19c19ef89.png)

**Comment by eohtake** [comment] 2024-05-08 03:25
Changing the Connection type to 'Test' did the trick for me.

<img width="866" alt="image" src="https://github.com/dbeaver/dbeaver/assets/13766344/167b5dee-cccb-4f4f-87ff-cb826082faf6">
