### ISSUE TITLE
Invalid SQL statement generated for a table without a primary key

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13344] opened 2021-07-28 08:50 UTC
In addition to a feature added in #8760 it would be better to somehow warn the user that generated `SELECT .. WHERE .. IN` statement would be invalid if the table does not have a primary key.

**Comment by ShadelessFox** [comment] 2021-07-28 09:02
Or we can use selected columns instead of keys.

**Comment by ShadelessFox** [comment] 2022-01-24 08:23
Duplicate of #14193

**Closed as completed by ShadelessFox** 2022-01-24 08:23 UTC
Labels: enhancement, duplicate, xf:sql, xf:data
