### ISSUE TITLE
The value is not set for the parameter number 1.

### ISSUE THREAD

**Issue by pruggera** [dbeaver/dbeaver#4677] opened 2018-11-23 23:16 UTC
Just installed 5.2.5 and now I get "The value is not set for the parameter number 1." on every database I try to connect to.  I was asked to select new MS SQL driveres during the install. Clicked download.

I don't appear to have any DB driver now for MS SQL.

I use 
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>sqljdbc4</artifactId>
			<version>4.0</version>
		</dependency>

to get the driver for other apps.

Fixed by falling back to 5,2.4

**Comment by serge-rider** [comment] 2018-11-26 01:38
Duplicate of #4636 (see comments for workaround)

**Closed by serge-rider** 2018-11-26 01:38 UTC
Labels: bug, duplicate
