### ISSUE TITLE
ERD Diagramm

### ISSUE THREAD

**Issue by AndreaHaymoz** [dbeaver/dbeaver#18738] opened 2023-01-11 12:55 UTC
I have a question about the erd diagramm of dbeaver.  We have the erd diagramm file on the filesystem to push it to git. In the ERD-Diagramm File we have the data_source id = ."... ".  How is it possible that 2 personen can work with the same erd_diagramm without to change the datasource id in the erd file?

**Comment by ShadelessFox** [comment] 2023-01-12 13:54
Hello @AndreaHaymoz,

As a general solution, there's none.

As a workaround, you or your colleague can change the ID of the data source to match the other's data source ID.

Duplicate of #13503

**Closed as not planned by ShadelessFox** 2023-01-12 13:54 UTC
Labels: duplicate, xf:erd
