### ISSUE TITLE
Toolbar buttons disapearing when mouse pointer over it.

### ISSUE THREAD

**Issue by chiessi-lmb** [dbeaver/dbeaver#19612] opened 2023-04-05 14:26 UTC
### Description

After updating to 23.0.1 version, we have a problem when the mouse cursor gets over the toolbar.
The picture below shows the normal toolbar when DBeaver opens:
![image](https://user-images.githubusercontent.com/75741623/230110059-5714f9bc-66e7-4e23-ac54-f999df5a9aea.png)
But, when we go to click in a toolbar button, all toolbar buttons disappear like the picture below:
![image](https://user-images.githubusercontent.com/75741623/230110485-9cd4939d-bf1f-4c62-a359-b08c99434816.png)
To fix this, we need to close and open again.

### DBeaver Version

Community Edition - Version 23.0.1.202303250535

### Operating System

macOS Ventura 13.1 (Intel)

### Steps to reproduce

1. Open the DBeaver;
2. Try to click or pointer over the toolbar button;
3. All toolbar disappeared;

**Comment by E1izabeth** [comment] 2023-04-05 14:48
Thank you for bug report. It's a duplicate of #19495
The fix will be available in the next release.

**Closed as not planned by E1izabeth** 2023-04-05 14:48 UTC
Labels: duplicate

**Comment by E1izabeth** [comment] 2023-04-08 11:19
Also you could try early access version https://dbeaver.com/files/ea/
