### ISSUE TITLE
ER Diagram: File Does Not Export

### ISSUE THREAD

**Issue by srtomy** [dbeaver/dbeaver#6929] opened 2019-10-07 11:52 UTC
#### System information: 
- Linux Mint 19.2
- DBeaver 6.2.0

#### Connection specification:
- PostgreSQL 11
- PostgreSQL JDBC Driver 

#### Describe the problem you're observing:
Export ER Diagram to Image
#### Steps to reproduce, if exist:
error in version 6.2.2, in version 6.2.0 error does not exist

#### Include any warning/errors/backtraces from the logs

![Untitled](https://user-images.githubusercontent.com/21697698/66309276-9b28bc80-e8df-11e9-8fd9-98950fa66f0a.png)

**Comment by serge-rider** [comment] 2019-10-07 17:19
Perhaps this issue is also caused by recent Eclipse 2019-09 migration. 
Ticket #6928 seems to be related. Probably we'll revert to previous Eclipse version.

**Comment by jernejkubuntu** [comment] 2019-10-08 06:41
6.2.1 worked fine for me
6.2.2  image coruped

Tried different formats:
- png: contain the same corrupt image
- bmp:contain the same corrupt image
- gif : fails to export. file size 0
 
Connection:
- PostgreSQL 11
- PostgreSQL JDBC Driver

**Comment by uslss** [comment] 2019-10-15 15:34
hi @srtomy , you could check if issue is fixed in EA version (https://dbeaver.io/files/ea/)

**Comment by srtomy** [comment] 2019-10-16 14:18
yes, the problem has been fixed 

thanks

**Closed** 2019-10-16 14:19 UTC
Labels: bug

**Comment by maggessi** [comment] 2019-10-21 20:25
hi, i have the same issue using the 6.2.3 of dbeaver, linux 64bits version.
