### ISSUE TITLE
Cannot connect to PostgreSQL Docker container with default JDBCPostgres driver

### ISSUE THREAD

**Issue by oniko94** [dbeaver/dbeaver#23352] opened 2024-04-08 11:46 UTC
### Description

Any attempt to create a new connection to the database residing in a docker container with an exposed port fails - even though connection from the console with psql works perfectly fine.

docker-compose.yml:
```
  postgresdb:
    image: postgres
    restart: always
    env_file: ./photopack_prizes/.env
    ports:
      - 54320:5432
    volumes:
      - ./db:/var/lib/postgres/data
```
Environmental variables:
```
POSTGRES_USER=postgres
POSTGRES_PASSWORD=p@$$w0rd1337
POSTGRES_DB=appdb
```
I managed to login successfully to the database in the console, with default `psql -h localhost -p 54320 -U postgres appdb` command, but DBeaver just fails with a cryptic error (I unfortunately do not know Java, so can't really debug and go through)

### Attempt №1: specify port, username, database name, password. Test connection - fail.
![image](https://github.com/dbeaver/dbeaver/assets/48897082/fad1f2fa-e56b-4b7f-baa4-6badec2ecd6a)
Stack trace: 
```
024-04-08 10:50:55.807 - Execution context opened (jdbc:postgresql://localhost:54320/appdb; Main <appdb>; 0)
2024-04-08 10:50:55.809 - Initiate connection to PostgreSQL database [appdb@localhost] for Main <appdb>
2024-04-08 10:50:55.832 - Invalid thread access
org.eclipse.swt.SWTException: Invalid thread access
        at org.eclipse.swt.SWT.error(SWT.java:4918)
        at org.eclipse.swt.SWT.error(SWT.java:4833)
        at org.eclipse.swt.SWT.error(SWT.java:4804)
        at org.eclipse.swt.widgets.Widget.error(Widget.java:565)
        at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:481)
        at org.eclipse.swt.custom.CLabel.setText(CLabel.java:934)
        at org.jkiss.dbeaver.ui.controls.StatusLineContributionItemEx.setText(StatusLineContributionItemEx.java:93)
        at org.jkiss.dbeaver.ui.app.standalone.ApplicationActionBarAdvisor.updateTimezoneItem(ApplicationActionBarAdvisor.java:354)
        at org.jkiss.dbeaver.ui.app.standalone.ApplicationActionBarAdvisor.lambda$0(ApplicationActionBarAdvisor.java:366)
        at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:47)
        at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:37)
        at org.jkiss.dbeaver.model.impl.preferences.BundlePreferenceStore.setValue(BundlePreferenceStore.java:255)
        at org.jkiss.dbeaver.registry.timezone.TimezoneRegistry.setDefaultZone(TimezoneRegistry.java:46)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:590)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:233)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:120)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:276)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:171)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:106)
        at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:115)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1366)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1243)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1033)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
        at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### Attempt №2: Specify the same parameters, do not click the "test connection" button and go straight to creating. Fail.

![image](https://github.com/dbeaver/dbeaver/assets/48897082/fe86903a-f51b-400a-a695-118de1c07b04)

Same error in the UI, a bit different stack trace:

```
2024-04-08 10:54:55.063 - Connect with 'appdb' (postgres-jdbc-18ebcaff540-699360df0a7605b9)
2024-04-08 10:54:55.063 - Execution context opened (appdb; Main <appdb>; 1)
2024-04-08 10:54:55.064 - Initiate connection to PostgreSQL database [appdb@localhost] for Main <appdb>
2024-04-08 10:54:55.065 - Invalid thread access
org.eclipse.swt.SWTException: Invalid thread access
        at org.eclipse.swt.SWT.error(SWT.java:4918)
        at org.eclipse.swt.SWT.error(SWT.java:4833)
        at org.eclipse.swt.SWT.error(SWT.java:4804)
        at org.eclipse.swt.widgets.Widget.error(Widget.java:565)
        at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:481)
        at org.eclipse.swt.custom.CLabel.setText(CLabel.java:934)
        at org.jkiss.dbeaver.ui.controls.StatusLineContributionItemEx.setText(StatusLineContributionItemEx.java:93)
        at org.jkiss.dbeaver.ui.app.standalone.ApplicationActionBarAdvisor.updateTimezoneItem(ApplicationActionBarAdvisor.java:354)
        at org.jkiss.dbeaver.ui.app.standalone.ApplicationActionBarAdvisor.lambda$0(ApplicationActionBarAdvisor.java:366)
        at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:47)
        at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:37)
        at org.jkiss.dbeaver.model.impl.preferences.BundlePreferenceStore.setValue(BundlePreferenceStore.java:255)
        at org.jkiss.dbeaver.registry.timezone.TimezoneRegistry.setDefaultZone(TimezoneRegistry.java:46)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:590)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:233)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:120)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:276)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:171)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:106)
        at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:115)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1366)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1243)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1033)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:117)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
        at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2505)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:89)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:73)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
 ```
 
All of the other attemps (trying to specify 0.0.0.0, 127.0.0.1, container IP address, container name etc) - fail in the same way.

Is it the issue of running in Docker or this is something specifically DBeaver-related?
 
 

### DBeaver Version

Community Edition 24.0.2

### Operating System

Arch Linux (6.8.4-arch1-1)

### Database and driver

1. PostgreSQL (postgresql, postgresql-libs): 16.2
2. JDBC PostgreSQL Driver: 47.2

### Steps to reproduce

1. Fire up a docker container with a postgresql database, either in docker compose, or by running `docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres`

2. Create a new connection to PostgreSQL database

3. Try to test connection; Expected -> success; Actual: error

4. Try to create connection without testing it and access it in the tree view later. Expected -> success; actual: error

### Additional context

Java version: OpenJDK Runtime Environment 22+36

_No response_

**Comment by skelmen** [comment] 2024-04-08 17:12
The same error on Ubuntu 22.04
JDBC PostgreSQL Driver: 47.2
Java version: openjdk 17

**Comment by oniko94** [comment] 2024-04-08 17:19
@skelmen judging by the stack trace, I doubt this is a driver-caused issue. It just doesn't appear anywhere along the lines. For some completely unexplicable reason I suspect `org.jkiss.dbeaver.registry.timezone.TimezoneRegistry.setDefaultZone(TimezoneRegistry.java:46)` to be the culprit - but, as I've said before, I'm a complete gonk at anything Java-related and have absolutely nothing but my intuition to back this claim up.

**Comment by skelmen** [comment] 2024-04-09 08:05
@oniko94 I've fixed the issue by downgrading dbeaver to version 22.3 and jdbc pg driver to 42.5.0

**Comment by oniko94** [comment] 2024-04-09 08:26
@skelmen thanks! will try downgrading as well

**Comment by E1izabeth** [comment] 2024-04-09 19:02
Thank you for bug report.

**Comment by E1izabeth** [comment] 2024-04-10 05:38
Similar reports
https://github.com/dbeaver/dbeaver/issues/19224#issuecomment-2044881242
https://github.com/dbeaver/dbeaver/issues/19224#issuecomment-2045482317
https://github.com/dbeaver/dbeaver/issues/19224#issuecomment-2045848505

**Comment by serge-rider** [comment] 2024-04-10 07:09
The issue was caused by workaround for legacy UA timezone support.
Fixed

**Comment by LonwoLonwo** [comment] 2024-04-10 09:48
Related: https://github.com/dbeaver/dbeaver/issues/18965

**Comment by serge-rider** [comment] 2024-04-10 15:49
Fixed. Fix will be included in version 24.0.3

**Closed as completed** 2024-04-10 15:49 UTC
Labels: xp:major, sp:2, xf:connection

**Comment by bugbenderx** [comment] 2024-04-11 13:53
I have the same error (Ubuntu 22.04 DBeaver 24.02) I'm a beginner what should I do, How can I decrease a version of DBeaaver or postgres driver or what should I do?

**Comment by E1izabeth** [comment] 2024-04-11 18:02
@k0dm you can download and install Early Access version https://dbeaver.io/files/ea/ or previous version https://dbeaver.io/files/

**Comment by MykolaRodin** [comment] 2024-04-15 14:25
I had this issue in `DBeaver Version 24.0.2.202404071654` under `Ubuntu 20.04` after the version update as well. Deleting the contents of `~/.local/share/DBeaverData/workspace6/.metadata/.plugins/` folder (like it is mentioned in `Manual Reset` section in https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings) fixed it for me.
