### ISSUE TITLE
java.lang.NoClassDefFoundError: org/postgis/binary/BinaryParser with column type geometry

### ISSUE THREAD

**Issue by UlrichKnaack** [dbeaver/dbeaver#9605] opened 2020-08-21 14:07 UTC
#### System information: 
- macOS Catalina 10.15.6
- DBeaver version 7.1.5.202008180601
- no extensions

#### Connection specification:
- PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit in Docker
- PostgreSQL JDBC Driver 42.2.5
- no proxies

#### Describe the problem you're observing:

I've inserted some rows with geometry data similar to https://dbeaver.com/docs/wiki/Working-with-Spatial-GIS-data/

In the table data view, a NoClassDefFoundError exception is shown.

<img width="861" alt="Bildschirmfoto 2020-08-21 um 14 29 45" src="https://user-images.githubusercontent.com/6562703/90899468-404d6600-e3c8-11ea-9561-07d9038dd74f.png">

The geometry can be viewed with Pgadmin 4.

When I try to export the rows with Dbeaver, same exception as above is thrown.

#### Include any warning/errors/backtraces from the logs

2020-08-21 14:28:38.303 - Connected (postgres-jdbc-1740c639508-edf9c4f60ab6335, PostgreSQL JDBC Driver [42.2.5])
2020-08-21 14:29:23.492 - Can't read column 'area' value
java.lang.NoClassDefFoundError: org/postgis/binary/BinaryParser
	at org.postgis.PGgeo.setValue(PGgeo.java:85)
	at org.postgresql.jdbc.PgConnection.getObject(PgConnection.java:574)
	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:2580)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:627)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.fetchColumnValue(PostgreGeometryValueHandler.java:53)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:202)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead$$Lambda$777/0000000000000000.run(Unknown Source)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4361)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

[dbeaver-debug.log.zip](https://github.com/dbeaver/dbeaver/files/5109230/dbeaver-debug.log.zip)

**Comment by UlrichKnaack** [comment] 2020-08-24 09:37
DDL (from PGAdmin 4)

CREATE TABLE public.area
(
    ident uuid NOT NULL,
    area geometry NOT NULL,
    customer_ident uuid,
    CONSTRAINT area_pkey PRIMARY KEY (ident),
    CONSTRAINT fkcnj24li129sjawfjoeba3hpb2 FOREIGN KEY (customer_ident)
        REFERENCES public.customer (ident) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.area
    OWNER to docker;

**Comment by serge-rider** [comment] 2020-09-11 09:11
Duplicate of #9616

**Closed by serge-rider** 2020-09-11 09:11 UTC
Labels: bug, duplicate, x:postgresql
