### ISSUE TITLE
Hive found results from temporary tables cannot be exported from the result set, indicating that tem_p tables cannot be found

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6371] opened 2019-07-29 13:03 UTC
![无标题](https://user-images.githubusercontent.com/26621087/62050668-45cb9180-b244-11e9-9d74-d7a009c711ba.png)
Hive found results from temporary tables cannot be exported from the result set, indicating that tem_p tables cannot be found

#### System information: 
- Operating system (distribution) and version win10 64bit 18945
- DBeaver version 6.1.3
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version  hadoop 2.6 hive1.10
[dbeaver_sql_20190729.log](https://github.com/dbeaver/dbeaver/files/3444768/dbeaver_sql_20190729.log)

- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

!SUBENTRY 1 org.jkiss.dbeaver.model 4 10001 2019-07-29 20:40:39.546
!MESSAGE Error while compiling statement: FAILED: SemanticException [Error 10001]: Line 4:1 Table not found 'temp_visit_01'

**Comment by serge-rider** [comment] 2019-08-29 12:57
Duplicate of #6637

**Closed by serge-rider** 2019-08-29 12:57 UTC
Labels: bug, duplicate
