### ISSUE TITLE
Column(s) could not be deleted.

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6667] opened 2019-09-02 18:23 UTC
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2 EA

#### Connection specification:
- Database name and version Mysql, Postgresql, Oracle

#### Describe the problem you're observing:
Column couldn't be deleted. Script is correct - column name appears instead of table name
![image](https://user-images.githubusercontent.com/31996417/64129925-d22f1e00-cdc7-11e9-9ea4-4650b8a029d4.png)

**Comment by serge-rider** [comment] 2019-09-02 18:24
Duplicate of #6662

**Closed** 2019-09-02 18:24 UTC
Labels: bug, duplicate, xp:major
