### ISSUE TITLE
DBeaver icons are missing in Version 23.0.1.202303250535

### ISSUE THREAD

**Issue by ykatyhoney** [dbeaver/dbeaver#19495] opened 2023-03-27 09:55 UTC
### Description

After upgrading the old version to `23.0.1.202303250535`, the icons are missing on the desktop app.

### DBeaver Version

Community edition 23.0.1.202303250535

### Operating System

macOS ventura 13.2.1

### Additional context

![image](https://user-images.githubusercontent.com/61254756/227908401-97285e44-078a-42ed-8255-3f9afeb0e457.png)
![image](https://user-images.githubusercontent.com/61254756/227908458-f5786ba4-4a51-4c6b-8a81-60e45597d32b.png)

**Comment by LonwoLonwo** [comment] 2023-03-27 11:13
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment] 2023-03-27 12:19
And you can try this resetting option: https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings#manual-reset

**Comment by LonwoLonwo** [comment] 2023-03-27 12:24
And you can try this resetting option: https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings#manual-reset

**Comment by ykatyhoney** [comment] 2023-03-27 15:01
> Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

[dbeaver-debug-1679911224234.log](https://github.com/dbeaver/dbeaver/files/11080091/dbeaver-debug-1679911224234.log)
[dbeaver-debug-1679911300669.log](https://github.com/dbeaver/dbeaver/files/11080092/dbeaver-debug-1679911300669.log)
[dbeaver-debug-1679929070022.log](https://github.com/dbeaver/dbeaver/files/11080093/dbeaver-debug-1679929070022.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/11080094/dbeaver-debug.log)

**Comment by ykatyhoney** [comment] 2023-03-27 15:07
> And you can try this resetting option: https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings#manual-reset

https://user-images.githubusercontent.com/61254756/227981697-8334cbec-73c9-4979-b965-4e0d2a2cdeae.mov

@LonwoLonwo It didn't help me out..

**Comment by mcapri** [comment] 2023-03-27 16:23
Hi,
I've the same problem after today update.
On every application startup, these icons goes away.
The only workaround that I've found is: after the startup and after the icons are gone, I open the Customize Perspective menu under Window menu, unselect/select the toolbars icons and then Apply and Close.
In this way seems that these icons stay on toolbar till the application closing.
Obviously is annoying, but for now is the only working way.
I've tried the manual reset that was suggested, but not worked for me.
I'm on Mac OS Big Sur 11.7.4 and DBeaver version is 23.0.1

**Comment by bitslayer42** [comment] 2023-03-29 15:48
I am having the same problem. When I reopen the application with no tables open, the icons are there. When I open a table, they go away. When I close the table they are still gone. Also, just mousing over the icons makes them go away.
Mac OS ventura 13.2.1 and DBeaver 23.0.1
mcapri's workaround works for me. After I do that, opening tables and mousing over the icons does not make them go away.

**Comment by serge-rider** [comment] 2023-03-30 09:43
Bug was caused by fix of https://github.com/dbeaver/dbeaver/issues/19416
Previous fix has been reverted

**Comment by Matvey16** [comment] 2023-04-05 08:16
Verified

**Closed as completed by Matvey16** 2023-04-05 08:16 UTC
Labels: xo:macos, sp:2, xf:ui
