### ISSUE TITLE
Unable to edit cells using inline editor

### ISSUE THREAD

**Issue by paulmccarthy** [dbeaver/dbeaver#5661] opened 2019-04-05 14:31 UTC
#### System information: 
- OS: Ubuntu 18.04.02 LTS (Linux cicero 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)
- DBeaver version: 6.0.1.2019032551040
- Java version: openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
- Additional extensions: None

#### Connection specification:
- Mysql 5.6.34-log
- Mysql JDBC driver provided in DBeaver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Open a table to view data. Double clicking a cell does not open the inline editor. Using the shortcut key [Enter] does not open the inline editor. When adding a new row to the table, the inline editor does not work. Only way to edit cells is right click cell -> Edit -> inline edit. Tabbing away from edited cell does not keep the inline editor open.

#### Steps to reproduce, if exist:
Connect to DB.
Open any table by double clicking.
Go to Data table.
Click Cell.
Double click -> no inline editor.

#### Include any warning/errors/backtraces from the logs

Relevant logs when double clicking cell:
2019-04-05 15:31:11.770 - Event loop exception
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1069)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:928)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:207)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1758)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1546)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:888)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetCellEditor.layout(SpreadsheetCellEditor.java:294)
	at org.eclipse.swt.custom.ControlEditor.setEditor(ControlEditor.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetCellEditor.setEditor(SpreadsheetCellEditor.java:265)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.Spreadsheet.showCellEditor(Spreadsheet.java:404)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.openValueEditor(SpreadsheetPresentation.java:965)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.Spreadsheet.handleEvent(Spreadsheet.java:292)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5663)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1386)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4472)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:184)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

**Comment by serge-rider** [comment] 2019-04-05 14:55
Duplicate of #5585. 
Please, try 6.0.2 EA version.

**Closed by serge-rider** 2019-04-05 14:55 UTC
Labels: bug, duplicate

**Comment by paulmccarthy** [comment] 2019-04-05 15:09
Thank you so much!
