### ISSUE TITLE
Ubuntu resultset regression

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#5680] opened 2019-04-08 11:05 UTC
#### System information: 
- Ubuntu 18.04
- DBeaver 6.0.2
- Java version: java-11-openjdk 
- Additional extensions: office

#### Connection specification:
- Database name and version: Postgres 9.6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Result-set and table data view mouse issues:

I cannot change column width using mouse.
I cannot select area. 
If I double click a cell, I cannot edit contents.

These problems appeared always after release, but the solution was to edit dbeaver.ini and add 
`--launcher.GTK_version

2`

This fix doesn't work anymore since 6.0.1

**Comment by serge-rider** [comment] 2019-04-08 15:16
Could you try to run `export GTK_IM_MODULE=ibus` before running DBeaver?

**Comment by alesc2000** [comment] 2019-04-08 15:40
You mean just to run it in the terminal? No change.

alex@y50:~$ export GTK_IM_MODULE=ibus
alex@y50:~$ dbeaver
Dbeaver:
The Dbeaver executable launcher no longer supports running with GTK + 2.x. Continuing using GTK+ 3.x.
WARNING: Using incubator modules: jdk.incubator.httpclient
2019-04-08 18:33:37.206 - Create display
2019-04-08 18:33:37.470 - > Start org.jkiss.dbeaver.core [6.0.2.201904071344]
2019-04-08 18:33:37.475 - DBeaver 6.0.2.201904071344 is starting
2019-04-08 18:33:37.476 - OS: Linux 4.15.0-47-generic (amd64)
2019-04-08 18:33:37.476 - Java version: 10.0.2 by Oracle Corporation (64bit)
2019-04-08 18:33:37.476 - Install path: '/usr/share/dbeaver'
2019-04-08 18:33:37.476 - Instance path: 'file:/home/alex/.dbeaver4/'
2019-04-08 18:33:37.476 - Memory available 77Mb/1024Mb
2019-04-08 18:33:37.492 - Starting RMI server at 34114
2019-04-08 18:33:37.553 - Run workbench
2019-04-08 18:33:37.561 - > Start org.eclipse.e4.ui.workbench.swt [0.14.500.v20190214-0851]
2019-04-08 18:33:37.561 - > Start org.eclipse.e4.core.services [2.1.400.v20181215-2145]
2019-04-08 18:33:37.562 - > Start org.eclipse.e4.core.contexts [1.8.0.v20190214-1713]
2019-04-08 18:33:37.569 - > Start org.eclipse.e4.ui.services [1.3.400.v20190212-2214]
2019-04-08 18:33:37.602 - > Start org.eclipse.e4.ui.di [1.2.500.v20190214-1316]
2019-04-08 18:33:37.638 - > Start org.eclipse.emf.common [2.15.0.v20181220-0846]
2019-04-08 18:33:37.664 - > Start org.eclipse.emf.ecore [2.17.0.v20190116-0940]
2019-04-08 18:33:37.729 - > Start org.eclipse.emf.ecore.xmi [2.15.0.v20180706-1146]
2019-04-08 18:33:37.931 - > Start org.eclipse.core.filesystem [1.7.300.v20190218-2054]
2019-04-08 18:33:37.968 - > Start org.eclipse.core.resources [3.13.300.v20190218-2054]
2019-04-08 18:33:38.209 - > Start org.eclipse.e4.ui.workbench.addons.swt [1.3.400.v20190224-1542]
2019-04-08 18:33:38.224 - > Start org.eclipse.core.expressions [3.6.300.v20190218-1215]
2019-04-08 18:33:38.243 - > Start org.eclipse.e4.ui.workbench.renderers.swt [0.14.500.v20190220-1002]
2019-04-08 18:33:38.367 - > Start org.eclipse.e4.ui.bindings [0.12.400.v20190131-1604]
2019-04-08 18:33:38.438 - > Start org.eclipse.e4.core.di.extensions [0.15.300.v20190213-1308]
2019-04-08 18:33:38.717 - > Start org.eclipse.e4.ui.css.swt [0.13.400.v20190223-1254]
2019-04-08 18:33:38.807 - > Start org.eclipse.e4.ui.css.swt.theme [0.12.200.v20190212-2214]
2019-04-08 18:33:39.162 - Initializing DBeaver 6.0.2
2019-04-08 18:33:39.163 - Host plugin: org.jkiss.dbeaver.core.application 6.0.2.201904071344
2019-04-08 18:33:39.163 - Initialize Core...
2019-04-08 18:33:39.174 - Can't find BC security provider. Use default JCE.
2019-04-08 18:33:39.174 - BouncyCastle not registered, using the default JCE provider
2019-04-08 18:33:39.176 - > Start org.jkiss.dbeaver.registry [1.0.0.201904071344]
2019-04-08 18:33:39.245 - > Start org.eclipse.team.core [3.8.500.v20190216-2155]
2019-04-08 18:33:39.259 - > Start org.jkiss.dbeaver.ui.navigator [1.0.6.201904071344]
2019-04-08 18:33:39.360 - Datasource provider 'wmi' not found. Bad provider description.
2019-04-08 18:33:39.367 - Total database drivers: 72 (72)
2019-04-08 18:33:39.408 - > Start org.eclipse.equinox.security [1.3.100.v20190215-2139]
2019-04-08 18:33:39.424 - > Start org.eclipse.ui.net [1.3.300.v20180827-1041]
2019-04-08 18:33:39.426 - > Start org.eclipse.core.net [1.3.400.v20181030-1645]
2019-04-08 18:33:39.427 - Proxy service 'org.eclipse.core.net.proxy.IProxyService' loaded
2019-04-08 18:33:39.432 - Core initialized (269ms)
2019-04-08 18:33:39.433 - Configure workbench window
2019-04-08 18:33:39.445 - > Start org.eclipse.help [3.8.300.v20190216-1017]
2019-04-08 18:33:39.790 - Create actions
2019-04-08 18:33:39.791 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2019-04-08 18:33:39.792 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2019-04-08 18:33:39.878 - > Start org.eclipse.ui.editors [3.11.400.v20190218-1547]
2019-04-08 18:33:39.882 - > Start org.eclipse.core.filebuffers [3.6.500.v20190218-1547]

(DBeaver:11728): Gdk-WARNING **: 18:33:40.134: Couldn't map window 0x7f310652e020 as subsurface because its parent is not mapped.
2019-04-08 18:33:40.373 - > Start org.eclipse.search [3.11.500.v20190218-2126]
2019-04-08 18:33:40.416 - > Start org.eclipse.ui.workbench.texteditor [3.11.300.v20190218-2126]
2019-04-08 18:33:40.465 - Initialize workbench window
2019-04-08 18:33:40.474 - Finish initialization

**Comment by serge-rider** [comment] 2019-04-08 19:53
That's too bad.
Unfortunately you can't switch to GTK2 anymore (because new version of Eclipse platform doesn't support it - https://www.eclipse.org/eclipse/news/4.10/platform.php#gtk2-removal)

Most likely these issues are caused by outdated Gnome (or some other related libs) on Ubuntu 14. Not sure what we can do..

**Comment by alesc2000** [comment] 2019-04-22 13:05
Upgraded to Ubuntu 19:04 and still have the problem.

**Comment by alesc2000** [comment] 2019-05-03 19:19
Maybe this Eclipse bug fix solves my problem?
https://bugs.eclipse.org/bugs/show_bug.cgi?id=544498

**Comment by serge-rider** [comment] 2019-05-13 16:40
@alesc2000 Maybe. We'll know this for sure after 2019.06 will be released.

**Comment by uslss** [comment] 2019-10-17 14:43
hi @alesc2000 , is issue still actual for you?

**Comment by uslss** [comment] 2019-12-26 11:03
there is no update on ticket for a long time.
ticket closed

**Closed by uslss** 2019-12-26 11:03 UTC
Labels: question, xo:linux
