### ISSUE TITLE
Error downloading driver libraries (connecting to Exasol BI)

### ISSUE THREAD

**Issue by melissagile** [dbeaver/dbeaver#18637] opened 2023-01-02 15:38 UTC
### Description

Hi,
I am receiving an error when I try to test the connection DBeaver to Exasol BI. I get the following Resolve driver files error:

```
Error downloading driver libraries

Reason:
Error resolving dependencies
--------------------------------------------
Error resolving dependencies
  Maven artifact 'maven:/com.exasol:exasol-jdbc:RELEASE' not found
```

When I go to Driver Settings and attempt to download the driver, the following connection error for occurs:

```
com.exasol.jdbc.EXADriver
--------------------------------------------
Can't create driver instance
  Error creating driver 'Exasol' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.exasol.jdbc.EXADriver'
  Error creating driver 'Exasol' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.
```

I've tried troubleshooting with some other driver threads from the internet, but no dice. 
Anyone have a solution? 
Thanks in advance! 

### DBeaver Version

Version 22.3.1.202212251901

### Operating System

MacOS Ventura Version 13.01

### Additional context

Libraries available:
1. Apache Version 2.0
2. Maven Artifact ID exasol-jdbc / Group ID com.exasol / Version 7.0.11 / Fallback Version RELEASE

**Comment by LonwoLonwo** [comment] 2023-01-02 18:01
Hello. Thanks for the bug report.
This is a duplicate of https://github.com/dbeaver/dbeaver/issues/18556
You can find a workaround there.

**Closed as not planned by LonwoLonwo** 2023-01-02 18:01 UTC
Labels: duplicate, x:exasol
