### ISSUE TITLE
Postgres permission error: Can't detect root node for objects tree

### ISSUE THREAD

**Issue by Lkledu** [dbeaver/dbeaver#14711] opened 2021-11-27 18:42 UTC
#### System information: 
- Operating system (distribution) and version
   `Windows10 Pro`
- DBeaver version
   `21.2.5.202111180314`
- Additional extensions
  Docker version: `20.10.10`
  Debian container `14.1-1.pgdg110+1`
- Drivers
  org.postgresql:postgresql:RELEASE [42.2.20]
  net.postgis:postgis-jdbc:RELEASE [2.5.0]
  net.postgis:postgis-geometry:RELEASE [2.5.0]

#### Connection specification:
- Database name and version
   Postgres `14.1`

#### Describe the problem you're observing:
I'm running postgres db from a docker container. When i goes to Permission screen of a table it popups a error saying: Can't detect root node for objects tree.

#### Steps to reproduce, if exist:
- install postgres in docker with `docker pull postgres`
- create network `docker network create --driver bridge postgres-network`
- run docker image `docker run --name teste-postgres --network=postgres-network -e "POSTGRES_PASSWORD=Postgres" -p 5432:5432 -v C:/PostgreSQL:/var/lib/postgresql/data -d postgres`

#### Include any warning/errors/backtraces from the logs
![Captura de Tela (13)](https://user-images.githubusercontent.com/38146538/143717302-b9a2572e-0f3a-4e81-b7e2-f2f162998b18.png)

**Comment by Lkledu** [comment] 2021-11-28 01:50
I was using intelliJ community, i switch to eclipse and it's work. (maybe the way that i build/run it was triggering the bug)

**Comment by ShadelessFox** [comment] 2021-11-28 02:40
Hello @Lkledu,

Please make sure you're on `devel` branch and it is up to date.

**Comment by Lkledu** [comment] 2021-11-28 05:02
Thanks @ShadelessFox i was in `master` branch. When I tried to change branch, git show the error `error: pathspec 'devel' did not match any file(s) known to git` . I was following the [https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA](https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA) guide

**Comment by ShadelessFox** [comment] 2021-11-28 11:06
`master` branch is outdated (at least in dbeaver repository). 

Are you sure you're inside `dbeaver` directory (where dbeaver was cloned) while performing `git checkout devel`?

**Comment by uslss** [comment] 2021-12-06 11:59
the issue is already fixed in 21.3.0 in the scope of #12071

**Closed as completed by uslss** 2021-12-06 11:59 UTC
Labels: x:postgresql, can't reproduce, development
