### ISSUE TITLE
Changing column types via drop/create table does not refresh type in Results Pane.

### ISSUE THREAD

**Issue by cdabel** [dbeaver/dbeaver#18993] opened 2023-02-07 17:04 UTC
### Description

The issue is that while writing ETL and changing the schema below, and after having changed the `shape` column to `varchar(10000)` and then back to `geometry` type (using `drop table` and re-`create table` statements), after loading the data and querying it, the Results pane shows the value as VARCHAR type still and the geometry value doesn't render as a map in the Value Panel. It only corrected after refreshing the table in the Database Navigator.

Here is an example CSV:
[redacted]

### DBeaver Version

Community Edition 22.3.2

### Operating System

macOS Monterey

### Database and driver

1. Aurora MySQL (MariaDB connection)
2. Driver Type: MySQL
    - MariaDB JDBC driver:  org.mariadb.jdbc:mariadb-java-client:RELEASE
    - Version: 3.0.7
3. DBeaver version:  22.3.2 (community)

### Steps to reproduce

0. Connect to Aurora MySQL database, have a comma separated CSV file in an S3 location. I've attached the CSV file example to this Issue.

1. 
CREATE TABLE loading.building_raw_testing
(
    building_id        VARCHAR(30)
  , area_sqft            DOUBLE
  , shape                GEOMETRY NOT NULL
  , SPATIAL INDEX (shape)
);

2. 
LOAD DATA
FROM S3 PREFIX 's3://<some_bucket>/Buildings.csv'
INTO TABLE loading.building_raw_testing
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
    building_lid       
  , area_sqft
  , @shape
)
SET 
    shape = ST_GEOMFROMTEXT(@shape, 4326)
; 

3. Change the `shape` column to `varchar(10000)` using `drop table` statement and `create table` to recreate the table. 
4. Load the data again.
5. Note the data type of the `shape` column values in the Results pane is VARCHAR.
6. Change the `shape` column back to `GEOMETRY` using `drop table` statement and `create table` to recreate the table. 
7. Load the data and query it, note that the Results pane shows the value as VARCHAR type still and the geometry value doesn't render as a geographical map in the Value Panel. 
8. Note that It only corrects itself after refreshing the table in the Database Navigator.

### Additional context

I am using StrongDM software, which simulates connecting to remote server/ports as `localhost:<port>`.

**Comment by cdabel** [comment] 2023-02-07 17:13
I feel like this is a bug because I wasted a lot of time under the assumption that I was doing something wrong in my DDL/ETL script. I would expect the data type to pull both the column type and the value fresh, rather than relying on any metadata cache for the data type.

**Comment by E1izabeth** [comment] 2023-02-16 14:17
Thank you for the idea. We do not automatically refresh metadata, but we have already got the issues connected to that.
Closing as a duplicate of #7924 #16219

**Comment by E1izabeth** [comment] 2023-02-16 14:17
You need to manually press F5 on navigator node (scheme or database).

**Closed as not planned by E1izabeth** 2023-02-16 14:17 UTC
Labels: duplicate, xf:metadata
