### ISSUE TITLE
"-con" command line argument broken

### ISSUE THREAD

**Issue by the8tre** [dbeaver/dbeaver#14304] opened 2021-10-20 08:17 UTC
#### System information: 
- Operating system (distribution) and version: `Window 10 20H2` and `Ubuntu 20.04`

- DBeaver version: `21.2.3.202110151816`

#### Description
When launching dbeaver (dbeaver, dbeaver.exe, dbeaver-cli.exe) using the "**-con**" command line argument the app exits with the following message:
`Can't connect to running instance, exiting`
This used to work up to version 21.2.2

#### Steps to reproduce:
Launch dbeaver or dbeaver-cli.exe with the following arguments:
`dbeaver-cli.exe  -con "name=Cmd Line testing|create=false|driver=postgresql|host=localhost|port=5432|database=postgres|user=postgres|password=Password1"`

#### Logs
Full application output:
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 21.2.3.202110151816]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.4.100.v20210506-1050]
2021-10-20 10:02:45.665 - Can't connect to running instance, exiting
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.12.0.v20210723-1034]
Commands processed. Exit DBeaver.

Log file found in `<install-path>/configuration`:
[1634717591204.log](https://github.com/dbeaver/dbeaver/files/7379338/1634717591204.log)

**Comment by uslss** [comment] 2021-10-20 08:34
thanks for the report

**Comment by uslss** [comment] 2021-10-20 08:40
closed as a duplicate of #14284

**Closed as completed by uslss** 2021-10-20 08:40 UTC
Labels: duplicate, xf:cli
