### ISSUE TITLE
DuckDB geometry display

### ISSUE THREAD

**Issue by hackenspp** [dbeaver/dbeaver#20236] opened 2023-06-08 14:34 UTC
### Description

The display of geometries is buggy:
```
install spatial;
load spatial;
select st_point(0, 0);
```
displays: 
```
java.lang.ClassCastException: class java.nio.DirectByteBuffer cannot be cast to class java.lang.String (java.nio.DirectByteBuffer and java.lang.String are in module java.base of loader 'bootstrap')
	at org.duckdb.DuckDBVector.getLazyString(DuckDBVector.java:211)
	at org.duckdb.DuckDBVector.getObject(DuckDBVector.java:110)
	at org.duckdb.DuckDBResultSet.getObject(DuckDBResultSet.java:161)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getAttributeValue(JDBCResultSetImpl.java:147)
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.fetchValueObject(DefaultValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:828)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3895)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```
And the display value (F7) doesn't show anything

### DBeaver Version

Community edition Version 23.1.0

### Operating System

Windows 11

### Database and driver

DuckDB

**Comment by LonwoLonwo** [comment] 2023-06-08 15:11
Hello @hackenspp 

What DuckDB database server and version do you use?

**Comment by hackenspp** [comment] 2023-06-08 15:24
v0.8.0

**Comment by iraidaa** [comment] 2023-06-22 09:16
Hi @hackenspp,

We reproduce this issue in DBeaver CE 23.1.0 with DuckDB JDBC driver 0.8.0 and 0.8.1. 

Could you please create a new issue on the DuckDB GitHub board https://github.com/duckdb/duckdb/issues? We think that it is a problem on the side of the driver.


![image](https://github.com/dbeaver/dbeaver/assets/49681450/aa8be53d-7e3a-4484-bb76-976fc00f743c)


```
java.lang.ClassCastException: class java.nio.DirectByteBuffer cannot be cast to class java.lang.String (java.nio.DirectByteBuffer and java.lang.String are in module java.base of loader 'bootstrap')
	at org.duckdb.DuckDBVector.getLazyString(DuckDBVector.java:211)
	at org.duckdb.DuckDBVector.getObject(DuckDBVector.java:110)
	at org.duckdb.DuckDBResultSet.getObject(DuckDBResultSet.java:161)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getAttributeValue(JDBCResultSetImpl.java:147)
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.fetchValueObject(DefaultValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:828)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3895)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by francbartoli** [comment] 2023-07-08 09:30
I can confirm the issue with version `0.8.1` of the driver

**Comment by LonwoLonwo** [comment] 2023-08-03 11:34
https://github.com/duckdb/duckdb/issues/8456 external ticket created

**Comment by LonwoLonwo** [comment] 2023-09-28 06:15
Fixed in the last driver version (0.9)

![2023-09-28 09_14_00-DBeaver Ultimate 23 2 1 - _duck_090 db_ Script-144](https://github.com/dbeaver/dbeaver/assets/45152336/0b36bdd2-56fd-4c92-ae68-cc9dd3e82c37)

**Closed as completed by LonwoLonwo** 2023-09-28 06:15 UTC
Labels: xf:data, xf:gis, third party issue, x:duckdb

**Comment by idantene** [comment] 2023-12-15 08:13
Follow-up question - the displayed value is now just a text, whereas in postgres DB one would get a preview of the geometry (see photos below). I'm not sure if this is a DBeaver issue, a driver issue, or just a settings overview... Should this be made into a different ticket (here and/or in duckdb repo)?
![image](https://github.com/dbeaver/dbeaver/assets/12184618/fdf09406-901d-4845-9f26-048ca0be4d36)
![image](https://github.com/dbeaver/dbeaver/assets/12184618/36116797-6275-404d-88d2-41d242a8870f)

**Comment by LonwoLonwo** [comment] 2023-12-15 14:17
Hello @idantene 

Please try to follow these instructions: https://github.com/dbeaver/dbeaver/wiki/Working-with-Spatial-GIS-data#viewing-string-or-binary-data-from-any-database-on-a-map

**Comment by idantene** [comment] 2023-12-18 10:23
Hey @LonwoLonwo,

Thanks for the tip! It was a good guess (and cool feature to learn!), but it does not seem to apply in this case --
<img width="1084" alt="image" src="https://github.com/dbeaver/dbeaver/assets/12184618/7b15985e-5c87-4abe-ac9a-90ac9b348a81">

**Comment by LonwoLonwo** [comment] 2023-12-18 11:14
That's because the data type is not string in your case here. You can try to cast it to any string type or use my workaround from this discussion: https://github.com/orgs/dbeaver/discussions/21491#discussioncomment-7259972

**Comment by AliHmaou** [comment] 2024-03-04 11:03
Thanks for the workaround @LonwoLonwo, but maybe we should open a new issue to have DBeaver showing spatial data seamlessly like it does with postgres ?

**Comment by LonwoLonwo** [comment] 2024-03-04 12:32
Yes, @AliHmaou, that's an excellent idea. Please create it.

**Comment by AliHmaou** [comment] 2024-03-04 18:54
Here it is : #23049

**Comment by AliHmaou** [comment] 2024-03-05 22:38
@idantene @LonwoLonwo 

What about liking the feature request #23049 ?
