### ISSUE TITLE
It's not working to set Home as the shortcut of "Line Start"

### ISSUE THREAD

**Issue by glacjay** [dbeaver/dbeaver#20504] opened 2023-07-07 09:08 UTC
### Description

<img width="927" alt="image" src="https://github.com/dbeaver/dbeaver/assets/292719/14936cb9-765e-405f-98e1-18aba25ac15a">

It's working for a while just after launch DBeaver every time, but not any more after some time. Then, press Home key will bring me to the start of the document. Command+← is always working.

No time for detailed testing.

### DBeaver Version

Community Edition 23.1.1.202306251800

### Operating System

macOS Ventura 13.4.1 (22F82)

**Comment by flambchap** [comment] 2023-07-13 13:08
Duplicate of https://github.com/dbeaver/dbeaver/issues/9414.

**Closed as not planned by flambchap** 2023-07-13 13:08 UTC
Labels: xo:macos
