### ISSUE TITLE
24.0.3 - Execute as script not working correctly

### ISSUE THREAD

**Issue by gplaza-alny** [dbeaver/dbeaver#29312] opened 2024-05-02 14:08 UTC
### Description

Execute as script (ALT+X) is now working correctly with some statements in the new version. Example below - if the 2nd line is commented out, it works. With the 2nd statement I get an error:
SQL Error [8] [0A000]: Actual statement count 2 did not match the desired statement count 1.
  Actual statement count 2 did not match the desired statement count 1.
  Actual statement count 2 did not match the desired statement count 1.

If each statement is run independently, all work.
I've seen it happen with other combination of statements (ie: this is not a "use warehouse" specific issue).

### DBeaver Version

Community Edition 24.0.3

### Operating System

Windows 10 Enterprise

### Database and driver

Snowflake (net.snowflake:snowflake-jdbc:RELEASE [3.14.4])

### Steps to reproduce

use role accountadmin;
use warehouse compute_wh;
select current_timestamp();
select current_user();

**Comment by E1izabeth** [comment] 2024-05-02 14:13
Duplicate of #26416
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Closed as not planned by E1izabeth** 2024-05-02 14:13 UTC
Labels: duplicate, xf:sql execution
