### ISSUE TITLE
WMS servers for geometry viewer?

### ISSUE THREAD

**Issue by apiszcz** [dbeaver/dbeaver#10531] opened 2020-11-27 19:58 UTC
The geometry viewer and WMS server feature is great.
Is it possible for one to configure their own WMS server endpoint?
Thank you.

**Comment by mkgrgis** [comment] 2020-11-28 11:57
Now the list of WMS servers is not configurable, but You can see https://github.com/dbeaver/dbeaver/blob/3d33e9456b66aac8f8db0625cb49886b33044eec/plugins/org.jkiss.dbeaver.data.gis.view/plugin.xml and customize for Your WMS data source. If there is nice public WMS, You are welcome with pull request.

**Comment by kseniiaguzeeva** [comment] 2020-12-03 13:01
Thank you for the suggestion

**Comment by flambchap** [comment] 2021-01-27 14:47
Duplicate of #10573. Will be done soon.

**Closed by flambchap** 2021-01-27 14:47 UTC
Labels: feature request, xf:gis
