### ISSUE TITLE
Database Navigator (7.2.5) Postgres 12 Not all partition displayed

### ISSUE THREAD

**Issue by PeterAlva** [dbeaver/dbeaver#10466] opened 2020-11-23 14:23 UTC
#### System information: 
- Windows 10 64 bit v1909
- DBeaver version 7.2.5
- Java version 11 -1.8.0_251

#### Connection specification:
- Postgres 12.3
- Driver name org.postgresql.Driver (jdbc)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

We have tables that were partitioned by month (range partition), as of the 06/2020 the monthly partitions were replaced by monthly partitions that were then sub partitioned by day (range).

In prior versions of DBeaver these would be displayed in the navigator whereas now only the partitions up to the monthly parititions before the new sub-partitions were added -i.e. up to and including 05/2020

EXPLAIN query shows the partitions do exist and they are displayed in other IDEs such as Datagrip

#### Include any warning/errors/backtraces from the logs
None relevant

**Comment by serge-rider** [comment] 2020-11-23 21:12
Seems to be duplicate of #10426

**Closed by serge-rider** 2020-11-23 21:12 UTC
Labels: bug, duplicate, x:postgresql

**Comment by PeterAlva** [comment] 2020-11-23 21:14
Thank you very much, I did try to find others. I’ll check the link.

p.

**Comment by PeterAlva** [comment] 2020-11-23 21:16
Missed the (not inheritance) bit. Sorry
