### ISSUE TITLE
DBeaver: Changing selected database in Database Navigator makes DBeaver loose information on what database is active

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4914] opened 2019-01-04 14:12 UTC
DBeaver - **Version 5.3.2 CE**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

_DBeave_ does not keep information on what database is active when I click on another database in the **Database Navigator**.

**o** Start _DBeaver_ and choose **Connect** to a database server.

**o** Right click on a database and choose **Set active** _(Ctrl+Shift+A)_ in the contex menu.

**o** Choose the **Navigate** -> **Open Database Object** _(Ctrl+Shift+D)_ in the menu.

**o** Search for a table name that is available in the active database.

**o** The table name pops up in the **Mathing items** list. This is **OK**.

**o** Just click in the **Database Navigator** on another database (**don't make it active**).

**o** Choose the **Navigate** -> **Open Database Object** _(Ctrl+Shift+D)_ in the menu.

**o** Search for the same table name that you searched for before in the database.

**o** When using the **PostgreSQL** driver:
>  An error is shown - **No active datasource**.

**o** When using the **new Microsoft driver**
> No table name pops up in the **Matching items** list.

My guess is that the information of active database is overwritten when I move around in the **Database Navigator**. Feels like this is a bug.

I think the easiest way would be for issue #4914 (this issue) and #4915 that both the **Open Database Object** and the **Assistant/Completion** (manual/automatic) only looked in the active database and always looked in all schemas. No matter what I click on in the **Database Navigator**. 

Only difference is that:
**o** The **Open Database Object** get the active database from the **Database Navigator**.
**o** The **SQL Editor** get the active database from its own **Active catalog/schema** combo box.

Why make things more complicated than they have to be.

**Comment by serge-rider** [comment] 2019-01-10 15:25
I can't reproduce this anymore. Perhaps this issue was fixed in one of recent GoTo object fixes.
Could you check how it works in EA version?

**Comment by pdanie** [comment] 2019-01-10 16:05
I have now tried the EA from **10-Jan-2019 15:15**.

**o** Seems the **PosgreSQL** works **OK**.
**o** The **New Microsoft Driver** connection is still **BROKEN** and work as explained above.

I will test further with and also try the behaviour in **5.3.2** to see if there has been a shift in behavior.

Can you repeat the faulty behaviour with the **new Microsoft Driver** ?

**Comment by serge-rider** [comment] 2019-01-10 16:12
No, I can't. Perhaps I'm doing something wrong.
Could you post a short video (e.g. Screen2Gif)?

**Comment by pdanie** [comment] 2019-01-10 16:55
I have now tried the EA from **10-Jan-2019 15:15**.

**o** Seems the **PostgreSQL** works **OK**.
**o** The **New Microsoft Driver** fails 100% and is still **BROKEN** in the way described in the issue above.

I include a MP4 video where you can see the effect:

[DBeaver_5.3.3B_170110.zip](https://github.com/dbeaver/dbeaver/files/2746312/DBeaver_5.3.3B_170110.zip)

**Comment by serge-rider** [comment] 2019-01-10 17:09
Well, for me it looks correct. "Open Database object" first searches in currently selected database node (database, catalog or schema). It searches in active database only if nothing is selected or it is impossible to detect a selection.

This behavior is the same for all databases.

**Comment by pdanie** [comment] 2019-01-10 17:17
Try the same with a **PostgreSQL** database (I have tried with the same EA from 10-Jan-2019 15:15) .

You will notice that the lookup database stays put with the **Active** database. I would say that this behaviour with **PostgreSQL** is better. Ie. only look for dataelements in the active database.

Or what do you think ?

**Comment by pdanie** [comment] 2019-01-10 17:30
I have also make #4915 issue, where you get what I feel the same misbehaviour when you click on different MS SQL schema (like 'sys', 'mydbschema', etc).

Here the **Open Database Object** can't find my database elements if I click on for instanse the "sys" database schema...

**NOTE**: There is here a difference between the **Open Database Object** _(Ctrl+Shift+D)_ behaviour and the
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Assistant/Completion** in a **SQL Editor**. The latter is able to locate a table in the "dbo" schema
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;even if I in the **Database Manager** click once on the "sys" schema.

**Closed** 2020-04-21 10:22 UTC
Labels: question
