### ISSUE TITLE
Doesn't open on Wayland without XWayland

### ISSUE THREAD

**Issue by Axolite15** [dbeaver/dbeaver#35111] opened 2024-08-07 12:53 UTC
### Description

When trying to run dbeaver version 24.1.3 on Wayland without XWayland, the application fails to open beyond the loading screen. The previous version of dbeaver (24.1.2) works perfectly on pure Wayland. So the issue lies within this revision. Installed both from official Arch repository.

Logs:
```
WARNING: Using incubator modules: jdk.incubator.vector

> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.15.300.v20240418-0734]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.4.300.v20240419-2334]
> Start DBeaver Application Standalone [org.jkiss.dbeaver.ui.app.standalone 24.1.3.202407282257]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.5.400.v20240416-0658]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.22.200.v20240524-2010]
> Start jna [com.sun.jna 5.14.0.v20231211-1200]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.150.202407282257]
> Start Expression Language [org.eclipse.core.expressions 3.9.400.v20240413-1529]
> Start DBeaver Usage Statistics [org.jkiss.dbeaver.ui.statistics 1.0.31.202407282257]
> Start DBeaver Desktop Application Core [org.jkiss.dbeaver.core 24.1.3.202407282257]
2024-08-07 18:10:31.845 - DBeaver 24.1.3.202407282257 is starting
2024-08-07 18:10:31.846 - OS: Linux 6.10.3-arch1-2 (amd64)
2024-08-07 18:10:31.846 - Java version: 22.0.2 by Arch Linux (64bit)
2024-08-07 18:10:31.847 - Install path: '/usr/lib/dbeaver'
2024-08-07 18:10:31.847 - Instance path: 'file:/home/USER/.local/share/DBeaverData/workspace6/'
2024-08-07 18:10:31.849 - Memory available 65Mb/1024Mb
2024-08-07 18:10:31.862 - Create display
2024-08-07 18:10:31.958 - Initialize desktop platform...
2024-08-07 18:10:32.089 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.10.400.v20240426-1040]
> Start Core Resource Management [org.eclipse.core.resources 3.20.200.v20240513-1323]
> Start Team Support Core [org.eclipse.team.core 3.10.400.v20240413-1529]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.135.202407282257]
2024-08-07 18:10:32.239 - Initialize base platform...
2024-08-07 18:10:32.261 - Platform initialized (302ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.135.202407282257]
2024-08-07 18:10:32.281 - Starting instance server at http://localhost:37391
2024-08-07 18:10:32.288 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.17.400.v20240425-0840]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.4.400.v20240413-1529]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.6.300.v20231201-1637]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.4.400.v20240424-0956]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.14.400.v20240321-1245]
> Start Eclipse e4 core commands [org.eclipse.e4.core.commands 1.1.400.v20240424-0444]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.37.0.v20231208-1346]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.14.400.v20240424-0956]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.5.400.v20240416-0658]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.16.400.v20240418-1547]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.18.300.v20240413-1529]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.15.400.v20240321-1245]
> Start Default Text Editor [org.eclipse.ui.editors 3.17.300.v20240524-2010]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.17.400.v20240524-2010]
2024-08-07 18:10:33.612 - Configure workbench window
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.125.202407282257]
2024-08-07 18:10:33.709 - Total database drivers: 117 (117)
> Start Help System Core [org.eclipse.help 3.10.400.v20240415-0528]
2024-08-07 18:10:33.779 - Create actions
2024-08-07 18:10:33.784 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2024-08-07 18:10:33.785 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2024-08-07 18:10:33.785 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2024-08-07 18:10:33.785 - Create workbench actions
2024-08-07 18:10:34.085 - Initialize workbench window
2024-08-07 18:10:34.090 - Finish initialization
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.135.202407282257]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.135.202407282257]
> Start DBeaver SQL Terminal [org.jkiss.dbeaver.ui.editors.sql.terminal 1.0.111.202407282257]

(DBeaver:49893): Gtk-WARNING **: 18:10:34.265: Negative content height -7 (allocation 6, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

(DBeaver:49893): Gtk-WARNING **: 18:10:34.272: Negative content height -7 (allocation 6, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
> Start Core Compare Support [org.eclipse.compare.core 3.8.500.v20240524-2010]

(DBeaver:49893): Gtk-WARNING **: 18:10:34.461: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
> Start Internet Connection Management UI [org.eclipse.ui.net 1.5.400.v20240413-1529]
> Start Internet Connection Management [org.eclipse.core.net 1.5.400.v20240413-1529]
2024-08-07 18:10:34.659 - Internal error in workbench lifecycle
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/java.awt.Desktop.getDesktop(Unknown Source)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchAdvisor.postStartup(ApplicationWorkbenchAdvisor.java:270)
	at org.eclipse.ui.internal.Workbench.lambda$17(Workbench.java:2813)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1108)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:291)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
2024-08-07 18:10:34.660 - DBeaver is stopping
2024-08-07 18:10:34.661 - Stop instance server
2024-08-07 18:10:35.664 - Instance server has been stopped
2024-08-07 18:10:35.677 - DBeaver shutdown completed
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.172.202407282257]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.141.202407282257]
> Start GEF Classic Draw2d [org.eclipse.draw2d 3.16.0.202405290843]
> Start GEF Classic GEF (MVC) [org.eclipse.gef 3.18.0.202405290843]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.95.202407282257]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.95.202407282257]
> Start DBeaver Dashboard UI [org.jkiss.dbeaver.ui.dashboard 1.0.132.202407282257]
> Start DBeaver Dashboards Model [org.jkiss.dbeaver.model.dashboard 1.0.8.202407282257]
> Start DBeaver UI Editors - Connections [org.jkiss.dbeaver.ui.editors.connection 1.0.126.202407282257]

(DBeaver:49893): Gdk-CRITICAL **: 18:10:36.018: gdk_threads_set_lock_functions: assertion 'gdk_threads_lock == NULL && gdk_threads_unlock == NULL' failed
> Start DBeaver SSH Tunnels [org.jkiss.dbeaver.net.ssh 1.0.156.202407282257]
> Start DBeaver JDBC Model [org.jkiss.dbeaver.model.jdbc 1.0.28.202407282257]
> Start DBeaver MySQL Support [org.jkiss.dbeaver.ext.mysql 2.1.220.202407282257]
> Start DBeaver SSH implementation (SSHJ) [org.jkiss.dbeaver.net.ssh.sshj 1.0.156.202407282257]
2024-08-07 18:10:36.059 - SSHSessionController: Creating new session to a*****n@1*****6:22
2024-08-07 18:10:36.060 - SSHSessionController: Connecting session to a*****n@1*****6:22
2024-08-07 18:10:36.080 - Security Provider class 'org.bouncycastle.jce.provider.BouncyCastleProvider' not found
2024-08-07 18:10:36.080 - BouncyCastle not registered, using the default JCE provider
2024-08-07 18:10:36.085 - Creating new SecureRandom.
2024-08-07 18:10:36.098 - Shutdown desktop platform...
2024-08-07 18:10:36.099 - Listener 'org.jkiss.dbeaver.ui.actions.datasource.DataSourceToolbarHandler@bef5b42' is not unregistered from DBM model
2024-08-07 18:10:36.100 - Some project listeners are still register: [org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchWindowAdvisor@2cddd4f7]
2024-08-07 18:10:36.101 - Some datasource registry listeners are still registered: [org.jkiss.dbeaver.ui.actions.datasource.DataSourceToolbarHandler@bef5b42]
2024-08-07 18:10:36.148 - Platform shutdown completed (49ms)
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.runtime.jobs.ConnectJob
```

### DBeaver Version

 24.1.3.202407282257

### Operating System

Linux

### Steps to reproduce

1. Run a WM or DE without XWayland. (eg. in riverWM, run `river -no-xwayland`)
2. Open dbeaver

**Comment by E1izabeth** [comment] 2024-08-07 12:55
Thank you for bug report.
It sound like a duplicate of #34929
We have already fixed it. Please try DBeaver 24.1.4

**Comment by Axolite15** [comment] 2024-08-07 13:03
@E1izabeth Thank you for your immediate response.

aaaa! sorry for the ridiculous bug report. I forgot to search in closed issues. Sorry for wasting everyone's time :p

**Comment by E1izabeth** [comment] 2024-08-07 13:04
Please let me know, if 24.1.4 runs fine for you, when you try.

**Closed as completed** 2024-09-04 15:29 UTC
Labels: xo:linux, wait for response
