### ISSUE TITLE
Dbeaver hung at Import DBeaver configuration

### ISSUE THREAD

**Issue by brilliant-smart** [dbeaver/dbeaver#12323] opened 2021-04-30 16:32 UTC
I force purged dbeaver community that comes with kali and installed a newer version as the old one refused to update or allow me install the new one on top of it.
Now if I start the dbeaver it hang at welcome logo with import dbeaver configuration written at the task bar..

Please help!

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by autodidact1958** [comment] 2021-05-03 15:34
Delete the older configuration-paths in your home-directory (in Linux /home/<USER>/.dbeaver4, .dbeaver-drivers etc.). Older configurations can prevent new versions from starting (as I learned today :-))

**Comment by brilliant-smart** [comment] 2021-05-03 16:41
Can't find such directory. However, running dbeaver --configure in terminal makes the program open...

**Comment by kseniiaguzeeva** [comment] 2021-05-19 12:23
Is the issue still actual? Please try to reset workspace https://github.com/dbeaver/dbeaver/wiki/Reset-workspace.

**Comment by brilliant-smart** [comment] 2021-05-19 15:59
The issue persisted. BTW I reloaded the kali linux os and continue using dbeaver version 6 that comes with the os.
My issue now is how to update the dbeaver to latest version without going back to same problem. I can not install version 21 on top of it and I don't wanna uninstall it and run back to previous issue.

**Comment by kseniiaguzeeva** [comment] 2021-05-20 17:04
Could you send log files https://github.com/dbeaver/dbeaver/wiki/Log-files?

**Comment by uslss** [comment] 2021-06-15 09:20
seems it is a duplicate of #10852

**Closed as completed by uslss** 2021-06-15 09:20 UTC
Labels: duplicate
