### ISSUE TITLE
Vertical/Horizontal scrollbars overlap text in editor pane

### ISSUE THREAD

**Issue by alexabunny** [dbeaver/dbeaver#14368] opened 2021-10-25 02:38 UTC
#### System information: 
OS: **Ubuntu 20.04 - XFCE**
DBeaver:  **21.2.3.202110181332**
Additional extensions: **None**

#### Connection specification:
Any

#### Describe the problem you're observing:
The scrollbars in the query editor pane overlap text, making it impossible to do anything with that text using the mouse.

![Screenshot_2021-10-24_22-31-34](https://user-images.githubusercontent.com/3958783/138626429-da518a7a-3d48-4213-af06-d2b7aa291e8d.png)

Not sure if this a DBeaver thing or a window manager thing to be honest. I'm using xfce / xfwm4 though so my setup is pretty standard.

#### Steps to reproduce, if exist:
Open the editor and populate it when enough text to trigger vertical/horizontal scrollbars

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by alexabunny** [comment] 2021-10-25 03:02
Expected behavior is for the pane to shrink a tiny bit to accommodate scrollbars, instead of overlaying them over its contents.

**Comment by uslss** [comment] 2021-10-25 07:50
thanks for the report
closed as a duplicate of #10950

**Closed as completed by uslss** 2021-10-25 07:50 UTC
Labels: duplicate
