### ISSUE TITLE
I can't modify cell in resultset. Earlier this function was work. It is very necessary function and it not work. 

### ISSUE THREAD

**Issue by nkiseev** [dbeaver/dbeaver#3763] opened 2018-07-06 13:43 UTC

**Comment by serge-rider** [comment] 2018-07-07 17:59
Can't reproduce. Please provide more details. 
- What is your database
- How do you edit cells (in table editor or in custom query results).
- Are you sure that exactly the same results were editable in earlier versions?

**Comment by nkiseev** [comment] 2018-07-09 09:59
Sorry. I rechecked and made sure that I can edit cell in the result of query for MySQL and PostgreSQL.
I can't edit cell for Amazon Redshift, after update the driver for this DB. 
It is driver issue (i think) or interaction between DBeaver and Driver Amazon Redshift.

I tried edit cell in the custom query results.

**Comment by serge-rider** [comment] 2018-09-01 19:11
This was fixed in 5.1.5.

**Closed by serge-rider** 2018-09-01 19:11 UTC
Labels: can't reproduce, question
