### ISSUE TITLE
incomplete stored procedure (function) creation with CTRL+ENTER

### ISSUE THREAD

**Issue by shungabubus** [dbeaver/dbeaver#5682] opened 2019-04-08 13:10 UTC
Dear All,

System information: Win7 64bit, 6.0.0., java version "1.8.0_201"
Connection specification: oracle.jdbc.OracleDriver (ojdbc7.jar)

It can be considered as feature request, but for me it is rather a bug.

When I try to create a function or stored procedure with CTRL+ENTER (because I have plenty of other stuff in my editor tab and as you see I have already too many tabs) it stops at the ; sign resulting this:
![image](https://user-images.githubusercontent.com/36946814/55726410-06b4ce80-5a10-11e9-9d99-9a89d0cc31b0.png)
Original script (copied from PLSQL developer - no I don't use it from the moment I met the Beaver but others do. :():
![image](https://user-images.githubusercontent.com/36946814/55726699-b9852c80-5a10-11e9-94e5-84da065fbd80.png)

Any chance to have different behaviour for CREATE command? (I know I can just select all the lines, but it is so great that for normal scripts I can do this and it would be amazing if the program could select the connected lines until the first blank line...)

Many thanks:
Tamas

**Comment by serge-rider** [comment] 2019-04-12 13:49
Duplicate of #2590
Please test the fix in Early Access version (https://dbeaver.io/files/ea)

**Comment by shungabubus** [comment] 2019-04-13 13:55
Hello, apologies I tried to search but it was related to the block and this to the stored procedure so I did not find that, but yes they both are from the same origin. Many thanks.

**Comment by serge-rider** [comment] 2019-04-13 14:37
@shungabubus Thanks for testing

**Closed** 2019-04-13 14:37 UTC
Labels: bug, duplicate, x:oracle
