### ISSUE TITLE
Index viewer doesn't show columns in Custom view>hide folders

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10362] opened 2020-11-14 15:16 UTC
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.2.5 EA

#### Steps to reproduce, if exist:
Open an index
Expected: a related column is displayed in the index viewer
Actual result: the Index viewer is empty
![Screenshot 2020-11-14 at 18 10 38](https://user-images.githubusercontent.com/51405061/99150380-42f8e800-26a5-11eb-9478-d21886919d59.png)

**Comment by LonwoLonwo** [comment] 2021-01-27 08:18
Can't reproduce on DBeaver 7.3.3 on Windows 10. May be it is Mac issue?
![2021-01-27 11_17_18-DBeaver Enterprise 7 3 3 - IPK_Artist](https://user-images.githubusercontent.com/45152336/105962798-493a1600-6091-11eb-9c94-b97d4b73a7a5.png)

**Comment by LonwoLonwo** [comment] 2021-02-16 07:27
Actual also for all key viewers.

**Comment by LonwoLonwo** [comment] 2021-02-19 08:15
Fixed in 21.0.1

**Comment by uslss** [comment] 2021-02-19 10:50
verified

**Closed by uslss** 2021-02-19 10:50 UTC
Labels: bug, xp:minor
