### ISSUE TITLE
Unable to order columns in record view.

### ISSUE THREAD

**Issue by dwhitz** [dbeaver/dbeaver#18806] opened 2023-01-18 16:12 UTC
### Description

In the last releases is no more possible to order columns in the record view. (pressing tab on a record).
In the release `22.2.5.202211202223`  the sort button was available.

**Missing:** `DBeaver CE 22.3.2.202301060755`
![image](https://user-images.githubusercontent.com/25538711/213226513-459d9406-6aab-4c10-a5d5-1cad2e7852f7.png)

**Available:** `DBeaver CE 22.2.5.202211202223 `
![image](https://user-images.githubusercontent.com/25538711/213228601-8d9f4614-67e6-4f77-8ab0-fb46892b3896.png)

### DBeaver Version

Community Edition 22.3.2.202301060755

### Operating System

Windows 11

### Database and driver

SQLite 3.40
Oracle 12

### Steps to reproduce
- Run a select query
- Select a record and press tab to switch to the record view
- Unable to order columns by name

**Comment by E1izabeth** [comment] 2023-01-18 16:44
Thank you for bug report. It's a duplicate of #18618
The fix is available in the early access version (https://dbeaver.io/files/ea/) and will be available in the next release.

**Closed as not planned by E1izabeth** 2023-01-18 16:44 UTC
Labels: duplicate, xf:data
