### ISSUE TITLE
Dictionary not working properly

### ISSUE THREAD

**Issue by aspatzier** [dbeaver/dbeaver#19240] opened 2023-03-02 07:29 UTC
### Description

When a selected cell of a field/column referenced to the value list with a foreign key is NULL, it works - i.e. all values in the dictionary are displayed in the *Value panel*, double clicking fills the desired value into the selected cell of the referenced field/column.

When/Once the cell of a referenced field/column contains a value, the *Value panel* only shows this one value or only values of the dictionary starting with the same character as the cell value.
This can temporarily be fixed with clicking *Define Description* and (instantly) closing the pop-up window for editing the value/description (not doing anything except clicking *OK*). However, leaving the cell of the referenced field/column and re-selecting it, same problem...

The field/column name in my table serving as dictionary is equal to the name of the referenced field/column. I renamed it to "value" thinking there might be a problem caused by the column name - same behaviour, dictionary does not work properly. So this obviously doesn’t cause the problem.

UPDATE: The problem occurs (seemingly) when leaving the column and re-selecting it (or the cell respectively) with the value filled with a dictionary entry.

### DBeaver Version

Community Edition 22.3.5.202302180832

### Operating System

macOS Ventura 13.2.1

### Database and driver

1. SQLite
2. sqlite-jdbc-3.39.4.1.jar

https://user-images.githubusercontent.com/74900017/222704182-d82950d5-378a-4579-9a90-1b1c9ec92881.mp4

**Comment by LonwoLonwo** [comment] 2023-03-02 10:49
Hello @CommunyAS 

Please provide footage of your issue.

**Comment by aspatzier** [comment] 2023-03-03 11:05
Sure - edited my initial post and added a demonstration video.

Seemingly, the behaviour is a little different and only occurs when leaving the cell/column and then re-selecting it. Hope the video shows this clearly.

**Comment by Destrolaric** [comment] 2023-03-16 13:33
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by aspatzier** [comment] 2023-03-22 08:38
> Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

I just send you all available log files by mail, since I didn’t won't to post them here publicly.

**Comment by Destrolaric** [comment] 2023-03-22 16:47
```
java.lang.NumberFormatException: For input string: "659,493,139,143,324,367,373,482,504,505,649,658,553,537,545,613,684,633"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.valueOf(Unknown Source)
	at org.jkiss.dbeaver.utils.GeneralUtils.convertString(GeneralUtils.java:211)
	at org.jkiss.dbeaver.model.DBUtils.compareDataValues(DBUtils.java:2195)
	at org.jkiss.dbeaver.model.exec.DBCLogicalOperator$1.evaluate(DBCLogicalOperator.java:37)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel$AttributeColorSettings.evaluate(ResultSetModel.java:102)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.updateRowColors(ResultSetModel.java:825)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.appendData(ResultSetModel.java:878)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.setData(ResultSetModel.java:734)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setData(ResultSetViewer.java:2360)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchEnd(ResultSetDataReceiver.java:180)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:213)
```
@CommunyAS, It looks like these are the exceptions that may be the issue. Not entirely sure how they happen for now. Are there any existing color formatting in presentation?

**Comment by aspatzier** [comment] 2023-03-23 07:43
Yes there is color formatting. But they do not cause the problem, the problem with the dictionary existed (and still exists) before I set row colors and the formatting apply to a different table that I currently work with.

**Comment by Destrolaric** [comment] 2023-04-13 12:50
@CommunyAS, Could you see if the issue still exists in the release version of DBeaver?

**Comment by aspatzier** [comment] 2023-04-17 18:29
@Destrolaric, I just installed the latest DBeaver Community built 23.0.2.202304091457 and tried. The problem still exists as to be seen in the video of my initial post

**Comment by E1izabeth** [comment] 2023-05-09 21:56
Unfortunately, we can't reproduce your issue. Could you provide a DDL to recreate an issue? We need to know at least create statements for the table where the reference from and the target table on which the issue appears.

**Comment by E1izabeth** [comment] 2023-06-05 09:42
It's been a long time since no update here, so I'm closing this issue.
Please, let me know if the issue is still actual and provide some minimal example to reproduce your issue.

**Closed as not planned by E1izabeth** 2023-06-05 09:42 UTC
Labels: can't reproduce, xf:data, wait for response
