### ISSUE TITLE
The Table-Data editor ignores auto-commit setting in Db2 for IBM i connections.

### ISSUE THREAD

**Issue by marcmuel** [dbeaver/dbeaver#23269] opened 2024-03-28 13:25 UTC
### Description

Since the update to version 24.01 the behavior of my database connections for "DB2 for IBM i" (jt400) changed. 
The connection initialization preferences for the connection seem to be ignored.
If you expected to work in manual mode, this is a dangerous change.
On my non-JT400 connection, the behavior is still the same. The Table data editor opens in the same mode as the SQL editor.

### DBeaver Version

Community Edtion 24.01.202403241413

### Operating System

Windows 10

### Steps to reproduce

1. Update to DBeaver 24.01.
2. Check the connection settings of a Db2 for I Database and ensure that the connection is initialized without auto-commit.
3.  Connect to a Db2 for i Database
4. double click any database-table to open the table data editor. 
5. Check the commit mode.

**Comment by LonwoLonwo** [comment] 2024-03-28 14:48
Hello @marcmuel 

Could you please provide screens with your connection settings?

![2024-03-26 16_40_55-Window](https://github.com/dbeaver/dbeaver/assets/45152336/66fc7876-99c5-4d60-b827-b5985ca509a2)

![2024-03-26 16_41_14-Window](https://github.com/dbeaver/dbeaver/assets/45152336/53546292-0723-4bed-849a-2ebb7ebeb3f6)

**Comment by marcmuel** [comment] 2024-03-28 14:56
Here are my settings:
![grafik](https://github.com/dbeaver/dbeaver/assets/3865744/0c85ee50-6c09-4442-b311-fba9af31567f)

![grafik](https://github.com/dbeaver/dbeaver/assets/3865744/0e629806-6dd9-4b48-877a-928fbf586c6e)

**Comment by Matvey16** [comment] 2024-03-28 16:47
@marcmuel Thank you for the report. It seem like a duplicate of https://github.com/dbeaver/dbeaver/issues/23240
So i'll close this one

**Closed as completed** 2024-03-28 16:47 UTC
Labels: duplicate
