### ISSUE TITLE
Cannot modify the language using Window->Preferences->User Interface

### ISSUE THREAD

**Issue by wangqian-49** [dbeaver/dbeaver#14694] opened 2021-11-26 07:05 UTC
#### System information: 
- Operating system (distribution) and version : Centos7
- DBeaver version : 21.2.2
- Additional extensions : nothing

#### Connection specification:
- Database name and version : postgresql 12.3
- Driver name : PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:

Cannot modify the language using Window->Preferences->User Interface

#### Steps to reproduce, if exist:

start dbeaver, click Window->Preferences, left click User Interface, and In the right window to modify the language, restart according to the prompt, the interface language has not changed. If closed and restarted, the language is modified. The -nl parameter in the dbeaver.ini is successfully modified.

**Comment by Matvey16** [comment] 2021-12-07 13:11
@wangqian-49 Hello, can you add how did install dbeaver?

**Comment by wangqian-49** [comment] 2021-12-08 03:23
> @wangqian-49 Hello, can you add how did install dbeaver?

@Matvey16 

1. Download the installation package "dbeaver-ce-21.2.2-stable.x86_64.rpm" from the website "https://dbeaver.io/download/".
2. Install using command "rpm -ivh dbeaver-ce-21.2.2-stable.x86_64.rpm".
3. cd /usr/share/dbeaver-ce, and ./dbeaver to start.
4. click Window->Preferences, left click User Interface,  and In the right window to modify the language,restart according to the prompt, the interface language has not changed.

The installation package of “rpm -ivh dbeaver-ce-21.3.0-stable.x86_64.rpm ” also has the same problem in the website "https://dbeaver.io/download/".

**Comment by Matvey16** [comment] 2021-12-15 10:46
@wangqian-49 I was not able to reproduce your issue because I don't have privileges to modify files in /usr/share directory and therefore can't change language in UI. I assume you modified privileges to be able to edit that directory?

**Comment by Matvey16** [comment] 2021-12-16 08:14
@wangqian-49 Did you by any chance start DBeaver from terminal with `sudo`?

**Comment by wangqian-49** [comment] 2021-12-16 08:36
@Matvey16 Yes, I created an ordinary user named test and changed the permission of the directory " /usr/share/dbeaver-ce/" to test with the command "chown -R test:test /usr/share/dbeaver-ce/", and then start DBeaver with command "cd  /usr/share/dbeaver-ce/;./dbeaver".

**Comment by Matvey16** [comment] 2021-12-17 14:07
@wangqian-49 Thank you for the report. This happened because you started DBeaver from the terminal, so the restart after prompt reused the old .ini file without language change, only after manual closing the process was properly killed. We have plans to change the way that language property is stored, so this issue won't exist.

**Comment by serge-rider** [comment] 2022-02-20 19:50
Language can be changed in `config.ini` in `~/.eclipse/${product-version-id}/configuration` folder

Sample configuration:
```
osgi.nl=de
```
We can modify this file instead of primary `dbeaver.ini` in product installation directory.

Note: this setting takes effect only for particular product version. After new version install it stop working.

**Comment by serge-rider** [comment] 2022-02-20 20:00
We also probably should keep only major version in .eclipseproduct to avoid configuration loose every minor version update

**Comment by ShadelessFox** [comment] 2022-02-24 16:24
Fixed.

**Comment by Matvey16** [comment] 2022-02-25 12:53
Verified

**Closed as completed by Matvey16** 2022-02-25 12:53 UTC
Labels: enhancement, sp:3, xf:ui
