### ISSUE TITLE
Only DDL shows correct column size with MAX_STRING_SIZE  = EXTENDED (Oracle 19c)

### ISSUE THREAD

**Issue by rockyfjord** [dbeaver/dbeaver#21463] opened 2023-10-06 22:56 UTC
### Description

Under table T, under columns dropdown, The Database Navigator shows the column as 4000.

Also right-click table, view table, Properties tab, columns vertical tab, shows 4000.

Only viewing the DDL shows the correct size.

![Nav](https://github.com/dbeaver/dbeaver/assets/17992793/df2ed9d1-380c-46d0-bdd2-ddd65e9313a0)
![Props](https://github.com/dbeaver/dbeaver/assets/17992793/4a113046-5ee7-4e15-aae1-269f47394a62)
![DDL](https://github.com/dbeaver/dbeaver/assets/17992793/e3dc757d-a756-4724-b488-0fd504f1a07a)

### DBeaver Version

DBeaver Enterprise Version 23.2.0.202309120446

### Operating System

Windows 11

### Database and driver

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.15.0.0.0

with MAX_STRING_SIZE  = EXTENDED

### Steps to reproduce

CREATE TABLE T(
column1 VARCHAR2(8000 CHAR)
)

Under table T, under columns dropdown, The Database Navigator shows the column as 4000.

Also right-click table, view table, Properties tab, columns vertical tab, shows 4000.

Only viewing the DDL shows the correct size.

**Comment by LonwoLonwo** [comment] 2023-10-07 15:41
Hello @rockyfjord 

Thanks for the report.

This is for future testing: https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/MAX_STRING_SIZE.html#GUID-D424D23B-0933-425F-BC69-9C0E6724693C

**Comment by LonwoLonwo** [comment] 2023-10-31 17:24
Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/20231

**Closed as not planned by LonwoLonwo** 2023-10-31 17:24 UTC
Labels: x:oracle, duplicate, environment, xf:metadata, xp:normal
