### ISSUE TITLE
ORACLE - error throwing in compile package body doesn't work

### ISSUE THREAD

**Issue by majkyyx** [dbeaver/dbeaver#6085] opened 2019-06-12 07:42 UTC
#### System information: 
- Operating system (distribution) and version: **Ubuntu 18.04.2 LTS (same behavior on win10)** 
- DBeaver version: **6.1.0**
- Java version:  **openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03), OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)**
- Additional extensions: **none**

#### Connection specification:
- Database name and version: **Oracle 11.2.0.4** (same behavior on oracle 18)
- Driver name: **ojdbc8.jar**
- Do you use tunnels or proxies (SSH, SOCKS, etc): **yes, but behavior is same with tunel or without**

#### Describe the problem you're observing:

If package body has an error, you get a message (in package head error throwing works): 

> <package_name> compiled successfully

#### Steps to reproduce, if exist:
There is some example, i made error by typing ```yyy``` in package body **verso_info** (no mather whish error or package, i tried many times on diferent packages)

![compile_of_body](https://user-images.githubusercontent.com/14957734/59332015-9b2ffb80-8cf5-11e9-9351-341036da123c.png)
![body_status](https://user-images.githubusercontent.com/14957734/59332012-9b2ffb80-8cf5-11e9-9c17-303ec32d1438.png)
![body_compile_in_sql_line](https://user-images.githubusercontent.com/14957734/59332011-9b2ffb80-8cf5-11e9-81c9-0b6d688eb24a.png)

thanks for any solution

**Comment by paolovador** [comment] 2019-06-24 12:50
duplicate of #5453

**Comment by majkyyx** [comment] 2019-06-24 14:47
Hi it's look same, than sry for duplicate :-)  I tried to find same issue, but i was looking only for label bugs.
Maybe here is some additional information, but it's same.

Can u add bug label please?I this it's definitely bug :-)

I tried with my friends many ways (on all platforms), but there is no workaround. Almost immposible to develop oracle package.

THX

**Comment by paolovador** [comment] 2019-06-25 19:38
Hi,
There is a workaround as mentioned by pszabo1977 [here](https://github.com/dbeaver/dbeaver/issues/5453#issuecomment-497617483):

> IF I close the editor, re-open it, and than pressing Ctrl+F9 it's popping up the normal compilation error message.

**Comment by majkyyx** [comment] 2019-06-27 07:00
Yeah, i know, this workaround works, but it is realy realy user-unfriendly. You have to reopen editor  on every new error.

**Comment by uslss** [comment] 2020-03-23 12:09
fixed in scope of #5453

**Closed by uslss** 2020-03-23 12:09 UTC
