### ISSUE TITLE
DBEAVER 4.3 CE : Install Office Extension manually

### ISSUE THREAD

**Issue by jerherder** [dbeaver/dbeaver#2660] opened 2017-12-19 11:56 UTC
Hello,

how can you install the office extension manually in the CE edition without internet?

i have all the mandatory file.

When i load the contents.jar file, it's find the extension but when i do finished, i have this :+1: 

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No artifact repository available.
noArtifactRepositoriesAvailable

Kind Regards

**Comment by serge-rider** [comment] 2017-12-19 18:15
How did you install it?
Just retested with Marketplace and Eclipse 4.7 drag-n-drop method - works perfect.
Note: you need to most recent version of DBeaver plugin to install Office extension.

**Comment by ruspl-afed** [comment] 2017-12-19 18:20
Do you mean "from pre-downloaded archive"? Please describe the resources you have locally and the actions you performed,

**Comment by jerherder** [comment] 2017-12-27 10:14
HEllo

i have no eclipse on my pc. i have just install dbeaver 4.3 community edition.

i dowloaded all the sources files on https://dbeaver.jkiss.org/update/office/latest/ and create the same paths locally.


after i load the content.xml
[office_dbeaver.docx](https://github.com/dbeaver/dbeaver/files/1588808/office_dbeaver.docx)

**Comment by serge-rider** [comment] 2017-12-27 18:04
You need to install the most recent version (4.3.1) to install latest extensions.

**Comment by jerherder** [comment] 2017-12-28 06:22
O, thanks for the information

**Comment by jerherder** [comment] 2017-12-28 06:27
yes but the extensions i dowloaded are the extensions of the 4.3 version

**Comment by jerherder** [comment] 2018-01-02 13:57
Have you an idea?

**Comment by serge-rider** [comment] 2018-01-02 19:38
@jerherder looks like something went wrong with DBeaver CE p2 configuration.
Hope to fix it in 4.3.2..

**Comment by serge-rider** [comment] 2018-01-02 20:07
Please try EA version (https://dbeaver.jkiss.org/files/ea/) and try to install the recent Office extension.

**Comment by jerherder** [comment] 2018-01-03 07:10
HEllo

thanks you. i try to install too with eclipse. 

Have a nice day

Kind regards

**Comment by jerherder** [comment] 2018-01-03 14:04
Hello

Internet access is mandatory? because i have eclipse but i can't install marketplace without internet access.

**Comment by jerherder** [comment] 2018-01-03 14:11
how can i load the contents.jar and artifacts.jar in the same time?

**Comment by jerherder** [comment] 2018-01-03 14:51
Hello

When i try from application or eclipse and internet open, i have this 

could not find https://dbeaver.jkiss.org/update/office/latest/

**Comment by jerherder** [comment] 2018-01-03 14:51
i am in the 4.3.1 EA version

**Comment by jerherder** [comment] 2018-01-03 14:58
now i have this via eclipse

[office_dbeaver2.docx](https://github.com/dbeaver/dbeaver/files/1600705/office_dbeaver2.docx)

**Comment by jerherder** [comment] 2018-01-03 15:17
after install dbeaver and this extension in eclipse, it's works but it's not my project. dbeaver should be independant of eclipse.

kind regards

**Comment by jerherder** [comment] 2018-01-03 15:25
proxy is open but i have : could not find https://dbeaver.jkiss.org/update/office/latest/

**Comment by jerherder** [comment] 2018-01-10 11:13
Hello

i am on the new version 4.3.2 and take manually all the files of https://dbeaver.jkiss.org/update/office/latest/features/

and now when i do the manual installation, i have theses errors after copying the features and plugins in the folder of the dbeaver installation

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No artifact repository available.
noArtifactRepositoriesAvailable

**Comment by serge-rider** [comment] 2018-01-10 21:16
I think I found the root problem (it happens during product P2 repository build).
This is related not just to Office extension but to any extension you install in DBeaver.
Will try to fix this in the next version.

**Comment by jerherder** [comment] 2018-01-11 07:20
hello serge

ok, great news. thanks to you.

**Comment by serge-rider** [comment] 2018-01-20 19:13
Well, after all I figured out what is wrong with Office (and not only) extension install.
The problem is in location where DBeaver is installed. If it is `Program Files` on Windows or `/Applications` on Mac or `/usr/share` on Linux then DBeaver (Eclipse P2 manager actually) can't write local config there (because it is write protected folder).

Workarounds:
- Install DBeaver in some non-write protected folder.
- Run DBeaver as Administrator/root.

Also Windows Installer was fixed (see #2783) so now DBeaver will be installed in local user folder by default. This will let users to install any extensions with additional configuring.

**Closed by serge-rider** 2018-01-20 19:13 UTC
Labels: bug

**Comment by serge-rider** [comment] 2018-01-20 22:16
![image](https://user-images.githubusercontent.com/6398845/35188568-9ebc5b1e-fe48-11e7-9097-2003f51f0a54.png)

**Comment by jerherder** [comment] 2018-01-22 08:12
Hello

thanks you very much.

i founded an alternative solution too. 

1) download the files of the office url in local in a folder with the same architecture of the url.

2) load the repository with the files folder paths.

and it's works.
