### ISSUE TITLE
Export data exports wrong rows

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#9633] opened 2020-08-26 11:21 UTC
Ordering rows in Datagrid (Eg. by "ID desc"), selecting the first rows in datagrid (meaning i select the latest/biggest N IDs Eg), and selecting "Export data"-> "Export SQL Insert statement"  with following options
![Screenshot at 2020-08-26 13-15-26](https://user-images.githubusercontent.com/3930671/91297411-92163780-e79e-11ea-956a-1a4428552320.png)
Does not export selected rows, but the first X rows *ordered by ID*, not in a desc way.

**Comment by uslss** [comment] 2020-08-26 17:15
seems to be duplicate of #9252 (issue with rows is mentioned in comments)
anyway, thanks for the bug report

**Closed by uslss** 2020-08-26 17:15 UTC
Labels: bug, duplicate, xf:datatransfer
