### ISSUE TITLE
SQL Server - cannot filter Catalogs

### ISSUE THREAD

**Issue by Nekromancer** [dbeaver/dbeaver#4636] opened 2018-11-19 11:00 UTC
Using newest DBeaver i cannot filter catalog using `connection properties -> General -> Filters -> Catalogs`. When i set some filter i get an exception: `SQLServerException: The value is not set for the parameter number 1` while trying to get catalogs list. It's working fine without filter

**Comment by axias41** [comment] 2018-11-19 11:06
Me too, same issue

**Comment by serge-rider** [comment] 2018-11-19 12:09
Duplicate of #4632

Workaround: switch to SQL Server Legacy driver.

**Closed by serge-rider** 2018-11-19 12:09 UTC
Labels: bug, duplicate
