### ISSUE TITLE
[Wayland/GTK] Massive titlebar

### ISSUE THREAD

**Issue by p1u3o** [dbeaver/dbeaver#7262] opened 2019-11-21 09:27 UTC
#### System information: 
- Fedora 31 (31.20191121.0) 
- Dbeaver 6.2.5

#### Describe the problem you're observing:

Under Wayland, the GTK backend seems to have a massive title bar, this didn't occur under 6.2.4. 

#### Steps to reproduce, if exist:

Run 6.2.5 under GNOME Wayland and observe the titlebar.
![dbeaver_titlebar](https://user-images.githubusercontent.com/38067056/69324848-1a304500-0c41-11ea-84f0-2cda7a786376.png)

**Comment by serge-rider** [comment] 2019-11-23 14:26
Well, I don't understand what is wrong with title bar. How did it look before?

**Comment by p1u3o** [comment] 2019-11-25 09:26
Here's how 6.2.4 looked.

I've highlighted over maximize as it makes the bug easier to see.

![Screenshot-20191125092331-1606x885](https://user-images.githubusercontent.com/38067056/69528087-82df3080-0f65-11ea-8bae-4e5a59f2e4c3.png)

This might actually be a SWT bug.

**Comment by uslss** [comment] 2020-04-22 20:22
@p1u3o is it still actual?

**Comment by p1u3o** [comment] 2020-04-25 18:52
![image](https://user-images.githubusercontent.com/38067056/80288201-41c69480-872e-11ea-84cb-3a6a043e33c4.png)


Yep with 7.0.3. I spun up a quick Fedora 32 VM in GNOME Boxes.

That's Rhythmbox behind it, both are running natively on Wayland.

**Comment by jonnyso** [comment] 2020-06-21 05:16
Same problem here, managed to reproduce it flatpack, snap and rpm versions, only on wayland.

**Comment by p1u3o** [comment] 2020-09-02 10:05
Upstream SWT issue

https://bugs.eclipse.org/bugs/show_bug.cgi?id=563401

**Comment by uslss** [comment] 2021-08-30 18:36
seem it is duplicate of #6581

**Closed** 2021-08-30 18:37 UTC
Labels: bug, duplicate, xo:linux, xo:eclipse
