### ISSUE TITLE
22.3.4 Bug on Windows Store

### ISSUE THREAD

**Issue by Naibaowjk** [dbeaver/dbeaver#19038] opened 2023-02-10 18:45 UTC
### Description

This `22.3.4.0` Version (update in 2022-02-06, download in Microsoft Store) can't open because jre path cannot find.
![image](https://user-images.githubusercontent.com/17290838/218172133-4966f476-f604-4d1d-a7d7-aa460ed5b7de.png)

I check the path manually.

That's have double `jre` folder in the path:
```
C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_22.3.4.0_x64__1b7tdvn0p0f9y\jre\jre\bin
```

please fix this error

### DBeaver Version

22.3.4.0 (Windows Store version)

### Operating System

Windows 11

**Comment by E1izabeth** [comment] 2023-02-10 18:53
Thanks for the bug report. This is a known issue in the latest release.

As a workaround, you can either download DBeaver from https://dbeaver.io/files or install JRE 11 or greater.

Closing as a duplicate of #18960

**Closed as not planned by E1izabeth** 2023-02-10 18:53 UTC
Labels: duplicate, xo:windows, xf:packaging
