### ISSUE TITLE
Delete Object Alert Window Not Parsing {0} and {1} Values MacOS

### ISSUE THREAD

**Issue by knadt** [dbeaver/dbeaver#4948] opened 2019-01-09 05:38 UTC
#### System information: 
- Operating system (distribution) and version
MacOs Mojave v 10.14.1 (18B75) x86_64
- DBeaver version:(DBeaver Standalone Application) 5.3.2.201901062109
- Java version 
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
- Additional extensions

#### Connection specification:
- Database name and version
Microsoft SQL Sever 2017
- Driver name
mssql-jdbc, SQLJDBCDriver
- Do you use security connection (SSH, Proxy, etc)? 
SSH Tunnel

#### Describe the problem you're observing:

When deleting a table, the alert dialog does not parse the values into {0} and {1}. See below screenshot.
![Uploading Screenshot 2019-01-09 at 07.27.11.png…]()

#### Steps to reproduce, if exist:
1. Select any table
2. Right click on the table
3. Select delete

**Comment by knadt** [comment] 2019-01-09 05:40
<img width="631" alt="screenshot 2019-01-09 at 07 27 11" src="https://user-images.githubusercontent.com/16526578/50878979-dbefb580-13e1-11e9-9d95-3904f9ec3f12.png">

Attached image

**Comment by serge-rider** [comment] 2019-01-09 10:04
Duplicate of #4924
Thanks for the bug report anyway

**Closed by serge-rider** 2019-01-09 10:04 UTC
Labels: bug, duplicate
