### ISSUE TITLE
Copy as HTML, XML

### ISSUE THREAD

**Issue by vos56** [dbeaver/dbeaver#19337] opened 2023-03-11 09:09 UTC
**Describe the solution you'd like**
Look at this part of a SQL statement:
select stock.amount as WLM, st2.amount as MOT, items.ean, items.description from items ....

On the screen you see the result header like this:
|WLM|MOT|ean          |description                                               |

If you export the result you get a header as on screen, but if you "copy as" the SQL result from screen as HTML, XML, text, ... you get
|amount|amount|ean          |description                                               |

It would be nice always to get the header content with the directives given in the SQL statement.

**Comment by LonwoLonwo** [comment] 2023-03-13 08:42
Hello @vos56 

It looks like a duplicate of https://github.com/dbeaver/dbeaver/issues/18946

Do you mean using aliases as column names in the target instead of real column names?

**Comment by E1izabeth** [comment] 2023-04-10 12:39
It's been a long time since no update here. Please let me know, if it's still actual for you and provide additional information.

**Closed as not planned by E1izabeth** 2023-04-10 12:39 UTC
Labels: xf:datatransfer, wait for response
