### ISSUE TITLE
no mmsql-jdbc_auth-8.2.0.x64 in Java library path

### ISSUE THREAD

**Issue by yiting-wang-dl** [dbeaver/dbeaver#8344] opened 2020-04-05 18:05 UTC
#### System information: 
- Operating system (distribution) and version: MacOS Catinila
- DBeaver version 7.0.1 community

#### Connection specification:
- Microsoft SQL Server 

#### Describe your question:
I am connecting to the Microsoft SQL Server using DBeaver with Windows Authentication. The connection error is " no mssql-jdbc_auth-8.2.0.x64 in java.library.path: " 

I checked the driver management. Both drivers are version 8.2.0. I checked issue #8251, #8504. I tried reset to default, manually downloaded the drivers. None of these worked. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/37285002/78506022-01c25200-772c-11ea-9f27-8152a917b2f2.png">

The Information of each driver looks correct:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/37285002/78506095-3afac200-772c-11ea-991a-731b5392eb44.png">
<img width="963" alt="image" src="https://user-images.githubusercontent.com/37285002/78506100-40f0a300-772c-11ea-93ff-2540cc906110.png">

However, the download/update for the two drivers only have the JDBC Driver For SQL Server, no JDBC Driver For SQL Server Authentication Library for Windows.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/37285002/78506084-2f0f0000-772c-11ea-80eb-b3cc08c4c1c0.png">

When I update/download different versions, I can only change the version of JDBC Driver, not the driver for authentication. I manually dowloaded mssql-jdbc_auth-8.2.0.x64.dll and put in in the DBeaver driver folder, and add that folder to the driver library, but that raised the same error. 

I am not sure how to solve it. Can someone help me? 
Thank you.

**Comment by yiting-wang-dl** [comment] 2020-04-05 18:17
I also tried manually downloaded the drivers, and it didn't work.
<img width="857" alt="image" src="https://user-images.githubusercontent.com/37285002/78506541-050b0d00-772f-11ea-92fd-35910dd9abfe.png">

**Comment by serge-rider** [comment] 2020-04-05 21:17
Probably fixed in #8251
Click on "Reset to defaults" in driver editor dialog and then on Download/Update.

**Comment by yiting-wang-dl** [comment] 2020-04-06 16:55
Reset to defaults did not work for me. But I switched to SQL Server authentication, and there is no connection error anymore.

**Comment by szapote-tmo** [comment] 2020-05-11 22:45
@yiting-wang-dl Could we open this back up? I have the exact same problem with,

**System information:**
- Operating system (distribution) and version: MacOS Catalina
- DBeaver version 7.0.4 community

**Connection specification:**
- Microsoft SQL Server

Unfortunately for me, using SQL Server Authentication is not an option for me.

<img width="1680" alt="Screen Shot 2020-05-11 at 15 39 55 copy" src="https://user-images.githubusercontent.com/64446730/81619412-29ea4400-93af-11ea-9a5a-658e8e2bfced.png">

**Comment by n3tl0kr** [comment] 2020-05-20 16:37
@yiting-wang-dl I'm also seeing the same issue where Windows auth is a requirement.  I'm more than happy to assist with testing. 

**System information:**

    Operating system (distribution) and version: MacOS Catalina
    DBeaver version 7.0.5 community

**Connection specification:**

    Microsoft SQL Server

**Comment by quiescer** [comment] 2020-05-28 03:48
I have the same issue.

> DBeaver Community Edition Version 7.0.5.202005171753
> OS: Debian GNU/Linux 10 (buster) x86_64

**Comment by uslss** [comment] 2020-07-22 21:33
will be fixed in scope of #8666

**Closed by uslss** 2020-07-22 21:33 UTC
Labels: question, x:mssql

**Comment by ravenlost** [comment] 2020-10-07 07:51
Is this problem still ongoing ? I'm running into the same issue connecting to my workplace's MS SQL Server from a Linux desktop, using Windows Authentication. There's no other means for me to connect to it, and I would really not have to install windows ;) Cheers !!

**Comment by emiliogarza** [comment] 2020-10-16 02:56
Same, is there a way to use Windows Authentication on Mac? Why is it an option if there isn't a way to make it work?

**Comment by tumainimosha** [comment] 2022-06-27 17:23
Ran into this issue today, when connecting from a Mac to SQL Server using Azure AD integration. 

Similar to @emiliogarza @n3tl0kr and @yiting-wang-dl despite attempting to redownload the drivers this still didn't solve the issue.

I was able to get it working by adding a maven dependency for `msal4j` on the drivers section. I got the maven dependency link from [here](https://github.com/AzureAD/microsoft-authentication-library-for-java)

<img width="556" alt="Screenshot 2022-06-27 at 20 16 26" src="https://user-images.githubusercontent.com/7481490/175999061-1aa430fb-04be-4018-b57a-c7ced4dde632.png">

<img width="680" alt="Screenshot 2022-06-27 at 20 16 42" src="https://user-images.githubusercontent.com/7481490/175999098-b2e79226-274f-495d-be86-58f12dd875d0.png">

Added below in the above window
```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>msal4j</artifactId>
    <version>1.12.0</version>
</dependency>
```

And after saving this, it downloaded the msal4j dependency and worked for me.

**Comment by kingmanzhang** [comment] 2022-11-14 14:12
Not sure whether the issue is fixed. On Mac Montery, I have this error:

no mssql-jdbc_auth-9.2.0.x64 in java.library.pat

with DBeaver version 22.2.4

**Comment by yezhengli-Mr9** [comment] 2022-12-29 22:36
> <dependency>
>     <groupId>com.microsoft.azure</groupId>
>>    <artifactId>msal4j</artifactId>
>>     <version>1.12.0</version>
>> </dependency>



does not work and still has
```java
no mssql-jdbc_auth-9.2.0.x64 in java.library.path: 

/Users/***/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
```

> Ran into this issue today, when connecting from a Mac to SQL Server using Azure AD integration.
> 
> Similar to @emiliogarza @n3tl0kr and @yiting-wang-dl despite attempting to redownload the drivers this still didn't solve the issue.
> 
> I was able to get it working by adding a maven dependency for `msal4j` on the drivers section. I got the maven dependency link from [here](https://github.com/AzureAD/microsoft-authentication-library-for-java)
> 
> <img alt="Screenshot 2022-06-27 at 20 16 26" width="556" src="https://user-images.githubusercontent.com/7481490/175999061-1aa430fb-04be-4018-b57a-c7ced4dde632.png">
> 
> <img alt="Screenshot 2022-06-27 at 20 16 42" width="680" src="https://user-images.githubusercontent.com/7481490/175999098-b2e79226-274f-495d-be86-58f12dd875d0.png">
> 
> Added below in the above window
> 
> ```
> <dependency>
>     <groupId>com.microsoft.azure</groupId>
>     <artifactId>msal4j</artifactId>
>     <version>1.12.0</version>
> </dependency>
> ```
> 
> And after saving this, it downloaded the msal4j dependency and worked for me.



does not work and still has
```java
no mssql-jdbc_auth-9.2.0.x64 in java.library.path: 

/Users/***/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
```
Can download `mssql-jdbc_auth-9.2.0.x64.dll`, `mssql-jdbc-9.2.0.jre8.jar`, `mssql-jdbc-9.2.0.jre11.jar`, `mssql-jdbc-9.2.0.jre15.jar` from [here](https://learn.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16) and put it in both `/Users/***/Library/Java/Extensions` and `/Library/Java/Extensions` but still does not work.

**Comment by yezhengli-Mr9** [comment] 2022-12-30 19:09
> 
> Can download `mssql-jdbc_auth-9.2.0.x64.dll`, `mssql-jdbc-9.2.0.jre8.jar`, `mssql-jdbc-9.2.0.jre11.jar`, `mssql-jdbc-9.2.0.jre15.jar` from [here](https://learn.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16) and put it in both `/Users/***/Library/Java/Extensions` and `/Library/Java/Extensions` but still does not work.

Eventually uses username and password for `SQL server authentication` instead of `Windows authentication` and works now.

**Comment by yezhengli-Mr9** [comment] 2022-12-30 19:10
> > com.microsoft.azure
> >     msal4j
> >     1.12.0
> 
> does not work and still has
> 
> ```
> no mssql-jdbc_auth-9.2.0.x64 in java.library.path: /Users/***/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
> ```

Eventually uses username and password for `SQL server authentication` instead of `Windows authentication` and works now.

**Comment by manas007** [comment] 2024-10-11 15:46
Same issue. any updates ?
