### ISSUE TITLE
add ability to change foreign key parameters from the interface for Postgresql

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#11922] opened 2021-03-30 10:02 UTC
DBeaver 21.0.1

![изображение](https://user-images.githubusercontent.com/61137576/112971725-f0f2c380-9168-11eb-9d90-896b7af160bf.png)

**Comment by kseniiaguzeeva** [comment] 2021-04-08 08:28
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/3400. We are going to implement it after 21.1.0 release.

**Comment by LonwoLonwo** [comment] 2021-11-02 10:55
Ability to change update/delete rule for existing foreign key implemented in DBeaver 21.2.5

**Comment by Matvey16** [comment] 2021-11-03 06:49
Verified

**Closed as completed by Matvey16** 2021-11-03 06:49 UTC
Labels: x:postgresql, sp:2, xf:metadata
