### ISSUE TITLE
DBeaver Opens Internal Browser Window Gets Stuck at Authentication

### ISSUE THREAD

**Issue by ufuk-ergin-carbon** [dbeaver/dbeaver#21341] opened 2023-09-27 11:25 UTC
### Description

With this new update, DBeaver no longer opens an external browser on Mac, but instead opens an internal "Browser" window and fails to authenticate the credentials. Screenshot attached.

![Screenshot 2023-09-27 at 11 12 20](https://github.com/dbeaver/dbeaver/assets/114302087/155285ee-844c-49a5-9d33-9be24e5ab619)
![Screenshot 2023-09-27 at 11 10 25](https://github.com/dbeaver/dbeaver/assets/114302087/51bf4c93-d701-45b1-9dbe-ac21aaf1ceee)
![Screenshot 2023-09-27 at 11 10 45](https://github.com/dbeaver/dbeaver/assets/114302087/9eda957d-318e-4f75-96a0-2930664d979e)

### DBeaver Version

Version 23.2.1.202309250303

### Operating System

MacOS Ventura 13.5.2

### Database and driver

Database name and version: Snowflake 7.33.1
Driver name and version: Snowflake 3.13.30

### Steps to reproduce

1. Open DBeaver after logging off from the external authentication.
2. SIgn in and Browser in DBeaver appears.
3. After credentials, it gets stuck and opens a dialog with a long token link with timed out response.

**Comment by Destrolaric** [comment] 2023-09-27 12:22
@ufuk-ergin-carbon Hi, as a workaround the auth in the internal browser is configurable by the `open auth links in the embedded browser` checkbox in User Interface preferences
![image](https://github.com/dbeaver/dbeaver/assets/20579256/7ec853a3-9286-479f-ba29-2d02f228e8d6)

**Comment by E1izabeth** [comment] 2023-09-28 07:43
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by ufuk-ergin-carbon** [comment] 2023-09-28 10:54
Hi @E1izabeth, here are the log files.

[dbeaver-debug-1695802169958.log](https://github.com/dbeaver/dbeaver/files/12748615/dbeaver-debug-1695802169958.log)
[dbeaver-debug-1695823101033.log](https://github.com/dbeaver/dbeaver/files/12748616/dbeaver-debug-1695823101033.log)
[dbeaver-debug-1695898077235.log](https://github.com/dbeaver/dbeaver/files/12748617/dbeaver-debug-1695898077235.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/12748618/dbeaver-debug.log)

**Comment by ufuk-ergin-carbon** [comment] 2023-09-28 10:55
> @ufuk-ergin-carbon Hi, as a workaround the auth in the internal browser is configurable by the `open auth links in the embedded browser` checkbox in User Interface preferences ![image](https://user-images.githubusercontent.com/20579256/270326140-7ec853a3-9286-479f-ba29-2d02f228e8d6.png)

Thanks for the temporary workaround.

**Comment by E1izabeth** [comment] 2023-09-28 10:55
@ufuk-ergin-carbon thanks

**Comment by nicchristeller** [comment] 2023-09-28 21:52
I'm seeing this issue too, for GCP - so I don't think this is snowflake specific.

Interestingly the auth does work, but the browser window hangs and I get an auth error if I closed it (but running queries is then successful).

The workaround works for me as well, thank you :)

**Comment by ufuk-ergin-carbon** [comment] 2023-09-29 08:13
> I'm seeing this issue too, for GCP - so I don't think this is snowflake specific.
> 
> Interestingly the auth does work, but the browser window hangs and I get an auth error if I closed it (but running queries is then successful).
> 
> The workaround works for me as well, thank you :)

@nicchristeller, you're right. If you can manage to close this very long error pop up window out of range on even a big monitor, the queries run. Thanks for adding that.

**Comment by Destrolaric** [comment] 2023-09-29 08:53
@nicchristeller Hi, are you rinning DBeaver on macOS?

**Comment by nicchristeller** [comment] 2023-09-29 08:57
Oops yes sorry, on Mac. Afk now so not sure of the DBeaver version, but downloaded it yesterday

**Comment by CTEric** [comment] 2023-09-29 17:45
> @ufuk-ergin-carbon Hi, as a workaround the auth in the internal browser is configurable by the `open auth links in the embedded browser` checkbox in User Interface preferences ![image](https://user-images.githubusercontent.com/20579256/270326140-7ec853a3-9286-479f-ba29-2d02f228e8d6.png)

Many thanks, this is exactly what I was looking for.   I hope DBeaver sorts out whatever the issue is but for now this is a perfect workaround.

**Comment by rgriffogoes** [comment] 2023-10-10 13:46
Probably I missed the Release notes, but when I updated from DBeaver windows version `23.0.4.202305071722` to `23.2.2.202310081633` my Snowflake connections with SSO didn't work anymore (internal browser doesn't have appropriate certificates/settings to work with company's policies - for me it doesn't freeze)

And the reason was that now the auth links defaults to embedded browser (new setting mentioned as workaround) instead of using the "Web Browser" settings! 

Unchecking the new option makes the auth happen in the browser, and everything works again. Thanks for the indirect suggestion

**Comment by Destrolaric** [comment] 2023-11-24 09:41
Can't reproduce on Windows

**Comment by Destrolaric** [comment] 2023-12-01 10:56
@ufuk-ergin-carbon Hi, we tried to reproduce the mentioned issue with the same environment. We were able to connect, but to be sure. Have you tried closing redirect page when it pops up?

**Comment by ufuk-ergin-carbon** [comment] 2023-12-01 15:31
Hello @Destrolaric, the window that pops up has a very very long token address which makes the close button of the popped up window invisible. I am only able to close it when I change the resolution of the screen to something very very large and only then am I able to see the close button (I'm on Mac). Even if I could close the window, then I am left with an unauthenticated session, which I will not be able to use, since the connection was unsuccessful.

**Comment by Destrolaric** [comment] 2023-12-01 15:55
@ufuk-ergin-carbon Does this window popup appears on login popup closure?

**Comment by ufuk-ergin-carbon** [comment] 2023-12-01 18:14
@Destrolaric, this window appears for the authentication after the Dbeaver is not used for a long time. Dbeaver pops up an authentication window, asks for credentials, and then redirects as in the screenshots. But then it can't establish a connection and it pops up this error window as in the first screenshot above. Does it make sense?

**Comment by ufuk-ergin-carbon** [comment] 2023-12-04 12:02
Here is the same situation after today's Dbeaver update to Version 23.3.0.202312031432. It fails to redirect and this authentication window pops out for timeout.
![Screenshot 2023-12-04 at 14 54 57](https://github.com/dbeaver/dbeaver/assets/114302087/9836ae21-b5c7-4e05-baff-24dfdd3a06e0)
![Screenshot 2023-12-04 at 14 58 06](https://github.com/dbeaver/dbeaver/assets/114302087/7312c5aa-bc66-4f25-985b-c216ee73fe5b)

**Comment by Destrolaric** [comment] 2023-12-04 12:16
@ufuk-ergin-carbon There is a current issue that the window is not automatically closed, but the redirection should happen if you manually close the window. Can you try to manually close the window when `redirecting to snowlake client` appears?

**Comment by ufuk-ergin-carbon** [comment] 2023-12-06 07:40
I manually closed it and the connection was not successful. The queries did not work.

Also, I think there needs to be a character limit for the timeout pop out window. Otherwise, it shows all the characters of the token address and the pop out window's OK button falls out of range of the screen. I had to change the resolution of the screen to 3456 x 2234 in order to see the OK button.

**Comment by arhayka** [comment] 2024-09-26 13:08
We are unable to reproduce the issue, so I’ll close the ticket. Please feel free to reopen it if the issue persists.

**Closed as not planned by arhayka** 2024-09-26 13:08 UTC
Labels: can't reproduce, xo:macos, x:snowflake, environment, xf:auth
