### ISSUE TITLE
Unable to create a new database connection - DriverTreeViewer cannot be cast to class DriverTabbedViewer

### ISSUE THREAD

**Issue by rgoncalves-fuze** [dbeaver/dbeaver#11743] opened 2021-03-16 00:16 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 20H2
- DBeaver version: 21.0.0.202102281712
- Additional extensions: none

#### Describe the problem you're observing:
When trying to create a new database connection, I always get the following error:
```
Internal error when opening new connection wizard

Reason:
class org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer cannot be cast to class org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer (org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer and org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @458b4487)
```

#### Steps to reproduce, if exist:
Just try to create a new database connection by going to menu Database -> New Database Connection or just by clicking on the New Database Connection button on the toolbar.

#### Include any warning/errors/backtraces from the logs
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Mar 16 00:10:29 GMT 2021
class org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer cannot be cast to class org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer (org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer and org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @458b4487)
```

```
!SESSION 2021-03-16 00:01:29.281 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2021-03-16 00:02:04.691
!MESSAGE class org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer cannot be cast to class org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer (org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer and org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @458b4487)
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-03-16 00:02:04.691
!MESSAGE class org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer cannot be cast to class org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer (org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer and org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @458b4487)
!STACK 0
java.lang.ClassCastException: class org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer cannot be cast to class org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer (org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer and org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @458b4487)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverSelectViewer.getTabbedViewer(DriverSelectViewer.java:438)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageDriver.createControl(ConnectionPageDriver.java:101)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:743)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:635)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.open(NewConnectionDialog.java:100)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.openNewConnectionDialog(NewConnectionDialog.java:118)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.openNewConnectionDialog(NewConnectionDialog.java:108)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceCreateHandler.execute(DataSourceCreateHandler.java:32)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:243)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
```

**Comment by LonwoLonwo** [comment] 2021-03-16 07:56
Hello @rgoncalves-fuze
This ticket is duplicate of https://github.com/dbeaver/dbeaver/issues/11646
And answer was:
"This bug is already fixed. We've released hotfix version right after 21.0 release.
Just re-download it from dbeaver.io."

**Closed as completed by LonwoLonwo** 2021-03-16 07:56 UTC
Labels: duplicate
