### ISSUE TITLE
Query still running after data fetch

### ISSUE THREAD

**Issue by geuss** [dbeaver/dbeaver#6813] opened 2019-09-24 08:37 UTC
#### System information: 
- Operating system (distribution) and version: Windows 7
- DBeaver version: CE 6.2.1
- Java version : Default DBEAVER Java version
- Additional extensions: none

#### Connection specification:
- Database name and version: Teradata 15.00
- Driver name: Teradata JDBC Type 4 driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3646158/dbeaver-debug.log)

#### Include any warning/errors/backtraces from the logs

Hi!
From relase 6.1.5, sometimes, query still result in execution even if data was fetched:

![image](https://user-images.githubusercontent.com/26387091/65495359-ef32aa80-deb6-11e9-83cf-273437392c4c.png)

If I wait for a lot of time, the connection was closed:

![image](https://user-images.githubusercontent.com/26387091/65495523-2b660b00-deb7-11e9-8ac8-20e78994e489.png)

I use DBEAVER CE 6.2.1 with Teradata DBMS v.15.00.

**Comment by geuss** [comment] 2019-10-11 11:02
The issue is still present with version 6.2.2
![image](https://github.com/dbeaver/dbeaver/assets/26387091/fdf57925-5253-465b-ac97-2630808eae54)

**Comment by geuss** [comment] 2019-11-05 16:36
Hi! The issue is still present in version 6.2.4:

![image](https://github.com/dbeaver/dbeaver/assets/26387091/d63c0b84-ca27-4323-9c0f-347615563572)

I launched the query: "select * from mytable;"

Data was fetched and displayed in Result Viewer (all 200 records!), but query results always in execution (see "Background Task"). I can't execute others queries...:

![image](https://user-images.githubusercontent.com/26387091/68226469-6731db80-fff2-11e9-95ab-dc8944a6a6d0.png)

If I try to break execution from Background Task, after a lot of time... the connection was automatically closed.

It happens (almost always) with slow queries. The last version of Dbeaver where this bug was not present (or the problem is very infrequent) is the 6.1.5.

Thanks!

**Comment by geuss** [comment] 2020-01-07 14:39
The issue is still present with release 6.3.2. 

In this video you can see the problem with version > 6.1.5

Here, with the version 6.1.5 (that works...):


Thanks!!

**Comment by geuss** [comment] 2020-01-07 14:44
Sorry... I closed the issue by mistake. :-)

**Comment by geuss** [comment] 2020-02-17 10:08
Hi Serge, the error is still present with the 6.3.5 release.

**Comment by serge-rider** [comment] 2020-03-04 10:01
Can't reproduce as I don't have access to live Teradata instance at the moment.

**Comment by geuss** [comment] 2020-03-06 09:19
I suggest you to improve (by an application option) the application log, perhaps catching the bug will be more simple. :-)

If you need a Teradata DB test instance, you can download here freely:
https://downloads.teradata.com/download/database/teradata-express-for-vmware-player

Thanks!!!

**Comment by serge-rider** [comment] 2020-05-24 19:52
@geuss I still can't reproduce this issue. Queries run fine.
Maybe it depends on server/driver version (I use version 16.20).
Or maybe it happens because since 6.3 we open separate connection for each SQL editor by default (it can be disabled in preferences).

Could you make a thread dump once it will hang in your environment? https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump

**Comment by geuss** [comment] 2020-05-25 08:08
[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/4675949/thread-dump.txt)

Hi Serge!
Here there's the dbeaver thread dump (catched during a hanging event...).

I confirm you that the last version on dbeaver where the issue was not present in 6.1.5: I install every single release on the software... the issue raised in the passage from rel 6.1-5 to 6.2.0.

I'm a team leader of 5 people... I convinced all my collaborators to use Dbeaver (cause the default Teradata query tool, SQL Assistant, sucks... :-) ) . All of them have the same problem. We all connect to different Teradata Instance (same version of server... v.15.0). By now, we are using the old 6.1.5. of dbeaver. 

Tell me if I can help you in any way.

Thanks!!

**Comment by prajib** [comment] 2020-10-08 15:53
Thanks all. I also have the same issue with Version 7.2.1 -- Waiting for 7.3.1. 
Appreciate your work on this fix.

**Comment by EWingate7** [comment] 2020-10-14 03:27
Same here. I and several others on my team would greatly appreciate this fix! Looking forward to it.

**Comment by geuss** [comment] 2020-10-30 09:39
Still present in Version 7.2.3:
![image](https://user-images.githubusercontent.com/26387091/97689611-21401400-1a9c-11eb-8521-44ae2fa95df8.png)

Waiting fot 7.3.1
Thanks!

**Comment by geuss** [comment] 2021-03-18 11:48
Still present in 21.0.0

**Comment by geuss** [comment] 2021-05-10 09:29
Still present in 21.0.4

**Comment by LonwoLonwo** [comment] 2021-06-02 15:13
Hello @geuss 

Maybe the problem is what driver does not support multiple resultset, but in thread-dump I see method nextResults:

```
"DBeaver: Read data [select * from vp_ebil_log.query_log]" #332 prio=5 os_prio=0 cpu=515.63ms elapsed=342.43s tid=0x000000005e011000 nid=0x2a30 runnable  [0x0000000066dde000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.5/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.5/Unknown Source)
	at java.net.SocketInputStream.read(java.base@11.0.5/Unknown Source)
	at java.net.SocketInputStream.read(java.base@11.0.5/Unknown Source)
	at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.read(TDNetworkIOIF.java:798)
	at com.teradata.jdbc.jdbc_4.io.TDPacketStream.readStream(TDPacketStream.java:800)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementReceiveState.action(StatementReceiveState.java:141)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementController.runBody(StatementController.java:137)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementController.run(StatementController.java:128)
	at com.teradata.jdbc.jdbc_4.ifsupport.Results.moreResults(Results.java:204)
	at com.teradata.jdbc.jdbc_4.ifsupport.Results.getMoreResults(Results.java:145)
	at com.teradata.jdbc.jdbc_4.TDStatement.getMoreResults(TDStatement.java:865)
	at com.teradata.jdbc.jdbc_4.TDStatement.getMoreResults(TDStatement.java:830)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.nextResults(JDBCStatementImpl.java:207)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:541)
```

Can you please try to disable this setting in Edit Connection -> Edit Driver Settings -> Advanced parameters

![2021-06-02 18_09_35-Edit Driver 'Teradata'](https://user-images.githubusercontent.com/45152336/120506045-3c765780-c3ce-11eb-84e0-4c6d5b86389a.png)

**Comment by geuss** [comment] 2021-06-07 07:23
thanks @LonwoLonwo , I modified the setting.... I'll test it for some days.

**Comment by LonwoLonwo** [comment] 2021-06-09 07:24
Thanks for feedback @geuss 
We will wait for your answer

**Comment by geuss** [comment] 2021-06-11 09:47
Hi @LonwoLonwo , at the moment,  it seems that the issue is no more present!! I ask you (if possible) to wait another week before closing the issue.

Thanks!!!!

**Comment by LonwoLonwo** [comment] 2021-06-11 09:53
@geuss Ok

**Comment by vrkadiyala** [comment] 2021-07-01 12:59
This issue still exists even in 21.1.1.

**Comment by LonwoLonwo** [comment] 2021-07-05 20:23
Hello @vrkadiyala 
Did you uncheck "support multiple resultsets" in driver settings?

**Comment by vrkadiyala** [comment] 2021-07-08 09:11
Hi, 

After disabling the above one in driver settings, it is working fine. However, I find another issue. 

I generally use upper case when I write my SQL statements. Dbeaver names the alias for the table used in the query in a lower case by default, but, it does not get me the list of columns from the table when I type alias name in upper case. 

for example: 

SELECT * FROM EMPLOYEE e;

In this case, if I use alias 'e' in either where clause or select clause, it gets me the list f columns, but not the same in vice-versa.

**Comment by LonwoLonwo** [comment] 2021-07-12 08:22
So, I think there is no problem with data fetch in Teradata now and I'm closing this ticket.
If the problem appears again feel free to reopen the ticket.

**Comment by LonwoLonwo** [comment] 2021-07-12 08:24
@vrkadiyala Can't reproduce the autocompletion issue, unfortunately. 

![2021-07-12 11_17_40-](https://user-images.githubusercontent.com/45152336/125254908-976f6880-e303-11eb-84c5-c00a8a3380ce.png)

![2021-07-12 11_18_39-](https://user-images.githubusercontent.com/45152336/125254911-976f6880-e303-11eb-92f6-45000bf1a22b.png)

![2021-07-12 11_19_15-DBeaver 21 1 3 - _localhost 3_ Script-22](https://user-images.githubusercontent.com/45152336/125254913-9807ff00-e303-11eb-99e8-1147bed38dd6.png)

Some screens with examples will be very helpful. But please create another ticket for this issue.

**Closed by LonwoLonwo** 2021-07-12 08:24 UTC
Labels: bug, sp:3, wait for response, x:teradata

**Comment by vrkadiyala** [comment] 2021-07-12 16:40
Hi

This is the scenario. 

SELECT * FROM EMPLOYEE e WHERE E. 

This query is not fetching any search proposals related to attributes of employee table.

Warm Regards,

Venkat K

**Comment by LonwoLonwo** [comment] 2021-07-12 16:48
I'm not sure what we will fix it, @vrkadiyala , sorry.
Aliases must be consistent. And we think what "e" and "E" are different aliases.

Examples:
![2021-07-12 19_46_11-DBeaver Enterprise 21 1 3 - _DBeaver Sample Database (SQLite)_ Script-138](https://user-images.githubusercontent.com/45152336/125325789-04a5ec80-e34a-11eb-9a5c-3a3c18c8727a.png)

![2021-07-12 19_46_44-DBeaver Enterprise 21 1 3 - _DBeaver Sample Database (SQLite)_ Script-138](https://user-images.githubusercontent.com/45152336/125325793-04a5ec80-e34a-11eb-83c8-4c6a463a1de8.png)
