### ISSUE TITLE
Horizontal Scrolling of results grid does not work with two finger scroll gesture

### ISSUE THREAD

**Issue by mattcsl** [dbeaver/dbeaver#7983] opened 2020-02-22 23:31 UTC
Using the latest dbeaver in the latest eclipse I can't get the results grid to scroll horizontally when I use the two finger swipe right /left gesture in windows. Dbeaver/eclipse in mac os x works fine.

**Comment by uslss** [comment] 2020-02-23 13:29
thanks for the bug report

**Comment by riula** [comment] 2020-11-11 05:08
Any update on this? The scroll bar literally jumps all over the place when you try to scroll, making the editor unusable.

**Comment by richardbiddle** [comment] 2020-12-10 20:49
I think this is now an issue caused by https://github.com/dbeaver/dbeaver/issues/8404
Swiping right to left works (results scroll to the right as expected)
Swiping left to right does not work (results jump around left and right, but mostly to the right incorrectly)

It looks/feels to me that the windows default scroll is fighting against the horizontal scroll wheel (swipe) action.

**Comment by jpodpro** [comment] 2020-12-23 22:31
i've had this issue for a while - 7.1.3. grid freaks out like trump's twitter when 2-finger scrolling left.

**Comment by uslss** [comment] 2021-11-03 08:51
seems to be fixed in 21.2.4

**Closed by uslss** 2021-11-03 08:51 UTC
Labels: feature request, xo:eclipse, planned
