### ISSUE TITLE
Table Filters not work when navigator view is in Simple Mode

### ISSUE THREAD

**Issue by liusiyuxyfx** [dbeaver/dbeaver#34855] opened 2024-07-17 12:37 UTC
### Description

# Problem
The table filters not work when navigator view is in Simple Mode.
My table filter configured like this 
<img width="459" alt="image" src="https://github.com/user-attachments/assets/0b9db322-b347-445c-9abe-9c6b9db704a3">
And the navigator view is in Custom Mode or Advanced Mode
<img width="958" alt="image" src="https://github.com/user-attachments/assets/aeb8b486-be57-4c39-8d7a-2f1b1f453e1f">
The filters worked
<img width="276" alt="image" src="https://github.com/user-attachments/assets/10bb7f63-0b7c-4bcc-b016-81406e4e26ab">

**But when I change the navigator view mode to Simple Mode**
<img width="928" alt="image" src="https://github.com/user-attachments/assets/b1c9aaef-dd09-48bb-9f1e-2963b92cdc1e">

**The filters no longer worked**
<img width="804" alt="image" src="https://github.com/user-attachments/assets/d09ea5fa-502c-483a-86aa-f6d200632de0">

**Besides there is no "filter" button on right-click menu**

### DBeaver Version

Version 24.1.2.202407071610

### Operating System

mac OS Sonoma 14.5 M1 PRO

### Database and driver

Mysql 8.0.32
mysql-connector-j 8.2.0

### Steps to reproduce

1. setup table filters
2. set navigator view to Simple Mode
3. check whether the table is filtered

**Comment by E1izabeth** [comment] 2024-07-18 09:05
Thank you for bug report.
I'm closing it as it's a duplicate of #18440.
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-07-18 09:05 UTC
Labels: duplicate, xf:navigator
