### ISSUE TITLE
Copy as SQL IN (...)

### ISSUE THREAD

**Issue by Mizar01** [dbeaver/dbeaver#12369] opened 2021-05-06 08:06 UTC
When copying some values from a column, i would like to have an advanced copy of the following type:
 
Copy as SQL IN statement.

For example if i select the values 1,2,3 from the id column i would like to have a copy type that creates the text:

`in (1, 2, 3)`

or if it's a text type:

`in ('1', '2', '3') `

and so on. It could be an option to add the column name at the beginning, but usually this is useful for queries on other tables, so the column name is probably different.

**Comment by LonwoLonwo** [comment] 2021-05-06 08:38
Hello @Mizar01 
Thanks for idea.
As workaround you can use "Filter by column value"
![2021-05-06_11h36_49](https://user-images.githubusercontent.com/45152336/117267968-7b60ce00-ae5f-11eb-9de5-d9f975aabe62.gif)

**Comment by LonwoLonwo** [comment] 2021-05-06 08:40
Also this is duplicate of https://github.com/dbeaver/dbeaver/issues/8760

**Closed as completed by LonwoLonwo** 2021-05-06 08:40 UTC
Labels: duplicate

**Comment by Mizar01** [comment] 2021-05-07 07:42
FilterByColumn name is good but it cannot be considered a practical workaround for most of the situations, as said in the other similar thread (that I couldn't find before). Thanks.
