### ISSUE TITLE
Copy of table is not created SQLite

### ISSUE THREAD

**Issue by ForumLiker** [dbeaver/dbeaver#10582] opened 2020-12-02 14:25 UTC
There is no way to create a copy of the table structure. Instead, a new empty table is created.
https://recordit.co/No5cbr4e3T
DBeaver 7.3.0.202011291229 Windows 10x64
DBeaver 7.2.5 on Linux
sqlite-jdbc-3.32.3.2

**Comment by uslss** [comment] 2020-12-07 16:12
Hi @ForumLiker ,
you can use data export for it. Just export table to table in the same database.
https://github.com/dbeaver/dbeaver/wiki/Data-transfer
Can you check if it solves your problem and write back?
Thanks in advance

**Comment by ForumLiker** [comment] 2020-12-16 19:54
Hello @uslss! This is not a solution but only a temporary workaround

**Comment by ShadelessFox** [comment] 2021-02-05 11:02
This is an intended behavior for all databases, so I'll close this issue.

**Closed by ShadelessFox** 2021-02-05 11:02 UTC
Labels: enhancement, x:sqlite
