### ISSUE TITLE
CockroachDB DDL does not work

### ISSUE THREAD

**Issue by robert-s-lee** [dbeaver/dbeaver#4449] opened 2018-10-21 21:44 UTC
Trying dbbeaver-community 5.2.3 

Using the same schema from https://github.com/dbeaver/dbeaver/issues/4386

Nice ERD works with with 5.2.3.  Thank you.

The DDL does work as expected.  Please see below.

<img width="754" alt="screen shot 2018-10-21 at 5 37 50 pm" src="https://user-images.githubusercontent.com/6315124/47272767-44a06200-d558-11e8-858c-0f0ba8a7cbef.png">

**Comment by serge-rider** [comment] 2018-10-22 14:10
Can't reproduce this. Could you post erro/debug log?

https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by robert-s-lee** [comment] 2018-10-24 01:28
dbeaver-debug.log

```
2018-10-23 21:27:06.549 - Can't find data source 'postgres-cockroach-jdbc-1669883bbf3-6b4e5b353ea84d9e'
2018-10-23 21:27:06.554 - Can't find data source 'postgres-cockroach-jdbc-1669883bbf3-6b4e5b353ea84d9e'
2018-10-23 21:27:06.558 - Can't find data source 'postgres-cockroach-jdbc-1669883bbf3-6b4e5b353ea84d9e'
Oct 23, 2018 9:27:06 PM org.apache.commons.jexl2.JexlEngine unknownVariable
WARNING: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![17,32]: '!object.view && !object.external;' inaccessible or unknown property object
Oct 23, 2018 9:27:06 PM org.apache.commons.jexl2.JexlEngine unknownVariable
WARNING: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![17,32]: '!object.view && !object.external;' inaccessible or unknown property object
```

**Comment by serge-rider** [comment] 2018-10-24 08:13
Perhaps it is because of different Cockroach server versions.
Workaround has been committed.

**Closed by serge-rider** 2018-10-24 08:13 UTC
Labels: can't reproduce, question
