### ISSUE TITLE
Pressing Tab in the filter-field behaves incorrectly

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35645] opened 2024-09-18 17:50 UTC
### Description

There are also some side effects:
1. all the available items in a list are appeared in the suggestion list
2. the Tab character is typed in the field
3. if user finally chooses some of the items from the list, he will end up with wrong text in the filter-field, which is unhelpful and unwanted

https://github.com/user-attachments/assets/a3246d97-6c8f-473e-ada1-4712acfcdb37

### DBeaver Version

Enterprise Edition 24.2.1-202409122322

### Operating System

Windows 10

### Steps to reproduce

- start typing the symbol "c"
- press Tab
- choose some item from the list using mouse or pressing Enter

**Comment by E1izabeth** [comment] 2024-09-19 13:57
Thank you for the bug report. I reproduced the issue.

**Comment by ask9** [comment] 2024-11-29 14:59
@E1izabeth it seems to be, my issue is a duplicate of this one: #22081

**Comment by E1izabeth** [comment] 2024-12-03 12:22
You're right. Thanks.
Then I'm closing your issue as a duplicate of #22081

**Closed as not planned by E1izabeth** 2024-12-03 12:22 UTC
Labels: duplicate, xf:ui, xf:filters
