### ISSUE TITLE
The problem of comments disappearing when saving when modifying tables in DM database.

### ISSUE THREAD

**Issue by cnxjk** [dbeaver/dbeaver#35303] opened 2024-08-22 02:38 UTC
### Description

I am using a DM database, and when I create a table, the comments on the columns in the table are normal. However, when I modify the comments on the columns in the table and save them, there is no new comment code in the SQL. Do any experts have any suggestions? thank you！

### DBeaver Version

24.1.5

### Operating System

Windowns 11

### Database and driver

Dameng JDBC driver 18RELEASE

### Steps to reproduce

1. Connect to the DM database
2. Find a table with annotations in the columns.
3. Modify the comments on the columns in the table.
4. Click to save
5. There is no new comment code in the SQL pop-up box.

### Additional context

win 11环境

**Comment by humphreygao** [comment] 2024-08-22 04:24
duplicate of https://github.com/dbeaver/dbeaver/issues/34641

**Comment by E1izabeth** [comment] 2024-08-23 16:33
Thank you for bug report.
I'm closing it as it's a duplicate of #34641

**Closed as not planned by E1izabeth** 2024-08-23 16:33 UTC
Labels: duplicate, xf:metadata, x:dameng
