### ISSUE TITLE
ER Diagramm NPE

### ISSUE THREAD

**Issue by Bouncer77** [dbeaver/dbeaver#16111] opened 2022-04-07 07:52 UTC
After exporting the diagram and then opening it. On version Версия 22.0.0.202203060510 DBeaver Community - taked error. 
I can nor fix this problem. Please, help me.  

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Ошибка
Thu Apr 07 10:36:06 MSK 2022
NullPointerException

java.lang.NullPointerException
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorPart.getDiagram(ERDEditorPart.java:400)
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:212)
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:171)
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment] 2022-04-07 07:59
@Bouncer77 , unfortunately, cannot reproduce it. Could you provide a video with the issue and more clear steps to reproduce it?

**Comment by LonwoLonwo** [comment] 2022-04-07 08:02
Connected to https://github.com/dbeaver/dbeaver/issues/15766

**Comment by LonwoLonwo** [comment] 2022-04-15 09:08
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/15766

**Closed as completed by LonwoLonwo** 2022-04-15 09:08 UTC
Labels: can't reproduce, wait for response
