### ISSUE TITLE
DBeaver Reports N-1 Date with Clickhouse Driver

### ISSUE THREAD

**Issue by rglynn** [dbeaver/dbeaver#23421] opened 2024-04-14 01:41 UTC
### Description

All dates using the clickhouse driver display N-1 date value -- based on previous reports (https://github.com/dbeaver/dbeaver/issues/1527) and my reproduction steps below, it definitely seems like a bug in DBeaver.
![image](https://github.com/dbeaver/dbeaver/assets/81239954/10415ca4-ebc4-4671-8fee-27bbc4ffd79b)

### DBeaver Version

24.0.2.20240407179

### Operating System

Windows 10

### Database and driver

Database: Clickhouse
Driver: com.clickhouse.jdbc.ClickHouseDriver Official 21.3+

### Steps to reproduce

CREATE TABLE default.dates (date1 date) ENGINE = ReplacingMergeTree ORDER BY date1;
INSERT INTO default.dates (date1) values ('2024-04-13');
SELECT * FROM default.dates;

**Comment by rglynn** [comment] 2024-04-14 01:49
And as I am operating in some other functions on dates, it actually is more impactful than just the display date -- this also causes incorrect date value calculations:

![image](https://github.com/dbeaver/dbeaver/assets/81239954/977f4c09-8621-40f1-a11e-cf7ab354f488)


CREATE TABLE default.dates (date1 date) ENGINE = ReplacingMergeTree ORDER BY date1;
INSERT INTO default.dates (date1) values ('2024-04-13');
SELECT date1, current_date(), current_date() - date1 AS test FROM default.dates;

Here's the same execution in Python on the same table (had to convert to EST so it was the same relative date for current_date)
![image](https://github.com/dbeaver/dbeaver/assets/81239954/b37eb799-3464-4335-9cad-66066669b3fe)

**Comment by aadant** [comment] 2024-05-07 00:13
looks like a duplicate of this one https://github.com/dbeaver/dbeaver/issues/21619

**Comment by E1izabeth** [comment] 2024-05-10 06:52
Duplicate of #21619
Please read this comment with explanation https://github.com/dbeaver/dbeaver/issues/21619#issuecomment-2060976863

**Closed as not planned by E1izabeth** 2024-05-10 06:52 UTC
Labels: duplicate, xf:data, x:clickhouse
