### ISSUE TITLE
After update DBeaver resets language to system settings

### ISSUE THREAD

**Issue by inliquid** [dbeaver/dbeaver#18079] opened 2022-10-29 12:25 UTC
### Description

After update DBeaver resets language to system settings. User has to reconfigure application each time it upgrades.

### DBeaver Version

22.2.3.202210231354

### Operating System

Windows 10

**Comment by E1izabeth** [comment] 2022-10-29 13:10
Thank you for bug report. I'm closing it as a duplicate of #17857

**Closed as not planned by E1izabeth** 2022-10-29 13:10 UTC
Labels: duplicate
