### ISSUE TITLE
DBeaver becomes irresponsive when scrolling through file with one very long line (MacOS)

### ISSUE THREAD

**Issue by MathiasVersichele** [dbeaver/dbeaver#8287] opened 2020-03-27 14:22 UTC
Hi, I love DBeaver as an environment, but I've had lots of trouble with SQL files that contain long lines. I attached a file to this ticket. When I open it in Beaver 7.0.1 and try scroll to the bottom, it freezes up when it reaches line 168, and stays irresponsive for minutes almost melting my cpu.

Is this a bug, or a known limitation ?

[dbeaver_crash.txt](https://github.com/dbeaver/dbeaver/files/4394006/dbeaver_crash.txt)

**Comment by MathiasVersichele** [comment] 2020-03-27 14:23
I run macOS High Sierra (10.13.6)

**Comment by uslss** [comment] 2020-07-22 11:59
Hi @MathiasVersichele ,
cannot reproduce it. Is it still actual for you?

Sorry for the late response

**Comment by uslss** [comment] 2020-08-17 13:26
probably similar to #7777 .
Closed as duplicate

**Closed by uslss** 2020-08-17 13:26 UTC
Labels: bug, can't reproduce, duplicate, wait for response
