### ISSUE TITLE
Auto commit enabled in production

### ISSUE THREAD

**Issue by EnricoPullara** [dbeaver/dbeaver#23240] opened 2024-03-26 15:17 UTC
### Description

After upgrading to 24.0.1, whenever I connect to a SQL Server configured with Connection type "Production" auto-commit is always enabled.

It should be disabled according the connection configuration and I even tried to reset settings. 
I downgraded to 24.0.0 at works fine there

### DBeaver Version

24.0.1

### Operating System

Windows 11

### Database and driver

SQL Server

### Steps to reproduce

1. Connect to a database marked as Production
2. Check commit mode

**Comment by LonwoLonwo** [comment] 2024-03-26 15:43
Hello @EnricoPullara 

I can't reproduce your issue.
Could you please provide screens from your settings?
Are you sure you didn't change the auto-commit mode in your connection settings?

![2024-03-26 16_40_55-Window](https://github.com/dbeaver/dbeaver/assets/45152336/66fc7876-99c5-4d60-b827-b5985ca509a2)

![2024-03-26 16_41_14-Window](https://github.com/dbeaver/dbeaver/assets/45152336/53546292-0723-4bed-849a-2ebb7ebeb3f6)

**Comment by EnricoPullara** [comment] 2024-03-26 16:07
Hi @LonwoLonwo 

I checked everywhere, I even restored settings.
As I mentioned before, with the exact same configuration I don't have any issues on 24.0.0

Here my current settings 

![Screenshot 2024-03-26 170352](https://github.com/dbeaver/dbeaver/assets/15218706/0f616686-4114-4b0a-96e1-459f0e6ec9bc)

**Comment by LonwoLonwo** [comment] 2024-03-26 17:32
Ok, but how exactly do you understand that auto-commit is ON in DBeaver? What do you do?

**Comment by ruengels** [comment] 2024-03-27 08:23
Hello, 
Same problem here, since release of 24.0.1 is auto-commit ON, despite settings stating otherwise
I noticed this at making changes to a table. After saving these changes and before I could review them the data had already been committed. 
![image](https://github.com/dbeaver/dbeaver/assets/107548725/3dc2e1b4-d203-46dc-a208-26611a20b62e)
![image](https://github.com/dbeaver/dbeaver/assets/107548725/53b807ca-7262-4adf-8758-9df1da9633b4)

**Comment by LonwoLonwo** [comment] 2024-03-27 09:07
Can some of you make a video of the issue? I still can't reproduce.

![2024-03-27 10_04_29-Window](https://github.com/dbeaver/dbeaver/assets/45152336/9167e1b1-f431-4a8c-8c43-4a487b68bb0d)

**Comment by EnricoPullara** [comment] 2024-03-27 09:11
I just connect to any SQL Server database and I see the T icon on the toolbar. I also see "Auto" where I should see pending transactions count and Commit and Rollback buttons are gray. If I edit something, it's automatically committed when I press on Save.
I also noticed I don't have the confirmation popup which warns me if I'm sure I want to make changes in a production environment.

**Comment by LonwoLonwo** [comment] 2024-03-27 12:41
Ok, we can reproduce it. Thanks for the report!

**Closed as completed** 2024-04-01 13:47 UTC
Labels: xp:major, sp:1

**Comment by JuanIbcar** [comment] 2026-01-02 12:04
same behaviour reported observed in 25.3.1. Tested with auto-commit disabled (connection and session) different levels of isolation and the pending commits counter does not increase, shows AUTO after saving any update data.

**Comment by kjkit** [comment] 2026-01-08 15:42
I report the same behaviour. Auto-commit setting is ignore! Always AUTO commit is ON.
I started noticing this bug after repair ticket #7302 and merged with version 25.3.1.

**Comment by EnricoPullara** [comment] 2026-01-08 16:02
Can't reproduce on 25.3.2

Looks like it's a different issue or it's already fixed

**Comment by serge-rider** [comment] 2026-01-08 16:25
@kjkit In https://github.com/dbeaver/dbeaver/issues/7302 we changed behavior so toggling auto-commit option changes it but doesn't save it in configuration. So after restart or reconnect this option will reset to default.
In order to change this option in the saved configuration you need to go to connection settings dialog, page Transactions and change it there.

**Comment by kjkit** [comment] 2026-01-08 16:56
Ok. I put my screens here.
When I open Dbeaver 25.3.2 and connect to production DB MSSQL. 
Transaction Settings Connection for this DB:
<img width="390" height="384" alt="Image" src="https://github.com/user-attachments/assets/5189369e-1655-42f7-ba7a-0f09a64c6985" />

I see on transaction bar:
<img width="230" height="199" alt="Image" src="https://github.com/user-attachments/assets/cc4be201-e43d-4c47-ac9a-78d741cdc19c" />

<img width="156" height="54" alt="Image" src="https://github.com/user-attachments/assets/9d1baec5-2cb1-4c55-9591-71c94ffae105" />

Default option for this config should be Manual Commit not AutoCommit. When I execute transactions every transact is in auto-commit mode. I can't change commit setting to ManualCommit from the task bar menu.... Always config is in AUTO commit mode.

**Comment by serge-rider** [comment] 2026-01-09 05:16
You are right, there is an inconsistency in dbeaver transaction mode configuration.

1. We have connection type which defines default auto-commit flag.
2. We have separate option "Auto-commit" on the Initialization page

<img width="831" height="161" alt="Image" src="https://github.com/user-attachments/assets/d48c9ffa-4648-4500-a694-433ad38c759f" />

If you ever set "Auto-commit" on the Initialization page then it will have higher priority than this flag in connection type. And it is not possible to "reset" this flag.
Generally it blows the mind.

I created the ticket https://github.com/dbeaver/dbeaver/issues/40069 which should solve it.
Let's continue there.
