### ISSUE TITLE
Issue on Theme Change

### ISSUE THREAD

**Issue by bhagatkhyati5** [dbeaver/dbeaver#9977] opened 2020-10-06 06:37 UTC
![image](https://user-images.githubusercontent.com/72433097/95166997-799d3200-07cc-11eb-8a0f-564c33960c09.png)

**Comment by kseniiaguzeeva** [comment] 2020-10-06 08:09
I cannot reproduce it. Please:
- tell your OS and DBeaver version
- send logs

**Comment by uslss** [comment] 2020-10-06 08:20
Reproducible (Windows 10)
![image](https://user-images.githubusercontent.com/31996417/95176741-f5e04700-07c5-11eb-82e9-66b69907e600.png)

**Comment by bhagatkhyati5** [comment] 2020-10-08 09:35
> I cannot reproduce it. Please:
> 
> * tell your OS and DBeaver version
> * send logs

DBeaver 7.2.2
and OS - Windows 10 Pro

**Comment by serge-rider** [comment] 2020-12-13 12:23
This issue was resolved in the recent Eclipse platform

**Comment by kseniiaguzeeva** [comment] 2020-12-14 10:07
verified

**Closed by kseniiaguzeeva** 2020-12-14 10:07 UTC
Labels: bug, xo:windows
