### ISSUE TITLE
Internal error connection to xxx.xxx.xxx.xxx

### ISSUE THREAD

**Issue by lzb-libra** [dbeaver/dbeaver#10498] opened 2020-11-26 02:38 UTC
![QQ截图20201126103916](https://user-images.githubusercontent.com/63389341/100301695-abb06080-2fd3-11eb-855f-f2c0c7ae49f4.png)
I use dbeaver to execute sql statement to query the data and close dbeaver. When I open dbeaver again, internal error connection to xxx.xxx.xxx.xxx always appears. Can this warning be removed? Why the program has not been initialized yet? Try to connect that? I think the program should be initialized before trying to connect.

**Comment by kseniiaguzeeva** [comment] 2020-12-03 12:29
Please tell your database and DBeaver version

**Comment by lzb-libra** [comment] 2020-12-04 01:43
Connecting to any remote database and any version has this problem

**Comment by kseniiaguzeeva** [comment] 2020-12-08 08:58
Please send log files https://github.com/dbeaver/dbeaver/wiki/Log-files, I cannot reproduce it.
Also please try to reinstall DBeaver.

**Comment by lzb-libra** [comment] 2020-12-08 11:04
Hello, I can't find the log of dbeave. My computer is windows

**Comment by kseniiaguzeeva** [comment] 2020-12-08 11:10
Please check one more time:
On Windows open Explorer and paste path %APPDATA%\DBeaverData\workspace6\.metadata.

In special cases log files can be written in other directories. Special case is an emergency situation when DBeaver can't start and there is no workspace. Two typical places to find emergency logs:
<install-path>/configuration
${HOME}/.eclipse/org.jkiss.dbeaver.product_<dbeaver-version>

**Comment by lzb-libra** [comment] 2020-12-17 02:22
Does %APPDATA% refer to the installation directory of dbeaver?
![20201217102123](https://user-images.githubusercontent.com/63389341/102435494-af268d00-4051-11eb-91a3-7cbdef05b441.png)

**Comment by kseniiaguzeeva** [comment] 2020-12-17 07:04
It leads to DBeaver metadata folder.

**Comment by lzb-libra** [comment] 2020-12-17 07:15
I finally found the dbeaver log
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5707562/dbeaver-debug.log)

**Comment by kseniiaguzeeva** [comment] 2020-12-17 07:19
Great! Please send also .log file from the same folder. It has the main information about errors.

**Comment by lzb-libra** [comment] 2020-12-17 07:22
[Uploading dbeaver_log.txt…]()

**Comment by kseniiaguzeeva** [comment] 2020-12-17 07:23
Thank you!

**Comment by kseniiaguzeeva** [comment] 2020-12-21 13:11
Please try:
- Most probably you have an SQL Editor window opened. Please  close it and reopen DBeaver.
and
- Please install also the latest DBeaver version  https://dbeaver.io/download/

Did you set any SHELL commands?
![dbeaver_tq8OPTZgEb](https://user-images.githubusercontent.com/51405061/102780558-30aa5200-43a7-11eb-9c2f-40a9dcdfc66f.png)

**Comment by lzb-libra** [comment] 2020-12-23 02:57
I haven't encountered this problem in the new version for the time being. I often encountered this problem in the version before 7.3.1. I can't always remember to close the "SQL Editor" window after using DBeaver. I don’t remember if I set the SHELL command. Does it matter?

**Comment by kseniiaguzeeva** [comment] 2020-12-23 05:30
Yes, it will help us to find a, reason.

**Comment by serge-rider** [comment] 2020-12-27 10:33
I suppose it was fixed in https://github.com/dbeaver/dbeaver/commit/e620e4455fa9ebd1fd8df0cd16b7d502155b1338
Please reopen if it is still reproducible.

**Closed** 2020-12-29 09:12 UTC
Labels: bug

**Comment by lzb-libra** [comment] 2020-12-29 10:13
thank you
