### ISSUE TITLE
Copy/Paste Roles (PostgreSQL) don't works

### ISSUE THREAD

**Issue by zarpelon** [dbeaver/dbeaver#6271] opened 2019-07-12 17:51 UTC
When I try to copy roles from postgres between differents connections, it does not work.

#### System information: 
- Ubuntu 19.04
- DBeaver 6.0.4

#### Connection specification:
- Database name and version
- PostgreSQL

**Comment by uslss** [comment] 2020-12-11 00:49
related to #8133

**Comment by uslss** [comment] 2021-08-03 15:25
closed as duplicate of #8133

**Closed by uslss** 2021-08-03 15:25 UTC
Labels: duplicate, feature request, x:postgresql
