### ISSUE TITLE
Suggestion: Highlighting selected text

### ISSUE THREAD

**Issue by YuriyTT** [dbeaver/dbeaver#4077] opened 2018-08-24 08:35 UTC
Hi, 

I have one suggestion, which would help in code reading. Similar to Oracle sql developer, one feature I really miss in dbeaver - highlighting selected text. 
When double-clicking on table name/selected text, it highlights all places where it is used in particular tab.

Sometimes, when the code is quite big, it's really time-consuming to find out where some table is used.

BR,
Yuriy

**Comment by serge-rider** [comment] 2018-08-29 14:42
Duplicate of #222

**Closed by serge-rider** 2018-08-29 14:42 UTC
Labels: duplicate, feature request
