### ISSUE TITLE
Setting to save the request to the export file in the form in which it was written

### ISSUE THREAD

**Issue by zkelo** [dbeaver/dbeaver#7273] opened 2019-11-21 19:48 UTC
**Is your feature request related to a problem? Please describe.**
Yes. When I exporting result to HTML file, the query that was executed for getting results writes in file as one line. I want some option that will make this thing customizable, so I can use it to save query "as is" as I wrote it in editor before

**Describe the solution you'd like**
Some checkbox in export results window with label "save formatted query" or toggle button with label like "save query in line <> save query as is"

**Describe alternatives you've considered**
Saving SQL script as *.sql file in project folder. But this solution is workaround, because I have some individual cases when I use the query one time and I don't know will I be use it in future. If I will need to reuse it I'll opening HTML and copying query from there. But if I will save every script then my script folder will have some hundred of thousands of files, so search for one script will be hard

**Additional context**
No

**Comment by kseniiaguzeeva** [comment] 2020-08-04 10:09
Sorry for the long answer and thank you for the suggestion.

**Comment by uslss** [comment] 2022-05-31 13:40
closed as a duplicate of #9136

**Closed by uslss** 2022-05-31 13:40 UTC
Labels: feature request, duplicate, xf:datatransfer, planned
