### ISSUE TITLE
MSSQL: Schemas organized by Owner - No longer able to access tables or views

### ISSUE THREAD

**Issue by Choens** [dbeaver/dbeaver#2769] opened 2018-01-10 15:09 UTC
My MSSQL (Microsoft SQL Server) connections have become less useful. 

- Old Behavior: When I opened the connection, I could see a list of databases.
    - When opened, I could see tables, views, etc.
    - I could open these and see my tables, view, etc.
- New Behavior: When I open the connection, I see a list of databases.
    - When opened, I am given a list of owners.
    - After opening an owner role, I am not able to see tables/views.
    - My user is not an owner, but I do have view access to all tables/views in the databases.
    - I can still run queries in DBeaver and when I log in using SSMS, everything continues to work as expected. My problem, whatever it is, is in DBeaver/my connection setup. It is not in my permissions, credentials, etc.
    - This all worked before Christmas.
    - When I updated DBeaver, it also updated the jTDS driver to 1.3.1
    - I also tried creating a new jTDS driver using the driver from the Fedora repository, and I get the same behavior with it.

Goal: I want to turn off this extra layer of complexity. I have tested this on Fedora Linux and Windows 10 using the jTDS driver (Linux and Wnidows) and the Microsoft Driver (Windows only) and I get the same behavior. I can still run queries, but the list of tables/views on the left is unusable, which makes it harder to write new queries.  😄 

This is a screen shot of the NEW behavior. I used to be able to see tables and views. Now I cannot, regardless of which owner I use.

![image](https://user-images.githubusercontent.com/424993/34778983-e8f9e570-f5ec-11e7-95c0-7ccf3fd43552.png)

Normally, I would not be able to upload an image, of one of our databases, but in this case since it isn't actually showing anything, I figure it can't hurt anything.

Because I can still run queries, I don't think this is a driver issue. It has something to do with how DBeaver is setting up / displaying the connection. That is, at least, my theory. Any help is greatly appreciated. I really dislike SSMS and I can only access it via a VM which is a clunky workflow.

**Comment by Choens** [comment] 2018-01-10 15:40
I forgot to mention:
- I observed the problem when using Community Editiion version 4.3.2 of DBeaver
- I deleted my config and installed 4.3.1, and was able to return to the expected behavior (Linux)
- I am still using the jTDS 1.3.1 driver, but with DBeaver 4.3.1, I am able to access tables, views, etc.

If anyone else stumbles onto this, downgrading to 4.3.1 is a viable work-around.

**Comment by serge-rider** [comment] 2018-01-10 17:01
Seems to be duplicate of #2750

**Closed by serge-rider** 2018-01-10 17:01 UTC
Labels: bug, duplicate
