### ISSUE TITLE
Data transfer: value transformers

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#12608] opened 2021-05-26 13:13 UTC
We need to allow to configure column value transformations. For export, import and direct data migration.

Transformation like: 
- convert number to string
- truncate string
- call some SQL function in INSERT statement
- etc

**Comment by tati-kru** [comment] 2021-07-05 09:40
Duplicate of #12889

**Closed as completed by tati-kru** 2021-07-05 09:40 UTC
Labels: duplicate, xf:datatransfer
