### ISSUE TITLE
Connection won't be kept alive when set up through a VPN

### ISSUE THREAD

**Issue by Lautenschlager-id** [dbeaver/dbeaver#11457] opened 2021-02-23 13:50 UTC
#### System information: 
- OS Version: Windows 10 Version / 10.0.19041 Build 19041
- DBeaver version: 7.3.5.202102151746

#### Connection specification:
- MySQL
- Remote connection using a VPN

#### Issue
For some reason that I'm unable to understand, the remote connection I'm using through a VPN is failing to keep the connection alive. Every query I perform requires the system to reconnect to the database, and I can't change values in the interface because it keeps saying "Error synchronizing data with database".

I tried to change every single timeout option and nothing has fixed this issue. __I started questioning if it wouldn't be an issue with DBeaver itself, since it works decently in other softwares such as Workbench.__ 

It also doesn't reconnect when this specific error occurs even though this option is enabled in preferences.

#### Logs
Whenever I execute a query:
![image](https://user-images.githubusercontent.com/26045253/108852707-b7a4c200-75c4-11eb-9e13-9b026ea7f2ec.png)

Whenever I try to change a table's value using the interface:
![image](https://user-images.githubusercontent.com/26045253/108852837-d5722700-75c4-11eb-9676-1e597ffc6559.png)

Looking forward a solution for this issue X_X Thanks in advance!

**Comment by kseniiaguzeeva** [comment] 2021-02-25 14:12
Thank you for the report. 
The similar tickets https://github.com/dbeaver/dbeaver/issues/9110 and https://github.com/dbeaver/dbeaver/issues/6903

**Comment by uslss** [comment] 2021-03-04 10:37
closed as a duplicate of #6903

**Closed as completed by uslss** 2021-03-04 10:37 UTC
Labels: duplicate
