### ISSUE TITLE
error thrown when updating multiple tables (related to other update bug)

### ISSUE THREAD

**Issue by we-sell-bags** [dbeaver/dbeaver#22528] opened 2024-01-22 03:16 UTC
### Description

you appeared to fix the bug in the new version related to the PK's

however

if you have a simple join of 2 tables and the tables are not ordered exactly the same the update results are wrong.
DBeaver Version

Version 23.3.3.202401211839
Operating System

12.7.2
Database and driver

postgres 15
Steps to reproduce

take two basic tables with a pk
in the second table make the join condition the first table pk

SELECT *
FROM customer , workers
where customer.id=partner_id

if you only edit data in ONE table, then the update succeeds, data goes into the correct record
however if you update the data in TWO separate tables on the SAME record line , you get an error thrown saying it cannot find the updated  column" in the other table.

### DBeaver Version

23.3.3.202401211839

### Operating System

12.7.2

### Database and driver

12.7.2
Database and driver

postgres 15

**Comment by we-sell-bags** [comment] 2024-01-22 03:38
name is a field in the  "customer" database and it displays ok & updates corectly, as long as you do not try to update another field in the secondary table "workers" in the same record.


`!ENTRY org.jkiss.dbeaver.model 4 0 2024-01-22 11:08:19.569
!MESSAGE ERROR: column "name" of relation "workers" does not exist
  Position: 80
!STACK 0
org.postgresql.util.PSQLException: ERROR: column "name" of relation "workers" does not exist
  Position: 80
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.executeStatement(ExecuteBatchImpl.java:310)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:178)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:822)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$2(ResultSetPersister.java:707)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:706)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:644)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by LonwoLonwo** [comment] 2024-02-08 08:56
Hello @we-sell-bags 

For now, it looks like this case: https://github.com/dbeaver/dbeaver/issues/16755

Do you have PK columns with the same names? If it is true, did you try to use an alias (another name) for one of them for the result set and try to update the data again?

**Comment by we-sell-bags** [comment] 2024-02-15 01:34
yes, our PK is generally called ID, policy.... and i have to work with what i've got.
but since you would have to distinguish ,between the tables, to prevent errors due to the parser being confused, it should not be an issue.

Really it is common for DB to have "born,updated,deleted,id" on multiple tables.

TBH... it's not a difficult case to  pull the tables metadata, then do a scan on the keys/fields to see if they Hash identically.
and if they do .. print a warning or branch the code.

But i don't see why an operation on a table, would associate another table col, with an insert based on the tables having the same PK.

**Comment by LonwoLonwo** [comment] 2024-02-19 15:01
I understand your concern.
And for me, it looks like a duplicate of https://github.com/dbeaver/dbeaver/issues/16755.

**Comment by we-sell-bags** [comment] 2024-02-20 02:06
here is the  sql to gen the tables

`-- Table: public.workers

-- DROP TABLE IF EXISTS public.workers;

CREATE TABLE IF NOT EXISTS public.workers
(
    id integer NOT NULL DEFAULT nextval('workers_id_seq'::regclass),
    born_timestamp timestamp with time zone NOT NULL,
    update_timestamp timestamp with time zone,
    total_workers integer,
    production_lines integer NOT NULL DEFAULT 0,
    monthly_cap integer NOT NULL DEFAULT 0,
    partner_id integer NOT NULL DEFAULT 0,
    CONSTRAINT workers_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.workers
    OWNER to test_only;

GRANT ALL ON TABLE public.workers TO test_only;`


and the next table
`-- Table: public.customer

-- DROP TABLE IF EXISTS public.customer;

CREATE TABLE IF NOT EXISTS public.customer
(
    id integer NOT NULL DEFAULT nextval('customer_id_seq'::regclass),
    born_timestamp timestamp with time zone NOT NULL,
    update_timestamp timestamp with time zone,
    name text COLLATE pg_catalog."default" NOT NULL,
    existing_customer boolean NOT NULL,
    image_id integer,
    status integer NOT NULL,
    current_screening_id integer,
    deleted integer NOT NULL DEFAULT 0,
    not_secured integer NOT NULL DEFAULT 0,
    contact_type integer NOT NULL DEFAULT 0,
    shortname_id text COLLATE pg_catalog."default" DEFAULT ''::text,
    alias_id text COLLATE pg_catalog."default" DEFAULT ''::text,
    CONSTRAINT customer_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.customer
    OWNER to test_only;

GRANT ALL ON TABLE public.customer TO test_only;
`

**Comment by iraidaa** [comment] 2024-03-28 12:08
Hi @we-sell-bags,

Can we clarify the steps to reproduce the issue with you, please?

1. Create table _workers_ with the query you provided and populate with some data
2.  Create table _customers_ with the query you provided and populate with some data
3. Run the _SELECT *
FROM customer , workers
where customer.id=partner_id_ query and get an expected result
4. Edit some fields within a particular record in the _customers_ table and save the change
5. Edit some fields in the _workers_ table of a particular record  where customer.id=partner_id and save the change
6.  Run the  _SELECT *
FROM customer , workers
where customer.id=partner_id_ and get an error

If so, we do not reproduce the issue in CE 24.0.1. Could you please check it in the latest version https://dbeaver.io/download/?

If we have missed any details, please correct our steps.

**Comment by we-sell-bags** [comment] 2024-04-05 01:53
Hi, 
It might be.......
I reported one first ,then you did an update and it disappeared for THAT specific boundary case, but then it reappeared on another boundary case as outlined.


Ill take a new look at it to see if it is gone.

Ok i had a preliminary look. and it does not look good..... there is another "bug"
nope this is very dangerous.

Specifically if you have multiple tables with "id" when you do a  "select *", you end up with a table with multiple "id" fields and no way to distinguish what table they came from.

really in this sort of case, the headers should be marked, or that specific duplicate should be prefixed by the original table name.

![image](https://github.com/dbeaver/dbeaver/assets/25189116/11aae926-bebc-46cb-8912-a72fcd308733)

**Comment by E1izabeth** [comment] 2024-04-25 13:24
Thank you for detailed explanation. I'm closing this issue as a duplicate of #16755
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-04-25 13:24 UTC
Labels: duplicate, xf:sql
