### ISSUE TITLE
I request to be able to create triggers, procedures and sequences in Firebird through the Bbeaver Enterprise interface.

### ISSUE THREAD

**Issue by buhlerax** [dbeaver/dbeaver#16837] opened 2022-06-20 04:39 UTC
I request to be able to create triggers, procedures and sequences in Firebird through the Bbeaver Enterprise interface.
In the current version of Dbeaver 22.1.0 we can only see triggers, procedures and views.
We were unable to create through the interface.

![procedure](https://user-images.githubusercontent.com/6946344/174526209-01572172-bf0c-452f-af4b-4b29864cf6d5.png)
![senquences](https://user-images.githubusercontent.com/6946344/174526250-39d8c29f-bda0-489b-a237-f74051ae2597.png)
![trigger](https://user-images.githubusercontent.com/6946344/174526265-77a860ee-8794-4244-917b-ca13f63f53c4.png)

**Comment by uslss** [comment] 2022-06-20 09:10
thanks for the suggestion
closed as a duplicate of #14225

**Closed as completed by uslss** 2022-06-20 09:10 UTC
Labels: x:firebird, duplicate
