### ISSUE TITLE
Data Transfer on Mysql doesn't handle reserved words correctly

### ISSUE THREAD

**Issue by rijnhard** [dbeaver/dbeaver#13571] opened 2021-08-17 19:28 UTC
#### System information: 
- Operating system (distribution) and version: Linux mint 20.2
- DBeaver version: Version 21.1.4.202108020335
- Additional extensions: None

#### Connection specification:
- Database name and version: Mysql 5.5 / Mysql 5.6
- Driver name: Mysql 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes, SSH

#### Describe the problem you're observing:
Initiate data transfer between two Mysql 5 instances when a reserved word is used as a column name.
![Screenshot from 2021-08-17 21-20-47](https://user-images.githubusercontent.com/4290536/129787969-6fb12d05-073a-4776-9746-1fc60515f8c3.png)
![Screenshot from 2021-08-17 21-21-22](https://user-images.githubusercontent.com/4290536/129787986-00948333-d229-4e49-8c1b-00d228e1f6d2.png)

#### Include any warning/errors/backtraces from the logs
```
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_ZA
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Aug 17 21:21:00 SAST 2021
Can't find target attribute [sequence]

org.jkiss.dbeaver.model.exec.DBCException: Can't find target attribute [sequence]
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchStart(DatabaseTransferConsumer.java:216)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:196)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:254)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:165)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.ui.pages.database.PreviewMappingDialog.loadImportPreview(PreviewMappingDialog.java:159)
	at org.jkiss.dbeaver.tools.transfer.ui.pages.database.PreviewMappingDialog.lambda$1(PreviewMappingDialog.java:120)
	at org.jkiss.dbeaver.ui.dialogs.BaseProgressDialog.lambda$0(BaseProgressDialog.java:99)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by LonwoLonwo** [comment] 2021-08-18 05:20
Hi @rijnhard 
Thanks for the bug report.
This is a duplicate of https://github.com/dbeaver/dbeaver/issues/13402
Will be fixed in DBeaver 21.2.0

**Closed as completed by LonwoLonwo** 2021-08-18 05:20 UTC
Labels: duplicate
