### ISSUE TITLE
Crash loop on startup after installing Office plugin

### ISSUE THREAD

**Issue by maphew** [dbeaver/dbeaver#4791] opened 2018-12-11 20:09 UTC
Dbeaver CE on Win10x64, installed with Chocolatey. I've had v5.2.3 installed for about a month, zero issues with it (awesome program!) until I installed [Extension Office][0] today. Install went through all it's steps without any apparent problem. 

At end when prompted to Restart I said yes. The splash screen shows, then disappears, then shows again, then disappears, then shows... forever. I had to use `pskill dbeaver` from Sys Internals to stop it (in Task Manager it's a whack-a-beaver game to nab and press delete on the process before it disappears).

I upgraded to v5.3.0.201812092025 using `choco upgrade dbeaver`. After this dbeaver launched normally, and asked if I wished to also import and uprade the Office extension. I said yes and checked the box to fetch latest. At end I said no to automatic restart and closed dbeaver manually.

On next launch the crash looping resumed. While looping the `.log` and `dbeaver-debug.log` files under `%USERPROFILE%\.dbeaver4` are not updated.

I renamed `.dbeaver4` to something else, and then `.dbeaver-drivers`: No difference in either case.

I finally managed to get Dbeaver back again my renaming `%USERPROFILE%\.eclipse\org.jkiss.dbeaver.product_5.3.0_1535670467_win32_win32_x86_64` and then cancelling the plugin install/upgrade procedure.

[0]: https://github.com/dbeaver/dbeaver/wiki/Extension-Office
[9]: https://github.com/dbeaver/dbeaver/blob/devel/CONTRIBUTING.md

_((Note: issue template says to read [contributing][9] first, but that document is empty))_

**Comment by serge-rider** [comment] 2018-12-11 22:18
It is a known Eclipse bugs: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=192623
https://bugs.eclipse.org/bugs/show_bug.cgi?id=232191
https://bugs.eclipse.org/bugs/show_bug.cgi?id=238800

I saw such issue a couple of times (VERY annoying). But is uneasy to reproduce this.
Looks like this happens only after some extension install in admin (root) mode.

**Comment by serge-rider** [comment] 2018-12-11 22:30
Tried to reproduce this in different run modes, different extensions install, etc. No luck.

If you will see such error again (and it will reproduce every time you start DBeaver) - could you archive whole DBeaver install directory + org.jkiss.dbeaver.product_XXX directory and send me on serge@jkiss.org? 
Generally these folders doesn't contain any secured/personal data, only DBeaver binaries.

**Comment by p91paul** [comment] 2018-12-12 08:33
I reproduced this bug. I sent you an email with a MEGA link to the archives. 

Renaming %USERPROFILE%\.eclipse\org.jkiss.dbeaver.product_5.3.0_1535670467_win32_win32_x86_64 worked: DBeaver will start, ask me to copy office plugin from previous installation. Cancelling that leads to a working workspace.

**Comment by p91paul** [comment] 2018-12-12 08:45
Reinstalling the office plugin after removing the folder triggers the issue again, so my archives should provide you useful information.
I also added the "org.jkiss.dbeaver.product_5.2.5_XXX" folder because I suppose that when I remove 5.3.0 folder it copies info from the 5.2.5 folder.

Do you have a workaround to be able to install the office plugin again without breaking? I can live without it, but I must admit it's useful.

**Comment by serge-rider** [comment] 2018-12-12 12:08
In my case removing org.jkiss.dbeaver.product* plus removing org.eclipse.platform* folders from .eclipse resolved the issue. You can even remove whole .eclipse folder - it do not contain anything important except caches and installed extensions.

I think some mess happens in configuration after multiple DBeaver version upgrades which also include base Eclipse platform version upgrade.

**Comment by p91paul** [comment] 2018-12-12 16:44
I would not recommend removing .eclipse folder as other eclipse-based programs (including eclipse itself) might be using it. Will try removing org.eclipse.platform.

**Comment by maphew** [comment] 2018-12-12 20:49
I removed `.eclipse` (I don't use any other Eclipse products) and reinstalled the office plugin: crash looping. I'll send archive too, but that might have to wait until tomorrow as i expect to be away from the computer for rest of day.

**Comment by serge-rider** [comment] 2018-12-12 21:10
@maphew thanks for checking this. So this seems to be unrelated to .eclipse folder contents.
Then, probably something is wrong with DBeaver installation folder or workspace (less likely).
Unfortunately I still can't reproduce this on my end - even with Paul's installation files.

To validate that workspace is not related you could rename .dbeaver4 folder (or start `dbeaver.exe with -data path-to-empty-workspace` parameter).

If so then something is definitely wrong with installation folder. If DBeaver is in `Program Files/DBeaver` then this folder is write protected and generally shouldn't contain anything but the files copied there during installation. But in fact the folder will be modified if you will run DBeaver as administrator (this may happen if you run DBeaver right from the installer for example).

By default folder configuration contains only two sub-folders:
- org.eclipse.equinox.simpleconfigurator
- org.eclipse.update
an file config.ini

The rest is created during runtime and can be deleted. So, you could try this. Evil should be somewhere over there.

**Comment by p91paul** [comment] 2018-12-12 22:35
I sent you my installation directory as well, so you should be able to check your hypotesys.
Your reasoning is sound, as I did install dbeaver in program files, I did launch it from the installer and most importantly the issue arose only after i closed it and launched it from a standard launcher!

**Comment by p91paul** [comment] 2018-12-20 10:58
I had those folders in my `Program Files/DBeaver/configuration/` directory:
![immagine](https://user-images.githubusercontent.com/2157006/50280697-7eed8900-044d-11e9-954c-35bcc18fbe5b.png)

Removing them did not solve the issue.

Reinstalling DBeaver, paying attention to NOT select the option to launch it at the end of the installation **did solve it**. So avoiding to launch DBeaver from the installer is a workaround, and you should be able to reproduce it using the installation directory I shared with you.

**Comment by serge-rider** [comment] 2018-12-20 12:03
Thank you for testing this.
I think we should remove "Launch DBeaver" option from installer. Because it launches DBeaver with admin permissions and thus makes a configuration mess.

**Closed** 2018-12-20 21:00 UTC
Labels: bug, ready for qa, xo:eclipse

**Comment by gagsa69** [comment] 2019-04-24 12:24
i also did suffer from this affliction! every time i did install a plugin the restart loop occured. I did reinstall dbeaver but just for my user ( not for everyone on the computer ) and now it's working well.

**Comment by Rich28** [comment] 2019-04-24 13:52
I've also ran into this problem, which forces the needed to restart Windows.  As gagsa69 says there is a work around of reinstalling dbeaver as 'my user' but this isn't ideal

**Comment by mdpublic** [comment] 2019-06-18 15:39
@serge-rider ... I'm seeing same behavior as @gagsa69 .  I have v6.0x installed under my user profile, and installing Office extension works fine.  I have v6.1x installed for all users and installing Office extension puts me in launch loop that can only be cleared by rebooting.  v6.0x is still launching fine...every time I try to launch v6.1x I get launch loop.
Guess I'll try re-installing latest version under my profile.

**Comment by tomiyoshi-smartvalue** [comment] 2020-03-03 00:42
The startup loop happened to me too and I solved it by deleting the plugin folder as Rich28 said. Thank you Rich28.

**Comment by Spoelle** [comment] 2020-03-06 15:17
Thanks Rich28, works for me too.

**Comment by GiannisDimitriou** [comment] 2020-04-14 19:25
@serge-rider I am experiencing the same issue as well with the plugin for git.
Don't know much of what may be the issue but I noticed the below weird behaviour in .eclipse folder.

After updating DBeaver to the latest version all other org.jkiss.dbeaver.product_* folders since the first version I had installed this plugin was modified.
Dont know if that is helpful just posting it here
![image](https://user-images.githubusercontent.com/47314887/79265394-b5e77980-7e9e-11ea-85b6-b7fe4c63de33.png)

**Comment by nkgiovannivl** [comment] 2020-04-22 20:36
> Similar environment Windows 10x64, installation from executable file in Program Files. I also did suffer from this affliction! every time i did install a plugin the restart loop occured. I did reinstall dbeaver but just for my user ( not for everyone on the computer ) and now it's working well. I did install some plugins with this type of installation without any problem.

Thanks! after install just for my user in my work laptop (i'm not have admin account on Windows) the restart loop does not happen anymore!

**Comment by bnserig** [comment] 2020-05-04 14:05
Update from 7.0.3 to 7.0.4. Installation in Program Files (Win 10 x64).
Startup ok.
Update plugins (Office & Devstyles).
After that stuck in startup loop.
I had to reboot my computer 3 times (I don't know why but it worked).

**Comment by mrstig** [comment] 2020-12-14 07:44
Another data point: I got the startup loop after installing the Office plugin, and resolved the problem by resetting permissions on the folder %USERPROFILE%\.eclipse\org.jkiss.dbeaver.product_7.2.4_1535670467_win32_win32_x86_64 - that is, opening the properties for that folder, clicking the Advanced... button on the Security tab, selecting the checkbox "Replace all child object permission entries with inheritable permission entries from this object" and clicking through OK and the warning. Note that "org.jkiss.dbeaver.product_7.2.4_1535670467_win32_win32_x86_64" should be replaced with the name corresponding to the version you have installed.

**Comment by hennie7863** [comment] 2021-04-14 12:00
Same problem here. After installation Git repository browser, a half hour rebooting and it is finished..

**Comment by mk1tools** [comment] 2021-05-19 12:54
Same problem. After each DBeaver upgrade, I install Office plugin. Then DBeaver start to loop on splash screen.
I install DBeaver for "anyone" on Windows 10.
I found this workaround.
1) upgrade Dbeaver
2) Start Dbeaver and install Office plugin, without automatic restart. Close Dbeaver.
3) Start DBeaver "as administrator" and install Office plugin, without automatic restart. Close Dbeaver.
4) Start DBeaver "as administrator". Close Dbeaver.
5) Start DBeaver normally

**Comment by lotnikov** [comment] 2021-10-06 08:50
endless DBeaver restart loop after install office plugin 
version 21.2.2.202110030714
installed for all users, win10x64
after 2 system restarts, I found this page, thanks to "mk1tools" - I start Dbeaver as administrator, and it worked
then I try to run it again as normal user - and it also works, the plugin also works - I can export data to excel

**Comment by pjom** [comment] 2022-03-08 09:14
@mk1tools' workaround's still rocking.
I've been having issues with the Darkest Dark theme from DevStyle and the workaround solved the issue.
I'm taking note of it for next time.
Thanks!
