### ISSUE TITLE
DBeaver postgresql debugger

### ISSUE THREAD

**Issue by pkfox** [dbeaver/dbeaver#10846] opened 2021-01-01 13:54 UTC
Hi all has anyone here got the debugger working for postgresql ? I've tried several tutorials and can't get it to work

**Comment by hotsmile** [comment] 2021-01-11 11:31
dbeaver 7.3 version, but i want to install the sql-debugger pluggin in eclipse market ,but i can't install ,notice me that my version is higher!!! ,the same to you!!

**Comment by uslss** [comment] 2021-01-14 19:57
thanks for the report.

seems to be a duplicate of #10192

**Closed as completed by uslss** 2021-01-14 19:57 UTC
Labels: duplicate, xf:debug
