### ISSUE TITLE
Silent crash at startup

### ISSUE THREAD

**Issue by Masterxilo** [dbeaver/dbeaver#4812] opened 2018-12-17 14:05 UTC
I click the executable, the splash screen comes up, then it goes away.

What is going on?

Make this GUI open a console and print some status information as the thing is loading and keep it open when it crashes. It will help everyone in the long term...
We don't want to be blind and ignorant about the software we use.

**Comment by ilovesusu** [comment] 2018-12-18 03:20
i download Linux Debian package 64 bit (installer) and install it,but silent crash at startup,
client:dbeaver5.3.0 
os:Debian Testing
```
$ dbeaver 
2018-12-18 11:17:22.937 - Create display
2018-12-18 11:17:23.241 - > Start org.jkiss.dbeaver.core [5.3.0.201812092025]
2018-12-18 11:17:23.243 - DBeaver 5.3.0.201812092025 is starting
2018-12-18 11:17:23.244 - OS: Linux 4.18.0-3-amd64 (amd64)
2018-12-18 11:17:23.244 - Java version: 11.0.1 by Oracle Corporation (64bit)
2018-12-18 11:17:23.244 - Install path: '/usr/share/dbeaver'
2018-12-18 11:17:23.245 - Instance path: 'file:/home/susu/.dbeaver4/'
2018-12-18 11:17:23.245 - Memory available 66Mb/1024Mb
2018-12-18 11:17:23.255 - Starting RMI server at 60778
2018-12-18 11:17:23.291 - Run workbench
2018-12-18 11:17:23.297 - > Start org.eclipse.e4.ui.workbench.swt [0.14.101.v20170710-1119]
2018-12-18 11:17:23.298 - > Start org.eclipse.e4.core.services [2.1.0.v20170407-0928]
2018-12-18 11:17:23.300 - > Start org.eclipse.e4.core.contexts [1.6.0.v20170322-1144]
2018-12-18 11:17:23.307 - > Start org.eclipse.e4.ui.services [1.3.0.v20170307-2032]
2018-12-18 11:17:23.320 - Internal error in workbench lifecycle
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more
2018-12-18 11:17:23.325 - DBeaver is stopping
2018-12-18 11:17:23.325 - Stop RMI server
2018-12-18 11:17:23.344 - < Stop org.jkiss.dbeaver.ext.mssql [1.0.92.201812092025]
2018-12-18 11:17:23.345 - < Stop org.jkiss.dbeaver.ext.oracle [2.1.83.201812092025]
2018-12-18 11:17:23.345 - < Stop org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.4.201812092025]

```

**Comment by jprusik** [comment] 2018-12-18 15:06
I've installed `5.3.0.201812092025` on MacOS with homebrew `brew cask install dbeaver-community`. When I launch from Terminal ( `/Applications/DBeaver.app/Contents/MacOS/dbeaver` ), it runs fine, but crashes on launch when opening the App via the system ui (finder, dock, etc).

**Comment by serge-rider** [comment] 2018-12-18 22:10
Duplicate of #4765

**Closed by serge-rider** 2018-12-18 22:10 UTC
Labels: bug, duplicate
