### ISSUE TITLE
Error with autocomplete on 5.2.3

### ISSUE THREAD

**Issue by fgonzalez-cespi** [dbeaver/dbeaver#4473] opened 2018-10-23 12:07 UTC
After upgrading to 5.2.3 I have encountered an error when using the autocompletion: after the autocompleted part, it pastes the text that was used to autocomplete. E.g:

![1](https://user-images.githubusercontent.com/5173841/47359296-c3091b00-d6a2-11e8-8deb-f018c42d74eb.png)

After hitting enter on the first option, it yields this:

![2](https://user-images.githubusercontent.com/5173841/47359319-d5835480-d6a2-11e8-8e09-22d7742398b1.png)

As you can see, the autocompleted text is inserted at correct position but then the text that was used to show the autocompletions is kept and stays after the autocompleted text.

I use windows 10 pro 64

**Comment by infectormp** [comment] 2018-10-23 12:15
Related to https://github.com/dbeaver/dbeaver/issues/4458, https://github.com/dbeaver/dbeaver/issues/4469

**Comment by serge-rider** [comment] 2018-10-23 12:54
Duplicate of #4450
Already fixed in 5.2.3 (just re-download it)

**Closed by serge-rider** 2018-10-23 12:54 UTC
Labels: bug, duplicate

**Comment by ascendhans** [comment] 2018-10-23 12:56
I had the same issue when i updated Dbeaver to 5.2.3.
All you need to do is check the Replace Current Word checkbox in SQL Completion option.

Screenshot below:
![image](https://user-images.githubusercontent.com/38669892/47362060-22fac400-d699-11e8-9137-9c86fdae5440.png)
