### ISSUE TITLE
DBEAVER 7.2.3 "case when" in "group by" function

### ISSUE THREAD

**Issue by h-point** [dbeaver/dbeaver#10193] opened 2020-10-28 14:43 UTC
Hello,

I'm using Dbeaver 7.2.3 and I get an "invalid caracter error" when launching this request:

create table tmp as
select
case when plat.plateform_grp='Web' then 'web' else 'other' end as web_plat
from dwh.DIM_PLATEFORM plat
group by
case when plat.plateform_grp='Web' then 'web' else 'other' end;

I get this error when using a "case when" in a "group by" function.
It used to work before I upgraded my 6.3.3 version into 7.2.3.
And it works without the ; at the end.

Any idea how to manage it ?

**Comment by kseniiaguzeeva** [comment] 2020-11-02 09:15
Please tell your database

**Comment by h-point** [comment] 2020-11-02 15:38
Oracle 11gR2

**Comment by kseniiaguzeeva** [comment] 2020-11-03 12:14
Looks like a bug. Thank you for the report.
The query can be used in HR Oracle 12 to reproduce:
```
create table tmp as
select
case
    when "Date" > "CURRENT_Time" then 1
    when "Date" <= "CURRENT_Time" then 2
    else 3
 END as web_plat
from HR.GROUP_BY_CASE_WHEN
group by (case
    when "Date" > "CURRENT_Time" then 1
    when "Date" <= "CURRENT_Time" then 2
    else 3
 end)
```

**Comment by kseniiaguzeeva** [comment] 2020-12-09 10:27
Cannot reproduce anymore in 7.3.1 EA. Most probably was fixed in scope of another ticket. Please try https://dbeaver.io/files/ea/

Feel free to reopen the ticket, if some case still can be reproduced.

**Closed by kseniiaguzeeva** 2020-12-09 10:27 UTC
Labels: bug, x:oracle
