### ISSUE TITLE
Column delete operation generates a wrong DDL query

### ISSUE THREAD

**Issue by imarat88** [dbeaver/dbeaver#6682] opened 2019-09-05 10:56 UTC
#### System information: 
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

- DBeaver version 6.1.5.201908201218
- Additional extensions None

#### Connection specification:
- Database name and version SQL SERVER
- Driver name jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Column delete operation generates a wrong DDL query.
ALTER TABLE [ColumnName] DROP COLUMN  [ColumnName]  GO
#### Steps to reproduce, if exist:
Delete column
Save
#### Include any warning/errors/backtraces from the logs
Cannot find the object [ColumnName] because it does not exist or you do not have permissions.

**Comment by serge-rider** [comment] 2019-09-05 16:02
Duplicate of #6662
Thanks for the bug report anyway

**Closed by serge-rider** 2019-09-05 16:02 UTC
Labels: bug, duplicate
