### ISSUE TITLE
Can't change background color in Dark Theme

### ISSUE THREAD

**Issue by ClodoaldoPinto** [dbeaver/dbeaver#7925] opened 2020-02-17 12:29 UTC
DBeaver 6.3.4. Windows 10 1709. Dark Theme. I want the background color to be black or blacker.

When I try to change the background color for the text editor this is what happens. When I do it for the first time I click on **`Apply`** and the background color changes but when I click **`Apply and Close`** it reverts to what it was. When I do it for the second time not even **`Apply`** works.

The path I'm trying is `Preferences -> General -> Editors -> Text Editors -> Appearance color options -> Background color -> Color`

![image](https://user-images.githubusercontent.com/1433209/74653577-39b70b00-5167-11ea-8ec0-261d13bf86c9.png)

**Comment by uslss** [comment] 2020-02-17 14:07
thanks for the bug report

**Comment by serge-rider** [comment] 2020-03-05 11:34
Duplicate of #7540

**Closed by serge-rider** 2020-03-05 11:34 UTC
Labels: bug, duplicate
