### ISSUE TITLE
[jTDS] data column returns as  [ClobImpl]

### ISSUE THREAD

**Issue by MadRay** [dbeaver/dbeaver#4694] opened 2018-11-27 08:19 UTC
Hello, Devs.

I'm experiencing problems with selecting text columns (varchar, ntext, xml) on last build. Data returns as [ClobImpl]

Test query: **select top 1 column  from table**
Returns: **[ClobImpl]**

Casting column as it's type helps.
Test query: **select top 1 cast(column as varchar)  from table**
Returns: **Column Data**

Dbeaver -   5.2.5.201811181655 (19 November 2018)
Package - 64bit RPM
jtds -  Tried 1.3.1 and 1.2.6

**Comment by serge-rider** [comment] 2018-11-27 18:56
Duplicate of #4656

**Closed by serge-rider** 2018-11-27 18:56 UTC
Labels: bug, duplicate, x:mssql

**Comment by erickneverson** [comment] 2020-08-17 14:58
This issue has resurfaced in Version 7.1.5.202008170457 Mac (DMG download).  The first batch of results look normal (JSON). The next batch of results (scroll down) turns everything into ClobImpl. Shall I open a new issue?
