### ISSUE TITLE
Autocomplete doesn't work for select-queries with CTE

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#36015] opened 2024-10-21 15:17 UTC
### Description

The query with CTE doesn't show any autocomplete on Ctrl + Space after the character *

https://github.com/user-attachments/assets/2ad96629-7232-4399-925c-bc35396a1037

- use the query:
```
--query with CTE
with ct as (
    select r.*
    from rental as r
)
select *
from ct;

```
- use Ctrl + Space after character * to show autocomplete

By the way, there is no problem for DBever to show autocomplete for queries with derived tables, which are slightly similar to CTE:

```
select *
from (
    select r.*
    from rental as r
) as r;

```

### DBeaver Version

Enterprise Edition 24.2.4-202410172322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by E1izabeth** [comment] 2024-10-22 09:15
Thanks for the bug report.
I'm closing it as a duplicate of #8949

**Closed as not planned** 2024-10-22 09:16 UTC
Labels: duplicate, xf:sql editor
