### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/annotation/PreDestroy after upgrade to dbeaver 5.3.0

### ISSUE THREAD

**Issue by poor-man** [dbeaver/dbeaver#4765] opened 2018-12-10 11:01 UTC
Hello

I upgraded DB from 5.2.5 (working perfectly) to 5.3.0 this morning and it crashes at startup

Searching for solutions, I tried to specify the VM path at dbeaver.ini with:
-vm /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin
but I get the same error.

I'm using Java 11.0.1

This is what I got from .dbeaver4/.metadata/.log

!SESSION 2018-12-10 10:57:35.427 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=es_ES
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.e4.ui.workbench 4 0 2018-12-10 10:57:38.073
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.lang.NoClassDefFoundError: javax/annotation/PreDestroy
	at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:450)
	at org.eclipse.e4.core.internal.di.Requestor.disposed(Requestor.java:156)
	at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:78)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:111)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(TrackableComputationExt.java:74)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:178)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:99)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:141)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
	at org.eclipse.osgi.container.Module.doStop(Module.java:634)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.annotation.PreDestroy cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 21 more

**Comment by serge-rider** [comment] 2018-12-10 11:10
We had to revert to Eclipse Oxygen as our base platform (as latest one was too buggy). Oxygen doesn't support Java 11.

Workarounds:
- On Windows/MacoOS use DBeaver installers with bundled Java
- On Linux install Java 9 or Java 10
- Patch configuration in dbeaver.ini (see #4308)

We'll add support in the next CE versions once new version of Eclipse platform will be released (hopefully it won't be so buggy).

**Comment by poor-man** [comment] 2018-12-10 11:20
Patch configuration in dbeaver.ini worked for me.

I hope Eclipse starts working all these bugs in Oxygen soon.

Thanks!

**Comment by hugorn** [comment] 2018-12-10 13:17
> Patch configuration in dbeaver.ini worked for me.
> 
> I hope Eclipse starts working all these bugs in Oxygen soon.
> 
> Thanks!


can you share how your dbeaver.ini file got?

**Comment by hugorn** [comment] 2018-12-10 13:30
SO - Deepin Linux

hugo@hugo-PC:~/Documents$ java -version
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

hugo@hugo-PC:~/Documents$ cat /usr/share/dbeaver/dbeaver.ini
-startup
plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.551.v20171108-1834
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m
-XstartOnFirstThread

hugo@hugo-PC:~/Documents$ dbeaver
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
2018-12-10 10:28:10.058 - Create display
2018-12-10 10:28:11.350 - > Start org.jkiss.dbeaver.core [5.3.0.201812092025]
2018-12-10 10:28:11.362 - DBeaver 5.3.0.201812092025 is starting
2018-12-10 10:28:11.363 - OS: Linux 4.15.0-29deepin-generic (amd64)
2018-12-10 10:28:11.363 - Java version: 10.0.2 by Oracle Corporation (64bit)
2018-12-10 10:28:11.364 - Install path: '/usr/share/dbeaver'
2018-12-10 10:28:11.364 - Instance path: 'file:/home/hugo/.dbeaver4/'
2018-12-10 10:28:11.365 - Memory available 77Mb/1024Mb
2018-12-10 10:28:11.407 - Starting RMI server at 30970
2018-12-10 10:28:11.544 - Run workbench
2018-12-10 10:28:11.550 - > Start org.eclipse.e4.ui.workbench.swt [0.14.101.v20170710-1119]
2018-12-10 10:28:11.551 - > Start org.eclipse.e4.core.services [2.1.0.v20170407-0928]
2018-12-10 10:28:11.552 - > Start org.eclipse.e4.core.contexts [1.6.0.v20170322-1144]
2018-12-10 10:28:11.561 - > Start org.eclipse.e4.ui.services [1.3.0.v20170307-2032]
2018-12-10 10:28:11.610 - Internal error in workbench lifecycle
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 25 more
2018-12-10 10:28:11.618 - DBeaver is stopping
2018-12-10 10:28:11.618 - Stop RMI server
2018-12-10 10:28:11.664 - < Stop org.jkiss.dbeaver.ext.mssql [1.0.92.201812092025]
2018-12-10 10:28:11.665 - < Stop org.jkiss.dbeaver.ext.oracle [2.1.83.201812092025]
2018-12-10 10:28:11.667 - < Stop org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.4.201812092025]

**Comment by serge-rider** [comment] 2018-12-10 13:32
@hugorn Add following txt in the beginning of dbeaver.ini:

```
org.osgi.framework.system.packages = \
 javax.accessibility,\
 javax.activation,\
 javax.activity,\
 javax.crypto,\
 javax.crypto.interfaces,\
 javax.crypto.spec,\
 javax.imageio,\
 javax.imageio.event,\
 javax.imageio.metadata,\
 javax.imageio.plugins.bmp,\
 javax.imageio.plugins.jpeg,\
 javax.imageio.spi,\
 javax.imageio.stream,\
 javax.jws,\
 javax.jws.soap,\
 javax.lang.model,\
 javax.lang.model.element,\
 javax.lang.model.type,\
 javax.lang.model.util,\
 javax.management,\
 javax.management.loading,\
 javax.management.modelmbean,\
 javax.management.monitor,\
 javax.management.openmbean,\
 javax.management.relation,\
 javax.management.remote,\
 javax.management.remote.rmi,\
 javax.management.timer,\
 javax.naming,\
 javax.naming.directory,\
 javax.naming.event,\
 javax.naming.ldap,\
 javax.naming.spi,\
 javax.net,\
 javax.net.ssl,\
 javax.print,\
 javax.print.attribute,\
 javax.print.attribute.standard,\
 javax.print.event,\
 javax.rmi,\
 javax.rmi.CORBA,\
 javax.rmi.ssl,\
 javax.script,\
 javax.security.auth,\
 javax.security.auth.callback,\
 javax.security.auth.kerberos,\
 javax.security.auth.login,\
 javax.security.auth.spi,\
 javax.security.auth.x500,\
 javax.security.cert,\
 javax.security.sasl,\
 javax.sound.midi,\
 javax.sound.midi.spi,\
 javax.sound.sampled,\
 javax.sound.sampled.spi,\
 javax.sql,\
 javax.sql.rowset,\
 javax.sql.rowset.serial,\
 javax.sql.rowset.spi,\
 javax.swing,\
 javax.swing.border,\
 javax.swing.colorchooser,\
 javax.swing.event,\
 javax.swing.filechooser,\
 javax.swing.plaf,\
 javax.swing.plaf.basic,\
 javax.swing.plaf.metal,\
 javax.swing.plaf.multi,\
 javax.swing.plaf.nimbus,\
 javax.swing.plaf.synth,\
 javax.swing.table,\
 javax.swing.text,\
 javax.swing.text.html,\
 javax.swing.text.html.parser,\
 javax.swing.text.rtf,\
 javax.swing.tree,\
 javax.swing.undo,\
 javax.tools,\
 javax.xml,\
 javax.xml.bind,\
 javax.xml.bind.annotation,\
 javax.xml.bind.annotation.adapters,\
 javax.xml.bind.attachment,\
 javax.xml.bind.helpers,\
 javax.xml.bind.util,\
 javax.xml.crypto,\
 javax.xml.crypto.dom,\
 javax.xml.crypto.dsig,\
 javax.xml.crypto.dsig.dom,\
 javax.xml.crypto.dsig.keyinfo,\
 javax.xml.crypto.dsig.spec,\
 javax.xml.datatype,\
 javax.xml.namespace,\
 javax.xml.parsers,\
 javax.xml.soap,\
 javax.xml.stream,\
 javax.xml.stream.events,\
 javax.xml.stream.util,\
 javax.xml.transform,\
 javax.xml.transform.dom,\
 javax.xml.transform.sax,\
 javax.xml.transform.stax,\
 javax.xml.transform.stream,\
 javax.xml.validation,\
 javax.xml.ws,\
 javax.xml.ws.handler,\
 javax.xml.ws.handler.soap,\
 javax.xml.ws.http,\
 javax.xml.ws.soap,\
 javax.xml.ws.spi,\
 javax.xml.ws.spi.http,\
 javax.xml.ws.wsaddressing,\
 javax.xml.xpath,\
 org.ietf.jgss,\
 org.omg.CORBA,\
 org.omg.CORBA_2_3,\
 org.omg.CORBA_2_3.portable,\
 org.omg.CORBA.DynAnyPackage,\
 org.omg.CORBA.ORBPackage,\
 org.omg.CORBA.portable,\
 org.omg.CORBA.TypeCodePackage,\
 org.omg.CosNaming,\
 org.omg.CosNaming.NamingContextExtPackage,\
 org.omg.CosNaming.NamingContextPackage,\
 org.omg.Dynamic,\
 org.omg.DynamicAny,\
 org.omg.DynamicAny.DynAnyFactoryPackage,\
 org.omg.DynamicAny.DynAnyPackage,\
 org.omg.IOP,\
 org.omg.IOP.CodecFactoryPackage,\
 org.omg.IOP.CodecPackage,\
 org.omg.Messaging,\
 org.omg.PortableInterceptor,\
 org.omg.PortableInterceptor.ORBInitInfoPackage,\
 org.omg.PortableServer,\
 org.omg.PortableServer.CurrentPackage,\
 org.omg.PortableServer.POAManagerPackage,\
 org.omg.PortableServer.POAPackage,\
 org.omg.PortableServer.portable,\
 org.omg.PortableServer.ServantLocatorPackage,\
 org.omg.SendingContext,\
 org.omg.stub.java.rmi,\
 org.w3c.dom,\
 org.w3c.dom.bootstrap,\
 org.w3c.dom.css,\
 org.w3c.dom.events,\
 org.w3c.dom.html,\
 org.w3c.dom.ls,\
 org.w3c.dom.ranges,\
 org.w3c.dom.stylesheets,\
 org.w3c.dom.traversal,\
 org.w3c.dom.views,\
 org.w3c.dom.xpath,\
 org.xml.sax,\
 org.xml.sax.ext,\
 org.xml.sax.helpers
```

**Comment by poor-man** [comment] 2018-12-10 13:58
> > Patch configuration in dbeaver.ini worked for me.
> > I hope Eclipse starts working all these bugs in Oxygen soon.
> > Thanks!
> 
> can you share how your dbeaver.ini file got?

I didn't modify the default dbeaver.ini

> -startup
> plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
>--launcher.library
> plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.551.v20171108-1834
> -vmargs
> -XX:+IgnoreUnrecognizedVMOptions
> --add-modules=ALL-SYSTEM
> -Xms64m
> -Xmx1024m

I paste what serge-rider is saying in my configuration/config.ini (as the [#4308](https://github.com/dbeaver/dbeaver/issues/4308) says) and it worked

**Comment by hugorn** [comment] 2018-12-10 14:04
> I paste what serge-rider is saying in my dbeaver/configuration/config.ini (as the [#4308](https://github.com/dbeaver/dbeaver/issues/4308) says) and it worked

Thanks, it worked correctly now.

**Comment by valters** [comment] 2018-12-17 08:44
I also hit this issue (Ubuntu 18.04, Java 11 from adoptopenjdk.net) when upgrading to 5.3.0. Decided to roll back to 3.2.5. Maybe a warning should be provided in the release notes to not bother upgrading when user is on Linux and Java 11, we can sit it out until the next release.
Eclipse 2018-12 is coming out Dec 19, are you referring to this version that you will integrate next?

**Comment by Jokero** [comment] 2018-12-17 08:51
@serge-rider I haven't found this file in ubuntu. However, there are `dbeaver-instance.properties` and `dbeaver-workspace.properties` in `~/.dbeaver4/.metadata` directory. I tried to put your workaround there, but with no luck. And I even created `dbeaver.ini` in `~/.dbeaver4`, but with same result

**Comment by svrnwnsch** [comment] 2018-12-17 09:58
@Jokero the dbeaver.ini file is located at `/usr/share/dbeaver/dbeaver.ini`nevertheless adding the text posted by @serge-rider did not fix the problem for me on ubuntu.

**Comment by serge-rider** [comment] 2018-12-17 14:13
@valters Yes, Eclipse 2018-12 is our next try.

**Comment by Foorack** [comment] 2018-12-20 08:56
Can confirm adding the text posted by serge-rider in /usr/share/dbeaver/dbeaver.ini does not fix it on Ubuntu.
```2018-12-20 09:54:35.174 - > Start org.jkiss.dbeaver.core [5.3.0.201812092025]
2018-12-20 09:54:35.180 - DBeaver 5.3.0.201812092025 is starting
2018-12-20 09:54:35.181 - OS: Linux 4.15.0-42-generic (amd64)
2018-12-20 09:54:35.181 - Java version: 11.0.1 by Oracle Corporation (64bit)
2018-12-20 09:54:35.182 - Install path: '/usr/share/dbeaver'
2018-12-20 09:54:35.182 - Instance path: 'file:/home/foorack/.dbeaver4/'
2018-12-20 09:54:35.182 - Memory available 66Mb/1024Mb
2018-12-20 09:54:35.222 - Starting RMI server at 54082
2018-12-20 09:54:35.341 - Run workbench
2018-12-20 09:54:35.357 - > Start org.eclipse.e4.ui.workbench.swt [0.14.101.v20170710-1119]
2018-12-20 09:54:35.360 - > Start org.eclipse.e4.core.services [2.1.0.v20170407-0928]
2018-12-20 09:54:35.375 - > Start org.eclipse.e4.core.contexts [1.6.0.v20170322-1144]
2018-12-20 09:54:35.410 - > Start org.eclipse.e4.ui.services [1.3.0.v20170307-2032]
2018-12-20 09:54:35.469 - Internal error in workbench lifecycle
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more
2018-12-20 09:54:35.479 - DBeaver is stopping
2018-12-20 09:54:35.479 - Stop RMI server
2018-12-20 09:54:35.562 - < Stop org.jkiss.dbeaver.ext.mssql [1.0.92.201812092025]
2018-12-20 09:54:35.563 - < Stop org.jkiss.dbeaver.ext.oracle [2.1.83.201812092025]
2018-12-20 09:54:35.564 - < Stop org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.4.201812092025]
```

**Comment by hugorn** [comment] 2018-12-20 10:54
past the code in dbeaver/configuration/config.ini not in dbeaver.ini

**Comment by serge-rider** [comment] 2018-12-22 20:09
In 5.3.1 will switch to Eclipse 2018-09 which supports Java 11. This will resolve this bug.

In 5.3.2 will move to Eclipse 2018-12 which also supports Java 11 but doesn't support 32bit (32bit version will be not longer supported).

**Closed by serge-rider** 2018-12-22 20:09 UTC
Labels: question, xo:linux
