### ISSUE TITLE
Dbeaver crashes when I edit a field in the result tab con commit the change

### ISSUE THREAD

**Issue by The-Tramp-It** [dbeaver/dbeaver#7002] opened 2019-10-17 11:15 UTC
#4952  System information: 
- Operating system (distribution) and version Windows 10 Pro
- DBeaver version Version 6.2.2.201910061950
- Java version (build 1.8.0_221-b11)
- Additional extensions None

#### Connection specification:
- Database name and version IBM iSeries V7R3M0
- Driver name DB2 iSeries/AS 400
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I do a simple SELECT, go in result table, change a value and click SAVE. It crashes instatly.

#### Include any warning/errors/backtraces from the logs

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3738910/dbeaver-debug.log)

**Comment by serge-rider** [comment] 2019-10-17 11:17
Duplicate of #6928
Just re-download 6.2.2.

**Closed by serge-rider** 2019-10-17 11:17 UTC
Labels: bug, duplicate
