### ISSUE TITLE
DBeaver does not support left/right scrolling the page with Logitech mouse

### ISSUE THREAD

**Issue by Pil0tXia** [dbeaver/dbeaver#20518] opened 2023-07-10 09:42 UTC
### Description

Hello, I have a Logitech M720 mouse that has a scroll wheel which can be tilted left or right. In the Logitech Options software, the default behavior is to scroll left or right in web pages, similar to swiping left or right with two fingers on a laptop touchpad. **IntelliJ IDEA, Typora, Chrome, and other applications fully support this feature.** 

However, DBeaver only supports two-finger scrolling and does not recognize the left/right tilting of the M720 mouse scroll wheel. 

I would like DBeaver to support this functionality. Thanks a lot.

Logitech Options: https://www.logitech.com/en-us/software/options.html

I **guess** M705, MX Master 3 or MX Anywhere 3 will have the same problem too, because scrolling left or right relies on the software.

### DBeaver Version

Community 23.1.0.202306041918

### Operating System

Win10 22H2

**Comment by E1izabeth** [comment] 2023-07-10 10:13
Seems like a duplicate of #8404

**Closed as not planned by E1izabeth** 2023-07-10 10:13 UTC
Labels: duplicate, xf:ui

**Comment by Pil0tXia** [comment] 2023-10-02 18:53
Logitech Options+ encountered the same problem.
