### ISSUE TITLE
Unable to open Bookmarks: error 'can't find datasource' when double-clicking connection

### ISSUE THREAD

**Issue by daelynum** [dbeaver/dbeaver#20567] opened 2023-07-13 10:50 UTC
### Description

The issue arises when trying to open bookmarked connection. Error message displayed is "Can't open resource 'postgres.bm'. Reason: Can't find datasource 'postgres-jdbc-187faea12af-121bacb51049336d'".

Datasource 'postgres-jdbc-187faea12af-121bacb51049336d' exists in data-sources.json.

[Logs](https://github.com/dbeaver/dbeaver/files/12038471/Bookmarks.log)

<img width="845" alt="Bookmarks" src="https://github.com/dbeaver/dbeaver/assets/38179706/fa2d8faa-f1b2-427c-a419-f9dddf6b20aa">

### DBeaver Version

23.1.2.

### Operating System

macOS Ventura 13.2

### Steps to reproduce

1) Drag and drop a connection into Bookmarks from Database Navigator.
2) Double-click on the bookmarked connection.
3) Observe the error message.

**Comment by ShadelessFox** [comment] 2023-07-14 12:13
Duplicate of https://github.com/dbeaver/dbeaver/issues/19377

**Closed as not planned by ShadelessFox** 2023-07-14 12:13 UTC
Labels: duplicate, xf:navigator
