### ISSUE TITLE
Tree View not listing tables

### ISSUE THREAD

**Issue by cedrickhoury** [dbeaver/dbeaver#36491] opened 2024-12-08 21:13 UTC
### Description

Hello team, 

I'm using the DBeaver Amazon Redshift driver to connect to an AWS Redshift Serverless endpoint from DBeaver, and the tree view listing of external tables under schemas is not listing any tables. It lists databases, and their schemas but you can never list any table. 
That said, I'm able to query the tables under those schemas so it's not a permission issue. 

For authentication, I'm using an Azure AD integration with Redshift to allow me to authenticate using my network credentials. 

![image](https://github.com/user-attachments/assets/bc3dde0c-2610-4d44-9e05-01f5f7688270)

### DBeaver Version

Community Edition 24.3.0

### Operating System

macOS Sonoma 14.1

### Database and driver

Database: Redshift Serverless - Patch 186
Driver: Redshift JDBC 42-2.1.0.29
Class Name: com.amazon.redshift.jdbc42.Driver

### Steps to reproduce

1. Copy an existing AWS Redshift driver into a new one and configure it to use OAuth2 (requires a few additional driver properties)
2. Create a new connection against Redshift using the newly created Redshift driver
3. Use the left side bar connection view to connect and list schemas, and then list their tables 
4. Try listing tables under external Redshift schemas

**Comment by E1izabeth** [comment] 2024-12-10 19:46
Please provide the connection settings tab screen. You can remove all sensitive data from it.

**Comment by cedrickhoury** [comment] 2024-12-10 20:11
Please see below the Connection and Driver Settings 

**Driver Settings and Libraries** 

![image](https://github.com/user-attachments/assets/9f0f4d3b-8f8d-478a-89c8-42d749d136ac)

![image](https://github.com/user-attachments/assets/1a32c882-2f71-4d38-8a93-8a00a4a88e73)

**Connection Settings**

![image](https://github.com/user-attachments/assets/981db367-a127-40bc-9cbd-d08762dd0261)

**The following Driver User Properties were also included**

![image](https://github.com/user-attachments/assets/381c374d-9bf1-4a07-8f87-f3e6d3c0a0c2)

**Comment by E1izabeth** [comment] 2024-12-10 20:18
I see you're using the PostgreSQL connection type. Can you use the Redshift one?
![image](https://github.com/user-attachments/assets/78868738-2df4-47ae-b2e7-60c0c9752ce7)

**Comment by cedrickhoury** [comment] 2024-12-10 20:22
I just noticed on the connection settings it's showing PostgreSQL. I actually copied this driver from the Redshift one when I created it but it now shows PostgreSQL logo in the top. However, it still shows the Redshift logo in the left sidebar tree view 

![image](https://github.com/user-attachments/assets/721f8655-8ac7-4725-8778-86aa972a19ff)

**Comment by cedrickhoury** [comment] 2024-12-10 20:29
You can tell here that I'm using the Redshift driver. You can compare the driver name listed below with the one from my Driver Settings above. 

![image](https://github.com/user-attachments/assets/3248f006-7c58-4bd8-8d8a-37b835302953)

**Comment by E1izabeth** [comment] 2024-12-10 20:33
It sounds exactly like the following issue #22293
As far as I understand, the workaround was NOT to press the `Find class` button in the Libraries tab. Could you try copying your connection again without pressing that button?

**Comment by cedrickhoury** [comment] 2024-12-10 21:33
Recreating the connection (without clicking "Find Class") seems to be have solved the problem but I don't remember clicking on "Find class" when I set it up the first time, so I fear an unknown event (maybe version update/upgrade) can trigger this to happen again. What other factors can cause this switch from Redshift to PostgreSQL (which in return caused the table tree view to stop working)?

**Comment by E1izabeth** [comment] 2024-12-11 16:59
I'm glad to hear that my suggestion helped. Unfortunately, we can't reproduce this issue, so I don't know what caused it. If you reencounter this, please let me know.

For now, I'm closing this issue as a duplicate of #22293
If you want to be notified about updates on this issue, you can subscribe to the mentioned one.

**Closed as not planned by E1izabeth** 2024-12-11 16:59 UTC
Labels: duplicate, x:redshift, xf:connection
