### ISSUE TITLE
Snap app does not start

### ISSUE THREAD

**Issue by Edw125** [dbeaver/dbeaver#19785] opened 2023-04-24 08:33 UTC
### Description

Hello! After upgrade I have some issue
![image](https://user-images.githubusercontent.com/57034089/233942125-86f7f51e-95a9-4003-81c7-14dcb6c01201.png)

### DBeaver Version

snap 23.0.3.202304240616

### Operating System

Ubuntu 22.04 LTS

### Database and driver

No database or driver

### Steps to reproduce

1. I tried to open app and process failed

**Comment by serge-rider** [comment] 2023-04-24 08:42
Duplicate of #19779

**Closed as completed by serge-rider** 2023-04-24 08:42 UTC
Labels: duplicate
