### ISSUE TITLE
Oracle unable to edit table content with 6.2.5

### ISSUE THREAD

**Issue by angelinux** [dbeaver/dbeaver#6043] opened 2019-06-03 13:30 UTC
#### System information: 
- OSX 10.14
- DBeaver 6.2.5
- Java 1.8.0_144

#### Connection specification:
- Oracle
- Oraclke thin drivers
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
 
Updating to DBeaver 6.2.5 it is impossible to edit a value on a "Data" tab of an existing table on an Oracle database. One can click on a cell but its value cannot be changed. This problem does not exist on the same connection with Dbeaver 6.2.4 

#### Steps to reproduce, if exist:

Please open a connection to Oracle database with jdbc thin driver and try to edit the content of a cell in a Data tab of an existing table.

#### Include any warning/errors/backtraces from the logs

!ENTRY org.eclipse.core.net 1 0 2019-06-03 15:04:05.041
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences
!SESSION 2019-06-03 15:07:06.648 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=it_IT
Framework arguments:  -keyring /Users/angelinux/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/angelinux/.eclipse_keyring

!ENTRY org.jkiss.dbeaver.model 4 0 2019-06-03 15:11:31.907
!MESSAGE Errore SQL [904] [42000]: ORA-00904: "C"."CONSTRAINT_NAME": invalid identifier

!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-06-03 15:11:31.907
!MESSAGE ORA-00904: "C"."CONSTRAINT_NAME": invalid identifier

!STACK 0
java.sql.SQLSyntaxErrorException: ORA-00904: "C"."CONSTRAINT_NAME": invalid identifier

**Comment by serge-rider** [comment] 2019-06-03 19:35
Duplicate of #5957
This bug was already fixed. You can check the fix in Early Access version (https://dbeaver.io/files/ea)

**Closed by serge-rider** 2019-06-03 19:35 UTC
Labels: bug, duplicate

**Comment by joaofmeneses** [comment] 2019-11-25 09:56
Sorry for post on this closed Issue. But after read #5957, I didnt went into any conclusion. I keep with the impossibility of edit inline values of the output of a Oracle Query. Using last Oracle driver and Dbeaver 6.2.5.

Was this option definitely disabled for Oracle connections?

**Comment by p91paul** [comment] 2019-11-25 23:04
this thread was actually about 6.0.5, not 6.2.5. That said, try using qualified table names (e.g. owner.table instead of just table), this helps dbeaver to discover metadata. Otherwise you can select the query from navigator or with ctrl+click to open table editor.
