### ISSUE TITLE
5.1.6 - Data Transfer window grows bigger at each step

### ISSUE THREAD

**Issue by masebu** [dbeaver/dbeaver#4144] opened 2018-09-03 18:17 UTC
Hi,

the data transfer window grows bigger each time I click "Next" (except for 1 step)
This is new, I've never seen it in a previous version. Last I used was 5.1.5.

Below are screenshots for a csv export from 1st to last step. It happens with "any" export type (actually I use only csv and sql).
1st shot is 536x424, last is 632x556. Growth in height stops at 556px, Growth in width never seems to stop. Right border of the window ends up out of screen. Next use of the data transfer window will reuse previous last size.
I'm on windows 7 with a dual display setup.

Please ask if you need further details.

![image](https://user-images.githubusercontent.com/19706602/44998363-6304cb00-afb5-11e8-8a4f-7843b5341f65.png)
![image](https://user-images.githubusercontent.com/19706602/44998369-69934280-afb5-11e8-8149-8e13a6664f91.png)
![image](https://user-images.githubusercontent.com/19706602/44998378-7152e700-afb5-11e8-81a5-a5acb090a344.png)
![image](https://user-images.githubusercontent.com/19706602/44998500-60ef3c00-afb6-11e8-9799-7d18c5c55cee.png)
![image](https://user-images.githubusercontent.com/19706602/44998391-86c81100-afb5-11e8-845e-2b0d3c8f0cb6.png)

Regards,
sebastien

**Comment by serge-rider** [comment] 2018-09-03 19:42
Duplicate of #4097
Thanks for the bug report anyway.

**Closed by serge-rider** 2018-09-03 19:42 UTC
Labels: bug, duplicate
