### ISSUE TITLE
somehow the context help completion is getting worse

### ISSUE THREAD

**Issue by wumpz** [dbeaver/dbeaver#4503] opened 2018-10-29 06:57 UTC
I don't know exactly in which of the previous versions this got introduced. But this is what happens. I have a table **test_table** and start typing my sql.

**select * from test**

now the context help starts and helping my with the complete name **test_table**. If I accept this I get:

**select * from test_tabletest**

What I typed before (**test**) is not replaced, but the tablename is included before. 

That is pretty annoying.

**Comment by serge-rider** [comment] 2018-10-29 09:06
duplicate of #4450
This is already fixed in the latest 5.2.3 build (just re-download it from dbeaver.io).

**Closed by serge-rider** 2018-10-29 09:06 UTC
Labels: bug, duplicate

**Comment by wumpz** [comment] 2018-10-29 09:22
But I am using 5.2.3 already. Is another build done with the same version number? Or do I have to remove some older settings to install and use it?
