### ISSUE TITLE
SQL assist/autocomplete does not work with select into

### ISSUE THREAD

**Issue by elring** [dbeaver/dbeaver#13465] opened 2021-08-06 13:14 UTC
#### System information: 
- OS: Linux Mint 20
- DBeaver: 21.1.4

#### Connection specification:
- Database: Postgresql 12

#### Describe the problem you're observing:
When editing plpgsql function which contains select xxx **into xxx** where xxx, the assist doesn't work (in where block) - ctrl+space has no proposals.

Working assist /autocomplete (select without into):
![obrazek](https://user-images.githubusercontent.com/24586123/128514661-66fe5be4-fb15-495f-b72b-59d8c66deaa9.png)

Not-working autocomplete (select into):
![obrazek](https://user-images.githubusercontent.com/24586123/128515529-445283b4-9f43-4261-a0d7-1c1314cc5380.png)

**Comment by Matvey16** [comment] 2021-08-10 10:26
@elring Thank you for the report, we will work on it.
![image](https://user-images.githubusercontent.com/82543000/128854119-32407bd7-4478-4ce0-ad77-28c25cbe8df0.png)

**Comment by LonwoLonwo** [comment] 2021-12-28 07:23
I can't reproduce it against in DBeaver 21.3.2
Probably fixed in previous releases.

![2021-12-28 10_18_11-DBeaver Ultimate 21 3 2 - _postgres 13 3_Script-97](https://user-images.githubusercontent.com/45152336/147539517-6b6ee11c-e6f7-4692-8e01-868784ee5753.png)

If the issue arises again - feel free to reopen this ticket.

**Closed as completed by LonwoLonwo** 2021-12-28 07:23 UTC
Labels: x:postgresql, can't reproduce, xf:sql, sp:2
