### ISSUE TITLE
Function "Copy as .." and custom filter bug

### ISSUE THREAD

**Issue by Kerksys** [dbeaver/dbeaver#13722] opened 2021-08-29 10:37 UTC
#### System information: 
- Windows 10
- DBeaver 21.1.3
- Additional extensions - No

#### Connection specification:
- PostgreSQL 12.7, compiled by Visual C++ build 1914, 64-bit
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No, local instance

#### Describe the problem you're observing:
Have a simple table
|id                                  |isdeleted|date_1    |name   |short_name|number|
|------------------------------------|---------|----------|-------|----------|------|
|4e5ac59d-f7a5-4172-9ba8-8ee6db5ca08b|false    |2010-01-01|Имя № 1|Имя № 1   |1     |
|ee02dc6c-7be4-4b39-8475-22ee48ee59cb|false    |2010-01-01|Имя № 2|Имя № 2   |2     |
|366c97a4-b3ec-4592-add9-4488f31bb995|false    |2010-01-01|Имя № 3|Имя № 3   |3     |
|a2c3ce96-14bc-42a3-8d90-418a6f330b67|false    |2010-01-01|Имя № 4|Имя № 4   |4     |

**1.** Ctrl+(right mouse click) I check ALL column and call "Copy as TXT" and get a good result (see above).
**2.** Go to filter and uncheck some columns, for example "date_1" like this
![image](https://user-images.githubusercontent.com/89728905/131246971-e187b961-739a-4ec1-baeb-3cba409bd072.png)
**3.** Now i repeat check all columns (wo "date_1") and call "Copy as TXT" again
![image](https://user-images.githubusercontent.com/89728905/131247197-f9a4c39a-2a13-4ecf-8315-16b1bb881eb6.png)

but get a bad result like this - data from column "number" are in column "name". But column names and their order are correct. 
|id                                  |isdeleted|name|short_name|number|
|------------------------------------|---------|----|----------|------|
|4e5ac59d-f7a5-4172-9ba8-8ee6db5ca08b|false    |1   |          |      |
|ee02dc6c-7be4-4b39-8475-22ee48ee59cb|false    |2   |          |      |
|366c97a4-b3ec-4592-add9-4488f31bb995|false    |3   |          |      |
|a2c3ce96-14bc-42a3-8d90-418a6f330b67|false    |4   |          |      |

I experimented with the order of columns and their disabling in the filter, he did not find a pattern.

#### Steps to reproduce, if exist:
- uncheck some columns in filter options
- check some columns to Copy as TXT 
- Paste to notepad and see result

**Comment by uslss** [comment] 2021-08-29 14:57
thanks for the report
closed as a duplicate of #9252

**Closed as completed by uslss** 2021-08-29 14:57 UTC
Labels: duplicate
