### ISSUE TITLE
GUI output floats

### ISSUE THREAD

**Issue by Crutchmaster** [dbeaver/dbeaver#6914] opened 2019-10-04 04:43 UTC
`SELECT 0.0000001 FROM dual`

Result : 0

![proof](https://user-images.githubusercontent.com/13776084/66181716-041ff280-e69c-11e9-964a-ce6cc6e5c11c.png)

Text version - ok.
![text](https://user-images.githubusercontent.com/13776084/66181743-29146580-e69c-11e9-8f20-99449e68ab0d.png)

Version: 6.2.0.201909081341

**Comment by serge-rider** [comment] 2019-10-28 14:47
Fixed.
@uslss this ticket correlates with #6111, please check floating point formatting in general. At least for PG, MySQL and Oracle.

**Comment by uslss** [comment] 2019-10-28 16:17
Reopened.
Quite strange behavior with big numbers (PostgreSQL)
![float](https://user-images.githubusercontent.com/31996417/67696217-88be1200-f9b7-11e9-9531-d7bb55d99612.gif)

**Comment by serge-rider** [comment] 2019-10-28 19:45
One more fix committed

**Comment by uslss** [comment] 2019-10-30 13:05
Behavior is quite strange in the next cases:
1) Postgresql, float4: 1111111.1 transformates to 1111111.125  (Not reproducible for float8)
2) Oracle, float: 
![image](https://user-images.githubusercontent.com/31996417/67860536-2425c300-fb2f-11e9-975c-c3a31744de16.png)

**Comment by serge-rider** [comment] 2019-10-30 14:18
We can't fix issue with float4 numbers (it is a Java-specific floating point numbers formatting in case of number overflow).
Can't reproduce for Oracle

**Comment by serge-rider** [comment] 2019-10-30 14:54
Fixed FLOAT data type handle for Oracle

**Comment by uslss** [comment] 2019-10-31 16:57
verified

**Closed by uslss** 2019-10-31 16:57 UTC
Labels: bug
