### ISSUE TITLE
Schema Missing for Mainframe DB2

### ISSUE THREAD

**Issue by KapsGit** [dbeaver/dbeaver#6099] opened 2019-06-13 15:27 UTC
#### System information: 
- Operating system (distribution) and version ==> Windows 10 Pro. Version 1803
- DBeaver version ==> 6.0.5

#### Connection specification:
- Database name and version ==> Mainframe DB2

#### Describe your question:
Schema list is missing under the "Tables" section. IT directly displays the tables without grouping them by Schema.

**Comment by serge-rider** [comment] 2019-06-14 17:41
Duplicate of #6092
Please see commited for workaround

**Closed by serge-rider** 2019-06-14 17:41 UTC
Labels: duplicate, question, x:db2
