### ISSUE TITLE
In the MS Store version 22.3.4, an extra layer of JRE (jre/jre) is placed in the JRE path, causing the startup failure

### ISSUE THREAD

**Issue by Sec-Joe** [dbeaver/dbeaver#19058] opened 2023-02-14 07:27 UTC
### Description

As for 22.3.4 of MS Store version, an extra layer of JRE (jre/jre) is placed in the JRE path, so it cannot be started. Currently, the MS store has been removed from the shelf, so the installation cannot be searched

### DBeaver Version

22.3.4

### Operating System

Microsoft Store

**Comment by E1izabeth** [comment] 2023-02-14 07:33
Thank you for the bug report. This is a known issue in the latest release.
As a workaround, you can either download DBeaver from https://dbeaver.io/files or install JRE 11 or greater.

We have some issues connected with Microsoft store and are trying to solve them. Hope DBeaver will appear in the store again soon.

Closing as a duplicate of #18960

**Closed as not planned by E1izabeth** 2023-02-14 07:33 UTC
Labels: duplicate, xo:windows, xf:packaging

**Comment by liu-junjie** [comment] 2023-02-14 13:05
![image](https://user-images.githubusercontent.com/31123200/218747025-34655a71-c0f9-4a45-8942-3f8f38c8656a.png)
Won't Microsoft Store be supported anymore?

**Comment by E1izabeth** [comment] 2023-02-14 13:30
It's hard to say whether we'll do it again or not. The current answer is no, but things may change.
