### ISSUE TITLE
MySQL script dont accept multiple USE command 

### ISSUE THREAD

**Issue by simeds** [dbeaver/dbeaver#29262] opened 2024-04-29 09:46 UTC
### Description

Since version 24.0.3 MySQL scripts with two or more USE command, to change schema, stops at second USE command showing sintax error near schema name.

For example, this script work in 24.0.2 but not in 24.0.3:

USE ADTSICLAMM;
SELECT * FROM ADT_ArchivioDettaglio;
USE ADTSICLAMMCRON;
SELECT * from _CRON_ADT_ArchivioPrincipale;

Also dont work the autocompletion for schema name.

### DBeaver Version

24.0.3

### Operating System

Ubuntu 20.04.6 LTS

### Database and driver

Database MySQL 8
Connector 8.3

### Steps to reproduce

try to switch between two schemas

### Additional context

USE ADTSICLAMM;
SELECT * FROM ADT_ArchivioDettaglio;
USE ADTSICLAMMCRON;
SELECT * from _CRON_ADT_ArchivioPrincipale;

**Comment by E1izabeth** [comment] 2024-04-29 09:48
Thank you for bug report. It's a duplicate of #24128
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Closed as not planned by E1izabeth** 2024-04-29 09:48 UTC
Labels: duplicate, xf:sql execution

**Comment by simeds** [comment] 2024-04-29 09:58
Thank you for the Early Access version, now the scripts works, but still remain the problem with autocomplete feature.
It dont suggest the schemas names

**Comment by E1izabeth** [comment] 2024-04-29 10:00
Please create a separate issue for autocompletion.

**Comment by E1izabeth** [comment] 2024-04-29 10:02
Also please provide the screenshot of this settings page
![image](https://github.com/dbeaver/dbeaver/assets/28875055/285c5dff-49ea-4503-9d0b-2c3eae067e22)
