### ISSUE TITLE
Support horizontal scroll using mouse buttons inside views with a scrollbar

### ISSUE THREAD

**Issue by daniellwdb** [dbeaver/dbeaver#12065] opened 2021-04-09 14:32 UTC
**Is your feature request related to a problem? Please describe.**
When you are inside the grid view, viewing a table with a lot of columns, you can not scroll horizontally with native mouse buttons.

**Describe the solution you'd like**
It would be nice if we could scroll horizontally in views where a horizontal scrollbar is visible using mouse buttons.

**Additional context**
Windows 10 Home
DBeaver 21.0.2
Tested with Logitech MX Master 3

It seems like it only works (sometimes) if you click another window and then hover the view with a scrollbar and scroll with the mouse button, when you click back into the DBeaver window you can't scroll anymore. Everytime it works you see the icon blink inside the taskbar 
![image](https://user-images.githubusercontent.com/44723767/114197635-d5e73700-9952-11eb-82d6-20c6190b1c45.png)

**Comment by kseniiaguzeeva** [comment] 2021-04-10 09:48
Did you try hold shift+scroll by mouse wheel?

**Comment by daniellwdb** [comment] 2021-04-10 10:03
Yes that does seem to work and is a nice alternative, however some mice have a dedicated horizontal scroll wheel and that one does not work, even when holding shift

**Comment by qupear** [comment] 2021-04-12 15:15
In my case, it's Logitech MX Master 2S, and behavior is like that:
horizontal scroll in Dbeaver works one time (one step of scrolling). Then it stops scrolling. It tries to do something because when a horizontal wheel is moved, Dbeaver flashes its horizontal scrollbar, but nothing happens then. Then I switch the focus to any other window, Then move focus back to Dbeaver, and I can scroll one more step with a horizontal wheel. So it looks like some issue with focusing elements of window.

**Comment by kseniiaguzeeva** [comment] 2021-04-14 14:02
Thank you for the report and additional details, Will try to reproduce and fix.

**Comment by qupear** [comment] 2021-04-14 15:17
One more detail. It looks like horizontal scroll works only in table data pages (and results). In pages with queries, in values of results cells and definitions it doesn't work to me even using SHIFT + SCROLL.

**Comment by kseniiaguzeeva** [comment] 2021-06-09 08:48
My steps:
1. Open a table in Data Editor and scroll horisontally by Logitech mouse
2. Open the same table in SQL Editor and try to scroll by the same way - the horizontal scroll doesn't work
3. Go back to the Data Editor and try to scroll horisontally by the mouse again - the scroll doesn't work anymore

https://user-images.githubusercontent.com/51405061/121323320-653fa500-c918-11eb-86eb-894f28cd5395.mp4

OS: Win10

**Comment by serge-rider** [comment] 2021-12-13 14:51
Can't reproduce anymore. Perhaps it was fixed in Eclipse 2021-06/09

**Comment by qupear** [comment] 2021-12-13 15:02
In version 21.3.1 this issue is fixed (maybe earlier). At least in my case horizontal scroll works OK.

**Closed as completed** 2021-12-14 08:47 UTC
Labels: can't reproduce, sp:2, xf:ui
