### ISSUE TITLE
Column cannot be sorted in "Record mode"

### ISSUE THREAD

**Issue by ccctang** [dbeaver/dbeaver#18656] opened 2023-01-04 14:39 UTC
### Description

The sorting in record mode used to work.  After I updated to 22.3.1.202212251901, the sorting arrow was gone.

### DBeaver Version

22.3.1.202212251901

### Operating System

Window 10

### Database and driver

Sybase 
jConnect (TM) for JDBC(TM)/16.0 SP03 PL02 (Build 27403)/P/EBF27518/JDK 1.6.0/jdbcmain/OPT/Mon Aug 28 18:41:14 PDT 2017

### Steps to reproduce

1. query a table
2. click record
3. The arrow in missing in coulumn_name column

**Comment by uslss** [comment] 2023-01-04 14:41
thanks for the report.
Closed as a duplicate of #18618

**Closed as completed by uslss** 2023-01-04 14:41 UTC
Labels: duplicate
