### ISSUE TITLE
SQL Formatting error - nested joins are staggered on align

### ISSUE THREAD

**Issue by kiravi** [dbeaver/dbeaver#3714] opened 2018-06-29 14:32 UTC
Please take a look at this SQL:
```sql
WITH aw AS ( SELECT
  LEVEL AS lvl
FROM
  dual
CONNECT BY
  LEVEL <= 4 ) SELECT
  a.*
FROM
  aw a
INNER JOIN aw b ON
    ( a.lvl = b.lvl - 1 )
  INNER JOIN aw c ON
      ( a.lvl = c.lvl - 2 )
    INNER JOIN aw d ON
        ( a.lvl = d.lvl - 3 ) ;
```
The inner joins are misaligned by a space as the join depth increases.
They should aligned to the FROM clause.  Please run the formatter to see this.

I had another issue on aligning single line comments that may have been fixed.  I am not sure whether the alignments on other elements causes this.

**Comment by serge-rider** [comment] 2018-07-01 17:45
Duplicate of #3679, fix in 5.1.2

Hint: in order to format SQL code surround it with ` ```sql ` and ` ``` ` lines

**Closed by serge-rider** 2018-07-01 17:45 UTC
Labels: bug, duplicate
