### ISSUE TITLE
Snowflake driver on EE edition does not show source for Procedures

### ISSUE THREAD

**Issue by ishah-ia** [dbeaver/dbeaver#18506] opened 2022-12-13 10:10 UTC
### Description

In the EE edition, when viewing source for Snowflake procedures it gives:

/* ERROR WHILE READING SOURCE:

SQL Error [1003] [42000]: SQL compilation error:
parse error line 1 at position 31 near '95'.
parse error line 1 at position 36 near '95'.
*/

Where as in community edition it displays the source code fine

### DBeaver Version

DBEaver Enterprise Version 22.3.0.202212112120

### Operating System

macOS Catalina 10.15.7

### Database and driver

Snowflake EE JDBC snowflake_jdbc_ee. 3.13.6

### Steps to reproduce

Connect to DB
Navigate to stored procedure 
Double Click to open
Click Source tab

**Comment by E1izabeth** [comment] 2022-12-13 10:37
I can't reproduce your issue. Maybe you have some specific procedure name? Could you show the query executed by DBeaver when you are opening the procedure source? You can find it in [Query manager](https://dbeaver.com/docs/wiki/Query-Manager/) when the `Meta `option is checked. It should be something like `SELECT GET_DDL(...).`

![image](https://user-images.githubusercontent.com/28875055/207295109-2f5f870d-c175-4c21-b0ab-8471adb13d65.png)

**Comment by ishah-ia** [comment] 2022-12-13 10:45
I am not seeing a GET_DDL when I look at procedures:
![image](https://user-images.githubusercontent.com/15666127/207296682-77301868-5472-49de-b0d8-d911a9175d7e.png)
I do see that when I click on a function.... but not prcedures:

![image](https://user-images.githubusercontent.com/15666127/207297067-81018fb8-f56e-4154-b509-ea3684f16f38.png)

**Comment by ishah-ia** [comment] 2022-12-13 10:46
I should point out in community edition which I think uses a different driver, i don't get this problem.

**Comment by E1izabeth** [comment] 2022-12-13 10:47
Thank you for answering.

**Comment by LonwoLonwo** [comment] 2022-12-13 12:01
Hello.

Yes, this is a knowing issue.
You can read about it here: https://github.com/dbeaver/dbeaver/issues/17121
or here https://github.com/dbeaver/dbeaver/issues/17065

My PR fixing this issue is already merged. We are waiting for the driver release https://github.com/snowflakedb/snowflake-jdbc/pull/1130

But you can try to use another driver version: https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.13.22/snowflake-jdbc-3.13.22.jar

Driver changing you could find in the Connection Settings:
![2022-12-13 15_00_40-Window](https://user-images.githubusercontent.com/45152336/207312486-48ac712c-34ad-439d-9f7b-7418d020fad6.png)

**Comment by uslss** [comment] 2023-02-01 11:22
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.

**Closed as completed by uslss** 2023-02-01 11:22 UTC
Labels: x:snowflake, PRO, wait for response, xf:metadata
