### ISSUE TITLE
Oracle constraint,references and foreign key views no longer work in 6.0.5

### ISSUE THREAD

**Issue by Feemal** [dbeaver/dbeaver#5958] opened 2019-05-21 12:13 UTC
#### System information: 
- Operating system (distribution) and version
Mac OSX 10.14.4
- DBeaver version
6.0.5
- Java version 
Openjdk 11.0.1
- Additional extensions
None

#### Connection specification:
- Database name and version
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 
- Driver name
Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:

After upgrading to 6.0.5 Constraint, foreign key and reference views no longer work when checking table properties. 
When the client is searching for the constraints it fails with the following error: 

> SQL Error [904] [42000]: ORA-00904: "C"."CONSTRAINT_NAME": invalid identifier
> 
>   ORA-00904: "C"."CONSTRAINT_NAME": invalid identifier
> 
>   ORA-00904: "C"."CONSTRAINT_NAME": invalid identifier
> 

The query that the client is using according to the query manager:

```
SELECT
    c.TABLE_NAME,
    c.CONSTRAINT_NAME,
    c.CONSTRAINT_TYPE,
    c.STATUS,
    c.SEARCH_CONDITION,
    (
        SELECT LTRIM(MAX(SYS_CONNECT_BY_PATH(cname || ':' || NVL(p,1),','))    KEEP (DENSE_RANK LAST ORDER BY curr),',') 
        FROM   (SELECT 
                       col.CONSTRAINT_NAME cn,col.POSITION p,col.COLUMN_NAME cname,
                       ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) AS curr,
                       ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) -1 AS prev
                FROM   ALL_CONS_COLUMNS col 
                WHERE  col.OWNER =:owner AND col.TABLE_NAME = :tableName AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME 
                )   GROUP BY cn CONNECT BY prev = PRIOR curr AND cn = PRIOR cn START WITH curr = 1      
        ) COLUMN_NAMES_NUMS
FROM
    ALL_CONSTRAINTS c
WHERE
    c.CONSTRAINT_TYPE <> 'R'
    AND c.OWNER = :owner
    AND c.TABLE_NAME = :tableName
```

This seems to be caused by the inner join between ALL_CONS_COLUMNS and ALL_CONSTRAINT done in the select.

When downgrading to 6.0.4 which has the old query for constraints which does not include the changes from #5878 everything works as it should.

#### Steps to reproduce, if exist:

Trying to access Constraints, Foreign Keys or References from table properties in version 6.0.5

**Comment by serge-rider** [comment] 2019-05-21 19:36
Duplicate of #5957
Thanks for the report anyway

**Closed by serge-rider** 2019-05-21 19:36 UTC
Labels: bug, duplicate, x:oracle
