### ISSUE TITLE
JDBC Impala SSL 

### ISSUE THREAD

**Issue by lvillal** [dbeaver/dbeaver#19750] opened 2023-04-19 18:47 UTC
### Description

I'm triying to conect to impala with jdbc driver and SSL.
I added the .pem to my key store with:

* keytool –import –alias my_alias     –file  \A\ImpalaCert\Ca_bundle.pem

* and I tried with several string connections:
   jdbc:impala://impala-host:21050/default;ssl=1;SSLTrustStore=C:\.keystore;SSLTrustStorePwd=xxxxxx
   jdbc:impala://impala-host:21050/default;ssl=1;SSLKeyStore=C:\.keystore;SSLKeyStorePwd=xxxxxxxxx

* I copied \jdk-17.0.1\lib\security\cacerts  to replace dbeaver cacerts file

but nothing worked.

### DBeaver Version

Comunity Edition 23.0.2.202304091457

### Operating System

Windows 10

### Database and driver

Impala with JDBC driver

### Steps to reproduce

Configure JDBC strings as mentioned in description

### Additional context

Herer bellow a log

[Simba][ImpalaJDBCDriver](500151) Error setting/closing session: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
  javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      unable to find valid certification path to requested target
      unable to find valid certification path to requested target

**Comment by LonwoLonwo** [comment] 2023-04-20 08:34
Hello @lvillal 

Could you please change this setting, restart DBeaver, and try to connect again?

![2023-04-20 11_33_05-Preferences](https://user-images.githubusercontent.com/45152336/233308576-e03c03b4-12a2-41e1-9719-7dec48312a84.png)

**Comment by lvillal** [comment] 2023-04-20 20:08
Hi,

I don't have these options:
Here a screenshot:

**Comment by LonwoLonwo** [comment] 2023-04-21 07:38
Please provide your image via this GitHub page. It doesn't work via e-mail.

**Comment by lvillal** [comment] 2023-04-24 15:52
Here are my screenshoots

My connection config
![image](https://user-images.githubusercontent.com/2653583/234058417-28864a09-8a31-4f53-b41e-9e82201848cd.png)

![image](https://user-images.githubusercontent.com/2653583/234058281-210c4835-c8f4-4b0b-bbf5-f9d60c17debe.png)

![image](https://user-images.githubusercontent.com/2653583/234049594-8e6f359d-6d36-45c4-bb0c-214d3c571b4f.png)

![image](https://user-images.githubusercontent.com/2653583/234050078-915c1f08-080d-454e-ab5f-3f63bbad5082.png)

**Comment by E1izabeth** [comment] 2023-05-09 20:37
Am I correctly understand, that you unchecked `Use Windows trust store` setting, restarted DBeaver and it didn't help?

**Comment by E1izabeth** [comment] 2023-06-05 09:39
Let me know if the issue is still actual.
It's been a while since no update here, so I'm closing it.

**Closed as not planned by E1izabeth** 2023-06-05 09:39 UTC
Labels: x:impala, wait for response, xf:connection, xf:ssl

**Comment by AmitHBhagat** [comment] 2024-04-22 22:09
Hi Friends,

I am trying to connect to impala through DBeaver24.0.3.
Getting the same error "unable to find valid certification path to requested target".
I tried above steps, but no luck.
Is it possible to face this issue if the certificate is not valid?

Any suggestions please.

**Comment by AmitHBhagat** [comment] 2024-04-23 12:38
> Hi Friends,
> 
> I am trying to connect to impala through DBeaver24.0.3. Getting the same error "unable to find valid certification path to requested target". I tried above steps, but no luck. Is it possible to face this issue if the certificate is not valid?
> 
> Any suggestions please.

Hi Friends,
It turned out to be an issue of an invalid certificate.
The issue is resolved by providing a valid cert irrespective of the toggling "Use Windows trust store" option.

**Comment by E1izabeth** [comment] 2024-04-23 13:01
Thank you for update
