### ISSUE TITLE
Dbeaver today with error exit code 13 from 8/02/23 

### ISSUE THREAD

**Issue by ctortosab** [dbeaver/dbeaver#19004] opened 2023-02-08 08:52 UTC
Dbeaver has been running for more than 1 year without problems, but today, when opening it, it gives Java exit code 13 error. I have just installed the latest version 6th Feb, which still gives the error. 
<img width="202" alt="dbeaver error" src="https://user-images.githubusercontent.com/124772853/217480932-f67318bf-9c57-482c-91f2-d41d308b396e.png">

**Comment by E1izabeth** [comment] 2023-02-08 08:58
Thanks for the bug report. This is a known issue in the latest release.

As a workaround, you can either download DBeaver from https://dbeaver.io/files or install JRE 11 or greater.

Closing as a duplicate of #18960

**Closed as not planned by E1izabeth** 2023-02-08 08:58 UTC
Labels: duplicate, xo:windows, xf:packaging

**Comment by ctortosab** [comment] 2023-02-08 09:00
Thanks,  but I had this problem before installing the last version

**Comment by E1izabeth** [comment] 2023-02-08 09:02
This issue is reproducible on 22.3.4. As I can see by the attached image, you have this version.

**Comment by ctortosab** [comment] 2023-02-08 09:05
yes, because I installed the latest version when today when I opened the program it gave me an error.  I'm going to do as you said and I will let you know if I have some error. Thanks a lot for your support
