### ISSUE TITLE
The user interface language setting gets reset to machine UI language after update

### ISSUE THREAD

**Issue by codingphil** [dbeaver/dbeaver#18023] opened 2022-10-25 06:52 UTC
### Description

I run DBeaver on a Windows machine with german UI language and run DBeaver with the setting "English"
for "User Interface / Regional settings / language".
After each update the language setting gets reset to "German" (UI language of my Windows machine) and I have to manually change the setting to the value "English".
It would be great if the language setting does not get reset to the local machine language after the update.

### DBeaver Version

Communitity Edition 22.2.3.202210231354

### Operating System

Windows 10 21H2 (UI language set to German)

### Steps to reproduce

1. Install a version of DBeaver on a Windows machine with display language "German".
2. Change the "User Interface / regional settings / language" to "English"
3. Install a new version of DBeaver (or just click through the update dialog if it appears)
4. Now the "User Interface / regional settings / language" is "German" but expected to remain "English"

**Comment by E1izabeth** [comment] 2022-10-25 08:08
Duplicate of #17857

**Closed as not planned by E1izabeth** 2022-10-25 08:08 UTC
Labels: duplicate
