### ISSUE TITLE
Spatial viewer chokes on postgis geometries with Z coordinate

### ISSUE THREAD

**Issue by AsgerPetersen** [dbeaver/dbeaver#10667] opened 2020-12-11 11:33 UTC
#### System information: 
- Operating system (distribution) and version
OSX and Windows
- DBeaver version
7.3.0.202011291229
- Additional extensions
None

#### Connection specification:
- Driver name
Postgresql

#### Describe the problem you're observing:
The spatialviewer shows a blank map when the geometries have a Z coordinate.

#### Steps to reproduce, if exist:
This shows a blank map:
```postgresql
select st_geometryfromtext('POINT(12 55 0)', 4326);
```
![image](https://user-images.githubusercontent.com/1392735/101898198-fa512380-3bab-11eb-943f-36d85ab33991.png)

Dropping the Z coord makes the map work as expected
```postgresql
select st_force2d(st_geometryfromtext('POINT(12 55 0)', 4326));
```
![image](https://user-images.githubusercontent.com/1392735/101898342-3f755580-3bac-11eb-88a3-874abb3d24f3.png)

I think dbeaver should just drop the Z coordinate if present. No one would reasonably expect the map viewer to be full 3D, so showing the 2D projection of the geometries would be the expected behaviour.

#### Include any warning/errors/backtraces from the logs
There are no entries in the logs for this issue.

Thank you for a great tool!

**Comment by uslss** [comment] 2020-12-11 12:05
seems to be duplicate of #9270 
anyway, thanks for the report

**Closed by uslss** 2020-12-11 12:05 UTC
Labels: bug, duplicate

**Comment by AsgerPetersen** [comment] 2020-12-11 12:20
Sorry! Tried to search for potential duplicates, but obviously failed miserably.
