### ISSUE TITLE
Possibility to set the relative path to public key or/and make it possible to store it in repository (project)

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7641] opened 2020-01-15 10:07 UTC
**Is your feature request related to a problem? Please describe.**
I need to put all connections that are used to GIT repo, but almost all connections use public key, that stored at my local machine. So any user that will use my repo, should set path to key manually for all connections.

**Describe the solution you'd like**
Make possible to set the relative path to public key or/and make it possible to store it in repository (project)

**Comment by serge-rider** [comment] 2020-01-20 11:34
Duplicate of #7681 (I know this ticket is older butt still).

**Closed by serge-rider** 2020-01-20 11:34 UTC
Labels: duplicate, feature request
