### ISSUE TITLE
Context Menu gets open

### ISSUE THREAD

**Issue by GisaDeve** [dbeaver/dbeaver#35689] opened 2024-09-23 17:52 UTC
### Description

In script editor with the shortcut Control + Enter, the contex menu gets open in the script editor and on tabs.

### DBeaver Version

Community Edition Versión 24.2.1

### Operating System

macOS Sequoia 15.0

### Database and driver

Every sql editor

### Steps to reproduce

Cursor on script editor use the shortcut Control + Enter

**Comment by E1izabeth** [comment] 2024-09-24 06:48
Thank you for bug report. It's a duplicate of #35681 Please follow the mentioned issue to get updates

**Closed as not planned by E1izabeth** 2024-09-24 06:48 UTC
Labels: duplicate, xo:macos, xf:ui

**Comment by hemant171k** [comment] 2024-09-28 10:06
when we can expect new version to fix this issue

**Comment by E1izabeth** [comment] 2024-09-28 11:36
@hemant171k please take a look at this comment https://github.com/dbeaver/dbeaver/issues/35109#issuecomment-2306254608
