### ISSUE TITLE
Export with "selected columns only" creates all columns from source table in target table

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14278] opened 2021-10-18 04:05 UTC
#### System information: 
- Win10
- DBeaver 21.2.3 CE

#### Connection specification:
- Greenplum (partner access)

#### Steps to reproduce, if exist:
1. Select fewer columns than there are in the table
2. Perform export into table
Expected: only those columns were created that were selected in the source table 
Actual: All columns from source table were created and those that weren't selected are filled by NULLs

**Comment by LonwoLonwo** [comment] 2022-04-07 12:04
Duplicate of https://github.com/dbeaver/dbeaver/issues/14442

**Closed as completed by LonwoLonwo** 2022-04-07 12:04 UTC
Labels: duplicate, xf:datatransfer, sp:2
