### ISSUE TITLE
Move vertical Server Output window with result, horizontally

### ISSUE THREAD

**Issue by thomasbronner** [dbeaver/dbeaver#12687] opened 2021-06-01 10:39 UTC
#### System information: 
- Operating system (distribution) and version : Win 10
- DBeaver version : 21.1,0
- Java version : 1.8.0_271
- Additional extensions

#### Connection specification:
- Database name and version : PostgreSQL 11.x
- Driver name  ??
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

The server output window appear vertically beside the script window and it is impossible to move it down as another tab in the result area (Layout is set to horizontal)

#### Steps to reproduce, if exist:

run a query with server output, click the output button 

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/13118907/120310116-4fa5fc00-c2d6-11eb-8bd1-0a1a6eb1349c.png)

**Comment by uslss** [comment] 2021-06-02 08:21
seems to be a duplicate of #12534 
anyway, thanks for the report

**Closed as completed by uslss** 2021-06-02 08:21 UTC
Labels: enhancement, duplicate
