### ISSUE TITLE
autocompletion - duplicating schema names

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#19899] opened 2023-05-07 14:44 UTC
### Description

Hello
There is a scenario(s) where the autocompletion feature duplicates a schema name found in fully qualified table identifier. In the case shown on video below, it happens when I changed one table to another one, while both are located in the same schema.  Possibly it might happen even if the first table doesn't exist (is a result of typo), then fixing using autocompletion duplicates the schema

https://youtu.be/SVYE64SZ2Qg

WIth regards

### DBeaver Version

CE 23.0.3

### Operating System

Fedora 37

### Database and driver

PostgreSQL

### Steps to reproduce

See video

**Comment by LonwoLonwo** [comment] 2023-05-08 07:48
Hello @michalk-k 

Ok, I agree that the duplication of the schema name is incorrect in your case on the video.

You can choose the first proposal without a schema name as a workaround.

![2023-05-08 10_41_36-DBeaver - multiplication of schema name - YouTube — Mozilla Firefox](https://user-images.githubusercontent.com/45152336/236765615-7f80c096-5d02-492b-b1a7-7f85f657b3e6.png)

**Comment by michal-bartak** [comment] 2023-05-08 07:54
selecting object without schema I would expect the result without the schema at all.

But thank you for suggestion. Somehow I didn't notice the same table is listed twice: without and with schema

**Comment by E1izabeth** [comment] 2024-01-25 16:03
Should be fixed in scope of #19821
I can't reproduce it on DBeaver 23.3.3
If the issue is still actual, please fill free to let me know.

**Closed as completed by E1izabeth** 2024-01-25 16:03 UTC
Labels: xp:minor, xf:sql

**Comment by michal-bartak** [comment] 2024-01-26 13:12
I can confirm, behaves good in 23.3.3
