### ISSUE TITLE
Error synchronizing data with database: (Editing text type field)

### ISSUE THREAD

**Issue by andresoym** [dbeaver/dbeaver#10159] opened 2020-10-24 00:52 UTC
#### System information: 
WIndows 10 Pro - Version 2004 (OS Build 19041.572)
DBeaver Version 7.2.3.202010191702
No Additional extensions

#### Connection specification:
PostgreSQL
PostgreSQL JDBC Driver

#### Describe the problem you're observing:
Can't edit cell with text type (multiline)

#### Steps to reproduce, if exist:
1.- Open table data
2.- Edit field with multiples lines
3.- Save

#### Include any warning/errors/backtraces from the logs
Error synchronizing data with database:
 Object parameter [text\nmultiline] binding not supported

![dbeaverError](https://user-images.githubusercontent.com/57728603/97064085-3f23eb00-1569-11eb-911f-6f291582f9e0.png)

**Comment by brad-rimsys** [comment] 2020-10-24 22:14
Same issue. This seems to only affect version 7.2.3  as I now reverted back to 7.2.2 and I'm able to edit these fields,

**Comment by kseniiaguzeeva** [comment] 2020-10-25 03:51
I cannot reproduce it.
Most probably the fix will be included in 7.2.4 release. You can try Early Access version https://dbeaver.io/files/ea/. If the issue can be reproduced there, please send DDL example

**Comment by carragom** [comment] 2020-10-25 16:05
Similar issue when editing a column on a table with a UUID PK on PostgreSQL. Problem visible on versions 7.2.3 and 7.2.2. Had to go back to 7.2.1

**Comment by kseniiaguzeeva** [comment] 2020-10-26 12:14
@carragom please try 7.2.4 (release 02.11.20). You can try Early Access version https://dbeaver.io/files/ea/ now.

**Comment by christiankaiser** [comment] 2020-10-27 18:16
> @carragom please try 7.2.4 (release 02.11.20). You can try Early Access version https://dbeaver.io/files/ea/ now.

I had this problem or similar with version 7.2.3 with PostgreSQL when editing a text field. The problem was not around with 7.2.2 and before. The Early Access version as of today (7.2.3.202010230753) works again, the problem does not appear.

**Comment by kseniiaguzeeva** [comment] 2020-10-28 07:16
Thank you for testing! So, I close the ticket,

**Closed by kseniiaguzeeva** 2020-10-28 07:16 UTC
Labels: bug, can't reproduce, wait for response, x:postgresql
