### ISSUE TITLE
Ctrl+Enter behavior change--no longer replaces currently selected resultrs tab

### ISSUE THREAD

**Issue by glancep** [dbeaver/dbeaver#16515] opened 2022-05-17 18:49 UTC
#### System information: 
- Operating system (distribution) and version **Windows 10**
- DBeaver version **22.0.4.202205011839**
- Additional extensions

#### Connection specification:
- Database name and version **MySQL 5**
- Driver name **MySQL 5**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **SSH**

#### Describe the problem you're observing:
After updating DBeaver, I noticed that when I run a query with Ctrl+Enter, it closes all other results tabs.
Before the update, I could have several results tabs open and use Ctrl+Enter to replace the results in the current tab without affecting the other tabs.  I found this behavior very useful, where I write query 1 followed by query 2 ... but need to tweak query 2 and rerun without losing my results from query 1.

This seems related to this old (closed) issue: #4550

#### Steps to reproduce, if exist:
Use Ctrl+Enter to run query 1 and see results results tab 1
Use Ctrl+\ to run query 2 in a separate results tab 2
Use Ctrl+Enter to run query 3, expecting it to replace tab 2

**Comment by E1izabeth** [comment] 2022-05-17 18:52
Hi, @glancep! Thank you for report. Fix will be available in the next release.
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/16402

**Closed as completed by E1izabeth** 2022-05-17 18:52 UTC
Labels: duplicate

**Comment by glancep** [comment] 2022-05-17 19:07
> Hi, @glancep! Thank you for report. Fix will be available in the next release. Closed as duplicate of #16402

Awesome -- thanks for the very prompt response!  For what it's worth, I tried looking for an existing issue, but didn't catch it b/c it was already closed.  I love how active this project is!

**Comment by TheresaAd** [comment] 2022-07-30 06:47
Hi , on the preference settings, I found this and it worked for me

![image](https://user-images.githubusercontent.com/23723296/181878452-3bf2596c-f583-41d7-9070-b8fd26d5dd76.png)
