### ISSUE TITLE
Autocomplete problem when using table aliases

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#5247] opened 2019-02-11 08:47 UTC
#### System information: 
Windows 7 Enterprise SP1
- DBeaver 5.3.x (various) but includes 5.3.4
- Whatever is bundled with DBeaver
- None

#### Connection specification:
- Oracle

#### Describe the problem you're observing:

When I use autocomplete to select a column (Ctrl-SPace) in a query with a table alias it fails with "no proposals". 

If I do the same operation without the table alias, it works, and I get a list of columns to select from.

Pretty sure this has been the case with several 5.3.x releases, I am currently using 5.2.5 which does not exhibit the problem.

I see this has been raised before but not for a while so perhaps a new issue?

#### Steps to reproduce, if exist:

SELECT a.[autocomplete here] from my_table a; --  Doesn't work

SELECT [autocomplete here] from my_table; --  Works

**Comment by thisisbinod** [comment] 2019-02-15 14:31
I am facing the exact same issue. I am on the latest version currently. I remember few versions ago, it was working fine.

**Comment by bobf32** [comment] 2019-02-21 09:38
Follow-up: I installed 5.3.5 yesterday and the autocomplete worked when specifying an alias in the query. Today it doesn't. I have the keepalive set on all my connections, but even after a disconnect / connect queries with aliases do not autocomplete. 

Back to 5.2.5 again for now.

**Comment by bobf32** [comment] 2019-03-11 12:13
Additional info re 6.0.0 behaviour:

`SELECT * FROM {my_schema}.{my_table} o WHERE o.<C-SPACE>`

produces a proposal list consisting of all columns from {my_schema}.{my_table}. As expected.

`SELECT * FROM user_objects o WHERE o.<C-SPACE>`

produces an empty proposal list. I would expect this list to consist of all columns from the standard Oracle dictionary view user_objects.

**Comment by bobf32** [comment] 2019-03-27 17:57
Update re 6.0.1, Now, none of these results in a list of possible column completions:

- queries against dictionary views like, user_tables, with table alias
- queries against dictionary views like, user_tables, without table alias
- queries against tables owned by currently logged in user, with table alias

Queries against tables owned by currently logged in user, with no table alias seem to offer auto complete suggestions, but that's presumably only useful for tables with only one table in!

Help! Don't make me go back to sqldeveloper :)

**Comment by bobf32** [comment] 2019-04-09 08:18
Still not working in 6.0.2. 

I find myself using 5.1.6 as this version is the latest I have found that supports completion well, and allows for the execution of PL/SQL blocks.

**Comment by ThangLeQuoc** [comment] 2019-05-06 00:56
Updated from the latest version **6.0.4**, it's dead again
![image](https://user-images.githubusercontent.com/20574640/57202863-764cb800-6fd4-11e9-8431-e30ee4217526.png)

**Comment by Evil2000** [comment] 2019-05-06 09:31
Same here in 6.0.4.201925252017 with Firebird connection:
![grafik](https://user-images.githubusercontent.com/697191/57217264-6e9c0c00-6ff2-11e9-8f06-11d1907d21a3.png)

**Comment by thisisbinod** [comment] 2019-05-08 17:10
For me it's working but still sometime buggy though. If auto suggestion doesn't work then I try couple of things like removing extra lines in the code or refreshing database and it will start working just fine. Thank you all for working so hard to make such a great product!

**Comment by ZeusDeus** [comment] 2019-05-27 07:17
same, but I can't get it to work on 5.2.5 either, it works only when full table name is specified
oracle, mac os

**Comment by Evil2000** [comment] 2019-07-01 10:35
Still not fixed in 6.1.1 :-( Even specifying the full table name doesn't seem to help.

**Comment by jim256** [comment] 2019-08-08 21:16
Not working for me.
OS X Mojave 10.14.6 (18G87)
DBeaver 6.1.4
Database is Snowflake

The box usually doesn't come up at all in my case.

**Comment by Evil2000** [comment] 2019-08-09 06:03
On Windows this seems to work again in DBeaver 6,1,4 with Firebird 2.5.

**Comment by bozhidarc** [comment] 2019-08-22 13:48
Not working with PostgreSQL under Windows 10 with DBeaver 1.6.5.

**Comment by konpl** [comment] 2019-09-20 11:53
The same issue with MS SQL Server under Windows 7 with DBeaver 6.2.0.

**Comment by SteveLGraf** [comment] 2019-09-30 14:25
Same issue 
DBeaver 6.2.1
Mojave 10.14.6
Oracle 12.2.0

**Comment by nxmaxx** [comment] 2019-12-02 11:13
Still not working with aliases on PostgresSQL with DBeaver 6.3.0 :
![completeBug](https://user-images.githubusercontent.com/20315647/69954953-a417c200-150d-11ea-89a9-2e0e56bd476e.png)

**Comment by maciey** [comment] 2020-01-14 08:48
Same here v.6.3.2, issues with autocompleton (postgress & infromix)
I have impression 6.2.x worked better in this matter

**Comment by uslss** [comment] 2020-01-27 18:35
cannot reproduce on 6.3.4 EA (postgresql)
![image](https://user-images.githubusercontent.com/31996417/73202811-e7c52b80-414c-11ea-86fd-c81ffa7e6d1c.png)
is it still actual?

**Comment by AndrewGabelliTR** [comment] 2020-01-28 08:39
I think this is mostly fixed in 6.3.0. However I still see autocomplete offering no suggestions if the (Oracle) object being selected from is a synonym to an object in another schema.

**Comment by bobf32** [comment] 2020-01-28 08:40
I think this is mostly fixed in 6.3.0. However I still see autocomplete offering no suggestions if the (Oracle) object being selected from is a synonym to an object in another schema.

**Comment by nxmaxx** [comment] 2020-01-28 09:04
Testing it on 6.3.3:
![bug](https://user-images.githubusercontent.com/20315647/73249301-a9b81e00-41c5-11ea-9d3e-f7b783f0f340.png)
Seems to occur on tables with a guid in their name

**Comment by uslss** [comment] 2020-06-29 11:46
seems that issue from the first message is solved. If it is reproducible in any other cases - feel free to create new ticket.

**Closed by uslss** 2020-06-29 11:46 UTC
Labels: bug, can't reproduce

**Comment by ar-work-acc** [comment] 2023-03-06 03:39
Version 22.3.4.202302060909, same problem with MySQL 8.

**Comment by skelawsky** [comment] 2024-01-16 17:43
same :/
