### ISSUE TITLE
Oracle package compile doesn't show compile errors

### ISSUE THREAD

**Issue by yaoguoba** [dbeaver/dbeaver#5453] opened 2019-03-11 02:05 UTC
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 5.3.5+
- Java version 1.8
- Additional extensions

#### Connection specification:
- Database name and version Oracle 12c
- Driver name ojdbc8
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Do not show any compile error or compile log when I save&persist the package. Compile always success.

#### Steps to reproduce, if exist:
~5.3.4 is OK
![image](https://user-images.githubusercontent.com/18393410/54095892-62c20e00-43e4-11e9-9880-1ef7f15fffb7.png)

5.3.5&6.0.0
![image](https://user-images.githubusercontent.com/18393410/54095814-124ab080-43e4-11e9-8548-0f395dc2d2e1.png)

**Comment by serge-rider** [comment] 2019-03-12 09:07
Since 5.3.5 we don't compile packages along with package save. 
So saving package do not validate package contents.

You need to perform compile separately (ctrl+f9 or click on Compile in the context menu)

**Comment by yaoguoba** [comment] 2019-03-12 09:33
Push ctrl+f9, also success.

**Comment by p91paul** [comment] 2019-03-12 20:57
When you say "Since 5.3.5 we don't compile packages along with package save.", is this by design or is it a bug that is going to be fixed? If the former, may I ask why is that?

**Comment by adeorato** [comment] 2019-03-23 06:57
> Since 5.3.5 we don't compile packages along with package save.

As far as I can see (SQL-Log-Viewer), this is not correct. In the "old world" the commands
```
ALTER PACKAGE PKG_FSRI_DATA_LOAD COMPILE;
ALTER PACKAGE PKG_FSRI_DATA_LOAD COMPILE BODY;
```
and the errors are displayed. Now DBeaver only calls the first compilation (no more body). The first command always returns "true" and the errors have to be checked explicitly (show errors). It seems that this does not (anymore) happen. 

But the display of "Compiled successfully" (screenshot) leads to two possibilities:
* It is compiled and errors are ignored.
* The message is wrong

Either way, it's a critical behaviour.

**Comment by DragonStorm97** [comment] 2019-04-03 05:07
I Also get the same (agreed, Critical) issue. it looks like a `ALTER PACKAGE SOME_PACKAGE COMPILE BODY` is never called. so it only compiles the spec and not the body, then when going to call the package it fails as it tries to actually compile the body.

this seems to be an easy fix of just adding the compile body clause.
Any idea when this can/will be fixed? I just updated from 5.3.4 and got this issue, and would prefer to keep the niceties of 6.0.1 which I'm on now.

**Comment by DragonStorm97** [comment] 2019-04-16 04:31
@serge-rider Can this one get some love? seems to be a relatively simple fix.

**Comment by pszabo1977** [comment] 2019-05-31 08:05
@serge-rider I'm facing the very same issue within the latest early access version (6.1.0).

Steps to reproduce:
1. Create a proper oracle package
2. Save it to DB (Ctrl+S) 
3. Make some trivial error in the code (ex.:     modify a simple  ' null; '    line to '  nu ll;  '  
4. Save (Ctrl+S) or (Ctrl + F9) also drops back with "... compiled successfully" message

IF I close the editor, re-open it, and than pressing Ctrl+F9 it's popping up the normal compilation error message.

**Comment by mastachaos** [comment] 2019-06-10 11:47
I'd also love to see a fix for this.    It makes editing a procedure very difficult as it always reports a success, even when there are errors.

**Comment by ZeroHager** [comment] 2019-06-11 23:02
Hi all,
I have the same problem, my example, an "x" on function "TEST" and a missing semicolon on syntax "RETURN 0" (Oracle 9i), compiled successfully
![ima_1](https://user-images.githubusercontent.com/40251003/59312367-26fc4600-8c6a-11e9-8e0f-19871b360e3b.png)

Now Oracle 11g, same error, missing semicolon on syntax "RETURN 0" but this time I have a compilation error
![ima_2](https://user-images.githubusercontent.com/40251003/59312477-7e9ab180-8c6a-11e9-855f-8ff8200a430e.png)

I really appreciate if someone can fix this.

Thanks for your time.

**Comment by nonpervenuto** [comment] 2019-07-19 15:58
I have the same problem as described from @pszabo1977 and I confirm it happens with Oracle 12c.
I tried the latest version of dbeaver and an old one (5.3.5) with the same result
As a workaround after I save a stored procedure i run this query:

select * from all_errors where name ='<package name>' order by sequence

**Comment by muslimoff** [comment] 2019-08-02 11:08
Hi all,
More clarified info IMHO below. Symptoms [here](
https://github.com/dbeaver/dbeaver/issues/5453#issuecomment-475845859)
> I Also get the same (agreed, Critical) issue. it looks like a `ALTER PACKAGE SOME_PACKAGE COMPILE BODY` is never called. so it only compiles the spec and not the body, then when going to call the package it fails as it tries to actually compile the body.

Case 1. Compilation of unmodified package, body of wich have errors:
![image](https://user-images.githubusercontent.com/15119293/62365104-0acba580-b545-11e9-9b5a-42f344c683ea.png)

Case 2. 
* Change package body
* Ctrl + S (save)
* Ctrl + F9 (compile)
* see second image - syntaxys error persists, but!
* Reopening editor - we are in Case #1

![image](https://user-images.githubusercontent.com/15119293/62366042-9cd4ad80-b547-11e9-9cea-973897b84a9c.png)

**Comment by Zidkon** [comment] 2019-08-09 15:12
Same issue, please give this some attention, is very hard to work checking every some time at SQLDeveloper if the package compiled or not.

**Comment by earlb710** [comment] 2019-08-27 12:12
Using Oracle 12, DBeaver 6.1.4 and it is still an issue - this is a deal breaker, cannot use this program if it cannot show errors.
Errors is package spec is shown but package body saved, compiled, but errors are ignored. If I use SQLDeveloper, it shows that there is errors in the package body.

**Comment by lufivuahaitac** [comment] 2019-09-03 07:43
Using Oracle 12, DBeaver 6.1.5 and it is still an issue

**Comment by k0mita** [comment] 2019-09-15 13:02
Still an issue with
Oracle 18c and DBeaver 6.2.0.201909081341

**Comment by mastachaos** [comment] 2019-09-16 11:06
@serge-rider can we get this labeled as a bug? This is pretty much a deal breaker for anyone who works in Oracle procedures or packages.

**Comment by FalconShadow** [comment] 2019-10-09 16:04
Yo tuve el mismo problema por meses. Finalmente lo que yo hice fue cambiar una propiedad del driver.
desde
OCIErrHandle : 0 
a 
OCIErrHandle : 1

Espero que les ayude.

![image](https://user-images.githubusercontent.com/28327588/66498853-26977e80-ea95-11e9-9ade-9673db181a40.png)

**Closed** 2019-12-26 10:58 UTC
Labels: question, x:oracle
