### ISSUE TITLE
[Snowflake] Duplicate values in column filter for Date and Time columns

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15261] opened 2022-01-24 07:10 UTC
#### System information: 
- Win10
- DBeaver CE 21.3.3

#### Connection specification:
- Snowflake

#### Describe the problem you're observing:
In the column filter window for Date and Time columns you can see valгes with and without quotes. Both are inserted with quotes into the filter's search bar above the data grid.
![image](https://user-images.githubusercontent.com/43252954/150736955-7004989a-5604-4b83-99ca-cb056b6bed18.png)
![image](https://user-images.githubusercontent.com/43252954/150736975-826c5242-f4fc-4c61-95df-9810a7a04e8c.png)

**Comment by LonwoLonwo** [comment] 2022-01-24 08:25
Duplicate of https://github.com/dbeaver/dbeaver/issues/14858

**Closed as completed by LonwoLonwo** 2022-01-24 08:25 UTC
Labels: duplicate, x:snowflake, xf:filters
