### ISSUE TITLE
Error procedure comment show

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#9466] opened 2020-08-06 08:26 UTC
dbeaver 7.1.4

1. Create procedure in SQL editor
CREATE OR REPLACE PROCEDURE form.proc_tem(p_temp integer)
 LANGUAGE plpgsql
AS $procedure$ 
declare
  g int4;
begin
  g = 1;
end;
$procedure$
;

COMMENT ON PROCEDURE form.proc_tem(int4) IS 'THIS POCEDURE NOT A FUNCTION';

2. Open code of this procedure in object tree
![изображение](https://user-images.githubusercontent.com/61137576/89508873-f53c2c00-d7e7-11ea-81f4-064d0bb413bb.png)

I seen wrong comment script. This is procedure, not a function!!!

3. Click to Save in this window
![изображение](https://user-images.githubusercontent.com/61137576/89509056-3f251200-d7e8-11ea-9397-71fd0220db49.png)

I can save this function after i corrected COMMENT ON FUNCTION form.proc_tem(int4) IS 'THIS POCEDURE NOT A FUNCTION';

to

COMMENT ON PROCEDURE form.proc_tem(int4) IS 'THIS POCEDURE NOT A FUNCTION';

only.

**Comment by kseniiaguzeeva** [comment] 2020-08-06 13:06
By some reason COMMENT is not created at all, when I create the procedure. Do you use Postgresql 12?

**Comment by detkliff** [comment] 2020-08-07 06:32
> 
> 
> By some reason COMMENT is not created at all, when I create the procedure. Do you use Postgresql 12?

yes i do. Postgresql version is 12.3

**Comment by detkliff** [comment] 2020-08-11 04:59
> 
> 
> By some reason COMMENT is not created at all in DDL, when I create the procedure. Do you use Postgresql 12?

is full support Postgresql 12 planned? Because many erorrs with 12 version

**Comment by ShadelessFox** [comment] 2020-09-22 09:41
Can't reproduce on version 7.2.1. Is the problem still actual for you @detkliff?

**Comment by uslss** [comment] 2020-09-28 11:45
already fixed in scope of #8993

**Closed by uslss** 2020-09-28 11:45 UTC
Labels: bug, can't reproduce, wait for response
