### ISSUE TITLE
No Error Logged to Error Log on View Panel Failure

### ISSUE THREAD

**Issue by shawnweeks** [dbeaver/dbeaver#8621] opened 2020-05-04 23:16 UTC
#### System information: 
- Operating system (distribution) and version: MacOS Catalina 10.15.4
- DBeaver version: 7.0.2.202004051509
- Additional extensions: None

#### Connection specification:
- Database name and version: N/A - Denodo 7.x
- Driver name: N/A- Denodo 7.x
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I'm trying to troubleshoot what I assume is an out of spec JDBC Driver provided by Denodo aka www.denodo.com but I'm unable to confirm anything because the exception doesn't result in an error in the Error Log View. After expanding Views/my_view_name I get the following error but I really need the full stack trace to figure out exactly where the driver is failing and maybe what DBeaver is calling
. I'm using the "Generic" option with the https://files.denodo.com/support/releases/Denodo/7.0/driver/denodo-vdp-jdbcdriver.jar?fname=denodo-vdp-jdbcdriver-7.0-update-20200310.jar version of the JAR.

SQL Error: Error in method findColumn(). Field name not found.
  Error in method findColumn(). Field name not found.
  Error in method findColumn(). Field name not found.

To be clear the exception isn't the DBeaver Bug, the bug is that the exception isn't getting logged anywhere preventing me from troubleshooting furthur.

#### Include any warning/errors/backtraces from the logs

<img width="1920" alt="Screen Shot 2020-05-04 at 6 10 15 PM" src="https://user-images.githubusercontent.com/9768773/81022467-4af0e900-8e33-11ea-9acf-cb93890d1a4f.png">
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4580410/dbeaver-debug.log)

**Comment by uslss** [comment] 2020-05-05 09:47
hi @shawnweeks ,
could you check dbeaver-debug.log? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by shawnweeks** [comment] 2020-05-05 11:29
I checked there as well, nothing.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4580412/dbeaver-debug.log)

**Comment by serge-rider** [comment] 2020-05-24 16:53
This is weird.
I don't see any logging in debug-log. Although there should be some logging about connection initiation. 
I can't test this as I don't have test Denodo instance.

Anyhow, I've added extra logging of all items loading errors.
Please try in the new dbeaver version.

**Comment by shawnweeks** [comment] 2020-05-24 17:29
Is this fix in 7.0.5 the current release or do I need to wait? I can test this tomorrow when I get back home.

**Comment by uslss** [comment] 2020-05-26 14:32
@shawnweeks you could test if the issue is fixed in EA version https://dbeaver.io/files/ea/

**Comment by shawnweeks** [comment] 2020-05-29 14:35
Tested in the EA version this morning and my exception is gone so apparently you fixed whatever edge case the driver was hitting.

**Comment by kseniiaguzeeva** [comment] 2020-06-01 08:35
Thank you for your help! Closed.

**Closed by kseniiaguzeeva** 2020-06-01 08:35 UTC
Labels: bug, environment, wait for response
