### ISSUE TITLE
Cannot run program "/run/user/1000/doc/aed1eb8/bin/mysqldump" since version 23.1.4/snap (Permission denied)

### ISSUE THREAD

**Issue by mat-hew1** [dbeaver/dbeaver#20886] opened 2023-08-14 13:02 UTC
### Description

I try to do a mysqldump and get the error
```
Error executing process
  Cannot run program "/run/user/1000/doc/aed1eb8/bin/mysqldump" (in directory "/run/user/1000/doc/aed1eb8/bin"): error=13, Permission denied
  Cannot run program "/run/user/1000/doc/aed1eb8/bin/mysqldump" (in directory "/run/user/1000/doc/aed1eb8/bin"): error=13, Permission denied
    error=13, Permission denied
    error=13, Permission denied
```

is almost the same as in #18958, but now in version 23.1.4/Ubuntu 22.04/snap install.
The mysqldump command is working in termial.

```
/run/user/1000/doc/aed1eb8/bin$ ll mysqldump
-rwxr-xr-x 1 root root 6879872 Mai 12 01:15 mysqldump*
```

### DBeaver Version

Comunity Edition, Version 23.1.4.202308061552

### Operating System

Ubuntu 22.04.2

### Database and driver

MySQL (client installed)

### Steps to reproduce

Trying to create DB dump

### Additional context

SSH tunneled connection

**Comment by E1izabeth** [comment] 2023-08-15 09:46
Thank you for bug report. So, I'm closing this issue as a duplicate of #19055.
You could read these comments, probably you may find a workaround https://github.com/dbeaver/dbeaver/issues/7521#issuecomment-723479076

**Closed as not planned by E1izabeth** 2023-08-15 09:46 UTC
Labels: duplicate, xf:snap, xf:native clients

**Comment by mat-hew1** [comment] 2023-08-15 13:42
Hi @E1izabeth,
I think it is not a duplicate, because of different version.
Also, none of the workarounds helped, I didn't try the mount one because it's not my PC where I work and don't want to create new mounts there.

I just find it unpleasant that a Java app does not accept the system permissions (r-x) and after an automatic snap update the exports/imports suddenly do not work!

**Comment by E1izabeth** [comment] 2023-08-15 13:45
You could try to install DBeaver not from snap. This issue exists only on snap installations.

**Comment by vkywalker** [comment] 2024-12-03 08:50
I have the same issue with new version 24.3.0, I have tried to set up local client (Ubuntu) to /usr , but it is not possible.  The client config automatically  fills up /run/user/1000/doc/32703207/usr and ofcourse generates error because of the permissions.  So I keep using  24.2.1.

**Comment by yjgcwgg** [comment] 2024-12-24 11:09
@vkywalker Do not use snap, use flatpak is ok.

**Comment by Neschadin** [comment] 2025-06-17 20:59
@E1izabeth i installed DBeaver v25.1.0 from flatpack and from downloaded archive, anyway i got the same issue.

> alex@localhost:~> cat /etc/os-release
> NAME="openSUSE Tumbleweed"
> VERSION="20250614"

> alex@localhost:~> flatpak list | grep dbeaver
> DBeaver Community       io.dbeaver.DBeaverCommunity     25.1.0  stable  system

![Image](https://github.com/user-attachments/assets/8f0c1210-065f-43c0-9ccd-fa9bfb6e141a)

**Comment by x011** [comment] 2025-12-13 09:43
Worthless  program that doesn't allow a simple dump.
