### ISSUE TITLE
DBeaver does not have newly saved database connections on new open (new session)

### ISSUE THREAD

**Issue by AzisK** [dbeaver/dbeaver#7296] opened 2019-11-26 13:24 UTC
#### System information: 
- macOS Mojave Version 10.14.6 (18G1012)
- DBeaver Version 6.2.5.201911171645

#### Describe the problem you're observing:
When I add a new database connection and close DBeaver, then open it again, the connection is gone with the new start-up.

#### Steps to reproduce, if exist:
1. create new connection
2. close DBeaver
3. open DBeaver
4. try to find the created connect (fail!)

#### Logs
```
!SESSION 2019-11-26 14:44:32.932 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_LT
Framework arguments:  -keyring /Users/akrusna/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/akrusna/.eclipse_keyring

!ENTRY org.jkiss.dbeaver.model 4 0 2019-11-26 14:48:17.822
!MESSAGE Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found

!ENTRY org.jkiss.dbeaver.model 4 0 2019-11-26 14:48:33.785
!MESSAGE Error saving datasources configuration
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-11-26 14:48:33.785
!MESSAGE Error creating backup copy of /General/.dbeaver/data-sources.json
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2019-11-26 14:48:33.785
!MESSAGE A resource already exists on disk '/Users/akrusna/Library/DBeaverData/workspace6/General/.dbeaver/.data-sources.json.bak'.
!STACK 0
java.lang.Exception: A resource already exists on disk '/Users/akrusna/Library/DBeaverData/workspace6/General/.dbeaver/.data-sources.json.bak'.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.File.create(File.java:141)
	at org.jkiss.dbeaver.utils.ContentUtils.makeFileBackup(ContentUtils.java:510)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveDataSources(DataSourceRegistry.java:682)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.addDataSource(DataSourceRegistry.java:440)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard.performFinish(NewConnectionWizard.java:199)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.jkiss.dbeaver.ui.dialogs.connection.CreateConnectionDialog.buttonPressed(CreateConnectionDialog.java:58)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4193)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.dialogs.connection.CreateConnectionDialog.open(CreateConnectionDialog.java:83)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceCreateHandler.execute(DataSourceCreateHandler.java:36)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4193)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:226)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-11-26 14:49:16.852
!MESSAGE Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found

!ENTRY org.jkiss.dbeaver.model 4 0 2019-11-26 14:49:38.150
!MESSAGE Error saving datasources configuration
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-11-26 14:49:38.150
!MESSAGE Error creating backup copy of /General/.dbeaver/data-sources.json
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2019-11-26 14:49:38.150
!MESSAGE A resource already exists on disk '/Users/akrusna/Library/DBeaverData/workspace6/General/.dbeaver/.data-sources.json.bak'.
!STACK 0
java.lang.Exception: A resource already exists on disk '/Users/akrusna/Library/DBeaverData/workspace6/General/.dbeaver/.data-sources.json.bak'.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.File.create(File.java:141)
	at org.jkiss.dbeaver.utils.ContentUtils.makeFileBackup(ContentUtils.java:510)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveDataSources(DataSourceRegistry.java:682)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.addDataSource(DataSourceRegistry.java:440)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard.performFinish(NewConnectionWizard.java:199)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.jkiss.dbeaver.ui.dialogs.connection.CreateConnectionDialog.buttonPressed(CreateConnectionDialog.java:58)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4193)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.dialogs.connection.CreateConnectionDialog.open(CreateConnectionDialog.java:83)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceCreateHandler.execute(DataSourceCreateHandler.java:36)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4193)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:226)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-11-26 14:49:50.525
!MESSAGE Error saving datasources configuration
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-11-26 14:49:50.525
!MESSAGE Error creating backup copy of /General/.dbeaver/data-sources.json
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2019-11-26 14:49:50.525
!MESSAGE A resource already exists on disk '/Users/akrusna/Library/DBeaverData/workspace6/General/.dbeaver/.data-sources.json.bak'.
!STACK 0
java.lang.Exception: A resource already exists on disk '/Users/akrusna/Library/DBeaverData/workspace6/General/.dbeaver/.data-sources.json.bak'.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.File.create(File.java:141)
	at org.jkiss.dbeaver.utils.ContentUtils.makeFileBackup(ContentUtils.java:510)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveDataSources(DataSourceRegistry.java:682)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.access$6(DataSourceRegistry.java:657)
	at org.jkiss.dbeaver.registry.DataSourceRegistry$ConfigSaver.run(DataSourceRegistry.java:868)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Looking `~/Library/DBeaverData/workspace6/General/.dbeaver/.project-metadata.json.bak` at I see
```
{"resources":{"Scripts/Script-1.sql":{"sql-editor-data-source-id":"vertica-jdbc-8-167117eeeb7-511c89fe7f54d9d1"},"Scripts/Script-10.sql":{"sql-editor-data-source-id":"apache_hive2-16ea7523e40-30d36a836699a17c"},"Scripts/Script-2.sql":{"sql-editor-data-source-id":"mysql8-16cf6ba3193-275da2832ec49ee6"},"Scripts/Script-3.sql":{"sql-editor-data-source-id":"mysql8-167164e6cc4-6e10ad12a413b400"},"Scripts/Script-4.sql":{"sql-editor-data-source-id":"mysql8-167164e6cc4-6e10ad12a413b400"},"Scripts/Script-5.sql":{"sql-editor-data-source-id":"mysql8-167164e6cc4-6e10ad12a413b400"},"Scripts/Script-6.sql":{"sql-editor-data-source-id":"vertica-jdbc-8-167117eeeb7-511c89fe7f54d9d1"},"Scripts/Script-7.sql":{"sql-editor-data-source-id":"mysql8-16ea2a49849-e55f373dd188154"},"Scripts/Script-8.sql":{"sql-editor-data-source-id":"mysql8-16977a1c224-6889d3b5b98fcaa4"},"Scripts/Script-9.sql":{"sql-editor-data-source-id":"mysql8-16977a1c224-6889d3b5b98fcaa4"},"Scripts/Script.sql":{"sql-editor-data-source-id":"mysql8-16cf2376105-26ad3c5b43a8e31e"}}}
```
where Hive connection is the one that was added and did not appear on opening a new session.

**Comment by uslss** [comment] 2019-11-26 13:57
seems to be duplicate of #7251

**Closed by uslss** 2019-11-26 13:57 UTC
Labels: bug
