### ISSUE TITLE
Dameng database support

### ISSUE THREAD

**Issue by zero-wsh** [dbeaver/dbeaver#20740] opened 2023-07-30 07:01 UTC
### Description

Official website of China Da Meng Database http://www.dameng.com/

Tables and table fields cannot be modified

1: Table fields cannot be modified

2: Table and column annotations cannot be modified
<img width="924" alt="image" src="https://github.com/dbeaver/dbeaver/assets/44697042/d6f60a3a-cb82-4cb3-a769-136e65f25455">

### DBeaver Version

23.1.0.202306120813

### Operating System

windows11

**Comment by LonwoLonwo** [comment] 2023-07-30 19:26
Hello @zero-wsh 

How are you connecting to your database? DBeaver doesn't have official support for this database.

**Comment by zero-wsh** [comment] 2023-07-31 01:05
Referenced this blog：https://blog.csdn.net/u012063422/article/details/123759444
Connect using a driver

**Comment by zero-wsh** [comment] 2023-07-31 01:05
> Hello @zero-wsh
> 
> How are you connecting to your database? DBeaver doesn't have official support for this database.

Referenced this blog：https://blog.csdn.net/u012063422/article/details/123759444
Connect using a driver

**Comment by LonwoLonwo** [comment] 2023-07-31 13:15
Ok, you are using a custom ODBC driver and connection.

DBeaver doesn't have the support of this database, so I marked this ticket as a feature request.

**Comment by E1izabeth** [comment] 2023-09-12 16:51
Duplicate of #10133

**Closed as not planned by E1izabeth** 2023-09-12 16:51 UTC
Labels: duplicate, new driver, xf:metadata
