### ISSUE TITLE
Save the size of the SQL code complete

### ISSUE THREAD

**Issue by luapfr** [dbeaver/dbeaver#32370] opened 2024-05-14 00:29 UTC
Any position?

I just downloaded the latest version and the SQL code completer doesn't save the size. 

https://github.com/dbeaver/dbeaver/issues/20498

**Comment by E1izabeth** [comment] 2024-05-14 06:46
No update on the mentioned issue.

Closing as duplicate of #20498, #21374

**Closed as not planned by E1izabeth** 2024-05-14 06:46 UTC
Labels: duplicate, xf:ui
