### ISSUE TITLE
Caching issue: DDL for stored procedure not updated if SP is changed

### ISSUE THREAD

**Issue by Aileron79** [dbeaver/dbeaver#15143] opened 2022-01-11 08:34 UTC
#### System information: 
- Operating system (distribution) and version
Win 10

- DBeaver version
21.2.3.202110151816

- Additional extensions

#### Connection specification:
- Database name and version
Azure SQL 

- Driver name
Azure SQL Server

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
- Opened a stored procedure by right clicking => Generate SQL => DDL
- Colleague edited the SP in a separate session
- Opened the same procedure by right clicking => Generate SQL => DDL
- Changes did not show up and I accused him wrongly of not having made the required changes

Looks like caching issue to me, dbeaver seems to not fetch the DDL from the server when it is cached.

Note that even "Invalidate/Reconnect" does not solve the issue, the connection has to be closed and reconnected, then the changes will show up.

If it is not an issue with the Azure driver I suggest not to cache the DDL or, at least, provide a "reload" button in the popup window displaying the DDL.

#### Steps to reproduce, if exist:
- See above, open stored procedure as described above, copy DDL to a new Script, ALTER it, get DDL again and the changes won't show up before the server is disconnected entirely and reconnected.

**Comment by Matvey16** [comment] 2022-01-19 10:06
Looks like a duplicate of #15129 at least the cause of both issues seems to be the same

@Aileron79 Does a refresh button change the DDL generated after pressing it? Or the only workaround is to disconnect and reconnect?
![image](https://user-images.githubusercontent.com/82543000/150109072-aec89d08-8f21-4bba-8db9-0e7b601cdd35.png)

**Comment by uslss** [comment] 2022-01-27 18:17
duplicate of #15129

**Closed as completed by uslss** 2022-01-27 18:17 UTC
Labels: duplicate, x:mssql, xf:metadata

**Comment by uslss** [comment] 2022-01-27 18:28
#8922 #6398
