### ISSUE TITLE
MS SQL Server Autocompletion removes 'dbo' schema

### ISSUE THREAD

**Issue by roman-svystun** [dbeaver/dbeaver#4131] opened 2018-08-31 12:48 UTC
After updating to DBeaver 5.1.5, the autocompletion bug started happening when typing queries for the SQL Server DB. The `dbo` schema word is removed each time I hit Enter to autocomplete the table name:

![dbeaver515-516-autocompletionbug](https://user-images.githubusercontent.com/20768687/44912950-781ef700-ad34-11e8-93d5-8a38b3f58015.gif)

This issue is reproducible on both 5.1.5 and an August build of 5.1.6.
The workaround is to type a table name entirely and not rely on completion.

My *SQL Completion* preferences are the following:

![image](https://user-images.githubusercontent.com/20768687/44913113-0a26ff80-ad35-11e8-84e3-419abeeeb94d.png)

**Comment by akoval-liaison** [comment] 2018-08-31 12:49
Reproducible issue, +1

**Comment by serge-rider** [comment] 2018-09-16 15:16
Looks like it was already fixed in 5.2

**Closed by serge-rider** 2018-09-16 15:16 UTC
Labels: bug, can't reproduce
