### ISSUE TITLE
Content of JSONB columns are not displayed on Panel -> Value

### ISSUE THREAD

**Issue by andvenancio** [dbeaver/dbeaver#7362] opened 2019-12-04 12:38 UTC
#### System information: 
- Operating system (distribution) and version: **Linux Mint 19.1 Cinnamon**
- DBeaver version: **6.3.0**
- Additional extensions

#### Connection specification:
- Database name and version: **PostgreSQL**
- Driver name: **PostgreSQL JDBC Driver**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **No**

#### Describe the problem you're observing:
After update DBeaver to version 6.3.0 the content of JSONB columns are not displayed on Panel -> Value.

#### Steps to reproduce, if exist:
Execute a statement on a table with JSONB column, select de column on grid and click on "Panel" to view.

#### Include any warning/errors/backtraces from the logs
![image](https://user-images.githubusercontent.com/25935569/70143163-a8f98480-1679-11ea-8769-9d9a3906a8a2.png)

**Comment by serge-rider** [comment] 2019-12-04 15:48
Duplicate of #7331

**Closed by serge-rider** 2019-12-04 15:48 UTC
Labels: bug, duplicate
