### ISSUE TITLE
Unable to execute sql present in file with extension .md

### ISSUE THREAD

**Issue by emanueol** [dbeaver/dbeaver#21221] opened 2023-09-14 21:10 UTC
### Description

Hi after I just learned markdown (obsidian, sync etc.), I'm now starting to convert my large collection of .sql scripts into .md files, they look great in obsidian, GitHub, etc..

but.. after opening /md file with SQL statements inside dbbeaver is unable to execute anything, pressing 
CTRL+enter, ALT+X etc don't have any effect, see GIF:
![problem - unable execute sql on non sql file extension files](https://github.com/dbeaver/dbeaver/assets/8422412/f9ac42ef-bc5d-4280-8cf4-1ee709331785)

1. How can I execute sql on any file extension (.md etc) ?
2. Also I was unable to drag .md from windows file explorer into DBeaver :( that action would open notepad++ which is my open everything tool. Then I found in DBeaver a workaround to display a file explorer by doing: Project windows > right click Scripts > Create > Link Folder, again double click .md would open it on external notepad++, but I found I can drag file into top area in dbeaver where scripts tabs are and it opened.. But.. I'm unable to execute sql inside as per above GIF.

I really hope there's some DBeaver configuration or workaround, as this is critical for me as I'm converting all my reference knowledge .sql scripts into .md (its minor changes really).

thanks in advance ~
Emanuel O.

### DBeaver Version

Community Edition - Version 23.2.0.202309041200

### Operating System

windows 10

### Database and driver

n.a. but im using Snowflake jdbc

### Steps to reproduce

1. open .md file with sql statements
2. unable to execute any SQL statement

**Comment by E1izabeth** [comment] 2023-09-15 08:55
DBeaver can open as a script only files with sql extension.
I'm closing this issue as a duplicate of #15817. You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2023-09-15 08:55 UTC
Labels: duplicate

**Comment by emanueol** [comment] 2023-09-15 09:01
> DBeaver can open as a script only files with sql extension. I'm closing this issue as a duplicate of #15817. You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

Thanks @E1izabeth i just voted it up.

This is very useful and surely easy to implement, so folloyup notifications on this one.
For the time being we switching into visual studio code till Dbeaver allows working with non .sql file extensions.
