### ISSUE TITLE
Can no longer restore database backups or execute scripts on PostgreSQL

### ISSUE THREAD

**Issue by bcostea** [dbeaver/dbeaver#21418] opened 2023-10-04 08:13 UTC
### Description

After upgrading to 23.2.1 I can no longer restore PostgreSQL backups or run Execute scripts.
I always get

> Error loading wizard settings
> Reason:
> Cannot find database for script execution

OR 

> Error loading wizard settings
> Reason:
> Cannot find database for restoring

### DBeaver Version

Community Edition 23.2.1

### Operating System

macOS Ventura 13.6

### Database and driver

1. Database name and version: PostgreSQL 14.9 aarch64
2. Driver name and version: PostgreSQL JDBC Driver 42.2.5

### Steps to reproduce

1. open a connection
2. right click on a database
3. select Tools > Restore or Tools > Execute script
4. a Settings load dialog will pop up containing the error

**Comment by E1izabeth** [comment] 2023-10-04 08:22
Thank you for bug report. I couldn't reproduce your issue.
Could you check if it's reproducible on early access version? You can download it here https://dbeaver.io/files/ea/

**Comment by bcostea** [comment] 2023-10-04 08:36
Hi, installed EA, I see the same issues
<img width="1440" alt="image" src="https://github.com/dbeaver/dbeaver/assets/3836378/47b034a0-120c-42cc-98db-a94a142bb48f">

<img width="1440" alt="image" src="https://github.com/dbeaver/dbeaver/assets/3836378/9211ca61-4b63-4a3f-80c1-4673ae5cd03d">


Letme know what other information I can provide
Thank you 🤗

**Comment by E1izabeth** [comment] 2023-10-04 08:54
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by bcostea** [comment] 2023-10-04 09:44
Hi, of course, here you go
[dbeaver-debug-1696412196352.log](https://github.com/dbeaver/dbeaver/files/12801899/dbeaver-debug-1696412196352.log)

**Comment by uslss** [comment] 2023-10-04 10:24
Reproduce the issue with restore on schema level. Still cannot reproduce the issue with script

https://github.com/dbeaver/dbeaver/assets/31996417/9f97868b-d8b9-4321-a485-73755f5f4116

**Comment by LonwoLonwo** [comment] 2023-10-05 13:17
Could you please download the latest EA version and see if the issue is gone there?
https://dbeaver.io/files/ea/

**Comment by bcostea** [comment] 2023-10-05 13:36
@LonwoLonwo Works as expected in latest EA, I no longer see the issues in restore (database and schema level) or execute script (database level)

<img width="1124" alt="image" src="https://github.com/dbeaver/dbeaver/assets/3836378/83ea9bce-bdfd-4225-8d6e-d9f918dd6c55">

**Comment by LonwoLonwo** [comment] 2023-10-05 15:38
Thanks for the answer @bcostea 

Closing as a duplicate of #19054

**Closed as completed by LonwoLonwo** 2023-10-05 15:38 UTC
Labels: can't reproduce, xf:native clients
