### ISSUE TITLE
"Native client is not specified for connection"- Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by S2GN** [dbeaver/dbeaver#20580] opened 2023-07-16 21:58 UTC
I'm trying to backup my MySql DBases and I keep getting this ridiculus "Native client is not specified for connection" error, with a rat maze of fields to fill in.

Seriously what I'm I supposed to fill in here?
Why can't DBeaver find the required "client" file itself? (I did install the latest JDBC from Oracle....but what is it?  ...where was it installed? ....IDK.)

Please provide detailed instructions on how to setup and configure this feature.  
- (I see ppl have been complaining about this for YEARS, please fix and/or provide better docs.)

v/r,

-TV

**Comment by Destrolaric** [comment] 2023-07-20 13:45
Hello! Thank you for your request. We are currently working on updating our wiki with the description of installation methods.

**Comment by tabiznet** [comment] 2023-07-23 04:19
How do I work around this?

**Comment by TwonkyHardware** [comment] 2023-08-25 20:47
I am affected by this issue, and I'd like to add my vote to have it addressed.  Thanks!

**Comment by rhuanbarreto** [comment] 2023-09-25 10:54
The option native client is not present on the window so I cannot pass the path there.

![Screenshot 2023-09-25 at 07 51 26](https://github.com/dbeaver/dbeaver/assets/283004/fded4987-b491-4eaa-b418-c85355527eed)

**Comment by mcd92** [comment] 2023-09-30 19:47
Same thing on Pop! OS 22.04 LTS
DBeaver CE - Version 23.2.1.202309250303

![image](https://github.com/dbeaver/dbeaver/assets/20120390/e359ec82-3ef2-4a2a-b8c7-ae9fd070f602)

**Comment by LonwoLonwo** [comment] 2023-10-26 10:26
Maybe this workaround will be helpful: https://github.com/dbeaver/dbeaver/issues/7976#issuecomment-725436879

**Comment by LonwoLonwo** [comment] 2023-10-26 10:27
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/14620

**Closed as not planned by LonwoLonwo** 2023-10-26 10:27 UTC
Labels: duplicate, xo:linux, xf:native clients
