### ISSUE TITLE
truncated sql error message

### ISSUE THREAD

**Issue by collicalex** [dbeaver/dbeaver#1788] opened 2017-06-16 13:23 UTC
When compiling a stored proc (Sybase ASE) with an error;
the error messaged displayed in DBEaver is truncated:

![dbeaver_error](https://user-images.githubusercontent.com/24322371/27228352-87f67646-52a7-11e7-94d2-5c2263c0cac5.png)

Under antother tool, the error message has more data (like the line number).

![sybaseworkspace_error](https://user-images.githubusercontent.com/24322371/27228370-9ca4b1e8-52a7-11e7-8ae8-20ad59d0c911.png)

**Comment by jeisoncp** [comment] 2017-09-15 20:15
I have the same problem.

**Comment by fesbom** [comment] 2017-09-15 20:27
I have the same problem.

**Comment by serge-rider** [comment] 2017-09-17 08:32
I've added SQL error chain to the error message but didn't yet test with Sybase. So moving to 4.2.2 when I'll be able to test it.

**Comment by serge-rider** [comment] 2017-10-01 20:44
Please check in 4.2.2

**Comment by jeisoncp** [comment] 2017-10-03 17:33
@collicalex Where I find this Event window? 

Isn't the same window when you try to submit a procedure by SQL Editor:
![2017-10-03](https://user-images.githubusercontent.com/7952798/31139342-a83d498e-a847-11e7-97f4-45342a3e5e76.png)

**Comment by serge-rider** [comment] 2017-10-05 20:31
Main menu Window->Show View->Error Log.
But it looks like the issue wasn't resolved.
Moving to the next release.

**Comment by marcelovsantos** [comment] 2020-03-10 18:46
SybSQLException have others methods:

* getEedParams
* getStatus
* getLineNumber
* getProcedureName
* getServerName
* getSeverity
* getState
* getTranState

This informations are massive help and could be added in the method [makeMessage(SQLException)](https://github.com/dbeaver/dbeaver/blob/0dde5c3459c5ebfd9e7c9bd3a03a440d5172369c/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/DBException.java#L135)

Sybase SybSQLException documentation:
http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc39001.0605/html/prjdbc/prjdbc79.htm

**Comment by uslss** [comment] 2020-12-07 22:23
cannot reproduce. If issue is still actual for you - feel free to create a new one

**Closed by uslss** 2020-12-07 22:23 UTC
Labels: bug, x:sybase
