### ISSUE TITLE
23.2.5 No RAISE NOTICE is displayed

### ISSUE THREAD

**Issue by LiHanGod** [dbeaver/dbeaver#21924] opened 2023-11-21 07:47 UTC
### Description

Execute the following SQL multiple times using Dbeaver
```SQL
DO 
$$
DECLARE

BEGIN
	RAISE NOTICE '1111';
END;
$$
;
```

Dbeaver 23.2.3.202310221533
![Dbeaver-Bug-00](https://raw.githubusercontent.com/LiHanGod/saveData/master/Dbeaver-Bug-00.png)
![Dbeaver-Bug-01](https://raw.githubusercontent.com/LiHanGod/saveData/master/Dbeaver-Bug-01.png)

Dbeaver 23.2.5.202311191730
![Dbeaver-Bug-02](https://raw.githubusercontent.com/LiHanGod/saveData/master/Dbeaver-Bug-02.png)
![Dbeaver-Bug-03](https://raw.githubusercontent.com/LiHanGod/saveData/master/Dbeaver-Bug-03.png)

### DBeaver Version

23.2.5.202311191730

### Operating System

Win 10

### Database and driver

PostgreSQL : PostgreSQL 14.4 (Debian 14.4-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

Driver: 42.5.2

**Comment by LiHanGod** [comment] 2023-11-21 07:47
23.2.5 RAISE NOTICE Is Not Displayed

**Comment by E1izabeth** [comment] 2023-11-21 07:50
Thank you for bug report. It's a duplicate of #21902

**Closed as not planned by E1izabeth** 2023-11-21 07:50 UTC
Labels: duplicate

**Comment by E1izabeth** [comment] 2023-11-21 07:54
@LiHanGod 
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by LiHanGod** [comment] 2023-11-21 07:58
[Uploading log.zip…]()

**Comment by LiHanGod** [comment] 2023-11-21 07:59
[log.zip](https://github.com/dbeaver/dbeaver/files/13423314/log.zip)

**Comment by E1izabeth** [comment] 2023-11-21 07:59
Thank you
