### ISSUE TITLE
[BUG]Auto Completion produces duplicated table alias

### ISSUE THREAD

**Issue by yiding-he** [dbeaver/dbeaver#21191] opened 2023-09-13 03:04 UTC
### Description

![dbeaver_g2yHGfuMZs](https://github.com/dbeaver/dbeaver/assets/900606/40415b16-d566-49d0-b874-b85b8709cb99)

Auto Completion produces duplicated table alias and it breaks sql statement.

### DBeaver Version

DBeaver CE 23.2.0.202309041200

### Operating System

Windows 11

### Database and driver

It doesn't matter

### Steps to reproduce

This issue does not occur every time. It appears to be related to a particular SQL structure.

**Comment by E1izabeth** [comment] 2023-09-14 10:58
Thank you for bug report. It's a duplicate of #19821
You can vote for that issue with 👍🏻 under the mentioned issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2023-09-14 10:58 UTC
Labels: duplicate, xf:sql editor
