### ISSUE TITLE
Reduce filter options based on the current dataset

### ISSUE THREAD

**Issue by noschang** [dbeaver/dbeaver#11805] opened 2021-03-20 21:15 UTC
I don't believe this is a bug, so I'm opening this issue as a feature request.

DBeaver has the feature of easily filtering a dataset using the filter icon on the "Results" tab. See below:

![Captura de tela de 2021-03-20 17-57-17](https://user-images.githubusercontent.com/709553/111885352-f4868d80-89a5-11eb-8753-de126ea95b84.png)

Given the dataset on the previous picture, if I open the filter for the column ```ADDRESS_CITY```, I am presented with all the distinct values for this column. Then, I can select some options as shown in picture below:

![Captura de tela de 2021-03-20 17-58-03](https://user-images.githubusercontent.com/709553/111885368-141db600-89a6-11eb-9494-ae2d7d101f78.png)

After applying the first filter, you can clearly see in the dataset that it reduced the values of the column ```ADDRESS_STATE``` to only 2 possible values: ```SC``` and ```RS```.

![Captura de tela de 2021-03-20 17-58-16](https://user-images.githubusercontent.com/709553/111885425-7676b680-89a6-11eb-9d68-48892953053f.png)

Now, if I click on the filter icon for column ```ADDRESS_STATE```, what I expect to see is the distinct values that are being shown on the dataset ```SC``` and ```RS```. But it shows all the values. See below:

![Captura de tela de 2021-03-20 17-58-21](https://user-images.githubusercontent.com/709553/111885481-da00e400-89a6-11eb-92a7-41c54693fbc8.png)

So, my request is to make the filters show only the values currently present on the dataset.

I understand that many users are used to the default behavior, so you could implement this as a customizable behavior. Maybe a toggle button near the refresh button (see picture below), that allows you to toggle between the two behaviors with just one click.

![Captura de tela de 2021-03-20 18-14-13](https://user-images.githubusercontent.com/709553/111885699-2dbffd00-89a8-11eb-9e38-a48f11c127fb.png)

**Comment by uslss** [comment] 2021-03-22 08:42
thanks for suggestion
closed as a duplicate of #10549

**Closed as completed by uslss** 2021-03-22 08:42 UTC
Labels: duplicate
