### ISSUE TITLE
"Local Client" missing from dump screen

### ISSUE THREAD

**Issue by Fydon** [dbeaver/dbeaver#21453] opened 2023-10-06 12:09 UTC
### Description

When using DBeaver 23.2.1, the Local Client button is missing on the dump screen. The dump fails as it looks for the binaries in the wrong location. It is looking in `AppData\Local\DBeaver`, but there are in `AppData\Roaming\DBeaverData\drivers\clients\mysql\win`.

Reinstalling DBeaver 23.1.5 restore the Load Client button.
![image](https://github.com/dbeaver/dbeaver/assets/3404761/466d4308-bcc7-4b66-aa43-3a7a18dfdd8b)

### DBeaver Version

Community Edition 23.2.1

### Operating System

Windows 11

### Database and driver

MySQL 5.7
mysql-connector-java:RELEASE 5.1.49

### Steps to reproduce

1. Right click on a database
2. Go to Tools -> Dump database

**Comment by LonwoLonwo** [comment] 2023-10-06 12:42
Hello @Fydon 

Thanks for the report.

This is a duplicate of https://github.com/dbeaver/dbeaver/issues/21282.

The issue is already fixed. The fix will be available in the next release on Monday.

**Closed as completed by LonwoLonwo** 2023-10-06 12:42 UTC
Labels: duplicate, xf:native clients
