### ISSUE TITLE
SSH tunnel not connect from DBeaver to latest linux distros.

### ISSUE THREAD

**Issue by mayerro** [dbeaver/dbeaver#17537] opened 2022-09-02 09:10 UTC
#### System information: 
- Linux, macOS
- DBeaver *

#### Connection specification:
- SSH tunnel 

#### Describe the problem you're observing:
SSH tunnel not connect from DBeaver to latest linux distros.

#### Steps to reproduce, if exist:
Install latest version of any linux distro (ubuntu22,fedora36,redhat8) and update it
Try to setup ssh tunnel from dbeaver connection with rsa key

#### Include any warning/errors/backtraces from the logs
```
2022-08-31 21:36:47.642 - pageant connect exception
com.jcraft.jsch.agentproxy.AgentProxyException: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.connector.PageantConnector$User32
        at com.jcraft.jsch.agentproxy.connector.PageantConnector.<init>(PageantConnector.java:68)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:110)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$7.execute(SSHTunnelConfiguratorUI.java:257)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:603)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2022-08-31 21:36:47.643 - SSH: Connected with ssh-agent
2022-08-31 21:36:47.643 - Creating identity repository
2022-08-31 21:36:47.643 - Configure tunnel
2022-08-31 21:36:47.706 - Connect to tunnel host
2022-08-31 21:36:47.707 - SSH INFO: Connecting to -.-.-.- port 22
2022-08-31 21:36:47.740 - SSH INFO: Connection established
2022-08-31 21:36:47.782 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
2022-08-31 21:36:47.782 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.54
2022-08-31 21:36:47.782 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2022-08-31 21:36:47.783 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2022-08-31 21:36:47.792 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2022-08-31 21:36:47.792 - SSH INFO: SSH_MSG_KEXINIT sent
2022-08-31 21:36:47.811 - SSH INFO: SSH_MSG_KEXINIT received
2022-08-31 21:36:47.811 - SSH INFO: kex: server: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
2022-08-31 21:36:47.811 - SSH INFO: kex: server: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
2022-08-31 21:36:47.811 - SSH INFO: kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
2022-08-31 21:36:47.811 - SSH INFO: kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
2022-08-31 21:36:47.811 - SSH INFO: kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2022-08-31 21:36:47.811 - SSH INFO: kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2022-08-31 21:36:47.811 - SSH INFO: kex: server: none,zlib@openssh.com
2022-08-31 21:36:47.812 - SSH INFO: kex: server: none,zlib@openssh.com
2022-08-31 21:36:47.812 - SSH INFO: kex: server: 
2022-08-31 21:36:47.812 - SSH INFO: kex: server: 
2022-08-31 21:36:47.812 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2022-08-31 21:36:47.812 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2022-08-31 21:36:47.812 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2022-08-31 21:36:47.812 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2022-08-31 21:36:47.812 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2022-08-31 21:36:47.812 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2022-08-31 21:36:47.812 - SSH INFO: kex: client: none
2022-08-31 21:36:47.812 - SSH INFO: kex: client: none
2022-08-31 21:36:47.812 - SSH INFO: kex: client: 
2022-08-31 21:36:47.812 - SSH INFO: kex: client: 
2022-08-31 21:36:47.812 - SSH INFO: kex: server->client aes128-ctr hmac-sha1 none
2022-08-31 21:36:47.812 - SSH INFO: kex: client->server aes128-ctr hmac-sha1 none
2022-08-31 21:36:47.813 - SSH INFO: SSH_MSG_KEX_ECDH_INIT sent
2022-08-31 21:36:47.813 - SSH INFO: expecting SSH_MSG_KEX_ECDH_REPLY
2022-08-31 21:36:47.847 - SSH INFO: Host '-.-.-.-' is known and matches the ECDSA host key
2022-08-31 21:36:47.847 - SSH INFO: SSH_MSG_NEWKEYS sent
2022-08-31 21:36:47.847 - SSH INFO: SSH_MSG_NEWKEYS received
2022-08-31 21:36:47.847 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2022-08-31 21:36:47.879 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2022-08-31 21:36:47.916 - SSH INFO: Authentications that can continue: publickey,keyboard-interactive,password
2022-08-31 21:36:47.916 - SSH INFO: Next authentication method: publickey
2022-08-31 21:36:47.953 - SSH INFO: Disconnecting from -.-.-.- port 22
2022-08-31 21:36:48.055 - Auth fail
com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:519)
        at com.jcraft.jsch.Session.connect(Session.java:183)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:116)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:133)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$7.execute(SSHTunnelConfiguratorUI.java:257)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:603)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

```
2022-08-31 21:23:04.152 - pageant connect exception
com.jcraft.jsch.agentproxy.AgentProxyException: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.connector.PageantConnector$User32
        at com.jcraft.jsch.agentproxy.connector.PageantConnector.<init>(PageantConnector.java:68)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:110)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$7.execute(SSHTunnelConfiguratorUI.java:257)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:603)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2022-08-31 21:23:04.152 - SSH: Connected with ssh-agent
2022-08-31 21:23:04.152 - Creating new SecureRandom.
2022-08-31 21:23:04.153 - No such algorithm: IDEA/CBC/NoPadding
2022-08-31 21:23:04.154 - No such algorithm: IDEA/CTR/NoPadding
2022-08-31 21:23:04.156 - Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy
2022-08-31 21:23:04.242 - Client identity string: SSH-2.0-SSHJ_0.33.0
2022-08-31 21:23:04.293 - Server identity string: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
2022-08-31 21:23:04.569 - Exhausted available authentication methods
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
        at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:110)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:133)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$7.execute(SSHTunnelConfiguratorUI.java:257)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:603)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2022-08-31 21:25:04.331 - Dying because - Broken transport; encountered EOF
2022-08-31 21:25:04.331 - Disconnected - UNKNOWN
```

**Comment by mayerro** [comment] 2022-09-02 09:15
Possible workaround is decreasing ssh security on remote host:
add 2 lines to sshd config and restart it
```
PubkeyAuthentication yes
PubkeyAcceptedKeyTypes=+ssh-rsa
```

**Comment by n5a5** [comment] 2022-09-02 10:44
Can't reproduce it on Pop!_OS 22.04

**Comment by flambchap** [comment] 2022-09-02 11:02
I have a gut feeling that this is a duplicate of https://github.com/dbeaver/dbeaver/issues/14749.

**Comment by flambchap** [comment] 2022-09-02 11:03
https://github.com/dbeaver/dbeaver/issues/17312

**Comment by flambchap** [comment] 2022-09-02 11:04
https://github.com/dbeaver/dbeaver/issues/16247

**Comment by yapsr** [comment] 2022-09-05 10:26
Another workaround could be to not use the agent, but select "Public Key" as authentication method.

**Comment by throttlehead-dev** [comment] 2022-09-10 23:07
> Possible workaround is decreasing ssh security on remote host: add 2 lines to sshd config and restart it
> 
> ```
> PubkeyAuthentication yes
> PubkeyAcceptedKeyTypes=+ssh-rsa
> ```

I had this same problem on 22.04. I only needed to add `PubkeyAcceptedKeyTypes=+ssh-rsa` to `/etc/ssh/sshd_config` and restart `sudo systemctl restart ssh`

**Comment by ged-yuko** [comment] 2022-10-03 05:30
Seems it has nothing to do with DBeaver itself but with ssh configuration. Though ssh-related libraries may require upgrade, as i remember issues about missing support of the recent key types walkarounded by switching the ssh-related library explicitly.

See [OpenSSH 8.2 release notes](https://www.openssh.com/txt/release-8.2):
><pre>
> <i>Security</i>
> ========
> <b> * ssh(1), sshd(8), ssh-keygen(1): this release removes the "ssh-rsa"
>    (RSA/SHA1) algorithm from those accepted for certificate signatures
>    (i.e. the client and server CASignatureAlgorithms option) and will
>    use the rsa-sha2-512 signature algorithm by default when the
>    ssh-keygen(1) CA signs new certificates.</b>
>
>...
><i>Potentially-incompatible changes</i>
>================================
><b>This release includes a number of changes that may affect existing configurations:
>   * ssh(1), sshd(8): the above removal of "ssh-rsa" from the accepted CASignatureAlgorithms list.
></b>...</pre>

One doesn't even always need to change keys of the affected authorities, just upgrade client and server software for both sides to use another signing alorithm. See also [OpenSSH 8.7 release notes](https://www.openssh.com/txt/release-8.7):

><pre>...
>
> Imminent deprecation notice
> ===========================
> 
> OpenSSH will disable the ssh-rsa signature scheme by default in the
> next release.
> 
> In the SSH protocol, the "ssh-rsa" signature scheme uses the SHA-1
> hash algorithm in conjunction with the RSA public key algorithm.
> It is now possible[1] to perform chosen-prefix attacks against the
> SHA-1 algorithm for less than USD$50K.
> 
> <b>Note that the deactivation of "ssh-rsa" signatures does not necessarily
> require cessation of use for RSA keys. In the SSH protocol, keys may be
> capable of signing using multiple algorithms. In particular, "ssh-rsa"
> keys are capable of signing using "rsa-sha2-256" (RSA/SHA256),
> "rsa-sha2-512" (RSA/SHA512) and "ssh-rsa" (RSA/SHA1). Only the last of
> these is being turned off by default.</b>
> 
> This algorithm is unfortunately still used widely despite the
> existence of better alternatives, being the only remaining public key
> signature algorithm specified by the original SSH RFCs that is still
> enabled by default.
> 
> The better alternatives include:
> 
> <b> * The RFC8332 RSA SHA-2 signature algorithms rsa-sha2-256/512. These
>    algorithms have the advantage of using the same key type as
>    "ssh-rsa" but use the safe SHA-2 hash algorithms. These have been
>    supported since OpenSSH 7.2 and are already used by default if the
>    client and server support them.</b>
> ...
> </pre>

**Comment by Destrolaric** [comment] 2022-11-24 16:39
It looks like it is related to using JSCH for our interactions with ssh agents. This library can't work correctly with the new RSA keys. Because it recognizes them as old `ssh-rsa` and not as `rsa-sha2-512` or `rsa-sha2-256` keys and leads to server blocking usage of them.

**Comment by IreneKnapp** [comment] 2023-03-09 22:13
I just wanted to mention that I am reading through this issue as part of evaluating DBeaver for my needs, and this issue is a blocker for us. So please take that as a vote to move to a modern, maintained ssh library which supports secure ciphers. Weakening our security posture by allowing the old cipher would not be a suitable workaround, though I understand why others might choose to do it.

I see from a close read of #14749 that DBeaver has been dealing with the fact that its ssh libraries have stalled on cipher support (and one of them is totally unmaintained) for two years now. I'm not here to find fault or get into an argument; I offer this in a spirit of constructive criticism because I want your product to be better.

It is normal for old ciphers to be discontinued, and you can expect this to continue happening on a regular basis - it is the nature of cryptography to be subject to attacks which force continued improvement. In an ideal world, new ciphers would be supported as soon as they are standardized, without waiting for discontinued ciphers to force the issue.

I know that you can't afford to prioritize your product development solely on the say-so of one user, who may or may not ever become a paying customer, so please just take this for what it's worth. Good luck with everything!

**Closed as completed** 2023-03-22 05:33 UTC
Labels: xp:major, xo:linux, xo:macos, sp:5
