### ISSUE TITLE
DBeaver Office integration is removed after each DBeaver update installation

### ISSUE THREAD

**Issue by ftonioli** [dbeaver/dbeaver#36203] opened 2024-11-08 11:26 UTC
### Description

Hello,

After each Dbeaver update installation, is necessarie reinstall DBeaver Office integration.

Is it correct?

### DBeaver Version

Community Edition 24.2.4.202411031831

### Operating System

Windows 10

### Steps to reproduce

Install any DBeaver update

**Comment by ask9** [comment] 2024-11-08 11:46
Yes, this is well-known limitation.
Keep an eye on this issue #5317 and thumbs up emoji there to vote for faster resolving.

**Comment by ShadelessFox** [comment] 2024-11-08 23:45
Closing as a duplicate of the referenced ticket.

**Closed as not planned by ShadelessFox** 2024-11-08 23:45 UTC
Labels: duplicate
