### ISSUE TITLE
Allow saving the view settings for a table

### ISSUE THREAD

**Issue by GITMichaelK** [dbeaver/dbeaver#22452] opened 2024-01-13 13:41 UTC
Looking at a table (F4), dBeaver allows to customize the view, f.e. column widths or ordering by ... ASC / DESC. As it simplifies my work, I'm using these options quite often for several tables. 
 
Unfortunately all my effort is gone, as soon as I close and re-open that table.
Therefore I'd appreciate an option to store those settings, similar as for filters ([described here](https://github.com/dbeaver/dbeaver/issues/20225#issuecomment-1580428995)).

Thanks a lot for dBeaver and your work!

**Comment by arhayka** [comment] 2024-01-25 13:59
Duplicate of https://github.com/dbeaver/dbeaver/issues/21948

**Closed as not planned by arhayka** 2024-01-25 13:59 UTC
