### ISSUE TITLE
Problem with Dbeaver Git 

### ISSUE THREAD

**Issue by joshepp** [dbeaver/dbeaver#12764] opened 2021-06-07 17:55 UTC
Since de upper Version of Dbeaver 21.0.4 I can't use DBEAVER it always restart I had to downgrade to 21.0.4 this always happen with older versions when de plugin ask to restart but now even if you don't restart it , DBEAVER doesn't start . Please help Thanks.

**Comment by uslss** [comment] 2021-06-08 08:17
seems to be duplicate of #12172 .
please try to delete the `plugin `folder under `%USERPROFILE%\.eclipse\org.jkiss.product*`
thanks for the report

**Closed as completed by uslss** 2021-06-08 08:17 UTC
Labels: duplicate
