### ISSUE TITLE
PostgreSQL: Create Role Wizard

### ISSUE THREAD

**Issue by MahatmaFatalError** [dbeaver/dbeaver#2052] opened 2017-08-22 14:29 UTC
In the Roles context menu it should be possible to open a wizard to create a  new role. The wizard should consist of pages which contain the following configuration items:
- name
- password (password repetition)
- privileges (like superuser, can create database, roles etc.)
and optionally
- connection limit and expiration date for that user

**Comment by clounie** [comment] 2017-12-07 18:02
Agreed..seems like a pretty foundational feature.

**Comment by Wirone** [comment] 2017-12-29 15:39
Wizard should allow also viewing/setting attributes like `search_path`.

Today for testing some libraries I used MySQL instead of Postgresql because of lack of this functionality (there is wizard for MySQL) :smiley:

**Comment by serge-rider** [comment] 2018-01-04 14:02
This is actually duplicate of #1712

**Closed by serge-rider** 2018-01-04 14:02 UTC
Labels: duplicate, feature request, x:postgresql
