### ISSUE TITLE
LOG ERROR:Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

### ISSUE THREAD

**Issue by emanueol** [dbeaver/dbeaver#21164] opened 2023-09-09 12:49 UTC
### Description

I delete log and restarting DBeaver I see 2 errors in the Log window:

1. message: Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
![image](https://github.com/dbeaver/dbeaver/assets/8422412/643751be-7132-4d10-9cd2-80ea4e5aa85d)

2. message: /css/gef_dark.css
![image](https://github.com/dbeaver/dbeaver/assets/8422412/697e0c94-cc8f-453d-ab37-fe90f20939f2)

Any suggestions ?
I was having problems with DBeaver not remembering my font settings, till I reseted values, set my preferred font again, and now seems working again - that is - exiting DBeaver and launching DBeaver again I see now font setting getting properly remembered and set.

So.. I wonder if above 2 errors are related and how can I stop DBeaver getting LOG ERRORS ?

Thanks ~

### DBeaver Version

Community Version 23.2.0.202309041200

### Operating System

windows 10 

### Database and driver

n.a.

### Steps to reproduce

simply starting DBeaver I see these 2 errors.

**Comment by E1izabeth** [comment] 2023-09-10 21:46
It has nothing to do with the messages you see in logs.

Your issue is a duplicate of #19982, so I'm closing it. You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2023-09-10 21:46 UTC
Labels: duplicate, xf:ui

**Comment by emanueol** [comment] 2023-09-10 22:10
ok thanks
