### ISSUE TITLE
[MariaDB] Error while trying to sort a table with filter

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#4330] opened 2018-10-04 08:31 UTC
version: 5.5.61-MariaDB-1~wheezy

When I just open the table and sort by some column, everything is ok.
But after I apply filter I receive the error:
```
Query execution failed

Причина:
 SQL Error [1054] [42S22]: (conn:10505417) Unknown column 'x.9' in 'order clause'
Query is : SELECT x.* FROM smsapi.sms x
WHERE provider_code ='somevalue'
ORDER BY x.9 DESC
```

**Comment by serge-rider** [comment] 2018-10-04 09:29
Duplicate of #4284

**Closed by serge-rider** 2018-10-04 09:29 UTC
Labels: bug, duplicate
