### ISSUE TITLE
Find by column name in Data viewer

### ISSUE THREAD

**Issue by LendLord** [dbeaver/dbeaver#8901] opened 2020-06-05 13:58 UTC
**Is your feature request related to a problem? Please describe.**
Very hard to find column on big tables(many columns), so I need to scroll through columns until find needed. 

**Describe the solution you'd like**
Find/Replace also work for columns in table view mode like with text view mode and row view mode.

**Comment by uslss** [comment] 2020-06-08 10:25
thanks for suggestion

**Comment by LonwoLonwo** [comment] 2021-07-27 10:14
Hey @LendLord 
You can try to use the "Search item(s)" field or Ctrl+F.

![2021-07-27 13_10_36-DBeaver Enterprise 21 1 4 - Track](https://user-images.githubusercontent.com/45152336/127137402-2dcac47e-1c9f-45ad-8a88-82c2349295b7.png)

**Comment by LendLord** [comment] 2021-07-27 10:18
@LonwoLonwo I need such feature when viewing table data, not table columns.

**Comment by E1izabeth** [comment] 2023-01-16 11:15
Duplicate of #3052

**Closed by E1izabeth** 2023-01-16 11:15 UTC
Labels: feature request, xf:search
