### ISSUE TITLE
show /* JDBC:DatabaseMetaData.getColumns() */ columns in database "*"

### ISSUE THREAD

**Issue by guoming-xu** [dbeaver/dbeaver#5536] opened 2019-03-20 00:50 UTC
#### System information: 
- Operating system: Windows 10 Pro 
- DBeaver version: 5.1.6.201808262133 
- Java version: 1.8.0_151

#### Connection specification:
- Database name and version: Snowflake (Cloud based database) 
- Driver name - Snowflake JDBC Driver 
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No. 

#### Describe the problem you're observing:
Every time when I query a table for the first time after a connection is established, dbeaver will fire a sql query to fetch the whole database's metadata and this could take quite a long while. 

**show /* JDBC:DatabaseMetaData.getColumns() */ columns in database "*"**

#### Steps to reproduce, if exist:
1. Open a new connection 
2. Query a table with any simple query. 
3. Observe query history from snowflake history, you'll see the mentioned sql statement and if you database has a lot database objects, this query would take quite a while.

**Comment by onevedrov** [comment] 2019-12-12 19:37
Are there any update regarding this issue?

**Comment by kkusgeek** [comment] 2020-08-11 15:11
Are there any latest update towards the fix?

**Comment by uslss** [comment] 2021-03-04 15:55
is it still actual?

**Comment by onevedrov** [comment] 2021-03-04 16:23
Yes. It's quite annoying especially with database with large amount of tables.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sudeepm** [comment] 2021-05-20 13:11
if you are using a schema / table with _ or something like that in it, escape it with a \   and then send it. It should work. I faced this with a generic JDBC client and snowflake JDBC driver (even latest) and escaping with \ worked there.  I am not sure if dbeaver is handling \ differently , if so then probably you need to do a double escape (like \\ ) to make it work.

**Comment by LiBerti13** [comment] 2022-01-14 08:39
This issue is still present. This is clearly a bug. I see no reason why all the columns _in the entire database_ should be retrieved before a single table is queried.

**Comment by DmitryMaletin** [comment] 2022-03-21 11:45
I have the same issue with latest DBeaver & latest driver for snowflake.

**Comment by tpiotrowicz** [comment] 2022-04-18 13:51
Yes still an issue, would like it configurable to schema level

**Comment by LonwoLonwo** [comment] 2022-10-17 11:05
Can't reproduce against in DBeaver 22.2.2
Probably fixed in https://github.com/dbeaver/dbeaver/issues/9875

Did someone expect this issue in the latest DBeaver version?

**Comment by uslss** [comment] 2022-11-30 10:23
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.

**Closed by uslss** 2022-11-30 10:23 UTC
Labels: enhancement, x:snowflake, wait for response, xf:metadata
