### ISSUE TITLE
In  spatial view instead of a picture with a map with all objects, just a black picture is copied

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#19419] opened 2023-03-18 12:31 UTC
### Description

https://user-images.githubusercontent.com/84867187/226105563-cd121664-c5df-4ca8-aa12-9e61b4a455df.mp4

### DBeaver Version

23.0.0

### Operating System

windows 10

### Database and driver

PostgreSQL 11.6 (GIS)

### Steps to reproduce

1. Open a table with geometry data
2. Open spatial view
3. Click Copy as picture button
4. Open an image editor (e.g. Paint) and press Ctrl + V

**Expected Result - The map with all objects is copied into file
Actual Result -** just a black picture is coped

**Comment by arhayka** [comment] 2023-03-28 16:55
Duplicate of https://github.com/dbeaver/pro/issues/1151

**Closed as not planned by arhayka** 2023-03-28 16:55 UTC
Labels: xf:ui, xp:normal
