### ISSUE TITLE
Oracle 11g date/time stamps return NULL on 5.2.1+ 

### ISSUE THREAD

**Issue by Efus10n** [dbeaver/dbeaver#4409] opened 2018-10-16 14:51 UTC
I connect to several Oracle databases which are on 11g (11.2.0.4). Currently, on any version of DBeaver 5.2.1 and above (including EA) all date/time stamps return as NULL. This seems to match up with issue #4270 except for that was using ojdbc7.jar driver for 12c vs ojdbc6.jar for 11g. That and the fix applied still isn't working for me. I can convert the date/times to strings and it works, but that is cumbersome to do in some of my scripts.

Anyone know of a fix for 11g? Timestamps are working still in DBeaver 5.2.0, but I'm looking to be able to upgrade to new versions.

Thanks!

**Comment by serge-rider** [comment] 2018-10-16 15:29
Duplicate of #4348

**Closed by serge-rider** 2018-10-16 15:29 UTC
Labels: bug, duplicate
