### ISSUE TITLE
Binding of HOME and END keys to do different actions on macOS is unreliable

### ISSUE THREAD

**Issue by hungariandude** [dbeaver/dbeaver#35033] opened 2024-07-31 11:52 UTC
### Description

Configuring HOME key to do "Line Start" and END key to do "Line End" does not work properly on macOS. The binding works only if the application is restarted but after some time, the binding is forgotten and HOME key starts doing "Text Start" and END key starts doing "Text End", which are the macOS default behavior, however I want to use these keys in "Windows-way". I did not check other keys so I don't know if the complete key binding configuration is lost after some application run time or only these two keyboard buttons are affected.

### DBeaver Version

Community Edition 24.1.3.202407211303

### Operating System

macOS 14.5

### Database and driver

Affects SQL Editor globally.

### Steps to reproduce

1. Have this key binding configured: [dbeaver_key_binding.csv](https://github.com/user-attachments/files/16440808/dbeaver_key_binding.csv)
2. Open an SQL editor and write some text lines
3. Try out HOME and END keys --> they should work as expected
4. Leave the application running for several hours in the background
5. Go back to the editor and try out the HOME and END keys --> they should jump to text start and text end instead of line start and line end

**Comment by MashaKorax** [comment] 2024-08-29 09:27
Duplicate of https://github.com/dbeaver/dbeaver/issues/9414.

**Closed as completed by MashaKorax** 2024-08-29 09:27 UTC
