### ISSUE TITLE
Snap fails on Manjaro

### ISSUE THREAD

**Issue by ChacheGS** [dbeaver/dbeaver#9679] opened 2020-09-01 19:24 UTC
#### System information: 
- Operating system (distribution) and version
```terminal
$ lsb_release -a && uname -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.1
Codename:       Mikah
Linux ryzen 5.4.52-1-MANJARO #1 SMP PREEMPT Thu Jul 16 16:07:11 UTC 2020 x86_64 GNU/Linux
```

- DBeaver version
```terminal
$ snap --version
snap     2.45.2-1
snapd    2.45.2-1
series   16
manjaro  -
kernel   5.4.52-1-MANJARO
$ snap info dbeaver-ce
name:      dbeaver-ce
summary:   Universal Database Tool
publisher: DBeaver (dbeaver-corp)
store-url: https://snapcraft.io/dbeaver-ce
contact:   dbeaver@jkiss.org
license:   unset
description: |
  Free multi-platform database tool for developers, SQL programmers,
  database administrators and analysts. Supports all popular databases
  MySQL, PostgreSQL, MariaDB, SQLite, Oracle, DB2, SQL Server, Sybase,
  MS Access, Teradata, Firebird, Derby, etc.
commands:
  - dbeaver-ce
snap-id:      3faKn1hkBHHE6SCJ1W3QDTPWRlumswc4
tracking:     latest/stable
refresh-date: 11 days ago, at 20:38 CEST
channels:
  latest/stable:    7.1.5.202008180601 2020-08-21 (78) 201MB -
  latest/candidate: ↑
  latest/beta:      ↑
  latest/edge:      7.0.0.202003021717 2020-03-16 (49) 135MB -
installed:          7.1.5.202008180601            (78) 201MB -
```

#### Connection specification:
- Database name and version
   None.

#### Describe your question:
DBeaver crashes on launch.
```terminal
$ dbeaver-ce
Picked up _JAVA_OPTIONS: -Duser.home=/home/carlos/snap/dbeaver-ce/78
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.1.5.202008180601]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.200.v20200205-1503]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.700.v20200106-1020]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.17.0.v20200217-1511]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.1.5.202008180601]
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Core Resource Management [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-09-01 21:08:09.801 - Initializing DBeaver 7.1.5
2020-09-01 21:08:09.801 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.1.5.202008180601
2020-09-01 21:08:09.801 - Initialize Core...
2020-09-01 21:08:09.802 - Can't find BC security provider. Use default JCE.
2020-09-01 21:08:09.802 - BouncyCastle not registered, using the default JCE provider
2020-09-01 21:08:09.847 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.39.202008180601]
2020-09-01 21:08:09.892 - Core initialized (91ms)
2020-09-01 21:08:09.898 - Create display
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.600.v20200116-2127]
2020-09-01 21:08:09.995 - DBeaver 7.1.5.202008180601 is starting
2020-09-01 21:08:09.995 - OS: Linux 5.4.52-1-MANJARO (amd64)
2020-09-01 21:08:09.996 - Java version: 1.8.0_265 by Private Build (64bit)
2020-09-01 21:08:09.996 - Install path: '/snap/dbeaver-ce/78/usr/share/dbeaver'
2020-09-01 21:08:09.996 - Instance path: 'file:/home/carlos/snap/dbeaver-ce/78/.local/share/DBeaverData/workspace6/'
2020-09-01 21:08:09.996 - Memory available 112Mb/910Mb
2020-09-01 21:08:10.000 - Starting RMI server at 22376
2020-09-01 21:08:10.012 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.900.v20200213-1442]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.200.v20200127-0814]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start EMF Common [org.eclipse.emf.common 2.18.0.v20191225-1014]
> Start EMF Ecore [org.eclipse.emf.ecore 2.21.0.v20200127-1342]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.800.v20191212-1231]
> Start Expression Language [org.eclipse.core.expressions 3.6.700.v20200212-1751]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1100.v20200217-1217]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.800.v20191216-0805]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.15.500.v20200106-1259]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.900.v20200203-0840]
2020-09-01 21:08:10.634 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
        at org.eclipse.swt.SWT.error(SWT.java:4723)
        at org.eclipse.swt.SWT.error(SWT.java:4638)
        at org.eclipse.swt.SWT.error(SWT.java:4609)
        at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
        at org.eclipse.swt.graphics.Device.getFontList(Device.java:454)
        at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
        at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
        at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
        at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
        at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
        at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:123)
        at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:68)
        at org.eclipse.ui.internal.Workbench$23.runWithException(Workbench.java:1793)
        at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
        at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
        at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
        at org.eclipse.swt.widgets.Display.syncExec(Display.java:5797)
        at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
        at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1787)
        at org.eclipse.ui.internal.Workbench.init(Workbench.java:1641)
        at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2811)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:646)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-09-01 21:08:10.642 - DBeaver is stopping
2020-09-01 21:08:10.644 - Stop RMI server
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.54.202008180601]
2020-09-01 21:08:10.652 - DBeaver shutdown completed
2020-09-01 21:08:10.668 - Shutdown Core...
2020-09-01 21:08:10.780 - Loading user drivers configuration from '/home/carlos/snap/dbeaver-ce/78/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml'
2020-09-01 21:08:10.785 - Total database drivers: 84 (84)
2020-09-01 21:08:10.876 - Shutdown completed in 208ms
```

**Comment by uslss** [comment] 2020-09-03 16:40
thanks for the bug report

**Comment by uslss** [comment] 2020-09-03 16:41
closed as duplicate of #9307

**Closed by uslss** 2020-09-03 16:41 UTC
Labels: bug, environment, xf:snap, xo:linux

**Comment by meddario** [comment] 2020-10-01 22:18
@ChacheGS Hi, can you try the workaround described here? https://github.com/snapcrafters/gimp/issues/122
It fixed the problem for me. Cheers!

**Comment by saitodisse** [comment] 2021-01-21 16:09
> @ChacheGS Hi, can you try the workaround described here? [#9307 (comment)](https://github.com/dbeaver/dbeaver/issues/9307#issuecomment-702426109)
> It fixed the problem for me. Cheers!

On Manjaro here:
I tried removing font cache but still get same error: `Graphic is disposed`

dbeaver is not working on AUR instalation or SNAP to me on arch linux

**update:** 
this version works for me: https://aur.archlinux.org/packages/dbeaver-ce-latest-deb/
