### ISSUE TITLE
Very tiny icons on HIDPI Screens (Ubuntu 18.04)

### ISSUE THREAD

**Issue by rmetcalf9** [dbeaver/dbeaver#8514] opened 2020-04-22 08:29 UTC
I have checked https://github.com/dbeaver/dbeaver/wiki and no search results for hidpi.
I have searched github for HIDPI issues and I can't find any. There are some in "old forum" but these are locked.

OS: Ubuntu 18.04

The icons take up about 1mm on my screen. It's unusable and I can't find any options to change this.
![image](https://user-images.githubusercontent.com/14248366/79958703-297b1f00-847b-11ea-835f-6446fd06bf1d.png)

**Comment by uslss** [comment] 2020-04-22 12:54
seems to be duplicate of  #6581 
anyway, thanks for the bug report

**Closed by uslss** 2020-04-22 12:54 UTC
Labels: bug, duplicate

**Comment by rmetcalf9** [comment] 2020-04-22 14:07
I saw this but I didn't think it was a duplicate. #6581 talks about multiple monitors which is not the case for me.
