### ISSUE TITLE
Bookmarks in SQL Editor

### ISSUE THREAD

**Issue by PesterevViacheslav** [dbeaver/dbeaver#7877] opened 2020-02-10 09:12 UTC
When working with long list of code (two screens or more) in SQL there is no posibillity to set a bookmark near the row number. Navigation between bookmarks is very convenient, no need to scroll and scroll and scroll... code.

**Comment by podoni** [comment] 2020-02-11 11:39
![image](https://user-images.githubusercontent.com/59002295/74233662-740b4d00-4d0e-11ea-9a54-8f1a808c62e3.png)

![image](https://user-images.githubusercontent.com/59002295/74233593-55a55180-4d0e-11ea-916e-590abee833f5.png)

![image](https://user-images.githubusercontent.com/59002295/74233718-8d13fe00-4d0e-11ea-9a41-35c3979b8e16.png)

**Comment by PesterevViacheslav** [comment] 2020-02-11 12:34
This bookmarks for database navigation, not for sql editor navigation.
![pl_sql_dev_04](https://user-images.githubusercontent.com/36879076/74237026-a94e7580-4ce3-11ea-9805-153f3c5d95f9.png)
Example from plsql developer.
I need to navigate from one code row to another.

**Comment by podoni** [comment] 2020-02-11 22:10
You can also use it in the sql editor.
But there seems to be no pop-up menus or buttons.
At first, hot keys are set so that you can use them.

![image](https://user-images.githubusercontent.com/59002295/74284192-94ff8c80-4d66-11ea-914e-56ffa6438fc0.png)

![image](https://user-images.githubusercontent.com/59002295/74284105-6ed9ec80-4d66-11ea-90be-4ca1669416d7.png)

**Comment by podoni** [comment] 2020-02-12 00:18
I recommend installing the plugin.

This plugin is an eclipse plugin but works fine in dbeaver.

https://marketplace.eclipse.org/content/quick-bookmarks-plugin#.U9p6nEThGlM

**Comment by uslss** [comment] 2021-08-04 08:41
duplicate of #3416

**Closed by uslss** 2021-08-04 08:41 UTC
Labels: duplicate, feature request
