### ISSUE TITLE
Improve switching of active Postgre databases

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#5027] opened 2019-01-17 14:33 UTC
Switching between active databases in Postgre is not obvious (https://github.com/dbeaver/dbeaver/issues/2892). We can add a special icon/button near each database name. The database will become active after a click on this icon.

**Comment by jyinpci** [comment] 2019-01-17 15:50
Thanks for opening this discussion again!  The problem is not that activating a database is hard.  Pressing ctrl-shift-a is not hard at all.  The problem is that users forget to do it - it is less intuitive.  Now for postgresql, double-click is like a partial switch between databases.  That is why it is dangerous.  I suspect that adding an icon will not help in this aspect.  If we can get it back to 5.1.x where this was configurable, it will give the users the option to choose how they want double-click to behave.  Thanks again.

**Comment by serge-rider** [comment] 2019-01-17 21:34
In fact double-clicking never acted as default database switching.
In 5.1 and earlier DBeaver didn't support multiple PG databases. Only one database could be activated and it was not possible to even view table data from another database.
"Smart" switch actually deactivated current database (so you'd loose all you changes in table editors, all active transactions, etc).

Now we support multiple PG databases. We open separate connection to every database (on first access).
The problem is that SQL editor must be associated with some particular database (as cross-databases queries are not supported by PG).
And sometimes users forgot with which database it is associated (although we write this in the main toolbar and mark this database with bold in navigator).

So, the question is - how to make this more obvious.

Note: for safer work you can create separate connection for each PG database (and disable "Show non-default databases" option).

**Comment by jyinpci** [comment] 2019-01-17 22:03
Serge,

Thank you very much for your insight.   Now I appreciate much more why it had been changed to this way.  

What if we do the following:  when a user double-clicks a database, if the database is PG, then a window pops up with a question like: "Do you want to switch your active database connection?  (Warning: any changes not yet committed in your current editor will be lost!)", and two buttons "Yes" and "No".   If Yes button is pressed, everything will be switched to the new database.  If No button is pressed, everything will work as today.  Also add a configuration option for applying the same answer in the future so that the popup can be suppressed.

Thanks again!

**Comment by uslss** [comment] 2021-09-09 12:37
already implemented

**Closed by uslss** 2021-09-09 12:37 UTC
Labels: enhancement, x:postgresql, help wanted
