### ISSUE TITLE
java.lang.NullPointerException for Date type in ClickHouse

### ISSUE THREAD

**Issue by kalyagin-private** [dbeaver/dbeaver#17287] opened 2022-08-08 08:13 UTC
### Description

When you select data from Clickhouse table with  "Date" type, you see "java.lang.NullPointerException" instead of NULL

![image](https://user-images.githubusercontent.com/3599574/183371460-94b31922-da50-41bc-a9a8-5b9bf60d0244.png)

### DBeaver Version

CE 22.1.3

### Operating System

Ubuntu 20.04

### Database and driver

Database name: ClickHouse 22.2.2.1
Driver: clickhouse-jdbc-0.3.2

### Steps to reproduce

1. Connect to Clickhouse
2. Write SQL: 
`create table t1 (
 id Int32,
 ts Nullable(Date)
)
engine = MergeTree
order by id;

insert into t1 values (1, '2020-12-12');
insert into t1 values (2, null);

select * from t1;`

**Comment by E1izabeth** [comment] 2022-08-08 10:30
@kalyagin-private, we are unable to reproduce your issue. Please, send us the log files: https://dbeaver.com/docs/wiki/Log-files/

**Comment by kalyagin-private** [comment] 2022-08-08 10:46
> @kalyagin-private, we are unable to reproduce your issue. Please, send us the log files: https://dbeaver.com/docs/wiki/Log-files/
@E1izabeth ,
I selected same table as in general messasage and got the same error

![image](https://user-images.githubusercontent.com/3599574/183400981-2b516321-6ef4-4086-944d-3567f2f5a23a.png)

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=ru_RU
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Предупреждение
Mon Aug 08 14:28:26 SAMT 2022
NullPointerException

java.lang.NullPointerException
    at com.clickhouse.jdbc.ClickHouseResultSet.getDate(ClickHouseResultSet.java:358)
    at com.clickhouse.jdbc.ClickHouseResultSet.getDate(ClickHouseResultSet.java:340)
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getDate(JDBCResultSetImpl.java:419)
    at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:97)
    at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
    at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:798)
    at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:609)
    at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
    at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
    at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
    at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
    at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3642)
    at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
    at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
    at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
    at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4891)
    at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by E1izabeth** [comment] 2022-08-08 10:50
Thank you for quick answer.

**Comment by E1izabeth** [comment] 2022-09-03 14:32
It's a clickhouse issue https://github.com/ClickHouse/clickhouse-jdbc/issues/915.
Should be fixed with the driver update.

**Comment by kseniaguzeeva** [comment] 2022-10-28 14:58
The new driver works properly in CloudBeaver (Backend version 22.2.3.202210281332, Frontend version 22.2.3.202210281340)

**Comment by uslss** [comment] 2022-10-31 11:42
fixed in the scope of #17879

**Closed as completed by uslss** 2022-10-31 11:42 UTC
Labels: xf:data, x:clickhouse, third party issue, sp:1
