### ISSUE TITLE
Editor not respecting multi-line comment

### ISSUE THREAD

**Issue by coatsden** [dbeaver/dbeaver#11558] opened 2021-03-01 17:01 UTC
![DBeaver_EditorCommentIssue](https://user-images.githubusercontent.com/51123206/109530762-fc41c900-7aae-11eb-91b3-b9d7ecd2e08a.gif)

#### System information: 
- Operating system (distribution) and version - Windows 10 (2004)
- DBeaver version - 21.0.0.
- Additional extensions - None

#### Connection specification:
- Database name and version - Postgresql
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - No

#### Describe the problem you're observing:
Editor not respecting multi-line comment

#### Steps to reproduce, if exist:
1. Enclose any sql statement using multi-line or block comment
2. Edit the sql statement and add or remove more than 1 character.

**Comment by uslss** [comment] 2021-03-01 19:02
thanks for the report.
Closed as duplicate of #11364

**Closed as completed by uslss** 2021-03-01 19:02 UTC
Labels: duplicate
