### ISSUE TITLE
Postgresql text between $$ looks like comment

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#7183] opened 2019-11-07 06:07 UTC
#### System information: 
- Windows 7 x64 Professional
- DBeaver 6.2.4.2019110311605
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5.13
- Driver org.postgresql:postgresql:RELEASE[9.4.1212.jre7]
- No tunnels or proxies

#### Describe the problem you're observing:
In DBeaver 6.2.3 was problem with executing anonymous code block ($$). When trying to execute the request, an error occurred and the code looked commented out. In dbeaver 6.2.4 there is no problem with execution, but the code is periodically highlighted as commented.

#### Steps to reproduce, if exist:
Copy query below (ctrl+v) into query editor - part of query highlighted as commented.
Type query below and move it in query editor down by pressing Enter before "DO"

```
DO $$
BEGIN
	RAISE NOTICE '%', 'Test';
END $$;
```

**Comment by serge-rider** [comment] 2019-11-07 15:36
Duplicate of #7124

There was a proposal to use AS as prefix for code block. But it won't work in your case.
Do you have any better idea?

**Comment by ems2811** [comment] 2019-11-07 18:04
I apologize. I read the issue #7157 incorrectly. Now i will use named tag like $proc$

**Comment by pyrocks** [comment] 2019-11-08 06:18
@serge-rider perhaps "AS" and "DO" as prefixes will work?
I am using flyway to upgrade. All my functions use $$. If I change all the functions - it will have to re-run everything, which I want to avoid (although I admit won't cause too much harm).
I just don't like the fact that the tool I'm using forces me to change my code to be "compatible". This needs to be solved to work as it did pre 6.2.3... pretty please? :)

**Comment by morl-la** [comment] 2019-12-02 09:24
@serge-rider this was not yet resolved in 6.3.0 ?

**Comment by pyrocks** [comment] 2019-12-02 09:24
@serge-rider this was not yet resolved in 6.3.0 ?

**Comment by serge-rider** [comment] 2019-12-02 09:39
No. It is not that easy. 
It is not always prefixed with AS or DO so we need to make some strict general rule.

**Comment by pyrocks** [comment] 2019-12-02 09:53
@serge-rider yes I assumed so - due to `language` specifications and other clauses.
Seeing it was an unexpected change for many people (not only me) I would have suggest to revert the behavior back to 6.2.2 until it is resolved as this prevents me from upgrading, but perhaps I'm the only stubborn one who wouldn't replace $$ with $func$. If it can't be reverted - I'll wait until it is addressed. Thanks.

**Comment by serge-rider** [comment] 2019-12-10 13:52
There is still no good solution for this problem.

Different prefixes (like do/as/etc) recognition doesn't solve problem in general (but makes syntax highlight behavior much less obvious).
Analyzing contents inside $$ $$ blocks (e.g. we can assume that it is a PgSQL code  if it contains BEGIN/END keywords)  also isn't a good solution. After all PgSQL is just one of possible languages for PG functions.

Possible workaround: add preference option which will enable/disable $$ treating as string.
As half of people use them for strings and other half use them as code block markers.

Any new ideas would be very appreciated.

**Comment by morl-la** [comment] 2019-12-10 14:26
@serge-rider Totally fine with a configuration parameter and OK with it being disabled by default and having to enable it manually, even though I believe it should be enabled by default to be pre-6.2.3 compatible. will it affect only $$ or all $...$ ?

**Comment by pyrocks** [comment] 2019-12-10 14:27
@serge-rider Totally fine with a configuration parameter and OK with it being disabled by default and having to enable it manually, even though I believe it should be enabled by default to be pre-6.2.3 compatible. will it affect only $$ or all $...$ ?

**Comment by serge-rider** [comment] 2019-12-10 21:09
We may have two different options.
- [ ] Treat $$ as string quote (enabled by default)
- [ ] Treat $name$ as string quote (disabled by default)

**Comment by serge-rider** [comment] 2019-12-16 16:03
![image](https://user-images.githubusercontent.com/6398845/70922237-cdb90900-2036-11ea-8aa4-20ded1635b13.png)

**Comment by uslss** [comment] 2019-12-17 13:44
verified

**Closed by uslss** 2019-12-17 13:44 UTC
Labels: bug, x:postgresql

**Comment by jamessa** [comment] 2020-01-21 01:00
Verified. Thank you all.
