### ISSUE TITLE
When advanced copy to json, key is not the other name of the as in the sql statement, but the original field name

### ISSUE THREAD

**Issue by Saber-CC** [dbeaver/dbeaver#34050] opened 2024-05-23 08:38 UTC
### Description

On the query result page, select a result, right-click -> Advanced Copy -> Copy as json to the clipboard, key is not the other name of the as in the sql statement, but the original field name

### DBeaver Version

24.0.5.202405191503

### Operating System

13.6.6 (22G630)

### Database and driver

MySQL

### Steps to reproduce

right-click -> Advanced Copy -> Copy as json to the clipboard

**Comment by uslss** [comment] 2024-06-10 12:09
@Saber-CC unfortunately cannot reproduce the issue. Could you add some screenshots or video with the issue?

thanks. And sorry for the late response

**Comment by Saber-CC** [comment] 2024-06-11 06:29
> @Saber-CC unfortunately cannot reproduce the issue. Could you add some screenshots or video with the issue?不幸的是无法重现该问题。您能否添加一些有关该问题的屏幕截图或视频？
> 
> thanks. And sorry for the late response谢谢。抱歉回复晚了

I upgraded to 24.1.0 and still have this problem. More specifically, in a mysql query, the alias as of the sql statement does not correspond to the key output into json, which is still the name in the table.Here's the video.

https://github.com/dbeaver/dbeaver/assets/49194769/0917e9fa-8896-48f1-afe5-a1d3a7f29013

**Comment by uslss** [comment] 2024-07-08 12:22
Unfortunately, still cannot reproduce the issue.
Could you try if it is reproducible for you against the recent version?
![image](https://github.com/dbeaver/dbeaver/assets/31996417/c7b22714-db49-4e18-a2ca-58f639f2a17f)

**Comment by Saber-CC** [comment] 2024-07-10 03:20
> Unfortunately, still cannot reproduce the issue.不幸的是，仍然无法重现该问题。 Could you try if it is reproducible for you against the recent version? 您可以尝试一下它是否可以针对最新版本重现？ ![image](https://private-user-images.githubusercontent.com/31996417/346559748-c7b22714-db49-4e18-a2ca-58f639f2a17f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzcwNzQsIm5iZiI6MTcyMDU3Njc3NCwicGF0aCI6Ii8zMTk5NjQxNy8zNDY1NTk3NDgtYzdiMjI3MTQtZGI0OS00ZTE4LWEyY2EtNThmNjM5ZjJhMTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAxNTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMWRlZWI5ZDk1NDgyYjQ1MWYwMWNlNGI0ODYwOGY1MjRlN2NjNTM2YzIwN2U4ZGI3MDM0ZGM5ZmIxZDdiNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oQFwERH-_ACXEBX8eQ82ANYZZx9Yvj0C9yB4VmQsD4o)

The latest version still has this problem, perhaps I did not express my problem clearly. The problem is that at 14 seconds of the video above, the copied text, the key is not the sql as named a and b, but the original start_time and end_time

**Comment by dstivanov** [comment] 2024-07-30 21:49
@uslss I think that https://github.com/dbeaver/dbeaver/pull/35007 will solve this, isn't it ? 

cc @Saber-CC

**Comment by MashaKorax** [comment] 2024-08-06 17:56
It should be fixed by PR https://github.com/dbeaver/dbeaver/pull/35007

**Closed as completed by MashaKorax** 2024-08-06 17:56 UTC
Labels: xf:datatransfer
