### ISSUE TITLE
Before a Postgres table is created physically, allow columns drag&drop to change their order 

### ISSUE THREAD

**Issue by meglio** [dbeaver/dbeaver#16939] opened 2022-07-01 03:00 UTC
**Is your feature request related to a problem? Please describe.**

While designing a Postgres table in UI, and before it is created, I would like to be able to change columns order. It is safe to allow that because the table does not exist yet, so the user should be free to change the order of columns.

**Describe the solution you'd like**

I would like to be able to drag&drop columns in the UI before the table is created physically in database.

**Describe alternatives you've considered**

The are two alternatives, both tedious and time-wasting.
1. Once I finish designing the table in the UI, copy the CREATE SQL, reorder the columns manually in the query, and execute the query.
2. Re-create the table in the UI from scratch.

**Additional context**

Order of columns is important because it will make the table take more or less space depending on the **alignment padding**.

Every data type has specific alignment requirements:
https://www.postgresql.org/docs/current/catalog-pg-type.html

You can minimize space lost to padding between columns by ordering them favorably. The following (extreme) example would waste a lot of physical disk space:

```sql
CREATE TABLE t (
    e int2    -- 6 bytes of padding after int2
  , a int8
  , f int2    -- 6 bytes of padding after int2
  , b int8
  , g int2    -- 6 bytes of padding after int2
  , c int8
  , h int2    -- 6 bytes of padding after int2
  , d int8)
```

To save 24 bytes per row, use instead:

```
CREATE TABLE t (
    a int8
  , b int8
  , c int8
  , d int8
  , e int2
  , f int2
  , g int2
  , h int2)   -- 4 int2 occupy 8 byte (MAXALIGN), no padding at the end
```

This is elaborated in great detail in many articles. For more, see this article at StackOverflow: https://stackoverflow.com/a/7431468/335304

**Comment by flambchap** [comment] 2022-07-04 12:23
Thank you for your suggestion.

**Comment by LonwoLonwo** [comment] 2022-09-19 10:12
I'm closing this as duplicate of https://github.com/dbeaver/dbeaver/issues/16411

**Closed as not planned by LonwoLonwo** 2022-09-19 10:12 UTC
Labels: duplicate, xf:metadata
