### ISSUE TITLE
PostgreSQL empty statistic after 2 not "SELECT" query

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#5226] opened 2019-02-07 07:37 UTC
Hello.
Windows 7 x64
DBeaver 5.3.4
Java 1.8.0_201
PostgreSQL 9.5.3
PostgreSQL driver 9.4.1212

Query (need to execute step by step):
--1
CREATE TEMP TABLE tt AS
SELECT unnest('{1,2,3,4,5,6,7}'::int[]) as id, ''::text as commentary;

--2
UPDATE tt
SET commentary=id;

--3
UPDATE tt
SET commentary=id;

At query 3 statistic of execution is empty. If between 2 and 3 query execute "SELECT * FROM tt" - 3 query returns statistic correctly (2 not "SELECT" requests in succession create a similar problem)

**Comment by serge-rider** [comment] 2019-02-07 19:55
Duplicate of #5192

**Closed by serge-rider** 2019-02-07 19:55 UTC
Labels: bug, duplicate
