### ISSUE TITLE
Help: can't export MS Access tables...

### ISSUE THREAD

**Issue by dbeaveroo** [dbeaver/dbeaver#4770] opened 2018-12-10 16:24 UTC
Hello,

I am using Windows 10 and DBeaver Community 5.3.

I need to export some tables from MS Access 2016 to MySQL. It used to work. However, recently, I can't use the following: 
1) Use a mouse to Right click the table in MS Access and select Export Data
2) In the window, Data Transfer, select the Target MySQL database; Mapping: Create.
...

Get a problem at 2), here if click the button, Column's mapping, **no** columns show up in the window, Map columns of [table name]. (But it should display the columns needed to be exported.)

I can export tables from other sources (e.g. CSV, Oracle) to MySQL. 

How to solve this problem? Is this a bug for DBeaver?

**Comment by serge-rider** [comment] 2018-12-11 11:38
I can't reproduce this. In my env export from Access works ok:

![access-export](https://user-images.githubusercontent.com/6398845/49798047-5e894480-fd52-11e8-870c-60e743b39c97.gif)

Could you provide a bit more details?

**Comment by dbeaveroo** [comment] 2018-12-11 15:59
Thank you serge-rider.

I use the same steps as you do but I can't see the info of columns.

I just find a work-around for this problem: 
* Every time after I connect to the MS Access 2016 database, I need to click the arrow for [Indexes] first and let the list drop down. (There are 2 SYS_IDX_... indexes created by DBeaver or MS Access automatically. Not sure how they come out.)
* Then use whatever [Export Data] or other features like [Edit data], [Read data in SQL console], and [View Diagram], the columns info (e.g. in Properties for [Edit data]) can be found. 
* Export can work after the columns info shows up.

It's weird. 

Not sure what happened? Is this a bug?

**Comment by serge-rider** [comment] 2018-12-13 09:39
If you can reproduce the problem with columns - please post debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files).

Maybe the actual problem is in database version or something like that.

If it is possible to send me a sample of a database with such "corrupted" columns - please send it on serge@jkiss.org.

**Comment by serge-rider** [comment] 2019-01-21 17:46
This was fixed in #4956. You can check it in 5.3.3 version.

**Closed by serge-rider** 2019-01-21 17:46 UTC
Labels: duplicate, question
