### ISSUE TITLE
22.1.2 hanging after upgrade 

### ISSUE THREAD

**Issue by amartin141** [dbeaver/dbeaver#17144] opened 2022-07-21 15:11 UTC
#### System information: 
- Operating system (distribution) and version - Windows Server 2012R2
- DBeaver version - Latest on website as of 7/21/2022 10:00 AM DST
- Additional extensions 

#### Connection specification:
- Database name and version IBM V7R3
- Driver name IBM DB2 odbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:  

immediate previous version was working no problem.  With this upgrade, data sets returned with previously working query (no changes) of 144,000 rows - dbbeaver hangs.

**NOTE:  the query appears to return all of the requested rows in a timely manner, and immediately afterwards pops up a small message about 'Copying', and then hangs**

**Comment by uslss** [comment] 2022-07-21 16:35
#17136

**Comment by LonwoLonwo** [comment] 2022-07-21 17:35
Probably fixed in #17068 
Fix will be available in the next release - 22.1.3

**Comment by nathmate** [comment] 2022-07-22 00:36
I am also finding that since upgrading to 22.1.2 , dbt is now hanging on all queries. It seems to get stuck on the "Load composite cache: Load composite objects".

**Comment by LonwoLonwo** [comment] 2022-07-22 07:15
Hello @nathmate 
What database do you use?

**Comment by LonwoLonwo** [comment] 2022-07-22 09:45
We created an Early Access version.
Please test it and tell us the hanging issue is solved or not https://dbeaver.io/files/ea/

**Comment by LonwoLonwo** [comment] 2022-07-25 06:43
Closed as duplicate of #17068

Fix is already available in version 22.1.3
https://dbeaver.io/download/

**Closed as not planned by LonwoLonwo** 2022-07-25 06:43 UTC
Labels: xf:data
