### ISSUE TITLE
DBEAVER 6.2.2 can't open CLOB - (oracle)

### ISSUE THREAD

**Issue by jssnfc** [dbeaver/dbeaver#6953] opened 2019-10-09 22:23 UTC
Hi,
I can't open CLOB data in result set. 
Please help!

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment] 2019-10-10 05:14
I can't reproduce this. CLOB issue (with long clob/text values in panel view) was fixed in 6.2.2.
Please provide more details about your problem.

**Comment by uslss** [comment] 2019-11-18 20:30
Ticket closed.
There is no update more than a month

**Closed by uslss** 2019-11-18 20:30 UTC
Labels: can't reproduce, wait for response
