### ISSUE TITLE
Add support for multiple cursor/edit/selection (again)

### ISSUE THREAD

**Issue by BERRELION** [dbeaver/dbeaver#13917] opened 2021-09-15 14:48 UTC
Addition of support for multiple cursor / selection / edition pleeeeaaassssseeeee.
Issue #6064 already claimed it... trying to throw this back again now in mid-2021
Or has it already been added?

And frustrating fact is that pgAdmin4 has this feature... 😢😒

**Comment by ShadelessFox** [comment] 2021-09-15 14:52
Hello @BERRELION,

The feature is not added yet but planned to be added.

I have to close this issue as a duplicate of mentioned #6064 because it's indeed a duplicate.

**Closed as completed by ShadelessFox** 2021-09-15 14:52 UTC
Labels: duplicate
