### ISSUE TITLE
Keep Office Integration on upgrade

### ISSUE THREAD

**Issue by Austin1** [dbeaver/dbeaver#17732] opened 2022-09-26 15:00 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I do an upgrade and lose the Office integration extension

**Describe the solution you'd like**
When checking for a DBeaver upgrade, the application should note to the end user if there is not compatible extensions. If the extensions are compatible, include this in the upgrade process so that you do not lose features on upgrade.

**Describe alternatives you've considered**
Manually reinstalling each upgrade

**Additional context**

**Comment by E1izabeth** [comment] 2022-09-26 15:02
Thank you for feature request.
Duplicate of #5317.

**Closed as not planned** 2022-09-26 15:03 UTC
Labels: duplicate
