### ISSUE TITLE
New Version Release Checker - error

### ISSUE THREAD

**Issue by peterhatz** [dbeaver/dbeaver#4261] opened 2018-09-24 01:49 UTC
Hi,

I get a `java.lang.NullPointerException` when the **New Version Release Checker** runs (background or manual). I've tried running this on 2 different installs of DBeaver (Pop!_OS 18.04) and get the same (version `5.2.0.201809092115`) message.

Not sure if it's my side or something it's checking?

Thanks!

**Comment by pstein** [comment] 2018-09-24 04:40
I have the same problem

**Comment by serge-rider** [comment] 2018-09-24 10:41
Duplicate of #4264
It was fixed in 5.2.1 version (201809240817)
Thank for the bug report anyway.

**Closed by serge-rider** 2018-09-24 10:41 UTC
Labels: bug

**Comment by peterhatz** [comment] 2018-09-24 23:09
Thanks for that.

**Comment by yooitzPatricia** [comment] 2019-12-30 13:58
This seems to be an issue again. When opening DBeaver (current version 6.3.1.201912221734), I receive a "Problem Occurred" box advising Open connection to -db- has encountered a problem. java.lang.NullPointerException. This happens with each tab that is opened. 


![db bug 1](https://user-images.githubusercontent.com/59365765/71584849-8fb1ef80-2ae2-11ea-8db8-ce2d70069fb0.JPG)
![db bug 2](https://user-images.githubusercontent.com/59365765/71584850-8fb1ef80-2ae2-11ea-8ba6-37d0854e9185.JPG)
