### ISSUE TITLE
Format - Morph to delimited list cuts off list items

### ISSUE THREAD

**Issue by DragonStorm97** [dbeaver/dbeaver#5782] opened 2019-04-24 12:36 UTC
Morph to delimited list cuts off list items.
example:

> abcasdfasdf asdf 
> asdfsadfsdfdsfsadfd
> asdfas
> dfs
> afdfdsfadfasdfasdf sadfsadf sadfs

is transformed into:

> ('abcasdfasdf asd','asdfsadfsdfdsfsadfd','asdfas','dfs','afdfdsfadfasdfasdf sadfsadf sad')

instead of:

> ('abcasdfasdf asdf ','asdfsadfsdfdsfsadfd','asdfas','dfs','afdfdsfadfasdfasdf sadfsadf sadfs')

I'm not sure what the pattern of missing characters are, or if there is one, but this happened when I was morphing a list for an in() filter and caused me to miss a lot.

It's seemingly random as it's not cut off at a specific length or characters.

**Comment by serge-rider** [comment] 2019-04-24 21:16
Looks like duplicate of #5663
You can test the fix in Early Access version (https://dbeaver.io/files/ea)

**Closed by serge-rider** 2019-04-24 21:16 UTC
Labels: bug, duplicate
