### ISSUE TITLE
Singel "Save" dialog for all open files

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#12893] opened 2021-06-18 11:59 UTC
In the course of a day's work I edit several editors.
On closing DBeaver a series of "Save resource" dialogs pops up, one for each open editor.

Instead, use one dialog for all open editors, like Eclipse does:
![Screenshot_20210618_135253](https://user-images.githubusercontent.com/50481865/122557634-5609d700-d03d-11eb-97fb-7f2a43daa8ab.png)

**Comment by michal-bartak** [comment] 2021-06-22 12:36
I'm sure it was working like this about half year ago, and with some version suddenly has been replaced with request for every single file.
BTW seems like duplicate of https://github.com/dbeaver/dbeaver/issues/12862

**Comment by uslss** [comment] 2021-06-23 11:54
duplicates #12862

**Closed as completed by uslss** 2021-06-23 11:54 UTC
Labels: duplicate
