### ISSUE TITLE
Snap: update strategy

### ISSUE THREAD

**Issue by fbc** [dbeaver/dbeaver#9673] opened 2020-08-31 11:41 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my DBeaver asks me to update it when there is no snap update for it yet.

**Describe the solution you'd like**
I would be wonderful is you either a)disable the update mechanism on those uploaded to SNAP or FLATPAK for example, or b)update to SNAP and FLATPAK first and wait 24-48 hours before releasing the version on your servers. So half the planet does not get notifications for upgrades they cannot perform/get through their chosen distribution method.

**Describe alternatives you've considered**
It's too wonderful a piece of software to consider using anything else.

**Additional context**
Keep up the good work!

**Comment by kseniiaguzeeva** [comment] 2020-09-04 14:07
We are going to integrate SNAP update. It is a kind of bug from our side.

**Comment by tati-kru** [comment] 2020-09-18 11:42
duplicate of #9698

**Closed by tati-kru** 2020-09-18 11:42 UTC
Labels: bug, xf:snap
