### ISSUE TITLE
Postgres JSONB big Json Object - freeze - memory leak

### ISSUE THREAD

**Issue by FHBGLD** [dbeaver/dbeaver#16383] opened 2022-05-02 05:55 UTC
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

Windows 10
Dbeaver 22.0.4

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

Postgres 11
see screenshots
ssh tunnel

#### Describe the problem you're observing:
when you open a table with a JSONB field and this JSONB Field contains a large JSON object and you click on this field the DBeaver didn't respond any more and the ram/memory usage goes through the sky (see screenshots).

#### Steps to reproduce, if exist:
just click on a JSONB field with a large JSON object in it.

#### Include any warning/errors/backtraces from the logs
see screenshot
![dbeaver_1](https://user-images.githubusercontent.com/33415881/166190305-ae061f81-5e48-490a-b889-ce6a983f73c2.jpg)
![dbeaver_2](https://user-images.githubusercontent.com/33415881/166190307-51548a01-afb1-48fc-967c-fabe955aa216.jpg)
![dbeaver_3](https://user-images.githubusercontent.com/33415881/166190309-bb2df7ac-9819-420a-9df9-7e0cbf09ee79.jpg)
![dbeaver_4](https://user-images.githubusercontent.com/33415881/166190312-376935ab-ca31-44da-b15f-c49754852964.jpg)

**Comment by LonwoLonwo** [comment] 2022-05-02 09:48
Hello @FHBGLD 

What current value representation do you have? Did you try to change it?
Also, do you use auto-format? If you do, did you try to disable it?

![2022-05-02 12_43_19-DBeaver Ultimate 22 0 4 - json_test](https://user-images.githubusercontent.com/45152336/166215994-26971ef3-d1dc-4411-a14b-64d07416e0b3.png)

**Comment by LonwoLonwo** [comment] 2022-05-02 09:49
Duplicate of https://github.com/dbeaver/dbeaver/issues/15951

**Comment by FHBGLD** [comment] 2022-05-02 11:21
Hello @LonwoLonwo ,

thanks for the quick answer.
No I don't have the auto format option enabled (see screenshot).
I also tried it on another PC and the same problem appear.

Thanks and best regards
Michael
![dbeaver1](https://user-images.githubusercontent.com/33415881/166225909-ced96a20-f190-4ba4-bef6-f28e5f49da36.jpg)
l

**Comment by LonwoLonwo** [comment] 2022-05-03 14:08
Thanks for the answer and for the bug report @FHBGLD 

I am closing this issue as a duplicate.

**Closed as completed by LonwoLonwo** 2022-05-03 14:08 UTC
Labels: x:postgresql, xf:data, xf:ui
