### ISSUE TITLE
oracle case clause based statement not evaluated correctly

### ISSUE THREAD

**Issue by kiravi** [dbeaver/dbeaver#3484] opened 2018-05-16 21:52 UTC
The following oracle sql is not evaluated in DBeaver. But runs OK in sql developer.
-------------------------------------------------------------------------------------------
**Oracle SQL:**
-------------------------------------------------------------------------------------------
WITH dw AS (
  SELECT 
-- null AS str
    ';abc_def;def_ghi;ghi_jkl;' AS str
  FROM
    dual
) SELECT
  d.str,
  CASE
      WHEN d.str IS NOT NULL THEN length(d.str) - length(replace(d.str,';') ) - 1
      ELSE 0
    END
  AS len,
  l.lvl,
  (
    CASE
      WHEN d.str IS NOT NULL THEN substr(d.str,instr(d.str,';',1,l.lvl) + 1,instr(d.str,';',1,l
.lvl + 1) - instr(d.str,';',1,l.lvl) - 1)
      ELSE d.str
    END
  ) AS sstr
  FROM
  dw d,
  (
    SELECT
      level AS lvl
    FROM
      dual
    CONNECT BY
      level <= 25
  ) l
  WHERE
  l.lvl <= (
    CASE
      WHEN d.str IS NOT NULL THEN length(d.str) - length(replace(d.str,';') ) - 1
      ELSE 1
    END
  );

**Comment by serge-rider** [comment] 2018-05-20 15:03
Duplicate of #3481

**Closed by serge-rider** 2018-05-20 15:03 UTC
Labels: bug, duplicate, x:oracle
