### ISSUE TITLE
Unable to run plpgsql code with version 6.2.3.2.xx

### ISSUE THREAD

**Issue by petervalencic** [dbeaver/dbeaver#7052] opened 2019-10-22 09:35 UTC
Hi,
I'm using the latest version of DBeaver:  6.2.3.201910141013, On Windows 10.

I have a problem running  the plpgsql script:  

![image](https://user-images.githubusercontent.com/10866388/67273709-467c6880-f4bf-11e9-95f4-98e474fe7cd3.png)

Also, the code is "colored" almost all "green"
![image](https://user-images.githubusercontent.com/10866388/67273798-775c9d80-f4bf-11e9-8316-5cfaaaf4608a.png)

Don't know why.. but with some older version of DBeaver it worked fine...

**Comment by serge-rider** [comment] 2019-10-22 13:22
Duplicate of #7050
Workaround: use $$ with tag name (e.g. $function$) around function definition.

Thanks for the bug report anyway.

**Closed by serge-rider** 2019-10-22 13:22 UTC
Labels: bug, duplicate
