### ISSUE TITLE
新建表新建列的注释会莫名其妙小时

### ISSUE THREAD

**Issue by ShisanXing** [dbeaver/dbeaver#16474] opened 2022-05-13 06:40 UTC
新建表新建列时，如果不点击”更多“按钮，填写的注释在点击其他地方时会丢失，这个问题存在N年了，就没有想过要解决？？？？
![image](https://user-images.githubusercontent.com/18689511/168225871-6b5e170e-f923-4ebe-9bc7-ba004b6e7b4c.png)

**Comment by E1izabeth** [comment] 2022-05-13 11:58
Hi, @ShisanXing! Thank you for bug report.
The issue is reproducible if to click on another area after writing text to the text area for Comment instead of pressing Enter. This behavior differs from another textboxes, for example, changes are saved after writing text to text area for Default and clicking to other area.

**Comment by LonwoLonwo** [comment] 2022-05-13 12:15
Closing as duplicate of https://github.com/dbeaver/dbeaver/issues/15620

**Closed as completed by LonwoLonwo** 2022-05-13 12:15 UTC
Labels: xf:ui
