### ISSUE TITLE
SQL Server - don't recognize "go"

### ISSUE THREAD

**Issue by rramos-as** [dbeaver/dbeaver#29325] opened 2024-05-03 16:42 UTC
### Description

Sames as issue #9303 and #12078

It works fine with 23.3.5

![imagem](https://github.com/dbeaver/dbeaver/assets/97473661/4efec7f3-fa86-461d-a1e5-5ff97b2c4ecc)

### DBeaver Version

24.0.3

### Operating System

Windows 11 Pro

### Database and driver

com.microsoft.sqlserver mssql-jdbc 12.4.1.jre11

**Comment by E1izabeth** [comment] 2024-05-03 17:06
Thank you for bug report.
It's a duplicate of #26416
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Closed as not planned by E1izabeth** 2024-05-03 17:06 UTC
Labels: duplicate, xf:sql execution
