### ISSUE TITLE
PostgreSQL Internal jdbc driver error while creating function

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#7469] opened 2019-12-24 12:21 UTC
#### System information: 
- Windows 7 x64
- DBeaver 6.3.1.201912221734
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5
- PostgreSQL standard driver [9.4.1212.jre7]
- NO tunnels or proxies

#### Describe the problem you're observing:
SQL Error: Internal jdbc driver error while creating or replacing function

#### Steps to reproduce, if exist:
```
CREATE OR REPLACE FUNCTION public.test_function(integer)
 RETURNS SETOF record
 LANGUAGE plpgsql
AS $function$
BEGIN
	IF('1'='1') THEN
		RETURN NEXT ('Error code'::text,'Error text'::text);
	END IF;
END;
$function$
```
returns "SQL Error: Internal jdbc driver error". Tested with both new PostgreSQL params $$ and $text$ (text and code block). This code doesn't raise error in DBeaver 6.2.2

**Comment by serge-rider** [comment] 2019-12-26 13:29
Seems to be duplicate of #7460

**Closed by serge-rider** 2019-12-26 13:29 UTC
Labels: bug, duplicate
