### ISSUE TITLE
Menus are displayed out of place.

### ISSUE THREAD

**Issue by arael82** [dbeaver/dbeaver#8748] opened 2020-05-19 19:42 UTC
#### System information: 
- Operating system (distribution) and version: Linux (Ubuntu 19.04)
- DBeaver version 7.0.5 (Community Edition).

![Selección_034](https://user-images.githubusercontent.com/13138288/82370905-b02a0a00-99ef-11ea-9dfd-159db3997c9c.png)

- Additional extensions NONE

#### Connection specification:
- Database name and version Oracle 19g
- Driver name Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

The menus are displayed in this part of the GUI, as the main ones as the contextual menu.

This error happened to me when updating from 7.0.4 to 7.0.5 today.

#### Steps to reproduce, if exist:
Click over any menu, or right-click over a DB object.

**Comment by uslss** [comment] 2020-05-20 21:35
cannot reproduce it.
do you use some special shell?

**Comment by arael82** [comment] 2020-05-22 17:50
I am using Ubuntu 19.04, no special shell is installed. I used the deb package from DBeaver official sources.

**Comment by uslss** [comment] 2020-06-26 10:00
Still cannot reproduce.
@arael82 is it still reproducible against 7.1.1?
Thanks in advance

**Comment by arael82** [comment] 2020-06-26 15:56
It does. But I think I could find a way to reproduce. When you move the window from one display to another with bigger resolution, the menus appear out of place.

If I don't move the window after starting the application, I don't have the issue. Maybe it is more related to the shell instead of the application.

**Comment by uslss** [comment] 2020-07-06 20:13
closed as non-dbeaver issue

**Closed by uslss** 2020-07-06 20:13 UTC
Labels: bug, can't reproduce, wait for response, xo:linux
