### ISSUE TITLE
Close Idle Connection Setting Ignored

### ISSUE THREAD

**Issue by Xylandor** [dbeaver/dbeaver#22764] opened 2024-02-08 21:27 UTC
### Description

With the recent version (23.3.4.202402041841) that defaults to the disconnection of idle connections, trying to disable the setting is being ignored. You can uncheck the "Close idle connection after (seconds)" setting and save it, but DBeaver still continues to auto-disconnect idle connections. Going back into the settings, it shows this settings unchecked, but when you exit DBeaver and run it again, that setting has been checked again. 

### DBeaver Version

23.3.4.202402041841

### Operating System

Sonoma 14.3 on an Apple M2 Pro

### Database and driver

MySQL 8 and AWS / Redshift

### Steps to reproduce

1. In DBeaver settings, navigate to Connections > Connection Types. 
2. Uncheck the option under the Settings secion, named, "Close idle connection after (seconds)".
3. Click Apply and Close.
4. Go back into settings and you'll notice it stays unchecked, so it should work.
5. Establish a connection and wait the alotted idle time and it will disconnect your connection.
6. Exit out of DBeaver.
7. Start up DBeaver again.
8. Go back into the settings and you'll notice now that the setting is checked again.

### Additional context

I'm not using any extensions or add-ons. Except for some minor data formatting setting changes, I'm using the factory default settings setup in DBeaver.

**Comment by Xylandor** [comment] 2024-02-08 22:06
In addition, trying to change the seconds value doesn't save either. Keeps reverting back to 3600.

**Comment by E1izabeth** [comment] 2024-02-08 22:28
Thank you for bug report. It's a duplicate of #22721
You can try Early Access version - it's fixed there already https://dbeaver.io/files/ea/

**Closed as not planned by E1izabeth** 2024-02-08 22:28 UTC
Labels: duplicate, xf:connection
