### ISSUE TITLE
Auto-complete doesn't propose column names (without a table alias)

### ISSUE THREAD

**Issue by gururagavan2008** [dbeaver/dbeaver#20140] opened 2023-05-30 16:22 UTC
### Description

![image](https://github.com/dbeaver/dbeaver/assets/55467822/6d357268-cd57-4368-9131-69958f52d7dc)

Auto-complete doesn't propose column names (without a table alias).
Whereas, if I a use a table alias, then it proposes column names. This feature seems to be not working from CE 23.0.5. Was working until CE 23.0.3.

![image](https://github.com/dbeaver/dbeaver/assets/55467822/98411d85-0afe-43bd-b6b8-a80382b4a37a)

### DBeaver Version

CE 23.0.5.202305211610

### Operating System

Win 10

### Database and driver

REDSHIFT - redshift-jdbc42-2.1.0.3
Was able to replicate the issue in Postgres as well

**Comment by E1izabeth** [comment] 2023-05-30 16:26
Thank you for bug report. I'm closing this issue as a duplicate of #20032. This bug has been already fixed and fix will be available in the next release.

As a workaround you can uncheck this setting to make it work again.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/987309c0-6adf-41d8-ac2b-d1ca9be7d772)

**Closed as not planned by E1izabeth** 2023-05-30 16:26 UTC
Labels: duplicate, xf:sql parser
