### ISSUE TITLE
Add Elapsed Time on the Statistics Tab.

### ISSUE THREAD

**Issue by gtdegamo** [dbeaver/dbeaver#14189] opened 2021-10-11 18:48 UTC
**Is your feature request related to a problem? Please describe.**

When performing a delete / update / plsql.  A statistics tab is produced.  It would be nice to include the time it too to complete command.  I know it's at the bottom of the corner, but I think it sometimes shows the times of the latest query done and not the time associated with the statistics tab?  I don't know.  I get confused at times.  it would be nice to include it in the statistics page the time it took, b/c after all, it is the statistics page.  (Thanks.  And keep up the great work!)

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by ShadelessFox** [comment] 2021-10-11 18:59
Hello @gtdegamo,

Thanks for feature request.

Looks like it's a duplicate of #5450. I've extended it to also include elapsed/delta time of query.

**Closed as completed by ShadelessFox** 2021-10-11 18:59 UTC
Labels: duplicate
