### ISSUE TITLE
NullPointerException in Goto Database Object

### ISSUE THREAD

**Issue by jk3us** [dbeaver/dbeaver#3794] opened 2018-07-13 14:21 UTC
In the Ctrl+Shift+D dialog to search for and go to a db object, as soon as I type the first letter, I always get an error.  The error log shows this:

```
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.core.jobs
Error
Fri Jul 13 09:16:07 CDT 2018
An internal error occurred during: "Items filtering".

java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.dialogs.GotoObjectDialog.fillContentProvider(GotoObjectDialog.java:132)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2050)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:1998)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:1970)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:1957)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

This is dbeaver 1.5.2 on win7.  This happens for me when connected to a postgres db and an sqlite db, at least.

**Comment by serge-rider** [comment] 2018-07-14 13:04
Duplicate of #3727
Thanks for report anyway

**Closed by serge-rider** 2018-07-14 13:04 UTC
Labels: bug, duplicate
