### ISSUE TITLE
Have a tab filter by connection

### ISSUE THREAD

**Issue by mikesmichael** [dbeaver/dbeaver#34654] opened 2024-07-04 12:56 UTC
If you work with many environnement, many user and so, many scripts and opened database object, Can be pain in the *ss to retrieve properly the script you are working with for the right environnement.

I propose to be able to filter the script by current connection with a button, When pressed, the tab will be filtered by the selected database and when off, all tabs will be showed. The button can be next to the connection list in the toolbar.

I tried to generate and icon to represent it just to give an idea:

![image](https://github.com/dbeaver/dbeaver/assets/9534827/af049bfb-cb54-4509-a909-9a1733363b54)

A filter or anything else linked to the database dropdown can be an option too.

**Comment by E1izabeth** [comment] 2024-07-08 15:35
Thank you for idea. I'm closing it as a duplicate of #10235 and #21485
Your idea is great. I like the icon.
You can vote for the mentioned issues with 👍 under the issue description, left a comment there to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-07-08 15:35 UTC
Labels: duplicate, xf:ui
