### ISSUE TITLE
Database filter is broken

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#4582] opened 2018-11-08 14:55 UTC
I updated to 5.2.4 and now the database filter is broken.

I create a new filter:

![grafik](https://user-images.githubusercontent.com/3126597/48206443-ba853580-e36e-11e8-9def-ba847388c542.png)

and this is the result:

![grafik](https://user-images.githubusercontent.com/3126597/48206457-c40e9d80-e36e-11e8-9128-2822f91250d6.png)

I tried restarting and reseting the filter. Then it worked again. Not sure what caused this.

**Comment by serge-rider** [comment] 2018-11-09 06:04
Duplicate of #4554
Thanks for the bug report anyway.

**Closed by serge-rider** 2018-11-09 06:04 UTC
Labels: bug, duplicate, x:mysql
