### ISSUE TITLE
Informix table information: References

### ISSUE THREAD

**Issue by amivanovano** [dbeaver/dbeaver#1980] opened 2017-08-08 06:59 UTC
When I clicked on Tab References dbeaver did some work and said:

![image](https://user-images.githubusercontent.com/28041955/29059905-312acf9a-7c20-11e7-9935-84d5eeca4edf.png)

It happens sometimes.

**Comment by serge-rider** [comment] 2017-08-08 07:14
Please post error stacktrace (you can get it in Error Log view or in debug log - https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by amivanovano** [comment] 2017-08-08 09:11
eclipse.buildId=unknown
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Aug 08 12:08:38 MSK 2017


java.sql.SQLException
	at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:474)
	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:443)
	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:394)
	at com.informix.jdbc.IfxSqli.receiveError(IfxSqli.java:3477)
	at com.informix.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2379)
	at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2304)
	at com.informix.jdbc.IfxSqli.executeFetch(IfxSqli.java:2038)
	at com.informix.jdbc.IfxSqli.getaRow(IfxSqli.java:4082)
	at com.informix.jdbc.IfxResultSet.next(IfxResultSet.java:494)
	at com.informix.jdbc.IfxDatabaseMetaData.getColumns(IfxDatabaseMetaData.java:3533)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getColumns(JDBCDatabaseMetaDataImpl.java:1155)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:129)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChild(JDBCStructCache.java:230)
	at org.jkiss.dbeaver.ext.generic.model.GenericTable.getAttribute(GenericTable.java:156)
	at org.jkiss.dbeaver.ext.generic.model.GenericTable.loadReferences(GenericTable.java:371)
	at org.jkiss.dbeaver.ext.generic.model.GenericTable.getReferences(GenericTable.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:793)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:479)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:403)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:190)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:563)
	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:229)
	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by amivanovano** [comment] 2017-08-08 09:22
It happens sometimes.

**Comment by serge-rider** [comment] 2017-08-08 20:12
This seems to be driver-related problem (https://stackoverflow.com/questions/42509044/schemaspy-error-message-while-generating-the-report)
Could you try to use different Informix driver version?

**Comment by amivanovano** [comment] 2017-08-15 06:02
Yes, it works in version 3.70.JC8DE and not works in 4.10.JC8DE and 4.10.JC9DE

**Comment by ceinmart** [comment] 2019-03-28 17:13
With Informix driver 4.10.JC12 works fine for me (dbeaver 6.0)

**Comment by amivanovano** [comment] 2019-03-29 13:32
Informix driver 4.10.JC12 not works for me (dbeaver up to 6.01) ( for tables with tens references to its )

**Comment by ceinmart** [comment] 2019-03-29 17:24
> Informix driver 4.10.JC12 not works for me (dbeaver up to 6.01) ( for tables with tens references to its )

Weird, I have here a table with 120 references and many other tables with +50 references where all them show the references without problem. 
Did you have IBM support subscription? 
My suggestion is open a CASE there since really looks like a driver defect. 
Unfortunately (or not) I'm not able to reproduce here, otherwise, I opened a CASE for that....

I'm using Informix Server v12.10.FC12
If you have other versions of the Informix server for test to validate if the problem is really at the JDBC driver or the version of the Informix server you are using.

Regards
Cesar

**Comment by amivanovano** [comment] 2019-04-01 13:34
I'm using Informix Server 12.10.FC7

**Comment by brian-hughes** [comment] 2019-04-01 15:09
The problem here is with some versions of the Informix JDBC driver.  Quick fix is to upgrade to the latest 4.50.1 driver.  It's out on maven.

`
<dependency>
    <groupId>com.ibm.informix</groupId>
    <artifactId>jdbc</artifactId>
    <version>4.50.1</version>
</dependency>
`

In detail.  The 4.10.X drivers introduced a statement cleaner thread that runs every 15 seconds and looks for resources that need to be closed as they have no more references and could be garbage collected. The problem, then compounds as a couple JDBC metdata calls incorrectly failed to close resources causing this cleaner thread to close resources in the middle of the work sometimes.  Hence some people see it often, some never. You can work around it with 4.10.JC12 where we added a connection flag to disable the cleaner thread (IFMXCONNECTION_CLEANER_THREADS=0).  Or the best option is to upgrade to the newest 4.50.1 driver which has this issue properly fixed.

**Comment by amivanovano** [comment] 2019-04-02 07:02
Many thanks to Brian. 
Newest driver 4.50.1 cleaned resources precisely ( workaround is OK too )

I'll close issue.

**Closed** 2019-04-03 07:25 UTC
Labels: bug, can't reproduce
