### ISSUE TITLE
Incorrect Chinese translation for tab right-click menu item [Close All] (erroneously translated as 关闭关闭)

### ISSUE THREAD

**Issue by bianyun** [dbeaver/dbeaver#21465] opened 2023-10-07 05:35 UTC
### Description

In recent releases, the Simplified Chinese translation of the menu item "Close All" in the right-click menu of an editor tab has been incorrectly translated as "Close All", while the correct translation is "Close All".

This menu item is Eclipse's own localization plug-in (as far as I know, babel) that is responsible for translation. This translation error problem has existed in previous versions, but the latest version (https://download.eclipse .org/technology/babel/update-site/latest/) has fixed this issue.

I don’t know why the Simplified Chinese translations of recent versions of DBeaver do not use the latest version of Babel.

If you manually install the latest version of babel in the version compiled from the latest source code, this problem will not exist.

![Snipaste_2023-10-07_11-55-02](https://github.com/dbeaver/dbeaver/assets/4619776/5dc5ac04-06e9-4193-9908-818a19f6bd09)

![Snipaste_2023-10-07_11-59-48](https://github.com/dbeaver/dbeaver/assets/4619776/8f6bd498-101b-4e91-9240-afeb2aa0172d)

![Snipaste_2023-10-07_12-11-08](https://github.com/dbeaver/dbeaver/assets/4619776/4941b26d-fb4e-452b-a6a2-80d09c9d2cec)

### DBeaver Version

Community Edition 23.2.1

### Operating System

Windows 11 Professional Edition (Simplified Chinese), 22H2

### Steps to reproduce

In Preferences => User Interface => Regional Settings, set the language to Simplified Chinese.

**Comment by E1izabeth** [comment] 2023-10-09 08:34
Thank you for bug report.
We're waiting for a stable build. It's available in the update site, but there is no fresh build included this fix (https://github.com/dbeaver/dbeaver/issues/17697#issuecomment-1404587242)

Closing as a duplicate of #17697

**Closed as not planned by E1izabeth** 2023-10-09 08:34 UTC
Labels: duplicate, xf:i18n

**Comment by bianyun** [comment] 2023-10-09 09:47
OK, I get it. I hope the latest stable version of babel will be released soon.

**Comment by bianyun** [comment] 2023-10-23 03:16
A temporary solution for this issue:
`https://github.com/dbeaver/dbeaver/issues/17697#issuecomment-1754592163`
