### ISSUE TITLE
xls description export not working with 22.3

### ISSUE THREAD

**Issue by caribouman** [dbeaver/dbeaver#19019] opened 2023-02-09 08:10 UTC
### Description

Hi, when export result to xls or to other format
![image](https://user-images.githubusercontent.com/33265244/217753669-b45e1773-2060-47fe-a3a6-93b7adb5f3e8.png)
the description text is not exported

even select both , or label or description in the options
![image](https://user-images.githubusercontent.com/33265244/217753892-7a0d4b73-903f-4622-b47e-17cb1dc499f1.png)

### DBeaver Version

CE 22.3.4

### Operating System

windows 10

### Database and driver

DB2

### Steps to reproduce

export result to xls

**Comment by LonwoLonwo** [comment] 2023-02-09 09:00
Thanks for the report @caribouman 

This is a duplicate of https://github.com/dbeaver/dbeaver/issues/18330

As a strange workaround - you can create a table/view from your resultSet with commented columns and export from the table/view.

**Closed as not planned by LonwoLonwo** 2023-02-09 09:00 UTC
Labels: duplicate, xf:datatransfer
