### ISSUE TITLE
Each editor connects separately bug

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6458] opened 2019-08-06 11:49 UTC
When "each editor is connected separately" is checked, a temporary Table is created using the script. The result found from the temporary Table cannot be exported. It is indicated that "Table not found 'temp_visit'",If you don't check, you can only export one result set
![image](https://user-images.githubusercontent.com/26621087/62537303-a9783f00-b882-11e9-9e1e-02f0d06767ae.png)
![image](https://user-images.githubusercontent.com/26621087/62537597-623e7e00-b883-11e9-9f53-ba1015fc4a6d.png)
![image](https://user-images.githubusercontent.com/26621087/62538253-eba28000-b884-11e9-980b-53baac5ee5ec.png)
![image](https://user-images.githubusercontent.com/26621087/62538278-fbba5f80-b884-11e9-8662-b4161373b371.png)

eclipse.buildId=unknown
java.version=1.8.0_73
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
错误
Tue Aug 06 19:42:58 CST 2019
SQL 错误 [10001] [42S02]: Error while compiling statement: FAILED: SemanticException [Error 10001]: Line 1:15 Table not found 'temp_visit'
eclipse.buildId=unknown
java.version=1.8.0_73
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
错误
Tue Aug 06 19:42:58 CST 2019
Error while compiling statement: FAILED: SemanticException [Error 10001]: Line 1:15 Table not found 'temp_visit'

org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: FAILED: SemanticException [Error 10001]: Line 1:15 Table not found 'temp_visit'
	at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:400)
	at org.apache.hive.service.cli.operation.SQLOperation.prepare(SQLOperation.java:187)
	at org.apache.hive.service.cli.operation.SQLOperation.runInternal(SQLOperation.java:271)
	at org.apache.hive.service.cli.operation.Operation.run(Operation.java:337)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:439)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementAsync(HiveSessionImpl.java:416)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:78)
	at org.apache.hive.service.cli.session.HiveSessionProxy.access$000(HiveSessionProxy.java:36)
	at org.apache.hive.service.cli.session.HiveSessionProxy$1.run(HiveSessionProxy.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1924)
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:59)
	at com.sun.proxy.$Proxy23.executeStatementAsync(Unknown Source)
	at org.apache.hive.service.cli.CLIService.executeStatementAsync(CLIService.java:282)
	at org.apache.hive.service.cli.thrift.ThriftCLIService.ExecuteStatement(ThriftCLIService.java:503)
	at org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1313)
	at org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1298)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:56)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:15 Table not found 'temp_visit'
	at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.getMetaData(SemanticAnalyzer.java:1906)
	at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.getMetaData(SemanticAnalyzer.java:1564)
	at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.genResolvedParseTree(SemanticAnalyzer.java:10174)
	at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.analyzeInternal(SemanticAnalyzer.java:10225)
	at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.analyzeInternal(SemanticAnalyzer.java:10110)
	at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:223)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:560)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1358)
	at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1345)
	at org.apache.hive.service.cli.operation.SQLOperation.prepare(SQLOperation.java:185)
	... 26 more
Caused by: java.lang.RuntimeException: org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:15 Table not found 'temp_visit'
	at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.getMetaData(SemanticAnalyzer.java:1614)
	... 35 more

**Comment by Pengchenghua** [comment] 2019-08-06 12:02
![image](https://user-images.githubusercontent.com/26621087/62538307-0e349900-b885-11e9-861d-08a4d8df6f1e.png)

**Comment by serge-rider** [comment] 2019-08-06 12:03
You need to create temp table in the same SQL editor where you use it. Temporary tables exist only within current session (and with this option each SQL editor has its own session).

**Comment by Pengchenghua** [comment] 2019-08-06 12:09
> 您需要在使用它的同一SQL编辑器中创建临时表。临时表仅存在于当前会话中（使用此选项，每个SQL编辑器都有自己的会话）。

没错，但是我是从当前会话中导出的，不是从另外一个会话窗口导出，出现这个问题

**Comment by serge-rider** [comment] 2019-08-06 13:03
Then I can't reproduce this issue. Can you post an SQL script which will reproduce the problem?

**Comment by Pengchenghua** [comment] 2019-08-07 01:04
You can try to connect HIVE and create temporary tables and export them

**Comment by Pengchenghua** [comment] 2019-08-07 01:06
Use different scripts to execute in different session Windows, and export to try

**Comment by Pengchenghua** [comment] 2019-08-07 01:09
SET hive.exec.dynamic.partition.mode = nonstrict;
set mapred.job.queue.name=default;
set  sdate=20180701;
set  edate=20190731;

-- 单品计算SKU
 drop table
	b2b_tmp.p_temp_goods;

create temporary table
	b2b_tmp.p_temp_goods as select
		sdt ,
		customer_no  cust_id,
		goods_code goodsid ,
		SUM(sales_value )sale ,
		SUM(profit )profit
	from
		csx_dw.sale_b2b_item 
	where
		sdt >= '${hiveconf:sdate}'
		and sdt <= '${hiveconf:edate}'
		and shop_id != 'W098'
		and sales_type in('qyg','qyg_c','gc')
	GROUP by
		sdt ,
		customer_no ,
		goods_code ;

**Comment by serge-rider** [comment] 2019-08-29 12:58
Fixed in #6637

**Closed by serge-rider** 2019-08-29 12:58 UTC
Labels: question
