### ISSUE TITLE
incorrect data updated  when editing and the initial select is over multiple tables. with un aligned pk's , but  identical join condition

### ISSUE THREAD

**Issue by we-sell-bags** [dbeaver/dbeaver#22496] opened 2024-01-18 07:35 UTC
### Description

if you have a simple join of 2 tables and the tables are not ordered exactly teh same the update results are wrong.

### DBeaver Version

Version 23.3.2.202401072024

### Operating System

12.7.2

### Database and driver

postgres 15

### Steps to reproduce

take two basic tables with a pk
in the second table make the join condition the first table pk

 SELECT *
FROM customer , workers 
where customer.id=partner_id

when the second table content is edited , the data updated goes into the second table  record of the first tables PK

so if the first table has a pk of 295  & the second table has a pk of 13

when any column related to  table 2 is edited, it goes into the record of teh first tables pk

so data from table 2 shown on screen with record 295 TB1,record 13 TB2 
would actually go into record 295 of TB2 instead of record 13 TB2

**Comment by we-sell-bags** [comment] 2024-01-22 03:31
partial fix....
it now updates the correct table, but throws another error when both tables are edited.
see new bug filed

**Comment by LonwoLonwo** [comment] 2024-02-01 14:57
Hello @we-sell-bags 

Please provide table DDLs.

**Comment by we-sell-bags** [comment] 2024-02-20 02:09
provide it in .
" error thrown when updating multiple tables (related to other update bug) #22528 "

**Comment by Destrolaric** [comment] 2024-03-28 13:14
@we-sell-bags Hi, the #22528 looks pretty similar to the current issue. Are there any noticeable differences?

**Comment by E1izabeth** [comment] 2024-04-23 11:50
Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/22528
If issues are different, please let me know ad provide additional information about it.

**Closed as not planned by E1izabeth** 2024-04-23 11:50 UTC
Labels: duplicate, wait for response, xf:sql execution
