### ISSUE TITLE
Bug: wrong cursor focus introduced in 21.0.4 - 21.1.0

### ISSUE THREAD

**Issue by btanner2** [dbeaver/dbeaver#12672] opened 2021-05-31 14:40 UTC
Hi,

I backup all dbeaver portable versions by myself, so it is very easy to check, which behavior was changed in which version. Until version 21.0.3, you could run a SQL statement and the focus of the cursor stays still in the SQL window.

With 21.0.4 (until 21.0.1) this behavior changed. From that version, the cursor switched automatically from SQL window to the result window after the SQL statement was finished. That happened for exactly the same statements as in 21.0.3. This is really annoying, because I suspect to work and write on from exactly the same cursor position as before I started the SQL statement. Now the focus lies on the result window and if I start typing, I change the results in the first line, first column. Furthermore, you cannot see anymore where an error in your SQL script appears, because till version 21.0.3 the cursor jumped to this position in the SQL windows, which was very helpful. With 21.0.4 and later the cursor jumps to result window.

Could you please change this behavior back to the old way?

From my point of view, this is clearly a bug.

Kind regards
Brian

**Comment by eshirvana** [comment] 2021-05-31 14:47
yes, I can confirm this issue , I have the same problem and It's annoying.

**Comment by uslss** [comment] 2021-06-01 07:40
cannot reproduce an issue against win10. What OS do you use?

**Comment by btanner2** [comment] 2021-06-01 08:50
Win 10.

I guess you have to do a SELECT from a existing table.

`SELECT 1`

let the cursor stay in SQL window. Pressing arrow keys let the cursor move in SQL window. This is how it should work.

`SELECT 1 FROM >existing_table<`

let the cursor switch to result window. Pressing arrow keys let the cursor move in result window. This is a wrong behavior.

Brian

**Comment by p91paul** [comment] 2021-06-01 10:33
@uslss it happens if you run script (Alt+X) instead of running single statement (Ctrl + Enter)

@btanner2 how are you running your statement? I've tried keyboard shortcuts and toolbar buttons and that's the only way I could reproduce, but you seem to be looking to run a single statement and not many.

**Comment by btanner2** [comment] 2021-06-01 12:23
@p91paul

You are right. I am running statements always as a script with (Alt+X) instead of single statement (CTRL + Enter). The reason is I always have to run everything in the active window, instead of a single part. If I want to run a single part only, I select this part and use once more Alt+X. Worked perfectly until 21.0.3.

A short try shows: Alt+X switches the focus, CTRL+Enter does not. Well, this was definitely changed with 21.0.4. Thanks for pointing to this.

In my opinion, the focus should NEVER switch. This is a dangerous behavior, because if you are typing after script is finished you will start to change content of the result table.

**Comment by serge-rider** [comment] 2021-06-01 13:35
Fixed

**Comment by eshirvana** [comment] 2021-06-01 14:42
@serge-rider  did it fixed in Version 21.1.0.202105300349 ? because I still can see it happening

**Comment by serge-rider** [comment] 2021-06-02 07:26
@eshirvana It will be fixed in the version 21.1.1 (see ticket milestone).
Also you can download the Early Access  version (http://dbeaver.io/files/ea)

**Comment by uslss** [comment] 2021-06-03 12:13
verified

**Closed as completed by uslss** 2021-06-03 12:13 UTC
Labels: xf:sql
