### ISSUE TITLE
Cannot access Redshift Spectrum table

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [dbeaver/dbeaver#13928] opened 2021-09-16 20:44 UTC
#### System information: 
- macOS Big Sur 11.6
- 21.2.0

#### Connection specification:
- Redshift server 1.0.29551
- connect through a VPN

#### Describe the problem you're observing:

When trying to query a table that lives inside an external schema (i.e. an AWS Glue database) I get the error:
```
Can't find specified data type by name: 'string'
```

I've confirmed (with TablePlus) that the table is indeed accessible.

**Comment by LonwoLonwo** [comment] 2021-09-16 20:51
Hello @ConstantinoSchillebeeckx 
Thanks for the bug report.
The problem was fixed here https://github.com/dbeaver/dbeaver/issues/13133 and the fix will be available in DBeaver version 21.2.1.
Or you can download the latest build that includes this fix on our early access page https://dbeaver.io/files/ea/

**Comment by uslss** [comment] 2021-09-17 07:20
closed as a duplicate of #13133

**Closed as completed by uslss** 2021-09-17 07:20 UTC
Labels: duplicate, x:redshift, wait for response

**Comment by ConstantinoSchillebeeckx** [comment] 2021-09-17 13:18
I'm having issues with the EA on my mac (dbeaver-ce-21.2.1-macosx.cocoa.x86_64.tar.gz); am I doing something wrong?
![image](https://user-images.githubusercontent.com/8518288/133789024-621cfef7-f9e1-4b97-8c64-9e1bb00f4a38.png)

**Comment by Matvey16** [comment] 2021-09-17 14:14
@ConstantinoSchillebeeckx This happens because the EA version is unsigned. As a workaround you need to disable gatekeeper for this file 
`xattr -dr com.apple.quarantine ~/Downloads/DBeaver.app` (Replace path with your own, bit it is most likely in your Downloads folder)
