### ISSUE TITLE
Tab completion broken in result filtering

### ISSUE THREAD

**Issue by DDriggs00** [dbeaver/dbeaver#35829] opened 2024-10-04 18:09 UTC
### Description

When filtering the results of a query using the `Enter a SQL expression to filter results (use Ctrl+Space)` box, instead of functioning like in the main editor, it both inserts a tab character *and* opens up a dropdown menu containing all columns.

### DBeaver Version

Community Edition 24.2.1

### Operating System

Windows 11

### Steps to reproduce

1. Turn on tab auto-completion in settings
2. Connect to any database which has a table containing data
3. Run a select statement on a table
4. In the results panel, select the filtering text input field
5. Type the first letter of a column name (e.g. `i`) then hit tab to autocomplete
6. See the bug described above.

**Comment by E1izabeth** [comment] 2024-10-04 18:11
Thanks for the bug report. I reproduced the issue

**Comment by ask9** [comment] 2024-12-09 09:24
This has already been reported here: #22081

**Comment by E1izabeth** [comment] 2024-12-09 10:21
Thank you, @ask9

I'm closing it as it's a duplicate of #22081

**Closed as not planned by E1izabeth** 2024-12-09 10:21 UTC
Labels: duplicate, xp:normal, xf:sql autocompletion
