### ISSUE TITLE
Compare tables from different databases (drivers)

### ISSUE THREAD

**Issue by nikitaclarion** [dbeaver/dbeaver#286] opened 2016-03-16 10:22 UTC
Trying to compare metadata of 2 tables of databases-SQL Server 2008 R2 & My SQL respectively.
But its displaying message that 'Objects of different types are selected.You may compare only objects of the same type'. Please suggest.

**Comment by jiangxincode** [comment] 2016-04-01 16:50
Yeah, I also want it.

**Comment by serge-rider** [comment] 2017-01-24 09:38
Agreed, this would be a great feature.

**Comment by serge-rider** [comment] 2017-01-24 09:50
Correlates with #957

**Comment by serge-rider** [comment] 2019-05-04 22:28
Closing as duplicate of #957 (see comments)

**Closed by serge-rider** 2019-05-04 22:28 UTC
Labels: duplicate, feature request
