### ISSUE TITLE
crashing dbeaver after several hours of running refresh data every 1 second on multiple tables

### ISSUE THREAD

**Issue by l-771** [dbeaver/dbeaver#17030] opened 2022-07-08 14:36 UTC
#### System information: 
- windows 10 x64 - 00391-70000-00000-AA078
- DBeaver version - 22.1.1
- Additional extensions

#### Connection specification:
- Database name and version - mysql x64, 8.0.28
- Driver name odbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
when refreshing tables refresh every 1 seconds, dbeaver crashing
#### Steps to reproduce, if exist:
refresh tables every 1 seconds

**Comment by E1izabeth** [comment] 2022-07-08 14:39
Connected to https://github.com/dbeaver/dbeaver/issues/16793

**Comment by ShadelessFox** [comment] 2022-07-18 08:35
Duplicate of https://github.com/dbeaver/dbeaver/issues/16793

**Closed as not planned by ShadelessFox** 2022-07-18 08:35 UTC
Labels: duplicate
