### ISSUE TITLE
problem with ' (single quotation mark) in choose value by filter tab 

### ISSUE THREAD

**Issue by 0red** [dbeaver/dbeaver#8334] opened 2020-04-03 22:56 UTC
![single_quotation_datefield](https://user-images.githubusercontent.com/11916804/78410966-58396e80-760e-11ea-9102-3148d878e5ed.PNG)

I have the problem - the data contains i.e. value '2019-04-28'  (not 2019-04-28) and if I click the value from column drop down filter program generate field IN (''2019-04-28'') not ('''2019-04-28''') so the query fails to show the results. Btw query works with ' and ''' quoatation for both types of values.

Also maybe the issue is because of:
 1. this is the date field - so there should not be ' in front and at the end shown in grid
 2. the text results not shown ' between
 3. in the dropdown menu as well and in the grid there are both types of 'dates' with ' and without.
 4. this works correctly from execute select but fails when it's open in tab --> PostgrSQL->db->public->test0

Windows 10 Enterprise 
DBeaver SW ver. 7.0.1.202003211804 
db: PostgreSQL 10.6 on x86_64-pc-mingw64, compiled by gcc.exe (Rev5, Built by MSYS2 project) 4.9.2, 64-bit|

to recreate:

create table test0  (  field date);

insert into test0 values ('2021-03-17');
insert into test0 values ('2021-03-17');
insert into test0 values ('2021-03-17');
insert into test0 values ('2021-03-17');
insert into test0 values ('2021-03-17');
insert into test0 values ('2019-04-28');
insert into test0 values ('2021-03-17');

select * from test0; -- works

but open public.test0 in Database Navigator--> tab see attachment

Rg
Jacek

**Comment by uslss** [comment] 2020-04-04 15:35
seems to be duplicate of #8225 .
will be fixed in 7.0.2 version. btw, you could test if it works for you in EA version (https://dbeaver.io/files/ea/)
and thanks for the bug report :)

**Closed by uslss** 2020-04-04 15:35 UTC
Labels: bug, wait for review
