### ISSUE TITLE
Result cell value viewer (value panel) not working for JSON and enum

### ISSUE THREAD

**Issue by williamsp** [dbeaver/dbeaver#7390] opened 2019-12-09 03:47 UTC
#### System information: 
- Operating system (distribution) and version: Ubuntu 16.04 LTS
- DBeaver version: Version 6.3.0.201912011827
- Additional extensions: -

#### Connection specification:
- Database name and version: Postgres
- Driver name: Postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Result cell value viewer (value panel) not showing any text area for JSON and drop down for enum which can be edited

#### Steps to reproduce, if exist:
Select a cell with JSON or enum data type, and show the Value panel

#### Include any warning/errors/backtraces from the logs
**JSON**
eclipse.buildId=unknown
java.version=1.8.0_222
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

This is a continuation of log file /home/payfazz14/.local/share/.DBeaverData/workspace6/.metadata/.bak_0.log
Created Time: 2019-12-09 10:35:48.530

org.jkiss.dbeaver.model
Error
Mon Dec 09 10:44:34 WIB 2019
Can't determine object class 'org.jkiss.dbeaver.ui.data.managers.ContentValueManager'

**Enum**
eclipse.buildId=unknown
java.version=1.8.0_222
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

This is a continuation of log file /home/payfazz14/.local/share/.DBeaverData/workspace6/.metadata/.bak_0.log
Created Time: 2019-12-09 10:35:48.530

org.jkiss.dbeaver.model
Error
Mon Dec 09 10:43:37 WIB 2019
Can't determine object class 'org.jkiss.dbeaver.ext.postgresql.ui.config.PostgreEnumValueManager'

**Comment by williamsp** [comment] 2019-12-09 03:49
#### Screenshot:
![image](https://user-images.githubusercontent.com/3760416/70405926-754f9d80-1a71-11ea-8cbe-a018b7a2e59f.png)

**Comment by mathieudz** [comment] 2019-12-09 09:39
Same on Windows 10

**Comment by serge-rider** [comment] 2019-12-09 16:42
Duplicate of #7333
You can re-download 6.3.0 version from dbeaver.io - we have released hotfix version on the last week.

**Closed by serge-rider** 2019-12-09 16:42 UTC
Labels: bug, duplicate, x:postgresql
