### ISSUE TITLE
Update resets configured language

### ISSUE THREAD

**Issue by doerwalter** [dbeaver/dbeaver#18833] opened 2023-01-23 12:05 UTC
### Description

I'm running DBeaver on a german macOS, but have switched DBeaver's language to from German to English (under Preferences -> User Interface -> Language).

Every time I install a DBeaver update the language switched back to German.

### DBeaver Version

Community edition 22.3.3.202301211053

### Operating System

macOS Venture 13.1 (22C65)

**Comment by E1izabeth** [comment] 2023-01-23 12:09
Thank you for bug report. It's a duplicate of #17857

**Closed as not planned by E1izabeth** 2023-01-23 12:09 UTC
Labels: duplicate
