### ISSUE TITLE
Cannot open object statement in MSSQL

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#14390] opened 2021-10-26 00:27 UTC
#### System information: 
- win10 1809
- 21.2.3

#### Connection specification:
- MSSQL (2005,2008R2,2014)
- MICROSOFT JDBC DRIVER 8.2 FOR SQL SERVER
- NO

#### Steps to reproduce, if exist:
Cannot open object statement when use ctrl+Left mouse click or F4,but it's OK in previous version.
I must add the schema such as 'dbo'.object,then it's OK.
Can restore the previous version?

**Comment by LonwoLonwo** [comment] 2021-10-26 06:36
Hello @leezm 
Thanks for the bug report.
This is actually a duplicate of this ticket https://github.com/dbeaver/dbeaver/issues/14001
We will fix the problem in the next releases.

**Closed as completed by LonwoLonwo** 2021-10-26 06:36 UTC
Labels: duplicate
