### ISSUE TITLE
Changing the font size in the navigation tree

### ISSUE THREAD

**Issue by Essentia-G** [dbeaver/dbeaver#17433] opened 2022-08-23 12:46 UTC
We need to add a new setting to the User Interface -> Appearance -> Colors and Fonts to make it possible to change the font size only for the Database Navigator.

**Comment by E1izabeth** [comment] 2022-08-24 10:27
Probably it's a duplicate of https://github.com/dbeaver/dbeaver/issues/17253

**Comment by uslss** [comment] 2022-08-25 08:36
closed as a duplicate of #17253

**Closed as completed by uslss** 2022-08-25 08:36 UTC
Labels: duplicate
