### ISSUE TITLE
Unable to restore/backup 12.1 PostgreSQL database with Dbeaver default pg clients

### ISSUE THREAD

**Issue by LoganWlv** [dbeaver/dbeaver#8091] opened 2020-03-04 21:47 UTC
#### System information: 
- Operating system : Windows 10 Home
- DBeaver version : 7

#### Connection specification:
- Database PostgreSQL 12.1 (Debian 12.1-1 docker instance)
- Driver PostgreSQL JDBC Driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Nop

#### Describe the problem you're observing:
I can't not restore any PostgreSQL database above 12.1 because the default drivers used by Dbeaver are from 11.2

![image](https://user-images.githubusercontent.com/22358070/75925665-5e9ac600-5e69-11ea-94bc-809a800aff78.png)

#### Steps to reproduce, if exist:
1) Connect to a 12.1 postgresql database
2) Tools -> Restore -> Client... -> use "PostgreSQL Binaries" 
Then start restoration you'll get this postgreSQL error : 

_pg_restore: [archiver] unsupported version (1.14) in file header_

### Solution
Download the correct binaries from postgresSQL and add a new binaries home with the Client... button. 

But still, should not we expect PostgreSQL Binaries option to download up to date binaries ?

**Comment by uslss** [comment] 2020-03-05 09:42
seems to be duplicate of #8069 .
ticket will be closed. anyway, thanks for the bug report

**Closed by uslss** 2020-03-05 09:42 UTC
Labels: bug, wait for review
