### ISSUE TITLE
DBeaver Community 24.1.0 do not display table Constraints and Indexes (at least for Postgres and Oracle)

### ISSUE THREAD

**Issue by shtoormanSam** [dbeaver/dbeaver#34299] opened 2024-06-07 11:50 UTC
### Description

New update 24.1.0 crash text of table Constraints and Indexes, at least for Postgres and Oracle.
Previous version is OK.

https://github.com/dbeaver/dbeaver/assets/127952519/9e2a22cd-d7be-4d15-8bfe-ad2d0d153176

### DBeaver Version

Community 24.1.0

### Operating System

Win10

### Database and driver

Postgresql 13.8
PostgreSQL JDBC Driver

### Steps to reproduce

Shift+LeftButton Click on table name, select Indexes tab.
IndexesTab show pixel dust.

**Comment by E1izabeth** [comment] 2024-06-07 12:10
Thank you for bug report. Judging by the provided video, it's a duplicate of #34209
As a workaround, you can turn off darkest dark plugin.

**Closed as not planned by E1izabeth** 2024-06-07 12:10 UTC
Labels: duplicate, xf:dark theme
