### ISSUE TITLE
Postgres - Set Active Option is Gone

### ISSUE THREAD

**Issue by igormorse** [dbeaver/dbeaver#7703] opened 2020-01-20 21:15 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 
- DBeaver version: 6.3.3.202001191557

#### Connection specification:
- Postgres 11

#### Describe your question:

I updated from 6.0.3 and on this previous version ( Specifically for Postgres ) when you had a lot of Databases in one connection there was an option in right click context menu to **set active database** and that same option is gone in the 6.3.3 version.

There is another way of doing that ? Even when using the Hotkey Ctrl + Shift + A it says that `Internal error: active object change not supported`

Any tips ?

**Comment by serge-rider** [comment] 2020-01-20 22:27
Duplicate of #7693

**Closed by serge-rider** 2020-01-20 22:27 UTC
Labels: duplicate, question
