### ISSUE TITLE
Mysql dump 

### ISSUE THREAD

**Issue by simeds** [dbeaver/dbeaver#35446] opened 2024-09-03 09:08 UTC
### Description

My sql dump is verbose and report error after few seconds.

Dump report all the operation during the dump and when the file is big report this error: 
2024-09-03 11:04:49.732 - IO error: Process failed (exit code = 1). See error log.
2024-09-03 11:04:49.732 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
Task 'MySQL dump' finished at Tue Sep 03 11:04:49 CEST 2024
In the previos version works fine. 

### DBeaver Version

Community edition 24.02

**Comment by ShadelessFox** [comment] 2024-09-03 09:32
Hello @simeds,

Thanks for the bug report. This is a duplicate of #35421. Please track the progress on the issue there.

**Closed as not planned by ShadelessFox** 2024-09-03 09:32 UTC
Labels: x:mysql, duplicate, xf:native clients
