### ISSUE TITLE
Session Manager Shows an Incomplete List in ORACLE database

### ISSUE THREAD

**Issue by luiscarlosbolanhos** [dbeaver/dbeaver#10437] opened 2020-11-19 13:29 UTC
Since the version 7.2.4 until the lastest release 7.2.5, the session manager shows/loads an inclomplete list of the real sessions connected to the database in Oracle database., it shows the 10% of the real info, not the whole one. 

I have tested it from Oracle 11.2.0.4 Standad to 18c Enteprise, SAME RESULTS.

The problem reported is:

Plugin: org.jkiss.dbeaver.ext.oracle
Code: OracleServerSessionManager
Line: 84 ... or so

The outer join is missing
Wrong:
sql.append(" AND s.sql_child_number = sq.child_number");
Correct:
sql.append(" AND s.sql_child_number = sq.child_number (+)");

**Comment by luiscarlosbolanhos** [comment] 2020-11-19 20:43
Oracle: Only Sessions that execute SQL are shown #10413 --- is the same issue than :

https://github.com/dbeaver/dbeaver/issues/10413 

But needs to be corrected in the 7.2.5 version, is the same problem than the reported in 7.3.0!

**Comment by LonwoLonwo** [comment] 2020-11-20 08:59
Early versions do not always contain all changes, especially those unverified by testers. Most likely the changes will be included in one of the nearest EA and will definitely be in version 7.3.0 on November 30

**Comment by luiscarlosbolanhos** [comment] 2020-11-20 13:50
Thanks Anastasiya, very kind of you for the information! Very clear indeed. Best regards and wishes

**Comment by uslss** [comment] 2020-11-24 08:27
hi @luiscarlosbolanhos ,
fix is already included in EA :)

close this issue as a duplicate of #10413

**Closed by uslss** 2020-11-24 08:27 UTC
Labels: bug, duplicate, x:oracle
