### ISSUE TITLE
Checkboxes / bool values - improve visibility

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#10606] opened 2020-12-04 08:44 UTC
Im using verison 7.3 and noticed checkboxes changed to smaller, red squares - which is less visible then in past.
Is there any option to return to previous presentation 

**Currently:**

![obraz](https://user-images.githubusercontent.com/5410448/101141628-d96d5900-3614-11eb-8f00-245b5a3d44a5.png)

**Before:**

![obraz](https://user-images.githubusercontent.com/5410448/101141902-3537e200-3615-11eb-90c5-d908ef679b8c.png)

**Comment by uslss** [comment] 2020-12-07 15:55
thanks for the report.
Color for boolean type could be changed in preferences:
![image](https://user-images.githubusercontent.com/31996417/101373224-c5985000-38bd-11eb-941d-e65a60b6a309.png)

**Comment by maciey** [comment] 2020-12-08 10:37
It is better but still Id prefer previous (bolded version)

Ive tried setup different colours but still not ideal
![obraz](https://user-images.githubusercontent.com/5410448/101472918-7f88ce00-3949-11eb-96b3-4ec6442c5dcb.png)
![obraz](https://user-images.githubusercontent.com/5410448/101473004-98917f00-3949-11eb-97c7-29fdadbb7c89.png)

in previous versions:
![obraz](https://user-images.githubusercontent.com/5410448/101473144-bfe84c00-3949-11eb-8734-886617689da4.png)

**Comment by kseniiaguzeeva** [comment] 2020-12-09 11:04
Can have one implementation with https://github.com/dbeaver/dbeaver/issues/10645

**Comment by serge-rider** [comment] 2020-12-27 11:23
Duplicate of #10645

**Closed** 2020-12-27 11:23 UTC
Labels: duplicate, enhancement
