### ISSUE TITLE
There is no way to close the autocomplete popup without accepting on of the options

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#18662] opened 2023-01-05 00:24 UTC
### Description

If you trigger the autocomplete in the SQL Editor, you can only close it by accepting one of the suggestions. Clicking around the popup, using the Esc key, or something similar doesn't work. Also, the popup displays on top of any other app.

### DBeaver Version

DBeaver UE 22.3.1 devel

### Operating System

macOS 13.1

**Comment by E1izabeth** [comment] 2023-01-05 07:23
Duplicate of #18578

**Closed as not planned** 2023-01-06 12:43 UTC
Labels: duplicate, xf:sql, xf:ui

**Comment by EdVinyard** [comment] 2024-09-03 19:18
I don't think this was really a duplicate of #18578, since there are more comments over there about this _after_ it was fixed/closed.

Although the escape key makes much more sense to me, I'm able to close the auto-complete pop-up with the space key.  I'm (slowly) getting in the habit of hitting `SPACE` and then `BACKSPACE` when I want that window to go away.

**Comment by E1izabeth** [comment] 2024-09-04 09:58
Another issue about it #10088
