### ISSUE TITLE
SQLite driver missing since 7.1.0

### ISSUE THREAD

**Issue by mosesontheweb** [dbeaver/dbeaver#8895] opened 2020-06-04 12:16 UTC
#### System information: 
- Ubuntu Linux 18.04
- DBeaver version 7.1.0

#### Connection specification:
- Database name and version - some random SQLite DB
- Driver name - according to Dbeaver org.xerial:sqlite-jdbc:RELEASE
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Nope

#### Describe the problem you're observing:
I try to connect to a SQLite DB. As soon as I create the new connection, DBeaver somehow wants to download some drivers. The error message is:
```
Error resolving dependencies
  Maven artifact 'maven:/org.xerial:sqlite-jdbc:RELEASE' not found
```
Network connection is alright. It was working properly before in 7.0.x.

#### Include any warning/errors/backtraces from the logs

Error resolving dependencies
  Maven artifact 'maven:/org.xerial:sqlite-jdbc:RELEASE' not found
  Maven artifact 'maven:/org.xerial:sqlite-jdbc:RELEASE' not found

**Comment by uslss** [comment] 2020-06-04 15:35
hi @mosesontheweb , 
could you try to reset driver to default?
![image](https://user-images.githubusercontent.com/31996417/83777490-29815800-a692-11ea-8bac-20d748bf8e3b.png)

**Comment by mosesontheweb** [comment] 2020-06-04 19:24
Hi, well I did, but no success.
However, I was able to solve it that way, that I deleted this default entry, downloaded the corresponding SQLite JDBC driver from bitbucket and added the location to the libraries of this driver. This actually solved my issue for now, however, it is strange that the previous default entry wasn't working in 7.1.0, but versions before had no problems with that.
Regards, Thomas

**Comment by cindymeliyen** [comment] 2020-06-16 18:56
dBeaver version 7.1.0
macOS High Sierra version 10.13.6

I also have a similar problem trying to connect to a Redshift DB. I'm getting a "Maven Artifact not found" error, and the pop-up that prompts you to download the driver doesn't do anything. A co-worker with an earlier version of dBeaver was able to download the driver from the pop-up.

**Comment by uslss** [comment] 2020-07-06 12:02
@cindymeliyen this issue is resolved in scope of #9065 
@mosesontheweb still cannot reproduce the issue against the current version. If it is still actual for you - feel free to reopen the ticket

**Closed by uslss** 2020-07-06 12:02 UTC
Labels: bug, wait for response

**Comment by dasosjt** [comment] 2020-10-28 03:00
I had similar error with SQLite driver but my miss was that I am behind a vpn, maybe you are behind a firewall or there is proxy settings to set. I removed the vpn and it worked smoothly

**Comment by lleeoo** [comment] 2021-04-07 03:32
I was not on VPN, but did not realise that I was behind a proxy server. Paused it, everything worked fine, resumed it. Worth checking.

**Comment by LMM11231** [comment] 2022-04-10 07:18
> hi @mosesontheweb , could you try to reset driver to default? ![image](https://user-images.githubusercontent.com/31996417/83777490-29815800-a692-11ea-8bac-20d748bf8e3b.png)

Although I tried to reset the driver, the download progress bar also appeared, but the download failed again after a while, why is this?
![批注 2022-04-10 151313](https://user-images.githubusercontent.com/86695044/162607087-71015469-5a60-4787-a93e-882b782f5849.png)
