### ISSUE TITLE
CRASH WITH EXPLAIN ANALYZE ON POSTGRES 13.1

### ISSUE THREAD

**Issue by lucamanga** [dbeaver/dbeaver#11734] opened 2021-03-15 13:05 UTC
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04
- DBeaver version: 21.0.0

#### Connection specification:
- Database name and version: Postgres 13.1
- Driver name: the official one
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
When I do an EXPLAIN ANALYZE, dbeaver crashes badly

#### Steps to reproduce, if exist:
Simply execute a SQL query with EXPLAIN ANALYZE

#### Include any warning/errors/backtraces from the logs
```
2021-03-15 14:00:54.038 - Initiate connection to PostgreSQL database [base@11c81] for SQLEditor <Script-1.sql>
> Start DBeaver Data GIS - view [org.jkiss.dbeaver.data.gis.view 1.0.47.202102281712]
2021-03-15 14:01:00.438 - A grid has been found.
SWT WebKitGDBus: error creating DBus server Error binding to address: Permission denied
SWT WebKit: error initializing DBus server, dBusServer == 0
```

**Comment by lucamanga** [comment] 2021-03-15 13:06
Note: I'm using the snap version of DBeaver

**Comment by kseniiaguzeeva** [comment] 2021-03-23 10:29
Works correctly in Win10

**Comment by noschang** [comment] 2021-03-24 05:15
@lucamanga see https://github.com/dbeaver/dbeaver/issues/11855

**Comment by kseniiaguzeeva** [comment] 2021-03-25 08:18
Thank you for the report. I close the ticket as a duplicate of #11855 because it has more details.

**Comment by noschang** [comment] 2021-03-25 11:34
@kseniiaguzeeva I mentioned the issue #11855 here because maybe this is the problem that @lucamanga is facing. He didn't mention if he used the keyboard shortcut or wrote the query with ```explain analyze``` at the beginning.

So I'm not entirely sure if these bugs are related. Before marking it as a duplicate, I suggest that @lucamanga test disabling the emoji app to see if his problem is gone.

**Comment by kseniiaguzeeva** [comment] 2021-03-25 11:45
Thank you for pointing it out.

**Comment by uslss** [comment] 2021-07-22 19:29
cannot reproduce it against dbeaver 21.1.3. If it is still actual - feel free to reopen an issue.

**Closed as completed by uslss** 2021-07-22 19:29 UTC
Labels: xo:linux, xo:eclipse
