### ISSUE TITLE
Cant see/access the insert script

### ISSUE THREAD

**Issue by YV38** [dbeaver/dbeaver#9094] opened 2020-06-24 08:16 UTC
System information:
Ubuntu 20.04
7.1.1
None

Connection specification:
Oracle 12c 12.2.0.1.0
Oracle JDBC 12.2.0.1.0

Describe the problem you're observing:
Cant see/access the insert script anymore after a select script
I have downgraded to 7.0 and error is gone.

**Comment by kseniiaguzeeva** [comment] 2020-06-24 10:37
Hotfix was published yesterday. Please try download again 7.1.1. I can't reproduce the issue.

**Comment by YV38** [comment] 2020-06-24 22:59
Hello, I'm currently on 7.1.1 and I still have the bug. Before, I was able to see/access the insert script by using the rigth click on the result from a select request. This option was at the bottom of the menu (after the right click).

**Comment by kseniiaguzeeva** [comment] 2020-06-30 08:26
Please try EA version. https://dbeaver.io/files/ea/
I have INSERT in context menu of ResultSet. 
Please write whether it helps.
![dbeaver_jaYjsA1EEF](https://user-images.githubusercontent.com/51405061/86102736-94bd1f00-bac4-11ea-8a25-0fc7a443ffb0.png)

**Comment by uslss** [comment] 2020-07-06 11:30
Issue is already fixed. Closed as duplicate of #9060 .

**Closed by uslss** 2020-07-06 11:30 UTC
Labels: bug, can't reproduce, duplicate, wait for response
