### ISSUE TITLE
Using Space On Template

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#36343] opened 2024-11-24 19:22 UTC
Hi, Templates working great but can't we use space or tab together. Using space bar would be awesome. And using special chars like s* would be great.

Thanks

**Comment by E1izabeth** [comment] 2024-11-25 12:17
Thanks for the feature request.
I'm closing it as a duplicate of #11553

**Closed as not planned by E1izabeth** 2024-11-25 12:17 UTC
Labels: xf:sql
