### ISSUE TITLE
Columns not sorting

### ISSUE THREAD

**Issue by mustafasacli** [dbeaver/dbeaver#18775] opened 2023-01-16 08:58 UTC
At Result set or table tab. Record button working but record columns could not be sorted. In Previous versions, i could sort columns. Is there any setting for this sorting?

**Comment by E1izabeth** [comment] 2023-01-17 00:52
Thank you for bug report. It's a duplicate of https://github.com/dbeaver/dbeaver/issues/18618
The fix will be available in the next release.

**Closed as not planned by E1izabeth** 2023-01-17 00:52 UTC
Labels: duplicate, xf:data
