### ISSUE TITLE
Content assist in data editor filter field works only for the first word

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14721] opened 2021-11-29 12:44 UTC
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.0

#### Describe the problem you're observing:
If content assist is called in blank filter field it will propose column names and keywords like 'or', 'and', 'not', 'is' which are uselees at the start of the filter. But if first word is already entered the content assist won't propose anything

#### Steps to reproduce, if exist:
1. Open a table in data editor
2. Type an expression in filter field e.g. `id <> 5 and`
3. Press <kbd>Ctrl + Space</kbd>

**Expected:** Column names are proposed
**Actual:** Nothing happens

**Comment by serge-rider** [comment] 2021-12-06 09:16
Duplicate of #12718

**Closed as completed by serge-rider** 2021-12-06 09:16 UTC
Labels: duplicate, xf:data
