### ISSUE TITLE
Apache Hive - Cannot start a query with a comment

### ISSUE THREAD

**Issue by mtdeguzis** [dbeaver/dbeaver#3363] opened 2018-04-19 14:48 UTC
Verified this works in hive/beeline (CLI). I am use ALT+X / Execute Query.  Highlighting the entire block and using Execute Query (CTRL + ENTER) does not work.

![image](https://user-images.githubusercontent.com/27829577/38998103-deade6fc-43bc-11e8-8fc6-639c06043315.png)

![image](https://user-images.githubusercontent.com/27829577/38998123-e5c85e22-43bc-11e8-8234-97528786126e.png)

```
Error while compiling statement: FAILED: ParseException line 2:0 cannot recognize input near 'set' 'hive' '.' in statement
  Error while compiling statement: FAILED: ParseException line 2:0 cannot recognize input near 'set' 'hive' '.' in statement
    org.apache.hadoop.hive.ql.parse.ParseException:line 2:0 cannot recognize input near 'set' 'hive' '.' in statement
    org.apache.hadoop.hive.ql.parse.ParseException:line 2:0 cannot recognize input near 'set' 'hive' '.' in statement
```

Does not work
```
--Comment
set hive.auto.convert.join=false;
```

Works:
```
set hive.auto.convert.join=false;
--Comment
```

**Comment by serge-rider** [comment] 2018-04-22 14:09
Are you on Windows?
Try to convert line feeds to unix style (main menu file->Convert Line Delimiters To->Unix).

**Comment by serge-rider** [comment] 2018-04-26 06:35
No, I didn't yet reproduce that yet. Don't have live Hive instance at the moment.
Will try on the next week.

**Comment by mtdeguzis** [comment] 2018-05-31 19:32
Hi, any update?

**Comment by serge-rider** [comment] 2018-05-31 20:01
No, I wasn't able to reproduce. What Hive client version do you use? 
Did you try any other version?

**Comment by djmartin4** [comment] 2018-06-01 17:34
Hive 1.2.1

**Comment by mtdeguzis** [comment] 2018-06-01 17:35
We use hive 1.2.1, but also have Hive 2.1 available. So both

**Comment by serge-rider** [comment] 2018-08-16 19:04
Please try with new Hive driver (uber jar), it was changed in DBeaver 5.1.5.
I can't reproduce this problem with Hive 1.2.1 and new driver.

**Comment by djmartin4** [comment] 2018-08-20 11:42
Thanks for the info. I'll try 5.1.5 when I can get it installed on my computer.

**Comment by serge-rider** [comment] 2018-08-26 17:14
Closing. If this problem will appear in 5.1.6 - please reopen.

**Closed by serge-rider** 2018-08-26 17:14 UTC
Labels: bug
