### ISSUE TITLE
Unable to Export Multiple Query as Highlight Multiple Query Gets Removed On Right Click

### ISSUE THREAD

**Issue by endy-imam** [dbeaver/dbeaver#18215] opened 2022-11-14 17:08 UTC
### Description

This feature where I can export CSV files from multiple queries had been working for a long while where I click and hold to highlight all the queries I want to run in order to output files per query by [Execute] > [Export From Query] from right-click menu.

All of a sudden as of last week, whenever I try to right-click after highlighting all of the queries I want to run, it removes all the highlighting and thus when running [Export From Query], it only runs the one query where the text cursor is on instead of running all of the selected queries.

Is there some settings that I may or may not have set that caused it to change this behavior all of the sudden? Is there other ways to run and export multiple queries to files?

### DBeaver Version

22.2.4

### Operating System

Windows 10 Enterprise, v. 21H2

### Database and driver

I don't think this is specifically related to the database and rather related to the DBeaver Client.

### Steps to reproduce

Assuming you already connected to a database and written a couple of SQL queries:

1. Highlight all of the SQL queries you want to run in the text editor.
2. Right click in the text editor.

Originally, the highlight should still be around as you go to [Execute] > [Export From Query], but now the highlight is gone upon right-click.

**Comment by E1izabeth** [comment] 2022-11-14 17:22
Thank you for bug report. It's a duplicate of https://github.com/dbeaver/dbeaver/issues/18152
Fix will be available in the next release.

**Closed as not planned by E1izabeth** 2022-11-14 17:22 UTC
Labels: duplicate
