### ISSUE TITLE
advanced copy of output creates duplication & omissions

### ISSUE THREAD

**Issue by gqbsong** [dbeaver/dbeaver#3483] opened 2018-05-16 19:13 UTC
Repro steps
-query distinct ID's from table. 
-use 'fetch all rows' command
-select all & right click -> advanced copy
-options (copy header, quote cell values, value format = display/editable, column delimiter = \t, row delimiter: \n, quote character = " )
-paste into excel, use remove duplicates command

I am a fan of the software. Let me know if you need anymore information on this.

**Comment by serge-rider** [comment] 2018-05-20 15:31
I can't reproduce this. 
* Do you see what exactly rows are duplicated? 
* Do you see them in DBeaver grid?
* Is there anything special about them?

**Comment by gqbsong** [comment] 2018-05-21 21:07
- I can see the rows that are duplicated in the dbeaver output grid.
- There is nothing special about the rows that are being duplicated from what I can tell.

My use case is I'm finding all unique ID's that fit a certain criteria. This is the query:

SELECT DISTINCT
    player_id
FROM
    table1
WHERE
    match_id IN
    (
        	SELECT 
        		match_id
        	FROM table 2
        	WHERE 
        		mode_id = 1
        		AND number_participants >= 30
        		AND timestamp BETWEEN '2018-05-11 10:00:00' AND '2018-05-14 10:00:00'
    )
    AND RANK = 1

**Comment by serge-rider** [comment] 2018-05-23 19:58
So this ticket is not about advanced copy but about fetched rows.

- What is your database?
- What rows are duplicated? Could you post a screenshot?

**Comment by GiannisDem** [comment] 2018-06-01 08:28
Hi @serge-rider 
Im experiencing the same issue with fetch all rows for a query similar with the one posted above by @gqbsong .

What i noticed are the following:

- The query fetches the correct number of rows but in the process it seems like the data of a row is overwritten by another row.

- Using 'order by' on the outer query seems to solve the issue

- Also 'Export from query' into csv solves the issue as well

- The first 200 rows in the output grid are always correct

- The duplicate rows are random

Results sorted by natural_key on output grid after fetching all rows:
![image](https://user-images.githubusercontent.com/25582863/40830263-a0dc8fd8-658e-11e8-81c8-75fe34f9fa15.png)


Results after exporting query from csv: 
![image](https://user-images.githubusercontent.com/25582863/40830298-b08ae858-658e-11e8-9427-73eda3f6e139.png)

Database: Postgres 9.4

**Comment by uslss** [comment] 2019-10-03 11:11
Ticket is closed.
Fixed in scope #2416

**Closed by uslss** 2019-10-03 11:11 UTC
Labels: can't reproduce, question
