### ISSUE TITLE
SQL Server Table column size is changed  after add table column ('nvarchar')

### ISSUE THREAD

**Issue by Tylor-77** [dbeaver/dbeaver#17066] opened 2022-07-13 06:12 UTC
#### System information: 
- **Windows 10 home edition**
- **DBeaver version 22.1.2**
- Additional extensions

#### Connection specification:
- Database name and version :  **SQL Server**
- Driver name : **MS SQL Server**
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  **No**

#### Describe the problem you're observing:
**When Table Column Type is "nvarchar " , 
after Add Column ,
Column Size is cha
![DBeaver_bug_ColumnSize](https://user-images.githubusercontent.com/109200561/178663197-3130b532-961d-4eed-9cce-1cbe43907d47.png)
nged**

**Comment by E1izabeth** [comment] 2022-07-13 12:27
Hello, @Tylor-77! Please, send the screenshot with sever and driver information.
![image](https://user-images.githubusercontent.com/28875055/178733155-2401745d-f3b5-433d-8cb5-bd773c5dfc55.png)

**Comment by Tylor-77** [comment] 2022-07-14 12:03
![DBeaver_bug_ColumnSize2](https://user-images.githubusercontent.com/109200561/178978042-a69df442-1149-4a16-88d2-b1557d097c97.png)

Hi ! 
my information is here.

**Comment by heliocj** [comment] 2022-07-14 13:19
Hi there !

Here we're getting the same issue with nvarchar columns. Every change we tried to make, the size of all nvarchar columns just changed to mid of the last size. If we make 5 changes, the size just change to 0. We got lots of problems on our production database :(

And there is an issue with the lenght of columns too. If we create the column with nvarchar(150) for example, that show column with lenght 75. That's causing lots of confusion at the team.

Our version is:
![image](https://user-images.githubusercontent.com/69656528/178991734-de38a723-c1e2-43a1-a9a6-76055f4e8d26.png)

![image](https://user-images.githubusercontent.com/69656528/178992156-2e77a695-c399-4e4c-a02c-4e9b5346bfe6.png)

**Comment by heliocj** [comment] 2022-07-16 16:36
The issue stil even after that latest update.

![image](https://user-images.githubusercontent.com/69656528/179363920-09d75211-d3af-45f3-9e45-627ff6a4ba7e.png)

**Comment by antoniustefan** [comment] 2022-07-17 21:37
The bug seems to occur only on the database that is currently default, regardless if it's set on the connection or it is changed after connecting

You can try to reproduce as follows:
1. open a connection and make sure that master is selected as default
2. use the database navigator to expand the column definition of a table from the affected database. Columns with nvarchar will be shown with correct length.
![image](https://user-images.githubusercontent.com/7008135/179425477-64767fce-f7d6-44cc-908d-1a52f5e69b26.png)

4. right click on the affected database and select "Set as default"
5. right click and refresh the column definition of the table from point 2 above. You will now see all nvarchar columns displayed with half their actual length.
![image](https://user-images.githubusercontent.com/7008135/179425490-4c02d451-6932-437f-9f52-9782b0c5f67c.png)

**Comment by heliocj** [comment] 2022-07-17 23:10
I have tested those steps that sugested by @antoniustefan and that confirmed.

But even with that, if we tried to get the script from DDL that generated with half of size of the columns.

**Comment by LonwoLonwo** [comment] 2022-08-04 07:44
Closed as duplicate of #16996

**Closed as not planned by LonwoLonwo** 2022-08-04 07:44 UTC
Labels: x:mssql, xf:metadata
