### ISSUE TITLE
The SQL section disappears on hover on the toolbar.

### ISSUE THREAD

**Issue by lexx-edu** [dbeaver/dbeaver#19642] opened 2023-04-08 11:16 UTC
### Description

The SQL section disappears on hover on the toolbar.

Completely removed and reinstalled DBeaver (including ~/Library/DBeaverData)

https://user-images.githubusercontent.com/104719330/230718054-a2d7cff6-e5ac-45f7-833c-5e19d159bec2.mov

### DBeaver Version

23.0.1

### Operating System

MacBook Pro M1 macOS Ventura 13.2.1

### Database and driver

Without drivers to

**Comment by E1izabeth** [comment] 2023-04-08 11:18
Thank you for bug report. It's a duplicate of #19495
The fix will be available in the next release.

**Closed as not planned by E1izabeth** 2023-04-08 11:18 UTC
Labels: duplicate, xo:macos
