### ISSUE TITLE
Dark theme issue on Mac

### ISSUE THREAD

**Issue by mnt1979** [dbeaver/dbeaver#8151] opened 2020-03-10 19:39 UTC
I am having dark theme issue on macbook pro with almost all versions, currently I am using 7.0.0.   As soon as any popup window opens, result grid acts weird and hard to read.

![image](https://user-images.githubusercontent.com/40701061/76352336-ddb25300-62dc-11ea-9ae9-1f7909ff5306.png)

**Comment by mnt1979** [comment] 2020-10-22 16:44
What is the status of this defect?   is it prioritized?   I am still having same issue in 7.2.3 version.

**Comment by dmetzler1988** [comment] 2021-02-22 09:08
I also have an issue with dark theme (Community Edition - Version 7.3.5.202102151746).

On my dark theme only the Info/Warning popups is white and can't be read.  
![image](https://user-images.githubusercontent.com/8446518/108686372-9cb74c80-74f5-11eb-8e8c-89630bfc5cc7.png)


@mnt1979 
This issue you have does not occur on my machine with the current version.

**Comment by serge-rider** [comment] 2021-03-13 19:36
Duplicate of #10841

Will be fixed in 21.0.1

**Closed by serge-rider** 2021-03-13 19:36 UTC
Labels: bug, duplicate, xo:macos

**Comment by gilshimer** [comment] 2021-10-28 17:34
Issue still exist in Community 21.2.3
