### ISSUE TITLE
Pinned result tab gets overwritten when no unpinned is left

### ISSUE THREAD

**Issue by n8falke** [dbeaver/dbeaver#35238] opened 2024-08-16 12:32 UTC
I expect a pinned result to be kept and not overwritten.

Is it possible to create a new result tab when all tabs are pinned?

Execute a query, pin the result and execute a second one which overwrites the result. Same with multiple pinned results. The active tab is overwritten.

After running a complicated long running query pinning the result is an intuitive way to keep the result and continue in other tabs with detail queries. Running the next query in a new tab works too, but you have the think about that in the moment of execution.

**Comment by E1izabeth** [comment] 2024-08-16 12:38
Thank you for bug report.
I'm closing it as it's a duplicate of #35072

You can try Early Access version with fix (https://dbeaver.io/files/ea/) or wait for the next release

**Closed as completed by E1izabeth** 2024-08-16 12:38 UTC
Labels: duplicate, xf:sql execution

**Comment by n8falke** [comment] 2024-08-16 12:41
Sorry, searched only in open issues. Should have searched in closed as well. Thanks.
