### ISSUE TITLE
When the version is upgraded, the previously installed Office integration plug-in needs to be reinstalled

### ISSUE THREAD

**Issue by suningya123** [dbeaver/dbeaver#36476] opened 2024-12-06 01:25 UTC
### Description

When the version is upgraded, the previously installed Office integration plug-in needs to be reinstalled

### DBeaver Version

community24.3.0

**Comment by E1izabeth** [comment] 2024-12-06 14:34
Thanks for the request.
I'm closing it as it's a duplicate of #5317

**Closed as not planned by E1izabeth** 2024-12-06 14:34 UTC
Labels: duplicate, xf:packaging
