### ISSUE TITLE
Wrong Launcher in dbeaver.ini after update

### ISSUE THREAD

**Issue by lukasza67** [dbeaver/dbeaver#17085] opened 2022-07-14 11:49 UTC
#### System information: 
- Operating system: Debian GNU/Linux 11 (bullseye) x86_64
- DBeaver version: Version 22.1.2.202207091909
- Java version:  Jre 11.0.12 (dbeaver bundle)
- Additional extensions: -

#### Connection specification:
- Database name and version: -
- Driver name: -
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : -

#### Describe the problem you're observing:

After the OS software update (APT) was made, the main launcher was unable to launch the application.

![image](https://user-images.githubusercontent.com/25504901/178975473-094c0655-b723-4852-85d0-06cc301f8669.png)

It looks like: _plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20211117-0650_ was not updated into: _plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.500.v20220509-0833_ in the file: **_dbeaver.ini_** under param: _--launcher.library_.

#### Steps to reproduce, if exist:

Solved according to description above.

**Comment by uslss** [comment] 2022-07-14 12:08
thanks for the report.
closed as a duplicate of #17048

**Closed as completed by uslss** 2022-07-14 12:08 UTC
Labels: duplicate, xo:linux
