### ISSUE TITLE
 HIVE executes scripts to report errors

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6456] opened 2019-08-06 08:20 UTC
In different Windows to execute different script directly error, stop execution, if a single execution script, execution, and then execute another window script, normal execution, hope can be executed in different Windows, no need to wait!thank you1q

https://github.com/dbeaver/dbeaver/issues/6449#issue-477119515

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment] 2019-08-06 10:20
Seems to be a duplicate of #6449

**Closed by serge-rider** 2019-08-06 10:20 UTC
Labels: duplicate, question, x:hive
