### ISSUE TITLE
Transactions in databade "XXX" will be enbed 

### ISSUE THREAD

**Issue by AlFreitasP7** [dbeaver/dbeaver#22730] opened 2024-02-06 17:32 UTC
### Description

When executing any transaction in the database (select, update, insert) the message is immediately displayed:
Transactions in databade "Oracle" will be enbed because of the long idle period. Press cancel to prevent this.

### DBeaver Version

Community Edition Versão 23.3.4.202402041841

### Operating System

Windows 10

### Database and driver

1 - Oracle  Database 12C
2 - Oracle Database 19C

### Steps to reproduce

1 - Connect to the database
2 - I perform a common select
3 - Press the Execute Instruction button
4 - Presents the result
5 - Open the End Transaction screen
![ScreenShot652](https://github.com/dbeaver/dbeaver/assets/159175628/ac0e57c4-ca40-47f0-a3ed-e3562c3a959f)

**Comment by doerwalter** [comment] 2024-02-06 17:44
That happens for me too. The dialog pops up every three seconds or so.

**Comment by zar-advancepact** [comment] 2024-02-07 04:03
I am having the same issue after updated to DBeaver 23.3.4

**Comment by mjogo** [comment] 2024-02-07 06:50
For me too with MySQL and DBeaver 23.3.4. No issue with prior DBeaver version 23.3.3.
It doesn't matter if config setting "Close idle connection after (secs)" is set to "0" (default) or "3600". Above message comes up after three seconds when running a select statement.

**Comment by uslss** [comment] 2024-02-07 11:25
thanks for the report
seems it is duplicate of #22709

**Comment by NorbertSandor** [comment] 2024-02-09 13:45
With Postgres too :(

**Comment by E1izabeth** [comment] 2024-02-14 12:30
The issue was solved and the fix is available in the Early access version https://dbeaver.io/download/ea and next release on Monday.

**Closed as not planned by E1izabeth** 2024-02-14 12:30 UTC
Labels: duplicate, xf:connection
