### ISSUE TITLE
Keep Language Settings un Updates

### ISSUE THREAD

**Issue by marsalcher** [dbeaver/dbeaver#19387] opened 2023-03-16 09:28 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marsalcher** [comment] 2023-03-16 09:30
If you are serving an update, youre always using the system language als default settings.
Keep the setting of the old version, its anoing to set english everry time on an german setting every time an updates arrives

**Comment by E1izabeth** [comment] 2023-03-16 09:31
Thank you for bug report.
It's a known issue. Closing as a duplicate of #17857 or #12771

**Closed as not planned by E1izabeth** 2023-03-16 09:31 UTC
Labels: duplicate, xo:eclipse, third party issue
