### ISSUE TITLE
Add JSON viewer to value viewer

### ISSUE THREAD

**Issue by jkeruzec** [dbeaver/dbeaver#5238] opened 2019-02-08 09:14 UTC
I have added some JSON fields using PostgreSQL 10.
When I want to visualize value of my JSON field, it gives me only plain text.

Maybe, it could be cool to have a nice JSON viewer with formatted data on this view.

Example : 
![image](https://user-images.githubusercontent.com/3499632/52468751-e8eef880-2b89-11e9-9368-300ea8c992ec.png)

What we could have : 
![image](https://user-images.githubusercontent.com/3499632/52468870-3b301980-2b8a-11e9-9d78-fc61ea0d1851.png)

Thanks !

**Comment by serge-rider** [comment] 2019-02-12 19:50
Duplicate of #2944

**Closed by serge-rider** 2019-02-12 19:50 UTC
Labels: duplicate, feature request
