### ISSUE TITLE
Declaring and setting variables will return Bind Parameters prompt

### ISSUE THREAD

**Issue by IonutR2019** [dbeaver/dbeaver#5700] opened 2019-04-11 09:07 UTC
#### System information: 
- Operating system (distribution) and version: MacOS Mojave 10.14.4 (18E226)
- DBeaver version 6.0.2
- Java version Version 8 update 201 (build 1.8.0_201-b09)
- Additional extensions n/a

#### Connection specification:
- Database name and version MySQL
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When attempting to DECLARE variables to query various tables by calling the said declared variable will return a "Bind Parameters" prompt.
#### Steps to reproduce, if exist:
1. Declare a variable. @variable varchart (50)
2.Set @variable = '123'
3. Select * from table where datapoint = @variable.
4. Notice that the Bind Parameters prompt is displayed and further querying cannot be performed.

#### Include any warning/errors/backtraces from the logs
No errors returned.

![Screenshot 2019-04-11 at 11 53 11](https://user-images.githubusercontent.com/49515817/55944874-3b17cd00-5c52-11e9-8b1e-5f6fc2fce1e2.png)

**Comment by serge-rider** [comment] 2019-04-11 09:14
Duplicate of #5674 . It is already fixed, you can check it in Early Access version (https://dbeaver.io/files/ea)

**Closed by serge-rider** 2019-04-11 09:14 UTC
Labels: bug, duplicate, x:mssql
