### ISSUE TITLE
Autocompletion popup gets stuck

### ISSUE THREAD

**Issue by ufuk-ergin-carbon** [dbeaver/dbeaver#21324] opened 2023-09-26 09:13 UTC
### Description

Autocompletion pop window does not go away and the suggestions are inconsistent. I attach the screen recording.

### DBeaver Version

Version 23.2.1.202309250303

### Operating System

MacOS Ventura 13.5.2

### Database and driver

Database name and version: Snowflake 7.33.1
Driver name and version: Snowflake 3.13.30

### Steps to reproduce

Try to insert table names and you'll see that the pop up window gets stuck and does not go away, even if you switch to other programs like Chrome.

https://github.com/dbeaver/dbeaver/assets/114302087/b70b6d38-86b5-4ec2-8085-4c4b69165733

https://github.com/dbeaver/dbeaver/assets/114302087/4915429e-572f-490f-a011-ffc2e89305da

**Comment by E1izabeth** [comment] 2023-09-26 11:29
Thank you for bug report and detailed videos with explanation.
We already have an issue about it, so I'm closing this one as a duplicate of #19977

**Closed as not planned by E1izabeth** 2023-09-26 11:29 UTC
Labels: duplicate, xf:ui, xf:sql editor
