### ISSUE TITLE
How to make dbeaver reconnect automatically (or not disconnect in the first place)

### ISSUE THREAD

**Issue by happysailingdude** [dbeaver/dbeaver#2718] opened 2018-01-02 15:59 UTC
We connect to mysql on our server using Dbeaver - I love the app etc except one thing, if I leave the app for a bit and then execute a query I get this error:

> Communications link failure
> 
> The last packet successfully received from the server was 3,990,735 milliseconds ago.  The last packet sent successfully to the server was 18,160 milliseconds ago.
>   Operation timed out
>   Operation timed out

Is there a way to make dbeaver reconnect automatically or not disconnect in the first place?

Thanks in advance

**Comment by benyanke** [comment] 2018-01-07 17:58
I don't have permission to do it myself, but this is a duplicate of #2201, propose to close it.

**Comment by happysailingdude** [comment] 2018-01-07 18:22
2201 says his ip changes / internet connection drops. That isn't the case with my issue.

**Comment by benyanke** [comment] 2018-01-08 16:38
Connections can drop for a variety of reasons, but the solution required is still the same.

An app should try a silent auto-reconnect whenever a connection is lost before alerting the user.

**Comment by serge-rider** [comment] 2018-01-09 21:23
Duplicate of #2201

**Closed by serge-rider** 2018-01-09 21:23 UTC
Labels: duplicate, feature request
