### ISSUE TITLE
File not saved when saving SQL console

### ISSUE THREAD

**Issue by mibrunet** [dbeaver/dbeaver#21413] opened 2023-10-03 13:30 UTC
### Description

Script lost when trying to save the file. As soon as the file is saved the script goes blank and is unrecoverable.

If you can't save a console script, please remove the "Save as" option when you right-click the script console tab.

### DBeaver Version

23.2.0.202309041200

### Operating System

Microsoft Windows 11 Enterprise

### Database and driver

DB2 for LUW

### Steps to reproduce

1. Open a new SQL console
2. Work in the console, write some scripts..
3. Decide your work is valuable and worthy of being saved
4. Right-click on the Script (SQL console) tab and select "Save as"
5. Write in the file name to save your work
6. Click "save"
7. Observe your work disappear.

**Comment by ShadelessFox** [comment] 2023-10-03 13:54
Hello @mibrunet,

This issue was fixed in 23.2.1 (#20994). Can you please upgrade to the newest version to see if the issue is gone there?

https://dbeaver.io/download/

**Comment by E1izabeth** [comment] 2023-10-30 11:10
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Closed as completed by E1izabeth** 2023-10-30 11:10 UTC
Labels: can't reproduce, wait for response
