### ISSUE TITLE
Generated DDL for tables does not correspond to how they were actually created

### ISSUE THREAD

**Issue by aledmb** [dbeaver/dbeaver#6510] opened 2019-08-13 10:42 UTC
#### System information: 
- Windows 10 Pro
- DBeaver 6.1.4
- No additional extensions

#### Connection specification:
- PostgreSQL 9.6

#### Describe the problem you're observing:
I'm using PostgreSQL and I built my tables using DBeaver's interface.

To generate values for the "id" column, I created a sequence and I set the default value of that column to call the nextval() function, so the sequence advances and I don't have to manually generate the values.

As you can see in attachment 1.jpg, when looking at the table properties, everything is correct for the "id" column.

But when I ask DBeaver to generate the DDL for the table (attachment 2.jpg), it generates the "id" column as a serial and there's no default value configuration in the generated script (attachment 3.jpg).

![1](https://user-images.githubusercontent.com/5561899/62935563-d5715400-bd9d-11e9-8827-d21ce2e28c86.jpg)
![2](https://user-images.githubusercontent.com/5561899/62935564-d5715400-bd9d-11e9-8011-13913a1761bf.jpg)
![3](https://user-images.githubusercontent.com/5561899/62935566-d5715400-bd9d-11e9-924a-80b577fdd8d3.jpg)

**Comment by uslss** [comment] 2021-04-20 11:40
seems the issue is fixed in 21.0.3

**Closed by uslss** 2021-04-20 11:40 UTC
Labels: bug, x:postgresql, xf:metadata
