### ISSUE TITLE
ER diagram does not showing references from parent to child table if they in different schemas

### ISSUE THREAD

**Issue by shurarama** [dbeaver/dbeaver#22501] opened 2024-01-18 12:39 UTC
### Description

ER diagram does not showing references from parent to child table if they in different schemas, but if open diagram for child table it successful show reference to parent table 

![image](https://github.com/dbeaver/dbeaver/assets/92807911/1e5961cf-2023-46aa-b79a-fd16e0540e87)
![image](https://github.com/dbeaver/dbeaver/assets/92807911/bb723d6c-ba12-46ca-9580-ecc9e9edbb41)

### DBeaver Version

community edition 23.3.1

### Operating System

manjaro os

### Database and driver

Oracle database with ojdbc11 driver

### Steps to reproduce

create two schemas, tables in each of them and add constraint from one to another : 
```
create user sch1;
grant all privileges to sch1;
create user sch2;
grant all privileges to sch2;

CREATE TABLE sch1.parent (id int PRIMARY KEY, name varchar(14));
CREATE TABLE sch2.childr
(
	id int PRIMARY KEY, 
	name varchar(14), 
	parentid int
);
grant references on sch2.childr to sch1;
grant references on sch1.parent to sch2;
ALTER TABLE sch2.childr ADD CONSTRAINT fk_chld_to_prnt FOREIGN KEY (parentid) REFERENCES sch1.parent(id);
```

**Comment by iraidaa** [comment] 2024-01-25 11:24
I reproduce the issue with the steps above on Windows 10 using Oracle 12.2 EE:

![image](https://github.com/dbeaver/dbeaver/assets/49681450/c7d748b7-9396-4973-8854-8228978dcf77)

![image](https://github.com/dbeaver/dbeaver/assets/49681450/b69f7ce6-4557-4904-9c1e-7c130587721b)

**Comment by LonwoLonwo** [comment] 2024-01-30 09:31
Thanks for the report.

Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/5637

**Closed as not planned by LonwoLonwo** 2024-01-30 09:31 UTC
Labels: duplicate, xf:erd
