### ISSUE TITLE
Can't open resource 'Script.sql'  

### ISSUE THREAD

**Issue by zhouqing-inovance** [dbeaver/dbeaver#13894] opened 2021-09-14 02:40 UTC
#### System information: 
- win10 X64
- 版本21.2.0.202108310918

#### Describe the problem you're observing:
Can't open resource 'Script.sql'
原因：
 -951788399

#### Include any warning/errors/backtraces from the logs

This is a continuation of log file C:\Users\inovance\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2020-11-26 10:29:33.230

!ENTRY org.jkiss.dbeaver.model 4 0 2020-11-26 10:29:33.230
!MESSAGE -917708255
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-11-26 10:29:33.230
!MESSAGE -917708255
!STACK 0
java.lang.NegativeArraySizeException: -917708255
	at org.eclipse.swt.program.Program.getKeyValue(Program.java:165)
	at org.eclipse.swt.program.Program.getProgram(Program.java:197)
	at org.eclipse.swt.program.Program.getPrograms(Program.java:230)
	at org.eclipse.ui.internal.registry.EditorRegistry.getSortedEditorsFromOS(EditorRegistry.java:463)
	at org.eclipse.ui.internal.registry.EditorRegistry.addExternalEditorsToEditorMap(EditorRegistry.java:303)
	at org.eclipse.ui.internal.registry.EditorRegistry.initializeFromStorage(EditorRegistry.java:579)
	at org.eclipse.ui.internal.registry.EditorRegistry.<init>(EditorRegistry.java:184)
	at org.eclipse.ui.internal.WorkbenchPlugin$15.compute(WorkbenchPlugin.java:1365)
	at org.eclipse.e4.core.internal.contexts.ValueComputation.get(ValueComputation.java:70)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.internalGet(EclipseContext.java:271)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.get(EclipseContext.java:237)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.get(EclipseContext.java:608)
	at org.eclipse.ui.internal.WorkbenchPlugin.getEditorRegistry(WorkbenchPlugin.java:463)
	at org.eclipse.ui.internal.Workbench.getEditorRegistry(Workbench.java:1533)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3133)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3100)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3068)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3051)
	at org.jkiss.dbeaver.ui.editors.sql.scripts.ScriptsHandlerImpl.openResource(ScriptsHandlerImpl.java:106)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenEditor.openResource(SQLEditorHandlerOpenEditor.java:75)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenEditor.openResourceEditor(SQLEditorHandlerOpenEditor.java:84)
	at org.jkiss.dbeaver.ui.controls.ScriptSelectorPanel$6.widgetDefaultSelected(ScriptSelectorPanel.java:290)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.dialogs.AbstractPopupPanel.open(AbstractPopupPanel.java:86)
	at org.jkiss.dbeaver.ui.controls.ScriptSelectorPanel.showTree(ScriptSelectorPanel.java:346)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenEditor.openEditor(SQLEditorHandlerOpenEditor.java:130)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenEditor.execute(SQLEditorHandlerOpenEditor.java:98)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:235)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)

**Comment by uslss** [comment] 2021-09-14 07:32
@zhouqing-inovance could you provide steps to reproduce? video could be helpful for issue investigation.

**Comment by straklhl** [comment] 2021-09-14 07:46
@uslss FYI
https://user-images.githubusercontent.com/90668017/133216776-9ed94486-5420-489c-99b9-826a1c44d418.mp4

**Comment by uslss** [comment] 2021-09-14 07:56
@straklhl unfortunately, still cannot reproduce. Is it actual for all script files or for some special only?

**Comment by straklhl** [comment] 2021-09-14 08:08
All "open script" and "new script" oprations prompt this error (it just happened today , last week DBeaver was nomal).

I have reinstalled DBeaver and restarted my PC but it can't solve this problem.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dbeaver/dbeaver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dbeaver/dbeaver] Can't open resource 'Script.sql'   (#13894)





 
@straklhl unfortunately, still cannot reproduce. Is it actual for all script files or for some special only?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShadelessFox** [comment] 2021-09-14 09:37
Hello @straklhl,

What application is associated with `.sql` extension in your OS?

**Comment by serge-rider** [comment] 2021-09-14 09:39
Also please check preferences. It should look like this:
![image](https://user-images.githubusercontent.com/6398845/133234172-77c0c8fa-dc66-476b-be70-4fecfb5adf0b.png)

**Comment by serge-rider** [comment] 2021-09-14 10:44
Seems to be duplicate of #12986

**Comment by straklhl** [comment] 2021-09-15 03:22
@uslss @serge-rider @ShadelessFox 
After I deleted the user data, reinstalled the software and restarted my PC, the problem was resolved.
Thanks for your support.

**Closed as completed** 2021-09-15 08:48 UTC
Labels: xp:major, xo:windows, xo:eclipse

**Comment by zhouqing-inovance** [comment] 2021-09-23 02:31
I deleted my data and reinstalled the software,it done.
but a few days it reproduced again.
my steps is similar like straklhl. open a sql file and it promot the error。

**Comment by ShadelessFox** [comment] 2021-09-23 08:34
Hello @zhouqing-inovance,

We can't reproduce this issue, unfortunately. Maybe your PC had a hard reset or DBeaver process was terminated ungracefully. 

Is there anything suspicious in the Windows' <kbd>Event Viewer</kbd>?
