### ISSUE TITLE
SQL Error: Internal jdbc driver error

### ISSUE THREAD

**Issue by kufii** [dbeaver/dbeaver#4252] opened 2018-09-21 15:30 UTC
I work on some pretty complex Oracle queries, and I find that often times after running some queries, coming back to dbeaver after leaving it open for a bit, whenever I try to run any other queries I get "SQL Error: Internal jdbc driver error". I have to invalidate the connection for it to start working again

**Comment by kufii** [comment] 2018-09-21 15:32
I should note that the jars I have added are ojdbc8, orai18n, and xdb6 downloaded from [here](http://www.oracle.com/technetwork/database/features/jdbc/jdbc-ucp-122-3110062.html), and xmlparserv2.jar

**Comment by serge-rider** [comment] 2018-09-27 09:35
Could you post error stacktrace next time you will see this error? 
Open Error Log view and find the error in the list. Double click and copy/paste stacktrace.

**Comment by kufii** [comment] 2018-09-27 14:18
```
java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:309)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:343)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:448)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:392)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:390)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:822)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2384)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.IllegalArgumentException
	at java.nio.Buffer.limit(Buffer.java:275)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:142)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:101)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:80)
	at oracle.net.ano.CryptoNIONSDataChannel.readDataFromSocketChannel(Unknown Source)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForReading(T4CMAREngineNIO.java:98)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:534)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:485)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:733)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4646)
	at oracle.jdbc.driver.OracleStatement.doScrollStmtExecuteQuery(OracleStatement.java:4762)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1741)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1692)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:300)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:341)
	... 12 more

```

**Comment by uslss** [comment] 2019-11-19 14:31
@kufii is issue still reproducible on 6.2.5?

**Comment by kufii** [comment] 2019-11-20 15:06
Yes, it's still an issue with jdbc 8

**Comment by serge-rider** [comment] 2019-11-24 08:48
I need some query example in order to reproduce this.
Maybe it is an Oracle driver bug (you could try to upgrade/downgrade driver version).
Or maybe it is somehow related to the way DBeaver processes queries in Oracle.

**Comment by kufii** [comment] 2019-11-24 15:07
It happens with literally any query. Select * from table;, go use another application for a bit leaving dbeaver open, then come back and run it again

**Comment by serge-rider** [comment] 2019-11-26 21:51
Ah. Most likely it happens because your connection was timed out and closed by server.
Generally it is handled by dbeaver - we catch specific error codes and reopen connection in case of disconnect.
But in your case driver throws internal error instead of valid Oracle error.
Probably because of driver version mismatch.

What is your Oracle server version and driver version?
You can get this info by clicking on Test Connection in connection settings dialog.

**Comment by kufii** [comment] 2019-12-02 16:06
Server:  
Oracle Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

Driver:  
Oracle JDBC driver 12.2.0.1.0

**Comment by uslss** [comment] 2020-09-10 11:43
is it still actual?

**Comment by uslss** [comment] 2020-10-05 08:17
there aren't any updates for a long time.
Issue closed. If it is still actual for you - feel fee to reopen it

**Closed by uslss** 2020-10-05 08:17 UTC
Labels: can't reproduce, question, wait for response, x:oracle
