### ISSUE TITLE
Redshift external table columns read problem

### ISSUE THREAD

**Issue by sravikrishna3** [dbeaver/dbeaver#13133] opened 2021-07-07 13:52 UTC
#### System information: 
- Operating system (distribution) and version : Mac OS bigsur
- DBeaver version  CE 21.1.2
- Additional extensions

#### Connection specification:
- Database name and version : Redshift
- Driver name JDBC4.2 (from AWS)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

We use spectrum with redshift.  Spectrum allows us to refer to Athena tables.
In 21.1.2, if a table has been created in Athena with "String" data type, then trying to see the DDL in Spectrum would give us
an error "Unknown data type String".
This works fine in 21.1.1.

In the attached screen shot from 21.1.1 we can see the table DDL in Redshift.  This errors out in 21.1.2.
<img width="443" alt="Screen Shot 2021-07-07 at 9 44 02 AM" src="https://user-images.githubusercontent.com/44801660/124771393-1716c500-df09-11eb-9b7f-195f0942378a.png">

**Comment by uslss** [comment] 2021-07-08 08:22
@sravikrishna3 
Could you check if enabling Read all data types option in connection properties resolves the problem?
![image](https://user-images.githubusercontent.com/31996417/124888452-c96c8c00-dfde-11eb-9567-551548bf9437.png)

**Comment by sravikrishna3** [comment] 2021-07-08 09:45
No, it made no difference.


<img width="1280" alt="Screen Shot 2021-07-08 at 5 43 21 AM" src="https://user-images.githubusercontent.com/44801660/124901027-a4145980-dfaf-11eb-9344-76e849b229de.png">


<img width="1280" alt="Screen Shot 2021-07-08 at 5 41 42 AM" src="https://user-images.githubusercontent.com/44801660/124901062-aaa2d100-dfaf-11eb-8152-e6cbf85b6e8a.png">

**Comment by sravikrishna3** [comment] 2021-07-09 20:46
Again, enabling Read all Data Types did NOT fix the issue.

**Comment by barel166** [comment] 2021-08-19 23:30
I can confirm this is still an issue in 21.1.5 when trying to list columns of a table in a Redshift Spectrum schema. This worked fine before.

![image](https://user-images.githubusercontent.com/75643982/130156822-daa3a19b-9daf-42a7-8377-aaa659077e5c.png)

**Comment by sravikrishna3** [comment] 2021-08-19 23:32
I believe it will be fixed only in 21.2.1 version.

**Comment by Matvey16** [comment] 2021-09-06 10:37
@sravikrishna3 Hello, if it is possible, I would like to ask you to verify if this was fixed for you
You can download Early access version here https://dbeaver.io/files/ea/

**Comment by sravikrishna3** [comment] 2021-09-06 10:56
Are we talking about version 21.2.0.  It still shows the same error. Screenshot attached

<img width="1280" alt="Screen Shot 2021-09-06 at 6 54 55 AM" src="https://user-images.githubusercontent.com/44801660/132206892-183ab434-82d8-443c-b4e0-d11a06246416.png">

**Comment by Matvey16** [comment] 2021-09-06 11:58
@sravikrishna3 It is not fixed in 21.2.0, but is scheduled to be in 21.2.1. You can download the latest build that includes this fix on our early access page https://dbeaver.io/files/ea/

**Comment by sravikrishna3** [comment] 2021-09-06 12:40
Indeed it has been fixed.  SS attached.
<img width="1280" alt="Screen Shot 2021-09-06 at 8 40 12 AM" src="https://user-images.githubusercontent.com/44801660/132219033-1a44b1b1-94f9-4edb-b777-b5d5d6649bc0.png">

**Closed as completed** 2021-09-06 12:45 UTC
Labels: xp:major, x:redshift, sp:2, xf:metadata

**Comment by sravikrishna3** [comment] 2021-09-06 14:50
Thanks.

**Comment by s-mikkelsen** [comment] 2022-07-21 18:00
I am experiencing the same issue with the newest version of DBeaver

#### System information: 
- Operating system (distribution) and version: macOS Monterey 12.4
- DBeaver version 22.1.2.202207091909

#### Describe the problem you're observing: 

We are using Amazon Redshift Spectrum to query external data in S3. Users on the newest version of DBeaver are unable to expand columns. I have seen null pointer exception errors and "Cannot invoke "org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType.getTypeID()" because "dataType" is null"

Users on older versions are not experiencing this issue.

**Comment by barel166** [comment] 2022-07-21 18:11
I can confirm same problem. I had to roll back to DBeaver v22.1.0. Also on macOS Monterrey 12.4

**Comment by s-mikkelsen** [comment] 2022-07-21 20:17
@barel166 Thank you! Rollback fixed for us as well.
