### ISSUE TITLE
DBeaver CE 6.0.4 - Error message and fail to launch after installation

### ISSUE THREAD

**Issue by hakonhei** [dbeaver/dbeaver#5862] opened 2019-05-06 17:39 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 Home 1803
- DBeaver CE 6.0.4
- Installing JRE with DBeaver / Version 8 Update 211 (build 1.8.0_211-b12) also installed
- Additional extensions: No

#### Describe the problem you're observing:
Downloading and executing Windows 64 bit (installer + JRE), also installing JRE. Installation completes successfully. Error message when trying to start the application: The DBeaver executable launcher was unable to locate its companion launcher jar.
![image](https://user-images.githubusercontent.com/23156650/57243219-d9bb0200-7035-11e9-8299-78449cf41110.png)

#### Steps to reproduce, if exist:
Download and run DBeaver CE version 6.0.4 Windows 64 bit (installer + JRE) including JRE. Then launch DBeaver application.

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by serge-rider** [comment] 2019-05-06 18:42
Seems to be duplicate of #5769.

Are you using 64-bit Windows?
Try to setup from zip archive. In some cases archive unpacking fails in installer.

**Comment by hakonhei** [comment] 2019-05-06 19:03
64-bit Windows. 
Tried uninstalling Java and reinstalling DBeaver, but no difference. 

So I:
- Uninstalled DBeaver again
- Downloaded the Windows 64 bit (zip archive) and extracted to a folder in Downloads using 7zip
- Ran the Executable, but got the following error message now: 

![image](https://user-images.githubusercontent.com/23156650/57248342-6a97da80-7042-11e9-8e1d-9def502544af.png)

**Comment by serge-rider** [comment] 2019-05-06 19:10
Unfortunately, in case of zip archive you need to install Java separately.

BTW we going to replace current installer with new one after DBeaver 6.1 release (as well as bundled Java version).

**Closed** 2019-10-23 15:43 UTC
Labels: bug, can't reproduce, duplicate, xo:windows
