### ISSUE TITLE
Export via advanced copy does not use the filter/sorting in source table

### ISSUE THREAD

**Issue by kschaumann** [dbeaver/dbeaver#9932] opened 2020-10-01 06:40 UTC
Reproduce the Error: 
#### System information: 
Windows 10 
and Linux (Ubuntu 18.4)
DBBeaver CE in Version 7.2.1

#### Connection specification:
- Postgres in Version 8.4, 9.6, 9.4

#### Describe the problem you're observing:
Advanced Export does not use the Quick-Filter, but export as the initial query result.
The export does also not respect if any column order is changed in view. 

#### Steps to reproduce, if exist:
Query any table
Use a "quick sort" via the table-Headers
![Auswahl_581](https://user-images.githubusercontent.com/57621623/94776024-39e7dc00-03c1-11eb-9dda-0e039c0b8e55.png)

Open the Menu via the right mouse button
Choose "erweitertes Kopieren" (Maybe "advanced copy" in english?)
Select any of the Options, as example I have used "as TXT":
![Auswahl_582](https://user-images.githubusercontent.com/57621623/94776041-41a78080-03c1-11eb-89c6-d3ce0666f728.png)

**Comment by uslss** [comment] 2020-10-01 08:34
thanks for the bug report.
close as a duplicate of  #9252

**Closed by uslss** 2020-10-01 08:34 UTC
Labels: bug, duplicate
