### ISSUE TITLE
Export parameters bug introduced in 6.2.1 (6.2.0 was ok)

### ISSUE THREAD

**Issue by TuncGercek** [dbeaver/dbeaver#6822] opened 2019-09-25 01:55 UTC
#### System information: 
- Operating system (distribution) and version: Linux / Fedora 30
- DBeaver version: 6.2.1
- Additional extensions

#### Connection specification:
- Database name and version DB2, MSSQL, MySQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Sometimes, but behaviour is the same for all situations

#### Describe the problem you're observing:
I frequently use DBeaver to export data into CSV files. Up until 6.2.0, my CSV parameters (destination file, delimiter, open folder upon completion, etc.) would be saved, so that I could just select "Export" after a right-click on the result area, and press Enter-Enter-Enter and know exactly where to find the exported data. Now, after upgrading to 6.2.1, these parameters are lost (except the selection of CSV vs HTML, etc.) and I have to set them each time I do an export.

#### Steps to reproduce, if exist:
Right-click the results pane, select "Export" from the menu, and do an export. Type \t as a delimiter, type a destination folder/file, and do an export. Then, repeat the exact process again - to find that your settings have been lost and you need to retype it all.

**Comment by serge-rider** [comment] 2019-09-25 20:28
Duplicate of #6798
Thanks for the bug report anyway

**Closed by serge-rider** 2019-09-25 20:28 UTC
Labels: bug, duplicate
