### ISSUE TITLE
Can't edit the cell in a result set using inline/righclick method  for redshift DB's using Dbeaver 5.1.1 version

### ISSUE THREAD

**Issue by mintuamb** [dbeaver/dbeaver#3674] opened 2018-06-21 23:53 UTC
see snapshot attached for details
I can't edit only for DB's which are on Redshift DB but the Dbeaver tool works fine on other DB types like MYSQL or Posgres

tried both inline edit method and right click edit method on a cell

see snapshot for details
![double click-inline](https://user-images.githubusercontent.com/40477577/41750945-948c2f64-7573-11e8-90e3-e93259ac4281.jpg)
![can t edit right click](https://user-images.githubusercontent.com/40477577/41750946-94a4e446-7573-11e8-8109-bf7d6b5cead9.jpg)

**Comment by mintuamb** [comment] 2018-06-27 18:31
can someone please take a look and help me with this?

**Comment by serge-rider** [comment] 2018-06-27 20:38
I see that you are trying to edit results of some custom query.
By some reason these results are read-only. 

Please check that your connection isn't read-only (it is on page General of connection properties dialog).
Can you edit table data directly (on the tab Data of table editor)?

**Comment by xmiseggs** [comment] 2018-06-28 10:07
I don't know what to tell you, the same thing happens to me as to @mintuamb, but in the "Result" window, when I try to edit the text of a cell, I am not allowed to edit it, the "Save", "Cancel" and "Script" buttons in the base of the "Result" tab are also activated.

I am in Oracle 11.2.0 and the connection is not read-only

**Comment by serge-rider** [comment] 2018-06-28 10:13
@xmiseggs could you post some sample SQL query which will let me to reproduce this? 
You could use some system Oracle tables for that.

**Comment by serge-rider** [comment] 2018-06-28 10:33
Thanks, now I see this.
DBeaver can't find source table (view) in metadata catalog because it don't know in what schema this view resides (and Oracle JDBC driver doesn't provide valid query metadata).

You could use fully qualified table names in your queries (e.g. SYS.DICTIONARY). This will let you to edit results.

**Comment by serge-rider** [comment] 2018-06-28 10:38
Also - enabled save/cancel controls is a actually a bug, thanks for noticing.

**Comment by xmiseggs** [comment] 2018-06-28 10:40
@serge-rider I attach new image, I think I've done what you tell me, but the same thing happens, it goes into edit mode, the buttons are activated but I can't write.

![clipboard01](https://user-images.githubusercontent.com/29940632/42029591-5be66d34-7ad0-11e8-99ab-edb70f9a5560.jpg)

**Comment by serge-rider** [comment] 2018-06-28 10:49
That's odd. 
Do you have access to all SYS objects? What happens if you press F4 when cursor is on SYS.DICTIONARY ?

**Comment by xmiseggs** [comment] 2018-06-28 10:53
@serge-rider this is what happens when you press F4
![clipboard01](https://user-images.githubusercontent.com/29940632/42030161-2ea1590e-7ad2-11e8-8e1b-0fbf6c90c929.jpg)

**Comment by serge-rider** [comment] 2018-06-28 11:35
Ok, good. Are you able to edit data in table directly (on Data tab)?

**Comment by xmiseggs** [comment] 2018-06-28 12:11
I can't edit it, but it's funny what happens, for example in Oracle SQL Developer it happens the same as in DBeaver but in the SQL editor that has the PowerBuilder programming language if I can edit the information, the 3 database managers connect in the same way and use the same username and password.

When I see this I understand that it is not DBeaver's problem, I will investigate and try to locate the cause if the solution is relevant I will detail it here.

Thank you for your help  @serge-rider

**Comment by xmiseggs** [comment] 2018-06-28 14:57
I don't know what to think anymore... in SQL Developer if I do a simple SELECT and try to modify a record in the "Result" tab, it will not let me edit it, if I select the complete table and go to the "Data" tab I can edit a record perfectly. If I perform these same actions in DBeaver I can't edit in any of the ways.

I'm not going to keep investigating just to transfer my evidence in case they can be of any help.

Thank you

**Comment by mintuamb** [comment] 2018-06-28 16:29
Hi Serge
I have checked both things you asked me to check

1) my connection is not readonly see attached

2) also I can't even edit in the data tab of the table   see attached

And it only happens for me for redshift DB only and all other DB's I can
make inline edit.

It use to work earlier till this version `dbeaver-ce-4.3.4-x86_64-setup`

**Comment by xmiseggs** [comment] 2018-06-28 20:56
Well then we're just as @mintuamb have if they verify it and can be solved

**Comment by serge-rider** [comment] 2018-06-29 12:31
@xmiseggs thank you for investigation. Although I can't reproduce this but now I have a couple of clues.
@mintuamb this seems to be a problem with RedShift JDBC driver. We'll investigate this a bit more, thanks for report.

**Comment by serge-rider** [comment] 2018-07-07 22:08
Any update?

**Comment by mintuamb** [comment] 2018-07-07 23:12
I still can't edit only redshift dbs with the latest update.

**Comment by mintuamb** [comment] 2018-07-16 17:24
I just downloaded and installed  the latest version(DBeaver 5.1.3) today  and the issue still persists...
Still Can't edit cells using inline edit method only for RedShift db's for others(Postgres,Mysql) they are working

**Comment by xmiseggs** [comment] 2018-07-17 08:08
I still can't edit.
Apparently we're not the only ones:
https://github.com/dbeaver/dbeaver/issues/3749

**Comment by jeffkillian** [comment] 2018-08-15 17:53
I'm also experiencing the same thing. The save/cancel buttons are always greyed out.

**Comment by serge-rider** [comment] 2018-08-23 11:00
Fixed in #4051

**Closed by serge-rider** 2018-08-23 11:00 UTC
Labels: bug, question, x:redshift

**Comment by sistem06** [comment] 2018-12-06 11:51
> Thanks, now I see this.
> DBeaver can't find source table (view) in metadata catalog because it don't know in what schema this view resides (and Oracle JDBC driver doesn't provide valid query metadata).
> 
> You could use fully qualified table names in your queries (e.g. SYS.DICTIONARY). This will let you to edit results.

you genius.. that was it, so simple.. tnx!!!!!

**Comment by Zardoz89** [comment] 2019-05-29 07:14
This is happening on DBeaver 6.0.5.201905192012 (linux , with Oracle JDK 1.8.0_191 and OpenJDK 11.0.3) connecting to Oracle databases.

Tested with :
* Oracle 12 driver (ojdbc7-12.1.0.2.0)
    * Oracle 12 database -> OK
    * Oracle 11 databases -> Can't edit cells or add new rows. However, doing a simple UPDATE table SET X... works fine
* Oracle 11 driver (ojdbc6-11.2.0.4)
    * Oracle 11 databases -> Can't edit cells or add new rows. However, doing a simple UPDATE table SET X... works fine
    * Oracle 10 databases -> Same issue
    * Oracle 9 databases -> Ok

**Comment by Gaboxondo** [comment] 2019-06-06 16:04
I have the same issue in Dbeaver 6 and my connection is not read only, the buttons are disabled and my connection user has permissions to read and write.
When I use dbeaver 4 it works perfect and I can edit.

**Comment by awoedey2k** [comment] 2019-06-07 11:47
I am also having the same problem with oracle ojdbc driver 7 after i upgraded to Dbeaver Version 6.0.5.201905192012. my connection is not read only , and i was able to inplacelly update cell before now.
