### ISSUE TITLE
After upgrade, lost the default database on connection settings

### ISSUE THREAD

**Issue by mcunha98** [dbeaver/dbeaver#6594] opened 2019-08-22 15:45 UTC
After migrated to 6.1.5 lost the default database definition for all connections...

https://i.postimg.cc/FRDJ53DL/screenshot-547.png

**Comment by serge-rider** [comment] 2019-08-22 16:02
Can't reproduce. What database types do you use?

**Comment by mcunha98** [comment] 2019-08-24 21:17
For postgres the config was preserved, for mysql/mariadb lost

**Comment by serge-rider** [comment] 2019-08-25 06:11
I'm quite sure that this bug was fixed in 6.1.4. Maybe you noticed that only after 6.1.5 upgrade?

In order to restore lost settings just delete DBeaverData folder and perform migration again.

**Closed** 2019-11-20 14:40 UTC
Labels: bug, can't reproduce
