### ISSUE TITLE
cannot save scripts

### ISSUE THREAD

**Issue by enricjaen** [dbeaver/dbeaver#14063] opened 2021-09-30 07:47 UTC
#### System information: 
- Operating system (distribution) and version.  Mac Big Sur 11.5.2
- DBeaver version. Version 21.2.1.202109181446
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

when I try to save a file, either by keys combination or file > Save, nothing happens. The File tab keeps with the asterisk.

**Comment by uslss** [comment] 2021-09-30 08:35
thanks for the report.
closed as a duplicate of #9097

**Closed as completed by uslss** 2021-09-30 08:35 UTC
Labels: duplicate
