### ISSUE TITLE
Connection attempt timed out, when using hostname instead of IP

### ISSUE THREAD

**Issue by guilhermedotcamargo** [dbeaver/dbeaver#34982] opened 2024-07-25 13:09 UTC
### Description

The database is remote, i'm using a VPN to reach him, when using a hostname like `ixxxdxxx-instance-1.czd1zxxxjxxx.us-east-1.rds.amazonaws.com` i get this error:

`Connection attempt timed out.`

If I try to use an interface IP it connects successfully, and if I try to use another database client such as Beekeeper, it works using the hostname

### DBeaver Version

Community 24.1.3.202407211303

### Operating System

Windows 11 Home Single Language

### Database and driver

Server: PostgreSQL 15.4
PostgreSQL 15.4 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 9.5.0, 64-bit

Driver: PostgreSQL JDBC Driver 42.7.2

**Comment by E1izabeth** [comment] 2024-08-01 11:04
It looks like you may be experiencing some issues with your DNS and the Java application may be having trouble resolving the hostname correctly. This can happen when there are multiple network adapters on your computer and/or if your network configuration is complex.

**Comment by E1izabeth** [comment] 2024-09-24 07:29
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Closed as not planned by E1izabeth** 2024-09-24 07:29 UTC
Labels: x:postgresql, can't reproduce, wait for response, xf:connection
