### ISSUE TITLE
Can't connect to DB through SHH anymore.

### ISSUE THREAD

**Issue by edgarsbbb** [dbeaver/dbeaver#19008] opened 2023-02-08 13:14 UTC
### Description

When upgrading to 22.3.4. can't connect to DB through SHH anymore

### DBeaver Version

22.3.4

### Operating System

Ubuntu 20.04

### Database and driver

MySQL DB
com.mysql.cj.jdbc.Driver 

### Steps to reproduce

Set up SSH connection in 22.3.3.
Upgrade to version 22.3.4.
Try to access DB, getting error = 13

deb package used to upgrade versions

Downgrade back to 22.3.3. - SSH connection works as expected and can access DB.

### Additional context

Message from logs:
 - error=13, Permission denied
Stack trace:
 - An exception stack trace is not available.

**Comment by LonwoLonwo** [comment] 2023-02-08 14:47
Hello @edgarsbbb

Thanks for the report.

Closing as duplicate of https://github.com/dbeaver/dbeaver/issues/18958

**Closed as not planned by LonwoLonwo** 2023-02-08 14:47 UTC
Labels: duplicate
