### ISSUE TITLE
sql editor fonts size can't change

### ISSUE THREAD

**Issue by JonSnower** [dbeaver/dbeaver#19576] opened 2023-04-01 09:04 UTC
### Description

sql editor fonts size can't change use ctrl + +

### DBeaver Version

23.0.1.202303250535

### Operating System

windows 10

### Database and driver

mysql

**Comment by E1izabeth** [comment] 2023-04-01 11:04
Thank you for bug report. Close as duplicate of #19521

**Comment by JonSnower** [comment] 2023-04-01 11:04
您好，邮件已收到，我会尽快给您回复。

**Closed as not planned by E1izabeth** 2023-04-01 11:04 UTC
Labels: duplicate
