### ISSUE TITLE
Derby: PK wrong creation

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12454] opened 2021-05-13 15:31 UTC
#### System information: 
- Windows 10, Derby server, DBeaver CE 21.0.5

#### Describe the problem you're observing:
If create table with explicitly specified PK then
  DDL isn't correctly displays: empty PK constraint parameter and we can see index creation info. Therefore we cannot also assign any foreign keys
![image](https://user-images.githubusercontent.com/43252954/118148546-58af5600-b419-11eb-854e-6051ead6b5a9.png)
![image](https://user-images.githubusercontent.com/43252954/118148586-6238be00-b419-11eb-8f3e-8ca75ee632f3.png)

In EE 21.0.0 there is no problem, dbeaver see right information 
![image](https://user-images.githubusercontent.com/43252954/118151394-3ec34280-b41c-11eb-8f73-a98f4b1b9af5.png)

#### Steps to reproduce, if exist:
![2021-05-13_17h09_41](https://user-images.githubusercontent.com/43252954/118147568-61ebf300-b418-11eb-924f-c4db173f3fa4.gif)

**Comment by LonwoLonwo** [comment] 2021-05-14 15:18
Apache Derby Network Client JDBC Driver 10.15.2.0 driver issue. Works fine with 10.15.1.3 (which we use in EE version)

**Comment by LonwoLonwo** [comment] 2021-12-23 14:25
duplicate of #15000

**Closed as completed by LonwoLonwo** 2021-12-23 14:25 UTC
Labels: x:derby, xf:metadata
