### ISSUE TITLE
Generate SQL in Azure SQL DB does not generate PK

### ISSUE THREAD

**Issue by willturcios1** [dbeaver/dbeaver#17515] opened 2022-08-31 15:58 UTC
### Description

``When trying to generate SQL and grab the DDL for an NC index, it works but when you do a PK it does not, it just returns a semi-colon:
Even under properties, it shows empty.
![image](https://user-images.githubusercontent.com/64033961/187723482-afa78bff-41ed-4c53-a252-76108c704a26.png)
![image](https://user-images.githubusercontent.com/64033961/187723630-63059227-f707-4781-8094-282ca88d88c1.png)
![image](https://user-images.githubusercontent.com/64033961/187723762-53beb7ec-3d5a-4d22-97a4-84c2cfa9e745.png)

### DBeaver Version

22.1.5.202208211008

### Operating System

Windows 10

### Database and driver

Azure SQL DB
Driver Name : Azure SQL Server
Class Name : com.microsoft.sqlserver.jdbc.SQLServerDriver

### Steps to reproduce

Expand Indexes under Schema. Right click on index and click generate SQL
This works for NC indexes but not for PKs.

**Comment by LonwoLonwo** [comment] 2022-08-31 18:00
Thanks for the bug report @willturcios1 

Actually, this is a duplicate of https://github.com/dbeaver/dbeaver/issues/13529

We do not show index DDL at all at this moment.

**Closed as not planned** 2022-08-31 18:00 UTC
Labels: duplicate, x:mssql, xf:metadata
