### ISSUE TITLE
Cannot connect to Firebird

### ISSUE THREAD

**Issue by FIFernandes** [dbeaver/dbeaver#9380] opened 2020-07-27 15:06 UTC
[<!--](url)
#### System information: 
- Windows 10
- DBeaver version Version 7.1.3.202007192031
- Additional extensions - non

#### Connection specification:
- Firebird 3.0

I can't seem to connect to my firebird database. It  say's firebird driver files are missing

![image](https://user-images.githubusercontent.com/11407431/88557809-9d046d80-d022-11ea-8d85-6acb31382176.png)

**Comment by kseniiaguzeeva** [comment] 2020-07-28 14:22
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/9373

**Closed by kseniiaguzeeva** 2020-07-28 14:22 UTC
Labels: bug, wait for review
