### ISSUE TITLE
Auto-restart app when updating

### ISSUE THREAD

**Issue by FMorschel** [dbeaver/dbeaver#26609] opened 2024-04-24 12:45 UTC
**Is your feature request related to a problem? Please describe.**
When you open the app and there is a new version available, a popup opens prompting the user to update the app. When you do accept the update, the app itself closes and the installer starts running. When the installer finishes, nothing happens.

**Describe the solution you'd like**
I'd like to propose a change in the installer. Add a checkbox at the last page to open DBeaver and for that to be checked by default.

**Describe alternatives you've considered**
If that is not available we need to manually open the app when we first install the app or when we update it (I believe the latter is more annoying because in my cases I've usually just had the time to open the app and it asks me to close it to update and it stays that way).

**Additional context**
There could be a checkbox right under this one:
![Last page of the installer](https://github.com/dbeaver/dbeaver/assets/52160996/fb2114ff-f805-4b55-908e-fa2e733d6082)

Similar, for example, to what gave me the idea, the VSCode installer:
![Last page for the VSCode installer with the option to open the app when completing the instalation](https://github.com/dbeaver/dbeaver/assets/52160996/1d3b6628-e455-4531-9616-ddadbefa3855)

**Comment by E1izabeth** [comment] 2024-04-25 08:45
Thank you for the idea. I'm closing it as a duplicate of #13457 (_"The last dialog should have a 'start dbeaver' button"_)
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-04-25 08:45 UTC
Labels: duplicate
