### ISSUE TITLE
context menu randomly opens while using other apps

### ISSUE THREAD

**Issue by clemlaugit** [dbeaver/dbeaver#22749] opened 2024-02-07 18:18 UTC
### Description

Three similar issues:
-When using other apps, randomly only the context menu from dbeaver comes into focus.  
-Sometimes it brings dbeaver into focus with context menu showing
-sometimes when using dbeaver the context menu will just pop up

This came up while i was submitting this issue:
![image](https://github.com/dbeaver/dbeaver/assets/91501833/41d84f8e-8e71-4898-a6fd-6e469d8c5c31)

This just popped up when i was looking at a query result:
![image](https://github.com/dbeaver/dbeaver/assets/91501833/a4d1071b-a9ba-4f6c-b525-24121b97cbac)

### DBeaver Version

Version 23.3.4.202402041841

### Operating System

Mac Sonoma 14.3

### Database and driver

snowflake 3.14.4

### Steps to reproduce

hard to reproduce because it is random

**Comment by E1izabeth** [comment] 2024-02-08 08:28
Thank you for bug report and detailed videos with explanation.
We already have an issue about it, so I'm closing this one as a duplicate of #19977

**Closed as not planned by E1izabeth** 2024-02-08 08:28 UTC
Labels: duplicate, xf:ui, xf:sql editor
