### ISSUE TITLE
Can't edit cell inline with enter or doubleclick

### ISSUE THREAD

**Issue by Ocanipse** [dbeaver/dbeaver#5639] opened 2019-04-03 12:45 UTC
#### System information: 
- Linux Mint 19
- DBeaver	6.0.1.201903251040
- java.runtime.name=OpenJDK Runtime Environment
- java.runtime.version=1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12

#### Connection specification:
- Several databases (PostgreSQL, Oracle, MySQL)

#### Describe the problem you're observing:
Since version 6.0.1 I can't I edit cells inline with enter button or with doubleclick. But I can do it when I use right click -> edit -> inline edit.

#### Include any warning/errors/backtraces from the logs
In .log file I could find this:

!ENTRY org.eclipse.e4.ui.workbench 4 0 2019-04-03 09:32:26.041
!MESSAGE Execution exception for: ParameterizedCommand(Command(org.jkiss.dbeaver.core.resultset.row.edit.inline,Inline edit,
		Edit cell value with inline editor,
		Category(org.jkiss.dbeaver.core.rs,Result Set,Result Set Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@33827b88,
		,,true),null) in 
	context chain: WorkbenchContext -> TrimmedWindowImpl (IDEWindow) Context -> PerspectiveImpl (org.jkiss.dbeaver.core.perspective) Context -> PartImpl (org.eclipse.e4.ui.compatibility.editor)  org.jkiss.dbeaver.ui.editors.sql.SQLEditor removeOnHide activeOnClose (<geo - 10.20.0.120> Calles) Context
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'org.jkiss.dbeaver.core.resultset.row.edit.inline': java.lang.NullPointerException
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:584)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:653)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:443)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$2(KeyBindingDispatcher.java:386)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1726)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1385)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1412)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1395)
	at org.eclipse.swt.widgets.Control.traverse(Control.java:6122)
	at org.eclipse.swt.widgets.Control.translateTraversal(Control.java:6100)
	at org.eclipse.swt.widgets.Composite.translateTraversal(Composite.java:1735)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3597)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:842)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1962)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6298)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5880)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:3969)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1385)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1581)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4470)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:184)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 50 more
Caused by: java.lang.NullPointerException

!ENTRY org.eclipse.ui 4 0 2019-04-03 09:32:26.069
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException

!ENTRY org.jkiss.dbeaver.model 4 0 2019-04-03 09:32:26.070
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-04-03 09:32:26.070
!MESSAGE 
!STACK 0
java.lang.NullPointerException

**Comment by riquena969** [comment] 2019-04-03 16:28
Same problem here.
Operating system: Linux mint 19.1 with Cinnamon
I have installed Oracle JDK 1.8.0_201

Please correct this, it's a very important feature. :(

**Comment by serge-rider** [comment] 2019-04-03 16:29
Duplicate of #5575
See fix in 6.0.2 EA (https://dbeaver.io/files/ea)

**Closed by serge-rider** 2019-04-03 16:29 UTC
Labels: bug, duplicate

**Comment by riquena969** [comment] 2019-04-03 16:33
Thank you. Now it's working!
