### ISSUE TITLE
5.2 rpm issue

### ISSUE THREAD

**Issue by lhupfeldt** [dbeaver/dbeaver#4200] opened 2018-09-12 08:43 UTC
Trying to install 5.2 RPM on Fedora 28 fails:
```
$ sha1sum dbeaver-ce-5.2.0-stable.x86_64.rpm
3262215a4b29cf64ebdb3decf56f2d0208804a60  dbeaver-ce-5.2.0-stable.x86_64.rpm

$ sudo dnf install ./dbeaver-ce-5.2.0-stable.x86_64.rpm 
Last metadata expiration check: 0:45:11 ago on Wed 12 Sep 2018 09:53:48 CEST.
Can not load RPM file: ./dbeaver-ce-5.2.0-stable.x86_64.rpm.
Could not open: ./dbeaver-ce-5.2.0-stable.x86_64.rpm

$ rpm -i ./dbeaver-ce-5.2.0-stable.x86_64.rpm 
error: ./dbeaver-ce-5.2.0-stable.x86_64.rpm: tag[34]: BAD, tag 1096 type 5 offset 48168 count 745 len 2980
error: ./dbeaver-ce-5.2.0-stable.x86_64.rpm cannot be installed

$rpm --version
RPM version 4.14.2
```

**Comment by serge-rider** [comment] 2018-09-12 09:03
Duplicate of #4177
Thanks for the bug report anyway

**Closed by serge-rider** 2018-09-12 09:03 UTC
Labels: bug, duplicate
