### ISSUE TITLE
5.1.4 table tree is empty for vertica connection

### ISSUE THREAD

**Issue by phil-88** [dbeaver/dbeaver#3907] opened 2018-08-02 08:56 UTC
Hello
DbEaver 5.1.4 on ubuntu 14.04 (the same valid for macos high sierra)
Vertica jdbc 8.1

Tree with database objects is empty. There used to be schemas at a top level. Now there are no schemas and table list is empty

**Comment by phil-88** [comment] 2018-08-02 08:57
Old dbeaver
![dbeaver_nobug](https://user-images.githubusercontent.com/42028484/43573739-22aab4b2-964b-11e8-9df7-0bc9dad6f62b.png)
New dbeaver
![dbeaver_bug](https://user-images.githubusercontent.com/42028484/43573741-22d79f36-964b-11e8-9c6e-76010ebf659e.png)

**Comment by serge-rider** [comment] 2018-08-03 06:43
Duplicate of #3883
thanks for the report anyway

**Closed by serge-rider** 2018-08-03 06:43 UTC
Labels: bug, duplicate
