### ISSUE TITLE
Is not possible to change Athena Data Source in Database Navigator

### ISSUE THREAD

**Issue by ferjh1** [dbeaver/dbeaver#19515] opened 2023-03-28 13:31 UTC
### Description

We've tried all the options to change the default data source of a Athena connection in the database navigator but it always shows the tables associated to the default workgroup

### DBeaver Version

23.0.1.202303250535

### Operating System

Windows 10

### Database and driver

Database: Athena
Driver: Simba Athena JDBC Data Connector 2.0.34.1000

### Additional context

We have an account with two data sources: AwsDataCatalog (default) and Pyr (secondary). 

We've configured the schema, the workgroup, and the catalog to the Pyr value, but in database navigator we always see the tables associated to AwsDataCatalog data source. Although, if we refer the tables os Pyr schema in the SQL Editor (as pyr.schema.table), we can access to the results and view the records without any problem.

**Comment by LonwoLonwo** [comment] 2023-03-28 14:32
Hello @ferjh1 

We will look into it. Thanks.

Probably a duplicate of https://github.com/dbeaver/dbeaver/issues/18786

**Comment by ferjh1** [comment] 2023-03-29 06:24
Hello Anastasiya, and thank you for your answer.

I've reviewed the question #18786 and the error that we're receiving is different that the one that the user shows in it when he includes the user property MetadataRetrievalMethod=ProxyAPI; in our case, when we try to access to a table included in the data source that is not the default one (and what is showed in the database navigator in the same way that the tables of default data source), we get this error:

```
SQL Error [100071] [HY000]: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. Database pyramid not found. (Service: AmazonDataCatalog; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 182864dd-cf02-456b-95be-e61243ed9b9e; Proxy: null) [Execution ID not available]
  [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. Database pyramid not found. (Service: AmazonDataCatalog; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 182864dd-cf02-456b-95be-e61243ed9b9e; Proxy: null) [Execution ID not available]
  [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. Database pyramid not found. (Service: AmazonDataCatalog; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 182864dd-cf02-456b-95be-e61243ed9b9e; Proxy: null) [Execution ID not available]
    Database pyramid not found. (Service: AmazonDataCatalog; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 182864dd-cf02-456b-95be-e61243ed9b9e; Proxy: null) (Service: AmazonAthena; Status Code: 400; Error Code: MetadataException; Request ID: ce773448-a3c7-42ca-b202-8229a8b5f4f3; Proxy: null)
    Database pyramid not found. (Service: AmazonDataCatalog; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 182864dd-cf02-456b-95be-e61243ed9b9e; Proxy: null) (Service: AmazonAthena; Status Code: 400; Error Code: MetadataException; Request ID: ce773448-a3c7-42ca-b202-8229a8b5f4f3; Proxy: null)
```

If you need any other information about the issue, please don't doubt to answer this message.

Thanks in advance for all.

**Comment by LonwoLonwo** [comment] 2023-03-29 08:58
Thanks for clarifying. For now, I am waiting for the test environment to reproduce your issue. It will take some time for this.

**Comment by LonwoLonwo** [comment] 2023-07-28 12:58
Hello.

We decided to add a special setting, "Show all data sources", for Athena in DBeaver in this ticket  https://github.com/dbeaver/dbeaver/issues/18786

For this reason, I'm closing this ticket as a duplicate.

Thanks for all the provided info!

**Closed as completed by LonwoLonwo** 2023-07-28 12:58 UTC
Labels: duplicate, environment, x:athena, xf:metadata

**Comment by ferjh1** [comment] 2023-08-06 18:16
Great job! I've upgraded my version to 23.1.4 and now I can see all catalogs that with previous ones were hidden.

Thank you very much for your advice and your great software.

Best regards from Madrid.
