### ISSUE TITLE
@Oracle Small Bug 

### ISSUE THREAD

**Issue by fayca121** [dbeaver/dbeaver#3970] opened 2018-08-12 14:48 UTC
Hello

I've just tested the 5.1.5 EA version and when I tried to update a varchar2 value on result panel and clicked on save button a popup window appeared with the following error message

![2018-08-12 15_42_33-data error](https://user-images.githubusercontent.com/547548/44003168-786f1e94-9e46-11e8-8ceb-dee5e4ca3f38.png)

The problem doesn't occur in version 5.1.4

My config:
-------------------
Oracle 11g
ojdbc8
Windows 7 x64
 
Thanks

**Comment by serge-rider** [comment] 2018-08-13 07:52
Duplicate of #3973 
Thanks for the bug report

**Closed by serge-rider** 2018-08-13 07:52 UTC
Labels: bug, duplicate, x:oracle
