### ISSUE TITLE
dbeaver cannot view sparksql tables, use spark thriftserver

### ISSUE THREAD

**Issue by wonb168** [dbeaver/dbeaver#5842] opened 2019-05-02 11:47 UTC
Hi. I don't seem to be able to display non-default databases using hadoop spark. Setting a database in the driver or url does not seem to work. Not sure if I'm missing anything.

**Comment by serge-rider** [comment] 2019-07-05 15:05
Duplicate of #5314

**Closed by serge-rider** 2019-07-05 15:05 UTC
Labels: bug, duplicate
