### ISSUE TITLE
SQL Parsing Error at "Implicity"

### ISSUE THREAD

**Issue by dr00gz** [dbeaver/dbeaver#7821] opened 2020-02-04 08:46 UTC
#### System information: 
- Windows 10
- Version 6.3.4.202002011957
- none

#### Connection specification:
- com.ibm.db2.jcc.DB2Driver
- DB2
- No

#### Describe the problem you're observing:
We are trying to backup table-content to history tables. For adding the history tables, we need to add system internal columns to the origin table. The SQL what add system-column will be failed executing. I think there is a problem with "IMPLICITY" Keyword parsing.

ALTER TABLE table_name ADD COLUMN sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN IMPLICITLY HIDDEN;

#### Steps to reproduce, if exist:
execute SQL Statement above

**Comment by kseniiaguzeeva** [comment] 2020-02-04 10:02
Thank you for the bug report

**Comment by serge-rider** [comment] 2020-02-07 18:57
DBeaver doesn't generate such queries. It is DB2-specific issue with SQL dialect. You need to fix your query (I can't say how exactly as I'm not that deep in DB2).

**Comment by patrickmdnet** [comment] 2020-02-21 03:55
This is a bug in DBeaver's SQL query processing.  Because DBeaver does not know how to parse this SQL statement, it leaves the semicolon in, which triggers a syntax error.  If I execute this statement as the last statement in the buffer (so, no semicolon) it will work properly.

System information: Windows 10
Version devel (built today)
Connection specification: com.ibm.db2.jcc.DB2Driver DB2
Using DB2 z/OS V12R1M500.  (Also reproduced on DB2 LUW v11.1.4.4.)

With a semicolon, the dbeaver_sql_20200220.log file is:

```
!ENTRY org.jkiss.dbeaver.model 1 25 2020-02-20 22:33:04.757
!MESSAGE ALTER TABLE sample ADD COLUMN sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN IMPLICITLY HIDDEN;
;

!SUBENTRY 1 org.jkiss.dbeaver.model 4 -104 2020-02-20 22:33:04.830
!MESSAGE ILLEGAL SYMBOL "". SOME SYMBOLS THAT MIGHT BE LEGAL ARE:. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.19.49
```

and this stacktrace from dbeaver-debug.log:

```
2020-02-20 22:33:04.986 - SQL Error [42601]: ILLEGAL SYMBOL "". SOME SYMBOLS THAT MIGHT BE LEGAL ARE:. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.19.49
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: ILLEGAL SYMBOL "". SOME SYMBOLS THAT MIGHT BE LEGAL ARE:. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.19.49
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:488)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:425)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:417)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:775)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2914)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3423)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Without a semicolon this works. The dbeaver_sql_20200220.log output is:
```
!ENTRY org.jkiss.dbeaver.model 1 27 2020-02-20 22:43:07.738
!MESSAGE ALTER TABLE sample ADD COLUMN sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN IMPLICITLY HIDDEN


!SUBENTRY 1 org.jkiss.dbeaver.model 1 0 2020-02-20 22:43:07.787
!MESSAGE SUCCESS [0]
```

Also you can see that the syntax highlighting is broken for this statement:

![image](https://user-images.githubusercontent.com/858798/75002880-f218d380-5433-11ea-858e-9d082484e68d.png)

**Comment by kseniiaguzeeva** [comment] 2020-02-21 11:39
Thank you for the additional information. Yes, the statement is successfull without semicolon.

**Comment by serge-rider** [comment] 2020-05-05 12:21
The problem is in BEGIN keyword evaluation. DBeaver expects code block after it.

**Comment by serge-rider** [comment] 2020-05-05 12:28
Fixed with extra heuristics.

Note: we need better semantic parser of DB2 dialect.

**Comment by kseniiaguzeeva** [comment] 2020-05-06 12:32
I still can reproduce the issue when I execute ALTER TABLE table_name ADD COLUMN sys_start TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN IMPLICITLY HIDDEN;
error appears: 
Error occurred during SQL query execution
Reason:
SQL Error [42601]: An unexpected token "" was found following "".  Expected tokens may include:  "IN IMPLICITLY HIDDEN".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.26.14

**Comment by serge-rider** [comment] 2020-05-06 15:48
Fixed

**Comment by kseniiaguzeeva** [comment] 2020-05-07 13:02
verified

**Closed by kseniiaguzeeva** 2020-05-07 13:02 UTC
Labels: bug, x:db2
