### ISSUE TITLE
Connection not automatically reconnecting when using Agent + SSH tunnel

### ISSUE THREAD

**Issue by webtoolbox** [dbeaver/dbeaver#23383] opened 2024-04-10 10:26 UTC
### Description

An SSH agent and tunneling is being used to connect. This always used to work before. If a connection was left idle and it disconnected, upon issuing a new SQL query, it would automatically reconnect. After the second to last update, it stopped working. 

Initially when executing the query on a connection that is no longer connected due to being idle too long, it first takes many seconds to try to execute the query. That fails with this error:
<img width="735" alt="Screenshot 2024-04-10 at 1 19 59 PM" src="https://github.com/dbeaver/dbeaver/assets/1911826/f5c0637e-04f4-46ad-b017-aad7cc138758">

Then I try to run the query again and it gives this error each time I try to run the query again:
<img width="756" alt="Screenshot 2024-04-10 at 1 20 08 PM" src="https://github.com/dbeaver/dbeaver/assets/1911826/d0b5be91-ff27-4926-874c-74b0a86282d6">

It works if I manually disconnect the connection and then connect to it again.

### DBeaver Version

Community Edition 24.0.2

### Operating System

MacOS Sonoma 14.4.1

### Database and driver

mySQL

### Steps to reproduce

Explained above.

**Comment by ShadelessFox** [comment] 2024-04-10 13:31
Thanks for the bug report. A duplicate of #23359

**Closed as not planned by ShadelessFox** 2024-04-10 13:31 UTC
Labels: duplicate, xf:ssh, regression
