### ISSUE TITLE
dbeaver23~24版本的拖动界面上组件时触发闪退的问题解决了吗(Has the issue of triggering a crash when dragging section components in dbeaver23~24 been resolved)

### ISSUE THREAD

**Issue by longhuihy** [dbeaver/dbeaver#34066] opened 2024-05-24 01:50 UTC
### Description

dbeaver23~24版本的拖动截面组件时触发闪退的问题解决了吗(Has the issue of triggering a crash when dragging section components in dbeaver23~24 been resolved)

### DBeaver Version

23.x~24.x

**Comment by ShadelessFox** [comment] 2024-05-24 10:07
Hello @longhuihy,

I'm not sure what this issue is about. Can you elaborate, please?

**Comment by E1izabeth** [comment] 2024-05-29 14:51
Thanks for the bug report. I''m closing it as a duplicate of https://github.com/dbeaver/dbeaver/issues/33253

**Closed as not planned by E1izabeth** 2024-05-29 14:51 UTC
Labels: duplicate
