### ISSUE TITLE
Shift+Tab should delete leading whitespaces

### ISSUE THREAD

**Issue by DerPeterA** [dbeaver/dbeaver#21245] opened 2023-09-19 11:30 UTC
**Is your feature request related to a problem? Please describe.**
In most tools, pressing Shift+Tab repeatedly, when a text block is highlighted, all lines of the text block are moved all the way to the left removing all tabs and spaces at the beginning of all lines. DBeaver does the same thing BUT does not delete whitespaces, it only deletes tabs.

**Describe the solution you'd like**
Dbeaver should remove spaces as well, when there are no more tabs to delete (in packets of formatting parameter 'indent size').

**Describe alternatives you've considered**
Manually delete the whitespaces from every line manually.

**Additional context**
N/A

**Comment by E1izabeth** [comment] 2023-09-19 20:57
Thank you for report.
I'm closing this issue as a duplicate of #7280.
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2023-09-19 20:57 UTC
Labels: duplicate
