### ISSUE TITLE
incorrect sorting of sv_SE.utf8

### ISSUE THREAD

**Issue by oldguy76** [dbeaver/dbeaver#9903] opened 2020-09-29 09:20 UTC
#### System information: 
- Operating system (distribution) and version
Ubuntu 20.04
- DBeaver version
7.2.0
- Additional extensions

#### Connection specification:
- Database name and version
postgresql 12
- Driver name
postgresql JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
Data with a primary key collation of sv_SE.utf8 does not sort correctly. Specifically, the letter ä appears before å; it should be the opposite. Although different Swedish collations do produce slightly different sort orders, psql does sort the umlauted characters in the expected order; å -> ä -> ö. Also, DB results seem random; with the same data, fiddling with the four options of the Order menu produces inconsistent results such that the three umlauted characters appear to randomly be given priorities over each other for each sort run.

**Comment by uslss** [comment] 2020-10-19 14:12
thanks for the report
closed as duplicate of #9905

**Closed by uslss** 2020-10-19 14:12 UTC
Labels: bug, wait for review
