### ISSUE TITLE
中文翻译关闭全部翻译有误

### ISSUE THREAD

**Issue by ybin-hub** [dbeaver/dbeaver#17946] opened 2022-10-18 07:31 UTC
### Description

[
![微信图片_20221018152854](https://user-images.githubusercontent.com/73328869/196365014-39d6a915-ac15-490e-8aa6-db75409f28d2.png)
](url)
右键选项卡的时候，关闭全部翻译有误

### DBeaver Version

DBeaver Community 22.2.2

### Operating System

windows 10

**Comment by LonwoLonwo** [comment] 2022-10-18 07:47
Hello @ybin-hub 

Thanks for the bug report.

Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/17697

This is the bug from the Eclipse side.

**Closed as not planned by LonwoLonwo** 2022-10-18 07:47 UTC
Labels: xo:eclipse, xf:i18n
