### ISSUE TITLE
Incorrect work with custom types - postgres

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#12558] opened 2021-05-21 16:51 UTC
1. Create table:
CREATE TABLE repl.repl_statements (
	id bigserial NOT NULL,
	entity repl_log."t_log_entity" NULL, -- Имя сущность
....

2. Try to filter values (in visual grid), filter becomes as follows:
filter is:entity IN ('db2l.cms_channel'::t_log_entity::t_log_entity)  -- sic!!!

3. error is:
SQL Error [42704]: ОШИБКА: тип "t_log_entity" не существует
  Позиция: 93

Nota bene: all custom types MUST be "schemed" (my opinion), e.g. in table create dialog, elsewhere. Now it is not, so many errors occur.

**Comment by plotn** [comment] 2021-06-02 14:21
Addition - bug with filter select 
![dbeaver_typed_val_filter_bug](https://user-images.githubusercontent.com/11477081/120497285-f1a51180-c3c6-11eb-8c95-7d2ab31fcfac.png)

**Comment by kseniiaguzeeva** [comment] 2021-06-03 08:50
Thank you for the report. We already have the [ticket](https://github.com/dbeaver/dbeaver/issues/11973) with the bug and we will fix it.
Closed as duplicate.

**Closed as completed by kseniiaguzeeva** 2021-06-03 08:50 UTC
Labels: duplicate

**Comment by plotn** [comment] 2021-06-03 08:53
Did you notice 2 problems with the filter window?:
1. Filtering doesnt work (left part)
2. Filter values "doubles" (right part)

**Comment by LonwoLonwo** [comment] 2021-06-17 11:29
Hello @plotn 
Please add t_log_entity type DDL

Data examples for filter select bug will be very helpful. I can't reproduce it now.

Also, have you another t_log_entity type in other schemas?

**Comment by plotn** [comment] 2021-06-24 08:25
CREATE TYPE repl_log."t_log_entity" AS ENUM (
	'db2l.asr_charges',
...... many entries
	'FK',
	'SEQ');
