### ISSUE TITLE
Filters for Schemas/Users broken in 6.1.3

### ISSUE THREAD

**Issue by RamonEbdon** [dbeaver/dbeaver#6495] opened 2019-08-12 02:12 UTC
#### System information: 
- Operating system: Windows 7 x64 SP1
- DBeaver version: 6.1.3 (CE)
- Additional extensions: n/a

#### Connection specification:
- Database name and version: All
- Driver name: All

#### Describe the problem you're observing:
Under Edit Connection -> General -> Filters -> Schemas/Users, the "Enable" option does not stay checked between restarts of DBeaver.
Seems to be related to a configuration setting not being stored or recorded correctly under the new configuration style introduced in 6.1.3.

#### Steps to reproduce, if exist:
1. Load DBeaver, under any database type (I tried both Teradata and Postgres), click Edit Connection -> General -> Filters -> Schemas/Users. 
2. Click "Enable", then create an Include or Exclude filter list. I created an Exclude of '%' to Filter everything.
3. Save the Filter list and press OK.
4. DBeaver offers to reconnect to database to apply new settings, press Yes to reconnect. 
5. Observe that new settings have been applied and the Filter is applied correctly. 
6. Restart DBeaver and connect to same database. 
7. Notice that Filter is NOT applied.

Thanks :)

**Comment by serge-rider** [comment] 2019-08-12 14:12
Duplicate of #6414
This bug was fixed in 6.1.4

**Closed by serge-rider** 2019-08-12 14:12 UTC
Labels: bug, duplicate

**Comment by RamonEbdon** [comment] 2019-08-13 04:05
Ah, apologies, DBeaver "check for updates" still wasn't showing that there was a newer version available, so didn't check in 6.1.4 first.

Cheers!
