### ISSUE TITLE
How to set the date format so that it doesn't change when importing the csv file to the dbever database column

### ISSUE THREAD

**Issue by rachmadhartono8** [dbeaver/dbeaver#17804] opened 2022-10-04 01:42 UTC
### Description

I have a problem importing csv data into DBeaver DBMS, when importing data, the date column changes from 2022-09-30 to 2022-09-29, what should I do to prevent this problem from recurring in my dbever, thanks

### DBeaver Version

Community Edition 22.1.3

### Operating System

mac.OS.Monterey 12.2.1

### Database and driver

1. Database Name MySQL

### Steps to reproduce

I have a problem importing csv data into DBeaver DBMS, when importing data, the date column changes from 2022-09-30 to 2022-09-29, what should I do to prevent this problem from recurring in my dbever, thanks

**Comment by Destrolaric** [comment] 2022-10-06 13:29
Hi, it looks similar to https://github.com/dbeaver/dbeaver/issues/16624, can you look at it?

**Comment by uslss** [comment] 2022-10-31 13:51
thanks for the report
closed as a duplicate of #16624

**Closed as completed by uslss** 2022-10-31 13:51 UTC
Labels: x:mysql, duplicate, xf:data, xf:datatransfer, wait for response

**Comment by rachmadhartono8** [comment] 2022-11-01 06:16
Thanks Sir and Mrs. That very help me

**Comment by johanyulian92** [comment] 2022-11-17 11:50
Thanks for the questions
