### ISSUE TITLE
Feature to make database name or a connection to fixed/pinned in Database Navigator

### ISSUE THREAD

**Issue by MaheshS08** [dbeaver/dbeaver#35979] opened 2024-10-17 09:45 UTC
**Is your feature request related to a problem? Please describe.**

I'm always confused when I am scrollin through schema objects in Database navigator in dbeaver I wish i knew to which Database it is in (ofcourse working with multiple servers is a bit confusing).

**Describe the solution you'd like**
I wanted to make database name or a connection to fixed/pinned whenever we scroll through all the Schema Objects in Database Navigator.

**Describe alternatives you've considered**

**Additional context**
Before scrolling in Database Navigator:
![image](https://github.com/user-attachments/assets/aa68db19-3f7b-4d49-9480-d1de8cb77e91)

After scrolling in Database Navigator:
![image](https://github.com/user-attachments/assets/f49e8e48-b194-4427-9b82-bfb9dd966b17)

Database name (master2) is going upward while scroll, I want it to be fixed.

**Comment by ask9** [comment] 2024-10-17 11:34
I also wish this.
It will be implemented here (see the last message) and subscribe for the topic: #35267

**Comment by E1izabeth** [comment] 2024-10-17 11:45
Thanks.
I'm closing it as a duplicate of #35267

**Closed as not planned by E1izabeth** 2024-10-17 11:45 UTC
Labels: duplicate, xf:navigator
