### ISSUE TITLE
Application Freezes When Exporting

### ISSUE THREAD

**Issue by k4rl0sA** [dbeaver/dbeaver#34830] opened 2024-07-16 00:14 UTC
### Description

When clicking on export, the export assistant opens but immediately closes. After this, the program freezes, and it is necessary to close it from the processes. This occurs with the Ubuntu 22.04.4 LTS operating system in DBeaver Community Edition Version 24.1.2.202407071610.

### DBeaver Version

24.1.2.202407071610

### Operating System

Ubuntu 22.04.4 LTS

### Database and driver

jdbc:mysql

[Grabación de pantalla desde 15-07-24 19:11:49.webm](https://github.com/user-attachments/assets/7638ee80-7b3c-4add-a68e-d2f79f8d32a9)

**Comment by E1izabeth** [comment] 2024-07-16 09:21
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by reger** [comment] 2024-07-16 20:06
I'm having the same issue, but I'm on a MacBook Pro M2 Pro running Sonoma 14.5. DBeaver version is 24.1.2.202407071610. I was not having this problem with the previous version. I believe I updated last week.

**Comment by reger** [comment] 2024-07-16 20:53
FYI, I went back to the previous version (24.1.1.202406231636) and exporting is back working as expected.

**Comment by E1izabeth** [comment] 2024-07-17 06:58
@reger, could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.
Unfortunately, for now we can't reproduce the issue.

**Comment by saroshmk** [comment] 2024-07-17 07:37
I'm facing the same issue too. Here are my log files
[dbeaver-debug.log](https://github.com/user-attachments/files/16261937/dbeaver-debug.log)
[hs_err_pid36678.log](https://github.com/user-attachments/files/16261942/hs_err_pid36678.log)

**Comment by reger** [comment] 2024-07-17 15:43
> @reger, could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/. Unfortunately, for now we can't reproduce the issue.

I'll try to find time to update to the broken version again and get logs. I'm in the middle of something on my project where I need a working version of DBeaver right now.

**Comment by E1izabeth** [comment] 2024-07-19 06:26
@k4rl0sA @saroshmk 
We made some changes that might fix the issue. However, we can't reproduce the issue to check, if it helps.
Could you try early access version and let me know about the results? You can download it here https://dbeaver.io/files/ea/

**Comment by k4rl0sA** [comment] 2024-07-19 13:10
If the freezing issue has already been resolved, thank you very much.

**Comment by reger** [comment] 2024-07-23 14:29
@E1izabeth this seems to be fixed in Version 24.1.3.202407211303, at least for me.

**Comment by E1izabeth** [comment] 2024-07-23 14:31
Thank you!

**Closed as completed** 2024-07-23 14:31 UTC
Labels: xf:datatransfer, xf:sql editor
