### ISSUE TITLE
Export From Query Dialog expands horizontally and becomes unusable

### ISSUE THREAD

**Issue by avishnyak** [dbeaver/dbeaver#34764] opened 2024-07-10 20:00 UTC
### Description

When attempting to use the Export Query Results dialog, it resizes horizontally and becomes unusable after about a second.

I have not customized scaling or changed default fonts.

See attached video.

https://github.com/dbeaver/dbeaver/assets/6599079/b32cefa5-e0f2-4ce3-abbb-bfaab3caf24c

### DBeaver Version

Community 24.1.2

### Operating System

macOS Sonoma 14.2.1 (23C71)

### Database and driver

Postgres

### Steps to reproduce

1. Connect to database
2. Highlight a query
3. Click "Export Query Results"

### Additional context

The export dialog starts out normal size, then resizes to some crazy horizontal width without any explanation.

**Comment by E1izabeth** [comment] 2024-07-10 20:09
Thank you for bug report.
I'm closing it as a duplicate of #34705
The fix is on the way.

**Closed as not planned** 2024-07-10 20:09 UTC
Labels: duplicate, xf:datatransfer, xf:ui
