### ISSUE TITLE
DBeaver application language changes to Spanish after update

### ISSUE THREAD

**Issue by hnavia** [dbeaver/dbeaver#20594] opened 2023-07-18 15:51 UTC
### Description

I have my Windows 11 OS in Spanish as it's my main language. However, I mostly work in English so I use DBeaver in English as well.

The bug/problem is that, after an update, the application language changes back to Spanish and I need to change the language manually and then restart the application.

I can provide logs and information as needed.

### DBeaver Version

Community Edition 23.1.2.202307091549

### Operating System

Windows 11 with latest updates

### Database and driver

Not related to DB

### Steps to reproduce

1. Launch DBeaver
2. Update the application if a new version appears
3. Restart DBeaver
4. The language will match the one of the OS, even if English has been selected manually (language goes back to Spanish)

**Comment by E1izabeth** [comment] 2023-07-19 11:52
Thank you for bug report.
I'm closing the issue as it's a duplicate of #17857

**Closed as not planned by E1izabeth** 2023-07-19 11:52 UTC
Labels: duplicate, xo:eclipse, third party issue
