### ISSUE TITLE
Advanced Copy > As Markdown -> does not use the column alias in paste result

### ISSUE THREAD

**Issue by m3c-ode** [dbeaver/dbeaver#34963] opened 2024-07-23 22:34 UTC
**Is your feature request related to a problem? Please describe.**
I wonder if it's a settings or not. but tried looking, and didn't find anything.
I would like the Copy and Paste feature to use the columns names given in the alias. 
It would make for some much more readable results.

**Describe the solution you'd like**
When giving alias to column names, would like them used in the paste result

**Describe alternatives you've considered**

**Additional context**

**Comment by MashaKorax** [comment] 2024-07-25 11:15
Hello @m3c-ode . Actually, Advanced Copy > As Markdown with column alias works for me. Please provide more details to reproduce the issue

https://github.com/user-attachments/assets/a5935936-5ae2-49a7-bcd9-1fb2e01f803c

**Comment by dstivanov** [comment] 2024-07-30 21:44
@MashaKorax I think that https://github.com/dbeaver/dbeaver/pull/35007 will solve this, isn't it ? 
cc @m3c-ode

**Comment by m3c-ode** [comment] 2024-07-31 15:43
It seems to work on a simple query as you display @MashaKorax 

But when I have a query with JOIN, it doesn't seem to be consistent.

![image](https://github.com/user-attachments/assets/25796259-31eb-481a-9e4f-b46d0d63d200)
![image](https://github.com/user-attachments/assets/1c9d8ef7-7d40-4730-8142-8c2e49fb23bb)
![image](https://github.com/user-attachments/assets/c29e8a27-2e6f-4f73-955f-4dc604bf9975)

**Comment by MashaKorax** [comment] 2024-08-06 17:55
I reproduced the issue.
It is fixed by PR https://github.com/dbeaver/dbeaver/pull/35007

**Closed as completed by MashaKorax** 2024-08-06 17:55 UTC
Labels: xf:data
