### ISSUE TITLE
Postgres driver download error maven

### ISSUE THREAD

**Issue by FMorschel** [dbeaver/dbeaver#34775] opened 2024-07-11 12:17 UTC
### Description

when I recently installed a DBeaver (some version previous to CE 24.1.2) it showed me the following error when trying to download Postgres drivers:

![image](https://github.com/dbeaver/dbeaver/assets/52160996/e8014041-1f93-4c70-9230-2d07654b86b1)

This simply tells me to uncheck this checkbox:

![image](https://github.com/dbeaver/dbeaver/assets/52160996/cd35eac0-d5a3-4afb-bb58-a3efe19753c1)

After restarting its all working to download the driver.

But in the last version (as of today) CE 24.1.2. This is what shows:

![Untitled](https://github.com/dbeaver/dbeaver/assets/52160996/8c657e47-1d8b-460a-89a1-8e184c705cd3)

Randomly while trying to download, I got more info on the error:

```
Network unavailable
java.io.IOException:Exception during a connection to https://repo1.maven.org
  Error resolving dependencies
    Exception during a connection to https://repo1.maven.org/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
      Exception during a connection to https://mvnrepository.com/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
        Exception during a connection to https://oss.sonatype.org/content/repositories/snapshots/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
          Exception during a connection to https://repo1.maven.org/maven2/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
            Exception during a connection to https://repo1.maven.org/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom
              Exception during a connection to https://mvnrepository.com/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom
                Exception during a connection to https://oss.sonatype.org/content/repositories/snapshots/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom
                  Exception during a connection to https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom
```

### Edit

I was able to install everything with no issue (just the above mentioned need to uncheck that box) with the installer for version CE 23.3.5.

### DBeaver Version

Community Edition 24.1.2

### Operating System

Microsoft Windows Server 2022 Standard

### Database and driver

None at this point.

### Steps to reproduce

1. Click to create a Postgres DB. 
2. Click on the "Driver properties" tab and download.

**Comment by ShadelessFox** [comment] 2024-07-11 12:43
Hello @FMorschel,

Did you install the newer version using the installer? Perhaps you have unchecked the option called "Include Java" during the installation?

**Comment by FMorschel** [comment] 2024-07-11 12:44
Yes I did install with the latest Windows installer. 

Sorry but I did not change any default options in the installer.

**Comment by ShadelessFox** [comment] 2024-07-11 14:27
Can you manually open URLs from the error message in your browser? Do all of them open fine?

**Comment by FMorschel** [comment] 2024-07-11 15:30
## The ones that open

Both that machine and my personal computer:
- https://repo1.maven.org
- https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom
- https://repo1.maven.org/maven2/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom

Only my personal computer:
- https://oss.sonatype.org/content/repositories/snapshots/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
- https://oss.sonatype.org/content/repositories/snapshots/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom

## The ones that do not

Both that machine and my personal computer:
- https://repo1.maven.org/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
- https://mvnrepository.com/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
- https://repo1.maven.org/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom
- https://mvnrepository.com/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom

Only on said machine:
- https://oss.sonatype.org/content/repositories/snapshots/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
- https://oss.sonatype.org/content/repositories/snapshots/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom

## Every type of error I got

![image](https://github.com/dbeaver/dbeaver/assets/52160996/b01627b6-5809-4403-9b49-0606cd9d662c)
![image](https://github.com/dbeaver/dbeaver/assets/52160996/b7bd8d48-837f-4026-a6e9-6edca9b96b3d)
![image](https://github.com/dbeaver/dbeaver/assets/52160996/c94ca263-93e1-4f60-afff-f5d88c395492)

**Comment by FMorschel** [comment] 2024-07-16 11:51
Just to be explicit: both machines are not in the same network. 

But my point here stands that when doing the same steps with the previous version, I got a warning to uncheck that security verification and by doing so, everything was downloaded just fine.

**Comment by Destrolaric** [comment] 2024-07-18 12:42
@FMorschel Hi, do you use Java with the DBeaver, it might be an issue with java truststore?

**Comment by FMorschel** [comment] 2024-07-18 12:52
Hi!

> [...] do you use Java with the DBeaver [...]?

I'm not sure but I think so.

> [...] it might be an issue with java truststore?

I'm not familiar with Java Truststore, not a Java dev. What can I do to help you in helping me? Can you point me to any docs so I can meet you with more basic knowledge in common that relates to this problem?

**Comment by degger80** [comment] 2024-07-23 11:06
Same problem. Fresh install on windows.

```
Network unavailable
java.io.IOException:Exception during a connection to https://repo1.maven.org
  Error resolving dependencies
    Exception during a connection to https://oss.sonatype.org/content/repositories/snapshots/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
      Exception during a connection to https://repo1.maven.org/maven2/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
        Exception during a connection to https://oss.sonatype.org/content/repositories/snapshots/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom
          Exception during a connection to https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom

```

**Comment by JavaProgswing** [comment] 2024-07-29 17:47
I have the same issue since I fresh installed DBeaver.

**Comment by nrbrt10** [comment] 2024-08-04 04:28
Also having this issue. I'm trying to connect to a postgress 16 DB:

Network unavailable
java.io.IOException:Exception during a connection to https://repo1.maven.org
  Error resolving dependencies
    Exception during a connection to https://oss.sonatype.org/content/repositories/snapshots/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
      Exception during a connection to https://repo1.maven.org/maven2/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
        Exception during a connection to https://oss.sonatype.org/content/repositories/snapshots/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom
          Exception during a connection to https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom

The ones I'm having trouble opening are these two:
https://oss.sonatype.org/content/repositories/snapshots/com/github/waffle/waffle-jna/1.9.1/waffle-jna-1.9.1.pom
https://oss.sonatype.org/content/repositories/snapshots/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.pom

Browsing the sites for postgres I can't find a 42.7.2 snapshot
![image](https://github.com/user-attachments/assets/ba8c93bf-4b8d-474a-8ea7-91ad7303faa2)

Similarly for waffle-jna I can't find a 1.9.1 snapshot
![image](https://github.com/user-attachments/assets/3326c9dc-08c7-41b8-b1c3-b8b6587d435f)

Admittedly I'm a bit out of my depth here but this is as far as I was able to go.

**Comment by AndreSchulz-IONOS** [comment] 2024-08-05 13:31
work-around:
- go to Driver Manager - PostgreSQL
- remove all libraries
- add file https://jdbc.postgresql.org/download/postgresql-42.7.3.jar (download first)

**Comment by mohamed-montaser91** [comment] 2024-08-05 15:52
I'm having the same error, fresh installtion of dbeaver

**Comment by nrbrt10** [comment] 2024-08-05 18:19
> work-around:
> 
>     * go to Driver Manager - PostgreSQL
> 
>     * remove all libraries
> 
>     * add file https://jdbc.postgresql.org/download/postgresql-42.7.3.jar (download first)

This worked for me, thank you.

**Comment by FMorschel** [comment] 2024-08-05 18:47
Just another work-around if anyone is interested or if the above doesn't work for some reason (I [commented above](https://github.com/dbeaver/dbeaver/issues/34775#issuecomment-2230698036)):

> [...] doing the same steps with the previous version [[CE 23.3.5](https://dbeaver.io/files/23.3.5/)], I got a warning to uncheck that security verification and by doing so, everything was downloaded just fine.

After downloading the drivers, I simply updated my dbeaver.

**Comment by Kritik29** [comment] 2024-08-06 18:32
I get this same issue when trying to connect to an Azure SQL database.... anybody have any ideas?

**Comment by eclipse7723** [comment] 2024-08-11 21:40
Go to Preferences and disable "Use Windows trust store". It worked for me. But if not, try to download 24.1.0 version.

**Comment by bakyeono** [comment] 2024-08-19 19:11
> Go to Preferences and disable "Use Windows trust store". It worked for me. But if not, try to download 24.1.0 version.

+1 in Windows 11
Disable it and restart the app.

**Comment by clibercastillo** [comment] 2024-09-03 16:56
Vaya a Preferencias y desactive la opción "Usar el almacén de confianza de Windows". A mí me funcionó

**Comment by falvarezcolq** [comment] 2024-09-05 13:15
> Go to Preferences and disable "Use Windows trust store". It worked for me. But if not, try to download 24.1.0 version.

1. Ve a preferencias > conexiones 
2. el cuadro de security , desactiva Use Window trust store 
3. Cerrar Dbeaver y volver a abrir 

Me funciono Gracias

**Comment by TanyaShey** [comment] 2024-09-17 20:15
I had the same issue when I tried to add a mySQL db on a freshly installed dBeaver today (on a new machine) with default settings. I managed to correct it by going to Preferences and disabled "Use Windows trust store", then restarted the app.

**Comment by daltonpfdev** [comment] 2024-09-20 14:40
In 2024-09-20 I downloaded DBeaver version 24.2.0 and had the same problem with Maven dependencies. But in my case when trying to download the MariaDB driver. I solved my problem by DISABLING the option: 
Window -> Preferences -> Connections -> Use Windows trust store.

I only have java openSDK 17.0.2 installed on my WSL2 Ubuntu 24.04.

**Comment by sankarst** [comment] 2024-09-24 23:11
I faced the same issue. Here are the steps to resolve on Mac.
First download PostgreSQL driver from https://jdbc.postgresql.org/download/

"Database"-> "Driver Manager" -> select "PostgreSQL" -> "Edit" -> "Libraries"
1. Delete everything present there
2. Click "Add File" -> select the driver downloaded and click "OK"
3. Close the "Driver Manager" window and restart the DBeaver tool

Now the DB connection starts to work.

**Comment by serge-rider** [comment] 2024-09-25 13:49
Potentially this may happen if Windows root certificate storage doesn't contain CA for GlobalSign (it is the CA for root Maven repository).

By default DBeaver uses Windows cert storage (because it may contain non-standard corporate certificates).
Disabling checkbox "Use Windows trust-store" forces internal DBeaver Java trust store (which contains all standard certificates).

If your browser opens links like https://repo1.maven.org/maven2 then driver download should work in DBeaver with enabled "Use Windows trust store".

**Comment by FMorschel** [comment] 2024-09-25 13:53
@serge-rider thanks for the explanation.

The reason I opened this issue is because on previous versions I got a reasonable message telling me to disable that check, now it doesn't show that message anymore.

See https://github.com/dbeaver/dbeaver/issues/34775#issuecomment-2230698036:

> But my point here stands that when doing the same steps with the previous version, I got a warning to uncheck that security verification and by doing so, everything was downloaded just fine.

**Comment by serge-rider** [comment] 2024-09-25 15:52
@FMorschel thanks for the clarification
We'll try to fix it

**Comment by timothydilbert** [comment] 2024-09-26 14:26
> I had the same issue when I tried to add a mySQL db on a freshly installed dBeaver today (on a new machine) with default settings. I managed to correct it by going to Preferences and disabled "Use Windows trust store", then restarted the app.

This fixed my issue as well. Thank you.

**Closed as completed** 2024-09-27 16:14 UTC
Labels: xp:major, xf:connection

**Comment by JayDS22** [comment] 2024-10-19 18:12
> work-around:
> 
> * go to Driver Manager - PostgreSQL
> * remove all libraries
> * add file https://jdbc.postgresql.org/download/postgresql-42.7.3.jar (download first)

This did work. Thank You!!

**Comment by richardschoen** [comment] 2025-04-18 16:14
Just ran into this same issue. Thanks for this. Solved it for me as well on Windows Server 2022.

**Comment by palitshubhankar** [comment] 2025-04-28 15:15
> > work-around:
> > 
> > * go to Driver Manager - PostgreSQL
> > * remove all libraries
> > * add file https://jdbc.postgresql.org/download/postgresql-42.7.3.jar (download first)
> 
> This did work. Thank You!!

**Comment by robinwilson16** [comment] 2025-10-26 09:06
This issue is still happening on a fresh Windows 11 install, fresh Java 21 install on a local machine, a work machine and an Azure machine (Windows Server 2025).
The error message still doesn't tell you to uncheck that box whilst unchecking that box does fix it.

I can browse to the URLs myself without any certificate errors.
Is it possible to revert to being a useful error like it used to be and tell you to untick the box, or even better default to the box not being ticked if it never works when ticked.

Not sure why the issue is closed as it seems the issue is still occurring as far as I can tell.

**Comment by serge-rider** [comment] 2025-10-29 06:38
@robinwilson16 I cannot reproduce this. How does the error message looks on your side?

**Comment by robinwilson16** [comment] 2025-11-01 01:22
@serge-rider this is how it looks: 

<img width="676" height="601" alt="Image" src="https://github.com/user-attachments/assets/658a2e57-16b7-481f-a74f-6f5f2919b44e" />

Just trying it again on a different server hosted on Azure.

**Comment by robinwilson16** [comment] 2025-11-01 01:26
If I turn this off then it works:

<img width="659" height="567" alt="Image" src="https://github.com/user-attachments/assets/5f6b47cc-dc8e-4033-be39-29107ec58477" />

Now it downloads and connects (after closing and reopening it after making the change above):

<img width="417" height="196" alt="Image" src="https://github.com/user-attachments/assets/5c38f9c6-0604-4482-a000-7a7160f4a238" />
