### ISSUE TITLE
Error in SSH Tunnel Reconnection

### ISSUE THREAD

**Issue by dpeytorr** [dbeaver/dbeaver#8083] opened 2020-03-04 11:28 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise 
- DBeaver version:  6.3.5.202002151353
- Additional extensions - None

#### Connection specification:
- Database name and version:  PostreSQL 3.5
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - SHH Tunnel

#### Describe the problem you're observing:
When I open  a connection to PostrgeSQL DDBB it works.
I have several environments (DEV, PRE, PROD), while I'm working I use to switch between them, previously within problem. 

Since I updated to the last version, while I'm working (at some moment, sometimes soon sometimes later), when I switch and I try to return to a previous environment, the connection can't be reestablished, returning the error:

_Can't open editor connection

Reason:
Connection to 127.0.0.1:24242 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections._

I tried to Disconnect and reconnect but it doesn't work.  I need to stop Dbeaver, and then the Connection works again.

#### Steps to reproduce, if exist:
They are not always the same.
Launch several queries, updates in on environment, switch to another. Go to another program for 2 houres, return and try to connect to the first environemnt.

**Comment by uslss** [comment] 2020-03-05 09:53
hi @dpeytorr ,
could you try if issue is reproducible against 7.0.0 for you?
seems to be duplicate of #7952

**Closed** 2020-03-16 10:54 UTC
Labels: bug, duplicate, wait for response
