### ISSUE TITLE
Add CREATE OR ALTER syntax for SQL Server.

### ISSUE THREAD

**Issue by linxpatrick** [dbeaver/dbeaver#22518] opened 2024-01-19 20:32 UTC
Microsoft has added CREATE OR ALTER (view, proc, etc.) to it's syntax. dBeaver strips OR ALTER from the line and leaves spaces behind. Please add CREATE OR ALTER as a valid syntax to dBeaver.

**Comment by E1izabeth** [comment] 2024-01-21 21:09
Thank you for suggestion

**Comment by LonwoLonwo** [comment] 2024-03-19 17:37
Hello @linxpatrick 

We already have the ALTER syntax for procedures, functions, views, and triggers.

![2024-03-19 18_31_44-Window](https://github.com/dbeaver/dbeaver/assets/45152336/2ac659ef-1e35-4187-8d74-166a38ce096d)

![2024-03-19 18_32_43-Window](https://github.com/dbeaver/dbeaver/assets/45152336/e15ce501-f2b1-4719-a7f0-ed2c43b151de)

![2024-03-19 18_33_28-Window](https://github.com/dbeaver/dbeaver/assets/45152336/9f9da7b5-fb2c-407d-a5ff-28116dd3c1d3)

![2024-03-19 18_35_15-Window](https://github.com/dbeaver/dbeaver/assets/45152336/9452fd7a-2c28-4a59-84e5-1ce1f471fe1b)

And I do not see the point in changing these objects' DDLs because DBeaver reads them from the database directly.

So, what exactly do you want? Please provide more info.

**Comment by linxpatrick** [comment] 2024-03-19 21:39
Microsoft has added the combination statement "CREATE OR ALTER" to 
views, stored procedures and other objects. dBeaver strips out the "OR 
ALTER" portion of the command.

I'm using dBeaver today and the issue seems to have been resolved in a 
recent update.



*/Patrick Headley/*
Linx Consulting, Inc.
(303) 916-5522
***@***.***
www.linxco-inc.com

**Comment by LonwoLonwo** [comment] 2024-03-20 09:53
> dBeaver strips out the "OR
> ALTER" portion of the command.

Yes, I can't reproduce this part.

Can I close the issue then?

**Comment by linxpatrick** [comment] 2024-03-20 18:24
Yes. You may close the issue.

**Closed as completed** 2024-03-21 08:44 UTC
Labels: enhancement, x:mssql, xf:sql, sp:1, xf:metadata
