### ISSUE TITLE
Newline and even semicolon sometimes ignored as end marker

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#26843] opened 2024-04-26 08:29 UTC
### Description

```
SELECT *
FROM foo
WHERE 1=1

AND bar=1
```

does not execute, but errors out with  
`SQL Error [42601]: ERROR: syntax error at or near "AND"`  

```
SELECT *
FROM foo
WHERE 1=1;

AND bar=1
```

yields the same error.
Doesn't happen always and not in every editor. 

### DBeaver Version

Version 24.0.3.202404211624

### Operating System

Debain/Linux

### Database and driver

Postgres 15, PostgreSQL JDBC Driver, cannot find more info in DBeaver.

**Comment by E1izabeth** [comment] 2024-04-26 08:37
Thank you for bug report. It's a duplicate of #26416
We're working on fix

As a workaround, you could try switching `Blank line is statement delimiter` setting to `Always`
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be8457a0-d62c-4acb-ac2f-67ce518cf3f5)

**Closed as not planned by E1izabeth** 2024-04-26 08:37 UTC
Labels: duplicate, xf:sql execution
