### ISSUE TITLE
Filter autocomplete bug for uppercase fild names (PostgreSQL)

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#3684] opened 2018-06-26 06:49 UTC
5.1.1

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3856344/41893859-c7763630-7925-11e8-9e82-0980fcbb265a.gif)

Bug when select item with press Enter. When click mouse - norm.

**Comment by serge-rider** [comment] 2018-06-29 21:02
Duplicate of #3656

**Closed by serge-rider** 2018-06-29 21:02 UTC
Labels: bug, duplicate
