### ISSUE TITLE
Comment in header barely visible in dark mode

### ISSUE THREAD

**Issue by DavidHJong** [dbeaver/dbeaver#23062] opened 2024-03-06 01:46 UTC
### Description

In dark mode, the comment in header is barely visible and, when selected, almost invisible. 
![image](https://github.com/dbeaver/dbeaver/assets/31554275/cc23d54c-4c9f-426b-9c39-0cde727ed2c5)

### DBeaver Version

Community Ediction 24.0.0

### Operating System

Windows 10 Pro 19045.4046

### Database and driver

Database name and version: PostgreSQL 15.5
Driver name and version: PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

1. enable `show comment in header` throught `
top menu: windows > preferences > editors > data editor > appearance > show column description in header`.
2. enable dark mode through ` top menu: windows > preferences > user interface > appearance > theme`. 
3. add a comment to a column.

**Comment by E1izabeth** [comment] 2024-03-06 05:02
Thank you for bug report. It's a duplicate of #19972
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-03-06 05:02 UTC
Labels: duplicate, xf:dark theme
