### ISSUE TITLE
Close idle connection reactivates

### ISSUE THREAD

**Issue by Dorregaray1** [dbeaver/dbeaver#22796] opened 2024-02-13 07:39 UTC
### Description

There are two connected problems:
- Since last update, with every start of the dBeaver, in connection properties the "Close idle connection after (seconds)" checkbox is always reactivated (value 3600 s.).

- When manual commiting is set, it tries to close idle transaction every 10 seconds.
![pic1](https://github.com/dbeaver/dbeaver/assets/18217565/8ca9458d-652e-4c64-ad37-1d60d568e748)
With this two problems, everytime I start beaver, i have to disable property "Close idle transaction...", otherwise it´s impossible to work within manual commit mode - every 10 seconds window 
![pic2](https://github.com/dbeaver/dbeaver/assets/18217565/9905c6b0-442f-40a1-beb1-7d0faedb9244)

### DBeaver Version

Community 23.3.4

### Operating System

Windows 10

### Database and driver

Postgres jdbc 42.5.2

### Steps to reproduce

Problem 1:
1. Connect to db postgres. - Connection settings to postgres having connection type setting like in the picture. Close idle transaction is ON. Seconds = 3600.
![pic2](https://github.com/dbeaver/dbeaver/assets/18217565/9905c6b0-442f-40a1-beb1-7d0faedb9244)
2. Deactivate the checkbox "Close idle transaction connection after" in appropriate connection type.
3. Restart dBeaver a connect to database. Connection setting "Close idle transaction is on" again.

Problem 2:
1. Connect to db postgres - Connection settings to postgres having connection type setting like in the picture above. Close idle transaction is ON.  Seconds = 3600.
3. Do any select to the database using script. (select * from test_table;)
4. In few seconds dBeaver tries to close connection (10 second counter) almost immidiately, although setting is 3600 sec.

![pic1](https://github.com/dbeaver/dbeaver/assets/18217565/8ca9458d-652e-4c64-ad37-1d60d568e748)

**Comment by E1izabeth** [comment] 2024-02-13 07:56
Thank you for bug report. It looks like a duplicate of #22721. The issue was solved and the fix is available in the Early access version https://dbeaver.io/download/ea
Could you try it?

**Closed as not planned** 2024-02-14 09:51 UTC
Labels: duplicate, xf:connection
