### ISSUE TITLE
Paste as Row Condition Where

### ISSUE THREAD

**Issue by gtdegamo** [dbeaver/dbeaver#14194] opened 2021-10-11 19:25 UTC
**Is your feature request related to a problem? Please describe.**

I use dbeaver for investigative work using queries.  Often times I need to select a few fields from a row in the result set and use the values from the 'sub-row' in part of the where clause for a new query.  Entering that information is time consuming and error prone.  It be nice if dbeaver can do it for me.

**Describe the solution you'd like**

Suppose I want to select the following values from the result set (displaying only relevant fields below):

| Col3 | Col5 | Col7 |
|------|-------|------|
|   a    |    b    |   c    |
|   r    |    s     |   t    |
|   x   |    y     |   z    |

I'd like to be able to past the selection into the sql console as the string:

"
(Col3 = a  and Col5 = b and Col7 = c)
or
(Col3 = r  and Col5 = s and Col7 = t)
or
(Col3 = x  and Col5 = y and Col7 = z)
"

dbeaver should mind the type on the columns.  So if the column is a string, the value should be quoted.  Handling dates would be nice, but handling strings and numbers would be a great start.

**Describe alternatives you've considered**

Right now, I have to do this by hand.

**Additional context**

None.  Keep up the great work.

**Comment by ShadelessFox** [comment] 2021-10-13 13:07
Hello @gtdegamo,

Will be fixed along with #14193 since the issue is the same.

**Closed as completed by ShadelessFox** 2021-10-13 13:07 UTC
Labels: xf:sql, xf:data
