### ISSUE TITLE
postgresql9.6 TAN(45 * Pi()/180) = 0.9999999999999999 not 1

### ISSUE THREAD

**Issue by cooltnt** [dbeaver/dbeaver#12684] opened 2021-06-01 08:50 UTC
#### System information: 
- Operating system (distribution) and version
- win10
- DBeaver version    
- 21.1.0.202105300349
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
database: postgresql9.6
run  select TAN(45 * Pi()/180)  result is 0.9999999999999999 not 1 
also
select COS(60 * Pi()/180)  result is 0.5000000000000001 not 0.5

but in pgAdmin4 this all correct

**Comment by ShadelessFox** [comment] 2021-06-01 12:18
Hello @cooltnt,

I cannot reproduce your issue:
![image](https://user-images.githubusercontent.com/35821147/120320850-52f7b280-c2eb-11eb-8fcc-19b80d714784.png)

But in pgAdmin4 the issue is present:
![image](https://user-images.githubusercontent.com/35821147/120321698-49bb1580-c2ec-11eb-98fd-c02216189956.png)

This phenomenon is called rounding error. Some numbers cannot be simply represented in binary.
It may depend on the server settings, driver you're using and the database itself.

Perhaps I misunderstood you? If so, then please correct me and provide actual and expected behavior.

**Comment by ShadelessFox** [comment] 2021-06-01 12:23
If you're expecting the same results as shown in pgAdmin4, you can change number formatter settings:
![3JRVLF8psJ](https://user-images.githubusercontent.com/35821147/120322530-2cd31200-c2ed-11eb-9479-e770d03a01ec.png)

By doing so, the results are following:
![java_a5YcjRxHuc](https://user-images.githubusercontent.com/35821147/120322613-44aa9600-c2ed-11eb-906b-026be3df53b7.png)

Let me know if your problem was solved.

**Comment by cooltnt** [comment] 2021-06-02 05:39
First of all Thank you for your  attention！ @ShadelessFox 
1、dbeaver and pgAdmin connect to then same database， in my place， pgAdmin results is  1,  0.5 
2、dbeaver  number formatter settings  by default setting( unselected )， I tried set selected  before， but the results did not change （also 0.999999, 0.500000000000001）
3、Current drivers , dbeaver Automatic installation , I doubt it ，Let me try to change it
![image](https://user-images.githubusercontent.com/41370387/120428914-16898c80-c3a7-11eb-91b2-8c3f0336d273.png)

**Comment by ShadelessFox** [comment] 2021-06-02 08:18
In that case, you can manually adjust amount of fraction digits in the formatter mentioned previously:

![image](https://user-images.githubusercontent.com/35821147/120448029-d10f9400-c393-11eb-9bb6-85baa16d7848.png)

Try setting this value to `3`, for example.

**Comment by cooltnt** [comment] 2021-06-03 02:40
@ShadelessFox
The problem is solved !    I didn't know the reason before.  I checked it .
Maybe want to keep the data in its original state， Because the default setting truncates the number of decimal places.

now setting by default  
![image](https://user-images.githubusercontent.com/41370387/120574851-9e78a080-c452-11eb-8f3e-eca7210e53c7.png)

 results is correct
![image](https://user-images.githubusercontent.com/41370387/120575190-29f23180-c453-11eb-9646-8e7687c2af1e.png)

**Comment by ShadelessFox** [comment] 2021-06-03 06:16
I will close the issue then. You still can ask related questions here!

**Closed as completed by ShadelessFox** 2021-06-03 06:16 UTC
