### ISSUE TITLE
SSH with (outdated) JSch plugin can't connect to Ubuntu 2022

### ISSUE THREAD

**Issue by matke2002** [dbeaver/dbeaver#17312] opened 2022-08-09 10:30 UTC
### Description

Hi, 
I'm not able to create SSH tunneling connection using private key to one Ubuntu 2022 server. I get error "Auth failed" with correct key. 
I had the same issue with Filezilla, Putty ... and issue was solved with the latest version.
I see that DBeaver is using https://mvnrepository.com/artifact/com.jcraft/jsch , last update 4 years ago (or modification 3 years old). I assume that issue is in outdated plugin.

### DBeaver Version

22.1.4.202208051447 Community Edition

### Operating System

Windows 10

**Comment by E1izabeth** [comment] 2022-08-09 20:43
@matke2002, have you tried to use SSHJ?
![image](https://user-images.githubusercontent.com/28875055/183757043-a841e2fe-ed25-4259-9b5d-31e7383adccf.png)

**Comment by matke2002** [comment] 2022-08-10 11:35
Hi @E1izabeth,
with SSHJ I get connection timeout.

**Comment by E1izabeth** [comment] 2022-08-10 11:47
DBeaver uses the latest Jsch version. JSch seems not to be updated anymore.

I guess this issue is a duplicate of https://github.com/dbeaver/dbeaver/issues/14749

**Closed as not planned** 2022-08-10 11:50 UTC
Labels: duplicate
