### ISSUE TITLE
Start under Windows Server 2016 fails w/ "Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library."

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#35843] opened 2024-10-07 11:03 UTC
### Description

DBeaver installed into a shared home folder on a Win 2016 server. Plain installatzion from dbeaver.io -- included Java and everything.
Updated in September, but did not use until today.
Starting today failed with the error
`Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library.`

Downloaded most recent dbeaver-ce-24.2.2-x86-64.exe and installed over existing installation.
Issue persists, log from starting the new installation available.

Relevant part:
```
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
	\\<SERVER>\<SHARE>\<USER>\Desktop\dbeaver\swt-win32-4966r5.dll: Die angegebene Prozedur wurde nicht gefunden
	no swt-win32 in java.library.path: <PATH>
	no swt in java.library.path: <PATH>
	Can't load library: C:\Users\user\.swt\lib\win32\x86_64\swt-win32-4966r5.dll
	Can't load library: C:\Users\user\.swt\lib\win32\x86_64\swt-win32.dll
	Can't load library: C:\Users\user\.swt\lib\win32\x86_64\swt.dll
```
`<PATH>` starts with the installation path of DBeaver where `swt-win32-4966r5.dll` exists. (Thus `java.library.path` IMO contains a valid DLL and that should have been loaded)
`C:\Users\user\.swt\lib\win32\x86_64\` is empty.

Looks like the look-up of DLLs is broken, or at least the included DLLs are.

### DBeaver Version

CE 24.2.2

### Operating System

Windows Server 2016

### Steps to reproduce

1. Start DBeaver
2. See "An error has occured. See the log file \\<SERVER>\<SHARE>\<USER>\Desktop\dbeaver\configuration\17...log"

**Comment by arhayka** [comment] 2024-10-07 11:36
Thank you for the bug report.
I'm closing it as it's a duplicate of https://github.com/dbeaver/dbeaver/issues/35694

**Closed as not planned by arhayka** 2024-10-07 11:36 UTC
Labels: duplicate

**Comment by E1izabeth** [comment] 2024-10-07 11:38
The issue comes from the platform on which DBeaver is based.
Here are 2 options that might help:
- Downgrade DBeaver to 24.2.0
- Try upgrading Windows until it works. If no additional minor upgrades are available, upgrade to a higher major release of Windows. Experiments show that at least Windows Server 2022 works.
