### ISSUE TITLE
clickhouse DateTime64 import and copy and export sql error

### ISSUE THREAD

**Issue by mj520** [dbeaver/dbeaver#16863] opened 2022-06-23 08:04 UTC
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

CREATE TABLE default.sites
(
    `id` Int32,
    `last_order_time` DateTime64(3) COMMENT '最后出单时间-新增',
    `dt` DateTime COMMENT '时间'
)
ENGINE = MergeTree
PRIMARY KEY id
ORDER BY id
SETTINGS index_granularity = 8192;

insert into default.sites (id,last_order_time,dt) values (1,1655956585300,1655956585),
(2,'2022-06-22 00:00:00.020','2022-06-22 00:00:00'),
(3,'2022-06-21 00:00:00.001','2022-06-21 00:00:00');

import csv、excel、sync  error
"id","last_order_time","dt"
1,"2022-06-23 03:56:25.300","2022-06-23 03:56:25"
2,"2022-06-22 00:00:00.020","2022-06-22 00:00:00"
3,"2022-06-21 00:00:00.001","2022-06-21 00:00:00"

Error occurred during 批量插入
（您可以禁用批量插入以跳过特定行）。
原因：
 Object parameter [2022-06-23 03:56:25.300] binding not supported

copy.sql is not Quotation marks
INSERT INTO `select * from default.sites` (id,last_order_time,dt) VALUES (1,2022-06-23 03:56:25.300,'2022-06-23 03:56:25');
INSERT INTO `select * from default.sites` (id,last_order_time,dt) VALUES (2,2022-06-22 00:00:00.020,'2022-06-22 00:00:00');
INSERT INTO `select * from default.sites` (id,last_order_time,dt) VALUES (3,2022-06-21 00:00:00.001,'2022-06-21 00:00:00');

dbeaver version 21 or 22

**Comment by E1izabeth** [comment] 2022-06-23 11:45
Enabling _Skip bind values during insert_ results in another error:
` Code: 62. DB::Exception: Cannot parse expression of type DateTime64(3) here: 2022-06-23 03:56:25.300,'2022-06-23 03:56:25.000'): While executing ValuesBlockInputFormat. (SYNTAX_ERROR) (version 22.1.3.7 (official build))`

**Comment by LonwoLonwo** [comment] 2022-06-23 12:10
Thanks for the report @mj520

**Comment by emironovDB** [comment] 2022-09-05 09:56
Close as a duplicate of #17479

**Closed as not planned by emironovDB** 2022-09-05 09:56 UTC
Labels: duplicate, xf:sql, xf:data, x:clickhouse
