### ISSUE TITLE
Incorrect partial index scripting (DDL)

### ISSUE THREAD

**Issue by gogosofta** [dbeaver/dbeaver#2876] opened 2018-01-26 10:37 UTC
Here's how to reproduce:

```
create table t1(a int, b int, deleted boolean not null default false);
create unique index ix_t1_uk on t1(a, b) where deleted=false;
```

Look at the table's DDL in DBeaver:
```
CREATE TABLE t1 (
	a int4,
	b int4,
	deleted bool DEFAULT false NOT NULL
) ;
CREATE UNIQUE INDEX ix_t1_uk ON t1 (a,b) ;
```
The above 'create index' statement is missing the 'where deleted=false' clause and is therefore incorrect. 
Thus it will produce unexpected/unwanted behaviour when implemented.

**Comment by serge-rider** [comment] 2018-01-29 00:27
Can't reproduce (DDL contains index condition). This is similar to #2843 .
Perhaps you are using `PostgreSQL Generic` driver  or even manually create PG driver.
In order to support all PG features you need to use regular PostgreSQL driver.

**Comment by gogosofta** [comment] 2018-01-29 07:58
I'm using PG 9.4.11, but ... yes it's the Generic driver and that's because I can't use the regular... If you remember, I've reported in the past that DBeaver hangs on occasion when connecting to the PG DB. Your investigations showed that happens because of the huge number of relations in the database, thus I'm forced to use the Generic driver.

**Comment by serge-rider** [comment] 2018-01-29 08:11
Yep, I remember. This issue (with huge number of relations) is tracked in #2102. Hopefuuly will be ready in 3.4.5 or at least 5.0.
In any case Generic driver can't support native PG features. Closing.

**Closed by serge-rider** 2018-01-29 08:11 UTC
Labels: can't reproduce, question
