### ISSUE TITLE
One-line execution and SAVEPOINT do not work

### ISSUE THREAD

**Issue by DevNirsa** [dbeaver/dbeaver#29317] opened 2024-05-03 03:37 UTC
### Description

**Problem 1**
If you use the latest version, 'Ctrl+Enter' doesn't work properly. If there is a specific query (e.g., 'CREATE TABLE'), everything gets executed, leading to errors. To execute a specific query (e.g., 'INSERT'), you need to drag and highlight it, then use 'Ctrl+Enter' to execute it line by line.

**Problem 2**
also 'SAVEPOINT' doesn't work correctly. When you try to use 'ROLLBACK' to return to a 'SAVEPOINT', it instead goes back to the last COMMIT point. However, if you downgrade to version 23.2.2, it can properly return to the 'SAVEPOINT'.

### DBeaver Version

24.0.0

### Operating System

Windows10, 11, MacOS

### Database and driver

Database : Oracle 21c and 11g

### Steps to reproduce

**Problem 1**

CREATE TABLE DDL_FREE_BOARD(
	BOARD_NO NUMBER NOT NULL UNIQUE,
	BOARD_TITLE VARCHAR2(100) NOT NULL,
	BOARD_CONTENT CLOB NOT NULL,
	BOARD_DATE DATE,
	BOARD_VIEWS NUMBER
);

INSERT INTO DDL_FREE_BOARD dfb VALUES(1, '제목', '내용', sysdate, 0);
INSERT INTO DDL_FREE_BOARD dfb VALUES(1, '제목1', '내용2', sysdate, 0);
SELECT * FROM DDL_FREE_BOARD dfb ;

-----------------------------------------------------------------

**Problem 2**

INSERT INTO hr.JOBS j values('TEST', 'TEST_TITLE', 20000, 40000);
SAVEPOINT sp1;

DELETE FROM hr.jobs;

ROLLBACK TO sp1;   -- not work

**Comment by E1izabeth** [comment] 2024-05-03 05:13
Duplicate of https://github.com/dbeaver/dbeaver/issues/26416
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Closed as not planned by E1izabeth** 2024-05-03 05:13 UTC
Labels: duplicate, xf:sql execution
