### ISSUE TITLE
Color code databases (custom colors)

### ISSUE THREAD

**Issue by amivag** [dbeaver/dbeaver#34574] opened 2024-06-30 11:17 UTC
Example scenario: I have 2 databases under the same connection. One is the production db, the other is for testing... it's a direct replica of the production db.

With multiple tabs open, it often leads to errors to which table is being edited (user error, but it's not clear enough).

It would help immensely, if we could color code a database, so that all tabs receive a hint of that color as well, and make it a lot clearer what we're editing at any given time.

Thanks!

**Comment by ask9** [comment] 2024-06-30 16:27
You can change color of connection in its properties, see parameter "Connection type".
![0000002672](https://github.com/dbeaver/dbeaver/assets/33929221/c1463358-4099-4bd5-aa71-6eda3ec9a56a)

**Comment by E1izabeth** [comment] 2024-07-01 05:36
Thank you for idea. I'm closing this issue as a duplicate of #16827

**Closed as not planned by E1izabeth** 2024-07-01 05:36 UTC
Labels: duplicate, xf:ui, xf:sql editor
