### ISSUE TITLE
how to remove the '`' on the csv header

### ISSUE THREAD

**Issue by Dookie78** [dbeaver/dbeaver#6823] opened 2019-09-25 07:01 UTC
#### System information: 
- Operating system (distribution) and version
- DBeaver version
DBEAVER 6.2.0 portable windows
#### Connection specification:
- Database name and version
MySQL 8.0
#### Describe your question:
whenever i export the dataset to csv, the header will always be quoted with the '`' sign. how do i change the export settings?
![image](https://user-images.githubusercontent.com/35907473/65576862-50d14280-dfa5-11e9-9724-ee59f554dd86.png)

**Comment by serge-rider** [comment] 2019-10-07 12:46
Duplicate of #6815. Fixed in 6.2.2

**Closed by serge-rider** 2019-10-07 12:46 UTC
Labels: bug, duplicate
