### ISSUE TITLE
[Mac] Database Navigator Filter Field Clear (X) Button Does Not Work

### ISSUE THREAD

**Issue by RobertHana1** [dbeaver/dbeaver#21630] opened 2023-10-23 14:00 UTC
### Description

Database Navigator Filter Field Clear (X) Button Does Not Work

### DBeaver Version

CE 23.2.2.2023*

### Operating System

Mac OS X Ventura 13.5.1

**Comment by MashaKorax** [comment] 2023-10-23 14:09
Thanks for your bug report. I reproduced it. It works only after several clicks (5-7)

**Comment by LonwoLonwo** [comment] 2023-10-26 11:34
Duplicate of https://github.com/dbeaver/dbeaver/issues/10590

**Closed as not planned by LonwoLonwo** 2023-10-26 11:34 UTC
Labels: duplicate, xo:macos, xf:ui, xf:filters, xp:normal
