### ISSUE TITLE
when importing data from csv, if 'set empty strings to null' is on, everything after null is set to null, too

### ISSUE THREAD

**Issue by dbojan** [dbeaver/dbeaver#15738] opened 2022-03-05 14:23 UTC
#### System information: 
- Windows 10
- DBeaver version 21.3.5
- Additional extensions

#### Connection specification:
- Database name and version: sqlite3
- Driver name: odbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:
when importing data from csv, if 'set empty strings to null' is on, 
everything after null is set to null, too.
Same thing happens if the the empty string is at the top of the column, or in the middle.

#### Steps to reproduce, if exist:
Select table in dbeaver
select 'import data'
import source: csv
import file: table1.csv
column delimiter: | (same thing happens if I choose ',' as delimiter)
quote char:
set empty strings to null: yes
rest of settings are on the default.

map columns: I just choose one column with data I need, and skip the rest.
type of import column in the database is nvarchar(200).
csv has empty fields.
example:
table1.csv:
|
b|
c|

next, next, proceed.
imported data looks like this
null
null
null

expected is 
null
b
c

Table 2 example:
a|
|
c|
d|

next, next, proceed.
imported data looks like this:
a
null
null
null

expected is 
a
null
b
c

**Comment by dbojan** [comment] 2022-03-05 14:25
There are no errors during the import.

**Comment by dbojan** [comment] 2022-03-08 16:34
as a temporary workaround, one can replace empty cells values with * or some other character not used in the data,
and use 'null value mark' set to * when importing csv.

**Comment by LonwoLonwo** [comment] 2022-03-09 07:12
Hello @dbojan 

Thanks for the bug report.

Interesting thing - Preview works fine. And import without enabled 'set empty strings to null' setting is also working fine.

![2022-03-05 23_43_30-Preview data import - delimeter_coma_empty_csv2](https://user-images.githubusercontent.com/45152336/157390870-8ad34348-cdf0-474b-84b2-9b8668f29b28.png)

So the issue is here with this 'set empty strings to null' setting.

**Comment by tilmanb** [comment] 2022-03-10 13:32
I guess it's related to the check beginning at https://github.com/dbeaver/dbeaver/blob/master/plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/importer/DataImporterCSV.java#L250

**Comment by LonwoLonwo** [comment] 2022-04-08 06:51
Fixed in DBeaver 22.0.3

**Comment by uslss** [comment] 2022-04-08 08:38
verified

**Closed as completed by uslss** 2022-04-08 08:38 UTC
Labels: xf:datatransfer, sp:2
