### ISSUE TITLE
Coloristical or ergonomical bug for boolean elements

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#8299] opened 2020-03-30 11:15 UTC
#### System information: 
- Operating system (distribution) and version
Linux
- DBeaver version
7.0.1
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
![изображение](https://user-images.githubusercontent.com/41448637/77906485-b83bb800-7290-11ea-994e-26cbefeb4eac.png)
![изображение](https://user-images.githubusercontent.com/41448637/77906461-ad812300-7290-11ea-8ab2-d1d632c51793.png)

#### Steps to reproduce, if exist:
Open create column form or any interface table key-value in Dbeaver with boolean value

**Comment by uslss** [comment] 2020-03-30 12:18
cannot reproduce it on ubuntu 19.04.
What OS do you use?

**Comment by mkgrgis** [comment] 2020-03-31 04:51
OS isn't a decisive factor. There is the same situation in Mint, Ubuntu and any other. I use mate https://ru.wikipedia.org/wiki/MATE as graphical shell.
![изображение](https://user-images.githubusercontent.com/41448637/77988197-5e84cd80-7324-11ea-811d-b65dd3037e94.png)

**Comment by uslss** [comment] 2020-04-04 16:01
thanks for the bug report

**Comment by serge-rider** [comment] 2020-11-04 20:28
Fixed in #9327
Must be tested on Linuxes and MacOS.

**Comment by uslss** [comment] 2020-11-05 13:37
ubuntu - ok

**Comment by kseniiaguzeeva** [comment] 2020-11-06 12:25
Mac Catalina is ok too

**Closed by kseniiaguzeeva** 2020-11-06 12:25 UTC
Labels: bug, duplicate, xo:linux
