### ISSUE TITLE
DBeaver becomes unresponsive when interacting with MongoDB collection

### ISSUE THREAD

**Issue by codebling** [dbeaver/dbeaver#3108] opened 2018-03-07 19:47 UTC
Hey!! 

DBeaver 4.3.0 freezes up and becomes unresponsive, with DBeaver using 100% cpu on one core when interacting with a MongoDB collection, in certain circumstances. How can I get a thread dump or give you move info?

**Comment by serge-rider** [comment] 2018-03-07 20:45
Thread dump instruction: https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump
Please check this in the most recent version.

**Comment by codebling** [comment] 2018-03-07 20:56
As I said, 4.3.0. There is no downloadable EE version of 5.0.0 that I can find. 

I will take a thread dump the next time I'm able to reproduce.

**Comment by serge-rider** [comment] 2018-03-07 20:57
You can try EA version (https://dbeaver.com/files/ea/). 
5.0 will be released on Monday.

**Comment by codebling** [comment] 2018-03-07 21:58
[dump.txt](https://github.com/dbeaver/dbeaver/files/1791038/dump.txt)

**Comment by serge-rider** [comment] 2018-03-07 22:01
Looks like huge number of errors happen and UI freezes during error logging.
Cold you check error/debug log files to get actual error(s) - https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by codebling** [comment] 2018-03-07 22:14
[-.log](https://github.com/dbeaver/dbeaver/files/1791083/-.log)
None of the exceptions in this log match up with the dump time, but it looks like there are a few exceptions that need to be addressed anyhow

**Comment by codebling** [comment] 2018-03-07 22:48
Was able to reproduce on 5.0.0 EA, and here's the error that is spamming the log file during the unresponsiveness, as you suspected: 

    org.jkiss.dbeaver.model.exec.DBCException: Unsupported value type: java.lang.String
    	at org.jkiss.dbeaver.model.data.DBDAttributeBindingType.extractNestedValue(DBDAttributeBindingType.java:141)
    	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.getCellValue(ResultSetModel.java:330)
    	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$ContentProvider.getCellValue(SpreadsheetPresentation.java:1496)
    	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$ContentProvider.getCellText(SpreadsheetPresentation.java:1548)
    	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.getCellText(LightGrid.java:4157)
    	at org.jkiss.dbeaver.ui.controls.lightgrid.GridColumn.computeCellWidth(GridColumn.java:288)
    	at org.jkiss.dbeaver.ui.controls.lightgrid.GridColumn.pack(GridColumn.java:259)
    	at org.jkiss.dbeaver.ui.controls.lightgrid.GridColumn.pack(GridColumn.java:265)
    	at org.jkiss.dbeaver.ui.controls.lightgrid.GridColumn.pack(GridColumn.java:265)
    	at org.jkiss.dbeaver.ui.controls.lightgrid.GridColumn.pack(GridColumn.java:265)
    	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.refreshData(LightGrid.java:541)
    	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.Spreadsheet.refreshData(Spreadsheet.java:344)
    	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.refreshData(SpreadsheetPresentation.java:661)
    	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver$1.run(ResultSetDataReceiver.java:159)
    
	

Sometimes the line with `SpreadsheetPresentation.java:1548` is not there, otherwise the stack trace is always the same.

**Comment by codebling** [comment] 2018-03-07 22:51
I haven't reproduced enough times to confirm, but anecdotally it seems like this happens once DBeaver has been idle 5+ minutes

**Comment by serge-rider** [comment] 2018-03-08 08:51
Interesting. I can't reproduce that but there is some bug in DBeaver which should be fixed.

Does this happen with all Mongo collections or only with some particular ones? 
Is there anything special about this collection(s)? 
Could you post a sample Mongo document (here or send on serge@jkiss.org)?

**Comment by codebling** [comment] 2018-03-08 22:16
Most of the documents/rows in this collection have a field containing an object. But in some documents/rows, that field is a string. DBeaver has a column header for this field and it seems to be trying to cast the string into an object. It's only when those specific documents/rows are on screen that there is an issue. 
![column header](https://user-images.githubusercontent.com/1073841/37179547-f37b7b60-22f3-11e8-8736-c98136d1c0b3.png)

**Comment by serge-rider** [comment] 2018-03-10 20:31
Thanks for details! 
Now I've been able to reproduce that.

**Comment by serge-rider** [comment] 2018-03-10 20:49
I've fixed UI freeze and error log issue.
However it doesn't make much sense to use Grid/Text presentations in your case. 
They are designed to show results in structured way. So if different documents have different structure they will produce some mess which is quite hard to use.
I'd recommend to use JSON presentation (which was originally designed specifically for MongoDB).

And again - thanks for detailed report.

**Closed by serge-rider** 2018-03-10 20:49 UTC
Labels: bug, question

**Comment by codebling** [comment] 2018-03-10 22:03
I will look into JSON mode! Really like grid mode, too, might continue using it even if it displays null for those cells. At least it won't affect the rest of the UI, now.
