### ISSUE TITLE
Bind parameters dialog box does not allow to edit values since 6.0.1

### ISSUE THREAD

**Issue by emmanuelaverty** [dbeaver/dbeaver#5603] opened 2019-03-28 10:00 UTC
#### System information: 
- OS : Ubuntu 18.04
- DBeaver 6.0.1.201903251040
- Java version : openjdk version "1.8.0_191"

#### Connection specification:
- Tested for 
  - SqlServer (Microsoft driver)
  - Mysql
  - Sqlite

#### Describe the problem you're observing:
The «Bind parameter(s)» dialog box does not allow to edit parameters values. The field seems to be read-only.

#### Steps to reproduce, if exist:
Execute the query :
``` sql
select :value
```

#### Include any warning/errors/backtraces from the logs

Occurs when I execute the query :
```
2019-03-28 10:57:42.937 - Event loop exception
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1069)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:888)
	at org.eclipse.swt.custom.ControlEditor.layout(ControlEditor.java:218)
	at org.eclipse.swt.custom.TableEditor.layout(TableEditor.java:266)
	at org.eclipse.swt.custom.ControlEditor.setEditor(ControlEditor.java:246)
	at org.eclipse.swt.custom.TableEditor.setEditor(TableEditor.java:241)
	at org.eclipse.swt.custom.TableEditor.setEditor(TableEditor.java:257)
	at org.jkiss.dbeaver.ui.controls.CustomTableEditor.showEditor(CustomTableEditor.java:111)
	at org.jkiss.dbeaver.ui.controls.CustomTableEditor.showEditor(CustomTableEditor.java:88)
	at org.jkiss.dbeaver.ui.editors.sql.dialogs.SQLQueryParameterBindDialog.lambda$0(SQLQueryParameterBindDialog.java:160)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4475)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:822)
	at org.eclipse.jface.window.Window.open(Window.java:798)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob$1.runTask(SQLQueryJob.java:661)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob$1.runTask(SQLQueryJob.java:1)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:25)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:34)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4475)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:184)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

**Comment by weswaldix** [comment] 2019-03-28 15:44
We had this problem yesterday - @serge-rider fixed the issue with V6.0.2:
https://github.com/dbeaver/dbeaver/issues/5575#issuecomment-477095445

**Comment by serge-rider** [comment] 2019-04-03 16:31
Duplicate of #5575

**Closed by serge-rider** 2019-04-03 16:31 UTC
Labels: bug, duplicate

**Comment by emmanuelaverty** [comment] 2019-04-08 07:45
Works with **6.0.2**
Thanks a lot.
