### ISSUE TITLE
Wrong mapping for export form MongoDB to MySQL

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13556] opened 2021-08-16 13:52 UTC
#### System information: 
- Operating system (distribution) and version WIn10
- DBeaver version 21.1.5

#### Steps to reproduce, if exist:
1. Start export form MongoDB/DocumentsDB to MySQL
2. Look at DDL statement

**Expected:** Varchar columns have length defined in parenthesis
**Actual result:** Length is not defined which leads to syntax error

![dbeaver_tqzcywEEPY](https://user-images.githubusercontent.com/82543000/129574389-357058e8-79c6-45cf-9260-fe8396eb8b3d.png)

**Comment by ShadelessFox** [comment] 2021-09-30 11:26
Duplicate of #13290

**Closed as completed by ShadelessFox** 2021-09-30 11:26 UTC
Labels: x:mysql, duplicate, x:mongo, xf:datatransfer
