### ISSUE TITLE
AutoAssign DataExport converts to unsuitable column type

### ISSUE THREAD

**Issue by wumpz** [dbeaver/dbeaver#8668] opened 2020-05-11 14:49 UTC
I want to convert an Microsoft Access Table (mytable) into a H2 table (mytable_h2).

Within **mytable** there is a decimal column of type decimal (19,0). This column is shown in the data exporter as a **numeric** column without any size. The resulting H2 columns is of type **tinyint**.

So if this is not a bug: is it possible to somehow teak those standard column type transformations. In fact I want to transform hundreds of tables. I see no way to do this using UI.

**Comment by uslss** [comment] 2020-05-11 17:25
thanks for the bug report

**Comment by LonwoLonwo** [comment] 2021-09-05 15:12
Can't reproduce in DBeaver 21.2.0

We have some enhancements for numeric columns mapping. And I think, it helps.

![2021-09-05 18_10_02-Map columns of NEWTABLE](https://user-images.githubusercontent.com/45152336/132131791-98028717-fd6c-4ee3-b156-5c0603a90e7e.png)

So, I'm closing this ticket. If the problem appears again - feel free to reopen it.

**Closed by LonwoLonwo** 2021-09-05 15:12 UTC
Labels: bug, xf:datatransfer, x:h2
