### ISSUE TITLE
Pin tab not working anymore on CE 24.1.4

### ISSUE THREAD

**Issue by manugentile** [dbeaver/dbeaver#35173] opened 2024-08-12 17:19 UTC
### Description

I just downloaded DBeaver CE 24.1.4 (version 24.1.4.202408041450) on my Win 11 Home PC.
I opened a SQLite connection, wrote and ran a query, then I pinned its result.
After I wrote a different query and the result was subscribed in the pinned tab instead of creating a new one.

I attach a video I just recorded : https://github.com/user-attachments/assets/ddc2179c-5e0d-4f25-be99-7467f1269b1d

### DBeaver Version

Community Edition 24.1.4

### Operating System

Windows 11 Home 

### Database and driver

I tried with SQLite and Oracle

### Steps to reproduce

1. I connect to a DB
2. I write a first query on row 1
3. I execute the query on row 1
4. I pin the tab with the result of query on row 1
5. I write another query on row 2
6. I execute the second query on row 2

**Comment by E1izabeth** [comment] 2024-08-12 17:21
Thank you for bug report.
I'm closing it as it's a duplicate of #35072

You can try Early Access version with fix (https://dbeaver.io/files/ea/) or wait for the next release

**Closed as not planned by E1izabeth** 2024-08-12 17:21 UTC
Labels: duplicate, xf:sql execution
