### ISSUE TITLE
Oracle 23c JSON Type

### ISSUE THREAD

**Issue by prankware-code** [dbeaver/dbeaver#22983] opened 2024-02-28 07:59 UTC
### Description

When I create and insert table

```CREATE TABLE j_purchaseorder2
  (id          VARCHAR2 (32) NOT NULL PRIMARY KEY,
   date_loaded TIMESTAMP (6) WITH TIME ZONE,
   po_document JSON);
   INSERT INTO j_purchaseorder2
  VALUES (SYS_GUID(),
          to_date('30-DEC-2014'),
          '{"PONumber"             : 1600,
            "Reference"            : "ABULL-20140421",
            "Requestor"            : "Alexis Bull",
            "User"                 : "ABULL",
            "CostCenter"           : "A50",
            "ShippingInstructions" : "{...}",
            "Special Instructions" : "null",
            "AllowPartialShipment" : "true",
            "LineItems"            : "[...]"}');
```
            
I take error in table

```org.jkiss.dbeaver.model.exec.DBCException: SQL Error [18722] [72000]: ORA-18722: Не задано свойство подключения oracle.jdbc.jsonDefaultGetObjectType
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getAttributeValue(JDBCResultSetImpl.java:150)
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.fetchValueObject(DefaultValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:199)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: ORA-18722: Не задано свойство подключения oracle.jdbc.jsonDefaultGetObjectType
	at oracle.jdbc.driver.JsonAccessor.getObject(JsonAccessor.java:287)
	at oracle.jdbc.driver.GeneratedStatement.getObject(GeneratedStatement.java:196)
	at oracle.jdbc.driver.GeneratedScrollableResultSet.getObject(GeneratedScrollableResultSet.java:322)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getAttributeValue(JDBCResultSetImpl.java:147)
	... 9 more
```

![image](https://github.com/dbeaver/dbeaver/assets/82946570/c0acbd11-3ad7-4e67-9f87-d9dc144723c3)

### DBeaver Version

23.3.5 community

### Operating System

Windows 11

### Database and driver

Oracle
![image](https://github.com/dbeaver/dbeaver/assets/82946570/a480c7cc-52c8-471d-933a-2b0968d27e04)

**Comment by prankware-code** [comment] 2024-02-28 09:49
If drivers 12.2.0.1, then json type is worked
![image](https://github.com/dbeaver/dbeaver/assets/82946570/23f7fcef-2308-47a1-a689-be83ddd45d56)

**Comment by ShadelessFox** [comment] 2024-02-28 12:20
Hello @melisha-git,

It seems that they have changed something in the driver.

In the connection configuration, go to the "Driver properties" tab and add the following property:
|Name|Value|
|----|-----|
|`oracle.jdbc.jsonDefaultGetObjectType`|`oracle.sql.json.OracleJsonValue`|

Please let me know if it helps.

**Comment by prankware-code** [comment] 2024-02-28 12:24
@ShadelessFox Thanks for the speed and solution. It helped me. Can I close the ticket?

**Comment by ShadelessFox** [comment] 2024-02-28 12:37
Thanks for the response. No, please keep it open. We want to specify this parameter in DBeaver by default.

**Comment by Numerok** [comment] 2024-04-17 05:31
@ShadelessFox Hello, is there any updates on this issue? 
Solution that you posted in this issue worked only for reading the column but when trying to write to it it says: 
`Object parameter [{"test":"test"}] binding not supported`

Oracle 21.13.0 
OJDBC11 23.2.0.0

**Comment by ShadelessFox** [comment] 2024-04-17 09:11
The issue is not yet assigned to a particular milestone.

Thanks for the information. This error is reported by DBeaver, so it should be pretty trivial to fix it on our side.

**Closed as completed** 2024-05-23 17:47 UTC
Labels: x:oracle, xf:data, sp:2, xp:normal, pkg:CE, pkg:EE, xd:trivial
