### ISSUE TITLE
excessive consumption of resources

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#35153] opened 2024-08-11 09:08 UTC
### Description

since 24.1.3 version excessive consumption of resources RAM

start dbeaver

create 2 connection.
No opened objects, no opened editor

![image](https://github.com/user-attachments/assets/1ef799e0-ddca-4d15-9d38-71b182d0f5fd)

550 Mb RAM!!!  Why?

But with opened 3 table and 4 sql edititor 1500Mb RAM

I always especially appreciated dbeaver for its lightness.

### DBeaver Version

community edition 24.1.4

### Operating System

windows 11 64bit

### Database and driver

Postgresql 14

### Steps to reproduce

start dbeaver

create 2 connection.

**Comment by detkliff** [comment] 2024-08-12 10:50
![image](https://github.com/user-attachments/assets/24603070-c9ec-4b5b-af7a-eaa8b4c05086)

**Comment by serge-rider** [comment] 2024-08-13 11:47
Cannot reproduce. 
Memory consumption mostly depends on what are you doing in DBeaver.
You can enable "Show heap status" to monitor memory right in DBeaver interface.

Also resources may be consumed if you configure project with a lot of linked external folders.

**Comment by detkliff** [comment] 2024-08-14 07:27
i do not find this option "Show heap status"

**Comment by ShadelessFox** [comment] 2024-08-15 13:49
@detkliff you can enable it here:

![Image](https://github.com/user-attachments/assets/0d063640-4813-45a3-b100-5387acde393f)

**Comment by detkliff** [comment] 2024-08-15 14:10
ok

**Comment by detkliff** [comment] 2024-08-22 12:25
no tabs, no connection, no vpn

![image](https://github.com/user-attachments/assets/60f92268-3821-4466-b6bc-db0fe9315796)
![image](https://github.com/user-attachments/assets/e09fd66e-4781-414a-8878-9e2da5982d49)


![image](https://github.com/user-attachments/assets/40c64884-0fe0-4941-81d9-f8745e9b9a66)

**Comment by detkliff** [comment] 2024-08-22 12:28
Only reboot Dbeaver every 2-3 hour
![image](https://github.com/user-attachments/assets/32277f69-f7d9-4ec9-b6da-5052aebb9c56)

**Comment by ShadelessFox** [comment] 2024-08-22 13:29
Does DBeaver consume memory even if you don't do anything?

Try clicking on the heap indicator to perform garbage collection. If the used memory doesn't get lower, there might be a memory leak somewhere.

**Comment by detkliff** [comment] 2024-08-23 06:33
garbage collection has no effect

**Comment by ShadelessFox** [comment] 2024-08-23 09:30
Do you close all your connections and editors before it (effectively restoring DBeaver to the state it was in when you started it)?

It's possible to perform heap analysis, but the dump will contain sensitive information, so I wouldn't ask you to do that.

**Comment by detkliff** [comment] 2024-08-27 06:51
> Do you close all your connections and editors before it (effectively restoring DBeaver to the state it was in when you started it)?
> 
yes

**Comment by E1izabeth** [comment] 2024-08-29 13:26
@detkliff 
Could you try decreasing this limit in [dbeaver.ini](https://github.com/dbeaver/dbeaver/wiki/Configuration-files-in-DBeaver#dbeaverini) file? Does it help?
For example, try to change -Xmx1024m into -Xmx512m to decrease maximum memory to 512MB.

**Comment by detkliff** [comment] 2024-08-29 14:37
ok. I changed this parameter. I'm watching

**Comment by detkliff** [comment] 2024-09-01 03:10
if i close all connections and all tabs, the memory is still not released. It consumes less than it was, but still a lot of about 1Gb

**Comment by ask9** [comment] 2024-09-01 08:19
1. Open task manager (or see it in right bottom corner in Heap status) and monitor what your action in DBeaver leads to RAM consumption growth.
2. What's the value of parameter -Xms in file:
"C:\Users\user\AppData\Local\DBeaver\dbeaver.ini"

**Comment by detkliff** [comment] 2024-09-02 07:51
1. 
      1-Open Dbeaver. (original state) Current RAM utilization 230Мb
      2-Connect to remote server1 through VPN Current RAM utilization 260Мb
      3-Open SQL editor1 for server1 Current RAM utilization 300Мb
      4-Open SQL editor2 for server1 Current RAM utilization 320Мb
      5-Open SQL editor3 for server1 Current RAM utilization 330Мb
      6-Open SQL editor4 for server1 Current RAM utilization 330Мb
      
      7-run sql qyery 400 rows in code from SQL editor1 with 200rows in result Current RAM utilization 500Мb
      8-run sql qyery 400 rows in code from SQL editor2 with 200rows in result Current RAM utilization 650Мb
      9-run sql qyery 400 rows in code from SQL editor3 with 200rows in result Current RAM utilization 730Мb
     
     10 - close SQL editor1 Current RAM utilization 750Мb
     11 - close SQL editor2 Current RAM utilization 710Мb
     12 - close SQL editor3 Current RAM utilization 730Мb
     13 - Disconnect from remote server1 Current RAM utilization 650Мb

returned to the (original state) , but the memory was not cleared

2.Xms64m

**Comment by detkliff** [comment] 2024-09-02 07:51
-Xmx512m

**Comment by ShadelessFox** [comment] 2024-09-05 13:14
Please ensure that you have the `-Xmx` parameter located **after** the line that says `-vmargs`.

The fact that memory doesn't get cleared right away goes into the nature of the Java Virtual Machine (JVM), the platform on which DBeaver is built. The JVM does not clear the memory right away when an object is not used anymore - so-called garbage collection is performed only(*) when there's no spare memory to allocate new objects.

You can try decreasing the maximum allowed size even further, but beware that this might result in performance degradation due to a higher demand for garbage collection, or even in a crash when all the memory is exhausted.

(*) It depends on the garbage collector chosen.

**Comment by detkliff** [comment] 2024-09-05 15:46
![image](https://github.com/user-attachments/assets/57abb7c8-16b1-463e-994e-1d988e09fa84)

**Comment by detkliff** [comment] 2024-09-05 15:48
very bad(((( because with a value of 512 Dbeaver slows down noticeably

but utilization memory 600-900Mb. This definitely wasn't the case in previous versions

**Comment by ask9** [comment] 2024-09-05 16:09
Run dbeaver.exe with the argument -data "<some_folder>", for example:
`C:\Users\your_user\AppData\Local\DBeaver\dbeaver.exe -data C:\workspaces\my_workspace1`


It creates a new clean workspace with default settings in this folder and opens the application in it.

Check if the issue exists on this clean workspace.

When you want to switch back to you default workspace you can use the menu item: 
`File - switch workspace `
and paste the path to your default workspace usually located here:
`C:\Users\your_user\AppData\Roaming\DBeaverData\workspace6`

**Comment by detkliff** [comment] 2024-09-06 14:59
have no effect on new workspace. Over 1GB RAM utilization and memory was not cleared after close tabs and connections

**Comment by ask9** [comment] 2024-09-06 15:33
- update postgresql
- update drivers in your connection in dbeaver
- update Java
- update windows(?)

After update, please provide the versions you use.

**Comment by detkliff** [comment] 2024-09-17 03:44
it looks like the situation has stabilized after install last java version on Windows 11
![image](https://github.com/user-attachments/assets/d61ffde2-a7fe-4435-99ef-5d028ce21e90)

**Comment by E1izabeth** [comment] 2024-10-04 17:38
Unfortunately, we have not been able to reproduce the reported behavior. Therefore, I am closing this issue. If we receive a similar report from another user or can reproduce the issue in the future, we will reopen it.

**Closed as not planned by E1izabeth** 2024-10-04 17:38 UTC
Labels: can't reproduce, performance
