### ISSUE TITLE
String data shows as Hex

### ISSUE THREAD

**Issue by connor11528** [dbeaver/dbeaver#2658] opened 2017-12-18 19:53 UTC
I am running Dbeaver 4.3 and have connected to my database. When I execute a query the resulting string data shows as hex like so:

![](https://www.evernote.com/shard/s413/sh/57ce306a-a5a7-4627-895f-9c03a0f35425/95fde5aff719ab07/res/b08ce651-a575-4738-a64b-c7e536957767/skitch.png?resizeSmall&width=832)

By running this hex to through a hex-to-ascii converter I can see the actual data is regular english like "test purchase order"

How can I configure dbeaver to display ascii text instead of the hex values?

**Comment by serge-rider** [comment] 2017-12-20 14:38
I can't reproduce that.
What is your database/driver? What data-type these columns have (you can get it from metadata panel)

**Comment by connor11528** [comment] 2017-12-20 19:24
I got it working by downgrading to version 4.1 with Java 1.8

The database driver is JDBC and the columns are text fields

**Comment by serge-rider** [comment] 2017-12-20 19:46
What is the database? (Oracle, MySQL, PostgreSQL, .... ?).
What is the exact driver name?

**Comment by connor11528** [comment] 2017-12-22 01:27
It's a MySQL database. I'll get some more info next week regarding additional details.

**Comment by tati-kru** [comment] 2018-01-19 11:10
hi @connor11528 
Are there any updates about this issue? It would be really helpful.

**Comment by notEvil** [comment] 2018-03-05 13:46
I see this issue too in dbeaver 4.3.5 down to 4.3.0 (didnt check older versions). In my case the hex values only show up on second batch (201st - 400 record) in a SQL view with COALESCE(string columns..., json_unquote(json_extract(...))).

COALESCE without the json functions works just fine. However I need them, so the views are almost unusable at the moment.

**Comment by connor11528** [comment] 2018-03-05 18:14
Reopening cause it'd be nice to run the latest version of DBeaver!

**Comment by serge-rider** [comment] 2018-03-06 11:14
I can't reproduce that.
Please post some SQL snippet (DDL + insert).

**Comment by notEvil** [comment] 2018-03-08 09:20
restore from this dump (a little handcrafted to reduce length)

    -- MySQL dump 10.13  Distrib 5.7.21, for Linux (x86_64)
    --
    -- Host: [HOST]    Database: t1
    -- ------------------------------------------------------
    -- Server version	5.7.17-log

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

    --
    -- Table structure for table `t`
    --

    DROP TABLE IF EXISTS `t`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `t` (
      `c1` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
      `c2` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `t`
    --

    /*!40000 ALTER TABLE `t` DISABLE KEYS */;
    INSERT INTO `t` VALUES ('c1','{\"key\": [\"c2\"]}');
    INSERT INTO `t` SELECT * FROM `t`;
    INSERT INTO `t` SELECT * FROM `t`;
    INSERT INTO `t` SELECT * FROM `t`;
    INSERT INTO `t` SELECT * FROM `t`;
    INSERT INTO `t` SELECT * FROM `t`;
    INSERT INTO `t` SELECT * FROM `t`;
    INSERT INTO `t` SELECT * FROM `t`;
    INSERT INTO `t` SELECT * FROM `t`;
    INSERT INTO `t` SELECT * FROM `t`;
    /*!40000 ALTER TABLE `t` ENABLE KEYS */;

    --
    -- Temporary table structure for view `v`
    --

    DROP TABLE IF EXISTS `v`;
    /*!50001 DROP VIEW IF EXISTS `v`*/;
    SET @saved_cs_client     = @@character_set_client;
    SET character_set_client = utf8;
    /*!50001 CREATE VIEW `v` AS SELECT 
     1 AS `c1`,
     1 AS `c2`*/;
    SET character_set_client = @saved_cs_client;

    --
    -- Dumping routines for database 't1'
    --

    --
    -- Final view structure for view `v`
    --

    /*!50001 DROP VIEW IF EXISTS `v`*/;
    /*!50001 SET @saved_cs_client          = @@character_set_client */;
    /*!50001 SET @saved_cs_results         = @@character_set_results */;
    /*!50001 SET @saved_col_connection     = @@collation_connection */;
    /*!50001 SET character_set_client      = utf8 */;
    /*!50001 SET character_set_results     = utf8 */;
    /*!50001 SET collation_connection      = utf8mb4_bin */;
    /*!50001 CREATE ALGORITHM=UNDEFINED */
    /*!50013 DEFINER=`root`@`%` SQL SECURITY DEFINER */
    /*!50001 VIEW `v` AS select `t`.`c1` AS `c1`,coalesce(NULL,json_unquote(json_extract(`t`.`c2`,'$.key[0]'))) AS `c2` from `t` */;
    /*!50001 SET character_set_client      = @saved_cs_client */;
    /*!50001 SET character_set_results     = @saved_cs_results */;
    /*!50001 SET collation_connection      = @saved_col_connection */;
    /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

    /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
    /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

    -- Dump completed on 2018-03-08  9:55:58

then open view, go to data tab and scroll down to second page

**Comment by serge-rider** [comment] 2018-03-08 09:48
Still can't reproduce (MySQL 5.7.19)
![image](https://user-images.githubusercontent.com/6398845/37144264-8ab8f5fa-22ce-11e8-9cae-a353c3e9c945.png)

Should I execute some specific SQL query?

**Comment by notEvil** [comment] 2018-03-08 12:09
the table data tab is fine (shows json text), but the view (named `v`) shows numbers instead of "c2" on second page

**Comment by serge-rider** [comment] 2018-03-08 21:40
Yep, I've missed that. Now I can reproduce the problem.
This happens because function `json_unquote` returns LONGBLOB data type instead of  JSON or LONGCLOB or TEXT.
That's why DBeaver show it as binary data.

Workarounds:
- Use CAST(... AS CHAR) on json_unquote results
- Show binaries as strings (Preferences->Database->Result Sets->Editors->Binary data formatter)

**Comment by notEvil** [comment] 2018-03-09 07:43
Thanks, the first workaround does the trick. Still I don't really understand why dbeaver would use a different interpretation on first page compared to second and following.

**Comment by serge-rider** [comment] 2018-07-01 18:14
This was resolved in the latest MySQL drivers (8.0.11) - now it returns proper data type.
Please check and reopen if it will happen again.

**Closed by serge-rider** 2018-07-01 18:14 UTC
Labels: question

**Comment by sangem18** [comment] 2019-01-14 20:44
Hello , 

I am having the similiar issue in DB2 and dbeaver version is 5.3.2 , Can anyone suggest how to fix it .

**Comment by serge-rider** [comment] 2019-01-14 20:50
@sangem18 Please create separate issue with more details (sample table DDL, SELECT query)

**Comment by Roundabout-jsapi** [comment] 2025-01-29 20:05
> I see this issue too in dbeaver 4.3.5 down to 4.3.0 (didnt check older versions). In my case the hex values only show up on second batch (201st - 400 record) in a SQL view with COALESCE(string columns..., json_unquote(json_extract(...))).
> 
> COALESCE without the json functions works just fine. However I need them, so the views are almost unusable at the moment.
> 
> edit: I will add more information if you can't reproduce





https://lnkr.fun/70f0a61
