### ISSUE TITLE
Oracle table edited after opening it 

### ISSUE THREAD

**Issue by raqua** [dbeaver/dbeaver#4625] opened 2018-11-16 14:43 UTC
Version: 5.2.4
DB: Oracle

When I open any table it appears to be edited (table tab has * in front of table name). I have to go to "Columns" and click revert, otherwise I get prompt to save changes to table. There are no changes done. It happens on all tables. 

Example table:

  CREATE TABLE "E2D"."ACCOUNTS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(15) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(110 CHAR), 
	"PARENT_ID" NUMBER(19,0), 
	"VERSION" NUMBER(19,0), 
	"ACCOUNTING_TARGET" VARCHAR2(50) NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ORGANIZATION_NAME" VARCHAR2(15) NOT NULL ENABLE, 
	 UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PK_ACCOUNTS_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ACCOUNTS_ORGANIZATION_NAME" FOREIGN KEY ("ORGANIZATION_NAME")
	  REFERENCES "E2D"."ORGANIZATIONS" ("NAME") ENABLE, 
	 CONSTRAINT "FK_ACCOUNTS_PARENT_ID" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "E2D"."ACCOUNTS" ("ID") ENABLE, 
	 CONSTRAINT "FK_ACCOUNTS_ORGANIZATION_ID" FOREIGN KEY ("ORGANIZATION_ID")
	  REFERENCES "E2D"."ORGANIZATIONS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

These are the changes that DBeaver wants do persist:
ALTER TABLE E2D.ACCOUNTS 
MOVE TABLESPACE USERS;

**Comment by raqua** [comment] 2018-11-21 09:07
I have tried it and the issue persists also in new version.

**Comment by raqua** [comment] 2018-12-12 11:56
Hi, 

this bug is still present in 5.3.0.
Why is this labelled as question ?

**Comment by serge-rider** [comment] 2018-12-12 16:45
I can't reproduce this. See video.
This bug was definitely fixed in the previous DBeaver version.

![oracle-table-editor](https://user-images.githubusercontent.com/6398845/49884641-5f030780-fe46-11e8-8ef7-a72337b9c0e5.gif)

I have no clues so far..

**Comment by raqua** [comment] 2018-12-12 17:00
Would it help if I provided you with installed Oracle in a VirtualBox VM that you could connect to that exhibits this issue at my system?

**Comment by serge-rider** [comment] 2018-12-12 19:53
@raqua Yes, this would be very helpful. Please write me on serge@jkiss.org.

**Comment by ceyhunnabiyev** [comment] 2019-01-12 12:07
Hi @serge-rider, 
The problem also occurred in 5.3.2 version. I think, this is critical bug, because persisting this changes in a table makes table indexes be in unusable state (Given Error: ORA-01502: index _index_name_ or partition of such index is in unusable state). I have to rebuild indexes after this.

**Comment by serge-rider** [comment] 2019-01-12 14:01
@ceyhunnabiyev I still can't reproduce this. Please post more details. Short gif video also would be very helpful.

**Comment by raqua** [comment] 2019-01-12 14:14
Hi @serge-rider.

I have sent you a link to download VirtualBox VM, which exhibits this behavior as we agreed, but did not get response back from you. Did you downloaded it and was not able to reproduce or have you somehow missed my email?

**Comment by serge-rider** [comment] 2019-01-12 14:17
@raqua Nope, I didn't receive it :(  Could you send it again?

**Comment by serge-rider** [comment] 2019-01-12 15:55
Unfortunately this didn't help. I successfully run Oracle and opened LOG_ENTRIES table with no problems.
This makes me think that the problem is on your local machine where DBeaver is run.

- What Linux version do you have?
- After table becomes "modified" what happens if you press Save?
- Could you post a screenshot/video of this?

**Comment by raqua** [comment] 2019-01-12 16:08
1) I have Linux Mint 18. I don't really see how there could be an issue. Did you tested it from Linux or just Windows? I worked without an issue before the version mentioned in my first post. So I dunno .. 
2) When I press save it shows me the changes popup with changes like I mentioned at the end of my first post here. I have never actually gone to proceed with it, but I can try if you want me to. 
3) I will try to record my session, but I need to get some SW to do so first, so give me few days. 

Thx.

**Comment by serge-rider** [comment] 2019-01-12 16:11
1. I don't know. This whole issue looks quite crazy for me. But the problem is definitely not in the target database.
1. What changes exactly? You don't need to process them just post what they are (column changes? indexes?)
1. Ok. Even simple screenshot may help.

**Comment by raqua** [comment] 2019-01-12 16:14
These are the changes that DBeaver wants do persist (different table from example DB I prepared for you, but it happens with all tables and the changes are always the same):
ALTER TABLE E2D.ACCOUNTS
MOVE TABLESPACE USERS;

**Comment by serge-rider** [comment] 2019-01-12 18:10
Weird. Does tablespace USERS differs from actual tablespace?

I think that value of combobox "Tablespace" was somehow auto-applied making table "modified". And this may be specific to OS/Window manager. I'll keep digging it..

**Comment by raqua** [comment] 2019-01-12 18:35
I am not sure I follow .... 
But I just connected to my home server and checked the creation scripts. There is nothing about USERS tablespace in those and LOG schema should use LOG_DATA tablespace.

**Comment by serge-rider** [comment] 2019-01-12 18:42
So, the alter scripts changes table's tablespace from LOG_DATA to USERS?

What I need to understand - is this script just a dummy glitch which actually changes nothing or it can harm the database structure.

**Comment by ceyhunnabiyev** [comment] 2019-01-12 18:42
@serge-rider , @raqua ,
I use dbeaver archlinux package (version 5.2.4), but I downgraded package to version 5.2.1, then the problem didn't occur.

**Comment by ceyhunnabiyev** [comment] 2019-01-12 19:01
@serge-rider , @raqua 
I also tested followings: 
1. Create new column in a table (Successfully created both 5.2.4 and 5.2.1 )
2. Insert or update a row in the table.
For the second action, in version 5.2.4 gives me  ORA-01502 error, but in version 5.2.1 there is no errors.

**Comment by serge-rider** [comment] 2019-01-12 19:05
@ceyhunnabiyev Yeah. We are trying to understand what was broken in 5.2.4. Once I'll find it - I'll fix it.

@raqua Well, I have a clue. Just pushed the fix. Could your check it in Early Access version (https://dbeaver.io/files/ea)?

**Comment by ceyhunnabiyev** [comment] 2019-01-12 19:40
@serge-rider , I tested in Early Access version, the problem didn't occur..

**Comment by serge-rider** [comment] 2019-01-12 20:15
@ceyhunnabiyev Great, thanks 👍

**Comment by ceyhunnabiyev** [comment] 2019-01-12 20:30
Thank you for the fix..

**Closed** 2019-01-12 23:54 UTC
Labels: bug, can't reproduce, question, xo:linux
