### ISSUE TITLE
Can't scroll past already fetched rows after cancelling 

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#15811] opened 2022-03-12 21:01 UTC
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
1. Open a table
2. Edit something in it, so the editor becomes dirty
3. Scroll to the bottom, causing new data to load
4. Observe the confirmation dialog and press `Cancel`
5. Manually either save or cancel changes
6. Observe that you are still unable to load new rows

https://user-images.githubusercontent.com/35821147/158034806-d3a5d911-157a-4b5f-a5ea-1b3fd35b2943.mp4

**Comment by LonwoLonwo** [comment] 2022-03-13 15:57
Duplicate of https://github.com/dbeaver/dbeaver/issues/15812

**Closed as completed by LonwoLonwo** 2022-03-13 15:57 UTC
