### ISSUE TITLE
Navigator node not found

### ISSUE THREAD

**Issue by A-Nicoladie** [dbeaver/dbeaver#22655] opened 2024-02-01 09:13 UTC
### Description

Hello,

I have been encountering an issue with opening certain tabs since several versions. 
It often happens that a tab refuses to open and displays the following message instead of my table:

> Navigator node 'node://General/datasources/********/microsoft-************-*************/database/*******/schema/dbo_1/table/********************_1328723786' not found
> 
> Possible reasons:
>  - The connection view was changed
>  - The object this editor was opened for no longer exists in the database

This occurs regardless of the database being used. 
> Navigator node 'node://General/datasources/*******/db2_iseries-*************-***********/ADPFILE/table/*******' not found

The problem arises when I close DBeaver and open it the next day. 
The database exists and so does the table in question. 
Nothing has changed except for the connection which was interrupted. 

This error started occurring only recently (I haven't tested it yet, but I would say roughly since v23.0).

![image](https://github.com/dbeaver/dbeaver/assets/90625228/bdb520a1-32dd-4994-bf07-bf3790a4033d)

### DBeaver Version

Community Edition Version 23.3.3.202401211839

### Operating System

Windows 11 (FRA)

### Database and driver

- IBM DB2 iSeries/AS 400 driver : 20.0.6
- Microsoft JDBC Driver for SQL Server (MSSQL) : 12.4.1
- MariaDB JDBC driver : 3.0.7
- Driver for MySQL 8 and later : 8.2.0
- Sybase jConnect driver : jconn4
- Oracle JDBC driver : 23.2.0.0
- PostgreSQL standard driver : 42.5.2

### Steps to reproduce

1. Open a table
2. Quit DBeaver
3. Wait 24 hours
4. Open again

**Comment by LonwoLonwo** [comment] 2024-02-01 13:23
Hello @A-Nicoladie 

Could you please provide an example of your table name for testing? It can depend on the table name.

For ordinary "newtable," I can't reproduce your issue.

**Comment by A-Nicoladie** [comment] 2024-02-02 07:52
I closed DBeaver yesterday evening around 7 PM with an open tab on some different databases and opened it again today at about 8 AM. Here are the results:




<details>
<summary>SQLite - Table name : ServicesLogs_2023 (clic to show/hide) ↓</summary>
org.jkiss.dbeaver.DBException: Navigator node 'node://General/datasources/Perso/sqlite_jdbc-1891aa9e2d0-6e8119bbbab5dace/table/ServicesLogs_2023' not found

Possible reasons:
 - The connection view was changed
 - The object this editor was opened for no longer exists in the database
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:312)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:171)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
</details>





<details>
<summary>Oracle - Table name : ALERTER (clic to show/hide) ↓</summary>
org.jkiss.dbeaver.DBException: Navigator node 'node://General/datasources/PROD/oracle_thin-183cc21e36e-4525bbb0ee98c546/schema/S02/table/ALERTER' not found

Possible reasons:
 - The connection view was changed
 - The object this editor was opened for no longer exists in the database
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:312)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:171)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
</details>





<details>
<summary>DB2 - Table name : APB8CPP (clic to show/hide) ↓</summary>
org.jkiss.dbeaver.DBException: Navigator node 'node://General/datasources/DEV/db2_iseries-18245068301-81b9aea73022bb7/ADPFILE/table/APB8CPP' not found

Possible reasons:
 - The connection view was changed
 - The object this editor was opened for no longer exists in the database
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:312)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:171)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
</details>




<details>
<summary>Postgre - Table name : jiauditevent (clic to show/hide) ↓</summary>
org.jkiss.dbeaver.DBException: Navigator node 'node://General/datasources/PROD/postgres-jdbc-1824a9c2959-6be393031d9f77ba/database/jasperserver_41326/schema/public_2200/table/jiauditevent_41373' not found

Possible reasons:
 - The connection view was changed
 - The object this editor was opened for no longer exists in the database
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:312)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:171)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
</details>




<details>
<summary>MariaDB - Table name : vente (clic to show/hide) ↓</summary>
org.jkiss.dbeaver.DBException: Navigator node 'node://General/datasources/DEV/mariaDB-18d5ac4a8ae-4c48af7e2708b9e3/database/vnb_dvt/table/vente' not found

Possible reasons:
 - The connection view was changed
 - The object this editor was opened for no longer exists in the database
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:312)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:171)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
</details>




<details>
<summary>Sybase - Table name : spt_values (clic to show/hide) ↓</summary>
org.jkiss.dbeaver.DBException: Navigator node 'node://General/datasources/DEV/sybase_jconn-1853f6b3ac2-781364b6807a8bc/master/dbo/table/spt_values' not found

Possible reasons:
 - The connection view was changed
 - The object this editor was opened for no longer exists in the database
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:312)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:171)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
</details>




<details>
<summary>SQL Server - Table name : ENVOI_QTE (clic to show/hide) ↓</summary>
org.jkiss.dbeaver.DBException: Navigator node 'node://General/datasources/PROD/microsoft-18115155376-daaf3545cae51d9/database/industrie/schema/dbo_1/table/ENVOI_QTE_1328723786' not found

Possible reasons:
 - The connection view was changed
 - The object this editor was opened for no longer exists in the database
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:312)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:171)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
</details>




💡 Maybe an important detail that I forgot to mention:  I access these databases through a VPN (the same for all)

**Comment by hurcy** [comment] 2024-02-06 02:12
I have exactly same problem.

**Comment by nb-programmer** [comment] 2024-02-07 12:46
Same, happening with every connection tab that was left open and when reconnection is done.
Happening on v 23.3.4.202402060628 and at least 1 previous version (can't confirm which, sorry).

**Steps**:
- Have an SQL connection.
- Open a table / view open and view Data.
- Close DBeaver
- Re-open. All tabs will show this error.


**Screenshot**:
<img width="621" alt="image" src="https://github.com/dbeaver/dbeaver/assets/46126206/17d1d0e8-0ad9-4fe8-967f-e864fcb5291e">

**Comment by angeloruggieridj** [comment] 2024-02-09 08:38
I've also this problem since 23.3.0 update version.
I'm using Dbeaver Community Edition with Oracle Databases.

**Comment by gaetanodegennaro** [comment] 2024-02-09 08:40
I also have this problem with Dbeaver Community Edition 23.3.0 (Oracle).

**Comment by LonwoLonwo** [comment] 2024-02-09 09:31
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by A-Nicoladie** [comment] 2024-02-09 13:56
Before, I deleted all the log files and tried again to reproduce the problem (to avoid too much unnecessary information)

Here are the files [DBeaver-Log_files-Issues_22655.zip](https://github.com/dbeaver/dbeaver/files/14222097/DBeaver-Log_files-Issues_22655.zip)

The archive contains these 3 files:
- ".log"
- "dbeaver-debug.log"
- "dbeaver-debug-1707482586924.log"

**Comment by K-Ko** [comment] 2024-02-10 16:51
Same here, at least from 23.3.2

In my case, connections with SSL tunnels.

**Comment by struck89** [comment] 2024-02-14 16:14
+1 here. It has been happening after a few days/versions.
In my case connecting to Snowflake and it doesn't need to be after closing and opening. It happens in the same day after the connection times out. Database gets disconnected and all the tables I had open look like this:
![image](https://github.com/dbeaver/dbeaver/assets/18152095/f968019d-5c16-4a41-b9e9-e15b1a7cb2bc)
And I have to close them all and open again.

Would you like log files? I would need to review the information that those contain.
I use ZScaler, the authentication phase goes trough okta, and that needs the ZScaler VPN on

EDIT: the .log file doesn't show the issue, but the dbeaver-debug.log might have something:
``` 
2024-02-14 16:34:35.255 - No execution context within database instance  
2024-02-14 16:34:35.255 - No execution context within database instance  
2024-02-14 16:34:35.403 - Execution context closed (xxx, 16)  
2024-02-14 16:34:35.403 - Execution context closed (yyy, 15)  
2024-02-14 16:34:35.403 - Disconnected (snowflake_jdbc-1897xxx)  
2024-02-14 16:34:35.403 - Disconnected (snowflake_jdbc-1785yyy)  
2024-02-14 16:57:58.867 - Connect with 'xxx' (snowflake_jdbc-1897xxx)  
2024-02-14 16:57:58.867 - Execution context opened (PRD_PSG_ROLE; Main; 17)  
2024-02-14 16:58:02.224 - Connected (snowflake_jdbc-1897xxx, Snowflake [3.13.25])  
2024-02-14 16:58:02.489 - Node 'PRD' not found in parent node 'node://General/datasources'.  
Allowed children: [MSSQL, SNOWFLAKE, zzz.mdb [MS Access (UCanAccess)], DBeaver Sample Database (SQLite) [SQLite], nnnn.db [SQLite], mmmm.db [SQLite], uuuu[Snowflake], iiiii [PostgreSQL], oooo[PostgreSQL]]  
```
The last lines appears many times.

I think the issue is related to ordering the items in folder structure?
![image](https://github.com/dbeaver/dbeaver/assets/18152095/bf8d2ca8-ac4e-4a23-a7ab-6e4291a14975)

**Comment by LonwoLonwo** [comment] 2024-02-14 16:31
> Would you like log files? I would need to review the information that those contain.

Yes, please.

**Comment by struck89** [comment] 2024-02-15 08:44
The log from above shows the error:
Node 'PRD' not found in parent node 'node://General/datasources'.
PRD is a subfolder from SNOWFLAKE folder. And the connection is inside that folder.
![image](https://github.com/dbeaver/dbeaver/assets/18152095/652a853d-3e2d-4dbe-a587-9eb7b2acc648)
Allowed children in my comment above (last line of the code block) are all the folders and connections that I have at the root level. From the picture above you can see MSSQL folder and SNOWFLAKE folder.


AAAND
I can confirm the issue:
![image](https://github.com/dbeaver/dbeaver/assets/18152095/27c9692e-abb7-40b2-872d-ec7920977479)

That Node address is wrong.
I created now a connection inside a root folder, and the problem does not happen.
Correct Node address:
node://General/datasources/SNOWFLAKE/PRD/[...]
and not
node://General/datasources/PRD/[...]

Steps to reproduce:
Create two connections, one inside a folder, one in a subfolder:
aa/connection1
aa/bb/connection2

Set the "Close idle connection after" to something low.
Open both and open a table in each, wait for connection to time out and click on: 
![image](https://github.com/dbeaver/dbeaver/assets/18152095/6a2263f2-6fc0-4caf-a332-5b9055ab62a6)
One will fail (connection2), one will not (connection1).
At least this is happening to me right now. So I will move for now all my connections outside of subfolders within folders.
![image](https://github.com/dbeaver/dbeaver/assets/18152095/f1672af5-6129-4718-b56b-e7cd48779213)
Now all the connections are inside root folders and not breaking!

**Comment by struck89** [comment] 2024-02-15 08:57
> Same, happening with every connection tab that was left open and when reconnection is done. Happening on v 23.3.4.202402060628 and at least 1 previous version (can't confirm which, sorry).
> 
> **Steps**:
> 
> * Have an SQL connection.
> * Open a table / view open and view Data.
> * Close DBeaver
> * Re-open. All tabs will show this error.
> 
> **Screenshot**: <img alt="image" width="621" src="https://private-user-images.githubusercontent.com/46126206/302983017-17d1d0e8-0ad9-4fe8-967f-e864fcb5291e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5ODc1NjIsIm5iZiI6MTcwNzk4NzI2MiwicGF0aCI6Ii80NjEyNjIwNi8zMDI5ODMwMTctMTdkMWQwZTgtMGFkOS00ZmU4LTk2N2YtZTg2NGZjYjUyOTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA4NTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYmUwNmU4MDBhZTE1OGI5NTQzOTIyNmExZDRkNGViYmYzZGYwOTUyYWFmMmI1YjViM2JjMDVlYzVlMjFhMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M5aKmPYcjDz5ZmESuHHPidAy9ahBWejQwphgocdt_A8">

Look at this screenshot, the node address is not taking into account that the "SQlite" folder is inside "Databases" folder. Log will show for allowed children "Databases" only.

**Comment by E1izabeth** [comment] 2024-02-15 13:52
I reproduced the issue with help of the steps specified in https://github.com/dbeaver/dbeaver/issues/22655#issuecomment-1945619565

**Closed as completed** 2024-02-21 15:23 UTC
Labels: xp:major, xf:navigator, sp:2

**Comment by mkbaranovskyi** [comment] 2024-03-12 06:53
The issue persists (DBeaver v24.0.0). If there is at least one open tab during the DBeaver startup, this error message appears
![image](https://github.com/dbeaver/dbeaver/assets/39165507/b72a9360-0a64-4780-acee-04805a563727)

If I close all the tabs and reopen DBeaver - no error.. This is MySQL if that matters

This is the error log
[dbeaver_error_log.txt](https://github.com/dbeaver/dbeaver/files/14568351/dbeaver_error_log.txt)

P.S. I just experienced this error opening another (Postgres) connection right at the moment I was trying to open the table list. It still allowed me to access it though (after closing the error message).

**Comment by bmaciass** [comment] 2024-03-13 00:23
I'm experiencing the same issue. The steps for reproduce are:
1. Open Table Editors by clicking a table on the left panel
2. Close dbeaver
3. DROP the whole DB and CREATE it from scratch (this steps are needed in my case when, for example, I'm testing a feature and I want to do with a "clean" db; so I execute something like "recreate local db" which will drop it and create it from a existing SQL file)
4. Open Dbeaver

Now the editors have errors and I have to manually open them again. The error message is the same as the first picture.

I'm using version 24.0.0. The last version I used was 23.0.4 (?) not really sure but the error never raised with v23

btw great work, you guys really make my work easier

**Comment by b00weck** [comment] 2025-01-09 07:38
Issue still remains in 24.3.2

**Comment by Zurid** [comment] 2025-10-02 13:44
25.2.1 -- having this issue. you open a table, exit from DBVR, start it again, the tab remains, but now show the error: 

Navigator node 'node://General/datasources/zzzzzz/postgres-jdbc-1970dbb2f08-116895f9741d2b6d/database/postgres_5/schema/zzzzzz16397/table/zzzzzzzz_652808' not found

the issue needs to be re-opened

**Comment by ShadelessFox** [comment] 2025-10-02 13:56
@Zurid please create a new issue and provide detailed steps required to reproduce the issue there.

**Comment by neilpanchal** [comment] 2025-12-13 20:04
Still having this issue in 25.3.0

**Comment by symdeb** [comment] 2026-04-14 04:17
This error occurs when starting Dbeaver Version 26.0.1.202603221810. 
What does it mean, how to get rid of it ?

**Comment by jarkko-hautakorpi** [comment] 2026-05-01 15:31
Still has it in 26.0.3
