### ISSUE TITLE
v.22.1.2 «unable to locate its companion shared library»

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#17084] opened 2022-07-14 10:50 UTC
after uninstalling and reinstalling 22.1.1 problem disappeared 

related?: #14122

**Comment by E1izabeth** [comment] 2022-07-14 11:05
Thank you for bug report. This issue is a duplicate of #17048, so, I'll close it.

**Closed as completed by E1izabeth** 2022-07-14 11:05 UTC
Labels: duplicate
