### ISSUE TITLE
Can't perform export of Date type column to JSON and Source code

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14820] opened 2021-12-07 08:19 UTC
#### System information: 
- Win10 
- DBeaver CE 21.3.0

#### Connection specification:
- Tested on ClickHouse, DB2, Derby, MariaDB

#### Describe the problem you're observing:
DateTime column can be exported without any problem. But if you have Date column in the source table when export you'll get an error 

#### Include any warning/errors/backtraces from the logs
For JSON
```
java.lang.UnsupportedOperationException
	at java.sql/java.sql.Date.toInstant(Unknown Source)
	at org.jkiss.dbeaver.model.data.json.JSONUtils.formatDate(JSONUtils.java:51)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterJSON.exportRow(DataExporterJSON.java:142)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:233)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:252)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:169)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```
For Source code
```
java.lang.UnsupportedOperationException
	at java.sql/java.sql.Date.toInstant(Unknown Source)
	at org.jkiss.dbeaver.model.data.json.JSONUtils.formatDate(JSONUtils.java:51)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterSourceCode.exportRow(DataExporterSourceCode.java:156)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:233)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:252)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:169)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by LonwoLonwo** [comment] 2021-12-07 09:33
Duplicate of https://github.com/dbeaver/dbeaver/issues/12503
(Thanks for the error log)

**Closed as completed by LonwoLonwo** 2021-12-07 09:33 UTC
Labels: xf:datatransfer
