### ISSUE TITLE
Change timezone from Europe/Kiev to Europe/Kyiv

### ISSUE THREAD

**Issue by SashaArtemuk** [dbeaver/dbeaver#18965] opened 2023-02-06 13:27 UTC
### Description

timedatectl have recently changed Europe/Kiev timezone to Europe/Kyiv. As a result dbeaver doesnt work with this timezone. Please, change timezone or add new(for compatibility, some users still have Europe/Kiev timezone).
![image](https://user-images.githubusercontent.com/35603870/216983071-63e7088f-a367-4251-92b3-afbd3b58009d.png)

### DBeaver Version

Community edition 22.3.4

### Operating System

ubuntu 20.04

### Database and driver

not related

### Steps to reproduce

1. Change timezone to Europe/Kyiv
2. Open dbeaver
3. get error 
![image](https://user-images.githubusercontent.com/35603870/216983408-c8b60c95-568d-4f0a-aee8-7289c9602149.png)

**Comment by ShadelessFox** [comment] 2023-02-06 13:54
Hello @SashaArtemuk,

Thank you for your suggestion.

It was recently fixed in Java: https://bugs.openjdk.org/browse/JDK-8284405

**Comment by gagabu** [comment] 2023-02-07 14:10
It appears that currently postgres does not support Europe/Kyiv client timezone.
As workaround I [changed](https://stackoverflow.com/questions/45323552/how-to-change-dbeaver-timezone-how-to-stop-dbeaver-from-converting-date-and-ti/72533665#72533665 ) timezone in dbeaver to Universal and now it works.

**Comment by Destrolaric** [comment] 2023-02-07 14:56
https://www.postgresql.org/docs/release/15.1/#:~:text=the%20Europe/Kiev%20zone%20has%20been%20renamed%20to%20Europe/Kyiv
Since Postgres 15.1, the issue is fixed, but older versions require an old timezone name to work correctly. Still trying to figure out what to do about that. As a workaround in Java old timezone name also exists and can be used to work with old versions of Postgres.

**Comment by gagabu** [comment] 2023-02-07 15:39
I'm using latest docker image of postgres:
`PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`
And if run:
`SELECT "name" FROM PG_TIMEZONE_NAMES;`

There is only Europe/Kiev or posix/Europe/Kiev and no Kyiv

**Comment by ShadelessFox** [comment] 2023-02-07 15:42
I thought the issue was about timezone configuration in DBeaver? If not, it seems to be a third-party issue.

**Comment by Destrolaric** [comment] 2023-02-07 15:56
@ShadelessFox DBeaver, due to having a pretty recent Java version, contains the timezone, which is not supported for an old version of Postgres. So not sure about it being the issue of timezone configuration.

**Comment by ShadelessFox** [comment] 2023-02-07 16:00
@SashaArtemuk can you please clarify what your issue is about? What are you trying to do?

**Comment by SashaArtemuk** [comment] 2023-02-09 10:25
> @SashaArtemuk can you please clarify what your issue is about? What are you trying to do?

as far as I understood, this is postgres issue, not dbeaver, the solution that @gagabu offered works, thanks
however, you can add feature that replaces Kyiv on Kiev when connecting to old postgres versions, so users will get things done without receiving error and googling

**Comment by Destrolaric** [comment] 2023-02-09 10:58
@gagabu I have looked, and for the Postgre Debian docker image, its Debian version doesn't have Europe/Kyiv as an available timezone, so that is the probable reason why this doesn't work for your instance

**Comment by gagabu** [comment] 2023-02-09 11:00
It is depends not only postgres version, but on distribution. For example, the latest official docker image (https://hub.docker.com/_/postgres) is 15.1, but it doesn't support Kyiv timezone.
In other way, bitnami postgres image (https://hub.docker.com/r/bitnami/postgresql) supports both old and new timezone name.

**Comment by chinskiy** [comment] 2023-02-09 12:23
Also faced an error like in the original message at DBeaver 22.3.4 during connection to the PostgreSQL 12.10
After rollback to DBeaver 22.3.3 issue disappear to me

**Comment by Destrolaric** [comment] 2023-02-09 12:37
@chinskiy I think Java 11 didn't have Europe/Kyiv, so the old value was passed. After the upgrade to Java 17, it started using a new one, making the connection fail.

**Comment by Oleg-Odessa** [comment] 2023-02-17 13:48
@SashaArtemuk Just try to change Timezone in DBeaver Preferences
![image](https://user-images.githubusercontent.com/62992559/219671226-0b961b6e-cf66-4d0b-addb-b1f7e077a2e4.png)

**Comment by Destrolaric** [comment] 2023-03-02 14:55
We are reverting to Java 11 in 23.0.0, so the issue should not be actual for some time. Maybe it will arise again if Java 17 is used again.

**Comment by vojd11** [comment] 2023-08-29 14:00
same issue in 23.1.4

**Closed as completed** 2023-10-04 13:16 UTC
Labels: enhancement, x:postgresql, third party issue, sp:2, xp:normal, xo:java

**Comment by Baklov** [comment] 2025-06-24 00:34
I had this Error in my Spring Boot application: org.postgresql.util.PSQLException: FATAL: invalid value for parameter "TimeZone": "Europe/Kiev". My stack is Windows 11 / 10

PostgreSQL remote (somewhere with old tzdata )

JDBC driver 42.5.5

Spring Boot 3.2.2

HikariCP 5.0.1 . I found that I have to put this → -Duser.timezone=Europe/Kyiv. in VM options in Run/Debug configurations. Now work brilliant.
