### ISSUE TITLE
Have open files/tables saved for each project separately.

### ISSUE THREAD

**Issue by steelunicorn** [dbeaver/dbeaver#34259] opened 2024-06-05 08:55 UTC
As of now all open files/functions/tables etc. are shown at top bar and it is hard to understand which file in which project is used.
I suggest that on changing active project all open tabs from old project are saved (i mean saved info of which files were opened), tabs are closed, and if there was info on opened files in current active project - all those files are reopened.

**Comment by E1izabeth** [comment] 2024-06-05 08:58
Thank you for request.
I'm closing it as a duplicate of #21485
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-06-05 08:58 UTC
Labels: duplicate, xf:ui
