### ISSUE TITLE
Blank Popup will shown with ssh tunnel

### ISSUE THREAD

**Issue by ramrasi** [dbeaver/dbeaver#4588] opened 2018-11-09 12:24 UTC
If i connect server with ssh Tunnel one blank popup.

![image](https://user-images.githubusercontent.com/6615196/48262401-68b0de00-e448-11e8-8910-515d96f6374d.png)

**Comment by serge-rider** [comment] 2018-11-13 16:01
Can't reproduce. What is your OS/windows manager?
What happens if you close this popup?

**Comment by ramrasi** [comment] 2018-11-19 03:45
I am Using Fedora 28 x64 / Mate Desktop

**Comment by wzygadlo** [comment] 2018-11-21 23:49
I have got the same problem on ArchLinux DBVersion 5.2.4

![archlinux 2018-11-21 15-48-57](https://user-images.githubusercontent.com/26280326/48873859-12775f80-eda5-11e8-9d6b-a552d56169cb.png)

**Comment by uslss** [comment] 2019-03-31 21:35
cannot reproduce on 6.0.2 (ubuntu 18.04)

**Closed by uslss** 2019-03-31 21:35 UTC
Labels: bug, can't reproduce, question
