### ISSUE TITLE
I can't edit cell on a resultset

### ISSUE THREAD

**Issue by Tiger136500** [dbeaver/dbeaver#6127] opened 2019-06-20 02:08 UTC
I having this problem with DBeaver6.1 for linux.it's not a readonly oracle connection,if I try to  execute `select * from SYS.DICTIONARY;` and i can edit this result ,but when i select myself database  just like `select  *  from cs.test;`,i can't edit the result and the button of SAVE、CANCEL、Script was disabled,but if i press F4 when cursor is on table name,after that ,whatever i executed,that result can be modified

**Comment by Tiger136500** [comment] 2019-06-20 03:12
and it's happens only in version 6.1

**Comment by p91paul** [comment] 2019-06-20 06:10
There was a bug in 6.1, you should upgrade to the latest version

**Comment by Tiger136500** [comment] 2019-06-20 06:56
> There was a bug in 6.1, you should upgrade to the latest version
i had download 6.0version DBeaver  and it's work
Thanks for your answer

**Comment by uslss** [comment] 2019-06-20 20:10
Seems to be duplicate of #5957 
Closed.

**Closed by uslss** 2019-06-20 20:10 UTC
Labels: bug, duplicate, x:oracle
