### ISSUE TITLE
23.1.5 not create new connection or connect to existing connections

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [dbeaver/dbeaver#20937] opened 2023-08-21 13:25 UTC
![image](https://github.com/dbeaver/dbeaver/assets/25248634/b260bd64-7a86-4288-a5c3-cd60a797cdeb)
### Description

23.1.5 not create new connection

### DBeaver Version

23.1.5

### Operating System

Win10

### Steps to reproduce

Try create new connection...

**Comment by E1izabeth** [comment] 2023-08-21 13:45
Thank you for bug report.
Please try this workaround https://github.com/dbeaver/dbeaver/issues/20931#issuecomment-1685636108

I'm closing this as a duplicate of #20931

**Closed as not planned** 2023-08-21 13:45 UTC
Labels: duplicate, xf:ui

**Comment by aleksandr-shevchenko** [comment] 2023-08-21 13:57
I'll wait for the fixed version, but for now I rolled back to 23.1.4...
