### ISSUE TITLE
DB Name start with Numeric; Procedure is not visible in Database Navigator Panel.

### ISSUE THREAD

**Issue by jdabhi-hah** [dbeaver/dbeaver#22720] opened 2024-02-06 07:44 UTC
I am facing an issue while viewing of procedures on UI database Navigator. It happens where the DBNAME start with Numeric and followed by alphabets.

To recreate the issue:
1. Create database using snowflake Datawarehouse. start with "1test". (Database name must start with numeric.)
2. Create a procedure in same database with any name you want.
3. Check Database Navigator panel, select newly created database. select procedure dropdown.
4. You won't be able to see the procedure which you just created above.
5. we can run or access the procedure by SQL editor. Doing query on top of this procedure.

I want to see the procedure in database navigator where DB name start with Numeric.

**Comment by LonwoLonwo** [comment] 2024-07-25 11:33
Hello @jdabhi-hah 

Sorry for the late response. Ticket reopening can lead to it.

Could you please clarify this step?

> Create a procedure in the same database with any name you want.

Did you try to refresh the navigator view after the procedure was created?

![image](https://github.com/user-attachments/assets/5ff27a5d-3d05-4d36-9b26-d5494332064b)

For now, I can't reproduce your issue.

**Comment by jdabhi-hah** [comment] 2024-07-25 16:38
Hello @LonwoLonwo,

Oh. that's weird. 
I have one request here. 

Can you create a schema name which start like '**1up**'. then try to create SP in that schema. Now, can you see the procedure inside that schema?

**Comment by jdabhi-hah** [comment] 2024-07-25 16:41
> Hello @jdabhi-hah
> 
> Sorry for the late response. Ticket reopening can lead to it.
> 
> Could you please clarify this step?
> 
> > Create a procedure in the same database with any name you want.
> 
> Did you try to refresh the navigator view after the procedure was created?
> 
> ![image](https://private-user-images.githubusercontent.com/45152336/352089509-5ff27a5d-3d05-4d36-9b26-d5494332064b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjU1NjYsIm5iZiI6MTcyMTkyNTI2NiwicGF0aCI6Ii80NTE1MjMzNi8zNTIwODk1MDktNWZmMjdhNWQtM2QwNS00ZDM2LTliMjYtZDU0OTQzMzIwNjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE2MzQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MWY0ZGQ4ZWNhYjM2NzliYzgyODFkOGE4ZDVjNGMxMTM0NWMyMTc1ZjIxMWU0NTY1ZGZmOWJkNGNkOTgyMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oWU0uanKK5rRavozPGdfU6yx5Y4XLNTAYBFavyqfLlQ)
> 
> For now, I can't reproduce your issue.

Yes, I am refreshing the DB every time.

**Comment by uslss** [comment] 2024-08-07 20:43
Unfortunately still cannot reproduce the issue against 24.1.4

**Comment by jdabhi-hah** [comment] 2024-08-08 11:25
> Unfortunately still cannot reproduce the issue against 24.1.4

If you cannot reproduce the issue, feel free to close this issue.

**Comment by E1izabeth** [comment] 2024-09-05 09:54
Unfortunately, we can't reproduce the issue.
For now, I'm closing the issue. If we get similar report from another user or reproduce the issue, we will return to it.

**Closed as not planned by E1izabeth** 2024-09-05 09:54 UTC
Labels: can't reproduce, x:snowflake, xf:navigator, wait for response, xf:metadata
