### ISSUE TITLE
BUG: Granted roles in PostgreSQL appear with the same name after window refresh

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#10054] opened 2020-10-13 11:25 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 64-bit v2004 19041.508
- DBeaver version: Version 7.2.3.202010080916
- Java version: 1.8.0_261
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11
- Driver name: postgresql JDBC 42.2.14
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When opening a PostgreSQL role properties window, I can see the roles assigned to it properly.
After Right click->Refresh (F5) all the different role names change into the last role name in the list.

#### Steps to reproduce, if exist:
Run in Postgres:
`create role test1;`
`create role test2;`
`create role test3;`
`grant test2 to test1;`
`grant test3 to test1;`

Open/Refresh "Roles" navigation tree node
Double click on "test1"
Go to its' "Roles" tab
Right click on list ->refresh (or press F5) - you can see roles "test2" & "test3" change into "test3"

**Comment by uslss** [comment] 2020-10-15 11:08
Thanks for the bug report

**Comment by LonwoLonwo** [comment] 2020-11-22 10:29
Duplicate of https://github.com/dbeaver/dbeaver/issues/10271
(Will be fixed soon)

**Closed by LonwoLonwo** 2020-11-22 10:29 UTC
Labels: bug, x:postgresql
