### ISSUE TITLE
Table search in metadata not work

### ISSUE THREAD

**Issue by Ra5CZ** [dbeaver/dbeaver#12527] opened 2021-05-19 09:44 UTC
System information:
Operating system (distribution) and version Win10
DBeaver version 21.0.5

Connection specification:
Database: MSSQL

Steps to reproduce, if exist:
Open metadata search, select object source '_any database_', select object types 'Tables', select Name match to 'Contains' enter a valid value and begin the search

Expected: suitable objects are found
Actual result: objects are not found.

In version 21.0.2 works fine.

**Comment by kseniiaguzeeva** [comment] 2021-05-26 17:37
I cannot reproduce it. Is you table in _dbo_ schema?

**Comment by uslss** [comment] 2021-06-20 16:29
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info

**Comment by Ra5CZ** [comment] 2021-06-21 11:48
Sorry I'd forgotten send response.
My table is in _cor_ schema, or any other schemas. If I selected DB and try search table, it's not work.
![image](https://user-images.githubusercontent.com/66022207/122756596-e68f2400-d296-11eb-87e1-6a62629ea17d.png)
If is selected schema with table, search works. But I have many schemas and search worked on all of it.
![image](https://user-images.githubusercontent.com/66022207/122756735-19391c80-d297-11eb-8dcb-eba0c0855536.png)

On version 21.1.1 still not work.

**Comment by Ra5CZ** [comment] 2021-07-07 06:16
In 21.1.2 still not work.
![Snímek obrazovky 2021-07-07 081550](https://user-images.githubusercontent.com/66022207/124709303-9bfae200-defb-11eb-9972-b15cb4510c30.png)

**Comment by Ra5CZ** [comment] 2021-07-07 06:20
This is in 21.0.2
![Snímek obrazovky 2021-07-07 081951](https://user-images.githubusercontent.com/66022207/124709758-28a5a000-defc-11eb-8344-c685fb280714.png)

**Comment by flambchap** [comment] 2021-09-02 13:24
Thank you for your report. I'm working on it. The same problem can be observed in PostgreSQL.

**Comment by flambchap** [comment] 2021-09-03 09:56
Duplicate of https://github.com/dbeaver/dbeaver/issues/12143.

**Closed as completed by flambchap** 2021-09-03 09:56 UTC
Labels: x:postgresql, duplicate, x:mssql, sp:1, xf:metadata, xf:search

**Comment by Ra5CZ** [comment] 2023-02-08 10:21
Same problem again. Again, can't search in table metadata. The table exists, but it cannot be searched. The problem first manifested itself on a brand new DBeaver installation. I have tried reinstalling to versions 22.3.4, 22.3.3, 22.3.2, 22.3.1, 22.3.0 and 22.1.5. But strangely, on the old PC where I am using version 22.3.3, the search works. Even resetting the settings does not help.

New PC with 22.3.4 originally installed and reinstalled on 22.1.5
![image](https://user-images.githubusercontent.com/66022207/217502255-8d03a2c6-bb6d-4456-99f1-e22f49d41f31.png)

Old PC with version 22.3.3
![OldPC-22 3 3](https://user-images.githubusercontent.com/66022207/217502297-b5dea101-0084-4b47-8d8c-a79c3e5d860b.png)
