### ISSUE TITLE
SQL Server: Table index DDL is empty

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#15270] opened 2022-01-24 10:59 UTC
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.2

#### Connection specification:
- Database name and version SQL Server
#### Steps to reproduce, if exist:
Open a table index DDL in the Metadata Editor

**Expected**: the DDL tab has content or doesn't exist
**Actual result**: the DDL tab is empty

**Comment by LonwoLonwo** [comment] 2023-06-01 14:16
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/15270

**Closed as completed by LonwoLonwo** 2023-06-01 14:16 UTC
Labels: duplicate, x:mssql, xf:metadata, xp:normal
