### ISSUE TITLE
Auto format: Convert keyword case not working in 22.2.4

### ISSUE THREAD

**Issue by owendw1** [dbeaver/dbeaver#18227] opened 2022-11-15 23:15 UTC
### Description

Since upgrading to 22.2.4, the "Convert keyword case" functionality doesn't seem to work. When typing SQL statements in an SQL Editor, the automatic conversion of keywords to uppercase is no longer happening.

For example, "select * from mytable;" should convert to "SELECT * FROM mytable;" automatically as I type.

I've checked and the correct settings are in place:
1) Editors -> SQL Editor -> Code Editor -> Auto format: Convert keyword case
2) Editors -> SQL Editor -> Formatting -> Settings: Keyword case: Upper

### DBeaver Version

Community Edition 22.2.4

### Operating System

Ubuntu 20.04

### Database and driver

Database name and version: All MySQL and PostgreSQL databases
Driver name: MySQL Connector/J mysql-connector-java-8.0.29 and PostgreSQL JDBC Driver 42.5.0

### Steps to reproduce

Set the following settings:
1) Editors -> SQL Editor -> Code Editor -> Auto format: Convert keyword case
2) Editors -> SQL Editor -> Formatting -> Settings: Keyword case: Upper

In an SQL script, type, for example, "select * from mytable;". The automatic conversion to "SELECT * FROM mytable;" doesn't happen.

**Comment by E1izabeth** [comment] 2022-11-16 00:24
Thank you for bug report.
It's a duplicate of #18131

**Closed as not planned by E1izabeth** 2022-11-16 00:24 UTC
Labels: duplicate
