### ISSUE TITLE
DBeaver Does not return recordset for External Schemas

### ISSUE THREAD

**Issue by mmaayeh** [dbeaver/dbeaver#5773] opened 2019-04-23 05:58 UTC
#### System information: 
- Operating system (distribution) and version: Mac OS X Sierra Version 10.12.6
- DBeaver version: 6.0.3.201904211926
- Java version : 
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

- Additional extensions

#### Connection specification:
- Database name and version: Redshift Cluster 1.0.7078
- Driver name: Redshift (Library: com.amazon.redshift:redshift-jdbc42:RELEASE)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
When selecting from an external schema the result is always "no data" where there will be many thousands to many millions of records.  Also, viewed data from alternate clients such as psql command line client, as well as, Amazon technology from Athena for AWS Glue where these technologies have data being returned.
#### Steps to reproduce, if exist:
Select * from <external_schema>.<table_name> limit 10;

#### Include any warning/errors/backtraces from the logs

N/A

**Comment by serge-rider** [comment] 2019-04-23 15:03
Duplicate of #5771 
You can test the fix in Early Access version (https://dbeaver.io/ea)

**Closed by serge-rider** 2019-04-23 15:03 UTC
Labels: bug, duplicate, x:redshift
