### ISSUE TITLE
Filters in Data tab are not saved after applying

### ISSUE THREAD

**Issue by sergtop** [dbeaver/dbeaver#4480] opened 2018-10-24 06:32 UTC
After applying a filter in the data tab of a table this filter is not saved in the list of previously used filters (I think the caret down button to the right of a text field is supposed to hold these filters)
MacOS 10.14.1
DBeaver 5.2.3

**Comment by Sappurit** [comment] 2018-11-23 14:20
Yes, it's very handy function but it couldn't save. and can't remember the previous histories.

**Comment by akilovich** [comment] 2020-12-09 15:49
Duplicate of https://github.com/dbeaver/dbeaver/issues/10343.

**Closed by akilovich** 2020-12-09 15:49 UTC
Labels: xo:macos
