### ISSUE TITLE
Data Type - Properties of a column, when showing Data Type, not all text is visible

### ISSUE THREAD

**Issue by duskox** [dbeaver/dbeaver#20095] opened 2023-05-25 09:22 UTC
### Description

When looking at Properties of a column, in case of an enum field that has many entries, they are not all visible due to the right side of the screen overlapping the fields in the left part, as can be seen on the uploaded screenshot.

It is possible to click on the field and move the cursor with the keys all the way to the end of the string in the field, but it doesn't scroll into view, since I am guessing it's an overlap of the right side.

![Screenshot 2023-05-25 at 11 13 47](https://github.com/dbeaver/dbeaver/assets/792923/c63f2bf5-8bb8-4313-b5ec-c622350b6b7d)

### DBeaver Version

23.0.5

### Operating System

macOS Ventura 13.3.1 (a)

### Database and driver

MySQL 8

**Comment by E1izabeth** [comment] 2023-05-25 09:26
Thank you for bug report. 
It's duplicate of #19202, so I'm closing this issue.
You can vote under the #19202 by adding some emoji under the issue description

**Closed as not planned by E1izabeth** 2023-05-25 09:26 UTC
Labels: duplicate, xf:metadata, xf:ui
