### ISSUE TITLE
Spatial viewer fails to render if a geometry with a z-axis (altitude) is selected

### ISSUE THREAD

**Issue by phg0090** [dbeaver/dbeaver#9809] opened 2020-09-18 09:29 UTC
#### System information: 
- Ubuntu 20.04
- DBeaver 7.2.0
- Additional extensions: none

#### Connection specification:
- PostgreSQL 10 / PostGIS 2.4.3
- PostgreSQL JDBC Driver
- SSH Tunnel

#### Describe the problem you're observing:

The spatial viewer fails to render if a geometry with a z-axis (altitude) is selected. Tested on POLYGON And MULTIPOLYGON, with zero z-axis values and non-zero real world altitudes. Removing the z-axis from the geometry is a work around that lets the polygons render in the map view. 

#### Steps to reproduce, if exist:
-- This will work and render in the Map view
SELECT st_geomfromtext('POLYGON ((-5.8877073708810315 54.5612519325625, -5.8877073708810315 54.54789964061726, -5.920451778535011 54.54789964061726, -5.920451778535011 54.5612519325625, -5.8877073708810315 54.5612519325625))',4326);

-- This is the same polygon with zero altitude (z-axis) added, it will NOT render in the Map view
SELECT st_geomfromtext('POLYGON ((-5.8877073708810315 54.5612519325625 0, -5.8877073708810315 54.54789964061726 0, -5.920451778535011 54.54789964061726 0, -5.920451778535011 54.5612519325625 0, -5.8877073708810315 54.5612519325625 0))',4326);
		

#### Include any warning/errors/backtraces from the logs
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.600.v20200116-2127]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.900.v20200213-1442]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.200.v20200127-0814]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start EMF Common [org.eclipse.emf.common 2.18.0.v20191225-1014]
> Start EMF Ecore [org.eclipse.emf.ecore 2.21.0.v20200127-1342]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.800.v20191212-1231]
> Start Expression Language [org.eclipse.core.expressions 3.6.700.v20200212-1751]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1100.v20200217-1217]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.800.v20191216-0805]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.15.500.v20200106-1259]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.900.v20200203-0840]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.12.600.v20200124-0005]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.55.202008302047]
> Start Help System Core [org.eclipse.help 3.8.700.v20191212-1123]
> Start Default Text Editor [org.eclipse.ui.editors 3.13.100.v20200130-1507]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.14.100.v20200212-1049]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.40.202008302047]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.30.202008302047]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.40.202008302047]
> Start File Buffers [org.eclipse.core.filebuffers 3.6.900.v20200117-0616]
> Start Team Support Core [org.eclipse.team.core 3.8.900.v20200211-0946]
> Start Core Compare Support [org.eclipse.compare.core 3.6.800.v20191213-2246]
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.6.300.v20200211-1504]
> Start Equinox Provisioning Operations API [org.eclipse.equinox.p2.operations 2.5.700.v20191211-1713]
> Start Equinox Provisioning Platform Automatic Update Support [org.eclipse.equinox.p2.ui.sdk.scheduler 1.4.600.v20200221-0754]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.4.700.v20191213-1911]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.300.v20200222-1600]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.6.600.v20200110-2121]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.400.v20191211-1528]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.4.700.v20200110-2121]
> Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.5.800.v20200213-1530]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.40.202008302047]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.77.202008302047]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.46.202008302047]
> Start DBeaver ER Diagram [org.jkiss.dbeaver.ext.erd 2.0.142.202008302047]
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.126.202008302047]
> Start DBeaver PostgreSQL Support [org.jkiss.dbeaver.ext.postgresql 2.1.113.202008302047]
> Start DBeaver SQL Server Support [org.jkiss.dbeaver.ext.mssql 1.0.134.202008302047]
> Start Console [org.eclipse.ui.console 3.9.100.v20200215-1209]
> Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh 1.0.61.202008302047]
> Start DBeaver SSH implementation (JSch) [org.jkiss.dbeaver.net.ssh.jsch 1.1.50.202008302047]
> Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh.ui 1.0.61.202008302047]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.500.v20200114-1637]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.3.700.v20200212-0844]
> Start Internet Connection Management [org.eclipse.core.net 1.3.800.v20200218-0937]
> Start JSch Core [org.eclipse.jsch.core 1.3.800.v20200106-0907]
> Start JSch UI [org.eclipse.jsch.ui 1.3.800.v20200205-0619]
> Start DBeaver Data GIS - view [org.jkiss.dbeaver.data.gis.view 1.0.35.202008302047]

**Comment by uslss** [comment] 2020-10-05 09:01
seems to be duplicate of #9270
thanks for the report

**Closed by uslss** 2020-10-05 09:01 UTC
Labels: bug, duplicate, xf:gis
