### ISSUE TITLE
feature request:  allow user to change auto-completion key

### ISSUE THREAD

**Issue by ccurvey** [dbeaver/dbeaver#3264] opened 2018-04-04 15:35 UTC
I'd really like to be able to change the auto-completion key from "return" to "tab".  That way it will work the same as my other editors, and my shells.

**Comment by serge-rider** [comment] 2018-04-07 09:46
I'm afraid it will be very hard to implement. Current behavior (including shortcuts) is hardcoded in Eclipse platform.

**Comment by serge-rider** [comment] 2018-09-01 17:27
Duplicate of #2316

**Closed by serge-rider** 2018-09-01 17:27 UTC
Labels: question
