### ISSUE TITLE
Slow performance when Word Wrap is on for long text / JSON

### ISSUE THREAD

**Issue by pauljura** [dbeaver/dbeaver#20258] opened 2023-06-12 00:35 UTC
### Description

I have a table cell with ~90k of JSON data. Viewing this as Text or JSON doesn't seem to affect performance, turning on Auto Format doesn't seem to affect performance, but if I turn the Word Wrap option on, it takes several seconds to load.

In this screen capture, it's only the Australian data that is large, while NZ is ~2k.

![word-wrap-performance](https://github.com/dbeaver/dbeaver/assets/42629973/d22bb245-ca67-4e77-a9a4-dc2c2e473d94)

### DBeaver Version

Community Edition Version 23.1.0.202306041918

### Operating System

Windows 10

### Database and driver

MySQL 5.7.38-log

MySQL Connector/J mysql-connector-java-8.0.29 

### Steps to reproduce

See GIF

**Comment by LonwoLonwo** [comment] 2023-06-12 08:07
Thanks for the report @pauljura 

I'm closing this issue as a duplicate of https://github.com/dbeaver/dbeaver/issues/11802.

You can vote for the original ticket with +1 emoji.

**Closed as completed by LonwoLonwo** 2023-06-12 08:07 UTC
Labels: duplicate, xf:data, performance
