### ISSUE TITLE
Right click in SQL editor deselects selected text

### ISSUE THREAD

**Issue by Zelphium** [dbeaver/dbeaver#18181] opened 2022-11-10 17:33 UTC
### Description

Since the latest build, 22.2.4, selecting text and right clicking on the text deselects the text, making it impossible to use context menu operations such as 'morph to delimited list'.

### DBeaver Version

22.2.4

### Operating System

Windows 10

### Steps to reproduce

Open a SQL editor to a database. Enter text. Select text. Right click. Text will become deselected.

**Comment by E1izabeth** [comment] 2022-11-10 18:09
Thank you for bug report. It's a duplicate of #18152
Fix will be available in the next release.

**Closed as not planned** 2022-11-10 18:09 UTC
Labels: duplicate

**Comment by Zelphium** [comment] 2022-11-11 09:04
> Thank you for bug report. It's a duplicate of #18152 Fix will be available in the next release.

Ah, thank you! I did look but couldn't see anything. Good to know a fix is on the way!
