### ISSUE TITLE
application not responding on Mac OS Big Sur 

### ISSUE THREAD

**Issue by hiwjcn** [dbeaver/dbeaver#9818] opened 2020-09-19 15:13 UTC
```
apple@192 ~ % java -version 
java version "1.8.0_212"

apple@192 ~ % echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home
```

**Comment by yingtao-futurewonder** [comment] 2020-09-19 18:44
I have the same issue.

**Comment by serge-rider** [comment] 2020-09-21 17:25
Seems to be duplicate of #9533 

Workaround: download pkg installer.

**Closed by serge-rider** 2020-09-21 17:25 UTC
Labels: bug, duplicate, xo:macos
