### ISSUE TITLE
commit statement not recognized as commit by transaction handler

### ISSUE THREAD

**Issue by molok** [dbeaver/dbeaver#7760] opened 2020-01-29 09:26 UTC
#### System information: 
- Operating system (distribution) and version: Ubutu 19.10
- DBeaver version: 6.3.3 (official repo)
- Java version (1.8)
- Additional extensions (vrapper)

#### Connection specification:
- Database name and version (postgresql 11)
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Using manual transaction, dbeaver does not recognize a commit as such

#### Steps to reproduce, if exist:
1. connect to a postgresql database
2. issue an update
3. execute a commit statement
4. watch it being added to the transaction log

![image](https://user-images.githubusercontent.com/34475/73343939-bc902880-4281-11ea-8e32-d42ae08cc271.png)

**Comment by uslss** [comment] 2020-01-29 09:33
thanks for the bug report

**Comment by serge-rider** [comment] 2020-02-07 11:42
It is not a bug. It is a feature, it requires to support different dialects + it still won't be able to detect commit/rollback when they are initiated in stored procedures.

**Comment by molok** [comment] 2021-08-04 08:55
@uslss can you clarify why this bug was closed?

**Comment by uslss** [comment] 2021-08-04 08:56
My fault, it was closed by mistake :)

**Comment by molok** [comment] 2021-08-04 09:11
From a programmer point of view I understand why @serge-rider thinks it's a feature, but from the user-experience point of view it's 100% a bug: why would a click on the commit button and executing a commit statement have different behavior?
If DBeaver isn't able to detect when a transaction ends maybe the UI should reflect that, instead of trying to implement the transaction lifetime detection for each dialect.

**Closed** 2023-11-14 10:43 UTC
Labels: feature request, xf:sql, sp:2, xp:normal

**Comment by Udo-L-Mayer** [comment] 2025-03-17 19:40
Hello, still on this topic. 
Using DBEaver 25.0.0 with postgres. I noticed that if I select from the "START TRANSACTION" as well as the "UPDATE" command block and also the "COMMIT TRANSACTION" command and execute everything at once, the COMMIT will be done in the database, even so in the transaction log there will be pending transactions.

That's all!
