### ISSUE TITLE
UI bug,how can I reset?

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#36002] opened 2024-10-21 01:25 UTC
### Description

SQL result plane UI bug,can't see run time cost.See as pic:
![image](https://github.com/user-attachments/assets/5bb58673-bf75-4423-bdbb-abee4d46b201)
I have try reset UI by this way:https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings/72a7d53713f622addab4d6cdaa6e406a56b94830,but it doesn;t work...

### DBeaver Version

24.0

### Operating System

winserver2008R2

**Comment by leezm** [comment] 2024-10-21 01:36
MY fault!
I just delete xmi...
After I try  help->Reset Settings...Choose User preferences,then reset,it works.But I lose my font and theme and etc.

**Comment by leezm** [comment] 2024-10-21 02:20
But when I set other font.This problem occurs again...

**Comment by Destrolaric** [comment] 2024-10-24 10:30
Hi, could you show what exactly dissappears if font is changed?

**Comment by leezm** [comment] 2024-10-24 10:53
> Hi, could you show what exactly dissappears if font is changed?

![image](https://github.com/user-attachments/assets/91c18d07-67e7-449b-9878-e5ac9dff2539)
run time cost

**Comment by E1izabeth** [comment] 2024-11-21 11:01
We can't reproduce the issue. Could you provide clear steps to reproduce it?

**Comment by leezm** [comment] 2024-11-21 13:09
> We can't reproduce the issue. Could you provide clear steps to reproduce it?

After I switched to winserver 2025, it is now normal. I think it may have been screen tearing in win11 24H2 and winserver2008R2 remotely through RDP. Maybe it was caused by this problem. Sorry for causing trouble to you.

**Comment by E1izabeth** [comment] 2024-11-21 14:28
I see. Thank you.
I'll close the issue then. Let me know if you encounter this problem again

**Closed as not planned by E1izabeth** 2024-11-21 14:28 UTC
Labels: can't reproduce, wait for response, xf:ui
