### ISSUE TITLE
Cannot create a new DB connection: buttons without function

### ISSUE THREAD

**Issue by mhaertel** [dbeaver/dbeaver#8571] opened 2020-04-28 11:55 UTC
#8214 ## System information: 
- Windows 10 (Version 10.0.17763.1132)
- DBeaver version 7.0.3 (ZIP Version, downloaded today)
- Additional extensions: NONE

#### Connection specification:
ALL

#### Describe the problem you're observing:

Since one of the last updates I am not able to define a new DB connection. 

The "Verbindung testen" (Test connection) button has no function (It is clicked but nothing happens), same with the "Fertigstellen" (confirm/OK) button.  

#### Steps to reproduce, if exist:
New Connection > PostgreSQL (Also tested SQL Lite)

#### Include any warning/errors/backtraces from the logs
No error messages, Exceptions or popup windows.

**Comment by uslss** [comment] 2020-04-28 14:11
seems to be fixed in scope of #8503 
anyway, thanks for the bug report
as a workaround try to use New connection button ![image](https://user-images.githubusercontent.com/31996417/80225229-7285cb80-8653-11ea-8c11-2a38723c7ad8.png) is used - issue isn't reproducible

**Closed by uslss** 2020-04-28 14:11 UTC
Labels: bug, wait for review

**Comment by mhaertel** [comment] 2020-04-28 14:25
Thank you for the comment. I added a comment to #8503. 

So in my case the + Button didn't work but connections > create worked fine. 

In either case: there is a workaround which works.

Thank you for your investigation.
