### ISSUE TITLE
Data Export Error Inquiry

### ISSUE THREAD

**Issue by HoonK212** [dbeaver/dbeaver#13091] opened 2021-07-05 02:57 UTC
#### System information: 
- Operating system (distribution) and version : Big Sur 11.4
- DBeaver version : 21.1.1
- Additional extensions : none

#### Connection specification:
- Database name and version : Oracle 11g enterprise & Oracle 11g xe
- Driver name : oracle.jdbc.OracleDriver (default oracle driver in dbeaver)
- Do you use tunnels or proxies (SSH, SOCKS, etc) : nope

#### Describe the problem you're observing:

1. Back up tables from 'Oracle 11g enterprise' to 'Oracle 11g xe' with data export from DBeaver.
2. Backup aborted due to 'ORA-12953' error due to full capacity on 'Oracle 11g xe' side.
3. Data loss occurs in the source table (on the 'Oracle 11g Enterprise' side) immediately after backup is down.
4. Unable to track whether delete query was executed due to human error or tool error.

Q1. Is there any issue in advance that the delete query occurred due to an error in data export? (I didn't think there was any problem when I searched for it myself.)
Q2. Is there a possibility that both tables will be synchronized if the data export is forced to stop?

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2021-06-28 08:30:55.727
!MESSAGE Error transfering data from ORAEXR.TB_STOCK to LEEHANAPI.TB_STOCK [Existing]
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-06-28 08:30:55.727
!MESSAGE Can't insert row
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-06-28 08:30:55.727
!MESSAGE SQL Error [12953] [72000]: ORA-12953: The request exceeds the maximum allowed database size of 11 GB

!STACK 0
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [12953] [72000]: ORA-12953: The request exceeds the maximum allowed database size of 11 GB

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatementBatch(JDBCStatementImpl.java:155)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.flushBatch(ExecuteBatchImpl.java:284)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:206)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:327)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:297)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:202)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:240)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:161)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.sql.BatchUpdateException: ORA-12953: The request exceeds the maximum allowed database size of 11 GB

	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeBatch(OraclePreparedStatement.java:10032)
	at oracle.jdbc.driver.T4CPreparedStatement.executeLargeBatch(T4CPreparedStatement.java:1364)
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9839)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:234)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeBatch(JDBCStatementImpl.java:375)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatementBatch(JDBCStatementImpl.java:152)
	... 14 more
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2021-06-28 08:30:55.727
!MESSAGE ORA-12953: The request exceeds the maximum allowed database size of 11 GB

**Comment by Matvey16** [comment] 2021-07-08 07:21
@HoonK212 Thank you for the report. Can you attach the query that is executed (can be seen in query manager) when you perform data export.

![dbeaver_uKZz3kuZIL](https://user-images.githubusercontent.com/82543000/124879769-3f202a00-dfd6-11eb-986b-07e20e9f23fe.png)

![L8rXwgdTq5](https://user-images.githubusercontent.com/82543000/124879792-45160b00-dfd6-11eb-9938-4d97e9245755.png)

**Comment by HoonK212** [comment] 2021-07-14 05:46
> @HoonK212 Thank you for the report. Can you attach the query that is executed (can be seen in query manager) when you perform data export.
> 
> ![dbeaver_uKZz3kuZIL](https://user-images.githubusercontent.com/82543000/124879769-3f202a00-dfd6-11eb-986b-07e20e9f23fe.png)
> 
> ![L8rXwgdTq5](https://user-images.githubusercontent.com/82543000/124879792-45160b00-dfd6-11eb-9938-4d97e9245755.png)

I didn't use any query, just clicked data export and export database table.

**Comment by Matvey16** [comment] 2021-07-14 06:23
@HoonK212 Data export performs a query in the background for you, when you start it. Query manager is here to look for those background queries that may have done something you don't know about.

**Comment by HoonK212** [comment] 2021-07-16 01:54
@Matvey16 There's any query left in Query manager. Can you suggest me any other way?

**Comment by Matvey16** [comment] 2021-07-21 13:43
@HoonK212 Can you try exporting it with batches disabled or with a lower amount of inserts before commit. Also check if your target database actually have enough storage to fit all of the transferring data. DBeaver can't delete data in source tables because in the process of export it only reads data from the source.

**Comment by HoonK212** [comment] 2021-07-23 05:57
Thank you for your answer. I'll ask you two more questions.
1. Unlike normal cases, is there any logic that runs separately when data export is forced to terminate due to capacity issues in the destination database?
2. Is there no way to check the queries that were executed at that time through query manager now (or any other way)?

**Comment by Matvey16** [comment] 2021-07-23 10:55
@HoonK212 The export process runs multiple queries to create tables and insert data. Depending on the moment where it encounters an error it will either just stop or skip the query if the skip is possible and you choose to do it. If an error is encountered due to a reached capacity the process is still the same. Everything before the last successful commit (you can choose batch size before commits) won't be rolled back.
Unfortunately if you didn't enable saving to log file in Query manager properties, you won't be able to access it.

**Comment by uslss** [comment] 2021-08-26 08:17
there is no update on issue for a long time.
If it is still actual - feel free to reopen it with additional info that could help to reproduce an issue

**Closed as completed by uslss** 2021-08-26 08:17 UTC
Labels: x:oracle, xf:datatransfer, wait for response
