### ISSUE TITLE
Execute sql does not stop reading at semicolon anymore

### ISSUE THREAD

**Issue by w97655** [dbeaver/dbeaver#26840] opened 2024-04-26 07:08 UTC
### Description

When you have more sql statements in the windows, each ending with a semicolon and you do execute-single-statement (ctrl-enter) then it fails, reading into the next line.
This error started with installing Version 24.0.3.202404211624.

### DBeaver Version

24.0.3.202404211624

### Operating System

Win 10

### Database and driver

PostgreSQL 14.9 on x86_64-pc-linux-gnu, compiled by x86_64-pc-linux-gnu-gcc (GCC) 9.5.0, 64-bit
PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

1) windows contents
select now()
;
--comment
1234
2) Put cursor on select line, press ctrl-enter
3) See ERROR: syntax error at or near "1234"

Execute current sql-statement is supposed to stop parsing at semicolon.

This is new in latest version. My way of working is that I often write the resultt right under the statement ... not with -- which greys text out ... and I expect the parser to stop at semicolon.

**Comment by E1izabeth** [comment] 2024-04-26 07:12
Thank you for bug report. It's a duplicate of #26416
We're working on fix

As a workaround, you could try switching `Blank line is statement delimiter` setting to `Always`
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be8457a0-d62c-4acb-ac2f-67ce518cf3f5)

**Closed as not planned by E1izabeth** 2024-04-26 07:12 UTC
Labels: duplicate, xf:sql execution

**Comment by w97655** [comment] 2024-04-26 07:16
Thanks Elizabeth!! I did a downgrade to 24.0.1 for now §:o)

**Comment by E1izabeth** [comment] 2024-04-29 08:15
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.
