### ISSUE TITLE
[Bug report] Oracle PL/SQL Scripts fail due to truncated semicolon

### ISSUE THREAD

**Issue by caldeirae** [dbeaver/dbeaver#4760] opened 2018-12-09 00:30 UTC
Running PL/SQL Blocks fail with ORA-06550 (Semicolon missing related).
I've noticed through the exectution log that when SQL runs without selection it removes the semicolon,
When the script is fully selected the semicolon remains and the script runs sucessfully.  

![imagem](https://user-images.githubusercontent.com/2472736/49692097-92dde480-fb49-11e8-9f38-3c278750e3de.png)

**Comment by p91paul** [comment] 2018-12-09 08:56
#4655

**Comment by serge-rider** [comment] 2018-12-09 10:15
Yep, duplicate of #4655

**Closed by serge-rider** 2018-12-09 10:15 UTC
Labels: bug, duplicate
