### ISSUE TITLE
SSH agent authentication no longer works in Windows with Pageant.

### ISSUE THREAD

**Issue by virgoparna** [dbeaver/dbeaver#14856] opened 2021-12-09 13:06 UTC
#### System information: 
- Windows 10 21H2
- DBeaver Version 21.2.2.202109281101

#### Connection specification:
- mariadb 10.5
- Driver name: MariaDB
- SSH tunnel

#### Describe the problem you're observing:

After update from Windows Store today DBeaver fails to connect to database over ssh tunnel with an error:
Unable to initialize SSH agent

Can't initialize tunnel
  Unable to initialize SSH agent

Pageant is running. 

#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Dec 09 14:45:57 EET 2021
Unable to initialize SSH agent

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Dec 09 14:45:57 EET 2021
Unable to initialize SSH agent

org.jkiss.dbeaver.DBException: Unable to initialize SSH agent
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:127)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:219)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$16(UIUtils.java:1698)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

There are also messages about failing to read windows registry, but agent errors are before those in timeline.
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Warning
Thu Dec 09 14:53:49 EET 2021
Error reading Windows registry

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Warning
Thu Dec 09 14:53:49 EET 2021
Could not initialize class com.sun.jna.Native

java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.platform.win32.WinReg$HKEYByReference.<init>(WinReg.java:52)
	at com.sun.jna.platform.win32.WinReg$HKEYByReference.<init>(WinReg.java:48)
	at com.sun.jna.platform.win32.Advapi32Util.registryKeyExists(Advapi32Util.java:623)
	at com.sun.jna.platform.win32.Advapi32Util.registryKeyExists(Advapi32Util.java:607)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.findLocalClients(MySQLDataSourceProvider.java:190)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.findLocalClientLocations(MySQLDataSourceProvider.java:136)
	at org.jkiss.dbeaver.ui.dialogs.connection.ClientHomesSelector$2.run(ClientHomesSelector.java:136)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ShadelessFox** [comment] 2021-12-09 14:11
Hello @virgoparna,

I'm a bit confused by the provided log.

Can you please clear the debug log file first, reproduce the issue, and then send the newly filled debug log?

**Comment by virgoparna** [comment] 2021-12-09 14:23
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/7685781/dbeaver.log)
Added.

**Comment by virgoparna** [comment] 2021-12-09 14:28
Something strange: inside DBeaver it shows version number 21.2.2 (in title bar). But when i right-clicked on shortcut and selected more, app settings then Windows shows Version: 21.3.1.0. Something strange with Store install?

**Comment by virgoparna** [comment] 2021-12-09 14:33
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/7685850/dbeaver-debug.log)
That was not debug log, that should be correct.

**Comment by ShadelessFox** [comment] 2021-12-09 14:42
Thanks, that's a much clearer log. We'll also investigate the version issue you've mentioned.

**Comment by pculka** [comment] 2021-12-10 15:41
I think I stumbled upon this issue, too.
Cannot initialize any ssh tunnel using agent.
Using windows store install
OS Windows 11

**Comment by ShadelessFox** [comment] 2021-12-10 15:45
As turned out, the Windows Store version is outdated. We're working on it.

**Comment by serge-rider** [comment] 2022-01-17 17:35
Seems to be caused by the same problem as #14882

**Comment by Matvey16** [comment] 2022-01-18 13:44
Verified on standalone version. Needs to be tested again after publishing in MS store

**Comment by SunMar** [comment] 2022-01-24 08:30
@Matvey16 @serge-rider it seems like somehow this issue still persists in the Windows Store version of DBeaver. If I download a standalone DBeaver version the SSH tunnel with Pageant works just fine, but my Microsoft Store installed version keeps giving the error "Unable to initialize SSH agent" even after upgrading to 21.3.3.

**Comment by uslss** [comment] 2022-01-24 08:40
Still reproducible:
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Mon Jan 24 11:36:39 MSK 2022
Unable to initialize SSH agent

org.jkiss.dbeaver.DBException: Unable to initialize SSH agent
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:127)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:76)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$7.execute(SSHTunnelConfiguratorUI.java:241)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:580)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment] 2022-02-07 07:44
fixed in 21.3.4

**Closed as completed by uslss** 2022-02-07 07:44 UTC
Labels: xo:windows, sp:3

**Comment by SunMar** [comment] 2022-02-07 07:47
Can confirm, just upgraded to 21.3.4 via the Microsoft Store and I can connect again using an SSH tunnel that negotiates the key via my (Pageant-compatible) GPG agent 🎉

**Comment by virgoparna** [comment] 2022-02-12 08:14
Works again.

**Comment by pculka** [comment] 2022-02-12 08:52
I confirm aswell, works with agent and keepass
