### ISSUE TITLE
Refresh button from DDL tab of a table

### ISSUE THREAD

**Issue by greg-finley-ck** [dbeaver/dbeaver#8228] opened 2020-03-20 05:44 UTC
When looking at a table, most tabs show a refresh button

![Screen Shot 2020-03-19 at 10 41 39 PM](https://user-images.githubusercontent.com/28961086/77139332-d0127100-6a32-11ea-864c-7c5092f13b78.png)

If I'm looking at the DDL, I need to first go to a different tab, then refresh, then come back to see the refreshed DDL. I guess I could also remember to press F5, but ... 🤷‍♂ 

![Screen Shot 2020-03-19 at 10 41 56 PM](https://user-images.githubusercontent.com/28961086/77139346-db659c80-6a32-11ea-9e3a-e9b93cf6b8e6.png)

**Comment by uslss** [comment] 2020-03-20 13:14
thanks for suggestion

**Comment by serge-rider** [comment] 2020-04-27 16:24
Duplicate of #8228

**Closed by serge-rider** 2020-04-27 16:24 UTC
Labels: feature request

**Comment by greg-finley-ck** [comment] 2020-04-27 16:25
Duplicate of itself?
