### ISSUE TITLE
Mysql - User permissions on a schema

### ISSUE THREAD

**Issue by nokiomanz** [dbeaver/dbeaver#7960] opened 2020-02-19 16:26 UTC
#### System information: 
- Ubuntu18.04
- 6.3.3

#### Connection specification:
- Mysql 5.7 

#### Describe your question:
Using mysql workbench I can edit user permissions as well as specific schema privileges.
When under DBeaver, If I select the same user. I don't see any schema privileges.
And so my question is, Is that normal? Thanks in advance!

EDIT: Seems that I was wrong and it is the reverse that I have. If I set permission on a specific schema directly either from mysql workbench or dbeaver. I see it correctly in dbeaver. 
When I have sell the catalog (%all) tables(%all) and add the select permission and save. If I close the connection and open it again. I don't see that permissions under dbeaver. But I do see it under workbench.

**Comment by nokiomanz** [comment] 2020-02-20 19:29
This is related to : https://github.com/dbeaver/dbeaver/issues/7784
I added a comment over there to add more information on my testing.

In short this was working under 6.1.0 and stopped starting at 6.1.1

**Comment by uslss** [comment] 2020-02-23 16:34
ticket will be closed as duplicate of #7784 .
anyway, thanks for the bug report

**Closed by uslss** 2020-02-23 16:34 UTC
Labels: question, wait for review
