### ISSUE TITLE
intellisense / autocomplete select on tab

### ISSUE THREAD

**Issue by islandmonk** [dbeaver/dbeaver#18082] opened 2022-10-29 20:40 UTC
It would be nice if I could configure the auto complete to select on a tab rather than a carriage return.

I switch between SSMS and DBeaver a lot. This simple mismatch messes with my muscle memory.

Thanks,

Doug

**Comment by E1izabeth** [comment] 2022-10-30 18:03
Thank you for feature request.
Closed as duplicate of #2316

**Closed as not planned** 2022-10-30 18:03 UTC
Labels: duplicate
