### ISSUE TITLE
ER Diagram don't save tables size

### ISSUE THREAD

**Issue by kata32** [dbeaver/dbeaver#19732] opened 2023-04-18 07:36 UTC
If I resize one or more tables in a ER diagram and save, when I reopen it all tables are maximized loosing resize information.

**Comment by LonwoLonwo** [comment] 2023-04-18 08:44
Thanks for the report @kata32

**Comment by LonwoLonwo** [comment] 2024-01-30 09:25
Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/14988

**Closed as not planned by LonwoLonwo** 2024-01-30 09:25 UTC
Labels: duplicate, xf:erd, xp:normal
