### ISSUE TITLE
Query Editor tab unrecoverable after executing Redshift query after connection expires

### ISSUE THREAD

**Issue by cdabel** [dbeaver/dbeaver#10636] opened 2020-12-08 18:30 UTC
#### System information: 
- Mac OS Catalina 10.15.7
- DBeaver version: 7.2.4.202011011603
- Additional extensions

#### Connection specification:
- Redshift
- Driver name:  com.amazon.redshift:redshift-jdbc42:RELEASE
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Company VPN

#### Describe the problem you're observing:
The query editor tab gets locked in a 'running query' state when I execute a query after leaving my Redshift connection idle.

The only way is to kill the editor tab and stop running processes, but sometimes, doing this will freeze DBeaver entirely and forces me to kill DBeaver and restart it. 

The overall effect on my behavior as a user is that I must ensure that I always Invalidate/Reconnect prior to running any query after more than 20 minutes (the connection expiration period of my Redshift cluster).

To my knowledge this has been happening since version 6.

#### Steps to reproduce, if exist:
(Detailed above).

**Comment by kseniiaguzeeva** [comment] 2020-12-09 14:11
Thank you for the report. Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/10101

**Closed by kseniiaguzeeva** 2020-12-09 14:11 UTC
Labels: bug, wait for review
