### ISSUE TITLE
oid::regclass returns NULL

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#8304] opened 2020-03-31 14:59 UTC
Doday I found that cast of **srrelid** column of **pg_subscription_rel** table returns NULL.
By documentation, srrelid column is type of oid (the same as in pg_class)

The same query run in pgAdmin3 returns table names which leads me to conclusion this is DBeaver issue.

![obrazek](https://user-images.githubusercontent.com/7868445/78040755-286d3b00-7370-11ea-9e84-902e0a4e96ad.png)

![obrazek](https://user-images.githubusercontent.com/7868445/78040810-3e7afb80-7370-11ea-8353-cab441a02c7c.png)

If I cast one of IDs directly in SELECT statement, it works as expected:
![obrazek](https://user-images.githubusercontent.com/7868445/78041419-f3151d00-7370-11ea-8704-af43f06e51e4.png)

A bit strange is that cast performed in similar way on pg_class works as expected (SELECT oid::regclass FROM pg_class).

Anyway I'm almost sure it worked properly in DBeaver v6

**Comment by michalk-k** [comment] 2020-03-31 15:05
Here is similar issue with regrole:

![obrazek](https://user-images.githubusercontent.com/7868445/78041939-aaaa2f00-7371-11ea-9c62-9eb743af66b8.png)

Of course this query is proper working as expected in native postgresql tools

**Comment by serge-rider** [comment] 2020-04-03 16:28
@michalk-k That's weird. DBeaver converts column type using postgresql data type definition. regrole is defined as numeric type in pg_types. Thus fetch fails.

Perhaps we should make regrole a string data type. It looks like a hack but may work.

**Comment by serge-rider** [comment] 2020-04-03 21:06
Yeah, in fact I read this so many times )

I found a bug, by some reason `regrole` was the only OID type which wasn't marked as a special alias. Fixed.

**Comment by michalk-k** [comment] 2020-04-03 22:02
one issue solved, one left: what about issue from the first posting?

**Comment by serge-rider** [comment] 2020-04-04 07:33
I can't reproduce first issue so far (as I don't have a test db with subscriptions).
Queries like `SELECT oid::regclass,* FROM pg_class` work fine..

**Comment by michalk-k** [comment] 2020-04-04 07:53
As far as i remember pg_publication_rel behaves the same. so it's enough to initialize a publication with some tables

**Comment by michalk-k** [comment] 2020-04-06 11:48
Today I spotted new version v7.0.2 with change log entry about fixed OIDs.
I've checked regrole stuff. Right now there is no exception in record but NULL value while text should be displayed. Since consistent with my the first report.

SELECT oid, oid::regrole FROM pg_catalog.pg_roles 
![image](https://user-images.githubusercontent.com/7868445/78555428-4c67cb00-780d-11ea-95fa-aed2d28d0de4.png)

**Comment by michalk-k** [comment] 2020-04-06 13:44
Probably I found culprit of the issue
Using alias for one of the colums makes thigs work

![image](https://user-images.githubusercontent.com/7868445/78564851-55f92f00-781d-11ea-82de-c6db62a7695a.png)

**Comment by serge-rider** [comment] 2020-06-17 14:11
Fixed

**Comment by uslss** [comment] 2020-06-17 15:09
verified

**Closed by uslss** 2020-06-17 15:09 UTC
Labels: bug, x:postgresql
