### ISSUE TITLE
When the table name is capitalized, you cannot press and hold the Ctrl key directly in the SQL editor to click the table name

### ISSUE THREAD

**Issue by xieliangza** [dbeaver/dbeaver#21257] opened 2023-09-21 01:33 UTC
### Description

When the database table name is uppercase, you cannot press and hold the Ctrl key to click the table name directly in the SQL editor。
But if you add the database name, you can click on it again

![image](https://github.com/dbeaver/dbeaver/assets/43339563/4c66fe8e-2e21-40aa-9112-78c375ff63f2)

### DBeaver Version

23.2.0.202309041200

### Operating System

windows11

### Database and driver

TiDB Driver (MySQL Connector/J 8.0)

### Steps to reproduce

1、When I try to connect to the database“MySQL”、“TiDB”
2、Use the default configuration
3、Type a statement in the SQL editor, hold down the Ctrl key, and prepare to enter the data table by left-clicking the table name
4、When the database name is not added before the table name, the data table cannot be accessed

![image](https://github.com/dbeaver/dbeaver/assets/43339563/4c66fe8e-2e21-40aa-9112-78c375ff63f2)

**Comment by LonwoLonwo** [comment] 2023-09-21 08:58
Hello @xieliangza 

And what is the original table name in your case? Is it upper case and in quotes or lower case?

**Comment by LonwoLonwo** [comment] 2023-09-21 08:59
Related ticket: https://github.com/dbeaver/dbeaver/issues/21248
We need to improve MySQLStructureAssistant

**Comment by LonwoLonwo** [comment] 2023-09-21 09:24
Also, is your SQL Editor associated with the table database?

![2023-09-21 12_23_00-DBeaver Ultimate 22 3 2 - _localhost 3_ Script-140](https://github.com/dbeaver/dbeaver/assets/45152336/dae33ac4-f60c-4b6e-8713-c024e04ef362)

**Comment by E1izabeth** [comment] 2023-10-17 15:14
For now I'm closing as a duplicate of #21248

**Closed as not planned by E1izabeth** 2023-10-17 15:14 UTC
Labels: x:mysql, duplicate, wait for response, xf:search
