### ISSUE TITLE
DBeaver 6.2.2 crashes on Windows 10 1903, Problematic frame C MSCTF.dll

### ISSUE THREAD

**Issue by roman-svystun** [dbeaver/dbeaver#7033] opened 2019-10-21 11:26 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 1903
- DBeaver version: 6.2.2
- Additional extensions: none

#### Connection specification:
- Database name and version: Microsoft SQL Server 2016 (SP2-GDR) (KB4505220) - 13.0.5101.9 (X64)
- Driver name: mssql-jdbc-7.0.0.jre8.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
After upgrading from DBeaver 6.2.1 to 6.2.2 DBeaver crashes several times per day.
Downgrading back to 6.2.1 fixes the problem.

#### Steps to reproduce, if exist:
N/A

#### Include any warning/errors/backtraces from the logs
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb5f5aaca8, pid=7088, tid=5232
#
# JRE version: Java(TM) SE Runtime Environment (11.0.3+12) (build 11.0.3+12-LTS)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (11.0.3+12-LTS, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [MSCTF.dll+0x2aca8]
```
[hs_err_pid7088.log](https://github.com/dbeaver/dbeaver/files/3750433/hs_err_pid7088.log)
[hs_err_pid8328.log](https://github.com/dbeaver/dbeaver/files/3750434/hs_err_pid8328.log)
[hs_err_pid19032.log](https://github.com/dbeaver/dbeaver/files/3750435/hs_err_pid19032.log)
[hs_err_pid6112.log](https://github.com/dbeaver/dbeaver/files/3750436/hs_err_pid6112.log)
[hs_err_pid15012.log](https://github.com/dbeaver/dbeaver/files/3750437/hs_err_pid15012.log)
[hs_err_pid9152.log](https://github.com/dbeaver/dbeaver/files/3750438/hs_err_pid9152.log)

**Comment by serge-rider** [comment] 2019-10-21 12:35
Duplicate of #6928
Please download 6.2.3 version

**Closed by serge-rider** 2019-10-21 12:35 UTC
Labels: bug, duplicate
