### ISSUE TITLE
Dumping and restoring of MariaDB databases fails in DBeaver 24.2

### ISSUE THREAD

**Issue by eaibizz** [dbeaver/dbeaver#35483] opened 2024-09-05 11:50 UTC
### Error:
When dumping a database within DBeaver 24.2 and trying to restore the database (as well in another database server as on another device) the dumped sql file gives a corruption error.
When viewing the dumped sql file, we see that instead of **INSERT INTO (`column`, `column2`) VALUES ('value','value2')** the following is being printed: **('value','value2')**.
So the complete INSERT INTO () is missing.
We've also tried to disable the option for "Extended inserts", but that doesn't make any difference.

### Screenshot of wrong dump:

![1725535972_notepad++_CJzZ1z9qR2](https://github.com/user-attachments/assets/c7aa20a3-c9f3-40d1-b059-b6b1c6eb220d)
(red marks are for privacy and contain person names or table names)

### Headers of wrong dump:

![1725536767_notepad++_gNwXyndq0m](https://github.com/user-attachments/assets/e8dac57d-56e8-447e-b8f5-907dd37f7234)

### Error message:

C:\Users\USERNAME\AppData\Roaming\DBeaverData\drivers\clients\mysql_8\win\mysql.exe -u ****** --host=localhost --port=3306 -v DATABASENAME
Task 'MySQL restore' started at Thu Sep 05 13:47:24 CEST 2024
--------------

/*!40101 SET character_set_client = @saved_cs_client */

--------------

ERROR at line 129: Unknown command '\\''.

Task 'MySQL restore' finished at Thu Sep 05 13:47:24 CEST 2024
2024-09-05 13:47:24.427 - IO error: Process failed (exit code = 1). See error log.
2024-09-05 13:47:24.428 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)

### DBeaver Version

Community Version 24.2

### Operating System

Windows 11

### Database and driver

Driver type: MySQL; Driver name: MariaDB; MariaDB JDBC driver: org.mariadb.jdbc.Driver

### Steps to reproduce

1. Rightclick on the name of the database
2. Choose "Tools" > "Dump database"
3. Click "Next"
4. Have "Extended inserts", "Add DROP statements" and "Disable keys" enabled
5. Click "Start"
6. Select another databaseserver or databasename to import the dumped file into
7. Choose "Tools" > "Restore database"
8. Select dumpfile
9. Click Start

### Additional context

We do use an SSH connection to connect to the database server.
I've reverted the update of DBeaver 24.2 to DBeaver 24.1.5 now and then the dump is being exported correctly and can be imported succesfully too.

**Comment by lekoala** [comment] 2024-09-05 12:26
Similar issue here

On 24.2, part of the dump is somehow truncated
On 24.1.5 it works fine

Here is an example (24.2 export on top, 24.1.5 below)

![image](https://github.com/user-attachments/assets/18eb9636-0c2a-49bf-97ad-8066f6f58047)

On 24.2, when dumping, the window shows what the dump operation is doing so maybe it's linked to that

**Comment by nadamai** [comment] 2024-09-05 13:49
The same issue here, additionally the corrupted dump contains only some of the tables

**Comment by ShadelessFox** [comment] 2024-09-05 14:39
Hello @eaibizz @lekoala @nadamai ,

Thanks for the bug report. This is a duplicate of #35421. Please track the progress on the issue there.

**Closed as not planned by ShadelessFox** 2024-09-05 14:39 UTC
Labels: duplicate, x:maria, xf:native clients
