### ISSUE TITLE
Last version doesn´t run in Ubuntu 24.04. It was installed from Snap

### ISSUE THREAD

**Issue by osposto** [dbeaver/dbeaver#36020] opened 2024-10-21 20:28 UTC
### Description

Just a refereshed old installation (both from Snap), and the last one doesn´t even start.  Pretty weird.

### DBeaver Version

community 24.2.1.202409221725

### Operating System

Ubuntu 24.04 1 LTS

### Database and driver

MySQL

**Comment by dj12djdjs** [comment] 2024-10-21 21:13
Same issue. I'm not sure if these logs will be helpful.
```
17:07:25 systemd: snap.dbeaver-ce.dbeaver-ce-0c4bd8e9-a32b-4994-93f2-569bf696ed6e.scope: Consumed 26.902s CPU time.
17:07:25 dbeaver: /snap/dbeaver-ce/327/usr/share/dbeaver-ce/dbeaver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/dbeaver-ce/327/usr/share/dbeaver-ce/dbeaver)
17:07:25 dbeaver: /snap/dbeaver-ce/327/usr/share/dbeaver-ce/dbeaver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/dbeaver-ce/327/usr/share/dbeaver-ce/dbeaver)
17:07:25 dbeaver: /snap/dbeaver-ce/327/usr/share/dbeaver-ce/dbeaver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/dbeaver-ce/327/usr/share/dbeaver-ce/dbeaver)
17:07:19 glib-compile-sc: Warning: Schema “org.gnome.system.proxy.socks” has path “/system/proxy/socks/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
17:07:18 systemd: Started snap.dbeaver-ce.dbeaver-ce-0c4bd8e9-a32b-4994-93f2-569bf696ed6e.scope.
```

**Comment by dj12djdjs** [comment] 2024-10-21 21:16
@osposto I installed on the latest/candidate channel. `latest/candidate: 24.0.5.202405191503 2024-06-02`

This one is working for me.

**Comment by TB-HunBoka** [comment] 2024-10-21 23:07
Could you please check the current version of your GLIBC?
`ldd --version`

**Comment by dj12djdjs** [comment] 2024-10-22 00:34
> Could you please check the current version of your GLIBC? `ldd --version`

2.35

**Comment by heperaza** [comment] 2024-10-22 03:31
> Could you please check the current version of your GLIBC? `ldd --version`

2.39

**Comment by gracegengau** [comment] 2024-10-22 04:04
mine is 2.35

**Comment by julia-gabgomes** [comment] 2024-10-22 04:17
> Could you please check the current version of your GLIBC? `ldd --version`

hi! mine is 2.39

**Comment by petr-hybler-ofti** [comment] 2024-10-22 05:42
same here ldd -> 2:39 ..

/snap/dbeaver-ce/327/usr/share/dbeaver-ce/dbeaver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/dbeaver-ce/327/usr/share/dbeaver-ce/dbeaver)

**Comment by caneel07** [comment] 2024-10-22 05:58
same here ubuntu 22.04

```
$ ldd --version

ldd (Ubuntu GLIBC 2.35-0ubuntu3.8) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

```

**Comment by rthijs** [comment] 2024-10-22 06:10
Same issue for me.

`/snap/dbeaver-ce/327/usr/share/dbeaver-ce/dbeaver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/dbeaver-ce/327/usr/share/dbeaver-ce/dbeaver)`

ldd version: ` ldd (Ubuntu GLIBC 2.39-0ubuntu8.3) 2.39`

Had to install the latest/candidate version as mentioned above to get it working again:

`sudo snap refresh dbeaver-ce --channel=latest/candidate`

But I get a message right away saying that I have version 24.0.5.202405191503 and version 24.2.3 (21.10.2024) is available. So should I try latest/edge?

**Comment by batje** [comment] 2024-10-22 06:28
Upgrading to latest snap also works on (K)ubuntu 24.10
```
ldd (Ubuntu GLIBC 2.40-1ubuntu3) 2.40
```

**Comment by Arash-codedev** [comment] 2024-10-22 08:05
What if I am using `apt` and not trusting `snap`? Generally speaking, breaking stability of the application for using the latest library is not a good step. Who cares about the latest feature of dbeaver? I used to have a working dbeaver and today it does not work.
Nevertheless, I appreciate all time and effort of the open source society.

**Comment by fanshaohua-fan** [comment] 2024-10-22 08:35
duplicate issue as https://github.com/dbeaver/dbeaver/issues/36006

check this comment for a workaround
https://github.com/dbeaver/dbeaver/issues/36006#issuecomment-2427669216

**Comment by E1izabeth** [comment] 2024-10-22 09:08
Thanks for the bug report. I'm closing it as a duplicate of #36006

**Closed as not planned by E1izabeth** 2024-10-22 09:08 UTC
Labels: duplicate, xo:linux
