### ISSUE TITLE
Incorrect table DDL generation in azure sql server

### ISSUE THREAD

**Issue by szekeresgeza** [dbeaver/dbeaver#17215] opened 2022-08-01 09:47 UTC
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : 22.1.3.202207240747
- Additional extensions

#### Connection specification:
- Database name and version :  Azure SQL
- Driver name : Azure SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
We created a table. There are many columns with  column type nvarchar(35).
When we checked the table definition, we can see that the generated DDL shows nvarchar(17).

If we check it in the information_schema it shows the proper value.

#### Steps to reproduce, if exist:

create table sandbox.test_table
(
	address nvarchar(35)
);

--check
select table_name , COLUMN_NAME , CHARACTER_MAXIMUM_LENGTH  from INFORMATION_SCHEMA.COLUMNS 
where TABLE_NAME = 'test_table'
;

shows the proper value (35)

Generate the DDL:

-- dwh_test.sandbox.test_table definition

-- Drop table

-- DROP TABLE dwh_test.sandbox.test_table;

CREATE TABLE dwh_test.sandbox.test_table (
	address nvarchar(17) COLLATE Hungarian_Technical_100_CI_AS_SC_UTF8 NULL
);

**Comment by uslss** [comment] 2022-08-02 10:57
thanks for the report

**Comment by szekeresgeza** [comment] 2022-08-02 12:24
Hi!

Today we tested with another dbeaver sql driver  (MS SQL Server / SQL Server)  and unfortunatelly the same issue is occured. 

BR
Geza

**Comment by LonwoLonwo** [comment] 2022-08-04 07:44
Closed as duplicate of #16996

**Closed as not planned by LonwoLonwo** 2022-08-04 07:44 UTC
Labels: x:mssql, xf:metadata, x:azure
