### ISSUE TITLE
Find object has encountered a problem.  No enum constant

### ISSUE THREAD

**Issue by powelleric** [dbeaver/dbeaver#4706] opened 2018-11-28 15:28 UTC
This error occurs occasionally after double-clicking a column name in the text editor

![screen shot 2018-11-28 at 8 20 51 am](https://user-images.githubusercontent.com/11025490/49162095-69ba8a00-f2e7-11e8-86c8-7479baa9ef69.png)

p.s. I was offered the option to upgrade/change the mssql driver recently and I accepted.  I think things have not been right since.

**Comment by serge-rider** [comment] 2018-11-28 17:34
Duplicate of #4635
Thanks for the bug report anyways

**Closed by serge-rider** 2018-11-28 17:34 UTC
Labels: bug, duplicate
