### ISSUE TITLE
Installed packages missing after upgrade from 23.3.2 to 23.3.3

### ISSUE THREAD

**Issue by chrisgeo** [dbeaver/dbeaver#22546] opened 2024-01-22 16:39 UTC
### Description

All my packages were removed on my upgrade of DBeaver. A few notables:
* Darkest Dark Theme (DevStyles)
* Eclipse Marketplace
* CodeTogether

### DBeaver Version

23.3.3

### Operating System

macOS 14.2.1

### Steps to reproduce

1. Have 23.3.2 installed
2. Have desired packages from marketplace/install new software
3. Upgrade to 23.3.3
4. Missing installations show they are no longer loaded in installed software or their settings dialogs.

**Comment by E1izabeth** [comment] 2024-01-23 09:40
Thank you for bug report. I'm closing it as a duplicate of #5317

**Closed as not planned by E1izabeth** 2024-01-23 09:40 UTC
Labels: duplicate
