### ISSUE TITLE
DBeaver: The global Template Preferences dialog grid can not save and restore foreign characters correctly

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5052] opened 2019-01-19 20:30 UTC
DBeaver - **Version 5.3.3 CE** - **EA 19-Jan-2019 14:00**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new and old Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

If I create a global Template setting and use swedish characters in the **Name**, **Description** and **Pattern** entry, those values looks ok until I restart _DBeaver_.

My guess is that the save and restore of that setting/properties write the string using one character set and later read that setting/properties back using another character set.

The values after enter a new **Template** (presented ok):

![2019-01-19 21-10-24](https://user-images.githubusercontent.com/31191374/51431990-10107500-1c31-11e9-8473-a88ee0e38e20.png)

The values after restart of _DBeaver_ (presented in an errornous way)

![2019-01-19 21-15-37](https://user-images.githubusercontent.com/31191374/51432001-36361500-1c31-11e9-868f-38d3f6547f14.png)

**Comment by serge-rider** [comment] 2019-01-19 21:11
I can't reproduce this (with Chinese or Russian letters). 
Maybe your default workspace encoding was detected incorrectly. You can check it in Preferences->General->Workspace. Text file encoding should be UTF-8.

In any case, I can't fix this as Templates page is a part of Eclipse platform

**Comment by pdanie** [comment] 2019-01-19 21:19
It makes no difference if I set the **Preferences** -> **General** -> **Workspace** -> **Text file encoding** to either **Default (Cp1252)** or **Other (UTF-8)**.

**Comment by uslss** [comment] 2019-11-19 14:32
is this still actual?

**Comment by uslss** [comment] 2019-12-12 17:45
fixed in scope of #7294

**Closed by uslss** 2019-12-12 17:45 UTC
Labels: can't reproduce, question
