### ISSUE TITLE
Label drop-down option question

### ISSUE THREAD

**Issue by liuchengss** [dbeaver/dbeaver#19069] opened 2023-02-15 02:20 UTC
### Description

 Right mouse click on the TAB to display “关闭关闭”

### DBeaver Version

22.3.4

### Operating System

Window10

**Comment by E1izabeth** [comment] 2023-02-15 06:49
Please, clarify your request.
Which TAB are you talking about?

**Comment by E1izabeth** [comment] 2023-02-21 08:48
Thank you for bug report.
It's a duplicate of #17697 so I'm closing this issue.

**Closed as not planned by E1izabeth** 2023-02-21 08:48 UTC
Labels: duplicate, xf:i18n
