### ISSUE TITLE
Always attempts to download driver files even when already completed

### ISSUE THREAD

**Issue by Bilge** [dbeaver/dbeaver#23412] opened 2024-04-12 10:50 UTC
### Description

DBeaver, on first run, attempted to download (relevant) drivers for my database, but thereafter, still complains that it needs to download (no) drivers on every single connection attempt.

### DBeaver Version

CE 24.0.2

### Operating System

macOS Sonoma 14.4.1

### Database and driver

MySQL 8.0.32
MySQL Connector/J [mysql-connector-j-8.2.0 (Revision: 06a1f724497fd81c6a659131fda822c9e5085b6c)]

### Steps to reproduce

I don't remember the exact steps the first time I ran the application, but at some point whilst setting up the MySQL connection, it asked to download database drivers for MySQL, which it did and that seemed fine. But subsequently on attempting to connect, it pops up the same dialog but there are no drivers to download (_files required by driver_ list is now always empty).

To reproduce after initial setup, simply opening the application is enough to reproduce the issue. For some reason, it pops up on startup, _in addition_ to every subsequent connection attempt thereafter.

### Additional context

This is the dialog it always pops up now:

![image](https://github.com/dbeaver/dbeaver/assets/470626/c87ef245-8025-4c1a-9ccc-310dc09072de)

Only on first run was the list of _files required by driver_ actually populated.

**Comment by E1izabeth** [comment] 2024-04-12 11:03
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by Bilge** [comment] 2024-04-12 11:16
[DBeaver log](https://github.com/dbeaver/dbeaver/files/14957963/DBeaver.log)

**Comment by E1izabeth** [comment] 2024-04-12 17:33
Extracted from logs
```
java.lang.IllegalStateException: No workbench window
	at org.jkiss.dbeaver.ui.UIUtils.getActiveWorkbenchWindow(UIUtils.java:1877)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadDialog.<init>(DriverDownloadDialog.java:43)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadDialog.downloadDriverFiles(DriverDownloadDialog.java:126)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadDialog.downloadDriverFiles(DriverDownloadDialog.java:119)
	at org.jkiss.dbeaver.core.DesktopUI$3.runTask(DesktopUI.java:197)
	at org.jkiss.dbeaver.core.DesktopUI$3.runTask(DesktopUI.java:1)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:27)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:40)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4367)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3990)
	at org.jkiss.dbeaver.core.DesktopUI.readAndDispatchEvents(DesktopUI.java:754)
	at org.jkiss.dbeaver.utils.RuntimeUtils.runTask(RuntimeUtils.java:287)
	at org.jkiss.dbeaver.utils.RuntimeUtils.runTask(RuntimeUtils.java:247)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.shutdown(DBeaverApplication.java:691)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:323)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:647)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:607)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1464)
```

**Comment by Destrolaric** [comment] 2024-04-18 13:22
@Bilge Hi, how the DBeaver client was installed?

**Comment by Bilge** [comment] 2024-04-19 15:05
@Destrolaric I downloaded [`dbeaver-ce-24.0.2-macos-aarch64.dmg`](https://download.dbeaver.com/community/24.0.2/dbeaver-ce-24.0.2-macos-aarch64.dmg), double-clicked on it, and moved the icon into the apps folder. Then I started it from the apps folder.

![image](https://github.com/dbeaver/dbeaver/assets/470626/2c57c275-a840-4730-95d9-a7b6961a0cda)

**Comment by mieseprem** [comment] 2024-05-28 10:30
I have the same issue and my DBeaver (24.0.5.202405191503) is installed via Homebrew. So, this may be independent from installation source.

**Comment by Bilge** [comment] 2024-06-06 09:21
Even if I install from 24.1.0.202406021658 from Brew, it's the same problem.

**Comment by mieseprem** [comment] 2024-06-10 11:11
Regarding the "can't reproduce" I can tell this doesn't affect all DB systems.
I don't face this issue whan connecting to Oracle and Exasol, while I must "download" something twice when connecting to MariaDB and MySql.

**Comment by Bilge** [comment] 2024-08-06 09:40
Apparently, this may be due to also running [Darktrace](https://darktrace.com/) and/or [CFZT](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp/). As far as I know, both are paid products, but anyone can install WARP, which connects to the same network as CFZT.

It has also been hinted that [this Java issue](https://stackoverflow.com/questions/50379839/connection-java-mysql-public-key-retrieval-is-not-allowed) may be related, regarding public key retrieval.

**Comment by mieseprem** [comment] 2024-09-02 07:14
Update: meanwhile I'm on 24.2.0 and am not able to reproduce this issue anymore.

**Comment by arhayka** [comment] 2024-09-02 07:48
@mieseprem Thanks for testing! We also can't reproduce this issue, so I'm closing it.

**Closed as completed by arhayka** 2024-09-02 07:48 UTC
Labels: can't reproduce, xo:macos, sp:2, xf:connection

**Comment by Bilge** [comment] 2024-09-02 14:11
It also appears to be fixed in 24.1.0.

**Comment by jmatzen** [comment] 2024-09-20 14:30
Nope I'm on 24.2.0 still happening with MacOS 14.6.1

**Comment by evangelistagrace** [comment] 2024-10-01 05:30
> Nope I'm on 24.2.0 still happening with MacOS 14.6.1

Happening on version 24.2.1 on MacOS 15.0 too

**Comment by gabrielomnius** [comment] 2024-10-29 14:24
Reproducible with DBeaver 24.2.3.202410201725 on (M2) macOS 15.1 and PostgresSQL DBs.
Dialog always comes up upon connect. No driver versions/details are shown in dialog. And independently of how I close the driver download dialog (close window icon, download button, cancel button etc.) the connection is established right away.

**Comment by vittau** [comment] 2024-12-16 17:42
Same issue here, Dbeaver 24.3.0 on macOS Sonoma.

**Comment by larza** [comment] 2025-02-18 08:25
For others getting this error: check that your driver download is not blocked by a proxy, VPN etc.
