### ISSUE TITLE
Sorting button covered by scroll bar

### ISSUE THREAD

**Issue by felangga** [dbeaver/dbeaver#7835] opened 2020-02-05 05:15 UTC
I'm using KDE desktop running on linux 4.15. 
On the count column on the right, I can't click the sorting button because it covered by scroll bar. 
Is it possible to fix this?

![image](https://user-images.githubusercontent.com/14814984/73812913-05f7ef00-4811-11ea-9844-22d593b8451e.png)

**Comment by uslss** [comment] 2020-02-05 07:50
seems to be duplicate of #7695 
anyway, thanks for the bug report

**Closed by uslss** 2020-02-05 07:50 UTC
Labels: bug
