### ISSUE TITLE
SQL indentation lines

### ISSUE THREAD

**Issue by cleberlz** [dbeaver/dbeaver#34618] opened 2024-07-02 16:16 UTC
**Is your feature request related to a problem? Please describe.**

Hello, congratulations on the tool.
I would like to make a suggestion on the SQL editor.

When we set up a command, where there is a beginning and an end, there could be a connecting line, so we can better visualize what is inside that command.
Thanks.

For example:

![Sql Model](https://github.com/dbeaver/dbeaver/assets/168768247/4940d21d-9306-4a5a-8bfe-b98408ac796b)

**Comment by E1izabeth** [comment] 2024-07-02 20:33
Thank you for request. It's a duplicate of #13696
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-07-02 20:33 UTC
Labels: duplicate, xf:sql editor
