### ISSUE TITLE
Automatic underlining of table and column names in sql editor

### ISSUE THREAD

**Issue by hvenz** [dbeaver/dbeaver#22320] opened 2024-01-03 21:59 UTC
### Description

Since update to Community Version 23.3.1.202312241705 the SQL Editor formats table and column names in red underlined font. This happened for already opened scripts as well as for newly typed statements. The underlining appears and disappears sporadically during typing. Sorry that I have not identified a pattern how and when it occurs, but please see the below screenshot
![image](https://github.com/dbeaver/dbeaver/assets/99658485/a43234af-0389-4541-90c0-777551de9803)
If I add another identical line, the underlined table name in the last statement is formatted normal.

As it seems, this only happens when I connect to an Ingres DB, but not for Oracle, SQL Server, Access or Derby

### DBeaver Version

Community Edition 23.3.1.202312241705

### Operating System

Windws 10

### Database and driver

Ingres iijdbc-10.2-4.1.10

### Steps to reproduce

1. Click on existing DB connection and open SQL Console
2. Type SQL Select statements with table and column names
3. End statement with semicolon or not and press enter
4. Type the same in the next column: table name will be underlined or not (I am not joking, but it is unfortunately not consistent)

### Additional context

I know it is "only" a formatting issue, but this font is so annoying that I can't visually read my scripts anymore.
I also tried to fix it with SQL Editor Code formatters but that does not fix it. I have also already reset User preferences via Reset settings dialoge without success.

**Comment by E1izabeth** [comment] 2024-01-04 05:50
Such highlighting is the validation of tables and columns by metadata. It tells you that if you try executing your script, it will fail, and the reason is highlighted. 
You can turn this highlighting off for the concrete database in the `Preferences` -> `Editors` -> `SQL Editor` -> `Code Editor` ->`Read database tables/columns for semantic analysis`.

![image](https://github.com/dbeaver/dbeaver/assets/28875055/6a92f02b-ec24-443a-8218-5885024df5f3)

**Comment by hvenz** [comment] 2024-01-04 08:22
Thanks a lot, that got rid of the underlined tokens and gave me back a great DB tool! 
But then this validation is not correct, as the query runs very well if I end the statements with a semicilon. As you can see in my screenshot, I typed the same select 6 times but only 2 had underlined table names.
And why was it not there before the update? Did I miss something?

**Comment by E1izabeth** [comment] 2024-01-04 08:28
It's our new feature. Unfortunately, we don't have Ingres database in our test environment to check on our own. Could you help me to understand the roots of the issue? Does it get better if you put the delimiter `;` to the end of every query?

**Comment by Orffyreus** [comment] 2024-01-05 06:57
For me that highlighting issue occurs, if the query contains synonyms (Oracle database). Using the fully qualified names (schema.table) works.

**Comment by hvenz** [comment] 2024-01-05 10:02
With Oracle I get it for views too (e.g. all_tables), but not for tables.
I tried to record what it looks like with Ingres (3 consecutive gifs), as the underlines appear and disappear as you type. Perhaps you can understand the underlying logic. What always seems to work is to also specify the scheme. However, it then doesn't recognize that the table x1100pattt doesn't even exist.

![DBeaver schema check underline_1](https://github.com/dbeaver/dbeaver/assets/99658485/457ff771-2aca-4013-8230-fc9f80d53391)
![DBeaver schema check underline_2](https://github.com/dbeaver/dbeaver/assets/99658485/419a5bfe-7e06-4a31-850e-af1631120619)
![DBeaver schema check underline_3](https://github.com/dbeaver/dbeaver/assets/99658485/b7155d33-46c9-4c24-887d-ad6b43c1ef38)

Let me know if you would like to see more for Ingres.

**Comment by E1izabeth** [comment] 2024-01-05 19:20
Thank you, I'll try to reproduce with Oracle.

**Comment by E1izabeth** [comment] 2024-01-06 18:14
When you don't put `;` and don't add new line between queries we assume that it's not several separate queries. That's why validation doesn't work in this case. It's an expected behavior. Just separate queries with a new line or put `;` at the and.

The issue which looks like a bug here is that your `x1100pat` table is not highlighted as table while you don't add schema name there. 
Is `dps` chosen as an active schema for the current script? You can check it here:
![image](https://github.com/dbeaver/dbeaver/assets/28875055/37e42f5c-6360-4ae2-8349-b17232e0055b)

**Comment by hvenz** [comment] 2024-01-08 08:21
> The issue which looks like a bug here is that your `x1100pat` table is not highlighted as table while you add schema name there.

But it does present a list of available tables when I type the schema name followed by '.', so it looks like it would the meaning of each token.

> Is `dps` chosen as an active schema for the current script? You can check it here

That's a good question: it never seemed to work for Ingres. I can see a list of the available schemas in the dropdown or the dialog, but when I select one, it stays at <N/A>. However, I can see that it works for Oracle or SQL Server and even updates when I switch schemas by typing in the console

**Comment by ctopenpetra** [comment] 2024-01-08 17:13
I get the same issue with PostgreSQL. I have a single large query with multiple With statements, but the final SELECT (after the WITH statements) is made very difficult to read by every table or column referenced being in bright red, italic and underline. It is so annoying. DBeaver used to be a joy to use till the recent update made reading SQL that much harder.

**Comment by E1izabeth** [comment] 2024-01-08 17:14
@ctopenpetra you can turn it off https://github.com/dbeaver/dbeaver/issues/22320#issuecomment-1876391671

**Comment by ctopenpetra** [comment] 2024-01-08 17:16
Thanks, but would I lose any valuable analytical functionality? Allowing us to alter the colour of the highlighted tables/columns would be a great help, while retaining the functionality.

**Comment by ctopenpetra** [comment] 2024-01-08 17:23
> @ctopenpetra you can turn it off [#22320 (comment)](https://github.com/dbeaver/dbeaver/issues/22320#issuecomment-1876391671)

Thanks, but would I lose any valuable analytical functionality? Allowing us to alter the colour of the highlighted tables/columns would be a great help, while retaining the functionality.

On a new SQL script tab for my PostgreSQL database, I type the simplest of queries, followed by a new line, and get:

![image](https://github.com/dbeaver/dbeaver/assets/36154619/9a9ee7b6-bb10-46c7-89b4-703f67f3724b)

For no reason, account_code  in the WHERE clause is bright red, italics and underline.

**Comment by E1izabeth** [comment] 2024-01-08 17:26
@ctopenpetra thank you for sharing your case.

Unchecking `Read database tables/columns for semantic analysis` will turn off only query validation by metadata. Seems it has some bug which we're going to fix soon.

Syntax structure validation will work - for example, if you reference table in select, which wasn't specified in from clause.

**Comment by ctopenpetra** [comment] 2024-01-08 17:36
> @ctopenpetra thank you for sharing your case.
> 
> Unchecking `Read database tables/columns for semantic analysis` will turn off only query validation by metadata. Seems it has some bug which we're going to fix soon.
> 
> Syntax structure validation will work - for example, if you reference table in select, which wasn't specified in from clause.

Thanks, Elizabeth. That works perfectly.

**Comment by Grisgram** [comment] 2024-01-10 11:55
I would like to add to this issue, that, when editing a stored procedure, all table columns are in that bold red highlight font because the connection shown in the main toolbar of the current editor window (sp-editor) is "N/A".
For some reason, i never see the active connection up there, even when i double-click a stored procedure.
but without connection, the editor thinks, all symantic checks fail and therefore highlights everything in this eye-burning red.

for now, only option is to deactivate semantic analysis in an sp-heavy project.

**Comment by brunokinast** [comment] 2024-01-12 16:13
I have the same issue on PostgreSQL. Even simple queries show a lot of errors, even though the command runs fine.
I've disabled the highlighting, but it would be a really nice feature if it worked.
![image](https://github.com/dbeaver/dbeaver/assets/52048490/68cbc058-2d84-4a5e-9b11-6731bbee6f67)

**Comment by TB-HunBoka** [comment] 2024-01-15 14:30
I also like this feature when working on oracle database.
The only thing I would like to add to the comments before me is that this looks case sensitive for schemas.
I am a terrible person who mixes uppercase and lowercase schema names and I would love to see this became non case sensitive. At least for OracleDB, where it doesn't matter.
However, I am used to ctrl+a -> ctrl+shift+x to capitalize everything.

**Comment by jackgtor** [comment] 2024-01-15 14:48
I'll echo the previous comment. If you're going to mark something as an error, it really should be an error. This feature is flagging semantically correct statements that use different case in a language that is mostly case-insensitive. It seems like a useful feature, otherwise, so hopefully that can be fixed soon. In the meantime, I've disabled the whole semantic analysis feature as just that alone can cause similar misleading highlighting. Thanks for your work on this.

**Comment by E1izabeth** [comment] 2024-01-15 14:53
@jackgtor we're working on it

**Comment by jackgtor** [comment] 2024-01-15 15:00
Thanks. 😊

Jack Goldstein
SOS Compliance Reporting Team
https://w3.sos.ibm.com

**Comment by tmozes** [comment] 2024-01-17 14:44
> Such highlighting is the validation of tables and columns by metadata. It tells you that if you try executing your script, it will fail, and the reason is highlighted. You can turn this highlighting off for the concrete database in the `Preferences` -> `Editors` -> `SQL Editor` -> `Code Editor` ->`Read database tables/columns for semantic analysis`.
> 
> ![image](https://private-user-images.githubusercontent.com/28875055/294097249-6a92f02b-ec24-443a-8218-5885024df5f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDI0OTksIm5iZiI6MTcwNTUwMjE5OSwicGF0aCI6Ii8yODg3NTA1NS8yOTQwOTcyNDktNmE5MmYwMmItZWMyNC00NDNhLTgyMTgtNTg4NTAyNGRmNWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE0MzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYjAwNWMyNjFlM2U0YjkwODhkYmZmNmEzZDdiM2UxNzMyOTA4YTdjODk1ODY5OGQ2NmNlMjRlMDIwOWQ1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8FGkXKmL0q4X-AwQ5ZOYkF6xSJb1Eznz1eK2EzkB_VY)

This does not work as intended! This feature now highlights fields in queries that are perfectly fine, see example below. In addition, it really makes it hard to read field names with underline highlighting, when the field name has underscore in it.

<img width="387" alt="Screenshot 2024-01-17 at 9 43 38 AM" src="https://github.com/dbeaver/dbeaver/assets/5889763/da44014d-0ea6-413d-8038-32ef36d3338d">

**Comment by E1izabeth** [comment] 2024-01-18 08:36
We made some fixes and they're available in the Early Access version. You could try https://dbeaver.io/files/ea/

**Comment by m3n3chm0** [comment] 2024-01-18 21:54
Hi, Is it possible to switch directly from the stable version to early access and vice versa ? I mean without uninstalling it and loss of any configuration/data of course.

Best regards.

**Comment by E1izabeth** [comment] 2024-01-19 09:33
@m3n3chm0 yes, just run the installer of the version you want and the version will change, while connections and settings remain

**Comment by m3n3chm0** [comment] 2024-01-19 12:30
Ok, @E1izabeth. Really appreciated!

**Comment by jackgtor** [comment] 2024-01-22 22:39
It's much better now. Thanks for the quick fix.

I have one more question which may or may not be related.

When connected to DB2 UDB, it's not recognizing current_date or current_timestamp as valid SQL in the sense that it's not auto-completing them and is highlighting them in red underline. The expressions still run properly. When connected to PostgreSQL, they are identified correctly. From where is it getting the list of recognized SQL words? Is that a list I can customize?

Thanks,
Jack

**Comment by E1izabeth** [comment] 2024-01-23 08:25
@jackgtor thank you for feedback.
Unfortunately, there is no way to customize keywords from UI for now. Here is an issue to make it possible #6528. You can vote for the issue with 👍 under the issue description to promote it to a higher priority.

**Comment by E1izabeth** [comment] 2024-01-23 08:27
@jackgtor could you create a separate issue about adding `current_date` and `current_timestamp` keywords for DB2?

**Comment by jackgtor** [comment] 2024-01-23 14:01
Thanks Elizabeth. Feature [22563 ](https://github.com/dbeaver/dbeaver/issues/22563)has been opened.

**Comment by mtmcg** [comment] 2024-01-25 01:16
Hi, as others have said this is working better now. I'm still seeing an issue where the metadata validation does not follow aliases (using DB2 for LUW). If the query references a table directly it works well, but if an alias is used (which I personally use extensively) it always gets highlighted as an error even if the table and column names are valid. Is this expected to work?

**Comment by TB-HunBoka** [comment] 2024-01-26 08:04
Thanks Elizabeth. It's significantly better for my Oracle DB queries.
However for Snowflake DB it works strange, but might not directly because of this feature.
If I use all uppercase, it can't find the columns. I need to use lowercase or quote the table name. However I can use lower and upper case schema names.
![kép](https://github.com/dbeaver/dbeaver/assets/126617861/e1e5ae00-6d39-4553-aa7d-26cd5ebbd916)
The strange thing why I mentioned it's might related to other issue, is when I use the built in auto completion for complete the table name, it sometimes became quoted, sometimes doesn't. The incorrect underlining issue only persist when the autocomplete would quote the table name.

**Comment by E1izabeth** [comment] 2024-01-26 10:44
@TB-HunBoka 
Thank you for feedback. I can reproduce it, but only with VIEWS view, other views and tables works fine for me. Do you experience this issue only with VIEWS?

**Comment by E1izabeth** [comment] 2024-01-26 10:44
@mtmcg could you provide some example?

**Comment by TB-HunBoka** [comment] 2024-01-26 11:58
Hello @E1izabeth 
No, I experienced the same problem with a single table, and couple of views.
However, I think I found the problem.
![kép](https://github.com/dbeaver/dbeaver/assets/126617861/edee1775-2d29-476a-8253-a9e5bf9399be)
When an object has the same name as an sql word or command, currently it will be quoted by the autocomplete function and this function also requires it to be quoted, otherwise it will not scan the object for columns.

**Comment by E1izabeth** [comment] 2024-01-26 12:00
@TB-HunBoka 
Thank you. Yes, it's a separate issue, indeed. Could you create a new issue for that?

**Comment by TB-HunBoka** [comment] 2024-01-26 12:11
@E1izabeth 
Yes I will.

In the mean time I found another problem with the current version of this function.
The Having command validate for currently **selected** column names only. Furthermore the selected column name and the condition in the having command needs to be matching, I mean directly selected and not only aggregated:
![kép](https://github.com/dbeaver/dbeaver/assets/126617861/4c607c3b-d0d6-41d5-9449-a4bc12194cc7)

**Comment by E1izabeth** [comment] 2024-01-26 12:57
@TB-HunBoka I believe it should be fixed in scope of the issue #22302 and will be available in the next release 23.3.4 and in the [Early Access version](https://dbeaver.io/files/ea/) tomorrow

**Comment by TB-HunBoka** [comment] 2024-01-30 14:42
@E1izabeth You were right, the having part is now validated correctly in the early version. Thank you for the fix.

**Comment by E1izabeth** [comment] 2024-01-31 19:38
I'm closing this issue as it seems resolved.
If you find some inconsistency, please feel free to create a new issue.

**Closed as completed by E1izabeth** 2024-01-31 19:38 UTC
Labels: xf:sql editor

**Comment by rasqual** [comment] 2024-02-01 02:17
![image](https://github.com/dbeaver/dbeaver/assets/24901793/ac57d5f8-6cff-4312-9420-52f10b0e3144)


![image](https://github.com/dbeaver/dbeaver/assets/24901793/6d277cfc-a13d-4f58-a164-a60d0d55ecd8)

Then when I enable _Read database_ in Query Analysis, I get this:

![image](https://github.com/dbeaver/dbeaver/assets/24901793/6214b7db-1baf-4b02-8a80-f3ab4247cd91)

Completely lose SQL table/column/alias name foreground.

That's with the early access. 

First day trying the app.

**Comment by E1izabeth** [comment] 2024-02-01 05:11
@rasqual please create a new issue
