### ISSUE TITLE
All drivers download files with "Network unavailable"

### ISSUE THREAD

**Issue by timothydilbert** [dbeaver/dbeaver#35603] opened 2024-09-13 20:48 UTC
### Description

When we open DBeaver, attempt to create a new connection, we're prompted to  download a driver which always fails with "Network error: Network unavailable":
<img width="513" alt="image" src="https://github.com/user-attachments/assets/f73f56dc-77a1-46e4-8c0f-deacde2a1968">

It does not appear to be related to any ONE driver, but instead, all of them.

### DBeaver Version

Community Edition 24.2.0.202409011551

### Operating System

Windows Server 2022

### Database and driver

ALL OF THEM

### Steps to reproduce

1. Install DBeaver
2. Click "New Database Connection"
3. Select any database.
4. Click "Test Connection"
5. The error occurs

### Additional context

Troubleshooting:

1. Q: Firewall blocking traffic? A: There is no corporate firewall blocking traffic.
2. Q: Proxy? A: There is no proxy between this machine and the internet.
3. Q: Repeatable? A: Yes, this has occurred across multiple Win2k22 machines.

**Comment by E1izabeth** [comment] 2024-09-16 09:23
Can you open https://repo1.maven.org in the web browser?

**Comment by jonosooty** [comment] 2024-09-20 14:07
I have the same problem. Version 24.2.0.202409011551. 
The  URL for the maven repo can be opened. turning off Zscaler doesn't make a difference to success or otherwise. How can I stop the download and install manually. I managed once to connect to the database , but now I am back in the download trap and I. don't know why. Thanks for your help!

**Comment by E1izabeth** [comment] 2024-09-20 14:36
@jonosooty 
>How can I stop the download and install manually.

1. Download the driver files
2. Open Connection configuration and press Driver Settings
![image](https://github.com/user-attachments/assets/a92c020b-d939-40d9-b5d5-c5a744d97eba)
3. Choose the libraries that can't be downloaded. They're either red or blue for you, and delete them with the Delete button
![image](https://github.com/user-attachments/assets/83a50486-a4b4-49ae-bf22-f490a9668855)
4. Use add file or add folder to add driver files that you downloaded manually

**Comment by timothydilbert** [comment] 2024-09-26 03:05
@E1izabeth like with the other users, the maven repo can be opened. There are no firewall rules preventing outbound traffic, so that's not the issue either. 

Whilst manually downloading the driver is an option, I would assume that the the auto-download should work, no? Any other steps you'd recommend?

**Comment by Matvey16** [comment] 2024-09-26 12:47
Duplicate of #34775

**Closed as not planned by Matvey16** 2024-09-26 12:47 UTC
Labels: duplicate, xf:connection
