### ISSUE TITLE
Postgresql replacing * to all table columns doesn't work

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#12162] opened 2021-04-19 17:18 UTC
#### System information: 
- Windows 10 x64 Pro
- DBeaver 21.0.3.202104181339
- No additional extensions

#### Connection specification:
- PostgreSQL 11
- Default JDBC PostgreSQL driver
- SSH tunnel

#### Describe the problem you're observing:
Ctrl+space doesn't replace * after select to all columns from table

#### Steps to reproduce, if exist:
type "select * from some_table", stay after * and press ctrl+space

![img01](https://user-images.githubusercontent.com/22142845/115276990-63453b00-a14c-11eb-9292-93c598de62c4.jpg)

**Comment by LonwoLonwo** [comment] 2021-04-20 07:00
Hello @ems2811 
I can reproduce this behavior only in the case when table has no alias.
Am a right? 

![2021-04-20 09_56_32-DBeaver Enterprise 21 0 3 - _dvdrental_ Script-41](https://user-images.githubusercontent.com/45152336/115351737-3aaa5900-a1bf-11eb-9d10-9d2558eff9e1.png)

**Comment by ems2811** [comment] 2021-04-20 17:20
@LonwoLonwo, you're right. Error reproduces when table has no alias

**Comment by LonwoLonwo** [comment] 2021-04-20 21:48
side case: https://github.com/dbeaver/dbeaver/issues/12185

**Comment by LonwoLonwo** [comment] 2021-05-05 20:37
duplicate of https://github.com/dbeaver/dbeaver/issues/12162

**Closed as completed by LonwoLonwo** 2021-05-05 20:37 UTC
Labels: duplicate, xf:sql
