### ISSUE TITLE
Strange filter behaviour

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#8176] opened 2020-03-12 15:09 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.5, 7.0.0

#### Connection specification:
- Database name and version: PostgreSQL 12

... as shown in pic
![dbeaver_filter_bug](https://user-images.githubusercontent.com/11477081/76535890-a682a400-648c-11ea-956b-0bedf432f48c.png)

**Comment by plotn** [comment] 2020-03-12 15:13
Is there bugs bounty programs for getting personal enterprise license ? :)

**Comment by plotn** [comment] 2020-03-22 09:36
@serge-rider, hi, possibly it is the same as #8225

**Comment by uslss** [comment] 2020-04-14 14:08
seems to be duplicate of #8225 as it mentioned before.
ticket will be closed. if issue is still actual for you - feel free to reopen the ticket

**Closed by uslss** 2020-04-14 14:08 UTC
Labels: bug, duplicate
