### ISSUE TITLE
Colors messed up on MacOS after 

### ISSUE THREAD

**Issue by gprimosch** [dbeaver/dbeaver#14130] opened 2021-10-04 17:50 UTC
After the updating to Version 21.2.2.202110030714, the background color changes to black.

![image](https://user-images.githubusercontent.com/2371472/135899234-80ef5970-566f-478a-8b39-475bfeafcfe3.png)

If I enable theming, it gets worse and some text becomes unreadable (white on white or black on black).

I disabled theming, then tweaked the text color so it was more readable, but setting the text background color has no effect.

![image](https://user-images.githubusercontent.com/2371472/135899430-432f2ba4-026f-4f85-8cd2-8292f240b3e3.png)

I am on MacOS 11.6.

**Comment by uslss** [comment] 2021-10-04 19:49
thanks for the report.
closed as a duplicate of #13968

**Closed as completed by uslss** 2021-10-04 19:49 UTC
Labels: duplicate
