### ISSUE TITLE
SQL Editor text result output truncate last character of some columns

### ISSUE THREAD

**Issue by ptremblaygiga** [dbeaver/dbeaver#4601] opened 2018-11-12 18:51 UTC
The SQL Editor plain text output seems to truncate the last character of some columns (regardless of the type).  The Grid result works fine. 
 
The 'ID' column is in problem here, the RefID is ok :
```
ID       |RefID|
---------|----------|
10154784 |100104539 |     
10154784 |100104540 |     
10154784 |100104540 |   
10154784 |100104540 |   
10154784 |100104540 |     
```

And I should have this : 

ID                     RefID
101547840	100104539
101547841	100104540
101547842	100104540
101547844	100104540
101547847	100104540
101547848	100104540
101547849	100104540

Thanks,

Patrick

**Comment by serge-rider** [comment] 2018-11-12 18:57
Duplicate of #4547
Thanks for the bug report anyway

**Closed by serge-rider** 2018-11-12 18:57 UTC
Labels: bug, duplicate
