### ISSUE TITLE
PostgreSQL table does not show comment in DDL.

### ISSUE THREAD

**Issue by smcdl** [dbeaver/dbeaver#9387] opened 2020-07-29 02:42 UTC
#### System information: 
- Operating system (distribution) and version: MacOS
- DBeaver version: 7.1.3
- Additional extensions: Nothing

#### Connection specification:
- Database name and version: PostgreSQL 11.8
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
It does not show comment in DDL of Properties tab and Generate SQL -> DDL context menu.

#### Steps to reproduce, if exist:
Please refer to description.

**Comment by kseniiaguzeeva** [comment] 2020-07-29 08:20
Thank you for the bug report.

**Comment by hsseo0501** [comment] 2020-07-29 08:59
@smcdl @kseniiaguzeeva  Hello, Maybe you can fix that by following the link [issue-8329](https://github.com/dbeaver/dbeaver/issues/8329)

**Comment by kseniiaguzeeva** [comment] 2020-07-29 09:01
Thank you, indeed. I close the ticket as a duplicate of https://github.com/dbeaver/dbeaver/issues/8329

**Comment by smcdl** [comment] 2020-07-29 09:51
@kseniiaguzeeva It is not the same question. Generate SQL dialogs does not show 'COMMENT ON COLUMN' sql script and it also dose not have 'Show comments' button yet.

![image](https://user-images.githubusercontent.com/4975064/88785711-1e473600-d1c4-11ea-953d-215f0d2ec2a3.png)

**Comment by kseniiaguzeeva** [comment] 2020-07-29 10:55
You are right. 

(It can be tested on postgres.Xeniia.9294:
Select Generate SQL>DDL in the table context menu.
Expected: comments for the table and column "pk" are shown in the table DDL.
Actual result: there are no comments at all).

**Comment by serge-rider** [comment] 2020-08-09 11:34
@SA357 I think we need to add extra options in DDL generate dialog. Otherwise we will use existing options for a very different purposes and this will produce a mess.

I'd suggest to add new object definition options similar to PostgreSQL:
OPTION_INCLUDE_NESTED_OBJECTS
OPTION_INCLUDE_COMMENTS
OPTION_INCLUDE_PERMISSIONS

And add corresponding checkboxes in Generate SQL dialog.

To determine whether an option supported by underlying database object we can use DBPScriptObjectExt2 interface.
Existing implementations of DBPScriptObjectExt2 must be patched.

Then we can reuse this feature in other databases.

**Comment by uslss** [comment] 2020-08-12 14:30
verified

**Closed by uslss** 2020-08-12 14:30 UTC
Labels: bug, feature request, x:postgresql
