### ISSUE TITLE
Unable to recover my files after updating to 23.0.3

### ISSUE THREAD

**Issue by Siddhu1096** [dbeaver/dbeaver#35114] opened 2024-08-07 13:38 UTC
### Description

I had dbeaver 6.0.3 version. I had around 30 scripts in that. Today I updated the dbeaver to 23.0.2 version. When I opened the software, I couldn't see all my scripts. Its just blank. I went inside program files directory and I can see all files got over written.  I don't remember saving a backup of my scripts and my organization is not allowing me to install any third party data recovery tools. What to do? Is there any hidden place where I can find my all files? Thanks in advance

### DBeaver Version

23.0.3

### Operating System

Windows

### Database and driver

Postgresql

### Steps to reproduce

1. Add some scripts in DBeaver 6.0.3
2. Update to 23.0.3
3. Make the scripts available in the newer version

**Comment by E1izabeth** [comment] 2024-08-07 13:41
You can try finding your old workspace location https://github.com/dbeaver/dbeaver/wiki/Workspace-location?ysclid=lzjwchcq3h743494035#old-default-workspace-location
Most probably, they're there

**Comment by Siddhu1096** [comment] 2024-08-07 13:45
Nope, unfortunately couldn't find C:\Users\YourName\.dbeaver4 this path as suggested in the link

**Comment by E1izabeth** [comment] 2024-08-07 13:52
Have you installed new version for the current user or for all users?
![image](https://github.com/user-attachments/assets/e9116cc3-0e0c-4d0d-a784-6196c128f9e1)

**Comment by Siddhu1096** [comment] 2024-08-07 13:56
The new version was installed through companys software download portal. So all of these were set as default. Hence I am guessing its "For me"

**Comment by E1izabeth** [comment] 2024-08-07 13:58
OK, thank you
As an immediate workaround I can propose to try installing 6.0.0 version to find the script files location
https://dbeaver.io/files/6.0.0/

![image](https://github.com/user-attachments/assets/ecbf679e-db5b-40c3-8088-ddd564ab9a3c)

**Comment by Siddhu1096** [comment] 2024-08-07 14:00
But will it retrieve my codes? Since its got overwritten

**Comment by E1izabeth** [comment] 2024-08-07 14:00
Did you lose only scripts? Does connections come to the new version successfully?

**Comment by Siddhu1096** [comment] 2024-08-07 14:01
Connection does comes successfully. Only the scripts got lost

**Comment by Siddhu1096** [comment] 2024-08-07 14:12
Any thoughts? It had my 2 years of code and I saved only a lil of that in my local directory :(

**Comment by E1izabeth** [comment] 2024-08-07 14:28
Could you tell me, if you see path like mine with destination folder called `workspace6`, when pressing `File->Switch workspace->Other...`?
![image](https://github.com/user-attachments/assets/f5a43249-e14e-49c7-a54d-eef364dcf5b5)
![image](https://github.com/user-attachments/assets/8d5fe740-f8fe-45f8-988d-b04c67c13ab5)

**Comment by Siddhu1096** [comment] 2024-08-07 14:55
Yes I can see

**Comment by E1izabeth** [comment] 2024-08-07 15:01
Then installing old version might help in case if scripts we're not copied to the new workspace during migration
https://github.com/dbeaver/dbeaver/issues/35114#issuecomment-2273546438

Also, maybe you would be able to find it by searching for "Script" in explorer

**Comment by Siddhu1096** [comment] 2024-08-07 15:05
> Also, maybe you would be able to find it by searching for "Script" in explorer
Trying this

**Comment by Siddhu1096** [comment] 2024-08-07 15:06
They are listing so many files, what exactly should I be searching for?

**Comment by E1izabeth** [comment] 2024-08-07 15:07
Usually DBeaver stores all your scripts in the project location in "Scripts" folder. Also if you haven't renamed those files, their default name starts from "Script"

**Comment by Siddhu1096** [comment] 2024-08-07 15:38
Negative, Couldnt find the folder

**Comment by E1izabeth** [comment] 2024-08-07 15:40
Thank you for checking

**Comment by Siddhu1096** [comment] 2024-08-07 15:44
When I searched for .dbeaver, I got so many files and some of them are having previous dates when it got created. But none had my scripts

**Comment by Siddhu1096** [comment] 2024-08-07 16:37
Any other way @E1izabeth

**Comment by E1izabeth** [comment] 2024-08-07 16:49
I have no other ideas, except already mentioned

**Comment by TB-HunBoka** [comment] 2024-08-08 12:34
> When I searched for .dbeaver, I got so many files and some of them are having previous dates when it got created. But none had my scripts

If you use the windows 10 file explorer, then it might help, to search for this in the search box
kind:folder filename:.dbeaver4

or replace the filename with Scripts, if that was not changed since that version.

This will only search for folders having exactly the name you are searching for. I suggest to search on all hard drives you got, as it might have been installed somewhere else than the default workspace.

**Comment by E1izabeth** [comment] 2024-09-26 12:22
Unfortunately, we have not been able to reproduce the reported behavior. Therefore, I am closing this issue. If we receive a similar report from another user or can reproduce the issue in the future, we will reopen it.

**Closed as not planned by E1izabeth** 2024-09-26 12:22 UTC
Labels: can't reproduce, wait for response
