### ISSUE TITLE
Saving the editor while saving changes to the database

### ISSUE THREAD

**Issue by chapmanjacobd** [dbeaver/dbeaver#13186] opened 2021-07-13 22:41 UTC
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.1.10

#### Connection specification:
- Database name and version BigQuery 42_1.2.16.1020

#### Describe the problem you're observing:

Saving the editor while saving changes to the database causes Dbeaver to lock-up and save new rows to the database twice causing duplicate rows inserted.

**Comment by Matvey16** [comment] 2021-07-14 07:25
Can you please provide more clear steps to reproduce? What action is done first and last, maybe some additional actions in between.

**Comment by chapmanjacobd** [comment] 2021-07-14 07:59
I'm pretty sure doing Ctrl-S then Ctrl-S after a few seconds will trigger it. 

If not then Ctrl-S in the data window then typing something in the query editor and Ctrl-S definitely causes it.

maybe it's only super noticable on BigQuery driver because BQ is pretty slow compared to others

**Comment by serge-rider** [comment] 2022-04-20 08:01
I can't reproduce this anymore.
Probably the problem was resolved in one of previous data save fixes

**Comment by uslss** [comment] 2022-04-25 08:40
#15071

**Closed as completed by uslss** 2022-04-25 08:40 UTC
Labels: enhancement, can't reproduce, xf:sql, xf:data, sp:3
