### ISSUE TITLE
Snapcraft Installed dbeaver-ce Shouldn't Lead to RPM Version Upgrades

### ISSUE THREAD

**Issue by Lonniebiz** [dbeaver/dbeaver#9208] opened 2020-07-08 15:02 UTC
I'm running Dbeaver 7.1.0, which I installed onto Kubuntu 20.04 via [snapcraft](https://snapcraft.io/dbeaver-ce).

Upon launch, Dbeaver informs me that 7.1.2 is available, but if I click the "Upgrade" button is leads me to web page that prompts me to download a RPM package, which is incorrect for snap installs and for Ubuntu based distributions in general.

This doesn't confuse me; I know that I just need to wait for the snap-package to be upgraded and I'll automatically receive the upgrade via my normal system update process. However, I thought I'd mention this because I can imagine it confusing others.

**Comment by uslss** [comment] 2020-07-08 17:35
thanks for the bug report.
closed as a duplicate of #8545

**Closed by uslss** 2020-07-08 17:35 UTC
Labels: bug, duplicate

**Comment by Lonniebiz** [comment] 2020-07-08 19:58
Are you sure this is the exact same bug? It is certainly similar, but keep in mind that the Snap packaged installation of Dbeaver probably shouldn't point to either debian or RPM packages. It is my understanding that snap packages are automatically upgraded via regular system update once the snap package maintainer upgrades the snap package itself in the snap repository. Which, if so, is great because you wouldn't have to tell them about upgrades, they'd just get them.

I could be wrong about this, but it seems I notice other snap packages auto-upgrading in this way in Kubuntu 20.04.
