### ISSUE TITLE
'Auto Increment' option for Firebird columns doesn't do anything

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14204] opened 2021-10-12 11:50 UTC
#### System information: 
- Operating system (distribution) and version Ubuntu 20.04 on WLSg
- DBeaver version 21.2.2 CE
- Additional extensions

#### Connection specification:
- Database name and version Firebird 2.5 & 3.0
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
Inability to create auto increment columns from UI, even though corresponding UI controls are there.

#### Steps to reproduce, if exist:
1. Create a new Firebird table, open its entity editor
2. Add an integer column, tick _Auto Increment_, press _OK_
3. Save the table. Notice that DDL doesn't contain anything related to auto increment.
4. Refresh entity editor. _Auto Increment_ is gone, unsurprisingly.

Keep in mind that in Firebird <= 2.5, there is no such thing as an auto-increment column at all. The only option I know is to emulate them with sequences and triggers.

**Comment by LonwoLonwo** [comment] 2022-02-07 07:19
Duplicate of https://github.com/dbeaver/dbeaver/issues/13674

**Closed as completed by LonwoLonwo** 2022-02-07 07:19 UTC
Labels: x:firebird, duplicate, xf:metadata
