### ISSUE TITLE
Wrong minimal java version specified as requirement

### ISSUE THREAD

**Issue by SubOptimal** [dbeaver/dbeaver#10716] opened 2020-12-17 07:29 UTC
#### System information: 
- Operating system (distribution) and version - unrelated
- DBeaver version - checked for 7.3.0
- Additional extensions - unrelated

#### Connection specification:
- Database name and version - unrelated
- Driver name - unrelated
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  - unrelated

#### Describe the problem you're observing:

At some places the minimal required Java version is specified to be at least 1.8. Where as dbeaver actually at build and runtime it requires Java >= 11.

#### Steps to reproduce, if exist:
- https://github.com/dbeaver/dbeaver/wiki/Build-from-sources

> **Prerequisites**:
> Java (JDK) 8+.

- `deb` installer package

      $ dpkg -I dbeaver-ce_7.3.0_amd64.deb
      ...
      Depends: openjdk-8-jre-headless | openjdk-11-jre-headless | openjdk-11-jdk-headless

- `rpm` installer package

      $ rpm -qpR dbeaver-ce-7.3.0-stable.x86_64.rpm
      ...
      java >= 1.8

- in the `pom.xml`

      <plugin>
          <groupId>org.eclipse.tycho</groupId>
          <artifactId>tycho-compiler-plugin</artifactId>
          <version>${tycho-version}</version>
          <configuration>
              ...
              <target>1.8</target>

- build with Java 1.8 fails with

      Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/tycho/core/p2/P2ArtifactRepositoryLayout has been compiled by \
           a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file \
           versions up to 52.0

- running dbeaver with Java 1.8 fails with

      org.osgi.framework.BundleException: Could not resolve module: org.eclipse.debug.core [43]
        Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

**Comment by kseniiaguzeeva** [comment] 2020-12-21 13:29
Thank you for the report!
- Fixed in wiki.
- deb installer package - fixed in 7.3.1 release
- rpm installer package - fixed in 7.3.1 release
- pom.xml -  it is not a bug

**Closed by kseniiaguzeeva** 2020-12-21 13:29 UTC
Labels: bug, wait for review
