### ISSUE TITLE
Error converting string to composite type

### ISSUE THREAD

**Issue by CarlTien** [dbeaver/dbeaver#20053] opened 2023-05-23 00:59 UTC
### Description

org.jkiss.dbeaver.model.exec.DBCException: Error converting string to composite type
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:110)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:828)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3842)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5073)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Composite type 'jsonb' has no attributes
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:184)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:107)
	... 16 more

### DBeaver Version

ultimate 23

**Comment by ShadelessFox** [comment] 2023-05-23 01:13
Hello @CarlTien,

Please provide the steps required to reproduce your issue.

**Comment by CarlTien** [comment] 2023-05-23 04:19
I use opengauss version2.1.0 
https://docs.opengauss.org/en/docs/2.1.0/docs/Quickstart/Quickstart.html
which is compatible with PostgreSQL

```sql
CREATE TABLE public.newtable1 (
	column1 varchar NULL,
	column2 jsonb NULL,
	column3 json NULL
);
```

the jsonb type data cannot show

**Comment by LonwoLonwo** [comment] 2023-05-23 08:26
Hello @CarlTien 

Please also provide the example of jsonb data from your table and PostgreSQL database and driver version.

**Comment by CarlTien** [comment] 2023-05-24 02:14
I maybe know why,  database "opengauss" is compatible with postgresql9.2.4 which dont have "jsonb" data type, but opengauss added jsonb support. Maybe dbeaver dont support jsonb when the server info return postgresql9.2.4

**Comment by arhayka** [comment] 2023-05-25 13:16
If you're using our paid product and have an appropriate license, consider creating your ticket on our website: https://dbeaver.com/submit-ticket/
Thank you.

**Comment by E1izabeth** [comment] 2023-06-26 08:39
It's been a while since no update here, so I'm closing this issue. If it's still actual, please let me know.

**Closed as not planned by E1izabeth** 2023-06-26 08:39 UTC
Labels: x:postgresql, xf:data, AS
