### ISSUE TITLE
Autoload new part of data at scrolling

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#9796] opened 2020-09-17 06:27 UTC
#### System information: 
- Windows 10 x64
- DBeaver 7.2.0.202008302047
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5.22
- Driver name: org.postgresql:postgresql:RELEASE [42.2.5]
- No tunnels or proxies (SSH, SOCKS, etc)

#### Describe the problem you're observing:
If query result contains only boolean field - autoload new part of data at scrolling doesn't work.

#### Steps to reproduce, if exist:
```
create temp table tt as
select generate_series(1,1000) as id, false::boolean as res, 'text' as txt;

select res
from tt
```
at select query result go to the last row and try to scroll - new part of data doesn't loads.
if query contains another fields (id or txt) loading new part of data is works

**Comment by ooobii** [comment] 2020-09-17 12:21
Confirmed this affects DBeaver Version 7.2.0.202008302047 on MacOS Catalina 10.15.6

**Comment by kseniiaguzeeva** [comment] 2020-09-18 07:36
Thank you for the report.

**Comment by serge-rider** [comment] 2020-11-07 18:36
Can't reproduce this anymore.
Maybe if was fixed in some other ticket.

**Comment by kseniiaguzeeva** [comment] 2020-11-07 19:03
Can't reproduce anymore too. Please report if it is still actual for you.

**Closed by kseniiaguzeeva** 2020-11-07 19:03 UTC
Labels: bug, can't reproduce, x:postgresql

**Comment by ems2811** [comment] 2020-11-09 06:46
Still reproduces in 7.2.4.202011011603
