### ISSUE TITLE
DBeaver: Open Database Object is broken in 6.1.5 CE

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6601] opened 2019-08-23 09:15 UTC
DBeaver - **Version 6.1.5 CE**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

The function of menu choice **Navigate** -> **Open Database Object** have stopped to work in version  **6.1.5 CE** of _Dbeaver_.

**o** Connect to a database of choice.
**o** Open dialog for **Open Database Object** (shortcut **Ctrl+Shift+D**).
**o** Search for a table and press the **OK** button to table content/information.
**o** **Nothing happens**. This looks like a bug since it works in version **6.1.4 CE**.
**o** In version **6.1.4 CE** the table contents are shown.

Please, please, and a bit more please check the basic functionality before release of a new version. I have not been able to use any release after version **6.0.0 CE**. Maybe you ought to use one of the 14-days developer days to test only.

New bugs might be ok, but regression bugs that make previous working functionality to stop to work is sad to see.

The _DBeaver_ product is a **super great thing**, maybe that makes it more irritating when things stop working. I don't know.

**Comment by p91paul** [comment] 2019-08-23 12:18
I'm using 6.1.5 and this feature works fine.

**Comment by pdanie** [comment] 2019-08-23 19:50
Im glad for you that you get it to work in your environment.

I have tested it on two of my **Windows 7 - 64bit** and it does not work on any of them. I have tried with empty configurations and it still does not work. If I on the other side installs version **6.1.4 CE** it works as I like. So something has happened.

**Comment by fabianMendez** [comment] 2019-08-24 12:11
I had the same problem on 6.1.4 but updating to 6.1.5 made it work again.

PS: I am using Ubuntu 19.04

**Comment by p91paul** [comment] 2019-08-24 12:45
Open Database Object always had a bug: if you create a new object externally or from a script, then search for it, it will find it though it won't be able to open it until you hit F5 on the connection in the navigator, to refresh the list of objects. Maybe you are hit by that, regardless of the version? Not sure if the DBeaver developers are already aware of that.
@pdanie problem looks different since it appears to survive even a restart.

**Comment by serge-rider** [comment] 2019-08-24 14:01
@pdanie I believe this bug is a duplicate of #6551 and it was fixed in 6.1.5 hotfix version (it was released a day later).
Try to re-download 6.1.5.

**Closed** 2019-08-24 14:02 UTC
Labels: bug, duplicate

**Comment by pdanie** [comment] 2019-08-25 06:20
I tried it out on the new **version 6.1.5 CE** and it seems to work.

/ Thanks
