### ISSUE TITLE
SQL editor has rendering glitches

### ISSUE THREAD

**Issue by meglio** [dbeaver/dbeaver#23204] opened 2024-03-22 01:47 UTC
### Description

<img width="714" alt="image" src="https://github.com/dbeaver/dbeaver/assets/282177/c500d969-adaa-49a1-bfa6-0e6268a90cce">

### DBeaver Version

Version 24.0.0.202403031740

### Operating System

14.3.1 (23D60)

### Database and driver

postgres:16.1

**Comment by Destrolaric** [comment] 2024-03-22 08:50
Duplicate of https://github.com/dbeaver/dbeaver/issues/22299

**Closed as not planned by Destrolaric** 2024-03-22 08:50 UTC
Labels: duplicate

**Comment by Destrolaric** [comment] 2024-03-22 08:52
As a workaround disable `Window->Preferences->Editors -> SQL Editor -> Code Editor -> Enable semantic analysis`
![image](https://github.com/dbeaver/dbeaver/assets/20579256/eb043ce8-7731-4f23-837b-0d000e82868c)
