### ISSUE TITLE
erd bug

### ISSUE THREAD

**Issue by gibranHyun** [dbeaver/dbeaver#17106] opened 2022-07-18 05:23 UTC
#### System information: 
- Operating system (distribution) and version : win 10 pro
- DBeaver version :   22.1 etc
- Additional extensions

#### Connection specification:
- Database name and version : oracle 11g
- Driver name : oracle.jdbc.OracleDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
The table comments in the diagram are not displayed immediately, 
but comments appear in the diagram only when the specification is retrieved by double-clicking the table.
This is very inconvenient.
To see the comments of the saved er diagrams,
I have to refresh the table by double-clicking it every time and returning to the diagram tab and then refresh.

I've been expecting this bug to be fixed with every new version for several years, 
but there's no change,.

**Comment by uslss** [comment] 2022-07-18 13:04
thanks for the report
closed as a duplicate of #16858

**Closed as completed by uslss** 2022-07-18 13:04 UTC
Labels: duplicate, xf:erd
