### ISSUE TITLE
Ctrl+Enter no longer executing only statement where cursor is

### ISSUE THREAD

**Issue by Walkeer** [dbeaver/dbeaver#25061] opened 2024-04-22 10:52 UTC
### Description

Up until the very last version, this is my most used feature: to be able to execute just the query where the cursor is using Ctrl+Enter. Selecting 1 whole statement with mouse (the whole statement is blue-highlighted) fixes the issue.

### DBeaver Version

Community Edition 24.0.3

### Operating System

 Windows 10 Enterprise

### Database and driver

Terradata JDBC 20.00.00.19

### Steps to reproduce

1)have multiple statements separated y semicolon in SQL editor
2) put cursor on one of them
3) hut Ctrl + Enter
4) all statements are executed

**Comment by E1izabeth** [comment] 2024-04-22 10:57
Please provide the minimal script example to reproduce your issue

**Comment by Walkeer** [comment] 2024-04-22 11:00
example script here, confirmed its able to replicate this issue:
```
select 1;

select 2;
```

**Comment by E1izabeth** [comment] 2024-04-22 11:04
Unfortunately, I can't reproduce it. What setting value do you have here?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be8457a0-d62c-4acb-ac2f-67ce518cf3f5)

**Comment by E1izabeth** [comment] 2024-04-22 11:04
Is `Ignore native delimiter` turned on?

**Comment by Walkeer** [comment] 2024-04-22 11:13
I have exactly the same settings as you have. Using the latest terradata JDBC driver. Previous DBeaver version works fine as well as all older versions.

**Comment by MashaKorax** [comment] 2024-04-22 11:32
I can not reproduce the issue.

**Comment by E1izabeth** [comment] 2024-04-22 11:34
@Walkeer
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by Walkeer** [comment] 2024-04-22 12:08
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15062562/dbeaver-debug.log)

[empty.log](https://github.com/dbeaver/dbeaver/files/15062581/empty.log) - renamned from .log

**Comment by E1izabeth** [comment] 2024-04-22 12:12
Please try switching `Blank line is statement delimiter` setting to `Always`
https://github.com/dbeaver/dbeaver/issues/25061#issuecomment-2069107494

**Comment by Walkeer** [comment] 2024-04-22 12:41
that fixed it

**Comment by Walkeer** [comment] 2024-04-22 12:46
however, this setting breaks execute as script:
SQL Error [3576] [25000]: [Teradata Database] [TeraJDBC 20.00.00.19] [Error 3576] [SQLState 25000] Data definition not valid unless solitary.
  [Teradata Database] [TeraJDBC 20.00.00.19] [Error 3576] [SQLState 25000] Data definition not valid unless solitary.
  [Teradata Database] [TeraJDBC 20.00.00.19] [Error 3576] [SQLState 25000] Data definition not valid unless solitary.

**Comment by alesc2000** [comment] 2024-04-22 14:07
"Blank line is statement delimiter: Smart" not working as expected. If I have the usual delimiter ";" at the end of the query and then a blank line, then the delimiter is ignored. In the editor it appears as a query block, which can even be collapsed.
![image](https://github.com/dbeaver/dbeaver/assets/19900533/28fcb490-46bb-469c-82de-6229f89c5c78)
![image](https://github.com/dbeaver/dbeaver/assets/19900533/dd94940f-9b19-485f-a327-03c3f8f38cb3)

**Comment by E1izabeth** [comment] 2024-04-22 14:12
@alesc2000 currently it's the expected behavior

**Comment by Walkeer** [comment] 2024-04-22 20:03
something definitly changed or broke in the very last version. "Smart" is no longer working. It also broke "Execute SQL Script". When I have the default "smart" setting and use any DML along with "Collect Statistics" statement and run "Execute SQL Script", it ends with an error. With "Always", its working as usual.

```
SQL Error [3576] [25000]: [Teradata Database] [TeraJDBC 20.00.00.19] [Error 3576] [SQLState 25000] Data definition not valid unless solitary.
  [Teradata Database] [TeraJDBC 20.00.00.19] [Error 3576] [SQLState 25000] Data definition not valid unless solitary.

```

**Comment by Xylandor** [comment] 2024-04-22 20:55
I agree with @Walkeer. Something has broken this since the latest update. This behavior is occurring on my RedShift and MySQL connections. It doesn't happen all the time, but I know if I have the LIMIT keyword specified, it'll happen every time.

Here's a test script. Attached is a vid showing that even though I place the cursor in the `SELECT 1;` line, it ignores the semi-colon and tries to execute the second `LIMIT 1;` line too; which throws an error.

I'm using the same DBeaver version: 24.0.3, but on a MacOS Sonoma 14.4.1, with a MySQL v8 connection.

```
select 1;

limit 1;
```


https://github.com/dbeaver/dbeaver/assets/24617679/91f09dfa-5dda-4670-8069-93ac1a3cefb9

**Comment by Xylandor** [comment] 2024-04-22 21:16
After testing more with the `Blank line is statement delimter setting`, the `Smart` option seems to be causing me issues. I set it back to `Always` and it is now working like I'm used to. 

Not really sure how that `Smart` option is supposed to work or how it determines whether to use/ignore the semi-colon, but I believe there's something wrong with it. I don't know of a use-case where that would be a good option to use. 

Looking back at the previous version (24.0.2), this was a new option added.
![image (2)](https://github.com/dbeaver/dbeaver/assets/24617679/9b7f2e3d-c7a1-480f-8d18-7f6078aae5ea)

So, @Walkeer, I'd suggest changing this to Always to get it working like you expect.

**Comment by E1izabeth** [comment] 2024-04-23 07:40
@Walkeer Why do you expect to execute `limit 1` as a separate query? Just `limit 1` is not a valid statement

**Comment by JenChampagne** [comment] 2024-04-26 21:47
This new feature gave me an incredible amount of frustration until I set `Blank line is statement delimiter` to `Always`. I saw it happen in two cases. I don't have a reproduce case for the second case, but I do for the first.

The first case is that I've often used my script files as a bit of a scratch pad because I knew that empty lines were a delimiter anyway. Sometimes it might be some plain text, and sometimes it is a part of a query I was keeping for reference nearby or for future use.

For example, here is an minimized example in which you can see several semicolons reflecting my frustration. I didn't have a `select` in front of a partial query several lines later, which somehow equates to these should be the same query.

```
select * from mytable;;;;;;;;;;;;


-----
distinct type from mytable;
```

The other situation was where the second query started with `do` and was a plpgsql code block.

As mentioned, I've "solved" the issue by disabling "smart" mode, but it was really frustrating being automatically opted in to this. I'm not sure if "smart" mode always existed and changed, or if it's just new, but changing behaviour like this was bound to frustrate a bunch of people.

The last reply by @E1izabeth demonstrates their use cases never included partial queries, and that people who use the software differently should use it the way they use it instead. I'm not trying to pick on anyone, I just want to point out that a perspective like that is a recipe for trouble when making sudden changes.

At least in software libraries, I can generally rely on semver rules to suggest when there is a breaking change, but since I get nagged to upgrade every time I open the application, I don't generally expect to need to seek out changelogs on my own to see if something is going to sabotage my worlflow.

I hope in the future something like this at least requires being opted into.

**Comment by E1izabeth** [comment] 2024-04-29 08:10
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Closed as completed by E1izabeth** 2024-04-29 08:10 UTC
Labels: x:teradata, xf:sql execution

**Comment by coleman-rik** [comment] 2024-04-29 19:01
there's a problem with blank line as delimiter.  I often have multiple statements and I only want to run the one I have my cursor over.
ex:
```
select * from foo;
select bar from foo1;
delete from foo there bar < 10;
insert into bar (id, some_text) values (1, 'foo');
select * from baz where add_dt > '2023-10-06';
```
I _used_ to be able to place my cursor inside any of those statements, and "Execute SQL Squery" would **only** run the statement where my cursor was placed in.

There are no blank lines to use as a delimiter.

**Comment by steelunicorn** [comment] 2024-08-16 10:47
Having same issue in 24.1.3 and 24.1.4 versions.
But 24.1.0  works as expected, in both cases, either `Blank line is statement delimiter`  set as` Always` or `Smart`.

**Comment by E1izabeth** [comment] 2024-08-16 10:55
@steelunicorn please create a new issue and provide clear steps to reproduce for your case
