### ISSUE TITLE
There is no way to change connection for a detached tab (the connection get changed for incorrect tab)

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34517] opened 2024-06-26 19:39 UTC
### Description

There is no way to change connection for a detached tab (the connections get changed for incorrect tab)

### DBeaver Version

Community Edition 24.1.1

### Steps to reproduce

https://github.com/dbeaver/dbeaver/assets/33929221/937b2811-faa7-4e5e-b1b9-6f883a1bccd3

**Comment by E1izabeth** [comment] 2024-06-26 19:47
Thank you for bug report.
I'm closing it as a duplicate of #18658
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-06-26 19:47 UTC
Labels: duplicate, xf:ui, xf:sql editor
