### ISSUE TITLE
Importing from CSV some text characters are replaced by `?`

### ISSUE THREAD

**Issue by goxr3plus** [dbeaver/dbeaver#13346] opened 2021-07-28 10:59 UTC
#### System information: 
- Windows 10 / 2021 May Update
- DBeaver version - 21.1.3

#### Connection specification:
- Database name and version
- Driver name
![image](https://user-images.githubusercontent.com/20374208/127311026-95e76384-f823-4524-8e2f-5ef98dcb31fa.png)

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
 **Nope it's locally**

#### Describe the problem you're observing:

I am importing a csv to database and some German letters it shows them like this ( they contain a letter like `?` )

![image](https://user-images.githubusercontent.com/20374208/127311313-cc501bdb-1d69-4f94-a93e-714b9a968e7a.png)

But actually on the csv they are okay

![image](https://user-images.githubusercontent.com/20374208/127311402-0bffef8f-dfdd-4ad1-884a-0d205855d78d.png)

#### Steps to reproduce, if exist:

Import the following csv ( after you unzip the attached file ) on a mysql database with a table with following columns 

[123.zip](https://github.com/dbeaver/dbeaver/files/6892443/123.zip)

![image](https://user-images.githubusercontent.com/20374208/127311535-7887dc09-d1ca-438a-84c3-8b8aa40bacaa.png)

**Comment by ShadelessFox** [comment] 2021-07-28 11:07
Hello @goxr3plus,

The issue may be with database encoding. Make sure you're using suitable encoding in both CSV importer and your table.

**Comment by goxr3plus** [comment] 2021-07-28 12:01
I am using this default encoding for my database 

![image](https://user-images.githubusercontent.com/20374208/127318717-f1e1f0ad-7f35-45ad-a5fd-944d114a0b97.png)

Do you recommend another encoding ? 

@ShadelessFox

**Comment by goxr3plus** [comment] 2021-07-28 12:05
I just tried utf-8 and  ascii on the importer but still the problem is there .

![image](https://user-images.githubusercontent.com/20374208/127319318-e10f36e1-ea69-490e-a8e4-9dfad7286efd.png)

**Comment by ShadelessFox** [comment] 2021-07-28 12:10
Encoding looks OK. Strangely enough, with the same setup I was able to successfully import data containing unicode characters.

Try adding `-Dfile.encoding=UTF-8` just after `-vmargs` in dbeaver.ini located in DBeaver's root directory.

https://github.com/dbeaver/dbeaver/wiki/Command-Line#system-parameters

**Comment by goxr3plus** [comment] 2021-07-28 12:34
You tried with my attached .zip and UTF-8 encoding on the import ?

```Try adding -Dfile.encoding=UTF-8 just after -vmargs in dbeaver.ini located in DBeaver's root directory.```

Like this ?

![notepad_2021-07-28_15-32-29](https://user-images.githubusercontent.com/20374208/127322867-1bed2b8b-3071-4a99-8838-4ce4af796b64.png)

**Comment by ShadelessFox** [comment] 2021-07-28 12:42
Actually, I missed the attachment, my bad.

I was able to reproduce your issue and found several workarounds:
1. Your file is encoded in extended ASCII, also known as `latin1`. You can specify `latin1` as encoding in CSV importer.
2. You can convert file encoding to UTF-8.

Using these approaches, you don't have to edit `dbeaver.ini` file.

**Comment by goxr3plus** [comment] 2021-07-28 12:51
@ShadelessFox  

Excellent thank you a lot !!!!!!!!!!

=> I tried 1 and it worked.

=. I tried changing the encoding of the csv using Notepad++ to UTF-8 and then the encoding on the csv formatter was utf-8 but still the same problem .

As far as way 1 works i am fine :).

**Comment by ShadelessFox** [comment] 2021-07-28 12:55
Just a note: in case of Notepad++, you need to use <kbd>Convert to UTF-8</kbd> option rather than <kbd>UTF-8</kbd>:

![image](https://user-images.githubusercontent.com/35821147/127325260-e0dcbd3e-fec9-47ea-93a6-e8db15677a09.png)

**Comment by ShadelessFox** [comment] 2021-07-28 12:57
I will close this issue because it's now resolved. You're still able to add comments here.

**Closed as completed by ShadelessFox** 2021-07-28 12:57 UTC
Labels: x:mysql, xf:datatransfer, question

**Comment by javimediciones43** [comment] 2025-03-30 19:40
![Image](https://github.com/user-attachments/assets/0f14c82e-eaf4-49d4-8f9f-8a825d4feed6)
con **Encoding:  latin1** se me soluciono, gracias.
