### ISSUE TITLE
[Question-PG] Changed behiavour in 7.1.0 about search path?

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8877] opened 2020-06-03 09:28 UTC
I am 99.99999% sure that in versions before 7.1.0 the search path was not defined by default at connection.

Now, i can query `select * from table` withous specifying the schema, and the query works, *even when table is not i schema `public`*.

I really hope this is not expected and can be changed, couse this change might lead to a looot of problems... 

Please, for the future, don't implement those "breaking" features enabled by default.

**Comment by uslss** [comment] 2020-06-03 13:43
Hi, @wiwwo ,
unfortunately cannot reproduce an issue. What schema is chosen as default in the toolbar in your case?
![image](https://user-images.githubusercontent.com/31996417/83643957-63326000-a5b9-11ea-879a-66de65471cda.png)

**Comment by wiwwo** [comment] 2020-06-03 14:01
Not sure it matters, since I was never being able to refere to any table without using the schema in front of the table name (except from public schema, of course)...

**Comment by serge-rider** [comment] 2020-06-04 05:50
@wiwwo DBeaver set search_path during connection open whenever you have some active database/schema set. And it rememebers last active schema for each SQL script file (you can see it in the main toolbar on @uslss screenshot).

You can check what queries dbeaver executes internall in Query Manager view (just enable metadata/util queries view).

**Comment by mkgrgis** [comment] 2020-06-27 06:27
@serge-rider , 
> rememebers last active schema for each SQL script file 
but there is problems with initiation of active schema (=> problem with search path) for a new file https://github.com/dbeaver/dbeaver/issues/9040, https://github.com/dbeaver/dbeaver/issues/8766

**Comment by uslss** [comment] 2020-07-20 09:27
closed as duplicate of #9040

**Closed by uslss** 2020-07-20 09:27 UTC
Labels: bug, can't reproduce, duplicate, wait for response
