### ISSUE TITLE
Restore database error due to unrecognized configuration parameter 

### ISSUE THREAD

**Issue by Rccfrz** [dbeaver/dbeaver#9184] opened 2020-07-07 09:42 UTC
Hello,

I am trying to restore a database in Dbeaver 7.1.1 (working on a Chromebook)
psql (PostgreSQL) 12.3 (Debian 12.3-1.pgdg100+1)

The db I have to restore is in .tar format 
[dvdrental.zip](https://github.com/dbeaver/dbeaver/files/4884020/dvdrental.zip)

However, the restore process always fails due to an unrecognized configuration parameter "default_table_access_method"

Is there a way to solve this issue? Is that a problem in the file?

**Comment by Rccfrz** [comment] 2020-07-07 09:48
Hello,

I am trying to restore a database in Dbeaver 7.1.1 (working on a Chromebook)
psql (PostgreSQL) 12.3 (Debian 12.3-1.pgdg100+1)

The db I have to restore is in .tar format 
[dvdrental.zip](https://github.com/dbeaver/dbeaver/files/4884020/dvdrental.zip)

However, the restore process always fails due to an unrecognized configuration parameter "default_table_access_method"

Is there a way to solve this issue? Is that a problem in the file?

**Comment by uslss** [comment] 2020-07-08 18:07
closed as duplicate of #8069

**Closed by uslss** 2020-07-08 18:07 UTC
Labels: feature request
