### ISSUE TITLE
Error while direct editing content of text and varchar column

### ISSUE THREAD

**Issue by Lantok** [dbeaver/dbeaver#10170] opened 2020-10-26 11:30 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 (2004)
- DBeaver version: 7.2.3
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 11
- Driver name: PostgreSQL (jdbc postgresql)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
When inserting or updating a text or varchar column in the direct edit of the data panel of a table, always getting the error: "Object parameter [[NULL]] binding not supported" (if inserting null value) or
"Object parameter [[foobar]] binding not supported" (if inserting 'foobar' value).

#### Steps to reproduce, if exist:
Simply direct edit (both update or insert) of a text or varchar column of a table.

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2020-10-26 12:26:35.571
!MESSAGE Object parameter [[NULL]] binding not supported
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-10-26 12:26:35.571
!MESSAGE Object parameter [[NULL]] binding not supported
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Object parameter [[NULL]] binding not supported
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.bindValueObject(DefaultValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$2.bindStatement(JDBCTable.java:466)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:160)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:804)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:690)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:689)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:627)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2020-10-26 12:26:39.390
!MESSAGE Object parameter [foobar] binding not supported
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-10-26 12:26:39.390
!MESSAGE Object parameter [foobar] binding not supported
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Object parameter [foobar] binding not supported
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.bindValueObject(DefaultValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$2.bindStatement(JDBCTable.java:466)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:160)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:804)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:690)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:689)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:627)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by kseniiaguzeeva** [comment] 2020-10-26 15:00
It should be fixed in 7.2.4 release. While you can try EA version https://dbeaver.io/files/ea/

**Comment by KenLauritzen** [comment] 2020-10-26 15:02
unsubscribe

**Comment by kseniiaguzeeva** [comment] 2020-10-27 07:23
Do I understand right that the issue is fixed in EA verdion and the ticket can be closed?

**Comment by uslss** [comment] 2020-11-17 08:58
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.

**Closed by uslss** 2020-11-17 08:58 UTC
Labels: bug, can't reproduce, wait for response
