### ISSUE TITLE
Show statistics panel for single query

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#20416] opened 2023-06-28 15:35 UTC
### Description

Prior to 23.1.1 dBeaver would always show a statistics panel with the results of the run query, elapsed time, etc.
In the latest version it is missing.
Not only doesn't it appear with the results, there doesn't appear to be a listing in any of the context menus nor in the window manager.

How do I get this panel back?
thanks.

### DBeaver Version

Community Edition 23.1.1

### Operating System

Windows 10

### Database and driver

Problem apparent across both Oracle and PostgreSQL drivers.

### Steps to reproduce

1. connect to database
2. run query
3. marvel at the now missing statistics panel.

**Comment by E1izabeth** [comment] 2023-06-28 15:39
Does this setting is turned on for you?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/224058e4-3690-4082-906f-e89b9dd9a582)

**Comment by coleman-rik** [comment] 2023-06-28 15:56
@E1izabeth ,

Yes.
![dbeaver_23 1 1_prefs_20230628_114940](https://github.com/dbeaver/dbeaver/assets/3697063/4a6b3729-6874-4541-9d4a-98fecf70a509)

But, I am not running **multiple queries**, it used to show up all of the time, now it isn't showing up at all.
Here's an example:
![dbeaver_sample_query_missing_stats_20230628_115253](https://github.com/dbeaver/dbeaver/assets/3697063/c5775ba2-9b86-4fbc-a5ee-54e3bc42c68c)

Here's a trivial **multiple queries** example where it does show up.
![dbeaver_sample_query_multiple_with_stats_20230628_115253](https://github.com/dbeaver/dbeaver/assets/3697063/5d0c3f4f-dc7a-4ec5-afa4-78c6e2df32e5)

How do I get the behavior back to **always** showing that panel?

thanks.

**Comment by E1izabeth** [comment] 2023-06-28 16:01
Does it work for you in the previous DBeaver version (23.1.0)?

**Comment by coleman-rik** [comment] 2023-06-28 16:04
yes.

In all versions prior to the current one, the statistics panel was **always** displayed after  running anything in the query window.

**Comment by E1izabeth** [comment] 2023-06-28 16:08
How exactly are you executing the query? What shortcut or button do you use?

**Comment by coleman-rik** [comment] 2023-06-28 16:26
It doesn't matter.
I get the same results if I choose any of the first three icons in the upper left of the query editor window

- Execute SQL Query 
- Execute SQL in new tab
- Execute SQL script

**Comment by E1izabeth** [comment] 2023-06-29 12:56
Does Statics tab showed up on select query on the older DBeaver versions for you? I can't reproduce it on 23.1.0 and earlier DBeaver versions.

**Comment by coleman-rik** [comment] 2023-06-29 13:23
yes

**Comment by Matvey16** [comment] 2023-07-06 13:01
@coleman-rik For now it works as expected. We don't have an option to show statistics for a single query and right now it is intended to not show it. But we can see if it is a needed feature.

**Comment by coleman-rik** [comment] 2023-07-12 13:10
that seems odd, as it used to do so.

at the moment it is no longer even returning statistics for multiple queries, unless I run it with "Execute SQL script"

if I run multiple queries  with "Execute SQL query" or "Execute SQL query in new tab" the statistics panel no longer appears.

ex:
```
select * from schema.table1;
select * from schema.table2;
```
or even:
```
select now();
select * from schema.table1;
```
selecting both queries will cause dbeaver to run both queries and return results for both queries.

as far as the statistics panel showing up, either one will behave as follows:
- "Execute SQL query"                      -> no statistics panel
- "Execute SQL query in new tab"   -> no statistics panel
- "Execute SQL script"                       -> **statistics panel**



I don't know why it was decided to change the functionality.

it would be helpful if you could return that functionality.

thanks.

**Comment by coleman-rik** [comment] 2023-07-13 18:49
This functionality disappearing coincided with these release notes:
![dbeaver_release_notes_20230713_144639](https://github.com/dbeaver/dbeaver/assets/3697063/00a7ca5c-0e82-43a6-ae04-1179a933d03f)
https://dbeaver.io/2023/06/26/dbeaver-23-1-1/

**Comment by paul-eeoc** [comment] 2023-08-10 13:22
It's back. The statistics tab would periodically spontaneously load after I run a single query. Version 23.1.4.202308061552 (August 7, 2023).  See issue #7704

**Comment by coleman-rik** [comment] 2023-08-21 13:23
Rifting off of #7704, I am guessing addressing that was what lead us to where we are today.  Here are a couple thoughts.

It seems like there are those who don't want the statistics tab, and others, like myself, who always want the statistics tab.
The proposed solution seems to be to remove the statistics tab and then give users the option to only show it when multiple queries are run.
Unfortunately, it seems that even that attempt doesn't work correctly.

Personally, I think there a couple of avenues that can be explored.

1.  switch the option from the current "Show statistics for multiple queries with results" to something like;
    - never show statistics panel
    - always show statistics panel
    - only show statistics panel when running multiple queries
2. don't force the statistics panel to have focus.
The bigger pain point I am reading here doesn't appear to be the statistics panel, but the fact the dBeaver forces it to have focus whenever a script is run. This goes along with another bug that is the output panel randomly disappearing and reappearing, often forcing a Ctrl+Shift+O to display it.

Users should have more options. In this case that being which panel to receive focus when a query finishes running.

- statistics panel
- output panel
- 1st results panel

Ideally there should be an order of operations, in the event that any particular script doesn't generate an output or any results.
Something like:

Query completion panel order:
( ) - 1st results panel
( ) - output panel
( ) - statistics panel

and the user could specify the order they want them in with the first applicable panel having focus.

ex:

Query completion panel order:
( 2 ) - 1st results panel
( 1 ) - output panel
( 3 ) - statistics panel

with the understanding that if a particular query isn't applicable, either for example because there aren't any results, or because the user has indicated that they don't want to ever see statistics, that it would fall through to the next highest numbered choice.

Of course, it should go without saying that any such options will need to work consistently and reliably.

I hope that helps,

**Comment by paul-eeoc** [comment] 2023-08-21 16:44
Here is the thing:
I am running only a single query like this:
SELECT * FROM shared_code;

And I get no statistics tab.

However, if I have a comment after it like this:
SELECT * FROM shared_code;
--order by 1

Then I get the statistics tab. This is a bug.  I am using Version 23.1.5.202308201919 (August 21, 203)

**Comment by coleman-rik** [comment] 2023-08-22 13:29
@paul-eeoc I can't say for sure, but perhaps it's mistakenly interpreting the second commented line as another query, and if you have show statistics for multiple queries, that might be enough to trigger it.  But I'm just guessing.

personally I **want** the statistics tab to show up, all of the time, even for single queries, but the devs took that away from me.

I think there needs to be settings for none, always, multiple, and perhaps just single to complete the set.
I also think that the default focus is more vexing for most people than the fact that a panel is displayed.  The current **always make the statistics panel have focus**, can be annoying.  So much so that I think people are misplacing their angst. If they can't get some other panel to have focus; output, results, then just get rid of the statistics panel.

of course, whatever solution has to actually work, and work consistantly.

here's to hoping they get it right in the next go round.

**Comment by paul-eeoc** [comment] 2023-08-22 13:57
@coleman-rik I complete agree with all of your points. Hopefully they would implement the none, always, single and multiple (four choices) with an option for statistics to have focus or not.

**Comment by btanner2** [comment] 2023-08-22 14:41
The new behavior introduced with Version 3.1.1 (Data Editor: Statistics view now can be disabled) is super annoying. Dbeaver is not usable anymore for me. I always need to combine multiple queries and I never ever want to see the statistics view. Unfortunately, Dbeaver keeps penetrating me with that information. I need to get rid of this view. I really love Dbeaver, it is an amazing tool, but forcing the user to see this view if they are using multiple queries is definitely the wrong way to go.

Please make an option to disable this view completely and forever.

Thanks a lot
Brian

**Comment by coleman-rik** [comment] 2023-08-22 16:24
at the end of the day it's all about **user choice**

some users want the statistics panel, 
some users don't
some users only want it in certain cases
and **most** users want to be able to determine _which panel_ gets the focus when something finishes running....

let's hope the devs can deliver, and deliver consistently.

**Comment by btanner2** [comment] 2023-08-23 12:54
> and **most** users want to be able to determine _which panel_ gets the focus when something finishes running....

100% agree with that.

How can we get the developer involved here? This issue is still marked as feature request. But in #7704 it is more or less the same topic, it is marked as a bug, but closed.

**Comment by E1izabeth** [comment] 2023-08-23 13:06
You can vote for the issue with 👍 under the issue description to promote it to a higher priority.
This issue is about showing statistics panel for a single query execution. Our team sure that it never worked this way intentionally. Maybe it was a bug that it worked this way for you, but we were unable to reproduce this behaviour even on the earlier versions. So, it's marked as feature request.

P.S. we're here and we're watching 👀

**Comment by manguicho** [comment] 2023-10-06 18:13
super annoying

**Closed as completed** 2023-10-15 12:47 UTC
Labels: sp:3, wait for votes, xf:sql execution
