### ISSUE TITLE
comments no longer recognized since community version 22.0.1

### ISSUE THREAD

**Issue by james49** [dbeaver/dbeaver#16241] opened 2022-04-19 13:41 UTC
#### System information: 
- Windows 10
- DBeaver version 22.0.2 & 22.0.3
- Java version 8

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Dbeaver versions <= 22.0.1 ignore the commented lines of this statement.  But not in versions > 22.01.   I thought 22.0.3 would have fixed it;  But I've had to revert back to 22.0.1 because it is still a problem.

![image](https://user-images.githubusercontent.com/1851797/164016593-76116af0-f87d-4030-8f5f-e217d80f73d2.png)

**Comment by E1izabeth** [comment] 2022-04-19 13:50
Hi, @james49! Thank you for bug report! The problem is in the `;` at the end of query and connected to this issue https://github.com/dbeaver/dbeaver/issues/16077. As a workaround you can try this https://github.com/dbeaver/dbeaver/issues/16077#issuecomment-1099991921.

But anyway it will be fixed in 22.0.4 with https://github.com/dbeaver/dbeaver/pull/16218. So, I'll close this issue. 

If you encounter the same problem after upgrading to 22.0.4, please, reopen this issue.

**Closed as completed by E1izabeth** 2022-04-19 13:50 UTC
Labels: duplicate

**Comment by james49** [comment] 2022-04-19 14:29
@E1izabeth Thank you for the update!  I tried to look for any open issue that was similar, but nothing looked relevant at the time.
