### ISSUE TITLE
SQL Error [10713] [S1000]: The MERGE statement must end with a semicolon (;).

### ISSUE THREAD

**Issue by wjtien** [dbeaver/dbeaver#7277] opened 2019-11-22 06:46 UTC
db: sqlserver2012
os: ubuntu18.04
dbeaver: dbeaver-ce-6.2.5-linux.gtk.x86_64.tar.gz
SQL Error [10713] [S1000]: The MERGE statement must end with a semicolon (;).

dbeaver:dbeaver-ce-6.2.0-linux.gtk.x86_64.tar.gz  working fine

merge into  table a
using (select 1 id) b
on (a.id=b.id)
when not matched by target then
	insert (xxxxx)
	values (xxxxx)
;

**Comment by jetzerb** [comment] 2019-11-22 14:15
I ran across this same thing a few days ago.  See issue #1482, especially my [comment at the bottom](https://github.com/dbeaver/dbeaver/issues/1482#issuecomment-555557327) which explains how to configure DBeaver preferences to work around it.

**Comment by uslss** [comment] 2020-05-12 10:43
closed as duplicate of #1482

**Closed by uslss** 2020-05-12 10:43 UTC
Labels: bug
