### ISSUE TITLE
Flashing disconnect countdown 

### ISSUE THREAD

**Issue by alchemistmatt** [dbeaver/dbeaver#29329] opened 2024-05-04 01:15 UTC
### Description

When the DBeaver window is visible, but behind another application's window, after 60 seconds has elapsed, a warning message starts flashing rapidly at the bottom of the DBeaver window, showing a countdown timer for when the current tab's connection will be closed, for example `Disconnect in 3h 58m 46s`.  The attached screenshots show the message counting down while Excel is in the foreground. Note that one screenshot at 5:33 pm shows that the message has disappeared briefly. Switching back to DBeaver, the message disappears.

The only workaround (and it's obviously easy) is to minimize the DBeaver window (or rearrange windows so that the message is not visible).  I believe this behavior started sometime in March 2024, but it could have appeared one or two months earlier. I have also observed the behavior with Chrome as the front-most window, as shown in the last screenshot.

![DBeaver_Disconnect_Warning1](https://github.com/dbeaver/dbeaver/assets/6363449/33ffb17e-c002-4735-a8a1-d31fe962badc)
![DBeaver_Disconnect_Warning2](https://github.com/dbeaver/dbeaver/assets/6363449/25be1331-e0c7-47b7-9582-8cff77553c38)
![DBeaver_Disconnect_Warning3](https://github.com/dbeaver/dbeaver/assets/6363449/59cd6602-3c23-4039-b345-9647a2ae6db1)
![DBeaver_Disconnect_Warning4](https://github.com/dbeaver/dbeaver/assets/6363449/e8477cb5-6d23-4ca6-a62c-38064e5592a6)
![DBeaver_Disconnect_Warning5](https://github.com/dbeaver/dbeaver/assets/6363449/e4030bc0-c647-4e1e-9442-e984926394de)
![DBeaver_Disconnect_Warning6](https://github.com/dbeaver/dbeaver/assets/6363449/784e2ed1-ee5c-4dc0-9ab1-fe123f9a250e)
![DBeaver_Disconnect_Warning7](https://github.com/dbeaver/dbeaver/assets/6363449/e7cfc4e3-0a1d-4d96-bfdd-a7f8940f5ee1)

### DBeaver Version

Community Edition 24.0.3

### Operating System

Windows 10 Enterprise

### Database and driver

PostgreSQL 16.1, PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

1. Connect to the database and run a query
2. Switch to another window
3. Wait one minute
4. The countdown message appears, but flashes at random intervals, often several times per second

**Comment by E1izabeth** [comment] 2024-05-05 11:32
Thank you for bug report. It's a duplicate of #22795
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-05-05 11:32 UTC
Labels: duplicate, xf:ui
