### ISSUE TITLE
DBeaver old version can't install git support plugins

### ISSUE THREAD

**Issue by greenpean** [dbeaver/dbeaver#36052] opened 2024-10-24 03:22 UTC
### Description

DBeaver 24.0.0, when the plugin git support installtion is complete from https://dbeaver.io/update/git/latest/, but the share project still can't working.

### DBeaver Version

24.0.0

### Operating System

Windows11

### Steps to reproduce

1.Help->Install New Software->
2.Choose Git support
3.When the installation is complete and restart dbeaver,the Team->Share Project can't working.
![image](https://github.com/user-attachments/assets/dbf59fc3-5d31-436d-9574-d53efea4d3a5)
![image](https://github.com/user-attachments/assets/bebf4fe3-8e69-4ad5-8267-ea9b39ddbccd)

**Comment by E1izabeth** [comment] 2024-10-24 05:20
Thanks for the bug report.
It's a known issue. I'm closing I as a duplicate of #35359

**Closed as not planned** 2024-10-24 05:20 UTC
Labels: duplicate
