### ISSUE TITLE
After Reconnecting Redshift Connection Tab Becomes Readonly

### ISSUE THREAD

**Issue by nickheidke** [dbeaver/dbeaver#10690] opened 2020-12-14 19:56 UTC
#### System information: 
- Operating system (distribution) and version: Windows DBeaver Enterprise
- DBeaver version: 7.3.0.202012061950
- Additional extensions: None

#### Connection specification:
- Database name and version: Redshift
- Driver name: Redshift com.amazon.redshift.jdbc42.driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

After a period of inactivity, my connection to Redshift disconnects. While this isn't a problem, when I reconnect a particular script tab, it's defaulting to read-only, despite the connection not being set to read-only. To remedy, I have to open a new script tab and connection, and execute any DML/DDL there instead of the script I have open currently.

**Comment by kseniiaguzeeva** [comment] 2020-12-21 13:24
Unfortunatelly I cannot reproduce it. 
What do you mean when write read-only? Is it impossible to edit ResultSet? Does read-only label appear?
![dbeaver_Cv3hgguf78](https://user-images.githubusercontent.com/51405061/102781553-eaee8900-43a8-11eb-88b0-4e2a84ec2898.png)

Is it possible to send a screenshot or gif?

**Comment by nickheidke** [comment] 2020-12-29 02:59
In this screenshot, I'm attempting to create a materialized view. This is after Invalidating/Reconnecting my connection to Amazon Redshift. 
![image](https://user-images.githubusercontent.com/4443011/103255605-88206300-494f-11eb-92d4-b4147a7a1164.png)

**Comment by uslss** [comment] 2021-02-04 16:16
probably fixed with #11110

**Closed by uslss** 2021-02-04 16:16 UTC
Labels: bug, can't reproduce, environment, x:redshift
