### ISSUE TITLE
DBeaver quits after trying to view a geometry

### ISSUE THREAD

**Issue by kubi-yavuz** [dbeaver/dbeaver#18865] opened 2023-01-24 18:24 UTC
### Description

DBeaver unexpectedly quits without an error after i try to browse a geometry on a map. This started to happen after i updated to Ventura. I have an Intel Macbook. It doesn't depend on the version of DBeaver, i have tried the last 4 versions, no luck. 

here is the translated report from MacBook itself. 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               dbeaver [35359]
Path:                  /Applications/DBeaver.app/Contents/MacOS/dbeaver
Identifier:            org.jkiss.dbeaver.core.product
Version:               22.3.3 (22.3.3)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-01-24 18:16:18.7993 +0000
OS Version:            macOS 13.1 (22C65)
Report Version:        12
Bridge OS Version:     7.1 (20P2059)

Time Awake Since Boot: 450000 seconds
Time Since Wake:       18868 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [35359]
`

### DBeaver Version

Version 22.3.3.202301211053

### Operating System

macOS Ventura 13.1

### Database and driver

PostgreSQL

### Steps to reproduce

1. Query a table with geometry
2. Try to visualize the geometry
3. DBeaver quits without giving an error

**Comment by Destrolaric** [comment] 2023-01-24 18:55
Duplicate of https://github.com/dbeaver/dbeaver/issues/18117. Will be fixed with the release of new WebKit version

**Closed as not planned by Destrolaric** 2023-01-24 18:55 UTC
Labels: duplicate
