### ISSUE TITLE
UI schema privileges tab overlapping columns catalogs and tables cannot be adjusted

### ISSUE THREAD

**Issue by aavileli** [dbeaver/dbeaver#16868] opened 2022-06-23 11:59 UTC
#### System information: 
- Operating system (distribution) and version
fedora silverblue 36 
- DBeaver version
version 22.1.0 flatpak

UI schema privileges tab overlapping columns `catalogs` and `tables` cannot be adjusted
![image](https://user-images.githubusercontent.com/9123144/175293933-f9c37eda-c686-4024-b41d-693da904d454.png)

**Comment by LonwoLonwo** [comment] 2022-06-23 12:08
Thanks for the report @aavileli

**Comment by ShadelessFox** [comment] 2022-06-23 13:54
Hello @aavileli

Duplicate of #15516, please track the issue there

**Closed as not planned by ShadelessFox** 2022-06-23 13:54 UTC
Labels: x:mysql, duplicate, xf:ui
