### ISSUE TITLE
Intellisense not working with INFORMATION_SCHEMA

### ISSUE THREAD

**Issue by aviennas** [dbeaver/dbeaver#35497] opened 2024-09-06 10:45 UTC
### Description

Dear All. Having setup a connection to local MySQL database using root credentials, and while user databases are fully accessible, queries involving INFORMATION_SCHEMA succeed however the intellisense is not working.

![dbeaver2](https://github.com/user-attachments/assets/35508701-5390-4c3b-a577-2597c4ed1e87)
![dbeaver1](https://github.com/user-attachments/assets/fc13cdb2-3d8c-4d29-9567-a067618278a0)

### DBeaver Version

Community Edition 24.1.5

### Operating System

Windows 11

### Database and driver

Using MySQL 8.2 with MySQL Connector 8.2

### Steps to reproduce

1. setup connection
2. open connection 
3. create an sql script file
4. hard type a query involving INFORMATION_SCHEMA and verify results are returned
5. try to resolve INFORMATION_SCHEMA with intellisense

**Comment by ask9** [comment] 2024-09-08 08:47
Seems like this is a full duplicate of this one: #35338
And maybe related to this one: #35430

**Comment by E1izabeth** [comment] 2024-09-12 11:41
Thank you for report

**Comment by E1izabeth** [comment] 2024-11-25 12:56
The issue is solved 
![image](https://github.com/user-attachments/assets/149f1527-8dd8-421d-992a-e97cfb4196b0)

**Closed as completed by E1izabeth** 2024-11-25 12:56 UTC
Labels: xp:normal, xf:sql editor
