### ISSUE TITLE
Run SQL Statements and scripts with Oracle SQL Plus native client

### ISSUE THREAD

**Issue by alligator999** [dbeaver/dbeaver#18921] opened 2023-02-01 13:01 UTC
**Is your feature request related to a problem? Please describe.**
For Oracle databases, there is no option to run statements and scripts with SQL Plus. Basically the functionality would be the same as with Oracle SQL Developer.

![image](https://user-images.githubusercontent.com/35902744/216049202-c7f526dd-ac89-4650-90a3-2951beb63d15.png)

**Describe the solution you'd like**
Option to run statements and scripts with Oracle SQL Plus native client

**Describe alternatives you've considered**
I can run SQL file with option in connections but this is not an alternative to the above solution.

![image](https://user-images.githubusercontent.com/35902744/216049877-1c9e566c-fb68-41ce-8a92-66d8d1209ab6.png)

**Comment by E1izabeth** [comment] 2023-02-01 15:10
Thank you for the idea.

**Comment by E1izabeth** [comment] 2023-02-01 15:45
Duplicate of #4896

**Closed as not planned** 2023-02-01 15:45 UTC
Labels: x:oracle, duplicate, xf:sql
