### ISSUE TITLE
Connecting to sql server

### ISSUE THREAD

**Issue by GabrielKNdara** [dbeaver/dbeaver#18293] opened 2022-11-22 05:03 UTC
### Description

Hi guys .

I'm new to Dbeaver and mx linux. I want to connect dbeaver to  mssql server, yet i don't how, please help.
![Screenshot_2022-11-22_06-49-55](https://user-images.githubusercontent.com/52117833/203224824-8466444a-de62-46a3-9373-be70783b4d19.png)

### DBeaver Version

community edition 21.0.5

### Operating System

mx linux 21

### Database and driver

ms sql server

### Steps to reproduce

1. Open dbeaver community.
2. On the toolbar click on database
3. under database click on new database connection
4. Inside the dialog select which state "Select your database"
5. select Microsoft Sql Server
6. SQL Server Connection Settings dialog appears
7. This where i need help how to set up the connection.
8. Thanks in advance

**Comment by LonwoLonwo** [comment] 2022-11-22 09:03
Hello @ProgrammerGabs 

Perhaps you can not use Windows Authentication for your Linux machine.
You can use SQL Server Authentication with the login and password. SQL Server localhost database usually have user 'sa' as default.
And usually, you need to use [SQL Sever configuration manager](https://learn.microsoft.com/en-us/sql/relational-databases/sql-server-configuration-manager?view=sql-server-ver16) to configure your connection settings.

**Comment by JohnMCouch** [comment] 2022-12-08 16:40
Has anyone solved this? We are trying to connect to SQL Server from MAC and it is a domain laptop but fails saying untrusted device. We do not allow users to use SQL authentication to connect.

**Comment by E1izabeth** [comment] 2023-02-16 14:36
Probably it's a duplicate of #9751

**Comment by JohnMCouchAIP** [comment] 2023-02-16 15:21
It is. And I figured it out based on other peoples posts which also look similar.

**Comment by GabrielKNdara** [comment] 2023-02-16 15:30
It's not solved, if you found a solution please share

**Comment by JohnMCouchAIP** [comment] 2023-02-16 16:21
You have to use NTLM for authentication. My instructions include setting application Intent as we use AOAG and the developers connect to secondary's for queries.

**Comment by E1izabeth** [comment] 2023-03-16 14:36
Maybe some comments here #3320 might help you.

**Closed as completed** 2023-03-16 14:36 UTC
Labels: x:mssql, wait for response, question
