### ISSUE TITLE
Choosing a different schema works but is not displayed properly

### ISSUE THREAD

**Issue by Softsuit** [dbeaver/dbeaver#13019] opened 2021-06-28 16:09 UTC
#### System information: 
CentOS linux server (private)

#### Connection specification:
Database:  PostgreSQL 9.3.9 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11), 64-bit
DBeaver 21.1.1.20210610824
straight network connection to server in the cloud (private server)

#### Describe the problem you're observing:
I have a database server with several databases on.  I choose between them by means of clicking on the active catalog/schema combobox.  There I can choose the one I want.  But the content of the combobox does not reflect my selection.  Although, when I do a simple select I know I am in the selected database.  Very dangerous !

**Comment by Softsuit** [comment] 2021-06-28 16:15
![image](https://user-images.githubusercontent.com/69981590/123669791-c33b1a80-d83c-11eb-8805-9329fa077ece.png)

**Comment by uslss** [comment] 2021-06-29 07:54
@Softsuit please provide a video with the issue

**Comment by Softsuit** [comment] 2021-06-29 08:08
I'm a C/C++ developer and PostgreSQL specialist.  So forgive me that I do not have the capabilities to do video editing.  I can only tell you this is a severe bug for you are flying blind.   Selecting a catalog + schema works, but on top in the combobox it still reflects the previous selection.  I noticed this because on that server I have two databases or catalogs that have different tables.  And it is definitely a bug that was introduced with the latest update.

**Comment by p91paul** [comment] 2021-06-29 18:59
@Softsuit google for "screencast software" or "screen recording software", they are pretty easy to use, usually you just need you to hit play, do what you have to, then hit stop, and they will make a video of your screen. I would have recommended something, but if I understand correctly you are on RedHat 4 which is pretty ancient, so I don't know what will work. Maybe you'll just find something in your distribution's repositories.

**Comment by Softsuit** [comment] 2021-06-29 22:49
I don't know where you get Redhat4.  Actually it's CentOS 7.7 that runs a PostgreSQL 9.3.9.  But that is imho totally irrelevant.  I described the bug, which is a GUI related thing.  You choose a different database and in the previous version, your choice would be shown in the combobox on top.  But now it isn't.  It stays on the old selection.  So you think you're working on a different database schema.  Potentially dangerous when you have lots of databases with several schemas each.  Now I can start recording and doing all lots of stuff, but I find that overkill for this small an issue.  Now if anyone here would have said in this discussion, man I can't reproduce this, please give us more information then I would have understood a video would give evidence that it actually seem to occur on a pc and give us a clue to look to windows version, Java virtual machine and so on.  Im running DBeaver on a Win10 pro 64bits 2004 19041.1052 with experience pack 120.2212.2020.0  Java 8 Update 291 64bits

**Comment by p91paul** [comment] 2021-06-30 11:53
@Softsuit it's written in your original post, but I suppose it's the kernel version. Your operating system is mainly relevant to guide you into recording your screen, since DBeaver maintainer asked you for a video to help reproduce the issue and you claimed to be unable to record it. With CentOS 7 you might use gnome 3 builtin screen recording feature https://opensource.com/article/19/8/record-screencasts-gnome3. For windows I use screen2gif, that can also produce the video as a gif image.

**Comment by Softsuit** [comment] 2021-06-30 13:45
Ok I tried screen2gif, it produced a gif file of 1.6MB, tried to drop it here in this box but error:  Something went eally wrong, and we can't process that fiel.  Try again  = what I get

**Comment by FernandoTBarros** [comment] 2021-07-01 22:18
I'm having the same problem. Windows 10 x64 DBeaver CE version Version 21.1.1.202106210824
And while recording the video to demonstrate the error I noted that this only happens when I'm moving to the public schema. 

https://user-images.githubusercontent.com/3437672/124195544-0f869480-daa1-11eb-8b8c-8e4123d6db63.mp4

**Comment by LonwoLonwo** [comment] 2021-08-24 14:15
Fixed case with database and schema-changing to another database and non-public schema (changed always to the public earlier).

**Comment by Matvey16** [comment] 2021-08-25 08:52
Verified

**Closed as completed by Matvey16** 2021-08-25 08:52 UTC
Labels: x:postgresql, sp:2
