### ISSUE TITLE
Feature request - Keep current procedure line in focus after saving procedure in Postgres

### ISSUE THREAD

**Issue by roparo** [dbeaver/dbeaver#3362] opened 2018-04-19 09:04 UTC
Hello,

DBeaver focuses at the beginning of a procedure code, loosing current editing line focus.

This happens when using DBeaver non maximized (i.e.: half of display height) on Windows 
and editing and saving a procedure in Postgres which is longer than current DBeaver display height.

Thank you.

**Comment by serge-rider** [comment] 2018-04-20 18:12
Good point

**Comment by serge-rider** [comment] 2018-04-20 18:27
Please test in 5.0.4

**Comment by roparo** [comment] 2018-05-02 07:11
Tested today in 5.0.4

The problem is not fixed, same behavior was observed.

Thanks.

**Comment by serge-rider** [comment] 2018-05-02 15:12
Can't reproduce.

What is your OS?
Could you make some screenshots/short video?

**Comment by serge-rider** [comment] 2018-05-14 14:52
Well, I see this.
The strange part is that I still can't reproduce this on our test machines (Windows 10 and Mac OS).
Perhaps we need Windows 7..

Could you update to the most recent version to be 100% sure that this wasn't fixed there.

**Comment by roparo** [comment] 2018-05-15 08:39
Hello,


I've just installed the latest DBeaver 5.0.5 version an I've got the same
issue.

As an observation, it doesn't matter if is Postgres or Oracle, it is the
same .

Thanks.

**Comment by brkerez** [comment] 2018-05-24 11:14
Same here with DBeaver 5.0.5. I'm forced to use Windows 7 and focus is on the first line of package after each save. 
os: Windows 7 (I can't switch to win10)
db: Oracle 12c 12.1.0.2.0

**Comment by Speirs47** [comment] 2018-08-30 06:48
Same on Linux in MySQL/MariaDb

**Comment by serge-rider** [comment] 2018-08-30 14:18
Will be fixed in the next version. 
Procedure editor won't be refreshed for existing objects.

**Comment by serge-rider** [comment] 2018-08-30 14:18
Please reopen if this issue will happen again. Attach gif video if possible.

**Closed by serge-rider** 2018-08-30 14:18 UTC
Labels: enhancement, xo:windows
