### ISSUE TITLE
Different column is exported to CSV

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12676] opened 2021-05-31 19:40 UTC
How to reproduce:
when result have columns with same name and I select second column, but first column is exported into CSV

**Comment by uslss** [comment] 2021-06-01 07:38
cannot reproduce an issue.
what database and dbeaver version do you use?
could you provide a video with the issue?

**Comment by KES777** [comment] 2021-06-01 13:29
`select 1 as first, 2 as first, 3 as first`

After run your query by rightclicking column select first and third column
export to CSV

at csv you will get `1` and `2` value, instead of expected `1` and `3`

Version is 21.0.3, PostgresDB

**Comment by KES777** [comment] 2021-06-01 13:31
Here I select only two, but three columns =)

This is a bit different issue, but root of the problem is same: columns with similar names
![image](https://user-images.githubusercontent.com/799021/120331682-b4714e80-c2f6-11eb-9094-f464f7240cb1.png)

**Comment by uslss** [comment] 2021-06-07 11:30
thanks for the report and clarification

**Comment by LonwoLonwo** [comment] 2021-08-20 09:51
Export with enabled setting "Selected columns only" and columns with equals names fixed in DBeaver 21.2.0 .

**Comment by Matvey16** [comment] 2021-08-23 08:55
Verified
Need to fix another issue with same-named columns #13622

**Closed as completed by Matvey16** 2021-08-23 08:55 UTC
Labels: xf:datatransfer, sp:2
