### ISSUE TITLE
Enhance Search Module PLZ!

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#11460] opened 2021-02-24 02:32 UTC
**Is your feature request related to a problem? Please describe.**
The current search function cannot find codes in the database, etc.
**Describe the solution you'd like**
Refer to oracle sql developer 'Find database objects'
![image](https://user-images.githubusercontent.com/24444492/108938644-6e6b7580-768b-11eb-82ff-00ca416f8cf3.png)

**Describe alternatives you've considered**
...
**Additional context**
...

**Comment by uslss** [comment] 2021-03-11 08:30
thanks for the suggestion.

Closed as duplicate of #2443

**Closed as completed by uslss** 2021-03-11 08:30 UTC
Labels: duplicate
