### ISSUE TITLE
SQL template delete to enter hotkeys

### ISSUE THREAD

**Issue by lookpaw** [dbeaver/dbeaver#16951] opened 2022-07-02 08:21 UTC
Now, the SQL template needs to enter hotkeys. For example, press the hotkey and SF, and then display "select*from".

I want to input short text, then display the description SQL, delete the input hotkey to speed up, press SF and then display "select * from".

**Comment by E1izabeth** [comment] 2023-07-28 06:58
It's a duplicate of #11553, so I'm closing it.

**Closed as not planned by E1izabeth** 2023-07-28 06:58 UTC
Labels: duplicate, xf:sql
