### ISSUE TITLE
Spatial GIS viewer prompts to save HTML and does not render inside dbeaver

### ISSUE THREAD

**Issue by mblackgeo** [dbeaver/dbeaver#17477] opened 2022-08-26 08:30 UTC
### Description

Whenever viewing a geometry column, the spatial viewer does not render inside dbeaver just prompts the file manager to save a temporary HTML file only. The spatial viewer window within dbeaver stays blank, no matter what options are selected. The geberated HTML file contains HTML/JS including leaflet, and pressing the "open in browser" button at the bottom of the spatial viewer window then opens the browser with the geometry and openstreetmap tiles correctly rendered

### DBeaver Version

Community Version 22.1.5.202208211008 (installed from deb)

### Operating System

Pop! OS 22.04 LTS (jammy)

### Database and driver

MySQL v5.7.22
MySQL connector v8.0.17

### Steps to reproduce

1. Connect to database
2. Select from a table containing geometry
3. Click on a geometry column
4. Open the spatial view
5. It prompts to save a HTML file instead of rendering inside dbeaver

### Additional context

I've tried downgrading to v21.0.0, v20.0.0 and v7.3.5 and I have the same issue with every version, thus I think it could be something OS related or some misconfiguration.

**Comment by Destrolaric** [comment] 2022-08-26 09:01
Hi, a duplicate of https://github.com/dbeaver/dbeaver/issues/16125. A workaround for this issue can be found there.

**Closed as completed by Destrolaric** 2022-08-26 09:01 UTC
Labels: duplicate, xo:linux, xf:gis

**Comment by mblackgeo** [comment] 2022-08-26 09:09
Many thanks, that has fixed the issue. I'll try and do a better job of searching the closed issues next time, cheers :+1:
