### ISSUE TITLE
DBeaver does not honor modifier keys on MacOS

### ISSUE THREAD

**Issue by mmedic** [dbeaver/dbeaver#3860] opened 2018-07-27 14:06 UTC
For MacOS, it appears if you have set custom modifier keys (i.e. swapped Command and Control keys on the keyboard to more closely resemble windows keyboard layout), DBeaver does not honor that arrangement.

**Comment by LonwoLonwo** [comment] 2022-04-12 15:20
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/5931

**Closed by LonwoLonwo** 2022-04-12 15:20 UTC
Labels: bug, xo:macos
