### ISSUE TITLE
Pasting password copied from Password Manager with CTRL-V pastes it in the script window, not in password field

### ISSUE THREAD

**Issue by dstj** [dbeaver/dbeaver#22748] opened 2024-02-07 15:49 UTC
### Description

Hi,

After upgrading to v23.3.4.202402041841, when I try pasting a password with CTRL-V that was copied from my Password Manager (i.e. KeePass), the password is pasted in the **script window** instead of in the password field. (see attached video).

Note 1: , right-click and pasting with the mouse seems to always work, but that is really annoying ;)

Note 2: When copying a string from Notepad, CTRL-V works.

![DbBeaver Password Pasting Bug2](https://github.com/dbeaver/dbeaver/assets/467692/69fd6541-4352-4b70-b79a-ea4345b554e8)

Removing this "Drop to background after copying data to the clipboard" option in KeePass seems to solve it, but it's also really annoying.

![image](https://github.com/dbeaver/dbeaver/assets/467692/7769e31c-729a-489b-9a6d-59e748a4c948)

### DBeaver Version

Community Edition v23.3.4.202402041841

### Operating System

Microsoft Windows 11 Pro 10.0.22631 Build 22631

### Database and driver

Postgresql, but I don't think it's important here as the connection is not even opened yet...

### Steps to reproduce

(See video)
1. Open script
2. Copy password from KeePass
3. KeePass drops to background automatically on copied password.
4. DbBeaver password field has focus (normally)
5. CTRL-V

**Comment by ShadelessFox** [comment] 2024-02-08 12:51
Hello @dstj,

What version of DBeaver did you upgrade from? Was the described issue occurring before?

What is the configuration of your password manager that automatically makes it appear when typing passwords?

**Comment by dstj** [comment] 2024-02-08 14:22
@ShadelessFox 
1. Upgrading from the previous version (2023.3.3....) via Chocolatey. It just started. It's annoying as hell, so I would have noticed. ;)

2. Just using KeePass's global hotkey CTRL+ALT+K to make it appear.

**Comment by tbigby-kristin** [comment] 2024-02-09 04:56
Just to add that my issue #22766 might be related to this issue, or it might not.

In KeePassXC, for my Auto-Type of the password into the authentication popup window, I noticed that the Window Title is missing from 23.3.4, replaced by the Description in the middle of the popup. KeePassXC looks for the Window Title in order to determine which password to Auto-Type.

I don't have any knowledge of KeePass to know whether it may be unable to paste the password due to the lack of Window Title on the popup. But both issues started at the same 23.3.4 release.

**Comment by LonwoLonwo** [comment] 2024-02-13 08:25
Hello @dstj 

Please check your issue case in our Early Access version: https://dbeaver.io/files/ea/.
I hope it is already fixed there.

**Comment by dstj** [comment] 2024-02-13 19:14
@LonwoLonwo 
Confirmed, v23.3.5.202402130022 works as before.

**Comment by LonwoLonwo** [comment] 2024-02-14 11:12
Thanks for the answer @dstj !

I'm closing this issue as a duplicate of https://github.com/dbeaver/dbeaver/issues/22766

**Closed as not planned by LonwoLonwo** 2024-02-14 11:12 UTC
Labels: duplicate
