### ISSUE TITLE
Bookmarks in SQL-Editor

### ISSUE THREAD

**Issue by MeboGit** [dbeaver/dbeaver#8560] opened 2020-04-27 09:10 UTC
Hello,

I use to work with large working script with lots of sql-statements within the sql editor. The problem is, when working on different projects I have to search for those areas manually.

For this reason bookmarks would be very helpful:
e.g.;
ctrl+alt+1 - ctrl+alt+9 -> set bookmark
ctrl+1 - ctrl+9 -> jump to bookmark
The bookmarks should be stored corresponding to scriptxy.sql

Also, a shortcut for inserting timestamp into sql script (for documenting):
e.g.:
alt+d -> insert date(today) as in OneNote

That would be really great.

Thanks for you work...

Mebo

**Comment by uslss** [comment] 2020-04-28 13:54
thanks for suggestion

**Comment by Boudyno** [comment] 2020-09-24 13:02
I support such a featue.

**Comment by uslss** [comment] 2021-08-04 08:41
duplicate of #3416

**Closed by uslss** 2021-08-04 08:41 UTC
Labels: duplicate, feature request
