### ISSUE TITLE
table data autoupdate option

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#9737] opened 2020-09-10 11:50 UTC
DBeaver 7.2.0
Case:
1. rename column name in table
![изображение](https://user-images.githubusercontent.com/61137576/92725100-0a771e00-f385-11ea-8837-0de71b41c516.png)

2. save this changes
![изображение](https://user-images.githubusercontent.com/61137576/92725189-2e3a6400-f385-11ea-9ed5-3d5eae1fe6ad.png)
3. open data tab

4. We can see old column name
![изображение](https://user-images.githubusercontent.com/61137576/92725253-4c07c900-f385-11ea-9bd7-64a5b86382b8.png)

We can see the change after manualy refresh this tab. 

it would be nice to have such a setting so that after pressing the save button, an automatic update column name and ather table parameters

**Comment by detkliff** [comment] 2020-09-10 11:52
In table diagram column name refreshed automaticaly
![изображение](https://user-images.githubusercontent.com/61137576/92725767-0b5c7f80-f386-11ea-9935-ffb61ba3a233.png)

**Comment by kseniiaguzeeva** [comment] 2020-09-10 12:22
Thank you for the suggestion. It is similar to https://github.com/dbeaver/dbeaver/issues/9283, https://github.com/dbeaver/dbeaver/issues/6398, https://github.com/dbeaver/dbeaver/issues/6396

**Comment by kseniiaguzeeva** [comment] 2021-02-11 07:56
Closed as duplicate of #6398

**Closed by kseniiaguzeeva** 2021-02-11 07:56 UTC
Labels: feature request
