### ISSUE TITLE
Read-only button is missing in 23.0.1.202303250535

### ISSUE THREAD

**Issue by MunarYesen** [dbeaver/dbeaver#19587] opened 2023-04-03 08:13 UTC
### Description

Read-only button is missing in 23.0.1.202303250535

<img width="669" alt="image" src="https://user-images.githubusercontent.com/118156704/229450075-512b2ebe-d0f0-4dca-b8fb-965d9c31a6f2.png">

in version 23.0.0 which was working fine
<img width="670" alt="image" src="https://user-images.githubusercontent.com/118156704/229453786-095e3289-a0b8-4b38-89fd-4a2e42e8248b.png">

### DBeaver Version

Community Edition 23.0.1.202303250535

### Operating System

macOS Ventura 13.3 (22E252)

### Database and driver

Database connection: mariaDB, mysql
No specific setting for the connector.

### Steps to reproduce

1. Connect to any database using DBeaver 23.0.1
2. Click the read-only button
3. Reopen the app, and there is a chance that the read-only lock button is gone

### Additional context

I am guessing the click event when choosing from none to a specific database connection somehow fails to register. As I am switching from localhost connection to other db, the tool bar context fails to update.

**Comment by E1izabeth** [comment] 2023-04-03 08:39
Thank you for bug report. It's a duplicate of #19495
The fix will be available in the next release.

**Closed as not planned by E1izabeth** 2023-04-03 08:39 UTC
Labels: duplicate
