### ISSUE TITLE
DBeaver creates a ".eclipse/configuration" directory in your profile for each version

### ISSUE THREAD

**Issue by qris** [dbeaver/dbeaver#21574] opened 2023-10-18 15:05 UTC
### Description

DBeaver creates a .eclipse/<version>/configuration directory in your home directory (e.g. `c:\users\chris`). It contains quite a lot of files, a new one is created each time you upgrade DBeaver, and they are never deleted.

![image](https://github.com/dbeaver/dbeaver/assets/754175/91eee796-09de-46b8-8fb3-269b5e9f379e)

Some of them seem pretty egregious, for example there is a PNG splash screen. Why is that part of my configuration anyway?

![image](https://github.com/dbeaver/dbeaver/assets/754175/937ee874-2711-4b27-89ae-b95630922076)

In any case, this causes significant profile bloat over time. shouldn't DBeaver either use the same directory (maybe backing up the old one after an upgrade, keeping only one such backup) or delete old version-stamped directories after a while?

I had 90 MB in old configuration directories (about 15 of them) after using DBeaver for a few years.

### DBeaver Version

Community Version 23.1.4.202308061552

### Operating System

Windows 10

### Database and driver

n/a

### Steps to reproduce

1. Install and run DBeaver
2. Upgrade and run new version
3. Upgrade again and run new version
4. Look in %USERPROFILE%\.eclipse

**Comment by serge-rider** [comment] 2023-10-19 08:56
@qris thank you for the report.
It is a known issue, this happens when you install DBeaver in a write-protected folder (e.g. Program Files). DBeaver needs to extract several artifacts (including native binaries) native binaries during first start. When it is installed in a local user folder then all artifacts are extracted in the same folder where DBeaver was installed.
Otherwise they are extracted in user home `.eclipse` folder (because it is a part of Eclipse platform behavior).

Generally it is better to use different temp files location (e.g. `%APPDATA%\DBeaverData`). But we will need to patch core Eclipse libraries for that.

Workaround: install DBeaver for current user only (the default option).

**Comment by qris** [comment] 2023-10-19 12:14
Thanks, could the installer not extract these into a read-only system-wide directory, shared between all users?

**Comment by E1izabeth** [comment] 2023-11-17 13:21
Looks like a duplicate of #2118

**Closed as completed** 2024-02-13 12:53 UTC
Labels: enhancement, xp:major, sp:3
