### ISSUE TITLE
Snowflake - Not returning confirmation of certain statements after recent upgrade

### ISSUE THREAD

**Issue by mahonetim** [dbeaver/dbeaver#9972] opened 2020-10-05 18:31 UTC
#### System information: 
- Windows 10 Pro 64 bit
- DBeaver version: 7.2.2

#### Connection specification:
-Snowflake 
- Driver name: snowflake-jdbc-3.12.12.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Since the most recent update DBeaver is not returning confirmation on successful DDL commands such as CREATE, or USE.
Before this update it would return that the table was created successfully or the statement was executed successfully.

#### Steps to reproduce, if exist:
sql:

USE SCHEMA DIM;

CREATE OR REPLACE
TABLE dim.test AS
SELECT
	1 AS new_column;

neither statement returns confirmation after running after recent update;

**Comment by uslss** [comment] 2020-10-06 08:16
thanks for the bug report
closed as duplicate of #9936

**Closed by uslss** 2020-10-06 08:16 UTC
Labels: bug
