### ISSUE TITLE
Editor not shown in table Properties panel

### ISSUE THREAD

**Issue by zazy** [dbeaver/dbeaver#6663] opened 2019-08-31 15:23 UTC
#### System information: 
- Operating system (distribution) and version: Ubuntu 16.04.6 LTS
- DBeaver version: 6.1.5
- Additional extensions: none

#### Connection specification:
- Database name and version: MySql 5.7.27
- Driver name: mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When in table **Properties** panel, in the **Columns** subpanel, when I click on **Create new column** button, the _Edit attribute_ window opens. In this window, the **Properties** grid edit box doesn't appear and all edits are blind edits. 
Editing the _Data Type_ entry, I can see varchar(100) as the default value. I click on it to change the datatype but if I write anything the shown value is still _varchar(100)_. Blindly typing a **d** the result is the one shown in this photo (sorry for not posting a screenshot but drop down menu disappears is I try to take a screenshot):
![IMG_20190831_171719](https://user-images.githubusercontent.com/10668286/64065899-d1558b00-cc13-11e9-8a91-ae42f1242da7.jpg)

For checkboxex, instead, if I click on the corresponding **Value** column, the checkbox value is changed but the checkbox disappears and reappears checked as soon as I click on another entry:
![Schermata da 2019-08-31 17-19-38](https://user-images.githubusercontent.com/10668286/64065890-b97e0700-cc13-11e9-9ca2-780d611ef06d.png)

#### Steps to reproduce, if exist:
As described above

**Comment by zazy** [comment] 2019-09-09 17:03
Still an issue in 6.2.0

**Comment by biojack** [comment] 2020-02-08 16:39
I get this bug as well, Ubuntu 16.04, DBeaver 6.3.4, PostgreSQL 10.3. I had trouble with screenshots as well, but the Data Type value does not show at all when selected:
![Screenshot from 2020-02-08 11-28-17_2](https://user-images.githubusercontent.com/29980900/74088744-9b8cbc00-4a67-11ea-8d52-6ae75b53bd12.png)

**Comment by uslss** [comment] 2020-03-30 12:27
Is it still reproducible against current version? is it reproducible on ubuntu 16.04 only?
unfortunately, cannot reproduce it on 19.04

**Comment by zazy** [comment] 2020-03-30 20:38
I no longer have 16.04 installed. I will try it on a virtual machine next days and return to you. Issue disappeared on 18.04

**Comment by uslss** [comment] 2020-04-21 14:17
seems to be duplicate of #6171

**Closed by uslss** 2020-04-21 14:17 UTC
Labels: bug, duplicate, wait for response, xo:linux
