### ISSUE TITLE
第三方组件重新安装后不要清空

### ISSUE THREAD

**Issue by zhangdingrui** [dbeaver/dbeaver#20674] opened 2023-07-25 08:08 UTC
![image](https://github.com/dbeaver/dbeaver/assets/76196230/08e1390a-11e2-443d-9c9a-db1c880ab10b)
例：安装导出excel插件
DBeaver Office integration - https://dbeaver.io/update/office/latest/
每次升级版本，都需要重新安装

**Comment by E1izabeth** [comment] 2023-07-25 09:11
Thank you for bug report. This issue is a duplicate of #5317, so I'm closing it.

**Closed as not planned by E1izabeth** 2023-07-25 09:11 UTC
Labels: duplicate, xf:packaging
