### ISSUE TITLE
Collapsing the nested begin-end; region

### ISSUE THREAD

**Issue by dimahetman** [dbeaver/dbeaver#21798] opened 2023-11-09 07:27 UTC
**problems**
Dbeaver hasn't feature Collapsing the nested begin-end; regions like this example. If I have very big script i can't collapsing some blocks
```
DO$$
BEGIN
     <<MARK1>>   -- there  (+)
     DECLRARE
     BEGIN
         --- ...
     END MARK1;

     <<MARK2>>  -- there  (+)
     BEGIN
         --- ...
     END MARK2;

     BEGIN            -- there (+)
         --- ...
     END;
END;
$$
```

**desired solution**
Add the ability to collapse nested blocks and marked begin-end; regions

**Comment by E1izabeth** [comment] 2023-11-09 08:18
Thank you for the idea. It's a duplicate of #11830
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2023-11-09 08:18 UTC
Labels: duplicate, xf:sql editor
