### ISSUE TITLE
Workbench has not been created yet. DBeaver 5.

### ISSUE THREAD

**Issue by Pit37** [dbeaver/dbeaver#3319] opened 2018-04-13 14:07 UTC
I have dbeaver-ce-5.0.2-x86-setup.exe
Windows 7 32 bit.
When i run, i get error: 
An error has occurred. See the log file
C:\Users\...\.dbeaver4\.metadata\.log.
![dbeaver](https://user-images.githubusercontent.com/38354777/38739217-ae63450a-3f4d-11e8-89b5-5e19b9233809.jpg)

In log:

!ENTRY org.eclipse.osgi 4 0 2018-04-13 18:49:29.543
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalStateException: Workbench has not been created yet.)
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.swt.widgets.Display.release(Display.java:3874)
	at org.eclipse.swt.graphics.Device.dispose(Device.java:298)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:178)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: java.lang.IllegalStateException: Workbench has not been created yet.
	at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:93)
	at org.jkiss.dbeaver.core.WorkbenchContextListener.<init>(WorkbenchContextListener.java:60)
	at org.jkiss.dbeaver.core.WorkbenchContextListener$3.run(WorkbenchContextListener.java:246)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 17 more

**Comment by serge-rider** [comment] 2018-04-13 21:41
This is a known Eclipse bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=512052
Hopefully will be fixed in the next E4 release.

Workaround: try to restart DBeaver.

**Comment by Pit37** [comment] 2018-04-14 04:33
I don't undestand.
This problem is in the development environment of DBeaver (E4)?
I downloaded another version (DBeaver 4.3.5,), but the problem still remains.
Can I somehow use a different version of DBeaver?

**Comment by serge-rider** [comment] 2018-04-14 08:30
This problem occurs only on some machines and in some circumstances and it is very hard to reproduce it on others. 
There are tens of comments about that in the bug I linked above.
It is a bug in Eclipse platform, not DBeaver itself. I'm afraid I can't fix it.

Could you post full debug log? Maybe it'll give a clue.

**Comment by Pit37** [comment] 2018-04-14 08:56
> It is a bug in Eclipse platform, not DBeaver itself. I'm afraid I can't fix it.
I understand it. But I do not understand why the previous version does not work. In addition, for a while I worked and version 5.

Maybe I need to install a previous version of the JRE separately? Only I did not find how to do it. On the site of the oracle seems as soon as the latest version.

> Could you post full debug log? Maybe it'll give a clue.

[log.txt](https://github.com/dbeaver/dbeaver/files/1910188/log.txt)

**Comment by serge-rider** [comment] 2018-04-14 14:17
No, JRE and DBeaver versions change won't help (at least it shouldn't).

Thank for log, indeed now I have a clue and perhaps this is a different error.
Loooks like your workspace state was corrupted by some reason.
Try to reset workspace (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace), specifically delete `.dbeaver4\.metadata\.plugins\org.eclipse.core.resources\` folder.

**Comment by Pit37** [comment] 2018-04-14 17:09
> Try to reset workspace (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace), specifically delete .dbeaver4\.metadata\.plugins\org.eclipse.core.resources\ folder.

Yes, it helped! Thanks for the help and for the great product!

**Comment by serge-rider** [comment] 2018-04-14 18:35
👍

**Closed by serge-rider** 2018-04-14 18:35 UTC
Labels: bug

**Comment by Gieardia** [comment] 2018-06-07 18:53
Just wanted to put this out there. I was having this issue with dbeaver on Ubuntu. All I had to do was install JDK v8 and set it as the default. From there the problem went away. 

Looks like this problem stems from changes made in JDK version > 8 and the eclipse code just hasn't been update to work with the new versions of Java.

**Comment by jotafullstack** [comment] 2018-10-22 10:09
The solution its very easy, you need install first the java JDK and download again the Dbeaver..

**Comment by d-silva** [comment] 2019-06-03 12:54
> Just wanted to put this out there. I was having this issue with dbeaver on Ubuntu. All I had to do was install JDK v8 and set it as the default. From there the problem went away.
> 
> Looks like this problem stems from changes made in JDK version > 8 and the eclipse code just hasn't been update to work with the new versions of Java.

Had the same problem and this solution worked for me. Thank you @Gieardia :+1:
