### ISSUE TITLE
MySQL dump seems to be faulty in DBeaver 24.2.0

### ISSUE THREAD

**Issue by XavierEduardo99** [dbeaver/dbeaver#35509] opened 2024-09-07 18:59 UTC
### Description

When dumping a somewhat large MariaDB database using DBeaver 24.1.5, the resulting file is 42.9 MB, and the restore process works without any issue. 

![imagen](https://github.com/user-attachments/assets/8112310a-66bc-48cc-8131-dbc140d5d919)

However, the same process, with the same database in DBeaver 24.2.0, results in a 29.3 MB file, and the restore process returns the following errors: 

![imagen](https://github.com/user-attachments/assets/c9ee72d5-0d49-45e7-ae10-b962a14c51a0)

### DBeaver Version

Community Edition 24.2.0

### Operating System

Microsoft Windows 11

### Database and driver

1. Database MariaDB version 10.1.39-MariaDB

### Steps to reproduce

1. Connect to a MariaDB database.
2. Dump a database
3. Try restoring it, and the issue should pop up

### Additional context

1. Everything described has happened in a local environment using XAMPP and PHP 7.3.5

**Comment by ask9** [comment] 2024-09-07 21:09
Try the latest Early Access build:
https://dbeaver.io/files/ea/
I'm not sure but it seems to be it was fixed.

**Comment by ShadelessFox** [comment] 2024-09-08 12:54
Hello @XavierEduardo99,

Thanks for the bug report. This is a duplicate of #35421. Please track the progress on the issue there.

**Closed as not planned by ShadelessFox** 2024-09-08 12:54 UTC
Labels: duplicate, x:maria
