### ISSUE TITLE
snap 24.2.5.202411171748 doesn't start

### ISSUE THREAD

**Issue by daoxxx** [dbeaver/dbeaver#36264] opened 2024-11-18 11:01 UTC
### Description

Snap updated up to 24.2.5.202411171748. And application now doesn't start

```
ноя 18 13:54:40 ubook kernel: audit: type=1400 audit(1731927280.492:281): apparmor="DENIED" operation="open" profile="snap.dbeaver-ce.dbeaver-ce" name="/proc/cgroups" pid=17816 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
ноя 18 13:54:40 ubook kernel: audit: type=1400 audit(1731927280.492:282): apparmor="DENIED" operation="open" profile="snap.dbeaver-ce.dbeaver-ce" name="/proc/17816/coredump_filter" pid=17816 comm="java" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
ноя 18 13:54:40 ubook kernel: audit: type=1400 audit(1731927280.492:283): apparmor="DENIED" operation="open" profile="snap.dbeaver-ce.dbeaver-ce" name="/proc/17816/coredump_filter" pid=17816 comm="java" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
```

### DBeaver Version

24.2.5.202411171748

### Operating System

Ubuntu 22.04.5

**Comment by E1izabeth** [comment] 2024-11-18 11:04
Thank you for the bug report.
It looks like a duplicate of #36261
Please try this workaround https://github.com/dbeaver/dbeaver/issues/36261#issuecomment-2481961591

**Closed as not planned by E1izabeth** 2024-11-18 11:04 UTC
Labels: duplicate, xo:linux, xf:snap

**Comment by daoxxx** [comment] 2024-11-18 11:12
thank you. The workaround works. I did reverted earlier, but removing cache does the trick
