### ISSUE TITLE
The result window set USES the touchpad to slide left and right, does not respond

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#8524] opened 2020-04-23 01:20 UTC
![image](https://user-images.githubusercontent.com/26621087/80048649-5f83d600-8543-11ea-8eb0-66615c7fa611.png)

The result window set USES the touchpad to slide left and right, does not respond
#### System information: 
- Operating system (distribution) and version WIN10 64
- DBeaver version  7.03
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment] 2020-05-22 15:14
thanks for the bug report

**Comment by tati-kru** [comment] 2020-06-22 14:54
Duplicate of #8404

**Closed by tati-kru** 2020-06-22 14:54 UTC
Labels: bug
