### ISSUE TITLE
Cannot execute DDL with semicolon on new line

### ISSUE THREAD

**Issue by petrvalkoun-gooddata** [dbeaver/dbeaver#16174] opened 2022-04-13 10:32 UTC
#### System information: 
- Operating system (distribution) and version: MacOS 12.3.1
- DBeaver version 22.0.2.202204041542
- Additional extensions: none

#### Connection specification:
- Database name and version
- Driver name: gooddata JDBC proprietary, based on HP Vertica
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When executing DDL (CREATE VIEW) with closing semicolon on new line:
_CREATE OR REPLACE VIEW test AS
SELECT 1
;_

I receive following reply:
_Updated Rows	-1
Query	;
Finish time	Wed Apr 13 12:29:30 CEST 2022_

The view was not created.

This works ok it the semicolon is on the same line:
_CREATE OR REPLACE VIEW test AS
SELECT 1;_

reply:
_Updated Rows	0
Query	CREATE OR REPLACE VIEW test AS
	SELECT 1
Finish time	Wed Apr 13 12:30:58 CEST 2022_

I use our JDBC driver with DBeaver for years and this is first time I see this problem.

**Comment by ceinmart** [comment] 2022-04-13 12:50
Here, after upgrade to version 22.0.2 , the same behave start to occur. 
However, occurr with any SQL STATEMENT, not only DDL . Any DML too. 

This doesn't work.
```
select * from systables 
;
```

This work:
```
select * from systables ;
```

**Comment by E1izabeth** [comment] 2022-04-13 13:50
Thank you for bug report. Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/16077

**Closed as completed by E1izabeth** 2022-04-13 13:50 UTC
