### ISSUE TITLE
When "auto convert case" is on, undo should revert case change

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#7730] opened 2020-01-23 15:01 UTC
**Is your feature request related to a problem? Please describe.**
When "auto convert case" is on, there is no way to tell the editor to keep the case of a specific word as "was written" - it will always convert the case.
For example in a postgres DB I have a column called "content", every time i write "content" and a space/comma/return it auto converts to uppercase. I don't want to exclude the word from keywords.

**Describe the solution you'd like**
Some editors allow undoing the case change by hitting the undo combination (i.e ctrl+z) - this reverts the case change rather than the space/comma/return like the current behavior. I'm open to other suggestions.

**Describe alternatives you've considered**
currently I have to select the word and convert the case manually (ctrl+shift+x/y), or write the word except the last letter, add a space and then go back, add the letter and move the cursor

**Comment by uslss** [comment] 2021-08-04 08:32
closed as a duplicate of #6113

**Closed by uslss** 2021-08-04 08:32 UTC
Labels: duplicate, feature request
