### ISSUE TITLE
DB2: List of tables not working since version 21.0.5

### ISSUE THREAD

**Issue by surfer245** [dbeaver/dbeaver#19758] opened 2023-04-20 11:14 UTC
### Description

when I click on the `Tables` in the Database Navigator, I always get the following error: `[PWS9801] CALL QSYS.QSQSITABLE`. I guess my user does not have access right for `QSYS` on this database server.
It did work with Dbeaver version `21.0.5`. 
Is there a way to configure the old behaviour from `21.0.5`?

### DBeaver Version

23.0.2

### Operating System

Linux

### Database and driver

DB2 / Db2 for IBM i

**Comment by LonwoLonwo** [comment] 2023-04-20 11:46
Hello @surfer245 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by surfer245** [comment] 2023-04-20 12:31
I have attached the debug log:
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/11286174/dbeaver-debug.log)

Thanks, 
Michael

**Comment by LonwoLonwo** [comment] 2023-04-20 13:27
As I can see, the issue is from the driver side:

```
java.sql.SQLException: [PWS9801] CALL QSYS.QSQSITABLE
	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:985)
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:745)
	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1821)
	at com.ibm.as400.access.AS400JDBCPreparedStatementImpl.<init>(AS400JDBCPreparedStatementImpl.java:357)
	at com.ibm.as400.access.AS400JDBCCallableStatement.<init>(AS400JDBCCallableStatement.java:126)
	at com.ibm.as400.access.AS400JDBCConnectionImpl.prepareCall(AS400JDBCConnectionImpl.java:2027)
	at com.ibm.as400.access.AS400JDBCConnectionImpl.prepareCall(AS400JDBCConnectionImpl.java:1913)
	at com.ibm.as400.access.AS400JDBCDatabaseMetaData.getTables(AS400JDBCDatabaseMetaData.java:4632)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTables(JDBCDatabaseMetaDataImpl.java:1116)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareTableLoadStatement(GenericMetaModel.java:586)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:67)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.prepareObjectsStatement(JDBCStructLookupCache.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTables(GenericObjectContainer.java:159)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPhysicalTables(GenericObjectContainer.java:143)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.getPhysicalTables(GenericDataSource.java:416)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:964)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1036)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:595)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:464)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:303)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I can suggest you to ask your administrator to add you more permissions.

**Comment by surfer245** [comment] 2023-04-20 13:30
sorry, the db administrator won't do that. 
As I said, it worked with the same driver and  a previous version of dbeaver.

**Comment by E1izabeth** [comment] 2023-05-02 11:08
You could try changing the driver version to the version you used in 21.0.5. I suppose it's 11.5.0.0
![image](https://user-images.githubusercontent.com/28875055/235650174-9955f583-c52d-444c-80c1-ead230fca84b.png)

**Comment by surfer245** [comment] 2023-05-03 06:06
I had a look at the driver source code and I have found out that you have to set `metadata source` to `0`, than it works exactly like the older version.
![dbeaver_driver_properties](https://user-images.githubusercontent.com/20775112/235842660-759ab235-2ec0-4eea-b697-ce127e993f6e.png)

**Comment by E1izabeth** [comment] 2023-05-03 07:46
Thank you for investigation!

**Comment by LonwoLonwo** [comment] 2023-05-03 09:05
We can't change the metadata source parameter from our side. We tried it, and it was a wrong decision: https://github.com/dbeaver/dbeaver/issues/10302#issuecomment-869466711.

0 - it is not the default parameter for the driver - probably, they also have a reason to do it that way.

So, if your issue is solved - I'm closing this ticket.

**Closed as completed by LonwoLonwo** 2023-05-03 09:05 UTC
Labels: third party issue, xf:metadata, x:db2i
