### ISSUE TITLE
Offer of dark theme preferences to use as defaults

### ISSUE THREAD

**Issue by crokusek** [dbeaver/dbeaver#5184] opened 2019-02-01 23:54 UTC
#### System information: 
- Windows 10
- DBeaver 5.3.3.201901202008
- Java that came with 5.3

#### Connection specification:
- SQL Server latest driver

#### Describe the problem you're observing:

Offer my preferences file to improve colors for the dark theme.  Hoping it could become the shipped defaults.

Mainly just the SQL Server Editor and Data Grid were adjusted.   
Colors are more muted, less contrasting.  Better for longer sessions.
The odd/even row is more subtle.

There are still problems as some areas are apparently are not settable but IMO is large improvement over the defaults.  Hope you consider trying it out.

#### Steps to reproduce, if exist:
1. Download the attached file, rename by trimming the ".txt"
2. File -> Export -> "Preferences" -> Save to file so you can go back.
3. File -> Import -> "Preferences" -> The attached file

There may be a few other settings in there besides colors that need to be pruned.
[DBeaverPrefs.epf.txt](https://github.com/dbeaver/dbeaver/files/2823731/DBeaverPrefs.epf.txt)

**Comment by pdanie** [comment] 2019-02-02 21:18
I would say that your settngs are better than the _DBeaver_ default. But there are still some way left to go before the dark scheme are useful. The contrast in comboboxes, treeviews and still too low to be useful. Maybe a change in font could help it up some.

**PS**. Take a look at _JetBrains DataGrip_ and the color scheme **Darkula** that is clear and comfortable to look at even for long working hours.

**Comment by serge-rider** [comment] 2019-02-11 13:39
Thanks for proposal. We'll try to adapt it in the next version..

**Comment by serge-rider** [comment] 2019-02-11 13:45
Also note that you can use Darkest Dark theme (can be optionally installed in DBeaver from Help->Install New Software, P2 repo is preconfigured in the dropdown list).

Darkest Dark is much-much better than standard Dark theme. We are thinking about shipping it along with DBeaver although it is not that easy.

**Comment by crokusek** [comment] 2019-02-12 02:55
fyi, i selected the "DBeaver CE Update site", then tried just "DBeaver Core" but it stopped with "Cannot complete the install because of a conflicting dependency".  Then I re-tried by selecting all of them (not just core) and got similar message.  No big deal, I can wait.

**Comment by DavidMCook** [comment] 2019-03-04 22:35
Hi all, 

Even with this updated theme, there are still a few values that are simply illegible. Any chance the base navigation/helper text can be made to be configurable as well?

![image](https://user-images.githubusercontent.com/1742986/53767445-75e05580-3e9b-11e9-924a-f41a9c635279.png)

**Comment by serge-rider** [comment] 2019-03-05 14:50
@DavidMCook can't reproduce this:
Did you restart DBeaver after applying darkest dark theme?
What is your OS?

![image](https://user-images.githubusercontent.com/6398845/53813622-194e6a80-3f6f-11e9-96f4-438171a7b5b6.png)

**Comment by DavidMCook** [comment] 2019-03-05 23:23
I'm running on Mac OSX, and I did restart DBeaver after. But perhaps the
theme isn't truly available? Now that you mention, "darkest dark," should
that be the actual name of the theme in the dropdown menu?


Best,

*David Cook *

**Comment by DavidMCook** [comment] 2019-03-06 17:24
Closing the loop on this - it looks like the "Darkest Dark" them failed to install when using the direct jar method. Pulling from "install new software" (as mentioned in the later post) worked perfectly. Granted, something still didn't get set quite right, but it's a world of difference.

**Comment by DavidMCook** [comment] 2019-03-06 17:31
Yeah, I'm sorry to keep asking questions here but I'm guessing this isn't what the Properties tab is supposed to look like: 

![image](https://user-images.githubusercontent.com/1742986/53900959-57956980-4003-11e9-8005-5d40f96b9be1.png)

**Comment by serge-rider** [comment] 2019-03-06 19:34
It definitely shouldn't look like this.
Is this Darkest Dark?

**Closed** 2019-03-06 20:02 UTC
Labels: enhancement, xf:dark theme
