### ISSUE TITLE
Unrecognizable Font in Script Tabs

### ISSUE THREAD

**Issue by whongpine** [dbeaver/dbeaver#36506] opened 2024-12-10 07:48 UTC
### Description

Hi,

I recently updated to the new version and now the Script tabs are unreadable.  I've tried to change the font but no luck.  
Below is an image of that my current screeon looks like. 
![스크린샷 2024-12-10 164716](https://github.com/user-attachments/assets/3467a5b6-7e2c-4c85-93eb-78729d3f1643)

Thanks for your help!

### DBeaver Version

Community Edition Version 24.3.0.202412011650 

### Operating System

Windows 11 Version 24H2 (OS Build 26100.2314)

**Comment by E1izabeth** [comment] 2024-12-10 10:34
Please try changing fonts in Preferences
![image](https://github.com/user-attachments/assets/bc4d6ab0-b9fa-47e7-9eb2-8d0d1fa9cb5a)

**Comment by E1izabeth** [comment] 2024-12-10 10:34
Let me know about the results

**Comment by whongpine** [comment] 2024-12-11 01:01
It works!  Thank you!

**Comment by E1izabeth** [comment] 2024-12-11 16:51
The issue is similar to #9455
Closing as a duplicate

**Closed as not planned by E1izabeth** 2024-12-11 16:51 UTC
Labels: duplicate, xo:windows, xf:ui
