### ISSUE TITLE
DBeaver CE 21.3.1 does not launch

### ISSUE THREAD

**Issue by logangarcia-kubra** [dbeaver/dbeaver#14924] opened 2021-12-15 22:32 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: CE 21.3.1
- Additional extensions: N/A

After upgrading to DBeaver 21.3.1 from 21.3.0, I saw the splash screen briefly before it told me that the application had stopped and to consult the metadata logs. After looking at the logs, I saw this output:

```!SUBENTRY 1 org.eclipse.equinox.registry 4 1 2021-12-15 15:02:30.682
!MESSAGE Plug-in org.jkiss.dbeaver.core was unable to load class org.jkiss.dbeaver.core.DBeaverCoreAdapterFactory.
!STACK 0
java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.jkiss.dbeaver.core (174).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:572)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:388)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:467)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:616)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.lambda$4(AdapterFactoryProxy.java:84)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.loadFactory(AdapterFactoryProxy.java:157)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:334)
	at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:366)
	at org.jkiss.dbeaver.utils.GeneralUtils.queryAdapterManager(GeneralUtils.java:744)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:719)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:734)
	at org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform(DBWorkbench.java:45)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.initDebugWriter(DBeaverApplication.java:626)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:238)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: org.osgi.framework.BundleException: Exception in org.jkiss.dbeaver.core.DBeaverActivator.start() of bundle org.jkiss.dbeaver.core.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:828)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:759)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1019)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:404)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 33 more
Caused by: java.lang.IllegalStateException: Can't parse workspace location URL
	at org.jkiss.dbeaver.utils.GeneralUtils.getMetadataFolder(GeneralUtils.java:673)
	at org.jkiss.dbeaver.ModelPreferences.initializeDefaultPreferences(ModelPreferences.java:234)
	at org.jkiss.dbeaver.ModelPreferences.setMainBundle(ModelPreferences.java:162)
	at org.jkiss.dbeaver.core.DBeaverActivator.start(DBeaverActivator.java:63)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.lambda$2(BundleContextImpl.java:808)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:802)
	... 40 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 20: file:/C:/Users/Logan Garcia/AppData/Roaming/DBeaverData/workspace6/
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at java.base/java.net.URL.toURI(Unknown Source)
	at org.jkiss.dbeaver.utils.GeneralUtils.getMetadataFolder(GeneralUtils.java:663)
	... 46 more
```

The issue seems to be that my user name, `Logan Garcia`, contains a space in it that DBeaver 21.3.1 is having trouble parsing, whereas if I downgrade to DBeaver 21.3.0, it parses that username fine and launches successfully. I've cleared the metadata folder to make sure that it wasn't some workspace error.

**Comment by LeMapper** [comment] 2021-12-17 09:38
Duplicate of #14927

**Comment by flambchap** [comment] 2021-12-22 12:08
Duplicate of https://github.com/dbeaver/dbeaver/issues/14877.

**Closed as completed by flambchap** 2021-12-22 12:08 UTC
Labels: duplicate
