### ISSUE TITLE
Connection invalidation fails when using ssh tunnel

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#7958] opened 2020-02-19 15:15 UTC
#### System information: 
- Operating system (distribution) and version: mac 10.15.3
- DBeaver version: postgres 11.2
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? ssh tunnel through a VPN

#### Describe the problem you're observing:
SQL Error [08001]: Connection to 127.0.0.1:15622 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
![image](https://user-images.githubusercontent.com/18515297/74847712-3d02f000-533b-11ea-8b23-065d048104be.png)
Clicking "Retry" doesn't help. This happens everytime after returning from AFK - only for connections using an ssh tunnel. The only way to gain the connection back is to manually disconnect and reconnect.

This seems like a regression from 6.3.3 - I tried working with that version for a few hours and it did not occur even after being AFK - the connection invalidation was successful.

**Comment by pyrocks** [comment] 2020-02-23 07:11
A comment from #9752 - might be related
![image](https://user-images.githubusercontent.com/18515297/75105475-56968700-561c-11ea-98d0-0fef663f5911.png)

**Comment by uslss** [comment] 2020-02-23 14:58
closed as a duplicate of #7952

**Closed by uslss** 2020-02-23 14:58 UTC
Labels: bug, wait for review
