### ISSUE TITLE
task to dump database for all objects

### ISSUE THREAD

**Issue by mshakurov** [dbeaver/dbeaver#15086] opened 2021-12-29 13:02 UTC
How do I set up a task that will back up all schemas and all objects? Why do I have to choose schemes every time? Maybe I don’t see any special settings? Or should I manually write a script? Is there a setting through the DBeaver interface?
I mean, if a new scheme is added, then it will not be reserved by the same task, and I need to configure the task.

**Comment by Skydiveroid** [comment] 2022-01-12 12:58
@mshakurov 

Thanks for the idea.

**Comment by LonwoLonwo** [comment] 2023-01-05 09:01
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/17494

**Closed as not planned by LonwoLonwo** 2023-01-05 09:01 UTC
Labels: x:postgresql, duplicate, xf:native clients
