### ISSUE TITLE
SQL Editor / Set Active Connection doesn't do anything in 6.0.3

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#5846] opened 2019-05-03 11:38 UTC
Neither does the Ctrl-9 shortcut.

Windows 10 Enterprise version 1803.

**Comment by serge-rider** [comment] 2019-05-03 11:56
Ctrl+9 shortcut was fixed in #5767.
I can't  reproduce "doesn't do anything" part. If you choose another schema/connection in main toolbar it changes for the editor. Could you provide a bit more details?

**Comment by bobf32** [comment] 2019-05-03 13:08
Sure. In 5.1.6 if I select the menu option or do Ctrl-9 the window pops up to select a different DB connection. This does not happen in 6.0.3.

I see the fix and will await to test 6.0.4.

**Comment by uslss** [comment] 2019-05-12 18:59
The issue isn't reproducible on 6.0.4.
If it is still reproducible for you, feel free to reopen the ticket.

**Closed by uslss** 2019-05-12 18:59 UTC
Labels: can't reproduce, question
