### ISSUE TITLE
Change font size of db navigator

### ISSUE THREAD

**Issue by wolfgang-a-klein-db** [dbeaver/dbeaver#14147] opened 2021-10-05 13:10 UTC
Hi all,

I would like to ask whether it's possible to change the font size of db-navigator inside dbeaver (left side). 
A lot of places can be changed in settings, but somehow not this part.

A possibility to change this fonts also via settings would be nice or a common possibility to scale the whole ui of dbeaver even better.

On windows 10 I could also scale the whole desktop but I´m working on MacBook with external monitor, where it´s
not so easy to scale complete Desktop.

Regards,
Wolfgang

**Comment by ShadelessFox** [comment] 2021-10-05 16:07
Hello @wolfgang-a-klein-db,

Thanks for feature request.

Duplicate of #12975

**Closed as completed by ShadelessFox** 2021-10-05 16:07 UTC
