### ISSUE TITLE
 Cursor behaviour

### ISSUE THREAD

**Issue by JiaOkay** [dbeaver/dbeaver#34360] opened 2024-06-14 07:47 UTC
### Description

在linux 上使用 24.1.0 版本 发现以下问题：
当输入行前存在字符时 光标会下移，而在空白行的行首时不会

当然 没有图片中那么夸张 因为截图工具截取不了闪烁的光标，所以我画了一条线来表示

![图片](https://github.com/dbeaver/dbeaver/assets/38833358/dd51114b-e5c4-4c96-9761-df5973e57160)

事实上在之前的版本上就已经发现这个问题了 只是一直没有反馈

### DBeaver Version

24.1.0

### Operating System

deepin v23 RC2

### Database and driver

database oracle 11gr2
driver odbc11:release23.2.0.0

**Comment by JiaOkay** [comment] 2024-06-14 07:53
当光标在括号中间的时候更明显 括号会上移 光标会下移，光标移除括号之后括号显示恢复正常
![图片](https://github.com/dbeaver/dbeaver/assets/38833358/6f89caf9-1fd7-415f-a036-d638b0e91a31)

**Comment by serjiokov** [comment] 2024-06-14 08:05
Hello, I would appreciate if you translate issue on English language please

**Comment by JiaOkay** [comment] 2024-06-14 08:47
The following issues were found when using version 24.1.0 on Linux:
When there are characters before the input line, the cursor will move down, but it will not move down at the beginning of a blank line.
![图片](https://github.com/dbeaver/dbeaver/assets/38833358/21310c16-cafe-49e4-982b-4076d07858d0)

When the cursor is in the middle of the parentheses, it becomes more prominent. The parentheses will move up ,the cursor will move down, and after the cursor moves out of the parentheses, the display of the parentheses will return to normal
![图片](https://github.com/dbeaver/dbeaver/assets/38833358/9a627da6-8736-4214-9f97-776d252625ba)

**Comment by E1izabeth** [comment] 2024-06-14 09:50
Regarding the parentheses - you can turn this off in preferences
![image](https://github.com/dbeaver/dbeaver/assets/28875055/30069a68-aaeb-44fc-8bb3-cb890e7f2964)

I'm closing this issue as a duplicate of #8552

**Closed as not planned by E1izabeth** 2024-06-14 09:50 UTC
Labels: duplicate, xf:sql editor

**Comment by JiaOkay** [comment] 2024-06-14 10:12
Question 1, I mean  the cursor is lower than line area, when cursor is right of charator

Question2, I mean the size of chanparentheses will change when cursor in it

![录屏_选择区域_20240614180406](https://github.com/dbeaver/dbeaver/assets/38833358/46cb8227-0c4f-4745-9050-61d1ebd8b0f3)

**Comment by E1izabeth** [comment] 2024-06-14 10:24
Question 1 has already been described in issue https://github.com/dbeaver/dbeaver/issues/8552 . We haven't decided to change this behavior yet. However, you can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

Question2 - is expected behavior. If you don't like it, you can turn this off in the preferences.

**Comment by JiaOkay** [comment] 2024-06-14 12:37
Q1: I didn't express myself clearly
This picture may better illustrate the problem

![图片](https://github.com/dbeaver/dbeaver/assets/38833358/ca3891df-d3f0-4aec-a30f-3619e36c3b3f)

Q2 I understood

**Comment by E1izabeth** [comment] 2024-06-17 13:23
I get your explanation. This issue is closed in order to avoid duplication of similar requests. Here is the issue about the same thing, that is already exist https://github.com/dbeaver/dbeaver/issues/8552#issuecomment-627093247
