### ISSUE TITLE
ODBC jdbc-odbc-bridge-jre7.jar NullPointerException

### ISSUE THREAD

**Issue by dputzter82** [dbeaver/dbeaver#17701] opened 2022-09-21 19:50 UTC
### Description

Creating new ODBC connection. Downloaded both the jar and dll from github and placed in local directory.
![image](https://user-images.githubusercontent.com/2846197/191595682-67660e1b-ae9e-49ec-ad19-bdc9fa0b94b9.png)

Getting this error when attempting to connect:
Unexpected driver error occurred while connecting to the database
  NullPointerException
  java.lang.NullPointerException

When I check the driver class: find class option, I get nothing back:
![image](https://user-images.githubusercontent.com/2846197/191596093-43c733d3-7984-4958-993a-ea2257ff6623.png)

Here are the log files:
`!SESSION 2022-09-21 14:32:17.616 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2022-09-21 14:33:07.846
!MESSAGE NullPointerException
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-09-21 14:33:07.846
!MESSAGE NullPointerException
!STACK 0
java.lang.NullPointerException
	at sun.jdbc.odbc.JdbcOdbcDriver.initialize(JdbcOdbcDriver.java:453)
	at sun.jdbc.odbc.JdbcOdbcDriver.connect(JdbcOdbcDriver.java:153)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:191)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:210)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:208)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:137)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:113)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:953)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:887)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

Thanks.

### DBeaver Version

Community Edition 22.2.0

### Operating System

Windows 11 - 21H2

### Database and driver

1. IBM DB2
2. ODBC

### Additional context

May relate to issue #17569.

**Comment by dputzter82** [comment] 2022-09-21 20:03
Additionally, when I reset the driver libraries to the "restore default" option, then click the download/update button, and then the download button, I get a "Driver file download failed." error. Not sure if this is related or not.

![image](https://user-images.githubusercontent.com/2846197/191599729-f733bb71-3d7b-4566-a3d3-708ed6c2c156.png)

**Comment by LonwoLonwo** [comment] 2022-09-22 13:03
Hello @dputzter82 

Thanks for the info and for the logs.

And yes, this is a duplicate of https://github.com/dbeaver/dbeaver/issues/17569.

So I'm closing this ticket.

**Closed as not planned by LonwoLonwo** 2022-09-22 13:03 UTC
Labels: x:odbc
