### ISSUE TITLE
Bugs in new Oracle timestamp implementation

### ISSUE THREAD

**Issue by raqua** [dbeaver/dbeaver#3532] opened 2018-05-29 08:15 UTC
Hello, 

I just upgraded from version 5.0.1 to 5.0.6. 
I have noticed following issues:

1) select current_timestamp, systimestamp from dual -> returns nulls
![screenshot from 2018-05-29 10-10-57](https://user-images.githubusercontent.com/1541886/40646303-0da76542-6329-11e8-858b-13f27647a4ec.png)

2) timestamp columns now have variable length of milliseconds which looks really bad
![screenshot from 2018-05-29 10-10-48](https://user-images.githubusercontent.com/1541886/40646360-308c5022-6329-11e8-8a65-c6c98243c6f5.png)

**Comment by serge-rider** [comment] 2018-05-29 08:31
Seems to be a side effect of #238 fix. However I can't reproduce this.
- What Oracle driver and server do you use?
- Please post debug/error logs (https://github.com/dbeaver/dbeaver/wiki/Log-files) - at least partially

**Comment by raqua** [comment] 2018-05-29 08:53
I have closed the DBeaver, then opened and run the query.
This is full log:
[error.log](https://github.com/dbeaver/dbeaver/files/2047439/error.log)

Then I cleared the errors and run the query again.
Smaller log:
[error2.log](https://github.com/dbeaver/dbeaver/files/2047441/error2.log)

My oracle version:
![screenshot from 2018-05-29 10-44-47](https://user-images.githubusercontent.com/1541886/40647934-719d73f8-632d-11e8-9a55-3f6b38e8310e.png)

Both DBeaver and Oracle are running under Linux. 

Where can I find Oracle driver version? In my ~/.dbeaver-drivers there is no Oracle driver, just MySQL, H2 and Postgres.

**Comment by serge-rider** [comment] 2018-05-29 09:44
You can get driver version in
- Connection test dialog (open conneciton properties->Test connection)
- In properties view (Window->Show View->Properties, then select your connection in database navigator)

Solution: update your Oracle driver to version 12 (can be downloaded from Oracle.com). Also it is included in DBeaver EE version.
Most likely this problem caused by old Oracle driver which doesn't support latest JDBC API. I'll try to add some workaround..

**Comment by raqua** [comment] 2018-05-29 12:34
I was on Oracle 11 drivers and update to v.12 solved the first problem.
The second issue still present, obviously. 

One more thing I noticed - it seems like data formats formatting is not applied in this case:
![screenshot from 2018-05-29 14-33-27](https://user-images.githubusercontent.com/1541886/40659058-70d135a2-634d-11e8-965e-ced77e480411.png)

**Comment by serge-rider** [comment] 2018-06-01 07:02
Just a reminder

**Comment by raqua** [comment] 2018-06-01 10:39
[Untitled.log](https://github.com/dbeaver/dbeaver/files/2062389/Untitled.log)

"Can't create formatter for datetime value handler" exception was thrown when I opened table with timestamp column.


"Can't create formatter for zoned datetime value handler" was thrown when I run "select current_timestamp, systimestamp from dual;"

**Comment by serge-rider** [comment] 2018-06-01 11:34
Thanks. It is a problem with new Java8 datetime formatter. 
Will be fixed in 5.1.

**Closed by serge-rider** 2018-06-01 11:34 UTC
Labels: bug, x:oracle
