### ISSUE TITLE
Cannot sort column names in record mode

### ISSUE THREAD

**Issue by JiCiT** [dbeaver/dbeaver#18773] opened 2023-01-14 00:51 UTC
### Description

Used to be able to sort columns alphabetically.  With the new change in how sorting/ordering works generally (choice of ascending or descending upon click), I've been unable to find anyway to sort the columns themselves in record mode.

### DBeaver Version

Community Edition 22.3.2

### Operating System

Windows 10

### Database and driver

MSSQL Server
Microsoft JDBC Driver for SQL Server

### Steps to reproduce

1. Run a query than produces data grid results
2. Change to record mode (tab or click the record mode button)
3. Left-click column name or blank area above column names -OR- right-click anywhere within the grid to bring up context-menu
4. No option to sort column names only by column clicked or first column (in case of clicking blank area above column names

**Comment by E1izabeth** [comment] 2023-01-14 16:25
Thank you for bug report. It's a duplicate of #18618
The fix will be available in the next release.

**Closed as not planned by E1izabeth** 2023-01-14 16:25 UTC
Labels: duplicate, xf:data
