### ISSUE TITLE
Use tab instead of enter

### ISSUE THREAD

**Issue by williambuchanan2** [dbeaver/dbeaver#13094] opened 2021-07-05 03:34 UTC
**Is your feature request related to a problem? Please describe.**
I generally think that for code completion the tab button is the button that should do the completion (based on my use of various other tools). It would be good to have this as an option rather than the current default which is the enter button.

**Describe the solution you'd like**
When I type 'select * from ' the code completion appears. When I press 'TAB' the selected option is used for code completion.
Would be ideal to have an option to choose the button to use.

**Describe alternatives you've considered**

**Additional context**

**Comment by Matvey16** [comment] 2021-07-08 07:24
@williambuchanan2 This feature is highly demanded even by people in our team, but for now we are restricted in it's implementation by Eclipse platform. We will look what can be done in the future.

**Comment by uslss** [comment] 2021-09-22 19:16
closed as a duplicate of #2316

**Closed as completed by uslss** 2021-09-22 19:16 UTC
Labels: duplicate, third party issue
