### ISSUE TITLE
Hive driver download filed

### ISSUE THREAD

**Issue by ururu-fy** [dbeaver/dbeaver#2794] opened 2018-01-16 08:25 UTC
Dbeaver can't download jar file from maven central and it's really absent on url

![capture](https://user-images.githubusercontent.com/31213315/34978344-fae31d80-faae-11e7-8602-974f57b4cb00.PNG)

**Comment by serge-rider** [comment] 2018-01-20 11:51
Duplicate of #2349
Check for workaround in comments.

**Closed by serge-rider** 2018-01-20 11:51 UTC
Labels: bug, duplicate
