### ISSUE TITLE
Ubuntu PPA version stuck at 7.3.1

### ISSUE THREAD

**Issue by vanushwashere** [dbeaver/dbeaver#11031] opened 2021-01-18 10:53 UTC
#### System information: 
- Kubuntu 20.04
- DBeaver version 7.3.1
- Additional extensions - default

**Comment by matthewlenz** [comment] 2021-01-18 14:41
Related. Oddly Ubuntu 18.04's PPA shows 7.3.1 available but apt is keeping it at 7.3.0.  Unfortunately I didn't look at it too as to why (I can only assume some dependency or versioning mistake in the build) before I just updated to 7.3.3 using the .deb directly from the dbeaver site.

**Comment by schmitzkr** [comment] 2021-01-18 19:05
i reported this issue earlier https://github.com/dbeaver/dbeaver/issues/10916
its been labelled for 7.3.4 ?

**Comment by serge-rider** [comment] 2021-01-19 08:23
Duplicate of #10916

**Closed as completed by serge-rider** 2021-01-19 08:23 UTC
Labels: duplicate
