### ISSUE TITLE
dbeaver 6.3.1 - DB/2

### ISSUE THREAD

**Issue by guiwebdev** [dbeaver/dbeaver#7500] opened 2019-12-30 18:50 UTC
Hi all,

Just upgraded to 6.3.1 and every connection I have setup to DB2 iSeries/AS400 (not DB2 LUW) results on an error message related to a _Java null point exception._ 
Click on "OK" discards the message, and all saved scripts work without issue. Closing connection and connecting again results on new error message...

All other connections, Oracle, MySql, Firebird, ect have no issues.

Uninstalling 6.3.1 and installing 6.3.0 solves the problem without further configuration.

**Comment by serge-rider** [comment] 2019-12-31 13:20
Seems to be duplicate of #7486 
You can check the fix in Early Access version (https://dbeaver.io/files/ea)

**Closed** 2019-12-31 14:33 UTC
Labels: bug, duplicate, x:db2
