### ISSUE TITLE
Permission denied when executing external tool

### ISSUE THREAD

**Issue by mikeswain** [dbeaver/dbeaver#19077] opened 2023-02-16 03:26 UTC
### Description

Error running external tools (e.g. Tools->Restore)

Error executing process
  Cannot run program "/usr/bin/mysql" (in directory "/usr/bin"): error=13, Permission denied
  Cannot run program "/usr/bin/mysql" (in directory "/usr/bin"): error=13, Permission denied
    error=13, Permission denied
    error=13, Permission denied

This is a slightly misleading error message as it's not the helper app (mysql in this case) that's at fault, it's a JDK utility used to spawn the process. The problem seems to be in the packaged JRE  - the jspawnhelper executable does not have execute permission:

$ ls -l /usr/share/dbeaver-ce/jre/lib/jspawnhelper
-rw-r--r-- 1 root root 21904 Jan 19 06:20 /usr/share/dbeaver-ce/jre/lib/jspawnhelper

Workround is just to add execute permission:
sudo chmod +x /usr/share/dbeaver-ce/jre/lib/jspawnhelper

But probably needs permission fixed in JRE packaging

### DBeaver Version

Community Edition  22.3.4.202302060909

### Operating System

Ubuntu Linux 22.04.1 

### Database and driver

mysql

### Steps to reproduce

1. Right click on database in Navigator
2. Select Tools->Restore Database
3. Select input sql file
4. Click Start
5. Yes to 'It may corrupt your database, are you sure'
6. Error popup :
```
Cannot run program "/usr/bin/mysql" (in directory "/usr/bin"): error=13, Permission denied
  Cannot run program "/usr/bin/mysql" (in directory "/usr/bin"): error=13, Permission denied
    error=13, Permission denied
    error=13, Permission denied
```

**Comment by TheMechanist902** [comment] 2023-02-16 05:35
Likely related to: https://github.com/dbeaver/dbeaver/issues/18958
To put it short: Executing external programs was broken in 2.3.4. You have to revert to 2.3.3 or wait for an update.
I'm no developer but I had a similar issue with an external formatter (https://github.com/dbeaver/dbeaver/discussions/18972).
The dBeaver team is already working on that issue.
Hope this helps.
EDIT: Sorry you already explained whats wrong. To early in the morning here. Links here just for reference then.

**Comment by E1izabeth** [comment] 2023-02-16 11:22
Thank you for bug report.
Closing as duplicate of #18958
We have already fixed this issue. You can try the early access version https://dbeaver.io/files/ea/ or wait for the next release.

**Closed as not planned by E1izabeth** 2023-02-16 11:22 UTC
Labels: duplicate, xf:datatransfer
