### ISSUE TITLE
Context menu in database navigator

### ISSUE THREAD

**Issue by cldscchttn** [dbeaver/dbeaver#6489] opened 2019-08-10 08:23 UTC
When I right-clic on an item in the database navigator I cannot see the context menu. I'm using DBeaver 6.1.4 on Linux Mint 19.1 Cinnamon . In DBeaver 6.1.3 I can see the menu.

**Comment by serge-rider** [comment] 2019-08-10 14:20
Can't reproduce.
Please check error/debug logs, maybe there is something that will explain this.
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by ngocthienvnn** [comment] 2019-08-12 04:14
I have the same problem too, i'm using DBeaver 6.1.4 on Ubuntu 18.04. This error happens after i upgraded from 6.1.3 to 6.1.4. Just tried to remove dbeaver entirely and reinstall it but the the problem still remains. Besides, there is nothing in the log file too.

**Comment by serge-rider** [comment] 2019-08-13 11:57
Does this happen with any navigator items or only with some?
Please check debug log as well.

**Comment by cldscchttn** [comment] 2019-08-13 12:32
Any item.
I don't have the folder $XDG_DATA_HOME/DBeaverData so I cannot find any log file

**Comment by serge-rider** [comment] 2019-08-13 12:53
What about ~/.local/share/DBeaverData ?

**Comment by ngocthienvnn** [comment] 2019-08-13 15:05
![image](https://user-images.githubusercontent.com/14000527/62952547-0db47900-be16-11e9-9cf9-f63b86c477dd.png)
Please see my screenshot, those have red line that can not use right click context menu. In my screenshot, only **Statisctic** and **DLL** tab can use right click context menu

**Comment by ngocthienvnn** [comment] 2019-08-13 15:09
![image](https://user-images.githubusercontent.com/14000527/62952857-ab0fad00-be16-11e9-8cb5-b9545b1cb594.png)
Please see my screenshot, those have red line that can not use right-click context menu, only DLL and Statistic tab can use right-click context menu

**Comment by cldscchttn** [comment] 2019-08-13 16:02
Log files are in  ~/.local/share/.DBeaverData folder (.DbeaverData with point)
 I have three data sources: Ms Access, MySql and PostgreSQL. When I right clic on tables in MS Access an MySql I don't get any log (context menu does not appear). But when I clic on postgreSQL tables I have the following log lines ("avvertenza" in italian means "warning") 

ago 13, 2019 5:52:58 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![0,14]: 'object.utility || object.external;' inaccessible or unknown property object
ago 13, 2019 5:52:58 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![18,33]: 'object.utility || object.external;' inaccessible or unknown property object
ago 13, 2019 5:52:58 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![0,13]: 'object.system;' inaccessible or unknown property object
ago 13, 2019 5:52:58 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![1,16]: '!object.canLogin;' inaccessible or unknown property object
ago 13, 2019 5:52:58 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![0,14]: 'object.utility || object.external;' inaccessible or unknown property object
ago 13, 2019 5:52:58 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![18,33]: 'object.utility || object.external;' inaccessible or unknown property object
ago 13, 2019 5:52:58 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![0,13]: 'object.system;' inaccessible or unknown property object
ago 13, 2019 5:52:59 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![1,16]: '!object.canLogin;' inaccessible or unknown property object
ago 13, 2019 5:52:59 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![0,14]: 'object.utility || object.external;' inaccessible or unknown property object
ago 13, 2019 5:52:59 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![18,33]: 'object.utility || object.external;' inaccessible or unknown property object
ago 13, 2019 5:52:59 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![0,13]: 'object.system;' inaccessible or unknown property object
ago 13, 2019 5:52:59 PM org.apache.commons.jexl2.JexlEngine unknownVariable
AVVERTENZA: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![1,16]: '!object.canLogin;' inaccessible or unknown property object

**Comment by serge-rider** [comment] 2019-08-13 16:28
Did I understand correctly that context menu still works in some controls. E.g. SQL editor, data editor, some text controls?

**Comment by cldscchttn** [comment] 2019-08-13 16:35
Yes, it does

**Comment by ianhmh** [comment] 2019-08-13 19:29
I am also having this issue. Just upgraded from 6.1.3 to 6.1.4 on Manjaro. I was asked, and agreed, to convert my settings upon first opening after the upgrade.

I have a workaround at the moment by changing the key binding for context menu in preferences.
Window -> Preferences -> Keys. Search for context menu. Bind Ctrl+F12 In Dialogs and Windows.

This now shows the context menu when triggered using Ctl+F12 in the Database Navigator window.

The issues appears to be the relationship between right click and showing the context menu, and not that context menu just isn't showing in general.

It is not obvious if I can create the right click binding myself.

**Comment by cldscchttn** [comment] 2019-08-14 07:04
workaround works well

**Comment by cldscchttn** [comment] 2019-08-14 07:29
I found another work around.
In Dbeaver if you want rename a table you have to clic on the table with left-clic, just wait same time and re-left-clic. Same steps you can use to rename files in windows.
If you use these steps changing left-clic with right clic, you can open context menu

**Comment by Phr0ztByte** [comment] 2019-08-16 13:40
Have the same issue. And I don't have any "Context Menu" Window -> Preferences -> Keys

**Comment by Mizar01** [comment] 2019-08-20 13:34
Me too.

I have this issue since I updated to version 6.1.5.
The right click context menu only shows randomly and rarely. I couldn't identify the reason why.

It's frustrating, and it's kind of a deal breaker actually, but everything else seems fine so I will try some key binding workaround.

**Comment by schmunk42** [comment] 2019-08-21 11:26
Same here. I am able to access the context menu with a keyboard key (next to `alt gr` on my keyboard) or as described in https://github.com/dbeaver/dbeaver/issues/6489#issuecomment-521135007 ... left click, with some delay, twice, so that I could edit the name. Then I am able to right click.

This applies to **all** entries in DB-Navigator and Projects.

Version: 6.1.4
System: Arch Linux / Gnome 3.32.2

**Comment by cldscchttn** [comment] 2019-08-27 17:34
in 6.1.5 version the problem still remains.

**Comment by Phr0ztByte** [comment] 2019-08-28 10:18
I have downgraded to 6.1.13 on Linu where the problem does not exist. Can confirm that both 6.1.4 and 6.1.5 has the issue.

**Comment by serge-rider** [comment] 2019-08-28 10:32
Still can't reproduce it on any of our test linuxes.

Is there anything in log files (https://github.com/dbeaver/dbeaver/wiki/Log-files) ?
Please send debug log to serge@jkiss.org.

**Comment by megabyte0** [comment] 2019-09-05 10:41
Right click and then right click again in the same place does the job for me, 6.1.15,
no logs either in Window -> Show view -> Error log or log directory.
Ubuntu 16.04.6 LTS, Linux 4.15.0-60-generic x86_64

**Comment by Alexqwesa** [comment] 2019-09-06 08:41
DBeaverCommunity                        6.1.5 
then connect via freerdp (windows to linux)  -  all menu didn't work
on local machine - all menu works

**Comment by eborremans** [comment] 2019-09-09 07:46
> I found another workaround.
> In Dbeaver if you want rename a table you have to clic on the table with left-clic, just wait same time and re-left-clic. Same steps you can use to rename files in windows.
> If you use these steps changing left-clic with right clic, you can open context menu

I think this should give the devs some hint about what is going wrong. It seems to be related to handling the right mouse click event and timing. If you right-click for the second time too quickly it doesn't work. In any case, I can confirm that this workaround works. It is still pretty annoying as I use the context menu very often and 3 seconds waiting time often feels like ages.

**Comment by ngocthienvnn** [comment] 2019-09-11 08:41
It still happens. I have reinstalled my system(Ubuntu 18.04) and installed DBeaver(6.2) via this link: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb and still can not use right click context menu.

**Comment by felangga** [comment] 2019-09-19 04:14
Yes this only happen when you right click too fast ? if you hold right click for a moment, the context menu will appear.

**Comment by eborremans** [comment] 2019-09-20 08:32
> Yes this only happen when you right click too fast ? if you hold right click for a moment, the context menu will appear.
felangga, you are a life saver! You are right, holding the right mouse button is a pretty decent workaround. It is a strange bug and I am pretty sure, it should not work like this, but once you know this workaround the irritation level drops drastically!

**Comment by ngocthienvnn** [comment] 2019-09-20 14:58
> Yes this only happen when you right click too fast ? if you hold right click for a moment, the context menu will appear.

You are right, but it doesn't work with Touchpad

**Comment by aseem-hegshetye** [comment] 2019-09-22 20:36
I keep right clicking continuously and it sometimes works. Now instead of right-clicking on db , I click and then press f4 for edit connection and f3 to open new sql editor. 
But this is annoying.

**Comment by felangga** [comment] 2019-09-23 04:10
Still not fixed in 6.2.1 :(

Felix Angga

E: felangga@gmail.com (https://link.getmailspring.com/link/14F3EB51-5689-4338-A4AF-2ACDAED3430B@getmailspring.com/0?redirect=mailto%3Afelangga%40gmail.com&recipient=cmVwbHkrQURSQTZDQUNSUjNWV1NONzRFTlU0Uk4zU1VPQUhFVkJOSEhCWkVGTUU0QHJlcGx5LmdpdGh1Yi5jb20%3D)
W: http://felangga.blogspot.com (https://link.getmailspring.com/link/14F3EB51-5689-4338-A4AF-2ACDAED3430B@getmailspring.com/1?redirect=http%3A%2F%2Ffelangga.blogspot.com&recipient=cmVwbHkrQURSQTZDQUNSUjNWV1NONzRFTlU0Uk4zU1VPQUhFVkJOSEhCWkVGTUU0QHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by serge-rider** [comment] 2019-09-23 07:57
@felangga It is not.
We still can't reproduce it on our side. And I can't figure out what GTK settings cause this issue.

This glitch appeared after our upgrade to Eclipse platform 2019-06. So I believe it is some bug in SWT-GTK support. Hopefully it'll be fixed in 2019-09 version.

However, we keep trying to localize this bug.

**Comment by felangga** [comment] 2019-09-23 08:06
Thank you for the response.
Maybe I can help to provide some information ?

Felix Angga

E: felangga@gmail.com (https://link.getmailspring.com/link/38E972D8-D800-4A7A-8A1A-23D7A9B57B0C@getmailspring.com/0?redirect=mailto%3Afelangga%40gmail.com&recipient=cmVwbHkrQURSQTZDRElOVFdUWExWN1hLQUVSMzUzU1dXWDdFVkJOSEhCWkVGTUU0QHJlcGx5LmdpdGh1Yi5jb20%3D)
W: http://felangga.blogspot.com (https://link.getmailspring.com/link/38E972D8-D800-4A7A-8A1A-23D7A9B57B0C@getmailspring.com/1?redirect=http%3A%2F%2Ffelangga.blogspot.com&recipient=cmVwbHkrQURSQTZDRElOVFdUWExWN1hLQUVSMzUzU1dXWDdFVkJOSEhCWkVGTUU0QHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by eborremans** [comment] 2019-09-23 11:40
@serge-rider 

I run DBeaver both from windows - where the problem doesn't seem to occur, and in an Oracle Virtualbox (6.0.0 r127566 (Qt5.6.2)) running centos - where is DOES occur. For what it is worth, it may be related to keymappings/interception that take place in the VM. I also assume the VM is much slower and so mouse event timing may also be an influence. 
The reason I am mentioning this is because keeping the right mousebutton pressed DOES show the menu. So I can imagine that the duration for which the mouse needs to be pressed is longer on the vm (due to its relative slowness) than on a native system. Of course showing the context menu should not be mapped to mousedown+duration but just to mousedown (or mouseup?). I don't know how this is implemented in eclipse, but it may give you a hint for where to look next. My apologies for not having more detailed info, but in my experience as tester, when having trouble reproducing issues, at some point you learn to analyse even unlikely possibilities.

**Comment by Phr0ztByte** [comment] 2019-09-24 08:13
@eborremans I am running it on my main workstation with Ubuntu on it. No slowdown.

**Comment by felangga** [comment] 2019-09-25 03:09
What DE you use ? Unity ?

Felix Angga

E: felangga@gmail.com (mailto:felangga@gmail.com)
W: http://felangga.blogspot.com

**Comment by serge-rider** [comment] 2019-09-28 10:01
Please try latest Early Access version (https://dbeaver.io/files/ea/)
It is build on new Eclipse platform. Perhaps this issue will be resolved (at least on some Linuxes).

**Comment by bneff84** [comment] 2019-10-01 22:28
Just installed the EA build on Pop_OS! 19.04 and right click works with a mouse, but not a touchpad. I think this seems to confirm some of the earlier comments that this may be related to the duration of the right click event. The mouse right click works, but a two-finger tap doesn't open the menu for me.

**Comment by Phr0ztByte** [comment] 2019-10-02 08:33
@bneff84 I am using mousepad, so it makes perfect sense to me :)

**Comment by schmunk42** [comment] 2019-10-02 08:36
Regarding https://github.com/dbeaver/dbeaver/issues/6489#issuecomment-523415302 ... I am also using a touch- or track-pad.

**Comment by ianhmh** [comment] 2019-10-02 16:48
After doing some testing. When using a trackpad set up for 2-finger tap = secondary click the context menu does not come up. When I have used an external mouse, the secondary click to trigger the context menu does work. This is on manjaro linux. If it would be useful for me to dig into any of my trackpad/mouse settings, please let me know. This is not may area of expertise, so any guidance would be useful.

**Comment by serge-rider** [comment] 2019-10-05 09:40
I've reproduced this on CentOS 7 on VM.
Context menu is triggered by mouse down event there. Longer mouse down (for 1 second or so) shows menu.
Trying to localize the problem..

**Comment by clhefton** [comment] 2019-10-11 19:23
Similar issue on Mac Mojave 10.14, DBeaver Version 6.2.2.201910061950. Can't right click in the Properties panel of a table.

**Comment by webian** [comment] 2019-10-24 15:48
Same problem. Kubuntu 18.04 + i3 windows manager.
If I **select connection and press F4**, it let me edit the connection and since then I can also right click and it displays the menu.

**Comment by benyaminl** [comment] 2019-11-04 02:40
Confirmed on RHEL 7.7 and CentOS 7.7 and RHEL8 on version 6.15 up to newest version. Is there anyway or work arround? It doesn't respond at all.. so sad..

**Comment by eborremans** [comment] 2019-11-04 09:01
@benyaminl did you try keeping the right mouse button pressed until the menu shows? That currently seems to be a workaround.

**Comment by benyaminl** [comment] 2019-11-04 15:28
Yeah but it will destroy my touch pad. Hahaha.. i have work arround to set the default database ctrl+shift+a

On November 4, 2019 4:01:35 PM GMT+07:00, eborremans <notifications@github.com> wrote:
>@benyaminl did you try keeping the right mouse button pressed until the
>menu shows? That currently seems to be a workaround.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dbeaver/dbeaver/issues/6489#issuecomment-549267009

-- 
Sent from my ASUS Pegasus X005 with K-9 Mail.

**Comment by Salamafet** [comment] 2019-11-06 07:38
Same problem on Linux Mint 19.1 Mate.
I need to make a long press on right click button for the context menu to appear.

**Comment by ngocthienvnn** [comment] 2019-11-06 07:41
It's still not work on Ubuntu 18.04, i'm using touchpad and can not use  right click(two fingers press) to show context menu.

**Comment by benyaminl** [comment] 2019-11-06 09:56
yeah me too but I think only set as active that doesn't work, Or you can open it on new windows and right click on the window, it will work anyway. It can be the work arround for now I think

On Tue, 05 Nov 2019 23:42:09 -0800
ngocthienvnn <notifications@github.com> wrote:

> It's still not work on Ubuntu 18.04, i'm using touchpad and can not
> use  right click(two fingers press) to show context menu.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dbeaver/dbeaver/issues/6489#issuecomment-550186368yea

-- 
Benyamin Limanto

sent from ThinkPad X240 with Claws Mail

**Comment by benyaminl** [comment] 2019-11-07 11:44
yeah me too but I think only set as active that doesn't work, Or you can open it on new windows and right click on the window, it will work anyway. It can be the work arround for now 

On Tue, 05 Nov 2019 23:42:09 -0800
ngocthienvnn <notifications@github.com> wrote:

> It's still not work on Ubuntu 18.04, i'm using touchpad and can not
> use  right click(two fingers press) to show context menu.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dbeaver/dbeaver/issues/6489#issuecomment-550186368yea

-- 
Benyamin Limanto

sent from ThinkPad X240 with Claws Mail

**Comment by serge-rider** [comment] 2019-11-16 12:39
I found the problem eventually. It was caused by clipboard interactions during context menu population.
In some cases it produced a mess in GTK message queue and broke menu popup.

Thanks to everyone for help and workaround proposals.

The fix can be tested in Early Access version (https://dbeaver.io/files/ea). Or just wait for 6.2.5 version release.

**Comment by webian** [comment] 2019-11-16 12:45
@serge-rider just tested 6.2.5 and it works, thanks a lot!
(Kubuntu 18.04 + i3)

**Comment by uslss** [comment] 2019-11-17 09:34
verified (ubuntu 18.10)

**Closed by uslss** 2019-11-17 09:34 UTC
Labels: bug, xo:linux

**Comment by hamatimdotcom** [comment] 2019-11-25 15:00
you can hold right mouse button longer to show context menu

**Comment by felangga** [comment] 2019-11-26 02:27
> you can hold right mouse button longer to show context menu
> it is temp method until new patch released

already fixed on 6.2.5 ea

**Comment by hamatimdotcom** [comment] 2019-11-26 05:06
> > you can hold right mouse button longer to show context menu
> > it is temp method until new patch released
> 
> already fixed on 6.2.5 ea

that's right :+1:
