### ISSUE TITLE
DDL Generation is Wrong for NVARCHAR

### ISSUE THREAD

**Issue by JMarkMurphy** [dbeaver/dbeaver#22139] opened 2023-12-08 22:42 UTC
### Description

SQL Server, Azure ...

DDL Generation is wrong for NVARCHAR (and likely NCHAR) data type. The sys.columns catalog view reports max_length, but, this is in bytes. NVARCHAR and NCHAR use two bytes per character. Unfortunately, the length in the CREATE TABLE statement is in characters, not bytes, so for NCHAR and NVARCHAR, max length is 4000 in create table. But for these fields, max_length in the catalog view reports 8000 instead, and that is dropped directly into the CREATE TABLE without taking into account that max_length is not in characters, but create table requires characters. This results in invalid DDL in certain circumstances.

![image](https://github.com/dbeaver/dbeaver/assets/2379218/f2d2fa29-1c15-4fab-afc0-33ae87676b8f)

In this case, the column choicename is 4000 characters long, and should be defined as nvarchar(4000). The sys.columns view reports max_length as 8000 (in bytes, 2 bytes per character).

There is also a problem in other places as well. metadata does not report the correct length (it says 1Gb) which would be true for NVARCHAR(MAX), and the hover text on result columns reports NVARCHAR(MAX). So it appears that the column information is not being interpreted correctly in a number of cases.

I found this because I was trying to export data from an Azure database into a SQL Server database using Database Tasks, and a number of tables could not be created.

### DBeaver Version

Community Eddition 23.1.1.202306251800

### Operating System

Windows 10

### Database and driver

Azure, and SQL Server 2019
Using Microsoft JDBC driver

### Steps to reproduce

1. Connect to a database that has columns defined as NVARCHAR or NCHAR with a character length between 2001 and 4000.
2. Find one of these tables.
3. Generate DDL, the column length will be generated incorrectly (twice what it should be)
4. Look at the columns in the Database Navigator, you will see columns that have reported lengths longer than the Microsoft stated maximum for these data types (specifically 4000)
5. Try to do a Data Export to another SQL database where the table needs to be created. The job will fail because the length is too big.

**Comment by LonwoLonwo** [comment] 2023-12-11 08:52
Hello @JMarkMurphy 

Thanks for the bug report.

This is a duplicate of the ticket https://github.com/dbeaver/dbeaver/issues/19439
So, I'm closing this one.

**Closed as completed by LonwoLonwo** 2023-12-11 08:52 UTC
Labels: duplicate, xf:datatransfer, xf:metadata, x:azure

**Comment by LonwoLonwo** [comment] 2023-12-11 08:58
If I understand correctly, you are trying to export from Azure to SQL Server. But they have different rules for nvarchar column.
I think it is better to change the data length in data transfer settings here manually: https://github.com/dbeaver/dbeaver/wiki/Data-migration#column-mapping

**Comment by JMarkMurphy** [comment] 2023-12-11 14:02
The rules are the same between Azure and SQL Server for NCHAR, NVARCHAR. 

sys.columns.max_length is the length in bytes for both:

![image](https://github.com/dbeaver/dbeaver/assets/2379218/d7a2b5a4-a977-4de2-85da-2dac321ad321)

![image](https://github.com/dbeaver/dbeaver/assets/2379218/103dc451-8585-42be-b517-5dd691f058b8)

NCHAR(n), NVARCHAR(n) has max 4000 characters in both:

![image](https://github.com/dbeaver/dbeaver/assets/2379218/1f4172b6-0af3-42d9-bb10-1ce24149d699)

![image](https://github.com/dbeaver/dbeaver/assets/2379218/39f2425c-fd0f-4933-a11b-5378925aa615)

DBeaver is setting the parameter wrong when generating DDL. Ticket #19439 is indeed a duplicate, so I will put all further comments there. In any case, I have nearly 1000 tables to migrate. It would not be better to do it manually when dBeaver should be able to generate the DDL correctly.
