### ISSUE TITLE
Vertica - Reading comments table should be optional

### ISSUE THREAD

**Issue by alattke-chwy** [dbeaver/dbeaver#16396] opened 2022-05-03 15:46 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LonwoLonwo** [comment] 2022-05-03 17:59
Duplicate of https://github.com/dbeaver/dbeaver/issues/16397

**Closed as completed by LonwoLonwo** 2022-05-03 17:59 UTC
Labels: duplicate
