### ISSUE TITLE
`Copy as sql` may not use data from selected row when order is apply to data grid

### ISSUE THREAD

**Issue by yyjdelete** [dbeaver/dbeaver#14884] opened 2021-12-13 11:05 UTC
#### System information: 
- Operating system (distribution) and version: win10 x64
- DBeaver version: 21.3.1 and old versions
- Additional extensions

#### Connection specification:
- Database name and version: may not affected, I can reproduce this will pgsql, mssql, sqlite
- Driver name: -
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
For sqlite
1. Init data
```sql
CREATE TABLE NewTable (
	Column1 INTEGER NOT NULL,
	Column2 TEXT
);
INSERT INTO NewTable (Column1,Column2) VALUES
	 (1,'1');
INSERT INTO NewTable (Column1,Column2) VALUES
	 (3,'3');
INSERT INTO NewTable (Column1,Column2) VALUES
	 (2,'2');
```
2. Open the table and order by Column1 in data grid;
![image](https://user-images.githubusercontent.com/1819074/145800704-9a768476-14b3-42c8-8273-c245aa24b833.png)
3. Choose the 2nd line(with Column1=2), right click, click advanced copy/Copy as SQL, but it will get ***the data from the 3rd line***;
```sql
INSERT INTO NewTable (Column1,Column2) VALUES
	 (3,'3');
```

Normal copy(Ctrl+C) works.
Maybe all `advanced copy` not works, not tested.

#### Include any warning/errors/backtraces from the logs
none

**Comment by uslss** [comment] 2021-12-14 08:00
thanks for the report

duplicate of #9252

**Closed as completed by uslss** 2021-12-14 08:00 UTC
Labels: duplicate, xf:datatransfer
