### ISSUE TITLE
(Turn off/change behaviour) of an automatic highlighting of the executed code in sql editor on finish

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35991] opened 2024-10-19 17:04 UTC
### Description

STR:
- execute procedure and continue typing in the same tab while the procedure is being executing.
- when the query has been finished, the executed code in sql editor gets selected automatically, and if a user was typing something at that moment, the selected text will be replaced with the typed text.

It would be more robust if the text is not selected.
It is generally a nice idea to pay attention to the user, but I would suggest **to change the color of its background instead**.
This can be done in the same way as you highlight the background color of the line where the cursor is currently located (now by default it is pale blue).

```
create or replace procedure abc(param1 integer default 5)
language plpgsql
as
$$
--
begin
    perform pg_sleep(param1);
end;
$$
;

call abc(10);

select * 
from film
```

https://github.com/user-attachments/assets/25077f6b-7c46-40ba-98b2-ca5eb26555ce

### DBeaver Version

Enterprise Edition 24.2.4-202410172322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by E1izabeth** [comment] 2024-10-22 08:29
Thanks for the report. I agree that it's inconvenient.
Closing as a duplicate of #18370

**Closed as not planned by E1izabeth** 2024-10-22 08:29 UTC
Labels: duplicate, xf:sql editor, xf:sql execution
