### ISSUE TITLE
Wrong DDL generated for computed columns on SQL Server

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#3486] opened 2018-05-17 07:35 UTC
Create a table with a computed column, e.g.:

```
CREATE TABLE [dbo].[foo](
	[something] [int] NULL,
	[bar]  AS ((3)*[something])
) ON [PRIMARY]
```

Now, generate the DDL for that table in DBeaver. It will look like this:

```
CREATE TABLE foo (
	something int,
	bar int
) go;
```

This is wrong and clearly a bug. Note how `bar` isn't a computed column in DBeaver's result. The entire ` AS ((3)*[something])` part is missing.

**Comment by uslss** [comment] 2020-12-08 12:03
will be implemented in the scope of #3487 
closed as duplicate.

**Comment by ShadelessFox** [comment] 2021-04-18 01:33
Reopening this issue since it is not a duplicate. The referenced issue is about UI, but this one is about invalid SQL.

**Comment by flambchap** [comment] 2021-04-19 08:14
Closing it once again, now as a duplicate of https://github.com/dbeaver/dbeaver/issues/11426.

**Closed by flambchap** 2021-04-19 08:14 UTC
Labels: bug, x:mssql, xf:data
