### ISSUE TITLE
Cell Editor doesn't have 1 button

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10114] opened 2020-10-20 07:40 UTC
#### System information: 
- Operating system (distribution) and version Mac Catalina, Windows
- DBeaver version 7.2.3

#### Connection specification:
- Database name and version PostgreSQL

Mac: Cell Editor doesn't have Save button for both columns where uuid column exists (e.g. dvdrental.public.test_uuid)
Windows: Cell Editor doesn't have Open Editor button only for uuid column (e.g. dvdrental.public.test_uuid)

#### Steps to reproduce, if exist:
1. Open a table with uuid column (e.g. dvdrental.public.test_uuid)
2. Select a cell and press Shift+Enter

Expected: 4 buttons including Save and Open Editor are in the opened window

Actual result:
![Screenshot 2020-10-20 at 10 25 46](https://user-images.githubusercontent.com/51405061/96555525-92274500-12c0-11eb-9e5b-655e2ff7db97.png)

**Comment by serge-rider** [comment] 2020-10-20 20:53
Duplicate of #9964 (i.e. it is caused by the same bug)

**Closed by serge-rider** 2020-10-20 20:53 UTC
Labels: bug, duplicate, x:postgresql
