### ISSUE TITLE
After entering select, there is an extra letter e at the end

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#15943] opened 2022-03-23 05:10 UTC
#### System information: 
- Operating system (distribution) and version
- DBeaver version    DBeaver Enterprise Enterprise Database Manager   22.0.0.202203131528
- Java version  1.8
- Additional extensions

I uploaded a gif format image to illustrate the problem
![20220323130324](https://user-images.githubusercontent.com/43258262/159628220-48aab2e9-acf4-4ec8-80cd-10daef6c0c93.gif)

**Comment by uslss** [comment] 2022-03-23 10:13
looks similar to #15135.

@chazhongbao do you have Hippie Engine enabled?
![image](https://user-images.githubusercontent.com/31996417/159675854-976ded04-7d08-4fef-8e7d-da3cd2f4f8eb.png)

**Comment by ghost** [comment] 2022-03-23 11:20
yes, but when i unchecked it, the problem disappeared

**Comment by ShadelessFox** [comment] 2022-03-23 13:12
So it is indeed a duplicate.

Closing as duplicate of #15135

**Closed as completed by ShadelessFox** 2022-03-23 13:12 UTC
Labels: duplicate, xf:sql
