### ISSUE TITLE
crash on first program start ever

### ISSUE THREAD

**Issue by ellisonch** [dbeaver/dbeaver#22360] opened 2024-01-06 00:27 UTC
### Description

I'm on using dbeaver-ce-23.3.1-x86_64-setup on Windows 10.

I installed and started dbeaver.  It immediately exits (crashes) after only showing the splash screen, with no error message or dialogue box.  Nothing except the splash screen showed up.

The log file contains this:

```
2024-01-05 19:23:31.998 - DBeaver 23.3.1.202312241705 is starting
2024-01-05 19:23:31.999 - OS: Windows 10 10.0 (amd64)
2024-01-05 19:23:32.000 - Java version: 17.0.6 by Eclipse Adoptium (64bit)
2024-01-05 19:23:32.000 - Install path: 'D:\Program Files\DBeaver'
2024-01-05 19:23:32.000 - Instance path: 'file:/C:/Users/ellisonch/AppData/Roaming/DBeaverData/workspace6/'
2024-01-05 19:23:32.002 - Memory available 64Mb/1024Mb
2024-01-05 19:23:32.009 - Create display
2024-01-05 19:23:32.128 - Initialize desktop platform...
2024-01-05 19:23:32.255 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.10.200.v20231102-0934]
> Start Core Resource Management [org.eclipse.core.resources 3.20.0.v20231102-0934]
> Start Team Support Core [org.eclipse.team.core 3.10.200.v20231106-1240]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.121.202312241705]
2024-01-05 19:23:32.452 - 
2024-01-05 19:23:32.453 - 	Refreshing workspace.
2024-01-05 19:23:32.454 - Refreshing workspace contents
2024-01-05 19:23:32.464 - Error injecting field 'platformInstance' in 'org.jkiss.dbeaver.model.impl.app.ApplicationWorkbenchImpl@3d96fa9e'
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.utils.RuntimeUtils.injectComponentReferences(RuntimeUtils.java:651)
	at org.jkiss.dbeaver.utils.RuntimeUtils.getBundleService(RuntimeUtils.java:623)
	at org.jkiss.dbeaver.runtime.DBWorkbench.getApplicationWorkbench(DBWorkbench.java:39)
	at org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform(DBWorkbench.java:45)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:259)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make boolean sun.nio.fs.WindowsFileAttributes.isDirectoryLink() accessible: module java.base does not "opens sun.nio.fs" to unnamed module @2b6fcb9f
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	at org.eclipse.core.internal.filesystem.local.nio.DosHandler.isDirectoryLink(DosHandler.java:80)
	at org.eclipse.core.internal.filesystem.local.nio.DosHandler.fetchFileInfo(DosHandler.java:61)
	at org.eclipse.core.internal.filesystem.local.LocalFileNativesManager.fetchFileInfo(LocalFileNativesManager.java:89)
	at org.eclipse.core.internal.filesystem.local.LocalFile.fetchInfo(LocalFile.java:181)
	at org.eclipse.core.filesystem.provider.FileStore.fetchInfo(FileStore.java:260)
	at org.eclipse.core.internal.utils.FileUtil.realPath(FileUtil.java:136)
	at org.eclipse.core.internal.utils.FileUtil.realURI(FileUtil.java:191)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.setLocation(FileSystemResourceManager.java:1098)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.getStoreRoot(FileSystemResourceManager.java:628)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.getStoreRoot(FileSystemResourceManager.java:631)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.getStore(FileSystemResourceManager.java:585)
	at org.eclipse.core.internal.resources.Resource.getStore(Resource.java:1239)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:101)
	at org.eclipse.core.internal.resources.Project.create(Project.java:305)
	at org.eclipse.core.internal.resources.Project.create(Project.java:291)
	at org.eclipse.core.internal.resources.Project.create(Project.java:286)
	at org.jkiss.dbeaver.registry.EclipseWorkspaceImpl.createDefaultProject(EclipseWorkspaceImpl.java:160)
	at org.jkiss.dbeaver.registry.EclipseWorkspaceImpl.initializeProjects(EclipseWorkspaceImpl.java:77)
	at org.jkiss.dbeaver.core.DesktopPlatform.initialize(DesktopPlatform.java:135)
	... 21 more
2024-01-05 19:23:32.531 - Starting instance server at http://localhost:55293
2024-01-05 19:23:32.545 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.17.200.v20231030-2045]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.4.200.v20231103-2012]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.6.200.v20231030-2045]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.4.200.v20231030-2045]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.14.200.v20231030-2045]
> Start Eclipse e4 core commands [org.eclipse.e4.core.commands 1.1.200.v20231108-1058]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.36.0.v20231002-1156]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.14.200.v20230913-1724]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.5.200.v20231106-1600]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.16.200.v20231030-2045]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.18.100.v20231103-2012]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.15.200.v20231025-0632]
> Start jna [com.sun.jna 5.13.0.v20230812-1000]
2024-01-05 19:23:38.823 - Event loop exception
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.app.DBPPlatform.getQueryManager()" because "org.jkiss.dbeaver.model.qm.QMUtils.application" is null
	at org.jkiss.dbeaver.model.qm.QMUtils.getDefaultHandler(QMUtils.java:62)
	at org.jkiss.dbeaver.model.runtime.features.DBRFeatureRegistry.useFeature(DBRFeatureRegistry.java:98)
	at org.jkiss.dbeaver.model.runtime.features.DBRFeature.use(DBRFeature.java:123)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchAdvisor.preStartup(ApplicationWorkbenchAdvisor.java:231)
	at org.eclipse.ui.internal.Workbench$20.runWithException(Workbench.java:1754)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4802)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1750)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2854)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:641)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:287)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
2024-01-05 19:23:38.836 - DBeaver is stopping
2024-01-05 19:23:38.847 - Stop instance server
2024-01-05 19:23:39.882 - Instance server has been stopped
2024-01-05 19:23:39.888 - DBeaver shutdown completed
```

I tried uninstalling, reinstalling (and clearing user data on install) and it still crashes on startup.

### DBeaver Version

Community 23.3.1

### Operating System

Windows 10

**Comment by E1izabeth** [comment] 2024-01-07 10:11
Is your workspace directory a link?
According to the log files, your issue looks like exactly like this one #22325

**Comment by ellisonch** [comment] 2024-01-07 17:15
> Is your workspace directory a link? According to the log files, your issue looks like exactly like this one #22325

Not the workspace directory itself, but part of its path.  My system's `%appdata%` is set to `C:\Users\username`, and `C:\Users\username` is itself a symbolic link to `d:\users\username`

**Comment by E1izabeth** [comment] 2024-01-07 17:18
Thank you for reply. Please move workspace to any place with path, not containing links, as a temporary workaround.
I'll close this issue as a duplicate of #22325 to keep all cases in one place. We're going to fix it.

**Closed as not planned by E1izabeth** 2024-01-07 17:18 UTC
Labels: duplicate

**Comment by bianyun** [comment] 2024-01-08 07:00
@ellisonch 
I got the same issue, and the root cause in the log file is :

> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make boolean sun.nio.fs.WindowsFileAttributes.isDirectoryLink() accessible: module java.base does not "opens sun.nio.fs" to unnamed module @262816a8

The work around is simple: add one line config in dbeaver.ini:

> --add-opens=java.base/sun.nio.fs=ALL-UNNAMED
