### ISSUE TITLE
copy empty string from table data grid does not function

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#13915] opened 2021-09-15 11:41 UTC
#### System information: 
- Operating System: Windows
- DBeaver version 21.2.0

When a cell in the table data grid is selected it is possible to copy its value. This does not function when the cell contains an empty string (or NULL value). After select Copy the content of the copy-buffer still has the same value as before making a copy.

**Comment by uslss** [comment] 2021-09-15 12:06
closed as a duplicate of #6802

**Closed as completed by uslss** 2021-09-15 12:06 UTC
Labels: enhancement, duplicate
