### ISSUE TITLE
PostgreSQL problem with $$

### ISSUE THREAD

**Issue by PBekleshov** [dbeaver/dbeaver#7566] opened 2020-01-08 07:00 UTC
#### System information: 
- Operating system (distribution) and version Windows 8.1
- DBeaver version 6.3.2
- Additional extensions

#### Connection specification:
- Database name and version PostgreSQL 11.5
- Driver name PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Large procedures dos not compile
The problem with $$
Tries to work out part of the procedure and does not reach the closing $$

**Comment by serge-rider** [comment] 2020-01-08 07:57
Can't reproduce. Please post an example of such query.
(most of problems with $$ were fixed in 6.3.2)

**Comment by PBekleshov** [comment] 2020-01-08 08:02
The problem appeared in version 6.3.2. After the upgrade, I was unable to compile some of my procedures.
In the previous version, everything worked.
Unfortunately, I can’t provide the procedure code in connection with the company's security policy.

**Comment by serge-rider** [comment] 2020-01-09 04:21
Sorry, but I can't fix it as I can't reproduce this.

**Closed by serge-rider** 2020-01-09 04:21 UTC
Labels: bug, can't reproduce, x:postgresql
