### ISSUE TITLE
Mac os 13.0 Beta (22A5331f) can not open menu and right menu

### ISSUE THREAD

**Issue by hktalent** [dbeaver/dbeaver#17605] opened 2022-09-09 04:18 UTC
### Description

Mac os 13.0 Beta (22A5331f) can not open menu and right menu

### DBeaver Version

22.2

### Database and driver

mysql

### Steps to reproduce

Mac os 13.0 Beta (22A5331f) can not open menu and right menu

### Additional context

<img width="658" alt="image" src="https://user-images.githubusercontent.com/18223385/189270849-89a5b593-54a7-4dcc-be3a-3cc69b5f5587.png">

**Comment by LonwoLonwo** [comment] 2022-09-09 06:50
Hello @hktalent 

Thanks for the bug report.

DBeaver is based on the Eclipse platform, and this is the Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=580322

It seems to be fixed already, but this fix will only be available in our product in Autumn with the new Eclipse release.

As a workaround, you can now use DBeaver versions <= 22.1.0.

I am closing this as a duplicate of https://github.com/dbeaver/dbeaver/issues/17204

**Closed as not planned by LonwoLonwo** 2022-09-09 06:50 UTC
Labels: xo:macos, xf:ui
