### ISSUE TITLE
upgrade lost installed plugins

### ISSUE THREAD

**Issue by wonb168** [dbeaver/dbeaver#35537] opened 2024-09-10 22:49 UTC
### Description

I upgrade Dbeaver version，but installed plugins all lost，need download and install again，why？

### DBeaver Version

24.1.4

### Operating System

macos 14.6.1

### Steps to reproduce

1. download office plugin
2. upgrade to newest version
3. office plugin lost

**Comment by E1izabeth** [comment] 2024-09-11 07:13
Thank you for the request.
I'm closing it as it's a duplicate of #5317

**Closed as not planned by E1izabeth** 2024-09-11 07:13 UTC
Labels: duplicate
