### ISSUE TITLE
Column metadata does not update

### ISSUE THREAD

**Issue by WolfX2** [dbeaver/dbeaver#12752] opened 2021-06-07 06:42 UTC
#### System information: 
- Operating system (distribution) and version, Windows 10, Windows server 2012
- DBeaver version 21.0.5
- Java version - included JRE
- Additional extensions none

#### Connection specification:
- Database name and version: Oracle 12
- Driver name Oracle.jdbc.oracledriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

The column metadata pane shows the columns from the last query run, instead of the current query. If you run the current query again, it will update correctly.

**Comment by kseniiaguzeeva** [comment] 2021-06-07 06:50
Could you please provide me with steps to reproduce? It will help me to assess the issue and find a solution.

**Comment by uslss** [comment] 2021-06-07 11:25
seems to be duplicate of #11639 .
The issue will be fixed in 21.1.1.
anyway, thanks for the report

**Closed as completed** 2021-06-07 11:25 UTC
Labels: duplicate, wait for response, xf:metadata
