### ISSUE TITLE
Find and Replace Function Jumps to the End of Editor After Operation

### ISSUE THREAD

**Issue by ufuk-ergin-carbon** [dbeaver/dbeaver#29888] opened 2024-05-06 15:49 UTC
### Description

When you perform a find and replace on a selection of code, the editor navigation jumps to the very end of the file. Isn't expected to stay where you are? Attaching the screen recording.

### DBeaver Version

Version 24.0.4.202405051837

### Operating System

MacOs Sonoma 14.4.1 (23E224)

### Database and driver

Server: Snowflake 8.17.3
Driver: Snowflake 3.14.4

https://github.com/dbeaver/dbeaver/assets/114302087/01c28645-eb46-4d8a-acfd-b2c8e5f2aeb3

### Steps to reproduce

1. At the beginning or mid-through your editor, select a part of code where you will perform find and replace operation.
2. Open the Find and Replace window by pressing CMD+F. Select the operation that you want to perform.
3. Click on Find and Replace All. 
4. The editor jumps to the very end of the file and you'll have to navigate and find the part of the code that you performed the operation.

**Comment by E1izabeth** [comment] 2024-05-07 07:31
I tested on Windows and it's not happening for me. Maybe this issue exists only on MacOS

UPDATE: Reproduced, just it happens not every time for me.

**Comment by E1izabeth** [comment] 2024-05-07 07:47
Seems it just replaces in whole text. I'll close this issue as a duplicate of #29886
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-05-07 07:47 UTC
Labels: duplicate, xf:sql editor

**Comment by ufuk-ergin-carbon** [comment] 2024-05-07 13:02
OK, Thanks, will do.
