### ISSUE TITLE
dBeaver stopped responding when closing SQL editor tabs

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#19437] opened 2023-03-20 17:55 UTC
### Description

while transversing open SQL editor tabs, dBeaver took up most of the CPU and went white.

Created the below thread dump and had to manually kill the process in Task Manager.

[thread-dump_2023-03-20.txt](https://github.com/dbeaver/dbeaver/files/11021417/thread-dump_2023-03-20.txt)

### DBeaver Version

Community Edition 23.0.0

### Operating System

Windows 10

### Steps to reproduce

dBeaver was open
there were a number of SQL editor tabs open
I was navigating between them
dBeaver froze

**Comment by Destrolaric** [comment] 2023-03-30 13:28
@coleman-rik Hi, could you retake the thread dump it looks like it was made when the app was initializing when the freeze happened.

**Comment by coleman-rik** [comment] 2023-03-30 17:50
@Destrolaric , 
I don't understand your request.  I can't take another at this point because it is no longer doing that.
The thread dump was taken **after** the UI froze, while it was white an unresponsive.

**Comment by arhayka** [comment] 2023-04-06 13:10
@coleman-rik Thank you for your report.

**Comment by serge-rider** [comment] 2023-04-06 14:33
Can't reproduce and there not hints in the thread dump. It may be an Eclipse bug, I may assume that bug was caused by a big number of events in window proc.

**Comment by E1izabeth** [comment] 2023-04-10 12:49
Probably will be fixed in #19553

**Comment by serge-rider** [comment] 2023-04-17 11:52
@coleman-rik please reopen if it will happen again

**Closed as completed by serge-rider** 2023-04-17 11:52 UTC
Labels: can't reproduce
