### ISSUE TITLE
DBeaver crashes on loading geometry of any size (PostGIS)

### ISSUE THREAD

**Issue by moiz-i-am** [dbeaver/dbeaver#18332] opened 2022-11-25 11:41 UTC
### Description

DBeaver is crashing every time I click on the spatial data view window after the update of macOS from 12.6 monetary to 13 Ventura.

Don't know what's going on. 

Also tried installing different versions of DBeaver but the problem remains still.

### DBeaver Version

Community Edition

### Operating System

macOS 13.0.1 Ventura

### Database and driver

Database version: PostgreSQL 14.5
PostGIS version: 2.5 and 3.1

**Comment by Destrolaric** [comment] 2022-11-25 11:43
Hi, the issue is a duplicate of https://github.com/dbeaver/dbeaver/issues/18117

**Closed as not planned** 2022-11-25 11:43 UTC
Labels: duplicate
