### ISSUE TITLE
After updating the Community edition of Dbeaver to 7.0.4 it stopped asking to save the SQL scripts before closing & hence many times I am closing the Dbeaver & accidentally loosing all of my changes that i have done on the SQL scripts.

### ISSUE THREAD

**Issue by dhirajkumarsinha27091982** [dbeaver/dbeaver#8630] opened 2020-05-05 15:24 UTC
After updating the Community edition of Dbeaver to 7.0.4 it stopped asking to save the SQL scripts before closing & hence many times I am closing the Dbeaver & accidentally loosing all of my changes that i have done on the SQL scripts.

**Comment by uslss** [comment] 2020-05-05 15:28
seems to be duplicate of  #8617 
anyway, thanks for the bug report

**Closed by uslss** 2020-05-05 15:28 UTC
Labels: bug, duplicate
