### ISSUE TITLE
Indexes are shown in Simple View

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9153] opened 2020-07-03 11:21 UTC
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.2

#### Connection specification:
- Database name and version SQLite

#### Describe the problem you're observing:
Indexes are shown when Simple view (or Custom view where Options Show only Tables and Views and Hide Folders options are checked) is enabled 
![image](https://user-images.githubusercontent.com/31996417/86464588-77908680-bd38-11ea-90e3-035923b82b75.png)

**Comment by serge-rider** [comment] 2020-07-07 09:44
Duplicate of #9164

**Closed by serge-rider** 2020-07-07 09:44 UTC
Labels: bug, x:sqlite, xp:major
