### ISSUE TITLE
Search Proposals takes too long

### ISSUE THREAD

**Issue by SaulR** [dbeaver/dbeaver#15489] opened 2022-02-14 16:03 UTC
#### System information: 
- Operating system (distribution) and version Windows Server 2016 Version 1607
- DBeaver version  21.3.4.202202051448
- Additional extensions

#### Connection specification:
- Database name and version AWS Postgres
- Driver name PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When typing in a statement such as 
SELECT a, * FROM table
The Search Proposal runs and runs without giving any dropdowns until it's done.  And worse, when it finally completes, it pops up the suggestions above any other window I have open.

#### Steps to reproduce, if exist:
Try SELECT * FROM table
then before the *, try to find a particular field in table by typing the first few characters

**Comment by E1izabeth** [comment] 2022-02-16 13:06
Hi, @SaulR! Thank you for the report. Could you, please, tell us how many columns in this table and which queries are executed while searching proposals? You can find executed queries in Query manager (Window>Show view>Query manager).

**Comment by SaulR** [comment] 2022-02-16 13:09
It's all of them.

For example, I started typing 
select * from n 
(where we have several tables that start with "n")
and the Search Proposals began, presumably to offer the table choices as it did before the last update.

That was before I started typing this and it's still running.

**Comment by SaulR** [comment] 2022-02-16 13:13
And now the results popped up in front of another window I had switched to.

**Comment by flambchap** [comment] 2022-02-23 13:08
Could you please send us a screenshot of the query manager? Thanks.

**Comment by SaulR** [comment] 2022-02-23 13:21
![dBeaver Query Manager](https://user-images.githubusercontent.com/36461031/155327508-4c623237-8ac5-4b59-98db-54687a0b312c.PNG)

**Comment by SaulR** [comment] 2022-02-25 13:38
Here's another screenshot I can share which may help.

I don't know why it's pulling in these values.  Those aren't fields in the table in question.

I used to only get table names or column names.  Now I'm getting all of these as well when the query finally finishes running.

![image](https://user-images.githubusercontent.com/36461031/155724523-04e33edf-b434-4caa-a2a9-bf26a877310c.png)

**Comment by dkbarn** [comment] 2022-03-02 02:38
Any movement on this?

I'm experiencing this behavior too and came here just to file this issue. It started happening after upgrading from 21.0.1 to 21.3.5, and it's so annoying to have this auto-pop appear minutes after executing a query, on top of another window I've switched to. I'm considering downgrading back down to 21.0.1

The Query Manager does not log the queries executed when searching proposals, even if I check every Query Type in the Query Manager settings. However if I switch to the Background Tasks tab when it is searching proposals, it says: "Searching proposals... Seeking for SQL completion proposals: Find proposals." This message lasts for several seconds, and finally the pop-up appears.

**Comment by SaulR** [comment] 2022-03-07 13:06
I have upgrade to 22.0.0.202203060510 and the problem is still happening

**Comment by guardiande** [comment] 2022-03-20 21:25
Same here. I just upgraded to 22.0.1 hoping that it would resolve the issue but no dice.

I'm running on Win 10 connecting to a local Postgres database.

The responses are not always slow but even if they're quick the completed table names screw with what I had typed before.

Reducing the settings in the Query Manager seemed to help but testing around more makes me think it was wishful thinking.

**Comment by rproserpio** [comment] 2022-03-24 14:07
Same exact issue here. On Linux with remote mysql dbs.

**Comment by flambchap** [comment] 2022-03-24 14:19
Hi everyone. I think the issue is caused by the Hippie Engine. I suggest disabling Hippie Engine. To do that, please follow the steps below:

1. Open Preferences (Window -> Preferences).
2. Open the ‘Code Completion’ tab (Editors -> SQL Editor -> Code Completion).
3. On the tab, disable the ‘Activate Hippie Engine for autocompletion’ checkbox.

**Comment by SaulR** [comment] 2022-03-24 14:22
Initial try of that is looking good!
I'll report back later today with a more-usage update.

Thanks akilovich!

**Comment by flambchap** [comment] 2022-03-24 14:23
I'll call it a duplicate of https://github.com/dbeaver/dbeaver/issues/15820.

**Closed as completed by flambchap** 2022-03-24 14:23 UTC
Labels: duplicate, xf:sql

**Comment by SaulR** [comment] 2022-03-24 14:25
That one's really a duplicate of mine :P

**Comment by charlbury** [comment] 2022-04-12 07:43
Same issue for me, resolved by turning of Hippie engine. What do we lose when the Hippie engine is turned off?

**Comment by Destrolaric** [comment] 2022-04-12 08:10
@charlbury Hippie looks for proposals with the same prefix in the current script file. If the script file is big enough, it can cause long loading times.
