### ISSUE TITLE
MSSQL Parameters unable to enter

### ISSUE THREAD

**Issue by TerranOP** [dbeaver/dbeaver#5659] opened 2019-04-04 19:10 UTC
#### System information: 
- Linux Mint 19.1
- DBeaver version 6.0.1
- Java version 10.0.2
- Additional extensions

#### Connection specification:
- Microsoft SQL Server 11.00.3128
- Microsoft JDBC Driver 7.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Can't enter a value when binding parameters. Dbeaver 6.0 worked - 6.0.1 doesn't. Every time I click on the 'value' cell it inserts the 2 entries below in the log file. Reinstalled 6.0 from archive.
e.g. Select * from [table] where id = :id 
#### Steps to reproduce, if exist:
Install 6.0.1 and run a query with a parameter and attempt to enter a value.

#### Include any warning/errors/backtraces from the logs

!ENTRY org.eclipse.ui 4 0 2019-04-04 13:06:48.892
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1069)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:888)
	at org.eclipse.swt.custom.ControlEditor.layout(ControlEditor.java:218)
	at org.eclipse.swt.custom.TableEditor.layout(TableEditor.java:266)
	at org.eclipse.swt.custom.ControlEditor.setEditor(ControlEditor.java:246)
	at org.eclipse.swt.custom.TableEditor.setEditor(TableEditor.java:241)
	at org.eclipse.swt.custom.TableEditor.setEditor(TableEditor.java:257)
	at org.jkiss.dbeaver.ui.controls.CustomTableEditor.showEditor(CustomTableEditor.java:111)
	at org.jkiss.dbeaver.ui.controls.CustomTableEditor.lambda$0(CustomTableEditor.java:82)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4475)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:822)
	at org.eclipse.jface.window.Window.open(Window.java:798)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob$1.runTask(SQLQueryJob.java:661)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob$1.runTask(SQLQueryJob.java:1)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:25)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:34)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4475)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:184)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-04-04 13:06:48.905
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-04-04 13:06:48.905
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1069)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:888)
	at org.eclipse.swt.custom.ControlEditor.layout(ControlEditor.java:218)
	at org.eclipse.swt.custom.TableEditor.layout(TableEditor.java:266)
	at org.eclipse.swt.custom.ControlEditor.setEditor(ControlEditor.java:246)
	at org.eclipse.swt.custom.TableEditor.setEditor(TableEditor.java:241)
	at org.eclipse.swt.custom.TableEditor.setEditor(TableEditor.java:257)
	at org.jkiss.dbeaver.ui.controls.CustomTableEditor.showEditor(CustomTableEditor.java:111)
	at org.jkiss.dbeaver.ui.controls.CustomTableEditor.lambda$0(CustomTableEditor.java:82)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4475)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:822)
	at org.eclipse.jface.window.Window.open(Window.java:798)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob$1.runTask(SQLQueryJob.java:661)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob$1.runTask(SQLQueryJob.java:1)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:25)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:34)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4475)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:184)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
![working](https://user-images.githubusercontent.com/23221953/55581779-faacd200-56da-11e9-8391-fdd5f6dc5d1b.png)
![cantbindparameters](https://user-images.githubusercontent.com/23221953/55581797-08faee00-56db-11e9-8772-e98fe3355f80.png)

**Comment by a-baturin** [comment] 2019-04-05 14:02
Same here, Fedora 29, Spark database, java.version=1.8.0_201

**Comment by tati-kru** [comment] 2019-04-05 14:23
It's a duplicate of https://github.com/dbeaver/dbeaver/issues/5585. Please, try 6.0.2 EA  version.

**Closed** 2019-04-05 14:54 UTC
Labels: bug, duplicate
