### ISSUE TITLE
Advanced copy => Advanced paste => save => error.

### ISSUE THREAD

**Issue by google007049** [dbeaver/dbeaver#17339] opened 2022-08-12 05:04 UTC
### Description

Advanced copy => Advanced paste => save => error on Grid
Upload the video.

I uploaded this question before, but I am uploading it again with a video attached.

Thank you for your interest.

https://user-images.githubusercontent.com/58673078/184288145-04ce03f8-6aed-4920-b509-f4e145635705.mp4

### DBeaver Version

community edition 22.1.4.202208051447

### Operating System

Windows10

### Database and driver

oracle 11g

**Comment by LonwoLonwo** [comment] 2022-08-12 07:52
Ok, thanks @google007049 

Close as duplicate of https://github.com/dbeaver/dbeaver/issues/17210

**Closed as not planned by LonwoLonwo** 2022-08-12 07:52 UTC
