### ISSUE TITLE
DBeaver 5.2.4 - Output of to_char() calls in text mode output

### ISSUE THREAD

**Issue by yoda-br** [dbeaver/dbeaver#4571] opened 2018-11-07 18:40 UTC
- Bug report

In DBeaver 5.2.4 there is a problem with the output of to_char() calls in text mode output.

The last character of the field value is supressed on the output only when the to_char() function is used and the output is selected to text mode.

This behavior not happened in previous versions...

See the screenshots attached.

This is the Oracle database where I'm connected:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Productio
PL/SQL Release 11.2.0.4.0 - Production
CORE	11.2.0.4.0	Production
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production

![image](https://user-images.githubusercontent.com/44846614/48152151-dc64b680-e2a1-11e8-94fa-2f9ad3c05ba8.png)

![image](https://user-images.githubusercontent.com/44846614/48152526-e89d4380-e2a2-11e8-966c-fd9d6f2676a4.png)

**Comment by MocniMax** [comment] 2018-11-08 11:58
Hi,

Not only when to_char is used and not only with Oracle.
I am using DB2 LUW and zOS and each result set column in Text view is truncated by one character when column Label is shorter than column content.
Export to TXT works correctly.

**Comment by yoda-br** [comment] 2018-11-09 18:40
> 
> 
> Hi,
> 
> Not only when to_char is used and not only with Oracle.
> I am using DB2 LUW and zOS and each result set column in Text view is truncated by one character when column Label is shorter than column content.
> Export to TXT works correctly.

Really, fellow MocniMax. I realized this today.

**Comment by serge-rider** [comment] 2018-11-09 19:30
Duplicate of #4547 (see fix in 5.2.5)
Thanks for the bug report anyway

**Closed by serge-rider** 2018-11-09 19:30 UTC
Labels: bug, duplicate
