### ISSUE TITLE
Cant Create New Connection

### ISSUE THREAD

**Issue by binarytracer** [dbeaver/dbeaver#11791] opened 2021-03-19 08:48 UTC
#### System information: 
- Operating system (distribution) and version : Ubuntu 18.04.5 LTS
- DBeaver version: 21.0.0
- Additional extensions: none

#### Connection specification:
- Database name and version: mysql 8.0.23 ( Mysql Community Server, docker )
- Driver name: 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? nope

#### Steps to reproduce, if exist:
1. Open the DBeaver 21.0.0, then right on on the Database Navigator -> click Create -> click Connection.
2. And this is what I get.
![image](https://user-images.githubusercontent.com/8814442/111753852-49f16a80-88d2-11eb-8967-99e9a752384e.png)

### Thing to Achieve
 I want to use Dbeaver to connect to my running Mysql Server.

### Existing PostgreSQL Connections
- Are all working, I have them already before i upgrade to the current version.

### More Screenshot
![image](https://user-images.githubusercontent.com/8814442/111754400-eb78bc00-88d2-11eb-9697-a0f902a8925a.png)

**Comment by ShadelessFox** [comment] 2021-03-19 09:23
Hello @binarytracer,

I cannot reproduce your issue. 

Dumb, but sometimes a working suggestion - have you tried restarting DBeaver? Otherwise, can you try the [EA](https://dbeaver.io/files/ea/) version?

If the issue still can be reproduced, please provide the [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by LonwoLonwo** [comment] 2021-03-19 10:30
Hello @binarytracer
This ticket is duplicate of #11646
And answer was:
"This bug is already fixed. We've released hotfix version right after 21.0 release.
Just re-download it from dbeaver.io."

**Closed as completed by LonwoLonwo** 2021-03-19 10:30 UTC
Labels: duplicate

**Comment by binarytracer** [comment] 2021-03-19 13:07
what i did to fix this done is, reinstall the new one :)
