### ISSUE TITLE
Zoom buggy since 22.3.5

### ISSUE THREAD

**Issue by Moridin11** [dbeaver/dbeaver#19600] opened 2023-04-04 13:45 UTC
### Description

I frequently use CTRL + + and CTRL + - to zoom in and out.  After I recently upgraded to 22.3.5 and subsequently 23.0.1 the zoom will stop working.  Behind the scenes I think it still works but it doesn't refresh the view anymore, but then once I restart DBeaver it will be at whatever zoom it was supposed to be at.

I haven't been able to pinpoint a reason for it to stop working.

### DBeaver Version

23.0.1 / 22.3.5

### Operating System

Windows 11

### Database and driver

JDBC Driver 42.2.23

### Steps to reproduce

Open DBeaver (I have scripts saved that automatically open haven't figured out if this matters or not)
Zoom in (to verify it is working)
Go to Projects and double click a project to open it on the right panel.
Close the Projects view that just opened
Attempt to zoom in again. (should not zoom in)
Restart DBeaver (the zoom should be what it was supposed to be)

**Comment by E1izabeth** [comment] 2023-04-04 15:31
Thank you for bug report.
It's a known issue, so I'm closing it as a duplicate of #19521

**Closed as not planned by E1izabeth** 2023-04-04 15:31 UTC
Labels: duplicate
