### ISSUE TITLE
Problem with Spanish/Catalan keyboard in v23.0.5

### ISSUE THREAD

**Issue by catarineu** [dbeaver/dbeaver#20056] opened 2023-05-23 08:44 UTC
### Description

In the SQL editor I cannot write the '|' (pipe), '@' (at) and '#' (hashtag) symbols using the Cmd+1, Cmd+2 and Cmd+3 usual combinations. I'm using MacOS 13.4 and DBeaver 23.0.5

Surprisingly, I can write without problems symbols like '{' which requires also the Cmd+... combination.

The affected keys work perfectly in all the other macOS apps, and they used to work perfectly also in DBeaver until now.

### DBeaver Version

23.0.5

### Operating System

macOS 13.4

### Database and driver

Not rellevant. The problem is in the SQL editor

### Steps to reproduce

Edit a file and try to type '@'

**Comment by E1izabeth** [comment] 2023-05-23 09:07
Thank you for bug report.
I'm closing it as a duplicate of  #19907. Please follow that issue to be notified about updates.

**Closed as not planned by E1izabeth** 2023-05-23 09:07 UTC
Labels: xo:macos, xf:sql
