### ISSUE TITLE
Table last update info

### ISSUE THREAD

**Issue by JoaoMoro** [dbeaver/dbeaver#19414] opened 2023-03-17 16:27 UTC
I'm new to dbeaver and I don't know if there's a way, if there is please tell me how, but how can I see the last time a specific table was updated?

**Comment by ftsfranklin** [comment] 2023-03-17 18:18
What database are you using?

If it's Oracle, it's a duplicate of #11179.

If it's not, then @ShadelessFox said,
> Not every database offer such information, so we can't retrieve it and display somewhere.

**Comment by JoaoMoro** [comment] 2023-03-17 18:47
I am using SQL SERVER

**Comment by LonwoLonwo** [comment] 2023-03-20 14:35
Hello @JoaoMoro 

Now we do not have representation of this info for SQL server tables.

We can add your request to our backlog.

For now, you can use this query:

`select * FROM master.sys.all_objects o WHERE o.type IN ('U','S','V','TT') AND o.schema_id = 1`

with your schema id (you cab find it with double click on the schema object in the database navigator)

**Closed as completed** 2024-02-21 10:49 UTC
Labels: x:mssql, sp:1, xf:metadata
