### ISSUE TITLE
Two versions of Oracle show up in connections and can't connect now.

### ISSUE THREAD

**Issue by kruncheee** [dbeaver/dbeaver#2809] opened 2018-01-19 00:05 UTC
My work upgraded to Oracle 12c but from what I can tell they just renamed the folder that oracle 11g was installed to and installed the newer version. dbeaver is still looking for 11g even after I choose the 12 client. I get a invalid username/password message when I test the connection.

Here's the part of the error log that shows it looking for a folder that doesn't exist. 
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
2018-01-18 15:59:06.003 - Unrecognized Oracle client version at C:\oracle\product\11.2.0\client_1
2018-01-18 15:59:06.081 - Unrecognized Oracle client version at C:\oracle\product\11.2.0\client_1

**Comment by serge-rider** [comment] 2018-01-24 16:41
Basically you need native client only for sqlplus invocations (which are usually not used).
Invalid user/password error can't be related to local client settings.

**Comment by kruncheee** [comment] 2018-01-25 19:52
So I tried it on another computer that only ever had Oracle 12c installed and on connection setup and test I get the invalid user/password. We recently switch to using AD for username and passwords too.  I'm not running any SQL just trying to make a connection.

**Comment by serge-rider** [comment] 2018-01-29 02:14
I think you need to ask your DBA about new connection settings/user credentials. 
This is definitely not a bug in DBeaver.
Closing as non-reprroducible

**Closed by serge-rider** 2018-01-29 02:14 UTC
Labels: can't reproduce, question
