### ISSUE TITLE
rpm can't be installed

### ISSUE THREAD

**Issue by kurdt2507** [dbeaver/dbeaver#4182] opened 2018-09-10 18:28 UTC
Hi, I have a problem updating dbeaver CE through the RPM package; I get the following message:
error: dbeaver-ce-5.2.0-stable.x86_64.rpm: tag[34]: BAD, tag 1096 type 5 offset 48168 count 745 len 2980.
I have Fedora 28 to 64 bits.
Thanks in advance.

**Comment by serge-rider** [comment] 2018-09-10 19:27
Duplicate of #4177

**Closed by serge-rider** 2018-09-10 19:27 UTC
Labels: bug, duplicate, xo:linux
