### ISSUE TITLE
Find/Replace window doesn't open in procedure/function source window after being opened it in SQL Editor

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#9189] opened 2020-07-07 14:12 UTC
#### System information: 
- Operating system (distribution) and version: Windows Server 2016 Datacenter 64-bit
- DBeaver version: 7.1.2.202007051953
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11 on Aurora RDS
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Find/Replace window doesn't open in procedure/function source window after being opened it in SQL Editor

#### Steps to reproduce, if exist:
1. open a procedure/function source
2. open a new/existing SQL editor
3. press CTRL+F to open Find/Replace window and close it
4. switch to procedure/function source and press CTRL+F again to see the issue

#### Workaround
Click on the procedure/function tab name and press CTRL+F again

**Comment by uslss** [comment] 2020-07-08 17:57
thanks for the bug report

**Comment by serge-rider** [comment] 2020-07-24 14:35
Duplicate of #8927 (and also hard to reproduce)

**Closed by serge-rider** 2020-07-24 14:35 UTC
Labels: bug, duplicate

**Comment by serge-rider** [comment] 2020-07-25 09:32
Fixed in #9191
