### ISSUE TITLE
Raise not working on latest version for any level except EXCEPTION

### ISSUE THREAD

**Issue by Maxine-van-der-Smissen** [dbeaver/dbeaver#21946] opened 2023-11-22 11:49 UTC
### Description

Since updating to the latest version (23.2.5-x86_64) of DBeaver earlier on Windows, my testing scripts weren't raising any notices anymore. Reverting to version 23.2.4-x86_64 brought this behavior back.
The 'EXCEPTION' level does still lead to a SQL ERROR which stops execution in the same way as on version 23.2.4.

I can easily reproduce it by updating to the latest version, and fix it again by simply running the installer for 23.2.4-x86_64.

### DBeaver Version

Community Edition 23.2.5

### Operating System

Windows x86_64

### Database and driver

Database: PostgreSQL 9.6.16
Driver: PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

1. Connect to the database (both on version 23.2.4 and 23.2.5 of DBeaver Community Edition);
2. Open a SQL script;
3. Write a DO block with a RAISE command in it such as the following:
```sql
DO
LANGUAGE plpgsql
$$
BEGIN
    RAISE NOTICE 'This is a test notice';
END;
$$;
```
4. Execute the script;
5. The Server Output window should pop up (default settings) and the notice is visible on version 23.2.4, opening the window on version 23.2.5 leads to an empty panel without any message in it however.

**Comment by E1izabeth** [comment] 2023-11-22 11:51
Thank you for bug report. I'm closing it as a duplicate of #21902

**Closed as not planned by E1izabeth** 2023-11-22 11:51 UTC
Labels: duplicate
