### ISSUE TITLE
Export from query option returns an extremely large popup dialog

### ISSUE THREAD

**Issue by dswpersonal** [dbeaver/dbeaver#34776] opened 2024-07-11 12:21 UTC
### Description

Using the export from query option now returns an extremely large popup dialog.  The popup opens normally and then expands horizontally.   It is possible to resize the window down to a usable size after many drag and drop attempts.  Here is an example of the screen after it expands.

<img width="1728" alt="image" src="https://github.com/dbeaver/dbeaver/assets/175313564/238508b9-ae48-4b77-91b8-35258da1c9ef">

### DBeaver Version

Community Version 24.1.2.202407071610

### Operating System

macOS Sonoma Versionn 14.5

### Database and driver

Aurora PostgreSQL Engine Version 13.12
PostgreSQL JDBC Driver Version 42.7.2

### Steps to reproduce

(1) A query like the following:

select id1, id2 
from id2_table
where id1 in ('0193jdh3hdj3hdnhhdnbwhwhdh37292',
'0293jdh3hdj3hdnhhdnbwhwhdh37292',
'0393jdh3hdj3hdnhhdnbwhwhdh37292',
'0493jdh3hdj3hdnhhdnbwhwhdh37292',
'0593jdh3hdj3hdnhhdnbwhwhdh37292',
'0693jdh3hdj3hdnhhdnbwhwhdh37292',
'0793jdh3hdj3hdnhhdnbwhwhdh37292',
'0893jdh3hdj3hdnhhdnbwhwhdh37292',
'0993jdh3hdj3hdnhhdnbwhwhdh37292',
'1093jdh3hdj3hdnhhdnbwhwhdh37292',
'1193jdh3hdj3hdnhhdnbwhwhdh37292',
'1293jdh3hdj3hdnhhdnbwhwhdh37292',
'1393jdh3hdj3hdnhhdnbwhwhdh37292',
'1493jdh3hdj3hdnhhdnbwhwhdh37292',
'1593jdh3hdj3hdnhhdnbwhwhdh37292',
'1693jdh3hdj3hdnhhdnbwhwhdh37292',
'1793jdh3hdj3hdnhhdnbwhwhdh37292',
'1893jdh3hdj3hdnhhdnbwhwhdh37292',
'1993jdh3hdj3hdnhhdnbwhwhdh37292',
'2093jdh3hdj3hdnhhdnbwhwhdh37292',
'2193jdh3hdj3hdnhhdnbwhwhdh37292',
'2293jdh3hdj3hdnhhdnbwhwhdh37292',
'2393jdh3hdj3hdnhhdnbwhwhdh37292')
order by id1;

(2) Highlight and select the entire command
(3) Execute -> Export From Query

**Comment by E1izabeth** [comment] 2024-07-11 12:26
Thank you for bug report.
I'm closing it as a duplicate of https://github.com/dbeaver/dbeaver/issues/34705
The fix is on the way.

**Closed as not planned by E1izabeth** 2024-07-11 12:26 UTC
Labels: duplicate, xf:datatransfer, xf:ui
