### ISSUE TITLE
Windows Defender find Trojan (false positive)

### ISSUE THREAD

**Issue by ffblanch** [dbeaver/dbeaver#3005] opened 2018-02-19 15:57 UTC
Trojan:Win32/Sprisky.U!cl 
in Windows 64 bit (installer + JRE) 4.3.5

**Comment by infectormp** [comment] 2018-02-19 16:00
False positive. Feel free to scan it on virustotal.com

**Comment by ffblanch** [comment] 2018-02-19 16:05
can i download oldest version ?

**Comment by tati-kru** [comment] 2018-02-19 16:10
@ffblanch of course, you can find all DBeaver versions in the archive: https://dbeaver.jkiss.org/files/.
We will check it once again and fix near future. Thank you for your issue.

**Comment by serge-rider** [comment] 2018-02-24 21:10
Can't reproduce this in any available online services (including MS Windows Defender).
Closing as a glitch.

(I assume that you downloaded DBeaver installer from the official web site)

**Closed by serge-rider** 2018-02-24 21:10 UTC
Labels: question

**Comment by ffblanch** [comment] 2018-03-01 18:18
I tried this morning and everything works !
