### ISSUE TITLE
Jasper Report Parameters don't work anymore

### ISSUE THREAD

**Issue by mathiasherbst** [dbeaver/dbeaver#18713] opened 2023-01-10 10:06 UTC
### Description

[https://github.com/dbeaver/dbeaver/issues/6140]

### DBeaver Version

Community Edition 22.3.2.202301060755

### Operating System

Ubuntu 22.04 LTS

**Comment by LonwoLonwo** [comment] 2023-01-11 13:00
Hello. Please provide more details about your issue. Footage will be beneficial.

**Comment by mathiasherbst** [comment] 2023-01-11 15:38
Hello, the feature introduced with #6140 isn`t working anymore.
I get the following message (see attachment) when calling a sql statement with jasper parameter:

example statement:
select
raw.*
from
(select 'Test' testdata) raw
where
$P{testcall} like testdata

![parameter_message](https://user-images.githubusercontent.com/47530629/211848938-9600b237-8706-48a7-83c6-c63f241e0608.png)

**Comment by E1izabeth** [comment] 2023-01-13 10:38
Thank you for bug report. It's a duplicate of #18354

**Closed as not planned by E1izabeth** 2023-01-13 10:38 UTC
Labels: duplicate, xf:sql
