### ISSUE TITLE
Can't insert or update data into a geometry column with CRS modifier

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12883] opened 2021-06-17 13:24 UTC
#### System information: 
- DBeaver version 21.1.1

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1. Create a geometry column with modified data type e.g. `geometry(point, 4326)`
2. Open Data editor, Value tab.
3. Try to add a point in Text value and save changes.

**Expected:** Data is saved
**Actual:** Error is thrown

![2021-06-17_16h19_49](https://user-images.githubusercontent.com/82543000/122404503-f4d3fc00-cf87-11eb-96c3-909ca0b26dce.png)
![2021-06-17_16h20_17](https://user-images.githubusercontent.com/82543000/122404488-f271a200-cf87-11eb-926f-6c32e0b87c1e.png)

**Comment by tati-kru** [comment] 2021-10-18 10:21
duplicate of #12238

**Closed as completed by tati-kru** 2021-10-18 10:21 UTC
Labels: enhancement, x:postgresql, duplicate
