### ISSUE TITLE
Variables in Network profiles replaced by a value at first connection

### ISSUE THREAD

**Issue by ibcht** [dbeaver/dbeaver#10019] opened 2020-10-08 14:06 UTC
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : 7.2.2
- Java version : "1.8.0_152"
- Additional extensions : none

#### Connection specification:
- Database name and version : MySQL 5.7
- Driver name : Driver for MySQL 4.x+
- Do you use tunnels or proxies (SSH, SOCKS, etc) : YES

#### Describe the problem you're observing:

The network profile doesn't allow to use variables between several connections.

On the first connection started with this profile, the value of this particular connection is applied to all the other connections with the same profile.

#### Steps to reproduce, if exist:

1. Create 2 connections (MySQL 4+ driver in my case), both need SSH tunnel, with the General set-up with Server Host, Database, Username and Password. 
![image](https://user-images.githubusercontent.com/6569743/95468480-d93b3f00-097e-11eb-810f-87cf1e245f64.png)
1. On the first one, on the SSH settings, use the profile management to create default settings as below (please note the ${host} variable) : 
![image](https://user-images.githubusercontent.com/6569743/95467811-31257600-097e-11eb-9fb3-df339b217bce.png)
1. Apply and close, so that the fields are automatically filled with the profile values 
![image](https://user-images.githubusercontent.com/6569743/95467967-59ad7000-097e-11eb-8dcf-75b1fae3c2c0.png)
1. Open this connection. It works well.
1. Open the second connection. Go to SSH settings. Choose the previously created profile. Now the ${host} variable has been unfortunately replaced by the first connection IP.
![image](https://user-images.githubusercontent.com/6569743/95469020-67afc080-097f-11eb-85cc-a64784be0ab5.png)

#### Include any warning/errors/backtraces from the logs

N/A

**Comment by uslss** [comment] 2020-10-08 14:54
thanks for the bug report
closed as a duplicate of #9134

**Closed by uslss** 2020-10-08 14:54 UTC
Labels: bug, duplicate
