### ISSUE TITLE
Cannot install DBeaver 22.3.0 from Eclipse Marketplace

### ISSUE THREAD

**Issue by harmin-parra** [dbeaver/dbeaver#18582] opened 2022-12-23 23:56 UTC
### Description

I am using eclipse 2022-12

I get these errors when trying to install DBeaver from Eclipse Marketplace

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver IDE 22.3.0.202212070729 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.0.202212070729)
  Missing requirement: Bouncy Castle PKIX, CMS, EAC, TSP, PKCS, OCSP, CMP, and CRMF APIs 1.70.0.v20220105-1522 (org.bouncycastle.bcpkix 1.70.0.v20220105-1522) requires 'java.package; org.bouncycastle.asn1 [1.70.0,1.71.0)' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver IDE 22.3.0.202212070729 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.0.202212070729)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.runtime.feature.feature.group [22.3.0.202212070729,22.3.0.202212070729]
  Cannot satisfy dependency:
    From: DBeaver Runtime 22.3.0.202212070729 (org.jkiss.dbeaver.runtime.feature.feature.group 22.3.0.202212070729)
    To: org.eclipse.equinox.p2.iu; org.bouncycastle.bcpkix [1.70.0.v20220105-1522,1.70.0.v20220105-1522]

```

### DBeaver Version

22.3.0

### Operating System

Linux

**Comment by E1izabeth** [comment] 2022-12-24 05:54
Thank you for bug report. 
It's a duplicate of #18475

**Closed as not planned** 2022-12-24 05:55 UTC
Labels: duplicate, xo:eclipse, xf:packaging
