### ISSUE TITLE
F4 not open declaration for views and othe database objects

### ISSUE THREAD

**Issue by shamsheermh** [dbeaver/dbeaver#7865] opened 2020-02-07 03:14 UTC
click F4 to open declaration of view other object in oracle

**Comment by uslss** [comment] 2020-02-07 09:49
cannot reproduce an issue.
what version do you use?

**Comment by Pengchenghua** [comment] 2020-02-08 02:58
I show up sometimes

**Comment by uslss** [comment] 2020-02-24 10:24
fixed in scope of #7871

**Closed by uslss** 2020-02-24 10:24 UTC
Labels: bug, can't reproduce, wait for response
