### ISSUE TITLE
Externalbrowser re-authenticating for every new Query Editor file

### ISSUE THREAD

**Issue by eequalsmcaputo** [dbeaver/dbeaver#12029] opened 2021-04-07 16:36 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.0.1
- Additional extensions: None

#### Connection specification:
- Database name and version: Snowflake
- Driver name: JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing: 
I just moved to a new laptop. I connect to Snowflake from DBeaver using externalbrowswer authentication. On the new laptop, DBeaver re-authenticates every time I open a new SQL Query Editor window or open an existing file from a project. Sometimes it authenticates as many as six times for one file, i.e. opens six browser tabs. The authentication does work.

#### Steps to reproduce, if exist:
1. Set up an externalbrowser connection to Snowflake
2. Open a new Query Editor window

#### Include any warning/errors/backtraces from the logs:
Couldn't find any.

**Comment by uslss** [comment] 2021-04-29 11:04
Seems to be a duplicate of #10402

As a workaround, you could disable those options:
![image](https://user-images.githubusercontent.com/31996417/116541093-af823f00-a8f3-11eb-926f-17474e4e3265.png)
![image](https://user-images.githubusercontent.com/31996417/116541156-c9238680-a8f3-11eb-9284-36b2901521aa.png)

**Closed as completed by uslss** 2021-04-29 11:04 UTC
Labels: duplicate, x:snowflake
