### ISSUE TITLE
How to export data from multi tables to a single .sql file

### ISSUE THREAD

**Issue by mythcolor** [dbeaver/dbeaver#5142] opened 2019-01-29 07:16 UTC
I use DBeaver 5.3.1 for postgresql .Is it possible to export data from multi tables(suppose no foreign keys) to a single *.sql file with insert statement? I  tried many option but failed. It just exported the one table which I chosen at last. BTW, how to execute a *.sql file which contains dml and ddl statement (Just like In Oracle we use @xxx.sql to execute it)? I just want to migrate data in some tables from one Postgresql DB to another one.

In fact it's not an issue but I don't know where is the forum to ask for help. 

Thanks!

**Comment by p91paul** [comment] 2019-01-29 12:10
this request is tracked in https://github.com/dbeaver/dbeaver/issues/2855

**Comment by serge-rider** [comment] 2019-02-02 21:41
I still think it is separate. 2855 is about exporting multiple queries in one command. 
But it exports data to different files by default.
Merging results into single file is different feature.

**Comment by p91paul** [comment] 2019-02-03 01:00
well you closed #4972 as duplicate of #2855, and #4972 seems this very issue! That's why I thought you planned to work on them together...

**Closed** 2019-02-03 17:56 UTC
Labels: feature request, xf:datatransfer

**Comment by mythcolor** [comment] 2019-04-19 07:15
Thanks! And I have mentioned another question: how to exexute a sql file.It seems the same as issue #2179. Please have a look.
