### ISSUE TITLE
Saved Filter not available

### ISSUE THREAD

**Issue by Neumi25** [dbeaver/dbeaver#18642] opened 2023-01-03 12:28 UTC
### Description

Highlighted some values in an open Table-spreadsheet.
F11 (Save Filters) produces a popup that the filter is saved successfully; the preview shows not the values selected.
The Windows-clipboard is empty.
How and where can I get the generated filter-sql for the preselected values?
Thanks for your Response in advance,
Carsten.

![2023-01-03 13_21_22-DBeaver-save-Filter](https://user-images.githubusercontent.com/121864400/210356671-962f2121-0515-4aa4-97b8-ffc72393f1ef.png)

### DBeaver Version

Community Edition 22.3.1.202212251901

### Operating System

Windows 10

### Database and driver

DB2 LUW

**Comment by uslss** [comment] 2023-01-04 11:19
hi @Neumi25 , in this case you can use Filter by value (Ctrl+F11) option. 
Previously chosen values will be checked in Filter dialog
![image](https://user-images.githubusercontent.com/31996417/210543738-acfe5abd-a9f7-4a3e-a184-f8f3c2f7fe1a.png)
After filter applying SQL expression will be available  in the top filter field
![image](https://user-images.githubusercontent.com/31996417/210544172-66443e3a-6e2d-4d19-9b0f-44f93799d321.png)

**Comment by uslss** [comment] 2023-02-01 11:25
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.

**Closed as completed by uslss** 2023-02-01 11:25 UTC
Labels: wait for response, question, xf:filters
