### ISSUE TITLE
Problem set active Dbeaver Community Edition 6.3.3

### ISSUE THREAD

**Issue by Linkj2** [dbeaver/dbeaver#7796] opened 2020-01-31 15:28 UTC
For the most recent version of dbeaver: Community Edition 6.3.3
I can't set an active object, there is no option to set active, then I went back to the previous version and it still works correctly.

Thanks.

**Comment by uslss** [comment] 2020-01-31 16:43
Hi @Linkj2 ,
seems to be duplicate of #7693 .
Feature "Set default database" will be back in 6.3.4 :) 
You could test it in EA version (https://dbeaver.io/files/ea)

**Closed by uslss** 2020-01-31 16:43 UTC
