### ISSUE TITLE
data format settings doesn't effect result set

### ISSUE THREAD

**Issue by Sylvan86** [dbeaver/dbeaver#4008] opened 2018-08-16 08:51 UTC
dbeaver version: 5.1.5.201808130751
sqlite-jdbc driver version: 3.23-1

In my understanding, the data format settings exist so that the results can be displayed in a special form independent of the internal database format.

For example: Integers are to be output with thousands separators. Or SqLite internally stores dates as a string in the form "yyyy-MM-dd" but should be displayed in the form "yy/M/d" during output.

That's what the data format settings are for. - am I right?

The problem: This doesn't work for me.
All my SQLite output ignores my data format preferences.
No matter if I make this setting for the single connection or globally.
I can see from the column header that the respective attribute was correctly recognized as a number type, for example. However, the output is not formatted accordingly.
Since I suspected it could be related to sqlite, I also tested the phenomenon once with WMI. But even there the results are not displayed as I pretend.

I think I have overlooked or ignored something fundamental in this context.

My settings (here globally but also connection-related):
![settings](https://user-images.githubusercontent.com/28677087/44198523-f5961500-a141-11e8-82b6-7f0384405de0.JPG)

And this is the result:
![result](https://user-images.githubusercontent.com/28677087/44198537-fe86e680-a141-11e8-932f-5db2b59d578a.JPG)

Thanks in advance!

**Comment by serge-rider** [comment] 2018-08-16 14:03
I think this problem was there always and it is SQLite-specific. It doesn't respect formatting options because of weird type system in SQLite.
In any case it is a bug, thanks for the report.
If you see the same problem with any other database - please provide more details.

**Comment by Sylvan86** [comment] 2018-08-16 16:25
Yes, the type system of sqlite is quite ...  well ... "special".
However, for a lightweight local relational DBS i don't know of a better alternative and I am actually very satisfied with sqlite.

Sounds funny but good to hear that it is a "bug". I have been trying for 2 hours because I assume that the error is on my side. 

Another "database" with this phenomenon would be WMI.
Also there, numerical values are not formatted properly
For example the UInt-values of the Win32_Volume class.

But first of all thank you for the quick reaction and especially for your great work. Dbeaver really is a fantastic tool!

**Comment by serge-rider** [comment] 2018-08-17 16:52
SQLite fix will be in the next version.

WMI is a bit more sophisticated.

Thanks for the bug report :)

**Closed by serge-rider** 2018-08-17 16:52 UTC
Labels: bug, x:sqlite

**Comment by Sylvan86** [comment] 2018-08-17 19:41
Um - just "wow!"

24h between report and fix!
For a "bug" that is anything but critical.
Again: Many thanks for your amazing work!

**Comment by slobatch** [comment] 2018-08-22 19:35
@serge-rider running into what appears to be the same bug, on the same version/build as @Sylvan86, but in my case i'm using Redshift SQL / PostgreSQL.

Wondering if I should file as a separate bug or whether these might be related. 

FWIW, a colleague with 5.1.1 is not seeing this issue, which suggests it might be a regression.

**Comment by serge-rider** [comment] 2018-08-25 11:56
Can't reproduce this issue with RedShift.
BTW we will use PostgreSQL extension for Redshift driver in the next version. Means quite a lot of changes for Redshift users.
