### ISSUE TITLE
Url Template not taken into account for postgresql driver type

### ISSUE THREAD

**Issue by jaimepineiro** [dbeaver/dbeaver#5516] opened 2019-03-18 07:48 UTC
I created a driver extending postgresql driver type 
![image](https://user-images.githubusercontent.com/45460679/54514445-79bfad80-495a-11e9-8706-77b289eba4b1.png)

Then when i create a connection, using this driver, i notice that it is trying to connect, using postgreSQL defaults url template, instead of Url template that i configured

![image](https://user-images.githubusercontent.com/45460679/54514419-63195680-495a-11e9-8fe5-e53e924dce38.png)

I'm using dbeaver 6.0.0

**Comment by nledenyi** [comment] 2019-08-27 07:40
I confirm the issue is still present in 6.1.5 as well. I was trying to load the official Pivotal Greenplum JDBC driver, however, for that the URL template is different ("jdbc:pivotal:greenplum://" instead of "jdbc:postresql://", see http://gpdb.docs.pivotal.io/5140/datadirect/datadirect_jdbc.html )
If I create a new driver where Driver Type=Greenplum, then DBeaver will insist using jdbc:postgresql:// no matter what I type into the URL template or leave it empty and fails to connect.
My other option is to set the Driver Type=Generic, then it correctly uses the URL template and I'm able to connect, however I'm losing Greenplum specific features which I otherwise have with Driver Type=Greenplum
DBeaver is a great tool, I would love to see this fixed.

**Comment by serge-rider** [comment] 2019-08-29 10:47
Sorry, I missed this ticket.
It will be fixed as well.

**Comment by uslss** [comment] 2019-08-30 11:50
verified

**Closed by uslss** 2019-08-30 11:50 UTC
Labels: bug, x:postgresql
