### ISSUE TITLE
add empty space bottom in table view. because there are horizontal scrollbar

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#8484] opened 2020-04-19 12:58 UTC
https://imgur.com/a/NjR1xWL

currently dificult to edit last record because the horizontal scrollbar will shown if my cursor there

dbeaver 7.0.2

**Comment by uslss** [comment] 2020-04-20 11:24
hi @erlangp ,
what os do you use? also issue isn't clearly shown at the picture, could you add another one?

**Comment by uslss** [comment] 2020-04-22 13:14
probably duplicate of #4839

**Closed by uslss** 2020-04-22 13:14 UTC
Labels: duplicate, feature request, wait for response
