### ISSUE TITLE
disabled driver window

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#18001] opened 2022-10-24 05:18 UTC
### Description

disabled element on driver window

### DBeaver Version

22.2.3

### Operating System

windows 11 64bit

### Database and driver

Postgresql 14

### Steps to reproduce

1. Open Connection 
![image](https://user-images.githubusercontent.com/61137576/197453066-c411d7ed-c80c-4711-b88e-a7342eb36b93.png)
2. Open Download
![image](https://user-images.githubusercontent.com/61137576/197453135-51e7f245-c356-4d00-b9a7-da922d28ad02.png)
3. All elements are disabled. Nothing to do on click. 
![image](https://user-images.githubusercontent.com/61137576/197453315-da7ec669-6dcd-4033-a966-d03e22200094.png)

**Comment by ShadelessFox** [comment] 2022-10-24 08:10
Hi @detkliff,

What do you mean by `disabled`? I can clearly see that the highlighted elements of the dialog are active.

Can you please clarify what is going on? You mean pressing on anything doesn't have any effect? If so, please attach the log files: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Destrolaric** [comment] 2022-10-24 08:14
Was not fixed in https://github.com/dbeaver/dbeaver/issues/17892

**Comment by ShadelessFox** [comment] 2022-10-24 09:59
Duplicate of #17892

**Closed as not planned by ShadelessFox** 2022-10-24 09:59 UTC
Labels: xp:major, duplicate, xf:ui

**Comment by detkliff** [comment] 2022-10-24 11:11
> Hi @detkliff,
> 
> What do you mean by `disabled`? I can clearly see that the highlighted elements of the dialog are active.
> 
> Can you please clarify what is going on? You mean pressing on anything doesn't have any effect? If so, please attach the log files: https://github.com/dbeaver/dbeaver/wiki/Log-files

You mean pressing on anything doesn't have any effect?
yes
