### ISSUE TITLE
Firebird database views are not visible in version 7.2.5

### ISSUE THREAD

**Issue by yiwan74** [dbeaver/dbeaver#10392] opened 2020-11-17 09:11 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.2.5

Database name and version: Firebird

In version 7.2.5 database views could not be found.

![image](https://user-images.githubusercontent.com/14015195/99369757-1c14fe80-28bd-11eb-9f04-1622cdb85f0b.png)

**Comment by LonwoLonwo** [comment] 2020-11-17 09:54
Thanks for bug report! fix it soon

**Comment by serge-rider** [comment] 2020-11-17 10:20
Fixed

**Comment by uslss** [comment] 2020-11-18 09:08
#10411 created
verified

**Comment by teklstudio** [comment] 2020-11-24 13:11
> Fixed

I have tried 7.3.0 from https://dbeaver.io/files/ea/  just now and views in Firebird are still not shown.  I see them as regular tables.

**Comment by uslss** [comment] 2020-11-24 13:13
@teklstudio what firebird version do you use?

**Comment by teklstudio** [comment] 2020-11-24 13:16
> @teklstudio what firebird version do you use?
@uslss Firebird version 2.5.5

**Comment by uslss** [comment] 2020-11-24 13:29
@teklstudio cannot reproduce it
![image](https://user-images.githubusercontent.com/31996417/100100680-3b3dfe00-2e72-11eb-9614-104d23f65227.png)
Is there something in the logs?

**Comment by teklstudio** [comment] 2020-11-24 13:38
@uslss where can I send you my database?

**Comment by teklstudio** [comment] 2020-11-24 14:00
@uslss maybe helps, that I have view which consist from union of two selects

**Comment by uslss** [comment] 2020-11-24 14:17
@teklstudio you can send the database to diana@jkiss.org
Thanks in advance

**Comment by uslss** [comment] 2020-11-25 10:28
@teklstudio thanks for the help with the investigation of the issue.
The new issue is created #10492 
Close this issue as resolved.

**Closed by uslss** 2020-11-25 10:28 UTC
Labels: bug, wait for response, x:firebird, xp:major

**Comment by teklstudio** [comment] 2020-11-25 10:34
@uslss  thank you. it will  be in early access  7.3.2 I expect

**Comment by DorwinDT** [comment] 2021-01-03 14:29
@uslss , I have downloaded EA version 7.3.2 and issue is not resolved...
