### ISSUE TITLE
Add a button to transpose a results set (show rows as columns and columns as rows)

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#11611] opened 2021-03-04 18:55 UTC
**Is your feature request related to a problem? Please describe.**
I often filter to one or two rows in tables with 50+ columns, and want to efficiently compare them side-by-side. The best way to do this sort of comparison is often showing each column as a row, and each row as a column (i.e. transposing the table). Currently, I have to copy it out to Excel to do this soft of viewing.

**Describe the solution you'd like**
I want to click a button near the Erase button for filters applied to a results set, and it transposes the table. Ideally, I want to be able to make edits.

**Describe alternatives you've considered**
Currently I just copy the table to Excel, which has this feature built in.

**Comment by uslss** [comment] 2021-03-18 09:42
thanks for the suggestion

closed as a duplicate of #7014

**Closed as completed by uslss** 2021-03-18 09:42 UTC
Labels: duplicate

**Comment by viniciusczanini** [comment] 2026-01-14 21:06
Any news on this one?

**Comment by DeflateAwning** [comment] 2026-01-15 02:52
You can select many rows and **press tab** (or click the "Record" button in the bottom-left of the table). 

@viniciusczanini  It's moved to the other issue (as indicated by the "closed as a duplicate" comment).
