### ISSUE TITLE
Dbeaver 23.2.3 - data export fails with I/O error and no other  details

### ISSUE THREAD

**Issue by Asurion-AM** [dbeaver/dbeaver#21661] opened 2023-10-25 20:46 UTC
### Description

it shows up with export screen and green bar moving then ends abruptly with no explanation. 
File name was not existing. Tried as CSV, TXT but got same error. Tried couple of different connections/drivers - same issue.
Reverting to previous version of Dbeaver solved the problem. 

### DBeaver Version

Community Edition 23.2.3

### Operating System

Windows 10 enterprise

### Database and driver

Presto Trinio, 
Databricks Spark SQL

### Steps to reproduce

take any query and try to export data, doesnt matter how many records

**Comment by E1izabeth** [comment] 2023-10-25 21:05
Please provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by dotNetNoob** [comment] 2023-10-26 12:57
Same issue: After updating to 23.2.3 Community Edition,  can't "export from query" to a share path, but export to local path works fine. 

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -eclipse.keyring C:\Users\XXXXXXXX\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Oct 26 08:37:14 EDT 2023
\\vfs01\XXXXXXXXXX\Claims\Proprietary\XXXXXXXX\XXXXXXXXXXXXXXX_20211130-1698323834048.txt

java.nio.file.NoSuchFileException: \\vfs01\XXXXXXXXXX\Claims\Proprietary\XXXXXXXX\XXXXXXXXXXXXXXX_20211130-1698323834048.txt
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.openOutputStreams(StreamTransferConsumer.java:506)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.initExporter(StreamTransferConsumer.java:385)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchStart(StreamTransferConsumer.java:167)
	at org.jkiss.dbeaver.model.sql.data.SQLQueryDataContainer.readData(SQLQueryDataContainer.java:140)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:270)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:187)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:113)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by E1izabeth** [comment] 2023-10-26 13:37
Thank you for bug report. It's a duplicate of #21611
We have already fixed this bug and the fix is available in the early access version https://dbeaver.io/files/ea/

**Closed as not planned** 2023-10-26 13:37 UTC
Labels: duplicate, xf:datatransfer
