### ISSUE TITLE
Showing ghosting in the SqlEditor screen  

### ISSUE THREAD

**Issue by BradSelfridge** [dbeaver/dbeaver#3927] opened 2018-08-05 20:07 UTC
Ubuntu 16.04 - 
DBeaver 5.1.4 

![image](https://user-images.githubusercontent.com/1494177/43689493-86ba4294-98c9-11e8-9748-a6bfb165a52a.png)

**Comment by serge-rider** [comment] 2018-08-05 20:08
Duplicate of #3916. See workaround in last #3916 comments.

**Closed by serge-rider** 2018-08-05 20:08 UTC
Labels: bug, duplicate
