### ISSUE TITLE
Incorrect quotation during export from postgresql to maria

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#13453] opened 2021-08-05 12:57 UTC
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.4

#### Connection specification:
- Database name and version PostgreSQL 12.3, MariaDB 10.3.23

#### Describe the problem you're observing:
Double quotes are used instead of backtick in some cases during data transfer from PostgreSQL to MariaDB
#### Steps to reproduce, if exist:
1. Start export from postgresql to maria
2. Export should be performed to the new table

Result:
There are double quotes instead of backticks in the generated script. Export cannot be performed.
![image](https://user-images.githubusercontent.com/31996417/128353165-6d3354b5-90ac-4776-95df-f6dcf682bc25.png)

Note:
The quotation is changed to correct after column mapping changing 
![Z55WGcoLsu](https://user-images.githubusercontent.com/31996417/128353507-189c4419-8a65-4249-a91e-46f47eb6cd32.gif)

**Comment by LonwoLonwo** [comment] 2021-08-18 08:00
Seems to be fixed in #13542

**Comment by Matvey16** [comment] 2021-08-18 08:59
This issue needs a separate fix, still reproducable

**Comment by serge-rider** [comment] 2021-08-18 12:21
@Matvey16 This bug was fixed in #13542 indeed.
For problem with columns remapping after target database change we need another ticket.

**Comment by Matvey16** [comment] 2021-08-19 11:40
New ticket with a more complete description created #13582

**Closed as completed by Matvey16** 2021-08-19 11:40 UTC
Labels: x:postgresql, x:maria, xf:datatransfer, AS
