### ISSUE TITLE
Screen flickering under Hyprland

### ISSUE THREAD

**Issue by shilkazx** [dbeaver/dbeaver#34528] opened 2024-06-27 03:19 UTC
### Description

The window/panal(like data view, detail view) flickering under Wayland(Hyprland compositor), but there is nothing wrong under X11(AwesomeWM compositor) with the same dbeaver install.

### DBeaver Version

24.1.0

### Operating System

Archlinux x64

**Comment by E1izabeth** [comment] 2024-06-27 13:00
Could you explain what exactly is flickering? A video or screenshot would be useful.

**Comment by E1izabeth** [comment] 2024-06-27 13:01
Also please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by Davincible** [comment] 2024-06-28 11:38
Can confirm as well on Hyprland, used to work fine before. Now its trippy

**Comment by E1izabeth** [comment] 2024-06-28 11:42
Please provide the requested additional information.

**Comment by kohane27** [comment] 2024-06-28 15:29
Not OP but I have the exact problem that makes DBeaver unsable. Content is literally gone until I move the cursor or click something in the UI.   


https://github.com/dbeaver/dbeaver/assets/57322459/c74e50d4-5fe7-4535-beb8-48acfbfd1594



I see the following log when I opened DBeaver:

```
!ENTRY org.eclipse.ui 2 2 2024-06-28 23:19:09.282
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
!SESSION 2024-06-28 23:23:23.890 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.3
java.vendor=Flathub
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -eclipse.keyring /home/username/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.urischeme 4 0 2024-06-28 23:23:26.258
!MESSAGE Cannot run program "xdg-mime": error=2, No such file or directory
!STACK 0
java.io.IOException: Cannot run program "xdg-mime": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at org.eclipse.urischeme.internal.registration.ProcessExecutor.execute(ProcessExecutor.java:36)
	at org.eclipse.urischeme.internal.registration.RegistrationLinux.getRegisteredDesktopFileForScheme(RegistrationLinux.java:144)
	at org.eclipse.urischeme.internal.registration.RegistrationLinux.determineHandlerLocation(RegistrationLinux.java:86)
	at org.eclipse.urischeme.internal.registration.RegistrationLinux.getSchemesInformation(RegistrationLinux.java:75)
	at org.eclipse.urischeme.AutoRegisterSchemeHandlersJob.run(AutoRegisterSchemeHandlersJob.java:85)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:295)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:225)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 7 more

!ENTRY org.eclipse.ui 2 2 2024-06-28 23:23:27.672
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
```

Hopefully it helps. Thank you!

**Comment by E1izabeth** [comment] 2024-07-01 06:20
Hi, @kohane27. Thank you for providing more information regarding this issue.

**Comment by Davincible** [comment] 2024-07-01 07:05
Yeah mine looks exactly the same as in the video here

**Comment by E1izabeth** [comment] 2024-07-01 08:48
Does it happen all the time or do you have any steps to reproduce this bug?

**Comment by MacheroKiller** [comment] 2024-07-02 14:27
I have the same issue, it happens all the time.

**Comment by RockyCott** [comment] 2024-07-03 17:35
I'm experiencing the same flickering issue. The issue occurs with both the AUR and Flatpak versions. It started happening with version 24.1.0. Here's a video of the problem and my system config:

Issue:

https://github.com/dbeaver/dbeaver/assets/67379041/95e6d141-7a90-40bc-98e9-495e4df818e1

System config:

![240703_12h31m29s_screenshot](https://github.com/dbeaver/dbeaver/assets/67379041/d7d7241c-7772-4018-894d-2b0c14fa9153)

**Comment by E1izabeth** [comment] 2024-07-03 18:21
Please send the log files not right after the application start, but after the issue happens. You can find instructions how to find log files here https://dbeaver.com/docs/wiki/Log-files/

**Comment by RockyCott** [comment] 2024-07-03 21:00
> Please send the log files not right after the application start, but after the issue happens. You can find instructions how to find log files here https://dbeaver.com/docs/wiki/Log-files/

Here are the log files
[07-03-24.log](https://github.com/user-attachments/files/16090740/07-03-24.log)

**Comment by MacheroKiller** [comment] 2024-07-03 21:12
> Please send the log files not right after the application start, but after the issue happens. You can find instructions how to find log files here https://dbeaver.com/docs/wiki/Log-files/

Do you need this one: dbeaver-debug.log?

**Comment by MacheroKiller** [comment] 2024-07-03 21:34
> Please send the log files not right after the application start, but after the issue happens. You can find instructions how to find log files here https://dbeaver.com/docs/wiki/Log-files/

This is my .log File. 

Edit: In my case, this only happens when Dbeaver is in dark theme. 

[logFile.txt](https://github.com/user-attachments/files/16090973/logFile.txt)

**Comment by E1izabeth** [comment] 2024-07-04 09:53
Thank you

**Comment by matrox471** [comment] 2024-07-04 10:04
I have the same issue as @MacheroKiller and i just tested what he said about the dark theme.
On my side, simply switching form "light" to "Classic" fixed it (User Interface -> Appearance -> Theme).
Light and Dark doesn't work and flicker on the same way as the video above, Classic has no issues.

Also i tried the ibus fix in the wiki but it didn't do anything.

Using:
Archlinux -> hyprland
dbeaver -> 24.1.1

**Comment by Davincible** [comment] 2024-07-05 07:38
@matrox471 thanks for the tip!! Classic themes works. Looks hideous but can some work done now

**Comment by shilkazx** [comment] 2024-07-06 11:43
@E1izabeth sorry for late reply. My dbeaver behave the same way as @RocyCott, and thanks for @matrox471 solution. Change theme to classic works for me too.

**Comment by DrElizar** [comment] 2024-07-06 15:58
Classic theme does not solve the problems here.

The table view GUI (at least table data and table properties) is flickering on each and every smallest mouse move.

System:
openSUSE Tumbleweed 20240617,
xfce desktop,
XDG_SESSION_TYPE is "x11",
dbeaver 24.1.1

**Comment by samintejas** [comment] 2024-07-08 06:37
Faced same issue here 

Using: Archlinux + hyprland & dbeaver 24.1.1

I've made it work by disabling theming , it will use the GTK theme once disabled . for me editor had weird colors so fixed it by  adjusting the editor colors in settings.

**Comment by bootids** [comment] 2024-07-18 01:14
> Faced same issue here
> 
> Using: Archlinux + hyprland & dbeaver 24.1.1
> 
> I've made it work by disabling theming , it will use the GTK theme once disabled . for me editor had weird colors so fixed it by adjusting the editor colors in settings.

thanks, after disabling the theme(Window->Preference->User Interface->Uncheck "Enable Theming."), it is now displaying normally

**Comment by eletrolitico** [comment] 2024-07-22 14:25
It seems that https://github.com/hyprwm/Hyprland/pull/6608 fixed it. Running NixOS with the Hyprland flake, Hyprland commit 83a5395eaa99fecef777827fff1de486c06b6180. Can someone else confirm?

**Comment by slackerbob** [comment] 2024-07-23 17:57
I can also confirm this issue.

ArchLinux, Hyprland 0.41.2-3, and DBeaver 24.1.2

Constant flashing when the Dark or Light theme are active.

**Comment by flambchap** [comment] 2024-07-25 11:29
@eletrolitico This is very odd. I've used DBeaver with another wlroots compositor (Sway) without such issues. I'm unsure if moving to Aquamarine will help.

**Comment by flambchap** [comment] 2024-07-25 11:33
It seems like this issue is tied to Hyprland, not Wayland in general. I've been using DBeaver on Wayland (Plasma 5 and 6, Sway) for years without such issues.

At the same time, we heavily use the Eclipse Platform to draw our UI. Can you guys please test any of Eclipse IDEs and see if the same issue happens there? I suspect it's an upstream issue. https://www.eclipse.org/downloads/packages/

**Comment by Urbinholt** [comment] 2024-08-11 09:36
> At the same time, we heavily use the Eclipse Platform to draw our UI. Can you guys please test any of Eclipse IDEs and see if the same issue happens there? I suspect it's an upstream issue. https://www.eclipse.org/downloads/packages/

Hey, I've tested Eclipse for C developers version 20240606-1231 and yes, the flickering is actually the same as in videos above and as I experience myself in DBeaver 24.1.4 on hyprland v0.41.2.

**Comment by E1izabeth** [comment] 2024-08-14 22:27
@Urbinholt thank you for checking

**Comment by shilkazx** [comment] 2024-08-15 02:16
I have test **eclipse-java-2024-06-R-linux-gtk-x86_64.tar.gz** from eclipse official, and got the same result as @Urbinholt. My hyprland is v0.42.

**Comment by vgarciae** [comment] 2024-08-27 02:21
Dbeaver, Studio 3T have the same problem, only changing the black background solves it

**Comment by RodrigoMarquesBarbosa** [comment] 2024-08-28 17:08
Changing the theme to classic or desabling the theming all together solves the flickering problem. But still my mouse movement is rendering weirdly, if i move the mouse a little fast it gets thrown to a diferent positions in the screen, way off from where it should be. Only happens if the mouse is over the dbeaver app.

Im on Arch and using hyprland.

**Comment by CS-Aditya-Rawat** [comment] 2024-09-01 07:53
Launching dbeaver like this solve the issue for now
`env GDK_BACKEND=x11 /usr/share/dbeaver-ce/dbeaver`

**Comment by emad-elsaid** [comment] 2024-09-20 09:31
Disabling dbeaver theme in preferences solved the issue for me 
![2024-09-20_11-31-08](https://github.com/user-attachments/assets/6e80b768-6a3b-484c-ba21-b8557158484a)

**Comment by npc-z** [comment] 2024-09-22 13:39
> Disabling dbeaver theme in preferences solved the issue for me ![2024-09-20_11-31-08](https://private-user-images.githubusercontent.com/54403/369349043-6e80b768-6a3b-484c-ba21-b8557158484a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTI1NzksIm5iZiI6MTcyNzAxMjI3OSwicGF0aCI6Ii81NDQwMy8zNjkzNDkwNDMtNmU4MGI3NjgtNmEzYi00ODRjLWJhMjEtYjg1NTcxNTg0ODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDEzMzc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NzJjZDEwYmMwYzk4MmYxYTI0ZjcwNmQyMDFkOThiNThkZDM3ODY3NThjYTE2Njg3OGM5ZGNiNzk5MWZjYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G2BrJJBpPQdCzlYzKvm6UyJ4qvvUjmZcVc5EFXxVe_U)

works for me.

**Comment by flambchap** [comment] 2024-09-30 13:44
Thanks a lot for your suggestions, everyone. I'm closing the issue since it's a bug in Hyprland: https://github.com/hyprwm/Hyprland/issues/6844.

**Closed as not planned by flambchap** 2024-09-30 13:44 UTC
Labels: xo:linux, xo:eclipse, third party issue, xf:ui

**Comment by propilideno** [comment] 2024-10-14 23:33
Open terminal and type
`GDK_BACKEND=x11 dbeaver`

**Comment by dr0bz** [comment] 2024-11-25 10:43
>Open terminal and type
GDK_BACKEND=x11 dbeaver

that fixed my problem. Made my day!

I think it's worth mentioning that in this issue two problems are mixed:

1. ui flickering - solved through disabling theming.
2. other ui artifacts (navigating in menus like project view caused menu items to disappear so i can see the source code pane underneath ) - solved through x11 gdk backend

I'm on hyprland and after 1. i still had 2. Now both are solved!

**Comment by propilideno** [comment] 2024-11-25 21:51
> that fixed my problem. Made my day!

i use hyprland too, i'm glad i could help.
