### ISSUE TITLE
How to make dbeaver export of db? 

### ISSUE THREAD

**Issue by sergeynilov** [dbeaver/dbeaver#21621] opened 2023-10-23 07:33 UTC
### Description

How to make dbeaver (Version 23.2.2.202310081633/under kubuntu 22.04) export from Postgres 14 db ?

I found in submenu  of current database Tiools->Backup and 
filled 1st and second tabs : https://prnt.sc/cXvQDDC2bs6e and https://prnt.sc/Qgy58MH6JdYu
but in both cases button “Next” is disabled and I can not proceed next...

What did  I miss ?

### DBeaver Version

Comminity Edition Version 23.2.2.202310081633

**Comment by MashaKorax** [comment] 2023-10-23 08:08
Hello, @sergeynilov. 
Unfortunately, we do not have support for native tools for Mac and Linux. 
Workaround: First you have to install your local postgresql server. When this is done, just make a rightclick on your PostgreSQL connection and then click on "Edit Connection". Here you can choose your local client. 
![dbeaver_l7G831C3fF](https://github.com/dbeaver/dbeaver/assets/84867187/e56ff032-9a36-4dcb-a961-fc0e12a4ff83)


After that when you make Backup  you need to select in this menu the local client
![slack_0fz7fvtqGn](https://github.com/dbeaver/dbeaver/assets/84867187/b50a63c9-9ee8-4b52-81c1-0146c0ee03e3)

Hope it helps.

**Comment by Nriver** [comment] 2023-10-26 09:33
I had the same issue with mariadb/mysql. For those who are confused like me:

Choose `/usr/bin` folder for that `Database Client Homes`.
Maybe developers should consider adding some description for this interface.
![ksnip_20231026-172028](https://github.com/dbeaver/dbeaver/assets/6752679/8f773a8d-b878-4f9c-bf48-9ec5227345d1)

Then you can continue with the dump by the `start` button
![ksnip_20231026-172151](https://github.com/dbeaver/dbeaver/assets/6752679/5ffdc53f-ee27-4d86-bc40-762b4ddd11ba)

**Comment by LonwoLonwo** [comment] 2023-10-26 10:32
Related ticket: https://github.com/dbeaver/dbeaver/issues/14620

**Comment by E1izabeth** [comment] 2023-11-21 19:22
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
For now I'm closing it as a duplicate of #14620 .

**Closed as not planned by E1izabeth** 2023-11-21 19:22 UTC
Labels: duplicate, xo:linux, wait for response, question, xf:native clients
