### ISSUE TITLE
Advanced copy => Advanced paste    Null Value Script Error ????

### ISSUE THREAD

**Issue by google007049** [dbeaver/dbeaver#17407] opened 2022-08-22 01:22 UTC
### Description

Thank you always for your hard work.

Even with version 22.1.5.202208211008, there is still an error when you  advanced paste and save after an advanced copy.
Script has an error. **'[NULL]'** must be changed to **NULL**. And for NULL of DATE TYPE, you need to change **TIMESTAMP'[NULL]'** to **NULL**. 

![image](https://user-images.githubusercontent.com/58673078/185825757-62a43664-e6e4-4aea-9ba5-133a4c0459af.png)

Below is the script generated during the Advanced Paste.
The error is the sql statement.

INSERT INTO A_MAU (COMPANY_KIND,ISSNO,ISSEQ,ITEM_CODE,DEPT_CODE,ISDATE,QTY,UPRICE,AMT,IS_TYPE,SLIP_NO,IN_CD,COA_CODE,STOCK_FLAG,FB_FLAG,FB_SEQ,AC_FLAG,AC_SLIPNO,AC_DATE,REMARK,IS_STATUS,CREATE_EMPNO,CREATE_DTIME,MODIFY_EMPNO,MODIFY_DTIME)
	VALUES ('610','200410260003',12,'020101022','411','20041026',1,31926.71,31927,'1',**'[NULL]'**,'2','[NULL]','S','0',0,'N','[NULL]','[NULL]','[NULL]','[NULL]','501335',TIMESTAMP '2004-10-26 17:29:43.000000','501335',**TIMESTAMP'[NULL]'**);

**'[NULL]' => NULL        : **I think it should be NULL, not "[NULL]".**
TIMESTAMP'[NULL]' => NULL**    : **I think it should be NULL, not TIMESTAMP'[NULL]".**

That way, it's saved and there's no error. I use this kind of action a lot. I sincerely ask you again. Please correct it.

https://user-images.githubusercontent.com/58673078/185821010-ca4d7234-51bf-423c-8154-c267b464f8e4.mp4

https://user-images.githubusercontent.com/58673078/185821738-d0ca8271-c48f-483f-93b7-3e02339e02da.mp4

### DBeaver Version

Community Edition 22.1.5.202208211008

### Operating System

Windows10

### Database and driver

ORACLE 11g

**Comment by uslss** [comment] 2022-08-23 12:44
@google007049, unfortunately, cannot reproduce it. It would be helpful if you could provide a DDL to create the table to reproduce an issue

**Comment by google007049** [comment] 2022-08-24 00:51
Thank you for your reply. And thank you for your interest.
Raise the table layout and DDL.

When Dbeaver does Advanced Paste, there is an error as below when creating a script.

INSERT INTO A_MAISSU (COMPANY_KIND,ISSNO,ISSEQ,ITEM_CODE,DEPT_CODE,ISDATE,QTY,UPRICE,AMT,IS_TYPE,SLIP_NO,IN_CD,COA_CODE,STOCK_FLAG,FB_FLAG,FB_SEQ,AC_FLAG,AC_SLIPNO,AC_DATE,REMARK,IS_STATUS,CREATE_EMPNO,CREATE_DTIME,MODIFY_EMPNO,MODIFY_DTIME)
VALUES ('610','200410260003',12,'020101022','411','20041026',1,31926.71,31927,'1','[NULL]','2','[NULL]','S','0',0,'N','[NULL]','[NULL]','[NULL]','[NULL]','501335',TIMESTAMP '2004-10-26 17:29:43.000000','501335',TIMESTAMP'[NULL]');


**### '[NULL]' => NULL : I think it should be NULL, not '[NULL]'.
TIMESTAMP'[NULL]' => NULL : I think it should be NULL, not TIMESTAMP'[NULL]'.**


Please check.


![image](https://user-images.githubusercontent.com/58673078/186290733-0f3df39b-6794-4f75-abfd-c7f78acda6e4.png)


![image](https://user-images.githubusercontent.com/58673078/186291856-7b992b34-9c8a-4713-8e4a-47f858d8fe5f.png)


CREATE TABLE A_MAISSU
(
  COMPANY_KIND  CHAR(3 BYTE)                    NOT NULL,
  ISSNO         VARCHAR2(12 BYTE)               NOT NULL,
  ISSEQ         NUMBER(4)                       NOT NULL,
  ITEM_CODE     VARCHAR2(10 BYTE)               NOT NULL,
  DEPT_CODE     VARCHAR2(10 BYTE)               NOT NULL,
  ISDATE        VARCHAR2(8 BYTE)                NOT NULL,
  QTY           NUMBER(12,2),
  UPRICE        NUMBER(12,2),
  AMT           NUMBER(12),
  IS_TYPE       VARCHAR2(2 BYTE),
  SLIP_NO       VARCHAR2(20 BYTE),
  IN_CD         VARCHAR2(1 BYTE),
  COA_CODE      VARCHAR2(10 BYTE),
  STOCK_FLAG    VARCHAR2(1 BYTE),
  FB_FLAG       VARCHAR2(1 BYTE),
  FB_SEQ        NUMBER(5),
  AC_FLAG       VARCHAR2(1 BYTE),
  AC_SLIPNO     VARCHAR2(20 BYTE),
  AC_DATE       VARCHAR2(8 BYTE),
  REMARK        VARCHAR2(50 BYTE),
  IS_STATUS     VARCHAR2(2 BYTE),
  CREATE_EMPNO  VARCHAR2(30 BYTE),
  CREATE_DTIME  DATE,
  MODIFY_EMPNO  VARCHAR2(30 BYTE),
  MODIFY_DTIME  DATE
)

**Comment by LonwoLonwo** [comment] 2022-09-08 13:36
Hello @google007049 

What is the reason to create so many tickets with one problem? Any difference from the case in https://github.com/dbeaver/dbeaver/issues/17210?

I'm closing this ticket as a duplicate of https://github.com/dbeaver/dbeaver/issues/17210

You can add additional info about your new case in the original ticket.

**Closed as not planned by LonwoLonwo** 2022-09-08 13:36 UTC
Labels: x:oracle, xf:datatransfer
