### ISSUE TITLE
Export SQL mistmatch

### ISSUE THREAD

**Issue by BernardoBJ** [dbeaver/dbeaver#11286] opened 2021-02-10 18:34 UTC
#### System information: 
- Windows 10
- DBeaver version: Version 7.3.3.202101161839

#### Connection specification:
- MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When we do a SELECT and order the data using the columns, and after that try to export some row in SQL, the copied information is of other row (maybe the row previous sorting).

#### Steps to reproduce, if exist:
1. Do a SELECT statement
2. Order by any column (be sure the data is in different order)
3. Select a data row
4. Click right button on the selected row
5. Click on Export data...
6. Select SQL and click Next button
7. Make sure selected options are 'Selected columns only' and 'Selected rows only' and click Next button
8. Check 'Copy to clipboard' and click Next button
9. Click Start button
10. Paste the text in some place to confirm the data pasted is different to the row selected

**Comment by uslss** [comment] 2021-02-11 08:26
thanks for the report
closed as duplicate of #9252

**Closed as completed by uslss** 2021-02-11 08:26 UTC
Labels: duplicate
