### ISSUE TITLE
Neo4j should return a result set when query starts with CALL

### ISSUE THREAD

**Issue by gstamac** [dbeaver/dbeaver#22738] opened 2024-02-07 10:29 UTC
**Is your feature request related to a problem? Please describe.**
Neo4j uses MATCH to retrieve data from the database. But you can also use CALL to create subqueries. As I understand Dbeaver expects CALL to execute an update to the database so it doesn't show a result set. This shouldn't be used with Neo4j server.

**Describe the solution you'd like**
When using CALL to get data from Neo4j server it should show a result set the same as with MATCH query.

**Describe alternatives you've considered**
None.

**Additional context**
Query
``` 
CALL { MATCH (t) RETURN t } RETURN t
``` 
should behave the same as query
```
MATCH (t) RETURN t
```

**Comment by LonwoLonwo** [comment] 2024-02-08 08:20
Hello @gstamac 

For now, I can't reproduce your case. I have equal results for both queries.

Could you please provide any footage of your issue? And DBeaver version info.

![2024-02-08 10_16_47-DBeaver Ultimate 23 3 4 - _Neo4j_ Script-58](https://github.com/dbeaver/dbeaver/assets/45152336/7d783a1e-223c-4aa5-a06c-ca049ead2360)

**Comment by gstamac** [comment] 2024-02-09 08:14
I am really sorry but looks like I had some other issue. I cannot reproduce it. Even if I try exactly the same query I did before it returns results now.
Thanks for your prompt reply.

**Comment by LonwoLonwo** [comment] 2024-02-09 08:55
Okay. Then, I'm closing this ticket.
If the issue happens again - please feel free to return here or create a new issue.

**Closed as completed by LonwoLonwo** 2024-02-09 08:55 UTC
Labels: xf:data, x:neo4j
