### ISSUE TITLE
v24.2.x - MySQL dump files are cut in the middle for binary columns

### ISSUE THREAD

**Issue by ksowa** [dbeaver/dbeaver#35588] opened 2024-09-13 11:06 UTC
### Description

There seems to be a problem with MySQL dumps on versions `24.2.x`, which was not there in `24.1.5`.

### DBeaver Version

24.2.0.202409011551

### Operating System

Ubuntu 22.04

### Database and driver

Database: `MySQL 5.7`
Driver: `com.mysql.cj.jdbc.Driver`

### Steps to reproduce

1. Have a database table with a binary columns (example structure added below - the columns store UUID values)
2. Try to make dump using `(database context menu) -> Tools -> Dump Database`
3. Select options like in the screenshot below

Problems:
1. the dump file is going to have content cut in the middle (sometimes te beginning of the file is cut off)
2. the output in the window looks to be formatted incorrectly 
3. the dump file is much smaller in size compared to dump made in version `24.1.5`

Dump options used:

![image](https://github.com/user-attachments/assets/37aec7bd-aec8-4f30-8694-9d2e18e9afa6)

Result dump file:

![image](https://github.com/user-attachments/assets/d755fbf2-470e-4243-83d9-5699f7dfa675)

File size comparison between `24.1.x` and `24.2.x`:

![image](https://github.com/user-attachments/assets/f7bbc2d8-a817-4323-9546-0e4429a3e48e)

DBeaver dump window output:

![image](https://github.com/user-attachments/assets/a68eae2b-5920-40f1-b895-4cd3e91018e1)

### Additional context

Example structure of the database table:

```sql
CREATE TABLE `user_product` (
  `id` binary(16) NOT NULL COMMENT '(DC2Type:uuid_binary_ordered_time)',
  `product_id` binary(16) NOT NULL COMMENT '(DC2Type:uuid_binary_ordered_time)',
  `user_id` binary(16) NOT NULL COMMENT '(DC2Type:uuid_binary_ordered_time)',
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `product_id_IDX` (`product_id`),
  KEY `user_product_IDX` (`user_id`,`product_id`),
  CONSTRAINT `FK_abc` FOREIGN KEY (`product_id`) REFERENCES `product` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by E1izabeth** [comment] 2024-09-13 12:12
Probably the issue is solved in scope of the #35421
Please download the latest EA version and see if the issue is gone there.
https://dbeaver.com/files/ea/

**Comment by ksowa** [comment] 2024-09-13 12:26
Yes, I can confirm I couldn't reproduce the issue on version `24.2.1.202409122322`, so I assume it's been fixed.

**Comment by E1izabeth** [comment] 2024-09-13 12:27
Thank you for checking. I'm closing this issue then

**Closed as completed by E1izabeth** 2024-09-13 12:27 UTC
Labels: x:mysql, xf:native clients
