### ISSUE TITLE
DDL cached and not updated on ALTER

### ISSUE THREAD

**Issue by Aileron79** [dbeaver/dbeaver#17334] opened 2022-08-11 09:13 UTC
### Description

To modify stored procedures I right click the SP => Generate SQL => DDL to get the source. In a script window I modify the script and then send the changes using an ALTER statement which goes through fine. When I now right click that SP again, click Generate SQL => DDL, I will get the unALTERed DDL from before. This caused quite some confusion when I needed to check if I had made changes to the procedure or not. 

Expected behavior: ALTER a procedure, get new DDL when loading it. 

Workaround: Refresh

### DBeaver Version

22.1.4

### Operating System

Windows 10 x64

### Database and driver

Azure SQL

### Steps to reproduce

- Use a DB that has SPs
- Generate SQL => DDL for that SP
- ALTER PROCEDURE and commit
- Generate SQL => DDL for that SP
- Old DDL from before the ALTER PROCEDURE is shown.

**Comment by iraidaa** [comment] 2022-08-18 12:15
Hello @Aileron79,

I've tried to reproduce the issue, using Azure SQL and DBeaver 22.1.4. 

The following way to modify the procedure works for me:

Open the procedure -> go to the Source tab -> modify the existing procedure with ALTER PROCEDURE before it -> Save it ->click on Persist in the pop-up.

Then, I tried to close DBeaver, opened it again, checked the procedure and found only the changed procedure (first line of the DDL changed with CREATE PROCEDURE).

What do you get if you follow these steps?

**Comment by Aileron79** [comment] 2022-08-19 06:51
That of course works, but the issue is not that the procedures are not updated - in fact, they are. The problem is that when right clicking a procedure that has been ALTERed => Generate DDL, that DDL is not fetched from the database but from the cache. I need to refresh the database view or disconnect/reconnect to the database to actually see the ALTERed procedure in the DDL. Not sure if that is a feature or a bug though, but it is counter intuitive to show a cached version of the procedure instead of that one that actually is in the DB.

**Comment by iraidaa** [comment] 2022-08-19 10:52
Hello @Aileron79,

I think it's connected with the fact that there is  the main connection to the database in the navigator on the left.  For example, the SQL script uses another connection. If we made changes through one connection, then the other one should get to know about the change. That's why clicking Refresh helps.

**Comment by uslss** [comment] 2022-09-15 09:20
#6398

**Comment by dr-1** [comment] 2024-02-13 07:25
Related feature request: #21754

**Comment by dr-1** [comment] 2024-02-13 07:42
Additional tickets requesting the same feature: #8922, #15143. It's been a popular request.

#6398 seems to have a different scope - it asks to always refresh the table list of a database, not the DDL statements. Implementation wise, those could be related though.

**Comment by LonwoLonwo** [comment] 2024-02-14 09:31
Thank you for the bug report. It's a duplicate of #15431, #8922, so I'm closing this issue.
 You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by LonwoLonwo** 2024-02-14 09:31 UTC
Labels: duplicate, x:mssql, xf:metadata, x:azure
