### ISSUE TITLE
Double clicked SQL file is not opened. DBeaver.exe from command prompt with filename argument does not open the file

### ISSUE THREAD

**Issue by nilsvandermeer** [dbeaver/dbeaver#36009] opened 2024-10-21 13:46 UTC
### Description

When I click a file in the explorer DBeaver is started, but does not open the file. This is as of update to 24.2.3.0 (24.2.2.0 opens the file correctly)
If DBeaver is already started the message is that the workspace is already locked by an instance of DBeaver.
If I start DBeaver from the command line with an SQL filename, i.e.: dbeaver.exe "AnSQLFile.sql" the same happens.

 

### DBeaver Version

Community Edition 24.2.3.0

### Operating System

Windows 11 Pro

### Database and driver

N/A

### Steps to reproduce

See description for the 2 ways to reproduce.

### Additional context

From the log:
!ENTRY org.jkiss.dbeaver.model 2 0 2024-10-21 15:21:08.323
!MESSAGE SWT resource leak detected
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2024-10-21 15:21:08.323
!MESSAGE SWT Resource was not properly disposed
!STACK 0
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.TextLayout.<init>(TextLayout.java:302)
	at org.eclipse.jface.viewers.StyledCellLabelProvider.getSharedTextLayout(StyledCellLabelProvider.java:207)
	at org.eclipse.jface.viewers.StyledCellLabelProvider.measure(StyledCellLabelProvider.java:276)
	at org.eclipse.jface.viewers.OwnerDrawLabelProvider$OwnerDrawListener.handleEvent(OwnerDrawLabelProvider.java:58)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4326)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1174)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1198)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1183)
	at org.eclipse.swt.widgets.Table.sendMeasureItemEvent(Table.java:3647)
	at org.eclipse.swt.widgets.Table.hitTestSelection(Table.java:2834)
	at org.eclipse.swt.widgets.Table.showItem(Table.java:5318)
	at org.eclipse.swt.widgets.Table.showSelection(Table.java:5411)
	at org.eclipse.swt.widgets.Table.setSelection(Table.java:4994)
	at org.eclipse.jface.viewers.TableViewer.doSetSelection(TableViewer.java:315)
	at org.eclipse.jface.viewers.AbstractTableViewer.setSelectionToWidget(AbstractTableViewer.java:910)
	at org.eclipse.jface.viewers.StructuredViewer.setSelectionToWidget(StructuredViewer.java:1706)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1662)
	at org.eclipse.jface.viewers.TableViewer.setSelection(TableViewer.java:167)
	at org.eclipse.e4.ui.internal.workbench.renderers.swt.AbstractTableInformationControl.selectFirstMatch(AbstractTableInformationControl.java:443)
	at org.eclipse.e4.ui.internal.workbench.renderers.swt.BasicPartList.setInput(BasicPartList.java:169)
	at org.jkiss.dbeaver.ui.e4.DBeaverStackRenderer.showAvailableItems(DBeaverStackRenderer.java:96)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showAvailableItems(StackRenderer.java:1268)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer$3.showList(StackRenderer.java:1233)
	at org.eclipse.swt.custom.CTabFolder.onSelection(CTabFolder.java:2196)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:340)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4326)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1174)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4124)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3712)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:293)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:650)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:610)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1461)
!SESSION 2024-10-21 15:22:15.646 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=nl_NL
Framework arguments:  -eclipse.keyring C:\Users\ik\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by E1izabeth** [comment] 2024-10-22 09:57
Thanks for the bug report. I reproduced the issue

**Comment by serge-rider** [comment] 2024-10-22 14:38
Perhaps it was a result of #36006 , i.e. new custom launcher.
Cannot reproduce it anymore in `devel`

**Comment by kseniaguzeeva** [comment] 2024-10-23 08:55
Can't reproduce too (Version 24.2.4.202410230637).

**Comment by slick59** [comment] 2024-10-23 13:52
Problem started occurring for me on Windows with  24.2.3.202410201725.  Tried starting using the -f option explicitly to open a file and worked.  Altered registry Computer\HKEY_CURRENT_USER\SOFTWARE\Classes\Applications\dbeaver.exe\shell\open\command from "G:\Program Files\DBeaver\dbeaver.exe" "%1" to "G:\Program Files\DBeaver\dbeaver.exe" -f "%1" and double-clicking again works to open file in current DBeaver session.

**Comment by xinyongtian** [comment] 2024-10-23 16:28
I have same problem after upgrading to 24.2.3

**Comment by arhayka** [comment] 2024-10-29 22:49
@xinyongtian @slick59 
This issue should be resolved with the next 24.2.4 release.
In the meantime, you can test it beforehand using the Early Access version: https://dbeaver.io/files/ea/.

**Closed as completed** 2024-10-30 08:08 UTC
Labels: can't reproduce, xp:major, regression, xrn:internal

**Comment by ntimpj** [comment] 2025-02-04 12:30
I have the same problem, I can't open a file from filesystem I am on Ubuntu 24.4 and Dbeaver 24.3.4
I tried dragging the file in with the mouse, and i works, or at least it open a file window, but it's empty. So it don't work as expected. 
My only possibility for a opening a file is open it in Ubuntu text editor and copy the sql into Dbeaver.
