### ISSUE TITLE
Can't input text in any text boxt on Ubuntu 20.04 (only for Wayland)

### ISSUE THREAD

**Issue by Koi7** [dbeaver/dbeaver#12753] opened 2021-06-07 07:13 UTC
Thanks for great DB management tool!
When I switch to Wayland on my Ubuntu I can not input text into ALL text boxes in the interface.
Seems to be the same problem as was described here - https://github.com/dbeaver/dbeaver/issues/8499 
Please fix this.

**Comment by Matvey16** [comment] 2021-06-07 07:24
Please provide more information about your environment. What version of Ubuntu are you using? And what version of GNOME?

**Comment by Koi7** [comment] 2021-06-07 09:05
Ubuntu version 20.04. 
![image](https://user-images.githubusercontent.com/9104031/120989880-ae60ef00-c788-11eb-94ff-f0cde6c3218a.png)

**Comment by Koi7** [comment] 2021-06-07 09:06
I switched to X11 to be able input text into dbeaver.

**Comment by Matvey16** [comment] 2021-06-17 07:59
It looks like a third party issue not exclusive to DBeaver, so we will have to wait and see if Canonical and Wayland developers will figure something in the future.
For now you can try this workaround that sometimes helps people with the same problem but in other applications.

> Make the application that you want to interact (or say typing into) always on the top. Just simply right click on the title bar and click "Always on the top";

**Comment by uslss** [comment] 2021-11-19 08:52
@Koi7 is it still actual for you?

**Comment by uslss** [comment] 2021-11-22 08:57
probably duplicates #5322

**Comment by Koi7** [comment] 2021-11-30 11:02
not actual for me, switched to windows

**Comment by uslss** [comment] 2021-12-06 12:00
closed as a duplicate of #5322

**Closed as completed by uslss** 2021-12-06 12:00 UTC
Labels: can't reproduce, duplicate, xo:linux, environment, third party issue
