### ISSUE TITLE
Bootstrap queries dont save after restart

### ISSUE THREAD

**Issue by wac0013** [dbeaver/dbeaver#6438] opened 2019-08-05 11:35 UTC
#### System information: 
- Operating system: Windows 8
- DBeaver version: 6.1.3 - 6.1.4
- Java version: 8

#### Connection specification:
- DB: Sybase - ASE16
- Driver: JConnect and JTDS
- Proxy: no 

#### Describe the problem you're observing:
After update to 6.1.3 version and migrate config workspace, I set the bootstrap queries in "Connection settings > Initialization > Bootstrap queries > Add", add the query "set quoted_identifier off", this work normaly. But after restart dbeaver this query is clear in the list of bootstrap queries.

In file data-sources.json the option is set correctly, 
`"bootstrap": {
    "query": [
       "set quoted_identifier off"
    ]
}
`

**Comment by serge-rider** [comment] 2019-08-05 11:37
Duplicate of #6356
We will release hotfix of 6.1.4 version shortly. It will include this bug fix.

**Closed by serge-rider** 2019-08-05 11:37 UTC
Labels: bug, duplicate
