### ISSUE TITLE
SQL Editor Display Issues caused by SQL Syntax Parser

### ISSUE THREAD

**Issue by afreller-1wa** [dbeaver/dbeaver#22904] opened 2024-02-21 16:30 UTC
### Description

Recently I am getting display issues on OSX with latest DBeaver. Please see attached screenshot.
![Screenshot 2024-02-21 at 8 26 10 AM](https://github.com/dbeaver/dbeaver/assets/50186072/27b10aff-0463-41cf-a796-f9e089d6983b)

I think it has something to do with the SQL Syntax parser. If I disable the parsing the text is displayed correctly.

### DBeaver Version

Community Edition Version 23.3.5.202402181738

### Operating System

macOS 14.2.1

### Steps to reproduce

Open SQL Editior
Add some sql commands with brackets ()

**Comment by E1izabeth** [comment] 2024-02-21 16:42
Thank you for bug report. It's a duplicate of #22299
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-02-21 16:42 UTC
Labels: duplicate, xo:macos, xf:sql editor
