### ISSUE TITLE
SQL Server integrated authentication broken at v 7.0.1

### ISSUE THREAD

**Issue by dpsspatial** [dbeaver/dbeaver#8257] opened 2020-03-24 18:29 UTC
Hi all,

An analyst upgraded to v 7.0.1 and started getting errors when connecting to SQL Server via windows authentication. I upgraded as well and am having the same issue. Reverting back to 6.3.5 and things work fine. 

Here is the error message: 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/PDI6o.png

#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.0.1
- Additional extensions

#### Connection specification:
- Database name and version: MS SQL Server 
- Driver name: Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

**Comment by uslss** [comment] 2020-03-24 18:30
seems to be duplicate of #8251 .
Closed.

**Closed by uslss** 2020-03-24 18:30 UTC
Labels: bug, duplicate

**Comment by dpsspatial** [comment] 2020-03-24 18:33
Thanks @uslss !!
