### ISSUE TITLE
Labels are black while using Dark theme on 7.3.2

### ISSUE THREAD

**Issue by ienigmax** [dbeaver/dbeaver#10887] opened 2021-01-06 09:12 UTC
Good morning all,

I want to report a strange bug with **Darkest Dark** theme on some new versions of DBeaver (Happened on 2 different PCs)
 
I've experienced this strange issue on both 7.3.1 and 7.3.2. On 7.3.0 the label is white and readable, on 7.3.1 and 7.3.2 the label is black and it is way harder to get what you are working on.

I've attached a screenshot on the link below
[https://ibb.co/3vYCtGg](https://ibb.co/3vYCtGg)

- OS: Windows 10

**Comment by kseniiaguzeeva** [comment] 2021-01-06 10:10
Thank you for the report.

**Comment by kseniiaguzeeva** [comment] 2021-03-01 08:39
Similar issues: 
[Icons do not respect colors in black theme](https://github.com/dbeaver/dbeaver/issues/11506),
[Notification wrong color theme](https://github.com/dbeaver/dbeaver/issues/10841), 
[DevStyle selected menu items colors](https://github.com/dbeaver/dbeaver/issues/11535)

**Comment by serge-rider** [comment] 2021-03-13 19:53
Problem with black labels seems to be Windows-specific.
See https://stackoverflow.com/questions/64049172/how-to-fix-black-foreground-color-for-selected-text-item-in-eclipse-dark-themes

We can't revert to older Eclipse version. 
So upgrading Windows 10 version seems to be the only solution for now.

**Comment by smeagol152** [comment] 2021-03-14 21:56
Hello @serge-rider , please reconsider this bug since I'm in Windows Built 2004 and I still have this issue,

Warm regards

**Comment by uslss** [comment] 2021-03-15 08:12
still reproducible for dark and darkest dark themes against win10 2004

**Comment by qupear** [comment] 2021-03-15 08:17
This is reproducible on Windows 10H2 as well as Windows 7 Windows Server 2008 and Windows Server 2019. So there is probably no relation to an OS version. There needs to be a white/red/green foreground for such menu elements to be seen.

**Comment by dicaetano** [comment] 2021-03-19 12:21
I'm facing some problem with font color of the icons with the same theme, but in linux. Do I need to create a specific issue? 

![1](https://user-images.githubusercontent.com/20803573/111778985-47702000-8894-11eb-97c9-31028568fd34.png)

When I open some menu, like Preferences, the color gets fixed: 

![2](https://user-images.githubusercontent.com/20803573/111779040-5e167700-8894-11eb-85f0-e2683786538a.png)

**Comment by SnowPowerCore** [comment] 2021-03-25 12:23
+1 having the same issue on Windows 10 20H2

**Comment by serge-rider** [comment] 2021-04-05 09:24
It is Eclipse-specific and it happens when theme in DBeaver doesn't match theme in OS (i.e. light OS theme + dark DBeaver theme).

Possibly will be fixed with next Eclipse version upgrade.

**Comment by SnowPowerCore** [comment] 2021-04-05 09:39
> It is Eclipse-specific and it happens when theme in DBeaver doesn't match theme in OS (i.e. light OS theme + dark DBeaver theme).
> 
> Possibly will be fixed with next Eclipse version upgrade.

No, i have both themes matching: OS theme is dark & DBeaver appearance theme is set to dark too.

**Comment by smeagol152** [comment] 2021-04-08 20:16
Hello, is this issue fixed with Eclipse migration?

**Comment by serge-rider** [comment] 2021-04-08 20:41
Not yet.
There are related Eclipse bugs:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=562043
https://bugs.eclipse.org/bugs/show_bug.cgi?id=566280

Looks like DBeaver misses new E4 bundle which may fix the problem on Windows 10.

**Comment by serge-rider** [comment] 2021-04-09 08:47
Fixed. Along with main/context menus and scrollbars.

The fix works only for Windows 10 1903+.
In earlier Windows 10 versions it will remain the same.

![image](https://user-images.githubusercontent.com/6398845/114154501-26499f00-9929-11eb-94f7-086a99b9cac0.png)

**Comment by serge-rider** [comment] 2021-04-09 10:14
You can test it in the Early Access version (https://dbeaver.io/files/ea)

**Comment by smeagol152** [comment] 2021-04-09 10:32
Confirmed. It is fixed in Windows 10 Build 2004

**Comment by uslss** [comment] 2021-04-09 10:37
verified

**Closed as completed by uslss** 2021-04-09 10:37 UTC
Labels: xf:dark theme, sp:3

**Comment by SnowPowerCore** [comment] 2021-04-09 12:48
Hope this fix would also be pushed to Microsoft Store version...

**Comment by computer-logix** [comment] 2021-07-24 21:38
Also happens on Windows 11

Edition	Windows 11 Pro
Version	21H2
OS build	22000.100
Windows Feature Experience Pack 421.18901.0.3
