### ISSUE TITLE
Transaction mode automatically changes from "Auto-commit" to "Manual commit" when "Smart commit mode" is active when executing DDL command

### ISSUE THREAD

**Issue by mateusviccari** [dbeaver/dbeaver#20895] opened 2023-08-15 10:40 UTC
### Description

Every time I run a DDL command in the editor, if I have the options "Auto-commit" and "Smart commit mode" selected, it automatically changes it to "Manual commit" and doesn't go back to "Auto commit" after the transaction is commited or rolled back, when in fact it should remember the previous selection. Here's a video showing this behavior:
[2023-08-14 15-16-23.webm](https://github.com/dbeaver/dbeaver/assets/8275175/ceb770df-4422-46d6-9797-7b335f497923)

### DBeaver Version

Community edition 23.1.4

### Operating System

Windows 11 21H2

### Database and driver

Database: Microsoft SQL Server 2019
Driver: Microsoft JDBC Driver for SQL Server

### Steps to reproduce

1. Change the query mode to "Auto-commit" and "Smart commit mode"
2. Execute a DDL command
3. Commit or rollback the transaction
4. Look at the selected mode, it should be set again to "Auto-commit"

**Comment by E1izabeth** [comment] 2023-08-27 11:12
Thank you for report. However, it's not a bug, see https://github.com/dbeaver/dbeaver/issues/20827#issuecomment-1669680031

Duplicate of #20827

**Closed as not planned** 2023-09-14 15:02 UTC
Labels: wait for response, question
