### ISSUE TITLE
support patterns in table name filter of Database Navigator View

### ISSUE THREAD

**Issue by imod** [dbeaver/dbeaver#11088] opened 2021-01-22 06:31 UTC
**Is your feature request related to a problem? Please describe.**
I'm coming from "Sequel Pro" (https://www.sequelpro.com) and there is one thing that I'm really missing in DBeaver: 
DBeaver and Sequel Pro, both support the filtering of the shown tables in the navigator, but Sequel Pro not only supports to enter pats of the table name,  but patterns. This feature allows to filter for tables which have no common part in the name. e.g. the filter "job.con|usr" will filter for tables like "job_config" AND "usr_data"

**Describe the solution you'd like**
I would like DBeaver to support patterns in the table filter, e.g. "." for a single character and "|" for an OR combination of two patterns.

**Comment by kseniiaguzeeva** [comment] 2021-01-26 06:46
Thank you for the suggestion. We already have the similar option. Select Filter>Configure filter.. in table/schema context menu in DB Navigator. You can add multiple objects to filter and use masks there. Here is wiki article https://github.com/dbeaver/dbeaver/wiki/Configure-Filters

**Comment by imod** [comment] 2021-01-26 08:02
Many thanks for the hint to the existing filter options. I just took a look at it and yes it does allow me to filter the tables by name. But to be very honest, I can't think of a way how this could help me in any way (other then when I always want to see the same tables):

- it does not allow me to have multiple patterns, e.g. I can not filter for all tables with prefix `usr*` AND `batch*`
- it does not allow me filter by table name across multiple databases
- even though I was able to save multiple filters, I was not able to figure out how to switch between them: I only see a toggle filter option

**Comment by tati-kru** [comment] 2021-05-31 10:02
Seems to be duplicate of #10137

**Comment by LonwoLonwo** [comment] 2021-06-07 13:54
About dot pattern

You can use asterisk in the pattern for a single character

![2021-06-07 16_52_21-Window](https://user-images.githubusercontent.com/45152336/121028900-db28fc80-c7b0-11eb-8324-9f76c2ea4690.png)

**Comment by LonwoLonwo** [comment] 2021-06-16 09:13
Implemented in scope with https://github.com/dbeaver/dbeaver/issues/10137

**Closed as completed by LonwoLonwo** 2021-06-16 09:13 UTC
Labels: sp:2
