### ISSUE TITLE
DBeaver (snap)  won't let me export/import databases.

### ISSUE THREAD

**Issue by smaatcoda** [dbeaver/dbeaver#8508] opened 2020-04-21 15:53 UTC
I'm running Ubuntu 20.04, maybe that's the problem, but I decided to report the bug I encountered.

**System information:** 
- Ubuntu 20.04 on Wayland
- DBeaver version: 7.0.3.202004191823 (snap)

**Connection specification:**
- MySQL version: 8.0.19
- Driver name: MySQL
- No tunnels or proxies (SSH, SOCKS, etc).

DBeaver won't let me export/import DBs. 
Using the default local mysql parameter (connection settings)

> /snap/dbeaver-ce/55/usr 

brings the following error:

> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (13 "Permission denied")

I tried pointing DBeaver to local mysql client like it is set up in the apt version

> /usr

but it doesn't work either and causes another error:

> IO error: Utility 'mysql' not found in client home '/usr' (/usr)

Steps to reproduce, if exist:
1. Install DBeaver version: 7.0.3.202004191823 (snap).
2. Install MySQL 8.0.19.
3. Create a DB and try to import data.
4. Get error ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (13 "Permission denied").

**Comment by wujekkiryl** [comment] 2020-05-10 19:33
I have the same problem

**Comment by onokje** [comment] 2020-05-15 19:29
Same problem here. Ubuntu 20.04, mysql server 8.0.20, dbeaver 7.0.3

**Comment by leonardoUhomie** [comment] 2020-05-17 16:51
I have the same problem right now too!

**Comment by uslss** [comment] 2020-05-22 15:15
thanks for the bug report

**Comment by ElijahAhianyo** [comment] 2020-06-08 22:34
same problem here. Ubuntu 18.04

**Comment by abdu4188** [comment] 2020-06-09 06:52
Same problem on ubuntu 18.04 too

**Comment by tttogo** [comment] 2020-06-17 11:17
Add another to the list. Ubuntu 20.04 / dbeaver 7.1.0 (snap)

**Comment by EliasJuniorNino** [comment] 2020-06-30 18:49
Same problem on ubuntu 20.04 too

**Comment by shashinvision** [comment] 2020-07-14 03:01
Same problem with mariaDB in a local host with a user root without password :C on Kubuntu 20.04 LTS, DBeaver installed with snap

**Comment by naezeroth** [comment] 2020-07-17 01:56
Same issue here with ubuntu 20.04

**Comment by EliasJuniorNino** [comment] 2020-07-29 21:11
it was happening to me, i updated dbeaver to the latest version and it worked.

**Comment by hibernius** [comment] 2020-08-10 15:19
Same issue on Ubuntu 20.04. Updating to latest version did not work. I've tried via deb, apt repo and snap.

**Comment by zloadmin** [comment] 2020-08-19 13:46
Same problem on ubuntu 20

**Comment by keithchee** [comment] 2020-09-07 04:52
same problem 
MySQL version: 8.0.21-0
ubuntu 20.04.4

**Comment by aldbgh** [comment] 2020-09-29 13:24
same problem on Kubuntu 20.04.4
MySQL version: 8

**Comment by Pablo75321** [comment] 2020-11-16 18:02
Try change the host from localhost to 127.0.0.1 😅

**Comment by giovannefc** [comment] 2020-11-26 15:22
@Pablo75321 
Perfect!!

**Comment by foxbit19** [comment] 2020-12-01 17:09
Same issue here.
By default, on import/export, dbeaver shows me:
```
Utility 'mysql' not found in client home
```

I discovered this path `/snap/dbeaver-ce/93/usr` is wrong because the folder `usr` does not exists. 
So I created it and in my case this fixed the issue.

**Comment by foxbit19** [comment] 2020-12-04 14:26
Nevermind. Issue persists using postgresql database.
I left `snap` package for now and install the `deb` package.
Adding public repository is discouraged because, unfortunately, public key is outdated.
I've managed using this link: [https://dbeaver.io/debs/dbeaver-ce/](https://dbeaver.io/debs/dbeaver-ce/) to download the `.deb` package.

**Comment by agmckee** [comment] 2021-01-11 15:36
It seems this issue is caused by the data source definition file, `data-sources.json`, in the workspace having file path references to obsolete versions of the snap. For each connection there is a key called configuration which has a key called home that points to the snap's usr directory. All works fine until you get updates to the snap at which point the reference to e.g. `/snap/dbeaver-ce/91/usr` no longer points to an existing file.

A workaround that seems to be stable and persistent is to edit that file and replace the version number in each of the connection config home property values with "current" e.g. change `/snap/dbeaver-ce/91/usr` to `/snap/dbeaver-ce/current/usr`. This works because current is a symlink to the current release installed on your system.

Tested on Linux only. Hope it helps someone, while this issue remains unresolved.

**Comment by remi-parain** [comment] 2021-02-11 09:58
> Try change the host from localhost to 127.0.0.1

it works ! thanks

**Comment by junedev** [comment] 2021-08-31 16:53
@agmckee Thanks so much! This worked perfectly for me.

**Comment by MarceloHoffmeister** [comment] 2021-09-08 15:32
> Try change the host from localhost to 127.0.0.1 sweat_smile

This doesn't work for me



> It seems this issue is caused by the data source definition file, `data-sources.json`, in the workspace having file path references to obsolete versions of the snap. For each connection there is a key called configuration which has a key called home that points to the snap's usr directory. All works fine until you get updates to the snap at which point the reference to e.g. `/snap/dbeaver-ce/91/usr` no longer points to an existing file.
> 
> A workaround that seems to be stable and persistent is to edit that file and replace the version number in each of the connection config home property values with "current" e.g. change `/snap/dbeaver-ce/91/usr` to `/snap/dbeaver-ce/current/usr`. This works because current is a symlink to the current release installed on your system.
> 
> Tested on Linux only. Hope it helps someone, while this issue remains unresolved.

same on this. I have the usr/ directory in both paths

I'm using Kubuntu 20.04. For now i uninstall dbeaver by snap and reinstall using .deb, always work.

**Comment by mannuespinosa** [comment] 2021-11-29 06:35
> Try change the host from localhost to 127.0.0.1 😅

Thanks a lot!

**Comment by osmar-mobilezone** [comment] 2022-05-12 12:48
> Try change the host from localhost to 127.0.0.1 sweat_smile

It works.. thanks!!!!

**Comment by Matvey16** [comment] 2022-05-29 20:59
It should have been fixed in the latest version of snap package where we changed the confinement.
Please reopen the issue if it is still actual for you

**Closed by Matvey16** 2022-05-29 20:59 UTC
Labels: bug, environment, xf:snap

**Comment by maurocolella** [comment] 2022-07-05 04:47
@Matvey16 I have just encountered the issue on Ubuntu 20.04

I started with the snap package, updated to the latest version of dbeaver-ce (22.1.1).

I couldn't see any native client (I am using mariadb), so I uninstalled, installed the deb package (from the website), reconfigured my connection to use locahost, and I encountered the issue in this thread.

I then configured my connection to use 127.0.0.1 instead of localhost, re-connected, and I was able to export.

**Comment by Dillonsmart** [comment] 2022-09-24 10:31
> Try change the host from localhost to 127.0.0.1 😅

This worked!

**Comment by jgaleaO** [comment] 2023-08-31 17:16
> Try change the host from localhost to 127.0.0.1 😅

ahahahah nice, it works!

**Comment by haidarabdillah** [comment] 2023-09-01 13:03
> Try change the host from localhost to 127.0.0.1 😅

save my day

**Comment by eciosilva** [comment] 2024-11-18 06:31
> Try change the host from localhost to 127.0.0.1 😅

Thank U !!!! =D
