### ISSUE TITLE
(or bug?) Importing from CSV does not update Preview Data fields (ver. 6.3.4.202002011957)

### ISSUE THREAD

**Issue by mariano-daniel** [dbeaver/dbeaver#7893] opened 2020-02-12 02:56 UTC
#### System information: 
- OSX El Cap 10.11.6
- DBeaver version  6.3.4.202002011957

#### Connection specification:
- MySQL.

#### Describe your question:
Hi, I'm new to SQL and DBeaver, I've been trying to import the following database CSV: [https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=question%2C+wait+for+review&template=question.md&title=](https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=question%2C+wait+for+review&template=question.md&title=).
I create the table with the corresponding cols, however, DBeaver seems to import them in its own order. I always need to rearrange the data source from the Preview Data Import page at the Wizard, and even doing so, the Data Previes does not update with the correct info, and import is always wonky, with many rows missing.

Strange thing is, this is not the case on MYSQL Workbench. Any ideas as to why?

Attached you will find the importing settings (I think they're the default ones). Any ideas why I'm unable to import the CSV properly? I've tried several options (unticking most checkboxes) and none worked.

Thanks in advance!
<img width="681" alt="Screen Shot 2020-02-11 at 11 50 03 PM" src="https://user-images.githubusercontent.com/60707523/74298974-09680a80-4d2a-11ea-9505-188a617c6264.png">

**Comment by uslss** [comment] 2020-02-12 09:44
hi @mariano-daniel ,
unfortunately, link to CSV is broken. could you try to share it once again?

**Comment by jacobmischka** [comment] 2020-02-12 16:12
I'm getting the same issue, CSV import currently seems completely broken. Selecting sources for fields doesn't update the preview table, and furthermore doesn't seem to actually take effect when trying to run the import and hope for the best.

**Comment by jacobmischka** [comment] 2020-02-12 16:25
I'm also getting this error when trying to import a different CSV into a different table. Unsure if related, but I imagine it probably is. It also works after downgrading to 6.3.0.

![image](https://user-images.githubusercontent.com/3939997/74355060-f123da00-4d81-11ea-80f7-85142bb24d5a.png)

**Comment by mariano-daniel** [comment] 2020-02-14 17:56
> hi @mariano-daniel ,
> unfortunately, link to CSV is broken. could you try to share it once again?

Hello uslss! Yeah, seems like they cannot show files that big, lemme upload it...

[https://www.dropbox.com/s/iazrjgb0s3lrzwu/earthquake.csv?dl=0](url)

Let me know if it's downloadable now.

**Comment by patrickmdnet** [comment] 2020-02-16 21:12
Duplicate of #7725

**Comment by uslss** [comment] 2020-02-17 08:30
thanks for the bug report.
Seems that it is duplicate of #7725. This ticket will be closed

**Closed** 2020-02-17 08:30 UTC
Labels: duplicate, question, wait for response
