### ISSUE TITLE
Within a project, highlight bookmarked items

### ISSUE THREAD

**Issue by rrousselot** [dbeaver/dbeaver#13419] opened 2021-08-03 14:38 UTC
**Is your feature request related to a problem? Please describe.**
If a bookmark is created, highlight the items up the tree to the table within the connection view so that the bookmark can be easily found.  A filter to bookmarked items in connections view could be an alternative as well.  

This would be very helpful when working with large and complex schemas/tables.

**Comment by ShadelessFox** [comment] 2022-05-20 10:11
Duplicate of #11798

**Closed as not planned by ShadelessFox** 2022-05-20 10:11 UTC
Labels: duplicate, xf:navigator
