### ISSUE TITLE
Azure SQL MFA login does not work

### ISSUE THREAD

**Issue by paulstegmann** [dbeaver/dbeaver#19180] opened 2023-02-24 11:20 UTC
### Description

Hi!

On Mac and Windows, i am unable to log in via MFA. A blank browser window opens (localhost), but apparently the authentication is not sent back to the client. 

What can I do?

### DBeaver Version

Community 22.3.5.202302180832

### Operating System

macOS Ventura 13.2.1

**Comment by LonwoLonwo** [comment] 2023-02-24 12:50
Probably duplicate of https://github.com/dbeaver/dbeaver/issues/16130

**Comment by LonwoLonwo** [comment] 2023-02-27 12:59
Hello @paulstegmann 

Please try do this:

```
Go to "Edit Driver Settings," click the "Libraries" tab, then click "Add Artifact," then add the Maven dependency declaration:

<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j --> <dependency> <groupId>com.microsoft.azure</groupId> <artifactId>msal4j</artifactId> <version>1.11.3</version> </dependency> 
```

https://github.com/dbeaver/dbeaver/issues/15446#issuecomment-1097140996

**Comment by uslss** [comment] 2023-03-22 11:57
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.

**Closed as completed by uslss** 2023-03-22 11:57 UTC
Labels: wait for response, x:azure, xf:connection
