### ISSUE TITLE
When trying to expand "Scripts" folder in "Projects" Window: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: " K"

### ISSUE THREAD

**Issue by Marmeladenbrot** [dbeaver/dbeaver#21599] opened 2023-10-20 10:17 UTC
### Description

This happens after upgrading from Community Edition 23.2.0 or 23.2.1 to 23.2.2.

Trying to expand my "Scripts" folder in the "Projects" window results in an

```
URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: " K"

Reason:
URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: " K"
```
popup error.

Nothing else changed between the upgrade.

The file names in the "Scripts" folder contain sensitive company information and can't be shared here.

### DBeaver Version

Community Edition 23.2.2

### Operating System

Windows 11

### Additional context

Extensions: Office Extension, Git Extension

**Comment by LonwoLonwo** [comment] 2023-10-20 10:37
Hello @Marmeladenbrot 

Thanks for the report.

This is a duplicate of https://github.com/dbeaver/dbeaver/issues/21501

**Closed as completed by LonwoLonwo** 2023-10-20 10:37 UTC
Labels: duplicate
