### ISSUE TITLE
Grouping SQL Editor Tabs

### ISSUE THREAD

**Issue by nickcurties** [dbeaver/dbeaver#21965] opened 2023-11-23 12:45 UTC
**Issue**
I can be dealing with multiple SQL editor tabs within multiple connections. Although it is possible to drag the various tabs into sequence to keep tabs dealing with the same connection together, you rapidly end up with many tabs across the many connections losing track of which are which.

**Solution**
Provide an option to only show tabs which are for a selected connection. Whenever you select a database or connection from the database navigator you will only see the SQL editor tabs which are for that connection.

**Alternative**
Similar to how browsers such as Chrome work, allow the creation of editor groups into which you can move editor tabs as you create them. Each group can be compressed or expanded as required. This means you can have one group per connection and compress them as you leave that task and expand as you return.

**Additional context**

**Comment by E1izabeth** [comment] 2023-11-23 12:47
Thank you for the feature request. Similar request #21485. Also related to #10235

**Comment by E1izabeth** [comment] 2023-11-23 14:36
I adjusted the mentioned issue to your request and now closing it as a duplicate of #21485 to keep the one issue with such request.
You can vote for the issue with 👍 under the issue #21485 description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2023-11-23 14:36 UTC
Labels: duplicate, xf:ui
