### ISSUE TITLE
Add ability to customize what goes in the tab title

### ISSUE THREAD

**Issue by cormacrw** [dbeaver/dbeaver#18909] opened 2023-01-30 15:36 UTC
When I'm using dbeaver, I'm often working across multiple environments that use the same schema. As a result of this, if I have two tables of the same name but from different databases open in my editor, the tabs look the same.

I'd like to be able to either show the schema they come from or be able to fully customize what is in the tab.

VSCode does something like this, if you have two files with the same name it provides extra context:
![image](https://user-images.githubusercontent.com/32876806/215521767-ee3922b6-929f-42e7-b31b-8be59bb393f5.png)

**Comment by LonwoLonwo** [comment] 2023-01-30 17:17
So, would you like more than a tooltip?

![2023-01-30 20_14_57-DBeaver Ultimate 22 3 3 - 11 24 324FFd](https://user-images.githubusercontent.com/45152336/215547633-6152551d-846b-477f-9797-29374cecc614.png)

Because tooltips show all the extra info.

**Comment by cormacrw** [comment] 2023-01-30 18:31
I didn't realize that info was in the tooltip, that's nice. However, ideally I'd like that information to be readily available in the tab along side the table name.

**Comment by LonwoLonwo** [comment] 2023-01-31 08:40
Ok, thanks for the idea.

**Comment by E1izabeth** [comment] 2023-02-02 12:32
#10235
#18709

**Comment by E1izabeth** [comment] 2023-02-02 12:37
Thank you for the request.
I'll close it as a duplicate of #18709.
Additionally you can vote for this feature request by adding +1 emoji to the request body.

**Closed as not planned** 2023-02-02 12:38 UTC
Labels: duplicate, xf:ui

**Comment by gutweniger** [comment] 2024-03-12 07:46
In Version 23.3.0 there is a setting "Show fully qualified object names in editors title" in Preferences / Editors. 
Maybe that helps, @LonwoLonwo?
