### ISSUE TITLE
Again Oracle Create Procedure Throws Invalid SQL Statement

### ISSUE THREAD

**Issue by Pecaas** [dbeaver/dbeaver#11121] opened 2021-01-26 14:18 UTC
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.3.3
- Additional extensions

#### Connection specification:
- Database name and version Oracle 19i
- Driver name ojdbc8 12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
There is again a bug with Oracle Database CREATE PROCEDURE. In DBeaver 7.3.3 the code from issue #3742 throws:

    SQL Error [900] [42000]: ORA-00900: invalid SQL statement
    ORA-00900: invalid SQL statement

But it executes without a problem on the Oracle SqlDeveloper Client.

**Comment by Pecaas** [comment] 2021-01-26 14:21
Another example
CREATE OR REPLACE PROCEDURE DROPPRIMCONSTRAINT(ATABLENAME IN VARCHAR2,
                                               AOWNER     IN VARCHAR2)
  AS
    CURSOR CUR IS
        SELECT CONSTRAINT_NAME
          FROM ALL_CONSTRAINTS
          WHERE CONSTRAINT_TYPE = 'P'
            AND OWNER = AOWNER
            AND TABLE_NAME = ATABLENAME;
  BEGIN
    FOR I IN CUR
    LOOP
      --DBMS_OUTPUT.PUT_LINE('ALTER TABLE ' || AOWNER || '.' || ATABLENAME || ' DROP CONSTRAINT ' || I.CONSTRAINT_NAME || ' DROP INDEX');
      EXECUTE IMMEDIATE 'ALTER TABLE ' || AOWNER || '.' || ATABLENAME || ' DROP CONSTRAINT ' || I.CONSTRAINT_NAME || ' DROP INDEX';
    END LOOP;
  END DROPPRIMCONSTRAINT;
/

**Comment by ShadelessFox** [comment] 2021-07-02 11:41
Duplicate of #11510

**Closed as completed by ShadelessFox** 2021-07-02 11:41 UTC
Labels: x:oracle, xf:sql
