### ISSUE TITLE
DBeaver 22.3.4 not working properly with Hadoop Connections

### ISSUE THREAD

**Issue by Wusl83** [dbeaver/dbeaver#19023] opened 2023-02-09 13:33 UTC
### Description

After upgrading DBeaver from 22.3.3 to 22.3.4 the connection to Hadoop-Systems can´t be established:

```
When using JDBC-Driver "hive-jdbc-3.1.3000.7.1.6.0-297-standalone.jar" following error is published:
org.apache.hive.jdbc.ZooKeeperHiveClientException: Unable to read HiveServer2 configs from ZooKeeper
  Unable to read HiveServer2 configs from ZooKeeper
    KeeperErrorCode = AuthFailed for /hiveserver2
```

When using JDBC-Driver "HiveJDBC41.jar" this error appears:

```
[Cloudera][HiveJDBCDriver](500164) Error initialized or created transport for authentication: [Cloudera][HiveJDBCDriver](500169) Unable to connect to server: GSS initiate failed.
  [Cloudera][HiveJDBCDriver](500169) Unable to connect to server: GSS initiate failed
    GSS initiate failed
```

Even if ZooKeeper is not used the same error reveals:
Could not open client transport with JDBC Uri: jdbc:hive2://xxx.xxx:10000/default;ssl=true;principal=hive/_HOST@XXX: GSS initiate failed

After Downgrading to  DBeaver 22.3.3 everything works fine again.

### DBeaver Version

22.3.4

### Operating System

Windows 10 Enterprise

### Database and driver

Hadoop: CDP 7.1.6
hive-jdbc-3.1.3000.7.1.6.0-297-standalone.jar
HiveJDBC41.jar

### Steps to reproduce

Connect to hadoop-DB

**Comment by LonwoLonwo** [comment] 2023-02-09 14:11
Hello @Wusl83 

Could you please provide the full log file? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Wusl83** [comment] 2023-02-09 14:29
[.log](https://github.com/dbeaver/dbeaver/files/10698188/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10698192/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment] 2023-02-09 16:33
Did you use Kerberos authentication?

**Comment by Wusl83** [comment] 2023-02-10 06:06
Yes

**Comment by Wusl83** [comment] 2023-02-15 12:48
Hi LonwoLonwo,
do you have some new ideas?

**Comment by Destrolaric** [comment] 2023-02-16 14:00
Linked issue https://github.com/dbeaver/dbeaver/issues/18978

**Comment by LonwoLonwo** [comment] 2023-02-23 12:54
Hello @Wusl83 

To get more debug info please add line
-Dsun.security.krb5.debug=true in the end of dbeaver.ini file.

Then restart DBeaver, try to connect and then provide dbeaver-debug.log file again, please.

**Comment by Wusl83** [comment] 2023-02-24 07:56
Hello @LonwoLonwo 

this is the dbeaver-debug.log with added parameter (-Dsun.security.krb5.debug=true):
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10821863/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment] 2023-02-24 09:39
Mmm... thanks for the answer... Probably the issue is somewhere here:

```
Found unsupported keytype (23) for v0****0@DE.TOP.COM
Key for the principal v0****0@DE.TOP.COM not available in C:\Users\v0****0\AppData\Local\DBeaver\v082860.keytab
		[Krb5LoginModule] authentication failed 
Unable to obtain password from user
```

I will look into it closer.

**Comment by Wusl83** [comment] 2023-02-24 13:03
Hello @LonwoLonwo 

this is the log of Version 22.3.3 with activated parameter (-Dsun.security.krb5.debug=true) and the same keytab. This works fine. 

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10824289/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment] 2023-02-24 17:33
Could you please provide your krb5.ini file? With changed personal info, obviously.

**Comment by Wusl83** [comment] 2023-02-27 06:00
@LonwoLonwo: Here it is:
[krb5.zip](https://github.com/dbeaver/dbeaver/files/10836535/krb5.zip)

**Comment by LonwoLonwo** [comment] 2023-02-27 10:00
So. What I found.
As I mentioned earlier, I saw in your logs

> Found unsupported keytype (23) for v0****0@DE.TOP.COM

23 - is rc4 type and, it seems, it is deprecated:

https://blog.qualys.com/product-tech/2013/03/19/rc4-in-tls-is-broken-now-what

So, maybe you need another type of encryption. Or, perhaps you can use this advice https://stackoverflow.com/a/23883508 and add `default_tkt_enctypes, default_tgs_enctypes, permitted_enctypes` in your krb5 config file.

Please, let me know if it helps.

**Comment by Destrolaric** [comment] 2023-02-27 10:32
@ Wusl83 I recommend updating tls algorithm due to it being compromised a long time ago. Still, as workaround, I would suggest removing it from disabled and deprecated algorithms in `[folder of dbeaver]/jre/conf/security/java.security`, you need to find `RC4` in jdk.tls.disabledAlgorithms and jdk.tls.legacyAlgorithms and remove it from them.

**Comment by Destrolaric** [comment] 2023-02-27 10:52
https://bugs.openjdk.org/browse/JDK-8139348
Hi, I found the exact reason why behaviour changed. Issue is not related to previous message, these algorhitm was deprecated for Kerberos for Java 17

**Comment by Wusl83** [comment] 2023-02-27 13:26
Hi @LonwoLonwo & @Destrolaric ,
It works. When using JRE < 17 Kerberos Credentials make no problem.
Thanks for your Support !!!

**Comment by LonwoLonwo** [comment] 2023-03-01 11:08
Hello @Wusl83 
DBeaver is again on java 11.
Can you please test the Early Access DBeaver version? https://dbeaver.io/files/ea/ Is the issue solved there?

**Comment by Wusl83** [comment] 2023-03-01 11:59
Hello @LonwoLonwo,
it works fine with DBeaver 23.0.0 too.
It seems that JRE is no JAVA_VERSION="11.0.12" again and not 17?!

**Comment by LonwoLonwo** [comment] 2023-03-01 12:04
Yes, it is 11 again. Thanks for the answer @Wusl83 
I'm closing the ticket now. If we try to use 17 java in DBeaver, we will try not to forget about your case.

**Comment by Wusl83** [comment] 2023-03-01 12:06
@LonwoLonwo : Thank you very much !!!

**Comment by pombuppa** [comment] 2023-05-10 08:59
> in DBeaver, we will try not to forget about your case

DBeaver (2.3.x) seem to use JDK17 and now Kerberos connection is broken again.

**Comment by serge-rider** [comment] 2023-07-06 12:54
Will be fixed in the next release.
Workaround: add next lines to dbeaver.ini
```
--add-opens=java.security.jgss/sun.security.jgss=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED
```

**Closed as completed** 2023-07-07 08:12 UTC
Labels: x:hive, xf:connection, xo:java, xf:kerberos
