### ISSUE TITLE
SQL Editor keypress becomes slow after a while

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#9073] opened 2020-06-23 07:07 UTC
#### System information: 
- Operating system (distribution) and version: Mac 10.15.4 (19E287)
- DBeaver version 7.1.0

#### Connection specification:
- Database name and version: pg 12.2 on RDS, also happened on 11.2, 11.6.
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH tunnel via VPN

#### Describe the problem you're observing:
I usually work with the sql editor, no navigators and such, so I write many queries and the likes.
When I just open dbeaver, everything is smooth. when I type something it instantly shows on the editor. After a while of dbeaver being open, could be days, the typing in the editor becomes unusable - it takes a while from typing (sometimes a second) to the point where I see what I type, and the worst part is that sometimes the editor shows what I type ("hello") not in the same order I typed it ("helol").
I assume this is related to auto completion.
This is present in all dbeaver version since I think 6 (I upgrade regularly) - always have to restart dbeaver after a few days.

#### Steps to reproduce, if exist:
Open an SQL file (not so large, ~150 lines) with many different sqls in it.
Work ok, after a few days problem starts to occur.
The only way to resolve the problem is to restart dbeaver (disconnect/reconnect doesn't solve it).
While I do not have one right now, I'll try to take a video capture of when it happens.

**Comment by uslss** [comment] 2020-06-23 13:41
Hi @pyrocks ,
thanks for the bug report. Will try to catch it.
BTW, it will be nice if you'll capture a video, and probably steps that could help to reproduce it.
Thanks in advance

**Comment by pyrocks** [comment] 2020-07-13 08:53
This reproduces quite often, but I'm having problems taking a video as it comes and goes.
Before the last time I restarted dbeaver I saw it's memory consumption is almost 4GB with a few connections connected, 3 files open in the editor (~500 lines each) and a data grid with 200 rows - so nothing out of the ordinary. Maybe a memory leak?

**Comment by pyrocks** [comment] 2020-07-28 08:12
Reproduced - here's a video: https://streamable.com/lm9q2d
I keep writing "display_symbol" (I type fast) - it's slow to appear and not always in the same order I type (I usually don't have typos when writing - well not in such a consistent manner as is displayed in the video)
DBeaver now takes 2.14gb of memory
![image](https://user-images.githubusercontent.com/18515297/88637391-c674d600-d0c2-11ea-8ab4-473bf812ae85.png)
It's really a bummer having to restart dbeaver every few days :|

**Comment by uslss** [comment] 2020-07-29 14:27
probably similar to #7777

**Comment by uslss** [comment] 2020-08-17 13:14
closed as duplicate of #7777

**Closed by uslss** 2020-08-17 13:14 UTC
Labels: bug, can't reproduce, wait for response, xo:macos
