### ISSUE TITLE
Previous and Next Word using Ctrl+Left/Right key in SQL Editor

### ISSUE THREAD

**Issue by ahhmedbilal** [dbeaver/dbeaver#16376] opened 2022-04-30 08:42 UTC
**Is your feature request related to a problem? Please describe.**

I have a word e.g ABC-DEF_GHI_JKL
If i double click this word, this will select whole word i.e from A to L, that is fine. 

Now lets assume the cursor is before letter A, and when i press Ctrl+Right key 4 times, the cursor first go to after letter C, then after "-" and then after letter F and then after "_"

**Describe the solution you'd like**

What i want to happen is that, if i press Ctrl+Right key, then cursor should move from "A" to end of word i.e after letter L, so with one key press  (Ctrl+Right key), the whole word should be passed by. i.e the same behavior that Notepad++ shows. 

In SQL coding, underscore and hyphen are part of word and are used quite often, it will be a time saving to select/traverse the whole word in one go rather pressing the key combination multiple times. 

Normally some editor allows this setting to be configurable i.e they allow underscore/hyphen/$/# etc, as part of the word, not as word delimiter. 

So DBeaver should allow this setting to be configurable, so i can chose whether i want DBeaver to consider underscore (or any special character) as part of word or not. Please add this feature in settings to do customization. 

**Describe alternatives you've considered**

**Additional context**

**Comment by uslss** [comment] 2022-05-04 09:20
thanks for the suggestion.
Closed as a duplicate of #1155

**Closed as completed by uslss** 2022-05-04 09:20 UTC
Labels: duplicate
