### ISSUE TITLE
v21.0.3 for MacOs - SQL autocompletion only works for first mentioned table

### ISSUE THREAD

**Issue by c-hennecke** [dbeaver/dbeaver#12271] opened 2021-04-28 09:27 UTC
#### System information: 
- macOS 11.3 (20E232)
- 21.0.3

#### Connection specification:
- MySQL 5.7.32
- Driver "MySQL 5"

#### Describe the problem you're observing:
After the update to 21.0.3 the column name autocompletion in SQL editors only works for the first table named in the query.
E.g. 
For "SELECT * FROM TABLE1 t1, TABLE2 t2 WHERE t1." the autocompletion works
For "SELECT * FROM TABLE1 t1, TABLE2 t2 WHERE t2." the autocompletion does not work
For "SELECT * FROM TABLE2 t2, TABLE1 t1 WHERE t1." the autocompletion does not work
For "SELECT * FROM TABLE2 t2, TABLE1 t1 WHERE t2." the autocompletion works

#### Steps to reproduce, if exist:
See above explanation

#### Include any warning/errors/backtraces from the logs
Nothing in the log about that error.

**Comment by uslss** [comment] 2021-04-28 11:29
thanks for the report

**Comment by LonwoLonwo** [comment] 2021-04-28 12:39
This is duplicate of https://github.com/dbeaver/dbeaver/issues/12168

**Closed as completed** 2021-04-28 12:39 UTC
Labels: x:mysql, duplicate, xf:sql
