### ISSUE TITLE
Fetch data in loop with Trino 433 jdbc driver but query is finished a long time before on database

### ISSUE THREAD

**Issue by YuriyGavrilov** [dbeaver/dbeaver#22114] opened 2023-12-06 16:03 UTC
### Description

Fetching data going and going already more than 300 seconds but request are done on database in 4 second. 
When i click "cancel" in dbeaver i will see the results. 
There is only one way to know is the request is complete or not to watch on database.

![image](https://github.com/dbeaver/dbeaver/assets/44679014/0b4fe683-bf3e-427b-8d91-30beec85b338)

![image](https://github.com/dbeaver/dbeaver/assets/44679014/3bc9df7d-dc1d-4ef3-acbf-260da0f563e8)

### DBeaver Version

23.3.0.202312031432

### Operating System

Linux Astra

### Database and driver

Trino jdbc 433

### Steps to reproduce

Connect to trino 
Run query 
See Fetching ....  Fetching Fetching Fetching  until you cancel it.
See the data but you spend a lot of time to watching on Fetching ... and actually users don't know when it will be finished

**Comment by LonwoLonwo** [comment] 2023-12-07 14:08
Hello @YuriyGavrilov 

Maybe Could you please check these settings? Does disabling of them help the process?

![2023-12-07 17_06_59-Preferences](https://github.com/dbeaver/dbeaver/assets/45152336/22fa685a-abf8-4af8-9e91-5d4408bb6000)

**Comment by YuriyGavrilov** [comment] 2023-12-07 18:53
Thanks a lot @LonwoLonwo looks like it helps for the first view... but actually don't know what it means and is it will fix for the future without those setting turned off. Do you suggest to close this?

**Comment by LonwoLonwo** [comment] 2023-12-08 09:07
No, it just helped me to understand where the issue is. It is not in the data fetching but in the metadata loading.
You can use SQL Editor with these disabled settings. However, it will be hard to edit your data in the result set.

Do you have a large number of tables in your schema? Does the opening of nodes take a lot of time in the navigator tree?

**Comment by YuriyGavrilov** [comment] 2023-12-08 11:34
@LonwoLonwo we are never edit data in the datalake. Just selecting and join, create and making update sometime. Trino is the pilot project so there are just a not more than 10 tables in iceberg schema and another one is oracle which is also connected to Trino and after we see it in dbeaver, there are much more tables, 100,200, 1000 it depends on schemas. Search meta is not so long. Not to much to focus on it.

**Comment by LonwoLonwo** [comment] 2024-01-18 12:07
I'm closing this ticket as a duplicate of https://github.com/dbeaver/dbeaver/issues/21774.

**Closed as completed** 2024-01-18 12:07 UTC
Labels: duplicate, x:trino, performance
