### ISSUE TITLE
DBeaver can't edit a view in a Firebird database

### ISSUE THREAD

**Issue by silvioprog** [dbeaver/dbeaver#6392] opened 2019-07-31 14:22 UTC
Hi.

I've tried to edit a view in a Firebird database, however, the "Edit View" (F4) raises the following message:

```
class org.jkiss.dbeaver.ext.firebird.model.FireBirdView cannot be cast to class org.jkiss.dbeaver.ext.firebird.model.FireBirdTable (org.jkiss.dbeaver.ext.firebird.model.FireBirdView and org.jkiss.dbeaver.ext.firebird.model.FireBirdTable are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1e5f96c6)
```

My DBeaver Community version: `6.1.3.201907211943` (running both DBeaver and Firebird on Windows)

The same error raised when trying to edit views in other Firebird databases.

Thank you!

**Comment by silvioprog** [comment] 2019-07-31 14:57
The same error when click at "Indexes":

```
class org.jkiss.dbeaver.ext.firebird.model.FireBirdView cannot be cast to class org.jkiss.dbeaver.ext.firebird.model.FireBirdTable (org.jkiss.dbeaver.ext.firebird.model.FireBirdView and org.jkiss.dbeaver.ext.firebird.model.FireBirdTable are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1e5f96c6)
```

**Comment by serge-rider** [comment] 2019-07-31 17:02
Duplicate of #6260
You can test the fix in Early  Access (https://dbeaver.io/files/ea).

**Closed by serge-rider** 2019-07-31 17:02 UTC
Labels: bug, duplicate, x:firebird
