### ISSUE TITLE
Mysqldump window can't be closed after succesfull DB dump via SSH

### ISSUE THREAD

**Issue by mushketer888** [dbeaver/dbeaver#13913] opened 2021-09-15 10:54 UTC
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04
- DBeaver version 21.2.0
- Additional extensions None

#### Connection specification:
- Database name and version 
- Driver name Mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  Yes, SSH tunnel

#### Describe the problem you're observing:
Mysqldump window can't be closed after succesfull DB dump via SSH but it shows that it was finished. Window freezes and DBeaver can't be used. Can kill only with xkill
![alt text](http://i.imgur.com/nq39GTT.png)

#### Include any warning/errors/backtraces from the logs
Not sure if this helps (maybe not related)
!ENTRY org.jkiss.dbeaver.model 4 0 2021-09-15 13:44:59.840
!MESSAGE Error adding nested editor
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-09-15 13:44:59.840
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.eclipse.ui.part.MultiPageEditorSite.<init>(MultiPageEditorSite.java:135)
	at org.eclipse.ui.part.MultiPageEditorPart.createSite(MultiPageEditorPart.java:471)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:221)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:203)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.addEditorTab(EntityEditor.java:844)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.addContributions(EntityEditor.java:827)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.createPages(EntityEditor.java:625)
	at org.jkiss.dbeaver.ui.editors.MultiPageAbstractEditor.recreatePages(MultiPageAbstractEditor.java:193)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.recreateEditorControl(EntityEditor.java:1065)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart.initEntityEditor(ProgressEditorPart.java:109)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart.access$2(ProgressEditorPart.java:103)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.completeLoading(ProgressEditorPart.java:154)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.completeLoading(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob$LoadFinisher.run(LoadingJob.java:130)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5067)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4573)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

**Comment by uslss** [comment] 2021-09-15 12:11
thanks for the report
seems the issue is similar to #12674 .
Focus doesn't move from Export dialog to Notification dialog.
![image](https://user-images.githubusercontent.com/31996417/133430944-5ae3031e-a5bd-482a-8137-34c04f900cac.png)
Could you try to close it e.g. by pressing enter?

**Comment by mushketer888** [comment] 2021-09-15 12:16
Yes you are right. It seems

**Comment by uslss** [comment] 2021-09-15 12:18
I'll close this ticket as a duplicate, it will be fixed in the scope of #12674

**Closed as completed by uslss** 2021-09-15 12:18 UTC
Labels: duplicate, xo:linux
