### ISSUE TITLE
Schema ER lines

### ISSUE THREAD

**Issue by paoloholzl** [dbeaver/dbeaver#15076] opened 2021-12-28 16:08 UTC
Schema ER is better if you can request to start line left or right of fields connected in foreign keys (and not only to table box).
An other semplification my be permit to transform (for example using double click), relation line orientation to vertical or horizontal.

**Comment by paoloholzl** [comment] 2021-12-29 09:34
![Example](https://user-images.githubusercontent.com/96785200/147647802-ce697b87-423f-4656-a60c-726c5aa95b21.png)

**Comment by Skydiveroid** [comment] 2021-12-29 13:39
Thanks for the idea!

**Comment by dbeaver-pm** [comment] 2022-05-04 11:49
Duplicate of #15755

**Closed as completed by dbeaver-pm** 2022-05-04 11:49 UTC
Labels: duplicate, xf:erd
