### ISSUE TITLE
DBeaver Crashes when previewing a geometry column in PostgreSQL/Postgis

### ISSUE THREAD

**Issue by nunoragil** [dbeaver/dbeaver#18601] opened 2022-12-26 23:53 UTC
### Description

Hello,

I'm using a 2,6 GHz 6-Core Intel Core i7 MacBook Pro with macOS Ventura 13.1.
I've installed Dbeaver and I've created a few connections to several PostgreSQL/Postgis databases v12 and newer.
Every time I open a table with a Postgis geometry column and try to preview its value, Dbeaver crashes.

On other computers I've used it didn't happen.

Any ideas please?

Kind regards.

### DBeaver Version

Community edition 22.3.1.202212251901

### Operating System

macOS Ventura 13.1

### Database and driver

Database name: PostgreSQL + Postgis
Version: 12, for instance (it happens with all versions I've already tried)
Driver: PostgreSQL 42.5.0 + postgis jdbc 2.5.0 + postgis geometry 2.5.0

### Steps to reproduce

1. I connect to the PostgreSQL database
2. I open a table with a geometry column
3. I click on top of a cell and preview the value
4. Dbeaver  crashes

### Additional context

I use no tunnels nor proxies.

[dbeaver-report.txt](https://github.com/dbeaver/dbeaver/files/10305022/dbeaver-report.txt)

**Comment by LonwoLonwo** [comment] 2022-12-27 08:04
Thank you for the bug report. It's a duplicate of https://github.com/dbeaver/dbeaver/issues/18117

**Closed as not planned by LonwoLonwo** 2022-12-27 08:04 UTC
Labels: duplicate, xo:macos, xf:gis
