### ISSUE TITLE
No suitable driver(-s) found for specified JDBC URL

### ISSUE THREAD

**Issue by geokoz** [dbeaver/dbeaver#17864] opened 2022-10-10 15:06 UTC
### Description

Hi Dbeaver support,

I am using DBeaver 22.2.0 and trying to "Create new connection from JDBC URL". I added the jdbc url address of a PostgreSQL server that I want to connect to, but the popup window says: "No suitable driver(-s) found for specified JDBC URL" without considering whatever I write in the url box.
The "Proceed" button remains disabled at all times.
Any idea how to resolve this?

Thanks

### DBeaver Version

Community edition 22.2.0

### Operating System

Windows 10

### Database and driver

PostgreSQL 14
postgresql driver 42.2.25

### Steps to reproduce

1. trying to "Create new connection from JDBC URL". 
2. I added the jdbc url address of a PostgreSQL server that I want to connect to, which works otherwise from other products
3. The popup window says: "No suitable driver(-s) found for specified JDBC URL" without considering whatever I write in the url box.
4. The "Proceed" button remains disabled at all times.

### Additional context

No tunneling
No extensions specially used

**Comment by LonwoLonwo** [comment] 2022-10-10 16:27
Hello @geokoz 

Can you provide please example of your URL?

**Comment by LonwoLonwo** [comment] 2022-10-10 16:30
For now, I can't reproduce.

![2022-10-10 19_30_06-DBeaver Ultimate 22 2 2 - storage](https://user-images.githubusercontent.com/45152336/194913135-acd32f28-a12e-4724-a405-fe4c06ff532a.png)

**Comment by geokoz** [comment] 2022-10-10 17:05
I tried now something like (can't post the "xxxxxx" part), then it proceeds but when it tries to connect it just times out:
jdbc:postgresql://ae-aurora-cluster.cluster-XXXXXX.amazonaws.com:5432/XXX

It never time outs from my other connection (which is ETL IBM DataStage tool) and it has the same URL.
Thanks,Georgi

**Comment by LonwoLonwo** [comment] 2022-10-10 23:08
So... It gives you the driver and connection page, but you can not connect during the timeout problems? Or it something else?
Maybe you can provide me some footage of your issue, please?

**Comment by geokoz** [comment] 2022-10-10 23:20
Maybe I need some investigation from my network team, why it times out ... to trace the connection.When I get their reply, I'll come up with more details.

**Comment by LonwoLonwo** [comment] 2022-10-11 00:17
Ok, I'll wait for your answer.

**Comment by E1izabeth** [comment] 2022-10-17 13:50
Probably it's a duplicate of #17627

**Closed as not planned** 2023-01-13 09:49 UTC
Labels: x:postgresql, wait for response
