### ISSUE TITLE
In table Data view filter box, column name autocompletion (ctrl+space) no longer useable without pointer

### ISSUE THREAD

**Issue by anophelesgreyhoe** [dbeaver/dbeaver#3657] opened 2018-06-20 02:20 UTC
This is an issue that seems to have popped up in a recent version (5.1.x), whereby if I start typing a column name in the filter box in the Data view for a table, then select the desired column with the arrow keys before pressing enter, I now get this error.

![image](https://user-images.githubusercontent.com/11037075/41633862-09937af4-7495-11e8-9cb5-2039c84531ca.png)

Clicking the column to add from the list still works, but it would be great not to have to reach for the mouse.

**Comment by anophelesgreyhoe** [comment] 2018-06-20 02:29
I'll also mention an issue that may be the same underlying problem - although this one has been around for as long as I've been using DBeaver (since 3.x).

When using a function in the filter box with auto-completion, then pressing Enter to accept the selected column, a missing expression error is displayed (on Oracle databases at least).

![image](https://user-images.githubusercontent.com/11037075/41633991-bf6b4b4a-7495-11e8-9a43-ef55a31adab3.png)

Using the mouse works okay.

I've tried several other keys to select the autocomplete option as alternatives to clicking Enter or using the mouse, but haven't found any that allow accepting the autocomplete option.

**Comment by serge-rider** [comment] 2018-06-20 07:05
Duplicate of #3657
Thanks for report anyway

**Closed by serge-rider** 2018-06-20 07:05 UTC
Labels: bug, duplicate

**Comment by anophelesgreyhoe** [comment] 2018-06-20 07:07
Thanks Serge, but I have a question - this is #3657 - so a duplicate of itself?

**Comment by serge-rider** [comment] 2018-06-20 07:08
#3656, sorry :)
