### ISSUE TITLE
PostgreSQL 11 - Unable to edit JSON column

### ISSUE THREAD

**Issue by sharathr1** [dbeaver/dbeaver#11704] opened 2021-03-12 10:09 UTC
Whenever we edit a json column or non-json column in the table which has json column is not supported.

**Comment by uslss** [comment] 2021-03-12 11:34
thanks for the report

**Comment by LonwoLonwo** [comment] 2021-04-01 14:49
Hello @sharathr1 
Can you provide example of table DDL and version of your PostgreSQL database? I can't reproduce.
Thanks in advance.

PS: More precisely, while it turned out to be reproduced only when the update occurs with all columns as key.

**Comment by sharathr1** [comment] 2021-04-01 16:24
> Hello @sharathr1
> Can you provide example of table DDL and version of your PostgreSQL database? I can't reproduce.
> Thanks in advance.
> 
> PS: More precisely, while it turned out to be reproduced only when the update occurs with all columns as key.

CREATE TABLE "public"."AppConfig" (
	 id varchar(25) NULL,
	"type" varchar(100) NULL,
	jsonInfo json NULL
);

**Comment by LonwoLonwo** [comment] 2021-04-02 09:41
@sharathr1 Yes, I see.
We will fix it
As workaround - use real or virtual keys in table, then update statement will use them.

**Comment by LonwoLonwo** [comment] 2021-04-14 08:00
related https://github.com/dbeaver/dbeaver/issues/6779

**Comment by LonwoLonwo** [comment] 2021-11-16 14:34
Fixed in DBeaver 21.3.0
Works for update/delete statements in the tables without keys and with JSON or XML columns.

**Comment by uslss** [comment] 2021-11-17 10:13
verified

**Closed as completed by uslss** 2021-11-17 10:13 UTC
Labels: x:postgresql, sp:3
