### ISSUE TITLE
Execute SQL Query and Execute SQL Script are no longer executing correctly

### ISSUE THREAD

**Issue by Moridin11** [dbeaver/dbeaver#29313] opened 2024-05-02 19:49 UTC
### Description

Previous version when I selected a script on a line and pressed CTRL-ENTER.  It would execute that query only.  Now it is trying to execute some number of queries on my script.  I honestly can't figure out what it chooses to execute as it doesn't appear to be a semi colon.

### DBeaver Version

24.0.3

### Operating System

Windows 11

### Database and driver

Yellowbrick 5.4

### Steps to reproduce

have multiple individual queries on a single script.  When I try to just execute the 3rd query it tries to execute all 3 of those queries.

**Comment by E1izabeth** [comment] 2024-05-02 20:41
Duplicate of https://github.com/dbeaver/dbeaver/issues/26416
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Closed as not planned by E1izabeth** 2024-05-02 20:41 UTC
Labels: duplicate, xf:sql execution
