### ISSUE TITLE
[postgresql] anonymous code block issues

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#7157] opened 2019-11-04 10:16 UTC
Hello
When using $$ tag, code between those tags is displayed as regular string
Example:
![Image1](https://i.imgur.com/MB9Bd6x.png)

If however I use named tag, put cursor somewhere in the middle of this query
and execute it, DBeaver tries to execute selected line, failing of course.
![Image2](https://i.imgur.com/n498lyf.png[)
I suppose it's because Execute query searches for standard SQL query, knowing nothing about anonymous block syntax.

BTW is there a way to show the notice from examples above?

**Comment by uslss** [comment] 2019-11-06 14:35
Hi, do you use 6.2.4 version?

**Comment by michalk-k** [comment] 2019-11-06 18:29
Yes

**Comment by ems2811** [comment] 2019-11-07 07:32
Same issue #7183

**Comment by serge-rider** [comment] 2019-11-23 15:35
Duplicate of #7157

**Closed by serge-rider** 2019-11-23 15:35 UTC
Labels: bug, duplicate
