### ISSUE TITLE
Configuration to limit result set by SQL does not seem to work

### ISSUE THREAD

**Issue by codearoo** [dbeaver/dbeaver#18302] opened 2022-11-22 21:29 UTC
### Description

I would expect that turning on "Use SQL to limit fetch size" would actually show SQL modification somewhere.
![image](https://user-images.githubusercontent.com/1846799/203423873-1cbf0a3a-5067-4889-8850-4006e4a944ef.png)

But I don't see that shown anywhere...
![image](https://user-images.githubusercontent.com/1846799/203424079-9dd669aa-90b9-419a-92e6-5677b4dea6ac.png)

And there are more than my configured 200 records.

BTW, this is loosely related to #18301 as I wanted to load all the records in my result set window but I no longer can!

### DBeaver Version

Community Edition 22.2.5.202211202223

### Operating System

Windows 10

### Database and driver

Mysql-connector-java-8.0.17.jar

### Steps to reproduce

Run any query or open data of a table that has more rows than configured fetch size.

**Comment by LonwoLonwo** [comment] 2022-11-23 19:19
Hello @codearoo 

You can see your query with the fetch limit in the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager).

It works in my case:

![2022-11-23 22_18_02-DBeaver Ultimate 22 2 5 - film](https://user-images.githubusercontent.com/45152336/203629715-1638cdc4-a54d-4667-9dd3-4e7d989176ae.png)

**Comment by codearoo** [comment] 2022-11-23 21:30
Oh. But if I can't edit that to rerun, what's the point?

**Comment by LonwoLonwo** [comment] 2022-11-24 08:13
To edit what?
You can copy your query from the Query manager and rerun it.

**Comment by codearoo** [comment] 2022-11-24 13:14
But the related point is that I can't get more than the fetch configuration
into my resultset because that button to get full results is gone.

A question I have though, if the limit is not in SQL, then how is it done?

**Comment by LonwoLonwo** [comment] 2022-11-24 15:40
This button returned in this ticket: https://github.com/dbeaver/dbeaver/issues/18274

**Comment by LonwoLonwo** [comment] 2022-11-28 08:46
Closed as duplicate of #18274

**Closed as not planned by LonwoLonwo** 2022-11-28 08:46 UTC
Labels: x:mysql, duplicate, xf:data
