### ISSUE TITLE
'Read results metadata' runs forever

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#7008] opened 2019-10-18 10:06 UTC
#### System information: 
- Operating system Windows 10
- DBeaver version 6.2.1

#### Connection specification:
- MariaDB 10.3
- Driver name org.mariadb.jdbc.Driver

#### Describe the problem you're observing:
Sometimes when I run a query I see the following message:

![grafik](https://user-images.githubusercontent.com/3126597/67085200-ae207400-f19e-11e9-8118-e2e020793a24.png)

and it blocks for a long period, or even forever.

#### Steps to reproduce, if exist:

Sadly, it seems to happen randomly. I know this probably can't be fixed if it can't be reproduced :-(

I reported it also here #4283 and was told to create a new issue if it happens again.

**Comment by uslss** [comment] 2020-04-22 14:10
still cannot reproduce.
Hope this is fixed in latest release.
but if it is still reproducible - feel free to reopen this ticket

**Closed by uslss** 2020-04-22 14:10 UTC
Labels: bug, can't reproduce
