### ISSUE TITLE
Write to the single file, different table SQL should start at a new line

### ISSUE THREAD

**Issue by ny5667** [dbeaver/dbeaver#16009] opened 2022-03-30 11:05 UTC
#### System information: 
- Operating system (distribution) and version:ubuntu
- DBeaver version: 22.0.1.202203181646
- Additional extensions

#### Connection specification:
- Database name and version

- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Write to the single file, different table SQL should start at a new line
![IMG20220330190633](https://user-images.githubusercontent.com/82657677/160821225-a6a0eb0f-423e-4103-9891-8978ac1eb0d2.jpg)
![屏幕截图_1](https://user-images.githubusercontent.com/82657677/160819496-20908aff-9420-4174-8077-d6e065e53017.png)
![屏幕截图](https://user-images.githubusercontent.com/82657677/160817649-e72a34f8-20e3-4ce4-8716-8fb4454fc302.png)

**Comment by LonwoLonwo** [comment] 2022-03-31 08:08
Unfortunately, can't reproduce.

![2022-03-31 11_05_24-export_202203311104 sql — H__asya_special_dbeaver_backup — Atom](https://user-images.githubusercontent.com/45152336/161007681-7bf06b70-44d2-4ff2-ad87-80371f572a60.png)

Can you provide please screenshots of setting from these two setting pages?

![2022-03-31 11_06_35-Data Transfer](https://user-images.githubusercontent.com/45152336/161007934-41f34490-66b0-4209-9d21-88d8b94eea94.png)

**Comment by ny5667** [comment] 2022-04-01 10:28
Ok, here is the screenshots of settings.
Extraction settings:
![Snipaste_2022-04-01_18-23-44](https://user-images.githubusercontent.com/82657677/161245707-a3b76022-5d52-4ed1-8edb-3397f6b6f922.png)
Format settings:
![Snipaste_2022-04-01_18-23-54](https://user-images.githubusercontent.com/82657677/161245732-95aaa8a4-8a8c-4a0b-8a17-4bf90f12b94f.png)

**Comment by LonwoLonwo** [comment] 2022-04-03 18:33
Ok, I can reproduce with the "Data rows per statement" = 1 setting.
Thanks for the bug report.

![2022-04-03 21_31_49-export_202204032130 sql — H__asya_special_dbeaver_backup — Atom](https://user-images.githubusercontent.com/45152336/161442874-a37796b9-c7ed-4ba9-bcc3-644357bdbf1a.png)

**Comment by CalmaKarma** [comment] 2022-04-24 22:40
@LonwoLonwo @NY5667 How did you write to the single file as the option is not available for SQL export?

And when trying to reproduce, I find two bugs.

1. If I enable "write to the single file" when exporting to txt, and then export to SQL where the option in not available, the setting in last step confirm of "write to the single file" is still yes. But the export result is still seperate files.

2. And when exporting to text with "write to the single file" enabled, the latter tables/views are not exported correctly at the column names. Column names are replaced by the first rows.
![image](https://user-images.githubusercontent.com/54739936/164999791-c396b521-7216-41a2-b1b0-b4737d5c85ca.png)
Exporting seperatedly has correct results.
![image](https://user-images.githubusercontent.com/54739936/164999996-4bba6f97-89f6-45f5-ba22-ad35b8442134.png)

@LonwoLonwo Would you please review them here, and have me or someone else post issues? Thanks.

And if I can reproduce the bug in this issue, I'd like to work on it!

**Comment by LonwoLonwo** [comment] 2022-04-25 05:04
Recently the option "Write to the single file" was disabled for SQL files. But it will be restored in the subsequent releases: https://github.com/dbeaver/dbeaver/issues/16204

And the second case is the bug, yes.

**Comment by CalmaKarma** [comment] 2022-04-25 05:32
Yes, I saw that DataExporterSQL does not implement the IAppendableDataExporter interface when I was trying to trace this bug. 
I have posted the second case to an issue: [#16295](https://github.com/dbeaver/dbeaver/issues/16295)
@LonwoLonwo Could you review it and assign it to me if possible? Thanks!

**Comment by CalmaKarma** [comment] 2022-05-04 22:06
@NY5667 Hi, I believe the bug has been fixed in the recent 22.0.4 release. Would you please check if your issue is properly solved on Ubuntu?

**Comment by LonwoLonwo** [comment] 2022-05-05 06:44
Thanks for the clarification @CalmaKarma 

I see, that the problem is fixed.

![2022-05-05 09_41_56-export_202205050941 sql — H__asya_special_dbeaver_backup — Atom](https://user-images.githubusercontent.com/45152336/166874032-e1ccea3c-cb6a-4394-97d7-27ad48a47a9a.png)

I am closing this ticket. Feel free to reopen it if this problem occurs again.

**Closed as completed by LonwoLonwo** 2022-05-05 06:44 UTC
Labels: xf:datatransfer

**Comment by ny5667** [comment] 2022-05-06 07:34
@CalmaKarma @LonwoLonwo  OK, this issure has been solved. Thanks！

**Comment by LonwoLonwo** [comment] 2022-05-11 06:21
Thanks for your reply @NY5667
