### ISSUE TITLE
[Greenpulm] export to json/source for selected rows from table without keys throws an error

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14262] opened 2021-10-15 12:13 UTC
#### System information: 
- Win10
- DBeaver 21.2.3 CE

#### Connection specification:
- Greenplum partner access
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
Export in JSON/Source Code formats with checked "Selected rows only" and unchecked "Selected columns only" throws UnsupportedOperationException for tables without any keys.
No problem if you try to export selected columns AND selected rows or just selected columns. 

#### Steps to reproduce, if exist:
Open table without PK/Virtual Keys 
Select some rows and columns
Start data export from data grid
Select JSON/Source code format
Check "Selected rows only" and uncheck "Selected columns only"

#### Include any warning/errors/backtraces from the logs
```
Task execution failed

Reason:
Error while exporting table row
```
```
java.lang.UnsupportedOperationException
	at java.sql/java.sql.Date.toInstant(Unknown Source)
	at org.jkiss.dbeaver.model.data.json.JSONUtils.formatDate(JSONUtils.java:51)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterJSON.exportRow(DataExporterJSON.java:142)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:217)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataContainer.readData(ResultSetDataContainer.java:107)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:248)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:165)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by LonwoLonwo** [comment] 2021-12-08 13:47
Duplicate of #12503

**Closed as completed by LonwoLonwo** 2021-12-08 13:47 UTC
Labels: x:greenplum, xf:datatransfer
