### ISSUE TITLE
SQL script generated by liquibase fails executing in DBeaver but works in SQL Management Studio

### ISSUE THREAD

**Issue by dimovelev** [dbeaver/dbeaver#23444] opened 2024-04-17 06:54 UTC
### Description

We are generating SQL migration scripts using liquibase. We used to run them with DBeaver but since we started defining remarks on tables / columns with MSSQL the scripts do not work anymore in DBeaver but they work in Microsoft SQL Management Studio.

### DBeaver Version

Community Edition 24.0.0

### Operating System

Windows 11 23H2

### Database and driver

- Microsoft SQL Server 14.00.3460
Microsoft SQL Server 2017 (RTM-CU31-GDR) (KB5021126) - 14.0.3460.9 (X64) 
	Jan 25 2023 08:42:43 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 18.04.6 LTS)
- Microsoft JDBC Driver 12.4 for SQL Server 12.4.1.0

### Steps to reproduce

1. Connect to a Microsoft SQLServer (e.g. in docker)
2. Create a new SQL script
3. Paste the following script (generated by liquibase):
```
CREATE TABLE ecs.t_movability (id uniqueidentifier NOT NULL, work_order_code varchar(255) NOT NULL, load_unit_code varchar(255) NOT NULL, location_type varchar(255) NOT NULL, location_code varchar(255) NOT NULL, operation varchar(255) NOT NULL, status varchar(255) NOT NULL, created datetime2 NOT NULL, last_modified datetime2 NOT NULL, version bigint NOT NULL, CONSTRAINT t_movabilityPK PRIMARY KEY (id))
GO
DECLARE @TableName SYSNAME set @TableName = N't_movability'; DECLARE @FullTableName SYSNAME; SET @FullTableName = N'ecs.t_movability';DECLARE @MS_DescriptionValue NVARCHAR(3749); SET @MS_DescriptionValue = N'Store the movability of load units replicated from other systems';DECLARE @MS_Description NVARCHAR(3749) set @MS_Description = NULL; SET @MS_Description = (SELECT CAST(Value AS NVARCHAR(3749)) AS [MS_Description] FROM sys.extended_properties AS ep WHERE ep.major_id = OBJECT_ID(@FullTableName) AND ep.name = N'MS_Description' AND ep.minor_id=0); IF @MS_Description IS NULL BEGIN EXEC sys.sp_addextendedproperty @name  = N'MS_Description', @value = @MS_DescriptionValue, @level0type = N'SCHEMA', @level0name = N'ecs', @level1type = N'TABLE', @level1name = @TableName; END ELSE BEGIN EXEC sys.sp_updateextendedproperty @name  = N'MS_Description', @value = @MS_DescriptionValue, @level0type = N'SCHEMA', @level0name = N'ecs', @level1type = N'TABLE', @level1name = @TableName; END
GO
```
5. Execute SQL Script (Alt+X)
6. This fails with the following error:
```
Error occurred during SQL script execution

Reason:
SQL Error [137] [S0001]: Must declare the scalar variable "@FullTableName".
```

However, the script can be executed using Microsoft management studio.
Furthermore, if I execute this single line using Execute SQL Query (Ctrl+Enter) it works!

**Comment by E1izabeth** [comment] 2024-04-18 18:57
Please select the whole second line (DECLARE @TableName SYSNAME...) and press Execute Query

**Comment by E1izabeth** [comment] 2024-04-18 18:57
I'm closing it as a duplicate of #15543

**Closed as not planned by E1izabeth** 2024-04-18 18:57 UTC
Labels: duplicate, x:mssql, xf:sql execution
