### ISSUE TITLE
Bug: DBeaver not launching

### ISSUE THREAD

**Issue by wout** [dbeaver/dbeaver#4842] opened 2018-12-20 19:41 UTC
Since today, I am unable to launch DBeaver. I'm on Pop!_OS 18.10 (Ubuntu based) with DBeaver 5.3.0. The ouput fomr syslot at the time of opening:

```
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.321 - Create display
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.727 - > Start org.jkiss.dbeaver.core [5.3.0.201812092025]
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.730 - DBeaver 5.3.0.201812092025 is starting
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.730 - OS: Linux 4.18.0-13-generic (amd64)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.731 - Java version: 11.0.1 by Oracle Corporation (64bit)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.731 - Install path: '/usr/share/dbeaver'
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.731 - Instance path: 'file:/home/wout/.dbeaver4/'
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.731 - Memory available 64Mb/1024Mb
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.748 - Starting RMI server at 39064
Dec 20 20:36:09 rossy systemd-resolved[1067]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Dec 20 20:36:09 rossy systemd-resolved[1067]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.924 - Run workbench
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.939 - > Start org.eclipse.e4.ui.workbench.swt [0.14.101.v20170710-1119]
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.945 - > Start org.eclipse.e4.core.services [2.1.0.v20170407-0928]
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.947 - > Start org.eclipse.e4.core.contexts [1.6.0.v20170322-1144]
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.957 - > Start org.eclipse.e4.ui.services [1.3.0.v20170307-2032]
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:09.989 - Internal error in workbench lifecycle
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
Dec 20 20:36:09 rossy dbeaver.desktop[9770]: #011at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011... 23 more
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: #011... 25 more
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:10.006 - DBeaver is stopping
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:10.007 - Stop RMI server
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:10.048 - < Stop org.jkiss.dbeaver.ext.mssql [1.0.92.201812092025]
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:10.049 - < Stop org.jkiss.dbeaver.ext.oracle [2.1.83.201812092025]
Dec 20 20:36:10 rossy dbeaver.desktop[9770]: 2018-12-20 20:36:10.050 - < Stop org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.4.201812092025]

```

**Comment by serge-rider** [comment] 2018-12-20 20:02
Duplicate of #4765 (see workaround in comments)

**Closed by serge-rider** 2018-12-20 20:02 UTC
Labels: bug, duplicate
