### ISSUE TITLE
Crash reading metadata from ODBC datasource

### ISSUE THREAD

**Issue by michaelstiller78** [dbeaver/dbeaver#21347] opened 2023-09-27 13:58 UTC
### Description

Hi everyone,

I im trying to analyse data in a proprietary database (KISAM). The only way to access this database is via ODBC.

I first tried to reintegrate the ODBC legacy driver into a current CE version (23.0.5). Then I have tried versions 22.3.5 and 21.0.5. in which the ODBC driver was still regularly available.

I can connect to the database, but when I expand the table view, DBeaver crashes. Based on the log, I would say that it happens when reading the metadata.

Can anyone tell me more about this problem and is there a way I can get around this?

Here the log file.

2023-09-27 15:18:01.526 - Create display
2023-09-27 15:18:01.595 - DBeaver 21.0.5.202105160657 is starting
2023-09-27 15:18:01.597 - OS: Windows 10 10.0 (amd64)
2023-09-27 15:18:01.597 - Java version: 11.0.9.1 by AdoptOpenJDK (64bit)
2023-09-27 15:18:01.597 - Install path: 'C:\Users\test.xxxxx\AppData\Local\DBeaver'
2023-09-27 15:18:01.598 - Instance path: 'file:/C:/Users/test.xxxxx/AppData/Roaming/DBeaverData/workspace6/'
2023-09-27 15:18:01.598 - Memory available 61Mb/989Mb
2023-09-27 15:18:01.612 - Starting RMI server at 25188
2023-09-27 15:18:01.658 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.0.v20201230-1610]
> Start Eclipse Anwendungsdienste [org.eclipse.e4.core.services 2.2.600.v20210110-1654]
> Start Eclipse Kontexte [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Anwendungsdienste [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF - Allgemein [org.eclipse.emf.common 2.22.0.v20210114-1734]
> Start EMF-Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF-XMI [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse BO Abhängigkeitsinjektion [org.eclipse.e4.ui.di 1.3.0.v20210222-1018]
> Start Eclipse CSS SWT Themenunterstützung [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start Eclipse e4-Workbanch-Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.100.v20201221-2332]
> Start Ausdruck Sprache [org.eclipse.core.expressions 3.7.100.v20210203-1000]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start Eclipse Bindungsunterstützung [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Abhängigkeitsinjizierungserweiterungen [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Unterstützung [org.eclipse.e4.ui.css.swt 0.14.100.v20201217-1340]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.72.202105160657]
2023-09-27 15:18:02.900 - Configure workbench window
> Start Hilfesystem - Core [org.eclipse.help 3.8.800.v20200525-0755]
2023-09-27 15:18:02.972 - Create actions
2023-09-27 15:18:03.047 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2023-09-27 15:18:03.048 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
Warning: NLS unused message: pref_page_ui_general_check_new_driver_versions in: org.jkiss.dbeaver.core.CoreResources
2023-09-27 15:18:03.438 - Initialize workbench window
2023-09-27 15:18:03.445 - Finish initialization
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.600.v20210126-1005]
> Start Benutzeroberfläche für die Verwaltung der Internetverbindungen [org.eclipse.ui.net 1.3.800.v20200422-1935]
> Start Verwaltung der Internetverbindungen [org.eclipse.core.net 1.3.1000.v20200715-0827]
> Start Equinox - Bereitstellung automatischer Aktualisierungen (EPP Automatic Update) [org.eclipse.equinox.p2.ui.sdk.scheduler 1.5.0.v20201012-1421]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.5.100.v20200908-1020]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.300.v20200222-1600]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.47.202105160657]
2023-09-27 15:18:04.260 - Loading user drivers configuration from 'C:\Users\test.xxxxx\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.jkiss.dbeaver.core\drivers.xml'
2023-09-27 15:18:04.267 - Total database drivers: 91 (91)
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.57.202105160657]
> Start Standardtexteditor [org.eclipse.ui.editors 3.14.0.v20210215-0846]
> Start Texteditor-Framework [org.eclipse.ui.workbench.texteditor 3.16.0.v20210120-0733]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.57.202105160657]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.57.202105160657]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.94.202105160657]
> Start DBeaver Tip des Tages [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.63.202105160657]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.17.202105160657]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.17.202105160657]
2023-09-27 15:18:07.107 - Open [https://dbeaver.io/product/version.xml]
> Start DBeaver UI Editors - Connections [org.jkiss.dbeaver.ui.editors.connection 1.0.48.202105160657]
> Start DBeaver Generic UI Plug-in [org.jkiss.dbeaver.ext.generic.ui 1.0.33.202105160657]
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.143.202105160657]
> Start DBeaver SSH tunnels UI [org.jkiss.dbeaver.net.ssh.ui 1.0.78.202105160657]
> Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh 1.0.78.202105160657]
2023-09-27 15:18:14.778 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
> Start Equinox Versorgungskern [org.eclipse.equinox.p2.core 2.6.300.v20200211-1504]
> Start Eclipse Updateunterstützung [org.eclipse.equinox.p2.engine 2.6.700.v20200511-1530]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.500.v20210108-0738]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.5.0.v20201013-0853]
> Start Eclipse Updateunterstützung Benutzeroberfläche [org.eclipse.equinox.p2.ui 2.7.0.v20210114-1216]
2023-09-27 15:19:42.851 - Connect with 'AXXXG' (odbc-18ad6c7f1f6-1f78875ebbb152a3)
2023-09-27 15:19:42.887 - Execution context opened (AXXXG; Main; 0)
2023-09-27 15:19:43.023 - Execution context opened (AXXXG; Metadata; 1)
2023-09-27 15:19:43.128 - Error determining server version
java.lang.UnsupportedOperationException
	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.readDatabaseServerVersion(JDBCDataSource.java:440)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:413)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:450)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:909)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:207)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:71)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2023-09-27 15:19:43.156 - Connected (odbc-18ad6c7f1f6-1f78875ebbb152a3, JDBC-ODBC Bridge (KISAM64.DLL) [2.0001 (02.04.21091)])
2023-09-27 15:19:44.273 - Can't get column 'TABLE_SCHEM': Column not found

Thank you!

Regards 

Michael

### DBeaver Version

CE 21.0.5 (and 23.0.5, 22.3.5)

### Operating System

Windows 10 10.0 (amd64)

### Database and driver

Database: KISAM
Driver: ODBC (legacy)

### Steps to reproduce

Expand table view after connecting to database

**Comment by ShadelessFox** [comment] 2023-09-27 14:15
Hello @michaelstiller78,

Legacy ODBC is no longer supported. We provide a modern ODBC driver in our commercial products.

I suggest taking a free two-week trial: https://dbeaver.com/trial/.

**Comment by E1izabeth** [comment] 2023-10-20 17:15
If the issue is actual for the suggested ODBC driver please let me know. It's been a while since no update here, so I'm closing this issue.

**Closed as not planned by E1izabeth** 2023-10-20 17:15 UTC
Labels: wait for response, third party issue, x:odbc

**Comment by viglu** [comment] 2025-08-20 08:09
I have downloaded dbeaver lite trial to evaluate. But the ODBC connection crashes the whole application. No error does appear. The last progress I can see is "Loading database metadata" then the application will close.
I'm trying to connect to a HFSQL database trough ODBC.

**Comment by ShadelessFox** [comment] 2025-08-20 09:46
@viglu please contact our customer support: https://dbeaver.com/support/
