### ISSUE TITLE
Content Viewer Settings no longer showing when running more complex SQL queries returning JSON data

### ISSUE THREAD

**Issue by garnierfrooc** [dbeaver/dbeaver#19453] opened 2023-03-22 12:35 UTC
### Description

It appears to have been slowly degrading, but now there is no ability to format data using the content viewer settings option when running an SQL query against JSON.

Here is a screenshot from a request where the content viewer was available and correctly formatting the JSON:
![sql_showing_content_viewer](https://user-images.githubusercontent.com/49648381/226903558-197c75c2-500f-4692-8652-b642bee402ab.png)

Here is the exact same query now no longer showing the viewer, and no options to format this JSON to how it was before:
![sql_not_showing_content_viewer](https://user-images.githubusercontent.com/49648381/226903692-f7205163-44a1-4936-89c5-bc4deeefb7f8.png)

I'd noticed this crop up every now and then recently, but now it seems like it never works. If I run a simple query to fetch the JSON field, something like:

select json, hash, timestamp from table_name

The JSON returned can be formatted.

While typing this out, I've noticed a difference also appears to be that a yellow padlock appears on the more complex queries, and the data seems to be read-only. This could also be part of the problem?

### DBeaver Version

Community Edition Version 23.0.0.202303040621

### Operating System

Windows 11

### Database and driver

Yandex ClickHouse driver (server version 21.3+)
Clickhouse

### Steps to reproduce

When running a somewhat complex SQL script that returns JSON data.

Example:
```
WITH (
    SELECT timestamp from table.name
    ORDER BY timestamp DESC
    LIMIT 1
    ) as latest
SELECT json, timestamp, JSON_VALUE(json, '$.email') FROM table.name
WHERE timestamp = latest
AND JSON_VALUE(json, '$.email') LIKE '%gmail%'
```

### Additional context

The problem doesn't happen when using a 'simpler' SQL query like:
```
select json, hash, timestamp from table.name
```

**Comment by Destrolaric** [comment] 2023-04-13 13:16
Duplicate of #19452

**Closed as not planned by Destrolaric** 2023-04-13 13:16 UTC
Labels: duplicate, xf:data, x:clickhouse
