### ISSUE TITLE
CAN SOMEONE SEND ME 32BIT DBEAVER FOR WINDOWS?

### ISSUE THREAD

**Issue by tia000000000** [dbeaver/dbeaver#14027] opened 2021-09-28 13:17 UTC
Hi everyone! I tried installing DBeaver but for some reason it says it doesn't match my Windows. I downloaded many of the archived versions but unfortunately even those whom I know are 32bit, they were still not working. I have Windows 7 Ultimate. I wonder if someone knows another ways of downloading and finding 32bit Beavers. Thanks in advance!

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by ShadelessFox** [comment] 2021-09-28 13:28
Closed as a duplicate of discussion #14030

**Closed as completed by ShadelessFox** 2021-09-28 13:28 UTC
Labels: question
