### ISSUE TITLE
wrong icon size on database navigator and projects on a 4k screen, ubuntu

### ISSUE THREAD

**Issue by lBilali** [dbeaver/dbeaver#3937] opened 2018-08-06 20:18 UTC
see screenshot below.

![screenshot from 2018-08-06 21-52-32](https://user-images.githubusercontent.com/5528169/43738325-79d3fa24-99c4-11e8-9596-a3ee636659d2.png)

I'm using:
dbeaver plugin 5.1.4
eclipse 4.8
ubuntu 18.04
4k screen

I download dbeaver community edition 5.1.4 to check and I have the same issue there as well.

the issue was introduced after updating eclipse from 4.7 to 4.8

to me it seems like the issue has to do with GTK 3

**Comment by serge-rider** [comment] 2018-08-06 21:19
Could you try EA version (https://dbeaver.io/files/ea) - there is a number of problems on GTK after migration to Eclipse 4.8. Most of them were fixed in EA.

**Comment by lBilali** [comment] 2018-08-06 21:43
downloaded dbeaver-ce-5.1.5-linux.gtk.x86_64.tar.gz  from 06-Aug-2018 11:21
extracted and run it.
the same issue :(

**Comment by serge-rider** [comment] 2018-08-06 21:47
Hm. I can't reproduce that (4k monitor with zoom factor 150%, Ubuntu 16).

Do you have any specific display settings? Zoom factor, VM?

Did you try to install DBeaver 5.1.4+ in Eclipse 4.7? (it works fine, E4.8 is not required for plugin version).

**Comment by serge-rider** [comment] 2018-08-06 21:52
I think this may be related: https://bugs.eclipse.org/bugs/show_bug.cgi?id=536578

**Comment by lBilali** [comment] 2018-08-06 21:52
display settings are at 200%
when I change at 100% it is fine. 
I'm running ubuntu 18.04 no VM

The issue happend when I updated Eclipse to 4.8 not sure which version of DBeaver I had than.

**Comment by serge-rider** [comment] 2018-08-06 21:54
Then this is definitely the same issue. It is fixed in Eclipse but will be included in DBeaver only after M2 release (September 2018?)

**Comment by lBilali** [comment] 2018-08-06 22:02
I see, Thanks for your quick response.
and for dbever btw, great tool

**Closed** 2018-08-10 20:46 UTC
Labels: bug, can't reproduce, xo:linux

**Comment by fulopattila122** [comment] 2021-05-06 13:58
I used to have this issue maybe about 2 years ago. It got fixed back then with one of the updates.
Somehow it has come back in recent weeks. I'm on Ubuntu 20.04, 4k 2x scale, and dbeaver 21.0.4

![image](https://user-images.githubusercontent.com/1162360/117308868-31d5aa80-ae82-11eb-8d1e-ea51979c1964.png)

![image](https://user-images.githubusercontent.com/1162360/117310439-92191c00-ae83-11eb-8926-ec354f807088.png)

I tried:
- resetting UI settings
- resetting Workspace State
- switching themes
- switching color
- disabling themes
- deleting config folders:
    - `~/.cache/DBeaver`
    - `~/.eclipse/org.jkiss.dbeaver.product_21.0.4_620785679_linux_gtk_x86_64`
    - `~/.local/share/DBeaverData/workspace6/.metadata/.plugins`
- various command line options (swt, scaling and GDK related ones)

None of above ones had effect on those icons. If I'm not mistaken, the same installation used to work a few weeks ago without problems, so I suspect it might be some "stuck" settings issue.

Do you have any idea what else to "reset"?

**Comment by Zeioth** [comment] 2021-09-16 17:07
I also have this problem on Sway with scaling x2. Why there is not a simple option to resize?
