### ISSUE TITLE
PostgreSQL: elements of arrays of basic numeric sub-types are not rendered

### ISSUE THREAD

**Issue by EugeneGunichev** [dbeaver/dbeaver#7468] opened 2019-12-24 00:21 UTC
#### System information: 
- Operating system (distribution) and version: Windows 7 Enterprise, SP1, 64-bit
- DBeaver version: 6.3.1.201912221734

#### Connection specification:
- Database name and version: PostgreSQL 12.0, compiled by Visual C++ build 1914, 64-bit
- Driver name: PostgreSQL JDBC Driver 42.2.5

#### Describe the problem you're observing:
Values of the array's elements are not rendered if it's the array of the domain sub-types.

#### Steps to reproduce, if exist:
create domain posint8 as int8 check (value > 0);

create table my_table
(
  id  posint8,
  arr posint8[]
);

insert into my_table(id, arr) values(100, array[200, 300]);
insert into my_table(id, arr) values(400, array[500, 600]);

select * from my_table;
Result:
id |arr|
---|---|
100|{,}|
400|{,}|

If you create a table with an array of elements of the base type, then the result is displayed well.
For example:
create table my_table
(
  id  int8,
  arr int8[]
);
-- use the same inserts as above
select * from my_table;
Result:
id |arr      |
---|---------|
100|{200,300}|
400|{500,600}|

#### Include any warning/errors/backtraces from the logs
There are no errors.

**Comment by serge-rider** [comment] 2019-12-31 16:22
Thanks for the bug report.
Problem was caused by jdbc driver - it packs array items to PgObject (even if they are just plain numbers). Only in case of domain types. Maybe it is a right behavior though.
Anyway, just pushed the fix.

**Comment by kseniiaguzeeva** [comment] 2020-01-03 14:15
Verified

**Closed by kseniiaguzeeva** 2020-01-03 14:15 UTC
Labels: bug, x:postgresql
