### ISSUE TITLE
Query against table with large jsons is very slow

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#6814] opened 2019-09-24 10:14 UTC
#### System information: 
- Operating system (distribution) and version: mac os
- DBeaver version: 6.2.0
- Additional extensions: n/a

#### Connection specification:
- Database name and version: postgres 11.2/4
- Driver name: default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:
1. Querying a table with very large jsons is very slow.
2. In data grid, moving left/right between cells of a row is fine, until you reach a json field with large content - then it loads for a few seconds.

#### Steps to reproduce:
create a table with a json column, insert large jsons (>100k chars), query the table.

#### Suggested alternative:
Load/show a preview, including in the value - and make it mandatory for the user to click on something (be active) to show full content.
Toad for Oracle handled it nicely If I remember correctly for CLOBs it allowed you to either hide the content unless double clicking the cell, show a preview or show the full content (which caused it to be very slow). If not loading/showing the full content when moving between cells or even when loading the grid - it will make navigation much faster.

**Comment by serge-rider** [comment] 2019-09-24 18:56
Try version 6.2.1. JSON render performance was significantly improved there.

**Comment by pyrocks** [comment] 2019-09-25 06:16
Hi,
6.2.1 only resolves the 2nd item - moving left/right in the data grid is a lot faster.

But the 1st issue is still very much present:
I have a table like this (columns aren't actually called col1..coln it's for demonstration purposes.
`CREATE TABLE mytable(
    col1 INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    col2 INT NOT NULL,
    col3 SMALLINT NOT NULL,
    col4 INT,
    col5 VARCHAR(100),
    col6 VARCHAR(1000),
    col7 INT,
    col8 json,
    col9 SMALLINT,
    col10 VARCHAR(50),
    col11 INT DEFAULT 0,
    col12 INT DEFAULT 0,
    col13 TIMESTAMPTZ,
    col14 TIMESTAMPTZ);`

If I issue `select col1, col2, ... col14 from mytable;` - 17 seconds
![image](https://user-images.githubusercontent.com/18515297/65573357-5150e580-df73-11e9-8f5d-e5a362d52a6a.png)
If I issue the same query again but without _col8_ (the json column) ~ 400 ms
![image](https://user-images.githubusercontent.com/18515297/65573495-ad1b6e80-df73-11e9-81da-f02514766573.png)
doing explain analyze on the original query with the json column - where the query is being run but dbeaver doesn't need to load the result: 0.1ms
![image](https://user-images.githubusercontent.com/18515297/65573608-ec49bf80-df73-11e9-8792-252a96b3a102.png)
If I run the full query in psql (/a, /timing) but with limit 200 (to simulate dbeaver's loading of the first 200 records ~3 seconds
![image](https://user-images.githubusercontent.com/18515297/65573989-e0123200-df74-11e9-942b-d30e9eb68a26.png)

I repeated the queries multiple times.
so dbeaver should not take more than 3-4 seconds, and I assume something it does in the background is causing the slowness.

I hope this provides enough information.

**Comment by pyrocks** [comment] 2020-07-23 05:41
@uslss @serge-rider this is still relevant, I don't have the option to reopen...

**Comment by LonwoLonwo** [comment] 2023-06-12 08:05
Closing as a duplicate of https://github.com/dbeaver/dbeaver/issues/11802

**Closed by LonwoLonwo** 2023-06-12 08:05 UTC
Labels: bug, xf:data, performance
