### ISSUE TITLE
error browsing indexes oracle db 11gr2

### ISSUE THREAD

**Issue by gthbusr0** [dbeaver/dbeaver#13110] opened 2021-07-05 19:13 UTC
System information:
Operating system (distribution) and version: windows 10 enterprise 10.0.18363
DBeaver version: DBeaver 21.1.1.202106210824
Additional extensions: NONE
Connection specification:default driver
Database name and version : oracle 11gr2
Driver name : default oracle driver bundled with s/w
Do you use tunnels or proxies (SSH, SOCKS, etc)? : no tunnels/proxies

#### Describe the problem you're observing:
hello, SMEs
browsing indexes either via mouse-hover+click or side navigation pane indexes node results in below error:

`

> SQL Error [1417] [72000]: ORA-01417: a table may be outer joined to at most one other table
> 
>   Error : 1417, Position : 397, Sql = SELECT  i.OWNER,i.INDEX_NAME,i.INDEX_TYPE,i.TABLE_OWNER,i.TABLE_NAME,i.UNIQUENESS,i.TABLESPACE_NAME,i.STATUS,i.NUM_ROWS,i.SAMPLE_SIZE,
> ic.COLUMN_NAME,ic.COLUMN_POSITION,ic.COLUMN_LENGTH,ic.DESCEND,iex.COLUMN_EXPRESSION
> FROM ALL_INDEXES i
> , ALL_IND_COLUMNS ic, ALL_IND_EXPRESSIONS iex WHERE ic.INDEX_OWNER=i.OWNER AND ic.INDEX_NAME=i.INDEX_NAME 
> AND iex.INDEX_OWNER(+)=i.OWNER AND iex.INDEX_NAME(+)=i.INDEX_NAME AND iex.COLUMN_POSITION(+)=ic.COLUMN_POSITION
> AND i.TABLE_OWNER=:1  AND i.TABLE_NAME=:2 
> ORDER BY i.INDEX_NAME,ic.COLUMN_POSITION, OriginalSql = SELECT  i.OWNER,i.INDEX_NAME,i.INDEX_TYPE,i.TABLE_OWNER,i.TABLE_NAME,i.UNIQUENESS,i.TABLESPACE_NAME,i.STATUS,i.NUM_ROWS,i.SAMPLE_SIZE,
> ic.COLUMN_NAME,ic.COLUMN_POSITION,ic.COLUMN_LENGTH,ic.DESCEND,iex.COLUMN_EXPRESSION
> FROM ALL_INDEXES i
> , ALL_IND_COLUMNS ic, ALL_IND_EXPRESSIONS iex WHERE ic.INDEX_OWNER=i.OWNER AND ic.INDEX_NAME=i.INDEX_NAME 
> AND iex.INDEX_OWNER(+)=i.OWNER AND iex.INDEX_NAME(+)=i.INDEX_NAME AND iex.COLUMN_POSITION(+)=ic.COLUMN_POSITION
> AND i.TABLE_OWNER=? AND i.TABLE_NAME=?
> ORDER BY i.INDEX_NAME,ic.COLUMN_POSITION, Error Msg = ORA-01417: a table may be outer joined to at most one other table
> 
>   ORA-01417: a table may be outer joined to at most one other table
> 

`

note: workaround to query indexes via orcl datadictionary tables via canned templates exists though.

**Comment by uslss** [comment] 2021-07-05 20:45
thank you for the report.
Looks like duplicate of the #13025. Will be fixed in the scope of 21.1.3. [EA ](https://dbeaver.io/files/ea/)with fix will be available soon

**Closed as completed by uslss** 2021-07-05 20:45 UTC
Labels: x:oracle, duplicate

**Comment by gthbusr0** [comment] 2021-07-05 21:38
sorymybad...
