### ISSUE TITLE
DBeaver hangs while trying to format/display big amounts of data in panel

### ISSUE THREAD

**Issue by dnbernardi** [dbeaver/dbeaver#16671] opened 2022-06-01 16:39 UTC
#### System information: 
- Windows 10 (21H2)
- DBeaver 22.0.5
- Additional extensions: postgis 3.0.0

#### Problem description:
When selecting a cell that has a big value (i.e, a geojson string/json) and having the right panel open (data visualizer), the formatting process hangs the application for a considerable time (1-10 minutes). This only happens with formatted data (one-line strings are shown immediately).

Sometimes if the sysems has no memory left, it ends up killing the application.

#### Steps to reproduce:
Select any cell containing a big formatted string/json(b).

I believe there should be a way to disable this automatic formatting, perhaps giving an option to select to enable/disable it.
Or at least, giving a way to cancel the formatting process.

**Comment by LonwoLonwo** [comment] 2022-06-01 19:27
Hello @dnbernardi 

Maybe disabling the "Auto Format" can help?

![2022-06-01 22_26_31-DBeaver Ultimate 22 1 0 - json_test_json](https://user-images.githubusercontent.com/45152336/171486113-d153dea2-76f0-4a39-bb71-36f8fe165dd9.png)

**Comment by LonwoLonwo** [comment] 2022-06-01 19:33
Probably connected with #15951 and #6814

**Comment by dnbernardi** [comment] 2022-06-01 19:49
Thanks for the help @LonwoLonwo,

I tried toggling off the option you mention, but only works when the value is already loaded. The loading itself is the heavy thing. And it's not a global option, meaning that toggling off "Auto Format" doesn't mean that the next loads will be unformatted, only applies to that value in that cell.

Note: I have 16GB of RAM and just now DBeaver consumed 9.5GB of memory after disabling "Auto Format" in the cell containing a big json, even bugging the panel:

![image](https://user-images.githubusercontent.com/91920450/171489332-aa2b9299-0c54-42a9-bbc6-73813f71d829.png)

![image](https://user-images.githubusercontent.com/91920450/171489455-dd9c4d0b-9f3d-4258-a083-33e7d0b27ca7.png)

**Comment by emironovDB** [comment] 2022-06-22 13:07
Close as duplicate of https://github.com/dbeaver/dbeaver/issues/15951 and https://github.com/dbeaver/dbeaver/issues/6814

**Closed as not planned** 2022-06-22 13:07 UTC
Labels: duplicate, xf:data, performance
