### ISSUE TITLE
arrows to sort columns alphabetically in results vertical view is now missing

### ISSUE THREAD

**Issue by clemlaugit** [dbeaver/dbeaver#18824] opened 2023-01-20 22:15 UTC
### Description

Hello, 

This feature was previously there but seems to have disappeared.
When you change the results to view one row vertically,  there used to be arrows to sort the columns alphabetically.
These arrows are gone now.

Please bring them back, they were very useful for finding columns.

![image](https://user-images.githubusercontent.com/91501833/213814326-faacbf51-8452-404b-9ac3-20b537faee4a.png)

### DBeaver Version

community version 22.3.2.202301060755

### Operating System

mac os monetery 12.6.2 (21G320)

### Database and driver

database:  snowflake 
driver:  net.snowflake.client.jdbc.SnowflakeDriver

### Steps to reproduce

1. get results from any query
2.  highlight one row from result set and press tab to view vertically

**Comment by E1izabeth** [comment] 2023-01-20 22:18
Thank you for bug report. It's a duplicate of #18618
The fix is available in the early access version (https://dbeaver.io/files/ea/) and will be available in the next release.

**Closed as not planned by E1izabeth** 2023-01-20 22:18 UTC
Labels: duplicate, xf:data
