### ISSUE TITLE
query writing Formatting is not consistent.

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#20268] opened 2023-06-12 15:05 UTC
### Description

formatting is all over the place..If I get DDL by right clicking and copy query and use it the commands are all uppercase but when I type a query then it only types in lowercase. Formatting is not consistent.  can it it be fixed?

### DBeaver Version

23.1.0

### Operating System

windows

### Database and driver

Postgres 14.2

### Steps to reproduce

right click a table to get DDL or generate SQL - commands are upper case - SELECT, FROM etc

But when sql command is typed then all commands are lower case - select, from..etc.

**Comment by E1izabeth** [comment] 2023-06-12 19:38
Seems like a duplicate of #18831

**Comment by LonwoLonwo** [comment] 2023-06-15 16:51
Hello. You can try to set this setting. Or change settings in the Formatting group.
By default we are using case from the database.

![2023-06-15 16_30_58-Transparent Window](https://github.com/dbeaver/dbeaver/assets/45152336/96951253-a437-4a03-8ffc-bcf00b8761fa)

**Comment by E1izabeth** [comment] 2023-07-13 12:37
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Closed as not planned by E1izabeth** 2023-07-13 12:37 UTC
Labels: xf:sql, wait for response
