### ISSUE TITLE
Dbeaver adds trailing semicolon if CASE statement used

### ISSUE THREAD

**Issue by arsturges** [dbeaver/dbeaver#3509] opened 2018-05-21 23:30 UTC
I'm running this query against an Oracle database, version 11.2.0.4.0. I'm using dbeaver 5.0.5.

This one fails:
```
SELECT 
	STVMAJR_CODE,
	STVMAJR_CIPC_CODE,
	STVMAJR_VALID_MINOR_IND
	, CASE WHEN STVMAJR_CODE = 'y' THEN 'valid_minor' END
FROM STVMAJR;
```

But if I remove the line with the `CASE` statement then it runs:
```
SELECT 
	STVMAJR_CODE,
	STVMAJR_CIPC_CODE,
	STVMAJR_VALID_MINOR_IND
	--, CASE WHEN STVMAJR_CODE = 'y' THEN 'valid_minor' END
FROM STVMAJR;
```

Equally strangely, if I put back the line with the `CASE` statement, but remove the trailing semicolon, it also runs:
```
SELECT 
	STVMAJR_CODE,
	STVMAJR_CIPC_CODE,
	STVMAJR_VALID_MINOR_IND
	, CASE WHEN STVMAJR_CODE = 'y' THEN 'valid_minor' END
FROM STVMAJR
```
Is DBeaver doing some sort of logic to determine whether to add a trailing semicolon? And this logic depends on whether there's a `CASE` statement in the body of the query? Feature or bug?

**Comment by serge-rider** [comment] 2018-05-22 17:38
Duplicate of #3481
Thanks for report anyway

**Closed by serge-rider** 2018-05-22 17:38 UTC
Labels: bug, duplicate, x:oracle
