### ISSUE TITLE
Blurry icons in hidpi screen

### ISSUE THREAD

**Issue by memeplex** [dbeaver/dbeaver#7689] opened 2020-01-19 14:54 UTC
#### System information: 

- Operating system (distribution) and version: Ubuntu 19.10
- DBeaver version: 6.3.2.202001051908
- Additional extensions: None
- Screen: 3000x2000 hidpi with 2x scaling factor

#### Describe the problem you're observing:

Many icons in contextual menus and other GUI elements look blurry, as if they were lodpi. OTOH icons in the main toolbar look crisp, just fine.

![image](https://user-images.githubusercontent.com/2845433/72683023-76350f80-3ab2-11ea-98d5-a4ee8a07f09d.png)

**Comment by memeplex** [comment] 2020-01-19 16:00
Also, the same icons in the screenshot above look crisp in the ER diagram, so it doesn't seem to be a case of low resolution icons after all:

![image](https://user-images.githubusercontent.com/2845433/72684020-b482fc80-3abb-11ea-8311-751574d54b01.png)

**Comment by memeplex** [comment] 2020-01-19 17:31
Another fact: `swt.autoScale` only affects icons that look crisp, blurry icons are always shown at the same scale (and blurriness :().

**Comment by serge-rider** [comment] 2020-03-05 11:47
Duplicate of #7689 (general scale issues, we can't fix it from dbeaver side)

**Closed by serge-rider** 2020-03-05 11:47 UTC
Labels: bug, duplicate
