### ISSUE TITLE
Execute SQL in a new tab did not show error

### ISSUE THREAD

**Issue by reini-1** [dbeaver/dbeaver#5917] opened 2019-05-16 08:12 UTC
#### System information: 
- Operating system (distribution) and version Ubuntu 18.04
- DBeaver version 6.0.4
- Java version OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
- Additional extensions

#### Connection specification:
- Database name and version postgresql 10.8
- Driver name postgresql-42.2.0.jre7.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When calling "Execute SQL in a new tab" and there is an error, the new tab with the error message is closed and I cannot see it. This leads to many troubles when modifying a query, then is an error, the new tab flashes shortly and then the previous tab is shown any you wonder why the result havn't changed until you realize that there was an error and the previous result is shown.
When calling "Execute SQL statement" the error is shown and not any previous result.

#### Steps to reproduce, if exist:
Take any SQL with an error and call "Execute SQL in a new tab" and "Execute SQL statement" to compare the behavior.

**Comment by uslss** [comment] 2020-05-19 12:13
cannot reproduce an issue for now. Probably you've got "Close relults tab on error" option checked in preferences
![image](https://user-images.githubusercontent.com/31996417/82324940-22482200-99e3-11ea-9a44-bd4ef92747bc.png)
if issue is still actual for you - feel free to reopen the ticket.
and sorry for so late response

**Closed by uslss** 2020-05-19 12:13 UTC
