### ISSUE TITLE
Nullpointer exception on result

### ISSUE THREAD

**Issue by edmundo-sw** [dbeaver/dbeaver#6349] opened 2019-07-25 16:05 UTC
#### System information: 
- Operating system:  Ubuntu 18.10 
- OS: Linux 4.18.0-25-generic (amd64)
- DBeaver 6.1.3.201907211943 is starting
- Java version: 1.8.0_201 by Oracle Corporation (64bit)
 - Install path: '/usr/share/dbeaver'
 - Memory available 109Mb/910Mb

#### Connection specification:
- PostgreSQL 11.4 (Ubuntu 11.4-1.pgdg18.10+1) on x86_64-pc-linux-gnu, compiled by gcc 
- (Ubuntu 8.3.0-6ubuntu1~18.10.1) 8.3.0, 64-bit
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
I tried to exceute the following query:

```
select * from hydra.select_my_truns_idsarray(340);
and
select  hydra.select_my_truns_idsarray(340);
```

The expected result is:

```
select_my_truns_idsarray                                                                                                                                                                  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {253,234,692,194,223,193,180,162,179,274,267,222,255,279,224,312,278,286,260,269,433,163,228,428,164,367,446,225,479,515,520,277,365,256,495,480,642,731,546,663,605,670,649,625,638,658,647,637,659,653,671,666,667,660,657,676,258,678,680,257,271,281,249,282,248,259,280,250,227,261,682,226,276,283,229,273,275,268,447,270,748,780,826,861,652,272}
(1 row)
```

but i get a null pointer exception:

![dbeaver-null-exception](https://user-images.githubusercontent.com/48522448/61889400-f6dfce00-aeca-11e9-84dd-55f634d5f389.png)

#### Include any warning/errors/backtraces from the logs

```
2019-07-25 10:37:14.863 - Can't read column 'select_my_truns_idsarray' value
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.DBUtils.getEntityFromMetaData(DBUtils.java:1804)
	at org.jkiss.dbeaver.model.DBUtils.getEntityFromMetaData(DBUtils.java:1792)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:197)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:62)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:82)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.fetchColumnValue(PostgreArrayValueHandler.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:755)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2776)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by serge-rider** [comment] 2019-07-25 16:07
Duplicate of #6312
You can check the fix in Early Access version (https://dbeaver.io/files/ea)

**Closed by serge-rider** 2019-07-25 16:07 UTC
Labels: bug, duplicate, x:postgresql

**Comment by edmundo-sw** [comment] 2019-07-25 16:19
It works on DBeaver 6.1.4.201907251011
