### ISSUE TITLE
Generated `UPDATE` statements modify wrong rows

### ISSUE THREAD

**Issue by onefifth** [dbeaver/dbeaver#20876] opened 2023-08-11 14:42 UTC
### Description

When saving modifications made to data fetched via a `SELECT` query that includes a `JOIN`, the generated `UPDATE` statements when saving will include a `WHERE id=##` clause that incorrectly uses the id value from the first selected id column, rather than the id belonging to the table that owns the column being updated.

This results in unintended modification of values from rows that were not present in the selected data.

This behavior is easiest to see when the "Show confirmation before save" is enabled and the generated `UPDATE` statements can be previewed before they're run, although the bug is reproducible regardless of this setting.

### DBeaver Version

Community Edition 23.1.4.202308061552

### Operating System

Windows 10/11

### Database and driver

PostgreSQL 14.2
PostgreSQL JDBC Driver

### Steps to reproduce

Given the query: 
`select T1.id, T2.id, T2.value from T1 join T2 on T2.t1_id=T1.id;`
| id | id | value |
|-|-|-|
|1|22|100|
|1|23|200|
|1|24|300|

Attempting to change the second row's value 200 to 400 will generate the incorrect update statement:
`UPDATE public.T2 SET value=400 WHERE id=1;`
The expected update statement should be:
`UPDATE public.T2 SET value=400 WHERE id=23;`

While the table owning the column being modified (e.g. `value`) is always correctly identified (`UPDATE public.T2`), the id value used in the `WHERE` clause appears to always be taken from the first column named `id` present in the initial select statement.

Omitting `T2.id` from the select statement entirely results in an (expected) error:
`Can't update attribute 'value' - attributes of key '"VIRTUAL_PK"' are missing in result set`

**Comment by onefifth** [comment] 2023-08-11 15:12
This issue can also be easily reproduced using the `DBeaver Sample Database` if the tables are first altered to use the same name for their primary key columns.
```
ALTER TABLE Album RENAME COLUMN AlbumId TO Id;
ALTER TABLE Artist RENAME COLUMN ArtistId TO Id;
```

![image](https://github.com/dbeaver/dbeaver/assets/862566/dc00bdaf-b5ec-4150-b06f-1ad5f8eb00a2)

The update statement in the screenshot above should be:
`UPDATE Album SET Title='Let There Be Rock TWO' WHERE Id=4;`

**Comment by Matvey16** [comment] 2023-08-31 07:48
@onefifth Thank you for the report

**Comment by LonwoLonwo** [comment] 2024-03-07 10:10
Again, thanks for the report. I found that this is a duplicate of https://github.com/dbeaver/dbeaver/issues/16755.
So, I'm closing it.

**Closed as completed by LonwoLonwo** 2024-03-07 10:10 UTC
Labels: duplicate, xf:data, xf:metadata, xp:normal
