### ISSUE TITLE
Connection fails on first attempt

### ISSUE THREAD

**Issue by premyslc** [dbeaver/dbeaver#10297] opened 2020-11-10 08:31 UTC
#### System information: 
- Ubuntu 18.04.5 LTS
- DBeaver version 7.2.4.202011011603

#### Connection specification:
- Oracle, 11, 12
- JDBC 12.2.0.1

Problem appears after upgrade from 7.2.1 to 7.2.4. When i open connection for the first time, it ends with error "ORA-01005: null password given; logon denied". The second attempt is fine.

**Comment by readytheory** [comment] 2020-11-10 14:01
Same here for LUW db2 connection, dbeaver on windows.  Community Edition, Windows 10, also  7.2.4.202011011603

 [jcc][t4][10205][11235][4.26.14] Null password is not supported. ERRORCODE=-4461, SQLSTATE=42815

**Comment by pyrocks** [comment] 2020-11-11 12:52
Same here started after upgrading to 7.2.4
running on Mac, DBs are postgres 12

**Comment by ian-a-b** [comment] 2020-11-13 20:42
Same issue on Mojave 10.14.6
DBeaver version Version 7.2.4

**Comment by serge-rider** [comment] 2020-11-16 13:41
Duplicate of #10319.
Fixed in version 7.2.5.

Thanks for the bug report anyway.

**Closed by serge-rider** 2020-11-16 13:41 UTC
Labels: bug, duplicate
