### ISSUE TITLE
Broken UI encoding?

### ISSUE THREAD

**Issue by artstylee** [dbeaver/dbeaver#14405] opened 2021-10-26 22:01 UTC
#### System information: 
- Operating system (distribution) and version // windows 10 last updates
- DBeaver version // 21.2.3
- Additional extensions OPEN JDK 16.0.2.7

#### Describe the problem you're observing:
I've just installed a dbeaver and I've got some issues with the UI text encoding
also, I cannot change the language of the program but nothing helps
![Снимок](https://user-images.githubusercontent.com/56781292/138967350-87735d1f-55e1-4029-ba3c-7b978e2df6b1.JPG)

#### Steps to reproduce, if exist:

tried to delete workbench.xmi
tried to change the language

**Comment by ShadelessFox** [comment] 2021-10-27 05:43
Hello @artstylee,

Thanks for report. Unfortunately, this is an Eclipse bug and we can't do much about it.

Closed as a duplicate of #13821

**Closed as completed by ShadelessFox** 2021-10-27 05:43 UTC
Labels: duplicate, xo:eclipse
