### ISSUE TITLE
Font size cannot be adjusted

### ISSUE THREAD

**Issue by yihoudejintian** [dbeaver/dbeaver#18105] opened 2022-11-02 10:46 UTC
### Description

![image](https://user-images.githubusercontent.com/13391048/199470300-d86a7da1-2504-4322-9f54-f5368e31a15b.png)
Font size cannot be adjusted

### DBeaver Version

22.1

**Comment by E1izabeth** [comment] 2022-11-02 12:26
Thank you for bug report. It's a duplicate of #17253

**Closed as not planned** 2022-11-02 12:26 UTC
Labels: duplicate, xf:ui
