### ISSUE TITLE
Can't create Foreign key on Postgres Table

### ISSUE THREAD

**Issue by ramrasi** [dbeaver/dbeaver#4015] opened 2018-08-17 05:13 UTC
I am Using Postgres.

When i create a new foreign key constraint cant create it(No action happen)

i check Debug log throwing an exception.

2018-08-17 10:43:02.445 - Event loop exception
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.editors.EditorUtils.trackControlContext(EditorUtils.java:289)
	at org.jkiss.dbeaver.ui.controls.itemlist.NodeListControl.<init>(NodeListControl.java:99)
	at org.jkiss.dbeaver.ui.controls.itemlist.NodeListControl.<init>(NodeListControl.java:118)
	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl.<init>(ItemListControl.java:74)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditForeignKeyPage.createPageContents(EditForeignKeyPage.java:143)
	at org.jkiss.dbeaver.ui.editors.object.struct.BaseObjectEditPage.createControl(BaseObjectEditPage.java:49)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.createDialogArea(EditObjectDialog.java:63)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:768)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.createContents(EditObjectDialog.java:70)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1096)
	at org.eclipse.jface.window.Window.open(Window.java:783)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.showDialog(EditObjectDialog.java:102)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.showDialog(EditObjectDialog.java:97)
	at org.jkiss.dbeaver.ui.editors.object.struct.BaseObjectEditPage.edit(BaseObjectEditPage.java:81)
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreForeignKeyManager$1.runTask(PostgreForeignKeyManager.java:71)
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreForeignKeyManager$1.runTask(PostgreForeignKeyManager.java:1)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:25)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:34)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:58)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:168)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4915)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4521)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:162)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)

**Comment by serge-rider** [comment] 2018-08-17 15:38
Duplicate of #3984
You can see the fix in EA version
Thanks for report anyway.

**Closed by serge-rider** 2018-08-17 15:38 UTC
Labels: bug, duplicate
