### ISSUE TITLE
DDL of Renamed Stored Procedure Makes Create With Old Name Not New

### ISSUE THREAD

**Issue by MrThwibble** [dbeaver/dbeaver#20496] opened 2023-07-06 15:55 UTC
### Description

The dBeaver generated DDL of a stored procedure that has been renamed will issue a 'CREATE PROCEDURE' using the original name of the procedure, not the new name.

### DBeaver Version

23.1.1.202306251800

### Operating System

Windows 10

### Database and driver

Microsoft JDBC Driver for SQL Server 9.2.0.jre8
com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE v. 9.2.0.x64

### Steps to reproduce

I needed to replace a stored proc and back up the old one.  I *think* this is what I did:

Renamed the old stored proc.
Copy/pasted the code from the old code in to an SQL editor.
Made the changes as required.
Created the new proc.

Therefore, the new proc has the same name as the original version of the proc.

Exported the DDL of both procs.

### Additional context

You can tell the difference between the new and renamed object by the addition of a line in the comments.

The 'new' version has:
**"-- 2023/05/12 | LJones   | Add PRL_GAS_FAC, PRL_LIQ_FAC"**

Attached:
- DDL as exported from SQL Server Managment Studio (correct)
- DDL as exported from dBeaver (incorrect)
- Some screenshots showing that when dBeaver is asked to display  the DDL; the correct object is loaded but the create statement is incorrect.

[dBeaver Bug Report - dBeaver New Object DDL.txt](https://github.com/dbeaver/dbeaver/files/11970010/dBeaver.Bug.Report.-.dBeaver.New.Object.DDL.txt)
[dBeaver Bug Report - dBeaver Renamed Object DDL.txt](https://github.com/dbeaver/dbeaver/files/11970011/dBeaver.Bug.Report.-.dBeaver.Renamed.Object.DDL.txt)
[dBeaver Bug Report - SSMS output for New Object.txt](https://github.com/dbeaver/dbeaver/files/11970016/dBeaver.Bug.Report.-.SSMS.output.for.New.Object.txt)
[dBeaver Bug Report - SSMS output for Renamed Object.txt](https://github.com/dbeaver/dbeaver/files/11970017/dBeaver.Bug.Report.-.SSMS.output.for.Renamed.Object.txt)
![dBeaver Bug Report - Right object, wrong CREATE name](https://github.com/dbeaver/dbeaver/assets/119704165/aa58e4d9-fd56-4dc7-9e7e-0259e270354b)
![dBeaver Bug Report - Right object, right CREATE name](https://github.com/dbeaver/dbeaver/assets/119704165/99eac1d4-bcaf-4fca-a426-4c7cbf08ea39)

**Comment by LonwoLonwo** [comment] 2023-07-13 10:20
Hello @MrThwibble 

Did you try to refresh the Navigator tree after the procedure manipulations?

**Comment by MrThwibble** [comment] 2023-07-15 12:37
Morning! I can't say for certain, however it was at least a month between renaming the proc and then wanting to export all of the DDL, and I would have expected to refresh the object tree in that time - yes. 
Thx! 

Sent from my lederhosen 
 
  On Thu., 13 Jul. 2023 at 4:20 a.m., ***@***.***> wrote:   


Hello @MrThwibble

Did you try to refresh the Navigator tree after the procedure manipulations?

**Comment by hrimthrusa** [comment] 2023-07-26 10:12
Thank you for the report!

### OS

Windows 10
SQL Server 16.0.950.9

### STR
Create a stored procedure for a schema in SQL Server
Rename it using the right click context menu
Refresh the schema to make sure the changes are visible in the UI
Generate a DDL for this stored procedure and verify, that the name in the script hasn't change from the name, which was given upon creation of the stored procedure

![image](https://github.com/dbeaver/dbeaver/assets/97725836/580687a1-f38d-417a-822e-695141001aea)

**Comment by LonwoLonwo** [comment] 2023-09-11 16:01
Also related https://github.com/dbeaver/dbeaver/issues/15431

**Comment by LonwoLonwo** [comment] 2024-02-14 09:31
Thank you for the bug report. It's a duplicate of #15431, so I'm closing this issue.
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by LonwoLonwo** 2024-02-14 09:31 UTC
Labels: duplicate, x:mssql, xf:metadata, xp:normal
