### ISSUE TITLE
Data Transfer box expands across multiple screens

### ISSUE THREAD

**Issue by rkgeorges24** [dbeaver/dbeaver#34777] opened 2024-07-11 12:27 UTC
### Description

I have 3 displays attached to my windows PC. After running a project query, I click on Export Data. This is followed by a Data Transfer box that expands across all 3 screens so I am unable immediately to process my data transfer request.  I have to pull the box a long way to the left so I can start reducing the size of the box so it will fit on one screen.

### DBeaver Version

Community edition 24.1.2.202407071610

### Operating System

Windows 10

### Steps to reproduce

See description.

### Additional context

This only recently began to happen, I believe after the latest DBeaver update. Wondering if there is a simple way to back out the last update.

**Comment by E1izabeth** [comment] 2024-07-11 12:30
Thank you for bug report.
I'm closing it as a duplicate of https://github.com/dbeaver/dbeaver/issues/34705
The fix is on the way.

To downgrade the version, you can download the previous version from the web site installer and just run it.
Here is the link to the page with Previous versions https://dbeaver.io/files/

![image](https://github.com/dbeaver/dbeaver/assets/28875055/06350202-3782-4bd5-93c9-70e75834ea36)

**Closed as not planned by E1izabeth** 2024-07-11 12:30 UTC
Labels: duplicate, xf:datatransfer, xf:ui

**Comment by rkgeorges24** [comment] 2024-07-11 14:59
Thank you!!
