### ISSUE TITLE
LOAD DATA INFILE throwing error

### ISSUE THREAD

**Issue by rootboyslim** [dbeaver/dbeaver#29321] opened 2024-05-03 13:47 UTC
### Description

I have a LOAD DATA INFILE command that is throwing an error.  Running the same script in another SQL tool (MySQL Workbench) there is no problem.  This problem seems to be related to the recent release. The explicit messages is:

SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LOAD DATA INFILE 'c:\\temp\\RateData_Power_RV_2024_05_01.txt'

INTO TABLE Sou...' at line 36

The only thing changed was the version of dbeaver I'm running.  Meaning, it ran before the recent update.

[dbeaver.log](https://github.com/dbeaver/dbeaver/files/15200748/dbeaver.log)
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/15200755/dbeaver.log)
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/15200758/dbeaver.log)

...here's the script:

DROP TABLE IF EXISTS SouthwestREProductMapper_STAGING;
CREATE TABLE SouthwestREProductMapper_STAGING (
		Ext_ProducerNumber 		INT(11) DEFAULT NULL,
		ProducerNumber 			VARCHAR(100) DEFAULT NULL,
		State_Code 				VARCHAR(4) DEFAULT NULL,
		Rate_ScheduleCode 		VARCHAR(100) DEFAULT NULL,
		Product 				VARCHAR(100) DEFAULT NULL,
		Program 				VARCHAR(100) DEFAULT NULL,
		Subprogram 				VARCHAR(100) DEFAULT NULL,
		Selector 				VARCHAR(100) DEFAULT NULL,
		Coverage_Code 			VARCHAR(100) DEFAULT NULL,
		Coverage_Name 			VARCHAR(100) DEFAULT NULL,
		Product_Code 			VARCHAR(100) DEFAULT NULL,
		Deductible_Code 		VARCHAR(10) DEFAULT NULL,
		Vehicle_Class_Code 		VARCHAR(50) DEFAULT NULL,
		Mileage_Start 			INT(11) DEFAULT NULL,
		Mileage_End 			INT(11) DEFAULT NULL,
		Effective_Date 			DATETIME DEFAULT NULL,
		Expiration_Date 		DATETIME DEFAULT NULL,
		IsModelYearEligile 		VARCHAR(5) DEFAULT NULL,
		ModelYearEligible 		VARCHAR(5) DEFAULT NULL,
		Subprogram_Code 		VARCHAR(5) DEFAULT NULL,
		TermCode 				VARCHAR(20) DEFAULT NULL,
		Term_Months 			INT(11) DEFAULT NULL,
		Term_Miles 				INT(11) DEFAULT NULL,
		Total_Producer_Cost 	DECIMAL(12,2) DEFAULT NULL,
		ProductTypeID 			INT(11) DEFAULT NULL,
		VehicleTypeID 			INT(11) DEFAULT NULL,
		ProductID 				VARCHAR(250) DEFAULT NULL,
		MinFinanceTerm 			INT(11) DEFAULT NULL,
		MaxFinanceTerm 			INT(11) DEFAULT NULL,
		RVUnitType 				VARCHAR(10) DEFAULT NULL,
		Stamp 					TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

LOAD DATA INFILE 'c:\\temp\\RateData_Power_RV_2024_05_01.txt'
INTO TABLE SouthwestREProductMapper_STAGING
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(    Ext_ProducerNumber 
    ,ProducerNumber 
    ,State_Code
    ,Rate_ScheduleCode 
    ,Product 
    ,Program 
    ,Subprogram 
    ,Selector 
    ,Coverage_Code 
    ,Coverage_Name 
    ,Product_Code
    ,Deductible_Code 
    ,Vehicle_Class_Code
    ,Mileage_Start 
    ,Mileage_End 
    ,@EffectiveDate 
    ,@ExpirationDate
    ,IsModelYearEligile 
    ,ModelYearEligible 
    ,@Subprogram_Code 
    ,TermCode
    ,Term_Months 
    ,Term_Miles 
    ,Total_Producer_Cost 
    ,@ProductTypeID 
    ,@VehicleTypeID
    ,@ProductID
    ,@MinFinanceTerm
    ,@MaxFinanceTerm
    ,@RVUnitType
)
SET 	ProductTypeID		= NULLIF(@ProductTypeID,'')
		,VehicleTypeID 		= NULLIF(@VehicleTypeID,'')
		,ProductID 			= NULLIF(@ProductID,'')
        ,MinFinanceTerm 	= NULLIF(@MinFinanceTerm,'')
        ,MaxFinanceTerm 	= NULLIF(@MaxFinanceTerm,'')
        ,Subprogram_Code  	= NULLIF(@Subprogram_Code ,'')
        ,RVUnitType  		= NULLIF(@RVUnitType ,'')
        ,Effective_Date		= STR_TO_DATE(@EffectiveDate, '%b%d%Y %l:%i%p')
        ,Expiration_Date	= STR_TO_DATE(@ExpirationDate, '%b%d%Y %l:%i%p')        
       	,Stamp 				= CURRENT_TIMESTAMP();

### DBeaver Version

Version 24.0.3.202404211624

### Operating System

Windows 11

### Database and driver

com.mysql.cj.jdbc.Driver

**Comment by E1izabeth** [comment] 2024-05-03 14:00
Duplicate of https://github.com/dbeaver/dbeaver/issues/26416
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Closed as not planned by E1izabeth** 2024-05-03 14:00 UTC
Labels: duplicate, xf:sql execution

**Comment by rootboyslim** [comment] 2024-05-03 17:59
Thank you!  That fixed it.
