### ISSUE TITLE
Mac Version 22.1.3 Not Working

### ISSUE THREAD

**Issue by tomlenzmeier** [dbeaver/dbeaver#17388] opened 2022-08-18 14:38 UTC
### Description

After upgrading my previous version, the program does not work. None of the menu options, such as File, Edit, Navigate, etc. work. If I click on them, nothing happens. Furthermore, I cannot right-click on anything at all. The only way to close the program is to force-quit.

### DBeaver Version

Community Edition 22.1.3

### Operating System

Monterey 12.5

### Database and driver

I can't even retrieve these settings.

### Steps to reproduce

1. Open the program
2. Can't do anything

I've completely uninstalled this program. I even went to /Library/DBeaverData and deleted that. I then reinstalled, but it's still not working.

### Additional context

tlenzmeier@gmail.com

**Comment by Apple-76** [comment] 2022-08-22 16:30
Having the same issue on 22.1.5 on MacOS Ventura 13.0 beta (22A5321d)

**Comment by fxerkan** [comment] 2022-08-24 16:54
I have the same issues and also these additional problems;
- I can't open the Context Menu (right click) menu in any place
- Dbeaver toolbar menus are NOT working - I can't click or open any menu item even if it highlight the menu 
<img width="630" alt="image" src="https://user-images.githubusercontent.com/20793273/186476730-0cb91c72-ab40-4ad5-a646-7c6faf39b68b.png">
- when I close the main Dbeaver application, another app or popup window appears which looks like the update windows or something similar and try to do something but then crash or close with the main app.

System : Apple Silicon (M1)
OS : macos 13.0 Ventura Beta (22A5321d)
Dbeaver Version : CE 22.1.5

**Comment by Destrolaric** [comment] 2022-08-25 13:14
Hi, the issue is a duplicate of #17204. Unfortunately, this is the Eclipse bug in Ventura, and it should be resolved later in the autumn. For now, downgrading may help.

**Closed as completed** 2022-08-25 13:14 UTC
Labels: duplicate
