### ISSUE TITLE
English connection name and table name can't change font size,

### ISSUE THREAD

**Issue by Maxx-Yang** [dbeaver/dbeaver#17253] opened 2022-08-04 01:30 UTC
### Description

I found thant the table name in the  Database Navigator is so smalll and I can't change the font size. But the chinese followed the table name can change size. so I want know why this take place.

### DBeaver Version

22.1.3

**Comment by Maxx-Yang** [comment] 2022-08-04 01:37
like the below image display,chinese can change the font size 
![image](https://user-images.githubusercontent.com/32293803/182744332-e54d4482-2ad1-4a71-abef-29a3e00b5092.png)

**Comment by E1izabeth** [comment] 2022-08-20 06:08
Thank you for bug report.

**Comment by E1izabeth** [comment] 2022-11-02 12:29
It may be related with #12975

**Comment by flambchap** [comment] 2022-12-15 10:27
~Duplicate of https://github.com/dbeaver/dbeaver/issues/12975.~

**Comment by E1izabeth** [comment] 2023-01-22 19:49
Fixed in scope of #12975
Can be changed in `Tree and table font for views`
![image](https://user-images.githubusercontent.com/28875055/213937047-329fb326-7285-4be9-9560-4677e39f88e7.png)

**Closed as completed by E1izabeth** 2023-01-22 19:49 UTC
Labels: xf:navigator, xf:ui
