### ISSUE TITLE
Add "starting time" to query statistic after execution

### ISSUE THREAD

**Issue by bob27aggiustatutto** [dbeaver/dbeaver#18651] opened 2023-01-04 10:37 UTC
**Is your feature request related to a problem? Please describe.**
When you execute a query (for example a "create table" query) you get a statistic about the execution itself
![immagine](https://user-images.githubusercontent.com/120955097/210536857-0fa10d76-3e8a-4002-a88f-94ca41f16770.png)

There's "finish time", I'd like to add "starting time"

**Comment by uslss** [comment] 2023-01-04 10:47
thanks for the suggestion. close it as duplicate of #5450

**Closed as completed by uslss** 2023-01-04 10:47 UTC
Labels: duplicate
