### ISSUE TITLE
ODBC Query with NULL value 

### ISSUE THREAD

**Issue by m2art** [dbeaver/dbeaver#6213] opened 2019-07-03 08:00 UTC
#### System information: 
- Windows 10
- DBeaver 6.1.1.201906240635
- Java 11.0.3 
- Additional extensions: without

#### Connection specification:
- Database: SQL
- Driver name: JDBC
- Do you use tunnels or proxies : ODBC Connection, SQL Anywhere 17

DBeaver returns NULL in fields where the value is 100%.
The following is an example of query and table view:

LOG FILE:
```
!SESSION 2019-07-03 09:20:11.687 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2019-07-03 09:20:24.000
!MESSAGE Error determining server version
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-07-03 09:20:24.000
!MESSAGE 
!STACK 0
java.lang.UnsupportedOperationException
	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:348)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:426)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:785)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Query:
![image](https://user-images.githubusercontent.com/2386396/60574139-48d47e80-9d79-11e9-81b1-8c92f29502e2.png)

**Comment by serge-rider** [comment] 2019-07-04 14:28
- What ODBC driver do you use?
- Did you try to use standar Sybase driver (jConnect or jTDS) instead of ODBC?

**Comment by m2art** [comment] 2019-07-05 21:45
Yes but I have problem with configuration this two type driver. To have workiem correctly thay need data: Host, Database, User, PASS. I have only DNS, User, PASS and I don’t know how cofig those new driver.

**Comment by lumik** [comment] 2019-10-15 12:04
I have the same problem. It shows null in all `NVARCHAR2` fields when I connect to Oracle through ODBC. I use 10.0.17134.1 ODBC with Oracle in OraClient12Home1 driver.
I issue
```
CREATE TABLE test (city NVARCHAR2(30) NOT NULL);
INSERT INTO test VALUES ('DALLAS');
SELECT city LENGTH(city) FROM test;
```
and the city column shows NULL inside.

**Comment by uslss** [comment] 2019-11-27 14:31
is it still actual?

**Comment by lumik** [comment] 2019-11-27 18:20
Yes, it is. I updated to DBeaver version 6.2.5 with the same result, `NVARCHAR2` colums display `[NULL]`.

**Comment by alangreg99** [comment] 2020-04-16 14:56
Was this ever resolved,  I am getting the same issue using a NetSuite ODBC driver ?

**Comment by eram** [comment] 2020-09-27 11:50
I'm getting the same issue with ODBC driver: CData for Azure Table Storage v 20.0.7515.0
DBeaver 7.2.1.202009201907

**Comment by marcosarmas** [comment] 2021-05-31 15:55
Hi, 
I have the same issue with Netsuite ODBC Driver, do you have solved this problem?

**Comment by bryan7087** [comment] 2021-06-02 13:25
Same for me.

**Comment by DenisCasselle** [comment] 2021-07-01 08:55
Had the same issue. Found a solution by configuring my ODBC data sources in Windows and activate the checkbox "Report unicode column as char" in client settings/Third party options/

**Comment by Drewster727** [comment] 2021-08-05 22:12
I can reproduce this issue with the latest version of dbeaver.

@DenisCasselle I don't have a "Third Party options" section to enable that checkbox on my DSN/ODBC sources in windows. Where can I find this?

**Comment by uslss** [comment] 2021-11-19 08:54
is it still actual?

**Comment by m2art** [comment] 2021-11-19 20:49
Yes. Problem still exist. Do you have some solution or any body else have idea how to solve this issue?

**Comment by Stadlerrr** [comment] 2021-12-06 14:26
Hi, there's any chance to solve this? 
I would really like to move from Navicat to dBeaver, but until this is fixed I just can't use it.
Having queries returning NULL values where they should not doesn't allow me to do my job in a very solid way.
I hope that someone can help. Thank you!

**Comment by Stadlerrr** [comment] 2021-12-10 00:06
Hi all,

I figured out a solution (or at least a possible quick workaround)!! 

It is just necessary to set the "Character set" in MySQL Connector/ODBC Data Source Configuration.
Usually it is blank by default...

You can easily find and modify it here: 
Type in Windows menú (Search) - ODBC Data Sources (64-bit) - _select your connection_ - Configure... - Details - Connection tab - Character Set

![image](https://user-images.githubusercontent.com/95294375/145494914-71914171-8e68-42c2-a6ef-666d26e40dcf.png)

I did some checks and (I'm not sure why) if the Character Set is different from **UTF8**, for example UTF8mb4 or latin1, dBeaver returns [NULL] for queries casting CHAR or NCHAR.

After setting it as UTF8 all my queries that were returning [NULL] now return the correct value!

You can quickly check this by running this simple query: 

**SELECT 'xxxx' as column1;**

I'm not sure if this should be fixed from dBeaver side. Other clients didn't require this workaround so I guess there are some compatibility modifications to apply.

Also, I'm not quite sure if by doing this I'm somehow limiting the possibilities of my ODBC connection, so I hope someone can tell me if there's a better way to fix this.

Thanks

**Comment by Stadlerrr** [comment] 2021-12-13 12:38
Actually my last comment just partially fixes the issue, but I discovered that it doesn't work for VARCHAR columns where the character set is different from the one chosen in ODBC connector. 

For example if I choose UTF8 in ODBC connector and the character set of the column is latin1 dBeaver returns NULL. 
If I swap to latin1 in ODBC connector the query display the correct values for columns set as latin1, but NULL value for columns having character set UTF8.

If I reset the value to default (blank) in ODBC connector latin1 columns will display the right value, but not the ones in UTF8.

I actually noticed that dBeaver does not even provide the option to change the character set and collation of the table and its columns.
After creating a new TEST_TABLE with dBeaver I checked it from Navicat and I can see that latin1 has been given a default charset, but I can't see/modify it from dBeaver.

Any idea to fix this?


**dBeaver view**
![image](https://user-images.githubusercontent.com/95294375/145880155-32707bdd-f5b0-4148-a9b3-7fa31d3bfedf.png)

**Navicat view**
![image](https://user-images.githubusercontent.com/95294375/145880666-4ea83ee1-64b5-4b07-b3d4-ceeb40731c94.png)

**Comment by DarlingR** [comment] 2022-02-01 22:12
Any updates here? I am using dbeaver 21.3.3 with netsuite odbc 8.10.92 64bit and the varchar2 columns are returning as [NULL]. I have confirmed the value is there as I can query the table with SQL Server Management Studio and see the results. I do not have the ability to change the charset in the odbc connection

![image](https://user-images.githubusercontent.com/7979124/152059119-45fc0719-3e61-43b2-9a13-25e08290b63e.png)

![image](https://user-images.githubusercontent.com/7979124/152059230-3f761e61-7eb1-49b3-9029-90cf69d9bfdc.png)

![image](https://user-images.githubusercontent.com/7979124/152059377-97bd8c44-236a-492c-ac0f-0e59ed7a7ddc.png)

SSMS
![image](https://user-images.githubusercontent.com/7979124/152060054-fff29197-d37a-4ac6-843a-9ce0291cea02.png)

**Comment by pawelwiejkut** [comment] 2022-02-04 10:07
I have the same issue in the case of the HANA ODBC connection.

**Comment by DarlingR** [comment] 2022-02-04 14:40
a solution to the problem was to switch to jdbc. I am now seeing all intended values the correct way. I used this article: http://jaem04.blogspot.com/2018/10/netsuite-odbc-and-jdbc-via-dbeaver.html . I removed the cipher section and left encryption and was able to connect on PC and MAC and see the data

**Comment by carverjc** [comment] 2022-03-09 20:08
For the CData ODBC driver I was using, I got it fixed by changing the "Map To WVarchar" to False.  Then I restarted DBeaver and it worked.

**Comment by mbulelo-damba** [comment] 2022-04-21 14:56
I figured it out. I had the same issue when I was using `NVARCHAR` as a data type. I changed it to `VARCHAR` and the data is visible.<br><br>
![hotels](https://user-images.githubusercontent.com/31652913/164740131-abd50943-1b4f-45cf-8f0b-5202ce192785.PNG)

**Comment by FakieKickflip** [comment] 2022-05-19 11:51
Have the same issue with the JDBC ODBC bridge driver from JRE7. All the varchar Columns are [NULL]. Any tips?

**Comment by rambouillet** [comment] 2022-08-09 15:26
I have the same issue with the following setup:

Operating System: `Windows 10 Enterprise Version`
DBeaver Version: `22.1.1.202206261508`
Driver: `sun.jdbc.odbc.JdbcOdbcDriver` and `ODBC Driver 17 for SQL Server`
Database: `SQL Server 2019 Express (a.k.a. SQLExpress)`
Connection String: `Driver={ODBC Driver 17 for SQL Server};Server=.\sqlexpress;Uid=;Pwd=;Trusted_Connection=Yes;`

Note: I don't want to change the nvarchar columns to varchar--I'm letting Entity Framework choose the column types, and it prefers nvarchar over varchar. I believe Entity Framework chooses nvarchar to take advantage of the nvarchar type's Unicode character support.

![bug](https://user-images.githubusercontent.com/20598632/183690616-582cfe4f-3276-4aef-bfae-669bab4e3624.PNG)

**Comment by Damba-Mbulelo** [comment] 2022-08-09 15:35
> 

Change your NVACHAR to VARCHAR and everything will be visible. That's how I did it on my project.

**Comment by rambouillet** [comment] 2022-08-09 15:44
> Change your NVACHAR to VARCHAR and everything will be visible. That's how I did it on my project.

I would do this, but Entity Framework is preferring nvarchar over varchar, and I don't want to change its default functionality. Plus, I would lose all the benefits of Unicode if I just used varchar.

**Comment by psychelzh** [comment] 2022-08-17 07:03
Weirdly, if I choose "ODBC ANSI Driver" when configuring data source on Windows, DBeaver will show Chinese characters as normal. However, ANSI is not recommended when data stores Unicode characters.

**Comment by ahmaldonado** [comment] 2022-09-02 22:06
Same problem. WIth ODBC connection the nvarchar values are shown as nulls. To work around this, change to varchar using cast function.

**Comment by aetonsi** [comment] 2022-11-24 11:24
Bump.

As of nov 24 2022, the issue is still present. `nvarchar` columns are filled with `null`s.

Changing column type to `varchar` fixes it, i tried locally. **But i cannot alter the client's database just to view data correctly in dbeaver.** Nor i can `CAST` every single textual field in every query. A simple `SELECT * FROM users` would become bloated with `CAST`s and absurd list of fields: the table has almost 20 `nvarchar` fields...

Yes i could just use dbeaver's SqlServer driver and it works correctly. I'm using ODBC because my application uses it to interact with the client's database, and i want to have the **same environment, to avoid discrepancies**: this means using the same driver and running the same queries.

So, please, please, fix this. It's evidently a problem with dbeaver or the JDBC driver used. **Running the same query with php's `PDO`, using the same DSN, works correctly.**

---

| info  | value |
| ------------- | ------------- |
| dbeaver version  | v22.2.5  |
| database  | Sql Server 2019  |
| connection driver | JDBC-ODBC Bridge (SQLSRV32.DLL) 2.0001 (10.00.22621.819) |
| DSN  | `odbc:Driver={SQL Server};Server=127.0.0.1`  |

**Comment by ShadelessFox** [comment] 2023-10-31 09:11
Legacy ODBC driver is no longer supported.

DBeaver now offers a custom and maintained ODBC driver available in all PRO products. You can read more about it on our wiki: https://github.com/dbeaver/dbeaver/wiki/ODBC-JDBC-Driver.

You can go ahead and request a trial license to see if it works there: https://dbeaver.com/trial/

**Comment by E1izabeth** [comment] 2023-12-12 12:43
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Closed by E1izabeth** 2023-12-12 12:43 UTC
Labels: bug, wait for response, third party issue, x:odbc

**Comment by aetonsi** [comment] 2023-12-14 11:50
Problem still persists since no new ODBC/JDBC **free** drivers has been released.
