### ISSUE TITLE
Changed ER connections can't be arranged by "Arrange diagram"

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12508] opened 2021-05-17 15:19 UTC
#### System information: 
- Windows 10, DBeaver CE 21.0.5, Derby Server (but I can reproduce this with other databases)

#### Describe the problem you're observing:
If the links between tables in the ERD have been edited (bent by moving the points in the middle of the connection), the button Arrange diagram acts on the tables, but not on the edited connections.
#### Steps to reproduce, if exist:
Make chaos in connections:
![image](https://user-images.githubusercontent.com/43252954/118513366-519b8700-b73c-11eb-8ac0-c293317221af.png)
![image](https://user-images.githubusercontent.com/43252954/118512590-9e329280-b73b-11eb-90a1-355549c735cc.png)
Click on this button in the ERD toolbar: ![image](https://user-images.githubusercontent.com/43252954/118512661-aee30880-b73b-11eb-8ef1-523c9b12fad8.png)
The tables recover to the default position, the connections remained in place:
![image](https://user-images.githubusercontent.com/43252954/118512643-aa1e5480-b73b-11eb-9013-0e2a7501b513.png)

**Comment by uslss** [comment] 2021-08-05 09:44
verified

**Comment by Matvey16** [comment] 2021-11-30 09:34
This was partially broken again by a fix in #14704 
Currently reproduces by:
1. Create a custom diagram with relations
2. Drag the lines so they will become a mess
3. Save diagram and close it
4. Reopen the diagram and click on `arrange diagram` button

**Comment by rsprinkle** [comment] 2022-03-29 14:10
I see similar problems when you select multiple tables in the diagram and drag them to a new location.  Any customized relation ship lines between the dragged table will not be redrawn as expected.  The 'bend points' are not moved along with the tables.

**Closed as completed** 2022-05-04 10:15 UTC
Labels: xf:erd, sp:2

**Comment by rezaza1967-byte** [comment] 2025-12-23 15:39
To have an effective diagram, we need the related fields to be exactly where the two ends of the lines connect.

Why aren't the table field connections in the diagram shown in the correct location?! (like above image)
 
It's also not possible to edit them because new points have been added unintentionally, which increases the number of vertices and breaks the line, and it's not possible to place the connection of two fields exactly where the related fields are located.

**Comment by rsprinkle** [comment] 2025-12-23 18:19
#

> To have an effective diagram, we need the related fields to be exactly where the two ends of the lines connect.
> 
> Why aren't the table field connections in the diagram shown in the correct location?! (like above image)
> 
> It's also not possible to edit them because new points have been added unintentionally, which increases the number of vertices and breaks the line, and it's not possible to place the connection of two fields exactly where the related fields are located.

I'm just a user of dBeaver, but the short answer is that the graphical model library that they use from the Eclipse project does diagrams this way by default.  Custom code would be required to override this behavior.
