### ISSUE TITLE
Slow DB Discovery for MS SQL Server (Ubuntu)

### ISSUE THREAD

**Issue by gajatko** [dbeaver/dbeaver#2614] opened 2017-12-07 14:07 UTC
Expanding "tables" node in Database Navigator in Ubuntu for MS SQL Server is incredibely slow. After ~30 min I killed a process, sorry. Not sure if it ever ends. 100% CPU utilization by java process on one of i7 cores.
Notes:
1) I have a high-end PC. MS SQL Management Studio on Windows has no such lag.
2) Query execution is fast. Now DBeaver is not responding so I cannot do anything, though.
3) DB Discovery ("view tables") is fast
It seems that the issue is in the "tree" eclipse control, just like list of git branches in java eclipse.

**Comment by serge-rider** [comment] 2017-12-07 16:59
Duplicate of #2152 (check comments for workaround).

This is SWT+GTK problem on some Linux systems (UI hangs if tree contains too many elements).  No good workaround so far.

**Comment by tati-kru** [comment] 2018-01-19 11:15
This ticket will be closed as a duplicate. Please, check #2152 for more details.

**Closed by tati-kru** 2018-01-19 11:15 UTC
Labels: duplicate, question
