### ISSUE TITLE
Cropped Text results - v5.2.4

### ISSUE THREAD

**Issue by lefty06** [dbeaver/dbeaver#4597] opened 2018-11-11 11:43 UTC
- When executing a query, the **last digit** is missing on **text view** but is **correct in grid view**
- epath column should show '301862:2091136:2091294' but instead show '301862:2091136:209129'
Last digits missing (see screenshot)? 

- I kept the default settings and cannot find out how to install an earlier version?

![dbeaver5 2 4](https://user-images.githubusercontent.com/31104194/48312440-73818500-e5a6-11e8-9404-7fcddfb68534.gif)

**Comment by lefty06** [comment] 2018-11-11 12:58
Think the global settings are also correct by default
![image](https://user-images.githubusercontent.com/31104194/48313248-6c13a900-e5b1-11e8-8879-c229e745032d.png)

**Comment by serge-rider** [comment] 2018-11-11 21:36
Duplicate of #4547

**Closed by serge-rider** 2018-11-11 21:36 UTC
Labels: bug, duplicate
