### ISSUE TITLE
Sql profiler

### ISSUE THREAD

**Issue by borisdj** [dbeaver/dbeaver#11764] opened 2021-03-17 13:04 UTC
I can't find option in Dbeaver to catch and see sql executed from external app.
Essentially feature of Sql Profiller tool from SSMS.
Does Dbeaver has this ?

**Comment by uslss** [comment] 2021-03-22 09:17
thanks for suggestion

**Comment by uslss** [comment] 2022-06-01 12:04
Closed as a duplicate of #9615

**Closed as completed by uslss** 2022-06-01 12:04 UTC
Labels: duplicate
