### ISSUE TITLE
I can't see the progress commands when backup or restore postgresql in ubuntu

### ISSUE THREAD

**Issue by lucasoz** [dbeaver/dbeaver#21354] opened 2023-09-27 19:52 UTC
### Description

I upgrade to 23.2.1 in ubuntu and when I tried to run a backup I noticed that I can't see the progress commands. I tried to restore a backup and I noticed the same.

### DBeaver Version

CE 23.2.1

### Operating System

Ubuntu 22.04.3 LTS

### Database and driver

1. Database: PostgreSQL 13.11
2. Driver: PostgreSQL JDBC Driver 42.2.20

### Steps to reproduce

1. Connect to a postgresql database
2. Select a database
3. Go to tools/backup o tools/restore

The next step button is disabled and when I press proceed the process runs in background.
![image](https://github.com/dbeaver/dbeaver/assets/18173423/f7afce04-1e6f-4898-9da1-a41494d9b846)

**Comment by E1izabeth** [comment] 2023-09-28 06:25
Thank you for bug report. It's a duplicate of #21302. We've already fixed it and re-released this version.

**Closed as not planned by E1izabeth** 2023-09-28 06:25 UTC
Labels: duplicate, xf:native clients
