### ISSUE TITLE
Cells are read only. Cant edit.

### ISSUE THREAD

**Issue by LwServices** [dbeaver/dbeaver#9092] opened 2020-06-24 04:42 UTC
#### System information: 
- Windows 10
- 7.1.1
- None

#### Connection specification:
- Oracle 12c 12.2.0.1.0
- Oracle JDBC 12.2.0.1.0

#### Describe the problem you're observing:
Cant edit cells. Shows read only.
I have downgraded to 7.0 and error is gone.

**Comment by nur7186** [comment] 2020-06-24 06:58
I have the same issue after update to version 7.1.1.

**Comment by sorcio46** [comment] 2020-06-24 07:13
Duplicate of #9076

**Comment by kseniiaguzeeva** [comment] 2020-06-24 10:29
The hotfix was published yesterday. Please download 7.1.1. again. Closed as a duplicate.

**Closed by kseniiaguzeeva** 2020-06-24 10:29 UTC
Labels: bug, duplicate
