### ISSUE TITLE
Feature request: Search for column usage

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#4045] opened 2018-08-21 11:04 UTC
It would be nice if I could search for column usage like when I need to know where I'm referring to a certain column in views, procedures, triggers and events (MySQL).

It would be even nicer if I could search a keyword in all database objects.

**Comment by serge-rider** [comment] 2018-08-31 21:47
I think it is a duplicate of #2443 (but less generic).
#2443 can be extended with additional context menu command Find Usages.

**Closed by serge-rider** 2018-08-31 21:47 UTC
Labels: duplicate, feature request, ts: l
