### ISSUE TITLE
Bug Report: Test Connection and Finish grayed out when setting up a new connection

### ISSUE THREAD

**Issue by lalato** [dbeaver/dbeaver#4247] opened 2018-09-20 15:35 UTC
Perhaps this is the expected behavior now, but I don't recall it being this way before.  When setting up a new connection (in my case for Teradata) the user is normally presented with a "Test Connection" and a "Finish" option.   However, these options are grayed out on the Generic JDBC Connection Settings screen.

The workaround appears to be to click on either link for "Network Settings (SSH, SSL, Proxy,...)" or "Connection details (name, type, ...)".  Once either of those are clicked the buttons are revealed and I can complete the connection.

I'm assuming that what is intended is for the user to click "Next" in order to see those screens sequentially, but the "Next" button is also grayed out.  At any rate, once I click on the above noted links, I can complete the process without further issue.

**Comment by serge-rider** [comment] 2018-09-20 20:16
Duplicate of #4235 (see workaround in comments)
Thanks for the bug report anyway

**Closed by serge-rider** 2018-09-20 20:16 UTC
Labels: bug
