### ISSUE TITLE
${datasource} not available in shell commands in the connection configuration

### ISSUE THREAD

**Issue by thulasi-ram** [dbeaver/dbeaver#23068] opened 2024-03-06 14:59 UTC
### Description

- ${datasource} variable is not replaced (evaled?) when executing a shell command. While the list shows its available.
- Other ones likes ${user}, ${port} is available

### Screenshots
<img width="698" alt="Screenshot 2024-03-06 at 8 31 44 PM" src="https://github.com/dbeaver/dbeaver/assets/5107093/e998b87a-355b-4172-bd24-b2d3a77148c5">

<img width="838" alt="Screenshot 2024-03-06 at 7 58 19 PM" src="https://github.com/dbeaver/dbeaver/assets/5107093/381a47e3-1a06-4af4-a816-dfa22ace4528">

### DBeaver Version

Community Edition 23.3.5.202402181738

### Operating System

macOS Ventura 13.6.1

### Database and driver

Database name and version: PostgreSQL 13.10
Driver name and version: PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

1. Try to setup a postgres connection
2. In `Connection Details` > `Shell Commands` > `Before Connect` type `echo ${datasource}`
3. Expectation is to echo the value of the variable but echoes verbatim `$datasource`

**Comment by LonwoLonwo** [comment] 2024-03-06 17:02
Hello @thulasi-ram 

Thanks for the bug report!
We discussed it recently here: https://github.com/dbeaver/dbeaver/issues/23041
And this is a duplicate of https://github.com/dbeaver/dbeaver/issues/21396

Now we are waiting for our QA Team to check the fix for the 21396. You can subscribe for the results.

**Closed as completed by LonwoLonwo** 2024-03-06 17:02 UTC
Labels: duplicate
