### ISSUE TITLE
Improve connection handling 

### ISSUE THREAD

**Issue by DavideArgellati** [dbeaver/dbeaver#2953] opened 2018-02-09 10:15 UTC
Feature request:
Hi, can we improve how the interrupted connections are handled?
everyday if i resume my computer session for example from suspension and I try to get into a previously open script or table view the connection is of course not valid anymore and it starts to throw alert messages, couldn't instead invalidate and reconnect automatically? instead of having to close the 2-3 popup alerting the connection failed and having to reconnect manually ?

Cheers

**Comment by serge-rider** [comment] 2018-02-12 18:55
Duplicate of #2201
Raising priority.

**Closed by serge-rider** 2018-02-12 18:55 UTC
Labels: duplicate, enhancement
