### ISSUE TITLE
"AI service error: The model: `code-davinci-002` does not exist"

### ISSUE THREAD

**Issue by dvandusen** [dbeaver/dbeaver#19597] opened 2023-04-04 07:45 UTC
### Description

I get "AI service error: The model: `code-davinci-002` does not exist " when I do a custom request ("select title" where title is a column of the table selected for custom".  API is set up and working

I'm at Version 23.0.0.202303211029

on M1 Mac w/ latest Ventura 13.2.1 (22D68)

Thx

### DBeaver Version

Enterprise Edition Version 23.0.0.202303211029

### Operating System

Ventura 13.2.1 (22D68)

### Database and driver

Mysql v8.032

### Steps to reproduce

1) create tab for sql query
2) click on openAI icon
3) set to 'custom' and select mysql table
4) type in english query "select title"   (keeping it simple)
5) click translate

### Additional context

Where would I download that component?  It seems to be important.

**Comment by E1izabeth** [comment] 2023-04-04 07:52
Please try choosing one of the `text-` models in preferences.

**Comment by Destrolaric** [comment] 2023-04-04 09:30
`code-` models were disabled by OpenAI we will add gpt3.5 turbo instead in the next release for now we recommend using text-davinci-03 instead.

**Comment by Destrolaric** [comment] 2023-04-04 09:30
Duplicate of https://github.com/dbeaver/pro/issues/1494

**Closed as completed by Destrolaric** 2023-04-04 09:30 UTC
Labels: duplicate, wait for response
