### ISSUE TITLE
Export resultset in Wiki syntax

### ISSUE THREAD

**Issue by cecrdle** [dbeaver/dbeaver#3150] opened 2018-03-14 21:45 UTC
Would be fine to add export result of queriy in wiki syntax to easy insert for example to JIRA. (https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all] and insert result to clipboard

**Comment by serge-rider** [comment] 2018-03-19 06:21
Duplicate of #3056

**Closed by serge-rider** 2018-03-19 06:21 UTC
Labels: duplicate, feature request, ts: m
