### ISSUE TITLE
mouse pointer disappears from screen after the execution of a multilne sql command with Ctrl-Intro

### ISSUE THREAD

**Issue by solisgb** [dbeaver/dbeaver#10431] opened 2020-11-19 08:53 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.2.5

#### Connection specification:
- Database name and version: postgres 11.10
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
 When I run a multiline sql command using Ctrl+Intro the mouse pointer disappears from the screen the first time I execute the command; I need to restore it (very easily) using the mouse; but if I repeat the execution of the same command the mouse pointer stay visible in the screen without any problem. 

Examples:
select t.col1 from tabla t order by t.col1; -- no problem

-- problem with mouse pointer visualization 
select t.col1 
from tabla t 
order by t.col1;

**Comment by jsteinfort** [comment] 2020-11-20 20:00
Occurs under Linux, as well.

Also occurs on a one line SQL statement.  When I place the cursor, perform a control-enter, the statement is executed but SOMETIMES the window loses focus.  No Editor or View appears to have focus at this point.

**Comment by jsteinfort** [comment] 2020-11-20 20:11
Hmm appears to be a duplicate of issue #10415.

**Comment by kseniiaguzeeva** [comment] 2020-11-25 11:10
You are correct. Should be fixed in 7.3.0.

**Closed by kseniiaguzeeva** 2020-11-25 11:10 UTC
Labels: bug, wait for review
