### ISSUE TITLE
dbeaver 6.1.3 failed to create java virtual machine

### ISSUE THREAD

**Issue by denis-GCP** [dbeaver/dbeaver#6331] opened 2019-07-23 14:45 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro ver 1803
- DBeaver version: 6.1.3
- Java version: SE RE 8.221
- Additional extensions: None

After downloading and running dBeaver windows installer for version 6.1.3, the new installation failed to start, with message "failed to create java virtual machine".

I uninstalled previous versions of DBeaver completely, uninstalled Java, re-installed dBeaver 6.1.3 and Java 8.122, rebooted system twice, with same result.

Re-installing dBeaver 6.0.5, my previous version, and it started perfectly without problems.  Although I note Oracle have changed Java licensing conditions recently, it obviously does not affect the older version and I guess may be irrelevant to this problem.

**Comment by serge-rider** [comment] 2019-08-06 13:50
Thanks for the bug report
Duplicate of #6331 (although it was created earlier).

**Closed by serge-rider** 2019-08-06 13:50 UTC
Labels: bug, duplicate
