### ISSUE TITLE
MySQL dump file corrupted since 24.2.0

### ISSUE THREAD

**Issue by WEGFan** [dbeaver/dbeaver#35425] opened 2024-09-02 10:23 UTC
### Description

I created a table with 500 lines, each line has 100 `a`s in one column, and 100 `1`s in another column.

![](https://github.com/user-attachments/assets/96e429ff-3f42-4ec9-a3a2-71beed95e723)

Then I used dump database with these settings.

![](https://github.com/user-attachments/assets/cc5fd27b-175c-4797-af06-9c28daec8512)

However the dump results are different each time I dump, and they are all corrupted sql files.

[dump.zip](https://github.com/user-attachments/files/16836108/dump.zip)

For example in `2.sql`, some parts got truncated

![](https://github.com/user-attachments/assets/013c44ba-188d-4e13-91e6-4cf36dd6df18)

### DBeaver Version

Community Editon 24.2.0

### Operating System

Windows 10

### Database and driver

- Database: MySQL 5.7.34
- Driver: MySQL Connector 8.0.29

**Comment by serge-rider** [comment] 2024-09-02 10:51
Seems to be duplicate of #35421

**Comment by Matvey16** [comment] 2024-09-02 11:07
@WEGFan Thank you for the report

**Comment by arhayka** [comment] 2024-09-02 12:11
Duplicate: https://github.com/dbeaver/dbeaver/issues/35421

**Closed as not planned by arhayka** 2024-09-02 12:11 UTC
Labels: x:mysql, xp:major, xf:native clients
