### ISSUE TITLE
No undo (Ctrl + Z) in function source code editor

### ISSUE THREAD

**Issue by fjf2002** [dbeaver/dbeaver#16184] opened 2022-04-13 17:23 UTC
#### System information: 
- Operating system (distribution) and version: Windoze 10
- DBeaver version: 22.0.1.202203181646

#### Connection specification:
- Database name and version: PostgreSQL 14
- Driver name: pgjdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
As the title says: When I am editing a function in its source code editor, CTRL-Z won't work.

**Comment by LonwoLonwo** [comment] 2022-04-18 16:01
Sorry @fjf2002 
I can't reproduce.

Do Ctrl+Z work in other places in your DBeaver?

![uEhyVFBZrA](https://user-images.githubusercontent.com/45152336/163836197-7d672046-ec3f-47c7-9777-8ea3368c4425.gif)

You can check your key bindings in the Preferences -> User Interface -> Keys

**Comment by fjf2002** [comment] 2022-04-19 11:12
Thanks your trying to reproduce. Now it works in my installation, too. Strange.

**Comment by LonwoLonwo** [comment] 2022-04-19 11:58
Some magic, maybe.

I'm closing this ticket.
Feel free to reopen it if the issue occurs again.

**Closed as completed by LonwoLonwo** 2022-04-19 11:58 UTC
Labels: x:postgresql, can't reproduce, xf:metadata

**Comment by fjf2002** [comment] 2022-05-03 12:03
The issue re-occurred to me. Please re-open.

The strange thing is, I cannot reproduce it. It suddenly occurred. Again.
I closed the source code editor and reopened it, and then Undo worked.

### Font problems
I noticed that when Undo wasn't working, the font also had problems.

Have you ever noticed? The font should look like this:
![image](https://user-images.githubusercontent.com/7130250/166449626-7d8ab403-22a4-45e2-bb6b-7be3a25ce1e6.png)

But sometimes the font switches in some GUI elements to this:
![image](https://user-images.githubusercontent.com/7130250/166449761-303381a0-7a6e-4230-a996-dfb1ac6a19c1.png)

### A relation between the font problems and Undo failing?
I notices that when the source code editor failed, the font of the bottom part of the window switched like described above.

As described, closing and re-opening the source code window solved the undo problem, and indeed the font looked normal again.

I do not know if this helps?

## .log file
The .log file has very many entries

> !ENTRY org.eclipse.e4.ui.workbench.renderers.swt 4 2 2022-05-03 14:06:07.431
> !MESSAGE Beim Aufrufen des Codes vom Plug-in sind Fehler aufgetreten: "org.eclipse.e4.ui.workbench.renderers.swt".
> !STACK 0
> java.lang.NullPointerException
