### ISSUE TITLE
[Amazon][JDBC](11220) Parameters cannot be used with normal Statement objects, use PreparedStatements instead.

### ISSUE THREAD

**Issue by GagandeepS** [dbeaver/dbeaver#6784] opened 2019-09-21 03:58 UTC
#### System information: 
- OS: Windows 10
- DBeaver version: 6.1.4.201908041900
- Additional extensions: None

#### Connection specification:
- Database name and version: Redshift
- Driver name: By default Redshift driver available in Dbeaver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: None

#### Issue:
Query containing '?' in the comments if giving the error that 'Parameters cannot be used with normal Statement objects, use PreparedStatements instead.' The error does not show up if you use the comment in the normal select query but when you have 'with' statement in it then it gives this error.

#### Query:
```
WITH filter_data as(
SELECT
    *
FROM
    table_name
    WHERE col_A >= '2019-07-20 00:00:00'
    and col_A <= '2019-07-21 00:00:00'
    -- dummy comment containing?
)
SELECT
    *
FROM
    filter_data limit 10
```

#### Steps to reproduce:
1. Create a with statement having a comment including '?' in it
2. Run the query

#### warning/errors/backtraces from the logs

> org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [11220] [HY000]: [Amazon][JDBC](11220) Parameters cannot be used with normal Statement objects, use PreparedStatements instead.
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2776)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3271)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: java.sql.SQLException: [Amazon][JDBC](11220) Parameters cannot be used with normal Statement objects, use PreparedStatements instead.
> 	at com.amazon.exceptions.ExceptionConverter.toSQLException(Unknown Source)
> 	at com.amazon.jdbc.common.SStatement.executeNoParams(Unknown Source)
> 	at com.amazon.jdbc.common.SStatement.execute(Unknown Source)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
> 	... 12 more
>

**Comment by uslss** [comment] 2020-06-02 22:41
hi @GagandeepS ,
sorry for the late response.
Cannot reproduce an issue for now, is it still actual for you?
![image](https://user-images.githubusercontent.com/31996417/83576837-553dfa00-a53b-11ea-9074-6f1074eadcc7.png)

**Comment by Azizimj** [comment] 2020-06-05 21:51
It can also happen if you have --? or -- ? anywhere in your script, even in the comments.

**Comment by Marcusln** [comment] 2020-06-26 01:03
Must be a Redshift bug, this also happens on AWS QuickSight.

**Comment by jdefontes** [comment] 2020-07-30 13:42
I can reproduce with this:

```
select
    * -- one? or two? two
from
    svv_table_info;
```

Looks like two ? on the same line triggers it.

**Comment by jdefontes** [comment] 2020-07-30 13:54
More detail... I ran into this issue by introducing a regex with question marks `regexp_replace(url, '^([^/\\?]+)([/\\?]+.*)?', '\\1')` into a complex query which included a bunch of comments. Removing all comments from the query solved the problem for me.

**Comment by rajrao** [comment] 2020-08-24 23:47
Happened to us on a comment that looked like this
--     1.0     2018-??-??  
This seems to have started happening sometime in June or July of this year (possibly)

**Comment by serge-rider** [comment] 2020-09-11 08:47
It seems to be a Redshift driver bug.

Hopefully it will be fixed in the next version of Redshift JDBC driver. Unfortunately we can't fix it from dbeaver side.

**Closed** 2020-09-11 08:48 UTC
Labels: bug, won't fix, x:redshift

**Comment by mferri17** [comment] 2022-01-04 11:11
Not sure it's the right place here, but the same error happens in Tableau when connected to Qubole Presto:
`[Qubole][JDBC](11220) Parameters cannot be used with normal Statement objects, use PreparedStatements instead.`

For me, it happened due to a regex containing "?". Even after removing the comments, the error was present. The only way to solve it was changing the regex to avoid using "?".
