### ISSUE TITLE
MS SQLServer 2000 issue with DBeaver 4.3

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#2806] opened 2018-01-18 08:57 UTC
Hi,

I'm connecting to a SQLServer 2000 database under Linux with DBeaver, using JTDS driver 1.3.1.
The connection is OK, but since DBeaver 4.3, I can't navigate throw schemas. I always get the following error:
![image](https://user-images.githubusercontent.com/12892581/35088892-81537450-fc35-11e7-8e85-49d0f5384639.png)

But this used to work in DBeaver 4.2.6 (that I have reinstalled to test), with the same JTDS driver version and same connection parameters:
![image](https://user-images.githubusercontent.com/12892581/35088937-a69d384a-fc35-11e7-9cc3-65496855f4f4.png)

Some more informations about my configuration:
eclipse.buildId=unknown
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en
Command-line arguments:  -os linux -ws gtk -arch x86_64

And the error stack trace:
2018-01-18 09:53:14.634 - org.jkiss.dbeaver.DBException: SQL Error [208] [S0002]: 'Archaeodendro.sys.sysusers' : nom d'objet incorrect.
org.jkiss.dbeaver.DBException: SQL Error [208] [S0002]: 'Archaeodendro.sys.sysusers' : nom d'objet incorrect.
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerMetaModel.loadSchemas(SQLServerMetaModel.java:239)
	at org.jkiss.dbeaver.ext.generic.model.GenericCatalog.getSchemas(GenericCatalog.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:798)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:484)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:408)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:199)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:576)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.sql.SQLException: 'Archaeodendro.sys.sysusers' : nom d'objet incorrect.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQLQuery(JtdsStatement.java:505)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.executeQuery(JtdsPreparedStatement.java:1029)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:230)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerMetaModel.loadSchemas(SQLServerMetaModel.java:219)
	... 17 more

Thanks in advance for your help.
Regards,
Cedric

**Comment by serge-rider** [comment] 2018-01-18 11:53
Duplicate of #2750
You can get EA version to check the fix.

**Comment by fedelepiz** [comment] 2018-01-22 15:23
New version downloaded but the error is the same.
version 4.3.3

**Comment by serge-rider** [comment] 2018-01-22 15:47
Unfortunately we didn't test with SQL Server 2000.
SQL Server 2005 is the earliest version. Moreover schema reading algorithm differs for 2000 and 2005+..

**Comment by serge-rider** [comment] 2018-01-31 00:35
Could you test the fix in EA version?

**Comment by ced75** [comment] 2018-02-01 08:32
Hi,
I've tested. The error message doesn't appear anymore.
However, there still remains a problem when trying to display the source code of a procedure by clicking on the "source" tab. I get the following message:

/* ERROR WHILE READING SOURCE:
SQL Error [2812] [37000]: Impossible to find the procedure 'OFF.sys.sp_helptext'.
*/

**Comment by fedelepiz** [comment] 2018-02-01 23:42
Hello,
i try the EA version and my problem is repared.
i dont' try your error with procedure for now, so i will check later this
error.
thanks
fedele

2018-02-01 9:32 GMT+01:00 ced75 <notifications@github.com>:

**Comment by serge-rider** [comment] 2018-02-02 19:57
Could you try it one more time?
All metadata reading functions were redone.

**Closed** 2018-02-03 04:14 UTC
Labels: bug

**Comment by serge-rider** [comment] 2018-11-28 18:37
@renezito Please provide a bitt moe info. 
What exactly problem exists in 5.2.5?

(workaround: use SQL Server (Legacy) driver in 5.2.5 - it works just like on 5.2.4 and earlier)
