### ISSUE TITLE
Escape apostrophe / single quote with backslash no longer works

### ISSUE THREAD

**Issue by johamm** [dbeaver/dbeaver#16064] opened 2022-04-04 10:03 UTC
I updated to the latest version of DBeaver this morning (Version 22.0.2.202204021640) and since anything that I'm attempting to select from a database with an apostrophe is no longer working when I escape with a backslash.

For example:

`select * from table1 where field1 = 'Jo\'s escaped string';`

I know I can just change my enclosures to be double quotes and remove the backslash or even use two apostrophes instead of one but sometimes my code is copied from my scripts and it's a hassle to change them over when adding into DBeaver when a backslash should work ok.

Is there any way I can put this escape method back in?

My setup:
- Operating system: Windows 11
- DBeaver version: 22.0.2.202204021640
- Database type: MariaDB (no SSH)

**Comment by E1izabeth** [comment] 2022-04-05 08:27
Hi, @johamm! Thank you for bug report. Unfortunately, I can't reproduce it for now. Was the connection established when it happened?

**Comment by johamm** [comment] 2022-04-05 08:31
The connection was established as I could run other queries fine.  However. this is very odd... I've tried it again today (after the program was closed and my machine has since restarted) and it seems to work now!!!

**Comment by E1izabeth** [comment] 2022-04-05 08:38
Thank you for the reply. I'll close this issue. Please, feel free to reopen it if this happens again.

**Closed as completed by E1izabeth** 2022-04-05 08:38 UTC
Labels: can't reproduce
