### ISSUE TITLE
Edit Actions Error

### ISSUE THREAD

**Issue by KevinWellsMLC** [dbeaver/dbeaver#12066] opened 2021-04-09 15:14 UTC
I’m attempting to add “Edit Actions” to my toolbar via Custom Perspective. However; I get an error message ( see attached ).

How can I get around / resolve this error?

System information:
Windows Server 2019 Standard
DBeaver Version 21.0.1.202103211229

Connection specification:
Database: Snowflake 

![Edit_Action_error](https://user-images.githubusercontent.com/75385195/114201046-6d309800-991b-11eb-929e-22b4baf94446.png)

**Comment by uslss** [comment] 2021-04-18 18:31
closed as a duplicate of #10692
anyway, thanks for the report

**Closed as completed by uslss** 2021-04-18 18:31 UTC
Labels: duplicate

**Comment by KevinWellsMLC** [comment] 2021-04-19 16:02
Not sure why this is considered a duplicate of  #10692.    #10692 was for DBeaver 7.2.4
This is for DBeaver Version 21.0.1.202103211229  ... a much more current version.  What is the fix then?
