### ISSUE TITLE
Dbeaver oracle dbms output  does not work

### ISSUE THREAD

**Issue by AlexuLag** [dbeaver/dbeaver#21969] opened 2023-11-23 13:44 UTC
### Description

when we use dbms output in oracle, it does not show the output in output window

### DBeaver Version

23.2.5.202311191730

### Operating System

windows

### Database and driver

Oracle 19
oracle.jdbc.OracleDriver

### Steps to reproduce

1 connect to database
2 on the editor put 
begin
DBMS_OUTPUT.PUT_LINE('BEGIN');
END;

3 run sentence
4 see output window

**Comment by E1izabeth** [comment] 2023-11-23 14:07
Thank you for bug report. It's a duplicate of #21902

**Closed as not planned by E1izabeth** 2023-11-23 14:07 UTC
Labels: xf:sql execution
