### ISSUE TITLE
Resizing toolbar icon size doesn't persists after program update

### ISSUE THREAD

**Issue by DavidHJong** [dbeaver/dbeaver#34951] opened 2024-07-23 07:07 UTC
### Description

According to [this report](https://github.com/dbeaver/dbeaver/issues/20704), . we can manually adjust toolbar icon size by adding 
to dbeaver.ini these commands: 
```
-Dswt.enable.autoScale=true
-Dswt.autoScale=200
-Dswt.autoScale.method=nearest
```
But each time I update the program, these commands are removed automatically. 

### DBeaver Version

24.1.3

### Operating System

windows 10

### Steps to reproduce

1. Open the dbeaver.ini
2. add to the bottom of the file 
```
-Dswt.enable.autoScale=true
-Dswt.autoScale=200
-Dswt.autoScale.method=nearest
```
3. the dbeaver toolbar icon size should be larger.
4. update the software
5. the dbeaver toolbar icon size is reset.

**Comment by Destrolaric** [comment] 2024-07-25 13:41
@DavidHJong Hi, unfortunately, DBeaver rewrites the dbeaver.ini file during the update to avoid any possible issues with version conflicts; you can try to create a shortcut to the .exe file with the required arguments.

**Comment by DavidHJong** [comment] 2024-07-27 02:48
@Destrolaric Thank you for your response. 

Is there a way to integrate this feature into the program, allowing users to choose the zoom level with a button/dropdown list?

**Comment by E1izabeth** [comment] 2024-08-11 18:55
Thank you for the issue.
I'm closing it as it's a duplicate of #21806
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-08-11 18:55 UTC
Labels: duplicate, xf:ui
