### ISSUE TITLE
editing view, basic text operation issue 

### ISSUE THREAD

**Issue by hismayilov** [dbeaver/dbeaver#8927] opened 2020-06-09 08:30 UTC
#### System information: 
- Operating system (distribution) and version : Win 10
- DBeaver version : DBeaver IDE	7.0.0.202003081811	
- Additional extensions : 

#### Connection specification:
- Database name and version : SQL Server
- Driver name  : Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
In view editor basic editing functionalities are not working. ctr+f for find ctr+z to undone is not working.  
#### Steps to reproduce, if exist:
Open any view and at simple text then press ctr+z or ctr+f to find. 
Also from edit menu it is not not working.

**Comment by kseniiaguzeeva** [comment] 2020-06-09 10:19
Cannot reproduce in 7.1.0 version.
![Rj4Hv7B6ZU](https://user-images.githubusercontent.com/51405061/84136201-a4ac8a80-aa53-11ea-8496-2db7e42ada14.gif)

Please check whether these hotkeys are applied (Window>Preferences>General>Keys).
If they are applied, could you check 7.1.0 release https://dbeaver.io/download/?

**Comment by hismayilov** [comment] 2020-06-09 11:31
Go to Properties tab and Definition section,  where it is written Create View****** 
there it is not possible to undo or delete but backspace is working :) in edit menu undo is grayed out, and not it is working. Sometimes it is not working.

**Comment by kseniiaguzeeva** [comment] 2020-06-09 12:10
Also cannot reproduce.. Is it possible to try 7.1.0?

**Comment by uslss** [comment] 2020-06-26 14:28
Ctrl+F still doesn't work. Ctrl+Z works ok for me.

**Comment by serge-rider** [comment] 2020-07-24 09:02
I can't reproduce this. Probably there are some prequesites.
@hismayilov should I do some actions before view edit?.

**Comment by hismayilov** [comment] 2020-07-24 09:10
> I can't reproduce this. Probably there are some prequesites.
> @hismayilov should I do some actions before view edit?.

This happens while editing views. 
Just in the middle of work undo, or delete button not working, so I have to delete with backspace. 
regularly I see this issue, but it is hard to find pattern to regenerate it. 
Also The Darkest Theme installed.
Installation details.
![image](https://user-images.githubusercontent.com/676555/88376614-6f12f500-cda6-11ea-9e22-8971ff45e5b1.png)

**Comment by serge-rider** [comment] 2020-07-24 15:30
There was a fix in #8887 . It resolved keybinding context activation and it was included in 7.1.2 version.
@hismayilov Could you test it in the latest version?

**Comment by serge-rider** [comment] 2020-07-25 09:32
Fixed in #9191

**Comment by uslss** [comment] 2020-07-27 12:07
verified

**Closed by uslss** 2020-07-27 12:07 UTC
Labels: bug

**Comment by hismayilov** [comment] 2020-07-29 10:35
> There was a fix in #8887 . It resolved keybinding context activation and it was included in 7.1.2 version.
> @hismayilov Could you test it in the latest version?

last days I don`t see this issue. it seems OK now. thanks.

**Comment by hismayilov** [comment] 2020-07-30 13:15
Same issue.

![image](https://user-images.githubusercontent.com/676555/88927202-c241e780-d27f-11ea-823d-4b4f6895ecff.png)
![image](https://user-images.githubusercontent.com/676555/88927300-e43b6a00-d27f-11ea-9f4e-cfce4eda0d3e.png)

**Comment by hismayilov** [comment] 2020-08-17 11:39
Sale issue continues. 
I realized that after opening view and wait for a while such as 30 min, then it starts making mentioned issue. 
as a workaround close view then open it again, works
