### ISSUE TITLE
Editing long CLOBs glitch

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#3692] opened 2018-06-27 05:52 UTC
In 5.1.1, editing long CLOBs (and by long I mean that in results panel they display as [CLOB] instead of actual text) in text mode. I need to switch to binary mode.

Steps to reproduce and workaround:

1. Open value editor for a CLOB cell which displays [CLOB] in results view
2. Edit content
3. Value editor changes; however, changes are not scheduled to be applied to db (i.e. the cell doesn't become orange in the results view and save/cancel/script buttons stay disabled)
4. "Apply cell value" button on the top of value editor has no effect either
5. Now workaround: switch to binary mode and edit content from there
6. Switch back to text mode
7. Editing now works from text mode too and gets applied!

**Comment by serge-rider** [comment] 2018-06-30 18:36
I think this was fixed in https://github.com/dbeaver/dbeaver/commit/dcae91fbfc9f63f296be5b48bab6aae4c92e5160

Please check in 5.1.2

**Closed by serge-rider** 2018-06-30 18:36 UTC
Labels: bug

**Comment by p91paul** [comment] 2018-07-02 06:58
Just reproduced it in 5.1.2, same steps as above.

**Comment by serge-rider** [comment] 2018-08-25 11:54
One more fix committed.
On my side CLOB editing looks like this:
![clob-editor](https://user-images.githubusercontent.com/6398845/44618012-bf117600-a876-11e8-8845-c1aefe961771.gif)

**Comment by serge-rider** [comment] 2018-08-26 13:03
It works the same way with long LOBs.
But there is another issue with really long LOBs (#4081).

**Comment by creage** [comment] 2018-08-28 10:14
@serge-rider for me it looks like this
![clob](https://user-images.githubusercontent.com/910967/44716791-975f1f80-aabb-11e8-8429-1f1a6e1eed71.gif)

CLOB size is 683KB (about 700000 chars)

**Comment by serge-rider** [comment] 2018-08-28 20:40
Thanks for details, now I can reproduce it.
