### ISSUE TITLE
SQL Editor: can't use right-click menu to copy selected text

### ISSUE THREAD

**Issue by hlampert** [dbeaver/dbeaver#18200] opened 2022-11-11 16:08 UTC
### Description

the right-click context menu no longer allows you to copy selected text.    Steps to reproduce:

1.  In the SQL editor, type any text and select it with the mouse.
2. right click.  The selected text becomes unselected and the copy option is greyed out on the context menu.

Expected behaviour:  selected text remains highlighted and copy option is available to copy the text.

### DBeaver Version

Community Edition Version 22.2.4.202211061524

### Operating System

Windows 10

### Database and driver

PostgreSQL 12

**Comment by E1izabeth** [comment] 2022-11-11 20:40
Thank you for bug report. It's a duplicate of #18152
Fix will be available in the next release.

**Closed as not planned by E1izabeth** 2022-11-11 20:40 UTC
Labels: duplicate
