### ISSUE TITLE
Copied SQL code does have (unwanted) extra line spacing since v22.3.1 

### ISSUE THREAD

**Issue by btanner2** [dbeaver/dbeaver#20033] opened 2023-05-22 08:02 UTC
### Description

Copy (formatted) SQL code out of SQL Editor in DBeaver und paste it directly into Outlook or Word worked perfectly until **v22.3.0**. Unfortunately, with **v22.3.1** and all later versions there was a change, which bloats the code enormously. Please take a look into attachments for the same SQL Code copied with both versions. With 22.3.1 there was added some kind of extra line spacing. This is really annoying. Could you please fix this? Or make it at least adjustable? If there is already an option, I would be very happy if you could give me a hint here, I have not found it.

Thanks Brian

**v22.3.0**
![v22 3 0](https://github.com/dbeaver/dbeaver/assets/36444364/f84c6f31-681f-4ea7-9247-c573f8d9477c)

**v22.3.1**
![v22 3 1](https://github.com/dbeaver/dbeaver/assets/36444364/85ff53ba-9e1e-4c0c-a04d-674f677d026a)

### DBeaver Version

23.0.5

**Comment by E1izabeth** [comment] 2023-05-24 18:44
Probably, connected with #18723

**Comment by E1izabeth** [comment] 2023-05-24 18:46
Thank you for bug report.
I'm closing this issue as a duplicate of #18723

**Closed as not planned by E1izabeth** 2023-05-24 18:46 UTC
Labels: duplicate, xf:sql editor
