### ISSUE TITLE
No autocomplete to Postgres db

### ISSUE THREAD

**Issue by warenix** [dbeaver/dbeaver#3929] opened 2018-08-06 03:10 UTC
I downgrade from 5.1.4/ 5.1.3 to 5.1.2 in order to have autocomplete of tables and columns names working. Newer version just have many problem on using postgres db. Autocomplete is the most annoying regression I've seen so far. Can you please look into it?

## Env
Version: 5.1.4, 5.1.3
OS: Ubuntu 18.04
DB connection: postgresql 9.4.11
JDBC driver: postgresql-42.2.4.jre7.jar

**Comment by serge-rider** [comment] 2018-08-06 06:44
Duplicate of #3911.
Please check EA version, it includes most of fixes.

**Comment by serge-rider** [comment] 2018-08-06 06:45
https://dbeaver.io/files/ea

**Closed by serge-rider** 2018-08-06 06:44 UTC
Labels: bug, duplicate, x:postgresql
