### ISSUE TITLE
DBeaver 24.2.4 Auto complete / Suggestion for table columns not showin

### ISSUE THREAD

**Issue by mmorehouse6** [dbeaver/dbeaver#36196] opened 2024-11-07 18:20 UTC
### Description

Coming from community version 23.3.1, when I begin to type in my query, the table names will autocomplete/recommend, however the table column names are not suggesting like they use to.
![image](https://github.com/user-attachments/assets/ae14f681-b3f0-4c21-86de-faccc6da8355)

### DBeaver Version

Community Edition 24.2.4

### Operating System

Windows 11

**Comment by E1izabeth** [comment] 2024-11-12 12:44
Hi, @mmorehouse6 ! Thanks for creating the bug report. For now we're unable to reproduce the issue. Could you provide clear steps to reproduce your issue or record a short video showing how it happens for you?

**Comment by E1izabeth** [comment] 2024-12-11 17:21
Unfortunately, we have not been able to reproduce the reported behavior. Therefore, I am closing this issue. If the issue is still actual, please provide more information regarding it.

**Closed as not planned by E1izabeth** 2024-12-11 17:21 UTC
Labels: wait for response, xf:sql autocompletion
