### ISSUE TITLE
Output tab switches every time a script is executed.

### ISSUE THREAD

**Issue by 18549** [dbeaver/dbeaver#7737] opened 2020-01-24 12:45 UTC
#### System information: 
- Operating system (distribution) and version: Win 10 
- DBeaver version: 6.3.3.202001191557
- Additional extensions: None

#### Connection specification:
- Database name and version: SQL Server Express
- Driver name: No idea
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:

Every time I run a database query the output pane switches to the 'Statistics' tab, which is where the results are displayed.

If I don't have a result pane open this is reasonable, but if I already have a result pane, and I've already selected the 'Output' or 'Execution Log' tab, then stop switching to the 'Statistics' tab every time I run a query.

When I'm testing the development of a script and I'm checking the logs to see how the script is performing to have DBeaver constantly switching to the 'Statistics' view when the script isn't even returning any data is infuriating.

I also don't know why the tab that displays the data returned by a query is called 'Statistics', there isn't any statistical information there, it's just data. This tab would be better called 'Data' or 'Results'.

**Comment by uslss** [comment] 2020-01-27 18:23
seems to be duplicate of #7704 .
anyway, thanks for the bug report

**Closed by uslss** 2020-01-27 18:23 UTC
Labels: bug

**Comment by 18549** [comment] 2020-01-28 09:26
Sorry, I did search, didn't spot it.
