### ISSUE TITLE
context menu for foreign table View reads: View %tree.foreignTable.node.name

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#21440] opened 2023-10-05 14:02 UTC
### Description

When looking at the context menu for the new Foreign Tables folder, instead of showing:

View Foreign Table

it instead displays:

View %tree.foreignTable.node.name

![foreign_table_context_tab_error_20231005_095904](https://github.com/dbeaver/dbeaver/assets/3697063/a7b41bca-9db5-46d4-b9a4-8e53869962b3)

### DBeaver Version

Community Edition 23.2.1

### Operating System

Windows 10

### Database and driver

PostgreSQL

**Comment by E1izabeth** [comment] 2023-10-05 14:08
Thank you for bug report. This is a duplicate of #21426
The fix will be available in the next release.

**Closed as not planned by E1izabeth** 2023-10-05 14:08 UTC
Labels: duplicate
