### ISSUE TITLE
Use eclipse Web Browser preference

### ISSUE THREAD

**Issue by juminda-suurekoerve** [dbeaver/dbeaver#17520] opened 2022-09-01 05:45 UTC
### Description

We upgraded DBeaver (22.1.0 to 22.1.5) on a Windows virtual machine. All other users were disconnected, but one hadn't closed DBeaver. Installation stopped ("cannot write to...") and after canceling this, DBeaver does not start anymore, pointing to the log file quoted below.

Is there any chance, we can fix (and keep settings, connections etc.) this or do we need a full new install?
Thanks!

 > !SESSION 2022-09-01 05:07:02.551 -----------------------------------------------
> eclipse.buildId=unknown
> java.version=11.0.12
> java.vendor=Azul Systems, Inc.
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> !ENTRY org.eclipse.osgi 4 0 2022-09-01 05:07:03.519
> !MESSAGE Application error
> !STACK 1
> java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

### DBeaver Version

CE 22.1.0

**Comment by juminda-suurekoerve** [comment] 2022-09-01 15:16
We were able to just run the installer again and it looked to be working fine. But switching the data view from grid or text to spatial does not work anymore: 
> Can't switch presentation
> Reason:
> Not implemented [WebView2 runtime not found]

Also wouldn't it be a good idea to check for open files / write protections before starting the installation and to then possibly stop the process?

**Comment by iraidaa** [comment] 2022-09-02 14:59
Hello @juminda-suurekoerve,

I guess you did the right thing by reinstalling DBeaver.

Now could you try to reset the workspace manually following the second part of the instruction: https://github.com/dbeaver/dbeaver/wiki/Reset-workspace?

**Comment by E1izabeth** [comment] 2022-09-03 13:50
Workspace reset will not help. It's a bug which was fixed in 22.2.0 (#17332).
@juminda-suurekoerve please update your DBeaver version to 22.2.0. Let me know if the issue is still exists after update.

**Comment by juminda-suurekoerve** [comment] 2022-09-05 08:41
Thanks @E1izabeth & @iraidaa. 

The issue still exists in 22.2.0:
> Can't switch presentation
> Reason:
> Not implemented [WebView2 runtime not found]

I did not reset the workspace, yet - should I try that now?

**Comment by Destrolaric** [comment] 2022-09-05 08:58
@juminda-suurekoerve, hi, could you try to switch the active web browser via preferences manually `User Interface -> Web Engine`? Switch it to Internet Explorer. Also, can you tell me your Windows version? 
![image](https://user-images.githubusercontent.com/20579256/188410107-408880e9-a139-4ac6-873d-148ea208500b.png)

**Comment by juminda-suurekoerve** [comment] 2022-09-05 10:26
Thank you, @Destrolaric - this did work! 
My VM runs with Windows Server 2019 (version 1809).

Is that actually unrelated to our original problem (the interupted upgrade)?
Coming back to it: still wouldn't it be a good idea to check for open files / write protections before starting the installation and to then possibly stop the process?

**Comment by E1izabeth** [comment] 2022-09-06 21:27
We try to use default eclipse preference page with the available browsers auto detection which is already included into DBeaver.
There is available browsers detection mechanism which could tell us whether Edge is available on the client machine or not.

![image](https://user-images.githubusercontent.com/28875055/188742943-ae8e4076-f1d7-4d38-8711-bd19887c88f9.png)

**Comment by E1izabeth** [comment] 2022-09-08 14:15
On some Windows 10 client machines users experience the same [issue with WebView2 runtime not found](https://github.com/dbeaver/dbeaver/issues/17597), and [this one](https://github.com/dbeaver/dbeaver/issues/17332#issuecomment-1240779511).

**Comment by E1izabeth** [comment] 2022-10-20 11:16
Sometimes we have `Not implemented [WebView2 runtime not found]` error which our users encounter even on Windows 10 with Edge. We handle this situation, but it leads to `No editor for [geometry]` message in value panel (#17746, #17983). We need to fallback to IE usage if Edge cannot be used as a web engine.

**Closed as completed** 2022-11-16 12:32 UTC
Labels: xp:major, xf:gis, sp:3
