### ISSUE TITLE
Collapse/expand big sql statements

### ISSUE THREAD

**Issue by avo15** [dbeaver/dbeaver#9527] opened 2020-08-13 21:03 UTC
I use DBeaver to write big statements and often need to collapse/hide some executed statements 
This feature will save a bunch of time scrolling between statements in Editor and help
to avoid mistakes changing already tested and executed statements.
Jumping between multiple tabs is an option but it is not as convenient as proposed enhancement
Thanks
Alex

**Comment by kseniiaguzeeva** [comment] 2020-08-14 10:23
Thank you for the report. This feature is already implemented, but needs revision (that's why it is disabled by default). To enable it go to:
Preferences>SQL Editor>Folding enabled (it works for global settings now)
![dbeaver_p738UPjd2r](https://user-images.githubusercontent.com/51405061/90239878-f21ced80-de30-11ea-9604-369386442ea4.png)
The ticket is closed as duplicate of #4108 and #2156

**Closed by kseniiaguzeeva** 2020-08-14 10:23 UTC
Labels: duplicate, enhancement
