### ISSUE TITLE
Compare Metadata and Generate Synchronization Script

### ISSUE THREAD

**Issue by Magnele** [dbeaver/dbeaver#2991] opened 2018-02-17 09:50 UTC
Hello, I am a very happy user with DBeaver. Congratulations to the developers for the great tool. I would like to have a feature to compare the structure between two databases and be able to automatically generate an update script from this comparison. Does this feature already exist? If yes, how to use it?

Note: Sorry for the spelling mistakes, I'm from Brazil ...

**Comment by serge-rider** [comment] 2018-02-24 20:49
Duplicate of #957

(we going to implements it in one of 5.x versions)

**Closed by serge-rider** 2018-02-24 20:49 UTC
Labels: duplicate, feature request
