### ISSUE TITLE
Clickhouse - Error while loading table columns

### ISSUE THREAD

**Issue by bmartynov** [dbeaver/dbeaver#1959] opened 2017-08-03 06:18 UTC
OS: Debian buster/sid
WM: i3wm
Database: Clickhouse 1.1.54245

Driver: 
ClickHouse
ru.yandex.clickhouse:clickhouse-jdbc:RELEASE
maven:/ru.yandex.clickhouse:clickhouse-jdbc:RELEASE
0.1.25

Error:
SQL Error [47]: ClickHouse exception, code: 47, host: <сut_out>, port: 8123; Code: 47, e.displayText() = DB::Exception: Unknown identifier: default_type, e.what() = DB::Exception

How to reproduce:
Open database -> open table -> open columns.

**Comment by serge-rider** [comment] 2017-08-03 18:06
Please post full error stacktrace (you can get it in Error Log view).

You could try to use different driver version (in Driver Editor->Download/Update->click on version column).

**Comment by bmartynov** [comment] 2017-08-04 05:53
Full stacktrace:
java.lang.Throwable: Code: 47, e.displayText() = DB::Exception: Unknown identifier: default_type, e.what() = DB::Exception

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:512)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:101)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:85)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:81)
	at ru.yandex.clickhouse.ClickHouseDatabaseMetadata.request(ClickHouseDatabaseMetadata.java:621)
	at ru.yandex.clickhouse.ClickHouseDatabaseMetadata.getColumns(ClickHouseDatabaseMetadata.java:797)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getColumns(JDBCDatabaseMetaDataImpl.java:1155)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:129)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:220)
	at org.jkiss.dbeaver.ext.generic.model.GenericTable.getAttributes(GenericTable.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:793)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:479)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:403)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:190)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:563)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Ok, i try another version.

**Comment by bmartynov** [comment] 2017-08-04 06:38
I tried other(older) versions of the drivers - same error.

**Comment by bmartynov** [comment] 2017-08-08 07:08
Any updates?

**Comment by serge-rider** [comment] 2017-08-08 08:11
Not yet. Seems to be a bug in clickhouse JDBC driver. Probably it makes sense to crate bug report in their issue tracker (https://github.com/yandex/clickhouse-jdbc)

**Comment by tati-kru** [comment] 2018-01-18 14:42
Hi @bmartynov! 
Could you, please, check that it can be reproduced or not on the latest version?

**Comment by serge-rider** [comment] 2018-01-29 02:11
Closing as non-reproducible

**Closed by serge-rider** 2018-01-29 02:11 UTC
Labels: can't reproduce, question

**Comment by ws-perelyaynen** [comment] 2019-10-23 10:28
problem was resolved after restart. macos 10.14

**Comment by igor-elbert** [comment] 2021-05-31 20:07
Same problem with Version 21.1.0.202105300349 on MacOS 11.3.1:

SQL Error [47]: ClickHouse exception, code: 47, host: 10.205.0.23, port: 8123; Code: 47, e.displayText() = DB::Exception: Unknown identifier: comment, e.what() = DB::Exception

  ClickHouse exception, code: 47, host: 10.205.0.23, port: 8123; Code: 47, e.displayText() = DB::Exception: Unknown identifier: comment, e.what() = DB::Exception

  ClickHouse exception, code: 47, host: 10.205.0.23, port: 8123; Code: 47, e.displayText() = DB::Exception: Unknown identifier: comment, e.what() = DB::Exception

    java.lang.Throwable: Code: 47, e.displayText() = DB::Exception: Unknown identifier: comment, e.what() = DB::Exception

    Code: 47, e.displayText() = DB::Exception: Unknown identifier: comment, e.what() = DB::Exception

**Comment by serge-rider** [comment] 2021-06-01 08:34
@igor-elbert What Clickhouse server version do you have? And \what driver version?
You cna get this info on Test Connection dialog.

**Comment by TXYH1** [comment] 2021-07-11 07:34
I have a similar error when loading table columns. The error message is as follows.  
`Code: 47, e.displayText() = DB::Exception: Unknown identifier: comment, e.what() = DB::Exception`

When I changed the jdbc driver to 0.1.55, it was fixed
