### ISSUE TITLE
Open Database Object krash if asked to select object when focus is not in the Database Navigator

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3786] opened 2018-07-11 08:47 UTC
DBeaver - **Version 5.1.2 CE**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

If one try to use the **Open Database Object** / _Ctrl+Shift+D_ command while the focus is not in the **Database Navigator** an exception message is shown:

> An internal error occurred during: "Items filtering". 
> java.lang.NullPointerException

**Contents in the _.log_ file:**

> !ENTRY org.eclipse.core.jobs 4 2 2018-07-11 10:26:51.356
> !MESSAGE An internal error occurred during: "Items filtering".
> !STACK 0
> java.lang.NullPointerException
> 	at org.jkiss.dbeaver.ui.dialogs.GotoObjectDialog.fillContentProvider(GotoObjectDialog.java:132)
> 	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2050)
> 	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:1998)
> 	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:1970)
> 	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:1957)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**To repeat the faulty behaviour:**

**o** Start _DBeaver_ and connect to a database (in my case Northwind).
**o** Click on your choosen database in the **Database Navigator** tree.
**o** Press the **Ctrl+Shift+D** and choose a table (in my case **Customers**).
**o** The table data is shown on the right - **OK**
**o** Click on the data tab **Data** to view the table data grid.
**o** Press the **Ctrl+Shift+D** and choose a new table (in my case **Orders**).
**o** As soon as I start to type the first letter in the new table name, the **ERROR** message are shown.

**Comment by serge-rider** [comment] 2018-07-11 08:57
Duplicate of #3727

**Closed by serge-rider** 2018-07-11 08:57 UTC
Labels: bug, duplicate
