### ISSUE TITLE
SAP HANA semicolon at the end  of line (Updated Rows -1)

### ISSUE THREAD

**Issue by mradeschnig** [dbeaver/dbeaver#16135] opened 2022-04-09 09:54 UTC
#### System information: 
- Operating system (distribution) and version  Windows 10 
- DBeaver version   dbeaver 22.0.2
- Additional extensions all dbeaver extensions installed

#### Connection specification:
- Database name and version  SAP HANA 2.0 SP3
- Driver name                            2.12.7
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:

If I have a semicolon at the next line after the select statement I
get the result shown:

SELECT * FROM DUMMY
;

![grafik](https://user-images.githubusercontent.com/1084030/162566845-99bfba93-63dc-44f2-b61f-475186f5c84f.png)

SELECT * FROM DUMMY;

![grafik](https://user-images.githubusercontent.com/1084030/162566805-c5d7b938-a01a-484b-b5af-37e01950d23a.png)

shows the expected result. If there are one or more empty line after statement and  semicolon it also works.

**Comment by E1izabeth** [comment] 2022-04-09 10:04
Thank you for bug report. Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/16077

**Closed as completed by E1izabeth** 2022-04-09 10:04 UTC
Labels: duplicate
