### ISSUE TITLE
[Vertica] Very slow to populate table lists and table data viewer

### ISSUE THREAD

**Issue by shearerp** [dbeaver/dbeaver#7834] opened 2020-02-04 21:28 UTC
#### System information: 
- OS X 10.13.6
- DBeaver 6.3.4.202002011957

#### Connection specification:
- Database name and version: Vertica 9.1
- Driver name: Vertica JDBC 9.3.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? I use a VPN

#### Describe the problem you're observing:

When I open a schema and click the table dropdown, it takes 30+ seconds to load the list of tables:
![image](https://user-images.githubusercontent.com/7192213/73787989-7a6f5700-4759-11ea-926e-69075eb7e948.png)

When I click on a table, the table viewer opens, but it shows a blank white space for 30+ seconds, then it finally says "getting table metadata..." and it shows the table data a couple seconds later.

Queries run in SQL scripts are not too slow, although metadata fetching (discover column attribute, discover owner attribute, etc) take a couple seconds longer than they used to.

SQL queries, including metadata queries, are fast in vsql, the command-line utility provided with Vertica.

#### Steps to reproduce, if exist:

Connect to a Vertica instance with DBeaver, open the table list dropdown, and see how long it takes to populate

**Comment by uslss** [comment] 2020-12-07 22:14
is it still actual for you against the recent version (7.3.0)?

**Comment by eTravelPartner** [comment] 2020-12-28 17:15
I have a similar problem. I use dbeaver 7.3.1 on ubuntu 18.4 and my database is on postgresql 10.x with about 2500 tables. It's fast to show my list of tables but when i double click on a table to see its details it hangs; the UI doesn't respond to any click and only after minutes it eventually shows the table details. Thanks in advance. Stefano

**Comment by eTravelPartner** [comment] 2020-12-28 17:31
i have to be more precise, if i'm (my dbeaver UI) in the tab DATA is fast in opening a table detail while if i'm in the tab PROPERTIES is superslow. May be the problems is linked to the number of tables (2500) in my databas, so i'd like to know if there is the feature to cache (and refresh) the database catalog when i enter in the database first time of the day. Regards. Stefano

**Comment by shearerpmm** [comment] 2020-12-29 22:47
Thanks so much for taking a look into this. It continues to be an issue for me. I am still on 7.2.5 and I will try a newer version in a bit, but I suspect the results will be the same. EDIT: confirmed, same issue in 7.3.1.

I'll give some more details, please let me know if I can do anything else to help you figure it out:

- The issue definitely has something to do with databases with very large numbers of schemas and/or tables, as in the data warehouse I'm working with.
- When I login using batch accounts that can only access a small subset of the schemas, the problem is not nearly as bad.
- It also helps to go into Preferences > Editors > Data Editor and uncheck "Read table metadata (unique keys)" and "Read table references (foreign keys)"

The impression from our Vertica admin is that the queries DBeaver uses to populate metadata may perhaps be more expensive than needed, since vsql is fast to do similar things. I would guess that the metadata query is being filtered for what is actually needed on the client side rather than the server side - thus, if the server-side metadata table is huge, the whole thing is transferred to the client, leading to long wait times.

**Comment by shearerpmm** [comment] 2020-12-30 19:57
Related issue - whenever I look at a table's data through the "Data" tab, it will spend 15 seconds on "Read data from container" before displaying the data. However, `select * from table` is instantaneous. None of the workarounds mentioned above have an effect on this.

**Comment by uslss** [comment] 2021-08-30 18:10
there is no update on issue for a long time.
If it is still actual for you - feel free to reopen it

**Closed by uslss** 2021-08-30 18:10 UTC
Labels: bug, can't reproduce, x:vertica

**Comment by hannahshachar** [comment] 2024-01-24 07:27
Everyone here has the same issue.  Nobody found any solution to this?

**Comment by tanguy29480** [comment] 2024-11-29 07:24
Yes, the same for me, even on a table with only 10 records ... Other tools do not encounter this problem.
