### ISSUE TITLE
Prevent auto upper casing of keywords in comments

### ISSUE THREAD

**Issue by jeffshumphreys** [dbeaver/dbeaver#32841] opened 2024-05-14 18:30 UTC
**Is your feature request related to a problem? Please describe.**
This is not a bug, just a limit to readability in commenting code. I heavily document code, so this makes me reluctant to comment SQL.
Here is an example of a line I commented:
``` sql
WHEN MATCHED AND NOT src.tgt_now_missing AND NOT src.src_is_new THEN -- Confusing, YES. It's NOT really MATCHED, since the "USING" IS bringing IN BOTH sides, past AND NEW.  So we've fake a MATCH USING the FULL JOIN, so we can deal WITH things LIKE deleted torrents IN NEW DATA, AND updating the CURRENT master WITH that status, keeping the history that these were deleted, FOR whatever reason.
```
The moment "YES" was upper-cased, I paused.  I didn't want to emphasize that word, which adds an implication that I couldn't guess at. I kept going to see how it continued.

I realized it only is doing it in single line comments, so that's an easy work-around.  I see that I can turn off the formatting, but ironically, keyword casing is part of self-documenting code.

Since multi-line comments prevent this auto-casing, I'm inclined to think this might be a bug, unless there's some reason single-line comments could still be code.

**Describe the solution you'd like**
Since multi-line comments don't auto-case, the best solution would be that single-line comments don't auto-case, either. No need for another preference option.

**Describe alternatives you've considered**
I'm converting the example line to multi-line format "/*".

**Additional context**
I can't think of any additional context.

Thank you

**Comment by E1izabeth** [comment] 2024-05-16 08:47
Thank you for the request.It's a duplicate of #20944
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-05-16 08:47 UTC
Labels: duplicate, xf:sql editor
