### ISSUE TITLE
Output Tab and  Execution Log no longer exists within the Results tab area.

### ISSUE THREAD

**Issue by tmbrye** [dbeaver/dbeaver#12794] opened 2021-06-09 15:50 UTC
I am definitely frustrated that the  execution log has now moved to  the right side of the script window.  A couple releases back it was down in the Results tab section.  It is much easier to view when it is horizontal because it holds many columns which  get completely cut off in the  small right window and you have  to expand it covering your script window.

My suggestion is to allow these tabs to be moveable and place it in either location making in user adjustable.

**Comment by uslss** [comment] 2021-06-10 08:55
thanks for the suggestion.
Seems to be the duplicate of #12534

**Closed as completed by uslss** 2021-06-10 08:55 UTC
Labels: duplicate
