### ISSUE TITLE
information window not closed

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#11059] opened 2021-01-20 10:25 UTC
DBeaver 7.3.3
Postgresql 12

Execute SELECT command in SQL Editor.  This command contained error "select * from sch.tytle;"   sch.tytle it is wrong name of table, correct name is sch.title.

Query executing for the long time and show this window
![изображение](https://user-images.githubusercontent.com/61137576/105161601-5c019780-5b33-11eb-8f12-19d2f92bdad1.png)

after i click on "No" "Нет" this window opens again and again until i click "Да" "Yes"

**Comment by p91paul** [comment] 2021-01-20 18:52
duplicate of https://github.com/dbeaver/dbeaver/issues/10101

**Comment by kseniiaguzeeva** [comment] 2021-01-25 07:54
Thank you for the report. Will be fixed in #10101

**Closed as completed by kseniiaguzeeva** 2021-01-25 07:54 UTC
Labels: duplicate
