### ISSUE TITLE
Code completion does not work for tables with names containing spaces

### ISSUE THREAD

**Issue by tkorach** [dbeaver/dbeaver#10619] opened 2020-12-05 23:43 UTC
#### System information: 
- Operating system (distribution) and version
Ubuntu 20.04, Amazon Linux 2
- DBeaver version
7.2.4
- Additional extensions
Git

#### Connection specification:
- Database name and version
Snowflake
- Driver name
Snowflake JDBC, Postgresql JDBC 42
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Code completion (using control+space) rarely works. Most of the time it shows a window "no proposals". This occurs both with and without an alias. Occurs more frequently with quoted table names. 

No errors appear in the error log. Not solved after refreshing the schema.

 
#### Steps to reproduce, if exist:

1. Connect to a Postgresql or Snowflake database. 
2. Create a script. 
3. Start writing a query: `Select t. from "<any table>" t`
4. Place the cursor after "t."
5. Press Control+Space

Expected behavior: a pop-up with column name, or an error message with the reason to absence of proposals. 
Current behavior: "no proposals" in the popup and no error messages. 

#### Include any warning/errors/backtraces from the logs
None

**Comment by kseniiaguzeeva** [comment] 2020-12-09 15:50
Thank you for the report. It is actual for non-default schemas.

**Comment by tkorach** [comment] 2020-12-10 14:34
@kseniiaguzeeva Is there an error log that shows the reason for the failure of a code completion request? I could not find any messages in the DBeaver's error log.

**Comment by kseniiaguzeeva** [comment] 2020-12-10 14:53
It wasn't necessary to look in the error log this time.

**Comment by tkorach** [comment] 2020-12-10 16:58
To clarify: The problem occurs both when using tables from the currently active schema and when using the qualified name for tables from non-default schema.

**Comment by LonwoLonwo** [comment] 2021-01-10 22:34
![2021-01-07 00_38_13-DBeaver Enterprise 7 3 0 - _SNOWFLAKE_SAMPLE_DATA_ Script-69](https://user-images.githubusercontent.com/45152336/104109875-42668180-52e3-11eb-8f63-045169414877.png)

![2021-01-07 00_39_28-](https://user-images.githubusercontent.com/45152336/104109878-4397ae80-52e3-11eb-8a84-9ce1ef394d18.png)

Can't reproduce with PostgreSQL and Snowflake. 
May be some non-default settings enabled?
![2021-01-10 02_10_04-Properties for Script-50 sql](https://user-images.githubusercontent.com/45152336/104110509-6a58e380-52e9-11eb-9578-0fa6eced79cd.png)

Does code completion work at all in SQLEditor?

**Comment by tkorach** [comment] 2021-01-11 03:59
The code completion seems to work better for tables whose names are not quoted (i.e. not having any illegal character, and therefore do not require surrounding with double quotes). For these it works some of the time.
For quoted tables, it almost never works. DBeaver can find the table (in the "from" clause) but cannot suggest column names. 

It used to work better. For unquoted tables it dropped from working roughly 50% to 20% of the time and for quoted tables it essentially stopped working. 

### Unquoted table: 
![image](https://user-images.githubusercontent.com/38960214/104145989-1efd0e80-5397-11eb-9ac8-0910bc2330ab.png)

### Quoted table:
![image](https://user-images.githubusercontent.com/38960214/104146061-5966ab80-5397-11eb-889c-8d098491f900.png)

### My settings: 
![image](https://user-images.githubusercontent.com/38960214/104146111-8915b380-5397-11eb-8f16-e9bd73885d42.png)

**Comment by LonwoLonwo** [comment] 2021-01-11 07:44
@tkorach The example helped, I was able to reproduce, thanks

**Comment by tkorach** [comment] 2021-01-13 01:17
Thanks. Will test once a new version is released.

**Comment by LonwoLonwo** [comment] 2021-01-14 07:14
So far, the task is not trivial. We are looking for the name of the table in query by alias using a regular expression that does not take into account spaces. Using a different regexp may result in longer auto-suggestion times. It might be worth using the SQLScriptParser. The problem will be solved when we find the optimal solution.

**Comment by tkorach** [comment] 2021-01-14 13:16
Thanks for the explanation. I am unfamiliar with this feature, so my suggestion might be irrelevant, but if the regular expression speed is a problem, [brics ](https://www.brics.dk/automaton/) is a DFA regex library with orders of magnitude (thousands of times ) faster performance than the stock Java one. 

It does limit the expressivity of the regex (e.g. no capturing groups) but if the regex can be written within its limits, it might be fast enough for this process. AFAIK the parser JFlex is based on this (or a similar) mechanism. 

Happy to contribute if helpful.

**Comment by ShadelessFox** [comment] 2021-04-05 12:05
Fixed in the scope of #10858. Fell free to comment here if you still have any questions left.

**Closed by ShadelessFox** 2021-04-05 12:05 UTC
Labels: bug, x:postgresql
