### ISSUE TITLE
Command-line switch to open DBeaver without auto connecting.

### ISSUE THREAD

**Issue by wattpuppy** [dbeaver/dbeaver#18818] opened 2023-01-19 23:01 UTC
When I open DBeaver and have tabs which were not closed previous, DBeaver will auto-connect to that db.  I would like to be able to launch DBeaver without connecting to anything and also have tab windows restored.  I've found the switches for -disconnectAll but appears to not work without -closetabs.

ver. 22.3.1.202212251901

**Comment by E1izabeth** [comment] 2023-01-20 17:59
There is a setting for SQL Editor. You can turn it off.
![image](https://user-images.githubusercontent.com/28875055/213773240-f4618d81-b1b7-4cd2-b01d-a89af2da5c8f.png)

**Comment by ShadelessFox** [comment] 2023-01-26 14:24
Duplicate of #18449

**Closed as not planned by ShadelessFox** 2023-01-26 14:24 UTC
Labels: duplicate
