### ISSUE TITLE
altibase table and column description not appear.

### ISSUE THREAD

**Issue by davidoff2500** [dbeaver/dbeaver#34890] opened 2024-07-18 13:02 UTC
### Description

we are using Altbase.

When double-clicking the table, it is uncomfortable that comments are not displayed in the table and column specification.

![제목 없음](https://github.com/user-attachments/assets/96a91cb8-4ab8-4d1e-930e-9a8d94f0f7e2)

### DBeaver Version

community 24.1.2

### Operating System

win 11

### Database and driver

altibase 6.5.1.9.9

**Comment by E1izabeth** [comment] 2024-07-18 13:11
Duplicate of #34891

**Closed as not planned by E1izabeth** 2024-07-18 13:11 UTC
Labels: duplicate, x:altibase
