### ISSUE TITLE
I hope dbeaver can be run on arm.

### ISSUE THREAD

**Issue by AliveGh0st** [dbeaver/dbeaver#9407] opened 2020-07-30 10:05 UTC
Eclipse 4.14 can already run perfectly on deepin arm machines, and hope to provide dbeaver arm build method or deb package.

**Comment by uslss** [comment] 2020-08-03 10:06
Seems to be duplicate of #8525 
> We don't support ARM platform officially. However there are some Eclipse builds for ARM. So potentially it is possible (open dbeaver in Eclipse and try to build it).

**Closed by uslss** 2020-08-03 10:06 UTC
Labels: feature request
