### ISSUE TITLE
update retrieve rows is not working: Error synchronizing data with database (Object parameter [XXX] binding not supported)

### ISSUE THREAD

**Issue by eladbenami** [dbeaver/dbeaver#10048] opened 2020-10-12 15:53 UTC
#### System information: 
- win10
- Version 7.2.2.202010041557
- Additional extensions: n/a

#### Connection specification:
- Database name and version: postgres
- Driver name: jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
updating retrieved results is throwing error 
Error synchronizing data with database (Object parameter [XXX] binding not supported)

#### Steps to reproduce, if exist:
1. running simple select (e.g. select * from table_1)
2. change 1 field from the result panel 
3. click on save or ctrl+s 
4. getting the error

**Comment by andreboyko** [comment] 2020-10-12 19:35
Same here.

*System information:*
- macOS 10.15.7 (19H2)
- Version 7.2.2.202010041557
- Additional extensions: n/a

* Connection specification:*
- Database name and version: postgres
- Driver name: jdbc (postgresql: 42.2.5, postgis-jdbc: 2.2.1, postgis-geometry: 2.5.0)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

**Comment by micperr** [comment] 2020-10-13 08:40
Same:

**System information:**
- Ubuntu 20.04
- Version 7.2.2.202010041557
- Additional extensions: n/a

**Connection specification:**
- Database name and version: postgres
- Driver name: jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

**Comment by LonwoLonwo** [comment] 2020-10-13 10:32
Any [error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)? What type has column, where field was changed?

**Comment by andreboyko** [comment] 2020-10-13 10:51
> Any [error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)? What type has column, where field was changed?

Here is some error-related lines from <workspace>/workspace6/.metadata/.log file.
`!ENTRY org.jkiss.dbeaver.model 4 0 2020-10-13 13:41:59.584
!MESSAGE Object parameter [ec9247ec-cd67-11e8-bbe1-db78d8dac638] binding not supported
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-10-13 13:41:59.584
!MESSAGE Object parameter [ec9247ec-cd67-11e8-bbe1-db78d8dac638] binding not supported
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Object parameter [ec9247ec-cd67-11e8-bbe1-db78d8dac638] binding not supported
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.bindValueObject(DefaultValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$2.bindStatement(JDBCTable.java:466)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:156)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:77)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:804)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:690)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:689)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:627)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.execute(ResultSetPersister.java:442)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.applyChanges(ResultSetPersister.java:170)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.saveChanges(ResultSetViewer.java:3781)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.applyChanges(ResultSetViewer.java:3754)
	at org.jkiss.dbeaver.ui.editors.data.AbstractDataEditor.doSave(AbstractDataEditor.java:210)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.doSave(EntityEditor.java:251)
	at org.eclipse.ui.internal.SaveableHelper.lambda$0(SaveableHelper.java:156)
	at org.eclipse.ui.internal.SaveableHelper.lambda$3(SaveableHelper.java:271)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:436)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:2375)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2373)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:278)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:260)
	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:160)
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3820)
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3833)
	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:57)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:584)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:653)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:443)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$2(KeyBindingDispatcher.java:386)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1113)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4382)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1549)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Canvas.sendKeyEvent(Canvas.java:522)
	at org.eclipse.swt.widgets.Control.doCommandBySelector(Control.java:1081)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6205)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents(NSResponder.java:59)
	at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:606)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6037)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2150)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2401)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6157)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5407)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5543)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3788)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:234)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
`

Table which i want to update has uuid as PK, and i update any column.

**Example:**
`create table "test" (uuid uuid primary key, somecol int);
insert into "test" (uuid, somecol) values ('F6112239-0285-405E-B253-CB51337F3775', 10);`
Next i'm trying to do update 10 => 20 of "somecol" via UI, then i get this:
`Object parameter [f6112239-0285-405e-b253-cb51337f3775] binding not supported`
on save

**Comment by kseniiaguzeeva** [comment] 2020-10-13 11:59
thank you for the report

**Comment by juliapacula** [comment] 2020-10-13 18:26
Same case.

**System information:**

- Fedora 32
- Version 7.2.2.202010041557
- Additional extensions: n/a

**Connection specification:**
- Database name and version: postgres
- Driver name: jdbc (postgresql: 42.2.5, postgis-jdbc: 2.2.1, postgis-geometry: 2.5.0)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

**Comment by ooobii** [comment] 2020-10-15 18:43
I have the same issue when trying to delete a row from the "Data" tab of a "Table" editor where the primary key is of type `GUID`

**System Information:**
- **Operating System:** Mac OS Catalina 10.15.7
- **DBeaver Version:** 7.2.2.202010041557

**Connection specification:**
- Database & Version: Postgres 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1)
- Driver name: JBDC (postgresql: 42.2.5; postgis-jbdc: 2.2.1; postgis-geometry 2.5.0)
- Connection Scheme: Production (default settings)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

I'm guessing it has something to do with the data type of the column used as the primary key?

**Comment by mogzol** [comment] 2020-10-15 20:18
Seeing the same issue on macOS 10.15.7 with a postgres 11 database, downgrading to DBeaver 7.2.1 fixes it.

**Comment by tavisca-tjajodia** [comment] 2020-10-16 08:24
Seeing the same error after recent update 7.2.2.202010041557

**Comment by nicholasbca** [comment] 2020-10-19 03:47
same here

**Comment by Paz1506** [comment] 2020-10-19 08:10
7.2.3.202010181902 problem is still there.

**Comment by serge-rider** [comment] 2020-10-19 09:45
Duplicate of #9964

**Closed by serge-rider** 2020-10-19 09:45 UTC
Labels: bug, duplicate, x:postgresql, xp:major

**Comment by windsonrochazup** [comment] 2020-10-19 12:54
same here!

**Comment by Kulasangar** [comment] 2020-10-19 18:07
Downgraded back to dbeaver version 7.1.2 and it worked.

**Comment by sofiarosati** [comment] 2020-10-20 09:29
Same 
Version:   7.2.3.202010181902
OS:   Ubuntu 18.04.5 LTS

**Comment by uslss** [comment] 2020-10-20 09:31
hotfix was released yesterday evening.
Version 7.2.3.202010191702 contains fix and available here https://dbeaver.io/download/

**Comment by renarsvilnis** [comment] 2020-10-20 09:35
@uslss  Updated from 7.2.2 to the latest 7.2.3.202010191702 still have the issue. Doesn't seem to fix it.
![image](https://user-images.githubusercontent.com/3515099/96568423-9c513f80-12d0-11eb-8a94-738a3d9c0f0d.png)

**Comment by uslss** [comment] 2020-10-20 09:35
thanks for response

**Comment by jeremyhon** [comment] 2020-10-22 03:07
Fixed for me on Version 7.2.3.202010191702

**Comment by rodrigocipriani** [comment] 2020-10-22 10:26
Not working for me, I've just tried.

![image](https://user-images.githubusercontent.com/1211294/96859399-d7ba4e00-1437-11eb-9efe-894005c0c4c7.png)

**Comment by alexbotelhoa** [comment] 2020-10-22 13:14
Downgrade to version 7.2.2 resolves

https://dbeaver.io/files/7.2.2/

**Comment by AmaralMarti** [comment] 2020-10-22 15:20
@alexbotelhoa
Não rolou não cara, estou na versão mais atual do momento (Version 7.2.3.202010181902) e estou com o erro. Acho que é alguma coisa com o UUID.

Don´t work for me in Version 7.2.3.202010181902

**Comment by AmaralMarti** [comment] 2020-10-22 15:26
@alexbotelhoa 
Cara, tive que remover e instalar o novo, então elel foi para Version 7.2.3.202010191702. Agora funcionou.
Valeu pela dica!

This version (Version 7.2.3.202010191702) works for me.

**Comment by kseniiaguzeeva** [comment] 2020-10-23 05:20
@rodrigocipriani please try ea version https://dbeaver.io/files/ea/(  DBeaver	7.2.3.202010202034)

**Comment by evilosa** [comment] 2020-10-23 08:24
@kseniiaguzeeva Working for me

**Comment by alexbotelhoa** [comment] 2020-10-23 10:39
@AmaralMarti então, deve ser problema parecidos. O meu caso bastou jogar a versão anterior e funfou. Mas lgl vc ter conseguido instalar a última versão, vou reinstalar a ultima verão depois pra ver o que acontece. Vlw pela dica bro

**Comment by sidsamant** [comment] 2020-10-23 19:25
Downgraded to Community Version 7.1.2.202007051953

**Comment by sofiarosati** [comment] 2020-10-28 17:00
Downgraded to Version 7.2.2.202010041557 now works (OS: Ubuntu 18.04.5 LTS).

**Comment by pfavv23** [comment] 2020-11-06 16:43
I also had to downgrade to 7.2.2 in order to import a csv file which I need to do weekly. Was this fixed in 7.2.4? I'm hesitant to update now

**Comment by kseniiaguzeeva** [comment] 2020-11-10 08:55
It works correctly in 7.2.4. Please try.

**Comment by vicreal** [comment] 2020-11-10 10:06
>It works correctly in 7.2.4. Please try.
In **7.2.4** not working for **PostgreSQL**: "_Object parameter [...] binding not supported_".
Work correctly only in **7.2.1**.

**Comment by bburns** [comment] 2020-11-11 21:10
I was getting this error trying to save an edited record but upgrading to 7.2.4 fixed it - PostgreSQL, on Mac OS 10.15.7.

**Comment by vicreal** [comment] 2020-11-11 23:41
Retested version **7.2.4**. The bug is only in the case of using custom types. For example:
```
CREATE EXTENSION uint;  -- add unsigned int types / https://github.com/petere/pguint
CREATE TABLE test(id uint4);
INSERT INTO test VALUES(5);
```

If you then try to add or change any value in the "id" column via the DBeaver interface, an error occurs: "_Object parameter [...] binding not supported_" ([pguint](https://github.com/petere/pguint) is a popular extension, written by _PostgreSQL Core Team member_).
**Version 7.2.1 is working correctly**.

In the process of fixing this bug, please also fix the following **2 artifacts with user types**:
**1)** If you restart DBeaver, it "forgets" about user types (in particular, types added by the pguint extension). Specifically, when creating a column with a custom type (or changing the column type to a custom type), BDeaver generates the "_invalid data type_" error. If you open the "_Data Types_" item in the left panel tree, then dbeaver sees the custom types and the error is not generated.
**2)** There are no custom types in the data type selection list.

**Comment by Annlix** [comment] 2021-01-15 01:36
I got it in 7.3.2.202101032114

**Comment by LonwoLonwo** [comment] 2021-01-15 08:03
@Annlix Hello. Any [error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)? What type has column, where field was changed? What type of Database? What type of OS?
