### ISSUE TITLE
"ORA-00933 Command not properly ended" on clicking to sort table by column in Data view

### ISSUE THREAD

**Issue by quiescer** [dbeaver/dbeaver#4295] opened 2018-09-28 00:06 UTC
This only happens with some tables. In this case, the table DDL looks like this:
```

CREATE TABLE "ACCESS_LOG" 
   (	"ACCESS_LOG_ID" NUMBER, 
	"REQUEST_TIME" TIMESTAMP (6), 
	"REMOTE_IP" VARCHAR2(200 CHAR), 
	"USER_NAME" VARCHAR2(30 CHAR), 
	"REQUEST_METHOD" VARCHAR2(10 CHAR), 
	"REQUEST_URI" VARCHAR2(255 CHAR), 
	"ELAPSED_TIME_MS" NUMBER, 
	 CONSTRAINT "ACCESS_LOG_PK" PRIMARY KEY ("ACCESS_LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ISG_TABLES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ISG_TABLES" 
```

**Comment by serge-rider** [comment] 2018-09-28 05:18
I believe it is a duplicate of #4284

**Closed by serge-rider** 2018-09-28 05:18 UTC
Labels: bug, duplicate
