### ISSUE TITLE
CSV import has a strange behavior

### ISSUE THREAD

**Issue by caioclementi** [dbeaver/dbeaver#7926] opened 2020-02-17 12:58 UTC
I use dbeaver sofware every day for quite a while, and I'm used to import data a from a csv file and mixes the imports with custons values in Mapping type and skip as well, until  the version dbeaver-ce_6.3.3_amd64 i have no problem with that but since the new look of boolean  types that was introduced in dbeaver-ce_6.3.4_amd64 and the current version dbeaver-ce_6.3.5_amd64 the import module stopped working the same way, this simply don't work right and has some stranger result in importantion process that i will describe now: 1º I have a table that has a primary key with other 9 columns, in my importantion process i used to skip the primary key and choose where which one of my csv column go and use custons values to complete the others, this workflow work perfectly until the last version, now simply this importantion way doesnt work correctly, and import things that i didnt choose in the importantion process, for example, if i had a csv with 5 columns by i choose the content of only 4 and skipped the id column the tool simply take de content of fifth column and import together, and that make me downgrade again to dbeaver-ce_6.3.3_amd64 version. I expect that in dbeaver-ce_6.3.5_amd64 this problem was solved but that not the case, so here i m to show that this little problem exist. I love Dbeaver, this peace of software make my life much better thank all the developers S2 !!!!

**Comment by uslss** [comment] 2020-02-17 14:03
seems to be duplicate of #7725 
ticket closed.
anyway, thanks for the bug report

**Closed by uslss** 2020-02-17 14:03 UTC
Labels: bug, wait for review
