### ISSUE TITLE
filtered out log viewer window not showing postgres raise info/notice messages

### ISSUE THREAD

**Issue by GarthMcC** [dbeaver/dbeaver#18882] opened 2023-01-26 13:33 UTC
### Description

DO $$
begin
	raise notice 'notify';
	raise log 'log';
       raise info 'info';
	raise warning 'warning';
end
$$;	

can not show all  levels of output available in postgres

### DBeaver Version

community eddition 22.3.3

### Operating System

Ubuntu 22.04

### Database and driver

Postgres 11

**Comment by E1izabeth** [comment] 2023-01-26 13:37
Thank you for bug report. Probably it's a duplicate of #18821 and has been already fixed.
You could try early access version https://dbeaver.io/files/ea/ or wait for the next release.
Let me know if the issue is still actual for you or not when you check.

**Comment by E1izabeth** [comment] 2023-02-01 15:48
Duplicate of #18896

**Closed as not planned by E1izabeth** 2023-02-01 15:48 UTC
Labels: duplicate, wait for response

**Comment by E1izabeth** [comment] 2023-02-01 15:49
The fix will be available in the DBeaver 22.3.4. If the issue will happen again for the new version, please let me know.
