### ISSUE TITLE
SQL Format Issue

### ISSUE THREAD

**Issue by wangjingyv** [dbeaver/dbeaver#11397] opened 2021-02-18 01:51 UTC
![image](https://user-images.githubusercontent.com/31919725/108292023-41701c00-71ce-11eb-8bd1-e57f7997bc02.png)
The key word "case" have no space before it after I format the sql.
Maybe there should be four Spaces in front of "case".

**Comment by uslss** [comment] 2021-02-18 08:47
Hi @wangjingyv ,
unfortunately cannot reproduce an issue.
Could you provide what formatted and dbeaver version do you use?

**Comment by wangjingyv** [comment] 2021-03-02 01:09
![image](https://user-images.githubusercontent.com/31919725/109581056-ac0e4980-7b36-11eb-9a4a-e5f5e2fb9032.png)
![image](https://user-images.githubusercontent.com/31919725/109581095-bfb9b000-7b36-11eb-8332-71eff80f7fbd.png)
![image](https://user-images.githubusercontent.com/31919725/109581121-cf38f900-7b36-11eb-8b88-11ba5ac4c9e7.png)
Here is my version number and format.

**Comment by wangjingyv** [comment] 2021-03-02 01:13
![image](https://user-images.githubusercontent.com/31919725/109581547-6b630000-7b37-11eb-8af2-b7617d86613a.png)
 This problem does not exist in the MySQL database, it exists in the Oracle database

**Comment by LonwoLonwo** [comment] 2021-03-24 08:52
Fixed in 21.0.2
Will be available [here](https://dbeaver.io/) at 2020-04-05

**Comment by uslss** [comment] 2021-03-24 10:28
verified

**Closed as completed by uslss** 2021-03-24 10:28 UTC
Labels: x:oracle, xf:sql, sp:2
