### ISSUE TITLE
1-click Update

### ISSUE THREAD

**Issue by allan-shoup** [dbeaver/dbeaver#9363] opened 2020-07-24 13:55 UTC
Whenever there is a new version of DBeaver the user needs to go through a bunch of clicks to install the new version. The most prevalent use case is to do an in-place upgrade to the latest version. If that can be done in a single click, that would streamline the upgrade process.

**Comment by kseniiaguzeeva** [comment] 2020-07-26 20:38
Thank you for the suggestion

**Comment by kseniiaguzeeva** [comment] 2020-07-27 05:27
We already have such ticket. Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/1590

**Closed by kseniiaguzeeva** 2020-07-27 05:27 UTC
Labels: duplicate, feature request, planned
