### ISSUE TITLE
[Feature Request] Option to display trailing whitespaces in data editor

### ISSUE THREAD

**Issue by Lautenschlager-id** [dbeaver/dbeaver#12631] opened 2021-05-27 17:09 UTC
I would like to be able to see trailing whitespaces in data from the data editor.

For example, assume the value `test ` in the following query:
``insert into `player` ( `name` ) values ( "test " )``

This way I currently can't see the whitespace in "test" when displayed in the data editor, leading me to face some bugs in my application. It would be easier for me if DBeaver displayed the whitespace somehow.

It could be enabled in the settings menu, preferably.

Illustration:
![image](https://user-images.githubusercontent.com/26045253/119515155-fd039780-bd4b-11eb-9fef-51823b710c31.png)
There is a whitespace, as you can see below, that I would like to have noticed when reading its content.
![image](https://user-images.githubusercontent.com/26045253/119515189-042aa580-bd4c-11eb-98f9-47a7ea61de0c.png)

##### Reposted by request https://github.com/dbeaver/dbeaver/discussions/12481#discussioncomment-790758

**Comment by uslss** [comment] 2021-05-31 09:01
thanks for the suggestion. Seems to be duplicate of #1934

**Closed as completed by uslss** 2021-05-31 09:01 UTC
Labels: duplicate, xf:data
