### ISSUE TITLE
format SQL introduce blank before underscore

### ISSUE THREAD

**Issue by Marco-InForge** [dbeaver/dbeaver#16250] opened 2022-04-20 12:30 UTC
#### System information: 
- Operating system (distribution) and version: Linux 5.16.20-200.fc35.x86_64
- DBeaver version: community Version 22.0.3.202204170718

#### Connection specification:
Not relevant

#### Describe the problem you're observing:
If a query as a database with a name starting with a number followed by an underscore
`select * from 2015_autovetture.tblmarca t;`
the "Format SQL" produce a wrong query due to an extra blank inserted after the number before the underscore
```
select
	*
from
	2015 _autovetture.tblmarca t;
```

#### Steps to reproduce, if exist:
1. new SQL script
2. write `select * from 2015_autovetture.tblmarca t;`
3. apply "Format SQL"
4. a blank is inserted before the underscore `...2015 _autovetture.tblmarca t;`

**Comment by LonwoLonwo** [comment] 2022-04-20 12:55
Hello @Marco-InForge 

Thanks for the bug report.

This ticket is duplicate of https://github.com/dbeaver/dbeaver/issues/15605 
You can read discussion about this problem there.

**Closed as completed by LonwoLonwo** 2022-04-20 12:55 UTC
Labels: xf:sql
