### ISSUE TITLE
Split Window Error

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#35493] opened 2024-09-05 23:58 UTC
### Description

While editing SQL in SQL Editor, open the function definition window to modify the contents of the function (Open Declaration).
For convenience of editing, you can separate the window vertically to make modifications and then go back to the SQL editor. 
A confirmation window for terminating Dbeaver will appear with the message “Unhandles event loop exception. No more handles.”

### DBeaver Version

Beaver Community 24.2.0

### Operating System

Window 10

### Database and driver

Oracle

### Steps to reproduce

1. Open SQL Editor
2. Open Declaration.
3. Move the declaration window to the right
4. Edit SQL Editor
5. Focus declaration window
![splitwindow](https://github.com/user-attachments/assets/e8c8333c-63a9-4584-8d3f-77f2e2b5b413)

**Comment by E1izabeth** [comment] 2024-10-04 17:45
For now, we're unable to reproduce the issue.
Could you reproduce the issue once again and, after that, send us log files? You can collect them to archive automatically with `Help->Collect Diagnostic Info`
![image](https://github.com/user-attachments/assets/51c7ca2e-6be2-489e-b495-028b9aa0e386)

**Comment by serge-rider** [comment] 2024-10-05 07:47
Duplicate of #35570

**Closed as completed** 2024-10-05 07:48 UTC
Labels: duplicate
