### ISSUE TITLE
Advance copy feature not working correctly in "Schema properties" view

### ISSUE THREAD

**Issue by ahhmedbilal** [dbeaver/dbeaver#13620] opened 2021-08-23 07:47 UTC
#### System information: 
- Operating system (distribution) and version win 10
- DBeaver version 21.1.2
- Additional extensions

#### Connection specification:
- Database name and version teradata 16.20
- Driver name teradata jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
The advance copy feature in schema properties does not copy the correct order to columns. 

#### Steps to reproduce, if exist:
Double click any schema. It will open schema window and show all objects. 
Under "Tables" sub window, the default col order is 
Schema    Table Name    Table Type    Table Description    Row Count

but if rearrange col as 
Schema    Table Name    Row Count Table Type    Table Description

and select 2 or more tables and click "Advance copy" and paste it then it still paste the col order as 

Schema    Table Name    Table Type    Table Description    Row Count

where as it should paste below order
Schema    Table Name    Row Count Table Type    Table Description

**Comment by uslss** [comment] 2021-08-23 08:12
thanks for the report
closed as a duplicate of #9252

**Closed as completed by uslss** 2021-08-23 08:12 UTC
Labels: duplicate, xf:metadata
