### ISSUE TITLE
macOS 13.0 Beta (22A5331f) DBeaver doesn't show dropdown menus

### ISSUE THREAD

**Issue by joaofconde** [dbeaver/dbeaver#17567] opened 2022-09-05 23:27 UTC
### Description

macOS 13.0 Beta (22A5331f) DBeaver doesn't show dropdown menus

### DBeaver Version

Community edition last version

**Comment by LonwoLonwo** [comment] 2022-09-06 06:57
Hello @joaofconde 

DBeaver is based on the Eclipse platform, and this is the Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=580322

It seems to be fixed already, but this fix will be available in our product only in Autumn with the new Eclipse release.

As a workaround, for now, you can use DBeaver versions <= 22.1.0.

I am closing this as a duplicate of #17204

**Closed as not planned by LonwoLonwo** 2022-09-06 06:57 UTC
Labels: xo:macos, xf:ui

**Comment by joaofconde** [comment] 2022-10-01 17:38
Hi all, with last version now works perfectly

**Comment by LonwoLonwo** [comment] 2022-10-03 06:13
Thanks for the report @joaofconde
