### ISSUE TITLE
It does not reconnect database after dropping the vpn connection

### ISSUE THREAD

**Issue by chboxbr** [dbeaver/dbeaver#10528] opened 2020-11-27 14:01 UTC
Use:
Database access by vpn.

Problem:
If during use the vpn connection drops, when you return it is not possible to select, update and delete ...
It is necessary to force the application to close and reopen.

**Comment by uslss** [comment] 2020-12-11 00:16
duplicate of #9379 
anyway, thanks for the report

**Closed by uslss** 2020-12-11 00:16 UTC
Labels: bug, duplicate
