### ISSUE TITLE
[SQL Server] "Export from query" to Database doesn't work

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7798] opened 2020-02-01 15:47 UTC
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
Export "from query" or from Resultset of SQL Editor to Database doesn't work.

#### Steps to reproduce, if exist:
1. Execute a select statement in SQL Editor.
2. Try to export from query/resultset to a database table.

Actual result:
1. Error window appears: "Can't get attributes from [select * from testimport t ]
Reason:
SQL Error [208] [S0002]: Invalid object name 'testimport'."
2. Import is failed.

![yVYOT1NFUj](https://user-images.githubusercontent.com/51405061/73594827-021f5080-4523-11ea-8be3-3856fbe09de6.gif)

[.log](https://github.com/dbeaver/dbeaver/files/4142735/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4142736/dbeaver-debug.log)

**Comment by serge-rider** [comment] 2020-02-08 17:21
Duplicate of #7731

**Closed by serge-rider** 2020-02-08 17:21 UTC
Labels: bug, duplicate
