### ISSUE TITLE
query keeps running for over 12 hrs..

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#20160] opened 2023-05-31 15:41 UTC
### Description

this query keeps running for over 12 hrs...I am attaching log file and following is the script.

create table temp_physician_alpha as (
select base_final.*,
base_3.Program_Year ,base_3.Participation_Status,base_3.Quality_Score,base_3.Promoting_Interoperability_Score,
base_3.Improvement_Activities_Score,base_3.Final_Mips_Score,base_4.Executive_Positions_Held,
base_5.Hospital_Sposored_Clinical_Trials,base_5.Other_Sponsored_Clincal_Trials
from 
(
select base.* ,f_temp2.Secondary_Practice_Locations from
(select A.npi,A.pac_id,A.First_Name,A.Middle_Name,A.Last_Name,A.Suffix,Gender,
Credential,Specialty_Primary,Specialty_Secondary,Medical_School_Name,
--replace(Graduation_Year,'.0','') as 
Graduation_Year,
--replace(Age,'.0','') as 
Age,
Hospitalist_Flag,Executive_Flag,replace(Primary_Affiliation_Hospital_Id,'.0','') as Primary_Affiliation_Hospital_Id,
Primary_Practice_Location_Name,
Primary_Taxonomy,
--replace(Total_Drug_Prescription_Count,'.0','') as 
Total_Drug_Prescription_Count,
--replace(Total_Drug_Day_Supply,'.0','') as 
Total_Drug_Day_Supply,
 case when total_drug_cost='' then null
else CAST(total_drug_cost  AS numeric)
end as Total_Drug_Cost,
--replace(Total_Number_Unique_Drugs,'.0','') as 
Total_Number_Unique_Drugs,
--replace(Total_Drug_Beneficiary_Count,'.0','') as 
Total_Drug_Beneficiary_Count,
Key_Opinion_Leader_Flag,Primary_Kol_Indication,Secondary_Kol_Indication,A.Primary_Practice_Location_Id,
Participates_In_Mips,Participated_In_Clinical_Trials,
C.Clinical_Activity_Percentile,C.Clinical_Activity_Level,C.Prescription_Activity_Percentile,C.Prescription_Activity_Level,
C.Propensity_To_Prescribe_Brand_Name_Drugs_Percentile,C.Propensity_To_Prescribe_Brand_Name_Drugs_Level
FROM dhc_src.physicians_overview A
left JOIN dhc_src.Physicians_Definitive_Dashboard_Data C
on A.npi = C.npi
)base 

left join
(
select npi,primary_affiliation_hospital_id, 
--Secondary_Practice_Locations
regexp_replace(Secondary_Practice_Locations, '[,]+$','') Secondary_Practice_Locations 
from
(
select npi,primary_affiliation_hospital_id,
case when primary_practice_location_name =''
	then 
	concat(primary_practice_location_id,',',practice_location_hospital_id_con)
	else 
	concat(primary_practice_location_name,',',primary_practice_location_id,',',practice_location_hospital_id_con) 
	end as Secondary_Practice_Locations
from 
(
Select npi,primary_affiliation_hospital_id ,primary_practice_location_name,primary_practice_location_id,
string_agg(practice_location_hospital_id, ',' order by npi,primary_affiliation_hospital_id ) as practice_location_hospital_id_con

from
( 
select A.npi,replace(A.primary_affiliation_hospital_id,'.0','') as primary_affiliation_hospital_id,
A.primary_practice_location_name,
replace(B.practice_location_hospital_id,'.0','') as practice_location_hospital_id,
replace(A.primary_practice_location_id,'.0','') as primary_practice_location_id
FROM dhc_src.physicians_overview A
left JOIN dhc_src.physicians_practice_locations B
on 
case when B.practice_location_hospital_id = '' then A.npi=B.npi
 else (A.npi=B.npi and replace(A.primary_affiliation_hospital_id,'.0','') != B.practice_location_hospital_id)
 end

)assa 
group by npi,primary_affiliation_hospital_id,primary_practice_location_name,primary_practice_location_id)final_temp
)final_temp_2)f_temp2
on f_temp2.npi=base.npi)base_final

left join 
(select * from
(select D.npi,D.Program_Year ,D.Participation_Status,D.Quality_Score,D.Promoting_Interoperability_Score,
D.Improvement_Activities_Score,D.Final_Mips_Score,
Rank() over( partition by D.npi order by D.npi,MAX(D.Program_Year) desc) as row_numbers
from 
dhc_src.Physicians_Quality_Overall_MIPS_Performance D
group by D.npi,
D.Program_Year ,D.Participation_Status,D.Quality_Score,D.Promoting_Interoperability_Score,
D.Improvement_Activities_Score,D.Final_Mips_Score)base_2 where row_numbers=1)base_3
on base_final.npi=base_3.npi

left join

(
	select replace(physician_npi,'.0','') as physician_npi ,
		array_to_string(array_agg(concat(department,'(',standardized_title,'-',replace(physician_npi,'.0','') ,')')),',') as Executive_Positions_Held
		from dhc_src.hospital_executives he 
		group by replace(physician_npi,'.0','') 

)base_4
on base_final.npi=base_4.physician_npi

left join

(

select npi,sum(temp_base.hospital) Hospital_Sposored_Clinical_Trials, sum(temp_base.non_hospital) as Other_Sponsored_Clincal_Trials from 
(select * from crosstab(
'select npi,lead_sponsor,number_of_trials
from dhc_src.temp_Physicians_Clinical_Trials_Sponsors order by 1,2',
'select distinct lead_sponsor
from dhc_src.temp_Physicians_Clinical_Trials_Sponsors order by 1'

)
as t(npi varchar,"hospital" int,"non_hospital" int ))temp_base
group by  temp_base.npi
)base_5
on base_final.npi=base_5.npi);

### DBeaver Version

23.0.0

### Operating System

windows

### Database and driver

postgres 14.0

### Steps to reproduce

[error log.txt](https://github.com/dbeaver/dbeaver/files/11616024/error.log.txt)

see logs attached

**Comment by E1izabeth** [comment] 2023-05-31 15:44
Thank you for bug report

**Comment by E1izabeth** [comment] 2023-06-01 12:29
@jgrover21 could you try Early Access version https://dbeaver.io/files/ea/?

**Comment by jgrover21** [comment] 2023-06-01 14:25
Which one do you suggest?  I went to 23.0.0. do you want me to get earlier than that?

Respectfully,

Jyoti Grover

**Comment by E1izabeth** [comment] 2023-06-01 14:29
By early access version we mean pre-release version.
We made some changes that may fix the issue and the fix will be included to the next release DBeaver 23.1.0. However, for some major bugs we built the version with fix earlier than a release date.

I propose you to try DBeaver 23.1.0, which you can download by this link only https://dbeaver.io/files/ea/

**Comment by jgrover21** [comment] 2023-06-01 16:13
I did that.
Now I m testing to export a file but it is super slow.

Respectfully,

Jyoti Grover

**Comment by jgrover21** [comment] 2023-06-01 16:14
Error occurred during batch insert
(you can disable batch insert in order to skip particular rows).

Reason:
SQL Error [22023]: No value specified for parameter 2.

Respectfully,

Jyoti Grover

**Comment by E1izabeth** [comment] 2023-06-01 16:16
Thank you for checking.

**Comment by LonwoLonwo** [comment] 2023-06-05 08:23
Hello @jgrover21 

Do you export a file from the table or this query from the main topic? And how about the execution issue from the main topic? Does it still reproducible?

**Comment by E1izabeth** [comment] 2023-06-30 09:44
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Closed as not planned by E1izabeth** 2023-06-30 09:44 UTC
Labels: xp:major, wait for response, xf:sql execution
