### ISSUE TITLE
can not copy cell value

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#8184] opened 2020-03-13 15:33 UTC
when copying float value only few digits are copied and I can not select all

see attached video

[Kazam_screencast_00024.mp4.zip](https://github.com/dbeaver/dbeaver/files/4330308/Kazam_screencast_00024.mp4.zip)

**Comment by uslss** [comment] 2020-03-16 10:18
thanks for the bug report

**Comment by serge-rider** [comment] 2020-03-17 11:45
I think it is a duplicate of #8099

**Comment by uslss** [comment] 2020-03-17 14:41
verified

**Closed by uslss** 2020-03-17 14:41 UTC
Labels: bug, duplicate, x:postgresql
