### ISSUE TITLE
Could not initialize class com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil

### ISSUE THREAD

**Issue by strangan** [dbeaver/dbeaver#17303] opened 2022-08-08 21:46 UTC
### Description

This only affects Dbeaver CE for Silicon ARM Mac OS X. 

Querying any Databricks table produces the following error:

SQL Error [500540] [HY000]: [Databricks][DatabricksJDBCDriver](500540) Error caught in BackgroundFetcher. Foreground thread ID: 124. Background thread ID: 172. Error caught: Could not initialize class com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.

### DBeaver Version

Version 22.1.4.202208051447

### Operating System

Mac OS X Monteray 10.5

### Database and driver

Database: Azure Databricks

I setup Dbeaver as desribed below.

https://docs.microsoft.com/en-us/azure/databricks/dev-tools/dbeaver

This issue only seems to be there on the Mac Silicon ARM version of Dbeaver. This issue does not occur if one uses the Mac OS X Intel DMG version.

### Steps to reproduce

1. Follow the steps below to setup the custom Azure Databricks Connector described on the MSFT site
https://docs.microsoft.com/en-us/azure/databricks/dev-tools/dbeaver

2. Connect to the Database
3. Write any SELECT SQL query on any table inside databricks.

**Comment by LonwoLonwo** [comment] 2022-08-09 08:49
Hello @strangan 

Do you use DBeaver bundled java or your java?

**Comment by strangan** [comment] 2022-08-09 16:07
HI @LonwoLonwo 

I am using the Java bundled with Dbeaver. In other words, I am not changing any environments etc. The issue seems to be with the Silicon ARM version of Dbeaver.

Thanks


> Hello @strangan
> 
> Do you use DBeaver bundled java or your java?

**Comment by dbeaver-pm** [comment] 2022-08-11 14:05
Probably it's connected with JAVA 17.

**Comment by flambchap** [comment] 2022-08-18 12:45
Hi @strangan. Can you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

**Comment by strangan** [comment] 2022-08-18 16:32
Hi @n5a5 

Please see attached.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/9375756/dbeaver-debug.log)
[Dbeaver-LogFile-MacM1Silicon.txt](https://github.com/dbeaver/dbeaver/files/9375759/Dbeaver-LogFile-MacM1Silicon.txt)

**Comment by flambchap** [comment] 2022-08-18 17:39
Thank you. The issue is indeed linked to Java 17:

`Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @4a007e64`

I think we can tweak the bundled JRE.

**Comment by flambchap** [comment] 2022-08-18 17:41
As a workaround, please find the `dbeaver.ini` file inside DBeaver.app and add the following two lines to the bottom of the file:

```
--add-opens
java.base/java.nio=ALL-UNNAMED
```

**Comment by flambchap** [comment] 2022-08-18 18:06
The same issue here: https://github.com/dbeaver/dbeaver/issues/14691

**Comment by strangan** [comment] 2022-08-18 19:20
I did that, but it doesn't solve the problem. Here's a copy of my
dbeaver.ini file

-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.aarch64_1.2.500.v20220509-0833
-vm
../Eclipse/jre/Contents/Home/bin/java
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-XstartOnFirstThread
--add-opens
java.base/java.nio=ALL-UNNAMED

**Comment by strangan** [comment] 2022-08-30 00:04
Hi Any update on this? I changed the dbeaver.ini file like you suggested, but it did not make a difference.

Let me know.

Thanks

**Comment by alexmalins** [comment] 2022-08-30 00:23
Hi, I've also run up against this issue this morning. I guess an issue is there are no Mac/AArch64 builds of OpenJDK for < Java 17... Would trying OpenJDK v18 help? Or Maybe an [Azul](https://www.azul.com/downloads/?os=macos&architecture=arm-64-bit&package=jdk) OpenJDK build with version < 17 - e.g. v11?

**Comment by sage5616** [comment] 2022-08-30 20:42
Hello, 

I am running into the same problem as OP. M1 Mac, 
Java version:
openjdk 18.0.2.1 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode)

This is Dbeaver for M1 specific bug. DataGrip by JetBrains works fine.
Also, the same error occurs with SQL Workbench/J.

Please fix Dbeaver for for M1 Macs.

**Comment by alexmalins** [comment] 2022-08-30 23:12
Here is an unofficial workaround for Apple silicon users:

- Download and install Azul's Zulu JRE v11 for macOS Arm64 from [here](https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jre)
- Open `/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini` and edit the line below `-vm` to point to the newly installed JRE v11 at `/usr/bin/java`
- Launch DBeaver and now Databricks queries should work

@okulikm yes DataGrip works fine for me also, running JetBrians' OpenJDK v17.0.3

**Comment by flambchap** [comment] 2022-08-31 11:09
@alexmalins, Thank you for the workaround. In fact, any JRE < 16 should work as the issue is directly linked to this JEP: https://openjdk.org/jeps/396. Another good alternative I know is BellSoft's Liberica JRE.

@strangan, I suggest using the workaround above. Please don't forget to restore dbeaver.ini to its original state.

The issue is scheduled for the 22.2.1 release.

**Comment by sage5616** [comment] 2022-08-31 12:50
@alexmalins thank you for sharing the workaround steps, I will give it a shot. I have a follow up question, is it possible to keep multiple versions of JRE on the same machine without conflicts and point Dbeaver to JRE v11? Have you done this, is it as simple as installing JRE in different directories or is there more configuration to do after the installation?

@n5a5 Nikita Akilov thank you for sharing about JRE < 16 and BellSoft's Liberica JRE. It is good to know. Also, do you happen to be aware of when 22.2.1 release is scheduled to become available?

**Comment by flambchap** [comment] 2022-08-31 13:04
@okulikm On September 26. 

Generally, no other configuration is needed. The only thing to be aware of is the `JAVA_HOME` variable. It points to your default java, and some installers may change it.

**Comment by alexmalins** [comment] 2022-08-31 13:24
@okulikm No I didn't, this was the first system-wide install I did of a JRE on this machine, and I don't have experience with multiple installs. As @n5a5 says though, it should be possible. Searching StackOverflow etc. will yield answers.

**Comment by sage5616** [comment] 2022-09-02 19:36
The workaround from @alexmalins has worked for me as well. I have installed Azul's Java 11 (LTS) using .dmg: https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jre

@n5a5 looking forward to that date. Will that release work with the latest OpenJDK@18 available via brew? https://formulae.brew.sh/formula/openjdk

**Comment by flambchap** [comment] 2022-09-14 13:34
@sage1147 I think it will. At the same time, we'll probably patch the JRE we bundle with our dmgs, so you won't need to install a separate JRE.

Unfortunately, we couldn't squeeze this ticket into 22.2.1. Re-scheduled to 22.2.2.

**Comment by strangan** [comment] 2022-09-15 06:03
Thanks @n5a5 . I dont want to mess around with Java and JRE versions. When is 22.2.2 due to be released? Sometime in October I imagine?

**Comment by flambchap** [comment] 2022-09-15 11:39
@strangan We release new versions every two weeks, so that will be October 10.

**Comment by strangan** [comment] 2022-10-10 20:35
Was this fixed in today's 10/10/2022 release? It doesn't seem like it, but i wanted to verify.

**Comment by E1izabeth** [comment] 2022-10-10 20:38
@strangan it wasn't fixed in 22.2.2

**Comment by strangan** [comment] 2022-10-10 20:47
ok thanks. Any idea when it will be fixed - which release will it be squeezed into?

**Comment by E1izabeth** [comment] 2022-10-10 20:49
I don't have an answer for this question now. We will try to keep you informed.

**Comment by sage5616** [comment] 2022-10-11 14:32
Thank you @E1izabeth. Hope it can be fixed soon... I like Dbeaver, but need to switch to an alternative when using Databricks.

**Comment by strangan** [comment] 2022-10-25 23:10
hi @E1izabeth : Any update on this? It doesn't look like it made it into today's release either.

**Comment by ShadelessFox** [comment] 2022-10-25 23:52
Hello @strangan,

It hasn't been fixed yet. The issue is currently scheduled for 22.3.0.

**Comment by Matvey16** [comment] 2022-11-01 11:36
Fixed in the scope of #14691

**Closed as completed** 2022-11-01 11:37 UTC
Labels: xp:major, xo:macos, sp:2, xf:packaging, x:databricks

**Comment by strangan** [comment] 2022-11-01 23:27
Has this been fixed in an upcoming release? will that release be next Monday/Tuesday Nov 7th/8th?  If so, please confirm?

**Comment by E1izabeth** [comment] 2022-11-02 07:27
The fix will be available in the next release.

**Comment by strangan** [comment] 2022-11-08 03:15
Thanks! I can confirm this now works. Thank you for getting this fixed.

**Comment by lotnikov** [comment] 2023-04-21 12:19
still have same issue on DBeaver Version 23.0.2.202304091457 with databricks jdbc driver DatabricksJDBC42-2.6.32.1054 
`org.jkiss.dbeaver.model.exec.DBCException: SQL Error [500540] [HY000]: [Databricks][DatabricksJDBCDriver](500540) Error caught in BackgroundFetcher. Foreground thread ID: 113. Background thread ID: 378. Error caught: Could not initialize class com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.nextRow(JDBCResultSetImpl.java:183)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:837)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3864)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5091)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: [Databricks][DatabricksJDBCDriver](500540) Error caught in BackgroundFetcher. Foreground thread ID: 113. Background thread ID: 378. Error caught: Could not initialize class com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.
	at com.databricks.client.hivecommon.dataengine.BackgroundFetcher.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Caused by: com.databricks.client.support.exceptions.GeneralException: [Databricks][DatabricksJDBCDriver](500540) Error caught in BackgroundFetcher. Foreground thread ID: 113. Background thread ID: 378. Error caught: Could not initialize class com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.
	... 5 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:228)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.ArrowBuf.nioBuffer(ArrowBuf.java:223)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:87)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:727)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.deserializeRecordBatch(MessageSerializer.java:363)
	at com.databricks.client.spark.arrow.ArrowBuffer.deserializeBatch(Unknown Source)
	at com.databricks.client.spark.arrow.ArrowBuffer.handleInitializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.HiveServer2BaseBuffer.initializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.RowsetBuffer.initializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.getRowSetInformation(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.fetchFromServer(Unknown Source)
	at com.databricks.client.spark.jdbc.DowloadableFetchClient.fetchNRows(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.fetchRows(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.BackgroundFetcher.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by LonwoLonwo** [comment] 2023-04-21 15:58
Hello @lotnikov 

Do you use the standalone version or Eclipse one? Do you use bundled DBeaver Java or your own version?
