### ISSUE TITLE
Export result set for error reporting

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6517] opened 2019-08-14 01:42 UTC
![image](https://user-images.githubusercontent.com/26621087/62988662-b515c800-be77-11e9-9e4a-8baf6c34371c.png)
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Administrator/AppData/Roaming/DBeaverData/workspace6/

This is a continuation of log file C:\Users\Administrator\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2019-08-14 09:40:38.271

org.eclipse.e4.ui.workbench
错误
Wed Aug 14 09:42:02 CST 2019
Failed to evaluate: WithExpression [variable=activePart, children=[<test property="running" plug-in activation: lazy/>]]

org.eclipse.core.runtime.CoreException: 属性测试对象未将 org.jkiss.dbeaver.runtime.process.running 属性添加至 class org.jkiss.dbeaver.ui.editors.sql.SQLEditor 类型
	at org.eclipse.core.internal.expressions.TypeExtensionManager.getProperty(TypeExtensionManager.java:130)
	at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:100)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:55)
	at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:81)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:74)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:100)
	at org.eclipse.ui.internal.services.EvaluationReference.changed(EvaluationReference.java:94)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:109)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.ui.internal.services.EvaluationService$1.changed(EvaluationService.java:79)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:109)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.activate(EclipseContext.java:683)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.activateBranch(EclipseContext.java:692)
	at org.eclipse.e4.ui.internal.workbench.swt.ShellActivationListener$1.run(ShellActivationListener.java:99)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.ShellActivationListener.processWindow(ShellActivationListener.java:95)
	at org.eclipse.e4.ui.internal.workbench.swt.ShellActivationListener.handleEvent(ShellActivationListener.java:65)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1194)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1080)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Decorations.WM_ACTIVATE(Decorations.java:1542)
	at org.eclipse.swt.widgets.Shell.WM_ACTIVATE(Shell.java:2178)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4756)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1501)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2138)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.DestroyWindow(Native Method)
	at org.eclipse.swt.widgets.Control.destroyWidget(Control.java:796)
	at org.eclipse.swt.widgets.Shell.destroyWidget(Shell.java:714)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:823)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:429)
	at org.eclipse.swt.widgets.Decorations.dispose(Decorations.java:408)
	at org.eclipse.swt.widgets.Shell.dispose(Shell.java:742)
	at org.eclipse.jface.window.Window.close(Window.java:335)
	at org.eclipse.jface.dialogs.Dialog.close(Dialog.java:993)
	at org.eclipse.jface.dialogs.ErrorDialog.close(ErrorDialog.java:688)
	at org.jkiss.dbeaver.ui.dialogs.StandardErrorDialog.close(StandardErrorDialog.java:167)
	at org.eclipse.jface.dialogs.Dialog.okPressed(Dialog.java:953)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:469)
	at org.eclipse.jface.dialogs.ErrorDialog.buttonPressed(ErrorDialog.java:162)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.jface.dialogs.ErrorDialog.open(ErrorDialog.java:342)
	at org.jkiss.dbeaver.core.DBeaverUI.lambda$1(DBeaverUI.java:202)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:146)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4580)
	at org.jkiss.dbeaver.ui.UIUtils.syncExec(UIUtils.java:1670)
	at org.jkiss.dbeaver.core.DBeaverUI.showError(DBeaverUI.java:204)
	at org.jkiss.dbeaver.core.DBeaverUI.showError(DBeaverUI.java:212)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferErrorJob.runInUIThread(DataTransferErrorJob.java:41)
	at org.jkiss.dbeaver.ui.AbstractUIJob.runInUIThread(AbstractUIJob.java:41)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Administrator/AppData/Roaming/DBeaverData/workspace6/

This is a continuation of log file C:\Users\Administrator\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2019-08-14 09:40:38.271

org.eclipse.e4.ui.workbench
错误
Wed Aug 14 09:40:38 CST 2019
Failed to evaluate: WithExpression [variable=activePart, children=[<test property="running" plug-in activation: lazy/>]]

org.eclipse.core.runtime.CoreException: 属性测试对象未将 org.jkiss.dbeaver.runtime.process.running 属性添加至 class org.jkiss.dbeaver.ui.editors.sql.SQLEditor 类型
	at org.eclipse.core.internal.expressions.TypeExtensionManager.getProperty(TypeExtensionManager.java:130)
	at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:100)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:55)
	at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:81)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:74)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:100)
	at org.eclipse.ui.internal.services.EvaluationService.requestEvaluation(EvaluationService.java:290)
	at org.eclipse.ui.internal.handlers.DirtyStateTracker.update(DirtyStateTracker.java:48)
	at org.eclipse.ui.internal.handlers.DirtyStateTracker.propertyChanged(DirtyStateTracker.java:110)
	at org.eclipse.ui.part.WorkbenchPart.firePropertyChange(WorkbenchPart.java:123)
	at org.eclipse.ui.texteditor.AbstractTextEditor.firePropertyChange(AbstractTextEditor.java:6366)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.updateDirtyFlag(SQLEditor.java:3196)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$SQLEditorQueryListener.lambda$4(SQLEditor.java:3091)
	at org.jkiss.dbeaver.ui.UIUtils$6.runInUIThread(UIUtils.java:1544)
	at org.jkiss.dbeaver.ui.AbstractUIJob.runInUIThread(AbstractUIJob.java:41)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

**Comment by serge-rider** [comment] 2019-08-29 12:57
Duplicate of #6637

**Closed by serge-rider** 2019-08-29 12:57 UTC
Labels: bug, duplicate
