### ISSUE TITLE
Add "Make Table Copy" button, which duplicates the table and its data

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#10962] opened 2021-01-13 18:09 UTC
**Is your feature request related to a problem? Please describe.**
Occasionally, I need to generate a duplicate of a table (sometimes with, sometimes without the data) in order to perform some quick manipulations and testing on the table and its data.

**Describe the solution you'd like**
I want to right click on a table, go to Create, and click the new "Table Copy" option. A dialog box (similar to below) will appear with options about specifically what parts of the table to copy (copy columns, indexes, foreign keys, and data). 

**Describe alternatives you've considered**
This feature could also be create in the Generate SQL section of the context menu. 

**Additional context**
This feature exists in HeidiSQL, and is the last thing holding me back from transitioning my team away from HeidiSQL to DBeaver.
![image](https://user-images.githubusercontent.com/11021263/104491486-8bdaf900-558f-11eb-87d0-2c0f5a56b0be.png)

**Comment by ShadelessFox** [comment] 2021-01-14 13:19
Hello @ThePiGuy, 

You can use data transfer to make a copy of your table: https://github.com/dbeaver/dbeaver/wiki/Data-migration.

Please let me know if this solution will suit your needs.

**Comment by DeflateAwning** [comment] 2021-01-14 15:32
I guess this does technically accomplish the same thing, but it's a way way
longer process. Ideally there would just be a button that lets me copy and
single table within the database. Maybe it can just call the main function
with the data migration wizard skipping through a bunch of the extra
screens that aren't needed in my case.

**Comment by LonwoLonwo** [comment] 2023-07-27 07:31
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/17767

**Closed as completed by LonwoLonwo** 2023-07-27 07:31 UTC
Labels: duplicate, xf:datatransfer

**Comment by DeflateAwning** [comment] 2023-07-27 17:23
The other person's issue is duplicate of mine! My description is way more comprehensive. Why would you close mine and not theirs?!

**Comment by LonwoLonwo** [comment] 2023-07-28 14:58
Hello @DeflateAwning 

I closed this ticket because another ticket has a better situation explanation. And workarounds - with links on the Data Transfer.
But in general - it is the same idea - create a "Table Copy" button.
Usually, during ticket investigation, we are reading bounded tickets. But you can copy your main message to another ticket to be sure.
