### ISSUE TITLE
[Feature request] DBeaver should not close table tabs without active connection

### ISSUE THREAD

**Issue by SylwesterZarebski** [dbeaver/dbeaver#4300] opened 2018-09-28 13:45 UTC
There is not expected behaviour with closing table tabs when there are no connection within these tabs.
Lets make simple scenario:
1. Create connection without saved password.
2. Connect and give password.
3. Open some tables.
4. Close DBeaver.
5. Reopen DBeaver and DO NOT give password when asked.
6. Tabs will be closed, which is not expected.

I propose to mark these tabs as non-active and only ask for password when user select tab.
If user second time do not give password, tab should be empty and read-only.

Above behaviour is the same on network outage, then even giving password often close tabs, because program detect connection closed before reconnection.

**Comment by serge-rider** [comment] 2018-11-02 14:05
This is still not very clear. If you click on some "saved" table and you don't provide password so there is no connection - table will be closed because DBeaver can't fetch any information about that table. for me this looks like more or less expected behavior.

Any how, we need some other opinions on that.

**Comment by uslss** [comment] 2020-07-22 19:14
Already implemented

**Comment by SylwesterZarebski** [comment] 2020-07-22 20:13
I'm afraid, it is not fully fixed. When there are no connection on dBeaver start and i have opened table (properties/data/er diagram) tab, error window is shown, but if i choose `Ignore`, then:
a) tab is lost, always displays error - i do not found a way to refresh this tab
b) and closes if i change tab to another (also these broken tabs are not saved at close).

It looks like only script tabs are properly supported by new mechanism now.

**Comment by SylwesterZarebski** [comment] 2020-07-23 09:04
Thanks, i appreciate all work You do on this great software :-).

**Comment by E1izabeth** [comment] 2023-05-25 08:59
Fixed in scope of #18449

Now it's controlled with this setting 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/88a3cd55-326f-4ffc-bf81-c0099512eb75)

**Closed by E1izabeth** 2023-05-25 08:59 UTC
Labels: feature request, xf:metadata

**Comment by SylwesterZarebski** [comment] 2023-05-25 09:39
Thanks, i'll try it.
