### ISSUE TITLE
Text indentation guides

### ISSUE THREAD

**Issue by shtoormanSam** [dbeaver/dbeaver#21224] opened 2023-09-15 06:39 UTC
Could you please add your own vertical indentation guides like https://marketplace.eclipse.org/content/indent-guide ?
This certive-plugin not available now in DBeaver 23.2.0 version (early it was 
at http://www.certiv.net/updates/net.certiv.indentguide.site)
![DBeaver IndentGuidePlugun error](https://github.com/dbeaver/dbeaver/assets/127952519/36947949-1fa7-4383-a6e6-f84403a2c657)

**Comment by E1izabeth** [comment] 2023-09-15 11:30
Thank you for feature request.
We actually already have such issue, so I'm closing it a a duplicate of #13696
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2023-09-15 11:30 UTC
Labels: duplicate
