### ISSUE TITLE
Create table not finishing - Query with 10 subqueries with joins/union/transformation

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#20102] opened 2023-05-25 19:12 UTC
### Description

I have a query built that has 10 subqueries which are running just fine independently...but when I want to create a table it keeps running for full day and half and still not return...

### DBeaver Version

23.0.5

### Operating System

windows

### Database and driver

postgresql 14.0

**Comment by E1izabeth** [comment] 2023-05-25 20:58
Probably, connected with #20060

**Comment by E1izabeth** [comment] 2023-05-25 20:58
Thank you for bug report.

Could you send log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by HrishikeshTangella** [comment] 2023-05-26 13:29
SQL Error [57014]: ERROR: canceling statement due to user request.
Query is taking long time to execute so cancelling to terminate the process.

**Comment by E1izabeth** [comment] 2023-05-26 13:32
Thank you. I'm closing this issue as a duplicate of #20060
You can follow that issue to be notified on updates.

**Closed as not planned by E1izabeth** 2023-05-26 13:32 UTC
Labels: duplicate, xf:sql execution

**Comment by jgrover21** [comment] 2023-05-26 15:03
Is there any solution out there?  I noticed this issue listed.

Respectfully,

Jyoti Grover

**Comment by E1izabeth** [comment] 2023-05-26 15:51
@jgrover21 
Unfortunately, I don't see any workaround. Hope we will fix it soon. The issue is related to JSQLParser library which we use.

**Comment by jgrover21** [comment] 2023-05-26 15:52
Ok thank you.

Respectfully,

Jyoti Grover

**Comment by E1izabeth** [comment] 2023-05-26 16:08
By the way, DBeaver 23.0.0 doesn't have this bug.

**Comment by jgrover21** [comment] 2023-05-26 16:19
Can we revert back to this version?

Respectfully,

Jyoti Grover

**Comment by E1izabeth** [comment] 2023-05-26 16:21
You can find this version in our versions archive and install it, while the issue is not solved
https://dbeaver.io/files/23.0.0/

**Comment by jgrover21** [comment] 2023-05-26 19:44
This is even slower to export.

Respectfully,

Jyoti Grover

**Comment by E1izabeth** [comment] 2023-05-26 19:50
Does your case similar to provided in this comment?
https://github.com/dbeaver/dbeaver/issues/20060#issuecomment-1562949376

**Comment by E1izabeth** [comment] 2023-06-01 11:39
@jgrover21 could you try Early Access version https://dbeaver.io/files/ea/? Does the issue is solved there?
