### ISSUE TITLE
Can't edit table contents - version 6.0.5

### ISSUE THREAD

**Issue by cesarmansur** [dbeaver/dbeaver#6057] opened 2019-06-05 18:10 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 64bit
- DBeaver version: 6.0.5
- Java version: Java 8 update 201
- Additional extensions: DBeaver Office Support version 1.1.46.201905192156 / IndentGuide version 1.5.0.20180902-2249

#### Connection specification:
- Database name and version: Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
- Driver name: ojdbc8.jar / orai18n.jar / xdb6.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Hello.
I can't edit table contents in "Table Data" tab and I'm also facing the same problem in SQL "Result" tab.
All buttons are greyed out.

![image](https://user-images.githubusercontent.com/43681608/58977139-742a7480-879f-11e9-8519-06759f255d30.png)

![image](https://user-images.githubusercontent.com/43681608/58976796-ad161980-879e-11e9-9ee0-7ecffc43f69d.png)

This used to work fine on previous Dbeaver versions.

I've tested the feature on another connection that is Oracle 12c and it worked fine.

I've noticed a warning on every SELECT statement issued in this connection.

![image](https://user-images.githubusercontent.com/43681608/58978833-15ff9080-87a3-11e9-8bf8-e3b35e59e6d1.png)

The same error pops out when clicking on "Constraints" panel or "Foreing Keys" panel or "References" panel in "Table Properties" tab.

![image](https://user-images.githubusercontent.com/43681608/58979003-768ecd80-87a3-11e9-8625-f2ae5d80828c.png)

Could you please check this issue?

#### Include any warning/errors/backtraces from the logs

SQL Error [904] [42000]: ORA-00904: "C"."CONSTRAINT_NAME": invalid identifier

  Error : 904, Position : 708, Sql = SELECT
    c.TABLE_NAME,
    c.CONSTRAINT_NAME,
    c.CONSTRAINT_TYPE,
    c.STATUS,
    c.SEARCH_CONDITION,
    (
        SELECT LTRIM(MAX(SYS_CONNECT_BY_PATH(cname || ':' || NVL(p,1),','))    KEEP (DENSE_RANK LAST ORDER BY curr),',') 
        FROM   (SELECT 
                       col.CONSTRAINT_NAME cn,col.POSITION p,col.COLUMN_NAME cname,
                       ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) AS curr,
                       ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) -1 AS prev
                FROM   ALL_CONS_COLUMNS col 
                WHERE  col.OWNER =:1  AND col.TABLE_NAME = :2  AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME 
                )   GROUP BY cn CONNECT BY prev = PRIOR curr AND cn = PRIOR cn START WITH curr = 1      
        ) COLUMN_NAMES_NUMS
FROM
    ALL_CONSTRAINTS c
WHERE
    c.CONSTRAINT_TYPE <> 'R'
    AND c.OWNER = :3 
    AND c.TABLE_NAME = :4 , OriginalSql = SELECT
    c.TABLE_NAME,
    c.CONSTRAINT_NAME,
    c.CONSTRAINT_TYPE,
    c.STATUS,
    c.SEARCH_CONDITION,
    (
        SELECT LTRIM(MAX(SYS_CONNECT_BY_PATH(cname || ':' || NVL(p,1),','))    KEEP (DENSE_RANK LAST ORDER BY curr),',') 
        FROM   (SELECT 
                       col.CONSTRAINT_NAME cn,col.POSITION p,col.COLUMN_NAME cname,
                       ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) AS curr,
                       ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) -1 AS prev
                FROM   ALL_CONS_COLUMNS col 
                WHERE  col.OWNER =? AND col.TABLE_NAME = ? AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME 
                )   GROUP BY cn CONNECT BY prev = PRIOR curr AND cn = PRIOR cn START WITH curr = 1      
        ) COLUMN_NAMES_NUMS
FROM
    ALL_CONSTRAINTS c
WHERE
    c.CONSTRAINT_TYPE <> 'R'
    AND c.OWNER = ?
    AND c.TABLE_NAME = ?, Error Msg = ORA-00904: "C"."CONSTRAINT_NAME": invalid identifier

  ORA-00904: "C"."CONSTRAINT_NAME": invalid identifier

**Comment by serge-rider** [comment] 2019-06-07 19:33
Duplicate of #5957
Thanks for the bug report anyway.

**Closed by serge-rider** 2019-06-07 19:33 UTC
Labels: bug, duplicate
