### ISSUE TITLE
Google big query (GBQ) connection error after version upgrade (23.1.5)

### ISSUE THREAD

**Issue by fsname** [dbeaver/dbeaver#20936] opened 2023-08-21 13:06 UTC
### Description

We getting error while trying to connect to GBQ with DBeaver Community 23.1.5. Connection from version 23.1.4 works fine! 

Error: 
[Simba][BigQueryJDBCDriver](100004) HttpTransport IO error : Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $..
  Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $.
  Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $.

### DBeaver Version

Community Edition 23.1.5.202308201919

### Operating System

Windows 10

### Database and driver

Database: Google Big Query
Driver: https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.3.3.1004.zip

### Steps to reproduce

I try to connect to GBQ via https://www.googleapis.com/bigquery/v2:443
OAuth type: service-based, using key json. 
Error: [Simba][BigQueryJDBCDriver](100004) HttpTransport IO error : Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $..
  Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $.
  Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $.

**Comment by LonwoLonwo** [comment] 2023-08-21 15:08
Thanks for the bug report.

Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/20935

**Closed as completed by LonwoLonwo** 2023-08-21 15:08 UTC
Labels: duplicate, x:bigquery, xf:connection

**Comment by jakub-sebek** [comment] 2023-08-22 07:19
same on macOS

**Comment by jitvimol** [comment] 2023-08-23 02:45
I upgrade Dbeaver to 23.1.5 and got error as well.  Before I can connect successfully.

Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $.

**Comment by jitvimol** [comment] 2023-08-23 03:16
> I upgrade Dbeaver to 23.1.5 and got error as well. Before I can connect successfully.
> 
> Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $.

Update :  I go to Database > driver manager and force reinstall biqguery driver.  After trying to add connection multiple times,  it works.  After that it show result  what driver its using --> SimbaJDBCDriverforGoogleBigQuery 01.03.03.1004

**Comment by THarris-dev** [comment] 2023-09-01 17:05
Had the same issue after doing the upgrade.  Because it was not obvious what needed to be done and my job needs to get done, I uninstalled the offending version and reinstalled version 23.1.0   Everything works again and I do not plan on upgrading until I know that this particular issue has either been addressed or information on how to address it is made clearer.
