### ISSUE TITLE
Theme doesn't work well 

### ISSUE THREAD

**Issue by Landris18** [dbeaver/dbeaver#15262] opened 2022-01-24 07:55 UTC
On linux devices, there is a conflicts between dbeaver theme and the device theme and causing some texts on the app to not be readable.

**Comment by uslss** [comment] 2022-01-24 19:20
looks like a duplicate of #5869
thanks for the report

**Closed as completed by uslss** 2022-01-24 19:20 UTC
Labels: duplicate, xo:linux

**Comment by Landris18** [comment] 2022-01-30 09:14
Thanks
