### ISSUE TITLE
All dbs are shown even though "Show non-default databases" is not selected

### ISSUE THREAD

**Issue by rngadam** [dbeaver/dbeaver#3831] opened 2018-07-20 08:43 UTC
dbeaver 5.1.3
PostgreSQL (hosted on heroku)

This is a regression.

All databases are listed even though  "Show non-default databases" is not selected.

<img width="858" alt="screen shot 2018-07-20 at 4 41 20 pm" src="https://user-images.githubusercontent.com/538542/42992755-0c5d4e04-8c3c-11e8-8edc-afed6baaf331.png">
<img width="221" alt="screen shot 2018-07-20 at 4 41 07 pm" src="https://user-images.githubusercontent.com/538542/42992757-0c963ac0-8c3c-11e8-830c-372a0a33fe5a.png">

**Comment by rngadam** [comment] 2018-07-20 08:48
This is made worst by:

1) non-alphabetic ordering of databases on the same database server 
2) filter is not applied to the list of databases

<img width="216" alt="screen shot 2018-07-20 at 4 45 37 pm" src="https://user-images.githubusercontent.com/538542/42992917-990b9c02-8c3c-11e8-8526-32f2292cdddf.png">

**Comment by serge-rider** [comment] 2018-07-20 20:00
Duplicate of #3801
Will be fixed in 5.1.4 (you can get  EA version to check this fix)
Thanks for report anyway

**Closed by serge-rider** 2018-07-20 20:00 UTC
Labels: bug, duplicate, x:postgresql
