### ISSUE TITLE
jdk-14 installed via homebrew is not compatible with DBeaver 7.0.1

### ISSUE THREAD

**Issue by mdahlman** [dbeaver/dbeaver#8260] opened 2020-03-25 04:28 UTC
#### System information: 
- Operating system: Mac 10.15.3
- DBeaver version: 7.0.1
The issue is _probably_ not linked to v7.0.1. But that's where I encountered it.

#### Describe the problem you're observing:
jdk-14 installed via homebrew is not compatible with DBeaver 7.0.1 on Mac.

#### Steps to reproduce, if exist:
1. Travel back in time to when jdk-13.jdk was current.
2. `brew cask install java`
3. You now have java 13, and DBeaver works well. You are happy!
4. Travel in time to today (2020-03-24) where jdk-14 is current.
5. `brew cask upgrade java`
or... if you never had the old java-13, then you just install java 14: `brew cask install java`
6. You now have java 14, and DBeaver no longer works. You are very sad.
This was especially confusing to me, because **I was not using java 14** as far as I could tell:
```
$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

Workaround 1:
Force the use of the relevant vm:
```
$ # with java 14 things are bad:
$ /Applications/DBeaver.app/Contents/MacOS/dbeaver
No Java runtime present, requesting install.
$ # but we can work around java 14:
$ /Applications/DBeaver.app/Contents/MacOS/dbeaver -vm /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/../lib/server/libjvm.dylib
```

Workaround 2:
Get rid of java 14
```
$ brew cask info java
java: 14,36:076bab302c7b4508975440c56f6cc26a
https://openjdk.java.net/
/usr/local/Caskroom/java/14,36:076bab302c7b4508975440c56f6cc26a (144B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb
==> Name
OpenJDK Java Development Kit
==> Artifacts
jdk-14.jdk -> /Library/Java/JavaVirtualMachines/openjdk-14.jdk (Generic Artifact)

$ brew cask uninstall java
==> Uninstalling Cask java
==> Backing Generic Artifact 'openjdk-14.jdk' up to '/usr/local/Caskroom/java/14,36:076bab302c7b4508975440c56f6cc26a/jdk-14.jdk'.
Password:
==> Removing Generic Artifact '/Library/Java/JavaVirtualMachines/openjdk-14.jdk'.
==> Purging files for version 14,36:076bab302c7b4508975440c56f6cc26a of Cask java
```

After removing java 14, then DBeaver works as expected. (There is probably a way to revert to java 13... but I have not found it.)
You are happy again!

Note: I opened this as a DBeaver bug. But I'm not really sure whose fault this compatibility issue is. Perhaps it's DBeaver's fault? Maybe Oracle? Homebrew? Apple?

**Comment by uslss** [comment] 2020-03-25 11:01
seems to be duplicate of #8229 .
ticket will be closed.
anyway thanks for the bug report.

**Closed by uslss** 2020-03-25 11:01 UTC
Labels: bug, wait for review
