### ISSUE TITLE
Dbeaver crushes after rdp connection

### ISSUE THREAD

**Issue by wvolkov** [dbeaver/dbeaver#5872] opened 2019-05-07 17:10 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 OS Build 1809 17763.475
- DBeaver version: 6.0.3
- Java version "1.8.0_191"
- No Additional extensions

#### Describe the problem you're observing:
Every time after I connect to my work computer via RDP protocol Dbeaver silently closes itself. The program just opened on remote machine with no running queries. 

#### Steps to reproduce:
1. Open DBeaver on Windows 10 machine A
2. Log out from A
3. From Windows 10 machine B try to connect to machine A via deafult RDP protocol
4. After successfull connect DBeaver app on machine A terminated unexpectedly

**Comment by wvolkov** [comment] 2019-05-09 09:40
After connect it still possible to see that dbeaver was launched in system tray icon:
![image](https://user-images.githubusercontent.com/49549154/57443730-67c20300-7257-11e9-86b6-df83253ac199.png)
After you hover a mose over it - dbeaver icon dissappears immediately

**Comment by mboeringa** [comment] 2019-05-12 10:00
@wvolkov 

You explicitly log out from A before opening a RDP session on machine B. Logging out means closing any running applications, including DBeaver, so I wouldn't expect DBeaver to be running when you open the RDP session from machine B. 

The application remaining visible in the system tray might be a Windows issue, but I don't actually see the DBeaver icon in the screenshot you posted?? Are you sure you aren't confusing it with another similar icon?

I also cannot reproduce such an issue: with DBeaver open on a machine A, but NOT logging out, I can simply connect via RDP from machine B and see DBeaver running on A.

**Comment by wvolkov** [comment] 2019-05-14 11:02
@mboeringa, It was my mistake, not logging out, but locking the remote pc (i.e. Win + L) So the final steps are:

1. Open DBeaver on Windows 10 machine A under User U
2. Lock the machine A (Windows + L)
3. From Windows 10 machine B try to connect to machine A via deafult RDP protocol with credential of user U
4. After successfull connect DBeaver app on machine A terminated unexpectedly

**Comment by mboeringa** [comment] 2019-05-14 17:52
@wvolkov 

I still can't reproduce that crash of DBeaver with a similar setup (both Windows 10 machines of exactly the same build as you have):

- Windows 10 1809 17763.475
- DBeaver 6.0.4

After having locked machine A, I can login via Windows RDP from machine B at machine A, and DBeaver is still open / not crashed when I get back in machine A's screen. No crash.

The only minor difference I see is a slightly newer Java version: 

- Version 8 Update 211 (build 1.8.0_211-b12)

**Comment by halvgud** [comment] 2019-05-28 13:15
it happens to me too, seems that it's an issue with the screen resolution bc it doesnt happens always

**Comment by wvolkov** [comment] 2019-06-20 15:57
I find out how to reproduce this issue. The problem based on resolution: if screen resolution on machine A is larger (or maby smaller) than the one on machine B - dbeaver crushes. I catched an error at Windows 10 event log:

**Comment by PavelKn** [comment] 2019-07-11 10:44
I'm getting the similar issue. Event Viewer is showing the following:

Faulting application name: dbeaver.exe, version: 0.0.0.0, time stamp: 0x5b995959
Faulting module name: MSCTF.dll, version: 10.0.18362.1, time stamp: 0x4bb49ab4
Exception code: 0xc0000005
Fault offset: 0x000000000005de6c
Faulting process id: 0x9c1c
Faulting application start time: 0x01d53326aa744217
Faulting application path: C:\Program Files\DBeaver\dbeaver.exe
Faulting module path: C:\WINDOWS\System32\MSCTF.dll
Report Id: 4c657f13-d412-40ec-8a09-417206411a48
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Karsonito** [comment] 2019-07-16 08:29
It seems clear that eclipse must be updated to fix the issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=543747

Same problem after connect via RDP:
Имя сбойного приложения: dbeaver.exe, версия: 0.0.0.0, метка времени: 0x5b995959
Имя сбойного модуля: MSCTF.dll, версия: 10.0.17763.529, метка времени: 0xbe1133cd
Код исключения: 0xc0000005
Смещение ошибки: 0x000000000004a0a4
Идентификатор сбойного процесса: 0xde4
Время запуска сбойного приложения: 0x01d5366b815c89b6
Путь сбойного приложения: Z:\PortableApps\dbeaver\App_6.1.2\dbeaver.exe
Путь сбойного модуля: C:\WINDOWS\System32\MSCTF.dll
Идентификатор отчета: 8abbac72-7d78-48fe-ae6b-a5e1ee5ecb5c
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:

**Comment by Karsonito** [comment] 2019-07-23 09:12
@serge-rider Please estimate, is it possible to fix it soon?

**Comment by wvolkov** [comment] 2019-08-13 15:21
Today after I have connected from PC at home to my work PC with running dbeaver 6.1.4 a following message appeared:

Collection was modified; enumeration operation may not execute

LOG:
``
Collection was modified; enumeration operation may not execute.
Contact your system administrator.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at System.Windows.Input.StylusWisp.WispLogic.EnableCore()
   at System.Windows.Input.StylusWisp.WispLogic.OnTabletAdded(UInt32 wisptisIndex)
   at System.Windows.Input.StylusWisp.WispLogic.HandleMessage(WindowMessage msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.SystemResources.InvalidateTabletDevices(WindowMessage msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.SystemResources.SystemThemeFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
``

**Comment by ahoman** [comment] 2019-09-06 13:36
I'm also seeing this issue very frequently and agree that it seems related to remote sessions with a different resolution.

I'm running Windows 10 Enterprise (10.0.17763)

Faulting application name: dbeaver.exe, version: 0.0.0.0, time stamp: 0x5b995959
Faulting module name: MSCTF.dll, version: 10.0.17763.1, time stamp: 0x6c634a1d
Exception code: 0xc0000005
Fault offset: 0x0000000000049f6e
Faulting process id: 0x7398
Faulting application start time: 0x01d56361453fadd2
Faulting application path: C:\Program Files\DBeaver\dbeaver.exe
Faulting module path: C:\WINDOWS\System32\MSCTF.dll
Report Id: 74aca7d2-54ff-4a14-829d-902846dfb72f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by twknight** [comment] 2019-10-16 15:42
I can confirm this crash is still happening in 6.2.2 on an RDP connection (actually, Chrome Remote Desktop, which uses the same protocol) with differing screen resolutions between local and remote.

**Comment by maciey** [comment] 2019-10-29 07:59
> 
> 
> I can confirm this crash is still happening in 6.2.2 on an RDP connection (actually, Chrome Remote Desktop, which uses the same protocol) with differing screen resolutions between local and remote.

Same here - Windows 10. 
I believe this happens only when resolution has to be changed

**Comment by Depariel** [comment] 2019-11-05 15:21
Difference in resolution can also mean same resolution per monitor but a different number of monitors. My work PC has two 2560x1440 monitors, and when I RDP from my home desktop with three 2560x1440 monitors, DBeaver crashes silently.

**Comment by maciey** [comment] 2019-11-06 07:20
Very true

**Comment by G-P-Git** [comment] 2019-12-19 20:01
Same here on Windows 10.

Also my font rendering is all messed up if I open it from RDP then go back to a physical desktop login, it gets all blurry and small.

**Comment by DamijanD** [comment] 2020-03-09 14:43
The same happens to me to (with several latest versions including 7.0.0).
PC: 2x 1920*1200 + 1x 1080*1920 (FHD vertical)
RDC resolutions: FHD, 1440p

**Comment by wvolkov** [comment] 2020-03-15 15:32
Hi Guys! I have found a workaround to avoid that issue: you have to minimize dbeaver window **before disconnection** from a remote session, after you will connect again - DBeaver won't crush. I have made an automatic script at windows scheduler that minimizes all the windows before locking PC now it helped me to avoid that problem for some way, in order to do it:

1. Make a text file with a command inside - `powershell (New-Object -ComObject Shell.Application).MinimizeAll()`, save it with extension `.cmd`
2. Create a scheduled task at windows scheduler with trigger "on every lock pc" or something like that
3. Assign launching program action and choose the path to your cmd file from p. 1
4. Save task and reboot pc
5. Now every time you are disconnecting from a remote PC, all opened windows will be minimized, thus, DBeaver will stay alive once you return back afterwards.

Hope that helps

**Comment by Moridin11** [comment] 2020-04-07 13:06
It still crashes for me @wvolkov  when I do that.  

That being said, is this planned for any future release?  I don't see this in anything up to 7.04

**Comment by serge-rider** [comment] 2020-04-10 16:02
Bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=543747 was fixed in the latest Eclipse (2020-03).
We are going to migrate to it in the next dbeaver version.

**Comment by serge-rider** [comment] 2020-04-10 16:15
Fixed in #8413

**Comment by kseniiaguzeeva** [comment] 2020-04-20 08:20
Please reopen, if the issue is still actual in 7.0.3.

**Closed by kseniiaguzeeva** 2020-04-20 08:20 UTC
Labels: bug
