### ISSUE TITLE
DBMS Output not showing in latest version 23.2.5 (Oracle SQL)

### ISSUE THREAD

**Issue by monosabio** [dbeaver/dbeaver#21974] opened 2023-11-23 17:11 UTC
### Description

I recently upgraded to the latest version of DBeaver 23.2.5, and I've encountered an issue where the DBMS OUTPUT is no longer displaying. I have tried forcing the display using Ctrl+Shift+O, but it doesn't work. As a workaround, I had to roll back to version 2.3.4 to regain this functionality.

### DBeaver Version

CE 23.2.5

### Operating System

Windows 10

### Database and driver

Oracle 12.1 Client

### Steps to reproduce

BEGIN
	DBMS_OUTPUT.put_line('TEST');
END;

**Comment by E1izabeth** [comment] 2023-11-23 18:20
Thank you for bug report. I'm closing it as a duplicate of #21902
The fix will be available in the next release.

**Closed as not planned by E1izabeth** 2023-11-23 18:20 UTC
Labels: duplicate, xf:sql execution
