### ISSUE TITLE
The integration panel does not accept the UTF-8 encoding

### ISSUE THREAD

**Issue by ViktorWhite** [dbeaver/dbeaver#22610] opened 2024-01-29 08:10 UTC
### Description

toolbar does not accept UTF-8 encoding
File contents dbeaver.ini
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
-Dosgi.requiredJavaVersion=17
-Dfile.encoding=UTF-8
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.nio.charset=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.base/java.time=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
--add-opens=java.base/jdk.internal.vm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/sun.nio.fs=ALL-UNNAMED
--add-opens=java.base/sun.security.ssl=ALL-UNNAMED
--add-opens=java.base/sun.security.action=ALL-UNNAMED
--add-opens=java.base/sun.security.util=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.jgss=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
--add-opens=java.sql/java.sql=ALL-UNNAMED
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=exe

![toolbar](https://github.com/dbeaver/dbeaver/assets/142132337/94714a6b-f145-483a-9d2e-308d06ddcb38)
![new connection](https://github.com/dbeaver/dbeaver/assets/142132337/4aa320f5-e759-4e0a-8f6a-f72dfad141fa)

### DBeaver Version

23.3.3

### Operating System

Windows 11

### Database and driver

Using Postgree

### Steps to reproduce

the problem occurs when starting the program

### Additional context

The Intsruemtnov panel and the New Connection Wizard window do not accept the UTF-8 encoding

**Comment by LonwoLonwo** [comment] 2024-01-29 09:02
Hello @ViktorWhite 

Could you please try to reset your UI settings? https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings

**Comment by ViktorWhite** [comment] 2024-01-29 09:33
When I press Clear history in dbeaver (aplly and restart), an error appears:
![error](https://github.com/dbeaver/dbeaver/assets/142132337/cfb51d07-8627-4078-a1ed-4d3f901466c5)
When i delete file workbench.xmi the toolbar remains the same (UTF-8 doesn't work) :(

**Comment by LonwoLonwo** [comment] 2024-01-29 10:07
Ok. Did you try to reinstall DBeaver?

**Comment by ViktorWhite** [comment] 2024-01-29 10:11
Yes - UTF-8 doesn't work in the toolbars

**Comment by LonwoLonwo** [comment] 2024-01-29 10:19
Could you please try this answer, then? https://github.com/dbeaver/dbeaver/issues/9455#issuecomment-880192661

**Comment by LonwoLonwo** [comment] 2024-01-29 10:21
And closing as a duplicate of https://github.com/dbeaver/dbeaver/issues/9455

**Comment by ViktorWhite** [comment] 2024-01-29 11:18
Yes, toolbar set UTF-8. YOOOOHOOOO ))) 
Thank you!

**Comment by ViktorWhite** [comment] 2024-01-29 13:43
![new connection](https://github.com/dbeaver/dbeaver/assets/142132337/add2970a-7ac4-4af5-9956-785107724cfb)
Sorry, but I can’t find where to change the font for the images of the new connection
![settings](https://github.com/dbeaver/dbeaver/assets/142132337/9fe18042-8d26-48b9-871c-0b0c03fe51dc)
Changed the selected settings, but it didn't help :(

**Comment by LonwoLonwo** [comment] 2024-01-29 15:22
We have the [original ticket](https://github.com/dbeaver/dbeaver/issues/9455) for this, with the same issue. For now, we have no more workarounds, unfortunately. Maybe it will be fixed in the future.

**Closed as completed by LonwoLonwo** 2024-01-29 15:22 UTC
Labels: duplicate, xo:windows, xf:ui

**Comment by ViktorWhite** [comment] 2024-01-29 15:34
Thanks anyway it's better than it was!
