### ISSUE TITLE
Redis Hash or Set values throws "Unsupported key type: none"

### ISSUE THREAD

**Issue by gencer** [dbeaver/dbeaver#4540] opened 2018-11-05 14:01 UTC
DBeaver fails to show Redis `HASH` and `SET` values.

When I connect to Redis v5.0 Server via DBeaver EE (Trial), It connects and lists all available databases and keys successfully. However, `HASH` and `SET` data cannot be opened.

Does it not support `HASH` and `SET` (if not when) or is a bug? Redis + Elasticsearch will be my buying reasons.

```
Query execution failed

Reason:
Unsupported key type: none
```

Target: Redis v5/v4
OS: Debian 9 x64
DBeaver: 5.2.2 EE

**Comment by serge-rider** [comment] 2018-11-12 21:33
DBeaver supports both Hash and Set values (as they are the most standard key types). However we didn't yet tested this with Redis 5. But it works fine with standalone Redis 4.x.

Do you use standalone Redis or some kind of service (like AWS Elastic Cache)?

**Comment by gencer** [comment] 2018-11-13 06:49
I'm using standalone Redis.

**Comment by serge-rider** [comment] 2018-11-14 09:05
Just tested on Redis 5 and hash/set keys seems to be working ok.
Could you provide a bit more details? 
Some steps to reproduce would be helpful.  

Also, if possible, attach error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by dariuszjastrzebski** [comment] 2019-02-05 16:12
I have the similar issue. 
Redis server v=4.0.9
DBeaver EE 5.3.3
Exception Stack Trace:
```
org.jkiss.dbeaver.model.exec.DBCException: Unsupported key type: none
	at com.dbeaver.ee.redis.exec.RedisKeyStatement.executeStatement(RedisKeyStatement.java:68)
	at com.dbeaver.ee.redis.model.RedisKey.readData(RedisKey.java:247)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:103)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:101)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Session Data:

```eclipse.buildId=unknown
java.version=1.8.0_152
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=pl_PL
Framework arguments:  -keyring /Users/user/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/user/.eclipse_keyring
```

I hope it will be helpful

**Comment by serge-rider** [comment] 2019-11-23 21:21
This bug was fixed in 6.2. Please verify.

**Comment by serge-rider** [comment] 2019-11-24 22:05
Fixed for "folder" keys (they are not real keys but fake ones for hierarchy organization)

**Comment by uslss** [comment] 2019-11-25 11:32
verified

**Closed by uslss** 2019-11-25 11:32 UTC
Labels: bug, ee, question, x:redis
