### ISSUE TITLE
[PostgreSQL] Invalid DDL shown for generated columns

### ISSUE THREAD

**Issue by 2-5** [dbeaver/dbeaver#11658] opened 2021-03-09 11:05 UTC
- DBeaver version: 21.0.0
- Database name and version: PostgreSQL 13.2
- Driver name: PostgreSQL JDBC Driver

#### Describe the problem you're observing:
DBeaver shows the wrong DDL (table/properties/DDL) for a table containing a generated column.

Table was created with this column definition:
```sql
is_active boolean NOT NULL GENERATED ALWAYS AS (state IN ('open', 'untriggered')) STORED
```

psql shows:
```sql
is_active boolean not null generated always as (state = ANY (ARRAY['open'::public.state_t, 'untriggered'::public.state_t])) stored
```

DBeaver shows:
```sql
is_active bool NOT NULL DEFAULT state = ANY (ARRAY['open'::public.state_t, 'untriggered'::public.state_t]),
```

DBeaver implies that the column just has a default and that is wrong.

https://www.postgresql.org/docs/current/ddl-generated-columns.html

**Comment by uslss** [comment] 2021-03-09 13:23
thanks for the report
closed as a duplicate of #7861

**Closed as completed by uslss** 2021-03-09 13:23 UTC
Labels: x:postgresql, duplicate
