### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 

### ISSUE THREAD

**Issue by badnotes** [dbeaver/dbeaver#18930] opened 2023-02-02 02:25 UTC
### Description

Click connections and raise Error:

```

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

原因：
 java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
```

![圖片](https://user-images.githubusercontent.com/3199446/216215485-238f9200-48ef-4b3e-ab93-f44cdc132d3b.png)

### DBeaver Version

dbeaver-ce-22.3.X

### Operating System

Windows 11

**Comment by E1izabeth** [comment] 2023-02-02 06:04
Please send the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by badnotes** [comment] 2023-02-13 06:07
!SESSION 2023-02-13 14:04:39.638 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-02-13 14:04:42.939
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-02-13 14:04:45.492
!MESSAGE Error loading datasource config from file://C:\Users\jun.wan\AppData\Roaming\DBeaverData\workspace6\pro\.dbeaver\data-sources.json
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-02-13 14:04:45.492
!MESSAGE java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-02-13 14:04:45.492
!MESSAGE Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
!STACK 0
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:395)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:182)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144)
	at com.google.gson.Gson.fromJson(Gson.java:1058)
	at com.google.gson.Gson.fromJson(Gson.java:1016)
	at org.jkiss.dbeaver.model.data.json.JSONUtils.parseMap(JSONUtils.java:306)
	at org.jkiss.dbeaver.registry.DataSourceSerializerModern.parseDataSources(DataSourceSerializerModern.java:389)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:741)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:697)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:676)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.<init>(DataSourceRegistry.java:95)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.<init>(DataSourceRegistry.java:88)
	at org.jkiss.dbeaver.registry.BaseProjectImpl.createDataSourceRegistry(BaseProjectImpl.java:193)
	at org.jkiss.dbeaver.registry.BaseProjectImpl.getDataSourceRegistry(BaseProjectImpl.java:185)
	at org.jkiss.dbeaver.model.navigator.DBNProject.readChildNodes(DBNProject.java:190)
	at org.jkiss.dbeaver.model.navigator.DBNResource.getChildren(DBNResource.java:213)
	at org.jkiss.dbeaver.model.navigator.DBNProject.getChildren(DBNProject.java:169)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorContentProvider.getChildren(DatabaseNavigatorContentProvider.java:123)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1445)
	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:350)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:850)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:638)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:839)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:611)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:790)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(AbstractTreeViewer.java:1565)
	at org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeViewer.java:897)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorTree$4.handleTreeExpand(DatabaseNavigatorTree.java:399)
	at org.eclipse.jface.viewers.AbstractTreeViewer$3.treeExpanded(AbstractTreeViewer.java:1577)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:136)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7585)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5799)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1961)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5367)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4801)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5028)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1542)
	at org.eclipse.swt.widgets.Tree.WM_LBUTTONDOWN(Tree.java:6484)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4781)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6016)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5028)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:292)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-02-13 14:04:45.510
!MESSAGE Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-02-13 14:04:45.510
!MESSAGE Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
!STACK 0
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:395)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:182)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144)
	at com.google.gson.Gson.fromJson(Gson.java:1058)
	at com.google.gson.Gson.fromJson(Gson.java:1016)
	at org.jkiss.dbeaver.model.data.json.JSONUtils.parseMap(JSONUtils.java:306)
	at org.jkiss.dbeaver.registry.DataSourceSerializerModern.parseDataSources(DataSourceSerializerModern.java:389)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:741)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:697)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:676)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.<init>(DataSourceRegistry.java:95)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.<init>(DataSourceRegistry.java:88)
	at org.jkiss.dbeaver.registry.BaseProjectImpl.createDataSourceRegistry(BaseProjectImpl.java:193)
	at org.jkiss.dbeaver.registry.BaseProjectImpl.getDataSourceRegistry(BaseProjectImpl.java:185)
	at org.jkiss.dbeaver.model.navigator.DBNProject.readChildNodes(DBNProject.java:190)
	at org.jkiss.dbeaver.model.navigator.DBNResource.getChildren(DBNResource.java:213)
	at org.jkiss.dbeaver.model.navigator.DBNProject.getChildren(DBNProject.java:169)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorContentProvider.getChildren(DatabaseNavigatorContentProvider.java:123)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1445)
	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:350)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:850)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:638)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:839)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:611)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:790)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(AbstractTreeViewer.java:1565)
	at org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeViewer.java:897)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorTree$4.handleTreeExpand(DatabaseNavigatorTree.java:399)
	at org.eclipse.jface.viewers.AbstractTreeViewer$3.treeExpanded(AbstractTreeViewer.java:1577)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:136)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7585)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5799)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1961)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5367)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4801)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5028)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1542)
	at org.eclipse.swt.widgets.Tree.WM_LBUTTONDOWN(Tree.java:6484)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4781)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6016)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5028)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:292)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by Destrolaric** [comment] 2023-02-16 13:45
`file://C:\Users\jun.wan\AppData\Roaming\DBeaverData\workspace6\pro.dbeaver\data-sources.json`
Could you send the first two lines of the file? It looks like something wrong with it.

**Comment by badnotes** [comment] 2023-02-24 02:36
![image](https://user-images.githubusercontent.com/3199446/221078164-eb3c9387-900e-4d4f-836f-68333e81f01f.png)

It's messy code.

This is OK on Version 22.1.0, but I can not open a project on 22.3.X

**Comment by ShadelessFox** [comment] 2023-03-02 14:05
Hello @badnotes,

It looks like you used one of the PRO products before and enabled [project encryption](https://github.com/dbeaver/dbeaver/wiki/Project-security). Can you confirm that?

Using the project in the community edition is only possible by first disabling project encryption in any of the PRO products.

Please let me know if you have any questions left.

**Comment by E1izabeth** [comment] 2023-04-03 08:42
It's been a long time since no update here, so I'm closing it.
Please let me know, if this issue is still actual and provide additional info.

**Closed as completed by E1izabeth** 2023-04-03 08:42 UTC
Labels: wait for response

**Comment by shatrudhanbind** [comment] 2025-07-16 19:00
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at tg.abhishek.real.rahul.HomePageActivity$6.onResponse(Unknown Source:35)
	at tg.abhishek.real.rahul.RequestNetworkController$3$2.run(Unknown Source:31)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8249)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 12 more
