### ISSUE TITLE
v21.1.0 unable to connect to legacy MSSQL servers

### ISSUE THREAD

**Issue by daggilli** [dbeaver/dbeaver#12695] opened 2021-06-02 01:12 UTC
#### System information: 
- Operating system (distribution) and version
  Ubuntu 18.04LTS
- DBeaver version
  21.1.0
- Java version
  openjdk-11-jdk 11.0.11+9-0ubuntu2~18.04
- Additional extensions
  N/A

#### Connection specification:
- Database name and version
  Microsoft SQL Server 2008
- Driver name
  MS SQL Server / SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  NO

#### Describe the problem you're observing:
Regression: upgrading from version 21.0.5 to version 21.1.0 results in a failure to connect to the server.

#### Steps to reproduce, if exist:
Connect to an instance of MS SQL server 2008 using v21.1.0 of DBeaver

#### Include any warning/errors/backtraces from the logs
  "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]"

It appears that the version of TLS that the remote server is requesting is no longer supported by DBeaver. Downgrading to 21.0.5 fixes the problem, but this is clearly not an ideal approach.

No combination of TLS versions in the driver configuration resolved the problem in v21.1.0. In v21.0.5, the TLS version is set to TLSv1.1, but selecting this option in v21.1.0 did not work.

**Comment by uslss** [comment] 2021-06-02 07:51
seems to be a duplicate of #12668 
Will be fixed in 21.1.1.
Anyway, thanks for the report

**Closed as completed by uslss** 2021-06-02 07:51 UTC
Labels: duplicate

**Comment by iateadonut** [comment] 2021-10-14 02:05
bug is back in 21.2.2
