### ISSUE TITLE
Result Panel: Data Grid view bug

### ISSUE THREAD

**Issue by mojamedali** [dbeaver/dbeaver#5684] opened 2019-04-08 18:07 UTC
After the new update, data grid view on result panel, doesn't work. I'm using Eclipse plug-in version 6.0.2.201904071344

**Comment by alesc2000** [comment] 2019-04-09 07:32
May it be the same problem as #5680 ?

**Comment by serge-rider** [comment] 2019-04-10 04:42
@mojamedali also please post information about your environment.

**Comment by fraxen** [comment] 2019-04-10 07:33
I am also seeing this:
----
System information:

    Windows 10 1709
    Eclipse Oxygen.3a Release (4.7.3a)
    DBeaver Eclipse plugin 6.0.2.201904071344
    Java version: 1.8.0_181

Connection specification:

    I am seeing the same problem with Postgres, Oracle and Sqlite connections

The display of the data grid is not working, clicking around reveals some tooltips and fields that are not displayed properly.
![image](https://user-images.githubusercontent.com/429171/55859947-6b3c6e80-5b73-11e9-8f1c-372617303f39.png)
Workaround: shift to text/plain text
![image](https://user-images.githubusercontent.com/429171/55860064-b22a6400-5b73-11e9-82d6-25a94aa2e53c.png)

**Comment by fraxen** [comment] 2019-04-10 07:35
Think my issue is a dupe of #5679 ...

**Comment by fraxen** [comment] 2019-04-10 07:52
Just upgraded Eclipse, and the problem went away:
```
Version: 2019-03 (4.11.0)
Build id: 20190314-1200
```

**Comment by serge-rider** [comment] 2019-04-10 11:49
It is a duplicate of #5679.
Thanks for the bug report anyway.

**Closed by serge-rider** 2019-04-10 11:49 UTC
Labels: bug, duplicate
