### ISSUE TITLE
Can't create reference or Foreign keys 

### ISSUE THREAD

**Issue by harrisyn** [dbeaver/dbeaver#3998] opened 2018-08-14 16:34 UTC
After upgrading to version 5.1.5
I am unable to add foriegn key references to existing tables.

rollback to 5.1.4 and all is well

**Comment by serge-rider** [comment] 2018-08-15 22:04
Duplicate of #3984.
Thanks for report anyway

**Closed by serge-rider** 2018-08-15 22:04 UTC
Labels: bug, duplicate
