### ISSUE TITLE
export table to csv, wrong format

### ISSUE THREAD

**Issue by helppass** [dbeaver/dbeaver#2896] opened 2018-01-30 08:43 UTC
version: 4.3.3.1 CE

Export table data to csv.
But the comma become "null"

![default](https://user-images.githubusercontent.com/12808832/35556143-6f99abf2-05dc-11e8-99fa-a97b44eb8df2.png)

![default](https://user-images.githubusercontent.com/12808832/35556148-72d9b87a-05dc-11e8-977c-a146bf49b087.png)

![default](https://user-images.githubusercontent.com/12808832/35556162-7c08d688-05dc-11e8-9d97-2cbd451f3648.png)

![default](https://user-images.githubusercontent.com/12808832/35556170-81508a28-05dc-11e8-94f1-018071f7eef4.png)

The table ddl :
CREATE TABLE t_parent_student_link (
id bigint(11) NOT NULL AUTO_INCREMENT,
parent_id bigint(19) DEFAULT NULL,
relation_ship bigint(10) DEFAULT NULL COMMENT '1,0',
student_id bigint(19) DEFAULT NULL,
create_time varchar(14) COLLATE utf8_bin DEFAULT NULL,
PRIMARY KEY (id),
UNIQUE KEY uk_parent_student_link_1 (parent_id,student_id),
KEY idx_parent_student_link_parent_id (parent_id),
KEY idx_parent_student_link_student_id (student_id)
) ENGINE=InnoDB AUTO_INCREMENT=453485 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

The export csv:
"id"null"parent_id"null"relation_ship"null"student_id"null"create_time"
566null565null7null564null
581null580null1null579null
735null565null7null527null
746null745null7null693null
753null752null7null686null
768null570null1null690null
...

**Comment by serge-rider** [comment] 2018-01-30 11:25
I can't reproduce this. 
Did you change call delimiter before? Or this is the default configuration?

**Comment by helppass** [comment] 2018-01-30 14:08
step:
1. use default setting, format wrong
2. change the delimiter, format ok
now it's ok
maybe my workspace is create too early;

**Comment by serge-rider** [comment] 2018-02-01 17:40
Closing as non-reproducible (perhaps config was corrupted during version upgrade or something).

**Closed by serge-rider** 2018-02-01 17:40 UTC
Labels: bug, can't reproduce, question

**Comment by serge-rider** [comment] 2018-02-02 18:07
Can't reproduce with fresh workspace. Maybe this is a problem of config migration.
In any case - closing as non-reprodcible. 
Please reopen in case of new info.

**Comment by it-techy4life** [comment] 2019-04-17 14:53
I started getting the same error when exporting! I removed the comma from the "DELIMITER " line in Format settings and I was able to put data into a csv file correctly without the nulls. ![image](https://user-images.githubusercontent.com/49724868/56297681-a3006480-60e5-11e9-8875-0182ec311086.png)

**Comment by joshchernoff** [comment] 2019-10-17 16:02
I'm seeing this issue and when I tired to follow the direction above it created yet another bug. 
<img width="606" alt="Data_Transfer_and_DBeaver_6_2_2_-__SQL_Server_-_master__Script-9" src="https://user-images.githubusercontent.com/961877/67026529-c324d680-f0bc-11e9-9331-4f4e37b3b098.png">

**Comment by ramseytm** [comment] 2020-11-04 19:48
Just an FYI, a member on my team ran into this same issue in CE version 7.2.4. He was attempting to change the delimiter to a tab (among some other changes) when it happened so hard to track down what exactly caused it. He updated dbeaver to version 7.2.4 hoping it would resolve it and it reverted it to default ',' character but still caused the export to insert "null" as the delimiter like reported above. Also like above, removing the ',' value from the delimiter setting and running the export fixed the issue.

I'm guessing he had a special character inserted along with the comma or something which caused the issue.
