### ISSUE TITLE
DBeaver v7.3.1 Community Edition on Windows 10 Pro not able to start up

### ISSUE THREAD

**Issue by richschaaf** [dbeaver/dbeaver#10852] opened 2021-01-02 23:34 UTC
I upgraded my DBeaver Community Edition on Windows 10 Pro from 7.3.0 -> 7.3.1.

When I first attempted to start the new version of DBeaver, I was prompted to update my DBeaver Office Support.

After updating the DBeaver Office Support, DBeaver got stuck in a loop of:
* Attempting to restart
* Showing the splash screen
* Attempting to restart
* ...

The problem persisted across a reboot of my laptop.

I uninstalled v7.3.1 and installed v7.3.0 and DBeaver is working again for me.

**Comment by btanner2** [comment] 2021-01-04 10:34
Same error here.

**Comment by serge-rider** [comment] 2021-01-04 11:01
Did you install DBeaver for all users or for the current user?

Could you try to delete folder `.eclipse` in your user home and then retry?

**Comment by richschaaf** [comment] 2021-01-05 03:18
@serge-rider I installed for all users.

I use Eclipse for SW development, so instead of deleting my .eclipse folder, I moved all of my “.eclipse\org.jkiss.dbeaver.product_<version>_win32_win32_x86_64” folders out of my .eclipse folder and into a subfolder.

I was then able to install DBeaver v7.3.1 without incident.  My upgraded DBeaver did not include the “DBeaver – Office support” software so I attempted to install that package.  After the install finished, I was back in the state of DBeaver not being able to start up.  When I attempt to launch DBeaver, it shows the splash screen, stops, shows the splash screen, stops, …  This continues until either I manage to kill the DBeaver process using Task Manager (or until I uninstall the program).

**Comment by rolivares** [comment] 2021-02-16 21:51
upgrading to v7.3.5 causes same error , I've downgrade to 7.3.4 (after delete all related files) works for me.

uninstalling and reinstalling v7.3.5 did not work

**Comment by Doxxxxxx** [comment] 2021-02-19 14:45
Hello,

Same probleme here.
What I do to "fix" the problem is starting another instance of Dbeaver (via Windows Start menu for example) and click on "discard" when it says it can't lock workspace.
And I do it after each dbeaver update.

**Comment by btanner2** [comment] 2021-02-22 10:27
I just found the solution. I just copied the zip content from dbeaver download into the existing dbeaver directory. This caused the endless loop after I started dbeaver. After creating a new directory, dbeaver starts normally. The settings are saved somehwere else, so nothing was lost.

Problem solved.

**Comment by Charles-II** [comment] 2021-04-09 07:45
Same problem for me.  Installed for all users. It is also installed Eclipse IDE 2020-12(4.18.0)
I have just installed dbeaver-ce-21.0.2-x86_64 and it started then I have installed DBeaver Office support. At DBeaver restart it stucked on the splash screen. I have uninstalled Dbeaver, removed all the files in %APPDATA%, and re-installing it I have also selected to reset settings but didn't fixed the problem.
At the end I have launched DBeaver with Administrator rights and it started but it still doesn't work without Admin rights.
I don't know how to fix the problem.
Rolled back to version 21.0.1 and it worked until I have installed DBeaver Office plugin version 1.1.92. I need Office plugin to export from query to XLSX format.
MORE INFO
I have to remove folders org.jkiss.dbeaver.product_21.0.1_* and org.jkiss.dbeaver.product_21.0.2_* from .eclipse folder to be able to use DBeaver again. Why do you not remove this folder when Dbeaver is installed with reset settings option set? 
Why DBeaver falls in an infinite start loop when this problem happens? It is very difficult to stop and CPU usage increases a lot.
EDIT
At the end I succeded to have a working DBeaver with Office extension. I had a working DBeaver 21.0.1 with Office plugin 1.1.89 installed on a Windows7 O.S. and I copied its org.jkiss.dbeaver.product_21.0.1_* folder to the Windows 10 O.S. and then installed DBeaver 21.0.1 and it is working like a charm.

**Comment by stevieJ** [comment] 2021-07-06 10:22
Confirmation issue still exists on DBeaverEE 21.1 (2021-07-06)

* Windows 10
* Java (_bundled Java 11_)
* `dbeaver-ee-21.1.0-x86_64-setup.exe` installer
* Installed for **ALL** users
* `TERMINAL` plugin

Purge all DBeaver & Eclipse artifacts, clean install all OK, install `TERMINAL` from the Eclipse Install New Software ... infinite loop (_splash screen grabs focus, then crashes ... repeat c. 1/sec with different process id_).

Uninstall - reinstall only fixes if you **also delete** the `.eclipse` directory in the user profile

Fixed by installing ONLY for current user (_in_ `C:\Users\<profile>\AppData\Local\DBeaverEE\`). No issue with installing `TERMINAL` plugin at this point.

**Comment by swiffer** [comment] 2021-07-20 15:27
Yes - same here. Start-Up loop after installing SSHJ / Office Plugin when DBeaver is installed System-wide. Switched to User Install now which is working fine (at least at the moment).

**Comment by NehalDamania** [comment] 2021-09-01 03:31
Same issue. This workaround from another issue comment helps: [comment link](https://github.com/dbeaver/dbeaver/issues/4791#issuecomment-844077570)
The workaround mentioned in the comment is:

1. upgrade Dbeaver
2. Start Dbeaver and install Office plugin, without automatic restart. Close Dbeaver.
3. Start DBeaver "as administrator" and install Office plugin, without automatic restart. Close Dbeaver.
4. Start DBeaver "as administrator". Close Dbeaver.
5. Start DBeaver normally

**Comment by E1izabeth** [comment] 2024-11-28 16:58
Is this issue still actual?

**Comment by E1izabeth** [comment] 2024-12-30 07:54
We expect that the issue is not actual anymore. So, I'm closing it

**Closed as not planned by E1izabeth** 2024-12-30 07:54 UTC
Labels: xo:eclipse, wait for response
