### ISSUE TITLE
DBeaver 7.0.2 - unable to refresh/install Git Support

### ISSUE THREAD

**Issue by RichardTarna** [dbeaver/dbeaver#8355] opened 2020-04-06 13:49 UTC
#### System information: 
- Windows 10 64bit 1909
- 7.0.2
- DBeaver Git support

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Can't update Git support after upgrading from version 7.0.1

#### Steps to reproduce, if exist:
Upgrade dbevaer from version 7.0.1, refresh Git extension

#### Include any warning/errors/backtraces from the logs

Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver Git support 1.0.18.202004051509 (org.jkiss.dbeaver.git.feature.feature.group 1.0.18.202004051509)
  Software currently installed: DBeaver 7.0.2.202004051509 (org.jkiss.dbeaver.core.product 7.0.2.202004051509)
  Only one of the following can be installed at once: 
    Apache Ant minimum package 1.10.0 (org.apache.ant 1.10.0)
    Apache Ant 1.10.7.v20190926-0324 (org.apache.ant 1.10.7.v20190926-0324)
  Cannot satisfy dependency:
    From: Git integration for Eclipse - UI 5.6.0.201912101111-r (org.eclipse.egit.ui 5.6.0.201912101111-r)
    To: osgi.bundle; org.apache.ant [1.10.5,2.0.0)
  Cannot satisfy dependency:
    From: DBeaver Community Edition 7.0.2.202004051509 (org.jkiss.dbeaver.ce.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [7.0.2.202004051509,7.0.2.202004051509]
  Cannot satisfy dependency:
    From: DBeaver 7.0.2.202004051509 (org.jkiss.dbeaver.core.product 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [7.0.2.202004051509,7.0.2.202004051509]
  Cannot satisfy dependency:
    From: DBeaver Git support 1.0.18.202004051509 (org.jkiss.dbeaver.git.feature.feature.group 1.0.18.202004051509)
    To: org.eclipse.equinox.p2.iu; org.eclipse.egit.ui [5.6.0.201912101111-r,5.6.0.201912101111-r]
  Cannot satisfy dependency:
    From: DBeaver RCP 2.1.105.202004051509 (org.jkiss.dbeaver.rcp.feature.feature.group 2.1.105.202004051509)
    To: org.eclipse.equinox.p2.iu; org.apache.ant [1.10.0,1.10.0]
  Cannot satisfy dependency:
    From: DBeaver Standalone 7.0.2.202004051509 (org.jkiss.dbeaver.standalone.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.rcp.feature.feature.group [2.1.105.202004051509,2.1.105.202004051509]

**Comment by kseniiaguzeeva** [comment] 2020-04-06 14:13
Thank you for the bug report.

**Comment by serge-rider** [comment] 2020-04-06 15:26
Duplicate of #8345

**Closed by serge-rider** 2020-04-06 15:26 UTC
Labels: bug, duplicate
