### ISSUE TITLE
Active schema changes without notice after disconnection

### ISSUE THREAD

**Issue by webian** [dbeaver/dbeaver#16520] opened 2022-05-18 08:05 UTC
#### System information: 
Windows 10 Enterprise 21H2
DBeaver 22.0.4.202205011839
No additional extensions

#### Connection specification:
10.1.48-MariaDB-0ubuntu0.18.04.1
MariaDB
SSH Tunnel

#### Describe the problem you're observing:
Active catalog/schema dropdown not updated after disconnection while in reality the SQL executed after disconnection are executed on the default DB. This could lead to data loss because the query is not executed in the intended database.

#### Steps to reproduce, if exist:
1. Open an SQL editor and select a not default database
2. Write a query
3. Execute the query on the not default database
4. Disconnect and reconnect
5. Execute the query again, this time will be executed on the default database

**Comment by Matvey16** [comment] 2022-05-25 11:53
Hello @webian . Did you manually disconnect and reconnect to the database? I was not able to reproduce this. Could you perhaps record a short video of the actions that lead to this.

**Comment by GuenterSch** [comment] 2022-05-28 11:40
Hello,
I have the same behaviour with a Snowflake / MSSQL Server connection.
**I suppose, the problem is, that the connection of the Tab (SQL Editor) does not save the schema or the schema will not be set after a reconnection.
But this is essential for development**, else the objects may be stored in a wrong schema.
The same behaviour is after a new start of DBeaver.
BR
Günter

Example:
![DBeaver-TabConnection](https://user-images.githubusercontent.com/99535516/170824028-7ffb96e2-4862-4d69-816f-e2cda7f2b09e.png)

**Comment by GuenterSch** [comment] 2022-05-28 11:42
![DBeaver-TabConnection](https://user-images.githubusercontent.com/99535516/170823956-71f279c4-5f67-4104-8f39-b9440a5610db.png)

**Comment by GuenterSch** [comment] 2022-05-28 11:43
![DBeaver-TabConnection](https://user-images.githubusercontent.com/99535516/170823992-1ff12dc0-ee33-4d98-b0cd-9d15c21ca811.png)

**Comment by LonwoLonwo** [comment] 2022-06-08 10:37
Can you please check this setting in the Preferences?

![2022-06-08 13_32_07-Preferences](https://user-images.githubusercontent.com/45152336/172596300-c1360e1d-b19e-4be4-811e-a32379d6958f.png)

Usually DBeaver restores last active schema for the SQL Editor if this setting is enabled.

**Comment by GuenterSch** [comment] 2022-06-08 11:04
Hello Anastasiya,
S**ave/restore active schema** is already set in my configuration.
BR
Günter

**Comment by webian** [comment] 2022-06-08 11:32
Same for me, already set.

**Comment by webian** [comment] 2022-06-08 11:33
> Hello @webian . Did you manually disconnect and reconnect to the database? I was not able to reproduce this. Could you perhaps record a short video of the actions that lead to this.

Not manually, it happens when I'm using a mobile connection that sometimes disconnects and reconnects.

**Comment by Matvey16** [comment] 2022-06-15 10:48
@GuenterSch Thank you. I reproduced it on Snowflake and also found that schema list in dropdown is inconsistent, sometimes it shows correct list of schemas, sometimes it shows schemas from other databases and so,etimes it doesn't show anything at all.

![dbeaver_YBsQbqGIMl](https://user-images.githubusercontent.com/82543000/173809255-39918ff2-7f16-453d-b04e-637c39bca7ab.gif)

After disconnect it uses the default schema.
Do you have any schema name in connection settings?

**Comment by GuenterSch** [comment] 2022-06-15 11:05
@Matvey16 Yes I have a schema default in the connection set.
But, if the tab is alread open, I disconnect it, then I connect it again. The database will be set correct, but it does not set the last used schema nor the default schema in the connection settings.
I have open more than one connection with different schemas. Therefore, after a reconnect it would be importent, that it set the last used schema of the connection.

**Comment by serge-rider** [comment] 2022-10-27 20:57
We keep script properties in project-metadata.json. In some cases resource path was not normalized (e.g. it had a leading slash). In these cases scipt properties were read incorrectly.

Should be fixed by now.

**Closed as completed** 2022-10-28 12:27 UTC
Labels: x:maria, xf:sql, x:snowflake, sp:2
