### ISSUE TITLE
Database Connection timeout notification in 23.3.4 is missing in 23.3.5

### ISSUE THREAD

**Issue by haufs** [dbeaver/dbeaver#23017] opened 2024-02-29 16:58 UTC
### Description

What happened to the popup in 23.3.4?
![image](https://github.com/dbeaver/dbeaver/assets/117753713/f6bab8dc-819d-4004-8124-2d527083cff7)

It appears to have been removed from 23.3.5

### DBeaver Version

Community Edition version 23.3.5

### Operating System

Windows 10

### Database and driver

PostgreSQL standard driver

### Steps to reproduce

-open DBeaver
-db connections established
-after an hour or so in 23.3.4, the popup would be thrown

**Comment by E1izabeth** [comment] 2024-03-06 11:47
Could you check preferences here?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/e065fc75-4842-46f2-864e-5b83dd95e0db)

**Comment by E1izabeth** [comment] 2024-03-06 11:48
We haven't changed something about notifications

**Comment by haufs** [comment] 2024-03-06 13:37
Hi Elizabeth, I have the same settings.
![image](https://github.com/dbeaver/dbeaver/assets/117753713/c0fb0712-7ee1-4203-8896-5e9a7619db81)

I now have version 24.0.0 which acts the same as 23.3.5.

Was there something regarding db connections in 23.3.4 that has changed in 23.3.5 and 24.0.0?

thank you

**Comment by E1izabeth** [comment] 2024-03-06 14:07
Only these changes in 23.3.5 might be connected to your issue #22721

I tried to reproduce the issue and seems everything works fine for me. I get this notification
![image](https://github.com/dbeaver/dbeaver/assets/28875055/c41f2c5e-3ceb-4242-bb24-b48483f3be46)

Only these changes in 23.3.5 might be connected to your issue #22721 As there was some issue with the setting save, could you try unchecking `Close idle connections after (seconds)` setting, Apply changes, then open settings again and check it back?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/18e8e53f-ab29-4086-9de4-b898002596b8)

**Comment by haufs** [comment] 2024-03-06 14:33
Thank you Elizabeth, I've performed those steps and will monitor.

**Comment by E1izabeth** [comment] 2024-04-01 06:24
It's been a while since no update here. If the issue is still actual please let me know.

**Comment by haufs** [comment] 2024-04-01 15:25
Hello Elizabeth, apologies, I failed to comment back after I would try the steps you provided.
The steps did not resolve the issue.
I still have the issue in version 24.0.1
Has anyone else reported the issue?
thank you very much

**Comment by E1izabeth** [comment] 2024-04-02 18:10
We haven't received other reports

**Comment by haufs** [comment] 2024-04-02 18:17
Thank you Elizabeth, all users (250 or so) within Corteva Agriscience have the issue. :)
We'd be SUPER happy if that popup could be added back.
thank you

**Comment by arhayka** [comment] 2024-04-03 13:05
Thank you, we'll try to reproduce it.

**Comment by Matvey16** [comment] 2024-04-16 10:15
I reproduced this. It probably is reproducable in other cases, but for me it was possible like this.
1. Enable disconnect for Idle connections
2. Close all editor tabs
3. Restart DBeaver
4. Select connection in the navigator and click connect
5. Minimize Dbeaver

After set time notification won't appear, but if you open DBeaver you would see that the connection is already disconnected

**Comment by Matvey16** [comment] 2024-04-22 16:36
@haufs I can't reproduce it anymore on 24.0.3 Can you check if maybe it has been fixed in your case too?

**Comment by haufs** [comment] 2024-04-22 16:39
Thank you Matvey16, we have discovered that it's an issue on our side with Zscaler Internet Security.
Please close this ticket.
Thank you for the quick response. :)

**Closed as completed** 2024-04-22 17:28 UTC
Labels: sp:2, xf:ui, xf:connection, xp:normal
