### ISSUE TITLE
Sometimes DBeaver starts consuming CPU heavily using one of its threads in an infinite loop

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35301] opened 2024-08-21 21:53 UTC
### Description

It leads to the call from the system library: ucrtbase.dll!configthreadlocale+0x50
At that moment, I do nothing in DBeaver.
This thread will never end (looks like it is an infinite loop, I waited more than a hour and it was still in progress)
Here is what I see in ProcExp:

https://github.com/user-attachments/assets/5a7cdd1d-a177-4f6a-b87c-2467836353b3

Here is thread dump:

[dbeaver-thread-dump.txt](https://github.com/user-attachments/files/16700376/dbeaver-thread-dump.txt)

### DBeaver Version

Community Edition 24.1.5-202408122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

- open many tabs (about 20)
- work for some time in DBeaver (the whole day long)
- when fans start working due to CPU pressure, open ProcExp and check that one thread do something heavily
- you can Suspend this thread in ProcExp in order to avoid high resource consumption temporary, but the application starts unresponsive after a few seconds
- after some time you can resume the thread and the consumption proceed
- after closing/reopening the app, everything is OK for some time

### Additional context

I found something interesting in log-files located in the folder: 
C:\Users\user\AppData\Roaming\DBeaverData\workspace6\.metadata\

See how much events `Datasource <*> not found in project General` generated every millisecond.
Could you please examine the possibility of an infinite loop over there in code?

[dbeaver-debug-1724276504022.zip](https://github.com/user-attachments/files/16709998/dbeaver-debug-1724276504022.zip)

**Comment by E1izabeth** [comment] 2024-08-29 13:04
>See how much events Datasource <*> not found in project General generated every millisecond.
Could you please examine the possibility of an infinite loop over there in code?

This message is sent, when you open DBeaver and have script for some deleted connection. Have you moved your connections to some folders or deleted them?

**Comment by E1izabeth** [comment] 2024-08-29 13:05
For now we can't reproduce the issue. We would appreciate to any clue how to reproduce it.
Unfortunately, neither logs not thread dump contain something specific.

**Comment by ask9** [comment] 2024-08-29 14:09
> > See how much events Datasource <*> not found in project General generated every millisecond.
> > Could you please examine the possibility of an infinite loop over there in code?
> 
> This message is sent, when you open DBeaver and have script for some deleted connection. Have you moved your connections to some folders or deleted them?

Yes, I delete/recreate my connections frequently. No problem if the connections will be disconnected in this case.

**Comment by ask9** [comment] 2024-08-29 14:10
> For now we can't reproduce the issue. We would appreciate to any clue how to reproduce it. Unfortunately, neither logs not thread dump contain something specific.

I tried to find the steps..
I think it will not be possible to find out the certain steps to reproduce it.
It happens rarely and without any certain action from my side.

**Comment by E1izabeth** [comment] 2024-08-29 14:11
I see, thank you

**Comment by ask9** [comment] 2024-08-31 20:01
I suspect the issue is only reproducible on Windows OS because the system library involved.
If someone will decide to investigate it, first of all try it on Windows (not Linux/MacOS). 
Ideally - on the same version as on my side: `Windows 10 Pro 22H2 19045.4780`

And check also the version of this suspicious system file: 
`C:\Windows\System32\ucrtbase.dll`


![0000003495](https://github.com/user-attachments/assets/a3d1604e-084d-4486-8725-e98628f644e3)
![0000003496](https://github.com/user-attachments/assets/41c8e245-c899-42f6-962a-32f6a2958659)
![0000003497](https://github.com/user-attachments/assets/0a0d1490-6cba-4297-9748-09d8e6a3be75)

**Comment by arhayka** [comment] 2024-09-05 13:26
Could you please try to generate a thread dump and attach it here? Important: you should do it at the very moment when it happens.
Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/
Thank you.

**Comment by ask9** [comment] 2024-09-05 14:19
@arhayka 
I've already done it (see the txt-file attached to my first message in this thread, right after the video).

**Comment by Destrolaric** [comment] 2024-09-12 12:59
Just for now, could you try `sfc /scannow` in administrator CMD terminal. Just to be sure that it's not corrupted library issue.

**Comment by ask9** [comment] 2024-09-12 19:39
@Destrolaric 
OK. I've done it. 
One component was repaired (not related to our issue) and some warnings are also presented in the log.

[CBS.log](https://github.com/user-attachments/files/16984714/CBS.log)

**Comment by jocot** [comment] 2024-12-11 01:41
I've also just experienced heavy CPU and RAM usage when starting dbeaver on Linux/Fedora 40.

I typically leave a number of tabs open in my workspace between sessions, and today it occurred after upgrading to the latest 24.3.0.
I downgraded back to 24.2.5 and the same issue occurred.
I get 1900%+ CPU usage and looks like there's a memory leak as it consumes 12GB+ RAM on starting up, the "not responding" window appears within 20-30 seconds.
It would terminate on its own, so then I ran it from CLI to capture the debug output.
When running from CLI it seemed to stall after a while, CPU usage would drop but RAM usage still remained high.

I'll make a backup of my workspace and try to isolate it.

There's also this warning about Negative content width, not sure if related:
(DBeaver:16964): Gtk-WARNING **: 12:24:52.545: Negative content width -8 (allocation 5, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

Also seems there might be a deadlock causing IllegalStateException in the 2nd log.

[dbeaver-debug.log](https://github.com/user-attachments/files/18088312/dbeaver-debug.log)
[dbeaver-metadata.log](https://github.com/user-attachments/files/18088313/dbeaver-metadata.log)

**Comment by ask9** [comment] 2024-12-14 18:28
By the way, I don't experience the initial issue anymore.
I suppose your new issue is not the same as my initial issue.
The initial issue consumed only one thread (one kernel) and didn't consume RAM.
It also happened spontaneously, not on application statup.
It also didn't lead to "not responding" window.

**Comment by E1izabeth** [comment] 2024-12-16 11:21
@jocot you have different case, different OS and different logs. Please create new issue about your case.

@ask9 thanks, I'll close the issue then. Let me know, if you notice this behavior again and we will reopen it.

**Closed as not planned by E1izabeth** 2024-12-16 11:21 UTC
Labels: performance
