### ISSUE TITLE
Ability to run Dbaever with a different scale from the OS

### ISSUE THREAD

**Issue by ac10n** [dbeaver/dbeaver#15151] opened 2022-01-11 15:46 UTC
For months, I've been unable to use Dbeaver because I'm using a HiDPI monitor.
I'm using Fedora 35 + KDE + Wayland. 

With a little bit of searching, I see that historically people had issues with the scaling.

One solution that can allow us to continue using dbeaver (even in a sub-optimal manner) is to allow the user to set a different scaling for dbeaver.

I would happily set Dbeaver's scale to 1 and use it, than using the other tools, but Dbeaver in my setting is really unusable.

**Comment by uslss** [comment] 2022-01-13 09:58
Thanks for the report. 
Unfortunately, this is a bug in Eclipse platform.
Close this as a duplicate of #6581

**Closed as completed by uslss** 2022-01-13 09:58 UTC
Labels: duplicate
