### ISSUE TITLE
single query to multiple connections

### ISSUE THREAD

**Issue by meyers-mike** [dbeaver/dbeaver#20803] opened 2023-08-04 14:51 UTC
i see you can connect to multiple databases at the same time, but you can only query 1 database connection at a time

would love to be able to have 1 query that spans more than 1 database connection

use case:
i want to blast in data from a .csv file into a database

work around
i created a .csv connection and pulled data from a .csv file
i executed select * from [csv file] (all results)
i advance copied the results into a SQL query--the insert function apparently only allows 1000 transactions at once, so i had to split up the query into chunks of 1000
i connected to the desired database
then i was able to run the insert queries into the database

**Comment by E1izabeth** [comment] 2023-08-07 11:28
What database do you use?

**Comment by meyers-mike** [comment] 2023-08-07 14:47
> What database do you use?

@E1izabeth, i'm using a few Microsoft Azure databases across a few different Azure cloud servers

**Comment by uslss** [comment] 2023-08-10 13:19
thanks for the suggestion. Feature request was already created.  Close this issue as a duplicate of #17263

**Closed as completed by uslss** 2023-08-10 13:19 UTC
Labels: duplicate, x:azure
