### ISSUE TITLE
Remapping Line End and Line Start shortcuts

### ISSUE THREAD

**Issue by anazzani** [dbeaver/dbeaver#12358] opened 2021-05-05 08:12 UTC
#### System information: 
- Operating system: macOS Big Sur v11.2.3
- DBeaver version: Version 21.0.4.202105021514
- Additional extensions: none

#### Connection specification:
- Database: PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5), 64-bit
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I'm trying to remap the Line End and Line Start shortcuts to the Home ↖ and End ↘ keys: [Example](https://i.gyazo.com/7ea2025cb3e449e43636c59080a20beb.png)

But it doesn't seem to work and those keys always take me to the End / Start of the whole text I'm editing.

The equivalent Select Line End/Start work as expected.

Is it a bug or am I missing something?

Thanks.

Alessandro

**Comment by anazzani** [comment] 2021-05-12 23:51
Just saw [this](https://github.com/dbeaver/dbeaver/issues/9414): seems to be the same (or very similar) issue.

**Comment by kseniiaguzeeva** [comment] 2021-06-08 06:59
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/9414

**Closed as completed by kseniiaguzeeva** 2021-06-08 06:59 UTC
Labels: duplicate, xo:macos
