### ISSUE TITLE
query pg_user and pg_group groname and usename return  {}

### ISSUE THREAD

**Issue by myeggo** [dbeaver/dbeaver#8331] opened 2020-04-03 16:11 UTC
#### System information: 
- Operating system (distribution) and version:  Windows server 2012R2
- DBeaver version: Version 7.0.1.202003211804
- Java version : redshift-jdbc42-1.2.41.1065.jar
- Additional extensions: NA

#### Connection specification:
- Database name and version: Redshift
- Driver name: AWS / Redshift
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
when select pg_user and pg_group return {} for usename and groname column.  I think this apply to any datatype "name"
#### Steps to reproduce, if exist:
select * from pg_user or select * form pg_group

**Comment by serge-rider** [comment] 2020-04-03 16:48
Duplicate of #8275

**Closed by serge-rider** 2020-04-03 16:48 UTC
Labels: bug, duplicate, x:redshift
