### ISSUE TITLE
"Find" is not jumping to find line

### ISSUE THREAD

**Issue by iwex** [dbeaver/dbeaver#8310] opened 2020-04-01 09:53 UTC
#### System information: 
- Operating system (distribution) and version - Manjaro
- DBeaver version 7.0.1

#### Describe the problem you're observing:
When I trying to find some line using "Find/Replace" window - search is not jumping to line which was found. In 7.0.0 there was no such bug.

**Comment by kseniiaguzeeva** [comment] 2020-04-09 09:59
Unfortunately I can't reproduce it in 7.0.2. IS it still actual for you?

**Comment by uslss** [comment] 2020-04-09 12:53
seems that issue is fixed in scope of #8362

**Closed by uslss** 2020-04-09 12:53 UTC
Labels: bug, duplicate
