### ISSUE TITLE
Edit data on grid is disabled on Oracle, like the Database was readonly since 6.0.5

### ISSUE THREAD

**Issue by gutojm** [dbeaver/dbeaver#5978] opened 2019-05-22 16:33 UTC
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.0.5
- Java version 1.8.0_77-b03
- Additional extensions

#### Connection specification:
- Database name and version Oracle 11
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

I'm used to edit data directly on result grid after doing a select. I had no problem with this until version 6.0.1. When I upgraded to 6.0.5, the edit on Oracle is disabled, like the database was readonly (but it's not). Editing on result grid on MySql still working with no problem.

#### Steps to reproduce, if exist:

Configure a oracle database, do a select, try to edit on result grid.

**Comment by Zabbah** [comment] 2019-05-23 07:42
You can't edit data, remove or add rows, etc.

**Comment by uslss** [comment] 2019-05-25 19:57
Thanks for the bug report
Seems to be duplicate of #5957.
The issue is already fixed in EA version. 
You could test the version from early access (https://dbeaver.io/files/ea/) and report the results here in comments (whether the problem is fixed or not).

**Closed** 2019-05-26 17:16 UTC
Labels: bug, duplicate, x:oracle, xf:data
