### ISSUE TITLE
GeoViewer tile servers URLs should be configurable

### ISSUE THREAD

**Issue by nirco1983** [dbeaver/dbeaver#10661] opened 2020-12-10 13:19 UTC
**Is your feature request related to a problem? Please describe.**
Some organizations have local OpenStreetMap or MapBox tile servers that serve clients in the local network to save network bandwidth and provide a very quick response to client requests.
Currently, the tile servers URLs are hardcoded in the GeoViewer, which makes it impossible use local tile servers with DBeaver.

**Describe the solution you'd like**
An option to edit tile providers and their URLs for the GeoViewer.

**Describe alternatives you've considered**
One can patch the plugin "org.jkiss.dbeaver.data.gis.view" and replace the URLs of the tile servers in:
1. plugin.xml
2. web/view_template.html

**Additional context**

**Comment by kseniiaguzeeva** [comment] 2020-12-10 13:33
Thank you for the suggestion.

**Comment by flambchap** [comment] 2021-01-22 08:00
Duplicate of #10573.

**Closed by flambchap** 2021-01-22 08:00 UTC
Labels: feature request, xf:gis
