### ISSUE TITLE
display the size of table

### ISSUE THREAD

**Issue by clfelos** [dbeaver/dbeaver#10078] opened 2020-10-15 18:30 UTC
#9835 ## System information: 
- Operating system (distribution) and version Ubuntu 18.04
- DBeaver version: 7.2

#### Connection specification:
- Database name and version sqlserver

#### Describe your question:
In previous versions 7.2, display the size of table. After update this function not working. what is problem?

**Comment by uslss** [comment] 2020-10-19 09:15
looks quite strange. It works for me against 7.2.3 for SQL Server.
What DBeaver version do you use?

**Comment by clfelos** [comment] 2020-10-19 13:49
Hi, I need version Version 7.2.3.202010181902. another problem is with size the columns, but i uninstalled and installed and this is ok.
![dbeaver](https://user-images.githubusercontent.com/14156021/96459685-c3d4d900-11f8-11eb-90ee-c542535a2499.png)

**Comment by clfelos** [comment] 2020-10-21 14:02
@uslss why is it closed?

**Comment by uslss** [comment] 2020-10-21 21:39
@clfelos sorry, incorrectly catch your answer.
Could you check if Show Statistic info option is checked in preferences?
![image](https://user-images.githubusercontent.com/31996417/96790185-09fb8980-13ff-11eb-936c-505123b9cfb8.png)

**Comment by ellis** [comment] 2020-10-29 08:47
@uslss I'm using postgres databases, and their table sizes are also no longer displayed.  DBeaver Version 7.2.3.202010181902.    "Show statistics info" is selected:

![image](https://user-images.githubusercontent.com/97852/97545415-46188680-19cb-11eb-982f-634b9c064fe6.png)

**Comment by vadbes46** [comment] 2020-12-02 10:00
Can confirm the same behaviour
It was ok on version 7.2.0.202008302047 and before, but not then.
Checkbox is enabled, just default settings for all

**Comment by LonwoLonwo** [comment] 2020-12-14 10:03
hello @vadbes46 
Could you add more information?

- Operating system (distribution) and version
- DBeaver version
- Additional extensions
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by sgrinko** [comment] 2021-01-11 17:15
I confirm.
Installed version 7.3.1 from scratch
Information about the size of tables is not displayed.
The setting is set to true initially.
Updated to version 7.3.2
Information about the size of tables is not displayed.
The setting is set to true initially.
Turned off the setting. Saved changes. Enabled the setting. Saved changes.
Information about the size of tables is not displayed.


    Operating system (distribution) and version - Linux mint 20.1
    DBeaver version - 7.3.2
    Additional extensions - only plpgsql
    Database name and version - Postgres 13.1 (local install)
    Driver name - org.postgresql:postgresql:RELEASE 42.2.5
    Do you use tunnels or proxies (SSH, SOCKS, etc) - No. local install

**Comment by serjflint** [comment] 2021-01-12 11:29
Same here

```
Operating system (distribution) and version: Manjaro 20.2 Linux 5.10
DBeaver version: CE Version 7.3.2.202101032114
Additional extensions: Default
Database name and version: MariaDB 10.2.13-MariaDB-10.2.13+maria~trusty 
Driver name: MariaDB Connector/J [2.4.3]
Do you use tunnels or proxies (SSH, SOCKS, etc)?: No
```

**Comment by flambchap** [comment] 2021-04-05 12:39
I can not reproduce this issue against the current DBeaver version on Fedora. If the issue is still actual for anyone, feel free to reopen it.

**Comment by BabakAmini** [comment] 2022-04-11 16:47
I can confirm the same things after I installed the latest version. **Show statistics info** is selected.

- Operating system: Windows 11
- DBeaver version: 22.0.0.202203131528
- Additional extensions: Nothing
- Database name and version: postgres 13.2 (local)
- Driver name: PostgreSQL 13
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

**Comment by hkrsmk** [comment] 2022-04-13 05:09
I've found that closing and opening DBeaver helped me restore the table sizes. Had this issue temporarily after expanding and minimising the dropdowns.

    Operating system: MacOS Monterey
    DBeaver version: 22.0.2.202204021640
    Additional extensions: Nothing
    Database name and version: MSSQL
    Driver name: MSSQL JDBC
    Do you use tunnels or proxies (SSH, SOCKS, etc)? VPN

**Comment by BabakAmini** [comment] 2022-04-13 15:18
> I've found that closing and opening DBeaver helped me restore the table sizes. Had this issue temporarily after expanding and minimising the dropdowns.

That didn't work for me on Windows 11.

**Comment by nvekariya** [comment] 2022-06-13 18:13
Another option:


- View tables:
<img width="301" alt="Screen Shot 2022-06-13 at 11 00 49 AM" src="https://user-images.githubusercontent.com/6309147/173416471-5613ae6f-df45-46a2-9523-a0d8bcc2d4d5.png">


- Click on Settings icon from the bottom bar and click 'Disk  Space'
 
<img width="614" alt="Screen Shot 2022-06-13 at 11 12 16 AM" src="https://user-images.githubusercontent.com/6309147/173417756-0ea0a52a-283d-414f-a573-49f8a73f06f3.png">


- And Disk Space column shows disk space for all the tables:

<img width="551" alt="Screen Shot 2022-06-13 at 11 12 26 AM" src="https://user-images.githubusercontent.com/6309147/173417789-f948acf6-203d-4836-9523-c1fd654b8ee8.png">

**Comment by LonwoLonwo** [comment] 2023-02-23 15:25
I can't reproduce this issue against DBeaver 22.3.5.
You can close/open your connection in case of this problem. Use "Refresh" button on the tables container. Enable specific data in the table properties. So, many workarounds here.
If issue occurs again, please create new ticket.

**Closed** 2023-02-23 15:26 UTC
Labels: bug, xo:linux, inreview
