### ISSUE TITLE
Error searching for DB object on SQL Server with schema selected

### ISSUE THREAD

**Issue by jest** [dbeaver/dbeaver#4950] opened 2019-01-09 09:23 UTC
#### System information: 
- Operating system (distribution) and version: Ubuntu 16.04
- DBeaver version: 5.3.2
- Java version: 1.8.0_191
- Additional extensions

#### Connection specification:
- Database name and version: SQL Server 2017-CU3
- Driver name: Microsoft driver
- Do you use security connection (SSH, Proxy, etc)? No

#### Describe the problem you're observing:

When searching for the DB object, if the default schema is used (i.e. if the item in the `Database Navigator` tree is the connection, or the database, e.g. `the_database`), the following query is being sent to the database:

```
SELECT * FROM the_database.sys.all_objects o WHERE o.type IN ('S','U','IT','V','SN','P','X') AND o.name LIKE @P0
```

and the object names are fetched correctly. When instead I want to search in specific schema and select the schema in the tree, the erroneous query is sent and `'Items filtering' has encountered a problem` dialog appears:

```
SELECT * FROM the_database.sys.all_objects o WHERE o.type IN ('S','U','IT','V','SN','P','X') AND o.name LIKE @P0AND o.schema_id=@P1
``` 

(Notice the lack of space between `@P0` and `AND` above).

#### Steps to reproduce, if exist:

1. Select schema in `Database Navigator` tree
2. `Navigate/Open Database object...`
2. Start typing
3. Problem dialog appears

**Comment by serge-rider** [comment] 2019-01-09 10:06
Duplicate of #4919
Thanks for the bug report anyway.

**Closed by serge-rider** 2019-01-09 10:06 UTC
Labels: bug, duplicate

**Comment by jest** [comment] 2019-01-09 10:37
Thanks. Tried to locate a similar bug, but it's sometimes hard to find, especially when you know the reason and your duplicate search is too specific. :)
