### ISSUE TITLE
Hippie Engine Autocomplete creates double aliases when selecting prompted option

### ISSUE THREAD

**Issue by jezabennett** [dbeaver/dbeaver#22170] opened 2023-12-13 14:39 UTC
### Description

When using Hippe Engine SQL Assist the prompt can only show options when typing parts of syntax already in the script, so the starting point is typically like the one below (line 11):
![image](https://github.com/dbeaver/dbeaver/assets/16517218/50030a4f-758c-4e19-93f9-0e9fb9e8f9a8)

Shows the Hippie prompt (fine):
![image](https://github.com/dbeaver/dbeaver/assets/16517218/760fb645-f7c9-4dc5-9dc5-397ae175047b)

Starting with the <alias.dot> part of your field name gets you the prompt. You select the item from the prompt and it creates the full alias and fieldname even though you have already started typing the field name. It replaces the fieldname part that you have already typed but not the alias. This leaves a double alias and and SQL that will not compile.

Final result with double alias (line 11):
![image](https://github.com/dbeaver/dbeaver/assets/16517218/1bc92e22-956f-42fe-baac-8dcfd1dc206a)

Not sure if this is a bug. Feels like it probably is. Because autocomplete does not work within a CTE, the Hippie engine is used far more often than ordinarily would be. This limitation has been bugging me since Jan 2023 when I recommenced using Dbeaver again.

### DBeaver Version

Community Version 23.3.0

### Operating System

Windows 11 Enterprise

### Database and driver

SQL Server 2017
Microsoft JDBC Driver for SQL Server

**Comment by E1izabeth** [comment] 2023-12-13 15:52
Thank you for bug report. It's a duplicate of #19821
You can vote for that issue with 👍🏻 under the mentioned issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2023-12-13 15:52 UTC
Labels: duplicate, xf:sql editor
