### ISSUE TITLE
Sort by columns name - no longer working 

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#18855] opened 2023-01-24 10:01 UTC
### Description

After some upgrade this functionality stopped working.
I do really miss this feature

![obraz](https://user-images.githubusercontent.com/5410448/214262490-2bb5bd2c-950a-4268-a287-5a16a9a99a56.png)

### DBeaver Version

22.3.2

### Operating System

Windows 10

**Comment by E1izabeth** [comment] 2023-01-24 10:04
Thank you for bug report. The issue has been already solved. Please, try DBeaver 22.3.3.

**Comment by E1izabeth** [comment] 2023-01-24 10:07
Duplicate of #18618

**Closed as not planned by E1izabeth** 2023-01-24 10:07 UTC
Labels: duplicate, xf:data
