### ISSUE TITLE
Unable to display COLUMN DESCRIPTION IN HEADER when entering SELECT LEFT JOIN in IBM DB2.

### ISSUE THREAD

**Issue by MrLuke1110** [dbeaver/dbeaver#22699] opened 2024-02-05 02:29 UTC
**Is your feature request related to a problem? Please describe.**
When the option 'SHOW COLUMN DESCRIPTION IN HEADER' is selected.

**Describe the solution you'd like**
When selecting a single file, you can display the column description in the header.
When using a LEFT JOIN, the column description may not be displayed.

**Additional context**
1. LEFT JOIN 
![image](https://github.com/dbeaver/dbeaver/assets/66194793/519d0052-07bf-4fc4-979b-d7ac81d10098)
2. SELECT
![image](https://github.com/dbeaver/dbeaver/assets/66194793/a7bd9808-a496-4e91-aab1-f3a819a00dc2)
3. SELECT
![image](https://github.com/dbeaver/dbeaver/assets/66194793/0cccb1c4-7405-4ddd-8292-6a1a04ed0410)

**Comment by LonwoLonwo** [comment] 2024-02-05 09:29
Hello @MrLuke1110 

Thanks for the report.

And I'm closing it because this is a duplicate of https://github.com/dbeaver/dbeaver/issues/14974

**Closed as completed by LonwoLonwo** 2024-02-05 09:29 UTC
Labels: duplicate, xf:metadata, x:db2i
