### ISSUE TITLE
Newline BUG

### ISSUE THREAD

**Issue by liuzhe101** [dbeaver/dbeaver#20374] opened 2023-06-25 02:25 UTC
### Description

Press enter to select the prompt table or field, then line break BUG

### DBeaver Version

DBeaverUltimate 23.1.0.202306120813

### Operating System

macos 13.4.1

### Database and driver

PostgreSQL 12.1
PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

https://github.com/dbeaver/dbeaver/assets/61652514/8b8155bb-facb-459a-b316-7a60de72f77a

**Comment by liuzhe101** [comment] 2023-06-25 12:17
@LonwoLonwo Can you tell me how to fix this bug? Automatic line wrapping is very troublesome

**Comment by E1izabeth** [comment] 2023-06-26 11:29
I suppose it's connected with the software you use to type hanzi. Does switching the language to English helps?

What input method do you use? What software?

**Comment by liuzhe101** [comment] 2023-06-26 16:01
> 我想它与你用来输入汉字的软件有关。将语言切换为英语有帮助吗？
> 
> 您使用什么输入法？什么软件？

The built-in macos input method used, when the input table name is in English, acridine

**Comment by liuzhe101** [comment] 2023-06-29 03:26
> 我想它与你用来输入汉字的软件有关。将语言切换为英语有帮助吗？
> 
> 您使用什么输入法？什么软件？

@E1izabeth  How to deal with the problem now

**Comment by E1izabeth** [comment] 2023-06-29 07:02
I couldn't reproduce the issue on Windows. I don't have Mac, so we're waiting for another person from our team to reproduce.

Could you clarify: when you're typing your language is set to English or to Chinese?

**Comment by liuzhe101** [comment] 2023-06-29 07:10
> 

It’s in English. During the video demonstration, when I typed the prefix of the pe_fe table, the letters will appear directly. If it’s in Chinese, Chinese characters will @E1izabeth

**Comment by E1izabeth** [comment] 2023-06-29 07:12
Thank you for clarification

**Comment by Matvey16** [comment] 2023-07-06 13:10
@liuzhe101 Does it happen with any table or column or with specific objects?

#16838

**Comment by liuzhe101** [comment] 2023-07-07 02:18
> 



> @liuzhe101任何表或列或特定对象都会发生这种情况吗？
> 
> [第16838章](https://github.com/dbeaver/dbeaver/issues/16838)

This problem does not occur with a single , but it is complicated for sql. This situation will occur when writing in the middle part. Every time you press enter, you need to move the cursor position. Whether it supports remote to solve this problem is really annoying.

**Comment by flambchap** [comment] 2023-07-13 12:49
Looks like a duplicate of https://github.com/dbeaver/dbeaver/issues/16838.

**Closed as not planned by flambchap** 2023-07-13 12:49 UTC
Labels: can't reproduce, duplicate, xo:macos, xf:sql editor

**Comment by LonwoLonwo** [comment] 2023-07-13 12:51
Could you please try to uncheck this setting if it is checked and try again?

![2023-07-13 15_49_36-Preferences](https://github.com/dbeaver/dbeaver/assets/45152336/1e0f84ad-751a-4eb5-a2bf-1efdfcb389b3)

**Comment by liuzhe101** [comment] 2023-07-14 09:18
> 



> 如果已选中此设置，请尝试取消选中该设置，然后重试吗？
> 
> ![2023-07-13 15_49_36-偏好](https://user-images.githubusercontent.com/45152336/253282315-1e0f84ad-751a-4eb5-a2bf-1efdfcb389b3.png)

If I cancel this option, the line will not change（no change line）, but if I check it, it will change(chang current line), and the same problem will occur when I try again. Complicated sql will have automatic line break problem，I opened this in dbeaver.ini. Is this the reason? If you can’t reproduce it, try -Dlm.debug.mode=true
