### ISSUE TITLE
Npe appears when using gis editor

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#17436] opened 2022-08-23 15:06 UTC
### Description

NPE when activating gis editor

### DBeaver Version

22.1.5

### Operating System

Windows 10

### Database and driver

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.primeEditorValue(GISBrowserViewer.java:140)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.primeEditorValue(GISPanelEditor.java:63)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:294)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$2(ValueViewerPanel.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$3(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:217)
```

### Steps to reproduce

Try to click on geometry data to open the editor, around 1 of 100 tries will lead to NPE

**Comment by E1izabeth** [comment] 2022-09-06 18:02
Seemed it was fixed in 22.2.0. I can't reproduce it anymore.

**Comment by E1izabeth** [comment] 2022-09-06 19:02
The issue appears after opening Value panel for gis values when the Microsoft Edge browser is set as Web Engine, but there is no Microsoft Edge on the client machine.

**Comment by E1izabeth** [comment] 2022-09-06 19:07
It happens because of the following errors.
![image](https://user-images.githubusercontent.com/28875055/188718679-198e9e8b-9706-4cda-b123-99ee126c63ff.png)
![image](https://user-images.githubusercontent.com/28875055/188718770-6ab2822d-4655-4a88-9395-98a3ce9a7893.png)

**Closed as completed** 2022-09-12 16:48 UTC
Labels: xf:gis, sp:3
