### ISSUE TITLE
Dbeaver asks for Bind Parameters when IS_NULL_VALUE used on Snowflake

### ISSUE THREAD

**Issue by ufuk-ergin-carbon** [dbeaver/dbeaver#22567] opened 2024-01-23 17:22 UTC
### Description

When the query uses IS_NULL_VALUE(TRY_PARSE_JSON(at.changes):reviewed) for example Dbeaver asks for Bind Parameters. Snowflake's own UI runs the query just fine. Also, the window for Bind Parameters popup window shows query on the second line, instead of starting with the first line. Upon resizing it, it shows the first line of the query. Attached the screen recording.

https://github.com/dbeaver/dbeaver/assets/114302087/ca848a01-3ae9-49af-bd89-8b39180b65ca

### DBeaver Version

Version 23.3.3.202401211839

### Operating System

MacOS Sonoma 14.3

### Database and driver

Snowflake Server version: Snowflake 8.2.0
Driver version: Snowflake 3.13.30

**Comment by E1izabeth** [comment] 2024-01-23 17:41
Thank you for bug report. I'm closing it as a duplicate of #19569
Please see this comment for a workaround https://github.com/dbeaver/dbeaver/issues/19569#issuecomment-1492920038

**Closed as not planned by E1izabeth** 2024-01-23 17:41 UTC
Labels: duplicate, x:snowflake, xf:sql execution

**Comment by ufuk-ergin-carbon** [comment] 2024-01-23 18:30
Thanks @E1izabeth!

**Comment by ufuk-ergin-carbon** [comment] 2024-01-23 18:31
How about the first line not being shown issue I also described in the ticket?

**Comment by E1izabeth** [comment] 2024-01-23 18:37
I suspect it's this issue: #18776

**Comment by ufuk-ergin-carbon** [comment] 2024-01-24 15:05
@E1izabeth hi, yes, it's exactly that issue. Will it be fixed?

**Comment by E1izabeth** [comment] 2024-01-25 10:22
You can vote for the issue with 👍 under the issue description to promote it to a higher priority. Then it will be fixed sooner.

**Comment by ufuk-ergin-carbon** [comment] 2024-01-25 10:26
Hi @E1izabeth , I just did, as well as on my own :) Thanks for the suggestion.
