### ISSUE TITLE
Since 24.0.3 dBeaver no longer consistantly runs just the statement my cursor is on.

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#26647] opened 2024-04-25 00:39 UTC
### Description

Prior to this version, if I place the cursor anywhere in an SQL statement in an SQL Editor and press "Execute SQL Query" it would only run that statement.

Since 23.0.3 it will often try to run all of the statements in the editor, often with disaterous results.

Is there anyway to fix this issue and return to the previous behavior?

the only safe way to run statements now is to either

- highlight the statement in its entirety
- only have a single statement per SQL Editor

Note my statements are well formed and terminated with the standard semicolon like this:

`select * from my_schema.my_table;`

thanks.

### DBeaver Version

Community Edition 23.0.3

### Operating System

Windows 10

### Database and driver

PostgreSQL 16

### Steps to reproduce

1. Have multiple statements in an SQL Editor window
2. place your cursor anywhere inside a statement
3. press the orange arrow "Execute SQL query"
4. watch as **every** statement in the SQL Editor is run

**Comment by E1izabeth** [comment] 2024-04-25 08:47
Thank you for bug report. I'm closing it as a duplicate of #25061
We're working on the fix

**Closed as not planned by E1izabeth** 2024-04-25 08:47 UTC
Labels: duplicate, xf:sql execution
