### ISSUE TITLE
"Export Data" selects last target, but uses "Database"

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#9746] opened 2020-09-11 12:23 UTC
#### System information: 
- Debian/SID
- DBeaver 7.2.0
- Additional extensions -

#### Connection specification:
- Postgres 12
- PostgreSQL JDBC Driver (there seems to be no detailed info in DBeaver? postgresql-42.2.5.jar in dbeaver-drivers )
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
After the first "Data Export" the last selected target is still selected, but export uses "Database" instead.
Apparently, despite the highlighting, the selection resets to the first entry of the tree.

#### Steps to reproduce, if exist:
1) Database Navigator: on a table, right click, select "Export Data"
2) in the wizard select as target "SQL"
3) walk through the export until finished
4) step 1 again
5) in the wizard "SQL" is still selected
6) hit "Next"
7) the dialog now asks for "Tables mapping" which obviously belongs to target "Database" in the previous pane

**Comment by uslss** [comment] 2020-09-11 13:34
seems to be duplicate of #9630 
anyway, thanks for the bug report

**Closed by uslss** 2020-09-11 13:34 UTC
Labels: bug, wait for review
