### ISSUE TITLE
SQLite: "open with" DBeaver

### ISSUE THREAD

**Issue by nmoreaud** [dbeaver/dbeaver#18323] opened 2022-11-24 12:44 UTC
I would like to be able to open SQLite files easily by setting Windows "open with" setting to DBeaver.exe.
Currently it opens a DBeaver window having an open query tab with binary content.

**Comment by ShadelessFox** [comment] 2022-11-24 14:23
Hello @nmoreaud,

Thanks for the feature request.

Duplicate of https://github.com/dbeaver/dbeaver/issues/15395

**Closed as not planned by ShadelessFox** 2022-11-24 14:23 UTC
Labels: duplicate, x:sqlite
