### ISSUE TITLE
No Proposal with table alias and empty line before FROM statement 

### ISSUE THREAD

**Issue by briandhuff** [dbeaver/dbeaver#17696] opened 2022-09-20 23:24 UTC
### Description

If you alias a table and have a space between your last select line and the FROM clause, column recommendations do not work.

Example of it not working with an alias and space between selection and from block
![image](https://user-images.githubusercontent.com/4779934/191381030-a5aefbfb-e926-4b8f-a562-d26b5c5b0f6d.png)

Example of it working without the alias and with the space between selection and from block
![image](https://user-images.githubusercontent.com/4779934/191381163-0a84fa10-6f38-43f0-b280-3d795780ae95.png)

Example of it working with alias and no space between selection and from block
![image](https://user-images.githubusercontent.com/4779934/191381093-23b1bb44-ae98-46d1-9d5c-3ab399385f5f.png)

### DBeaver Version

Community Edition 22.2.0

### Operating System

Windows 10 Pro

### Database and driver

Microsoft SQL Server 2016 (RTM) - 13.0.1601.5 (X64) 

MySQL 5.6.24-log

### Steps to reproduce

1. create a basic query - select * from mytable mt
2. put an empty line between * and from
3. change select * to select mt.  and hit CTRL + SPACE
4. you will see no proposal
5. remove empty line before from statement
6. repeat step 3 and you'll see column suggestions
7. put empty space back before from statement
8. change remove mt alias and use table name in select statement
9. repeat step 3 and see column names
10. see screenshots provided

**Comment by LonwoLonwo** [comment] 2022-09-22 13:56
Thanks for the bug report.

Actually, this is the duplicate of this ticket https://github.com/dbeaver/dbeaver/issues/13476

And please tack a look at this advice: https://github.com/dbeaver/dbeaver/issues/13476#issuecomment-1001506524

**Closed as not planned by LonwoLonwo** 2022-09-22 13:56 UTC
Labels: duplicate, xf:sql

**Comment by briandhuff** [comment] 2022-09-22 14:07
Thank you, I had looked for similar issues reported but didn't think about the empty line as a delimiter.
Problem resolved
