### ISSUE TITLE
(xx) Shift + Tab doesn't decrease indentation level if a line of code has less than 4 space symbols at begin of the line

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34941] opened 2024-07-22 17:24 UTC
### Description

It is not convenient, when the code is formatted with different number of space symbols and you want to format it correctly but application doesn't let you do it.
In this case most popular editors will let you to decrease the indentation level.
Why is it disallowed? 
Sometimes it is faster to decrease indentation level of the selected text (with incorrect 1-3 space symbols) and then add it again (with 4 space symbols) instead adding missing space symbols for each lines of code you want to indent.

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Steps to reproduce

- Maybe you need to set option in Preferences -> Editors -> Text Editors -> Insert spaces for tabs  = True.
- another option: Displayed tab width: 4

- use this code:

```
select 
   "oid", 
    relname, 
     relnamespace, 
      reltype, 
       reloftype, 
        relowner, 
         relam, 
          relfilenode, 
           reltablespace 
from pg_class
```
- select lines with column names and press Shift + Tab

Here on the vidoe I compare behavior of multiple presses of Shift + Tab hotkey for selected text in DBeaver and Notepad++.
I suggest to use the second behaviour:

https://github.com/user-attachments/assets/0de4a018-7bc4-4345-a180-f482680f68de

**Comment by E1izabeth** [comment] 2024-07-23 08:56
Thank you for bug report.
I'm closing it as it's a duplicate of #7280

**Closed as not planned by E1izabeth** 2024-07-23 08:56 UTC
Labels: duplicate, xf:sql editor
