### ISSUE TITLE
Redshift spectrum tables are not shown in navigator for copied driver

### ISSUE THREAD

**Issue by ANTGOMEZ** [dbeaver/dbeaver#14039] opened 2021-09-28 17:02 UTC
### Discussed in https://github.com/dbeaver/dbeaver/discussions/14037

<div type='discussions-op-text'>

<sup>Originally posted by **ANTGOMEZ** September 28, 2021</sup>
I have the latest version of Community Edition DBeaver, I also have the very latest AWS JDBC driver, from here: https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-download-driver.html

I  create a new Redshift **SSO connection**, expand a DB down to the Spectrum schema and expand the Tables node, **_no tables show up_**. The tables do exist, I can view them in another client navigator. Also, others that use DBeaver Community here can see the tables with same driver and version.

Any advice appreciated.

Thanks!</div>

**Comment by appleoddity** [comment] 2021-09-28 20:14
Seeing the same issues here. However, the tables show up after the drivers and connections are initially setup. Then, suddenly, out of the blue, the tables won't show anymore. Using the latest version of DBeaver and JDBC drivers. We are also using IAM authentication with browser based plugin (SSO / MFA). 

For me, it worked at first but I noticed the problem occur after adding a second connection to the same Redshift cluster but a different database.

This also occurred for another user on the previous version of DBeaver (21.2.0) who was using the UWP version. When we uninstalled UWP and installed the latest version of DBeaver (Non-UWP), it worked, again. However, for me, if I deleted the %AppData%\DBeaverData folder and reconfigure the driver/connection from scratch it still won't work.

There are no errors/warnings in the DBeaver log. Driver debug logging looks mostly "normal" to me. I can see the queries built and sent to the database when I refresh my table views. However, I do see a repeating error after these queries, "Sep 28 15:54:27.382 ERROR  [21 DBeaver: Refresh navigator object(s)] com.amazon.redshift.jdbc.RedshiftStatementImpl.cancel: statementState is StatementCancelState.IDLE"

Driver is configured like so: (The library is updated to point to the download Redshift JDBC with SDK driver) (All other options are default)
![image](https://user-images.githubusercontent.com/29755504/135160396-3015ea50-846c-4007-9237-a0ca9f181a1d.png)
![image](https://user-images.githubusercontent.com/29755504/135160438-89201e89-311b-4663-bac7-279a568ceb6a.png)

And connection is configured like so: (All other options are default)
![image](https://user-images.githubusercontent.com/29755504/135160751-b8d67c24-d60d-4728-b5c4-588c3ff671a8.png)
![image](https://user-images.githubusercontent.com/29755504/135160808-b6534e60-6b87-470c-9e07-8093772adaa3.png)

**Comment by appleoddity** [comment] 2021-10-05 20:10
@uslss Is there anything I can do to assist with troubleshooting this issue? While we like DBeaver, we have users who are unable to work with it at this time due to this issue. Is there any further information I can provide?

**Comment by Matvey16** [comment] 2021-10-06 13:49
@appleoddity Do you connect as a user that has a permission to view external schemas?

**Comment by ANTGOMEZ** [comment] 2021-10-06 14:24
> @appleoddity Do you connect as a user that has a permission to view external schemas?

I do, yes.

**Comment by appleoddity** [comment] 2021-10-06 14:35
@Matvey16 Yes. My user account is a member of a DB group that has been granted USAGE on the external schema and SELECT on the tables in the schema.

I tested additionally by:

- Confirming my logged in username with `select current_user;`
- As an admin, assigning the USAGE and SELECT permissions directly to my username `grant usage on schema <external_schema> to "<my_username>";` and `grant select on all tables in schema <external_schema> to "<my_username>";`
- As an admin, granting superuser permissions to my user account: `alter user "<my_username>" with password '<temp_password>';` and `alter user "<my_username>" createuser;`

All cases failed to show the external tables. I can navigate down to the external schema level in the UI, but under "Tables" it is empty.

Please note:

- I can list all external schemas, tables, and select on all data in these tables through another SQL client with the same login and connection configuration. (Specifically Workbench/j)
- DBeaver works after initially installing the product and configuring the database connection. At some point over the next 24 hours, it stops working. Possibly after the user is reauthenticated through the browser based SAML. The session has an 8 hour time limit. Once that expires, I am redirected to the sign on page and forced to login again, if I attempt any operations in DBeaver.
- I have since updated to the latest version 21.2.2.202110030714 - no resolution.
- I noticed during the update, it appeared to delete the old installation first. I have also tried deleting the folder `%AppData%\DBeaverData` and reconfiguring the database drivers and connection from scratch.
- I have not specifically uninstalled the product and tried to delete everything from the disk/registry, and reinstall. But, if I had a clean "uninstall" process, I could give it a try. It would make sense that this should temporarily resolve the issue if it works for a little while after initial setup, but then breaks.

**Comment by appleoddity** [comment] 2021-10-06 15:19
@Matvey16 I performed further troubleshooting.

I monitored the query log on the redshift cluster to try to see what DBeaver was doing behind the scenes. When I first open DBeaver it connects to the cluster and I see the following queries on the redshift cluster:
![image](https://user-images.githubusercontent.com/29755504/136231172-1a790dab-aebb-4931-96ec-05d13cb6bb2a.png)

After navigating down through the tree in the UI and trying to list tables, there are no other queries sent to the database. If I right-click and refresh, there are still no other queries sent to the database. It appears it is using stale data, and refusing to requery the database.

In the dbeaver-debug.log I see the application startup, and see it initiate a connection to the database. There are no further entries.

In the .log (error / warning) log all I see is a !session object and a single !entry for a redshift "This connection has been closed," error. But, I looked at this problem history and discovered that it was working for me on 2021-09-27 and I discovered it not working on 2021-09-28 before either of these entries in the error log showed up.

**Comment by Matvey16** [comment] 2021-10-15 11:38
@appleoddity Can you please verify that you have all query types enabled in query manager?

![dbeaver_70jVC1JeBh](https://user-images.githubusercontent.com/82543000/137480991-a0c3673b-7bf7-4f32-af0e-f7a9f0300598.png)

**Comment by appleoddity** [comment] 2021-10-15 14:59
@Matvey16 Hello. All the options were NOT enabled:

![image](https://user-images.githubusercontent.com/29755504/137508566-eeab9d89-c302-4d10-bcf3-8c299d1ab9e2.png)

I enabled each options, one at a time, and restarted DBeaver to test.

The end result is that all options are now enabled, but DBeaver is still not displaying the spectrum tables properly.

**Comment by Matvey16** [comment] 2021-10-18 09:26
@appleoddity I meant that you can enable all queries in query manager and check if Dbeaver sends any query to database when you try to open spectrum tables.

**Comment by appleoddity** [comment] 2021-11-02 14:31
@Matvey16 No, enabling these options did not make any difference in the queries sent to the database.

The problem persists in 21.2.4.

Can we perform additional troubleshooting steps to get this resolved? We are growing our Redshift Spectrum user base, and they are looking for a tool to use, but DBeaver has not been available due to this problem.

**Comment by appleoddity** [comment] 2021-11-08 14:54
@Matvey16 

I have confirmed the problem persists whether I login through an IAM / SSO role, or directly through a database user. Even when using the cluster admin user.

I have turned on the Redshift driver debug logging. During that time, I delete both the driver configuration and the connection and re-added it. One time it displayed the external spectrum tables and then immediately quit working again. So, I was able to capture the logs for both events. Yet, I am still unable to make heads or tails of why it is behaving the way it is.

My previous statement about queries sent to the database was not accurate. From the logs I can see additional queries sent to the database, but for some reason Redshift doesn't register those in svl_statementtext.

I do see a difference in the queries sent when it works, and when it does not work, but everything else looks the same in the logs. Namely, when it works, DBeaver sends the query `SELECT * FROM pg_catalog.svv_external_tables WHERE schemaname='<external schema name>';`

The following queries are sent when I try to expand the tables in the external schema within the UI.

The exact query flow when it works is:

```
SELECT current_schema(),session_user

SHOW search_path

SELECT db.oid,db.* FROM pg_catalog.pg_database db WHERE datname='<My DB Name>'

select * from pg_catalog.pg_settings where name='standard_conforming_strings'

SELECT version()

SELECT 1 FROM pg_catalog.pg_attribute s
JOIN pg_catalog.pg_class p ON s.attrelid = p.oid
JOIN pg_catalog.pg_namespace n ON p.relnamespace = n.oid
WHERE p.relname = 'pg_type'
AND n.nspname = 'pg_catalog'
AND s.attname = 'typcategory'

SELECT t.oid,t.*,c.relkind,format_type(nullif(t.typbasetype, 0), t.typtypmod) as base_type_name, d.description
FROM pg_catalog.pg_type t
LEFT OUTER JOIN pg_catalog.pg_class c ON c.oid=t.typrelid
LEFT OUTER JOIN pg_catalog.pg_description d ON t.oid=d.objoid
WHERE t.typname IS NOT NULL
AND (c.relkind IS NULL OR c.relkind = 'c')

SELECT * FROM pg_catalog.svv_external_tables WHERE schemaname='<My External Schema>';
```

The exact query flow when it doesn't work is this:
```
SET application_name = 'DBeaver 21.2.4 - Metadata <My DB Name>'

SELECT current_schema(),session_user

SHOW search_path

SELECT db.oid,db.* FROM pg_catalog.pg_database db WHERE datname='My DB Name'

select * from pg_catalog.pg_settings where name='standard_conforming_strings'

SELECT version()

SELECT 1 FROM pg_catalog.pg_attribute s
JOIN pg_catalog.pg_class p ON s.attrelid = p.oid
JOIN pg_catalog.pg_namespace n ON p.relnamespace = n.oid
WHERE p.relname = 'pg_type'
AND n.nspname = 'pg_catalog'
AND s.attname = 'typcategory'

SELECT t.oid,t.*,c.relkind,format_type(nullif(t.typbasetype, 0), t.typtypmod) as base_type_name, d.description
FROM pg_catalog.pg_type t
LEFT OUTER JOIN pg_catalog.pg_class c ON c.oid=t.typrelid
LEFT OUTER JOIN pg_catalog.pg_description d ON t.oid=d.objoid
WHERE t.typname IS NOT NULL
AND (c.relkind IS NULL OR c.relkind = 'c')
```

Notice that DBeaver has added a set statement in the beginning, and neglected to `SELECT * FROM pg_catalog.svv_external_tables` in the end when it does not work. This makes sense, as it is that final query that provides the list of external tables.

What else can I do to help get this fixed?

**Comment by appleoddity** [comment] 2021-11-08 20:54
@Matvey16 

I started to dig in to the source code for this issue.

I don't fully understand the details behind the DBPDriver.GetDriverParameter function. But, I have discovered that DBeaver is not getting the proper "serverType" property from the driver. 

In the DBeaver debug log, I can see DBeaver writes:
"Initiate connection to PostgreSQL database..." - when it doesn't work.
"Initiate connection to Redshift database..." - when it does work.

It seems to work one time after creating a new copy of the Redshift driver and new database connection. Then, the next time we connect to the database (perhaps after closing and opening DBeaver) it no longer recognizes the proper serverType.

I still have not reverse engineered this code enough to determine where the driver parameter "serverType" is coming from. Seems like it might be an artifact of the DBeaver plugin.xml for org.jkiss.dbeaver.postgresql.serverType. But, I'm also wondering if this is in the driver package itself, somewhere.

FYI, I am running the Redshift 2.1.0.1 JDBC driver. I have tried manually downloading it and using it, and also allowing DBeaver to download it within the driver manager.

**Comment by appleoddity** [comment] 2021-11-08 22:10
@Matvey16 

Ok. I have discovered the issue and how to reproduce.

If I go in to Driver Manager and I select the existing "Redshift" driver and then Copy that driver, it seems like DBeaver will no longer recognize the new drivers as serverType = Redshift. Instead, it changes to "PostgreSQL." I don't need to modify anything in the copied driver. Just simply copying it, breaks it.

I suspect another indication of that is the changed icon:
![image](https://user-images.githubusercontent.com/29755504/140825738-b7441297-3cb0-429a-8069-4a26d747f313.png)

However, if I create the copy of the driver, and then create a new connection to Redshift using that driver, DBeaver will recognize this as a Redshift serverType on the first connection and work properly. If I close DBeaver and re-open it, and try to connect, all subsequent connections will use the "PostgreSQL," serverType.

If I, instead, modify the settings of the original "Redshift" driver, it will continue to work fine. I have to modify the parameters because the JDBC URL template needs to be changed in my use case. But, I wanted the flexibility of having two "Redshift" drivers. One with the original settings, and one with the alternate settings.

Is this a misunderstanding of the driver copy functionality? Or is this a bug? Should I create a new issue with this detail?

**Comment by Matvey16** [comment] 2021-11-15 06:14
@appleoddity Thank you for the investigation. It is indeed a bug, although it is reproducible only in Community version. You don't need to open a separate issue, we will work on that in scope of this issue and your information will be very helpful.

**Comment by Matvey16** [comment] 2021-12-22 17:34
Verified

**Closed as completed by Matvey16** 2021-12-22 17:34 UTC
Labels: x:redshift, xf:navigator, sp:3
