### ISSUE TITLE
PostgreSQL Composite Type DDL generation is not correct

### ISSUE THREAD

**Issue by travelliu** [dbeaver/dbeaver#17775] opened 2022-09-29 15:12 UTC
### Description

```
PostgreSQL 13.4 (Debian 13.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
```

```sql
CREATE TYPE test_type AS (
 a numeric
);
```
![2022-09-29 at 23 11](https://user-images.githubusercontent.com/7792329/193069782-75545478-6e84-4ab7-aeb1-d3bdf58338d1.png)

### DBeaver Version

22.1.0

### Operating System

macOS 12.6

**Comment by LonwoLonwo** [comment] 2022-09-29 15:20
Hello @travelliu 

Thaks for the bug report.

But I'm closing this ticket as a duplicate of this ticket https://github.com/dbeaver/dbeaver/issues/15644

**Closed as not planned by LonwoLonwo** 2022-09-29 15:20 UTC
Labels: x:postgresql, xf:metadata
