### ISSUE TITLE
Export as Source code doesn't apply quote type changes

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10361] opened 2020-11-14 10:55 UTC
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.2.5 EA

#### Steps to reproduce, if exist:
1. Select source code type in a table export wizard
2. Change quote type in the export settings and execute the export

![Screenshot 2020-11-14 at 13 49 04](https://user-images.githubusercontent.com/51405061/99145547-e7b4fe80-2680-11eb-8ec6-b18efb49ef28.png)

Expected: the data is exported with changed quote type

Actual result: the default quote type is used

**Comment by akilovich** [comment] 2020-11-17 17:39
Duplicate of #10279.

**Closed by akilovich** 2020-11-17 17:39 UTC
Labels: bug, xf:datatransfer, xo:macos

**Comment by akilovich** [comment] 2020-11-23 10:07
It turned out to be a duplicate of https://github.com/dbeaver/dbeaver/issues/10366
