### ISSUE TITLE
Bug in driver class selector UI (macOS Monterey, Version 12.6.1)

### ISSUE THREAD

**Issue by wolfgang-a-klein-db** [dbeaver/dbeaver#18579] opened 2022-12-23 15:47 UTC
### Description

Dear all, 
I´m referring to this issue: https://github.com/dbeaver/dbeaver/issues/11083

I´m using:

macOS Monterey, version 12.6.1

DBeaverEE, Version 22.1.0.202206131826, Release Date 6. Juni 2022.

Error is identical with the description in issue: 11083:
In dialog "driver settings" I can find class successfully, it's displayed in combo box "driver" then.
Switching back to first tab "settings" I can see the driver name.
But when closing dialog with "ok" and opening it again, driver is again missing in tab "libraries" in combobox.

When then trying to create new connection with the driver, I again get error "driver class not found"

Would be nice, if somebody can take a look at it.

Thanks in advance,
W.

### DBeaver Version

DBeaverEE, Version 22.1.0.202206131826

### Operating System

macOS Monterey, Version 12.6.1

### Database and driver

1. Database: Google Spanner
2. Driver: google-cloud-spanner-jdbc 2.7.3

### Steps to reproduce

As described above

### Additional context

I also used older versions of Beaver (also CommunityEdition) where that already worked for 1,5 years or so.
Looks like a common problem on macOS independent from jdbc driver.

**Comment by LonwoLonwo** [comment] 2022-12-26 01:54
Hello @wolfgang-a-klein-db 

Can you please check the newest DBeaver version? https://dbeaver.io/download/

**Comment by wolfgang-a-klein-db** [comment] 2022-12-27 17:52
[](url)

**Comment by wolfgang-a-klein-db** [comment] 2022-12-27 18:03
Testet again with ce edition 22.3.1. I´m performing following steps:

Opening "driver manager", select first tab "settings", driver class name is listed there: com.google.cloud.spanner.jdbc.JdbcDriver

Selecting tab "library". Jar files are shown, combobox "driver class is empty"

Clicking on "find class" finds the exact driver class mentioned above and puts it into the combobox.

Try to open any connection containing this driver then shows:
Can't create driver instance
  Error creating driver 'Google Cloud Spanner' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.google.cloud.spanner.jdbc.JdbcDriver'
  Error creating driver 'Google Cloud Spanner' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.google.cloud.spanner.jdbc.JdbcDriver'
    com/google/cloud/spanner/SpannerException
    com/google/cloud/spanner/SpannerException
      com.google.cloud.spanner.SpannerException
      com.google.cloud.spanner.SpannerException

If I check tab "library" in driver manager again, combobox "driver class" is empty again.

I tested it with ce and ee, would appreciate solution for ee, since I bought I license for that some time ago.

Can you please recheck again?

Thanks in advance.

**Comment by E1izabeth** [comment] 2022-12-28 01:08
@wolfgang-a-klein-db Could you tell me your license id?

**Comment by flambchap** [comment] 2023-02-02 13:11
The issue is transferred to our support system on dbeaver.com.

**Closed as completed by flambchap** 2023-02-02 13:11 UTC
Labels: AS
