### ISSUE TITLE
Loss of text attributes with semantic analysis enabled

### ISSUE THREAD

**Issue by rasqual** [dbeaver/dbeaver#22662] opened 2024-02-01 15:48 UTC
### Description

Preferences/Editors/SQL Editor/Code Editor/Query Analysis

![image](https://github.com/dbeaver/dbeaver/assets/24901793/ac57d5f8-6cff-4312-9420-52f10b0e3144)

![image](https://github.com/dbeaver/dbeaver/assets/24901793/6d277cfc-a13d-4f58-a164-a60d0d55ecd8)

If I then enable _Read database_ , I get this:

![image](https://github.com/dbeaver/dbeaver/assets/24901793/6214b7db-1baf-4b02-8a80-f3ab4247cd91)

Completely lose SQL table/column/alias name foreground. The feature works otherwise, though. 

First day trying the app. Liking it. 

### DBeaver Version

Community 23.3.4.202402010022

### Operating System

Windows 11 Pro

### Database and driver

Microsoft JDBC Driver for SQL Server (MSSQL)

**Comment by uslss** [comment] 2024-02-02 13:44
Thanks for the report.
Reproducible on Microsoft SQL Server 15.00.2000,  Microsoft JDBC Driver 12.4 for SQL Server 12.4.1.0

**Comment by LonwoLonwo** [comment] 2024-02-07 12:49
Hello @rasqual 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by rasqual** [comment] 2024-02-07 17:18
[dbeaverrlog.log](https://github.com/dbeaver/dbeaver/files/14197146/dbeaverrlog.log)

I cleared the logs with _Enable semantic analysis_ enabled. 

I then enabled _Read database_ (noticed immediate errors) and ran a few things.

**Comment by E1izabeth** [comment] 2024-02-07 19:54
Thank you

**Comment by E1izabeth** [comment] 2024-02-08 22:24
@rasqual could you try Early Access version (https://dbeaver.io/files/ea/)? Just download it and run installer - you won't lose any of your connections and settings.
Please let me know, if your issue is solved in this version or not.

**Comment by rasqual** [comment] 2024-02-09 02:21
**With _neither_ option checked, table/column/alias are all gray.** 

I don't know that that's new, though (maybe, maybe not) -- I just realized that I didn't check this with both check-boxes disabled. Sorry about that.

When I enable the first checkbox, table/column/alias have right colors.

When I enable the second checkbox, that's also true. 

So better but not good with both disabled. 

Initially, both settings were enabled and all the statement's table/column/alias strings were just bold red underlined. I had to disable them both and then re-enable for things to be right.

**Comment by E1izabeth** [comment] 2024-02-09 08:02
Thank you for checking. That's intentional that only keywords are highlighted, when checkbox `Enable semantic analysis` is unchecked, because this highlighting of tables and columns depends on this setting. This highlighting is actually our recently added new feature =)
The initial issue with all red is solved too.

Can I close the issue then? It's solved, right?

**Comment by uslss** [comment] 2024-02-12 14:34
seems issue is solved

**Closed as completed by uslss** 2024-02-12 14:34 UTC
Labels: x:mssql, sp:3, xp:normal, xf:sql editor
