### ISSUE TITLE
Wrong timestamp formatting with time zone settings

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13484] opened 2021-08-10 07:19 UTC
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.5

#### Connection specification:
- Database name and version PostgreSQL 12

#### Describe the problem you're observing:
If time zone is set in Timestamp formatting, timestamp fields will display wrong formatting with `f` in pattern. Works correctly when using `S` as milliseconds in pattern.

#### Steps to reproduce, if exist:
1. Create a table with timestamp column
2. Change timestamp formatting to some timezone like `+8`
3. Change formatting to include milliseconds by adding more than one `f` in pattern

**Expected:** Field is formatted with set amount of millisecond digits
**Actual result:** Only one millisecond digit

![duxrAnw67n](https://user-images.githubusercontent.com/82543000/128824828-2c6a681c-e4a3-4d4b-815e-969b5842572e.gif)

**Comment by serge-rider** [comment] 2021-09-01 12:28
Probably duplicate of #13484

**Comment by Matvey16** [comment] 2021-09-06 13:22
This is another issue. It concerns the timestamp formatting for columns without a timezone. The option to change timezone also changes the formatting of second's fractions after the point, while it should only change the displayed hours (plus the timezone value if it is enabled in the custom formatting)

**Comment by serge-rider** [comment] 2021-09-07 09:53
@Matvey16 can't reproduce. Please post video or examples of formatting with and without explicit timezone.
Also please write timestamp format pattern you use.

**Comment by Matvey16** [comment] 2021-09-07 10:25
![Il8QqyY0zs](https://user-images.githubusercontent.com/82543000/132329449-a131f8fa-b447-4fc0-9e74-26f2b5f970a1.gif)

**Comment by serge-rider** [comment] 2021-09-08 06:24
This is how new Java time formatter works. It renders pattern `f` or `n` (nanoseconds) as 9-digit value. Explicit timezone forces new time formatter usage.
In order to show less digits for nanoseconds use `S` pattern. E.g. `SSSS`.

**Closed as completed** 2021-09-08 07:42 UTC
Labels: xf:data, sp:3
