### ISSUE TITLE
[PostgreSQL] Automatically update Database Navigator on DDL

### ISSUE THREAD

**Issue by andywicht** [dbeaver/dbeaver#3003] opened 2018-02-19 13:50 UTC
When using DDL commands e.g. CREATE|DROP TABLE, the user has to manually refresh the database/schema in the Database Navigator field in order to utilise the autocomplete feature in following statements when referencing to the new table/object/column...

Is there already a way to achieve updating the current database connection automatically?

**Comment by lemon-juice** [comment] 2018-02-25 12:08
I haven't found a way to update the database connection but I believe this is done when you refresh the Database Navigator view. I think automatic updating of database structure might be complicated because queries would need to be parsed in order to detect DDL SQL.

But I think it would be good to have a way to refresh database structure easily. Currently, the only way I have found is right click in the Navigator and choose Refresh, which is quite inconvenient. I would like to be able to assign a keyboard short but I haven't found a command for it in the preferences. There is command "Refresh" and it works but only when I first switch to the Navigator but when I am in the SQL editor it won't work.

My suggestions:

1. Add a command "Refresh Database Navigator" to Preferences > Keys so that we can assign a short cut for it that will work from any context.

2. (less important) Add a refresh icon somewhere in the Database Navigator panel, for example next to the New Connection icon.

**Comment by serge-rider** [comment] 2018-04-30 07:52
Seems to be a duplicate of #859

@lemon-juice Standard refresh shortcut (in all views/editors) is <kbd>F5</kbd>. But it works only for active UI part.

It is not very clear what exactly should be refreshed. All elements of navigator? It could take a lot of time (if you have many connections with very complicated metadata structure).

**Comment by lemon-juice** [comment] 2018-04-30 08:40
I agree it is not always clear what should be refreshed but I suggest to cover the most common case and simply refresh all objects of the current database of the editor (including all schemas for databases like PostgreSQL). That would mean loading the same metadata as when I first connect to a database - from my experience DBeaver does it pretty quickly so I don't think performance would be an issue.

So I think a new command like "Refresh current database metadata" would be fine.

**Closed** 2019-11-21 15:48 UTC
Labels: duplicate, feature request
