### ISSUE TITLE
@Set multiple strings in a list as 1 variable

### ISSUE THREAD

**Issue by aspano79** [dbeaver/dbeaver#18684] opened 2023-01-06 06:52 UTC
### Description

I'm trying to set multiple strings in a variable that I can use in multiple case statements within my query. 

@set olv_code = in ('857','858','859','865','866','867','868','869','870’,’871','813','814','815','816','820','821','822','823','824','825','826','819','298', '299', '300', '301', '302', '303', '304', '233', '234', '235', '259', '260', '261', '031', '032', '033')
	
SELECT
campaign, 
CASE est_code = **:olv_code** then 1 else 0 end as test

Any guidance on creating a "list" that can be used in my case statements? I have 49 instances in a 900-line query, and codes need to be added continually so I would prefer to only add the codes once each time.

Thanks in advance!

### DBeaver Version

Community 21.3.5

### Operating System

Windows 10

### Database and driver

Hive
Hadoop / Apache Hive

**Comment by ShadelessFox** [comment] 2023-01-12 14:24
Hello @aspano79,

The `@set` command is not supposed to evaluate to something. It's just replaced by the value assigned to it.

**Closed as not planned by ShadelessFox** 2023-01-12 14:24 UTC
Labels: xf:sql, question

**Comment by E1izabeth** [comment] 2023-01-13 11:03
Duplicate of #10131
