### ISSUE TITLE
DB2  Chinese characters is garbled

### ISSUE THREAD

**Issue by zidian** [dbeaver/dbeaver#22949] opened 2024-02-26 06:23 UTC
### Description

Encoding of tables in DB2 is iso-8859-1， Chinese characters in query result is garbled。

### DBeaver Version

Community Edition 23.3.5

### Operating System

Win10

### Database and driver

DB2

**Comment by LonwoLonwo** [comment] 2024-02-26 10:13
Hello @zidian 

Please provide screens of your issue, as well as your database and driver versions.

**Comment by zidian** [comment] 2024-02-27 00:34
> Hello @zidian
> 
> Please provide screens of your issue, as well as your database and driver versions.

screens   like this：

![微信图片_20240227083311](https://github.com/dbeaver/dbeaver/assets/5879254/3de9f053-1782-4dfe-9390-e8983cadbd69)
![微信图片_20240227083319](https://github.com/dbeaver/dbeaver/assets/5879254/cdffb36f-4ab8-4e18-9423-9a2bff9caf97)

**Comment by ShadelessFox** [comment] 2024-02-29 14:02
Hello @zidian,

You can't encode Chinese characters with Latin-1 encoding. Use UTF-8 instead.

**Comment by zidian** [comment] 2024-03-01 00:13
> Hello @zidian,
> 
> You can't encode Chinese characters with Latin-1 encoding. Use UTF-8 instead.

I have used other tools，such as SqlDbx or DB2 command tools, Chinese characters  in query result  can well display。So， I think  encode Chinese characters with Latin-1 encoding is not problem。

**Comment by serjiokov** [comment] 2024-03-14 12:46
Please, try to change the encoding to UTF-8, the current used **iso-8859-1** is 8 bits which does not fit well for Chinese.

**Comment by zidian** [comment] 2024-04-07 06:43
> Please, try to change the encoding to UTF-8, the current used **iso-8859-1** is 8 bits which does not fit well for Chinese.

We cannot change the encoding 。But we have solved this problem  by using costumed driver with Apache Druid。

**Comment by E1izabeth** [comment] 2024-04-12 06:38
Thank you for update. As far as I understood, the issue is solved. So, I'm closing the issue.

**Closed as not planned by E1izabeth** 2024-04-12 06:38 UTC
Labels: x:db2, xf:data, wait for response, question, xf:encoding
