### ISSUE TITLE
Extensions are gone after update

### ISSUE THREAD

**Issue by davinishi** [dbeaver/dbeaver#18115] opened 2022-11-03 16:41 UTC
### Description

Every time I run an update, the extensions for Office and Git are removed and/or broken.

I´ve seen closed issues on this subject but none of them are really solving the problem, they are just guiding the users on how to amend after the problem's happened.

In my case I have the following scenario:

- DBeaver for Windows 22.2.3 installed for single user on C:\Users\user\AppData\Local\DBeaver
- Personal workspace created on C:\Users\user\OneDrive - user

Office's extension has an aggravation factor, reinstalling it after an update is always painful and time consuming, it is needed at least a couple of restarts and attempts.

### DBeaver Version

22.2.3

### Operating System

Windows 10

### Database and driver

Not relevant

### Steps to reproduce

1. Install Office or Git extension
2. Update DBeaver
3. Open Dbeaver and check if the extensions are working

**Comment by E1izabeth** [comment] 2022-11-03 16:56
Thank you for bug report. Duplicate of #5317

**Closed as not planned** 2022-11-03 16:57 UTC
Labels: duplicate
