### ISSUE TITLE
Start DBeaver on installer close.

### ISSUE THREAD

**Issue by rburke-orthofi** [dbeaver/dbeaver#18289] opened 2022-11-22 00:58 UTC
**Is your feature request related to a problem? Please describe.**
I open DBeaver, do an upgrade, then it doesn't reopen. If I open DBeaver I'm more than likely wanting to use it, not just upgrade it.

**Describe the solution you'd like**
A checkbox (pre-checked) indicating I want DBeaver to run after installer is closed.

Many applications work like this.

**Comment by ShadelessFox** [comment] 2022-11-22 01:54
Hello @rburke-orthofi,

Thank you for your request.

What is your OS?

**Comment by E1izabeth** [comment] 2022-11-22 11:49
This issue looks like a duplicate of #17878

**Closed as not planned** 2022-11-22 13:28 UTC
Labels: duplicate, xf:installation
