### ISSUE TITLE
plugins deleted by upgrade dbeaver version?

### ISSUE THREAD

**Issue by wonb168** [dbeaver/dbeaver#35494] opened 2024-09-06 06:45 UTC
### Description

I download office plugin,
but when I upgrade dbeaver version,
it disappeared,
I need to download and install it again,
why?

### DBeaver Version

24.1.4

### Operating System

macos 14.6.1

### Steps to reproduce

1. download and install a plugin, ig: office
2. update dbeaver to newest version
3. office plugin disappeared

**Comment by E1izabeth** [comment] 2024-09-06 08:01
Thank you for the bug report.
I'm closing it as it's a duplicate of #5317

**Closed as not planned** 2024-09-06 09:02 UTC
Labels: duplicate
