### ISSUE TITLE
dbeaver用sql语句新建clickhouse表不自动刷新元数据

### ISSUE THREAD

**Issue by wuzhengqiang** [dbeaver/dbeaver#21709] opened 2023-10-31 07:00 UTC
### Description

after create table ，can not press ctrl key and click to load to this table metadata（Table Structure）

### DBeaver Version

23.2

### Operating System

windows10

### Database and driver

connect clickhouse or oracle

### Steps to reproduce

1、open a sql Editor
2、choose a clickhouse connection
3、execute a sql like:
create table tmp.tmp_user_bind_fd
(
id                                      String                comment '绑定关系ID'
,etl_time                               DateTime 		      comment '数据更新时间'
)engine=MergeTree
partition by toYYYYMMDD(etl_time)
primary key (id)
order by (id)
comment 'user bind info'
;
4、select * from  tmp.tmp_user_bind_fd; 
can  return select info,

5、but at this time，
click  tmp.tmp_user_bind_fd and press ctrl key，can not load this table metadata.
the 21.x has no this bug

### Additional context

no

**Comment by LonwoLonwo** [comment] 2023-10-31 09:38
Hello @wuzhengqiang 

Thanks for the report

This is a duplicate of https://github.com/dbeaver/dbeaver/issues/7924

**Closed as not planned by LonwoLonwo** 2023-10-31 09:38 UTC
Labels: duplicate, xf:metadata
