### ISSUE TITLE
Cannot move connection folder to top level

### ISSUE THREAD

**Issue by nagylzs** [dbeaver/dbeaver#17307] opened 2022-08-09 08:42 UTC
### Description

In the connection tree (database navigator), it is possible to move a subfolder between parents. But it is impossible to move it to the top level (e.g. make it a root folder). Today I accidentally moved one of my top folders under another folder, and now I'm stuck with it.

### DBeaver Version

22.1.3

### Operating System

Ubunut 22.04

### Steps to reproduce

1. Create two top folders in the connection tree (database navigator)
2. Create a subfolder inside one of them
3. You can move the subfolder between the two root folders with drag & drop. But you can't move it to the root. (Not with drag and drop, and I could not find any other way to do it.)

**Comment by ShadelessFox** [comment] 2022-12-02 14:42
Duplicate of #15892

**Closed as not planned by ShadelessFox** 2022-12-02 14:42 UTC
Labels: duplicate, xf:navigator
