### ISSUE TITLE
PostgreSQL - SET DATESTYLE crashes connection

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#19027] opened 2023-02-09 19:36 UTC
### Description

DBeaver 22.3.4

Steps to reproduce:
1. Connect to PostgreSQL database
2. Open a new sql editor
3. Execute the command: SET DATESTYLE = 'german'

Now the editor looses connection and tries to invalidate connection again and again.

### DBeaver Version

22.3.4

### Operating System

Mac

**Comment by E1izabeth** [comment] 2023-02-09 20:25
Thank you for bug report

**Comment by Destrolaric** [comment] 2023-02-16 10:55
@JamesInform Hi, it is similar to https://github.com/dbeaver/dbeaver/issues/4244, and looks like the driver issue. Which driver version is used?

**Comment by JamesInform** [comment] 2023-02-16 11:43
![image](https://user-images.githubusercontent.com/38714600/219356019-6acebf62-dfe6-47e1-8ad7-829fcfb3c8a3.png)

**Comment by Destrolaric** [comment] 2023-02-16 11:52
@JamesInform Looked into the issue a bit deeper. Unfortunately, the driver requires ISO, using other leads to disconnect, which is expected behavior because it can't maintain the session with `Datestyle='german'`. Not sure we can do anything about it.

**Comment by E1izabeth** [comment] 2023-02-16 12:04
@Destrolaric can we detect it and do not reconnect endlessly. Also showing some message about what is happening wrong would be beneficial.

**Comment by Destrolaric** [comment] 2023-02-16 12:07
@E1izabeth Tried on the Postgre database, it stopped constantly reconnecting after 30 secs.
The error message is shown later
![image](https://user-images.githubusercontent.com/20579256/219360809-4fa3e7e3-869b-4de7-8a2c-61a1b85c0b53.png)

**Comment by Destrolaric** [comment] 2023-02-21 11:59
Closing as third party issue, driver unfortunately doesn't support German Datestyle and we can't resolve this issue on the DBeaver site.

**Closed as not planned by Destrolaric** 2023-02-21 12:00 UTC
Labels: x:postgresql, xp:major, xf:sql, third party issue, xf:connection
