### ISSUE TITLE
Can't edit data in Data Editor for SQL Server connections 

### ISSUE THREAD

**Issue by ajpuerta** [dbeaver/dbeaver#7597] opened 2020-01-10 10:43 UTC
### System information: 
- Windows 10
- DBeaver 6.3.1 - 6.3.2
- Java 1.8.0_201

#### Connection specification:
- Database name and version: SQL Server
- Driver name: MS SQL Server / SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I cannot edit the data in the "Data Editor" on any SQL Server connection, always appears the message "Column is read only". It's impossible to generate SQL insert statement too. If I install the 6.2.1 version all works well with the same settings.

Check 'Read-only connection' is always disabled.

#### Steps to reproduce, if exist:
1. Create a SQL Server connection.
2. Run a select and try to edit any value in the "Data Editor"
3. The message "Column is read-only" appears.

Thank you.

**Comment by kseniiaguzeeva** [comment] 2020-01-10 10:54
1. Thank you for the bug report regarding possibility to edit data in ResultSet.
2. What way do you use to generate  SQL INSERT statement? I can do it using Context menu of DB Navigator.
![dbeaver_8KPQmIHMZv](https://user-images.githubusercontent.com/51405061/72147935-b0b2f400-33b0-11ea-90c3-f2bac799d932.png)

**Comment by ajpuerta** [comment] 2020-01-10 11:13
I select a row in the resultset and then use context menu, in last versions isn't working. In the editor the table hyperlink isn't working neither.

On the other hand, generate SQL and edit data works in the table data resultset.

**Comment by garrizano** [comment] 2020-01-20 14:24
I have the same problem with version 6.3.1, 6.3.2, 6.3.3. Inline cell editor doesn't work. I'm using Fedora 32, SQL Server 2014, Java 1.8.0_131

**Comment by uslss** [comment] 2020-01-21 17:29
Could you send error stacktrace (or log file)?
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by garrizano** [comment] 2020-01-21 17:52
> Could you send error stacktrace (or log file)?
> https://github.com/dbeaver/dbeaver/wiki/Log-files

There is no errors.
I just can't edit cell inline.

![error](https://user-images.githubusercontent.com/27860124/72829470-7402ba80-3c44-11ea-99dc-18e1ce707039.jpg)

**Comment by dirkesquire** [comment] 2020-01-29 14:03
I'm getting this as well for databases I routinely used to use the Edit Cell feature (double click and edit inline) and also the delete row record. Now it appears as if its readonly. This happened as soon as I upgraded to DBeaver 6.3.2. The previous version of DBeaver didn't have this issue and worked fine. I tried to upgrade java to 13.0.2 and it didn't help.

**Comment by crapp** [comment] 2020-02-03 09:21
Having the same problem with SQL Server 2014 and 2016 (Express versions). Issue is also present in 6.3.4. Logfiles are looking okay. We always had this problem with the new JDBC driver.

It does work if I use the fully qualified name (dbname.schemaname.table)

Windows 10 pro 1903
Dbeaver 6.3.1 - 6.3.4 with bundled jre

**Comment by ajpuerta** [comment] 2020-02-04 10:39
> It does work if I use the fully qualified name (dbname.schemaname.table)

It's true! Using the fully qualified name works

**Comment by dirkesquire** [comment] 2020-02-07 10:16
I downgraded back to dbeaver-community 6.3.0 and the inline cell editing is working again :)

**Comment by ajpuerta** [comment] 2020-02-17 07:10
With the last version appears a tooltip that says: (Read-only: No corresponding table column).
The sentence SQL I've execute was a simple SELECT * FROM table

Using the fully qualified table name it works

**Comment by serge-rider** [comment] 2020-02-17 09:22
@ajpuerta 
- is your table in `dbo` schema? 
- do you use both database and schema names in fully qualified name? what if you will use only schema prefix?
- what driver (MS or jTDS) do you use?

**Comment by ajpuerta** [comment] 2020-02-17 10:06
- My table is in imp schema
- _database.schema.table_ it works, _schema.table_ not
- Microsoft/mssql-jdbc

**Comment by crapp** [comment] 2020-02-17 16:40
Latest version now provides some more context on these ""Read Only" Columns

> Read-only: No corresponding table column

@serge-rider Just to make sure ths information is not lost. I have a connection (old driver jTDS) to a SQL Server instance. Editing cells in the data viewer worked perfect until DBeaver 6.3.0. I did not need to provide a fully qaulified table name. Since 6.3.1 this no longer the case (regardless which driver I use)

**Comment by evgeniyluzman** [comment] 2020-02-20 10:39
Same behavior for  Windows 10, Dbeaver 6.3.5

**Comment by altquant** [comment] 2020-02-20 21:49
@ajpuerta I have the same exact issue with mssql jdbc driver. database.schema.table works, schema.table doesn't.

**Comment by crapp** [comment] 2020-03-04 08:00
Version 7 is affected as well.

I did also try to use the latest jdbc driver version (8.2.1) from Microfsoft. Doesn't help. 

```sql
SELECT SCHEMA_NAME();
```
returns the correct default schema of my user.

**Comment by dirkesquire** [comment] 2020-03-04 09:55
I'm going to stay with using version 6.3.0 until this is resolved. For me, any other feature improvements, aren't worth losing this feature.

**Comment by crapp** [comment] 2020-03-04 16:11
@serge-rider 

I just compared the two tags for 6.3.0 and 6.3.1 on git hub and found theere changes to the behaviour of sql server default schemas

https://github.com/dbeaver/dbeaver/issues/5172

Could a code change for the mentioned issue cause this trouble?

**Comment by serge-rider** [comment] 2020-03-05 08:25
@crapp good point.
Eventually I found the bug. It was in target table search.

You can test the fix in Early Access version (https://dbeaver.io/files/ea)

**Comment by crapp** [comment] 2020-03-05 09:11
@serge-rider 
I have installed Version 7.0.0.202003050802 ( windows x64) but still have the problem.

**Comment by kseniiaguzeeva** [comment] 2020-03-16 15:16
@crapp Does your table has a space in its name?

**Comment by crapp** [comment] 2020-03-16 15:54
@kseniiaguzeeva There are no spaces in the table name and I installed the version I found here https://dbeaver.io/files/ea/

**Comment by kseniiaguzeeva** [comment] 2020-03-17 09:44
Please try the latest release https://dbeaver.io/download/ 
The issue "database.schema.table it works, schema.table not" does not reproduce on this version.

If the issue is still actual for you in the latest release, please reopen the ticket.

**Comment by crapp** [comment] 2020-03-17 10:20
@kseniiaguzeeva The problem still exists in the early access version released on march 5th. I won't reinstall the regular 7.0.0 release because @serge-rider found a bug in that version.

**Comment by weslylopes** [comment] 2020-03-26 22:02
version 7.0.1 is also not working, I went back to 6.1.0, as a colleague mentioned, with this feature I don't need any other.

**Comment by kseniiaguzeeva** [comment] 2020-03-27 03:26
Do you have any steps to reproduce? Could you give a query example?
Which schema is selected in SQL Editor, which schema is active? Which schema does the table belong to?

**Comment by ajpuerta** [comment] 2020-03-27 08:23
Hi @kseniiaguzeeva, it's working only when you use scheme.table but not when you only write the table name.
SELECT * FROM imp.table (it's working)
SELECT * FROM table (not)

**Comment by kseniiaguzeeva** [comment] 2020-03-27 09:34
What's schema your table in?
What schema is active?

**Comment by ajpuerta** [comment] 2020-03-27 09:37
As I said in issue #8201
"My tables are in imp schema and I connect with imp user. Conversely, the scheme active in DB Navigator tree is dbo@xxxxx"

**Comment by crapp** [comment] 2020-03-27 09:40
Same problem for me. try a 

`SELECT SCHEMA_NAME();`

This will show you your users default schema and is in my case not dbo. Nevertheless dbo seems to be the active schema.

**Comment by serge-rider** [comment] 2020-03-30 07:16
Partially fixed in #8222 (table recognition was broken for table names in square brackets).

**Comment by serge-rider** [comment] 2020-03-30 09:20
Current schema detect fixed.
Please check how it works in Early Access version (https://dbeaver.io/files/ea)

**Comment by d3claes** [comment] 2020-03-31 08:43
I can confirm that the problem is fixed in latest EA-version, but not when the schema name has brackets.
E.g. database.[62b].table -> still read-only

**Comment by serge-rider** [comment] 2020-03-31 10:46
@d3claes unfortunately @Jsqlparser doesn't support such syntax (schema name which start with number in square brackets). Hopefully next version will.

Workaround: use double quotes: `database."62b".table`
Perhaps we need to use double quotes by default for SQL Server. Or add an extra parameter.

**Comment by dirkesquire** [comment] 2020-03-31 12:08
OS: macOS Mojave 10.14.6
Version: **6.3.0.201912042122**
SQL: select * from ml.Comment
Results: Can edit cells, insert new rows, delete rows.

Version: **6.3.2.202001051908**, **6.3.5.202002151353**
SQL: select * from ml.Comment
Results: New record and delete record buttons disabled, can enter edit cell, but it will not persist.

Version: **7.0.1.202003211804**
Results: Can edit cells, insert new rows, delete rows.

Nice work! Well done!!!!

**Comment by crapp** [comment] 2020-03-31 12:17
I can confirm that latest ea version 7.0.2 does recognize the correct schema

But I can still not edit cells in the data editor when I made a select without any schema.

`SELECT * from bla` 

where bla is in schema blubb.

**Comment by serge-rider** [comment] 2020-04-01 08:08
@crapp Is `blubb` is you active schema? It is in the active schema selector in the main toolbar.

**Comment by crapp** [comment] 2020-04-01 11:02
@serge-rider Okay here is the thing. If I create a new SQL Editor for my connection it shows the correct connection but only the database (blubb) is shown in the schema selector. Autocompletion does not work and Result Sets are read only.

If I then change the active schema to something else and back to my schema the schema selector dropdown shows blubb@blubb and now everything works.

**Comment by serge-rider** [comment] 2020-04-02 09:55
One more issue with default schema init fixed.

**Comment by kseniiaguzeeva** [comment] 2020-04-04 13:13
Closed. Please crete new ticket if some of the issues is still actual for 7.0.2.

**Comment by chasen-bettinger** [comment] 2020-06-15 04:27
I am using 7.1.0 (Windows 10) and I am experiencing this issue. 

![image](https://user-images.githubusercontent.com/24480592/84617993-f7d87000-ae8d-11ea-9667-214d51cd92b4.png)

While there is data inside of this table, clicking on `View Table` tells me that the table has no columns. I cannot view the data through a select statement and then edit it. 

![image](https://user-images.githubusercontent.com/24480592/84618061-30784980-ae8e-11ea-9b87-da565915a2d2.png)

Tells me there is no corresponding table column.

**Comment by kseniiaguzeeva** [comment] 2020-06-22 09:20
Please create a new ticket and write steps to reproduce.

**Comment by Cesar10n** [comment] 2020-06-26 15:20
I have the same issue with the latest version 
![image](https://user-images.githubusercontent.com/67474393/85873150-5955e400-b796-11ea-8225-92fd59adc494.png)
![image](https://user-images.githubusercontent.com/67474393/85873366-a20d9d00-b796-11ea-9042-233c732405ed.png)

**Comment by michael-van-der-kamp** [comment] 2020-06-29 08:28
Same here, using  DBeaver IDE 7.1.1.202006211844 (Eclipse plugin):

![grafik](https://user-images.githubusercontent.com/67580421/85991062-3411e180-b9f3-11ea-995b-388b5c2b8f0d.png)

**Comment by kseniiaguzeeva** [comment] 2020-06-30 08:36
@michael-van-der-kamp hotfix was published  to solve this Oracle issue. Please try to dowload 7.1.1 again https://dbeaver.io/download/

@Cesar10n Please create new ticket and describe your situation. I can edit SQL Server tables in 7.1.1. Which schemas do you use?

**Comment by deepskyblue86** [comment] 2020-07-01 11:30
@kseniiaguzeeva I downloaded the 7.1.1 again following your suggestion and I still have the issue.
I downloaded [this](https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb) and I got Version 7.1.1.202006211844, which is the same as @michael-van-der-kamp (even if mine is not the plugin). I'm with Oracle too.
Which version should have the fix?

> @michael-van-der-kamp hotfix was published to solve this Oracle issue. Please try to dowload 7.1.1 again https://dbeaver.io/download/
> 
> @Cesar10n Please create new ticket and describe your situation. I can edit SQL Server tables in 7.1.1. Which schemas do you use?

**Comment by GTmAster** [comment] 2020-07-01 13:02
Same issue here, Version 7.1.1.202006211844

**Comment by deepskyblue86** [comment] 2020-07-01 13:20
> Same issue here, Version 7.1.1.202006211844, Oracle DB. Fully qualified name doesn't help.

@GTmAster I downgraded and that one works: https://dbeaver.io/files/7.1.0/

**Comment by paul-green** [comment] 2020-07-06 02:45
Also had this problem but only on Oracle connections - downgraded to 7.1.0 as per @deepskyblue86 and it now works.

**Comment by kseniiaguzeeva** [comment] 2020-07-06 09:15
Could you please try the latest 7.1.2? https://dbeaver.io/download/

**Comment by paul-green** [comment] 2020-07-06 22:22
Yes this now works as expected for me. Thanks @kseniiaguzeeva

**Comment by GTmAster** [comment] 2020-07-07 13:37
@kseniiaguzeeva Works like a charm. Thanks!

**Comment by aterilio** [comment] 2020-07-15 06:07
In version 7.1.2, the same error occurs in the Tibero connection using the jdbc driver.
When I type the user name in front of the table name, the result was inquired in a modifiable state.
In the previous version, just the table name was enough.
Which version should I downgrade to?
![image_version](https://user-images.githubusercontent.com/29734929/87509617-e8c32880-c6ac-11ea-8638-f09908fa5ecc.png)

**Comment by jazzfog** [comment] 2020-08-03 21:01
Struggling with the same on `7.1.3` version.

**Comment by cacing69** [comment] 2020-08-04 01:51
> Struggling with the same on `7.1.3` version.

yeah i think i got the same problem here, got this error after update

**Comment by cacing69** [comment] 2020-08-04 01:53
![image](https://user-images.githubusercontent.com/36250619/89244150-fdea0200-d62f-11ea-86cf-3f2abd71ec6a.png)

**Comment by jazzfog** [comment] 2020-08-04 04:44
I was able to get that column updated after I switched to `Properties` tab and reloaded the data on it (the column I was trying to update was relatively new and it was not on the Properties tab back when it was initially opened (column was added by other means)).

**Comment by madmatt112** [comment] 2020-08-18 02:02
> I was able to get that column updated after I switched to `Properties` tab and reloaded the data on it (the column I was trying to update was relatively new and it was not on the Properties tab back when it was initially opened (column was added by other means)).

This also removed the read-only state from my columns. Thanks.

**Comment by kseniiaguzeeva** [comment] 2020-08-18 14:51
@jazzfog , @madmatt112 , @cacing69 please answer:
which database do you use?
Do you query for default/non default schema?
Could you please give a query example?

**Comment by cacing69** [comment] 2020-08-18 14:54
> @jazzfog , @madmatt112 , @cacing69 please answer:
> which database do you use?
> Do you query for default/non default schema?
> Could you please give a query example?

i used mariadb, forget about version, later i will tell u

used a default schema and not using query there @kseniiaguzeeva

**Comment by jazzfog** [comment] 2020-08-18 15:04
I used either mariadb or MySQL, can't recall now.
I was not querying anything manually, it was the data view tab.

**Comment by kseniiaguzeeva** [comment] 2020-08-18 17:07
Thank you for your help. Finally I could reproduce it (MariaDB and SQL Server are tested). 
Steps:
1. Open a table in Data Editor
2. Open SQL Editor and create a column for this table
3. Go back to the Data Editor of this table and refresh it

Actual result: new column appears in read-only mode.
![vB2KH4YQPV](https://user-images.githubusercontent.com/51405061/90543424-5c65c300-e18e-11ea-9604-8c1590aa972f.gif)

**Comment by kseniiaguzeeva** [comment] 2020-08-19 10:33
A little investigating was needed. This behaviour is "expected" for now. Such FR already exists https://github.com/dbeaver/dbeaver/issues/9283.
The ticket is closed as a duplicate.

P.S. If any other issues happen with turning on read-only mode, please create new tickets. This one already has many different cases.
Thank you!

**Closed by kseniiaguzeeva** 2020-08-19 10:33 UTC
Labels: bug

**Comment by yjd** [comment] 2020-12-03 02:08
windows dbeaver (free) 7.3.0 connect to remote sqlserver the same problem.

**Comment by Qleoz12** [comment] 2020-12-07 02:38
windows dbeaver 
DB sybase 
Driver JTDS 
same problem im downgrading... DBbearer 7.3 >6.3

**Comment by drakut** [comment] 2020-12-22 20:03
Have the same trouble with 7.3.0
Oracle 12c
Downgrading to 6.3 didn't helped

**Comment by kseniiaguzeeva** [comment] 2020-12-24 07:48
Cannot reproduce it. Please open a new ticket and write a query example.

**Comment by mohdmusthafa** [comment] 2020-12-31 08:54
I just reconnected to the db and the issue is fixed

**Comment by novecentonove** [comment] 2021-02-05 14:40
Same issue.
I'm using Ubuntu 20.10, just close Dbweaver and reopen it, problem solved

**Comment by IDRIMalek** [comment] 2021-03-14 06:04
Same issue.
I've just downgrade. 
Work again.

**Comment by isuruamantha** [comment] 2021-04-01 10:15
Restarting the DBviewer helped me

**Comment by AnandKumarTokopedia** [comment] 2021-08-12 05:36
It is actually happening because the Table is updated, but the table columns are not updated.
You can do one thing after updating the table refresh the column too
`from the left pane ->table_name->Columns(right-click)->refresh`
No need for a restart.

**Comment by pwin0220** [comment] 2021-08-17 06:13
For me it happens when I do an automated creation of Table and Columns, where the source name contains a space in the end of its column name definition "Columnname ", in my case I'm using an excel as rawdata, reading it with (python) pandas df=pd.read_excel and creating the table/columns with df.to_sql.
If the excel sheets columns has a space in the end of the name I will get the "locked" behaviour because of a mismatch in the interpretation of names.

**The properties has the end-space in the column name but the data view does not.**

Removing the end-space in the properties=>column name of the column or removing it from the source before import/creation and a table refresh fixes the problem.

**Comment by KeithTt** [comment] 2021-11-09 03:34
> I used either mariadb or MySQL, can't recall now. I was not querying anything manually, it was the data view tab.

Thanks for your info, I just close the tab and reopen it, then the `read-only` tips gone.

**Comment by luna1522** [comment] 2025-04-24 06:20
I had the same question ,but now it fixed,I can modify the data in the table.This issue is because the database type I'm connecting to is MySQL(old),Then I reconnect to the database with select MySQL.
