### ISSUE TITLE
Possibilty to open multiple instances with the same user profile without the can't lock workspace error.

### ISSUE THREAD

**Issue by 0luc** [dbeaver/dbeaver#15510] opened 2022-02-16 12:59 UTC
#### Describe the problem you're observing:
Hi, I've noticed the following results;

When using **-con** combined with **-reUseworkspace** = -con merges into one instance like expected;
When using **-con** combined with **-newInstance** = can't lock workspace at ..... error at starting second instance;
When using **-con** with **-newInstance** and **-reUseworkspace** (to suppress the can't lock workspace error) =can't lock workspace at ..... error at starting second instance.

I would like to open a new instance, but with the same user profile, and without the can't lock workspace error. How can I achieve this?

I know my usecase is a bit specific. I've worked arround this by generating a new user profile for every new session. However that way usersettings can only be saved per instance.

**Comment by uslss** [comment] 2022-02-17 08:53
thanks for the suggestion
closed as a duplicate of #14364

**Closed as completed by uslss** 2022-02-17 08:53 UTC
Labels: duplicate
