### ISSUE TITLE
Adding indent/outdent hotkeys for multiple lines

### ISSUE THREAD

**Issue by Nick-Nal** [dbeaver/dbeaver#21089] opened 2023-09-01 11:14 UTC
Greetings

I want to ask about adding one text-editing feature which I'm missing a lot when switching to DBeaver from VSCode

There are these optional key preferences in VSCode:
![image](https://github.com/dbeaver/dbeaver/assets/92499666/56d18f9b-f28c-4f32-86e2-91a8468a2b25)

It can add/remove tabulation to/from the beginning of multiple lines at once - that's pretty handy for formatting nested SQL queries

**Comment by E1izabeth** [comment] 2023-09-01 15:27
I can perform it by selecting several lines and pressing Tab or Shift+Tab this way
https://github.com/dbeaver/dbeaver/assets/28875055/e05623ba-5a2e-4847-91a2-a86af18425f2

Am I correctly understood what you mean? Does it satisfy your needs?

**Comment by E1izabeth** [comment] 2023-09-19 20:58
Also it may be a duplicate of #7280.

**Comment by E1izabeth** [comment] 2023-09-19 20:59
However, it's been a while since no update on this issue. If the issue is still actual please let me know and provide additional information regarding the requested behavior.

**Closed as not planned by E1izabeth** 2023-09-19 20:59 UTC
Labels: wait for response, question
