### ISSUE TITLE
Mouse right click on tree node not working

### ISSUE THREAD

**Issue by medmedin2014** [dbeaver/dbeaver#7128] opened 2019-10-31 11:51 UTC
#### System information: 
- Ubuntu Mate 19.10 - 64bits
- DBeaver version 6.2.3

If I select any node in any tree view, like database navigator or projects view, and I click on right mouse button, the contextual menu is not appearing and I should always use keyboard to display it.
The right contextual menu is very critical to update changes inside tree view because dbeaver doesn't automatically apply changes to tree nodes after doing any change like creating/deleting  tables.

**Comment by serge-rider** [comment] 2019-11-02 15:39
Duplicate of #6489
Thanks for the bug report anyway

**Closed by serge-rider** 2019-11-02 15:39 UTC
Labels: bug, duplicate
