### ISSUE TITLE
Edit cell window for varchar

### ISSUE THREAD

**Issue by iwex** [dbeaver/dbeaver#9069] opened 2020-06-22 17:02 UTC
Hello! I have Dbeaver 7.1.0. In previous versions I was able to press Shift+Enter on varchar cell to edit it in separate window. Now I can't, it is possible only with INT and some other types.
![image](https://user-images.githubusercontent.com/4510068/85315262-625b6280-b4c3-11ea-9fc3-8bdd1d01fd05.png)

**Comment by quiescer** [comment] 2020-06-22 22:18
I've also just upgraded to 7.1.1 and I can't edit cells.

**Comment by iwex** [comment] 2020-06-23 00:28
@quiescer No, mysql :)

**Comment by uslss** [comment] 2020-06-23 13:50
Hi @iwex , cannot reproduce it. What driver and db version do you use?

@quiescer mentioned issue is fixed in scope of #9060

**Comment by iwex** [comment] 2020-06-23 17:20
@uslss Dbeaver Version 7.1.0.202006152217, mysql:mysql-connector-java:RELEASE 5.1.44

**Comment by llorephie** [comment] 2020-06-30 13:51
Same behavior (Read-only everything if used filter in data panel or in SQL script) on Oracle Database, auto-downloaded driver
![screenshoot](https://user-images.githubusercontent.com/3751049/86134072-d7492080-baf1-11ea-8089-34de006c9644.png)

**Comment by iwex** [comment] 2020-07-01 15:17
@uslss any news?

**Comment by uslss** [comment] 2020-07-06 11:47
@iwex , unfortunately still cannot reproduce an issue. Are there any errors in Logs?

**Comment by iwex** [comment] 2020-07-06 12:06
@uslss thanks for this idea :)

**Comment by LonwoLonwo** [comment] 2020-08-11 13:14
still can't reproduce.
@iwex can you try in version 7.1.4? https://dbeaver.io/download/
and few questions. Are these varchar and others columns read-only? What OS you have?

**Comment by quiescer** [comment] 2020-08-11 21:16
I am not seeing this error on 7.1.3 or 7.1.4

**Comment by serge-rider** [comment] 2020-08-18 09:12
@quiescer Thanks for the info

**Closed by serge-rider** 2020-08-18 09:12 UTC
Labels: bug, can't reproduce, x:mysql

**Comment by iwex** [comment] 2020-12-28 02:50
The same issue with 7.3.0.
```
> Start DBeaver UI Editors - Hex [org.jkiss.dbeaver.ui.editors.hex 1.0.46.202012052119]
2020-12-28 04:49:36.472 - Event loop exception
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.jkiss.dbeaver.ui.editors.binary.HexEditControl.composeByteToCharMap(HexEditControl.java:505)
	at org.jkiss.dbeaver.ui.editors.binary.HexEditControl.setCharset(HexEditControl.java:528)
	at org.jkiss.dbeaver.ui.editors.binary.HexEditControl.initialize(HexEditControl.java:756)
	at org.jkiss.dbeaver.ui.editors.binary.HexEditControl.<init>(HexEditControl.java:187)
	at org.jkiss.dbeaver.ui.editors.binary.HexEditorService.createHexControl(HexEditorService.java:39)
	at org.jkiss.dbeaver.ui.data.dialogs.TextViewDialog.createDialogArea(TextViewDialog.java:150)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:767)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.jkiss.dbeaver.ui.data.dialogs.ValueViewDialog.open(ValueViewDialog.java:234)
	at org.jkiss.dbeaver.ui.data.dialogs.ValueViewDialog.showValueEditor(ValueViewDialog.java:118)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.lambda$3(SpreadsheetPresentation.java:1122)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4930)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4451)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:235)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

**Comment by iwex** [comment] 2020-12-28 02:56
I've found the problem - my java version is 8. On 14 - everything is ok :+1:
