### ISSUE TITLE
Inválid Rows fetched

### ISSUE THREAD

**Issue by ricgavira** [dbeaver/dbeaver#12023] opened 2021-04-07 12:30 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.0.2

#### Connection specification:
- Database name and version: SQLServer 2012

#### Describe the problem you're observing:

SQLEditor with 7 statements, the result1 show 0 row(s) fetched, but exist 54 rows in the grid.

It is probably showing the affected lines from the last tab.

Thanks

**Comment by uslss** [comment] 2021-04-08 09:53
@ricgavira could you provide screenshots/video with an issue? 
Table DDL and query examples also will be very useful for issue investigation

**Comment by ricgavira** [comment] 2021-04-08 11:37
![Screenshot_1](https://user-images.githubusercontent.com/11458628/114019934-ffae3a00-983c-11eb-8a84-79a9026f5a23.png)


There are 7 queries in the same sqleditor, each one opens in a tab. Only the first tab contains data, the other 6 are empty.

**Comment by ricgavira** [comment] 2021-04-08 11:56
![Screenshot_2](https://user-images.githubusercontent.com/11458628/114022398-b7444b80-983f-11eb-8aaa-3348ca87a7e4.png)

Tab 1 with two records, Tab 2 Empty

The status displayed on the first tab is referring to the result of the second tab

**Comment by uslss** [comment] 2021-05-11 12:14
thanks for the report and clarification

**Comment by ShadelessFox** [comment] 2021-06-17 13:33
Hello @ricgavira,

Even after following clarification I cannot reproduce your issue. If the result set contains no rows, it displays <kbd>No data</kbd>.

I don't see any `SELECT` keyword in your query. What statement are you trying to execute?

Please provide more information.

**Comment by ricgavira** [comment] 2021-06-17 15:15
> 
> 
> Hello @ricgavira,
> 
> Even after following clarification I cannot reproduce your issue. If the result set contains no rows, it displays No data.
> 
> I don't see any `SELECT` keyword in your query. What statement are you trying to execute?
> 
> Please provide more information.


Perhaps the latest updates have fixed the problem. If I find the problem again I will post the error again.

**Comment by ShadelessFox** [comment] 2021-06-17 15:17
Okay, thanks for the response!

I will close this ticket for now, but you still can post comments here.

**Closed as completed by ShadelessFox** 2021-06-17 15:17 UTC
Labels: can't reproduce, x:mssql, xf:sql
