### ISSUE TITLE
Raise Info messages are not appearing in the output viewer

### ISSUE THREAD

**Issue by alchemistmatt** [dbeaver/dbeaver#21918] opened 2023-11-21 00:51 UTC
### Description

When a PostgreSQL procedure or anonymous code block uses `RAISE INFO` or `RAISE WARNING` to raise a message, the message is not appearing in the output viewer (aka output tab).  This has worked in all previous versions, but is not working in v23.2.5.  I updated my PostgreSQL JBDC Driver, but that did not fix things.

I uninstalled v23.2.5 and installed v23.2.4 and then the expected behavior returns, so this issue is specific to v23.2.5.

### DBeaver Version

Community Edition 23.2.5

### Operating System

Windows 10 Enterprise

### Database and driver

PostgreSQL 15.5
PostgreSQL JBDC Driver 42.5.2

### Steps to reproduce

Running the following anonymous code block should show the current timestamp in the output tab, but it does not:
```sql

DO
LANGUAGE plpgsql
$$
DECLARE   
    _currentTime timestamp;
BEGIN     
    _currentTime := CURRENT_TIMESTAMP;

    RAISE Info 'Current time: %', _currentTime;
END
$$;
```
![OutputWindowBugReport_2023-11-20a](https://github.com/dbeaver/dbeaver/assets/6363449/b03de677-c73d-41f1-9872-76c133da6c21)

In contrast, running the above SQL in `psql` shows:
```
INFO:  Current time: 2023-11-20 16:29:25.221739
```

In v23.2.4 the message appears in the output tab.

![OutputWindowBugReport_2023-11-20b](https://github.com/dbeaver/dbeaver/assets/6363449/c4db69e6-5020-4997-b1ae-02dd06f8a734)

**Comment by alchemistmatt** [comment] 2023-11-21 00:59
I just realized the behavior I'm seeing is the same as issue #21902

**Comment by alchemistmatt** [comment] 2023-11-21 01:23
In Issue #21902 E1izabeth asked if Debug, Log, Info, Notice, Warning, and Error were enabled in the output tab's dropdown filter. Yes, those are all enabled for me as well.

**Comment by E1izabeth** [comment] 2023-11-21 07:03
@alchemistmatt 
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by E1izabeth** [comment] 2023-11-21 07:52
I'm closing it as a duplicate of #21902
We received several reports about that. Let's gather all in one first issue.

**Closed as not planned by E1izabeth** 2023-11-21 07:52 UTC
Labels: duplicate
