### ISSUE TITLE
postgres backup error

### ISSUE THREAD

**Issue by bouyeijiang** [dbeaver/dbeaver#36498] opened 2024-12-09 12:49 UTC
### Description

2024-12-09 20:39:54.832 - IO error: Process failed (exit code = 1). See error log.
2024-12-09 20:39:54.832 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)

### DBeaver Version

24.3

### Operating System

win 11

### Database and driver

pg 12

**Comment by E1izabeth** [comment] 2024-12-10 19:50
Could you please reproduce the issue once again? After you reproduce the issue, please send us the DBeaver log files. You can collect them to archive automatically with `Help->Collect Diagnostic Info`
![image](https://github.com/user-attachments/assets/51c7ca2e-6be2-489e-b495-028b9aa0e386)

The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by bouyeijiang** [comment] 2024-12-10 19:51
谢谢您的来信！我会及时查阅的

**Comment by bouyeijiang** [comment] 2024-12-11 01:14
[dbeaver-diagnostic-info-1733879205963.zip](https://github.com/user-attachments/files/18088053/dbeaver-diagnostic-info-1733879205963.zip)

**Comment by E1izabeth** [comment] 2024-12-12 11:58
Could you try reproducing the issue again and provide full text from the database dump wizard? We're interested in the messages before this error

**Comment by bouyeijiang** [comment] 2024-12-13 01:37
I operated normally according to the functional steps. I doubt if it has been tested for usability, because I tried this feature several years ago but couldn't succeed

**Comment by ShadelessFox** [comment] 2024-12-19 11:51
I assume the issue is resolved. Therefore, I'm closing the ticket.

**Closed as completed by ShadelessFox** 2024-12-19 11:51 UTC
Labels: x:postgresql, xf:native clients
