### ISSUE TITLE
When encountering an Oracle database, batch execution of SQL reports an error.

### ISSUE THREAD

**Issue by QloveB** [dbeaver/dbeaver#29330] opened 2024-05-04 07:34 UTC
### Description

When encountering an Oracle database, batch execution of SQL reports an error. But there is no problem when executing each SQL separately.

### DBeaver Version

24.0.3.202404211624

### Operating System

Windows 10 Professional 22H2

### Database and driver

1、Database name and version: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production 
2、Driver name and version: ojdbc11-23.2.0.0.jar

### Steps to reproduce

1. Execute the following SQL：
```
CREATE TABLE TO_CM_GS_NE_ROUTE_D (	
    UUID NVARCHAR2(36) PRIMARY KEY,
    NET_TYPE NVARCHAR2(100),
    NE_TYPE NVARCHAR2(100),
    NE_NAME NVARCHAR2(100)
);
```

2. Select the following SQL in the SQL editor and click on batch execution to report an error.
```
COMMENT ON COLUMN TO_CM_GS_NE_ROUTE_D.UUID IS 'XXX';
COMMENT ON COLUMN TO_CM_GS_NE_ROUTE_D.NET_TYPE IS 'XXX';
```

3. The error message is as follows:
```
SQL 错误 [922] [42000]: ORA-00922: 选项缺失或无效

  Error : 922, Position : 854, SQL = CREATE TABLE TO_CM_GS_NE_ROUTE_D (	
    UUID NVARCHAR2(36) PRIMARY KEY,
    NET_TYPE NVARCHAR2(100),
    NE_TYPE NVARCHAR2(100),
    NE_NAME NVARCHAR2(100)
);

COMMENT ON COLUMN TO_CM_GS_NE_ROUTE_D.UUID IS 'XXX';
COMMENT ON COLUMN TO_CM_GS_NE_ROUTE_D.NET_TYPE IS 'XXX', Error Message = ORA-00922: 选项缺失或无效

  ORA-00922: 选项缺失或无效
```

4. There is no problem executing the SQL in the second supplement separately.

5. The preliminary judgment is that when executing in bulk, the SQL editor determines that the selected SQL has an issue.

### Additional context

The same SQL statement and operation method did not occur in lower versions.

**Comment by E1izabeth** [comment] 2024-05-04 07:39
Thank you for bug report.
It's a duplicate of #26416
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Closed as not planned** 2024-05-05 11:33 UTC
Labels: wait for response, xf:sql execution
