### ISSUE TITLE
Search DB Objects (Metadata) it's not working!

### ISSUE THREAD

**Issue by juniovitor** [dbeaver/dbeaver#3894] opened 2018-07-31 21:18 UTC
Hi all,

I'm using the new release for DBeaver 5.1.4 and the action to find/search objects in DB MetaData it's not working.

You can try it following the steps:
1) Click on Search DB Metadata;
2) Enter an object name;
3) Click on "Search"button and check that nothing is happening! :(

<img width="1135" alt="screen shot 2018-07-31 at 18 12 02" src="https://user-images.githubusercontent.com/34143557/43487681-b338594e-94ed-11e8-9db6-a2693892308e.png">

- DBeaver 5.1.4
- OS: Mac OS High Sierra (10.13.6)

Can you help me?

Thanks,

Junio Vitor

**Comment by serge-rider** [comment] 2018-08-03 06:42
Duplicate of #3863

**Closed by serge-rider** 2018-08-03 06:42 UTC
Labels: bug, duplicate

**Comment by juniovitor** [comment] 2018-08-03 20:32
Tks!
