### ISSUE TITLE
Unterminated string literal errors with Excel export on query with dynamic parameters

### ISSUE THREAD

**Issue by ethanherbertson** [dbeaver/dbeaver#7131] opened 2019-10-31 22:54 UTC
#### System information: 
- Windows 10 (1903), build 18362.418
- DBeaver 6.2.3.201910211155
- DBeaver Office Support 1.1.56.201910211155
- DevStyle (includes Darkest Dark Theme) 1.11.0.201909171704

#### Connection specification:
- PostgreSQL 10.9
- PostgreSQL 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:

For a query with a dynamic bind parameter, the excel export extension raises an "Unterminated string" error if, in the "Bind Parameter(s)" popup, you click 'OK' without editing a previously-used string value.

#### Steps to reproduce, if exist:

Enter a bind-parameter query and execute it once, providing some string value:

![image](https://user-images.githubusercontent.com/6392396/67991189-5a824180-fc06-11e9-87b3-479f416afa8d.png)

Now click the "Excel" extension's button to export your query result to Excel. You'll be prompted with the "Bind Parameter(s)" popup again, but this time it will remember the previous value you gave it. *Click 'OK'.* (Do not change the parameter's value.)

![image](https://user-images.githubusercontent.com/6392396/67991267-a208cd80-fc06-11e9-8442-1d5064d4c53f.png)

You will receive an "Unterminated string literal" error that references the last character in your query, like this:

![image](https://user-images.githubusercontent.com/6392396/67991316-cb295e00-fc06-11e9-8f7b-26c9421c6f5d.png)

#### Include any warning/errors/backtraces from the logs

Copying the error out of the Error Log gives:

```
org.jkiss.dbeaver.model
Error
Thu Oct 31 17:51:06 CDT 2019
Unterminated string literal started at position 21 in SQL select 'hello world'd' as does_not_matter. Expected  char

org.postgresql.util.PSQLException: Unterminated string literal started at position 21 in SQL select 'hello world'd' as does_not_matter. Expected  char
	at org.postgresql.core.Parser.checkParsePosition(Parser.java:1272)
	at org.postgresql.core.Parser.parseSql(Parser.java:1180)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:1124)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:40)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:314)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:285)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:468)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:399)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:769)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2854)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataContainer.readData(ResultSetDataContainer.java:115)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:196)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetHandlerOpenWith$1.run(ResultSetHandlerOpenWith.java:201)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by ethanherbertson** [comment] 2019-10-31 22:57
Possibly related: If the previous value is a numeric literal instead of a string (e.g. 1), the export completes but the column alias is... corrupted? Trimmed?

![image](https://user-images.githubusercontent.com/6392396/67991645-e6e13400-fc07-11e9-9b23-6ad1a992e804.png)

No error is reported in the Error log, however.

**Comment by serge-rider** [comment] 2019-11-02 15:36
Duplicate of #7038
It doesn't look like the same issue but it is caused by the same reason.

Thanks for the bug report anyways

**Closed by serge-rider** 2019-11-02 15:36 UTC
Labels: bug, duplicate
