### ISSUE TITLE
Windows update: streamline update process

### ISSUE THREAD

**Issue by tmssngr** [dbeaver/dbeaver#20582] opened 2023-07-17 08:43 UTC
**Is your feature request related to a problem? Please describe.**
When starting DBeaver, it checks for updates and reports them.
It should be able to download it right now, but install only on exit.

When installing after the DBeaver start, keep all the installation options as they are, e.g. don't ask for desktop icon.
And, because I started DBeaver not for fun, but for using it, suggest to restart it automatically after the setup finished.

**Describe alternatives you've considered**
Currently, it is inconvenient, to launch DBeaver, it installs updates, to relaunch it again.

Please have a look at [Paint.Net](https://www.getpaint.net/) how they handle updates.

**Comment by E1izabeth** [comment] 2023-07-17 08:50
Duplicate of #13457

**Closed as completed** 2023-07-20 12:45 UTC
Labels: duplicate
