### ISSUE TITLE
dBeaver 23.0.3  export to Text now escaping "

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#19812] opened 2023-04-26 13:23 UTC
### Description

When exporting the results of a query to text dBeaver 23.0.3 has started escaping double quotes in the output.

CREATE UNIQUE INDEX "FOO"."BAR" ON ...

now becomes:
CREATE UNIQUE INDEX \\"FOO\\".\\"BAR\\" ON ...

as you can see in the attached image, it doesn't happen in the grid results nor in the individualized value just in the exported output.

this only started happening after upgrading to the current 23.0.3 version
![dBeaver_23 0 3_escaping_characters_20230426_091621](https://user-images.githubusercontent.com/3697063/234588723-9e83e525-197f-4868-addb-82388454df09.png)

### DBeaver Version

Community Edition 23.0.3

### Operating System

Windows 10

### Steps to reproduce

write a select statement that contains " in the output
export to text
" are escaped to \" in the output

**Comment by LonwoLonwo** [comment] 2023-05-04 09:43
Hello @coleman-rik 

Unfortunately, I'm not able to reproduce your issue for now.

Please provide the DDL of your table and this data transfer settings page screen:

![2023-05-04 12_42_42-Data Transfer](https://user-images.githubusercontent.com/45152336/236169448-97b60697-82e7-4ed3-9fb3-718aabd46c49.png)

**Comment by E1izabeth** [comment] 2023-05-30 16:37
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.

Probably it's a duplicate of  #19992

**Closed as not planned by E1izabeth** 2023-05-30 16:37 UTC
Labels: can't reproduce, xf:datatransfer, wait for response
