### ISSUE TITLE
Data Export settings not saved between executions.

### ISSUE THREAD

**Issue by hproctor-tw** [dbeaver/dbeaver#6878] opened 2019-09-30 18:51 UTC
Prior versions (< 6.2.0) would save the last values used in data export dialogs. 6.2.1 appears to forget them and supply the default values only. I have looked to see if config changes had been done and if there was a way to set the defaults, but I have not found any.

Version : 6.2.1.201909221630
Database: PostgreSQL

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by Condor70** [comment] 2019-10-03 11:19
The export feature in the previous version 6.2.0 was still ok.

I reinstalled 6.2.0 and it seems that 6.2.1 does indeed save the CSV export settings (I can see the changes from 6.2.1 in 6.2.0), but it doesn't use them when reopening the export form.

Another bug in 6.2.1 is that the CSV Export always uses quotes, even when "Quote always" isn't checked. So there is no way to only quote when required.

**Comment by serge-rider** [comment] 2019-10-05 16:48
Duplicate of #6909 (it was created later than this ticket but I missed this one).
Fix will be dded in 6.2.2

**Closed by serge-rider** 2019-10-05 16:48 UTC
Labels: bug
