### ISSUE TITLE
MySQL: Query parser claims the table is missing if the name is escaped with backticks

### ISSUE THREAD

**Issue by pauljura** [dbeaver/dbeaver#35866] opened 2024-10-08 06:30 UTC
### Description

In MySQL if a table is named with a reserved word ("user" is a common example) then you have to escape the table name with the backtick character. The auto-fill even helps you to do this. However, it then immediately reports that the table does not exist.

![dbeaver](https://github.com/user-attachments/assets/8942b632-4e71-42e8-9bda-3b07d692e63e)

### DBeaver Version

Community Edition Version 24.2.2.202410061621

### Operating System

Windows 10

### Database and driver

Driver for MySQL 8 and later

### Steps to reproduce

1. Make a MySQL table named `User`
2. Try to write a select query for it

**Comment by E1izabeth** [comment] 2024-10-10 16:10
Thanks for the bug report. 
I'm closing it as a duplicate of #35812
The issue is solved and the fix will be available in the DBeaver 24.2.3

**Closed as not planned by E1izabeth** 2024-10-10 16:10 UTC
Labels: duplicate, xf:sql editor
