### ISSUE TITLE
At csv import Target DDL adds new column which already exists

### ISSUE THREAD

**Issue by BobJMW** [dbeaver/dbeaver#11062] opened 2021-01-20 12:01 UTC
Hello,

Just started using DBeaver and now I want to import a CSV file to a postgres database. The columns of the CSV and target table match with each other with the only exception that the target table has an id column, somewhere at position 15. This seems no issue when mapping columns using the option Mapping Existing. In Pgadmin we could deselect this column and there was no problem.

However, if I want to import the same file to the same table with DBeaver an additional column is added, frankly enough this added column is already the first column in both the CSV file and in the target table.
DBeaver signals this column as new and I cannot change it to existing in order to prevent the Target DDL action. 

What should I do differently? Or is this a bug?

Specifications
- Windows 10
- Dbeaver 7.3.3
- postgres 10 (on Azure)
- file location is on google drive

**Comment by kseniiaguzeeva** [comment] 2021-01-25 07:27
Unfortunatelly I cannot reproduce it. My steps:
1. I export table to CSV file (Here is DDL of the exported table)
```
CREATE TABLE import_csv (
	column1 varchar NULL,
	column2 varchar NULL,
	column3 varchar NULL,
	column4 varchar NULL,
	column5 varchar NULL,
	column6 varchar NULL,
	column7 varchar NULL,
	column8 varchar NULL,
	column9 varchar NULL,
	column10 varchar NULL,
	column11 varchar NULL,
	column12 varchar NULL,
	column13 varchar NULL,
	column14 varchar NULL,
	id int4 NULL,
	column15 varchar NULL,
	column16 varchar NULL,
	column17 varchar NULL
);
```
2. I delete column **id** from CSV file and import the file to the table

The result: all columns are mapped correctly, the data is inserted, the imported rows of **id** column remain empty.

 Please send me a table DDL example and CSV example.

**Comment by BobJMW** [comment] 2021-01-28 11:25
___________________________


*Bob Wuisman*
BI Lead
*+31 6 11835880*



*Digital Decisions B.V.*
*www.digitaldecisions.com <http://www.digitaldecisions.com/>*
*HQ:* 9th Floor, Pythagoraslaan 101, 3584 BB, Utrecht, The Netherlands
*London:* Chapter House, 16 Brunswick Place, London, N1 6DZ, United Kingdom
*New York:* 110 William St #2401, New York NY, 10038, United States of
America


Digital Decisions B.V. is a limited company registered in the Netherlands
(registered number 68518072), with its registered office located at 9th
Floor, Pythagoraslaan 101, 3584 BB, Utrecht, the Netherlands. This e-mail,
and any attachments thereto, are intended only for use by the addressee(s)
named herein and may contain legally privileged and/or confidential
information. If you are not the intended recipient of this e-mail, you are
hereby notified that any dissemination, distribution or copying of this
e-mail, and any attachments thereto, is strictly prohibited. If you have
received this e-mail in error, please notify me by replying to this message
and permanently delete the original and any copy of this e-mail and any
printout thereof.

**Comment by BobJMW** [comment] 2021-01-28 11:32
[DBeaver issue.zip](https://github.com/dbeaver/dbeaver/files/5886727/DBeaver.issue.zip)

Thank you for your reply and looking into the issue. Please find the .zipfile attached where you can find the ddl table script, test csv file and a picture of the DDL script that shouldn't be generated. 

Step 1. Create table
Step 2. Import attached CSV file (no column needs to be removed)
Step 2A. At the second screen "Tables Mapping" the DDL script is directly generated
`ALTER TABLE public.test_dbeaver ADD "﻿export_id" varchar(1024) NULL;`

My colleague had the exact same issue. Hopefully you can help us out :) 

Many thanks in advance

**Comment by kseniiaguzeeva** [comment] 2021-02-26 16:00
Thank you for the additional details. Reproduced.

**Comment by flambchap** [comment] 2021-07-09 10:28
Hi @BobJMW. In the target table DDL you provided, the `id` column is marked as `NOT NULL`. Since there is no corresponding column in the CSV file, data transfer fails, which is to be expected. If we delete the `NOT NULL` clause from the DDL, DT runs successfully. I believe there is no bug here.

**Closed as completed by flambchap** 2021-07-09 10:28 UTC
Labels: can't reproduce, xf:datatransfer, sp:2
