### ISSUE TITLE
Git plugin installation (aka Team work) gets uninstalled on every update

### ISSUE THREAD

**Issue by lackovic** [dbeaver/dbeaver#16267] opened 2022-04-21 11:15 UTC
#### System information: 
- Operating system and version: Windows 10 21H1
- DBeaver version: `22.0.3`
- Additional extensions: **Git Support plugin**

#### Connection specification:
- Database name and version: irrelevant
- Driver name: irrelevant

#### Describe the problem you're observing:

Every time I upgrade DBeaver to its latest version the Git Support plugin gets removed and I must install it again.

It happened when I upgraded from `21.3.5` to `22.0.0`, and then again when I upgraded to `22.0.1`, `22.0.2` and `22.0.3`.

**Comment by uslss** [comment] 2022-04-25 09:16
thanks for the report
closed as a duplicate of #5317

**Closed as completed by uslss** 2022-04-25 09:16 UTC
Labels: duplicate
