### ISSUE TITLE
Keep installed plugins

### ISSUE THREAD

**Issue by Ferrox12** [dbeaver/dbeaver#17826] opened 2022-10-06 07:51 UTC
Hi,
when I update DBeaver I must download again the plugins that were already installed (office support for example).
Is there a mehod to keep them installed?

**Comment by E1izabeth** [comment] 2022-10-06 07:53
Thank you for feature request. It's a duplicate of #5317. You can find temporary workaround there.

**Closed as not planned** 2022-10-06 07:54 UTC
Labels: duplicate
