### ISSUE TITLE
Autocomplete doesn't show field for aliased table

### ISSUE THREAD

**Issue by Bill2web** [dbeaver/dbeaver#21262] opened 2023-09-21 09:08 UTC
### Description

Hi, 
I don't know if it's a bug or a feature request 🙄

When I try to use an aliased subselect , DBeaver don't show fields list.

Exemple working on a simple table : 
![image](https://github.com/dbeaver/dbeaver/assets/75842365/cae81025-c109-4b5a-a61e-fdf3d6590cf1)

Exemple with sub select not working 
![image](https://github.com/dbeaver/dbeaver/assets/75842365/39284c47-43ae-4962-9d58-ea1dd61755a4)

Autocomplete doesn't seem to do anything ...

### DBeaver Version

Community 23.2.0.202309041200

### Operating System

Win 10

### Database and driver

Oracle 12c

**Comment by E1izabeth** [comment] 2023-09-22 10:25
Thank you for bug report. It's a known issue.
Closing as a duplicate of #7768

**Closed as not planned by E1izabeth** 2023-09-22 10:25 UTC
Labels: duplicate, xf:sql parser
