### ISSUE TITLE
PG:Grant user to role

### ISSUE THREAD

**Issue by mxwmwx** [dbeaver/dbeaver#8062] opened 2020-03-03 07:23 UTC
In pg，statements like this: grant user to role.This statement can add a user to a role(sometimes the collection of users)。We can grant some privileges(CREATE/SELECT.....) to the role and then the members of the role also have the same permissions .
However, in DBeaver I can't find the way to grant user to role.
Why not add a event  named "add members" around here to form a user group(actually the group is already exits,we just need to add it members use grant ... to ...).
![image](https://user-images.githubusercontent.com/37258498/75752062-e5b14680-5d62-11ea-84ef-f65ea1b6a419.png)

**Comment by uslss** [comment] 2020-03-03 12:26
thanks for suggestion

**Comment by uslss** [comment] 2020-12-11 00:47
closed as duplicate of #8133

**Closed by uslss** 2020-12-11 00:47 UTC
Labels: feature request

**Comment by jgrocha** [comment] 2025-03-17 12:16
This is not a duplicate of #8133. #8133 is a feature request to enable or disable the **create new role** action.

This is a request to support **grant user to role**. As far as I know, there is no way to do this in the UI.
