### ISSUE TITLE
Dbeaver Community Edition 22.3.5 frequent freezes only on Databricks SQL warehouse

### ISSUE THREAD

**Issue by RichardSCarchitect** [dbeaver/dbeaver#19586] opened 2023-04-03 06:46 UTC
### Description

I use Dbeaver on a number of different databases, it's always been very stable except on Databricks SQL warehouse which is admittedly an early pilot implementation where we are still learning the correct configuration.  Most crashes are in READ or WRITE operations.
Can someone tell me what logs etc. can I share to see what is the issue and if there is a solution - thanks!

### DBeaver Version

Community Edition 22.3.5

### Operating System

Windows 10 professional

### Database and driver

Databricks SQL Warehouse
Databricks native jbdc driver 2.6.32

### Steps to reproduce

Connect to SQL warehouse
INSERT INTO large table (>100m rows), or else
CREATE OR REPLACE VIEW xxx AS SELECT COL FROM yyy ETC

Random freezes of DBeaver.

**Comment by Destrolaric** [comment] 2023-04-03 09:29
HI, you can find instructions here : https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment] 2023-04-06 13:08
Would you send us the log files?

**Comment by RichardSCarchitect** [comment] 2023-04-10 08:43
Hello I checked the log files, not sure if company policy allows me to share them because they contain connection info, but anyways I could not see anything out of ordinary in the logs, I think what happened several times is that our new and unstable Databricks SQL warehouse can freeze or have other issues on server side, and on DBeaver the 'Cancel operation' button may become ineffective, it still makes you wait a very long time until it stops and you can use DBeaver again (I waited up to 15 minutes).  I suppose this may be due to some dependency with the server.

So could I suggest you add a more extreme option 'force cancel operation' etc. that will remove DBeaver from the transaction no matter the dependencies on the server side; in my case I may have 4 connections live with 3 different databases and up to now my only option has been to CTR-ALT-DEL force stop the whole Dbeaver application from Windows task manager.

**Comment by E1izabeth** [comment] 2023-04-10 08:57
Thank you for update. We will discuss it.

**Comment by ShadelessFox** [comment] 2023-04-27 13:22
Hello @RichardSCarchitect,
1. Does executing a `SELECT` statement from the view cause DBeaver to freeze?
2. If so, does adding a `LIMIT 100` clause fix the issue?

**Comment by RichardSCarchitect** [comment] 2023-04-28 02:44
Hello Shadeless Fox,
Does executing a SELECT statement from the view cause DBeaver to freeze? > yes, keep in mind that the root cause is most likely our faulty implementation of the Databricks cluster, so the proposed solution is just to add a 'force cancel operation' to DBeaver.  The main issue is that the currently available 'cancel operation' menu is grayed out during the Databricks freeze.
If so, does adding a LIMIT 100 clause fix the issue? No, it's not a query result size issue, it's something more fundamental on database side.

**Comment by ShadelessFox** [comment] 2023-04-28 10:04
Thanks for the response

**Comment by ShadelessFox** [comment] 2023-05-18 12:44
I'm sorry for the late response.

Could you please generate a thread dump while DBeaver is not responding and attach it here?

Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/.

**Comment by RichardSCarchitect** [comment] 2023-05-19 03:32
Have not had any freezes recently as we are fixing the issues in our Databricks instance.  Anyways my recommendation is to add a more extreme option 'force cancel operation' etc. that will remove DBeaver from the transaction no matter the dependencies on the server side.

**Comment by arhayka** [comment] 2023-05-25 12:57
I'm closing it because the issue is resolved.

**Closed as not planned by arhayka** 2023-05-25 12:57 UTC
Labels: third party issue, performance, x:databricks
