### ISSUE TITLE
Keep refreshing start screen after installing Eclipse Marketplace Client 

### ISSUE THREAD

**Issue by GaryLiuTelus** [dbeaver/dbeaver#12830] opened 2021-06-11 16:29 UTC
#### System information: 
- Operating system (distribution) and version Windows 10 20H2 update
- DBeaver version 21.04
- Java version version 8 update 121
- Additional extensions no

#### Connection specification:
It is not related to Database, so not providing below information. 
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

After installed Eclipse Marketplace, next time  restart the DBeaver, it keeps flashing start screen for ever.

#### Steps to reproduce, if exist:

go to `Help` -> `Install New Software...` -> In `Work With`, select Eclipse, and then search `market` -> select `Eclipse Marketplace Client` and install -> restart DBeaver, and then you can never enter or stop DBeaver. I have to restart my computer or manually uninstall DBeaver to stop it. 

I tried on 2 laptops, one of which is brand new installation, both are the same.

**Comment by Matvey16** [comment] 2021-06-11 16:38
Hello and thank you for the report. It is kind of a known issue with a lot of plugins and appears to be fixed in the newest version. Can you try installing early acces version and verifying if it still persists?
https://dbeaver.io/files/ea/

**Comment by Matvey16** [comment] 2021-06-11 16:41
Probably duplicates this #10852

**Comment by GaryLiuTelus** [comment] 2021-06-11 17:51
I tried the latest version, but got the below error when install marketplace client:
```
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: C:\Users\my_id\.eclipse\org.jkiss.dbeaver.product_21.1.0_1535670467_win32_win32_x86_64\features\org.eclipse.epp.mpc_1.9.1.v20210204-1408
```

**Comment by Matvey16** [comment] 2021-06-11 19:27
If you don't have many plugins installed I would recommend completely deleting `C:\Users\my_id\.eclipse\org.jkiss.dbeaver.product_21.1.0_1535670467_win32_win32_x86_64` folder or even the whole `.eclipse` folder and reinstalling the marketplace.
It is an Eclipse error and shows that the files downloaded were probably corrupted. Also make sure you are installing from Eclipse Repository - `https://download.eclipse.org/releases/2021-03/` and not some mirror.

**Comment by GaryLiuGTA** [comment] 2021-06-11 19:37
@Matvey16 Thanks for your quick response. 

I did as you suggested, and deleted the whole `.eclipse` folder, and reinstall the marketplace from official repository as you mentioned above, and then the looping flash screen comes back again. This is based on the early access version from `https://dbeaver.io/files/ea/`.

**Comment by optik-aper** [comment] 2021-06-14 15:18
I'm experiencing the same issue when installing the DevStyle plugin from [http://www.genuitec.com/updates/devstyle/ci/](http://www.genuitec.com/updates/devstyle/ci/).  The splash screen comes up and closes, over and over.  After removing the org.jkiss.dbeaver.product_21.1.0_1535670467_win32_win32_x86_64 file from .eclipse, the loop stops.

**Comment by Matvey16** [comment] 2021-06-15 06:42
I reproduced it on earlier versions, but can't reproduce on the latest version.

**Comment by Matvey16** [comment] 2021-06-15 09:23
Closing because of duplication. Will be looked at in scope of #10852

**Closed as completed** 2021-06-15 09:23 UTC
Labels: duplicate, xo:eclipse
