### ISSUE TITLE
View and edit JSON fields in version 6.3 not work

### ISSUE THREAD

**Issue by ZOOBR** [dbeaver/dbeaver#7354] opened 2019-12-04 07:29 UTC
Field editing functionality has stopped working in the new version 6.3. Both viewing and editing are not available.
![image](https://user-images.githubusercontent.com/16265636/70121855-7e5efa00-1680-11ea-9f6b-fecf1f1ae5ee.png)

**Comment by serge-rider** [comment] 2019-12-04 08:17
Duplicate of #7331

**Closed by serge-rider** 2019-12-04 08:17 UTC
Labels: bug, duplicate
