### ISSUE TITLE
view source SQL code to create a role

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#8501] opened 2020-04-21 07:11 UTC
it would be very convenient to be able to view the sql code for creating a role, as in pgAdmin4.

Or such as DDL tab in table settings.

**Comment by uslss** [comment] 2020-04-21 14:41
thanks for suggestion

**Comment by LonwoLonwo** [comment] 2021-02-07 22:36
duplicate of https://github.com/dbeaver/dbeaver/issues/9372

**Closed by LonwoLonwo** 2021-02-07 22:36 UTC
Labels: feature request, x:postgresql
