### ISSUE TITLE
Refresh Bug after sorting/filtering columns ORA-00933 Command not properly ended

### ISSUE THREAD

**Issue by fthiel** [dbeaver/dbeaver#4310] opened 2018-10-01 07:58 UTC
Hi,
I'm getting an error when trying to refresh table data after sorting or filtering a coulmn before that I can use refresh without problems. In some tables (often ones with many entries) I get the same error when I sort by a column and in this case the sorting is also not executed.

Error message: ORA-00933 Command not properly ended

DBeaver 5.2.1.201809240911
Windows 10
Oracle 12c (12.2.0.1.0)
java 1.8.0_77
ojdbc7.jar

**Comment by serge-rider** [comment] 2018-10-03 08:18
Duplicate of #4284

**Closed by serge-rider** 2018-10-03 08:18 UTC
Labels: bug, duplicate
