### ISSUE TITLE
Question about Oracle support for new Oracle versions

### ISSUE THREAD

**Issue by bmg61** [dbeaver/dbeaver#5541] opened 2019-03-20 16:22 UTC
#### System information: 
- Operating system (distribution) and version
- DBeaver version 6.0.
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
Oracle 19c
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
This is not a problem, but a question.  I'd like to know if DBeaver 6.0 (or a later version) will support Oracle 19c.  (It doesn't look like it supports Oracle 18c.).  I am planning to go to Oracle 19c this summer. 
I'd like to drop the commercial DB tool that we pay for for DBeaver, but I can't do that until I know that DBeaver will work with Oracle 19c.

**Comment by xyu-r0nin-** [comment] 2019-07-02 21:12
It would be great if DBeaver allows you to create connections to Oracle 18c and 19c databases using wallets or jks files:

[https://www.oracle.com/technetwork/database/application-development/jdbc/documentation/atp-5073445.html](url)

**Comment by maurochss** [comment] 2019-07-06 12:19
It would be really nice to have wallet support.

-M

**Comment by xyu-r0nin-** [comment] 2019-10-03 22:22
Is there any possibility that this request will be reviewed by the development team? I am being forced to use Sql Developer only to be able to connect to an 18c data base in Oracle Cloud. I wish I could do it from Dbeaver

**Comment by serge-rider** [comment] 2019-10-05 16:31
We'll try to test and resolve Oracle 18/19 issues in 6.2.4.
Thanks for raising this issue.

**Comment by xyu-r0nin-** [comment] 2019-10-07 12:43
> We'll try to test and resolve Oracle 18/19 issues in 6.2.4.
> Thanks for raising this issue.

Thanks to you Serge.

I had already made a feature request on the same topic with some images:
[Connect to Oracle 18c/19c Autonomous databases through wallets](https://github.com/dbeaver/dbeaver/issues/6912#issue-502335100)

**Comment by serge-rider** [comment] 2019-11-18 10:03
Duplicate of #6912

**Closed by serge-rider** 2019-11-18 10:03 UTC
Labels: duplicate, feature request, x:oracle
