### ISSUE TITLE
Show sequential scans on tables on Statistics page

### ISSUE THREAD

**Issue by qris** [dbeaver/dbeaver#7194] opened 2019-11-08 10:13 UTC
**Is your feature request related to a problem? Please describe.**
It's hard to calculate index hit ratio (and hence utility) when we know the number of index scans, but not the number of seq scans on the table, which is available from the [pg_stat_all_tables view](https://www.postgresql.org/docs/12/monitoring-stats.html#PG-STAT-ALL-TABLES-VIEW).

**Describe the solution you'd like**
Show the number of seq_scans in the table statistics.

**Describe alternatives you've considered**
Fetch the number manually with a query.

**Additional context**
![image](https://user-images.githubusercontent.com/754175/68468637-552d8400-0210-11ea-8c79-6b7ec5bb78a3.png)

**Comment by michalk-k** [comment] 2019-11-09 11:41
It's related to my issue, when I'm asking for even more statistics: https://github.com/dbeaver/dbeaver/issues/7159

**Comment by uslss** [comment] 2021-08-03 16:54
closed as duplicate of #7159

**Closed by uslss** 2021-08-03 16:54 UTC
Labels: duplicate, feature request, x:postgresql, xf:metadata
