### ISSUE TITLE
ctrl + shift + d open database object  null point exception

### ISSUE THREAD

**Issue by punkmonday** [dbeaver/dbeaver#10547] opened 2020-11-30 01:32 UTC
#### System information: 
- Operating system (distribution) and version
  windows 10 
- DBeaver version
  7.3
- Additional extensions

#### Connection specification:
- Database name and version
  mysql8
- Driver name
  mysql-connector-java 5.1.44
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  no
#### Describe the problem you're observing:
ctrl  + shift + d search table null pointer error
#### Steps to reproduce, if exist:
1. filter -> config databases filter -> filter database
2. ctrl + shift + d (do not choose database)
3. type something
4. crashed
#### Include any warning/errors/backtraces from the logs

An internal error occurred during: "Items filtering".
java.lang.NullPointerException

**Comment by uslss** [comment] 2020-11-30 05:28
Hi @punkmonday ,
unfortunately, cannot reproduce it (gif attached). Is there something in the log? or probably some special steps are needed?
![2020-11-30_08h27_15](https://user-images.githubusercontent.com/31996417/100572220-06083480-32e6-11eb-9f0e-e58fde3f799c.gif)

**Comment by punkmonday** [comment] 2020-11-30 06:09
> Hi @punkmonday ,
> unfortunately, cannot reproduce it (gif attached). Is there something in the log? or probably some special steps are needed?
> ![2020-11-30_08h27_15](https://user-images.githubusercontent.com/31996417/100572220-06083480-32e6-11eb-9f0e-e58fde3f799c.gif)

community version 7.3.0.202011291229 , i just choose a datasource and press ctrl + shift + d to search a word, it crashed everytime

**Comment by uslss** [comment] 2020-12-21 10:53
still cannot reproduce.
@punkmonday can you check if it is still reproducible against 7.3.1?

**Comment by punkmonday** [comment] 2020-12-24 03:57
> still cannot reproduce.
> @punkmonday can you check if it is still reproducible against 7.3.1?

An internal error occurred during: "Cache refresh".
java.lang.NullPointerException

**Comment by uslss** [comment] 2021-01-19 22:20
@punkmonday could you try to reset workspace using File - Reset workspace state or according to this [guide](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)?

**Comment by punkmonday** [comment] 2021-01-22 04:01
> @punkmonday could you try to reset workspace using File - Reset workspace state or according to this [guide](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)?

ok! thank you very much

**Comment by serge-rider** [comment] 2021-01-22 06:33
@punkmonday if this will happen again please attach logs with this error (instructions - https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by mbaric** [comment] 2022-11-18 14:18
Hey guys.
[open-database-object-error.log](https://github.com/dbeaver/dbeaver/files/10042028/open-database-object-error.log)

I managed to reproduce it. Here is Error log exported.

**Comment by E1izabeth** [comment] 2022-11-18 14:29
@mbaric thank you!

**Comment by mbaric** [comment] 2022-11-18 14:36
@E1izabeth no worries.let me know if you'll need more info. Cheers and thank you for super awesome Dbeaver app.

**Comment by LonwoLonwo** [comment] 2023-05-25 08:49
Fixed here: https://github.com/dbeaver/dbeaver/issues/19106
Closing the issue.

**Closed by LonwoLonwo** 2023-05-25 08:49 UTC
Labels: bug, xp:normal
