### ISSUE TITLE
Autocompletion doesn't work in some JOIN cases.

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#12335] opened 2021-05-03 15:32 UTC
#### System information: 
- Windows 10 Pro x64
- DBeaver 21.0.4
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5
- Default PostgreSQL driver
- No tunnels or proxies

#### Describe the problem you're observing:
Column autocompletion doesn't work when table in from clause doesn't have alias
#### Steps to reproduce, if exist:
https://user-images.githubusercontent.com/22142845/116897332-cdc2a480-ac3d-11eb-8f1b-5f8d6e5ebee0.mp4

**Comment by LonwoLonwo** [comment] 2021-05-03 19:52
Hello @ems2811 
Thanks for the bug report!
This is duplicate of https://github.com/dbeaver/dbeaver/issues/12185 and https://github.com/dbeaver/dbeaver/issues/12168

**Comment by ems2811** [comment] 2021-07-01 09:07
@LonwoLonwo, problem reproduces in DBeaver 21.1.1.202106210824. Need to create new issue or exists same open issue?

**Comment by LonwoLonwo** [comment] 2021-07-05 20:29
Hello @ems2811 
Can you please check the 21.1.2 version? https://dbeaver.io/

**Comment by ems2811** [comment] 2021-07-08 08:54
Hello @LonwoLonwo .
Problem reproduces in 21.1.2. Example below doesn't work
```
SELECT *
FROM some_table
	JOIN other_table ot ON ot.
```
But if i add alias to table in from or write inner join - autompletion works
```
SELECT *
FROM some_table st
	JOIN other_table ot ON ot.

SELECT *
FROM some_table
	INNER JOIN other_table ot ON ot.
```

**Comment by LonwoLonwo** [comment] 2021-07-12 08:12
Thanks for clarifying @ems2811 
I will reopen this ticket.

**Comment by Matvey16** [comment] 2021-12-03 06:38
Verified

**Closed as completed by Matvey16** 2021-12-03 06:38 UTC
Labels: xf:sql, sp:3
