### ISSUE TITLE
Query returns cached result instead of latest

### ISSUE THREAD

**Issue by dj-louw** [dbeaver/dbeaver#20193] opened 2023-06-03 19:33 UTC
### Description

I'm not sure if I am misunderstanding something about how dBeaver works, but it appears as if querys sometimes return a cached version of the data, in stead of the latest.

I'm a product manager, and must frequently run queries for either customer support or reporting reasons.

A developer and I would often work together, them making some change/update to the data, and I running a query to verify that I'm seeing the update on my end. Problem is, I often don't get the change on my side until I "invalidate/reconnect" the connection to the database itself. 

I've been caught out multiple times by this, any insights or assistance would be greatly appreciated.

### DBeaver Version

Community 23.0.3.202304240616

### Operating System

Windows 11

### Database and driver

Database: MySQL hosted on AWS RDS Aurora (not sure of version?)
Connection: Via SSH on bastion host that lives within the VPC
DBeaver Driver: MySQL

### Steps to reproduce

1. Prepare select statement with some joins that returns some data
2. On a remote connection, update some of this data
3. Re-run the select, and see how the data does not update
4. "Invalidate/Reconnect" the connection, re-run the query, and get the updated data back.

### Additional context

Connection via SSH.

**Comment by LonwoLonwo** [comment] 2023-06-05 08:20
Hello @dj-louw 

Could you please provide a video of your issue? I will be very appreciative.

**Comment by dj-louw** [comment] 2023-06-05 10:50
Sure, I'll see what I can do. Dealing with sensitive information, but I might be able to get something done.

**Comment by nettm** [comment] 2023-06-13 10:03
I have encountered the same problem as well.

**Comment by E1izabeth** [comment] 2023-07-04 13:51
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by miltontaylor-panotek** [comment] 2023-07-21 07:15
Can I re-open this issue as we're seeing this behavior as well, also with AWS Aurora, so maybe it's something specific to jdbc properties or settings?

**Comment by E1izabeth** [comment] 2023-07-21 07:53
Please provide more details. At least video showing the issue or detailed steps to reproduce are required

**Comment by miltontaylor-panotek** [comment] 2023-07-21 08:53
Very straightforward:

DBeaver 23.0.3 with jdbc driver aws-mysql-jdbc-1.1.6.jar

1. New DB connection with driver defaults for connection properties
2. Open a table
3. View the grid or text result set
4. Hit the refresh button
5. Grid continues to show stale result values

Note that dBeaver does give the appearance of having re-executed the query at the bottom right of the UI showing execution time etc.

The only way to get an updated result set is to disconnect and reconnect.

**Comment by E1izabeth** [comment] 2023-07-21 09:01
Do you see the any new query executed on Refresh button pressed in the [Query Manager](https://dbeaver.com/docs/wiki/Query-Manager/) with Meta queries option cheched?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/3592f427-cc41-440b-9e13-46630e76221b)

**Comment by miltontaylor-panotek** [comment] 2023-07-21 09:12
I will  check shortly - also updating the jdbc driver from 1.1.6 to 1.1.8 just rule out a driver issue of some type.

**Comment by miltontaylor-panotek** [comment] 2023-07-21 09:30
OK We think we partially figured this out, maybe this is a usability bug, but if you set tx autocommit on (which is not the default) then the refresh works.  I can sort of understand why you might do this if you had made some uncommitted edits, but for it to behave this way just generally seems a weird decision - is it intentional?

**Comment by LonwoLonwo** [comment] 2023-07-21 10:00
Hello @miltontaylor 

Maybe your case is described here: https://github.com/dbeaver/dbeaver/issues/20507 ?

**Comment by miltontaylor-panotek** [comment] 2023-07-21 10:11
Hmm, I don't see how that fits the picture. Firstly we're not doing any sort of db updates, just repeated selects with all dbeaver defaults.  Refresh should just work in this case. Do you not agree?

**Comment by E1izabeth** [comment] 2023-07-27 08:17
I believe it's not something that DBeaver do, but that's how things work. When you editing something together with your colleague, you're working in different connections to your database. Transaction - is something that can be rolled back, so while the transaction is not committed, changes are not visible outside the connection.

Why the transaction mode is not set to auto commit mode? Is it your local setting or you didn't touch it and that was the default for your connection?

**Comment by Matvey16** [comment] 2023-07-27 12:47
@dj-louw It seems like something happens with transactions between you and your collegue
Can you check how those settings are set for both you and your collegue

![image](https://github.com/dbeaver/dbeaver/assets/82543000/a937518e-697f-47f1-88cf-40153ae1b369)

**Comment by miltontaylor-panotek** [comment] 2023-07-27 12:50
1. Not editing the database, and this is not a multi-connection situation... single user just doing read-only refreshing of a query.
2. DBeaver defaulted it to auto commit mode being off.

As before, if autocommit is ON this behavior does not exhibit. My question is, when we're not talking about updating the database here, so there is nothing to commit, why when autocommit is OFF it cannot re-fetch an updated result set?

**Comment by ShadelessFox** [comment] 2023-08-03 12:38
I don't think this is DBeaver issue. Just set transaction mode to auto-commit.

**Closed as not planned by ShadelessFox** 2023-08-03 12:38 UTC
Labels: xf:data, question

**Comment by segonwork** [comment] 2024-01-19 16:01
I am also having same kind of issue with dbeaver where I am a single user of the database and the mysql database is installed on my dev machine. Its keep on getting the same data that was shown on the first execution of the select query.

**Comment by thehashrocket** [comment] 2024-03-13 21:35
I have the same issue as well. I'm connected to a remote db. I update the data via a website and get a confirmation back from the api. I refresh the data in dbeaver and it shows the old data. Nothing has changed. If I reset the connection and then refresh, it pulls the fresh data.

**Comment by segonwork** [comment] 2024-03-14 01:19
> I have the same issue as well. I'm connected to a remote db. I update the data via a website and get a confirmation back from the API. I refreshed the data in dbeaver and it shows the old data. Nothing has changed. If I reset the connection and refresh, it pulls the fresh data.

I've found a workaround though. I have my connection with database with auto-commit: false. Now I click on "rollback" in case I am executing select queries. This has no impact on the underlying database table as first I am doing select statement and second I am clicking on "rollback" button. This way I don't need to again refresh/reset the connection.
Hope this issue gets sorted out soon.

**Comment by ShadelessFox** [comment] 2024-03-14 02:30
That's how transactions work in databases. Enable auto-commit.

**Comment by theSuda** [comment] 2024-03-27 15:50
> I have the same issue as well. I'm connected to a remote db. I update the data via a website and get a confirmation back from the api. I refresh the data in dbeaver and it shows the old data. Nothing has changed. If I reset the connection and then refresh, it pulls the fresh data.

I had faced this issue in early 2022 frequently and it just became a habit for me to re-connect my query windows before running any 'check if things worked' queries. Hopefully this gets resolved some day.

**Comment by nicolasgarnil** [comment] 2024-04-13 10:36
It happened to me yesterday. I saw different query results than a teammate until I re-opened the app.

Version 24.0.0.202403031740
