### ISSUE TITLE
Unable to install dbeaver   in Eclipse 4.26

### ISSUE THREAD

**Issue by gnl42** [dbeaver/dbeaver#18538] opened 2022-12-19 19:55 UTC
### Description

Eclipse complains when I try to instal DBeaver in a vanilla Eclipse 4.26:

`Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver IDE 22.3.0.202212070729 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.0.202212070729)
  Software currently installed: Eclipse IDE for Enterprise Java and Web Developers 4.26.0.20221201-1200 (epp.package.jee 4.26.0.20221201-1200)
  Only one of the following can be installed at once: 
    Quick Search 1.1.300.v20211203-1705 (org.eclipse.text.quicksearch 1.1.300.v20211203-1705)
    Quick Search 1.1.400.v20221023-0941 (org.eclipse.text.quicksearch 1.1.400.v20221023-0941)
  Cannot satisfy dependency:
    From: Eclipse IDE for Enterprise Java and Web Developers 4.26.0.20221201-1200 (epp.package.jee 4.26.0.20221201-1200)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.26.0.v20221123-2302,4.26.0.v20221123-2302]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.26.0.v20221123-2302 (org.eclipse.platform.feature.group 4.26.0.v20221123-2302)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.400.v20221023-0941,1.1.400.v20221023-0941]
  Cannot satisfy dependency:
    From: DBeaver Local Standalone Application 22.3.0.202212070729 (org.jkiss.dbeaver.app.local.feature.feature.group 22.3.0.202212070729)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.300.v20211203-1705,1.1.300.v20211203-1705]
  Cannot satisfy dependency:
    From: DBeaver IDE 22.3.0.202212070729 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.0.202212070729)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.app.local.feature.feature.group [22.3.0.202212070729,22.3.0.202212070729]`

### DBeaver Version

22.3.0.202212070729

### Operating System

Windows 11

### Steps to reproduce

Download Eclipse 4.26
Try  and install DBeaver IDE

**Comment by LonwoLonwo** [comment] 2022-12-20 10:25
Looks like duplicate of https://github.com/dbeaver/dbeaver/issues/18475

**Comment by flambchap** [comment] 2022-12-20 13:03
>  Looks like duplicate of https://github.com/dbeaver/dbeaver/issues/18475 

Well, it is a duplicate. @gnl42 Thank you for the report.

**Closed as not planned by flambchap** 2022-12-20 13:03 UTC
Labels: duplicate
