### ISSUE TITLE
The "Delete current row" button disappears when clicked for 1st time

### ISSUE THREAD

**Issue by negora** [dbeaver/dbeaver#7499] opened 2019-12-30 18:09 UTC
The `Delete current row` button of the Data Editor disappears when it's clicked for 1st time. You still can delete rows by pressing the `Del` key on your keyboard, but  you can't continue doing it with the GUI.

Clicking on the `Save` or `Cancel` buttons doesn't work. Nor refreshing the Data Editor. You've to close and re-open the editor.

This is happening since version 6.2.5. Version 6.2.4 and previous ones don't suffer this problem.

Thank you!

**Comment by serge-rider** [comment] 2019-12-31 14:49
Seems to be duplicate of #7260

**Closed by serge-rider** 2019-12-31 14:49 UTC
Labels: bug

**Comment by negora** [comment] 2020-01-01 10:21
OK, I'll track the bug #7260. Thank you and apologizes for the duplication.
