### ISSUE TITLE
DB translate Data Table Closing Tab

### ISSUE THREAD

**Issue by amlx1018** [dbeaver/dbeaver#18547] opened 2022-12-21 01:56 UTC
### Description

Chinese translation error 
Close All table Should be ‘关闭全部’ ，Currently ‘关闭关闭’

### DBeaver Version

22.3.0

### Operating System

win11

**Comment by E1izabeth** [comment] 2022-12-21 07:59
Thank you for bug report. It's a duplicate of #17697

**Closed as not planned** 2022-12-21 08:00 UTC
Labels: duplicate, xf:i18n
