### ISSUE TITLE
Can't find target attribute [mode]

### ISSUE THREAD

**Issue by mikaelmockel** [dbeaver/dbeaver#13402] opened 2021-08-02 09:54 UTC
Hello,
since the upgrade 21.1.4 I'm unable to import data from CSV to DB (postgres).
Error message : Can't find target attribute [mode]
Everything works just find before the upgrade.

I have a column named : mode in the table and in the import file.
If I have a look to the mapping I have the Source Column named : mode
but the Target Column named : "mode"
It's impossible to rewrite the Target Column : mode

Any ideas ?

**Comment by uslss** [comment] 2021-08-02 13:13
@mikaelmockel it will be very helpful if you can provide some sample csv file to reproduce an issue.
Is this problem actual for all the csv files or just for some special?
is there something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by mikaelmockel** [comment] 2021-08-02 14:12
The logs says : Can't find target attribute [mode]
Here are the screen captures : 
![dbeaver_import1](https://user-images.githubusercontent.com/70712217/127875173-69c3d8c9-f55d-4190-9afd-61707aa2bca2.jpg)
![dbeaver_import2](https://user-images.githubusercontent.com/70712217/127875203-c31cdd61-c1dc-46aa-8f16-e79c843b62ef.jpg)

**Comment by mikaelmockel** [comment] 2021-08-02 17:24
I downgraded to 21.1.3 and it works just find.

In your changelog for 21.1.4 version I see some changes that can be the problem : 
- Data transfer:
                - Table/column name case conversion was fixed
                - Ambiguous column name mapping was fixed
- PostgreSQL:
                - Column rename DDL was fixed

**Comment by FHBGLD** [comment] 2021-08-04 05:12
Hello,
we have the same problem.
I exported a table to a csv file. That worked fine. When I imported it to the same empty table then I get ‚Can’t find target attribute [version]’. One column of this table is called ‘vesion’.
![db1](https://user-images.githubusercontent.com/33415881/128125480-dee74755-9e68-41a1-9a71-3dc6ed553f27.jpg)
![db2](https://user-images.githubusercontent.com/33415881/128125488-4cd9df37-c481-443d-a0c2-dce23f1fa293.jpg)



Thank you
Michael

**Comment by ilne** [comment] 2021-08-04 05:24
Reporting in to mention this is not limited to PostgreSQL, it doesn't work with MySQL either. It does work with SQLite. This is not an issue in version 21.1.3.

Table structure MySQL (MySQL 8.0.26-0ubuntu0.20.04.2):

![image](https://user-images.githubusercontent.com/30283610/128126288-57cf3ed8-104d-44a2-843b-22324a0d2b46.png)

Table structure PostgreSQL (PostgreSQL 13.3 (Ubuntu 13.3-1.pgdg20.04+1)):

![image](https://user-images.githubusercontent.com/30283610/128126566-43082ab7-5ead-4849-bc07-a57b94455447.png)

Sample data:

```csv
date,recipient,category,sum,description,transaction_id
2021-08-01,test,test,1,test,6863F2D476F3EB11A2D3001DD8B71C03
```

**Comment by djsnake81** [comment] 2021-08-05 09:47
Same for sql server

**Comment by Mrchensama** [comment] 2021-08-05 10:02
Yes,we have the same problem with  message "Cannot find target attribute [Index]" when try to import data table to either current database or annother database.
According to mikaelmockel's reply ,i downgrade it to 21.1.3 and it works well . Thank you for your solution ,@mikaelmockel。
> I downgraded to 21.1.3 and it works just find.
> 
> In your changelog for 21.1.4 version I see some changes that can be the problem :
> 
> * Data transfer:
>   - Table/column name case conversion was fixed
>   - Ambiguous column name mapping was fixed
> * PostgreSQL:
>   - Column rename DDL was fixed

**Comment by djsnake81** [comment] 2021-08-05 10:13
> Yes,we have the same problem with message "Cannot find target attribute [Index]" when try to import data table to either current database or annother database.
> According to mikaelmockel's reply ,i downgrade it to 21.1.3 and it works well . Thank you for your solution ,@mikaelmockel。
> 
> > I downgraded to 21.1.3 and it works just find.
> > In your changelog for 21.1.4 version I see some changes that can be the problem :
> > 
> > * Data transfer:
> >   
> >   * Table/column name case conversion was fixed
> >   * Ambiguous column name mapping was fixed
> > * PostgreSQL:
> >   
> >   * Column rename DDL was fixed

Same for me. Version 21.1.3 working flawless. Thanks @mikaelmockel

**Comment by Mrchensama** [comment] 2021-08-05 10:18
> > Yes,we have the same problem with message "Cannot find target attribute [Index]" when try to import data table to either current database or annother database.
> > According to mikaelmockel's reply ,i downgrade it to 21.1.3 and it works well . Thank you for your solution ,@mikaelmockel。
> > > I downgraded to 21.1.3 and it works just find.
> > > In your changelog for 21.1.4 version I see some changes that can be the problem :
> > > 
> > > * Data transfer:
> > >   
> > >   * Table/column name case conversion was fixed
> > >   * Ambiguous column name mapping was fixed
> > > * PostgreSQL:
> > >   
> > >   * Column rename DDL was fixed
> 
> Same for me. Version 21.1.3 working flawless. Thanks @mikaelmockel

But it sometimes get blocked and keeps waiting for data transform when executing data table import task ,even the table has just a few raws .

**Comment by Matvey16** [comment] 2021-08-12 06:23
Can be related to #13453

**Comment by LonwoLonwo** [comment] 2021-08-17 18:08
Seems to be fixed in https://github.com/dbeaver/dbeaver/issues/13542

**Comment by Matvey16** [comment] 2021-08-18 06:58
Verified

**Closed as completed by Matvey16** 2021-08-18 06:58 UTC
Labels: xp:major, xf:datatransfer

**Comment by mikaelmockel** [comment] 2021-08-19 09:57
Hi,
the issue is still present in the new 21.1.5 version of dbeaver.
Do not close the issue.

**Comment by LonwoLonwo** [comment] 2021-08-19 10:46
Hi @mikaelmockel 
Issue fixed but will be available only in release 21.2.0 on 2021-08-30 [here](https://dbeaver.io/)
or earlier [here](https://dbeaver.io/files/ea/)

**Comment by TsunamiHandia** [comment] 2021-08-25 07:43
Here are some screenshoots and the DDL of the table:

**DDL:**
CREATE TABLE XXX.dbo.Lista_contactos_eliminar_revisados_XXX (
	eliminar varchar(12) COLLATE Modern_Spanish_CI_AS NULL,
	[Nombre empresa] varchar(75) COLLATE Modern_Spanish_CI_AS NULL,
	Nº varchar(30) COLLATE Modern_Spanish_CI_AS NULL,
	Nombre varchar(75) COLLATE Modern_Spanish_CI_AS NULL
);

**Columns** mapped:
![campos](https://user-images.githubusercontent.com/19465702/130748267-019120d1-45df-473a-8d81-70cced69620c.jpg)

**Error:**
![error](https://user-images.githubusercontent.com/19465702/130748323-97cffadf-9d29-4350-8d06-12f715d435cc.png)

**Comment by LonwoLonwo** [comment] 2021-08-25 07:56
Thanks @TsunamiHandia 

The issue was resolved. You can test it in our earlier version [here](https://dbeaver.io/files/ea/)

**Comment by TsunamiHandia** [comment] 2021-08-27 06:12
Ok I proved it, and it works fine.

Thank you very much

**Comment by niziyong** [comment] 2022-07-08 07:24
他仍然存在于21.1.5中
