### ISSUE TITLE
Connecting AWS Redshift fails with error relation pg_catalog.pg_enum does not exist

### ISSUE THREAD

**Issue by SagarJyani** [dbeaver/dbeaver#21327] opened 2023-09-26 14:12 UTC
### Description

On updating the Community Edition to the latest version started giving the error : 
`SQL Error [42P01]: ERROR : relation pg_catalog.pg_enum does not exist`

### DBeaver Version

Community Edition 23.2.1

### Operating System

macOS Ventura 13.5.2

### Database and driver

Database : AWS Redshift - Cluster version 1.0.56754

### Steps to reproduce

1. Try to connect to Redshift cluster

### Additional context

On reverting to CE Version 23.2.0, I stopped facing this error. I am able to connect to Redshift using this version.

**Comment by LonwoLonwo** [comment] 2023-09-26 15:35
Hello @SagarJyani 

Thanks for the report.

This is a duplicate of: https://github.com/dbeaver/dbeaver/issues/21293

Rerelease is available at https://dbeaver.io/files/23.2.1/

**Closed as completed by LonwoLonwo** 2023-09-26 15:35 UTC
Labels: duplicate
