### ISSUE TITLE
ODBC query always returns null value

### ISSUE THREAD

**Issue by Stadlerrr** [dbeaver/dbeaver#14738] opened 2021-11-30 14:09 UTC
#### System information: 
- Operating system: Windows 10 Pro
- DBeaver version: 21.3.0.202111281534
- Java version : 8 update 131

#### Connection specification:
- Mysql ODBC
- Mysql ODBC 5.1 Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc): No, just a forticlient VPN to access the server

#### Describe the problem you're observing:

When running any simple query that should "autofill" the data in a column I always get NULL as value.

Example with the simpliest query possible:

SELECT 'xxxx' as column1;

![image](https://user-images.githubusercontent.com/95294375/144061910-7d9b542b-bec0-4c28-93fc-eaeadd4d111c.png)

This query should return "xxxx" as value in a column named "column1". 
The query works fine on the same system but different database tools. I tried with Navicat for Mysql or Excel query and it works just fine. 
On DBeaver the query gives me the right column but filled with NULL value.

**Comment by uslss** [comment] 2021-12-06 09:36
thanks for the report

closed as a duplicate of #6213

**Closed as completed by uslss** 2021-12-06 09:36 UTC
Labels: x:mysql, duplicate, xf:data, x:odbc
