### ISSUE TITLE
Compatibility with Eclipse 2022.12

### ISSUE THREAD

**Issue by ssttaarr** [dbeaver/dbeaver#18478] opened 2022-12-08 11:34 UTC
### Description

DBeaver installation fails due to missing Bouncycastle dependency

### DBeaver Version

22.3.0

### Operating System

Linux Mint 21 x86_64

### Steps to reproduce

1. Fresh Eclipse 2022.12 JDT installation
2. Install DBeaver from the Eclipse marketplace

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver IDE 22.3.0.202212070729 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.0.202212070729)
  Missing requirement: Bouncy Castle PKIX, CMS, EAC, TSP, PKCS, OCSP, CMP, and CRMF APIs 1.70.0.v20220105-1522 (org.bouncycastle.bcpkix 1.70.0.v20220105-1522) requires 'java.package; org.bouncycastle.asn1 [1.70.0,1.71.0)' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver IDE 22.3.0.202212070729 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.0.202212070729)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.runtime.feature.feature.group [22.3.0.202212070729,22.3.0.202212070729]
  Cannot satisfy dependency:
    From: DBeaver Runtime 22.3.0.202212070729 (org.jkiss.dbeaver.runtime.feature.feature.group 22.3.0.202212070729)
    To: org.eclipse.equinox.p2.iu; org.bouncycastle.bcpkix [1.70.0.v20220105-1522,1.70.0.v20220105-1522]
```

**Comment by ssttaarr** [comment] 2022-12-08 11:34
Seems to be a regression of the #15941

**Comment by E1izabeth** [comment] 2022-12-08 12:31
Thank you for bug report.

**Comment by o2b-ru** [comment] 2022-12-08 13:39
Another similar issue:

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver IDE 22.3.0.202212070729 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.0.202212070729)
  Software currently installed: Eclipse Platform 4.26.0.v20221123-2302 (org.eclipse.platform.feature.group 4.26.0.v20221123-2302)
  Only one of the following can be installed at once: 
    Quick Search 1.0.300.v20200519-2023 (org.eclipse.text.quicksearch 1.0.300.v20200519-2023)
    Quick Search 1.1.100.v20210426-1601 (org.eclipse.text.quicksearch 1.1.100.v20210426-1601)
    Quick Search 1.1.300.v20211203-1705 (org.eclipse.text.quicksearch 1.1.300.v20211203-1705)
    Quick Search 1.1.400.v20221023-0941 (org.eclipse.text.quicksearch 1.1.400.v20221023-0941)
    Quick Search 1.1.200.v20210616-1255 (org.eclipse.text.quicksearch 1.1.200.v20210616-1255)
    Quick Search 1.0.400.v20201026-1722 (org.eclipse.text.quicksearch 1.0.400.v20201026-1722)
  Cannot satisfy dependency:
    From: Eclipse Platform 4.26.0.v20221123-2302 (org.eclipse.platform.feature.group 4.26.0.v20221123-2302)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.400.v20221023-0941,1.1.400.v20221023-0941]
  Cannot satisfy dependency:
    From: DBeaver Local Standalone Application 22.3.0.202212070729 (org.jkiss.dbeaver.app.local.feature.feature.group 22.3.0.202212070729)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.300.v20211203-1705,1.1.300.v20211203-1705]
  Cannot satisfy dependency:
    From: DBeaver IDE 22.3.0.202212070729 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.0.202212070729)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.app.local.feature.feature.group [22.3.0.202212070729,22.3.0.202212070729]
```

**Comment by TheKlodster** [comment] 2022-12-09 16:24
Confirm that I am having the same issue on Spring Tool Suite v4.17.0.RELEASE

**Comment by E1izabeth** [comment] 2022-12-14 20:19
Thank you for bug report.
Duplicate of #18475

**Closed as not planned by E1izabeth** 2022-12-14 20:19 UTC
Labels: duplicate
