### ISSUE TITLE
Filter -> Filter by value - UUID FK value is not in the list since version 23.1.5

### ISSUE THREAD

**Issue by proutek** [dbeaver/dbeaver#21202] opened 2023-09-13 19:04 UTC
### Description

When I want to filter by value FK column with UUID type and input the correct value, it's not shown in the list.

The screen is from version 23.1.4 where it works.
It does not work with 23.1.5 and 23.2.0

![image](https://github.com/dbeaver/dbeaver/assets/21219132/fb18df98-9e11-4773-b5e6-6a3588fc35dd)

### DBeaver Version

23.2.0

### Operating System

Windows 10

### Database and driver

PostgreSQL 14.8

**Comment by E1izabeth** [comment] 2023-09-14 14:00
Thank you for bug report.

**Comment by E1izabeth** [comment] 2023-09-14 14:13
I couldn't reproduce on the early access version. Most probably it was already fixed in scope of #21114.
Could you try? https://dbeaver.io/files/ea/

**Comment by AwesomeNameMan** [comment] 2023-09-18 16:54
I could reproduce the error, we're not able to filter by value and search the fk dictionary with the newest version. Also tested ea-version.

Was working fine with < 23.1

**Comment by E1izabeth** [comment] 2023-09-18 16:55
Could you provide a minimum example to reproduce? Also video showing the issue would be useful.

**Comment by AwesomeNameMan** [comment] 2023-09-18 17:04
Here you can see different course IDs, values can be read fine:
![image](https://github.com/dbeaver/dbeaver/assets/30497046/8a2b8f86-71c1-4402-8a64-37f5d34a1497)

Now we want to filter them:
![image](https://github.com/dbeaver/dbeaver/assets/30497046/42966ffc-5770-4b9e-abc2-2e59ec999d09)

But when we search, nothing pops up. That worked with a previous version completely fine:
![image](https://github.com/dbeaver/dbeaver/assets/30497046/2fd55706-f50e-43c0-aac3-af7eb5edc65f)

**Comment by uslss** [comment] 2023-09-28 10:26
Reproducible even on SQLite

https://github.com/dbeaver/dbeaver/assets/31996417/9ef288f1-a654-4687-bd17-369cd369e03d

**Closed as completed** 2023-11-27 15:13 UTC
Labels: xf:data, sp:2, xf:filters, xp:normal
