### ISSUE TITLE
Add "Run DBeaver" after update.

### ISSUE THREAD

**Issue by LuisPeregrinaPSL** [dbeaver/dbeaver#22204] opened 2023-12-18 18:47 UTC
**Is your feature request related to a problem? Please describe.**
When there is an update, DBeaver picks up this and asks you to install, if you chosen to install right away, the installer finishes but DBeaver was closed.

**Describe the solution you'd like**
Please add a checkbox on the last dialog to enable running DBeaver, this is kind of standard.

**Describe alternatives you've considered**
No lost functionality, no alternative needed.

**Additional context**
I forget that this app doesn't have this in the installer, so I often wonder if there was a problem and DBeaver just crashed.

**Comment by E1izabeth** [comment] 2023-12-18 19:36
Thank you for the feature request.
It's a duplicate of #17878
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2023-12-18 19:36 UTC
Labels: duplicate
