### ISSUE TITLE
Refresh bug and commands merge bug

### ISSUE THREAD

**Issue by shimengfei** [dbeaver/dbeaver#8430] opened 2020-04-14 09:33 UTC
**Describe the problem**
When I create a new database object, such as a column, but I didn't save the object but clicked the refresh button, and finally the save button did not setEnable (false) as expected. The save button is still available and there is no response after clicking.
**To Reproduce**

1. First I created a column
![image](https://user-images.githubusercontent.com/38394120/79207289-1cef3900-7e73-11ea-8a84-669ee6fb4cd2.png)
2. Then click the refresh button
![image](https://user-images.githubusercontent.com/38394120/79207300-22e51a00-7e73-11ea-9870-b79ce0a632d3.png)
3.Finally found that the save button is still available
![image](https://user-images.githubusercontent.com/38394120/79207338-2f697280-7e73-11ea-9143-5debe1c84edf.png)
**Expected behavior**
The save button should be unavailable
**Environment:**
 - Server OS: [windows 10]
 - Client app [dbeaver 6.2.2]

**Additional context**
The second problem is that when I create a new object, after I delete it directly, I will find that the Save and Revert buttons are available at this time, but they are expected to be unavailable. In addition, when I modify an existing object and then delete the object directly, I will find that the Save button is available at this time, but no response is generated. Expectation should be the generation of delete statements. Above and so on, I think it should be that Commands had a problem during merge, I suggest to check the code related to Commands merge

**Comment by uslss** [comment] 2020-04-14 13:41
thanks for the bug report

**Comment by uslss** [comment] 2021-02-04 16:27
still reproducible against 7.3.4

**Comment by ShadelessFox** [comment] 2021-05-24 15:27
Looks like a duplicate of #12331

**Closed by ShadelessFox** 2021-05-24 15:27 UTC
Labels: bug, sp:3, xf:metadata
