### ISSUE TITLE
Autocompletion of fields broken in 23.0.5

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#20180] opened 2023-06-01 20:41 UTC
### Description

Until 23.0.4 it was possible to write 
`select * from table`
and then put the cursor behind the `*` and press ctrl+space to get all fields of the table.

Now, in 23.0.5 I need to write
`select t.* from table t`
to make it work.

Am I doing something wrong or is it a newly introduced bug?

### DBeaver Version

23.0.5

### Database and driver

PG15.3

**Comment by apdma** [comment] 2023-06-01 20:48
Hi, I was going to write the same ticket.

Find out, what if you disable "Enable experimental features" in Preferences > Editors > SQL Editor > Code Completion, then autocompletion is available again.

Question is - how quickly "experimental" will become mainstream.

![2023-06-01 23 44 01](https://github.com/dbeaver/dbeaver/assets/91953047/242dca88-e70a-44f6-a0d0-3a9bb4077d34)
![2023-06-01 23 38 29](https://github.com/dbeaver/dbeaver/assets/91953047/83fad96f-efad-488c-808f-e698a8167e43)
![2023-06-01 23 37 13](https://github.com/dbeaver/dbeaver/assets/91953047/f679d584-a6e3-4d12-bb92-1a1e59748cdc)

**Comment by JamesInform** [comment] 2023-06-01 21:55
Yep, that did the trick. Thank's! Saved my day!!! 

But I think this is a bug that needs to be fixed.

Btw. changes to the autocompletion are mentioned in the changelog.

**Comment by E1izabeth** [comment] 2023-06-01 23:20
The mentioned issue has been already fixed and will be available on Monday's release (DBeaver 23.1.0)
You can try early access version now https://dbeaver.io/files/ea/

I'm closing this issue as a duplicate of #20032

**Comment by E1izabeth** [comment] 2023-06-01 23:20
Thank you for bug report.

**Closed as not planned by E1izabeth** 2023-06-01 23:20 UTC
Labels: duplicate, xf:sql parser
