### ISSUE TITLE
view data error Postgres 9.6_ Dbeaver all versions, can open in EMS and others like PGadmin 4 /5.1

### ISSUE THREAD

**Issue by SherlockSoftware** [dbeaver/dbeaver#13404] opened 2021-08-02 12:14 UTC
#### System information: 
- Windows 10 
- DBeaver 21.1.4 (and earlier)
- Java JDBC 4.1 (JR 8+) driver for Postgres
- postGIS 2.2.1 Geometry 2.5.0

#### Connection specification:
- postGres 9.6
- postgres    port 5432.. standard simple
- Do you use tunnels or proxies (SSH, SOCKS, etc)?   NO
[dump-__crash_re_settings_View_Data-202108032218.zip](https://github.com/dbeaver/dbeaver/files/6923985/dump-__crash_re_settings_View_Data-202108032218.zip)

**Comment by SherlockSoftware** [comment] 2021-08-02 13:04
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [22021]: ERROR: invalid byte sequence for encoding "UTF8": 0xc2 0x76
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4711)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0xc2 0x76
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 7 more

**Comment by SherlockSoftware** [comment] 2021-08-02 13:08
![image](https://user-images.githubusercontent.com/64625961/127866991-293d8e25-56e1-4112-9317-116d462e66a0.png)

**Comment by tati-kru** [comment] 2021-08-11 13:04
Duplicate of #11139

**Closed as completed by tati-kru** 2021-08-11 13:04 UTC
Labels: x:postgresql, duplicate
