### ISSUE TITLE
Table view flashes, impossible to work 21.3.1

### ISSUE THREAD

**Issue by andriusign** [dbeaver/dbeaver#15018] opened 2021-12-25 11:23 UTC
Open Dbeaver 21.3. 
Table view flashes on each mouse move event, impossible to work at all. Glitches start randomly, sometimes on maximize window, sometimes just when program opens.

![Untitled](https://user-images.githubusercontent.com/14263959/147383920-fa70d0c2-25db-4bcf-9185-60639131c91b.png)

OS: Linux

**Comment by ShadelessFox** [comment] 2021-12-25 12:52
Hello @andriusign,

Thanks for the report.

Duplicate of #14751.

**Closed as completed by ShadelessFox** 2021-12-25 12:52 UTC
Labels: duplicate, xo:linux, xf:ui
