### ISSUE TITLE
Add new column by right click

### ISSUE THREAD

**Issue by felangga** [dbeaver/dbeaver#6736] opened 2019-09-13 03:46 UTC
Hello, I'm using DBeaver latest version 6.2.0. 
I'm having a problem when I want to add new column  by right clicking on Table Properties. The menu won't showing up. This problem exist in this version, but not in previous version 6.1.x.
Hope it will fixed soon.

**Comment by uslss** [comment] 2019-09-13 08:42
@felangga could you add info about your OS version?

**Comment by felangga** [comment] 2019-09-16 03:14
Distributor ID: neon
Description: KDE neon User Edition 5.16
Release: 18.04
Codename: bionic

Linux nullpad 4.19.0-041900-lowlatency #201810221809 SMP PREEMPT Mon Oct 22 22:19:15 UTC 2018 x
86_64 x86_64 x86_64 GNU/Linux

Felix Angga

E: felangga@gmail.com (https://link.getmailspring.com/link/E65B9274-D759-482A-8F29-C6708865F2A0@getmailspring.com/0?redirect=mailto%3Afelangga%40gmail.com&recipient=cmVwbHkrQURSQTZDRVhRVFVQVlZQQ0JMWktUVk4zUkNFUVBFVkJOSEhCMlpEVVNRQHJlcGx5LmdpdGh1Yi5jb20%3D)
W: http://felangga.blogspot.com (https://link.getmailspring.com/link/E65B9274-D759-482A-8F29-C6708865F2A0@getmailspring.com/1?redirect=http%3A%2F%2Ffelangga.blogspot.com&recipient=cmVwbHkrQURSQTZDRVhRVFVQVlZQQ0JMWktUVk4zUkNFUVBFVkJOSEhCMlpEVVNRQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by serge-rider** [comment] 2019-09-16 21:33
Duplicate of #6489

**Closed by serge-rider** 2019-09-16 21:33 UTC
Labels: bug, duplicate
