### ISSUE TITLE
 hadoop spark displays only default database

### ISSUE THREAD

**Issue by rmunoz10** [dbeaver/dbeaver#4680] opened 2018-11-25 00:11 UTC
Hi. I don't seem to be able to display non-default databases using hadoop spark.  Setting a database in the driver or url does not seem to work.  Not sure if I'm missing anything.

Thanks.
 
![selection_001](https://user-images.githubusercontent.com/26364789/48974094-1eb92200-f01c-11e8-9990-b7607b6cb4a0.png)
![selection_002](https://user-images.githubusercontent.com/26364789/48974102-6049cd00-f01c-11e8-9358-674ae2f54995.png)

**Comment by wonb168** [comment] 2019-04-24 23:57
same as me

**Comment by serge-rider** [comment] 2019-07-05 15:06
Duplicate of #5314

**Closed by serge-rider** 2019-07-05 15:06 UTC
Labels: bug, duplicate
