### ISSUE TITLE
Extremely slow or completely broken text editor for larger TEXT or JSON columns

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#11802] opened 2021-03-20 11:22 UTC
I've found an issue with the text editor for cell values that make it virtually impossible to use. By text editor I mean the one you open with Shift+Enter on a table cell in the data view tab. Either DBeaver will take a very long time to open the editor while being frozen or the editor will open empty. I've found out the problem happens when the text contains no line breaks.

I'm attaching a small table with sample data that will illustrate the problem:

[testtext.zip](https://github.com/dbeaver/dbeaver/files/6175395/testtext.zip)

It contains 3 rows with JSON and TEXT columns. Opening the json or the text column of row 1 for editing with Shift+Enter takes 38 seconds and DBeaver eats 100% cpu of one core at that time. The length of the text is about 30 KB so it is not really very large. I would expect such delays for lengths of several megabytes but 30 KB is really tiny,

Trying to open values for row 3 is even worse: the editor opens empty and when typing I can't see any text appearing on the screen but I see the length is changing so I presume the editing happens somehow being invisible. Same happens with the text column of row 2.

This issue is especially problematic for JSON columns which mysql presents as a string in one line. One-line TEXT columns are also affected.

DBeaver version: 21.0.0 on Win 10 64-bit, MySQL 5.7.

**Comment by uslss** [comment] 2021-03-22 08:54
Thanks for the bug report

**Comment by arhayka** [comment] 2023-09-05 09:04
Seems to be a duplicate of https://github.com/dbeaver/dbeaver/issues/15951

**Comment by serjiokov** [comment] 2023-09-06 13:54
Issue fixed in https://github.com/dbeaver/dbeaver/issues/15951, The large content representation and editing restricted by size of 1Mb, it allows keep navigation by fields JSON fields without of lags, additional content settings provided on preferences page. Not recommended to edit files with size more than 10 Mb.

**Closed as completed** 2023-09-14 13:14 UTC
Labels: duplicate, xf:data, performance, xp:normal
