### ISSUE TITLE
Connection related toolbar items disappear when I select a db from the list.

### ISSUE THREAD

**Issue by siniradam** [dbeaver/dbeaver#19572] opened 2023-03-31 20:16 UTC
### Description

I've installed the latest version of `dbeaver`. (Version 23.0.1.202303250535)
This is started to happen. 

![Screen Recording 2023-03-31 at 1 10 18 PM](https://user-images.githubusercontent.com/3178435/229221032-31e1ffe8-75d7-40fe-9418-611ee064eb5e.gif)

### DBeaver Version

Version 23.0.1.202303250535

### Operating System

macOS Ventura 13.2.1

### Steps to reproduce

1. Open dbeaver
2. Select a db from the list. (Doesn't matter if connected or not)
3. Icons disappear.
4. If I re-launch the app it comes back. 

### Additional context

If I right-click on the toolbar and click lock taskbar/unlock taskbar icons re-appear.

**Comment by E1izabeth** [comment] 2023-04-01 10:34
Thank you for bug report. It's a known issue. Close as duplicate of #19495
The fix will be available in the next release.

**Closed as completed by E1izabeth** 2023-04-01 10:34 UTC
Labels: duplicate, xo:macos
