### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by lrweck** [dbeaver/dbeaver#7313] opened 2019-11-28 19:42 UTC
Version: DBeaver 6.2.5

Problem:

I am trying to set up a graph using PostgreSQL pg_stat_statements view. 

This is the setup:

![image](https://user-images.githubusercontent.com/26086198/69829101-783ec880-11fd-11ea-8594-30a76693e9ee.png)

This is the result:

![image](https://user-images.githubusercontent.com/26086198/69829162-b9cf7380-11fd-11ea-8132-d4a348f5da52.png)

If I remove the "TOTAL" column, it show the real count for each of the items, and it looks much more believable:

![image](https://user-images.githubusercontent.com/26086198/69829238-f7cc9780-11fd-11ea-9cf3-7ca02ac26769.png)

Is there a limit to the number of columns I can add?

**Comment by serge-rider** [comment] 2019-11-29 21:26
Looks like a bug in dashboard processing.
Could you copy query in plaintext?

**Comment by lrweck** [comment] 2019-12-02 12:15
select sum(calls) filter (where upper(trim(query)) ~ '^SELECT' ) as "SELECT",
        sum(calls) filter (where upper(trim(query)) ~ '^UPDATE' ) as "UPDATE",
        sum(calls) filter (where upper(trim(query)) ~ '^INSERT' ) as "INSERT",
        sum(calls) filter (where upper(trim(query)) ~ '^DELETE' ) as "DELETE"
  from pg_stat_statements
where upper(trim(query)) ~ '^(SELECT|UPDATE|INSERT|DELETE)'

**Comment by serge-rider** [comment] 2019-12-16 19:38
The error was caused by timeseries interval "second". It should be passed as milliseconds timestamp in JFC lib.
Now fixed, thanks for the details.

PS Also dashboard config save was fixed.

**Comment by kseniiaguzeeva** [comment] 2019-12-18 20:34
Verified

**Closed by kseniiaguzeeva** 2019-12-18 20:34 UTC
Labels: bug
