### ISSUE TITLE
DBeaver/Okta/Snowflake

### ISSUE THREAD

**Issue by relcodedev** [dbeaver/dbeaver#18515] opened 2022-12-14 22:34 UTC
### Description

Connecting to snowflake with dbeaver/okta  on linux

I get the following error message:

Unexpected driver error occurred while connecting to the database

  NullPointerException
  java.lang.NullPointerException
  
  I followed the information in this article: https://dev.to/klo2k/connect-dbeaver-to-snowflake-via-okta-sso-flatpak-snap-cn4

I am using the flatpak version of dbeaver.  The external browser auth is not supported.   The article above states to add the authenticator key/value to okta url in the user properties.  

I get the error above.

I get the same error on Windows 10 with the same configuration.

![dbeaver](https://user-images.githubusercontent.com/91266964/207729384-9eb12755-fd46-4adc-899c-ee20e2f38001.png)

### DBeaver Version

22.3.0.202212070729

### Operating System

Pop!OS 22.04

### Database and driver

Latest Snowflake driver. 3.13.26

**Comment by uslss** [comment] 2022-12-15 12:58
#16309

**Comment by LonwoLonwo** [comment] 2022-12-15 14:00
Hello @relcodedev 

Can you please check other driver versions? 
Snowflake driver - 3.13.6 - as an example.

**Comment by relcodedev** [comment] 2022-12-15 14:39
I switched to 3.13.6 which is older driver and got this error:

JDBC driver encountered communication error. Message: Exception encountered when opening connection: no protocol: /login/cert.
  no protocol: /login/cert


The driver was changed to support okta in 3.13.22 forward.  I tested  3.13.22 -> 3.13.26 and get same error above.

**Comment by LonwoLonwo** [comment] 2022-12-19 07:49
Maybe you can provide me with your driver properties photo? To see how the property was added.

**Comment by relcodedev** [comment] 2022-12-19 13:48
![Screenshot from 2022-12-19 08-19-22](https://user-images.githubusercontent.com/91266964/208439866-bd498d09-2947-4f03-b4a1-e3d8f3754d1f.png)
![Screenshot from 2022-12-19 08-24-38](https://user-images.githubusercontent.com/91266964/208439803-e36160cb-dd68-43cd-9a85-d41a0ed7c0fd.png)

This is what the dev.to url described to do.

I tried several ways including not adding the property but adding the url to the Authenticator on the first screen with the same result with latest driver 3.13.26.

**Comment by LonwoLonwo** [comment] 2022-12-21 11:03
![2022-12-21 14_01_32-Window](https://user-images.githubusercontent.com/45152336/208890201-f9e4b0c3-7417-4a89-8338-ff60e5b56709.png)

Ok, just curious, what if you use your URL path in the authenticator field? Will it be the same result?

**Comment by relcodedev** [comment] 2022-12-21 13:42
Yes, I tried that also. I removed the driver property and entered the value in the Authenticator field.  I get the same NullPointer exception. I also tried the same thing on windows with the same result.

**Comment by LonwoLonwo** [comment] 2022-12-22 13:56
Unfortunately, I can reproduce this issue. I do not have a test environment.

I suggest you create a ticket here: https://github.com/snowflakedb/snowflake-jdbc/issues
because this is the driver's issue. I hope they can help you.

**Comment by EvanK** [comment] 2023-01-30 21:12
FWIW, I had a working Snowflake connection using an `Authenticator` argument of the Okta SSO subdomain, until the latest DBeaver update (to `22.3.3.202301211053`).

Said update started causing NPEs, which was fixed by changing the authenticator to `externalbrowser`:

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/84145/215596043-b48499e0-1d2c-4492-922d-9b91d12a0555.png">

**Comment by LonwoLonwo** [comment] 2023-01-31 10:11
Thanks for the workaround @EvanK

**Comment by relcodedev** [comment] 2023-02-23 01:52
@EvanK using the authenticator=externalbrowser opens the browser which is how I was originally using it. I can't use the okta username with external browser, the authentication fails.

**Comment by LonwoLonwo** [comment] 2023-10-20 11:18
Hello @relcodedev 

Is this issue still reproducible for you in DBeaver? We upgraded the default Snowflake driver version.

**Comment by E1izabeth** [comment] 2023-11-15 12:11
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Closed as completed by E1izabeth** 2023-11-15 12:11 UTC
Labels: x:snowflake, wait for response, third party issue, xf:connection
