### ISSUE TITLE
Tables missing from the Database Navigator table list for PostgreSQL in version 4.3.0

### ISSUE THREAD

**Issue by jmeliwsi** [dbeaver/dbeaver#2624] opened 2017-12-12 15:56 UTC
After upgrading to version 4.3.0, there are tables missing from the Table list in the Database Navigator for my PostgreSQL database.  There is no filter applied to the list of tables.  My database is using PostgreSQL 9.5.1 and DBeaver shows a 9.4 compatible driver.  There were no table list issues in the prior 4.2.x version of DBeaver.

**Comment by serge-rider** [comment] 2017-12-12 19:48
I can't reproduce this.
Is there anything special about missing tables? 
Some specific table type?

**Comment by serge-rider** [comment] 2017-12-12 19:57
Or maybe this is the same issue as #2622

**Comment by jmeliwsi** [comment] 2017-12-12 20:31
I tried updating the driver.  It had no effect on the problem.  Could the number of tables in the schema be an issue (there are 4691 tables)?  I usually use filters to reduce the number of tables in the list.  In this case, applying a filter shows the same problem, with tables missing from the list.  It could be the same problem as #2622, however I do not get an error popup dialog.

**Comment by serge-rider** [comment] 2017-12-12 21:50
@jmeliwsi generally number of tables shouldn't affect anything.
Please check
>Is there anything special about missing tables?
>Some specific table type?

Without this information it is unclear what is going on.

**Comment by jmeliwsi** [comment] 2017-12-13 12:32
@serge-rider I can find nothing special about the missing tables and there is no specific table type missing.  Below is an example.  From the list below, only the first table (it isn't always the first table) shows in the Database Navigator list.

table_schema|table_name|table_type|is_insertable_into|is_typed
wsi|taps_maint_flags|BASE TABLE|YES|NO
wsi|taps_reports|BASE TABLE|YES|NO
wsi|taps_reports_20171207|BASE TABLE|YES|NO
wsi|taps_reports_20171211|BASE TABLE|YES|NO
wsi|taps_reports_20171210|BASE TABLE|YES|NO
wsi|taps_reports_20171209|BASE TABLE|YES|NO
wsi|taps_reports_20171206|BASE TABLE|YES|NO
wsi|taps_reports_20171208|BASE TABLE|YES|NO
wsi|taps_reports_20171212|BASE TABLE|YES|NO
wsi|taps_reports_20171214|BASE TABLE|YES|NO
wsi|taps_reports_20171213|BASE TABLE|YES|NO

I see other issues also.   For example, when I click the "Edit Procedure" menu item, it opens a new tab, but it doesn't show the code for the procedure.  It only shows properties and the procedure columns.

**Comment by jmeliwsi** [comment] 2017-12-13 15:44
@serge-rider One thing I noticed that might be significant.  In the tables I listed in my previous post, the missing tables have Super Tables and have or are Sub Tables:

Table Name: taps_reports
ID: 463374
Owner: wsi_provider
Description: **********
Tablespace: pg_default
Row Count Estimate: 0
Super Tables: [wsi.audit_tables]
Sub Tables: [wsi.taps_reports_20171212, wsi.
 taps_reports_20171214, wsi.taps_reports_20171209, wsi.
 taps_reports_20171211, wsi.taps_reports_20171213, wsi.
 taps_reports_20171208, wsi.taps_reports_20171207, wsi.
 taps_reports_20171210]
Has Oids: false

**Comment by serge-rider** [comment] 2017-12-14 06:36
Looks like partition tables. Now they are not placed under the main table in the tab "Partitions".
This change was made in 4.3.

**Comment by GiannisDem** [comment] 2017-12-14 10:04
@serge-rider 

> Looks like partition tables. Now they are not placed under the main table in the tab "Partitions".
> This change was made in 4.3.

There is some logic showing "Partitions" under the main table but i don't find this change useful regarding "Child" tables.
With PostgreSQL Inheritance you can have a parent table with 0 rows and child tables inheriting only some columns from parent so i don't find it logically not to show child tables in the main list.
In general you want to see all tables of the schema under "Tables" drop down list.
Having to navigate further inside tables makes it more time consuming and confusing.
My suggestion would be to show ALL tables under "Tables" drop down and still show "Partitions" and "Child" tables under the main table.

**Comment by serge-rider** [comment] 2017-12-14 18:02
Agreed about child tables. It makes sense to have them in the main list. I'mm return them back in the next version.

But partition tables are different. They all have the same structure and sometime you have hundreds of them, this is a bit messy. So I personally would prefer to have them only inside "owner" table. WDYT?

**Comment by GiannisDem** [comment] 2017-12-15 08:05
I get the point that it may get messy if you have hundreds of partition tables.
But i'm trying to see it from the perspective of a new user of dbeaver, if you open the table drop down and you don't see all your tables it maybe a shocking experience especially if you don't know where you can find them.
I would suggest if that's possible to leave it to the user to decide, from preferences maybe, if he/she wants to see the partition tables under the main list. This would imply that you should leave the Partition folder under the main table.
Thanks and keep up the good job.

**Comment by rumbin** [comment] 2018-01-08 17:45
+1 for reverting the behavior of the child tables.
In my use case the child tables even belong several different schemas. This design was chosen in order to yield a comprehensive data structure. Intefrating them with the parent table in the parent table's schema removes a lot of usability for me.
On the other hand I like the idea of having all child tables easily visible/accessible at one place. Is there anything preventing a solution where the tables are shown both at their parent table and within the Tables folder of their respective schemas?
Or alternatively/optionally make the behavior configurable?

--------------
OT: This is my first time commenting to this repo. Thanks a lot for this wonderful piece of software. I highly appreciate its completeness of features and its compatibility with so many databases.

**Comment by rumbin** [comment] 2018-01-08 17:49
I just noticed that in version 4.3.2 the child tables are now shown in both places, just the way I would have preferred it. Thanks!

I guess this issue can be closed now, @jmeliwsi?

**Comment by jmeliwsi** [comment] 2018-01-08 18:48
@rumbin Yes, you can close it.  Thanks all for the quick turnaround!

**Comment by rumbin** [comment] 2018-01-08 18:54
@jmeliwsi: Well I cannot close it, as I'm not a contributor. Credits go to someone else, too (@serge-rider, I guess‽).

**Comment by serge-rider** [comment] 2018-01-08 21:05
Alright then.
Closing.

**Closed by serge-rider** 2018-01-08 21:05 UTC
Labels: can't reproduce, question
