### ISSUE TITLE
Feature: Make bookmarks in text files project bound instead of global

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4305] opened 2018-09-29 18:21 UTC
DBeaver - **Version 5.2.1 CE**
DBeaver JDBC driver: **jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014**

It would be benificial if my bookmarks that I have set in different SQL files project bound.

**o** Start _DBeaver_ program.
**o** Choose **Window -> Show View -> Bookmarks** in the menu.
**o** Open a text/sql file.
**o** Set a _bookmark_ on a row in the text/sql file (**Ctrl+3 -> Add Bookmark**).
**o** View the new _bookmark_ in the **Bookmark** view/tab.
**o** Switch/Create a _project_ in the **Projects view/tab** and activate it.
**o** The _bookmark_ that was previously created are still visible.

Currently that kind of bookmark are global (ie. no matter what project I choose, the same bokmarks are visible).

**Comment by uslss** [comment] 2020-07-22 15:19
duplicate of #4306 4306

**Closed by uslss** 2020-07-22 15:19 UTC
Labels: duplicate, feature request
