### ISSUE TITLE
Partition Column Tab is shown incorrectly

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7660] opened 2020-01-16 14:20 UTC
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/31996417/72532446-b9556f80-3873-11ea-8b13-e8eaa2eb0f33.png)

**Comment by serge-rider** [comment] 2020-01-16 21:56
Can't reproduce. Probably fixed in #7659

**Closed** 2020-01-20 14:16 UTC
Labels: bug, can't reproduce, x:exasol
