### ISSUE TITLE
Cannot SSH terminal on last version 22.2.1

### ISSUE THREAD

**Issue by jeanse7en** [dbeaver/dbeaver#17803] opened 2022-10-04 01:26 UTC
### Description

I cannot access MySQL DB via SSH tunnel. It throws me an exception like "SSH failed multi times", I didn't remember exactly.
I already reverted to previous version and it worked well

### DBeaver Version

22.2.0

### Operating System

MacOS  Monterey

### Database and driver

Mysql 8

### Steps to reproduce

1. Download the last version 22.2.1
2. setup a ssh tunel
3. try to connect

**Comment by Destrolaric** [comment] 2022-10-06 13:49
Hi, Duplicate of https://github.com/dbeaver/dbeaver/issues/17748

**Closed as not planned** 2022-10-06 13:49 UTC
Labels: duplicate
