### ISSUE TITLE
Export data to database connection issue

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#15296] opened 2022-01-26 10:44 UTC
DBeaver  21.3.3.202201221033, win10x64.
Oracle Database.

Hi!
I am performing the following scenario - export from one database to another. First step - I choose export, go to field select.
See pic 1. I checked "create new table", then "create every field except one, not needed (i set "skip").
Then I go further to final confirmation. I got an connection error, ok. I press ok, then again, it reconnects and tries to repeat.
But somehow columns settings became again to "create" state, even that first, marked as "skip". I go back to columns, set "skip", go further, everything works.
![dbeaver_export1](https://user-images.githubusercontent.com/11477081/151149278-d5762ce2-f445-4a81-9232-315cb19273ab.png)
![dbeaver_export2](https://user-images.githubusercontent.com/11477081/151149297-d425d7cd-0bc2-4f85-af51-3492cda4ee7c.png)

**Comment by Matvey16** [comment] 2022-01-26 11:48
@plotn Can you please explain what exactly you did after connection error? Have you finished the export or you closed the export wizard and opened it again after reconnect to retry?

**Comment by plotn** [comment] 2022-01-26 12:03
I try to continue.
Oracle says, that he cannot create column "RowId", because it is system for him.
I go back to column settings and set [skip] AGAIN (I surely did it once).
Then it works (I press next, next, and so on).

NB: During all of this I do not close thr wizard

**Comment by uslss** [comment] 2022-03-22 10:59
seems the issue is fixed in the scope of #15365

**Closed as completed by uslss** 2022-03-22 10:59 UTC
Labels: xf:datatransfer, wait for response
