### ISSUE TITLE
mysqldump failed if connection is URL

### ISSUE THREAD

**Issue by hayarobi** [dbeaver/dbeaver#34581] opened 2024-07-01 03:05 UTC
### Description

dump database module seem to refer only host and database field. 
When I set url to remote host address, the Server Host and database field are still localhost.

### DBeaver Version

Community edition 24.1.1.202406231636

### Operating System

macOS Ventura 13.6.7(22G720)

### Database and driver

mysql 

### Steps to reproduce

1. create connection by host with localhost 
2. update connection configuration by url with remote host address.
3. connect database and invoke tools>Dump database
4. the dump job will fail.

Please watch the screenshot. The value of `--host` flag was missing. 
<img width="731" alt="스크린샷 2024-07-01 11 22 12" src="https://github.com/dbeaver/dbeaver/assets/3103946/de2c54f4-a09e-4926-8d10-e6a0de24fc0d">
<img width="1630" alt="스크린샷 2024-07-01 11 25 16" src="https://github.com/dbeaver/dbeaver/assets/3103946/ea18aeee-efaf-40d3-9169-6a40d731c524">
<img width="1159" alt="스크린샷 2024-07-01 11 24 48" src="https://github.com/dbeaver/dbeaver/assets/3103946/9050fc29-08e4-4933-9a10-8440781c3de1">

**Comment by LonwoLonwo** [comment] 2024-07-01 04:54
Hello @hayarobi 

Thanks for the report.
This is a duplicate of https://github.com/dbeaver/dbeaver/issues/23220, so I'm closing it.

**Closed as completed by LonwoLonwo** 2024-07-01 04:54 UTC
Labels: x:mysql, duplicate, xf:native clients
