### ISSUE TITLE
Simple, low-volume queries take ~10 minutes to return results

### ISSUE THREAD

**Issue by MM026184** [dbeaver/dbeaver#4046] opened 2018-08-21 14:33 UTC
I recently upgraded to 5.1.5 (Community) and each time I attempt to run very simple, low volume (10 rows) queries it takes forever for results to return:

![image](https://user-images.githubusercontent.com/25959102/44407611-361bd700-a524-11e8-8eb1-226d56bfd967.png)

![image](https://user-images.githubusercontent.com/25959102/44407780-8abf5200-a524-11e8-99f4-7d77c8021aec.png)

Result pane either just says 'Execute query' or 'Discover owner entity' or 'Discover attribute 'result column'.

I've confirmed that this isn't an issue with the database itself.  While the above screenshots were taken, I kicked off the same query in SQuirreL, which returned results in < 0.1 sec:

`Query 1 of 1, Rows read: 10, Elapsed time (seconds) - Total: 0.071, SQL query: 0.07, Reading results: 0.001`

Additional Information:
Database connection type: Vertica
Vertica version: Vertica Analytic Database v8.1.1-14
OS: Windows 10 Enterprise

**Comment by MM026184** [comment] 2018-08-21 15:09
It is important to note, I also have Oracle connections that work without issue.

This issue is still reproducible in DBeaver, but not SQuirreL after updating Vertica drivers in both apps.

**Comment by serge-rider** [comment] 2018-08-21 18:50
Duplicate of #3981
Thanks for the bug report anyway.

**Closed by serge-rider** 2018-08-21 18:50 UTC
Labels: bug, duplicate, x:vertica
