### ISSUE TITLE
PG - Hidden actions when browsing a database?

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8160] opened 2020-03-11 08:08 UTC
PG - In "No autocommit mode", when connecting to a machine, after double clicking on a table, the "Transaction indicator" says i have 1 uncommitted action. And i just connected and did onthing else than double-click on table name.
What could that be?

**Comment by uslss** [comment] 2020-03-11 10:52
seems to be duplicate of #8136 .
closed as duplicate

**Closed by uslss** 2020-03-11 10:52 UTC
Labels: question, wait for review
