### ISSUE TITLE
"DBCException: Can't resolve data type" on array of user-defined data type inside another schema

### ISSUE THREAD

**Issue by fjf2002** [dbeaver/dbeaver#14004] opened 2021-09-24 15:33 UTC
#### System information: 
- Operating system (distribution) and version: **Windows 10**
- DBeaver version: **21.2.1 CE**
- Additional extensions: **None**

#### Connection specification:
- Database name and version: **PostgreSQL 13.3**
- Driver name: org.postgrsql:postgresql **42.2.23**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **no**

#### Describe the problem you're observing:
In the result table cells, the following Exception is shown instead of a value:
```
org.jkiss.dbeaver.model.exec.DBCException: Can't resolve data type "tools"."_foo"
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:67)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.fetchColumnValue(PostgreArrayValueHandler.java:53)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:721)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3440)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

#### Steps to reproduce:
This seems to only occur if I use
* an ARRAY of...
* a user-defined-type...
* ... that is located inside another schema.

Example:
```sql
CREATE SCHEMA tools;

CREATE TYPE tools.foo AS (
	bar integer
);

SELECT ARRAY[ROW(42)::tools.foo, ROW(42)::tools.foo];
```

The error vanishes if I change the above script to one of the following:
* omit the schema "tools" (i. e. creating the type on the first schema in the search_path)
* omitting ARRAY, i. e. just selecting SELECT ROW(42)::tools.foo

**Comment by uslss** [comment] 2021-09-29 08:13
@fjf2002 unfortunately, cannot reproduce an issue.
I've just executed the script provided by you as a script and get the following result:
![image](https://user-images.githubusercontent.com/31996417/135231718-69f3d898-7944-4431-82c2-66dd03d02423.png)
Probably some special steps are needed?

**Comment by fjf2002** [comment] 2021-10-09 06:45
(Note to myself: recreate the test on an empty database.)

**Comment by fjf2002** [comment] 2021-10-09 06:50
I can confirm that the problem does not occur on an empty database postgres-12.7, pgjdbc 42.2.5, dbeaver ce 21.0.0 on mac.
On monday I will test on the machine where the problem initially occurred.

**Comment by fjf2002** [comment] 2021-10-11 07:27
I have instantiated a brand new postgres docker container, version 13.4.
Dbeaver ce is Version 21.2.2.202110030714.
pgjdbc is version 42.2.23.

The problem still persists :-(

![Unbenannt](https://user-images.githubusercontent.com/7130250/136749442-0df832f1-4124-4920-b578-266da90768d7.png)

**Comment by uslss** [comment] 2021-10-25 13:20
thanks for the report. the issue isn't reproducible with 42.2.20 driver.
Reproducible with 42.2.23

**Comment by LonwoLonwo** [comment] 2022-02-28 13:06
Can't reproduce against in DBeaver 21.3.5 and with PostgreSQL driver 42.2.5

**Comment by LonwoLonwo** [comment] 2022-03-01 16:10
Hmm, ok, I can reproduce it with the 42.3 version driver. 

Data kind of the data type changed from object to array, and PostgreArrayValueHandler can't find data type by name - "tools"."foo".

**Comment by LonwoLonwo** [comment] 2022-03-03 15:00
Fixed in DBeaver 22.0.1

**Comment by uslss** [comment] 2022-03-14 08:24
verified

**Closed as completed by uslss** 2022-03-14 08:24 UTC
Labels: x:postgresql, xf:data, sp:2, xf:metadata

**Comment by DanteMF** [comment] 2023-08-08 11:37
Hello!

@uslss, @LonwoLonwo  the problem has returned :(
my version 23.1.3.202307231901 (mac os)

<img width="710" alt="Снимок экрана 2023-08-08 в 18 19 56" src="https://github.com/dbeaver/dbeaver/assets/44617307/89034601-cc73-4bf9-a0b7-c0dda4396478">
