### ISSUE TITLE
Cannot save changes to stored procedures through data editor

### ISSUE THREAD

**Issue by Wayusen** [dbeaver/dbeaver#33204] opened 2024-05-18 09:14 UTC
### Description

When applying database filters, cannot save changes in stored procedure or functions through data editor/Source tab. Getting a script generate error: "Cannot invoke "org.jkiss.dbeaver.model.struct.DBSObject.getDataSource()" because "object" is null".
Noticed that toolbar button for Active catalog/schema shows <N/A> and does not let me change it. When disabling database filters, this shows dbo@master and saving stored procedure works fine.

DBeaver Version
Community Edition v. 24.0.4.202405051837

Operating System
Windows 10 Enterprise v. 22H2 os build 19045.4291

Database and driver
DB name and version: Microsoft SQL server 2017 (RTM- CU31) (KB5016884) - 14.0.3456.2 (X64)
Driver and version: MS SQL server / SQL Server
Microsoft JDBC Driver for SQL Server (MSSQL)
Release 12.4.1.jre11, 12.4.1.x64

Steps to reproduce
Goto Edit Connection>General>Filters>Databases/Catalogs
Click on Enable checkbox
Add Alentpr% into Include. Need to filter all Databases that start with Alentpr.
Click Ok and Ok again.
Open connection to SQL server instance.
Filtered database works fine.
Open any database and then schemas>dbo>procedures.
Right click on any stored procedure and select View procedure.
Go to source tab.
Make any change.
Click on button on bottom right of screen called Save...
Will get error message stated in description above.
Noticed that toolbar button for active schema shows N/A.
To fix:
15. Disable filter from 2.
16. Steps 7 to 11 works fine by opening a new script with Alter stored procedure
17. Toolbar button from 13 shows dbo@master.

Additional context
Only have office extension installed. Using native dark theme.

### DBeaver Version

Community

### Operating System

Macos ventura 12

**Comment by E1izabeth** [comment] 2024-05-18 19:19
Thank you for bug report. I'm closing it as a duplicate of #32643
If you experience this issue too, you can vote for the mentioned issue with 👍 under the issue description or left a comment to promote it to a higher priority.

**Closed by E1izabeth** 2024-05-18 19:19 UTC
Labels: bug, wait for review
