### ISSUE TITLE
Teradata Filter User Schema

### ISSUE THREAD

**Issue by gwired2015** [dbeaver/dbeaver#9385] opened 2020-07-28 17:48 UTC
**Is your feature request related to a problem? Please describe.**
I have over 5900 Schemas in my Teradata connection.  Of those, a large percentage of them are User Schema's such that the ability to view actual useful schemas is limited and takes a long time to load.

**Describe the solution you'd like**
Enable the ability to filter out User Schemas without having to name them individually for Teradata Connections.  It should be on a per connection basis and I should be able to see my own user schema always.

**Describe alternatives you've considered**
Other tools instead of DBeaver have this option.

**Additional context**

**Comment by kseniiaguzeeva** [comment] 2020-07-29 09:04
Thank you for the suggestion.

**Comment by LonwoLonwo** [comment] 2021-07-27 08:46
Hello @gwired2015 
You can try to add filters in the "Edit connection" dialog for databases/schemas

![2021-07-27 11_41_57-DBeaver Enterprise 21 1 4 - _orcl_ Script-143](https://user-images.githubusercontent.com/45152336/127124621-eb23dd2b-17fd-427d-b009-3142b13dc98a.png)

Or use Database Navigator filters: 
![2021-07-27 11_42_58-DBeaver Enterprise 21 1 4 - _orcl_ Script-143](https://user-images.githubusercontent.com/45152336/127124623-c93e8f4a-6db4-4989-8961-de9de3beba1e.png)

**Comment by Anteus** [comment] 2023-02-05 08:27
Is it possible to save the chosen Database Navigator filter? It seems to be reset every time DBeaver is restarted.

**Comment by LonwoLonwo** [comment] 2023-03-02 11:12
Hello @Anteus 

Can you provide more info about your situation? What kind of Database Navigator filters do you use? For now, I can't reproduce this. My filters (from this answer https://github.com/dbeaver/dbeaver/issues/9385#issuecomment-887329928) are in their places after DBeaver restart.

**Comment by Anteus** [comment] 2023-03-02 15:47
Hi @LonwoLonwo

It's the Database Navigator filters which you show in the second pic. They get reset to default setting to only search for "Filter tables, procedures, etc.".
If I select search for "Filter table containers" and then restart DBeaver and that filter selection is back to default.

Might be good with an option to be able to search for containers and tables in one go or would it be too messy?
Could also imagine a second search box for the table container or being able to search for container and table in one go with wildcards such as contain*.table

**Comment by LonwoLonwo** [comment] 2023-03-03 09:35
Please try to enable this setting:
Preferences -> User Interface -> Navigator -> "Save database navigator filter"

![2023-03-03 12_31_09-DBeaver 23 0 0 - _postgres 2_ Script-18](https://user-images.githubusercontent.com/45152336/222685116-199878ab-8768-43b0-82e4-cb031faeb65f.png)

It works for me

![2023-03-03 12_35_11-DBeaver 23 0 0](https://user-images.githubusercontent.com/45152336/222685242-9d9fb6b6-9c69-438c-9dcd-82795c25f7e1.png)

**Comment by Anteus** [comment] 2023-03-03 15:03
Thanks that works great! Seems like that option is not searchable in the settings page though?

**Comment by LonwoLonwo** [comment] 2023-03-15 09:13
Only by the "navigator" word 

![2023-03-15 12_13_09-Preferences](https://user-images.githubusercontent.com/45152336/225262190-da4f0cf4-5992-4877-aa1e-e4b3f35b990e.png)

**Comment by LonwoLonwo** [comment] 2023-03-15 09:15
We discussed all available filters for Teradata schemas (databases) here.
So I'm closing this ticket.

**Closed by LonwoLonwo** 2023-03-15 09:15 UTC
Labels: feature request, x:teradata, wait for response, xf:filters
