### ISSUE TITLE
commented out where condition results in all columns being read-only

### ISSUE THREAD

**Issue by MtSuperDave** [dbeaver/dbeaver#21390] opened 2023-09-29 16:58 UTC
### Description

SELECT
*
FROM
	SOME_TABLE
where COLA = "2024"	
and COLB = 17644
\# and COLC = 'cat'

Although the last "and condition" is ignored in the results delivered, all columns will be marked read-only

### DBeaver Version

community edition 23.0.4

### Operating System

macOs  Ventura 13.4.1

### Database and driver

MySQL 8.0.22
Driver for MySQL 8 and later

### Steps to reproduce

run a query with a commented out condition of the where clause
try to edit the results
all of the columns are marked read-only

**Comment by LonwoLonwo** [comment] 2023-10-02 08:37
Thanks for the report @MtSuperDave 

This is duplicate of https://github.com/dbeaver/dbeaver/issues/19188

So, I'm closing this issue. And I will add this case to the original ticket.

**Closed as completed by LonwoLonwo** 2023-10-02 08:37 UTC
Labels: duplicate, xf:sql editor
