### ISSUE TITLE
Azure - MSSQL - Unable to switch DB

### ISSUE THREAD

**Issue by rbharathkumar** [dbeaver/dbeaver#8477] opened 2020-04-18 02:29 UTC
Dear All,
I am trying to use DBeaver to connect to the SQL Server Database on Azure.
DBeaver automatically downloaded the necessary drivers and the connection was successful, but the connection only connects to the master database. I am unable to switch to any of the other Databases. It either hangs or gives me a "Graphic is disposed" error message. I am also not able to use the fully qualified query option i.e. db.schema.tablename option. Getting an error message for that as well.

I already found a couple of similar issues in Github, all of them in closed state and none of them with any solutions. Only solution provided was to create a separate connection for each of the databases. I feel that would mean creating way too many connections.

Please note currently I am able to query using Azure Data Studio without any issues.
Kindly help.

**Comment by serge-rider** [comment] 2020-04-20 12:22
Perhaps you need to upgrade to the most recent dbeaver version (problem with "Graphic disposed" was fixed in 7.0.3).
Can you specify target database name in connection settings (not `master`)?
Azure SQL Server doesn't support active database change as well as cross-database queries. It has nothing to do with dbeaver.

**Comment by rbharathkumar** [comment] 2020-04-22 05:55
Hi @serge-rider , thank you very much for your response.
You are correct, I do not get the Graphic Disposed error anymore when I try to switch databases...but the databases do not change. But as you said it has to do with Azure DB not supporting and not particularly an issue with DBeaver. I wonder how Azure Data Studio and SSMS do it though..

Anyways this works for me for now as nothing beats the other features that DBeaver provides. Appreciate your work and the time taken to respond to my question. All the best (y)

**Comment by andreasnikiforosgeorgiadis** [comment] 2020-04-30 22:25
Hello.

An update on this.

Best regards


#### Describe the problem you're observing:
I get a "Graphic is disposed error" when I try to alter connection settings.


#### Steps to reproduce, if exist:
1. Being on the Database Navigator, I right-click at the desired connection and I select "Connect".
2. I right-click again and I select "Edit Connection".
3. The -Connection "xxx" configuration- window appears with "Connection settings" selected.
4. I select "General" (beneath "Connection settings").
5. I select "Connection settings" again.
6. A window titled "Page switch" appears with the following Error:

Error switching active page
Reason:
Graphic is disposed

7. Whatever option I click on next "Connection settings", "General", Initialization" etc. the same error occurs and the right hand display does not change its contents.

Please note that in I don't experience the same problem with the application from Windows Store (CE 7.0.0).


#### System information: 
- OS Name: Microsoft Windows 10 Enterprise
  OS Version: 10.0.17763 N/A Build 17763
- DBeaver CE 7.0.3 (portable x64)
- Additional extensions: N/A


#### Connection specification:
- Adaptive Server Enterprise/12.5.4
- com.sybase.jdbc4.jdbc.SybDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No


. . . _ _ _ . . .

![Connection settings error](https://user-images.githubusercontent.com/60822998/80763525-61ebbe80-8b47-11ea-95a9-962b08afd3fa.png)
[.log](https://github.com/dbeaver/dbeaver/files/4561635/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4561636/dbeaver-debug.log)

**Comment by uslss** [comment] 2020-07-22 21:43
is it still actual?

**Comment by andreasnikiforosgeorgiadis** [comment] 2020-07-25 17:21
> 
> 
> is it still actual?

Hello uslss. No, it's not. I performed the same actions using ce-7.1.3.zip and the problem does not appear anymore.

Regards

**Comment by andreasnikiforosgeorgiadis** [comment] 2020-07-25 17:29
Hello.

 

I posted a replay/comment on this on GitHub. The problem is fixed. I am not yet familiar with how things work regarding replies on GitHub so, I am replying to this e-mail also, in case you didn’t receive a notification for my reply/comment due to misuse.

 

 

Regards

**Closed** 2020-08-07 13:45 UTC
Labels: question, wait for response, x:mssql
