### ISSUE TITLE
Alt-X No Longer Reads @set parameters

### ISSUE THREAD

**Issue by drawnfallow** [dbeaver/dbeaver#6978] opened 2019-10-14 12:51 UTC
### System information: 
- win10 ent 1803 - 17134.345
- 6.2.2

#### Connection specification:
- MapR Drill
- Apache Drill JDBC Driver 1.16.0

#### Describe the problem you're observing:
alt-x does not read @set parameters in a script

#### Steps to reproduce, if exist:
@set send_date = '2019-01-01'

SELECT *
FROM db.warehouse
WHERE sent_date = :send_date

**Comment by uslss** [comment] 2019-10-15 13:30
Hi @drawnfallow ,
it seems issue is duplicate of #6969 that is already fixed in EA version. 
You could check it here https://dbeaver.io/files/ea/

**Closed** 2019-10-17 11:14 UTC
Labels: bug, duplicate
