### ISSUE TITLE
Dbeaver with Bitvise tunnelier

### ISSUE THREAD

**Issue by Ian-VI** [dbeaver/dbeaver#7607] opened 2020-01-12 14:09 UTC
#### System information: 
- Operating system (distribution) and version: Windows 7
- DBeaver version 5.0.4.

#### Connection specification:
- Database: mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
I used Dbeaver for quite some time with my hosting, connecting to SSH server (I input server name, user, password for SSH server and it all worked fine)
Since yesterday I cannot login anymore (tunnel error). They gave me a new SSH user, told me to install Bitvise tunnelier and sent me a configuration file. Bitvise actually connects to their server, it all seems fine, but I don't know how to connect dbeaver to the database. They gave me no password for the new user, so I cannot login via SSH. I guess I have to set it up to connect via Bitvise but I don't know how to do this. Do you have any suggestion, documentation, or can anyone tell me how to do this? Thanks to those willing to help. Ian

**Comment by serge-rider** [comment] 2020-01-12 14:57
Please write what exactly error do you see. 
Also debug log would be very helpful to localize the problem (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by Ian-VI** [comment] 2020-01-12 20:16
Hello Serge, thanks for your reply.
Sorry, probably I didn't explain well. The error was with the previous SSH user which has been abandoned anyway so that matter is closed.
My problem with the new SSH user is that I don't have a password to input in the SSH page of Dbeaver, as (I suppose they have a safer version of SSH) they sent me a configuration file with the password encrypted in it, a .bscp file to be used with Bitvise tunnelier.
When I uploaded the file in this program, it worked, so I see I am logged to the server via SSH, but I don't know how to tell Dbeaver to use that tunnel.
Hope I could explain better.

**Comment by serge-rider** [comment] 2020-01-13 10:33
Probably it is a duplicate of #7564 

Please test it in the Early Access version (https://dbeaver.io/files/ea)

**Closed** 2020-01-14 08:37 UTC
Labels: bug, duplicate
