### ISSUE TITLE
Filter values list does not contain all values

### ISSUE THREAD

**Issue by ptarant** [dbeaver/dbeaver#17242] opened 2022-08-03 07:19 UTC
### Description

percona table, size 12M, 164K records, trying to filter Int column. After opening the filter window I entered the desired value I want to retrieve. The value seems not to be present in the table according to the filter suggested values, which is not the case.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/17988931/182547864-9585abd0-b1a3-4ee4-bcb0-6002f6919cdd.png)

### DBeaver Version

Community 22.1.3

### Operating System

Windows 10

**Comment by uslss** [comment] 2022-08-03 09:08
thanks for the report

**Comment by Destrolaric** [comment] 2022-11-03 08:40
@ptarant, Hi. Can you tell me what DB was used?

**Comment by E1izabeth** [comment] 2022-11-03 08:46
Looks like a duplicate of #3977

**Comment by ptarant** [comment] 2022-11-03 10:11
@Destrolaric : db mysql/percona flavour. 
@E1izabeth : not likely, it happened at quite simple tables, not views or queries. I did not notice this behaviour at primary indexes, just at regular fields or foreign keys.

**Comment by Destrolaric** [comment] 2022-11-03 10:12
@ptarant Thank you for your response.

**Comment by ShadelessFox** [comment] 2022-11-10 18:22
Hello @ptarant,

Is the issue actual for you? We've changed the way filters work for numeric types. Previously, it was equal to `>= X`, not it's `= X`.

![image](https://user-images.githubusercontent.com/35821147/201175998-6db03a51-a447-4e08-92d8-f79d3c3793fb.png)

**Comment by E1izabeth** [comment] 2023-01-26 13:29
There is no update on this issue for a long time, so I'm closing it. Please let me know if the issue is still actual for you for the latest DBeaver version.

**Comment by ptarant** [comment] 2023-01-27 20:14
Sorry, notification mail went to spam. The issue is still there.
Filter by value at non-primary key column
Enter the desired EXISTING value
The value is not suggested for entry, the values suggested are BIGGER than the requested value

Using the latest dBeaver, Version 22.3.3.202301211053

On top of that, in the list of values are even such values which do not exist in the data column of the filtered table - seems the system selects possible items from the foreign key table, not from the table the selection is requested from.

![image](https://user-images.githubusercontent.com/17988931/215188254-4aa091e4-f4f2-4c69-b703-42caa2a43e03.png)

**Comment by ShadelessFox** [comment] 2023-03-09 16:40
> On top of that, in the list of values are even such values which do not exist in the data column of the filtered table - seems the system selects possible items from the foreign key table, not from the table the selection is requested from.

You're right. DBeaver shows values from the referenced "dictionary" table. This is an expected behavior.

I'm still unable to reproduce your issue.

1. Can you please provide a minimal reproducible example? For example, an SQL script for creating two tables with sample data. It would be really handy.
1. Are you sure that value is present there? Perhaps the foreign key constraint was violated and the value was removed from the referenced table?

**Comment by E1izabeth** [comment] 2023-04-10 15:58
It's been a long time since no update here. Let me know, if the issue still actual, and provide additional information to the questions being asked.

**Comment by ptarant** [comment] 2023-04-11 02:41
the problem is still present. I tried to construct a reproducible test pattern but without success so far. The tables / keys involved should be non-trivial to induce the mentioned behavior. I cannot publish the real data as it involves personally related information.

**Comment by Destrolaric** [comment] 2023-04-13 12:37
@ptarant DDL of the table doesn't usually contain the table data. You could share without exposing any personal information. If it is possible, it will allow us to look into the issue property.

**Comment by E1izabeth** [comment] 2023-05-08 17:33
It's been a while since no update here. If the issue is still actual, please let me know and provide table DDL (`create table` statement) so we can reproduce it.

**Closed as not planned by E1izabeth** 2023-05-08 17:33 UTC
Labels: enhancement, can't reproduce, wait for response, sp:3, xf:filters, xp:normal

**Comment by Ra5CZ** [comment] 2023-09-12 06:34
I think the problem is searching in a column that has a foreign key. It's looking in Description instead of Value. Is there somewhere to turn this off? I suppose that would solve both my and the author's problem. I think the primary search should be in Value.
