### ISSUE TITLE
dbeaver ce 6.2.2 closes unexpectedly when posting data edited in the grid (PG db)

### ISSUE THREAD

**Issue by gogosofta** [dbeaver/dbeaver#6975] opened 2019-10-14 07:43 UTC
#### System information: 
- win10 pro
- DBeaver CE 6.2.2
- no additional extensions

#### Connection specification:
- Postgresql 11+
- PostgreSQL standard driver 42.2.1
- no tunnels/proxies used 

#### Describe the problem you're observing:
Pressing Ctrl+S after editing data values in the grid, resulted by a select from a single table, causes DBeaver to close without prompt or confirmation.

#### Steps to reproduce, if exist:
Observed while editing values for diverse types.

#### Include any warning/errors/backtraces from the logs
The log says:
The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
and nothing is logged from at the shutdown time.

Here's the java fatal log file:
[hs_err_pid13244.log](https://github.com/dbeaver/dbeaver/files/3723474/hs_err_pid13244.log)

The above issue is not observed in DBeaver ce 6.2.1.

**Comment by serge-rider** [comment] 2019-10-14 09:49
Duplicate of #6928
Just re-download 6.2. from dbeaver.io

**Closed by serge-rider** 2019-10-14 09:49 UTC
Labels: bug, duplicate
