### ISSUE TITLE
Query result: column aliases ignored when copied as CSV

### ISSUE THREAD

**Issue by davidespagnoli** [dbeaver/dbeaver#18946] opened 2023-02-03 16:00 UTC
### Description

Trying to copy the result of a query with more than 1 result column alias, those aliases are ignored and the original column names are pasted instead 

### DBeaver Version

Community Edition 22.3.3

### Operating System

Windows 11

### Database and driver

MariaDB 10.5.16

### Steps to reproduce

execute query "SELECT t.ID AS Alias1, t.Description AS Alias2 FROM mytable t"
select all the results clicking the top-left cell in the results section (note that the aliases are correctly displayed there)
right-click "Advanced Copy"->Copy as CSV
Paste in Excel/LibreOffice Calc/NotePad: the first row will be "ID" - "Description" instead of "Alias1" - "Alias2"

**Comment by arhayka** [comment] 2023-02-09 14:44
Can you please provide footage showing your issue? Thank you.

**Comment by juan-salazar** [comment] 2023-02-28 19:17
"Copy as JSON" too.

Just make a query with aliases in columns names (I do it with MySQL connection), select all results in the Grid View, then select "Copy as JSON" in "Advanced Copy" in the context menu when right click over results selected. Paste in a text editor and you will see original column names, no the alias wrote in the SELECT query

I some version we lose this feature.

I use Linux (Ubuntu version 20.04) system

**Comment by davidespagnoli** [comment] 2023-03-06 14:19
@arhayka the "steps to reproduce" are detailed above, do you really need a footage?

**Comment by E1izabeth** [comment] 2023-03-09 14:28
Does it still reproducible on the latest DBeaver version (23.0.0)?

**Comment by E1izabeth** [comment] 2023-04-14 18:05
It's been a long time since no update here. Please let me know if the issue still actual and can be reproduced on the latest DBeaver version.

**Comment by kcbaltz** [comment] 2023-06-02 20:33
I'm able to reproduce this issue with Version 23.0.3.202304240630  .  Can this be reopened or do you need a fresh issue created? 

I'm on Community edition using MariaDB Driver 2.5.0

**Comment by E1izabeth** [comment] 2023-06-02 20:35
Thanks.
No need to create another one issue.

**Comment by E1izabeth** [comment] 2023-06-02 20:35
@kcbaltz could you provide an example please?

**Comment by E1izabeth** [comment] 2023-06-02 20:36
Is it the same as in the issue description or some other?

**Comment by kcbaltz** [comment] 2023-06-02 20:44
My steps are this: 

Query: 
SELECT cntry_a3_cd AS code3, cntry_a2_cd AS code2, cntry_nm AS country_name 
FROM countries

Advanced Copy as HTML result pasted here (Note `<tr><th>cntry_a3_cd</th><th>cntry_a2_cd</th>` instead of `<tr><th>code3</th><th>code2</th>`

```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/><style>
table {border: medium solid #6495ed;border-collapse: collapse;width: 100%;} th{font-family: monospace;border: thin solid #6495ed;padding: 5px;background-color: #D0E3FA;}td{font-family: sans-serif;border: thin solid #6495ed;padding: 5px;text-align: center;}.odd{background:#e8edff;}img{padding:5px; border:solid; border-color: #dddddd #aaaaaa #aaaaaa #dddddd; border-width: 1px 2px 2px 1px; background-color:white;}</style>
</head>
<body>
<table><tr><th colspan="3">SELECT cntry_a3_cd AS code3, cntry_a2_cd AS code2, cntry_nm AS country_name <br>FROM countries<br></th></tr><tr><th>cntry_a3_cd</th><th>cntry_a2_cd</th><th>cntry_nm</th></tr><tr class="odd"><td>ABW</td><td>AW</td><td>Aruba</td></tr>
<tr><td>AFG</td><td>AF</td><td>Afghanistan</td></tr>
<tr class="odd"><td>AGO</td><td>AO</td><td>Angola</td></tr>
<tr><td>AIA</td><td>AI</td><td>Anguilla</td></tr>
<tr class="odd"><td>ALB</td><td>AL</td><td>Albania</td></tr>
<tr><td>AND</td><td>AD</td><td>Andorra</td></tr>
<tr class="odd"><td>ARE</td><td>AE</td><td>United Arab Emirates</td></tr>
<tr><td>ARG</td><td>AR</td><td>Argentina</td></tr>
<tr class="odd"><td>ARM</td><td>AM</td><td>Armenia</td></tr>
<tr><td>ATG</td><td>AG</td><td>Antigua and Barbuda</td></tr>
</table></body></html>

**Comment by kcbaltz** [comment] 2023-06-02 20:44
I believe this is the same issue, only I was using HTML instead of CSV, but I believe all the Advance Copies are affected

**Comment by kcbaltz** [comment] 2023-06-02 20:45
Results with JSON: 
```
{
"SELECT cntry_a3_cd AS code3, cntry_a2_cd AS code2, cntry_nm AS country_name \nFROM countries\n": [
	{
		"cntry_a3_cd" : "ABW",
		"cntry_a2_cd" : "AW",
		"cntry_nm" : "Aruba"
	},
	{
		"cntry_a3_cd" : "AFG",
		"cntry_a2_cd" : "AF",
		"cntry_nm" : "Afghanistan"
	},
	{
		"cntry_a3_cd" : "AGO",
		"cntry_a2_cd" : "AO",
		"cntry_nm" : "Angola"
	},
	{
		"cntry_a3_cd" : "AIA",
		"cntry_a2_cd" : "AI",
		"cntry_nm" : "Anguilla"
	},
	{
		"cntry_a3_cd" : "ALB",
		"cntry_a2_cd" : "AL",
		"cntry_nm" : "Albania"
	},
	{
		"cntry_a3_cd" : "AND",
		"cntry_a2_cd" : "AD",
		"cntry_nm" : "Andorra"
	},
	{
		"cntry_a3_cd" : "ARE",
		"cntry_a2_cd" : "AE",
		"cntry_nm" : "United Arab Emirates"
	},
	{
		"cntry_a3_cd" : "ARG",
		"cntry_a2_cd" : "AR",
		"cntry_nm" : "Argentina"
	},
	{
		"cntry_a3_cd" : "ARM",
		"cntry_a2_cd" : "AM",
		"cntry_nm" : "Armenia"
	},
	{
		"cntry_a3_cd" : "ATG",
		"cntry_a2_cd" : "AG",
		"cntry_nm" : "Antigua and Barbuda"
	}
]}

```

**Comment by owendw1** [comment] 2023-10-17 00:00
If it is of help, I can also provide details for recreating the problem, which remains in DBeaver 23.2.2:

1) Run query

> SELECT resources.name AS resource_title
> FROM resources;

2) Result window in DBeaver shows column name is "resource_title" as expected

3) Right-click the top-left corner of the result window and click Advanced Copy -> Copy as TXT, then paste in a text editor. The the column is called "name" instead of the alias "resource_title":

|name          |
|----------------|
|Resource 1 |
|Resource 2 |
|Resource 3 |

The same occurs with Copy as CSV, which I also use often.

**Comment by E1izabeth** [comment] 2023-10-17 11:33
Thanks

**Comment by DG-WORK** [comment] 2023-12-12 13:28
Getting the same thing here too. 

select 
col1, 
col2 as NEW_COL_NAME_FOR_COL2, 
col3 
from table1

In DBeaver results panel this displays this accurately: col1, NEW_COL_NAME_FOR_COL2, col3
Advanced copy commands return the following however: col1, col2, col3

**Comment by DG-WORK** [comment] 2024-05-30 12:30
Has there been an development with a fix for this? Getting the same still

**Comment by E1izabeth** [comment] 2024-05-30 13:54
We haven't fixed it yet.
You can vote for the issue with 👍 under the issue description to promote it to a higher priority.

**Comment by dstivanov** [comment] 2024-07-27 21:08
I face the same for the "Copy as TXT" in Dbeaver with the recent version of the repo, i.e. commit 0d326aa112032931ec134156d89caa757fa64c13 . 

I set up the development environment on my machine and run the debug mode of Dbeaver and even manage to find a bit more context:
* When the transfer is finished in [StreamTransferConsumer#finishTransfer](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/StreamTransferConsumer.java#L637-L638) the `outputBuffer` does not have the aliases present;
* On the other side, when using the `Dbeaver Sample Database` (SQLite) that comes out of the box with the debug - the aliases are there.

I am planning to continue investigating this issue as I am now able to reproduce and debug it and will post my progress here.

**Comment by dstivanov** [comment] 2024-07-28 22:38
Cheers with an MR that I have tested and works like a charm. It took some time debugging, but I am pleased with the results. I hope it will get to production soon, because I use this functionality on a daily basis in JIRA. There the TXT tables (exported with `Advanced Copy` -> `Copy as TXT`) are displayed directly in the JIRA comments as tables. Evidence from the DB, as always.

**Comment by dstivanov** [comment] 2024-07-30 21:57
@MashaKorax Possible duplicates of this issue are:
* https://github.com/dbeaver/dbeaver/issues/34963
* https://github.com/dbeaver/dbeaver/issues/34050

I commented in them with a cc to the authors and I strongly recommend to ask them to retest as soon as this one is fixed with https://github.com/dbeaver/dbeaver/pull/35007

What do you think ?

**Comment by E1izabeth** [comment] 2024-07-31 08:02
Hi, @dstivanov! Thank you for your effort. Indeed the issues you mention looks very similar. I'll ask our QA to check those issues too and close, if they're solved.
At the moment, we have passed your pull request to our quality assurance team for testing. While we are waiting for them to complete the testing, the fix will not be included in the product.

**Closed as completed** 2024-08-07 03:34 UTC
Labels: xf:datatransfer, xp:normal, external
