### ISSUE TITLE
Must declare the scalar variable SQL SERVER 2019

### ISSUE THREAD

**Issue by oscarpt** [dbeaver/dbeaver#21916] opened 2023-11-20 17:15 UTC
### Description

There are problems with the input parameters of a store procedure, they are not recognized in the body of the store

### DBeaver Version

Community version  23.2.5

### Operating System

windows 10

### Database and driver

SQL server 2019

### Steps to reproduce

It is when creating a store procedure

**Comment by E1izabeth** [comment] 2023-11-20 18:02
Please provide minimal steps to reproduce the issue.

**Comment by E1izabeth** [comment] 2023-11-21 13:23
Closing as a duplicate of #21898

**Closed as not planned by E1izabeth** 2023-11-21 13:23 UTC
Labels: duplicate, x:mssql
