### ISSUE TITLE
upgrades remove xmx and xms settings

### ISSUE THREAD

**Issue by DerPeterA** [dbeaver/dbeaver#35685] opened 2024-09-23 11:00 UTC
### Description

every time I upgrade dbeaver, my xms and xmx settings are lost. they should not be lost.

### DBeaver Version

latest

**Comment by E1izabeth** [comment] 2024-09-24 06:01
Thank you for report.
I'm closing this issue as a duplicate of #7727 #35391 #7546

**Closed as not planned by E1izabeth** 2024-09-24 06:01 UTC
Labels: duplicate

**Comment by DerPeterA** [comment] 2024-10-01 09:33
Hi @E1izabeth - thank you for the links to the 3 other items. But unfortunately I do not understand - how is this solved in the other items? They put a second dbeaver.ini into their home directory? Is that what I am supposed to do? Merci!

**Comment by E1izabeth** [comment] 2024-10-01 09:35
The issue isn't solved. All linked issues are open. I closed this one to avoid duplication, because it's about the same as mentioned issues
