### ISSUE TITLE
6.3.2 [PostgreSQL] Unterminated dollar quote started

### ISSUE THREAD

**Issue by NickKush** [dbeaver/dbeaver#7654] opened 2020-01-16 10:32 UTC
#### System information: 
- OS Ubuntu 18.04
- DBeaver version - 6.3.2
- PostreSQL 11

#### Error

When I execute SQL script via "Alt - X" I occurred this problem.

```
Error occurred during SQL script execution

SQL Error [42601]: Unterminated dollar quote started at position 73 in SQL CREATE OR REPLACE FUNCTION bug_report() RETURNS void LANGUAGE plpgsql AS $$
```

[bug_sql.txt](https://github.com/dbeaver/dbeaver/files/4070605/bug_sql.txt)

I think the problem is how parser works with "with - end" block. 
If I delete "end" word in line 21, or only have one "with" block, it works fine.
If I have only a function, without select block outside, everything works fine.

Problem occurred after 6.3.2 when $$ strings parser was "fixed" 

Best Regards,
NickKush

Edit: 
Related.. sorry for dublicate
#7649 
#7566

**Comment by serge-rider** [comment] 2020-01-16 11:17
Seems to be duplicate of #7511 (the problem with wrong evaluation of `begin`/`end` keywords).
Please check the fix in Early Access version.

**Closed by serge-rider** 2020-01-16 11:17 UTC
Labels: bug, duplicate
