### ISSUE TITLE
dbeaver don't export the primary Key and Foreing Key when you execute a ExportData in database format ( Sap Hana)

### ISSUE THREAD

**Issue by hdkcreative** [dbeaver/dbeaver#34526] opened 2024-06-27 00:37 UTC
### Description

hi !

we have this issue :

this is the definition of our table in our SOURCE database

```
CREATE COLUMN TABLE "CORPORATE_TEST"."USER_ROL" ("ID" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
"ID_USER" INTEGER CS_INT,
"ID_ROL" INTEGER CS_INT,
"ACTIVE" TINYINT CS_INT,
"CREATED_AT" LONGDATE CS_LONGDATE,
"UPDATED_AT" LONGDATE CS_LONGDATE,
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE ;
```
when we try to export data : 
![image](https://github.com/dbeaver/dbeaver/assets/18191896/5dc566f6-eb7f-48ed-b49a-e747ecfc657d)
![image](https://github.com/dbeaver/dbeaver/assets/18191896/1647180f-33a1-40a3-8403-2079245c027d)
![image](https://github.com/dbeaver/dbeaver/assets/18191896/82ee4627-591b-4e06-a942-e64fa1665ce2)

the result is this:  

```
CREATE ROW TABLE "SBO_GASA"."USER_ROL" ( "ID" INT CS_INT NOT NULL,
"ID_USER" INT CS_INT,
"ID_ROL" INT CS_INT,
"ACTIVE" TINYINT CS_INT,
"CREATED_AT" LONGDATE CS_LONGDATE,
"UPDATED_AT" LONGDATE CS_LONGDATE );

```

is a code diferent totally to the original.

Has it happened to anyone? we have missing any configuration? Does anyone have more information please?

### DBeaver Version

24.1.0.202406091028

### Operating System

Windows 11

### Database and driver

1. Database name and version: SAP HANA
2. Driver name and version: HDB 2.19.16-039fb8926eb8d5b36a556bb703a047643a457642  JDBC

**Comment by LonwoLonwo** [comment] 2024-07-01 08:35
Hello @hdkcreative 

Data transfer doesn't copy the full table structure.
Generally, it is impossible as different databases have different metadata objects (column structure, constraints, triggers, etc).

Also, even if you transfer between the same database types (e.g., HANA) we don't create all constraints because some of them may block transfer itself. Some others may affect other database objects (e.g., triggers may perform inserts into other tables).

So, for now, if you need to copy the table structure completely, you need to do it before the data transfer and then import it into the existing table).

This is a duplicate of: https://github.com/dbeaver/dbeaver/issues/21516

**Comment by LonwoLonwo** [comment] 2024-07-01 08:37
You can vote with the 👍 emoji on the original ticket. And I'm closing this one as a duplicate.

**Closed as completed by LonwoLonwo** 2024-07-01 08:37 UTC
Labels: duplicate, xf:datatransfer

**Comment by hdkcreative** [comment] 2024-07-02 16:34
Thank you for the information @LonwoLonwo !  👍
