### ISSUE TITLE
Error downloading driver libraries.

### ISSUE THREAD

**Issue by samkit-jain** [dbeaver/dbeaver#20753] opened 2023-08-01 04:26 UTC
### Description

Getting the error "Error resolving dependencies. Index 0 out of bounds for length 0." when opening any connection. This is happening ever since I updated the DBeaver version.

### DBeaver Version

CE 23.1.3.202307231901

### Operating System

Ubuntu 22.04

### Database and driver

Didn't test on others but happening for PostgreSQL, MySQL and MariaDB.

### Steps to reproduce

Just open any connection, it will open the dialog to download drivers and then the following message will appear
![image](https://github.com/dbeaver/dbeaver/assets/15127115/a83e38ba-d8a6-4f01-8d6d-fddedf2de2c5)
![image](https://github.com/dbeaver/dbeaver/assets/15127115/461796ba-7d29-45e8-ac60-bc46372618d0)

### Additional context

Installed via Snap.

**Comment by LonwoLonwo** [comment] 2023-08-01 05:32
Hello @samkit-jain 
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by samkit-jain** [comment] 2023-08-01 06:25
@LonwoLonwo The steps at the website don't yield any results. Perhaps, the log files are stored in a different directory for snap based Ubuntu installations. I get the following error
```bash
$ cd $XDG_DATA_HOME/DBeaverData/workspace6/.metadata
bash: cd: /DBeaverData/workspace6/.metadata: No such file or directory
```

However, I exported the logs from the Error tab view and they are [here](https://github.com/dbeaver/dbeaver/files/12225235/dbeaver.log). The logs have a warning that says
```
Can't create drivers folder '/home/samkitjain/snap/dbeaver-ce/241/.local/share/DBeaverData/drivers'
```
and the warning is correct as there is no folder named `241` at the path `/home/samkitjain/snap/dbeaver-ce/`. I have folders `243`, `246` and `current` there. I tried creating the folder 241 but it had no impact.

**Comment by ShadelessFox** [comment] 2023-08-03 12:49
Hello @samkit-jain,

Try looking for logs under the `current` directory. or simply use `find` on `/home/samkitjain/snap/dbeaver-ce` to find all logs

**Comment by samkit-jain** [comment] 2023-08-03 13:21
Hi @ShadelessFox Please see attached the log files under the `current` directory 
[dbeaver-logs.zip](https://github.com/dbeaver/dbeaver/files/12251235/dbeaver-logs.zip)

**Comment by ShadelessFox** [comment] 2023-08-03 13:28
I was expecting to find something unusual, but it looks like it was caused by inability to create the `drivers` folder, as noted before.

Can you try specifying a different directory for storing driver files?

![image](https://github.com/dbeaver/dbeaver/assets/35821147/6f8c2696-b1e2-47cc-8228-ca27b644c22d)

I'm unfamiliar with snap, but you might need to somehow allow DBeaver package to access the specified directory.

**Comment by samkit-jain** [comment] 2023-08-04 08:00
Hi @ShadelessFox, changing the directory worked. But, why did it stop working suddenly in the latest version? I even checked the permissions of the folders and they are the same for all 3 folders.
```
drwxr-xr-x  6 samkitjain samkitjain 4096 Aug  1 11:54 ./
drwx------ 22 samkitjain samkitjain 4096 Jul 12 03:02 ../
drwxrwxr-x  2 samkitjain samkitjain 4096 Aug  1 11:54 241/
drwxr-xr-x  7 samkitjain samkitjain 4096 Jul 10 17:12 243/
drwxr-xr-x  8 samkitjain samkitjain 4096 Jul 31 17:09 246/
drwxr-xr-x  3 samkitjain samkitjain 4096 Apr 27  2022 common/
lrwxrwxrwx  1 samkitjain samkitjain    3 Jul 31 14:36 current -> 246/
```

**Comment by ShadelessFox** [comment] 2023-08-04 12:26
I asked my colleague, and they responded with the following:

These directories are old snap redactions. You might have accidentally changed the location the drivers stored in so it was remembered and used instead of the default location determined at runtime.

You can use `snap refresh dbeaver-ce` or perform a fresh install.

As the issue is resolved, I will close it now.

**Closed as completed by ShadelessFox** 2023-08-04 12:26 UTC
Labels: xo:linux, xf:snap

**Comment by drelolua** [comment] 2023-11-21 03:31
i just update the new version, and i got this issuse. windows11. cant solve it by many ways. finally, i switch to dbvisualizer.
when this issuse fixed, cue me pls.

**Comment by ShadelessFox** [comment] 2023-11-21 12:16
@drelolua please create a separate ticket and provide at least some information about your issue there.

**Comment by rudy-tao** [comment] 2023-11-22 02:27
> i just update the new version, and i got this issuse. windows11. cant solve it by many ways. finally, i switch to dbvisualizer. when this issuse fixed, cue me pls.

after I updated, I also encountered the same issue, mac m1, version: 23.2.5.

**Comment by b4shx0r** [comment] 2023-11-29 10:50
same problem here on ubuntu 22.04 updated the latest version via snap (Version 23.2.5.202311191730)

My workaround is to set the drivers download dir to tmp:

![Screenshot from 2023-11-29 12-02-55](https://github.com/dbeaver/dbeaver/assets/70095789/3825c164-3e9e-4683-9dba-3df6967d3426)

**Comment by Goldenbeef** [comment] 2023-12-05 01:46
我在 23.3.0.202312031432也遇到了相关问题
我的解决方法是 首选项-连接-驱动-Maven 将oss.sonatype.org仓库调整到最下面，再新增一个阿里的仓库到最上面
![image](https://github.com/dbeaver/dbeaver/assets/33057601/2b9213d9-c7a9-4eea-9499-55791704f742)

**Comment by lppjiau** [comment] 2023-12-06 06:40
> 我在 23.3.0.202312031432也遇到了相关问题 我的解决方法是 首选项-连接-驱动-Maven 将oss.sonatype.org仓库调整到最下面，再新增一个阿里的仓库到最上面 ![image](https://private-user-images.githubusercontent.com/33057601/287891038-2b9213d9-c7a9-4eea-9499-55791704f742.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDUwODAsIm5iZiI6MTcwMTg0NDc4MCwicGF0aCI6Ii8zMzA1NzYwMS8yODc4OTEwMzgtMmI5MjEzZDktYzdhOS00ZWVhLTk0OTktNTU3OTE3MDRmNzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA2Mzk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MzNmZmQ3ZDg1ZTgxZTRlNTI5ZTgwNDNmYjQwM2UwNzMxNGM3NDU5NGVhOTE0YjNiNWMwY2I5ZWJkNTIwMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmaIGALcwA_oNGd-XXvb3h09F6CBpcKUBcxMgGaxFP0)

感谢～ 有用！

**Comment by lppjiau** [comment] 2023-12-06 06:41
> 我在 23.3.0.202312031432也遇到了相关问题 我的解决方法是 首选项-连接-驱动-Maven 将oss.sonatype.org仓库调整到最下面，再新增一个阿里的仓库到最上面 ![image](https://private-user-images.githubusercontent.com/33057601/287891038-2b9213d9-c7a9-4eea-9499-55791704f742.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDUxMzksIm5iZiI6MTcwMTg0NDgzOSwicGF0aCI6Ii8zMzA1NzYwMS8yODc4OTEwMzgtMmI5MjEzZDktYzdhOS00ZWVhLTk0OTktNTU3OTE3MDRmNzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA2NDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MGQ2ZGZmNGQzMjc5MmYxNzZmMmNlNzM0YmYwOTVkMGY0NGQxZGEzNjk1NjAzMTc2NDAxMWQ2ZWJlNmZjODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a5huwG0JjG3BvmgETfh6xjLAWEp9OY3Fc2QexMuwAbU)

是有用的，非常感谢！

**Comment by neto-developer** [comment] 2023-12-08 14:40
Same issue here

![image](https://github.com/dbeaver/dbeaver/assets/844693/9b3eae84-dd63-45ba-82c6-ed65597d8671)

**Comment by ShadelessFox** [comment] 2023-12-08 15:00
Hello @neto-developer,

Please create a new issue and provide log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

Thank you.
