### ISSUE TITLE
[Oralce] Materialized view is unnecessarily shown as a common table

### ISSUE THREAD

**Issue by Bitros** [dbeaver/dbeaver#16656] opened 2022-06-01 06:33 UTC
#### System information: 
- Windows 11
- DBeaver CE Version 22.0.5.202205220912

#### Connection specification:
- Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

#### Steps to reproduce, if exist:
`CREATE MATERIALIZED VIEW TEST_MV AS SELECT 1 FROM DUAL;` refresh and you can see both materialized view and common table.

![image](https://user-images.githubusercontent.com/9913942/171342009-7d0e2140-261e-4c06-87dc-f473fba32de0.png)

Is it a bug or new feature.

**Comment by LonwoLonwo** [comment] 2022-06-01 08:09
Yes, this is a well-known problem in DBeaver.

But the [documentation](https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_6002.htm) says:

`When you create a materialized view, Oracle Database creates one internal table and at least one index, and may create one view, all in the schema of the materialized view. Oracle Database uses these objects to maintain the materialized view data. You must have the privileges necessary to create these objects.`

So what can we do?

**Comment by LonwoLonwo** [comment] 2022-06-01 08:10
This is our metadata reading statement for Oracle:

![2022-06-01 10_59_34-DBeaver Ultimate 22 1 0 - _orcl_Script-161](https://user-images.githubusercontent.com/45152336/171358336-9dde8829-9d80-45cd-9b5f-ef72eedb79d0.png)

**Comment by Bitros** [comment] 2022-06-01 09:27
Thanks for your response and good to know this Oracle materialized view trick. As you commented above, it is not a critical bug but we could exclude the table created by MV statement in table directory. It may complicate the table listing logic and get less improvement. Fix it or not is OK for me.

**Comment by LonwoLonwo** [comment] 2022-06-01 12:51
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/12537

**Closed as completed by LonwoLonwo** 2022-06-01 12:51 UTC
Labels: x:oracle, xf:metadata
