### ISSUE TITLE
Received fatal alert: handshake_failure after changing MySQL RDS instance CA to rds-ca-rsa4096-g1

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#21332] opened 2023-09-26 19:01 UTC
### Description

After changing RDS Instance Certificate authority from "rds-ca-2019" to "rds-ca-rsa4096-g1"

Getting error on existing MySQL RDS connection which worked before:
```
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  Received fatal alert: handshake_failure
```

Connection SSL settings:

![image](https://github.com/dbeaver/dbeaver/assets/103036539/ab250832-e16d-4881-8f85-736ab2b21569)

### DBeaver Version

Community Edition Version 23.2.1.202309260508

### Operating System

Windows 10 64 bit

### Database and driver

MySQL 8.0.34

### Steps to reproduce

1. Create successfull connection to RDS MySQL instance v8.0.34 with Certificate authority "rds-ca-2019" using mentioned SSL settings. (pem file was downloaded from [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.RegionCertificates))
2. Change RDS Instance Certificate authority to "rds-ca-rsa4096-g1"
3. Test connection again

**Comment by diegoy** [comment] 2023-09-27 14:09
Hey, I have the same issue with PostgreSQL and I could workaround this problem by going to the `SSL` tab and change `SSL mode: allow`.

![image](https://github.com/dbeaver/dbeaver/assets/1043265/ac72da59-98db-4d39-b878-955c70cc5e00)


Perhaps you can achieve the same by unticking `Verify server certificate` on your side.

**Comment by yoni-yad2** [comment] 2023-09-27 14:24
Didn't help:
![image](https://github.com/dbeaver/dbeaver/assets/103036539/24866209-d8eb-43f7-8523-7a0cb03774ce)

**Comment by MashaKorax** [comment] 2023-09-28 13:30
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by yoni-yad2** [comment] 2023-09-28 13:40
Only relevant recent entry from .log:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2023-09-28 16:33:55.440
!MESSAGE Received fatal alert: handshake_failure
!STACK 0
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:347)
	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:191)
	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:101)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:369)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:205)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1433)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:237)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:250)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:269)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:456)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:123)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:107)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:98)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:93)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:151)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1278)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1117)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by LonwoLonwo** [comment] 2023-10-05 10:30
Could you please add this flag: `-Djavax.net.debug=all` to your Dbeaver .ini file and provide the full logs? Maybe we can find a reason in a full-log version.

**Comment by yoni-yad2** [comment] 2023-10-10 13:35
This is the latest log entry with `-Djavax.net.debug=all`:
```
!SESSION 2023-10-10 16:34:01.582 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\Yoni_Sade\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-10-10 16:34:08.242
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.eclipse.jface 2 0 2023-10-10 16:34:12.485
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-10 16:34:12.486
!MESSAGE A conflict occurred for CTRL+J:
Binding(CTRL+J,
	ParameterizedCommand(Command(org.eclipse.ui.edit.findIncremental,Incremental Find,
		Incremental find,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.findIncremental"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(CTRL+J,
	ParameterizedCommand(Command(org.jkiss.dbeaver.core.resultset.grid.gotoColumn,Go To Column,
		Jump to a specified column,
		Category(org.jkiss.dbeaver.core.rs,Result Set,Result Set Commands,true),
		WorkbenchHandlerServiceHandler("org.jkiss.dbeaver.core.resultset.grid.gotoColumn"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.jkiss.dbeaver.ui.context.resultset,,,system)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-10-10 16:34:24.354
!MESSAGE Received fatal alert: handshake_failure
!STACK 0
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:347)
	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:191)
	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:101)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:369)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:205)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1433)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:246)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:259)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:278)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:456)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:123)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:107)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:98)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:93)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:151)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1280)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1117)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Destrolaric** [comment] 2023-10-19 13:38
@yoni-yad2 Could you try to connect without `verify server certificate`?

**Comment by yoni-yad2** [comment] 2023-10-19 14:11
Tried that.
Same error.

**Comment by ddatdt12** [comment] 2023-10-30 11:03
> [diegoy](/diegoy)
I already fixed problem by following his answer. Thanks a lot

**Comment by ecoms-ye** [comment] 2023-11-10 02:53
Hello, 

I got the same `Received fatal alert: handshake_failure` error when using SSH Tunnel, but everything is ok with pgAdmin and the same connection settings.

Here is the error log:

```
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:620)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:191)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
	at org.postgresql.Driver.makeConnection(Driver.java:434)
	at org.postgresql.Driver.access$100(Driver.java:61)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:344)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Destrolaric** [comment] 2023-12-01 10:54
Can't reproduce on Postgre and MySQL instances with mentioned certificate authority

**Comment by r-asiebert** [comment] 2023-12-22 00:40
I've just ran into the same issue with multiple RDS MySQL instances using the CA `rds-ca-ecc384-g1` (RDS MySQL 8.0.33).

I got some debug logs with `-Djavax.net.debug=all` in `dbeaver-debug.log`, here's a redacted version:
[2023-12-21 1600 dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13747124/2023-12-21.1600.dbeaver-debug.log)

I'm not fully versed in TLS negotiation let alone its Java implementation, but it seems to fail after reading just a few bytes from a "TLSv1.2 alert" reply just after sending its client handshake.
Could that be RDS explicitly rejecting the client because of a missing cipher/signature algorithms compatible with [that kind of CA](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.RegionCertificateAuthorities)? (`rds-ca-ecc384-g1` = _certificate authority with ECC 384 private key algorithm and SHA384 signing algorithm_)

Strangely, the same DBeaver connects just fine to _Aurora_ MySQL instances with the same CA (8.0.mysql_aurora.3.02.0).

(DBeaver 23.3.0, Java Corretto 21 – had the same error on Java 11)

**Comment by r-asiebert** [comment] 2023-12-22 02:02
This sent me into a wild goose chase, but I eventually found my issue: for some reason, my DBeaver connections had `enabledTLSProtocols` set to `TLSv1,TLSv1.1,TLSv1.2`.
(Setting in the connection configuration → sidebar _Connection Settings_ → tab _Driver Properties_ → appeared in _User Properties_ at the bottom for me).
As soon as I added 1.3 (recommendation: `TLSv1.2,TLSv1.3`), DBeaver succeeded to connect! ✅

I have no idea where my `enabledTLSProtocols` came from, I seem to have it on all my current connections. Default?

### Hypothesis
* RDS MySQL with the CA `rds-ca-ecc384-g1` allows applicable ciphers only on TLS 1.3 
  (at least in the default ciphers in Java 21).
  * OP @yoni-yad2: it's been a while but if you still have the issue, maybe enabling 1.3 will work with the `rds-ca-rsa4096-g1` CA?
* Aurora MySQL with the same CA does accept `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384` on TLS v1.2.

May be worth reporting this to AWS if we can confirm these; that's a somewhat confusing situation.

----
Troubleshooting notes that led me there:

re previous message: for comparison, I'm seeing the same `ClientHello` (different host & random) sent to those Auroras on the same CA, but the response is the expected handshake.
The Aurora `ServerHello` indicates it picks `"cipher suite" : "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384(0xC02C)"`, which is advertised in both `ClientHello`s.

My problem may be different from OP – I've found a number of application issues with the ECC CA (examples: [1](⁠https://stackoverflow.com/questions/77078130/springboot-hibernate-and-aws-rds-aurora-with-new-ca-rds-ca-ecc384-g1), [2](⁠https://github.com/npgsql/npgsql/issues/5314), [3](⁠https://www.reddit.com/r/aws/comments/175g29g/updated_rds_certificate_authority_ca_ca_was/) ) that were allegedly fixed with the RSA one that OP is already using.

I searched some more, also puzzled about the logs stating `Ignore unsupported cipher suite: TLS_AES_256_GCM_SHA384 for TLSv1.2`, which means they're not supported on 1.2, likely only 1.3. Seems unrelated, if that ECDHE one above works for Aurora?

Out of ideas, I've troubleshooted a dummy Java application, and its handshake to MySQL succeeded with `TLS_AES_256_GCM_SHA384`… …on TLS 1.3.
When running DBeaver, I'm only seeing 1.2 in the `ClientHello`:
```
    "supported_versions (43)": {
      "versions": [TLSv1.2]
    },
```
A dummy Java 11 app advertises both 1.2 and 1.3.

And hindsight being 20/20, that dummy app used the cipher exactly matching that `unsupported cipher ... for TLSv1.2` Java log from DBeaver… the rest is summarized at the top of this message.

**Closed as completed** 2024-01-03 14:21 UTC
Labels: x:mysql, environment, sp:1, xf:connection, xf:ssl

**Comment by r-asiebert** [comment] 2024-01-10 17:48
This change should help, cheers!
And a quick word of appreciation: beautiful version tracking here 🙂
