### ISSUE TITLE
Java.lang.NullPointer when importing data in Version 7.0.3

### ISSUE THREAD

**Issue by Dookie78** [dbeaver/dbeaver#8558] opened 2020-04-27 05:28 UTC
<!--
Thank you for reporting an issue.

*IMPORTANT* -  *before* creating a new issue please look around:
 - DBeaver documentation: https://github.com/dbeaver/dbeaver/wiki
 and
 - open issues in Github tracker: https://github.com/dbeaver/dbeaver/issues
  
If you cannot find a similar problem, then create a new issue. Short tips about new issues can be found here: https://github.com/dbeaver/dbeaver/wiki/Posting-issues

Please, do not create issue duplicates. If you find the same or similar issue, just add a comment or vote for this feature. It helps us to track the most popular requests and fix them faster.

when importing CSV data using version 7.0.3, the java.lang.NullPointer occurs

It works well in 7.0.1

**Comment by Dookie78** [comment] 2020-04-27 08:14
DBeaver version: 7.0.3
OS : Linux

when importing data from CSV to MySQL database, the Java.lang.NullPointer occurs. It worked well in Version 7.0.1.

**Comment by uslss** [comment] 2020-04-27 08:49
seems to be duplicate of #8520 
tickeet will be close das duplicate.
Anyway, thanks for the bug report

**Closed** 2020-04-27 08:49 UTC
Labels: bug, duplicate, wait for review
