### ISSUE TITLE
SQL semantic error foreground

### ISSUE THREAD

**Issue by apdma** [dbeaver/dbeaver#22456] opened 2024-01-15 07:19 UTC
### Description

How to disable semantic check?

In new version in DBeaver if I don't write SCHEMA and TABLE in UPPERCASE - all text highlight like error - it's very confusing.
![2024-01-15 10 17 33](https://github.com/dbeaver/dbeaver/assets/91953047/8b3757ec-593d-460d-a702-48425e564dbf)

### DBeaver Version

Version 23.3.2.202401072024

### Operating System

Windows 10

### Steps to reproduce

1) Open DBeaver
2) Connect to DB2/Postgres database
3) Write a query with lowercase schema and/or lowercase table
4) Add a WHERE condition with attribute

**Comment by E1izabeth** [comment] 2024-01-15 07:22
Thank you for bug report. It's a duplicate of #22385 
You can turn it off here
![image](https://github.com/dbeaver/dbeaver/assets/28875055/bf80edcb-fc10-4e92-aac9-6bac815fc1b5)

**Closed as not planned by E1izabeth** 2024-01-15 07:22 UTC
Labels: duplicate, xf:sql editor
