### ISSUE TITLE
Bind parameter is not remembered

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#14207] opened 2021-10-12 13:37 UTC
**Is your feature request related to a problem? Please describe.**
When I run query second time last value is not remembered
![image](https://user-images.githubusercontent.com/799021/136966381-8dc976fd-341a-4153-a8b3-47178ee390b4.png)

**Describe the solution you'd like**
Value should be remembered from first run

**Describe alternatives you've considered**

**Additional context**

**Comment by uslss** [comment] 2021-10-12 13:57
closed as a duplicate of #12217

**Closed as completed by uslss** 2021-10-12 13:57 UTC
Labels: duplicate

**Comment by KES777** [comment] 2021-10-12 15:28
ah, thank you. I try to find but without success
