### ISSUE TITLE
Drag and Drop of Field and Table names still broken (Ubuntu Linux)

### ISSUE THREAD

**Issue by klaymartens** [dbeaver/dbeaver#19916] opened 2023-05-09 05:53 UTC
### Description

Unable to drag and drop field and table names from database navigator to query editor.

### DBeaver Version

Community Edition 23.0.4

### Operating System

Ubuntu Linux

### Database and driver

Doesnt matter - behaviour is the same some on PostgreSQL, Ignite, MySQL and Oracle connections

### Steps to reproduce

1) Connect to whatever database
2) Open a new query editor
3) Drag a field or table name onto the query editor and attempt to drop

This has been a problem for several releases now - not 100% sure when it started cropping up......s

**Comment by klaymartens** [comment] 2023-05-09 06:10
Oh - forgot to add: I have confirmed that the "Enable Drag and Drop of Text" option in the preferences is checked. No idea what else might be blocking this....

**Comment by LonwoLonwo** [comment] 2023-05-09 08:51
Hello @klaymartens 

Looks like this is a duplicate of https://github.com/dbeaver/dbeaver/issues/18799

Could you please provide more info about your OS?

**Comment by klaymartens** [comment] 2023-05-09 10:03
Sure thing:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

Please let me know if you need more details?

**Comment by klaymartens** [comment] 2023-05-09 10:05
You are correct - it does look like a duplicate.

**Comment by LonwoLonwo** [comment] 2023-05-09 13:20
Thanks for the extra info. I'm closing this ticket as a duplicate.

**Closed as completed by LonwoLonwo** 2023-05-09 13:20 UTC
Labels: duplicate, xo:linux
