### ISSUE TITLE
[PostgreSQL] 3D Geometry Z-Value Not Displayed

### ISSUE THREAD

**Issue by gadams13** [dbeaver/dbeaver#3629] opened 2018-06-13 19:50 UTC
DBeaver shows a string that represents the geometry of PostgreSQL objects in the geom column, but it incorrectly displays 3D geometry as if it were 2D. This actually costed me quite a bit of time trying to figure out why my query was returning 2D geometry... I have double checked (using PSQL) and the table in question does indeed have 3D geometry.

Is it possible that this could be adjusted to properly display Z and/or M values?

**Comment by serge-rider** [comment] 2018-06-19 19:39
Could you post some SQL snippet (table DDL + select query)

**Comment by gadams13** [comment] 2018-06-19 20:12
CREATE TABLE test_schema."table_3d" (
	id int4 NOT NULL,
	"name" varchar NULL,
	geom geometry NULL
)
WITH (
	OIDS=FALSE
) ;

SELECT AddGeometryColumn('test_schema','table_3d', 'geom', 4326, 'POINT', 3);

INSERT INTO table_3d (id, name, geom)
VALUES (1, 'testName', ST_SetSRID(ST_MakePoint(1,1,1), 4326));


SELECT * FROM test_schema.table_3d;


In DBeaver, this returns: 

1	testName	POINT (1 1)

In PSQL console, SELECT ST_AsText(geom) FROM test_schema.table_3d returns:

    st_astext
-----------------
 POINT Z (1 1 1)
(1 row)


The issue is that DBeaver will try to automatically convert the geometry from something like "01010000A0E6100000000000000000F03F000000000000F03F000000000000F03F" into human readable text. However, this function in DBeaver drops Z/M values.

**Comment by FlorianFehring** [comment] 2019-07-08 07:24
I think this is a duplicate of #5333. The select statement issue is solved now. But There is a continuing error with the default view of 3D postgis data. When double clicking a table with 3D data the geom column is displayed only with its 2D values.

**Comment by vahtos** [comment] 2019-07-08 14:08
> I think this is a duplicate of #5333. The select statement issue is solved now. But There is a continuing error with the default view of 3D postgis data. When double clicking a table with 3D data the geom column is displayed only with its 2D values.

I think you are right, this is the same issue, it is just presenting itself in a different way. I don't know how the select statement was fixed, but I would think the table view would be using a select statement... so I don't understand how/why this issue is persisting.

**Comment by REIMSMetropole** [comment] 2019-09-03 06:57
Hi. 
Does anyone know when the bug would be fixed ?
Thanks in advance

**Comment by serge-rider** [comment] 2019-09-17 20:09
It is a complicated bug, I'm not quite sure what component is wrong here. 
Postgis returns 3d points as `POINT (x y z)`, jts (library we use for geometry conversions) expects something like `POINT Z(x y z)` for 3d. And converts POINT(anything) into 2d geometry by default.

Both Postgis and JTS seems to be not fully WKT-compliant. However JTS is wrong in any case.
I'll omit any conversions for non 2D Postgis Geometries.

Thanks for the bug report, sorry that it took so long time to fix it.

**Comment by uslss** [comment] 2019-09-18 07:15
verified

**Closed by uslss** 2019-09-18 07:15 UTC
Labels: bug, question, x:postgresql
