### ISSUE TITLE
DBeaver is freezing for one simple SQL query

### ISSUE THREAD

**Issue by coffe-with-hoarfrost** [dbeaver/dbeaver#10256] opened 2020-11-05 19:42 UTC
#### System information: 
- Windows 10 x64
- DBeaver Community Edition 7.2.3 and 7.2.4

#### Connection specification:
- PostgreSQL 11.2

#### Describe your question:
My DBeaver is freezing for the query [dbeaver-troubled-query.txt](https://github.com/dbeaver/dbeaver/files/5496585/dbeaver-troubled-query.txt)
 all the time.

**Comment by uslss** [comment] 2020-11-06 09:34
thanks for the bug report

**Comment by LonwoLonwo** [comment] 2020-11-06 13:58
may be it's connected to this ticket https://github.com/dbeaver/dbeaver/issues/9054

**Comment by mcdamo** [comment] 2020-12-01 02:37
dbeaver execution slows down when there are many nested parentheses in the SELECT query, if the nesting is too great then dbeaver hangs completely.

Not database specific, also happens with mysql, mariadb, mssql.

**Comment by serge-rider** [comment] 2020-12-17 08:31
Duplicate of #9054
Waiting for JSQLParser fix.

**Closed by serge-rider** 2020-12-17 08:31 UTC
Labels: bug, duplicate
