### ISSUE TITLE
Save/Cancel buttons grayed out in query result

### ISSUE THREAD

**Issue by webian** [dbeaver/dbeaver#18068] opened 2022-10-28 10:27 UTC
### Description

Whenever I try to delete a record in query result, the Save and Cancel buttons are grayed out.

To persist the delete I have to run the query again and answer "yes" when it asks me to save changes to database because result set was edited.

### DBeaver Version

Communiti Edition 22.2.3.202210231354

### Operating System

Windows 11

### Database and driver

Server version: 10.3.34-MariaDB-0ubuntu0.20.04.1-log Ubuntu 20.04
MariaDB JDBC driver

**Comment by LonwoLonwo** [comment] 2022-10-28 11:13
Hello @webian 

Please provide footage of your issue.

**Comment by E1izabeth** [comment] 2022-10-28 19:50
Maybe connected to #18013

**Comment by webian** [comment] 2022-10-29 08:03
Yes, same sporadic problem. I can't reproduce it atm, but it happen often.

**Comment by ShadelessFox** [comment] 2022-11-03 12:55
Duplicate of #18013

**Closed as not planned by ShadelessFox** 2022-11-03 12:55 UTC
Labels: duplicate
