### ISSUE TITLE
[ERD] Raltions of a table to itself ignore any collision

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16367] opened 2022-04-29 09:13 UTC
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.4

#### Steps to reproduce, if exist:
1. Open a diagram for a schema that has a table with reference to itself
2. Drag another table to overlap a line of this relation

**Expected:** Line is redrawn to not touch another table
**Actual:** Line always stays the same

![dbeaver_EcGOUQ1SUp](https://user-images.githubusercontent.com/82543000/165916659-34812358-6784-49fa-9b41-07497c6288ff.gif)

**Comment by serge-rider** [comment] 2022-05-17 17:44
Fixed in another issue

**Comment by Matvey16** [comment] 2022-05-18 12:16
Relation ignores the collision if it happens at one of the corners, but works if the line goes through another table.
![dbeaver_D3jYlFuSnp](https://user-images.githubusercontent.com/82543000/169036602-109e0924-1ca6-4c8b-b596-59f15fe5b75d.gif)

**Comment by ShadelessFox** [comment] 2022-05-30 14:54
Duplicate of #14724

**Closed as not planned by ShadelessFox** 2022-05-30 14:54 UTC
Labels: duplicate, xf:erd
