### ISSUE TITLE
DBeaver crashes when connecting via remote desktop.

### ISSUE THREAD

**Issue by Moridin11** [dbeaver/dbeaver#7828] opened 2020-02-04 16:00 UTC
#### System information: 
- Operating system (distribution) and version  **Windows 10 1903 Build 18362.592**
- DBeaver version **6.3.0**
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name **Postgres 9.4.1212**
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  ** NO**

#### Include any warning/errors/backtraces from the logs
All I can find
!ENTRY org.eclipse.core.resources 2 10035 <date>
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

The last entry before that, was an error I received the last time I had used it.

**Comment by fabianMendez** [comment] 2020-02-04 20:32
I think this is a problem related to eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=543747

**Comment by Moridin11** [comment] 2020-02-04 20:55
I don't have eclipse on my machine but I will check the event log when I
get home to see if there is anything in there.

Respectfully submitted,



Chip Adams
Chip.j.adams@gmail.com

**Comment by fabianMendez** [comment] 2020-02-04 21:00
> get home to see if there is anything in there.

Not exactly the eclipse IDE but the eclipse platform which DBeaver is based on

**Comment by fabianMendez** [comment] 2020-02-04 21:35
BTW this solution is working for me: https://stackoverflow.com/questions/1411829#59526421

**Comment by Moridin11** [comment] 2020-02-06 02:18
The error I get is:

Faulting application dbeaver.exe, version 0.0.0.0 timestamp 0x6581a05f
Faulting module msctf.dll v 10.0.18362.535
Exception code 0x000..5af34
Faulting process id: 0x2014

There are some path days there but I'm typing on my phone so hoping it
isn't useful.

Respectfully submitted,



Chip Adams
Chip.j.adams@gmail.com

**Comment by fabianMendez** [comment] 2020-02-06 13:13
@Moridin11 Yeah looks like the same error from the eclipse bug, did you try this workaround: https://stackoverflow.com/questions/1411829#59526421?

**Comment by uslss** [comment] 2020-02-06 15:08
seems to be duplicate of #6407

**Closed by uslss** 2020-02-06 15:08 UTC
Labels: bug, duplicate

**Comment by Moridin11** [comment] 2020-02-06 16:39
Fabian,

I don't have eclipse installed at all, so should I just ad DBeaver to that
list?


Respectfully Submitted,


Chip J. Adams
chip.j.adams@gmail.com
