### ISSUE TITLE
"Fetch all rows" is broken for Redshift

### ISSUE THREAD

**Issue by dmohns** [dbeaver/dbeaver#2910] opened 2018-02-01 11:14 UTC
**Problem description**

I experience the following error: When running a query or viewing a table using Amazon Redshift JDBC connector clicking on "Fetch all rows" will yield:
```
SQL Error [500310] [22003]: [Amazon](500310) Invalid operation: numeric value "4294967295" out of range for integer;
  [Amazon](500310) Invalid operation: numeric value "4294967295" out of range for integer;
    [Amazon](500310) Invalid operation: numeric value "4294967295" out of range for integer;
    [Amazon](500310) Invalid operation: numeric value "4294967295" out of range for integer;
```

**Additional Information / Observations**

- Using `Log` it looks like DBeaver is internally running
```sql
<query>
LIMIT -1
```
which apparently is not supported by Redshift. I am able to re-produce error `[500310]` by appending `LIMIT -1` to an arbitrary query.

- This error did not occur in DBeaver 4.3.1. In fact downgrade to version 4.3.1 fixes the error for the moment. Using `Log` in Version 4.3.1 "Fetch all rows" runs the query without any LIMIT clause at all.

- Versions: DBeaver 4.3.3.1 on macOS 10.13.2

**Comment by serge-rider** [comment] 2018-02-01 20:31
Duplicate of #2849
Will be fixed in 4.3.4
Thanks for report anyways.

**Closed by serge-rider** 2018-02-01 20:31 UTC
Labels: bug, duplicate
