### ISSUE TITLE
Some buttons icons are replaced by a red square

### ISSUE THREAD

**Issue by cumanacr** [dbeaver/dbeaver#3765] opened 2018-07-06 22:31 UTC
After upgrade to dbeaver 5.1.2,  **Database Navigator**, **Projects**, and **Project General** buttons icons are replaced by a red square, even though functionality is not affected at all and after click on them, icons are restored, so, this is a minor bug.

![selection-03-2018-07-05](https://user-images.githubusercontent.com/6874136/42402679-9a2ccc18-8139-11e8-9c04-86e856e9f8da.png)

**Comment by serge-rider** [comment] 2018-07-07 08:32
Duplicate of #3653
This happens only on some Linuxes, resetting UI cache (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace) helps

**Closed by serge-rider** 2018-07-07 08:32 UTC
Labels: duplicate, question

**Comment by cumanacr** [comment] 2018-07-09 22:12
Thank you very much @serge-rider resetting UI cached solved it
