### ISSUE TITLE
Issue with switching active database because of Wrong lock passed. 

### ISSUE THREAD

**Issue by yrimal** [dbeaver/dbeaver#8318] opened 2020-04-02 07:23 UTC
#### System information: 
- Windows 10 Pro Version 2004 (Build 19041.153)
- DBeaver  7.0.1.202003211804

#### Connection specification:
PostgreSql 9.6
PostgreSQL standard driver
Do you use tunnels or proxies (SSH, SOCKS, etc) : SSH

#### Describe the problem you're observing:
When trying to switch to another database, Dbeaver spends long time on `Excessive lock` and fails with the error message: `Wrong exclusive lock passed`. 
#### Steps to reproduce, if exist:
1. With active connection on databse_a, Open New Sql Editor through shortcut. 
2. In newly opened sql editor, try to change default object to databse_b
3. DBeaver will try to connect for a while and fail with aforementioned message. 

#### Include any warning/errors/backtraces from the logs
Log: 
```
!ENTRY org.jkiss.dbeaver.model 4 0 2020-04-02 12:59:05.707
!MESSAGE Wrong exclusive lock passed
!STACK 0
java.lang.IllegalArgumentException: Wrong exclusive lock passed
	at org.jkiss.dbeaver.model.impl.SimpleExclusiveLock.releaseTaskLock(SimpleExclusiveLock.java:90)
	at org.jkiss.dbeaver.model.impl.SimpleExclusiveLock.releaseExclusiveLock(SimpleExclusiveLock.java:78)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:162)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.openIsolatedContext(JDBCRemoteInstance.java:123)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:581)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Screenshot: 
![image](https://user-images.githubusercontent.com/6102813/78221386-00eaaf80-74e3-11ea-9173-cb053d99902b.png)

**Comment by serge-rider** [comment] 2020-04-02 07:28
Can't reproduce.

@yrimal Do you switch between different connections or between different databases within single connection?
Some screenshot would be also helpful.

**Comment by yrimal** [comment] 2020-04-03 02:41
@serge-rider, switch between different databases within single connection. My connection has about 40 databases there.

**Comment by xyluet** [comment] 2020-04-03 03:56
Same with ubuntu 18.04 dbeaver version `Version 7.0.1.202003211804`

After a long sleep, it happened, but it's intermittent. When you close the app then reopen, it said cannot lock data <home>/.local/share/workspace6.

**Comment by serge-rider** [comment] 2020-04-03 14:57
This happens in PostgreSQL databases in multi-database mode only.
Probably fixed by https://github.com/dbeaver/dbeaver/commit/6e8824935825d69da840d268ccdfee59b1490849 , can't reproduce this anymore.

**Comment by uslss** [comment] 2020-04-05 09:48
verified

**Closed by uslss** 2020-04-05 09:48 UTC
Labels: bug, x:postgresql
