### ISSUE TITLE
Filter Database Objects not allowing multiple or negative conditions

### ISSUE THREAD

**Issue by KipperK** [dbeaver/dbeaver#4500] opened 2018-10-26 23:51 UTC
I am trying to setup database filtering for one of my MariaDB connections in DBeaver 5.2.3 but it is failing due to syntax errors.

Multiple "Include" filters:
```
SQL Error [1064] [42000]: (conn:1105793) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '( LIKE 'database1' OR  LIKE 'database2')' at line 1
Query is: show databases( LIKE ? OR  LIKE ?), parameters ['database1','database2']
```
The query should be:
```
show databases WHERE (`Database` LIKE 'database1' OR `Database` LIKE 'database2');
```

Similarly, "Exclude" conditions also have a syntax error.
```
SQL Error [1064] [42000]: (conn:1105793) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'databasesNOT ( LIKE 'database_prefix%')' at line 1
Query is: show databasesNOT ( LIKE ?), parameters ['database_prefix%']
```
The query should instead be:
```
show databases WHERE (`Database` NOT LIKE 'database_prefix%');
```
Please let me know if I should provide any more information.

**Comment by serge-rider** [comment] 2018-11-06 12:47
Duplicate of #4554

**Closed by serge-rider** 2018-11-06 12:47 UTC
Labels: bug, duplicate

**Comment by KipperK** [comment] 2018-11-07 06:13
I jest tested f8258307a5916ef3574fe4c6d01752d73224e761 and can confirm it is working.  Thanks!
