### ISSUE TITLE
DB crashes after type data type in grid

### ISSUE THREAD

**Issue by danielfalsetti** [dbeaver/dbeaver#6935] opened 2019-10-07 16:39 UTC
DBeaver version: 6.2.2.201910061950
Driver: PostgreSQL JDBC Driver

Steps to reproduce:

Click on "Edit Table" on an existing table
Click on "Data" tab
Clique on Add New Row
Insert some data in fieds and type "enter"
DB closes !!!

**Comment by danielfalsetti** [comment] 2019-10-07 16:43
DBeaver version:  6.2.2.201910061950
Driver: PostgreSQL JDBC Driver

Steps to reproduce:

1. Click on "Edit Table" on an existing table
2. Click on "Data" tab
3. Clique on Add New Row
4. Insert some data in fieds and type "enter"
5. DB closes !!!

**Comment by serge-rider** [comment] 2019-10-07 16:47
Duplicate of #6928

**Comment by serge-rider** [comment] 2019-10-07 16:48
Thanks for the bug report anyways.

**Closed by serge-rider** 2019-10-07 16:47 UTC
Labels: bug, duplicate
