### ISSUE TITLE
DDL for PostgeSQL (10) doesn't include PARTITION BY clause for partitioned tables and PARTITION OF for partitions (show them as just inherited instead)

### ISSUE THREAD

**Issue by BorisFBogdanov** [dbeaver/dbeaver#4653] opened 2018-11-20 12:37 UTC

**Comment by AndrewKhitrin** [comment] 2019-04-23 19:44
And for partitioned table doesn't include any partition creation statement

**Comment by serge-rider** [comment] 2019-07-01 20:03
Seems to be duplicate of #6121

**Closed by serge-rider** 2019-07-01 20:03 UTC
Labels: feature request
