### ISSUE TITLE
Exception after copying a SQL query

### ISSUE THREAD

**Issue by ralebhattushar** [dbeaver/dbeaver#4710] opened 2018-11-29 08:21 UTC
I am using MS sql server database. Afer copying the sql query in SQL editor, following exception occured:

![image](https://user-images.githubusercontent.com/45413542/49208376-a5378000-f3dd-11e8-9c87-0ef16dfc031c.png)

I am using DBeaver 5.2.5.201811181655

**Comment by serge-rider** [comment] 2018-12-02 18:48
Duplicate of #4706

**Closed by serge-rider** 2018-12-02 18:48 UTC
Labels: bug, duplicate, x:mssql
