### ISSUE TITLE
How to connect to Athena using ACCESS_KEY, SECRET_KEY, and SESSION_TOKEN?

### ISSUE THREAD

**Issue by mnt1979** [dbeaver/dbeaver#5264] opened 2019-02-12 14:10 UTC
How to connect to Athena using ACCESS_KEY, SECRET_KEY, and SESSION_TOKEN?
I am using Dbeaver 5.3.4 on MAC.

**Comment by nmat** [comment] 2019-02-16 10:25
According to documentation:

To configure authentication using IAM credentials:
1. Set the User property to the access key provided by your AWS account.
2. Set the Password property to the secret key provided by your AWS account.

Did you test that?

**Comment by mnt1979** [comment] 2019-02-20 20:46
I tried few options including the link above but it fails with "unable to find valid certification path to requested target" error.

**Comment by mnt1979** [comment] 2019-02-28 14:27
any kind of help is appreciated here.

**Comment by Chandrian** [comment] 2019-04-04 13:49
Hello,

I'm using DBeaver 6.0.1 and trying to find a way to connect to it using access/secret key with session token (using an aws role to connect to it). So far I was not successful. The main problem seems to be that I cannot not set the access/secret key so that it will take into account the one I set in the Drive properties "AwsCredentialsProviderArguments" with "AwsCredentialsProviderClass" set to `com.example.CustomSessionCredentialsProvider`. Is there any documented example somewhere?

Could anyone point me in the right direction?

Thank you,

**Comment by arturhbs** [comment] 2019-07-02 16:54
Hello, 
I am having some troubles with the connection between Dbeaver and Athena in the matter of I can connect with Athena, but when I run any query, I am simply ignored by Dbeaver, I never got any answer back. Even so, when I look at Athena, I notice that all of my querys have were done, but I just got an answer, after a long time, saying that the connection was refused:

(SQL Error [100131] [HY000]: [Simba][AthenaJDBC](100131) An error has been thrown from the AWS SDK client. Unable to execute HTTP request: Connect to athena.us-east-1.amazonaws.com:444 [athena.us-east-1.amazonaws.com/52.45.125.121, athena.us-east-1.amazonaws.com/3.217.66.47, athena.us-east-1.amazonaws.com/52.87.95.198, athena.us-east-1.amazonaws.com/3.213.122.8, athena.us-east-1.amazonaws.com/52.45.75.211, athena.us-east-1.amazonaws.com/52.45.177.97, athena.us-east-1.amazonaws.com/3.213.195.203, athena.us-east-1.amazonaws.com/52.45.75.32] failed: Connection refused: connect
)  

I can see all the tables that are in Athena, but can't execute any query.
Anyone knows something about that?

**Comment by mistertjs** [comment] 2019-10-31 00:17
I'm running into the same problem as arturhbs. I can see all the metadata for the s3 buckets, and the tables under each in Dbeaver Database Navigator, but queries never return. They just spin forever, executing the process 'Read data'. 

BTW: The same queries work in Athena.

**Comment by johjairo** [comment] 2019-12-03 15:38
> Hello,
> 
> I'm using DBeaver 6.0.1 and trying to find a way to connect to it using access/secret key with session token (using an aws role to connect to it). So far I was not successful. The main problem seems to be that I cannot not set the access/secret key so that it will take into account the one I set in the Drive properties "AwsCredentialsProviderArguments" with "AwsCredentialsProviderClass" set to `com.example.CustomSessionCredentialsProvider`. Is there any documented example somewhere?
> 
> Could anyone point me in the right direction?
> 
> Thank you,

I have the same problem, could you ever fixed?

**Comment by chuanzgh** [comment] 2019-12-16 05:45
Same problem as arturhbs above @ https://github.com/dbeaver/dbeaver/issues/5264#issuecomment-507760455

**Comment by arturhbs** [comment] 2019-12-16 11:44
> Same problem as arturhbs above @ [#5264 (comment)](https://github.com/dbeaver/dbeaver/issues/5264#issuecomment-507760455)

I've tried changing the JDBC to an older version and it worked for me. You should try and see if it works for you too.

**Comment by chuanzgh** [comment] 2019-12-17 00:46
> I've tried changing the JDBC to an older version (2.0.2) and it worked for me. You should try and see if it works for you too.

Thanks, that worked.

I saw in the [documentation](https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html#migration-from-previous-jdbc-driver) a hint that this has probably got to do with the ResultSet streaming feature available in Simba Athena JDBC driver >= 2.0.5

So I went ahead and set UseResultsetStreaming=0 for the 2.0.9 driver properties and now it works.

On hindsight, I see the error message you posted saying port 444 connection refused. So in your case (and mine!) there's probably a firewall there blocking port 444. So by setting UseResultsetStreaming=0 it forces the driver to fallback to the pagination method and avoid streaming the results back from port 444.

**Comment by shawnweeks** [comment] 2019-12-23 22:19
> According to documentation:
> 
> To configure authentication using IAM credentials:
> 
>     1. Set the User property to the access key provided by your AWS account.
> 
>     2. Set the Password property to the secret key provided by your AWS account.
> 
> 
> Did you test that?
> 
> Just looked quickly at: https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.6/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf

This doesn't work with temp credentials. We will need to make some adjustments for that to work. 6088 is a duplicate of this I think but since it's clearer what's being asked for I'll try and tackle it.

**Comment by ryanaddington** [comment] 2020-02-24 23:43
It looks like this was answered in another thread and the original question of connecting via temp credentials is possible.  https://github.com/dbeaver/dbeaver/issues/3918

**Closed** 2020-04-05 13:49 UTC
Labels: question
