### ISSUE TITLE
Additional issues with autocompletion, sql editor, and Hippie Engine in 21.3.2

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#15103] opened 2022-01-01 11:27 UTC
#### System information: 
- Operating system (distribution) and version: Windows 11
- DBeaver version: 21.3.2
- Additional extensions

#### Connection specification:
- Database name and version: Oracle DB 19c
- Driver name: Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
 I was checking the new autocompletion features and the Hippie engine in 21.3.2, and I came across with some issues:

1. Autocompletion now works in sql editor for select statements specifying current schema name in the form "**select * from current_schema.*** ", but if you do "**select * from other_schema.*** " it doesn't work even when you have the option to search in other schemas (whenever possible, because current schema has grants to do so).

2. Autocompletion with functions inside packages is not working properly as before, now it autocompletes parameters with their types instead of parameter names as before:
![image](https://user-images.githubusercontent.com/121157/147849247-584eb7b8-77ed-415e-9ae3-eff2e70bece8.png)

It should autocomplete the parameter names in the form :param_value, or param_name => :parameter_value (better)

3. Autocompletion only works for select statements in sql editor, if you write a piece of code like the following example, it doesn't autocomplete anything:
```
BEGIN
  package_name.*;
  current_schema.package_name.*;
  other_schema.package_name.*;
END;
```

4. In sql editor when you just write "begin" in lowercase and press enter, what it does is to autocomplete with following:
```
BEGIN

end
```

Even when you have capitalization set up in lowercase,  it ignores it and puts the being in upper case, and the later end in lowercase. Also it should add a ; and a / at the end if it is placed in the sqleditor, or just the ; if it is in the package editor. The correct autocompletion should be:

```
begin

end;
/
```

5. The "END IF" statement is not properly managed, having this code as an example:

```
BEGIN
	IF(1=2) THEN
	  test_code();
	END IF;
END;
/
```

If you try to move the END IF; to the next line, it doesn't keep the current tabulation and it puts the "END IF" to the very first column. The same applies to any END * statement, like END LOOP etc.

6. The Hippie engine works nicely, I haven't found performance issues at the moment, but it would be very nice if it could autocomplete parameters for functions in the current package in the form (parameter_name => :parameter_value)

**All the issues also apply in the package editor.**

**Comment by LonwoLonwo** [comment] 2022-01-01 16:28
https://github.com/dbeaver/dbeaver/issues/13861

**Comment by LonwoLonwo** [comment] 2022-01-04 21:17
Hello @yevon 

1. 
> Autocompletion now works in SQL editor for select statements specifying the current schema name

![2022-01-05 00_01_31-](https://user-images.githubusercontent.com/45152336/148123690-01473b34-debd-4d6f-b55e-ff3fcf630fff.png)

I can't reproduce it. Can you provide more details, please? Maybe screenshots or video, or steps to reproduce (HippyEngine setting is on in my settings).

2. 
> Autocompletion with functions inside packages is not working properly as before

We already have a ticket for this issue in this milestone: https://github.com/dbeaver/dbeaver/issues/14275

**Comment by yevon** [comment] 2022-01-14 21:01
Find attached a video with found issues:

[Video capture link](https://we.tl/t-tmdfz2iEZT)

Sorry but my video screen recorder software is not able to capture the autocompletion pop up even when I was seeing it, but it just says (No proposals).

**Comment by Destrolaric** [comment] 2022-01-24 08:35
Hi, I will split issues into subparts to manage them separately.

**Comment by Destrolaric** [comment] 2022-01-24 08:44
@yevon Hi, the link has expired. Can you send a video via Github directly?

**Comment by yevon** [comment] 2022-01-24 09:48
I will try later but it was too big for github.

**Comment by E1izabeth** [comment] 2022-11-10 21:05
All issues except third point seems to be fixed for now.

@yevon could you give some example of such query where it's valid to have some statements containing just identifier inside begin..end section? DBeaver autocomplete identifiers only when you write them in some statement. For example, 
```
BEGIN
     SELECT * FROM <autocompletion works here>
END
```

**Comment by yevon** [comment] 2022-11-10 21:40
I will try to check it out as soon as I can, but there are some insights about this:


In Oracle begin / end statements are for executing any PL/SQL code, and as such it should be able to autocomplete anything in the form:



DECLARE --Autocompletion should work with a declare section or without it (If it doesn't do that already)
   l_var number;
BEGIN
     
     --Select statements
     SELECT count(*) into l_var FROM <autocompletion works here>;

     --Select statements starting with the sentence WITH in multiple lines:
     WITH test as (SELECT count(*) num_regs FROM <autocompletion works here> ) 
     select test.num_regs into into l_var from test, <autocompletion should work here>;

    --Exactly the same as previous ones, but with INSERT, UPDATE, DELETE and MERGE statements.

    --Select statements against dblinks:
    SELECT * FROM <table_name>@<dblink_name>;

     --Function and procedure calls, with prefix schema name or without it
     l_var = <optional_schema_name>.<function_name>();
     <optional_schema_name>.<procedure_name>();

     --Function and procedure calls inside oracle packages, with prefix schema name or without it
     l_var = <optional_schema_name>.<package_name>.<function_name>();
     <optional_schema_name>.<package_name>.<procedure_name>();

END;
/


I would also check for synonyms compatibility, as in oracle you can define synonyms for certain object types.

**Comment by E1izabeth** [comment] 2022-11-10 21:42
Thank you for your attention.

**Comment by E1izabeth** [comment] 2023-01-26 13:30
There is no update on this issue for a long time, so I'm closing it. Please let me know if the issue is still actual for you for the latest DBeaver version.

**Closed as completed by E1izabeth** 2023-01-26 13:30 UTC
Labels: xf:sql, wait for response
