### ISSUE TITLE
Allow editing filenames when exporting data to files

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#6965] opened 2019-10-11 09:43 UTC
**Is your feature request related to a problem? Please describe.**

Currently in _Data Transfer_ window all filenames are generated using mask from _File name pattern_ field and they can't be changed manually later. This works when exporting data from tables, but queries generate long ugly names that (in my case) are often very similar.

**Describe the solution you'd like**

Allow editing filenames in _Target_ column.

**Comment by kseniiaguzeeva** [comment] 2020-08-04 10:46
Sorry for the long answer While you can use different File name patters in Output step of Export wizard.
![K0jRulHVYV](https://user-images.githubusercontent.com/51405061/89285142-87152f00-d658-11ea-8a8b-92b2a0aebd47.png)

I close the ticket as duplicate of #8033, because the similar suggestion hasa detailed description there.

**Closed by kseniiaguzeeva** 2020-08-04 10:46 UTC
Labels: duplicate, feature request
