### ISSUE TITLE
Add project name in editors' names

### ISSUE THREAD

**Issue by itphonim** [dbeaver/dbeaver#13117] opened 2021-07-06 10:07 UTC
Hi,
this is a feature request that i'd like to see, concerning the editors' name.
Would be great if we could put the name of the project in the name shown.
![image](https://user-images.githubusercontent.com/82998099/124582371-3f8fb800-de52-11eb-9207-a4e0de96bd97.png)
a new variable like ${projectName} for instance

**Comment by uslss** [comment] 2021-07-06 10:38
thank you for the suggestion.
closed as a duplicate of #6012

**Closed as completed by uslss** 2021-07-06 10:38 UTC
Labels: duplicate
