### ISSUE TITLE
CTRL+ENTER and ALT+X not working

### ISSUE THREAD

**Issue by emanueol** [dbeaver/dbeaver#29327] opened 2024-05-03 17:21 UTC
### Description

CTRL+ENTER and ALT+X no longer working.

### DBeaver Version

Community 24.0.3.202404211624

### Operating System

windows 10

### Steps to reproduce

Before for years, I used to execute code in 2 ways:
- put cursor on a line (beginning or in middle) and press CTRL+ENTER --> and that would execute just one SQL command where cursor was.
- select multiple lines, press ALT+X --> and that would execute sequentially each SQL command.

I no longer can execute SQL normally.. only way to execute is selecting 1 single SQL statement and press CTRL+ENTER (which before wasn't necessary to select).
Also no longer can execute multiple lines.

------------------------------------------------------------
with following 4 lines:

SELECT CURRENT_DATABASE();   --line 1
SELECT CURRENT_user();       --line 2
use role orgadmin;           --line 3
show organization accounts;  --line 4

I used to be able to simple, put cursor on any of the lines, press CTRL+ENTER to just execute the line where cursor is, now having weird behaviour:
1. cursor in line 1 --> press CTRL+ENTER --> OK executes only 1st line
![image](https://github.com/dbeaver/dbeaver/assets/8422412/4f2e5907-9d1e-4380-8bb4-7ef2e6cd4c24)

2. cursor in line 2 --> press CTRL+ENTER --> NOK weirdly dbeaver tries to execute 3 lines ?!?
![image](https://github.com/dbeaver/dbeaver/assets/8422412/063ac616-d2c5-428b-9a35-7b90f84bcfee)

3. cursor in line 3 --> press CTRL+ENTER --> NOK weirdly dbeaver tries to execute 3 lines ?!?
![image](https://github.com/dbeaver/dbeaver/assets/8422412/1fa1cc21-cf32-4bc5-9786-6479a0ae737d)

4. cursor in line 4 --> press CTRL+ENTER --> NOK weirdly dbeaver tries to execute 3 lines ?!?
![image](https://github.com/dbeaver/dbeaver/assets/8422412/77304152-2e5b-482b-8aff-04bafa4b99e7)

--------------------------------------
-- the 2nd problem ALT+X 
Before I used to select couple of lines and press ALT+X to execute all of them, now this no longer possible:
![problem-CTRL+ENTER ALT+X not working](https://github.com/dbeaver/dbeaver/assets/8422412/04dff1f3-06dc-47d6-ba40-4ee76260dccf)

--==================================================================--
-- here's another gif showing me to try execute single SQL command using only CTRL+ENTER
![problem-CTRL+ENTER](https://github.com/dbeaver/dbeaver/assets/8422412/376f209c-75a8-4243-a862-211459574e64)

--==================================================================--
-- here's another gif showing me to try execute multiple lines after selecting couple of SQL command using ALT+X
![problem-ALT+X](https://github.com/dbeaver/dbeaver/assets/8422412/ec555c9e-be75-47f2-ad4b-c19af3eef2a0)

Any suggestions ? This seems to weird to be bug right ? I used to simple start DBeaver, put cursor on simple SQL SELECT and press CTRL+ENTER and no longer can do that.

----
FYI Heres my Preferences settings > SQL Processing to see SQL delimiter semicolon is there ;
![image](https://github.com/dbeaver/dbeaver/assets/8422412/79d19e4a-9482-429d-84a1-cba80b3642b5)

**Comment by E1izabeth** [comment] 2024-05-03 17:25
Thank you for bug report.
It's a duplicate of #26416
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Closed as not planned by E1izabeth** 2024-05-03 17:25 UTC
Labels: duplicate, xf:sql execution

**Comment by emanueol** [comment] 2024-05-03 17:28
Ha thanks Elizabeth, good to know its already detected, thanks.
