### ISSUE TITLE
Bug in version 5.2.1 with Oracle ojdbc7.jar for TimeStamp rendering null

### ISSUE THREAD

**Issue by copperorange** [dbeaver/dbeaver#4270] opened 2018-09-25 02:31 UTC
Hi,

I am probably missing something obvious, but I am experiencing the same issue as #3532 describes where timestamp is rendering null. I have tried setting the TimeStamp precision to various patterns. Date works fine.

Please advise.

Thank you.

Env
OSX
Java version: java 10.0.1 2018-04-17

ojdbc7.jar 
[https://www.oracle.com/technetwork/database/features/jdbc/jdbc-drivers-12c-download-1958347.html](url)
Ref Oracle driver doc [https://docs.oracle.com/cd/B19306_01/java.102/b14355/urls.htm#i1070726](url)

**Comment by pvandenbrink** [comment] 2018-09-27 07:04
I'm having the same problem with DBeaver 5.2.1 on Oracle; all TimeStamp fields are rendering as null, even if they do have a value.
Tried with both ojdbc7.jar and ojdbc8.jar drivers.

Windows 10
Oracle 11g (11.2.0.3.0)
java 1.8.0_162

The DBeaver log repeatedly shows the following error:

!ENTRY org.jkiss.dbeaver.model 2 0 2018-09-26 10:08:02.572
!MESSAGE Unrecognized type 'oracle.sql.TIMESTAMP' - can't convert to date/time value

**Comment by serge-rider** [comment] 2018-09-27 09:27
I can't reproduce this. Maybe it is related to the driver version (I'm using ojdbc8, JDBC driver 12.2.0.1.1 version).

Could you post some SQL query which will help to reproduce this issue? 
For instance `SELECT current_timestamp FROM dual` works fine in my env.

**Comment by marco-sanjuan** [comment] 2018-09-27 09:53
Same problem here since 5.2.1, also `SELECT current_timestamp FROM dual` returns null.

We use ojdbc7 driver.
![image](https://user-images.githubusercontent.com/4165141/46138321-e085c900-c24b-11e8-9255-0ac4b2cd0462.png)

**Comment by fthiel** [comment] 2018-09-27 09:54
I'm having the same problem.
DBeaver 5.2.1.201809240911
Windows 10
Oracle 12c (12.2.0.1.0)
java 1.8.0_77
ojdbc7.jar 

`SELECT current_timestamp FROM dual` returns also null.

**Comment by marco-sanjuan** [comment] 2018-09-27 10:03
I have upgraded to ojdbc8 but it's not solving the issue.
`SELECT current_timestamp FROM dual` now returns right timestamp, but **queries to db still returns null for all timestamp columns**.

![image](https://user-images.githubusercontent.com/4165141/46138835-432b9480-c24d-11e8-9991-decaf4645fae.png)

**Comment by serge-rider** [comment] 2018-09-27 21:44
Yep, it is reproducible with Oracle 11.
And it is a result of one of recent fixes in Timestamp columns handler.

I've just committed the fix, could you test it in Early Access version (https://dbeaver.io/files/ea)?

**Comment by marco-sanjuan** [comment] 2018-09-28 07:31
Tested and working on 5.2.2 EA, great @serge-rider !

**Comment by serge-rider** [comment] 2018-09-28 12:27
Thank you for the bug report and for testing )

**Closed by serge-rider** 2018-09-28 12:27 UTC
Labels: bug, question, x:oracle
