### ISSUE TITLE
The "Execute SQL in new tab" button is missing.

### ISSUE THREAD

**Issue by RafaelXI** [dbeaver/dbeaver#18341] opened 2022-11-25 16:38 UTC
### Description

The "Execute SQL in new tab" button in the "SQL Editor" window is missing.

![obraz](https://user-images.githubusercontent.com/66827234/204026816-1b919704-1bd5-4097-8b69-73d89c93ce69.png)

### DBeaver Version

Community Edition 22.2.5

### Operating System

Win 10

**Comment by E1izabeth** [comment] 2022-11-25 17:06
It's a duplicate of #18275.
Fix will be available in 22.3.0.

**Closed as not planned** 2022-11-25 17:06 UTC
Labels: duplicate
