### ISSUE TITLE
[7.0.2][win10] Text on unfocused tabs unreadable in default dark theme

### ISSUE THREAD

**Issue by skytomba** [dbeaver/dbeaver#8428] opened 2020-04-14 08:17 UTC
v. **7.0.2**.202004051509
With the default dark theme 6.0.0, unfocused tabs in the DBeaver interface have text that is very hard to read due to the colours
![1](https://user-images.githubusercontent.com/32893144/79201958-e6e98f00-7e49-11ea-8354-80d850a2e342.gif)

**Comment by uslss** [comment] 2020-04-14 13:35
seems to be duplicate of #8366 
ticket closed.
anyway, thanks for the bug report

**Closed by uslss** 2020-04-14 13:35 UTC
Labels: bug, wait for review
