### ISSUE TITLE
Some icons are scaled up too much when viewing in HiDPI

### ISSUE THREAD

**Issue by wout** [dbeaver/dbeaver#5095] opened 2019-01-24 19:49 UTC
#### System information: 
- Pop!_OS (Ubuntu based) 18.10
- DBeaver 5.3.3
- openjdk 11.0.1 2018-10-16 

#### Describe the problem you're observing:
Icons for columns and connection types are scaled up twice when viewing in HiDPI:

![image](https://user-images.githubusercontent.com/107324/51704333-17f95c00-2019-11e9-8d6b-8b2d18b0b0c8.png)

**Comment by lBilali** [comment] 2019-01-28 20:13
same issue here on Ubuntu 18.04

**Comment by wout** [comment] 2019-01-30 09:52
I would like to add that all icons in the main menu drop downs as well as the contextual menu are all LoDPI.

**Comment by lBilali** [comment] 2019-01-30 20:02
I think this has to do with fractional scaling.
I set it back to 1 and change the resolution instead and the icons are fine.
Just to clarify: I'm not keeping it this way as things get a blurry and low resolution and is giving me headache but it might help to look at the right direction. maybe @wout can check if this "fixes" it for him as well.

**Comment by wout** [comment] 2019-02-10 16:07
I'm sure it has to do with DPI scaling. The only way to fix it is to set the resolution to FHD (from QHD).

**Comment by slokhorst** [comment] 2019-03-25 15:42
Same issue here on Arch Linux. All the icons at the top are scaled correctly though. It's just the ones in the main screen.

![2019-03-25_16-40](https://user-images.githubusercontent.com/8083666/54933393-de5fa700-4f1c-11e9-8550-a3c02f4f6518.png)

**Comment by nestor-custodio** [comment] 2019-08-19 21:05
No comments on this in some time, but I can confirm this is indeed still an issue 7 months later on latest release (6.1.5).

**Comment by wout** [comment] 2019-08-20 06:55
@nestor-custodio Just upgraded to version 6.1.5 and the issue persists.

![image](https://user-images.githubusercontent.com/107324/63324253-f7338380-c327-11e9-8364-a4f429bdcaa3.png)

Although, I switched to elementary OS 5.0 in the meantime.

**Comment by nestor-custodio** [comment] 2019-08-20 19:59
@wout -- Good note on the OS in use. I'm seeing this on Ubuntu 19.04 (GNOME).

**Comment by johnf** [comment] 2019-09-22 21:25
Is everyone experiencing this using Wayland? See #6581

**Comment by slokhorst** [comment] 2019-09-23 07:53
@johnf no, I'm using Openbox (Xorg).

**Comment by nestor-custodio** [comment] 2019-09-27 20:03
Ditto. I'm running an Xorg session here, @johnf.

**Comment by slokhorst** [comment] 2019-10-07 10:37
This is fixed for me in 6.2.2! Awesome :)
![image](https://user-images.githubusercontent.com/8083666/66305216-22d1f380-e8ff-11e9-9e60-ee3d67175e3a.png)

**Comment by wout** [comment] 2019-10-09 10:19
Mine are still too large.

![image](https://user-images.githubusercontent.com/107324/66473198-11b7ec80-ea8f-11e9-810b-dedc3f86851e.png)

**Comment by nestor-custodio** [comment] 2019-10-09 16:16
I also am still seeing this on 6.2.2.201910072100.

**Comment by hiwaveSupport** [comment] 2019-10-26 13:34
![image](https://user-images.githubusercontent.com/39630233/67620330-95821080-f7d3-11e9-90a2-dc2da7bb968a.png)

on version 6.2.3 and ubuntu 16.04 and scaled down to 1x. Still the icons are zoomed in

**Comment by lBilali** [comment] 2019-10-26 18:28
installing the latest version of eclipse solved it for me. I’m running on Ubuntu 19.10 though not sure if that matters.
And the icons are fine on wayland and x.org

**Comment by timneedham** [comment] 2019-11-01 13:59
Hi, 

*Same here:*

* `Ubuntu 18.04.03`
* `3840 x 2160`, running at **200%** scale
* Eclipse: `org.eclipse.equinox.simpleconfigurator_1.3.200.v20
181101-1115.jar`

All other icons are fine for me, just the ones in the navigator are double-size:

![image](https://user-images.githubusercontent.com/1216632/68029258-c5875300-fcae-11e9-8d2f-4b015d02773b.png)

Oddly, they're fine in the first column here.... and double again to the right:

![image](https://user-images.githubusercontent.com/1216632/68029570-6544e100-fcaf-11e9-87ce-f72a5148b4c9.png)

...love DBeaver, will be buying the full version... but this is a really distracting eye-splinter. I've tried all the other related issues... anyone have any thoughts?

**Comment by abudis** [comment] 2019-11-04 12:33
This was fixed for me in 6.2.2, but after updating to 6.2.4 the icons are back to being broken.

Running Ubuntu 19.10
3840 x 2160, at 200% scale

**Comment by serge-rider** [comment] 2019-11-16 12:55
In 6.2.2 we used newer Eclipse platform but then rolled back (because of critical bugs in it).
This must be resolved in 6.2.5 as we'll upgrade to newer version.

You can check it in Early Access version (https://dbeaver.io/files/ea)

**Closed** 2019-11-16 23:18 UTC
Labels: bug

**Comment by ac10n** [comment] 2021-12-25 21:23
![image](https://user-images.githubusercontent.com/5188263/147393740-807223a4-6179-45f6-8c02-f0c92eff8455.png)

I'm using DBeaver Version 21.3.1.202112130652.
KDE Plasma 5.23.3 on Fedora. Dual Monitor (laptop: Frame.work 2256*1504@100%, External: Dell 32 4k@150%)

Same behavior in single monitor as well.

My only essential tool that does not work with hidpi is DBeaver. It also does not care about `QT_SCALE_FACTOR=1`.

Even if an option is added to fix scaling to 1, that would be good enough (the problem will be limited to this application only, people will not have to set global scaling to 1 to be able to use DBeaver)
