### ISSUE TITLE
Column to be modified to NULL cannot be modified to NULL

### ISSUE THREAD

**Issue by swanknight** [dbeaver/dbeaver#20259] opened 2023-06-12 05:17 UTC
### Description

Whenever I try to change the datatype of a column, I always get this error. 

This happens even if there are no constraints, or any data for that matter.
Also, I noticed that this happens only with DBeaver. If I do the exact same thing to the exact same table using SQL Navigator, it will work without issues.

### DBeaver Version

Community Edition 23.1

### Operating System

Windows 10

### Database and driver

Oracle 11.2.0.4
OJDBC8-Full

### Steps to reproduce

I created a new dummy table (empty), added some columns, then tried to change the datatype of one of the columns from NVARCHAR to NUMBER, and I got this error:

```
SQL Error [1451] [72000]: ORA-01451: column to be modified to NULL cannot be modified to NULL

Error : 1451, Position : 40, Sql = ALTER TABLE DUMMY_TABLE MODIFY DUMMY_NOTE NUMBER(38,0) NULL, OriginalSql = ALTER TABLE DUMMY_TABLE MODIFY DUMMY_NOTE NUMBER(38,0) NULL, Error Msg = ORA-01451: column to be modified to NULL cannot be modified to NULL

ORA-01451: column to be modified to NULL cannot be modified to NULL
```

**Comment by LonwoLonwo** [comment] 2023-06-12 07:59
Thanks for the report @swanknight 

It's because of the extra NULL at the end of the query. As a workaround, you can copy this command and execute it without the "NULL" element on the end.

**Comment by BelalAboarab** [comment] 2023-08-30 08:01
Can we remove the "NULL" in the end of the generated script somewhere in settings?

**Comment by LonwoLonwo** [comment] 2024-07-30 08:09
Can not reproduce this issue in the latest DBeaver release. No "NULL" keyword word at the end of the modifying query.

![image](https://github.com/user-attachments/assets/46074814-5ab5-4112-a486-3f30e9913048)

So, I'm closing this issue. If problem occurs again - feel free to open a new ticket.

**Closed as completed by LonwoLonwo** 2024-07-30 08:09 UTC
Labels: x:oracle, xf:metadata, xp:normal
