### ISSUE TITLE
DBeaver displays float8 data type where it should be double precision for PostgreSql

### ISSUE THREAD

**Issue by EdmilsonToledo** [dbeaver/dbeaver#35780] opened 2024-10-02 13:38 UTC
### Description

DBeaver displays float8 data type where it should be double precision for PostgreSql.
This also occurs with integer type fields where it displays int4 for smallint and int8 for integer...
Is there any configuration to correct the display of data types?

### DBeaver Version

Community Version 24.2.1.202409221725

### Operating System

Windows 10

### Steps to reproduce

Displaying Table DDL

**Comment by E1izabeth** [comment] 2024-10-02 17:40
There is nothing incorrect here. It's an aliases for data types https://www.postgresql.org/docs/current/datatype.html

**Comment by E1izabeth** [comment] 2024-10-02 17:40
There is no setting to change the displayed type name

**Comment by E1izabeth** [comment] 2024-10-02 17:41
I'm closing it as it's a duplicate of #34809

**Closed as not planned by E1izabeth** 2024-10-02 17:41 UTC
Labels: x:postgresql, duplicate, xf:metadata, xf:ui

**Comment by EdmilsonToledo** [comment] 2024-10-02 18:15
Hello!
I can send you images of examples of fields that I created myself as double
precision and on the screen they are displayed as float8...
[image: image.png]
