### ISSUE TITLE
Error when starting DBeaver - Unable to activate bundle org.eclipse.ui.ide

### ISSUE THREAD

**Issue by GTGeek88** [dbeaver/dbeaver#34244] opened 2024-06-03 15:54 UTC
### Description

The pertinent message seems to be this:  !MESSAGE An error occurred while automatically activating bundle org.eclipse.ui.ide (168). 
[1717429382433.log](https://github.com/user-attachments/files/15536532/1717429382433.log)

### DBeaver Version

Seems to be 24.1.0.0 (Very latest - Just installed it)

### Operating System

Windows Server 2012 R2 Standard

### Database and driver

Postgres 9.5

### Steps to reproduce

Not sure, really, except that I just installed the latest update and when that was done and I tried to start DBeaver, it gave me the error I'm reporting.

### Additional context

On the update, I did go from a version that may have been 6 weeks old or so (maybe older) to the latest version, but I imagine that should not have been a problem. I have not uninstalled the product, but I did download the install program and ran it as administrator and I'm running the program as administrator (normally, I don't do that) and I'm still getting the error.

**Comment by E1izabeth** [comment] 2024-06-03 16:23
Thank you for bug report.

**Comment by serge-rider** [comment] 2024-06-03 16:27
We cannot reproduce it. But we've seen a similar issue in the latest version on Windows 8.
Is there anything specific in your Windows machine?

**Comment by GTGeek88** [comment] 2024-06-03 17:18
"Anything specific" is a bit vague. I'm not sure what you're thinking of, but it's just Win 11 Pro and I keep the updates applied. I don't have anything unusual in my configuration that I know of. As mentioned, I have only downloaded the update directly and reinstalled it. Though I think it may uninstall the old version before running (don't remember for sure at the moment), maybe that's my next step. Do a full uninstall and then reinstall. Also, is it possible there are some related issues in this report?: Dbeaver Eclipse compatibility #34240

**Comment by GTGeek88** [comment] 2024-06-03 17:30
Ugh! My apologies! I run DBeaver on various machines and servers and I'm doing the reporting here on my dev machine, which is Win11. However, this problem actually occurred on a server running Windows Server 2012 R2 Standard and I have updated the report with that information. As to the question about "anything specific" on that computer, I am not sure, since I don't really control that machine in relation to the OS, updates, and other config issues. But it's not unusual in any way that I am aware of. DBeaver had been running fine on it until I performed the update this morning. Again, maybe a full uninstall and reinstall is in order.

**Comment by E1izabeth** [comment] 2024-06-03 18:15
Thank you for update. If this happens on Windows Server 2012, then it's the same bug that we experienced on Windows 8. Reinstalling won't help, unfortunately.

**Comment by GTGeek88** [comment] 2024-06-03 18:23
I tried the previous version, 23.5 or something like that, and had the same problem. I'm looking to do a server reboot when we can to see if that helps. Is there a previous version that will work? Or is there a fix for this problem in this version? I'd like to get DBeaver back up and running. I was forced to use PgAdmin! I'd like to avoid that in the future.  :-)

**Comment by E1izabeth** [comment] 2024-06-03 18:54
This issue came to DBeaver from the Eclipse platform that we use. So, things like reinstall/reboot/... won't help. As far as I know, the latest version without this bug is 24.0.3

**Comment by E1izabeth** [comment] 2024-06-03 18:57
The same issue #34034

**Comment by GTGeek88** [comment] 2024-06-03 19:43
So you're working with the Eclipse developers to address it, I assume?

**Comment by serjiokov** [comment] 2024-06-04 07:24
The root cause of issue
```
java.lang.UnsatisfiedLinkError: Could not load SWT library. 
Reasons: 
	C:\Users\***\AppData\Local\DBeaver\swt-win32-4965r8.dll: The specified procedure could not be found
	no swt-win32 in java.library.path: 
```

**Comment by GTGeek88** [comment] 2024-06-04 14:00
I'm only a bit behind using 24.0.3, but I hope this means a fix for the more recent versions is coming soon.

**Comment by arhayka** [comment] 2024-06-17 18:34
Unfortunately, after upgrading to Eclipse 2024-06, the following OS are no longer supported: Windows 8, macOS 10, and Windows Server 2012. This issue is not on DBeaver side, you can see the details here: https://github.com/eclipse-platform/eclipse.platform.swt/issues/1252.

We have already added the system requirements to the download pages and [are working on ways to warn users before the update](https://github.com/dbeaver/dbeaver/issues/34315).
However, we will keep an eye on the situation and try to do something if possible.

I’m closing the current ticket as a duplicate: https://github.com/dbeaver/dbeaver/issues/34034

**Closed as not planned by arhayka** 2024-06-17 18:34 UTC
Labels: xp:major
