### ISSUE TITLE
Truncated DDL Text from a view definition

### ISSUE THREAD

**Issue by Vitor-Almeida** [dbeaver/dbeaver#20026] opened 2023-05-19 19:33 UTC
### Description

I'm getting a truncated text of the DDL of a view definition.
I'm using the tab "Declaration" in "View View" option when I right click a view in my DB.
If I run:

SELECT TEXT
FROM ALL_VIEWS
WHERE VIEW_NAME = "xxxx"

I also get a truncated version, if I use DbVisualizer, the query return in CLOB format, and I have to export to a .txt to get the full text

Is there any option where I can get a longer version of the written DDL?

My correct view DDL text is ~3k lines, but in Dbeaver I'm getting 700 lines.

### DBeaver Version

CE 23.04

### Operating System

Win 11

### Database and driver

Oracle 12.2.0.1

### Steps to reproduce

Generate a large Text from DDL of a view.

**Comment by LonwoLonwo** [comment] 2023-05-22 08:09
Hello @Vitor-Almeida 

Thanks for the bug report.

It is a duplicate of https://github.com/dbeaver/dbeaver/issues/15730. So I'm closing this ticket.

**Closed as completed by LonwoLonwo** 2023-05-22 08:09 UTC
Labels: x:oracle, duplicate, xf:metadata
