### ISSUE TITLE
Autocompletion don't remove typed text

### ISSUE THREAD

**Issue by fabianMendez** [dbeaver/dbeaver#4533] opened 2018-11-02 14:42 UTC
As the title says: 
![autocomplete](https://user-images.githubusercontent.com/32204060/47921849-94015f00-de83-11e8-8f8a-1af97d497e91.gif)

**Comment by serge-rider** [comment] 2018-11-02 14:47
Duplicate of #4475
I is already fixed in 5.2.3 hotfix (just re-download it from dbeaver.io)
thanks for bug report anyway

**Closed by serge-rider** 2018-11-02 14:47 UTC
Labels: bug, duplicate
