### ISSUE TITLE
DBeaver: the cursor disappears

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#10415] opened 2020-11-18 10:17 UTC
#### System information: 
- Windows 10 Pro x64
- DBeaver 7.2.5.202011152110
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5
- PostgreSQL JDBC Driver [42.2.5]
- No tunnels or proxies (SSH, SOCKS, etc)

#### Describe the problem you're observing:
After executing some queries, the cursor disappears from the editor

#### Steps to reproduce, if exist:
Execute query below step by step and try to move cursor by keyboard arrows between executions
```
create temp table tt(id int)

select *
from tt

insert into tt(id)
values(1),(2),(3)
```
[Video example in archive](https://github.com/dbeaver/dbeaver/files/5559302/2020-11-18.12-59-05-983.zip)

**Comment by amzbiz** [comment] 2020-11-19 00:49
Same issue, here:

Windows 10 Pro x64
DBeaver 7.2.5.202011152110
No additional extensions
PostgreSQL 9.6.18 / 9.6.15

Seems to happen more often when the sql file has a lot of queries in it (I'm selecting a single row to run it). I'm assuming it's related to the folding support. Can't see where to turn that off otherwise I'd test it with folding turned off to see if that resolves it.

**Comment by kyleflan** [comment] 2020-11-19 18:44
You can disable code folding by going to Windows -> Preferences -> Editors -> SQL Editor -> Code Editor and unchecking "Folding enabled". Unfortunately, this did not fix the issue of the cursor disappearing, even after restarting DBeaver.

![image](https://user-images.githubusercontent.com/5608074/99709546-ef9be680-2a64-11eb-986c-82a2d072d09f.png)

**Comment by kyleflan** [comment] 2020-11-19 18:53
I've found that right clicking in the left sidebar and toggling "Show script position" restores the cursor. I don't think that option specifically is impacting anything, I think it just causes something in the editor to reset.

![image](https://user-images.githubusercontent.com/5608074/99709966-97b1af80-2a65-11eb-805a-1c7d2c508817.png)

I've found that after doing this, the cursor persists until a query runs with an error. Upon the next query execution after an error, the cursor will disappear.

![K6i3f2lE9T](https://user-images.githubusercontent.com/5608074/99710367-13136100-2a66-11eb-88b8-4b4f7fbae365.gif)

**Comment by serge-rider** [comment] 2020-11-19 18:54
I think this issue was already fixed in #10067 
The problem was in focus change. In some cases focus was set into value view panel after query execution.

Workaround: close resultset panels (f7).

**Comment by serge-rider** [comment] 2020-11-19 18:54
You can check the fix in the Early Access version (https://dbeaver.io/files/ea)

**Comment by kyleflan** [comment] 2020-11-19 19:06
Closing the resultset panels didn't resolve it for me (I used Alt + 6 to switch the focus back to the editor from the Results pane).

EA seems to fix the issue.

**Comment by amzbiz** [comment] 2020-11-19 21:09
Yes closing the results set wouldn't work for me because I usually need to see the result of the first query to write / review the next one. The EA version seems to have resolved it though thanks @serge-rider

**Comment by jsteinfort** [comment] 2020-11-20 20:09
I'm noticing that the issue occurs when the panel at the bottom switches from Results to Statistics or vice versa.

I perform a "USE ..." statement followed by a "SELECT..." and the panel changes from Statistics to Results.  The cursor goes away at this point.

**Comment by mdahlman** [comment] 2020-11-22 15:40
Not to pollute this issue with a bunch of "Me too!" comments... 
but I confirm that this change/regression was a big annoyance in practical terms. And **I confirm that Alt + 6 is an excellent workaround.** (It's a good shortcut to learn in general!) I have not tested the early access build myself because the workaround is sufficient... but I'll be keen to grab the update once `brew upgrade dbeaver-community` picks it up.

**Comment by kseniiaguzeeva** [comment] 2020-11-24 10:59
verified

**Closed by kseniiaguzeeva** 2020-11-24 10:59 UTC
Labels: bug
