### ISSUE TITLE
Corrupt UI components after fresh install of v24.0.4

### ISSUE THREAD

**Issue by Calab** [dbeaver/dbeaver#32921] opened 2024-05-15 02:18 UTC
### Description

I just downloaded and installed DBeaver 24.0.4 on my Windows 11 23H2 build 22631.3527. There were no issues during the installation, but when I open DBeaver several of the UI components are corrupted.

![image](https://github.com/dbeaver/dbeaver/assets/316725/6464e200-887b-444a-9e4e-6bca0da05a13)

### DBeaver Version

24.0.4

### Operating System

Windows 11 23H2 build 22631.3527

### Database and driver

N/A

### Steps to reproduce

Download Windows installer. Run the setup program and install DBeaver. Open the newly installed DBeaver. Several of the UI components are corrupted, as in the image I attached.

![image](https://github.com/dbeaver/dbeaver/assets/316725/6464e200-887b-444a-9e4e-6bca0da05a13)

### Additional context

I have never had DBeaver installed on the PC before.

**Comment by E1izabeth** [comment] 2024-05-15 08:16
That is a known eclipse bug, that we can't fix unfortunately. It is connected to fonts installed on your computer. The workaround is to change theme to classic or manually change fonts.

**Comment by E1izabeth** [comment] 2024-05-15 08:17
I'm closing it as a duplicate of #9455

**Closed as not planned by E1izabeth** 2024-05-15 08:17 UTC
Labels: duplicate, xf:encoding
