### ISSUE TITLE
Ability to edit or create pgAgent jobs on a PostGreSQL server, when installed.

### ISSUE THREAD

**Issue by potterpg** [dbeaver/dbeaver#6262] opened 2019-07-11 09:13 UTC
Just annoying not to be able to edit and or create pgAgent jobs on a server that has it installed.
I use it all the time for automated database backups.

Just the ability to edit and create pgAgent jobs, and schedules etc.

It does work in pgAdmin4, but I use DBeaver for everything else, surely I can do this within DBeaver as well.

Has this been looked at before?
What is involved?

**Comment by uslss** [comment] 2020-12-11 00:42
duplicate of #6077

**Closed by uslss** 2020-12-11 00:42 UTC
Labels: feature request
