### ISSUE TITLE
Open Database Object Error

### ISSUE THREAD

**Issue by roberto2357** [dbeaver/dbeaver#3741] opened 2018-07-03 16:20 UTC
Hi,
I'm using DBeaver 5.1.2 and I have performed the followings steps:

(1) I have opened an Oracle connection.
(2) I have opened a table.
(3) I have used the "Open Database Object" utility (CTRL+SHIFT+D).
(4) I have written a char in the search field.

Then, DBeaver has shown me the error message:

![immagine](https://user-images.githubusercontent.com/22471800/42232037-898523d6-7eed-11e8-8fbe-a3c3d816fa56.png)

I believe it's a bug ;-)

**Comment by serge-rider** [comment] 2018-07-03 18:08
Yes, it is a bug. Duplicate of #3727
Thanks for report anyway

**Closed by serge-rider** 2018-07-03 18:08 UTC
Labels: bug, duplicate
