### ISSUE TITLE
Wrong Postgresql DDL for table with serial column

### ISSUE THREAD

**Issue by elring** [dbeaver/dbeaver#10372] opened 2020-11-16 08:35 UTC
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04
- DBeaver version: 7.2.5

#### Connection specification:
- Database name and version: Postgresql 12

#### Describe the problem you're observing:
When extracting DDL for table with serial type for primary key, it creates invalid DDL:

`CREATE TABLE public.testtable (
	id serial NOT NULL DEFAULT nextval('public.testtable_id_seq'::regclass),	
	testchar varchar NULL,
	CONSTRAINT testtable_pkey PRIMARY KEY (id)
);`

When running this SQL, Postgresql thows error:
`SQL Error [42601]: ERROR: multiple default values specified for column "id" of table "testtable"`

DDL should probably omit the DEFAULT nextval('xxxx'), because serial type automatically creates the default value and sequence OR the type should be changed to integer (and DDL for sequence should be included).

#### Steps to reproduce, if exist:

Create test table with this SQL:
`CREATE TABLE public.testtable (
	id serial NOT NULL,
	testchar varchar NULL,
	CONSTRAINT testtable_pkey PRIMARY KEY (id)
);`
Show DDL for this table a try to run it.

**Comment by LonwoLonwo** [comment] 2020-11-16 08:39
Thanks for the bug report.

**Comment by elring** [comment] 2020-11-16 08:46
Additional comments:
- the bug is also valid for bigserial and smallserial types
- i think DDL should change the type to integer and provide DDL for sequence (because the sequence could be with non-default sequence name 'tablename_colname_seq') - see recommeneded DDL in Postgresql doc [here](https://www.postgresql.org/docs/12/datatype-numeric.html#DATATYPE-SERIAL)

**Comment by elring** [comment] 2020-11-16 09:37
OK, you are right. I tried changing default value of serial column and it automagically converts to datatype integer. So you probably can't have serial type with non default sequence name.

**Comment by LonwoLonwo** [comment] 2020-11-18 14:18
Fixed in 7.3.0

**Comment by elring** [comment] 2020-11-18 18:50
Thanks :-)

**Comment by kseniiaguzeeva** [comment] 2020-11-24 06:51
verified

**Closed by kseniiaguzeeva** 2020-11-24 06:51 UTC
Labels: bug, x:postgresql

**Comment by ramirobarreca** [comment] 2021-08-10 13:11
Is it possible that this error is still happening for actual DBeaver versions?
* DBeaver: version 21.1.4
* DB: PostgreSQL 8.4
Tables created with a SERIAL datatype ar shown as VARCHAR instead of integer.  Either at the Columns list but also in the DDL code.
For newer PG versions (i.e. PG 11) it is shown OK.

**Comment by LonwoLonwo** [comment] 2021-08-12 13:22
Hello @ramirobarreca 
Could you please provide table DDL as an example? And some screens. I can't reproduce in DBeaver 21.1.4
