### ISSUE TITLE
Version 7.2.2.202010041557 any click on a connection opens connection settings [Mac]

### ISSUE THREAD

**Issue by dlamblin** [dbeaver/dbeaver#10086] opened 2020-10-16 14:11 UTC
#### System information: 
- Operating system (distribution) and version
Mac OS 10.14.6
- DBeaver version
7.2.2.202010041557
- Additional extensions

#### Connection specification:
- Database name and version
Mysql 5 and Mysql (8)
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
Socks proxy over ssh via jump-host bastion.

#### Describe the problem you're observing:

Starting with 4 connections behavior is good, you can right click or regular click on any connection in the left pane (either Projects or Database Navigator. Adding more than 5 though (and maybe related that I have a folder structure:
System Folder
 - Hourly Folder
   - RO Conn
   - RW Conn
 - Daily Folder
   - RO Conn
   - RW Conn
 - Test Folder
   - RO Conn
   - RW Conn

If I click on any connection it immediately opens Connection Settings dialog. This makes it hard to right click on it to connect or disconnect (if you're lucky the context menu will render over the dialog and is usable).
Sometimes after closing the dialog the connection will behave as if it were dragged and then it will randomly drop into the wrong folder.

This might have to do with using MacBook Pro with an external logitech keyboard and mouse.

Quitting DBeaver and reopening do not recover normal UI behavior.
Removing connections until there's only 1, 2 or 3 does… but I actually need many more.

**Comment by dlamblin** [comment] 2020-10-16 14:59
Do not see anything relevant in a log of start up, click on connection, get the settings to open (unintentionally/unwanted):
```
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.600.v20200116-2127]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.900.v20200213-1442]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.200.v20200127-0814]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start EMF Common [org.eclipse.emf.common 2.18.0.v20191225-1014]
> Start EMF Ecore [org.eclipse.emf.ecore 2.21.0.v20200127-1342]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.800.v20191212-1231]
> Start Expression Language [org.eclipse.core.expressions 3.6.700.v20200212-1751]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1100.v20200217-1217]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.800.v20191216-0805]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.15.500.v20200106-1259]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.900.v20200203-0840]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.12.600.v20200124-0005]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.57.202010041557]
> Start Eclipse SDK Themes [org.eclipse.ui.themes 1.2.900.v20200106-1021]
> Start Help System Core [org.eclipse.help 3.8.700.v20191212-1123]
> Start Default Text Editor [org.eclipse.ui.editors 3.13.100.v20200130-1507]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.14.100.v20200212-1049]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.42.202010041557]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.32.202010041557]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.42.202010041557]
> Start File Buffers [org.eclipse.core.filebuffers 3.6.900.v20200117-0616]
> Start Team Support Core [org.eclipse.team.core 3.8.900.v20200211-0946]
> Start Core Compare Support [org.eclipse.compare.core 3.6.800.v20191213-2246]
> Start DBeaver Tasks - General UI [org.jkiss.dbeaver.tasks.ui 1.0.20.202010041557]
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.6.300.v20200211-1504]
> Start Equinox Provisioning Operations API [org.eclipse.equinox.p2.operations 2.5.700.v20191211-1713]
> Start Equinox Provisioning Platform Automatic Update Support [org.eclipse.equinox.p2.ui.sdk.scheduler 1.4.600.v20200221-0754]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.4.700.v20191213-1911]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.300.v20200222-1600]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.6.600.v20200110-2121]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.400.v20191211-1528]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.4.700.v20200110-2121]
> Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.5.800.v20200213-1530]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.42.202010041557]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.79.202010041557]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.48.202010041557]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.2.202010041557]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.2.202010041557]
> Start Console [org.eclipse.ui.console 3.9.100.v20200215-1209]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.500.v20200114-1637]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.3.700.v20200212-0844]
> Start Internet Connection Management [org.eclipse.core.net 1.3.800.v20200218-0937]
> Start DBeaver MySQL Support [org.jkiss.dbeaver.ext.mysql 2.1.127.202010041557]
> Start DBeaver UI Editors - Connections [org.jkiss.dbeaver.ui.editors.connection 1.0.33.202010041557]
> Start DBeaver MySQL UI Support [org.jkiss.dbeaver.ext.mysql.ui 1.0.34.202010041557]
> Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh.ui 1.0.63.202010041557]
> Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh 1.0.63.202010041557]
```

**Comment by serge-rider** [comment] 2020-10-16 16:20
Can't reproduce.
But this may be a side effect of recently implemented feature (connection actions - tiny icons to the right of connection name).

Connection must be opened on the left click only. I've committed the fix (see it in the next version).

Workaround: disable action icons (context menu->Connection View->Show action icons).

**Comment by dlamblin** [comment] 2020-10-17 13:06
The workaround works it seems. Thanks. Can post a video showing it if you want.

**Comment by akilovich** [comment] 2020-11-24 15:35
Fixed.

**Comment by kseniiaguzeeva** [comment] 2020-11-26 07:43
@dlamblin Could you please try EA https://dbeaver.io/files/ea/?

**Closed** 2020-11-26 07:43 UTC
Labels: bug, xo:macos
