### ISSUE TITLE
[UI] dropdown color (blue color) not take full width

### ISSUE THREAD

**Issue by erlangparasu** [dbeaver/dbeaver#10443] opened 2020-11-20 01:27 UTC
#### System information: 
- Ubuntu 18
- DBeaver 7.2.5

#### Connection specification:
- Database MariaDB

#### Describe the problem you're observing:
dropdown color (blue color) not take full width
#### Steps to reproduce, if exist:
change ubuntu theme

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/20636828/99744334-722eaf80-2b12-11eb-8da9-20a8eff33859.png)

**Comment by uslss** [comment] 2020-11-25 10:10
hi @erlangp ,
what theme do you use?

**Comment by erlangp** [comment] 2020-11-25 16:10
sierra-light-solid

**Comment by uslss** [comment] 2020-12-21 18:06
Hi @erlangp ,
can you check if it is still reproducible against 7.3.1?

**Comment by erlangparasu** [comment] 2021-04-29 20:59
sorry but it is still on version 21

**Comment by E1izabeth** [comment] 2023-05-26 10:58
Does this issue still reproducible on the latest DBeaver version?

**Comment by E1izabeth** [comment] 2023-06-26 08:40
It's been a while since no update here, so I'm closing this issue.

**Closed by E1izabeth** 2023-06-26 08:40 UTC
Labels: bug, xp:minor, xo:linux, wait for response, xf:ui
