### ISSUE TITLE
Crash when updating data to NULL

### ISSUE THREAD

**Issue by DKhalil** [dbeaver/dbeaver#6931] opened 2019-10-07 13:32 UTC
#### System information: 
- Operating system (distribution) and version: Win10 x64
- DBeaver version: 6.2.2

#### Connection specification:
psql 9.6.3

#### Describe the problem you're observing:
Whenever I set a column to NULL and press enter DBeaver crashes (or just exits)

Installed 6.2.1 again, doesn't happen there so it's a 6.2.2 specific issue

#### Steps to reproduce, if exist:
Empty column in existing row set and press enter.

#### Include any warning/errors/backtraces from the logs
No crash logs found

**Comment by n8falke** [comment] 2019-10-07 15:08
Same problem with Oracle: Crash on pressing "Save" after changing value to "" or NULL.

#### System information: 
- Operating system: Windowns 10 x64
- DBeaver version: 6.2.2.201910061950

#### Connection specification:
- Database name and version: Oracle 12.1
- Driver name: Oracle 12.2

**Comment by serge-rider** [comment] 2019-10-07 15:23
Duplicate of #6928

**Closed by serge-rider** 2019-10-07 15:23 UTC
Labels: bug, duplicate
