### ISSUE TITLE
Oracle - Execute with sqlplus

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4896] opened 2019-01-02 19:17 UTC
Currently there is an option in the "Tools" menu for Oracle connections to execute a script with sqlplus. This option however requires you to select a file to be executed.
It would be a nice addition to be able to execute the **current** script with sqlplus, without needing to save it. Ideally a "Run with sqlplus" command should be added to the sqleditor context menu, to the left bar along with "Run", "Run script", etc. and it should be bindable to a keyboard shortcut. The script shall be executed with the current connection settings.

The button should be visible only if oracle client path is available to dbeaver. As an alternative, it should always be visible for Oracle connections, but it should return an error leading the user to the Oracle client configuration page (which could be a good way to let the user know that dbeaver supports this).

This would give an answer to all those needing support for sqlplus commands and sqlplus scripts. For example I'm able to use dbeaver in my development environment, but scripts to be executed in production database must be valid sqlplus scripts, so I need to test them before handing them to the DBAs.

**Comment by serge-rider** [comment] 2019-01-08 17:59
Agreed.

**Comment by colhndchck** [comment] 2019-04-24 18:45
Is there a chance this will get done in 6.0.4 release?

**Comment by iseehk** [comment] 2019-10-31 04:14
yes, Good suggestion. I want to execute `DESC table`.

**Comment by p91paul** [comment] 2020-11-10 23:32
Any chance this could come back to life?

**Comment by merlyn383** [comment] 2020-11-25 13:18
Seconded. I would greatly appreciate this ability as well.

**Comment by clabnet** [comment] 2021-02-18 12:31
Also for me it is a good idea.

**Comment by ufukbakan** [comment] 2022-12-13 11:25
why is this still not implemented. It's still a donkey job to describe a stored procedure in dbeaver in 2022.

**Comment by alligator999** [comment] 2023-02-01 21:32
(https://github.com/dbeaver/dbeaver/issues/18921) was marked as not planned. Basically no SQL Plus feature in DBevar is a no go for Oracle users. It's a shame.

**Comment by E1izabeth** [comment] 2023-02-01 22:15
@rd5802 it was marked as duplicate of this issue, because the request is the same as here

**Comment by alligator999** [comment] 2023-02-02 03:56
@E1izabeth , thats why I make my comments here. Anyways, is there a chance that you consider developing this functionality?  DBeaver is really great tool but for Oracle users SQL Plus is a must. I will not recomend to my company to buy this product until it's available.

**Comment by E1izabeth** [comment] 2023-02-02 05:40
@rd5802 as you can see, at this moment it's planned for 22.3.5

**Comment by alligator999** [comment] 2023-02-02 10:47
> @rd5802 as you can see, at this moment it's planned for 22.3.5

It`s been 4 years.. :)

**Comment by arhayka** [comment] 2023-04-17 09:34
We want to add the possibility to execute script with SQL plus from the context menu in Database Navigator and script context menu.

**Comment by alligator999** [comment] 2023-04-24 09:29
> We want to add the possibility to execute script with SQL plus from the context menu in Database Navigator and script context menu.

Great news !!!

**Closed** 2023-05-17 17:19 UTC
Labels: x:oracle, feature request, sp:3
