### ISSUE TITLE
Metadata search can't find comments

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13766] opened 2021-09-02 09:36 UTC
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.0

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
DB metadata search doesn't find a table by it's comment (also actual for procedures and other objects)

#### Steps to reproduce, if exist:
1. Copy a table comment to clipboard
2. Open DB Metadata search
3. Paste a comment into search field and check <kbd>Search in comments</kbd>
4. Start search

**Expected:** Table is found
**Actual:** Table is not found

![OC4vtphxLA](https://user-images.githubusercontent.com/82543000/131820680-d62eec58-3d75-4d97-bcd2-5de1d6d5ae23.gif)

**Comment by flambchap** [comment] 2021-09-03 09:32
Duplicate of https://github.com/dbeaver/dbeaver/issues/12143.

**Closed as completed by flambchap** 2021-09-03 09:32 UTC
Labels: duplicate, xf:metadata, xf:search
