### ISSUE TITLE
Script editor graphic rendering problem

### ISSUE THREAD

**Issue by acanbiler** [dbeaver/dbeaver#22813] opened 2024-02-13 20:24 UTC
### Description

While working on a script, clicking bottom two lines breaks the render and I saw below screen:
![Screenshot 2024-02-13 at 23 10 46](https://github.com/dbeaver/dbeaver/assets/94890976/f02d6da2-2da9-4d01-b79a-2f270381f045)

### DBeaver Version

Community Edition   23.3.2.202401072024

### Operating System

macOS Sonoma 

### Database and driver

PostgreSQL JDBC Driver

### Steps to reproduce

1. Open new script editor
2. Copy paste a query
3. Indent as shown in the screen shot
4. Go to the bottom line
5. Screen distorts

**Comment by E1izabeth** [comment] 2024-02-14 08:12
Thank you for bug report. It's a duplicate of #22299, so I'm closing this issue.
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-02-14 08:12 UTC
Labels: duplicate, xo:macos, xf:sql editor
