### ISSUE TITLE
Refresh output option

### ISSUE THREAD

**Issue by rscs** [dbeaver/dbeaver#2961] opened 2018-02-11 15:39 UTC
The "Refresh Rate" option in Workbench is nice to be able to automatically refresh the Sessions output every few seconds instead of manually.

**Comment by serge-rider** [comment] 2018-02-17 20:49
I like it

**Comment by serge-rider** [comment] 2018-02-23 10:42
Seems to be duplicate of #2050

**Closed by serge-rider** 2018-02-23 10:42 UTC
Labels: duplicate, feature request, good first issue
