### ISSUE TITLE
SSH Tunnel is not used by Oracle DB

### ISSUE THREAD

**Issue by adeorato** [dbeaver/dbeaver#8204] opened 2020-03-17 13:02 UTC
#### System information: 
- Operating system (distribution) and version WIN 10
- DBeaver version Version 7.0.0.202002292132

#### Connection specification:
- Database name and version: Oracle Oracle Database 12c
- Driver name: OJDBC 6
- Do you use tunnels or proxies (SSH, SOCKS, etc): Not working

#### Describe the problem you're observing:
When I build an SSH tunnel, this tunnel is created, but  DBeaver / Oracledoes not use this connection.
When I look at netstat, it shows a tunnel, but also a direct connection to the database. If the firewall blocks direct connections, the database connection is running in a timeout. Therefore, I assume that the SSH tunnel is established but not used.

Not: When there is another tunnel starting at localhost which is used as "oracle port" of course, this works. But this has nothing to do with the SSH tunnel then.

#### Steps to reproduce, if exist:
1. Create a db connection and choose SSH tunnel
2. Choose as IP the remote system where the SSH tunnel should end.
2. Start netstat

#### Include any warning/errors/backtraces from the logs
In the UI:
"Connection timed out: connect"

The error log "Window->Show View->Error Log" has no entries.

**Comment by serge-rider** [comment] 2020-03-20 11:10
Can't reproduce (we have a lot of test Oracle databases accessible thru SSH only).

Maybe you use wrong host name in database connection (this host name must be resolvable from your SSH server). Try to use `localhost` if Oracle server runs on the same machine as SSH server.

Also if you use any advanced settings like Remove/Local host - please check them too.

**Comment by adeorato** [comment] 2020-03-25 06:36
> Can't reproduce 

This is strange. I tried again with an Oracle I am allowed to connect directly using SSH tunnel. 
The assumption is: No direct connection, because everything should be over the tunnel.

But netstat showed
{code}
netstat -an | grep $IP_ORACLE
{code}
no connections before dbeaver startet, but after starting it showed two connections. Can you confirm / reproduce this?

> Maybe you use wrong host name in database connection (this host name must be resolvable from your SSH server). Try to use `localhost` if Oracle server runs on the same machine as SSH server.
> 

It is on a different machine. I connected to the SSH server manually and run there 
telnet $IP_ORACLE 1521
which worked fine. The JDBC string itself is fine, cause when I am within an allowed network (Oracle can be there connected directly) dbeaver connects. 

> Also if you use any advanced settings like Remove/Local host - please check them too.

Local port 3596, timeout, keepaplive is set as it was as default, remote port is 0, everything else is empty

**Comment by uslss** [comment] 2020-06-29 11:54
still cannot reproduce it against a recent version. Is it still actual for you?

**Comment by adeorato** [comment] 2020-07-20 09:18
Still happens with 7.1.3.
I attached as picture my "extending settings."
![config](https://user-images.githubusercontent.com/20139218/87921295-a5850300-ca7a-11ea-94cf-ead7b8c2a1ca.png)

**Comment by xumio** [comment] 2020-07-27 09:36
I'm having exactly the same problem as described in this bug report.
The ssh-tunnel is created successfully but not used for the connection to the database.

- Operating System: Windows 10 (version 2004, build 19041.388)
- DBeaver version: 7.1.3
- Database: Oracle Database 12c
- Driver: OJDBC 6 
- Tunnels or proxies (SSH, SOCKS, etc): Not working

**Comment by uslss** [comment] 2020-08-07 13:47
Does dbeaver throw any error after clicking on Test Tunnel configuration button?
![image](https://user-images.githubusercontent.com/31996417/89652121-a9fc4900-d8cd-11ea-8910-df16368000e4.png)

**Comment by adeorato** [comment] 2020-08-10 06:55
![grafik](https://user-images.githubusercontent.com/20139218/89757850-b7d8e680-dae6-11ea-9327-ee86ac060a32.png)
No like told. The tunnel is build, but I see in your configuration that you have "Remote host" empty. I thought there has to be the IP of the remote Oracle server.

Maybe something important: The SSH server is a "jump server". The oracle and the ssh server have a different IP. Can you try with a setup like this if this works for you (and block a direkt connection by firewall, cause this is my setup).

**Comment by serge-rider** [comment] 2020-08-10 07:55
What Oracle connection type do you use?
In current version SSH tunnel isn't used when you use TNS names or Custom URL (because dbeaver can't substitute target host and port number).
PR https://github.com/dbeaver/dbeaver/pull/9417 fixes this for the custom URLs (will be included in 7.1.5).

**Comment by adeorato** [comment] 2020-08-10 16:05
@serge-rider Thanks a lot. This was the problem. I used the custom jdbc string tab. Using the first tab everything worked fine. So this bug can be closed.

**Closed** 2020-08-11 13:45 UTC
Labels: bug, can't reproduce, wait for response

**Comment by gustavofcalmeida** [comment] 2021-02-26 23:15
My DBeaver is 7.2, I'm using the first tab, so no custom URL, but never managed to make it work. Always get a timeout.

My setting is this:

(1) Windows 10, Dbeaver 7.2
  --[ssh]-->
(2) Ubuntu server
  --[direct access]-->
(3) Windows server hosting Oracle

(2) and (3) are in the same network. I know (2) can access (3)s Oracle directly, because I use Java programs using the same drivers and JDBC URLs.

Interestingly, this setup works:

(1) Windows 10, DBeaver 7
  --[ssh]-->
(2) Ubuntu server
  --[direct access]-->
(3) Windows server hosting Oracle

In this case (1), (2) and (3) are in the same network. I mean, (1) can also connect directly to (3) as (2) does. This endorses what @adeorato said in his original post. DBeaver is ignoring the tunnel and just connecting directly, which in this setup, is possible.

**Comment by bentosming** [comment] 2021-11-12 09:48
I am having similar issues with dbeaver 3.7.6 and Windows 10 enterprise. (I cannot upgrade the dbeaver version).

Interestingly, I connect to several databases (oracle mostly), all of them need to jump through the same tunnel. Only one connection does not work. After some debugging with a network specialist, he believes that dbeaver constructs the tunnel, but it fails to use it and attempts the connection to db from the "local" machine (the one, where dbeaver runs).

I checked and the connection from the remote machine (the one we tunnel to) to the database works fine.
