### ISSUE TITLE
[Postgresql] request cancellation does not work

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#4407] opened 2018-10-16 09:19 UTC
Hello.
DBEaver 5.2.2, Windows 7 x64, Java 1.8.0_172 x64, Postgresql 9.5
The cancel request button does not work. When you click on the button, the application waits for the end of the query.
![img01](https://user-images.githubusercontent.com/22142845/47005826-45428e00-d13d-11e8-87f9-0d0c93c12186.JPG)

**Comment by serge-rider** [comment] 2018-10-16 09:43
Query cancel is broken in 5.2.2 (for all JDBC drivers).
Duplicate of #3094

**Closed by serge-rider** 2018-10-16 09:43 UTC
Labels: bug, duplicate
