### ISSUE TITLE
Export  table from MySQL to Oracle fails in DBeaver 5.1.5

### ISSUE THREAD

**Issue by JensCarlbergLiU** [dbeaver/dbeaver#4036] opened 2018-08-20 11:55 UTC
Works in 5.1.0

The Oracle error message is "ORA-00911: invalid character". It is localized for Sweden below in the log snippets.

From <workspace-path>/.metadata/.log:

!ENTRY org.jkiss.dbeaver.model 4 0 2018-08-20 10:54:30.853
!MESSAGE Error inserting row
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-08-20 10:54:30.853
!MESSAGE SQL Error [911] [22019]: ORA-00911: ogiltigt tecken

!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2018-08-20 10:54:30.853
!MESSAGE ORA-00911: ogiltigt tecken
0
java.sql.BatchUpdateException: ORA-00911: ogiltigt tecken

	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:12296)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:246)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeBatch(JDBCStatementImpl.java:386)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatementBatch(JDBCStatementImpl.java:156)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.flushBatch(ExecuteBatchImpl.java:267)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:137)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:79)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:198)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:187)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:146)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:68)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2018-08-20 10:54:30.853
!MESSAGE ORA-00911: ogiltigt tecken

From <workspace-path>/.metadata/dbeaver-debug.log:

2018-08-20 10:50:24.129 - Connect with 'TestDB' (oracle_thin-15c1a22faba-7c18ae9f7cb27faf)
2018-08-20 10:50:24.459 - Connected (oracle_thin-15c1a22faba-7c18ae9f7cb27faf, Oracle JDBC driver [12.1.0.2.0])
2018-08-20 10:54:30.774 - Error inserting row
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [911] [22019]: ORA-00911: ogiltigt tecken

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatementBatch(JDBCStatementImpl.java:159)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.flushBatch(ExecuteBatchImpl.java:267)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:137)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:79)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:198)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:187)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:146)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:68)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.sql.BatchUpdateException: ORA-00911: ogiltigt tecken

	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:12296)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:246)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeBatch(JDBCStatementImpl.java:386)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatementBatch(JDBCStatementImpl.java:156)
	... 12 more

Loggning Oracle, v. 5.1.5:

PARSE ERROR #139819089412280:len=124 dep=0 uid=124 oct=2 lid=124 tim=360329894499 err=911
INSERT INTO TENTAANM.SHEETDATA_TMP (ORDERID,SHEETROW,SHEETCOLUMN,SHEETDATA,ASSUID,UPDATER,UPDATETIME)
VALUES (?,?,?,?,?,?,?) 
 

Loggning Oracle, v. 5.1.0:

PARSING IN CURSOR #140167013836320 len=138 dep=0 uid=124 oct=2 lid=124 tim=360770030785 hv=3856439938 ad='6bc8f170' sqlid='cdc8hnbkxt6n2'
INSERT INTO TENTAANM.SHEETDATA_TMP (ORDERID,SHEETROW,SHEETCOLUMN,SHEETDATA,ASSUID,UPDATER,UPDATETIME)
VALUES (:1 ,:2 ,:3 ,:4 ,:5 ,:6 ,:7 )

**Comment by JensCarlbergLiU** [comment] 2018-08-24 10:55
Yes, it appears to be the same problem! I get the same error message in DBeaver. I haven’t traced it into the Oracle DB, though, so I can’t vouch for it to be exactly the same error, but it seems very likely.

Best regards
Jens Carlberg
System Developer

[Linköping University]

IT Department
SE-581 83 Linköping
Phone: +46 (0)13-281741
Visiting address: Galaxen, Camous Valla
Please visit us at www.liu.se<http://www.liu.se/>



Från: negora <notifications@github.com>
Skickat: den 24 augusti 2018 12:23
Till: dbeaver/dbeaver <dbeaver@noreply.github.com>
Kopia: Jens Carlberg <jens.carlberg@liu.se>; Author <author@noreply.github.com>
Ämne: Re: [dbeaver/dbeaver] Export table from MySQL to Oracle fails in DBeaver 5.1.5 (#4036)


Does this error also happen when you simply edit a cell in a table of the Oracle database? I'm trying to know whether one error that I get (since version 5.1.5) is related with yours... Thank you.

**Comment by negora** [comment] 2018-08-24 13:01
At work, I've not been able to trace the SQL queries passed to the Oracle Database server (I don't know much about this server, really). But viewing your first logs, it seems as if DBeaver had changed the way of setting the parameters of the prepared statements. From ordinal parameters to positional parameters (I guess that are the proper names). May that be the cause?

**Comment by JensCarlbergLiU** [comment] 2018-08-24 13:41
Yes, the query is obviously sent to the server with place holders, and Oracle recognize “:<number>” but not “?” as placeholders. Usually I would expect the Oracle JDBC driver to convert the “?” in the JDBC query string to the “:<number>” Oracle syntax.


Med vänlig hälsning
Jens Carlberg
Systemutvecklare

[Linköpings universitet]

IT-avdelningen
581 83 Linköping
Telefon: 013-281741
Besöksadress: Hus Galaxen, Campus Valla
Besök oss gärna på: www.liu.se<http://www.liu.se/>



Från: negora <notifications@github.com>
Skickat: den 24 augusti 2018 15:01
Till: dbeaver/dbeaver <dbeaver@noreply.github.com>
Kopia: Jens Carlberg <jens.carlberg@liu.se>; Author <author@noreply.github.com>
Ämne: Re: [dbeaver/dbeaver] Export table from MySQL to Oracle fails in DBeaver 5.1.5 (#4036)


At work, I've not been able to trace the SQL queries passed to the Oracle Database server (I don't know much about this server, really). But viewing your first logs, it seems as if DBeaver had changed the way of setting the parameters of the prepared statements. From ordinal parameters to positional parameters (I guess that are the proper names). May that be the cause?

**Comment by p91paul** [comment] 2018-08-25 09:52
I suggest you redownload and reinstall dbeaver 5.1.5. This appears to be the bug which was hotfixed a few hours after 5.1.5 release.

**Comment by JensCarlbergLiU** [comment] 2018-08-28 05:17
I wasn't aware there was a hotfix, but it sounds promising!

Alas, I won't be able to check this for a month due to sick leave, and after that I'm likely to upgrade to latest and greatest of dbeaver anyway. I think odds are excellent this is fixed, so if you want to go ahead and close the issue, that's ok with me.

Best regards,
///Jens Carlberg
________________________________

**Comment by serge-rider** [comment] 2018-08-28 05:48
Yep, duplicate of #3973

**Closed by serge-rider** 2018-08-28 05:48 UTC
Labels: bug, duplicate
