### ISSUE TITLE
IDE closes/crashes abruptly

### ISSUE THREAD

**Issue by reddyshyam** [dbeaver/dbeaver#7009] opened 2019-10-18 11:44 UTC
#### System information: 
- Operating system (distribution) and version -- Windows 10 Pro x64 1909 (18363.418)
- DBeaver version -- 6.2.2
- Additional extensions -- None

#### Connection specification:
- Database name and version -- Oracle 9i  and MySQL 5.7
- Driver name -- Dbeaver downloaded
- Do you use tunnels or proxies (SSH, SOCKS, etc)? -- SSH

#### Describe the problem you're observing:
DE closes/crashes abruptly when clicking on 'Save' button of Result Set window after data update. This has been happening since 6.2.0

#### Steps to reproduce, if exist:
Please see attached.
![DBeaver IDE closes abruptly](https://user-images.githubusercontent.com/12392746/67091571-9ced5c80-f1ca-11e9-8f64-4f3f487cd16a.gif)

Also nothing much on error log

**Comment by maciey** [comment] 2019-10-18 15:08
Same here.
I have downloaded and reinstalled 6.2.2 as recommended in other thread but didnt help

**Comment by DaniFarias** [comment] 2019-10-18 18:21
> Same here.
> I have downloaded and reinstalled 6.2.2 as recommended in other thread but didnt help
> DB Engine: PostgreSQL

I reported in another post the same problem, we are waiting for a fix.

**Comment by reddyshyam** [comment] 2019-10-19 05:01
> > Same here.
> > I have downloaded and reinstalled 6.2.2 as recommended in other thread but didnt help
> > DB Engine: PostgreSQL
> 
> I reported in another post the same problem, we are waiting for a fix.

Hi DaniFarias, 

Is there a issue id you are referring to above as reported and awaiting fix please? This is confirmed?

**Comment by serge-rider** [comment] 2019-10-21 08:18
Duplicate of #6928. Please upgrade to 6.2.3.

**Closed by serge-rider** 2019-10-21 08:18 UTC
Labels: bug, duplicate

**Comment by DaniFarias** [comment] 2019-10-21 13:28
> Duplicate of #6928. Please upgrade to 6.2.3.

Done, thanks for attention.
