### ISSUE TITLE
DBeaver hanging

### ISSUE THREAD

**Issue by merlyn383** [dbeaver/dbeaver#11217] opened 2021-02-03 15:52 UTC
#### System information: 
- Operating system (distribution) and version macOS, currently 10.15.7 (19H512)
- DBeaver version EE 7.3.0.202012061950
- Additional extensions

#### Connection specification:
- Database name and version Oracle 19c, 19.0.0.0.0
- Driver name Oracle JDBC driver 12.2.0.1.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
For the last 3 days DBeaver EE randomly hangs, seemingly from a runaway process. Activity monitor shows DBeaver using 99.7% of a CPU core. More often then not this seems to happen when opening a new tab but not always. Sometimes I'm in the middle of typing and it just freezes. Problem persists after reboots and an OS software update.

I've attached an automated log from Console generated because of the CPU hogging.
[dbeaver_2021-02-03-102335_ia-mac-ka38.cpu_resource.txt](https://github.com/dbeaver/dbeaver/files/5919692/dbeaver_2021-02-03-102335_ia-mac-ka38.cpu_resource.txt)

**Comment by serge-rider** [comment] 2021-02-10 13:03
It seems to be a bug in Eclipse SWT + BigSur. In some circumstances DBeaver starts to consume tons of memory (end eventually CPU).
This can be resolved by DBeaver restart. 
No known workarounds so far.

**Comment by merlyn383** [comment] 2021-02-10 14:11
I turned off an accessibility feature in the OS (Hover Text) and I haven't had it hang on me in the last 3 days. Correlation != Causation but I figured it was worth sharing. (System Preferences -> Accessibility -> Zoom -> "Enable Hover Text").

**Comment by serge-rider** [comment] 2021-02-15 09:23
Duplicate of #11089

**Closed as completed by serge-rider** 2021-02-15 09:23 UTC
Labels: xp:major, xo:macos
