### ISSUE TITLE
[PostgreSQL] Display default privileges in schema DDL

### ISSUE THREAD

**Issue by rbovard** [dbeaver/dbeaver#18854] opened 2023-01-24 09:31 UTC
**Is your feature request related to a problem? Please describe.**
In schema DDL, we can see the privileges but NOT default privileges, see discussion in https://github.com/dbeaver/dbeaver/issues/6565

**Describe the solution you'd like**
It would be great to also display default privileges on **tables**, **sequences**, **functions** and **types** in schema DDL:
`ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> GRANT <privilege> ON <objects> TO <who>;`

Examples:
- `ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO <role>;`
- `ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO <role>;`
- `ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> GRANT EXECUTE ON FUNCTIONS TO <role>;`
- `ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> GRANT USAGE ON TYPES TO <role>;`

**Describe alternatives you've considered**
pgAdmin display all these information.

**Comment by LonwoLonwo** [comment] 2023-01-24 10:53
Hello @rbovard 

Thanks for the idea.

Actually, this is a duplicate of https://github.com/dbeaver/dbeaver/issues/14804. So I'm closing this ticket. And I've added a priority label to the original ticket.

**Closed as not planned by LonwoLonwo** 2023-01-24 10:53 UTC
Labels: x:postgresql, xf:metadata
