### ISSUE TITLE
Execute query going beyond the instructions delimiter on the query that the cursor is in

### ISSUE THREAD

**Issue by apwinterjunior** [dbeaver/dbeaver#26868] opened 2024-04-26 12:58 UTC
### Description

When executing queries on the most recent version, it won't recognize the queries delimiters anymore;

Executing the first statment bellow if it has more queries before it, even with the instructions delimiter, will cause the error `Only one sql statement is allowed`.

select * from ipsum;

select * from lorem;

### DBeaver Version

24.0.3.202404211624

### Operating System

Windows 10 Pro

### Database and driver

![image](https://github.com/dbeaver/dbeaver/assets/16057873/a1ce39b9-4de4-49e3-8bf3-19e607d8e241)

### Steps to reproduce

Just hit CTRL+ENTER in the paragraph of code you want to execute.

**Comment by E1izabeth** [comment] 2024-04-26 13:01
Thank you for bug report. It's a duplicate of #26416
We're working on fix

As a workaround, you could try switching `Blank line is statement delimiter` setting to `Always`
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be8457a0-d62c-4acb-ac2f-67ce518cf3f5)

**Closed as not planned by E1izabeth** 2024-04-26 13:01 UTC
Labels: duplicate, xf:sql execution
