### ISSUE TITLE
Query Builder - wrong JOINs order

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#10284] opened 2020-11-09 10:40 UTC
#### System information: 
- Operating system (distribution) and version Kubuntu 20.04
- DBeaver version EE 7.2.0
- Additional extensions

#### Connection specification:
- Database name and version MariaDB 10.2.29
- Driver name MariaDB JDBC driver (I can't find information about version)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes, SSH

#### Describe the problem you're observing:
The JOIN statements are added to query in order of tables being added to Builder. It is not changed when defining relations between tables which may lead to "Unknown column ... in 'on clause' " error.

I think that the whole idea of Query Builder is to help people not entirely familiar with SQL in building queries, so tweeking SQL query should not be a solution here.

#### Steps to reproduce, if exist:
1. Add tables A, B and C to Query Builder (so it's "FROM A JOIN B JOIN C), in that order
2. Link a column from table A to column in table C
3. Link a column from table C to column in table B
4. Try to run query
5. Get an error "Unknown column C.some_column in 'on clause' "

**Comment by uslss** [comment] 2020-11-09 13:54
Hi @Speirs47 ,
thanks for the report.

Can you check if issue is reproducible for you against [EA version](https://dbeaver.com/files/ea/)?
Thanks in advance

**Comment by Speirs47** [comment] 2020-11-10 07:47
Yes, it is reproducible in EA version

**Comment by E1izabeth** [comment] 2023-05-26 14:57
Does it reproducible on the latest DBeaver version?

**Comment by E1izabeth** [comment] 2023-06-26 08:40
It's been a while since no update here, so I'm closing this issue. If it's still actual, please let me know.

**Closed by E1izabeth** 2023-06-26 08:40 UTC
Labels: bug, xf:sql, PRO, wait for response
