### ISSUE TITLE
Missing duplicate row shortcut icon

### ISSUE THREAD

**Issue by felangga** [dbeaver/dbeaver#7260] opened 2019-11-21 04:19 UTC
I'm using Dbeaver v6.2.5 Early version, sometimes duplicate row button on bottom appear and sometimes it doesn't. Is this on purpose ? or bugs? 

![image](https://user-images.githubusercontent.com/14814984/69303715-98481800-0c50-11ea-8697-b7f4b372b2e5.png)

**Comment by kseniiaguzeeva** [comment] 2019-11-21 07:33
Could you please provide more info? Which database do you use?

**Comment by cumanacr** [comment] 2019-11-21 18:33
Same here, version 6.2.5.201911171645 and also the **delete current record** button disappear, it's surely a bug because switching to another script tab all four buttons appear

**Comment by serge-rider** [comment] 2019-11-21 20:02
Can't reproduce.
@felangga @cumanacr What is your OS?

**Comment by cumanacr** [comment] 2019-11-21 20:58
Hi @serge-rider mine is Ubuntu based
```
lsb_release -a
LSB Version:    core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: neon
Description:    KDE neon User Edition 5.17
Release:        18.04
Codename:       bionic
```

**Comment by felangga** [comment] 2019-11-22 02:28
> Could you please provide more info? Which database do you use?

I'm using mysql and postgresql 

> Can't reproduce.
> @felangga @cumanacr What is your OS?

```
Distributor ID: neon
Description:    KDE neon User Edition 5.17
Release:        18.04
Codename:       bionic
```

**Comment by felangga** [comment] 2019-11-22 02:43
Sometimes the duplicate and delete button missing when I create new row using the Add record button and save using shortcut (CTRL+S) and suddenly it gone.

**Comment by cumanacr** [comment] 2019-11-22 02:49
I'm querying a MySQL table, the buttons disappear after I click any of their siblings buttons

**Comment by felangga** [comment] 2019-11-22 03:04
Resizing the window will bring back those buttons

**Comment by cumanacr** [comment] 2019-11-22 03:52
@felangga Yes it works, thank you very much for the workaround :+1:

**Comment by serge-rider** [comment] 2019-11-22 17:26
Unfortunately there are multiple glitches with data viewer toolbars on some KDE-based systems.
We will try to improve it next versions.

**Comment by sor-penteado** [comment] 2019-12-06 18:09
> Resizing the window will bring back those buttons



> Resizing the window will bring back those buttons

Thanks! nice workaround @felangga !

**Comment by felangga** [comment] 2019-12-07 13:15
No more glitches on latest stable version 6.3.0. I will closed this isseu

**Comment by sor-penteado** [comment] 2019-12-09 19:32
> No more glitches on latest stable version 6.3.0. I will closed this isseu

Actually it's still happening here with 6.3.0 on Linux... :(

**Comment by mann-ed** [comment] 2019-12-22 05:44
I am on Version 6.3.0.201912042122 with Linux Enlightenment Desktop 0.22.4 
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment 18.9 (build 11.0.5+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.5+10, mixed mode, sharing)
and am having the same issue. I was searching for the duplicate row button that lead me here.
Not sure if any of the above helps, but resizing the window does bring things back.

**Comment by uslss** [comment] 2019-12-22 11:22
https://dbeaver.testquality.com defect [D33](https://dbeaver.testquality.com/project/8805/result/1743383/defect/6068). Do not remove or edit.

**Comment by serge-rider** [comment] 2019-12-31 15:26
I can't reproduce it anymore on our test Linuxes.
Please test latest Early Access version (https://dbeaver.io/files/ea)
We've upgraded Eclipse platform there.

**Comment by negora** [comment] 2020-01-01 10:27
I've tested version 6.3.2.201912311500, and the `Delete current row` button **does not disappear,** after the first click on it, **anymore** ;-) . I've also tested the `Duplicate current row` button, with the same positive result.

By the way, I'm using Debian 10 (Buster) with KDE 5.14.

**Comment by uslss** [comment] 2020-01-03 12:24
![Screenshot 2020-01-03 15:20:51](https://user-images.githubusercontent.com/31996417/71723221-edc13880-2e3c-11ea-8350-32731937b704.png)
still reproducible for inactive button like Move to first(previous) row, fetch all/ fetch next page buttons

**Comment by serge-rider** [comment] 2020-01-05 18:04
@uslss as far a i see all enabled buttons are visible, at least.
Let's close this one and open a new ticket for invisible disabled buttons?

**Comment by uslss** [comment] 2020-01-07 14:56
#7561 created

**Closed by uslss** 2020-01-07 14:56 UTC
Labels: bug, xo:linux
