### ISSUE TITLE
Allow to execute script with output to file/one tab

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#16518] opened 2022-05-18 06:08 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes I want to generate a script from multiple commands' output but they open many tabs if I run them as a script.

**Describe the solution you'd like**
Add an Execute to file / single tab option

**Describe alternatives you've considered**
Running the commands in mysql shell.

**Comment by ShadelessFox** [comment] 2022-05-18 13:41
Hello @yoni-yad2,

Thanks for the feature request.

Closing as a duplicate of #667, please track the issue progress there.

**Closed as completed by ShadelessFox** 2022-05-18 13:41 UTC
Labels: duplicate, xf:sql, xf:data
