### ISSUE TITLE
Document Auto-Scrolls to End After Saving

### ISSUE THREAD

**Issue by Xylandor** [dbeaver/dbeaver#15581] opened 2022-02-21 21:46 UTC
#### System information: 
- OS:  MacOS Big Sur v11.4
- DBeaver version:  21.3.5.202202200327
- Additional extensions:  None

#### Connection specification:
- Local installation of MariaDb
- Driver name: MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Since the update to 21.3.5.202202200327, anytime you save changes to a script with many lines (vertical scroll bars active), it automatically scrolls to the end of the document. When you're working on a long script and save often, it can be aggravating to have to keep finding your spot where you were. Here's a vid to show what's happening:

https://user-images.githubusercontent.com/24617679/155029602-4a8bb839-9b0c-49f2-afb2-91678f046566.mov

#### Steps to reproduce, if exist:
1.  Create/Open a script that has many lines that require scrolling vertically through.
2. Make a change and save the document, using either by keyboard shortcut or through the File menu. The document should now be scrolled to the very end of it. 

Intended behavior is for the document to be saved without any scrolling; keeping the cursor where is should be.

#### Include any warning/errors/backtraces from the logs
No errors produced.

**Comment by ShadelessFox** [comment] 2022-02-22 00:15
Hello @Xylandor,

Thanks for the bug report.

Duplicate of #15562

**Closed as completed by ShadelessFox** 2022-02-22 00:15 UTC
Labels: duplicate
