### ISSUE TITLE
Close All tab closes the dbeaver app

### ISSUE THREAD

**Issue by Rahul-Bukuwarung** [dbeaver/dbeaver#26841] opened 2024-04-26 07:53 UTC
### Description

If you have multiple tables and sql scripts open, right clicking on table and choosing close all tabs will close the dbeaver and a macOs popup shows that dbeaver closed unexpectedly 

### DBeaver Version

DBeaver 24.0.3.202404211624

### Operating System

macOs Sonoma Version 14.4.1 

### Steps to reproduce

1. Click Windows -> Rest Perspective
2. Open any two scripts or tables 
3. Right click on ont of the scripts and click on close all

Dbeaver will close

**Comment by E1izabeth** [comment] 2024-04-26 07:55
Please provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by Rahul-Bukuwarung** [comment] 2024-04-26 09:02
I was able to reproduce the issue 3-5 times but not i am not able to :) 

Anyway here is the log i could find before i posted this issue

```
2024-04-26 12:54:30.918 - DBeaver 24.0.3.202404211624 is starting
2024-04-26 12:54:30.919 - OS: Mac OS X 14.4.1 (aarch64)
2024-04-26 12:54:30.919 - Java version: 17.0.6 by Eclipse Adoptium (64bit)
2024-04-26 12:54:30.919 - Install path: '/Applications/DBeaver.app/Contents/Eclipse'
2024-04-26 12:54:30.919 - Instance path: 'file:/Users/rahulnarang/Library/DBeaverData/workspace6/'
2024-04-26 12:54:30.920 - Memory available 74Mb/1024Mb
2024-04-26 12:54:30.928 - Initialize desktop platform...
2024-04-26 12:54:30.989 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.10.200.v20231102-0934]
> Start Core Resource Management [org.eclipse.core.resources 3.20.0.v20231102-0934]
> Start Team Support Core [org.eclipse.team.core 3.10.200.v20231106-1240]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.129.202404211624]
2024-04-26 12:54:36.094 - Initialize base platform...
2024-04-26 12:54:36.106 - Platform initialized (5178ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.129.202404211624]
2024-04-26 12:54:36.206 - Error accessing instance server: java.net.ConnectException
2024-04-26 12:54:36.215 - Starting instance server at http://localhost:59376
2024-04-26 12:54:36.218 - Run workbench
2024-04-26 12:54:36.218 - Create display
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.17.200.v20231030-2045]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.4.200.v20231103-2012]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.6.200.v20231030-2045]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.4.200.v20231030-2045]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.14.200.v20231030-2045]
> Start Eclipse e4 core commands [org.eclipse.e4.core.commands 1.1.200.v20231108-1058]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.36.0.v20231002-1156]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.5.200.v20231106-1600]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.16.200.v20231030-2045]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.18.100.v20231103-2012]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.15.200.v20231025-0632]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.14.200.v20230913-1724]
2024-04-26 12:54:37.047 - Configure workbench window
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.119.202404211624]
2024-04-26 12:54:37.106 - Total database drivers: 111 (111)
> Start Help System Core [org.eclipse.help 3.10.200.v20231106-1240]
2024-04-26 12:54:37.149 - Create actions
2024-04-26 12:54:37.152 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2024-04-26 12:54:37.152 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2024-04-26 12:54:37.153 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2024-04-26 12:54:37.153 - Create workbench actions
> Start jna [com.sun.jna 5.13.0.v20230812-1000]
2024-04-26 12:54:37.359 - Initialize workbench window
2024-04-26 12:54:37.362 - Finish initialization
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.17.200.v20231106-1600]
> Start Default Text Editor [org.eclipse.ui.editors 3.17.100.v20231106-1600]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.5.200.v20231106-1240]
> Start Internet Connection Management [org.eclipse.core.net 1.5.200.v20231106-1240]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.129.202404211624]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.166.202404211624]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.135.202404211624]
> Start GEF Classic Draw2d [org.eclipse.draw2d 3.14.100.202311222042]
> Start GEF Classic GEF (MVC) [org.eclipse.gef 3.16.0.202311222042]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.89.202404211624]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.89.202404211624]
> Start DBeaver Dashboard UI [org.jkiss.dbeaver.ui.dashboard 1.0.126.202404211624]
> Start DBeaver Dashboards Model [org.jkiss.dbeaver.model.dashboard 1.0.2.202404211624]
2024-04-26 12:54:37.802 - Connect with 'accounting' (postgres-jdbc-18f150098e3-4f283c7a2f4727e2)
> Start DBeaver JDBC Model [org.jkiss.dbeaver.model.jdbc 1.0.22.202404211624]
> Start DBeaver PostgreSQL Model [org.jkiss.dbeaver.ext.postgresql 2.1.202.202404211624]
> Start DBeaver GIS Support [org.jkiss.dbeaver.data.gis 1.0.153.202404211624]
2024-04-26 12:54:37.833 - Execution context opened (accounting; Main <accounting>; 0)
2024-04-26 12:54:37.834 - Initiate connection to PostgreSQL database [accounting@host] for Main <accounting>
2024-04-26 12:54:39.087 - Execution context opened (accounting; Metadata <accounting>; 1)
2024-04-26 12:54:39.088 - Initiate connection to PostgreSQL database [accounting@host] for Metadata <accounting>
2024-04-26 12:54:40.351 - Connected (postgres-jdbc-18f150098e3-4f283c7a2f4727e2, PostgreSQL JDBC Driver [42.5.2])
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.129.202404211624]
> Start DBeaver PostgreSQL UI [org.jkiss.dbeaver.ext.postgresql.ui 1.0.105.202404211624]
> Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.8.200.v20231105-1139]
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.10.200.v20231102-1258]
> Start Equinox Provisioning Operations API [org.eclipse.equinox.p2.operations 2.7.200.v20231105-1139]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.9.0.v20231105-1139]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.8.0.v20231102-1258]
> Start Equinox Provisioning Platform Update Support [org.eclipse.equinox.p2.ui.sdk 1.3.200.v20230921-0854]
> Start Equinox Provisioning Director [org.eclipse.equinox.p2.director 2.6.200.v20231021-1906]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.5.200.v20231021-1438]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.8.0.v20231111-1058]
> Start Core Compare Support [org.eclipse.compare.core 3.8.300.v20231106-1240]
> Start Compare Support [org.eclipse.compare 3.9.300.v20231123-2204]
> Start Equinox Provisioning Extension Location Repository Support [org.eclipse.equinox.p2.extensionlocation 1.5.200.v20230914-2056]
> Start Equinox Provisioning Eclipse Touchpoint [org.eclipse.equinox.p2.touchpoint.eclipse 2.4.100.v20230630-1506]
> Start Equinox Provisioning Artifact Repository Support [org.eclipse.equinox.p2.artifact.repository 1.5.200.v20231105-1139]
> Start Equinox Provisioning Legacy Update Site Support [org.eclipse.equinox.p2.updatesite 1.3.200.v20231008-1114]
> Start Equinox Provisioning Publisher Infrastructure [org.eclipse.equinox.p2.publisher 1.9.0.v20230921-2011]
> Start Equinox Provisioning ECF based Transport [org.eclipse.equinox.p2.transport.ecf 1.4.100.v20230630-1506]
> Start ECF Filetransfer API [org.eclipse.ecf.filetransfer 5.1.103.v20230705-0614]
> Start Equinox Provisioning Directory Watcher [org.eclipse.equinox.p2.directorywatcher 1.4.200.v20230921-2011]
> Start Equinox Provisioning Publisher for Eclipse [org.eclipse.equinox.p2.publisher.eclipse 1.5.200.v20231105-1123]
> Start Equinox Security Default UI [org.eclipse.equinox.security.ui 1.4.100.v20231103-0809]
> Start DBeaver Tasks View [org.jkiss.dbeaver.tasks.ui.view 1.0.78.202404211624]

```

**Comment by E1izabeth** [comment] 2024-04-26 10:44
Are there any fatal logs named `hs_err_PID.log`?
https://dbeaver.com/docs/dbeaver/Log-files/#java-fatal-logs

**Comment by Rahul-Bukuwarung** [comment] 2024-04-29 12:00
Couldn't find one

**Comment by flambchap** [comment] 2024-05-07 10:24
@Rahul-Bukuwarung Unfortunately, I cannot reproduce it on the latest version (24.0.4). Was it a one-time thing, or is it reproducible all the time?

**Comment by Rahul-Bukuwarung** [comment] 2024-05-07 11:31
It was a one time thing i guess, even i could't reproduce it after first 3-4 times

**Comment by E1izabeth** [comment] 2024-05-07 11:49
Unfortunately, we can't fix the issue without reproduce or any diagnostics info. Let's close the issue for now. If you'll experience this bug again, let me know.

**Closed as not planned by E1izabeth** 2024-05-07 11:49 UTC
Labels: can't reproduce, xo:macos

**Comment by serge-rider** [comment] 2024-05-23 05:39
Probably fixed in https://github.com/dbeaver/dbeaver/issues/19526
