### ISSUE TITLE
Incompatible JVM: Version 1.8.0_361 of the JVM is not suitable for this product. Version: 11 or greater is required.

### ISSUE THREAD

**Issue by ray-magini** [dbeaver/dbeaver#18991] opened 2023-02-07 13:36 UTC
### Description

I have installed DBeaver CE via the windows store.  
Since the latest updated (today) to 22.3.4.0 I am getting the following error after starting DBeaver CE:  

Incompatible JVM - Version 1.8.0_361 of the JVM is not suitable for this product. Version: 11 or greater is required.

See: https://github.com/dbeaver/dbeaver/issues/15213#issuecomment-1419834838

![image](https://user-images.githubusercontent.com/18124805/217259053-913482c5-cdc9-4c53-a578-a9eeb3a4857a.png)

Java is installed as well:  
![image](https://user-images.githubusercontent.com/18124805/217260689-040f5b63-1102-4ced-80d9-6ab4d6de1fa4.png)

### DBeaver Version

22.3.4.0

### Operating System

Windows 10

### Steps to reproduce

1. Install/Update DBeaver CE via the windows store
2. Start it

**Comment by ShadelessFox** [comment] 2023-02-07 16:03
Hello @ray-magini,

Thanks for the bug report. This is a known issue in the latest release.

As a workaround, you can either download DBeaver from https://dbeaver.io/files or install JRE 11 or greater.

Closing as a duplicate of https://github.com/dbeaver/dbeaver/issues/18960

**Closed as not planned by ShadelessFox** 2023-02-07 16:03 UTC
Labels: duplicate, xo:windows, xf:packaging
