### ISSUE TITLE
SQL Server Tables Not Displaying in Navigator

### ISSUE THREAD

**Issue by jhughe25** [dbeaver/dbeaver#6446] opened 2019-08-05 19:17 UTC
#### System information: 
- Operating system (distribution) and version: Windows 7 Pro
- DBeaver version: 6.1.4
- Java version:  8
- Additional extensions

#### Connection specification:
- Database name and version: Microsoft SQL Server
- Driver name: JDBC Driver for SQL Sever
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
In 6.1.4, clicking on "Tables" in Database Navigator won't open up the table tree. I can double-click the Tables folder and see the table list, but I don't get the tree. This is only an issue for my SQL Server connections, my Oracle works just fine. 

I've also confirmed reverting to 6.1.3 brings the tree back up.

**Comment by serge-rider** [comment] 2019-08-05 21:00
Could you check error/debug logs |(https://github.com/dbeaver/dbeaver/wiki/Log-files) and post them here (if there is anything related).

**Comment by serge-rider** [comment] 2019-08-05 21:57
Also:
- What SQL Server version do you use?
- What DBeaver driver do you use (Microsoft or jTDS)?

**Comment by jhughe25** [comment] 2019-08-06 12:33
I reinstalled 6.1.4 this morning and it's working now. I did go back through the logs and found a couple of things that may help, see the entries below. For your other questions:

- Microsoft SQL Server 2008 (SP3): 10.0.5500.0
- I'm using the Microsoft DBeaver driver


!SESSION 2019-08-05 07:55:58.024 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 2 0 2019-08-05 08:10:10.223
!MESSAGE Listener org.jkiss.dbeaver.ui.editors.DatabaseEditorListener@70799ca7 wasn't registered in model

!ENTRY org.jkiss.dbeaver.model 4 0 2019-08-05 08:10:10.316
!MESSAGE Error adding nested editor
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-08-05 08:10:10.316
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.eclipse.ui.part.MultiPageEditorSite.<init>(MultiPageEditorSite.java:139)
	at org.eclipse.ui.part.MultiPageEditorPart.createSite(MultiPageEditorPart.java:492)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:237)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:214)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.addEditorTab(EntityEditor.java:758)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.createPages(EntityEditor.java:547)
	at org.jkiss.dbeaver.ui.editors.MultiPageAbstractEditor.recreatePages(MultiPageAbstractEditor.java:193)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.recreateEditorControl(EntityEditor.java:896)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart.initEntityEditor(ProgressEditorPart.java:109)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart.access$2(ProgressEditorPart.java:103)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.completeLoading(ProgressEditorPart.java:154)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.completeLoading(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob$LoadFinisher.run(LoadingJob.java:126)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:238)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-08-05 08:10:10.406
!MESSAGE Error adding nested editor
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-08-05 08:10:10.406
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.eclipse.ui.part.MultiPageEditorSite.<init>(MultiPageEditorSite.java:139)
	at org.eclipse.ui.part.MultiPageEditorPart.createSite(MultiPageEditorPart.java:492)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:237)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:214)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.addEditorTab(EntityEditor.java:758)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.addContributions(EntityEditor.java:741)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.createPages(EntityEditor.java:560)
	at org.jkiss.dbeaver.ui.editors.MultiPageAbstractEditor.recreatePages(MultiPageAbstractEditor.java:193)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.recreateEditorControl(EntityEditor.java:896)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart.initEntityEditor(ProgressEditorPart.java:109)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart.access$2(ProgressEditorPart.java:103)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.completeLoading(ProgressEditorPart.java:154)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.completeLoading(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob$LoadFinisher.run(LoadingJob.java:126)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:238)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-08-05 08:10:10.494
!MESSAGE Error adding nested editor
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-08-05 08:10:10.494
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.eclipse.ui.part.MultiPageEditorSite.<init>(MultiPageEditorSite.java:139)
	at org.eclipse.ui.part.MultiPageEditorPart.createSite(MultiPageEditorPart.java:492)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:237)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:214)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.addEditorTab(EntityEditor.java:758)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.addContributions(EntityEditor.java:741)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.createPages(EntityEditor.java:564)
	at org.jkiss.dbeaver.ui.editors.MultiPageAbstractEditor.recreatePages(MultiPageAbstractEditor.java:193)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.recreateEditorControl(EntityEditor.java:896)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart.initEntityEditor(ProgressEditorPart.java:109)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart.access$2(ProgressEditorPart.java:103)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.completeLoading(ProgressEditorPart.java:154)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.completeLoading(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob$LoadFinisher.run(LoadingJob.java:126)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:238)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)

!ENTRY org.jkiss.dbeaver.model 2 0 2019-08-05 10:45:06.272
!MESSAGE Listener 'org.jkiss.dbeaver.ui.editors.DatabaseEditorListener@eb23b5d' is not unregistered from DBM model
!SESSION 2019-08-05 10:47:43.758 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by serge-rider** [comment] 2019-08-06 13:01
These error looks like some kind of glitch. Quite unusual, most likely something went wrong with workspace configuration, probably the glitch with navigator tree had the same nature.
Thanks for the information.
Closing as non-reproducible.

**Closed by serge-rider** 2019-08-06 13:01 UTC
Labels: bug, can't reproduce, x:mssql
