### ISSUE TITLE
Foreign keys can't be set bec. no unique key detected (PostgreSQL)

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#6188] opened 2019-06-29 08:10 UTC
#### System information: 
- Windows 10
- DBeaver Enterprise 6.1.0 (latest)

#### Connection specification:
- Database: PostgreSQL 11 via https://www.heroku.com/postgres
- Driver name: PostgreSQL

#### Describe the problem you're observing:
I'm unable to create foreign keys via the UI if I want to match two ids for example two int8 fields. According to the DBeaver UI, there is no unique key found for the referenced table but this is wrong: There are primary keys set and even a non-primary key field with unique attribute is not detected. If I try to create a foreign key via a SQL command, it works fine.

#### Steps to reproduce, if exist:
Create two tables and try to make a foreign key relationship between them.

**Comment by serge-rider** [comment] 2019-07-23 17:17
Can't reproduce this

**Comment by serge-rider** [comment] 2019-07-24 12:27
Could you post DDL of such table ?

**Comment by GiantCrocodile** [comment] 2019-07-25 09:45
More information has been provided via email.

**Comment by serge-rider** [comment] 2019-07-25 09:47
Thanks, that helped.
The problem was in unique constraints detection. Your schema doesn't have any unique constraints but there are unique indexes instead (quite unusual but still legal way to implement RI).
There was a bug in foreign key dialog so all unique indexes were ignored.
Now fixed.

**Comment by GiantCrocodile** [comment] 2019-07-25 09:51
Thanks @serge-rider!

**Comment by kseniiaguzeeva** [comment] 2019-08-02 10:21
Verified (some nuances are possible when two tables are created at the same time)

**Closed by kseniiaguzeeva** 2019-08-02 10:21 UTC
Labels: bug, x:postgresql
