### ISSUE TITLE
Data Export to XLSX via latest Office Plugin doesn't work with Version 21.2 & 22.2

### ISSUE THREAD

**Issue by fabian-s-123** [dbeaver/dbeaver#16300] opened 2022-04-25 11:25 UTC
Hi, 
export to XLSX format doesn't work anymore with latest Office Plugin (1.1.117) and DBeaver Version 21.2 & 22.2.
For Version 21.2: cannot move past the second to last step in the export dialog.
For Version 22.2: receive multiple errors when proceeding to last step in export dialog.
![image](https://user-images.githubusercontent.com/55379268/165079428-2123298f-da6a-4562-9220-77df7840f4a3.png)

I have attached the complete error logs from the version 22.2. Curios is this line: 

java.lang.ClassNotFoundException: org.jkiss.dbeaver.tools.transfer.stream.IAppendableDataExporter cannot be found by org.jkiss.dbeaver.data.office_1.1.118.202204170718

The version of the plugin referenced here does not match the version of the installed plugin.

DBeaver Versions tested:

- 21.2.0.202108291732
- 22.0.2.202204041542

Office Plugin Version:
- 1.1.117.202204170718

OS System:
Windows 10 Enterprise 10.0.19044

[21_2_error.log](https://github.com/dbeaver/dbeaver/files/8554011/21_2_error.log)

**Comment by ShadelessFox** [comment] 2022-04-25 12:10
Hello @fabian-s-123,

Could you please download the latest EA version and see if the issue is gone there? https://dbeaver.io/files/ea/

**Comment by fabian-s-123** [comment] 2022-04-28 08:16
Hi @ShadelessFox,

yes, with the latest EA version it works again. In the meantime, I have also tested it with the version 22.0.3. and can confirm that it works with this version as well. So we'll most likely have to update to version 22.0.3.

**Comment by ShadelessFox** [comment] 2022-04-28 08:20
There were some changes to the Office plugin. It may be the reason why it stopped working on an older version.

If your issue is solved, please close it.

**Closed as completed** 2022-05-02 06:42 UTC
Labels: xf:datatransfer
