### ISSUE TITLE
Window increases in size and moves to another display when dumping a database

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35859] opened 2024-10-07 17:56 UTC
### Description

The window grows in size beyond the size of the screen.
If you have more than one display, it also moves to another display.

https://github.com/user-attachments/assets/a329b046-7208-4803-b47a-7e414b4c24a4

### DBeaver Version

Enterprise Edition 24.2.3-202410032322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by E1izabeth** [comment] 2024-10-10 09:42
Thank you for bug report.

**Comment by E1izabeth** [comment] 2024-10-10 09:50
I'm closing it as it's a duplicate of #34861

**Closed as not planned by E1izabeth** 2024-10-10 09:50 UTC
Labels: duplicate, xf:datatransfer, xf:ui
