### ISSUE TITLE
 You want to add the sorting function of the record view

### ISSUE THREAD

**Issue by z-hanzhe** [dbeaver/dbeaver#18682] opened 2023-01-06 00:52 UTC
The content uses translation software

In previous versions, fields can be sorted by switching to the record view after opening a table. This function can quickly find the target field when there are many fields in the table. However, after updating the version to 22.3.1.202212251901, it is found that this function is missing. I hope it can be added back

![图片](https://user-images.githubusercontent.com/58802604/210907494-4f71f1b2-9e10-40df-a6c6-20b6c84ec706.png)

**Comment by LonwoLonwo** [comment] 2023-01-06 10:50
Thanks for the report.
This is duplicate of https://github.com/dbeaver/dbeaver/issues/18618

**Closed as not planned by LonwoLonwo** 2023-01-06 10:50 UTC
Labels: duplicate, xf:data
