### ISSUE TITLE
Data results panel doesn't add or update horizontal scrollbar upon column resize

### ISSUE THREAD

**Issue by givihuda** [dbeaver/dbeaver#13971] opened 2021-09-21 18:32 UTC
#### System information: 
- Operating system (distribution) and version Mac OS Big Sur 11.6
- DBeaver version Version 21.2.0.202108291732
- Additional extensions ?

#### Connection specification:
- Database name and version doesn't matter
- Driver name not applicable
- Do you use tunnels or proxies (SSH, SOCKS, etc)? not applicable

#### Describe the problem you're observing:

Resizing data columns (like double-clicking their dividers) doesn't add or change the horizontal scroll bar, so it's impossible to scroll further to the right if resizing expands the full width of the view box. I have to resize the viewbox to get the scrollbar to become up to date.

#### Steps to reproduce, if exist:
Run a query in a small viewport; look at the data and notice the columns are too small, truncating or hiding the column names or values; resize the columns so you can read them; notice there's either no horizontal scrollbar to view the expandd columns, or it doesn't adjust so you can't scroll further to the right; resize the window horizontally so the scrollbar updates; scroll the bar to see the text to the right.

**Comment by uslss** [comment] 2021-09-22 18:27
thanks for the report

![fGSDErqK3N](https://user-images.githubusercontent.com/31996417/134400788-810a8ddd-b246-42da-b905-8f4d901cb2cf.gif)

**Comment by givihuda** [comment] 2021-09-22 19:28
@uslss Thanks for adding an animation... I'm not sure how to do this (though I also can't show proprietary company info).

Would you leave instructions for how you made the animated screenshot? I could probably use that at times for issues or discussions.

**Comment by ShadelessFox** [comment] 2021-12-08 14:35
Duplicate of #12319.

**Closed as completed by ShadelessFox** 2021-12-08 14:35 UTC
Labels: duplicate, xf:data, xf:ui
