### ISSUE TITLE
same query on different data sources

### ISSUE THREAD

**Issue by TheUnableDeveloper** [dbeaver/dbeaver#36565] opened 2024-12-16 15:54 UTC
Hello!

I work on multi-tenants applications every day and, when I try to debug or check differences between databases, I always have the need to run the same queries on different customers (different mysql instances in this case).

CURRENT SITUATION
I usually open different scripts editors inside DBeaver and I copy-paste and run the queries.
But it takes a lot of time, and the "Tasks" that DBeaver already provides, doesn't show the result sets in case of SELECT statements.
They also require to create a task, configure it and so on.. too much time for me because I don't need to save those queries.

IDEA / DESIRED STATE
1. Within one single script editor (doesn't matter which connection is active for that editor), 
I write a query (both read/write queries)
2. using a new shortcut, a searchable drop-down list appears , which contains the connections where I could use directly keyboard's arrows and space buttons to move up and down to select (also mouse of course but keyboard would be quicker)
3. By clicking enter from inside the dropdown list, it will execute the query on the selected connections and they will be saved for further queries in the same editor
4. one tab of result sets will be open for each connection selected showing the output

I hope this could be implemented because it would save me a lot of time

Thank you in advance!

**Comment by E1izabeth** [comment] 2024-12-17 11:59
Thanks for the idea and detailed description of your vision of this feature!
I'm closing it as a duplicate of #34071
Please follow the mentioned issue to get notified about the updates. Also, I would recommend voting for the issue with 👍🏻 to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-12-17 11:59 UTC
Labels: duplicate, xf:ui, xf:sql editor, xf:sql execution
