### ISSUE TITLE
Filter in [mariadb/mysql] `show processlist` returns "funny" error

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#16452] opened 2022-05-11 09:32 UTC
Running
`show processlist`
and then filtering the datagrid with whatever returns
`QL Error [1064] [42000]: (conn=714972276) You have an error in your SQL syntax` etc etc etc, since what the filter tryes to do is
```
SELECT * FROM (
show  processlist
) z_q WHERE meh =1
```
which is... wrong :-)

Maybe, avoid the use of the filter in queries like those, or "trap" the error and show "you canz no do dat"

**Comment by ShadelessFox** [comment] 2022-05-11 14:50
Hello @wiwwo,

I don't think we should restrict users from doing that. This behavior may depend on the database version. In the future, this syntax may be allowed.

As for the other `SHOW` variants, some support the `WHERE` clause, such as [`SHOW STATUS`](https://dev.mysql.com/doc/refman/8.0/en/show-status.html). We can support them, at least.

For now, I am closing as a duplicate of #9968.

**Closed as completed by ShadelessFox** 2022-05-11 14:50 UTC
Labels: x:mysql, duplicate, xf:sql, xf:filters
