### ISSUE TITLE
Not able to configure AWS Redshift DB with DBeaver update 23.2.1

### ISSUE THREAD

**Issue by rishabhjhs56** [dbeaver/dbeaver#21375] opened 2023-09-29 09:34 UTC
### Description

While setting up AWS Redshift DB on DBeaver( v23.2.1), I am getting below error and due to which not able to use Redshift DB.
`ERROR: relation "pg_catalog.pg_enum" does not exist`
![image](https://github.com/dbeaver/dbeaver/assets/49242674/70115c63-6f83-4f35-a98c-9fdb47249e0c)

Kindly please help and look into it.

### DBeaver Version

23.2.1

### Operating System

macOS ventura 13.6

### Database and driver

Amazon Redshift

### Steps to reproduce

Just setup any Redshift DB cluster and do the 'Test Connection'. This error will come.
 

### Additional context

I am using SSH tunnel for configuring Redshift

**Comment by E1izabeth** [comment] 2023-09-29 09:36
Thanks for the report.

This is a duplicate of #21293

Rerelease is available at https://dbeaver.io/files/23.2.1/

**Closed as not planned by E1izabeth** 2023-09-29 09:36 UTC
Labels: duplicate
