### ISSUE TITLE
SQL column value auto-completion issues

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11977] opened 2021-04-02 13:40 UTC
Column completion improvements should be made:
1. Auto-assist doesn't show integer values out of the first limited batch.
https://user-images.githubusercontent.com/51405061/113176784-879cae80-9255-11eb-9372-a0868955d210.mp4

2. Auto-assist list jumps to its beginning when you scroll to its end
https://user-images.githubusercontent.com/51405061/113176926-aa2ec780-9255-11eb-876b-49de6787e428.mp4

3.  Auto-assist shows a column value out of the first limited batch only where there are not matches in the list
https://user-images.githubusercontent.com/51405061/113175898-9b93e080-9254-11eb-8e3f-60c878f4960d.mp4

4. Auto-assist begins to show table columns instead of column values when you open Auto-assist list for a parsed value and delete its letter.
https://user-images.githubusercontent.com/51405061/113179819-afd9dc80-9258-11eb-9ce3-3ed02a170cd9.mp4

5. Auto-assist doesn't work for column names with spaces
https://user-images.githubusercontent.com/51405061/113577016-3f043d00-9629-11eb-89ca-8c2b19cf39a5.mp4

**Comment by serge-rider** [comment] 2021-06-23 11:44
1 Fixed
2 Can't reproduce  
3,4. Technically not a bug because further filtering happens only within already found proposals. To trigger search on server side you need to press ctrl+space again.
5 Fixed in #12044

**Comment by uslss** [comment] 2021-06-24 10:15
verified

**Closed as completed by uslss** 2021-06-24 10:15 UTC
Labels: xf:sql, sp:3
