### ISSUE TITLE
Export data/Table from one dbase to another

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#19351] opened 2023-03-13 14:56 UTC
### Description

I am failing to move large  tables using GUI which are sometimes 500MB or 1GB or over....it loads partially then halts the process.

### DBeaver Version

222.3.4

### Operating System

Dell

### Database and driver

 Azure Postgres Flexible server

### Steps to reproduce

1. right click the table want to move
2. select export 
3. Select source table
4. select target schema

### Additional context

I also want not be able to run SQL query to export table from one dbase to another.

**Comment by E1izabeth** [comment] 2023-03-13 15:06
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

Do you see some error? Does DBeaver stop responding? Does it look like successfully finished operations, but not all data were transferred?

**Comment by jgrover21** [comment] 2023-03-13 16:54
attached is .log file.  It times out with no error message and  dbeaver shuts down.                       
[ - Copy.log](https://github.com/dbeaver/dbeaver/files/10959668/-.Copy.log)

**Comment by E1izabeth** [comment] 2023-03-13 16:58
Thank you.

Seems that it's not enough memory for DBeaver process. By default DBeaver Community has maximum memory limit 1gb.
You can increase this limit in dbeaver.ini file.
Try to change `-Xmx1024m` into `-Xmx4096m` to increase maximum memory to 4Gb, for example.

**Comment by jgrover21** [comment] 2023-03-13 17:07
I got error message too. It tried to load 385 MB file.
![image](https://user-images.githubusercontent.com/28875055/224776389-503727e6-cf62-47a3-935b-8189fd4f26cc.png)

[DBeaver error msg.docx](https://github.com/dbeaver/dbeaver/files/10959782/DBeaver.error.msg.docx)

**Comment by jgrover21** [comment] 2023-03-13 17:13
BTW I just loaded on table 197 M..it loaded in 1.5 minutes...no error

**Comment by jgrover21** [comment] 2023-03-13 17:52
I will try that and let you know.

**Comment by jgrover21** [comment] 2023-03-13 17:54
where do I find dbeaver.init file?

**Comment by E1izabeth** [comment] 2023-03-13 17:55
In the installation folder near dbeaver.exe file

**Comment by jgrover21** [comment] 2023-03-13 18:00
When I downloaded dbeaver..I had a setup file that I ran from downloads folder.  I do not see any other file except this setup file.

**Comment by E1izabeth** [comment] 2023-03-13 18:09
Probably, you downloaded installation file. Then in the installer you chose installation type (for current user or for all users) and installation folder.

If you're under windows it may be located by the path `C:\Users\<Your user>\AppData\Local\DBeaver` or `C:\Program Files\DBeaver` if you haven't changed it.

**Comment by jgrover21** [comment] 2023-03-13 18:10
yes, it is in this folder

**Comment by jgrover21** [comment] 2023-03-13 18:13
Hi Elizabeth..I have some files 12 GB in size.  will I not be able to load those?

**Comment by jgrover21** [comment] 2023-03-13 18:25
one thing I want to mention..that we loaded 11GB file from one dbase to another and it worked with no error message.

**Comment by jgrover21** [comment] 2023-03-13 18:26
that we did last week.

**Comment by jgrover21** [comment] 2023-03-13 19:36
I figured out.  Instead of batches if I use single query, it loads quickly.

**Comment by uslss** [comment] 2023-03-30 13:53
@jgrover21 sorry for the late response
could you check if the issue is reproducible in case you set the keep-alive value to non-zero in connection properties?
thanks in advance
![image](https://user-images.githubusercontent.com/31996417/228858727-c40a3d10-ff3a-45cb-a4b2-decb8913d76e.png)

**Comment by uslss** [comment] 2023-04-26 10:29
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.

**Closed as completed by uslss** 2023-04-26 10:29 UTC
Labels: xf:datatransfer, wait for response, performance
