### ISSUE TITLE
DDL Trigger

### ISSUE THREAD

**Issue by nextstage-brasil** [dbeaver/dbeaver#10092] opened 2020-10-17 12:31 UTC
#### System information: 
- Operating system (distribution) and version: Windos 10 Enterprise
- DBeaver version: 7.2.2
- Additional extensions

#### Connection specification:
- Database name and version: Postgresql 11
- Driver name Postgresql
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
Triggers, Generate SQL, DDL

#### Steps to reproduce, if exist:
Triggers, Generate SQL, DDL

#### Include any warning/errors/backtraces from the logs
T
![dbeaver-trigger-create-error](https://user-images.githubusercontent.com/12989226/96337204-8edf4f80-105b-11eb-9e64-84211cf416e2.png)
he content of the generator is not in accordance with what exists

**Comment by uslss** [comment] 2020-10-18 19:56
Seems to be duplicate of #10041 
Anyway, thanks for the bug report

**Closed by uslss** 2020-10-18 19:56 UTC
Labels: bug, wait for review
