### ISSUE TITLE
triggers not shown in Database Navigator

### ISSUE THREAD

**Issue by fdeveloper** [dbeaver/dbeaver#18760] opened 2023-01-12 20:50 UTC
### Description

In several tables visualized in the Database Navigator (see attached image), when the name of the trigger has more than one underline sign "_" in its name, it is not visualized, however, in the SQL Server Studio environment it is visualized normally (occurs several other tables named after triggers in the same situation).

### DBeaver Version

Community 22.3.2.202301060755

### Operating System

Windows 10

### Database and driver

SQL SERVER.

### Steps to reproduce

1. Connect to any SQL Server database
2. Open the database browser
3. Open any table that has a trigger where the name is suffixed with more than one "_" sign (example: AdItemNotaEnt_i_d)

### Additional context

![DBeaver ERROR TRIGGER](https://user-images.githubusercontent.com/593068/212178465-6eab2e8f-7206-4bbc-8301-c15f677bcf6c.png)

**Comment by ShadelessFox** [comment] 2023-01-13 09:23
Thanks for the bug report

**Comment by ShadelessFox** [comment] 2023-01-13 10:13
Unfortunately, I'm unable to reproduce your issue:

![image](https://user-images.githubusercontent.com/35821147/212294897-90456a01-3d6f-44db-96f1-cfd9e43a76b8.png)

1. What database version are you using?
1. What driver version are you using?
1. Does it happen to every trigger with multiple `_` in it?

**Comment by LonwoLonwo** [comment] 2023-01-13 10:14
Hello @fdeveloper 

![2023-01-13 12_55_09-212178465-6eab2e8f-7206-4bbc-8301-c15f677bcf6c png (Изображение PNG, 1613 × 796 ](https://user-images.githubusercontent.com/45152336/212294750-7f8befca-ea35-48be-a0b1-7a954a61c518.png)

I see a filter on your picture. This filter works on triggers as on tables. So, It is unclear for now - can you see triggers at all or only because of the filter?

I can create and see triggers with more than one '_' in the name.

![2023-01-13 13_13_30-DBeaver 22 3 2 - products](https://user-images.githubusercontent.com/45152336/212295300-72c8796e-845c-4e2a-af71-c4fb4c25869a.png)

**Comment by fdeveloper** [comment] 2023-01-13 11:59
I'll explain the problem better:

Whenever I have triggers in some tables, and these triggers have the underscore character "_" in their name and then more than one digit in their name (AdNotaItemSai_iu, for example), in DBEaver these triggers are not visualized as I exemplified in the previous image .

This problem occurs (unless you see all the triggers in the table), regardless of whether or not there is a filter in the naming of objects in the Database Navigator, that is, it occurs in tables A, B, C, etc.

I believe that the problem of not seeing the triggers is related to the name that the trigger contains more than one digit after the character "_" because this same problem of not seeing the trigger occurs in another table where the triggers have the same situation.

**Comment by LonwoLonwo** [comment] 2023-01-13 12:46
Ok. Can you please check this query using your schema id:

```sql
SELECT  t.*, (SELECT STRING_AGG(te.type_desc, ', ') FROM master.sys.trigger_events te WHERE t.object_id = te.object_id) as trigger_type FROM master.sys.triggers t,master.sys.all_objects o
WHERE o.object_id=t.object_id AND o.schema_id=1
ORDER BY t.name 
```

Can you see all your triggers in the reult list?

**Comment by fdeveloper** [comment] 2023-01-13 13:07
The return is always empty.

Note: In SQL Server 2008 that we are using here, the STRING_AGG function does not exist, so I had to make a small modification to the SELECT statement as shown in the image.

![image](https://user-images.githubusercontent.com/593068/212327029-851229ac-5a43-44aa-8d86-58cffacdc59a.png)

**Comment by LonwoLonwo** [comment] 2023-01-14 19:23
Ok. Did it help? Can you see your triggers in the list without STRING_AGG?

**Comment by fdeveloper** [comment] 2023-01-16 12:05
With the SELECT statement you provided, no trigger appears.

I believe that the problem is related to the number of characters in the name right after the "_".

Example:

a) trigger name AdItemNotaFiscal_d viewer normally
b) trigger name AdItemNotaFiscal_iu is not displayed and others in the same situation are also not displayed.

**Comment by LonwoLonwo** [comment] 2023-01-18 09:33
ok, did you change the `AND o.schema_id=1` schema id parameter to the id of your trigger schema? 
you can see this info in your schema properties tab

**Comment by fdeveloper** [comment] 2023-01-18 12:44
No.

**Comment by LonwoLonwo** [comment] 2023-01-19 13:00
Ok. Could you please check your triggers schema id and use it in the query above? `AND o.schema_id=<your schema id>`

![2023-01-19 15_59_05-DBeaver Lite 22 3 0 - dbo](https://user-images.githubusercontent.com/45152336/213449208-2a46dff4-3691-4d05-ba15-a60757fe04a1.png)

**Comment by fdeveloper** [comment] 2023-01-24 16:49
![image](https://user-images.githubusercontent.com/593068/214355790-ec2a1a79-30f3-4f3c-893f-3437db1a2792.png)

**Comment by fdeveloper** [comment] 2023-01-25 19:26
Hi!

After updating the version today, I can normally view all the triggers that were not displayed before.

Thanks :)

![image](https://user-images.githubusercontent.com/593068/214666944-61771977-d349-44c1-9401-d5b019bce56e.png)

**Comment by E1izabeth** [comment] 2023-01-26 12:49
Thank you for informing us. I'm closing this issue. Please, let me know if it will happen again for you.

**Closed as not planned by E1izabeth** 2023-01-26 12:49 UTC
Labels: can't reproduce, x:mssql, xf:metadata

**Comment by fdeveloper** [comment] 2023-01-26 14:31
There were no further occurrences of the problem. Thanks.

**Comment by BruceJL** [comment] 2024-10-14 21:56
I think that I'm seeing the same issue in the PostgreSQL driver.


### DBeaver Version
Community 24.2.2.202410061621

### Operating System
Debian Testing

### Database and driver
SQL SERVER.

### Steps to reproduce
* Connect to the server with the [linked database](https://github.com/BruceJL/mrg/blob/master/pods/postgresql/00_mrg.sql)
* Open the database browser
* Select the Event Triggers item for the database


### Additional Context
```
SELECT  event_object_table AS table_name ,trigger_name         
FROM information_schema.triggers
```
returns the correct results.
![Screenshot from 2024-10-14 16-51-35](https://github.com/user-attachments/assets/c660ca22-5af0-4cbf-b570-cfab72045ebe)


However, when selecting triggers from the menu tree, no triggers are visible.
![Screenshot from 2024-10-14 16-49-01](https://github.com/user-attachments/assets/e6ab9d08-ba84-4042-9f06-b0cee7872c4e)

**Comment by ShadelessFox** [comment] 2024-10-15 09:37
@BruceJL please create a separate issue.
