### ISSUE TITLE
SQL Editor disabled - 6.1.3

### ISSUE THREAD

**Issue by mcunha98** [dbeaver/dbeaver#6321] opened 2019-07-22 14:48 UTC
After update the last version, I cannot create new SQL Editor windows, the menus always are disabled (database selected and everything its ok)

**Comment by finlbi** [comment] 2019-07-23 13:27
I'm experiencing the same thing in v6.1.3. It seems that no matter what options I select the SQL Editor (F3) button is greyed out.

I'm able to open scripts and execute existing scripts, but can't seem to create new ones.

**Comment by johnpfisk** [comment] 2019-07-23 22:52
Not sure if this is related, but I found that I can create new SQL Editor windows if I select a default Project.

**Comment by finlbi** [comment] 2019-07-24 01:31
@johnpfisk Ah, of course. Thanks for the tip! After setting the default project all of the SQL editor options were available.

**Comment by mcunha98** [comment] 2019-07-24 12:59
Doesn't make sense...if I choose a database on database navigator the menu will be enabled (because I have source for a new sql editor window, not a project, but a database).

My solution : back to 6.1.2

**Comment by serge-rider** [comment] 2019-07-24 15:16
Definitely a bug, most likely a side effect of projects migration in 6.1.3.
Will be fixed in 6.1.4. 
Workaround suggested by  @johnpfisk  and @finlbi also works.

**Comment by cerebel** [comment] 2019-07-25 09:58
#6333 was not fixed ..  [https://mega.nz/#!NGh2haBZ!ODAjhndtzqhaMnqDpJW68SQ0yF4cVyw5qu2BVoq454k](url)

**Comment by serge-rider** [comment] 2019-07-25 10:41
#6333 was closed as duplicate of this dticket.
You can test the fix in 6.1.4 Early Access (https://dbeaver.io/files/ea) or wait until 6.1.4 release.

**Comment by cerebel** [comment] 2019-07-25 10:50
I tested it .
1. git pull, mvn package ....  (the result i posted in previous comment)
2. and again "dbeaver-ce-6.1.4-win32.win32.x86_64.zip  25-Jul-2019 10:13     57M"
The result of test - it was not fixed the issue with migration on workspace .

**Comment by serge-rider** [comment] 2019-07-25 12:03
@cerebel Thanks for testing. 
Could you send error/debug logs? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by cerebel** [comment] 2019-07-25 14:43
The logs, only message with bind "CTRL+D"

**Comment by serge-rider** [comment] 2019-07-28 09:03
Yet another project migration fix was added. 
New Early Access version has been published.

@cerebel Can you open your scripts using Project explorer or Project Navigator views? 
Does this problem block opening older scripts or it is just one time issue with restoring previously opened editors?

**Comment by cerebel** [comment] 2019-07-28 14:55
The problem persists ..  v6.1.4.201907281358.
Additional i attached workbench.xmi from 6.1.2 and 6.1.4 - where after migrations - the list of opened* editors is lost* ( by example, try to search txt "Script-2.sql", in old version it exist, but in migrated* versions - was not found).
 ( the scenario of testing > git pull, mvn package .. delete initial workspace. run 6.1.2, and 6.1.4dev )
[6.1.2_.log](https://github.com/dbeaver/dbeaver/files/3439290/6.1.2_.log)
[6.1.2_dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3439291/6.1.2_dbeaver-debug.log)
[6.1.4_dbeaver-debug[v6.1.4.201907281358].log](https://github.com/dbeaver/dbeaver/files/3439292/6.1.4_dbeaver-debug.v6.1.4.201907281358.log)

**Comment by mcunha98** [comment] 2019-07-28 18:09
Guys,

Thanks for test and hard work, I'll wait for next official release and test it again, the downgrade works fine for me

**Comment by robobobeng** [comment] 2019-07-29 17:34
I'm encountering the same issue. It's annoying not to be able to create a new script from scratch, and I have to create empty .sql files in Notepad++, save them on my disk, and then drag-and-drop them into DBeaver. Not quite practical... 

I'm downgrading to 6.1.2 until 6.1.4 is released

**Comment by serge-rider** [comment] 2019-08-02 14:59
@robobobeng this issue will be fixed in 6.1.4

**Closed** 2019-08-02 14:59 UTC
Labels: bug, xo:eclipse
