### ISSUE TITLE
"Edit Table" menu item sometimes opens "Edit Data" view instead

### ISSUE THREAD

**Issue by JenChampagne** [dbeaver/dbeaver#5640] opened 2019-04-03 14:50 UTC
I couldn't find any other information or issues with this behaviour, apologies if I missed it.

#### System information: 
- Operating system (distribution) and version: MacBook Pro 2012 with macOS Mojave
- DBeaver version: 6.0.1.201903251041
- Java version: 11.0.1 2018-10-16 LTS
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 9.5.15 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When my active view/window is showing me the data of a table through either "edit table" or an SQL script and then right click on a different table in the Database Navigator selecting "Edit Table", I get a new view/window open up which is of the new table but in edit data mode and not edit table mode.

#### Steps to reproduce, if exist:
- have no other views/windows open
- open a table through the database navigator by right clicking and selecting "edit data" or open a new sql script
- open a different table through the database navigator by right clicking and selecting "edit table"
- new view/window opens in "edit data" mode instead of "edit table" mode

#### Include any warning/errors/backtraces from the logs
No errors, just unexpected behaviour.

**Comment by ShiloHo** [comment] 2019-04-14 23:06
Similar problem for me - trying to open "new view" and "new table"  is open.

Using DBeaver 6.0.2.201904071344 on Ubuntu mate
connecting to SQLite  with sqlite-jdbc-3.27.2.1.jar driver
but on PostgreSQL it works well for me 

> I couldn't find any other information or issues with this behaviour, apologies if I missed it.
> #### System information:
> 
>     * Operating system (distribution) and version: MacBook Pro 2012 with macOS Mojave
> 
>     * DBeaver version: 6.0.1.201903251041
> 
>     * Java version: 11.0.1 2018-10-16 LTS
> 
>     * Additional extensions: none
> 
> 
> #### Connection specification:
> 
>     * Database name and version: PostgreSQL 9.5.15 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit
> 
>     * Driver name: PostgreSQL JDBC Driver
> 
>     * Do you use tunnels or proxies (SSH, SOCKS, etc)? No
> 
> 
> #### Describe the problem you're observing:
> 
> When my active view/window is showing me the data of a table through either "edit table" or an SQL script and then right click on a different table in the Database Navigator selecting "Edit Table", I get a new view/window open up which is of the new table but in edit data mode and not edit table mode.
> #### Steps to reproduce, if exist:
> 
>     * have no other views/windows open
> 
>     * open a table through the database navigator by right clicking and selecting "edit data" or open a new sql script
> 
>     * open a different table through the database navigator by right clicking and selecting "edit table"
> 
>     * new view/window opens in "edit data" mode instead of "edit table" mode
> 
> 
> #### Include any warning/errors/backtraces from the logs
> 
> No errors, just unexpected behaviour.

**Comment by uslss** [comment] 2020-05-19 10:22
@JenChampagne , cannot reproduce issue for now - if it is still actual for you - feel free to reopen the ticket.
@ShiloHo issue fixed in scope of #4962

**Closed by uslss** 2020-05-19 10:22 UTC
Labels: xo:macos
