### ISSUE TITLE
Update job error

### ISSUE THREAD

**Issue by UlrichDemlehner** [dbeaver/dbeaver#11057] opened 2021-01-20 07:58 UTC
After updating to v7.3.3, an error message keeps popping up after starting DBeaver (with a delay of a few seconds):

Während "Update Job" ist ein interner Fehler aufgetreten. [_my translation_: error running "Update Job"]
Registry Directory not available: C:\Users\Ulrich%20Demlehner\.eclipse\org.jkiss.dbeaver.product_7.3.2_1535670467_win32_win32_x86_64\p2\org.eclipse.equinox.p2.engine\profileRegistry.

But this very directory does exist and has a subdirectory named <DefaultProfile.profile> so I'm a bit lost what DBeaver is trying to tell me.

My environment: Win10 64 bit, German language version, DBeaver v7.3.3 also German language version.

Thanks for your help!

**Comment by uslss** [comment] 2021-01-20 08:03
seems to be a duplicate of #11046 .
anyway thanks for the report

**Closed as completed by uslss** 2021-01-20 08:03 UTC
Labels: duplicate
