### ISSUE TITLE
Opening Snowflake procedure with underscore in schema name errors out with "SQL compilation error: parse error line 1 at position 29 near '95'."

### ISSUE THREAD

**Issue by fbonneville** [dbeaver/dbeaver#21412] opened 2023-10-03 12:11 UTC
### Description

Opening Snowflake procedure with underscore in schema name errors out with "SQL compilation error: parse error line 1 at position 29 near '95'."

SQL Error [1003] [42000]: SQL compilation error:
parse error line 1 at position 29 near '95'.
  SQL compilation error:
parse error line 1 at position 29 near '95'.
  SQL compilation error:
parse error line 1 at position 29 near '95'.

### DBeaver Version

Version 23.2.1.202309260508

### Operating System

Windows 10.0.19044

### Database and driver

Snowflake 3.13.30

### Steps to reproduce

Connect to Snowflake
Navigate to a schema with an underscore in the name
Open a procedure to view the source

**Comment by LonwoLonwo** [comment] 2023-10-03 13:42
Hello @fbonneville 

What is the name of your database and schema?

**Comment by LonwoLonwo** [comment] 2023-10-03 13:45
Also, could you please try to upgrade your driver version? To the latest, as an example

![2023-10-03 16_43_43-DBeaver Ultimate 22 3 2 - _postgres 6 1_ Script-122](https://github.com/dbeaver/dbeaver/assets/45152336/7a4d9856-857a-438f-a973-f09eed5d92ce)

**Comment by fbonneville** [comment] 2023-10-03 13:51
Hi @LonwoLonwo,

My db.schema name is dev.conformed_vcmd. This occurs in all other schemas which include an underscore as well.

I upgraded the driver to 3.14.2 and am seeing same issue.

![image](https://github.com/dbeaver/dbeaver/assets/66326601/f0daa2a9-f599-438d-9bb8-3e8c035f720a)

**Comment by LonwoLonwo** [comment] 2023-10-03 14:26
As a workaround for now - you can downgrade the driver version to 3.13.6

**Comment by fbonneville** [comment] 2023-10-03 14:59
> As a workaround for now - you can downgrade the driver version to 3.13.6

@LonwoLonwo, thanks for the suggestion but it didn't work for me.

**Comment by LonwoLonwo** [comment] 2023-10-04 07:52
For now, I can't reproduce your issue.

![2023-10-04 10_49_03-DBeaver Ultimate 23 2 2 - OUTPUT_MESSAGE2(ENV VARCHAR)](https://github.com/dbeaver/dbeaver/assets/45152336/4ef21028-6e09-42f3-bb97-c7096df4e251)

Could you please provide your procedure DDL?

You can read it with 

`SELECT GET_DDL('PROCEDURE', '<schema_name>.<procedure_name>(<parameters>)', TRUE)`

**Comment by fbonneville** [comment] 2023-10-04 18:17
@LonwoLonwo I'm noticing that you have double quotes around the schema which is what may be different.

This is what you can use to reproduce.

CREATE OR REPLACE PROCEDURE DEV.CONFORMED_VCMD.TESTPROC()
RETURNS VARCHAR(1677216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    RETURN ''Hello!'';
END
';

CALL DEV.CONFORMED_VCMD.TESTPROC();

SELECT GET_DDL('PROCEDURE', 'DEV.CONFORMED_VCMD.TESTPROC()', TRUE)

![image](https://github.com/dbeaver/dbeaver/assets/66326601/82300218-f6c7-4b9c-9c5a-dcef4df7fab7)

**Comment by LonwoLonwo** [comment] 2023-10-05 10:01
Unfortunately, steel can't reproduce.

![2023-10-05 12_58_18-DBeaver 23 2 2 - TESTPROC](https://github.com/dbeaver/dbeaver/assets/45152336/693d81d3-2d39-4a12-ac9a-8c6040d7c6f0)

Could you please again try to use Snowflake driver 3.13.30 and do a screen from your connection settings -> Test Connection?

**Comment by fbonneville** [comment] 2023-10-05 10:13
@LonwoLonwo, this is the strangest thing, I switched to 3.13.30, clicked on test connection to screengrab the version and now it works. I also tested upgrading to the latest snowflake driver version and that works too.

I'll check with my coworkers who are also having issues to see if I can figure what causes this to "fix" itself.

**Comment by LonwoLonwo** [comment] 2023-10-05 11:24
Sometimes, the oldest driver version also hangs in the Libraries section and can be used during connection.

Ok, I'm closing this issue for now. Feel free to add new comments here or create a new ticket with further details.

**Closed as completed by LonwoLonwo** 2023-10-05 11:24 UTC
Labels: can't reproduce, x:snowflake, xf:metadata

**Comment by fbonneville** [comment] 2023-10-05 12:17
@LonwoLonwo You're the BEST!

Thank you!
