### ISSUE TITLE
problem with query execution

### ISSUE THREAD

**Issue by esverb** [dbeaver/dbeaver#29323] opened 2024-05-03 15:07 UTC
## Description
DBeaver execute next query in case: 
next query starts with GRANT... despite on ";" in running query that causes unexpectfull results 

all queries were executed by pointed cursor on query and ctrl+enter or right-click button 

if highlight first query problem goes away

### DBeaver Version

DBeaver Community Edition 24.0.3.202404211624

### Operating System

macOS 14.4.1 (23E224)

### Database and driver

Database Clickhouse - Official ClickHouse driver (server version 21.3+)
Database GreenPlum - Greenplum JDBC driver

## Examples
```SQL
SELECT 3; ## <- cursor here




GRANT SELECT {database}.{table} TO {user}; ## this query starts
```

```SQL
SELECT 3 ## <- cursor here




GRANT SELECT {database}.{table} TO {user}; ## this query fails cuz missing ";" in first query
```

```SQL
SELECT 3; ## <- cursor here




GRANT SELECT {database}.{table}  ## fails cuz missing "TO {user}" in second query
```

**Comment by E1izabeth** [comment] 2024-05-03 15:20
Duplicate of https://github.com/dbeaver/dbeaver/issues/26416
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Closed as not planned** 2024-05-03 15:20 UTC
Labels: duplicate, xf:sql execution
