### ISSUE TITLE
"word wrap" on/off state not preserved in the value editor while navigating through table cells

### ISSUE THREAD

**Issue by meglio** [dbeaver/dbeaver#29275] opened 2024-04-30 02:49 UTC
### Description

<img width="616" alt="image" src="https://github.com/dbeaver/dbeaver/assets/282177/0e9d3929-d334-4fce-8770-e6d55ad07c9e">

### DBeaver Version

Community Version 24.0.3.202404211624

### Operating System

MacOS 14.4.1 (23E224)

### Database and driver

Postgresql 16.1

### Steps to reproduce

1. Create a table with jsonb fields and other scalar fields
2. Insert large multi-level json objects with values that contain long strings that don't fit into a single line
3. Open the table data view
4. Click on the jsonb field
5. Activate the value editor
6. Toggle Word Wrap, so that the wrapping is turned on
7. Navigate to various cells / various rows in the table
8. Click on the jsonb cell you started from
9. You can see the word wrap is turned off again. The expected behaviour is that the setting persists: while I navigate the query, after I refresh the table data, when I navigate between the tabs with different tables, and between Dbeaver reload.

**Comment by E1izabeth** [comment] 2024-04-30 15:27
Thank you for bug report. It's a duplicate of #19344
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-04-30 15:27 UTC
Labels: xf:data, xf:panels
