### ISSUE TITLE
Database task mapping doesn't handle nvarchar(MAX) in SQL server

### ISSUE THREAD

**Issue by jdussouillez** [dbeaver/dbeaver#18741] opened 2023-01-11 13:19 UTC
### Description

I have a remote db with columns of type `nvarchar(MAX)`. I want to copy it in a local db using a task (because I often do it once a week).

The problem is that DBeaver does not specificy the `MAX` in the target mapping. The default size is 1 so I get errors looking like `String or binary data would be truncated in table 'mytable', column 'SALESMEMO'. Truncated value: 'T'.`

DDL of remote table :

![remote_db_ddl](https://user-images.githubusercontent.com/5428355/211814914-27844c19-d81f-45c9-860c-47f4d5831390.png)

DDL generated by DBeaver :

![dbeaver_db_ddl](https://user-images.githubusercontent.com/5428355/211814964-71e8a117-8856-4ea4-a773-f45d062d834b.png)

Note: the "Columns mapping" data in the "Configure metadata structure" window seems fine, but the generated DDL is not.

![column_mapping](https://user-images.githubusercontent.com/5428355/211817008-91d8de77-2cb0-4909-a7d9-0679942b148d.png)

### DBeaver Version

Community Version 22.3.2.202301060755

### Operating System

Linuxmint 20.3

### Database and driver

Remote server : Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2
Local server : Microsoft SQL Server 2022 (RC0) - 16.0.900.3
Driver : com.microsoft.sqlserver:mssql-jdbc:RELEASE 9.2.0.jre8

### Steps to reproduce

1. Create a table on server S0
2. Add a column with type `nvarchar(MAX)`
3. Add a row with content "foo"
4. Create a db task to copy table from server S1 to S2. Keep the default mapping
5. Run the task. It should fail with `String or binary data would be truncated in table...`

**Comment by jdussouillez** [comment] 2023-01-11 13:30
Ok it seems the data are still inserted in the table if I click on "Skip all". And the newly created table DDL is actually of type `nvarchar(MAX)`... :thinking:

**Comment by ShadelessFox** [comment] 2023-01-12 13:49
Seems familiar to #17244

**Comment by uslss** [comment] 2023-01-26 09:21
thanks for the report. closed as a duplicate of #17244

**Closed as completed by uslss** 2023-01-26 09:21 UTC
Labels: duplicate, x:mssql, xf:datatransfer, xp:normal
