### ISSUE TITLE
GUI refresh delay after new line

### ISSUE THREAD

**Issue by G3zz** [dbeaver/dbeaver#14334] opened 2021-10-21 15:55 UTC
#### System information: 
- Operating system (distribution) and version: macOS Catalina (10.15.7 (19H1417))
- DBeaver version: Community Version 21.2.1.202109181446
- Additional extensions: N/A

#### Connection specification:
- Database name and version: all tried
- Driver name: N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)? N/A/

#### Describe the problem you're observing:
Since upgrading to a newer  version of DBeaver there is a large delay in refreshing the GUI 
after a new line is entered.  Please see the video below.

#### Steps to reproduce, if exist:
Write a query, add a new line in the middle of it, wait ages for the GUI to refresh.

#### Include any warning/errors/backtraces from the logs

https://user-images.githubusercontent.com/8767122/138313747-b9b0375f-8530-4aa3-aa82-3ecab8810f51.mov

**Comment by flambchap** [comment] 2021-10-22 09:37
Duplicate of https://github.com/dbeaver/dbeaver/issues/13966. Thank you for the report.

**Closed as completed by flambchap** 2021-10-22 09:37 UTC
Labels: duplicate, xo:macos
