### ISSUE TITLE
Table list (on the right) is empty until I resize it

### ISSUE THREAD

**Issue by Liudvikas-vinted** [dbeaver/dbeaver#19508] opened 2023-03-28 06:42 UTC
### Description

Sometimes when a new tab opens, usually when it's a list of tables/columns (not data), its contents appear empty. Then I double click on the tab, which causes it to expand (hides the left hand side Database Navigator), and its content appears. Appears instantly, so I think it's a display issue, not data querying issue.

### DBeaver Version

Community Version 22.0.1.202203181646

### Operating System

Fedora 37

### Database and driver

Happens with Impala JDBC driver and built-in MySQL driver

### Steps to reproduce

Reproducible ~50% of the time. I think there's logic (like opening tables that have previously been opened) for when bug happens, but not sure. 
1. In database navigator, expand a connection, double-click on "Databases"
2. New tab appears, supposed to list databases, but the list appears empty
3. (to fix) Double-click on tab name, which causes tab to expand 
4. Tab now shows the list of databases
5. Double-click the tab to shrink it back

### Additional context

Gnome 43.3 on X

**Comment by E1izabeth** [comment] 2023-04-06 10:08
Could you check, if it's actual for the latest DBeaver version 23.0.1?
We made some fixes and this issue might be solved too. At least, I can't reproduce it.

**Comment by Liudvikas-vinted** [comment] 2023-04-06 10:24
After update to 23, my database connections disappeared :cry: 
I know this is unrelated, but if you could point to a FAQ how to import settings from 22 to 23, it would really speed this up

**Comment by E1izabeth** [comment] 2023-04-06 10:26
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by E1izabeth** [comment] 2023-04-06 10:27
Also please check the file `.dbeaver/data-sources.json` following this guide https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Connections. Is it empty?

**Comment by Liudvikas-vinted** [comment] 2023-04-06 10:28
```
!SESSION 2023-04-06 13:16:01.242 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-04-06 13:16:09.582
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
!SESSION 2023-04-06 13:21:23.899 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-04-06 13:21:26.659
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
!SESSION 2023-04-06 13:25:11.404 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-04-06 13:25:15.354
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
```

**Comment by E1izabeth** [comment] 2023-04-06 10:28
My first assumption is that previously installed DBeaver was installed for All users, but the new one is for Current user only or vise versa. Don't you remember your choice in installer?

**Comment by Liudvikas-vinted** [comment] 2023-04-06 10:51
You are correct, it was caused by a different installer. I managed to solve that problem by uninstalling the snap package and installing the RPM provided by the website. 
On Version 23.0.1.202303250535, I couldn't reproduce the bug yet :partying_face:

**Comment by E1izabeth** [comment] 2023-04-06 11:17
Thank you for update. then I'm closing the issue.

**Closed as completed by E1izabeth** 2023-04-06 11:17 UTC
Labels: xo:linux, xf:navigator

**Comment by Liudvikas-vinted** [comment] 2023-05-30 13:58
Hi, I'd like to resubmit this same issue for version Version 23.0.1.202303250535 :(

**Comment by E1izabeth** [comment] 2023-05-30 13:59
Can you reproduce it on DBeaver 23.0.5?
