### ISSUE TITLE
can't read all records

### ISSUE THREAD

**Issue by EHornburg** [dbeaver/dbeaver#9531] opened 2020-08-14 07:48 UTC
#### System information: 
- windows 10 Enterprise
- DBeaver Enterprise 7.1

#### Connection specification:
- SQL Server and Oracle

#### Describe your question:
I’m testing your DBeaver enterprise Edition.
At first: it seem’s, that this is exactly what i need.

I have a question:
•	After i make one or two big query’s, this Symbols are not available, to read all data:
 
![image](https://user-images.githubusercontent.com/61511135/90226456-4f09ab00-de13-11ea-9eda-fd2f6f90a7aa.png)

•	After i close the other Query Windows the symbols are available again.

What can i do?
I have enough RAM (64 GB).

**Comment by kseniiaguzeeva** [comment] 2020-08-14 08:45
I'm glad that DBeaver are useful for you!
Could you please give me a query example? I cannot reproduce the issue.

**Comment by EHornburg** [comment] 2020-08-14 09:03
thanks for your replay.
it doesn't what kind of SQL i created, 
here an example:
SELECT
    k.FALL_ID,
    k.KDU_ID,
    k2.AB,
    k2.BIS,
    s.SBL_ID,
    s.SBLVW_ID,
    s2.SV_ID,
    s2.AB,
    s2.BIS,
    s2.FEHLER_AM
FROM
    BREMEN.KDU k
INNER JOIN BREMEN.KDUMIETE k2 ON
    k.KDU_ID = k2.KDUM_ID
INNER JOIN BREMEN.SBL s ON
    k.KDU_ID = s.KDU_ID
INNER JOIN BREMEN.SACHVERHALTE s2 ON
    s.SBL_ID = s2.SBL_ID
WHERE
    s2.FEHLER_AM = '31.12.9999'

if i have one big resultset (over 400.000 records - i must analyse big databases), then the next query show only 1.000 (for example)

is the any setting in ini-files where i can increase for example the workspace

**Comment by EHornburg** [comment] 2020-08-14 09:09
thanks for your replay.
it doesn't matter what kind of SQL i created,
here an example:
SELECT
k.FALL_ID,
k.KDU_ID,
k2.AB,
k2.BIS,
s.SBL_ID,
s.SBLVW_ID,
s2.SV_ID,
s2.AB,
s2.BIS,
s2.FEHLER_AM
FROM
BREMEN.KDU k
INNER JOIN BREMEN.KDUMIETE k2 ON
k.KDU_ID = k2.KDUM_ID
INNER JOIN BREMEN.SBL s ON
k.KDU_ID = s.KDU_ID
INNER JOIN BREMEN.SACHVERHALTE s2 ON
s.SBL_ID = s2.SBL_ID
WHERE
s2.FEHLER_AM = '31.12.9999'

if i have one big resultset (over 400.000 records - i must analyse big databases), then the next query show only 1.000 (for example)

is there any setting in ini-files where i can increase for example the workspace

 

 

 

 

Für weitere Fragen und Anregungen stehen wir gern zur Verfügung.

 

Mit freundlichen Grüßen

 

Eckhard Hornburg

EHS Software Entwicklung GmbH

Tel.: 05472 / 1396

Fax: 05472 / 957086

eMail: info@ehsoftware.de <mailto:info@ehsoftware.de> 

Home: www.ehsoftware.de <http://www.ehsoftware.de/> 

 

Von: Kseniia <notifications@github.com> 
Gesendet: Freitag, 14. August 2020 10:45
An: dbeaver/dbeaver <dbeaver@noreply.github.com>
Cc: EHornburg <extern@ehsoftware.de>; Author <author@noreply.github.com>
Betreff: Re: [dbeaver/dbeaver] can't read all records (#9531)

 

I'm glad that DBeaver are useful for you!
Could you please give me a query example? I cannot reproduce the issue.

**Comment by kseniiaguzeeva** [comment] 2020-08-18 16:39
Thank you for the report. I could reproduce it creating a query using Query Builder.
(_e.g. Oracle tables HR.9531 and HR.9531to can be used to reproduce_)

**Comment by serge-rider** [comment] 2020-11-07 15:11
Actual problem happens after tables drag-n-drop. It somehow breaks command context.
Perhaps because VQB editor is a quite sophisticated component.
I need to dig it a bit more..

Workaround: click on any other view (e.g. Database Navigator) and then back on SQL editor/Query Builder. It will re-activate the context and fix all commands including Fetch All. You need to do this only once.

**Comment by LonwoLonwo** [comment] 2023-05-25 08:33
I can't reproduce it against in DBeaver 23.0.5 EE
Closing as completed.

**Closed by LonwoLonwo** 2023-05-25 08:33 UTC
Labels: bug, xf:sql, PRO, planned
