### ISSUE TITLE
Database navigator live updates

### ISSUE THREAD

**Issue by lacanoid** [dbeaver/dbeaver#17920] opened 2022-10-14 00:31 UTC
Database navigator does not refresh automatically, one has to run "refresh" from the menu often. 
This is highly annoying as one never quite knows if what is shown is actually what is there.

This typically happens when running SQL DDL commands; neither metadata nor navigator is refreshed. 

Perhaps a thing to do would be to refresh open folders in the navigator every now and then...

**Comment by E1izabeth** [comment] 2022-10-17 13:04
It looks like a duplicate of #6398
Probably will be implemented in scope of that issue.

**Closed as not planned** 2022-10-17 13:04 UTC
Labels: duplicate, xf:navigator
