### ISSUE TITLE
"Open Database Object" can't user wildcard

### ISSUE THREAD

**Issue by dingb** [dbeaver/dbeaver#4421] opened 2018-10-18 04:09 UTC
Hi,

I find the latest release loses the functionality of wildcard (? and *) in "Open Database Object". Please help to fix it. Thanks.

Version: 5.2.2.201810071756

**Comment by serge-rider** [comment] 2018-10-31 20:08
Duplicate of #4373
Thanks for the bug report anyway

**Closed by serge-rider** 2018-10-31 20:08 UTC
Labels: bug, duplicate
