### ISSUE TITLE
Function header and trailler missing for PostgreSQL

### ISSUE THREAD

**Issue by HeikkiVesanto** [dbeaver/dbeaver#12735] opened 2021-06-04 11:58 UTC
I suspect this is similar to https://github.com/dbeaver/dbeaver/issues/3892 but it impacts PostgreSQL versions well above 8.4.

#### System information: 
Windows

Tested on:
DBeaver 7.3.0
DBeaver 21.1.0

#### Connection specification:
Tested on:
PostgreSQL 9.5 and 10.10:
PostgreSQL 9.5.23 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
PostgreSQL 10.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit

- Driver name
PostgreSQL JDBC Driver

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
Happens both on and off SSH.

#### Describe the problem you're observing:

Sometimes when loading a function in PostgreSQL you do not get the header.

You end up with:
![CropperCapture 31](https://user-images.githubusercontent.com/3973339/120797597-297d9780-c534-11eb-9b2d-9881b008d1ee.png)

Whereas it should look like:
![CropperCapture 32](https://user-images.githubusercontent.com/3973339/120797610-2d111e80-c534-11eb-91a6-1456cc78dd52.png)

Also missing from the end is:
$function$;

#### Steps to reproduce, if exist:

1. Open up a PostgreSQL connection.
2. Open the functions list in a schema with functions (more than 1 would show the results best).
3. Open up (view function) one of the functions in the schema. This should load as expected, close the function.
4. Leave DBeaver running for at least an hour with no interaction.
5. Open up one of the functions that was not opened in step 3. This will not load the header.
6. Opening up the same function that was opened in step 3 still loads correctly.

Workaround:

Restart of DBeaver.

Or just Disconnect the connection and reconnect (Invalidate/Reconnect does not seem to be enough).

#### Include any warning/errors/backtraces from the logs
Logs seem to show:

2021-06-04 12:50:21.729 - Error reading procedure body
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:767)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1659)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:373)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.queryString(JDBCUtils.java:624)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreProcedure.getObjectDefinitionText(PostgreProcedure.java:400)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:85)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.lambda$0(SQLEditorNested.java:271)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:269)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment] 2021-06-07 11:11
thanks for the report
closed as the duplicate of #12649

**Closed as completed by uslss** 2021-06-07 11:11 UTC
Labels: duplicate
