### ISSUE TITLE
Data Transfer from HANA to PostgreSQL suggests to transfer a DECIMAL field to an INT4 field

### ISSUE THREAD

**Issue by amarvin** [dbeaver/dbeaver#12031] opened 2021-04-07 23:57 UTC
#### System information: 
- Windows 10
- DBeaver version 7.1.4.202008021649

#### Connection specification:
- SAP HANA and PostgreSQL
- JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

The Data Transfer tool is great for copying a table from one database to another, but sometimes suggests the wrong field type when the two database technologies are different. I noticed this when copying an SAP HANA table that had fields of type DECIMAL to be copied to a PostgreSQL database, when the DBeaver Data Transfer tool suggested the new PostgreSQL table should have corresponding fields of type INT4. I think in this case the suggested field type should be NUMERIC in PostgreSQL to correspond with SAP HANA's type DECIMAL.

I can manually change the field type from the suggestion of INT4 to the correct NUMERIC, but it'd be nice if a future DBeaver version had a correct suggestion here.

**Comment by uslss** [comment] 2021-04-08 09:47
thanks for the report
In 21.0.2 Decimal field is suggested to the varbit field

**Comment by amarvin** [comment] 2021-04-08 13:06
Thanks! I'll try the newer version.

**Comment by tonytheodore** [comment] 2021-04-14 04:07
There's a similar issue transferring MS Access `double` field to PostgreSQL `varbit` type (should be `double precision`). 

Should I raise a new issue or is there a way to override the default mapping?

**Comment by LonwoLonwo** [comment] 2021-09-30 14:55
Can't reproduce in DBeaver 21.2.1

Transfer from HANA to PostgreSQL

![2021-09-30 17_45_46-Map columns of decimal_test](https://user-images.githubusercontent.com/45152336/135477984-ecc2e964-a24f-4af2-9fe7-862da2f6c83e.png)

![2021-09-30 17_46_03-Target DDL](https://user-images.githubusercontent.com/45152336/135477989-96ee94ef-a426-4502-a87a-f7e77a5bb946.png)

HANA Decimal data type mapped as PostgreSQL decimal data type. 

So, I'm closing this ticket.
If the problem still exists - feel free to reopen the ticket.

**Closed as completed by LonwoLonwo** 2021-09-30 14:55 UTC
Labels: can't reproduce, xf:datatransfer
