### ISSUE TITLE
The right-click menu tool is gone? How to dump database?

### ISSUE THREAD

**Issue by zhaixuepan** [dbeaver/dbeaver#17102] opened 2022-07-17 09:47 UTC
**Is your feature request related to a problem? Please describe.**

After the update version [22.1.2.202207091910], the tool is gone, the dump database and restore database are gone, and the toolbar needs to be restored

**Describe the solution you'd like**

Recovery tool related functions

**Describe alternatives you've considered**

Recovery tool related functions

**Additional context**

![image](https://user-images.githubusercontent.com/15258081/179392807-f3d9c304-8571-4508-822e-36637f85b244.png)

previous version
![image](https://user-images.githubusercontent.com/15258081/179392813-a61b7294-42aa-40e7-8fa4-8791ffdea2b5.png)

**Comment by zhaixuepan** [comment] 2022-07-17 09:48
download from microsoft store.

![image](https://user-images.githubusercontent.com/15258081/179392847-252de369-80e5-4026-9c0c-bb1de0926459.png)


![image](https://user-images.githubusercontent.com/15258081/179392861-0d25ee87-1584-42d3-b059-fffa92aeab11.png)

**Comment by LonwoLonwo** [comment] 2022-07-18 08:05
Hello @zhaixuepan 

Is tools menu also empty or doen't exist in Database -> Tools ?

![2022-07-18 11_01_46-Window](https://user-images.githubusercontent.com/45152336/179469156-f9cbc9cf-6638-41cf-9353-f3359b046163.png)

**Comment by zhaixuepan** [comment] 2022-07-18 08:17
Hello，Both are empty.


![image](https://user-images.githubusercontent.com/15258081/179470733-09962114-bd32-427b-98af-74d39738da9f.png)

![image](https://user-images.githubusercontent.com/15258081/179470781-0ac3d864-6c26-446e-b9b4-bb067018b371.png)

**Comment by Jmartirizo** [comment] 2022-07-21 15:53
I have the same problem, have you found a solution? Thanks!

**Comment by LonwoLonwo** [comment] 2022-07-21 16:03
Hello all.

DBeaver was republished to the Windows Store.
Can you please check it now?

**Comment by zhaixuepan** [comment] 2022-07-22 02:55
Hello @LonwoLonwo.
I uninstalled and re-downloaded it, but it still doesn't work.
Is the latest version not yet distributed in the Windows App Store?

![image](https://user-images.githubusercontent.com/15258081/180352491-3e249142-ab94-407a-8b9c-6db468d69e1a.png)
![image](https://user-images.githubusercontent.com/15258081/180352764-acb1a85b-1a6b-4ab2-9f56-e9569a6335dd.png)
![image](https://user-images.githubusercontent.com/15258081/180352826-b3800632-e883-4ebb-8b80-f72b1a60e2ac.png)

**Comment by LonwoLonwo** [comment] 2022-07-22 07:30
Thanks for the answer.

**Comment by LonwoLonwo** [comment] 2022-07-22 07:31
I'm closing this ticket as a duplicate of #17132
The fix will be available in the next release - 22.1.3

**Closed as completed by LonwoLonwo** 2022-07-22 07:31 UTC
Labels: x:mysql, duplicate

**Comment by zhaixuepan** [comment] 2022-07-22 08:56
Thanks.
