### ISSUE TITLE
Cannot rename Postgres table (DBeaver 4.1.2)

### ISSUE THREAD

**Issue by NekoKoneko** [dbeaver/dbeaver#2033] opened 2017-08-18 06:56 UTC
Steps to reproduce:

1. Create a new Postgress table if necessary or select an existing table
2. Press F2 or right click and select Rename
3. Enter a new table name and press OK
4. The name of the table doesn't change even after refreshing

DBeaver 4.1.2 x64, Windows 7 x64, Posgres 9.6.3 on Ubuntu 16.0.4

**Comment by serge-rider** [comment] 2017-08-18 13:18
Can't reproduce.

If you are working in transactional mode - make sure you committed the changes after table rename.

Also you can check Query Manager view (note: enable all query types in QM settings) for all SQL DBeaver actually executes - there should be something like:
```
ALTER TABLE schema.table1 RENAME TO table2
```

**Comment by NekoKoneko** [comment] 2017-08-18 13:53
I'm not working in transactional mode.
I forgot to mention, that I try to rename a table from the **Project** window, not from the **Database Navigator** window. Try the following:

1. Create a new project
2. Add a new Postgres connection to the project
3. Create a new table if necessary
4. Close **Database Navigator** window and all other open windows
5. Restart DBeaver
6. Select a table in the **Project** window and try to rename it
7. No entry is added to the **Query Manager** list, Rename script window doesn't show, table's name stays the same
8. Open the **Database Navigator** window
9. Return to the **Project** window and try to rename a table - it will succeed now

**Comment by tati-kru** [comment] 2018-01-18 14:47
It looks like this problem was  solved. Ticket will be closed. If you think that it is actual just let us know.

**Closed by tati-kru** 2018-01-18 14:47 UTC
Labels: can't reproduce, question
