### ISSUE TITLE
On Kubuntu 20.04 and Windows 10, toolbar icons of DBeaver are too small

### ISSUE THREAD

**Issue by yetangye** [dbeaver/dbeaver#9146] opened 2020-07-02 16:12 UTC
#### System information: 
- Operating system (distribution) and version
  Kubuntu 20.04 and Windows 10
- DBeaver version: 7.1.1
- Additional extensions: no
- Display resoluton:  2560*1400

#### Connection specification:
no relations.

#### Describe the problem you're observing:
Toolbar icons of DBeaver are too small, it is hard to eyes to see these small icons.

<img width="1223" alt="DBeaver-Icons-Two-Small-On-Big-Screen" src="https://user-images.githubusercontent.com/1502349/86384666-a4558700-bcc1-11ea-87b7-ccf89b0badf3.png">

#### Steps to reproduce, if exist:
no relations.

#### Include any warning/errors/backtraces from the logs
no

**Comment by uslss** [comment] 2020-07-04 20:01
hi @yetangye ,
thanks for the bug report. It seems that issue is duplicate of #6581 .
Ticket closed as duplicate

**Closed by uslss** 2020-07-04 20:01 UTC
Labels: bug, wait for review
