### ISSUE TITLE
NPE when DBeaver tries to autocomplete table names

### ISSUE THREAD

**Issue by braiam** [dbeaver/dbeaver#17533] opened 2022-09-01 19:37 UTC
### Description

Typing out a table name on a editor screen for a Postgres connection, produce the following NullPointerException:

```
java.lang.NullPointerException
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:112)
	at net.sf.jsqlparser.statement.select.WithItem.accept(WithItem.java:139)
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:95)
	at net.sf.jsqlparser.statement.select.Select.accept(Select.java:30)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromObject(SQLCompletionAnalyzer.java:1311)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromObject(SQLCompletionAnalyzer.java:1268)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromChildren(SQLCompletionAnalyzer.java:1188)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeDataSourceProposals(SQLCompletionAnalyzer.java:871)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:306)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:102)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:86)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:330)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

it can be something simple as `select * from d` to produce the error.

### DBeaver Version

22.1.5

### Operating System

Debian Stable

**Comment by LonwoLonwo** [comment] 2022-09-02 06:36
Hello @braiam 

For now, I can't reproduce your issue, unfortunately.

Maybe you can provide a screen or video of your issue, please?

**Comment by braiam** [comment] 2022-09-03 11:34
Sadly I can not. I restarted DBeaver, again after another NPE affecting data exports, and it continued working. I'm not aware of any specific steps required to reproduce either NPE, they just _happen_ :wavehands:

**Comment by LonwoLonwo** [comment] 2022-09-12 10:37
Hello @braiam 

Unfortunately, my colleagues nor I can reproduce this issue and catch NullPointerException.

Also, these code lines:

```java
at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:112)
	at net.sf.jsqlparser.statement.select.WithItem.accept(WithItem.java:139)
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:95)
	at net.sf.jsqlparser.statement.select.Select.accept(Select.java:30)
```

look outdated, not as in our JSQLibrary version. So it can be some installing problems.

So, for now, I'm closing this ticket. If you have more details about this issue - feel free to write it here or create a new ticket.

**Closed as not planned by LonwoLonwo** 2022-09-12 10:37 UTC
Labels: xf:sql, wait for response
