### ISSUE TITLE
CSV import - need to reassign columns on subsequent imports

### ISSUE THREAD

**Issue by guardiande** [dbeaver/dbeaver#10332] opened 2020-11-12 17:01 UTC
#### System information: 
- Windows 10
- DBeaver 7.2.4
- Java 10

#### Connection specification:
- SQLite 
- sqlite-jdbc-3.31.1 

#### Describe the problem you're observing:

* I do regular imports from CSV into SQLite using DBeaver.
* The CSV column names don't have the same names as the table columns.
* Because the mapping of columns is tedious I do the mapping once and save the import as a task.
* I can repeat the task while keeping the column mapping as long as don't use a different filename for the CSV file.
* If I change the name of the import file or import from a different directory the column mapping gets reset.

#### Steps to reproduce, if exist:

**Create a test table**
```
CREATE TABLE import_test (
   c1 TEXT(16),
   c2 INTEGER,
   c3 TEXT(16)
  )
  ```

**Create two CSV files**

export1.csv

```
col1;col2;col3
A;1;One
B;2;Two
```

export2.csv

```
col1;col2;col3
C;3;Three
D;4;Four
```

**Import export1.csv into the table**

* Right click on table in datasource tree view
* Import Data
* Map the columns col1, col2, col3 to c1, c2, c3 (make sure to use the "Columns..." button and dialog for mapping)
![image](https://user-images.githubusercontent.com/4947715/98969893-989b8c00-250f-11eb-903c-73c72899dacb.png)
* Save task
![image](https://user-images.githubusercontent.com/4947715/98969966-b23cd380-250f-11eb-8196-bca1069676ce.png)
* Press start to import the data.
* Verify that the data has been successfully imported.

**Import export2.csv**

* Open the task view to repeat the import with new data.
* Right click the saved task and click edit.
* Select export2.csv instead of export1.csv.
* Notice how the mapping has been reset
![image](https://user-images.githubusercontent.com/4947715/98970804-a7cf0980-2510-11eb-9503-9e6cfdd910f1.png)

**Comment by uslss** [comment] 2020-11-18 11:50
thanks for the report

**Comment by uslss** [comment] 2020-11-24 08:41
seems the issue still persists in the case of changing the source file. It is needed to manually reassign columns even if column names are similar to the first file's columns.

**Comment by ShadelessFox** [comment] 2020-11-24 08:59
Hello, @guardiande, 
Columns mappings reset every time the source is changed, it's not a bug. I'll update labels to a feature request.
There was an issue with saving column mappings in tasks, but it was fixed.

**Closed** 2020-12-11 09:27 UTC
Labels: feature request, xf:datatransfer
