### ISSUE TITLE
Display array elements in the spreadsheet

### ISSUE THREAD

**Issue by abolognino** [dbeaver/dbeaver#12148] opened 2021-04-19 08:51 UTC
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04.2 LTS
- DBeaver version: 21.0.3
- Additional extensions

#### Connection specification:
- Database name and version: Oracle 19
- Driver name: ojdbc8-12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
when selecting a row with a collection type inside, only the first element of
the collection is shown

#### Steps to reproduce, if exist:
    create type tst_kv as object (k varchar2(100), v varchar2(100));

    create type tst_kv_coll is table of tst_kv;

    create table tst_tab (id number, coll tst_kv_coll)
    NESTED TABLE COLL STORE AS "TST_TAB_NST1";

    insert into tst_tab(id, coll)
    select 1, tst_kv_coll(tst_kv('0', 'a')) x from dual;

    commit;

    /* REFRESH THE SCHEMA DEFINITION TO AVOID ANOTHER UNRELATED BUG */

    declare
        v_row tst_tab%rowtype;
    begin
        select * into v_row
        from tst_tab
        where id = 1;
        v_row.coll.extend();
        v_row.coll(2) := tst_kv('2', 'b');
        update tst_tab set row = v_row where id = 1;
        commit;
    end;

    select * from tst_tab;

    /* NOTICE ONLY the ('0', 'a') record is shown, sqlplus shows both ('0', 'a') and ('2', 'b') */

    -- cleanup
    drop type tst_kv_coll;
    drop type tst_kv;
    drop table tst_tab;

![image](https://user-images.githubusercontent.com/14804609/115208000-6b758a00-a0fc-11eb-9e85-cd3de9057d1c.png)
![image](https://user-images.githubusercontent.com/14804609/115208059-7a5c3c80-a0fc-11eb-9fc5-18e8fcccac15.png)

#### Include any warning/errors/backtraces from the logs
no errors

**Comment by LonwoLonwo** [comment] 2021-04-20 07:30
Hello @abolognino 
Thanks for the bug report.

As some workaround - you can see right values in "Text" mode.
![2021-04-20 10_26_58-DBeaver Enterprise 21 0 3 - _orcl_ Script-42](https://user-images.githubusercontent.com/45152336/115355528-6d565080-a1c3-11eb-95c7-c8e572604f51.png)

**Comment by emironovDB** [comment] 2022-06-30 13:29
Hi, @abolognino! 

This issue seems as already fixed by https://github.com/dbeaver/dbeaver/issues/16695

**Comment by LonwoLonwo** [comment] 2023-05-31 11:20
I can't reproduce this issue against DBeaver 23.0.5

![2023-05-31 14_16_51-DBeaver Ultimate 23 1 0 - _orcl_ Script-59](https://github.com/dbeaver/dbeaver/assets/45152336/f74d2c96-c9c2-4cad-a668-cc4602a6ea1d)

Closing the ticket.

**Closed as completed by LonwoLonwo** 2023-05-31 11:20 UTC
Labels: xf:data, AS, sp:8, xd:complex
