### ISSUE TITLE
PostgreSQL database dump without schema specification

### ISSUE THREAD

**Issue by PythonOfJungle** [dbeaver/dbeaver#18829] opened 2023-01-22 17:46 UTC
### Description

Cannot dump PostgreSQL database without schema specification (without -n key).
![image](https://user-images.githubusercontent.com/63949215/213931274-80251ee8-f677-4a01-a00c-a2535d849d68.png)
If I make a dump with a schema specification, then not all database data gets into it. 
When I run the same command in the console, but without the -n switch, then the dump is correct.

### DBeaver Version

Community Edition 22.3.1

### Operating System

Windows 10 Pro x64

### Database and driver

PostgreSQL 14.1
PostgreSQL JDBC Driver 42.5.1

**Comment by LonwoLonwo** [comment] 2023-01-23 12:48
Hello @PythonOfJungle 

Ok, we can probably remove this "-n" condition.

As a workaround - from the last (23.3.3) release, you can use the Global Dump tool. It dumps databases.

![2023-01-13 14_44_42-DBeaver 22 3 2 - _postgres_ Script-34](https://user-images.githubusercontent.com/45152336/214043422-fbb87640-2c31-45c5-97e5-60227a7101fe.png)

**Comment by PythonOfJungle** [comment] 2023-01-23 17:53
Thank you, I'll try it when DBeaver is updated from Windows Store :)

**Comment by LonwoLonwo** [comment] 2023-03-10 09:44
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/6741

**Closed as not planned by LonwoLonwo** 2023-03-10 09:44 UTC
Labels: enhancement, x:postgresql, duplicate, xp:normal, xf:native clients
