### ISSUE TITLE
SSH MFA Auth with interactive password prompt broken since 22.2.1

### ISSUE THREAD

**Issue by s1ashi** [dbeaver/dbeaver#18348] opened 2022-11-27 08:20 UTC
### Description

Since 22.2.1 release got following error while trying to connect DB over SSH Tunnel & Jump server with MFA enabled.
Error details:
```
Can't initialize tunnel
Cannot establish tunnel to 10.0.2.10:22
Cannot establish tunnel to 10.0.2.10:22
SSH_MSG_DISCONNECT: 2 Too many authentication failures 
SSH_MSG_DISCONNECT: 2 Too many authentication failures 

```
In 22.2.0 Password prompt appeared when trying to connect (expected behavior, as password was not saved in Dbeaver Connection Preferences/SSH Tab), and then connection successfully established.

Since 22.2.1 SSH password prompt not showing and connection automatically fails

![image](https://user-images.githubusercontent.com/20456934/204125276-5ad60682-ec45-476d-9335-db4bd11547fd.png)

### DBeaver Version

22.2.1-22.2.5

### Operating System

macOS BigSur 11.4

### Database and driver

SSH Driver used: JSch

### Steps to reproduce

1. Enable MFA (key+password) on linux host (JumpHost for example)

```
#/etc/ssh/sshd_config:
AuthenticationMethods publickey,password
```
2. Add ssh public key to user .ssh folder
3. Do not save passphrase in SSH Tunnel settings
4. Try to Test tunnel configuration by pressing "Test tunnel configuration" key

**Comment by Destrolaric** [comment] 2022-11-28 15:31
@s1ashi Hi. I was unable to reproduce it for my key. If possible, can you provide the ssh-keygen command example which was used? It may be helpful.

**Comment by uslss** [comment] 2023-02-01 11:20
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.

**Comment by s1ashi** [comment] 2023-02-25 04:10
I am sorry for the long answer.
@uslss @Destrolaric could you please reopen this issue.

`ssa-keygen -t rsa ` was used to generate the key.

And i also tried PEM key (generated with `ssh-keygen -t rsa -m PEM` command).
Error is the same

The latest Dbeaver version (22.3.5) displays the same error

Both keys works fine for MFA in 21.3, 22.2.0 (the latest version that works properly for MFA)

When I remove the MFA option (AuthenticationMethods publickey,password)from the sshd_config on the JUMP host - the connection is successfully established with the settings shown in the screenshot above using the latest Dbeaver version.

**Comment by E1izabeth** [comment] 2023-03-09 13:40
Seems that we're incorrectly determine encrypted with password keys via sshj/jsch libs.

**Comment by Destrolaric** [comment] 2023-03-09 14:04
Probably linked to https://github.com/dbeaver/dbeaver/issues/19243

**Comment by Destrolaric** [comment] 2023-03-27 16:10
@s1ashi Hi, we recently updated our ciphers. Could you see if it still happens in recent versions?

**Comment by Matvey16** [comment] 2023-03-28 11:15
Verified

**Comment by s1ashi** [comment] 2023-03-29 07:18
Please, reopen.

The problem still exists on the latest (23.0.1) version.

1)When I use an ssh key without a password, I get following error messages (without any password prompt):

Can't initialize tunnel
Cannot establish tunnel to 10.0.2.10:22
Cannot establish tunnel to 10.0.2.10:22
SSH_MSG_DISCONNECT: 2 Too many authentication failures 

2) When I use an ssh key with password, I get following password prompts:
a)Specify password for SSH Tunnel
b)Specify password for SSH jump server

After entering the passwords i get following errors:

Can't initialize tunnel
Cannot establish tunnel to 10.0.2.10:22
Cannot establish tunnel to 10.0.2.10:22
Auth fail for methods 'publickey'

The settings are exactly the same as in my first message.
Version 21.3.0 works correctly with the same settings.


> @s1ashi Hi, we recently updated our ciphers. Could you see if it still happens in recent versions?

**Comment by Destrolaric** [comment] 2023-03-31 13:08
@s1ashi Hi, could you try to connect using SSHJ? You could specify it in the advanced settings
![image](https://user-images.githubusercontent.com/20579256/229128436-352a16e6-3363-49cc-8566-76c16f9885b9.png)

**Comment by s1ashi** [comment] 2023-03-31 23:32
I tried SSHJ implementation and got the following error:
  Cannot establish tunnel to 10.0.2.10:22
  Exhausted available authentication methods


> @s1ashi Hi, could you try to connect using SSHJ? You could specify it in the advanced settings

**Comment by Destrolaric** [comment] 2023-04-03 09:36
@s1ashi Hi, if possible to look from the server side, could you check if an error similar to the one below happens?
`Algorithm negotiation fail: algorithmName="server_host_key" jsch Proposal="rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521" serverProposal="ssh-rsa,ssh-dss"`

**Comment by Destrolaric** [comment] 2023-04-03 12:28
Probably linked https://github.com/dbeaver/dbeaver/issues/19568

**Comment by s1ashi** [comment] 2023-04-04 10:30
I couldn't find the specified messages in server logs, but I can clarify sshd settings:

```
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
```

These settings have been applied by the PCI DSS/CIS security profiles

> @s1ashi Hi, if possible to look from the server side, could you check if an error similar to the one below happens? `Algorithm negotiation fail: algorithmName="server_host_key" jsch Proposal="rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521" serverProposal="ssh-rsa,ssh-dss"`

**Comment by Destrolaric** [comment] 2023-04-04 11:37
@s1ashi Could you please execute the `ssh -Q key` on server side to show acceptable keys

**Comment by s1ashi** [comment] 2023-04-04 12:40
> @s1ashi Could you please execute the `ssh -Q key` on server side to show acceptable keys

Output:

```
ssh-ed25519
ssh-ed25519-cert-v01@openssh.com
ssh-rsa
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
ssh-rsa-cert-v01@openssh.com
ssh-dss-cert-v01@openssh.com
ecdsa-sha2-nistp256-cert-v01@openssh.com
ecdsa-sha2-nistp384-cert-v01@openssh.com
ecdsa-sha2-nistp521-cert-v01@openssh.com
```

**Comment by Destrolaric** [comment] 2023-04-06 09:54
@s1ashi I am not entirely sure this was fixed, but could you try downloading an EA version?
https://dbeaver.io/files/ea/

**Comment by s1ashi** [comment] 2023-04-06 11:04
> @s1ashi I am not entirely sure this was fixed, but could you try downloading an EA version? https://dbeaver.io/files/ea/

Tested on the version 23.0.1.202303301037

Errors are the same:

1) SSHJ
Can't initialize tunnel
Cannot establish tunnel to 10.0.2.10:22
Exhausted available authentication methods

2) JSch
Can't initialize tunnel
Cannot establish tunnel to 10.0.2.10:22
Auth fail for methods 'publickey'

**Comment by Destrolaric** [comment] 2023-04-06 11:14
@s1ashi Sorry, my mistake. Currently, EA version, which contains a possible fix, is still not deployed. I will write as soon as it is ready.

**Comment by Destrolaric** [comment] 2023-04-06 11:58
@s1ashi The new EA version has been published. Could you try again, if possible?

**Comment by serge-rider** [comment] 2023-04-17 09:00
Probablt fixed in https://github.com/dbeaver/dbeaver/issues/19243

**Closed as completed by serge-rider** 2023-04-17 09:00 UTC
Labels: xp:major, sp:1, xf:connection
