### ISSUE TITLE
Renderig bug on 4K monitor with 150% scalling

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#19310] opened 2023-03-09 16:25 UTC
### Description

Recently I moved to 4K monitor. It makes me need to set the dpi scale in display settings to 150%.
After a system restart, DBeaver renders strangely, It renders a big frame (expected size), but DBeaver itself is rendered very small. In this case, the DBeaver menu is not operational. 

![image](https://user-images.githubusercontent.com/7868445/224083529-501e5b49-4e8e-4ba1-b6a6-49b01db8ae3f.png)

Worth to mention that this white frame visible in the screenshot above in reality is rather black and constantly flashing. 

What I can temporarily do is use a built-in notebook screen. I can move the DBeaver to the notebook screen - DBeaver looks correct here. Then move it back to the 4K main monitor. at this point, the DBeaver renders properly but asks for a restart (btw the requester is centered to the edge between 2 monitors, instead of the center of either screen)

![image](https://user-images.githubusercontent.com/7868445/224085152-e247ce99-0798-4b69-95e4-524de28ac825.png)

After answering yes and the restart, DBeaver rendering is broken again.
Answering 'No' makes DBeaver remain properly rendered making it look sharp and crisp with the expected font size.
in

### DBeaver Version

CE 23.0.0

### Operating System

Fedora 37 (Wayland)

### Database and driver

N/A

### Steps to reproduce

1. use FullHD laptop and 4K monitor
2. set 4K monitor to 150% scaling and restart the system
3. set 4K monitor to the primary screen
4. run DBeaver - it should open on a 4K screen with a rendering artifact
5. move it to the laptop screen - it should get fixed
6. move to 4K screen again - it should ask for a restart in order to apply dpi scaling
7. use yes to break rendering or no to make proper rendering

**Comment by E1izabeth** [comment] 2023-03-10 09:44
Thank you for bug report. It sounds like a known issue, so, I'm closing it as a duplicate of #6581
If you think your issue is different from the one I mentioned, please, let me know.

**Closed as not planned by E1izabeth** 2023-03-10 09:44 UTC
Labels: duplicate, xo:eclipse, xf:ui
