### ISSUE TITLE
query execution time incorrect

### ISSUE THREAD

**Issue by BorisFBogdanov** [dbeaver/dbeaver#6689] opened 2019-09-06 12:29 UTC
after recent upgrade, i see query execution time shows not real time of query running, but time of result loading, instead. for example, query runs for 30 sec, then i see at status line "2 rows received, 8 ms".

  DBeaver	6.1.5.201908181949	org.jkiss.dbeaver.core.produc
running on Win10.

server:
PostgreSQL 10.5 (PostgreSQL 10.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit)

Connection without ssh, proxy, etc.
Server:PostgreSQL 10.10
Driver:PostgreSQL JDBC driver 42.2.0.jre7

**Comment by serge-rider** [comment] 2019-09-09 19:27
Looks like duplicate of #6579
Please test this in 6.2

**Closed by serge-rider** 2019-09-09 19:27 UTC
Labels: bug, duplicate

**Comment by BorisFBogdanov** [comment] 2019-09-11 06:24
Yes, now its ok.
