### ISSUE TITLE
(xx) Add feature to pin tab

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34681] opened 2024-07-06 17:15 UTC
Please add feature to pin tabs.
If tab is pinned it becomes first.

Here is example from SSMS:

https://github.com/dbeaver/dbeaver/assets/33929221/f1d2e084-adde-4ba6-950c-ec6a4a2823e0

- add **menu item** "Pin tab" to a right click menu of each tab
- show "Pin tab" **button** on each tab 
- add option in Preferences: Hide button "Pin tab" on a tab (true/false)

Why hiding a tab is needed?
- for users who want to minimize width of tabs (it is useful when working with many tabs), but they still can pin a tab using menu item of a tab

**Comment by E1izabeth** [comment] 2024-07-08 08:43
Thank you for request. I'm closing it as a duplicate of #17160

**Comment by E1izabeth** [comment] 2024-07-08 08:44
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-07-08 08:43 UTC
Labels: duplicate, xo:eclipse, xf:ui
