### ISSUE TITLE
Change back the SQL toolbar

### ISSUE THREAD

**Issue by Spoelle** [dbeaver/dbeaver#11363] opened 2021-02-16 10:12 UTC
Why is the toolbar changed into a dropdown menu? Isn't handy in my opinion.

![image](https://user-images.githubusercontent.com/19902865/108048835-cb41ad00-7047-11eb-80e5-b8c3ce6ff37d.png)

**Comment by uslss** [comment] 2021-02-16 10:27
thanks for suggestion.
close this issue as duplicate of #11352 .

**Closed as completed by uslss** 2021-02-16 10:27 UTC
Labels: duplicate
