### ISSUE TITLE
no effective field auto-completion after  "where"

### ISSUE THREAD

**Issue by MiniFullC** [dbeaver/dbeaver#12390] opened 2021-05-10 06:18 UTC
#### System information: 
- Operating system (distribution) and version:   Windows 10  20H2
- DBeaver version : 21.0.4
- Additional extensions: none

#### Connection specification:
- Database name and version:  5.6.45-log
- Driver name: mysql-connector-java-5.1.48.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  none

#### Describe the problem you're observing:
There is no effective field auto-completion after  **where**.

#### Steps to reproduce, if exist:

in Dbeaver-win64:
version: 21.0.3
The completion looks normal.
![Animation-21 02](https://user-images.githubusercontent.com/37063727/117613962-38be2f00-b19a-11eb-9ba1-f936bcc10446.gif)

in Dbeaver-win64
version: 21.0.4
![Animation-21 04](https://user-images.githubusercontent.com/37063727/117614078-5f7c6580-b19a-11eb-902c-e359e08d694d.gif)

**Comment by LonwoLonwo** [comment] 2021-05-10 10:19
Hello @MiniFullC 
Thanks for the bug report.
The problem fixed here https://github.com/dbeaver/dbeaver/issues/12168
Will be available in DBeaver 21.0.5
You can test it in [Early Access version](https://dbeaver.io/files/ea/)

![2021-05-10 13_33_18-DBeaver Enterprise 21 0 5 - _localhost_ Script-23](https://user-images.githubusercontent.com/45152336/117646380-5c7e7680-b194-11eb-897e-563ee3676ce2.png)

**Comment by LonwoLonwo** [comment] 2021-05-10 12:28
duplicate of https://github.com/dbeaver/dbeaver/issues/12185

**Closed as completed by LonwoLonwo** 2021-05-10 12:28 UTC
Labels: duplicate, xf:sql
