### ISSUE TITLE
DBeaver CE from Microsoft Store Broken After Update

### ISSUE THREAD

**Issue by rrousselot** [dbeaver/dbeaver#18997] opened 2023-02-07 18:29 UTC
### Description

![8d0d4f67-5602-4ec4-abb4-fa5b4ce06886](https://user-images.githubusercontent.com/86017553/217332958-5712d5e0-5e92-4b45-a70d-b7127bff0b1b.jpg)

Error message: A Java Runtime Environment (JRE) or Java Development Kit (JDK) must be available in order to run DBeaver.  No Java virtual machine was found after searching the following locations. <filepath\javew.exe> javaw.exe in your current PATH

### DBeaver Version

Community Edition, cant tell version because of error.

### Operating System

Windows 11

### Database and driver

N/A

### Steps to reproduce

Launch DBeaver in windows.

**Comment by E1izabeth** [comment] 2023-02-07 19:15
Thanks for the bug report. This is a known issue in the latest release.

As a workaround, you can either download DBeaver from https://dbeaver.io/files or install JRE 11 or greater.

Closing as a duplicate of #18960

**Closed as not planned by E1izabeth** 2023-02-07 19:15 UTC
Labels: duplicate, xo:windows, xf:packaging
