### ISSUE TITLE
(Oracle) Error when save new column or table

### ISSUE THREAD

**Issue by diconart** [dbeaver/dbeaver#20394] opened 2023-06-27 07:39 UTC
### Description

when save column or table 
https://i.imgur.com/doq4C94.png

this is after refresh this table 
https://i.imgur.com/5ygJHME.png

### DBeaver Version

Community version 23.1.1

### Operating System

Windows 11 Home Edition 

### Database and driver

Driver: oracle.jdbc.OracleDriver

**Comment by E1izabeth** [comment] 2023-06-27 11:02
Unfortunately images are not working 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/de0c53d9-5039-405e-8803-a1ec49cf5b2c)

Please send attachments right here in the github comment.

**Comment by E1izabeth** [comment] 2023-06-27 11:21
I reproduced the issue. Thank you for bug report.

I'm closing it as it's a duplicate of #20393

**Closed as not planned by E1izabeth** 2023-06-27 11:21 UTC
Labels: x:oracle, duplicate, xf:data
