### ISSUE TITLE
View/Format > View As > Epoch Time (etc.) does not work on Results tab

### ISSUE THREAD

**Issue by sanelson2000** [dbeaver/dbeaver#3728] opened 2018-07-02 15:51 UTC
When using View/Format > View As > Epoch Time on the Results tab, instead of getting the dialog to select the date format, I get the following menu, which is not valid for the context:
![image](https://user-images.githubusercontent.com/1462090/42173798-31b5315a-7dee-11e8-9445-eb9dceaf9228.png)
I am unable to view any ints as epoch time in this or any view other than the Table Data view, and my column preferences on the Table Data view are not persisted to the Results view.

This also affects all other items under the View As menu
On Mac OS High Sierra

**Comment by serge-rider** [comment] 2018-07-02 18:21
I can't reproduce this (on MacOS  Sierra).
Maybe this happens only in certain circumstances. According to context menu I assume you are viewing results of custom SQL query + have extra results tab. Any other details? 
Some short video maybe?

**Comment by sanelson2000** [comment] 2018-07-02 23:40
OK, I figured out how to reproduce it.  The issue occurs when the schema for the script is different than the schema that the tables actually live in and no schema is specified on the tables in the query.  For example, in our production database, there is a schema for my user, and a schema called SP.  If the script is set to execute in my personal schema, but no schema is specified on the table, somehow the query still executes (I'm not exactly sure how), but the date Epoch Date settings are not respected, and I am unable to access the View As > * menus.  If I switch the schema to the proper schema OR if I specify the schema in the query, it works as expected.  Granted, this is probably not a typical use case.  I'm not even sure exactly how it is looking up the correct table without the proper schema selected.

The following combination DOES NOT work as expected:
![image](https://user-images.githubusercontent.com/1462090/42190952-27ad65b6-7e2e-11e8-939c-13561e5d424e.png)

The following two combinations DO WORK as expected:
![image](https://user-images.githubusercontent.com/1462090/42191066-bf4ffd2a-7e2e-11e8-9f77-bda1ef13cfae.png)
![image](https://user-images.githubusercontent.com/1462090/42191100-f96fa028-7e2e-11e8-8e9a-a9dcf08874dc.png)

**Comment by sanelson2000** [comment] 2018-07-02 23:42
As you can see from the above screenshots, which I just noticed, as well, the foreign key hyperlinks are also not working properly in the first example.

**Comment by sanelson2000** [comment] 2018-07-05 13:41
Also, the above context menu

- Maximize results panel
- Set tab title

Appears whenever any other context menu is dismissed from the Results tab.  You can reproduce it by simply right clicking on any value in the Results tab, and then left clicking anywhere else on the screen to dismiss the context menu.

**Comment by serge-rider** [comment] 2018-07-07 10:29
"View as" settings are saved per-table. If DBeaver can't properly resolve table (because schema is not specified) then settings aren't working. Not sure how exactly Oracle finds this table. Maybe this is a clue and we could use the same way in DBeaver.

Context menu problem is a known issue (#2864). It is Eclipse bug and it will be fixed once we'll migrate to Eclipse 4.8 (version 5.1.4 I guess).

**Comment by sanelson2000** [comment] 2018-07-11 16:43
OK, I now know how Oracle is finding these tables.  They are set up as synonyms in the other database.  So, the query is actually going against the synonym.  It seems DBeaver is not aware of these synonyms.

`CREATE OR REPLACE NONEDITIONABLE PUBLIC SYNONYM "SPT_WORK_ITEM" FOR "SP"."SPT_WORK_ITEM";`

**Comment by serge-rider** [comment] 2018-07-29 10:01
Thanks for investigating this. Indeed DBeaver didn't check for Oracle synonyms.
Will be fixed in the next version.

**Closed by serge-rider** 2018-07-29 10:01 UTC
Labels: bug, x:oracle
