### ISSUE TITLE
NaN values in posgresql numeric field are not visualized correctly on the table data view

### ISSUE THREAD

**Issue by Crysis85it** [dbeaver/dbeaver#21952] opened 2023-11-22 17:30 UTC
### Description

Hello, I have a table with some numeric fields that may contain NaN values. dBeaver used to handle this values reporting NaN on the field when the value was Indeed NaN, now on the table i see the text of the errore stack trace of a java NumberFormatException error. If i double click that stack trace i see that the editable value is NaN, if I put a numeric value there i see it correcly. I'd categorize this issue as a regression since it appeared on your last update. (I hadn't updated for a while so I can't pinpoint the exact version in witch this regression appeared.
Thank you

### DBeaver Version

Community Edition 23.2.5.202311191730

### Operating System

Windows 11 23H2

### Database and driver

PostgreSQL 13.4 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6), 64-bit

### Steps to reproduce

1. Open the table data view in the database
2. Find a row with a Numerical field
3.  Set that numerical value to NaN
4. Uset to see NaN in the table related to that field now i see the stack trace of an error (see image)
![Screenshot 2023-11-22 181819](https://github.com/dbeaver/dbeaver/assets/11576026/95b9dcc3-6820-4246-873d-08fd7f6e8382)

**Comment by serjiokov** [comment] 2023-11-23 14:43
duplicate of https://github.com/dbeaver/dbeaver/issues/21805

**Closed as not planned** 2023-11-23 14:45 UTC
Labels: x:postgresql, duplicate, xf:data

**Comment by Crysis85it** [comment] 2023-11-23 15:02
Sorry, I searched for the same issue but didn't find it.
