### ISSUE TITLE
pg_dump: error: aborting because of server version mismatch

### ISSUE THREAD

**Issue by treyhodgsonbkv** [dbeaver/dbeaver#23478] opened 2024-04-20 03:41 UTC
### Description

When trying to use DBeaver to backup a PostgreSQL database (ver 16.1 hosted on AWS RDS), I performed the following actions:
Within the Database Navigator, Right click database name
Click Tools
Click Backup
Choose objects to export: Select all objects within the database, Click Next
Backup Settings: Format = Tar, Click Start

I immediately receive DBeaver notification:
**PostgreSQL dump
Error executing process**

In order to redact certain information, I replaced certain strings with "xxxxx".  Here is the DBeaver log message:

C:\Users\xxxxx\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\15\pg_dump.exe --verbose --host=xxxxx.xxxxx.xxxxx --port=5432 --username=xxxxx --format=t --file C:\Users\xxxxx\xxxxx\xxxxx/xxxxx.tar -n "public" xxxxx
Task 'PostgreSQL dump' started at Fri Apr 19 21:01:30 MDT 2024
**pg_dump: error: aborting because of server version mismatch**

**pg_dump: detail: server version: 16.1; pg_dump version: 15.3**

Task 'PostgreSQL dump' finished at Fri Apr 19 21:01:31 MDT 2024
2024-04-19 21:01:31.317 - IO error: Process failed (exit code = 1). See error log.
2024-04-19 21:01:31.317 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

### DBeaver Version

24.0.2.202404071654

### Operating System

Windows 10 Pro

### Database and driver

Database = PostgresSQL v 16.1
Host = AWS RDS
DBeaver Driver = postgres-jdbc 
Driver Library = org.postgresql:postgresql:RELEASE [42.7.2]
PostgreSQL Binaries: Product Version: psql (PostgreSQL) 15.3

### Additional context

PostgreSQL 15.3 Release date: 2023-05-11
PostgreSQL 16.0 Release date: 2023-09-14
PostgreSQL 16.1 Release date: 2023-11-09
PostgreSQL 16.2 Release date: 2024-02-08

DBeaver should update the default driver binaries package from 15.x to 16.x

**Comment by E1izabeth** [comment] 2024-04-23 08:22
Thank you for report. You can change it manually here
![image](https://github.com/dbeaver/dbeaver/assets/28875055/9c464378-4e29-45da-b94e-c3a0da26b8f4)

**Comment by E1izabeth** [comment] 2024-04-25 13:08
Thank you for request. I'm closing it as a duplicate of #21241

**Closed as not planned by E1izabeth** 2024-04-25 13:08 UTC
Labels: x:postgresql, duplicate, xf:native clients

**Comment by mohamed-montaser91** [comment] 2024-07-21 10:44
@E1izabeth what should i do if I'm using postgres on docker?
