### ISSUE TITLE
endlessly trying to connect to an inaccessible resource

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#9110] opened 2020-06-26 07:24 UTC
Dbeaver 7.1.1

1. Open SQL Editor with current connetion asu_prod
2. Do sql query "query1" 
3. Switched to another programm
4. After 30minutes switched to Dbeaver. Do sql query "query1". Dbeaver trying to execute query  by very long time 2-7minutes. 
![изображение](https://user-images.githubusercontent.com/61137576/85830678-6bd81980-b7a6-11ea-9edc-5f82a44be371.png)

And show modal window with error "asu_prod inaccessible"

5. I swiched database in this window of SQL Editor. But Dbeaver endlessly trying to connect to an inaccessible resource
![изображение](https://user-images.githubusercontent.com/61137576/85830888-c96c6600-b7a6-11ea-89ee-2d5604bea072.png)

6. I closed this SQL Editor window. Open new  SQL Editor window with another resource asu_dev, but Dbeaver endlessly trying to connect to an inaccessible resource asu_prod

![изображение](https://user-images.githubusercontent.com/61137576/85831442-c3c35000-b7a7-11ea-96ab-984476852a35.png)

access to database doing with the VPN

**Comment by uslss** [comment] 2020-06-26 09:24
thanks for the bug report

**Comment by jdvor** [comment] 2020-07-07 16:16
Maybe check #8405, the symptoms seems rather similar.

**Comment by detkliff** [comment] 2020-07-30 06:37
in version 7.1.3 this problem not resolved

**Comment by detkliff** [comment] 2020-08-03 06:21
in version 7.1.4 this problem not resolved

**Comment by detkliff** [comment] 2020-08-25 09:35
in version 7.1.5 this problem not resolved
Dbeaver endlessly trying to connect to an inaccessible resource
![изображение](https://user-images.githubusercontent.com/61137576/91158472-19e93c80-e6e0-11ea-9faa-4a9a1c23680d.png)

**Comment by detkliff** [comment] 2020-09-14 11:11
in version 7.2.0 this problem not resolved
Dbeaver endlessly trying to connect to an inaccessible resource

**Comment by uslss** [comment] 2021-03-04 10:37
closed as a duplicate of #6903

**Closed by uslss** 2021-03-04 10:37 UTC
Labels: bug, duplicate
