### ISSUE TITLE
SQL o/p result Pin the tab is not working  and Keep opening in Same pined TAB - pls FIX IT ASAP 

### ISSUE THREAD

**Issue by RajeevHBK1985** [dbeaver/dbeaver#35195] opened 2024-08-13 15:24 UTC
### Description

Version 24.1.4.202408041450
Release Date : Aug 5 
I have run 1 query and o/p put in pined and 
![Screenshot 2024-08-13 204938](https://github.com/user-attachments/assets/49752711-15e2-40bc-af9e-0cd8865b6f88)

again I have run another query and  the o/p  is opened same PIN tab. This is really irritating - This issue started with new version pls fix this ASAP - or let me Know how to fix it 
![Screenshot 2024-08-13 205124](https://github.com/user-attachments/assets/7a915f0a-3891-4bdb-89d1-4cffe54b3409)

### DBeaver Version

Version 24.1.4.202408041450

### Operating System

windows 12

### Database and driver

DB2

**Comment by E1izabeth** [comment] 2024-08-13 15:39
Thank you for bug report.
I'm closing it as it's a duplicate of https://github.com/dbeaver/dbeaver/issues/35072

You can try Early Access version with fix (https://dbeaver.io/files/ea/) or wait for the next release

**Closed as not planned by E1izabeth** 2024-08-13 15:39 UTC
Labels: duplicate, xf:sql execution
