### ISSUE TITLE
reuseWorkspace option not preventing Can't lock workspace dialog

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#7310] opened 2019-11-28 11:34 UTC
#### System information: 
- Win 10 Enterprise Ver 1903
- DBeaver version 6.2.4, 6.3.0
- None

#### Connection specification:
- Oracle 12.2
- Jdbc
- No

#### Describe the problem you're observing:

I am trying to open a file in an existing instance of DBeaver. Yesterday worked fine all day by simply specifying the path to DBeaver and the filename. 

Today I get the DBeaver - Can't lock workspace dialog every time I do this.

#### Steps to reproduce, if exist:

Open DBeaver

"c:\Program Files\DBeaver\dbeaver.exe" -reuseWorkspace

DBeaver - Can't lock workspace dialog appears. 

NB this happens whether or not I specify -reuseWorkspace. Yesterday it worked fine, without -reuseWorkspace. The main difference is that today my connection is via a VPN, whereas yesterday I was connected directly to the internal network. Not that I would expect this to make a difference...

#### Include any warning/errors/backtraces from the logs

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3901396/dbeaver-debug.log)

**Comment by serge-rider** [comment] 2019-12-09 19:56
Look like it was fixed in 6.3.0. Can't reproduce anymore.

**Comment by bobf32** [comment] 2019-12-10 10:17
> Look like it was fixed in 6.3.0. Can't reproduce anymore.

Don't think so. Occurs in 6.3.0 too.

**Comment by bobf32** [comment] 2019-12-10 13:07
Perhaps this will help:

`
C:\Users\uC191773>"c:\Program Files\DBeaver\dbeaver-cli.exe" -f stash0.out -reuseWorkspace
2019-12-10 13:05:47.467 - > Start DBeaver Standalone [org.jkiss.dbeaver.core.application 6.3.0.201912011827]
2019-12-10 13:05:47.468 - > Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.0.v20191024-1147]
2019-12-10 13:05:47.475 - > Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.600.v20191025-1525]
2019-12-10 13:05:47.493 - > Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.600.v20191026-0839]
2019-12-10 13:05:47.523 - Error reading RMI config
java.rmi.ConnectIOException: Exception creating connection to: 192.168.0.66; nested exception is:
        java.net.SocketException: Permission denied: connect
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(Unknown Source)
        at java.rmi/sun.rmi.server.UnicastRef.newCall(Unknown Source)
        at java.rmi/sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
        at org.jkiss.dbeaver.core.application.rpc.InstanceClient.createClient(InstanceClient.java:44)
        at org.jkiss.dbeaver.core.application.DBeaverCommandLine.handleCommandLine(DBeaverCommandLine.java:250)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:162)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.net.SocketException: Permission denied: connect
        at java.base/java.net.PlainSocketImpl.connect0(Native Method)
        at java.base/java.net.PlainSocketImpl.socketConnect(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/java.net.Socket.<init>(Unknown Source)
        at java.base/java.net.Socket.<init>(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(Unknown Source)
        ... 20 more
2019-12-10 13:05:47.555 - No running DBeaver instance found
2019-12-10 13:05:47.584 - Create display
2019-12-10 13:05:47.651 - > Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.500.v20191014-1638]
`

**Comment by serge-rider** [comment] 2019-12-16 14:00
Fixed one more time (there was a problem with instance server config file)

**Comment by uslss** [comment] 2019-12-16 15:37
verified

**Closed by uslss** 2019-12-16 15:37 UTC
Labels: bug

**Comment by bobf32** [comment] 2019-12-18 10:10
> Fixed one more time (there was a problem with instance server config file)

Thanks @serge-rider. May I ask if this fix will be included in 6.3.1?

**Comment by serge-rider** [comment] 2019-12-21 10:15
It will. See milestone.
