### ISSUE TITLE
An error occurred while automatically activating bundle org.eclipse.ui.ide (167)

### ISSUE THREAD

**Issue by Joepadi** [dbeaver/dbeaver#34685] opened 2024-07-07 18:14 UTC
### Description

when starting the new Version of DBeaver after insallation of the new update (dbeaver-ce-24.1.2-x86_64-setup) it stops whit Error masage
An error occurred while automatically activating bundle org.eclipse.ui.ide (167) in log file
OS W8pro, would it better to switch to an older Version?

### DBeaver Version

Community edition

### Operating System

W8pro

### Database and driver

SQL

### Steps to reproduce

[1720374799283.log](https://github.com/user-attachments/files/16120281/1720374799283.log)

**Comment by serge-rider** [comment] 2024-07-08 08:26
Probably duplicate of #34034

**Closed as completed by serge-rider** 2024-07-08 08:26 UTC
Labels: duplicate
