### ISSUE TITLE
dbeaver creates eclipse artifacts in user $HOME directory

### ISSUE THREAD

**Issue by untainsYD** [dbeaver/dbeaver#21610] opened 2023-10-20 15:02 UTC
## HOST
```sh
> uname -a
Linux untainsYD-workstation 6.5.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 10 Oct 2023 21:10:21 +0000 x86_64 GNU/Linux
```

Installed via pacman [dbeaver](https://archlinux.org/packages/?name=dbeaver) package.

## PROBLEM
When i run/start dbeaver it creates `~/.eclipse`, `.swt` and `.local` folders and files ignoring XDG specification.

I have configured that $XDG_DATA_HOME should point to `.config` folder.
```sh
> echo $XDG_DATA_HOME
/home/untainsYD/.config/local/share
```

But dbeaver ignores it, and creates a new `.local` folder.
```sh
> ls -lah .local/share/
Permissions Size User      Group     Date Modified Name
drwxr-xr-x     - untainsYD untainsYD 20 Oct 17:53   applications
drwxr-xr-x     - untainsYD untainsYD 20 Oct 17:53   DBeaverData
```

And it also creates `.eclipse` and `.swt` folder as well in home directory, ignoring xdg.
```sh
> ls -lah .eclipse
Permissions Size User      Group     Date Modified Name
drwxr-xr-x     - untainsYD untainsYD 20 Oct 17:53   org.jkiss.dbeaver.product_23.2.2_1078795723_linux_gtk_x86_64
> ls -lah .swt
Permissions Size User      Group     Date Modified Name
.rw-r--r--    81 untainsYD untainsYD 20 Oct 18:01   trims.prefs
```

## DBeaver start log
```
x dbeaver
Picked up _JAVA_OPTIONS: -Djava.util.prefs.userRoot=/home/untainsYD/.config/java
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.14.0.v20230317-0901]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.1000.v20220801-1135]
> Start DBeaver Application Standalone [org.jkiss.dbeaver.ui.app.standalone 23.2.2.202310151102]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.5.0.v20230526-1051]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.21.0.v20230526-1500]
> Start Expression Language [org.eclipse.core.expressions 3.9.0.v20230317-0901]
> Start DBeaver Usage Statistics [org.jkiss.dbeaver.ui.statistics 1.0.12.202310151102]
> Start DBeaver Desktop Application Core [org.jkiss.dbeaver.core 23.2.2.202310151102]
2023-10-20 17:53:41.528 - DBeaver 23.2.2.202310151102 is starting
2023-10-20 17:53:41.529 - OS: Linux 6.5.7-arch1-1 (amd64)
2023-10-20 17:53:41.529 - Java version: 17.0.8 by Eclipse Adoptium (64bit)
2023-10-20 17:53:41.529 - Install path: '/usr/lib/dbeaver'
2023-10-20 17:53:41.529 - Instance path: 'file:/home/untainsYD/.local/share/DBeaverData/workspace6/'
2023-10-20 17:53:41.529 - Memory available 138Mb/1024Mb
2023-10-20 17:53:41.531 - Create display

(java:320026): Gdk-CRITICAL **: 17:53:41.533: gdk_threads_set_lock_functions: assertion 'gdk_threads_lock == NULL && gdk_threads_unlock == NULL' failed
2023-10-20 17:53:41.608 - Initializing DBeaver 23.2.2
2023-10-20 17:53:41.609 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 23.2.2.202310151102
2023-10-20 17:53:41.609 - Initialize desktop platform...
2023-10-20 17:53:41.728 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.10.0.v20230425-0513]
> Start Core Resource Management [org.eclipse.core.resources 3.19.0.v20230510-1240]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.116.202310151102]
> Start Team Support Core [org.eclipse.team.core 3.10.0.v20230317-0901]
2023-10-20 17:53:41.825 -
2023-10-20 17:53:41.826 - 	Refreshing workspace.
2023-10-20 17:53:41.827 - Refreshing workspace contents
2023-10-20 17:53:41.912 - Initialize base platform...
2023-10-20 17:53:41.935 - Platform initialized (326ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.116.202310151102]
2023-10-20 17:53:41.983 - Starting instance server at http://localhost:44845
2023-10-20 17:53:41.989 - Run workbench
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.131.202310151102]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.17.0.v20230501-1823]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.4.0.v20230429-1914]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.6.0.v20230501-1823]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.4.0.v20230501-1823]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.14.0.v20230501-1823]
> Start Eclipse e4 core commands [org.eclipse.e4.core.commands 1.1.0.v20230501-1823]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.18.0.v20230211-1150]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.14.0.v20230501-1533]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.5.0.v20230501-1823]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.16.0.v20230525-0648]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.18.0.v20230429-1914]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.15.0.v20230317-0802]
> Start Eclipse SDK Themes [org.eclipse.ui.themes 1.2.2200.v20230220-0932]
> Start jna [com.sun.jna 5.13.0]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.5.0.v20230317-0901]
> Start Internet Connection Management [org.eclipse.core.net 1.5.0.v20230317-0901]
2023-10-20 17:53:43.168 - Configure workbench window
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.106.202310151102]
2023-10-20 17:53:43.273 - Total database drivers: 107 (107)
> Start Help System Core [org.eclipse.help 3.10.0.v20230317-0802]
2023-10-20 17:53:43.368 - Create actions
2023-10-20 17:53:43.376 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2023-10-20 17:53:43.376 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2023-10-20 17:53:43.377 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2023-10-20 17:53:44.027 - Initialize workbench window
2023-10-20 17:53:44.030 - Finish initialization
Warning: NLS missing message: pref_page_content_editor_group_representation_content in: org.jkiss.dbeaver.ui.controls.resultset.internal.ResultSetMessages
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.116.202310151102]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.116.202310151102]
> Start GEF Classic Draw2d [org.eclipse.draw2d 3.13.0.202306071707]
> Start GEF Classic GEF (MVC) [org.eclipse.gef 3.14.0.202306071707]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.76.202310151102]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.76.202310151102]
> Start Default Text Editor [org.eclipse.ui.editors 3.16.0.v20230329-1609]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.17.0.v20230316-1200]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.153.202310151102]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.122.202310151102]
2023-10-20 17:53:46.080 - Open [https://dbeaver.io/product/version.xml]
> Start DBeaver UI Editors - Connections [org.jkiss.dbeaver.ui.editors.connection 1.0.107.202310151102]
```

**Comment by arhayka** [comment] 2023-11-15 10:51
Duplicate of https://github.com/dbeaver/dbeaver/issues/21574

**Comment by untainsYD** [comment] 2023-11-15 19:59
> Duplicate of #21574

No, this issue appears on linux, but issue that you have referenced is about windows.

On windows you do not have `$XDG_DATA_HOME ` and XDG specification as well.

**Comment by mztbc** [comment] 2024-11-09 13:36
I wonder why this was closed as completed?

It would be _very nice_ if Dbeaver adhered to the XDG specification and stopped creating .eclipse and .swt at every start.

**Closed as completed** 2024-11-22 16:42 UTC
Labels: duplicate, xo:linux, xo:eclipse

**Comment by DodoLeDev** [comment] 2025-02-11 11:55
This problem also applies to [Flatpak version of DBeaver](https://github.com/flathub/io.dbeaver.DBeaverCommunity/), because the sandboxing takes advantage of XDG_BASE_DIRS, to allow the app to put its configuration in dedicated directories.
Because of this issue, we have to allow full $HOME access in order to let DBeaver pollute our home dir with its non-XDG-compliant configuration files

**Comment by kjkent** [comment] 2025-04-24 23:51
Agreed -- it's great and appropriate that the feature flag is added, but @untainsYD could the issue be re-opened?

I understand that the odd extra folder might not be seen as a problem, but the `$HOME` dir quickly fills up with dotfiles/folders which is a pain for organization. On my machine, `$HOME` is a 40/60 mix of `.eclipse`, `.mozilla`, `.pki`, `.ssh`, etc. and folders I want. If all software in my `.config` folder took the same approach, there'd be 50+ more .xyz folders in `$HOME` (following which, complete anarchy :) )

PS - For DBeaver/Eclipse packages, this seems to be a non-trivial issue, at least where SWT (`~/.swt`) is concerned. See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1168

PPS - Thanks to all the contributors for DBeaver and their work! 🙏🏻
