### ISSUE TITLE
Error after upgrade to v23.1.5 - theme error

### ISSUE THREAD

**Issue by cmcconomyfwig** [dbeaver/dbeaver#21057] opened 2023-08-31 01:27 UTC
### Description

Right after upgrading, when I launch dbeaver, I am greeted with a dialog reading as follows:

> An error has occurred. See error log for more details.
Cannot invoke "org.eclipse.e4.ui.css.swt.theme.IThemeEngine.getActiveTheme()" because the return value of "org.eclipse.ui.IWorkbench.getService(java.lang.Class)" is null

This appears to prevent any UI panes from rendering.

In the meantime I've downloaded and reinstalled 23.1.4 which continues to work as before.

### DBeaver Version

23.1.5

### Operating System

Macos 13.4 (arm64)

### Steps to reproduce

Launch app (that's it!)

**Comment by E1izabeth** [comment] 2023-08-31 03:24
Thank you for bug report.

It's a duplicate of #20931. The fix will be available in the next release.

You could try early access version https://dbeaver.io/files/ea/

**Closed as not planned** 2023-08-31 03:24 UTC
Labels: duplicate
