### ISSUE TITLE
Autocomplete Add double quote to column names even if not needed.

### ISSUE THREAD

**Issue by KaynoLadd** [dbeaver/dbeaver#20450] opened 2023-07-03 08:01 UTC
### Description

Hello,
Since last update, Dbeaver autocomplete or drag&drop add " to all DB/Column names, even if not needed.  
`"EFDM_PROD_DB"."CI_EMD_PAVING_DEMAND"."MACHINE_MISC_ORDER_HEADER"`

Is it a feature I can disable? or a bug?

Regards,

### DBeaver Version

Community Edition 23.1.1

### Operating System

WIndows 10

### Database and driver

Snowflake JDBC

### Steps to reproduce

1. Add DB name
2. Quotes are added automatically

**Comment by E1izabeth** [comment] 2023-07-03 08:36
Thank you for bug report.
It's a duplicate of #20391. The fix is available in the early access version https://dbeaver.io/files/ea/

**Closed as not planned by E1izabeth** 2023-07-03 08:36 UTC
Labels: duplicate, x:snowflake

**Comment by zhaoxiangyublzcat** [comment] 2023-07-10 03:44
The problem in 23.1.2 with Calcite driver  still exists

**Comment by E1izabeth** [comment] 2023-07-10 08:32
@zhaoxiangyublzcat 
Please create a separate discussion or issue about Calcite. This discussion is about Snowflake.
