### ISSUE TITLE
[Sybase] Table statistic is not shown correctly

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#29274] opened 2024-04-30 00:58 UTC
### Description

Tested on Sybase ASE 16
STR:

1. Connect to Sybase 
2. Open statistic tab
Actual result - table size is always = -1
![iScreen Shoter - DBeaver Community - 240430025744](https://github.com/dbeaver/dbeaver/assets/84867187/f08a5373-543e-4346-84a9-ca64338a163e)

```
com.sybase.jdbc4.jdbc.SybSQLException: SQL Anywhere Error -143: Column '@@maxpagesize' not found
	at com.sybase.jdbc4.tds.Tds.processEed(Tds.java:4201)
	at com.sybase.jdbc4.tds.Tds.nextResult(Tds.java:3318)
	at com.sybase.jdbc4.jdbc.ResultGetter.nextResult(ResultGetter.java:78)
	at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:302)
	at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:284)
	at com.sybase.jdbc4.jdbc.SybStatement.queryLoop(SybStatement.java:2655)
	at com.sybase.jdbc4.jdbc.SybStatement.executeQuery(SybStatement.java:2641)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.executeQuery(SybPreparedStatement.java:274)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.mssql.model.generic.SQLServerGenericTable.readTableStats(SQLServerGenericTable.java:194)
	at org.jkiss.dbeaver.ext.mssql.model.generic.SQLServerGenericTable.getRowCount(SQLServerGenericTable.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$1(ObjectPropertyDescriptor.java:431)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$2(ObjectPropertyDescriptor.java:450)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:448)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:383)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:94)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:78)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### DBeaver Version

24.0.4

### Operating System

mac M1 Sonoma

**Comment by LonwoLonwo** [comment] 2024-04-30 11:11
Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/18718

**Closed as completed by LonwoLonwo** 2024-04-30 11:11 UTC
Labels: duplicate, x:sybase, xf:metadata, xp:normal
