### ISSUE TITLE
[Oracle] Error when reading job arguments

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4749] opened 2018-12-07 12:50 UTC
Seems like XMLType is not supported.

![obraz](https://user-images.githubusercontent.com/20753183/49648648-df7ccf00-fa26-11e8-9f33-3df78decea4b.png)

**Comment by serge-rider** [comment] 2018-12-20 12:01
Duplicate of #171
(you need to add xdb6.jar and xmlparserv2.jar)

**Closed by serge-rider** 2018-12-20 12:01 UTC
Labels: duplicate, question, x:oracle
