### ISSUE TITLE
DBeaver closes no matter what you do in 'Exit DBeaver' pop up window

### ISSUE THREAD

**Issue by niotisokin** [dbeaver/dbeaver#34564] opened 2024-06-28 11:48 UTC
### Description

No matter if Ι press yes, no or just close the 'Exit DBeaver' pop up window, dbeaver always exits.

### DBeaver Version

Community Edition 24.1.1

### Operating System

Ubuntu 22.04.4 LTS

### Steps to reproduce

1. Open DBeaver
2. (Optional) do some work
3. Close DBeaver
4. Press no or close 'Exit DBeaver' pop up window
5. DBeaver exits

**Comment by E1izabeth** [comment] 2024-06-28 11:49
Thank you for bug report. It's a duplicate of #34462
The fix will be available in the next release.

**Closed as not planned by E1izabeth** 2024-06-28 11:49 UTC
Labels: duplicate
