### ISSUE TITLE
Add type DateTime to Result Set formatting for BigQuery

### ISSUE THREAD

**Issue by UkrZilla** [dbeaver/dbeaver#2512] opened 2017-11-13 12:46 UTC
Hi,
Please add type DateTime to Result Set formatting for BigQuery in order to 
format it column value from 'yyyy-MM-ddTHH:mm:ss' to 'yyyy-MM-dd HH:mm:ss', like Timestamp

Thanks

**Comment by serge-rider** [comment] 2017-11-19 09:12
Please post more details.
Does DBeaver show NULLs instead of timestamp or there is some other error?

**Comment by UkrZilla** [comment] 2017-11-21 13:57
Hi @serge-rider 
DBeaver shows DateTime as 'yyyy-MM-ddTHH:mm:ss', but since DBeaver does not have type DateTime in Result Set formatting for BigQuery I can't format it.

![image](https://user-images.githubusercontent.com/5429192/33076106-64f67818-ced4-11e7-896b-9d3a1ea9297c.png)

![image](https://user-images.githubusercontent.com/5429192/33076170-a70d9060-ced4-11e7-9e8f-cabc811db6df.png)

**Comment by serge-rider** [comment] 2017-11-23 18:28
Looks like this column was recognized as String data type. 
Maybe it is a driver limitation or maybe something else. What is the real column data type (e.g. in metadata panel)?

**Comment by UkrZilla** [comment] 2017-11-24 08:33
Hi @serge-rider Real column data type in metadata panel is DateTime

![image](https://user-images.githubusercontent.com/5429192/33201856-e98ab80c-d102-11e7-92bb-e848c2fafce1.png)

**Comment by serge-rider** [comment] 2017-11-26 11:44
I think we'll need a special extension for BigQuery to support this..

**Comment by UkrZilla** [comment] 2018-01-17 16:28
Hi @serge-rider 
Could you please fix it?

**Comment by r-richmond** [comment] 2018-02-19 22:10
I think this has become a duplicate of #1687? (& +1 for 1687)

**Comment by r-richmond** [comment] 2018-10-03 03:02
This issue was fixed in the BigQuery JDBC driver

```
Released 2018-09-13

 * [GAUSS-686] Data type DATETIME mapped to SQL_TYPE_TIMESTAMP

   The Google BigQuery data type DATETIME is now mapped to the SQL data type 
   SQL_TYPE_TIMESTAMP. Previously this data type was mapped to the SQL data 
   type SQL_VARCHAR.
```

**Closed** 2020-03-16 14:22 UTC
Labels: feature request
