### ISSUE TITLE
Sybase procedure code error

### ISSUE THREAD

**Issue by sergionadal** [dbeaver/dbeaver#23426] opened 2024-04-15 06:28 UTC
### Description

From Dbeaver 24.0.0, Sybase databases show error when i try to view a procedure code:

* ERROR WHILE READING SOURCE:

SQL Error [208] [42S02]: SYS.SYSPROCEDURE not found. Specify owner.objectname or use sp_help to check whether the object exists (sp_help may produce lots of output).

*/
[dbeaver-diagnostic-info-1713161812227.zip](https://github.com/dbeaver/dbeaver/files/14974919/dbeaver-diagnostic-info-1713161812227.zip)

### DBeaver Version

24.0.2

### Operating System

Windows 10

### Database and driver

Sybase jTDS

### Steps to reproduce

Open a database with Sybase procedure. Click in a procedure. In the properties window, select source tab. In the text editor can see the error.

**Comment by LonwoLonwo** [comment] 2024-04-15 08:30
Hello @sergionadal 

Thanks for the report.

It is a duplicate of: https://github.com/dbeaver/dbeaver/issues/23259

I'm closing this one. You can follow the original ticket.

**Closed as completed by LonwoLonwo** 2024-04-15 08:30 UTC
Labels: duplicate, x:sybase, xf:metadata
