### ISSUE TITLE
Default column order in filter settings incorrect

### ISSUE THREAD

**Issue by JMarkMurphy** [dbeaver/dbeaver#6208] opened 2019-07-02 14:34 UTC
#### System information: 
- Windows 10
- DBeaver version 6.1.1.201906240635
- Java version: included

#### Connection specification:
- DB2 for i v7.2
- JTOPEN
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Sometimes the columns in the result set are in the wrong order. I believe that this has to do with the filters. the metadata shows the correct column order, but when I open the filter settings dialog, the column order is incorrect.

Query metadata:
![image](https://user-images.githubusercontent.com/2379218/60520982-5b38b480-9cb4-11e9-8965-5367c2c0d99b.png)

Filter Settings:
![image](https://user-images.githubusercontent.com/2379218/60521045-802d2780-9cb4-11e9-9324-e1c37b8ac48f.png)

The problem may have to do with multiple columns having the same name in the result set. This does not cause problems with the result set metadata, but the filter settings do not line up with that metadata. The default column order in the filter should be exactly the same as in the result set.

**Comment by cumanacr** [comment] 2019-07-03 22:43
#### System information: 
- Operating system (distribution) and version 
  - *Distributor ID:* **neon**
  - *Description:*    **KDE neon User Edition 5.16**
  - *Release:*        **18.04**
  - *Codename:*       **bionic**
- DBeaver version **6.1.1.201906240635**
- Java version **"1.8.0_201"**
- Additional extensions **Nope**

#### Connection specification:
- Database name and version 
  - **Server version: 10.2.22-MariaDB-1:10.2.22+maria~bionic-log mariadb.org binary distribution**
- Driver name **MySQL standard driver**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **SSH Tunnel**

#### Describe the problem you're observing:
I think I'm experiencing the same problem @JMarkMurphy is having.
When you run the query with CTRL+ENTER the first time it works normally.
This issue arises when you run the query with CTRL+ENTER a second time and onwards.
A workaround I found is running the query using CTRL+TAB I think it works because it's like run it for the first time.
It's my best guess  `¯\_(ツ)_/¯`
Regards

![Selection-09-2019-07-03](https://user-images.githubusercontent.com/6874136/60628821-6bce5500-9db0-11e9-9018-410912f345f9.jpg)

![Selection-04-2019-07-03](https://user-images.githubusercontent.com/6874136/60628643-9d92ec00-9daf-11e9-8f5b-f7d4d14b349d.jpg)

![Selection-06-2019-07-03](https://user-images.githubusercontent.com/6874136/60628626-88b65880-9daf-11e9-819c-a1bfe01de76f.jpg)

#### Steps to reproduce, if exist:
I manage to isolate my issue on a 3 columns query.
You can reproduce it with a [SuiteCRM](https://github.com/salesagility/suitecrm) instance if need it.
```sql
SELECT
q.`number` AS quote_number ,
q.name quote_name,
pq.`number` AS 'line_number'
FROM aos_products_quotes pq
LEFT JOIN aos_quotes q ON pq.parent_id = q.id
LIMIT 10
```

#### Include any warning/errors/backtraces from the logs
No logs

**Comment by serge-rider** [comment] 2019-07-04 20:23
Looks like duplicate of #6147
Could you check Early Access version (https://dbeaver.io/files/ea)? It already contains the fix.

**Comment by cumanacr** [comment] 2019-07-04 23:04
Yep, Everything ok in Early Access version, it works as expected.
I tested with:
```
dbeaver-ce_6.1.2_amd64.deb                         04-Jul-2019 10:26     56M 
```
Thanks @serge-rider 

I think you're one of the better open-source software author and community managers out there in the wild.

Please, keep up the good work.

**Comment by serge-rider** [comment] 2019-07-05 05:22
Thank you for testing

**Closed** 2019-07-05 14:47 UTC
Labels: bug, duplicate
