### ISSUE TITLE
SQL files always revert to 'file' format when saved

### ISSUE THREAD

**Issue by Riwaj1** [dbeaver/dbeaver#14335] opened 2021-10-21 16:04 UTC
#### System information: 
- Operating System
   Edition: Windows 10 Pro  
   Version: 21H1
   Installed on: 22/02/21
   OS Build: 19043.1237

- DBeaver version
  Version:  21.2.3.202110151816

#### Connection specification:
- Using Amazon AWS VPN Client 

#### Describe the problem you're observing:
The problem that has been occurring is that whenever I save a SQL file, it automatically changes the file type and becomes 'file' rather than 'SQL: source file'. The only way to make sure that the file is saved as a SQL file, is to save the script under the name 'Script 7' (or whatever the original number that dbeaver had given it), and then go back and rename the file afterwards.
When I do save the file type, *.sql is selected.
The issue seems to have started after I updated dbeaver, 2 updates ago (not sure what version that is, sorry).

The pictures attached represent what happens when I change the script name.

#### Steps to reproduce, if exist:
1) Click Save As
2) Click Save
3) See the wrong file type for your saved file 

#### How it happens in pictures 
![Picture 1](https://user-images.githubusercontent.com/71048270/138316320-39139da2-75e3-4303-8d96-5ff4fc96db80.png)
This first picture is me saving the file as the original name on Dbeaver.

![Picture 2](https://user-images.githubusercontent.com/71048270/138316435-0ef80a5a-acc8-460f-9fba-484220313ebe.png)
This second picture is me saving the file with a name that I have selected on Dbeaver. 

![Picture 3](https://user-images.githubusercontent.com/71048270/138316436-112eb93e-5475-4e07-ae09-1e509b953a79.png)
After saving and checking 'my documents'. The one with the original name has the correct file type, whereas the other one does not.

Edit- I changed the pictures as I was unable to read them myself, so I doubt anyone else reviewing them could read them either...

**Comment by LonwoLonwo** [comment] 2021-10-21 16:54
Hello @Riwaj1 
Thanks for the bug report!
We are going to fix it in the next releases.

Duplicate of https://github.com/dbeaver/dbeaver/issues/14013

**Closed as completed by LonwoLonwo** 2021-10-21 16:54 UTC
