### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by beiyinghu** [dbeaver/dbeaver#14659] opened 2021-11-23 17:14 UTC
#### System information: 
- Operating system (distribution) and version macOS 11.6 (20G165)
- DBeaver version 21.2.5
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

<img width="1429" alt="截屏2021-11-24 上午1 01 06" src="https://user-images.githubusercontent.com/47131226/143071392-ad51d14b-0408-47ab-999b-1b05545a52d6.png">
<br/>
the code did not showing<br/>

**Comment by ShadelessFox** [comment] 2021-11-23 18:38
Hello @beiyinghu,

Thanks for the report.

Duplicate of #13882

**Closed as completed by ShadelessFox** 2021-11-23 18:38 UTC
Labels: duplicate, xo:macos
