### ISSUE TITLE
Freezes or is very slow loading and executing large scripts

### ISSUE THREAD

**Issue by ygmarchi** [dbeaver/dbeaver#33267] opened 2024-05-21 09:54 UTC
### Description

Loading a large script (in my case 350 KB, so not so big), the user interface freezes e respond after tens of seconds. Execution is even worse.

### DBeaver Version

Comunity Edition 24.0.4

### Operating System

Windows 11

### Database and driver

Microsoft SQL Server 2022 (RTM-GDR) (KB5035432) - 16.0.1115.1 (X64) 
	Mar 15 2024 01:13:46 
	Copyright (C) 2022 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 22631: ) (Hypervisor)

### Steps to reproduce

Load a large script.

**Comment by E1izabeth** [comment] 2024-05-21 10:01
Please try 24.0.5 version or switch `Blank line is statement delimiter` setting to "Always"

![image](https://github.com/dbeaver/dbeaver/assets/28875055/d2ec4949-1518-467f-9741-542a65a5f01c)

**Comment by E1izabeth** [comment] 2024-05-21 10:02
I'm closing this issue as a duplicate of #29996

**Closed as not planned by E1izabeth** 2024-05-21 10:02 UTC
Labels: duplicate, wait for response, xf:sql execution

**Comment by ygmarchi** [comment] 2024-05-21 10:13
I confirm that version 24.0.5 solves the problem, thanks.
