### ISSUE TITLE
Set active instance database postgres not refresh in sql editor and toolbar

### ISSUE THREAD

**Issue by webjoel** [dbeaver/dbeaver#7522] opened 2020-01-03 21:56 UTC
1. If click in "Set active" on instance database in same connection on "Database Navigator" it not refresh in sql editor and toolbar;
2. If try in "Choose catalog/schema" on toolbar and click in the Instance, it window close unexpectedly.

#### System information: 
- Operating system (distribution) and version: Ubuntu 16.04
- DBeaver version: 6.3.1
- Databse: PostgreSQL

**Comment by webjoel** [comment] 2020-01-03 22:12
#7473

**Comment by michalk-k** [comment] 2020-01-06 17:04
I would say those are 2 separate problems. 
One as duplicate mentioned by you #7473 . The second issue is not working selector in Chose catalog/schema.

I would add that attempting to change active database using "Set active" on database instance in "Database Navigator" generates unneeded SQL queries to the current database:

```SET extra_float_digits = 3
SET application_name = 'PostgreSQL JDBC Driver'
SET application_name = 'DBeaver 6.3.2 - Main'
SELECT current_schema(),session_user
SHOW search_path```

Looks like orphans from previous functionality.

Is there any way (in current version of DBeaver) to change database the script is connected to?

TBH I don't know what was the intention of this change ('ve read that whole part has been rewritten). But I cannot see reason of removing the possibility of changing active db from context menu of Database Navigator.

**Comment by AOne-T** [comment] 2020-01-09 07:46
Same problems. The first one appeared when upgraded to 6.3. The second was in 6.2 and is still here. Ubuntu 18.04

**Comment by serge-rider** [comment] 2020-01-20 22:28
Duplicate of #7693

**Closed by serge-rider** 2020-01-20 22:28 UTC
Labels: duplicate, enhancement
