### ISSUE TITLE
plugins needs to be reinstalled after each Dbeaver update

### ISSUE THREAD

**Issue by wirowka** [dbeaver/dbeaver#21667] opened 2023-10-26 09:09 UTC
### Description

hi
Not sure whether this is a bug but very annoying behaviour.
Due to company policy we are to update each software each time a new version is released and in case of Dbeaver it means that all plugins installed need to be re-installed.
We do you plugin for Office integration.
Is it possible to configure the application so that the plugins are not removed after a new version is installed?

Thanks in advance

### DBeaver Version

community edition Version 23.2.3.202310221533

### Operating System

macOS Ventura 13.6

### Database and driver

DB independent

### Steps to reproduce

1. Install Office integration plugin for version current version
2. Update DBeaver with a new version
3. Office integration plugin is gone is needs to be re-installed.

**Comment by E1izabeth** [comment] 2023-10-26 09:46
Thank you for bug report. It's a duplicate of #5317
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2023-10-26 09:46 UTC
Labels: duplicate
