### ISSUE TITLE
Crow's Foot Notation

### ISSUE THREAD

**Issue by cacuestai** [dbeaver/dbeaver#10767] opened 2020-12-22 20:57 UTC
Hi:

Excellent application. Have you thought of a Crow's Foot Notation for database models?

Regards!

**Comment by uslss** [comment] 2020-12-23 08:22
thanks for the suggestion

**Comment by aryankarim** [comment] 2022-07-11 15:06
#1017 same topic

**Comment by E1izabeth** [comment] 2023-09-20 05:36
I'm closing it as a duplicate of #1017. It will be done in scope of that issue.

**Closed by E1izabeth** 2023-09-20 05:36 UTC
Labels: feature request, xf:erd
