### ISSUE TITLE
Sometimes cursor focus changes to result window after running SQL statement

### ISSUE THREAD

**Issue by nghoffman** [dbeaver/dbeaver#10514] opened 2020-11-26 17:31 UTC
#### System information: 
- Operating system (distribution) and version: Microsoft Windows 10 Enterprise, 10.0.17763 Build 17763
- DBeaver version: 7.2.5 (latest version)
- Additional extensions: none

#### Connection specification:
- Database name and version: Hana 2.00.051.00.1596053985
- Driver name: HANA (com.sap.db.jdbc.Driver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
In versions up to 7.2.5, when I ran SQL queries, the cursor focus always remained in the SQL editor window.  With version 7.2.5, periodically (maybe 25% of the time), the cursor focus changes to the result window.

#### Steps to reproduce, if exist:
I was trying to notice if there was a pattern, but hadn't found one yet.  Just run some SQL queries and see if it happens.

#### Include any warning/errors/backtraces from the logs
None.

**Comment by SirKlaus** [comment] 2020-11-26 20:06
I think I have the same problem and I can reproduce it. Try the following to reproduce it:

1. Execute a SELECT statement, e.g. `SELECT * FROM data.test;`
2. It displays the result in a grid view.
3. Execute an INSERT statement, e.g. `INSERT INTO "data".test ("name") VALUES('asdf');`
4. It now displays the result in a different type of view.

At this point the cursor focus leaves the editor. This happens always when the view type in the result window changes.
I tried to make a video with subtitles. I hope it helps to make it clear.

![screencast](https://user-images.githubusercontent.com/11761343/100388373-a8948f00-302a-11eb-8f9d-68d2316d1d39.gif)

**Comment by uslss** [comment] 2020-11-30 05:39
duplicates #10415 .

Seems to be fixed in 7.3.0.

Anyway, thanks for the report :)

**Closed by uslss** 2020-11-30 05:39 UTC
Labels: bug, duplicate

**Comment by nghoffman** [comment] 2020-11-30 14:08
Yes, that's it.  Turns out the focus was disappearing, not changing to the result window, so your above descriptions match what I was seeing.

Sorry for the duplication. I searched for things like "focus changes" but not "focus disappears", so I missed the earlier issue.

I've switched back to 7.2.4 until 7.3.0 becomes available.  Thanks!
