### ISSUE TITLE
Cannot update Oracle date column

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [dbeaver/dbeaver#5206] opened 2019-02-04 21:44 UTC
#### System information: 
- Operating system (distribution) and version: Linux Mint 19 Tara
- DBeaver version: 5.3.3.201901202008
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_201-b09)

#### Connection specification:
- Database name and version: Oracle 11g
- Driver name: oracle.jdbc.OracleDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I have a table with an Oracle Date column:

```
CREATE TABLE "SITE"."CONS_ACCOUNT_LOCK" 
   (	"CONS_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"FAILED_ATTEMPTS" NUMBER(3,0) DEFAULT 1, 
	"TIME_LOCKED" DATE, 
	 CONSTRAINT "CONS_ACCOUNT_LOCK_PK" PRIMARY KEY ("CONS_ID")
```

When I try to edit the value of TIME_LOCKED I get a NullPointerException.

#### Steps to reproduce, if exist:

1. Create  a table with the schema above.
2. Add a row with a value for TIME_LOCKED not through DBeaver.
3. Select the TIME_LOCKED cell and hit SHIFT + ENTER.
4. Try setting the value to 10 minutes before the current value (ie, 2019-02-04 15:27:05 becomes 2019-02-04 15:17:05)
5. Get NPE

#### Include any warning/errors/backtraces from the logs

java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.data.DateTimeCustomValueHandler.getValueFromObject(DateTimeCustomValueHandler.java:57)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.getValueFromObject(JDBCDateTimeValueHandler.java:60)
	at org.jkiss.dbeaver.ext.oracle.data.OracleTimestampValueHandler.getValueFromObject(OracleTimestampValueHandler.java:64)
	at org.jkiss.dbeaver.ui.data.editors.DateTimeStandaloneEditor.extractEditorValue(DateTimeStandaloneEditor.java:99)
	at org.jkiss.dbeaver.ui.data.dialogs.ValueViewDialog.okPressed(ValueViewDialog.java:319)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:469)
	at org.jkiss.dbeaver.ui.data.dialogs.ValueViewDialog.buttonPressed(ValueViewDialog.java:341)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at org.jkiss.dbeaver.ui.data.dialogs.ValueViewDialog.open(ValueViewDialog.java:304)
	at org.jkiss.dbeaver.ui.data.dialogs.ValueViewDialog.showValueEditor(ValueViewDialog.java:188)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$4.runInUIThread(SpreadsheetPresentation.java:946)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:98)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4586)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

eclipse.buildId=unknown
java.version=1.8.0_201
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

**Comment by serge-rider** [comment] 2019-02-05 19:57
I can't reproduce this.
Could you re-check it in the latest version (5.3.4)?

**Comment by serge-rider** [comment] 2019-02-11 14:44
Thanks for details. This bug will be fixed in the next version.

**Comment by serge-rider** [comment] 2019-02-11 14:48
Workaround: use context menu->Edit->Set to default (or <kbd>CTRL+Insert</kbd>) instead of value editor dialog.

**Closed** 2019-02-13 14:00 UTC
Labels: bug, ready for qa
