### ISSUE TITLE
Just curious about why this software has 5 fps GUI

### ISSUE THREAD

**Issue by andrew-medvedev** [dbeaver/dbeaver#12277] opened 2021-04-28 14:47 UTC
Hello. I'm using mac book air m1 and dbeaver ver. 7.3.5. And I just curious what kind of technologies or frameworks you use to reach this "significant" performance?

https://user-images.githubusercontent.com/7358595/116423330-06d3d100-a85a-11eb-801a-3bbe15bcea59.mp4

I understand that right now we have a long of technologies that should go in a trash can right now but for God sake.
(And no, I don't have any super-heavy-loaded processes in background.)

Does anybody working with dbeaver on regular basis and having same question?

Thanks

**Comment by p91paul** [comment] 2021-04-28 23:03
duplicate of https://github.com/dbeaver/dbeaver/issues/7777

**Closed as completed** 2021-04-29 06:37 UTC
Labels: duplicate, xo:macos
