### ISSUE TITLE
SQL formatting rules

### ISSUE THREAD

**Issue by RainySecret** [dbeaver/dbeaver#19595] opened 2023-04-04 03:53 UTC
It is hoped that SQL formatting rules can integrate formatting rules from PL/SQL developer tools, or support custom modification of SQL formatting methods.
Thank you!

**Comment by E1izabeth** [comment] 2023-04-04 06:09
Could you clarify, which exact formatting rules do you want? DBeaver has a preference with formatting customization, have you seen it?

**Comment by E1izabeth** [comment] 2023-04-04 06:49
Is it duplicate of #9928?

**Comment by E1izabeth** [comment] 2023-04-04 06:52
Also we have other issues with similar request #16678 #6072

**Comment by RainySecret** [comment] 2023-04-13 10:21
I know that. But I don't know how to use external format command.

**Comment by E1izabeth** [comment] 2023-04-13 10:37
Your issue is not clear. Please, add more details, otherwise it will be closed.

If you want to know more about external formatters, I can give you a link to this one, for example, https://www.sqlinform.com/free-dbeaver-sql-formatter/.

**Comment by E1izabeth** [comment] 2023-05-08 17:32
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.

**Closed as not planned by E1izabeth** 2023-05-08 17:32 UTC
Labels: xf:sql, wait for response
