### ISSUE TITLE
NullPointerException with empty table and presentation set to text and record

### ISSUE THREAD

**Issue by plessmann** [dbeaver/dbeaver#3343] opened 2018-04-16 20:04 UTC
Bug Report

I have an empty table in mysql stored and if I try to open the table data in the text mode instead of the grid mode and in the record representation (important is the combination of text + record presentation!) for the data in this table, an NullPointerException error is raised.

Sure I know it does not make sense to display empty tables but I don't know all tables and its content in advance. Its not user friendly if I need to switch all the time back to grid mode just to prevent this error. 

I use dbeaver v5.0.0 at Linux (fedora 27) with jdk8.
The "<< Details" button does not show any further additional info.

I hope its enough for you to reproduce.

![nullpointerexeption](https://user-images.githubusercontent.com/1119088/38831602-31c75cd2-41c0-11e8-9d14-498388b8fec0.png)

**Comment by serge-rider** [comment] 2018-04-16 20:17
Duplicate of #3211

**Closed by serge-rider** 2018-04-16 20:17 UTC
Labels: bug, duplicate
