### ISSUE TITLE
Garbled Characters in DBeaver Database Connection

### ISSUE THREAD

**Issue by Iuleoo** [dbeaver/dbeaver#22242] opened 2023-12-23 11:36 UTC
### Description

The database type names and navigation bar titles in DBeaver are displayed as garbled characters when creating a database connection

### DBeaver Version

Community Edition 23.3.0

### Operating System

Windows 11 23H2

### Steps to reproduce

I tried uninstalling and reinstalling DBeaver, but the issue persists. I didn't encounter this problem with previous installations of DBeaver. Adding the '-Dfile.encoding=UTF-8' parameter to the exe startup didn't solve the issue either. However, the top menu and settings are displayed correctly.

### Additional context

<img width="840" alt="Snipaste_2023-12-23_19-28-03" src="https://github.com/dbeaver/dbeaver/assets/79144535/2c5e6536-252c-4564-bd81-42b5acee4d52">

_No response_

**Comment by E1izabeth** [comment] 2023-12-26 20:25
Could you try changing the Main font in preferences?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/47415600-8f53-45d1-9b47-5d787366d55f)

**Comment by Iuleoo** [comment] 2023-12-27 10:41
> Could you try changing the Main font in preferences?  ![图像](https://private-user-images.githubusercontent.com/28875055/292917110-47415600-8f53-45d1-9b47-5d787366d55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzM0NTksIm5iZiI6MTcwMzY3MzE1OSwicGF0aCI6Ii8yODg3NTA1NS8yOTI5MTcxMTAtNDc0MTU2MDAtOGY1My00NWQxLTliNDctNWQ3ODczNjZkNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEwMzIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNjcwZjk2MGU3MWJhMjY3MjBhNWFhZjI2ZWQ5MTQzMTE0ZTNmZmFkNjFmYTQzMzI0ZWEyZmE5MjUwOGZhMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GBIq7sfOVKgK78aebuKCmhQACuSC2HscmfkR-Tg_93M)

This is an effective method. After I change the font in the preferences, the font in the UI main interface no longer displays as garbled characters. However, the "New Database Connection" still displays as garbled characters. Can it be modified?
![image](https://github.com/dbeaver/dbeaver/assets/79144535/fe42308f-31b5-4fd9-8d32-84123556a106)

**Comment by E1izabeth** [comment] 2023-12-27 10:43
Unfortunately, I don't know workaround to fix this.

**Comment by E1izabeth** [comment] 2024-01-06 18:05
I'm closing it as a duplicate of #9455

**Closed as not planned by E1izabeth** 2024-01-06 18:05 UTC
Labels: duplicate, xf:ui
