### ISSUE TITLE
Office Integration not working in the new update release

### ISSUE THREAD

**Issue by Yoan222** [dbeaver/dbeaver#36386] opened 2024-11-27 11:01 UTC
### Description

Hi the support team.

I've installed the newest release of DBeaver.  (Version 24.2.5.202411171748).
After the installation, as usual,  the office integrattion addon has been removed and I reinstalled it.
So now it's reinstallaed with the version as below.
![image](https://github.com/user-attachments/assets/d9860517-554a-4e30-86d4-a60c705460e9)

The thing is when I try to extract the result, I get an error message.
![image](https://github.com/user-attachments/assets/193b2189-d384-41b3-8db8-2569ebb711aa)

Would you have any clue how to solve this please ?

Best regards.

### DBeaver Version

24.2.5.202411171748

### Operating System

Server Wallix - 

### Database and driver

DataBase : SQLServer 
Driver : MS SQL Server / SQL Server 12.8.0
![image](https://github.com/user-attachments/assets/d5ba5e8e-4266-486c-921b-0d3776c757d7)

### Steps to reproduce

1. Run a simple SQL statement
2. Extract the result clicking on the button Excel and get the error message.
![image](https://github.com/user-attachments/assets/6485a0a6-166c-4cea-a32b-da1bd5d650cd)
![image](https://github.com/user-attachments/assets/f9a0bd18-5742-40bd-8b29-3065b42e8f2c)

**Comment by ShadelessFox** [comment] 2024-11-27 11:43
Hello @Yoan222,

Can you please provide log files? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Yoan222** [comment] 2024-11-27 13:23
Hello @ShadelessFox,

Please find attached the 2 log files.
[dbeaver-debug.log](https://github.com/user-attachments/files/17934848/dbeaver-debug.log)
[20241127.log](https://github.com/user-attachments/files/17934898/20241127.log)

Thank you for your prompt reply.

**Comment by ShadelessFox** [comment] 2024-11-27 13:25
Are you sure it worked against the same query before? It seems like that issue was always present.

**Comment by ShadelessFox** [comment] 2024-11-27 13:39
This has been fixed in #36290

**Comment by ShadelessFox** [comment] 2024-11-27 13:41
The fix will be available on Monday.

**Comment by Yoan222** [comment] 2024-11-27 14:06
Hi, 
Yes I'm sure it worked before with the script. And I encountered the issue with another script. (My colleagues as well).
OK let's wait monday then.

Thank you very much.

**Comment by E1izabeth** [comment] 2024-12-20 12:59
I suppose the issue is solved

**Closed as not planned by E1izabeth** 2024-12-20 12:59 UTC
Labels: xf:data, wait for response
