### ISSUE TITLE
Datsources mixed

### ISSUE THREAD

**Issue by guiwebdev** [dbeaver/dbeaver#17357] opened 2022-08-16 09:02 UTC
### Description

After latest upgrade, all my scripts are shown on F3, despite the connection I'm working on.
(the option to show scripts from all connections is not enabled), but if I do enable it, it only changes the icons of the scripts to their correct connection

More, if I right click on a result and choose the "Generate", all the options add the schema to the script which is not the connection nor the schema I'm using.

### DBeaver Version

22.1.4.202208051447

### Operating System

Windows 11

**Comment by uslss** [comment] 2022-08-16 09:14
thanks for the report
The issue is already fixed in #17316 
The fix will be available in 22.1.5

**Closed as completed by uslss** 2022-08-16 09:14 UTC
Labels: duplicate
