### ISSUE TITLE
Multi line comment not shown as comment

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#11364] opened 2021-02-16 12:05 UTC
#### System information: 
- Operating system (distribution) and version:  Mac 11.2.1
- DBeaver version: 7.3.5

#### Connection specification:
- Database name and version: postgres 12.5 on RDS, but not relevant
- Driver name: default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? not relevant

#### Describe the problem you're observing:
multi line comment not shown as comment

#### Steps to reproduce, if exist:
write this multi line comment
```
/* this IS a 
 *
 multi line comm */
```
looks OK:
![image](https://user-images.githubusercontent.com/18515297/108060680-ddc7e080-705f-11eb-8827-0a08c0147ba8.png)

now delete the * on the middle line
![image](https://user-images.githubusercontent.com/18515297/108060701-e9b3a280-705f-11eb-8e38-dfd5e5c2bdb0.png)

**Comment by uslss** [comment] 2021-02-16 16:15
thanks for the report

**Comment by jetzerb** [comment] 2021-02-26 15:41
I wonder if this is related to another of DBeaver's unexpected behaviors:

![image](https://user-images.githubusercontent.com/36859020/109320199-617a8d80-7815-11eb-8298-30ab969b6b46.png)
![image](https://user-images.githubusercontent.com/36859020/109320447-a4d4fc00-7815-11eb-9269-1dbae08b5d86.png)
![image](https://user-images.githubusercontent.com/36859020/109320648-d8b02180-7815-11eb-807a-276bb3b418cb.png)
![image](https://user-images.githubusercontent.com/36859020/109320814-12812800-7816-11eb-852a-6d1e4e7d1eb1.png)
![image](https://user-images.githubusercontent.com/36859020/109320846-1ca32680-7816-11eb-82ea-53f66559ffc1.png)

SSMS and Azure Data Studio both treat the remainder of the script after an open single or double quote as a string or object name, whereas DBeaver treats such text as if there were no opening quote, until such time as the closing quote is added.

Multi-line comments, string literals, and object names are all variations of quoted strings, so I would think that all of these instances may/could be parsed using a common bit of code.

**Comment by p91paul** [comment] 2021-02-27 08:04
@jetzerb I'd say it's 2 different issues: the OP one is most likely caused by the fact that empty line is by default a statement separator, so dbeaver is unable to match the opening and closing because it thinks they are on 2 different statements.

Yours would cause the first line to be properly shown, but not the third, as it applies independently from the presence of an empty line. I suggest you open a new issue.

**Comment by ShadelessFox** [comment] 2021-03-17 13:47
This is a result of #5990, whoops 😅

**Comment by ShadelessFox** [comment] 2021-03-17 14:23
Hello @jetzerb,

The problem with string literals is that, in fact, they can span across multiple lines, so if there's no closing quote, the entire document will turn into string, just like with the comments. I'm not sure if this is a nice solution ...

If you have any better solution, please share it with me :)

**Comment by jetzerb** [comment] 2021-03-17 19:28
@ShadelessFox That _is_ in fact what happens in other editors.  It can be helpful--when a large chunk of the script looks like a string, you know you've forgotten the closing quotation mark.

I think the formatting on that second select statement here
![image](https://user-images.githubusercontent.com/36859020/111526265-85523480-872c-11eb-8cf3-dc25a077412e.png)

is less informative than here:
![image](https://user-images.githubusercontent.com/36859020/111526400-b2064c00-872c-11eb-910d-571304d2e49a.png)

**Comment by ShadelessFox** [comment] 2021-03-17 19:55
I see. Can you please create a separate feature request for this?

**Comment by uslss** [comment] 2021-03-18 08:29
verified

**Closed as completed by uslss** 2021-03-18 08:29 UTC
Labels: x:postgresql, x:mssql, xf:sql
