### ISSUE TITLE
Ctrl+Enter no longer opening "Recent SQL Editor"

### ISSUE THREAD

**Issue by rodelrod** [dbeaver/dbeaver#11049] opened 2021-01-19 17:09 UTC
#### System information: 
- Linux Pop!_OS 20.04
- DBeaver Version 7.3.3.202101161839
- Additional extensions: Vrapper (although the same issue happens with Vrapper disabled)

#### Describe the problem you're observing:

Since my upgrade from 7.2.2 to 7.3.3, pressing Ctrl+Enter from the Database Navigator when a database or table is selected no longer opens the corresponding "Recent SQL Editor".

#### Steps to reproduce, if exist:
1. Highlight a table in Database Navigator using mouse or keyboard
2. Press Control+Enter (using the Enter/Return key from a 104/105 keys ANSI/ISO keyboard)

What is expected: The last  used SQL Editor for the corresponding connection is opened, or the respective tab is selected if it was already open
What happens: The Properties/Data/ER Diagram for the highlighted object opens instead.

#### Things that I've tried 
1. Disabling Vrapper extension: same problem
2. Unbinding and rebinding the key: same problem
3. Resetting the workspace by deleting `workbench.xmi`: same problem
4. Pressing Control+Numpad Enter: opens the recent SQL Editor as expected (unfortunately this does not help me in a laptop)
5. Rebinding "Recent SQL Editor" to Shift+Enter: same problem (works only with Numpad Enter)
6. Rebinding "Recent SQL Editor" to Ctrl+o: works (it's my current workaround)

#### Include any warning/errors/backtraces from the logs
Nothing shows in the logs

**Comment by kseniiaguzeeva** [comment] 2021-01-25 07:59
I cannot reproduce it on Windows. It can be a specific Linux problem.

**Comment by uslss** [comment] 2021-01-25 11:48
reproducible against ubuntu 20.0.4.1

**Comment by flambchap** [comment] 2021-06-21 12:51
Hi @rodelrod. It seems like this problem was resolved in one of the previous releases. I'm closing this ticket. If you still can reproduce the problem on the latest DBeaver release, please feel free to reopen the ticket.

**Closed as completed by flambchap** 2021-06-21 12:51 UTC
Labels: xo:linux, sp:3
