### ISSUE TITLE
Oracle temporary tables DDL

### ISSUE THREAD

**Issue by danieleangellotti** [dbeaver/dbeaver#2576] opened 2017-11-27 14:55 UTC
Hi Serge,
I noticed that in Oracle temporary tables description the generated DDL is incorrect: it's generated as if it were a regular table (`CREATE TABLE SCHEMA.TABLE_NAME...` and not `CREATE TEMPORARY TABLE...`).

Thanks.

**Comment by serge-rider** [comment] 2017-11-29 21:11
I can't reproduce that.
![image](https://user-images.githubusercontent.com/6398845/33399256-fc21d14e-d562-11e7-81b5-c79085dcaff5.png)

What Oracle driver do you use? Is table actually marked as temporary in object properties?

**Comment by danieleangellotti** [comment] 2017-11-30 14:32
Hi Serge,
I see from your screenshot that in fact the issue seems not existing in your environment, but I can replicate it.
I'm using DBeaver 4.2.6 64 bit stand-alone running on a Windows 7 64 bit system, with an Oracle 11.2.0.1.0 connection.
For completeness I attached a couple of screenshots.

![screenshot01](https://user-images.githubusercontent.com/32410707/33435821-7c59ced6-d5e3-11e7-9949-e831c8f4d5c0.png)

![screenshot02](https://user-images.githubusercontent.com/32410707/33435832-82f1caa0-d5e3-11e7-81a5-08781165c12b.png)

Thanks.

**Comment by serge-rider** [comment] 2017-11-30 21:47
Looks like something went wrong during Oracle DDL generation and DBeaver created DDL by itself on client-side.

Please check Error Log view or error log file (https://github.com/serge-rider/dbeaver/wiki/Log-files). There should be some warnings/errors when you open a table.

**Comment by danieleangellotti** [comment] 2017-12-16 10:25
Hi Serge,
thanks for the tip! I think that the issue can be related to the _ORA-31608: specified object of type COMMENT not found_ message found in _.log_ file, that's the same that is returned by executing `SELECT DBMS_METADATA.GET_DEPENDENT_DDL('COMMENT', 'SCOTT.GL_TMP_TABLE_EXAMPLE') FROM DUAL`.

Thanks for your attention.

**Comment by danieleangellotti** [comment] 2017-12-28 10:32
Hi Serge,
I saw that in the 4.3.1 version the issue no longer occurs: maybe it was just a case of a more general bug in table DDL generation that has been solved in the last release.

Thank you!

**Comment by serge-rider** [comment] 2018-01-03 18:24
@danieleangellotti Actually it was fixed in 4.3.1 (errors in GET_DEPENDENT_DDL are now handled as non-fatal).

**Closed** 2018-01-03 18:25 UTC
Labels: can't reproduce, question
