### ISSUE TITLE
 Add more space between line number and the text of a log-file in sql editor

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35504] opened 2024-09-06 19:06 UTC
### Description

This is very similar to this one #34814 but due to different location, I opened the separate bug report.
But maybe it is easier to fix it at once.
This log file can be opened on double click to the executed task in right bottom panel on the video.

*Please also check this for other file extensions, not only *.log

https://github.com/user-attachments/assets/8246ef1c-0483-42f4-968a-b74018d6e112

### DBeaver Version

Community Edition 24.1.5-202408122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by ShadelessFox** [comment] 2024-09-08 12:52
Thanks for the bug report.

The same control is used for displaying text, so I'm closing this ticket as a duplicate of #34814.

**Closed as not planned by ShadelessFox** 2024-09-08 12:52 UTC
Labels: enhancement, duplicate, xf:ui
