### ISSUE TITLE
The connection timed out

### ISSUE THREAD

**Issue by krsbalu** [dbeaver/dbeaver#4186] opened 2018-09-11 05:09 UTC

**Comment by krsbalu** [comment] 2018-09-11 05:10
Hi , I am facing an error as "connection timed out" while i am trying to connect for Oracle DB's from my office VPN network , whereas i am able to access using other utilities like dbvis, sql-workbench and sql developer as well.

But i am able to connect using Dbeaver only on our office normal network.

Can anyone let me know what kind of issues exits in tool and any settings has to be enabled.
I am waiting for solution.

**Comment by serge-rider** [comment] 2018-09-11 15:17
Normally there shouldn't be any issue. Most likely you have incorrect network configuration.
- Do you use the same Oracle driver for all these tools?
- Do you use SSH or proxy?
- Do you use TNS connection configuration or direct host/port config?

**Comment by krsbalu** [comment] 2018-09-12 05:08
Yes i use same driver.
No ssh/Proxy
Using direct host / port config

**Comment by serge-rider** [comment] 2018-09-12 20:11
Then I have no clues so far. Maybe you have some specific corporate network policies. Or even limitations on Oracle level.
I know that some companies limit database connections based on client name, e.g. only for TOAD. If so then this can be resolved by changing Application Name if in "Client Identification" settings. But its better to consult with DBA first.

**Comment by wloske** [comment] 2018-09-13 16:00
I have a similar issue. Interestingly the issue appeared with the install of the new 5.2.0 after return from vacation. Before - I don't recall the specific version - everything worked fine. After returning I thought "Oh, update? Do it!" and did it. And now I am stuck with immediate "connection timeout", it's not even trying. I can't say if it really has to with 5.2.0, might only be coincidence.

I am on a Mac and I use unixodbc/PHP@7.1 successfully as well as another JDBC based tool (PhpStorm) to connect to the DB. It's an exasol DB and the admin has not changed anything in the meantime or restricts by client name.

I also tried rolling back several version of DBeaver to no no avail. This is really killing me, I run out of ideas ;-/

**Comment by serge-rider** [comment] 2018-09-18 09:51
Seems to be the same issue: #4229
Try to configure connection timeouts (it is 20 seconds by default)

**Comment by wloske** [comment] 2018-09-19 07:29
Hi Serge, this does not seem to help in #4229 either. As far as I recall - will check later - the timeout is already set. Also, I am not using a proxy, the timeout hits immediately and other clients connect hassle free ...

It just worked with DBeaver out of the box, too, before installing 5.2.0 ... strange thing.

**Comment by wloske** [comment] 2018-09-19 11:49
Thanks for getting back,

Really sorry and my bad to not have mentioned this:  my error is related to exasol. 

I hit the timeout error right away within a second of trying.

**Comment by serge-rider** [comment] 2018-09-21 19:17
Although this may be caused by actual database connection timeout in some cases it fails without any real reason (I've reproduced this on Mac when DBeaver initiates a connection during startup).
After all I think we should disable client-side connection timeout by default.

**Comment by serge-rider** [comment] 2018-09-21 19:18
@krsbalu Please check this issue in 5.2.1
I'll reopen this ticket if it still be reproducible

**Closed by serge-rider** 2018-09-21 19:18 UTC
Labels: enhancement, question

**Comment by krsbalu** [comment] 2018-09-25 08:17
Hello, Thanks, its work well in 5.2.1 version.. its helps a lot.

**Comment by rirjkl19** [comment] 2020-03-02 21:48
Hi! I'm gonna apologize in advance cause I'm new and newbie here. I'm having trouble connecting to our office database in dbeaver in mac, I'm having timeout error or having problems with drivers (I think). I am able to connect in dbeaver in windows using our credentials but in mac I'm having difficulty. Please help.

**Comment by josh231101** [comment] 2021-04-16 17:21
Same problem here, running on Pop Os,(sort of Ubuntu)

**Comment by jaypn** [comment] 2021-08-28 18:05
Hello guys I recently changed my IP address from google cloud am trying to connect my database but am getting this same error that connect timed out can anyone help me out please?

**Comment by josh231101** [comment] 2021-08-28 19:49
> Hello guys I recently changed my IP address from google cloud am trying to connect my database but am getting this same error that connect timed out can anyone help me out please?

You have to update your DB to accept querys from your new IP, probably is mounted on AWS or something your db

**Comment by jaypn** [comment] 2021-09-01 20:01
Hello guys, thanks for your previous suggestion, I worked but now the issue I have is to recover my databases data, it looks like a brand new databases without any databases that I created before

**Comment by MoodConnect** [comment] 2022-02-10 03:25
I'm actually having trouble with connecting dbeaver. I'm getting a connection time out error when accessing with dbeaver lite. Anyone have any thoughts on how to fix that issue?

**Comment by muhammadh01** [comment] 2023-08-18 05:09
Hi guys, I literally have same issue in Dbeaver ERROR "Read timed out" .
I run a docker container for handle ssl and https and run postgresql on another one.
I installed letsencrypt certificate on my postgres domain in https container and with using reverse proxy I've point it to postgres container on port "5432", in postgresql.conf I've turn on ssl, anyway I've try a lot off things for use ssl on my postgres for secure connection but I didn't recive any result, if you know how to do it please give a guide.

**Comment by dev-peakmind** [comment] 2023-09-26 17:12
I'm facing the same issue and have tried setting literally every  timeout to around 50,000 ms but still it doesn't wait for 50,000 ms to say "Read Timed Out". Would really appreciate some help.

1. The DB is  fine as I am able to connect to it through AWS Lambda functions and other DB clients
2. My Laptop config and firewall is fine and there's no IP blocking as well since I am able to connect to the database using PgAdmin
