### ISSUE TITLE
Format SQL

### ISSUE THREAD

**Issue by yaoguoba** [dbeaver/dbeaver#3579] opened 2018-06-06 03:41 UTC
>settings
1.insert space for tab.
2.tab size is '4'

>issues
1.It will inserts 3 spaces in new line start when I click Enter key.
2.Inserts 1 space in SQL start from the secend SQL when format SQLs.

**Comment by serge-rider** [comment] 2018-06-16 22:04
Can't reproduce. 
Please post example of SQL query where this is reproducible.

**Comment by yaoguoba** [comment] 2018-06-18 02:08
![image](https://user-images.githubusercontent.com/18393410/41515152-46100a40-72df-11e8-82f8-90fde987d0a5.png)

**Comment by serge-rider** [comment] 2018-06-19 19:37
Thanks, now I can reproduce it.
SQL indentation will be fixed in the next version.

**Closed by serge-rider** 2018-06-19 19:37 UTC
Labels: bug
