### ISSUE TITLE
Version 24.0.1 - ERROR WHILE READING SOURCE: SQL Error [208] [42000]

### ISSUE THREAD

**Issue by rojasadrianza** [dbeaver/dbeaver#23247] opened 2024-03-26 21:39 UTC
### Description

Hello, yesterday when install the 24.0.1 version i hav this error:

/* ERROR WHILE READING SOURCE: SQL Error [208] [42000]: SYS.SYSPROCEDURE not found. Specify owner.objectname or use sp_help to check whether the object exists (sp_help may produce lots of output). */

I had that install the 24.0,0 version again for resolve the error

### DBeaver Version

24.0.1

### Operating System

windows 10 64

### Database and driver

sybase

### Steps to reproduce

whan open store procedure

### Additional context

VPN private

**Comment by LonwoLonwo** [comment] 2024-03-27 18:11
Hello @rojasadrianza 

Please specify your server version.
You can check it in your connections settings -> test connection

**Comment by rpallamo** [comment] 2024-03-28 13:43
Hello. I'm using Sybase ASE and I have the same behaviour. Here's the server version:

Adaptive Server Enterprise 16.0.04.03

In previous DBEAVER version I was able to access any source from any procedure.

**Comment by LonwoLonwo** [comment] 2024-03-29 08:42
Does this query work for you?

`select * from sys.SYSSOURCE`

@rpallamo @rojasadrianza

**Comment by PippoSkaio** [comment] 2024-03-29 09:44
> Does this query work for you?
> 
> `select * from sys.SYSSOURCE`
> 
> @rpallamo @rojasadrianza

That works only on Sybase/SAP IQ family of products (Adaptive Server Anywhere aka ASA, IQ, etc.). On Adaptive Server Enterprise aka ASE the query for source code is the same as with Microsoft SQL Server (the two forked in the 1990s):

select sc.text
from dbo.sysobjects so
join dbo.syscomments sc on sc.id = so.id
where user_name(so.uid)=:ownerName and so.name=:procName
order by sc.colid

Previous versions of SQLServerMetaModel.java code had it right using"isSapIQ" function (which unfortunately doesn't recognize Anywhere products as part of SAP IQ product family)

**Comment by chillymosh** [comment] 2024-04-12 07:50
I also encountered this issue and reverted back to 24.0.0 for now

**Comment by LonwoLonwo** [comment] 2024-04-12 12:16
Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/23259

**Closed as completed by LonwoLonwo** 2024-04-12 12:16 UTC
Labels: duplicate, x:sybase, xf:metadata

**Comment by serjiokov** [comment] 2024-04-24 09:10
HI @PippoSkaio, 
Could you please check and respond 
Does this query work fine on Sysbase ASE server?
`SELECT * from SYS.SYSPROCEDURE`

**Comment by rpallamo** [comment] 2024-04-24 09:15
You can see the answer to your question in this link:

https://github.com/dbeaver/dbeaver/issues/23247#issuecomment-2026958812

Basically, SYS.SYSPROCEDURE is only available for SYBASE IQ products, not ASE products.

Regards.

**Comment by PippoSkaio** [comment] 2024-04-24 09:50
> HI @PippoSkaio, Could you please check and respond Does this query work fine on Sysbase ASE server? `SELECT * from SYS.SYSPROCEDURE`

Nope, not working on ASE

I tested it anyway in DBeaver and DON'T work on:
- Adaptive Server Enterprise/12.5.3/EBF 13331
- Adaptive Server Enterprise/15.7.0/EBF 20953
- Adaptive Server Enterprise/16.0 SP03 PL08/EBF 28923

It works on:
- Adaptive Server Anywhere 16.0.0.1915
- Adaptive Server Anywhere 9.0.2 EBF 3951
- IQ versions?

Connections to ASE are with Sybase jTDS protocol (net.sourceforge.jtds.jdbc.Driver)
ASA/IQ connections are with SAP jConnect (com.sybase.jdbc4.jdbc.SybDriver)
