### ISSUE TITLE
A little suggestion about shortcut key ctrl+right/left at SQL edit window

### ISSUE THREAD

**Issue by hezemail** [dbeaver/dbeaver#4042] opened 2018-08-21 09:32 UTC
Hi,
     As we know, a underline symbol is always used in a DB object name. For example, a table may have a name as 't_test_table'. So when we write sql in SQL edit window, we treat this name as a full word. But when I use the shortcut key 'CTRL + right' at the end of the table name, the cursor move to the last underline symbol, but I want it to move to the first letter of the table name. So, can this be optimized ? I think that will be more convinient when use shortcut key if we don't use '_' as a word delimiter! Thanks!

**Comment by serge-rider** [comment] 2018-08-29 14:27
Looks like duplicate of #1155.

**Closed by serge-rider** 2018-08-29 14:27 UTC
Labels: enhancement
