### ISSUE TITLE
Postgres: cannot add a value with type array of enum using window Value

### ISSUE THREAD

**Issue by kaihanga** [dbeaver/dbeaver#5273] opened 2019-02-13 09:06 UTC
#### System information: 
- Operating system (distribution) and version: ArchLinux(x64) with the latest updates
- DBeaver version: 5.3.4.201902031804
- Java version: 11.0.2 2018-10-16 (build 11.0.2+7)
- Additional extensions: None

#### Connection specification:
- Database name and version: postgresql 11.1-3
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No, direct LAN connection over TCP (without SSL)

#### Describe the problem you're observing:
I get an error when I try to add values ​​for a column with type "array of enum" when using the "value" window.

#### Steps to reproduce:
Create any enum type: 
```
CREATE TYPE MyEnum AS ENUM ('first', 'second', 'third');
```

Add  a column with a type an array of enum
```
CREATE TABLE test (
	target MyEnum array, --or MyEnum[], no difference.
	for_test_enum MyEnum,
	for_test_array int array,
);
```
A hand-written SQL query appends data into table correctly.
When we try to add data to the table by grid, we can create array elements in the "value" window, but we cannot select values ​​from the enumerator for them. So that we cannot fill the "target" column.
For columns "for_test_enum" and "for_test_array" window "value" works correctly.
When I create an array element for column "target", the following error occurs:

#### Include any warning/errors/backtraces from the logs:
```
eclipse.buildId=unknown
java.version=11.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Feb 13 10:09:48 EET 2019
class org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType cannot be cast to class org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute (org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType and org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @18a35df8)

java.lang.ClassCastException: class org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType cannot be cast to class org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute (org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType and org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @18a35df8)
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreEnumValueManager.getEnumValues(PostgreEnumValueManager.java:39)
	at org.jkiss.dbeaver.ui.data.managers.EnumValueManager$EnumInlineEditor.createControl(EnumValueManager.java:109)
	at org.jkiss.dbeaver.ui.data.managers.EnumValueManager$EnumInlineEditor.createControl(EnumValueManager.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:58)
	at org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor.showEditor(ComplexObjectEditor.java:303)
	at org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor.access$12(ComplexObjectEditor.java:289)
	at org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor$AddElementAction.run(ComplexObjectEditor.java:724)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:439)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

Thank you in advance

**Comment by serge-rider** [comment] 2019-02-14 22:35
Duplicate of #5224
You can check the fix in Early Access version (https://dbeaver.io/files/ea)

**Closed by serge-rider** 2019-02-14 22:35 UTC
Labels: bug, duplicate
