### ISSUE TITLE
Auto-commit connection setting no longer saved

### ISSUE THREAD

**Issue by Condor70** [dbeaver/dbeaver#6511] opened 2019-08-13 11:32 UTC
I think this started in DBeaver 6.1.2 or 6.1.3 and is still present in 6.1.4:

The Auto-commit setting under Connection settings -> Initialization isn't saved anymore when exiting the application.

Side note: Why is Isolation level grayed out when enabling Auto-commit? The isolation level is also relevant for select-queries, so it should be configurable independent from the Auto-commit setting.

**Comment by serge-rider** [comment] 2019-08-13 12:01
I believe it was fixed in 6.1.4, can't reproduce this now. We released a 6.1.4 hotfix version just one day  later official release (mostly because of this problem). Could you try to check this on the current 6.1.4 version on https://dbeaver.io/download?

In regards to isolation levels - they are enabled only if connection is established or after you click "Test connection".

**Comment by Condor70** [comment] 2019-08-13 12:07
I'm running 6.1.4.201908041900. Is this the latest version or is there a newer version?

**Comment by serge-rider** [comment] 2019-08-13 12:12
It is the latest version. And it is doesn't load propr auto-comit option indeed. Maybe it was fixed in the Early Access only  (https://dbeaver.io/files/ea).
Thanks for the bug report anyway.

**Comment by Condor70** [comment] 2019-08-13 12:24
Thanks, the 6.1.5 early access fixes the problem.

**Comment by kseniiaguzeeva** [comment] 2019-08-14 14:02
Verified

**Closed by kseniiaguzeeva** 2019-08-14 14:02 UTC
Labels: bug
