### ISSUE TITLE
Keyword Auto-Captialization No Longer Working

### ISSUE THREAD

**Issue by GiraldoP** [dbeaver/dbeaver#18216] opened 2022-11-14 21:20 UTC
### Description

I recently updated to 22.2.4 and found that the auto-capitalization of keywords (FROM, SELECT, etc.) has been removed after pressing the space bar. I attempted to resolve the issue, to no avail, by adjusting the global formatting under the Preferences via the following steps: Window > Preferences > Editors > SQL Editor > Formatting > Keyword case: Upper > Apply and Close.

### DBeaver Version

Community Edition 22.2.4

### Operating System

Windows 10

**Comment by E1izabeth** [comment] 2022-11-14 21:28
Thank you for bug report.
It's a duplicate of #18131

**Closed as not planned by E1izabeth** 2022-11-14 21:28 UTC
Labels: duplicate
