### ISSUE TITLE
Auto start DBeaver after install

### ISSUE THREAD

**Issue by vierlijner** [dbeaver/dbeaver#19605] opened 2023-04-05 06:47 UTC
Please make it possible that after the installation wizard on the latest page i can checkmark a new option that I want to start(up) DBeaver when I click on Finish.
![image](https://user-images.githubusercontent.com/68417202/230000289-a9e21355-2b5a-42a8-bb82-8e1d49902435.png)

This is handy because mostly when DBeaver is running I get a reminder that there is a new version of DBeaver and if I want to install it. When Yes, it's shutdown DBeaver and download and install it automatic and I follow the wizard and finish, but then I have to start DBeaver again manualy.

Thanks in advance.

**Comment by E1izabeth** [comment] 2023-04-05 07:29
Thank you for idea. It's a duplicate of This issue looks like a duplicate of #17878

**Closed as not planned by E1izabeth** 2023-04-05 07:29 UTC
Labels: duplicate, xf:installation
