### ISSUE TITLE
Active Schema in a new SQL Editor isn't actually part of SEARCH_PATH

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#9185] opened 2020-07-07 12:49 UTC
#### System information: 
- Operating system (distribution) and version: Windows Server 2016 Datacenter 64-bit
- DBeaver version: 7.1.2.202007051953
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11 on Aurora RDS
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
custom selected schema from connection is showing at top of SQL editor but not actually part of search_path

#### Steps to reproduce, if exist:
1. set a custom schema (other than "public") in connection setting
2. open the connection
3. open a new SQL editor
4. run SQL: show search_path 
(you could see it is actually: "$user", public" instead of "$user", [custom_schema], public)

#### Workaround:
reselect schema at top of SQL Editor (Active Schema dropdown)

**Comment by kseniiaguzeeva** [comment] 2020-07-09 12:46
Thank you for the bug report.

**Comment by uslss** [comment] 2020-07-20 09:26
closed as duplicate of #9040

**Closed by uslss** 2020-07-20 09:26 UTC
Labels: bug, duplicate, x:postgresql
