### ISSUE TITLE
https://dbeaver.io/debs/dbeaver-ce/InRelease Certificate verification failed

### ISSUE THREAD

**Issue by yermulnik** [dbeaver/dbeaver#35777] opened 2024-10-02 13:07 UTC
Sectigo intermediate cert issue:
```bash
> fgrep -w VERSION /etc/os-release
VERSION="22.04.5 LTS (Jammy Jellyfish)"

> cat /etc/apt/sources.list.d/dbeaver.list
deb [signed-by=/usr/share/keyrings/dbeaver.gpg.key] https://dbeaver.io/debs/dbeaver-ce /

> apt update
[…]
W: Failed to fetch https://dbeaver.io/debs/dbeaver-ce/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 104.131.190.124 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.

> openssl.ssl_cert_check.sh -i dbeaver.io
Issuer: issuer=C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA

> wget https://dbeaver.io/debs/dbeaver-ce/InRelease
--2024-10-02 14:55:35--  https://dbeaver.io/debs/dbeaver-ce/InRelease
Resolving dbeaver.io (dbeaver.io)... 104.131.190.124
Connecting to dbeaver.io (dbeaver.io)|104.131.190.124|:443... connected.
ERROR: cannot verify dbeaver.io's certificate, issued by ‘CN=Sectigo RSA Domain Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB’:
  Unable to locally verify the issuer's authority.
To connect to dbeaver.io insecurely, use `--no-check-certificate'.
```

Resolution FWIW:
* Download `Sectigo RSA Domain Validation Secure Server CA [ Intermediate ]` from https://www.sectigo.com/knowledge-base/detail/Sectigo-Intermediate-Certificates/kA01N000000rfBO (also attached — rename from `.txt` to `.crt`
[Sectigo_RSA_Domain_Validation_Secure_Server_CA.txt](https://github.com/user-attachments/files/17229647/Sectigo_RSA_Domain_Validation_Secure_Server_CA.txt)
)
![image](https://github.com/user-attachments/assets/47498e46-fe62-4606-b300-b709fc834d6f)
* `sudo mkdir -p /usr/share/ca-certificates/extra/`
* `chmod a+r "path/to/downloaded/cert/file"`
* `sudo mv "path/to/downloaded/cert/file" /usr/share/ca-certificates/extra/Sectigo_RSA_Domain_Validation_Secure_Server_CA.crt`
* `sudo dpkg-reconfigure ca-certificates`
  * Select `Yes` on first screen
  * On next screen:
    * Enable `extra/Sectigo_RSA_Domain_Validation_Secure_Server_CA.crt`
    * (IMPORTANT) Disable `mozilla/Sectigo_Public_Server_Authentication_Root_R46.crt`
* Profit

Hope this helps others who stumble upon this issue.

**Comment by yermulnik** [comment] 2024-10-02 13:10
2maintainers: apologies for the `feature request` type of issue — I couldn't figure out which one to select to report this.

**Comment by bricemciver** [comment] 2024-10-02 13:18
> Sectigo intermediate cert issue:
> 
> ```shell
> > fgrep -w VERSION /etc/os-release
> VERSION="22.04.5 LTS (Jammy Jellyfish)"
> 
> > cat /etc/apt/sources.list.d/dbeaver.list
> deb [signed-by=/usr/share/keyrings/dbeaver.gpg.key] https://dbeaver.io/debs/dbeaver-ce /
> 
> > apt update
> […]
> W: Failed to fetch https://dbeaver.io/debs/dbeaver-ce/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 104.131.190.124 443]
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> 
> > openssl.ssl_cert_check.sh -i dbeaver.io
> Issuer: issuer=C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
> 
> > wget https://dbeaver.io/debs/dbeaver-ce/InRelease
> --2024-10-02 14:55:35--  https://dbeaver.io/debs/dbeaver-ce/InRelease
> Resolving dbeaver.io (dbeaver.io)... 104.131.190.124
> Connecting to dbeaver.io (dbeaver.io)|104.131.190.124|:443... connected.
> ERROR: cannot verify dbeaver.io's certificate, issued by ‘CN=Sectigo RSA Domain Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB’:
>   Unable to locally verify the issuer's authority.
> To connect to dbeaver.io insecurely, use `--no-check-certificate'.
> ```
> 
> Resolution FWIW:
> 
> * Download `Sectigo RSA Domain Validation Secure Server CA [ Intermediate ]` from https://www.sectigo.com/knowledge-base/detail/Sectigo-Intermediate-Certificates/kA01N000000rfBO (also attached — rename from `.txt` to `.crt`
>   [Sectigo_RSA_Domain_Validation_Secure_Server_CA.txt](https://github.com/user-attachments/files/17229647/Sectigo_RSA_Domain_Validation_Secure_Server_CA.txt)
>   )
>   ![image](https://private-user-images.githubusercontent.com/1274789/372862084-47498e46-fe62-4606-b300-b709fc834d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzUxOTUsIm5iZiI6MTcyNzg3NDg5NSwicGF0aCI6Ii8xMjc0Nzg5LzM3Mjg2MjA4NC00NzQ5OGU0Ni1mZTYyLTQ2MDYtYjMwMC1iNzA5ZmM4MzRkNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTMxNDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFiMDcwNGM2N2E0ODJhZTUyYTBiZWJiYTY0ODU5OGMzM2JmZjE0YjgxYTc3OTNjODU2YzViYTc1NzhiYjFlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4Et4tYTEkmwowl8wuI6oXcy1yYV9Od4Yh2GlnukHVzY)
> * `sudo mkdir -p /usr/share/ca-certificates/extra/`
> * `chmod a+r "path/to/downloaded/cert/file"`
> * `sudo mv "path/to/downloaded/cert/file" /usr/share/ca-certificates/extra/Sectigo_RSA_Domain_Validation_Secure_Server_CA.crt`
> * `sudo dpkg-reconfigure ca-certificates`
>   
>   * Select `Yes` on first screen
>   * On next screen:
>     
>     * Enable `extra/Sectigo_RSA_Domain_Validation_Secure_Server_CA.crt`
>     * (IMPORTANT) Disable `mozilla/Sectigo_Public_Server_Authentication_Root_R46.crt`
> * Profit
> 
> Hope this helps others who stumble upon this issue.

Real resolution is that dbeaver.io needs to serve the full certificate chain (including the intermediate certificate), right?

**Comment by yermulnik** [comment] 2024-10-02 13:37
> Real resolution is that dbeaver.io needs to serve the full certificate chain (including the intermediate certificate), right?

Unfortunately I have no idea as I'm not quite savvy in this scope 🤷🏻
It surfaced today and matches the new debeaver.io SSL cert start date (`Oct  2 00:00:00 2024 GMT`). So I attempted to bandaid broken APT on my desktop Ubuntu.

Maybe it's up to Ubuntu devs to update `ca-certificates` package 🤔 
```
> apt show ca-certificates 2>/dev/null | sed -n '/^Description:/,$p'
Description: Common CA certificates
 Contains the certificate authorities shipped with Mozilla's browser to
 allow SSL-based applications to check for the authenticity of SSL
 connections.
 .
 Please note that Debian can neither confirm nor deny whether the
 certificate authorities whose certificates are included in this package
 have in any way been audited for trustworthiness or RFC 3647 compliance.
 Full responsibility to assess them belongs to the local system
 administrator.
```

**Comment by maurom** [comment] 2024-10-02 16:58
First of all, thank you for your work on this excellent database client.

Regarding this issue, I am also affected by the certificate change. It seems the root CA for `dbeaver.io` is available in the ca-certificates package on Ubuntu/Debian[^1], but the intermediate certificate seems to be missing from the server chain  (see ["Chain issues" in this report](https://www.ssllabs.com/ssltest/analyze.html?d=dbeaver.io&hideResults=on)). This causes connection failures related to SSL verification.

Operating system: Debian GNU/Linux 12 (bookworm)
Error message when performing `apt update`:
```
W: Failed to fetch https://dbeaver.io/debs/dbeaver-ce/InRelease  Certificate verification failed:
   The certificate is NOT  trusted. The certificate issuer is unknown.
   Could not handshake: Error in the certificate verification. 
```

Typically, adding the missing intermediate certificate to the .pem file used for the server HTTPS configuration should resolve this, but I defer to those who know best on how to resolve it.

[^1]: /usr/share/ca-certificates/mozilla/USERTrust_RSA_Certification_Authority.crt

**Comment by ghost-from-the-past** [comment] 2024-10-03 07:16
copying the certificate to /usr/local/share/ca-certificates/
and doing
>sudo update-ca-certificate

also works

**Comment by jramosf** [comment] 2024-10-03 07:23
There shouldn't be any need to install intermediate CAs into truststores, this is `dbeaver.io` server which is not sending the complete chain in the TLS handshake. More details in https://github.com/dbeaver/dbeaver/issues/35794#issuecomment-2390633077

**Comment by moerkey** [comment] 2024-10-03 09:55
> There shouldn't be any need to install intermediate CAs into truststores, this is `dbeaver.io` server which is not sending the complete chain in the TLS handshake. More details in [#35794 (comment)](https://github.com/dbeaver/dbeaver/issues/35794#issuecomment-2390633077)

I can confirm this. Just visit: https://www.ssllabs.com/ssltest/analyze.html?d=dbeaver.io

For me, currently apt-get update is failing under Ubuntu.

```
Ign:8 https://dbeaver.io/debs/dbeaver-ce  InRelease
Ign:8 https://dbeaver.io/debs/dbeaver-ce  InRelease
Err:8 https://dbeaver.io/debs/dbeaver-ce  InRelease                                                                                                                  
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 104.131.190.124 443]
Fetched 129 kB in 8s (15,8 kB/s)                                                                                                                                     
Reading package lists... Done
W: Failed to fetch https://dbeaver.io/debs/dbeaver-ce/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 104.131.190.124 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Related issues: #35794 & #35796

**Comment by E1izabeth** [comment] 2024-10-03 09:58
Than you for report and workaround

**Comment by moerkey** [comment] 2024-10-03 10:01
@E1izabeth You can find the intermediate here: https://www.ssl247.com/knowledge-base/detail/sectigo-intermediate-certificates/ka03l0000015lEyAAI/

**Comment by serge-rider** [comment] 2024-10-03 10:01
Please check how it works now (it was fixed in #35796)

**Comment by moerkey** [comment] 2024-10-03 10:02
Works. Done

**Comment by E1izabeth** [comment] 2024-10-03 10:20
Thank you for checking. I'm closing the issue as solved then

**Closed as completed by E1izabeth** 2024-10-03 10:20 UTC
Labels: xp:major

**Comment by yermulnik** [comment] 2024-10-03 11:43
I also (as a topicstarter) can confirm now it's all good. Thanks.

**Comment by adaspender** [comment] 2026-05-19 16:26
I am running into this issue again. Followed the steps listed above to no avail.
What ended up fixing it was trying a solution mentioned on https://github.com/dbeaver/dbeaver/issues/36492 which I will paste below:
`sudo mkdir -p /usr/share/keyrings/
curl -s https://dbeaver.io/debs/dbeaver.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/dbeaver.gpg.key`
then
`sudo apt-get update && sudo apt-get install dbeaver-ce`
