### ISSUE TITLE
Navigation error - modal debug window preventing access to Dbeaver

### ISSUE THREAD

**Issue by taylorparsons** [dbeaver/dbeaver#21735] opened 2023-11-02 17:16 UTC
### Description

when I open dbeaver, as a UI starts to display I get the error box that I can't escape from.  

Navigation error
URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: " o"

Reason:
URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: " o"

### DBeaver Version

Community 23.2.3

### Operating System

Mac OS - 14.0

### Database and driver

Teradata
postgress sql

### Steps to reproduce

1. open dbeaver
2. error happens

**Comment by taylorparsons** [comment] 2023-11-02 17:17
<img width="1191" alt="image" src="https://github.com/dbeaver/dbeaver/assets/5473923/cbd6f999-1c9f-416e-9838-887ebf30e256">

**Comment by E1izabeth** [comment] 2023-11-02 19:45
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by taylorparsons** [comment] 2023-11-02 20:02
[dbeaver-debug-1698940165415.log](https://github.com/dbeaver/dbeaver/files/13244018/dbeaver-debug-1698940165415.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13244019/dbeaver-debug.log)

**Comment by E1izabeth** [comment] 2023-11-02 20:07
Hmm.. I don't see the mentioned error in the debug logs. Could you also provide `.log` file? (P.S. you can rename it if github doesn't allow attaching files without name)

**Comment by taylorparsons** [comment] 2023-11-02 20:17
yes here sorry missed that one 
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/13244126/dbeaver.log)

**Comment by taylorparsons** [comment] 2023-11-02 20:23
looking at the ..Library/CloudStorage/OneDrive-COMPANY/sql/.metadata/.plugins/org.eclipse.ui.workbench/log 
I see this which matches the error displayed.
[org_eclipse_ui_workbench_log.log](https://github.com/dbeaver/dbeaver/files/13244165/org_eclipse_ui_workbench_log.log)

```
ENTRY org.jkiss.dbeaver.model 4 0 2023-11-02 09:58:49.248
!MESSAGE URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: " o"
!STACK 0
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: " o"
```

**Comment by E1izabeth** [comment] 2023-11-02 20:25
Thank you

**Comment by LonwoLonwo** [comment] 2023-11-03 07:54
Hello @taylorparsons 

This is a duplicate of https://github.com/dbeaver/dbeaver/issues/21501. And it is already fixed. You can wait for the Monday release or check our Early Access version: https://dbeaver.io/files/ea/

**Comment by arhayka** [comment] 2023-12-06 16:29
Hello@taylorparsons, 
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
You can try to reproduce it on the new DBever version.

**Closed as not planned by arhayka** 2023-12-06 16:29 UTC
Labels: duplicate, wait for response
