### ISSUE TITLE
Code editor syntax highlighting bug

### ISSUE THREAD

**Issue by saikotek** [dbeaver/dbeaver#23116] opened 2024-03-13 01:16 UTC
### Description

Hello, I have similar problem to https://github.com/dbeaver/dbeaver/issues/22302 
Some fields in code editor are underlined in red color:
![dbeaver_Pdv499Acf1](https://github.com/dbeaver/dbeaver/assets/5068855/1e99d399-a516-45c1-b8d9-c8d27c64a534)
But this query runs perfectly fine.

Error.log:
[error.log](https://github.com/dbeaver/dbeaver/files/14580484/error.log)

### DBeaver Version

Community Edition 24.0.0.202403091004

### Operating System

Windows 11 Home

### Database and driver

Database: MySQL 8.3.0
Driver: mysql8 (MySQL Connector J 8.2.0)
![dbeaver_XBTggytEAg](https://github.com/dbeaver/dbeaver/assets/5068855/259761df-9992-4079-9750-880e568b1a45)

### Steps to reproduce

1. I connect to database
2. Open saved query or write new query in code editor

### Additional context

Code completion sees the field that is highlighted.
![SjjmJ3TFDj](https://github.com/dbeaver/dbeaver/assets/5068855/e6a3ebd9-2b65-4ba1-b9bd-002c6cd07da9)

I tried restarting settings.

**Comment by LonwoLonwo** [comment] 2024-03-13 09:53
Hello @saikotek 

Could you please provide your tables DDLs? For testing.

**Comment by saikotek** [comment] 2024-03-13 16:30
Hello @LonwoLonwo 
Yes, I think I found where is the problem. Check out the DDL I attached.

[dump-test_null-202403131722.txt](https://github.com/dbeaver/dbeaver/files/14590776/dump-test_null-202403131722.txt)

It seems that the problem arises when the table name is a MySQL keyword (therefore you need to query it with backticks)
![dbeaver_ejvG134OGT](https://github.com/dbeaver/dbeaver/assets/5068855/901632b8-bb83-40d9-b883-9f0a0bb520f5)

**Comment by E1izabeth** [comment] 2024-03-14 06:00
It's a duplicate of https://github.com/dbeaver/dbeaver/issues/23020

**Comment by E1izabeth** [comment] 2024-05-06 11:50
Does it still reproducible? I can't reproduce the issue.

UPDATED: never mind, reproduces with connection turned off

**Comment by Yigitttttttt** [comment] 2024-05-09 10:45
I have same bug on ORACLE

**Closed as completed** 2024-05-10 14:29 UTC
Labels: x:mysql, sp:2, xf:sql editor
