### ISSUE TITLE
How to connect to RedShift using dBeaver and IAM

### ISSUE THREAD

**Issue by adbdkb** [dbeaver/dbeaver#29331] opened 2024-05-04 08:33 UTC
### Description

I am attempting to connect to RedShift cluster using IAM role from a Mac machine.  When I do "Test Connection", I get the error below

WIA only support Windows platform. 

Something unusual has occurred to cause the driver to fail. Please report this exception.

![image](https://github.com/dbeaver/dbeaver/assets/26495406/c1ff698b-0f6f-4927-9d6e-99b3f1b9db3e)

### DBeaver Version

Community Edition 24.0.3

### Operating System

macOS Sonoma 14.4.1

### Database and driver

RedShift / 

Files extracted from redshift-jdbc42-2.1.0.26.zip from Amazon site

![image](https://github.com/dbeaver/dbeaver/assets/26495406/111a3188-c49e-488c-9519-ecda30df8f4a)

### Steps to reproduce

1. Setup the new drivers using above jars and RedShift cluster info
2. Click Test Connection

**Comment by Destrolaric** [comment] 2024-05-23 13:36
Duplicate of [#32349](https://github.com/dbeaver/dbeaver/issues/32349)

**Closed as not planned by Destrolaric** 2024-05-23 13:36 UTC
Labels: duplicate, xo:macos, x:redshift
