### ISSUE TITLE
No link on quoted object name

### ISSUE THREAD

**Issue by plmmihail** [dbeaver/dbeaver#14685] opened 2021-11-25 10:39 UTC
[x:sql]

#### System information: 
- Operating system (distribution) and version
Linux
- DBeaver version
The last
- Additional extensions
No
#### Connection specification:
- Database name and version
Most of SQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Steps to reproduce, if exist:
Create an object (view, procedure, function) or a query with objects 
`"Obj 1", "Obj_1", OBJ_1` etc. Try to click with ctrl for opening objects's windows. In Oracle no problems only with OBJ_1, in Postgres no problems only with obj_1. In most of SQL DBs in Dbeaver there is no event on name with spaces or other quoted, especially `MixedCase`.

**Comment by uslss** [comment] 2021-12-06 08:48
thanks for the report. Closed a duplicate of #12043

**Closed as completed by uslss** 2021-12-06 08:48 UTC
Labels: duplicate, xf:sql
