### ISSUE TITLE
Export in new table of several selected columns generates all columns

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14439] opened 2021-10-29 12:01 UTC
#### System information: 
- Win10, 
- DBeaver CE 21.2.4

#### Connection specification:
- Not specific

#### Describe the problem you're observing:
I want to export some columns to the new table, but all other columns of the source table are generated in the new table and filled with NULLs 

#### Steps to reproduce, if exist:
Open table with several columns.
Select some of them.
Begin export.
Select Database export type.
Select target table as new table (Mapping = create)
Check "Selected columns only" and start export.
**Expected:** only selected columns were exported
**Actual:** all other columns of the source table are generated in the new table and filled with NULLs

**Comment by Matvey16** [comment] 2021-10-29 14:02
Not specific to SQL server

**Comment by LonwoLonwo** [comment] 2022-03-04 12:01
Looks like a duplicate of https://github.com/dbeaver/dbeaver/issues/14278

**Closed as completed by LonwoLonwo** 2022-03-04 12:01 UTC
Labels: duplicate, xf:datatransfer
