### ISSUE TITLE
SQLite: Canceling Query Breaks Database Connection

### ISSUE THREAD

**Issue by XiozTzu** [dbeaver/dbeaver#10095] opened 2020-10-17 16:38 UTC
#### System information: 
- Operating system: Windows 10 Version 10.0.18363.1082
- DBeaver version:  7.2.2.202010041557
- Additional extensions: None

#### Connection specification:
- Database name and version: SQLite
- Driver name: sqlite-jdbc 3.32.3.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? N/A

#### Describe the problem you're observing:
Starting a query then canceling before completion breaks connection to the db.  Still shows connected on left panel.  
Can resolve by manually disconnecting and reconnecting.
Occasionally, canceling during query will crash DBeaver.  No error message.

#### Steps to reproduce, if exist:
Start a query and cancel it before it finishes.

#### Include any warning/errors/backtraces from the logs
No error message

**Comment by uslss** [comment] 2020-10-19 08:48
It is a known behavior,.
The issue is closed as a duplicate of #9142
Anyway, thanks for the report :)

**Closed** 2020-10-20 09:29 UTC
Labels: bug, duplicate
