### ISSUE TITLE
Disable auto-capitalization of keywords inside comments.

### ISSUE THREAD

**Issue by cdabel** [dbeaver/dbeaver#8839] opened 2020-05-29 15:46 UTC
#### System information: 
Mac OS - latest version

#### Connection specification:
Not sure if relevant, but Redshift via Postgres driver

#### Describe your question:
I think this may be more of an enhancement, but I would like to disable auto-capitalization of SQL keywords automatically while typing within comments. Is there a way to do this? I know how to turn it off completely, but I would like the behavior to be contextual in this way.

**Comment by uslss** [comment] 2020-05-30 20:30
thanks for suggestion

**Comment by uslss** [comment] 2020-09-11 15:28
duplicate of #5994

**Closed by uslss** 2020-09-11 15:28 UTC
Labels: enhancement
