### ISSUE TITLE
SQL edit box content is blocked

### ISSUE THREAD

**Issue by aiviseven** [dbeaver/dbeaver#22680] opened 2024-02-02 03:08 UTC
### Description

When I was writing SQL, I scrolled up and down the content with the mouse scroll wheel, and then some of the content was blocked. Even when I restarted the software, it was also blocked.

### DBeaver Version

Community Edition 23.3.3.202401211839

### Operating System

macOS Sonoma 14.2.1

### Database and driver

mysql 5.7.22 mysql-connector-java-5.1.46-bin.jar

### Steps to reproduce

When I was writing SQL, I scrolled up and down the content with the mouse scroll wheel.
<img width="940" alt="image" src="https://github.com/dbeaver/dbeaver/assets/24937078/bdca449c-6919-419e-9517-1c41ad3fbc0c">

### Additional context

Apple M1

**Comment by E1izabeth** [comment] 2024-02-02 08:23
Thank you for bug report. You can find a workaround here https://github.com/dbeaver/dbeaver/issues/22299#issuecomment-1910602876
I'm closing it as a duplicate of #22299

**Closed as not planned by E1izabeth** 2024-02-02 08:23 UTC
Labels: duplicate, xo:macos, xf:sql editor
