### ISSUE TITLE
NPE when edit target table in import task

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#23318] opened 2024-04-04 12:38 UTC
### Description

Tested on PostgreSQL 10.0

STR:

1. Create import task (CSV -> existing table) Save this task
2. Edit task. Remove target table and add another target table
3. Press Save tast
actual result - see NPE/ new target table is not saved

https://github.com/dbeaver/dbeaver/assets/84867187/ccecef66-c6b8-4edf-bcdf-bf11c23f58d9

```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.tools.transfer.stream.StreamEntityMapping.getInputFile()" because "mapping" is null
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer$ObjectSerializer.serializeObject(StreamTransferProducer.java:184)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer$ObjectSerializer.serializeObject(StreamTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DTUtils.serializeObject(DTUtils.java:269)
	at org.jkiss.dbeaver.tools.transfer.DataTransferSettings.saveNodesLocation(DataTransferSettings.java:706)
	at org.jkiss.dbeaver.tools.transfer.ui.wizard.DataTransferWizard.saveTaskState(DataTransferWizard.java:498)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.saveConfigurationToTask(TaskConfigurationWizard.java:316)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.saveTask(TaskConfigurationWizard.java:311)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard$2.widgetSelected(TaskConfigurationWizard.java:368)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.tasks.ui.view.TaskHandlerEdit.execute(TaskHandlerEdit.java:56)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:99)
	at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:298)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:232)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:785)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:762)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:295)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:647)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:607)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1464)

```

### DBeaver Version

DBeaver 24.0.2

### Operating System

windows 10

**Comment by LonwoLonwo** [comment] 2024-04-04 16:48
This is a duplicate of : https://github.com/dbeaver/dbeaver/issues/21452

**Closed as completed by LonwoLonwo** 2024-04-04 16:48 UTC
Labels: xp:major, duplicate, xf:datatransfer, regression
