### ISSUE TITLE
ERROR: relation "pgagent.pga_job" does not exist

### ISSUE THREAD

**Issue by loynoir** [dbeaver/dbeaver#17119] opened 2022-07-19 10:04 UTC
#### System information: 
- Operating system (distribution) and version  Arch
- DBeaver version Version 22.1.2.202207112146
- Additional extensions

#### Connection specification:
- Database name and version
docker postgres:14.4-alpine3.16
docker postgres:14.4-bullseye
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
- Administer -> jobs, got `ERROR: relation "pgagent.pga_job" does not exist`
- Refresh connection, error will not gone, need to close dbeaver

#### Steps to reproduce, if exist:
- Administer -> jobs, got `ERROR: relation "pgagent.pga_job" does not exist`
- Refresh connection, error will not gone, need to close dbeaver

#### Include any warning/errors/backtraces from the logs

Can't access pgAgent jobs.

This database may not have the extension installed or you don't have sufficient permissions to access them.

If you believe that this is DBeaver's fault, please report it.

SQL Error [42P01]: ERROR: relation "pgagent.pga_job" does not exist
  Position: 15
  ERROR: relation "pgagent.pga_job" does not exist
  Position: 15
  ERROR: relation "pgagent.pga_job" does not exist
  Position: 15

**Comment by ShadelessFox** [comment] 2022-07-19 15:11
Hello @loynoir,

Are you sure that the `pgagent` extension is installed on the server?

**Comment by loynoir** [comment] 2022-07-19 19:45
@ShadelessFox
Ah, seems not, just pull from docker without extra actions.

<details>
  <summary></summary>
  <p>
 
With current implement, `refresh connection`, don't need to click `Administer -> jobs` by mistake again, got a alert immediately and endlessly, thus need to `reopen dbeaver`
  </p>
</details>

Is it possible to detect it and show dialog suggest to install `pgagent`?

**Comment by ShadelessFox** [comment] 2022-07-20 09:31
Thanks for the clarification.

There is already a message that gives a hint:
> This database may not have the extension installed or you don't have sufficient permissions to access them.

We don't want to suggest installing anything since it will require performing additional actions outside DBeaver.

**Comment by LonwoLonwo** [comment] 2023-09-11 15:30
Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/16366

**Closed as completed by LonwoLonwo** 2023-09-11 15:30 UTC
Labels: x:postgresql, duplicate, xf:navigator, sp:2, xf:metadata
