### ISSUE TITLE
v7.1.0: Darkest Theme and 'Export data...'

### ISSUE THREAD

**Issue by valsamis-d** [dbeaver/dbeaver#8910] opened 2020-06-07 16:29 UTC
I'm not sure if this is entirely a DBeaver issue or not. I have also made a similar post to the 'Darkest Dark Theme with DevStyle' page.

System information: 

- Operating system (distribution) and version: Windows 10 Enterprise 1909
- DBeaver version: 7.1.0 Portable (Win64)
- Additional extensions: DBeaver Office Support

Connection specification:
- DB2
- DB2 JCC Type 4
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: Yes

#### Describe the problem you're observing:

By the time I install Darkest Dark Theme (https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle) export functionality gets broken. Specifically,  'Targets:' and 'Objects:' list come up as empty.

#### Steps to reproduce, if exist:
1) Install Darkest Dark Theme
1) Run a query
2) Right-click on the results grid, select 'Export data...'
3) The lists 'Targets:' and 'Objects:' in the "Data Transfer" form are empty

Now:

1) Uninstall Darkest Dark Theme
1) Run a query
2) Right-click on the results grid, select 'Export data...'
3) The lists 'Targets:' and 'Objects:' in the "Data Transfer" form have all available export types

**Comment by uslss** [comment] 2020-06-08 10:07
seems to be duplicate of #8113 .
anyway, thanks for the bug report

**Closed by uslss** 2020-06-08 10:07 UTC
Labels: bug, duplicate
