### ISSUE TITLE
Office Plugin - Data Transfer Screen Blank

### ISSUE THREAD

**Issue by blckshdw** [dbeaver/dbeaver#9214] opened 2020-07-09 14:39 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 1909
- DBeaver version 7.1.2
- Java version 
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
- Additional extensions
Darkest Dark
Office Integration

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
With both the Darkest Dark theme installed and the Office plugin.  When selecting Execute -> Export from Query the Data Transfer screen is blank.  
![image](https://user-images.githubusercontent.com/3106185/87053710-4c8eb280-c1d0-11ea-9892-2f61b7f3ff43.png)

#### Steps to reproduce, if exist:
- install Darkest Dark
- install Office integration
- open new sql query
- right click and Execute -> Export From Query

**Comment by uslss** [comment] 2020-07-09 15:46
thanks for the bug report
close as duplicate of #8113

**Closed by uslss** 2020-07-09 15:46 UTC
Labels: bug, duplicate, xf:dark theme
