### ISSUE TITLE
Autocomplete issue on Grouping configuration under Grouping tab

### ISSUE THREAD

**Issue by renchix** [dbeaver/dbeaver#12428] opened 2021-05-12 09:36 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: **21.0.4** (issue has been in all 21.0... versions)
- Additional extensions

#### Describe the problem you're observing:
In Grouping configuration window (Edit grouping columns) when editing functions section: you start typing column name i.e. enter first characters, autocomplete offers possible columns and when pressing Tab/Enter autocomplete inserts column name in addition to already typed characters. So then you need to manually delete already typed characters that called for autocomplete.

Expected solution: When pressing Tab/Enter on auto-complete choice first entered characters are replaced with chosen column name.

**Comment by LonwoLonwo** [comment] 2021-05-12 10:15
Hello @renchix 
Can't reproduce, sorry. We need more details - screenshots or video of incorrect behaviour will be very helpful.

![2021-05-12 13_11_43-Window](https://user-images.githubusercontent.com/45152336/117958652-ea3c9c00-b323-11eb-9bb7-4ee5b384a2ba.png)

![2021-05-12 13_11_56-Window](https://user-images.githubusercontent.com/45152336/117958654-ea3c9c00-b323-11eb-8a1e-b75ccaceb1cc.png)

**Comment by renchix** [comment] 2021-05-12 11:25
Issue shows up only when you first write the function name e.g. COUNT(  and then column name

**Comment by renchix** [comment] 2021-05-12 11:27
I just found that there is already similar issue - https://github.com/dbeaver/dbeaver/issues/11508
There is video in it..the same problem that I encounter

**Comment by LonwoLonwo** [comment] 2021-05-12 12:10
Ok. thanks

**Comment by LonwoLonwo** [comment] 2021-05-12 12:11
Closed as duplicate of #11508

**Closed as completed by LonwoLonwo** 2021-05-12 12:10 UTC
Labels: duplicate
