### ISSUE TITLE
I hope you can also realize the function of displaying function usage

### ISSUE THREAD

**Issue by zem558** [dbeaver/dbeaver#17630] opened 2022-09-13 04:38 UTC
![1](https://user-images.githubusercontent.com/45349060/189809721-99c0c00e-95b7-4d01-857b-9398321df7fb.png)
![2](https://user-images.githubusercontent.com/45349060/189810117-a7aa67c5-8079-4a7e-a9d5-9b12e88dfb46.png)
![3](https://user-images.githubusercontent.com/45349060/189810149-298cfb90-eac8-4f7e-b582-6a76aaee65a3.png)

**Comment by LonwoLonwo** [comment] 2022-09-13 07:18
Hello @zem558 

Thanks for the idea.

We already have the ticket with the same request, so I'm closing this as a duplicate of #14872

**Closed as not planned by LonwoLonwo** 2022-09-13 07:18 UTC
Labels: duplicate, xf:sql
