### ISSUE TITLE
After upgrade to 23.0.3.202304240616 DBeaver it's not loading at all Unbtu 22.04.1 

### ISSUE THREAD

**Issue by maorblum** [dbeaver/dbeaver#19787] opened 2023-04-24 11:40 UTC
### Description

After upgrade to version 23.0.3.202304240616
DBeaver it's not loading at all.
Cursor is spinning for some time but eventually the application is not loaded.
Trying to press again gets the same result.

### DBeaver Version

Community Edition 23.0.3.202304240616

### Operating System

Ubnuntu 22.04.1

**Comment by serge-rider** [comment] 2023-04-24 11:55
Could you check for any log files (https://github.com/dbeaver/dbeaver/wiki/Log-files) ?

**Comment by maorblum** [comment] 2023-04-24 13:06
I have no idea what was changed, 
but suddenly the application started working!!

Regarding the logs, taking a look at the logs here:
/snap/dbeaver-ce/231/.local/share/DBeaverData/workspace6/.metadata
I see that only now logs were created.
I think that in my earlier retries, when the application didn't start,
no logs were created.

**Comment by serge-rider** [comment] 2023-04-24 13:21
Thank you for the update.
Application start can take quite a time during first start (it extracts archives and validates consistency). Especially if you have any anti-virus software.

**Comment by LonwoLonwo** [comment] 2023-04-24 14:58
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/19779

**Closed as completed by LonwoLonwo** 2023-04-24 14:58 UTC
Labels: duplicate, xf:snap, question
