### ISSUE TITLE
Scrollbars (horizontal and vertical) overlap the data

### ISSUE THREAD

**Issue by p4scu41** [dbeaver/dbeaver#8322] opened 2020-04-02 16:48 UTC
#### System information: 
- Linux version 4.19.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.98-1 (2020-01-26)
- DBeaver Version 7.0.1.202003211804

#### Connection specification:
- MySQL 14.14 Distrib 5.6.33, for debian-linux-gnu (x86_64)
- mysql-connector-java-5.1.44

The scrollbars overlap the result grid

![Scrollbars (horizontal and vertical) overlap the data](https://user-images.githubusercontent.com/1633236/78275668-2241a080-74cf-11ea-8c98-639d802ad7bb.gif)

**Comment by uslss** [comment] 2020-04-09 14:21
seems to be duplicate of #5398 . ticket will be closed.
anyway, thanks for the bug report

**Closed by uslss** 2020-04-09 14:21 UTC
Labels: bug, duplicate
