### ISSUE TITLE
Can't acess dbo schema/user in 4.3.1

### ISSUE THREAD

**Issue by jeisoncp** [dbeaver/dbeaver#2741] opened 2018-01-05 17:18 UTC
I had to downgrade my DBeaver installation, because in the version 4.3.1 the dbo user was unavailable in the SQL editor auto-complete, the rows in results panel couldn't be edited and generate SQL function wasn't working.

Database: Sybase
DBeaver version: 4.31
No shemas/users filters.

![image](https://user-images.githubusercontent.com/7952798/34619536-989ee11e-f229-11e7-8910-f5ab1639fce4.png)

![image](https://user-images.githubusercontent.com/7952798/34619481-6fd2e348-f229-11e7-9542-c57345520605.png)

DBeaver version: 4.30
No shemas/users filters.

![image](https://user-images.githubusercontent.com/7952798/34619659-0818dc02-f22a-11e7-84ee-643893571070.png)

**Comment by serge-rider** [comment] 2018-01-05 19:42
It is a bug in 4.3.1, will be fixed in the next version.
Duplicate of #2633

Thanks for report anyway

**Closed by serge-rider** 2018-01-05 19:42 UTC
Labels: bug, duplicate
