### ISSUE TITLE
remove default fetch size?

### ISSUE THREAD

**Issue by mrhargro** [dbeaver/dbeaver#10178] opened 2020-10-26 23:08 UTC
I just updated to 7.2.3 and my setting to NOT limit the fetch size has somehow been lost. 

I can't seem to get that to work.  Currently everything is limited to 100 rows. How do I remove this limit? (I upped the limit to a large number and that seems to work but I believe I did something different before).

**Comment by uslss** [comment] 2020-10-27 12:13
Issue will be solved in 7.2.4 #10121 
You could check if the issue is solved in EA version https://dbeaver.io/files/ea/

Close this issue as duplicate

**Closed by uslss** 2020-10-27 12:13 UTC
Labels: duplicate, enhancement

**Comment by mrhargro** [comment] 2020-10-27 13:00
thx.
