### ISSUE TITLE
'Update Job' has encountered a problem.

### ISSUE THREAD

**Issue by anigart** [dbeaver/dbeaver#10855] opened 2021-01-03 18:19 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10 
- DBeaver version: 7.3.1.202012201616

#### Describe the problem you're observing:
After startup, an error message comes up:
'Update Job' has encountered a problem.
"An internal error occurred during: "Update Job".
Registry Directory not available: C:\Users\john\.eclipse\org.jkiss.dbeaver.product_7.2.5_1535670467_win32_win32_x86_64\p2\org.eclipse.equinox.p2.engine\profileRegistry."

#### Steps to reproduce, if exist:
- Startup, run a query

#### Include any warning/errors/backtraces from the logs
Log attached
[log.zip](https://github.com/dbeaver/dbeaver/files/5762032/log.zip)

**Comment by serge-rider** [comment] 2021-01-04 08:26
Duplicate of #10768

Thanks for the bug report anyway.

**Closed as completed by serge-rider** 2021-01-04 08:26 UTC
Labels: duplicate

**Comment by Jonathan-Martin1** [comment] 2021-05-09 15:31
I keep getting same error with Windows 10. Never used to get this error.

**Comment by swiateks** [comment] 2023-06-13 10:05
Hello, does anyone have a solution for this?
