### ISSUE TITLE
Advanced copy, copy wrong record

### ISSUE THREAD

**Issue by toninomanzi** [dbeaver/dbeaver#10371] opened 2020-11-16 08:06 UTC
DBEAVER 7.2.5

Function advance copy.

On a table when is sorted (by click on a column) if you use the fuction advance copy the record copied is not the same as selected.

**Comment by uslss** [comment] 2020-11-16 08:51
Thanks for the report.
Closed as duplicate of #9252

**Closed by uslss** 2020-11-16 08:51 UTC
Labels: bug, duplicate
