### ISSUE TITLE
"Save as" dialog fails to add default extension when specifying filename without one

### ISSUE THREAD

**Issue by getta-mike** [dbeaver/dbeaver#14495] opened 2021-11-05 16:30 UTC
When omitting an extension in the filename, the save as dialog box is supposed to add the extension specified in the below dropdown.  Instead, it saves the file without the extension, causing you to have to manually add the .sql (or whatever your default is) to it later.  I experience this problem when using the query editor; not aware of any other places, if there are any.

In the screenshot below, the file is supposed to be saved as `sample_query.sql` but instead will be saved as just `sample_query`

![image](https://user-images.githubusercontent.com/72145576/140544233-5515c401-d272-4297-8715-ab11bb91ceac.png)

Versions: 21.2.3, 21.2.4
Windows10
Conn. Driver: Postgres

-Mike

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by ShadelessFox** [comment] 2021-11-05 17:38
Hello @getta-mike,

Thanks for the report.

Duplicate of #14013

**Closed as completed by ShadelessFox** 2021-11-05 17:38 UTC
Labels: duplicate

**Comment by getta-mike** [comment] 2021-11-08 15:18
sorry - tried to do the homework by searching for already existing issue
but didn't find one.
