### ISSUE TITLE
Request: Option to not close windows on disconnect

### ISSUE THREAD

**Issue by theotherp** [dbeaver/dbeaver#7810] opened 2020-02-03 11:42 UTC
I often have to close my connection to the local database because I have to recreate it (which includes dropping the schema for which no connections may be open). Afterwards I want to continue working as before. But currently disconnecting the database closes all open table editors and I have to open each one again. It would be great to have an option to keep them open and perhaps refresh them on reconnect. Or perhaps some kind of indicator that the context is stale.

I checked the preferences but didn't find anything like that.

**Comment by serge-rider** [comment] 2020-02-11 14:00
This would be a good feature. But it is not that easy to implement it.
We already have sort of "hibernation" for editors (when you close DBeaver app). But for running instance we'll need to invent some new UI. Like editor "locking".

**Comment by SylwesterZarebski** [comment] 2021-07-13 17:54
What is a reason for linking tabs (editors or table/data) with connection?
Only state for tabs should be text (SQL) or visible data (tabular or table properties etc).
Connections should be managed on demand and cached in background, this would allow for multiple connections on demand (i.e. retrieving data in multiple tabs).

**Comment by E1izabeth** [comment] 2023-05-25 09:01
Fixed in scope of #18449

Now it's controlled by this setting
![image](https://github.com/dbeaver/dbeaver/assets/28875055/136dd751-cfa4-4ec6-98e5-1bf6896a367c)

**Closed by E1izabeth** 2023-05-25 09:01 UTC
Labels: feature request, planned, xf:ui

**Comment by dexy86** [comment] 2024-04-24 06:40
Cool feature but should it hold the data in the editor (view) on disconnect (i would love if it would) ? cause for me on fedora it just removes data and shows reconnect button in the middle... also it removes from history (quick query) anything i have queried.
Is that  a bug or a feature ? should i report it as a bug ?
thanks

**Comment by E1izabeth** [comment] 2024-04-25 08:23
It's definitely not a bug. You can create a new feature request, if you want
