### ISSUE TITLE
[v21.0.0] - Can't perform MariaDB dump with error : "/usr/bin/mysqldump: unknown variable 'column-statistics=0' "

### ISSUE THREAD

**Issue by RastaTaz** [dbeaver/dbeaver#11640] opened 2021-03-07 13:12 UTC
#### System information: 
- Operating system (distribution) and version : Ubuntu based
- DBeaver version : 21.0.0
- Additional extensions : -

#### Connection specification:
- Database name and version : 
  - Remote DB : MariaDB 10.x (maybe 10.2)
  - Local client : MariaDB 10.3 "mysqldump  Ver 10.17 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64)"
- Driver name : MariaDB (type : MySQL)
- Do you use tunnels or proxies (SSH, SOCKS, etc) : SSH tunnel

#### Describe the problem you're observing:
Can't dump remote DB

#### Steps to reproduce, if exist:
Perform a dump (with local client = /usr/bin), got following error:
```
/usr/bin/mysqldump --column-statistics=0 --routines --add-drop-table --disable-keys --extended-insert -u root --host=127.0.0.1 --port=25677 <ANON_DB_NAME>
Task 'MySQL dump' started at Sun Mar 07 14:06:54 CET 2021
/usr/bin/mysqldump: unknown variable 'column-statistics=0'
Task 'MySQL dump' finished at Sun Mar 07 14:06:54 CET 2021
```
=> It does not seem to be a default configuration on my side, and I can't find anywhere to remove this option in DBeaver

#### Include any warning/errors/backtraces from the logs

Don't think any backtrace pertinent here.

**Comment by uslss** [comment] 2021-03-07 13:14
thanks for the report
closed as a duplicate of #11562 .
will be fixed in the scope of 21.0.1

**Closed as completed by uslss** 2021-03-07 13:14 UTC
Labels: duplicate
