### ISSUE TITLE
Leading space for columns in text view still missing

### ISSUE THREAD

**Issue by S-Man42** [dbeaver/dbeaver#5321] opened 2019-02-19 13:42 UTC
Referring to Issue 5054: https://github.com/dbeaver/dbeaver/issues/5054

The feature added in 5.3.4 was the adding of the trailing space. But in 5.3.5 the leading space is still missing. Would it be possible to add this? Otherwise it looks weird to me:

This option should add both: trailing and leading space:
Actual:
```
|id     |released   |
|-------|-----------|
|     1 |2001-11-04 |
|     2 |2002-11-03 |
|     3 |2004-05-23 |
```
Expected
```
| id    | released   |
|-------|------------|
|     1 | 2001-11-04 |
|     2 | 2002-11-03 |
|     3 | 2004-05-23 |
```

**Comment by serge-rider** [comment] 2019-02-21 21:37
Duplicate of #5278

**Closed by serge-rider** 2019-02-21 21:37 UTC
Labels: bug, duplicate
