### ISSUE TITLE
SQL query(with join) export to XLSX files，"header format" description support

### ISSUE THREAD

**Issue by DenisQuan** [dbeaver/dbeaver#19238] opened 2023-03-02 02:14 UTC
export to XLSX files，"header format" selected both or description, XLSX file does not contain "description" row.
![image](https://user-images.githubusercontent.com/122078217/222312499-8d78a2e5-84d6-4c72-b3fb-e4f86797fc03.png)

![image](https://user-images.githubusercontent.com/122078217/222312122-b0bd9a92-bd52-4206-830e-cb68fcb104ac.png)

but if "Exported" is a table , not query(with join)  ,it can work.
![image](https://user-images.githubusercontent.com/122078217/222312455-408b8722-754d-4650-992b-7cf34431903d.png)

maybe, it's a bug

**Comment by LonwoLonwo** [comment] 2023-03-02 10:23
Hello @DenisQuan 

Thanks for the report. This is duplicate of https://github.com/dbeaver/dbeaver/issues/18330
But I changed the priority for the original ticket.

**Closed as not planned by LonwoLonwo** 2023-03-02 10:23 UTC
Labels: duplicate, xf:datatransfer
