### ISSUE TITLE
Row colors - save and load

### ISSUE THREAD

**Issue by DurkoS** [dbeaver/dbeaver#26851] opened 2024-04-26 09:26 UTC
**Is your feature request related to a problem? Please describe.**
When Dbeaver is restarted all row colors are lost and have to be set again. Row colors are very useful for logs in DB.

**Describe the solution you'd like**
Would be nice to save and load row colors, maybe with same name. Nice would be export and import too.

**Describe alternatives you've considered**
At least would be nice to remain row colors after restart. (Configuration Yes/No)

**Additional context**
Mean this Customize colors for rows:
![image](https://github.com/dbeaver/dbeaver/assets/168178298/637f9657-7e7d-4cbc-9509-ebf31a9a38f7)

**Comment by E1izabeth** [comment] 2024-04-26 09:35
Sounds like it's a duplicate of https://github.com/dbeaver/dbeaver/issues/8281

**Comment by DurkoS** [comment] 2024-04-26 15:14
#8281 is bug for problem with row colors. This issue is feature request for saving row colors event if Dbeaver is restarted

**Comment by serjiokov** [comment] 2024-05-16 07:16
Hello @DurkoS,
I can not reproduce it,   
After the product restart the row colors are restored successfully
![image](https://github.com/dbeaver/dbeaver/assets/32031248/69d4ea88-b4cf-45de-8012-8b2fb1574256)

What version are you using? 
Could you provide steps to reproduce, please?

**Comment by serjiokov** [comment] 2024-05-16 07:18
![image](https://github.com/dbeaver/dbeaver/assets/32031248/2db02fb6-4002-4621-92d9-247f6bde8521)

**Comment by DurkoS** [comment] 2024-05-16 11:12
Hello @serjiokov,
I am using the last windows(zip) version - https://dbeaver.io/files/dbeaver-ce-latest-win32.win32.x86_64.zip
For example a row color is set for Country Brazil:
![image](https://github.com/dbeaver/dbeaver/assets/168178298/03c0096f-9a97-4603-bd6e-4894db3c0a16)
After close and start DBeaver the row color is lost:
![image](https://github.com/dbeaver/dbeaver/assets/168178298/ce88f623-9cac-46d0-9831-9556be9ae5ca)

**Comment by E1izabeth** [comment] 2024-05-16 13:19
I can't reproduce either. @DurkoS , what database do you use?

**Comment by E1izabeth** [comment] 2024-05-16 13:22
Oh, seems I get it. It's a duplicate of this issue #8281 anyway. You want us to preserve row colors for results of the queries you execute. Please see this answer https://github.com/dbeaver/dbeaver/issues/8281#issuecomment-604447911

**Closed as not planned** 2024-05-16 13:22 UTC
Labels: duplicate, xf:data, wait for response
