### ISSUE TITLE
NULL values from csv tables aren't recognized as NULL but 'NULL' strings

### ISSUE THREAD

**Issue by braiam** [dbeaver/dbeaver#4755] opened 2018-12-07 19:55 UTC
When reading flat files, NULL values are interpreted as strings instead of NULL. This throws a wrench when trying to export results or just copy-n-pasting from a resultset. Please, recognize `,NULL,` as a NULL value for such column/row tuple.

**Comment by maln0ir** [comment] 2018-12-10 16:22
In csv files every value between commas is a string, so you can only use empty string (`,,`) to represent null value.

**Comment by braiam** [comment] 2018-12-10 17:12
Sadly that's not what happens:

```
ColA,ColB,ColC
NULL,2,
3,,NULL
,NULL,1
```

![image](https://user-images.githubusercontent.com/1323412/49748791-14825f00-fc7d-11e8-8780-e147adc9215f.png)

Null values should appear as grey `[Null]` values.

![image](https://user-images.githubusercontent.com/1323412/49748866-37ad0e80-fc7d-11e8-8121-ccc840bb3b2a.png)

If I try to export the results, it converts everything to strings.

**Comment by serge-rider** [comment] 2018-12-11 10:55
Well, by default all string literals in CSV are not null.
Generally this seems to be a duplicate of #1030

**Closed by serge-rider** 2018-12-11 10:55 UTC
Labels: duplicate, question

**Comment by braiam** [comment] 2018-12-11 12:14
@serge-rider Then how do we get NULL values? Because neither literal NULL nor empty strings seems to be recognized as NULL. And from what I gathered, neither \N would. Is there no way that a value would be recognized as NULL?
