### ISSUE TITLE
Add support for dameng database

### ISSUE THREAD

**Issue by yilusbu** [dbeaver/dbeaver#19078] opened 2023-02-16 08:16 UTC
Please support dream database, now we need to add drivers manually,and there are drawbacks to this approach.

1.After the table is created the fields of the table cannot be modified.
2.Incompatible data types.
3.SQL syntax does not match.
4.The UI interaction is not friendly.Exmple,The SQL statement is correct, but a red wavy line is displayed on the UI.

(DM Official website : https://www.dameng.com/)
Requests from Chinese users, thanks

**Comment by Destrolaric** [comment] 2023-02-16 14:28
Thank you for the idea.

**Comment by E1izabeth** [comment] 2023-09-12 16:51
Duplicate of #10133

**Closed as not planned by E1izabeth** 2023-09-12 16:51 UTC
Labels: duplicate, new driver, xp:normal
