### ISSUE TITLE
Regression: Dump Database Feature Causes Performance Issues and Wrong Dump File Options in Version 24.2.0

### ISSUE THREAD

**Issue by vatisteve** [dbeaver/dbeaver#35539] opened 2024-09-11 04:18 UTC
### Description

I recently upgraded from DBeaver version 24.1.5 to 24.2.0 and encountered several issues with the dump database feature that were not present in the previous version.

### Issues:

1. Result Dump Printed in Dump Process Tab: In version 24.2.0, the content of the result dump file is printed in the dump process tab. This change introduces a few problems:
    - I can no longer disable this feature, which was possible in previous versions.
    - When dumping a large database, the dump file can become enormous, causing the pop-up to lag and become unresponsive at times.
2. Incorrect Dump File Options: After dumping a database, the generated dump file contains incorrect options. Specifically, the file includes a LOCK TABLE command, even though I did not select this option in the Export configuration tab. This renders the dump file unusable for restoring on another machine, resulting in failed restores.

### Steps to Reproduce:

1. Upgrade DBeaver from version 24.1.5 to 24.2.0.
2. Use the "Dump Database" feature to export a database.
3. Observe that the dump result is printed in the dump process tab, with no option to disable it.
4. Attempt to restore the generated dump file on another machine, and note the incorrect options in the dump file (e.g., LOCK TABLE).

### Expected Behavior:

* There should be an option to disable printing the dump file content in the dump process tab.
* The dump file should not include incorrect options such as LOCK TABLE when the user has not selected them in the Export configuration.

### Actual Behavior:

* The dump process tab prints the content of the dump file, causing performance issues when dealing with large databases.
* The generated dump file contains incorrect options that prevent successful restoration on other machines.

### Workaround:

I downgraded to version 24.1.5, where the dump feature works as expected.

### Environment:
* DBeaver Version: 24.2.0 (issue present)
* DBeaver Version: 24.1.5 (working)
* Database Type: MariaDB
* Operating System: Window 10

Please investigate this regression as it severely impacts the usability of the dump and restore process in the latest version.

### DBeaver Version

Community Edition 24.2.0

### Operating System

Window 10

### Database and driver

**Database**: 10.3.39-MariaDB-0ubuntu0.20.04.2
**Driver**: MariaDB JDBC driver - org.mariadb.jdbc:mariadb-java-client:RELEASE - 3.3.2

**Comment by E1izabeth** [comment] 2024-09-11 07:08
Thank you for the bug report.
I'm closing it as it's a duplicate of #35421

**Closed as not planned by E1izabeth** 2024-09-11 07:08 UTC
Labels: duplicate, xf:native clients
