### ISSUE TITLE
strange behavior 5.1.4

### ISSUE THREAD

**Issue by hugorn** [dbeaver/dbeaver#3961] opened 2018-08-10 12:15 UTC
When you press the enter key panels appear on the right side.

Deepin Linux - dbeaver-ce_5.1.4_amd64.deb

After downgrade to 5.1.3 works fine.

![problem](https://user-images.githubusercontent.com/9035153/43957338-e0ad9352-9c7d-11e8-9ae2-ce851b832702.gif)

**Comment by serge-rider** [comment] 2018-08-10 12:16
Duplicate of #3916
See comments for workaround.

**Closed by serge-rider** 2018-08-10 12:16 UTC
Labels: bug, duplicate
