### ISSUE TITLE
Create procedure and function can't work

### ISSUE THREAD

**Issue by Wang19961231** [dbeaver/dbeaver#18049] opened 2022-10-26 19:23 UTC
### Description

When I create procedures or functions, it shows " Updated Rows   -1"., so when I call it, it shows "SQL Error [1305] [42000]: PROCEDURE/FUNCTION XXXXX does not exist. 
![1666812034630](https://user-images.githubusercontent.com/75326829/198117793-a44a306e-03bb-4fcc-9c15-b7adda635654.png)
![1666812013735](https://user-images.githubusercontent.com/75326829/198117807-f21b2506-bc6b-4051-9c7c-20802df554c4.png)

### DBeaver Version

DBeaver Community 22.2.3

### Operating System

Windows 10

### Database and driver

MySQL

### Steps to reproduce

create database shicuo;
use shicuo;

DELIMITER //
CREATE PROCEDURE insert_user(IN username VARCHAR(20),IN loginPwd VARCHAR(20))
BEGIN
INSERT INTO admin(user_name,pwd)
VALUES(username,loginpwd);
END //
DELIMITER ;

call insert_user();

### Additional context

]

**Comment by E1izabeth** [comment] 2022-10-27 10:23
Thank you for bug report.
As a workaround you can select the query part this way and press Execute. Than DBeaver will send the selected part of text to the database.
![image](https://user-images.githubusercontent.com/28875055/198260281-8de32ae4-4601-4c2f-ad45-23ef58a2a1d1.png)

**Comment by E1izabeth** [comment] 2022-10-27 10:38
The bug was initially posted here #17994. I'll close this issue as a duplicate.

**Closed as not planned** 2022-10-27 12:12 UTC
Labels: x:mysql, duplicate, x:maria, xf:sql

**Comment by E1izabeth** [comment] 2022-10-27 12:24
@Wang19961231 I figured out what the problem is. DELIMITER command works only with Execute script button.
