### ISSUE TITLE
Big Query Results not populated when query starts with a temp function

### ISSUE THREAD

**Issue by theloglizard** [dbeaver/dbeaver#12443] opened 2021-05-13 00:37 UTC
#### System information: 

- OS: MacOS Big Sur 11.3.1
- Dbeaver Version 21.0.4.202105021514

#### Connection specification:
- Big Query
-  Driver for Big Query: https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.13.1016.zip

- No tunnels or proxies

#### Problem observed:
I seem to have encountered a problem similar to [#10478](https://github.com/dbeaver/dbeaver/issues/10478) , "Dbeaver thinks it's an update statement but it is a select #10478" in that I see a "statistics" tab but no results when a simple SQL statement is preceded by a prior clause (in that case it was a with, but here I have a temp function).

#### Steps to reproduce, if exist:
The basic query :

> SELECT * FROM `bigquery-public-data.austin_311.311_service_requests`;

returns a results table, as expected :

![image](https://user-images.githubusercontent.com/55997192/118059879-846e0580-b35f-11eb-8b52-e621aa90ad7d.png)

Then the following query run in dbeaver:

> CREATE TEMP FUNCTION fiddle(val string) AS (
  substr(val,0,4)
  );
 SELECT fiddle(complaint_description) as fiddled,* 
FROM `bigquery-public-data.austin_311.311_service_requests`;

returns Statistics, but no results:

![image](https://user-images.githubusercontent.com/55997192/118059265-1ecd4980-b35e-11eb-9162-97d8bd17778a.png)

The corresponding log says no rows returned, though the query was a success:
![image](https://user-images.githubusercontent.com/55997192/118060213-34dc0980-b360-11eb-9be1-d8b39fb677a0.png)

And finally that same query returning no results in dbeaver, does provide results in the Big Query UI:
![image](https://user-images.githubusercontent.com/55997192/118059437-86839480-b35e-11eb-8ce7-dbd5bd9dea44.png)

#### Include any warning/errors/backtraces from the logs
There does not appear to be anything written in the error log.

Apologies if this has been reported before, but I could find nothing like this. 
Thanks in advance.

**Comment by uslss** [comment] 2021-05-13 08:02
thanks for the report

**Comment by ShadelessFox** [comment] 2021-05-13 11:34
As pointed out, the problem is indeed similar to one described in another ticket, and the solution is, in fact, the same.

This is a bug in Simba JDBC driver, updating it to 42_1.2.16.1020 fixes the problem.

**Comment by theloglizard** [comment] 2021-05-13 13:31
Thanks much for the reply. I had difficulty getting the driver editor to take it, but after deleting the old driver (I guess there can only be one?) and then loading the new version from a locally downloaded copy, all seems well. 

Though I should have noticed the driver versions, and I'm not sure where the default load gets set, but you might consider updating that.

**Comment by ShadelessFox** [comment] 2021-05-13 13:44
I've updated the driver version, but first we need to make sure everything is working flawlessly before closing the ticket. 

Until that, I will reopen this ticket.

**Comment by uslss** [comment] 2021-05-18 11:49
verified

**Closed as completed by uslss** 2021-05-18 11:49 UTC
Labels: xf:sql, x:bigquery, sp:1

**Comment by filkovsp** [comment] 2022-10-18 13:34
hi, 
same issue when running similar thing with temp table in dbeaver:
```sql
begin
  create temporary table if not exists tmp_Table (
    `number` float64
  );
  
  insert into tmp_Table 
  values 
    (rand()),
    (rand());
  
  select * from tmp_Table;
end;
```

that returns just `Statistics` result:
```
Updated Rows | 0
Query.       | begin
             |   create temporary table if not exists tmp_Table (
             |     `number` float64
             |   );
             |
             |   insert into tmp_Table 
             |   values 
             |     (rand()),
             |     (rand());
             |     
             |     select * from tmp_Table;
             |   end;
Finish time  | Tue Oct 18 14:26:00 BST 2022
```
