### ISSUE TITLE
Compilation error when trying to compile any postgresql function in DBeaver: Version 6.3.1.201912221734.

### ISSUE THREAD

**Issue by Gregory-Clark** [dbeaver/dbeaver#7487] opened 2019-12-26 19:03 UTC
I am getting a compilation error when trying to compile any postgresql function in DBeaver: Version 6.3.1.201912221734.

SQL Error [42601]: Unterminated dollar quote started at position 90 in SQL CREATE OR REPLACE FUNCTION 

To be sure it was not an issue with the functions themselves I pulled a function that compiled fine three days ago and tried it. It got the same error. 

Note that if I select all of the text and then compile, it works fine. Previously, I could have the cursor in front of the word "CREATE". That worked perfectly. Now it does not. 

Not the biggest issue in the world, and I can work around it. Just a slight problem.

Thank You,
Greg

**Comment by serge-rider** [comment] 2019-12-27 08:55
Most likely a duplicate of #7460

**Closed by serge-rider** 2019-12-27 08:55 UTC
Labels: bug, duplicate, x:postgresql
