### ISSUE TITLE
Cursor jumps to end of file when query was changed and executed using CTRL+ENTER

### ISSUE THREAD

**Issue by rhuesken** [dbeaver/dbeaver#15564] opened 2022-02-21 08:26 UTC
#### System information: 
- Windows 10
- Version 21.3.5.202202200327

#### Connection specification:
- Database name and version: Postgres 13

#### Describe the problem you're observing:
I have many queries I execute often in a script file for testing purposes. When I change a query (e.g. new condition) and execute it using CTRL+ENTER, the cursor jumps away from the current query and goes to end of the file. This does not happen when using the mouse and clicking the button.

This is very annoying, since I need to scroll back all the time. Happens since updatting to Version 21.3.5.202202200327

**Comment by uslss** [comment] 2022-02-21 08:34
thanks for the report
closed as a duplicate of #15562

**Closed as completed by uslss** 2022-02-21 08:34 UTC
Labels: duplicate, xf:sql
