### ISSUE TITLE
Erd diagrams: not fully export png

### ISSUE THREAD

**Issue by damienpolizzi** [dbeaver/dbeaver#6772] opened 2019-09-18 11:46 UTC
Linux debian 10
Dbeaver 6.2
Postgresql 11

#### Describe the problem you're observing:
When I try to export erd diagrams to png format, sometimes the diagram is not fully export

#### Steps to reproduce, if exist:
Makes a diagram with tables containing a few tables with columns
- try to export to png
- moves the tables and try to export again... a few times
You will see that, depending of the position of tables, sometimes the diagram is fully printed, sometimes not.

**Comment by uslss** [comment] 2020-01-07 15:54
still actual (6.3.2)

**Comment by serge-rider** [comment] 2020-01-18 15:19
Duplicate of #7300

**Closed by serge-rider** 2020-01-18 15:19 UTC
Labels: bug, duplicate
