### ISSUE TITLE
Database selector drop-down compacted and unusable.

### ISSUE THREAD

**Issue by philwrenn** [dbeaver/dbeaver#2375] opened 2017-10-19 13:18 UTC
The drop-down used to select the active database when a query editor is open is compacted. I have deleted ~/.dbeaver4 and the issue persists. 

DBeaver 4.2.3 insalled from 64bit RPM on Fedora 26

![selection_006](https://user-images.githubusercontent.com/234974/31772635-581384c8-b4ae-11e7-9891-8f6e05d879fe.png)

**Comment by serge-rider** [comment] 2017-10-19 14:52
Looks like all custom controls in toolbar are corrupted.
You could try to switch current them (Preferences->General->Appearance). And/or to drag-n drop toolbar panels. It helps in some cases.

Workaround: you can use database navigator tree for current schema switch (thru context menu->Set active and/or "Set connection from navigator" button).

**Comment by philwrenn** [comment] 2017-10-19 15:07
I switched themes and moved the tool panels around, specifically the ones with squashed content. No effect.

![selection_007](https://user-images.githubusercontent.com/234974/31778063-b05c37c4-b4bd-11e7-9eaa-62ceb81f28e0.png)

I am familiar with the workaround and use it, but I think that behavior is a little dangerous and could result in more easily running a script on the wrong database.

**Comment by philippdieter** [comment] 2018-03-04 15:44
![auswahl_001](https://user-images.githubusercontent.com/19897480/36947280-d74459e4-1fc9-11e8-8939-340f55dbed01.png)
I have the same problem with 4.3.5. Im running Arch Linux, which is up to date. I am not even able to rearrange the toolbars with squashed contents.
I have a second machine with the same configuration which doesn't suffer this problems. The only major difference i see is the one with the problem has a HiDPI display.

The dark theme is not the problem, I tried switching themes without a result. Removing all config files did not made a difference.

**Comment by dcupif** [comment] 2018-11-06 13:16
Same problem here, I also have an HiDPi display...

**Comment by serge-rider** [comment] 2018-11-06 14:31
This seems to be specific to some Linux versions. Some problems should be fixed in 5.2.3 (along with new Eclipse version migration).

Also you could try to install Darkest Dark theme (it is more a improvement than a workaround, it is the best Eclipse dark theme I know). It solves most of UI glitches with HighDPI screens.

**Comment by ShayMo1** [comment] 2018-12-07 02:38
I'm having this same issue with DBeaver 5.2.2 on Ubuntu 18.04.1. It's fine with scaling set to 100% but everything becomes so small it's unusable. I've tried installing the Darkest Dark theme. It didn't fix the problem (it is a really nice looking theme, though).

**Comment by uslss** [comment] 2019-03-31 21:03
cannot reproduce on 6.0.2

**Closed by uslss** 2019-03-31 21:03 UTC
Labels: bug, can't reproduce, help wanted
