### ISSUE TITLE
Large Text Data

### ISSUE THREAD

**Issue by TanerYurdunkulu** [dbeaver/dbeaver#20366] opened 2023-06-23 14:09 UTC
When there is large TEXT data like JSON in column , when I click column,  Value Preview TextBox taking time to load.
It would be good load first 200 chars for column for example , If I click show all , app would show all data then.

![image](https://github.com/dbeaver/dbeaver/assets/36150428/796560ba-e97a-478e-9be2-3993af4bcd79)

**Comment by E1izabeth** [comment] 2023-06-26 11:08
Thank you for report. It's a duplicate of #15951. You can vote for that issue by 👍🏻 under the description.

**Closed as not planned by E1izabeth** 2023-06-26 11:08 UTC
Labels: duplicate, xf:data
