### ISSUE TITLE
Menus don't follow selected Language

### ISSUE THREAD

**Issue by evandrosouza89** [dbeaver/dbeaver#20693] opened 2023-07-25 17:07 UTC
### Description

Since 23.1.2 I've noticed that several buttons and menus started to have mixed languages. On my case my Windows distribution has pt-BR language, and I've selected en-US for DBeaver, but the vast majority of menus are still labeled on Portuguese and just a few got changed to English.

![image](https://github.com/dbeaver/dbeaver/assets/10911282/b1cc383d-3202-4659-a1ed-f1d6ac3bd2dc)

![image](https://github.com/dbeaver/dbeaver/assets/10911282/92e111c3-ce8c-4808-a515-6d5ca88648af)

### DBeaver Version

23.1.2

### Operating System

Windows 11

**Comment by E1izabeth** [comment] 2023-07-27 11:31
Could you clarify how did you install DBeaver? Have you downloaded the installer from the web site, or you're using portable version, or it's a DBeaver from Microsoft Store?

**Comment by E1izabeth** [comment] 2023-07-27 14:59
It's a known bug, most possible that modifying launch shortcut will help you. See #13450.
Closing as a duplicate of #16187

**Closed as not planned by E1izabeth** 2023-07-27 14:59 UTC
Labels: duplicate, xo:windows

**Comment by evandrosouza89** [comment] 2023-07-27 16:38
I've downloaded the installer from website

**Comment by evandrosouza89** [comment] 2023-07-27 16:41
I could solve my problem by adding "-nl en" in the windows shortcut like this

"C:\Program Files\DBeaver\dbeaver.exe" **-nl en**
