### ISSUE TITLE
temporary database connections

### ISSUE THREAD

**Issue by wumpz** [dbeaver/dbeaver#16447] opened 2022-05-11 05:33 UTC
With older DBeaver versions, I would guess pre version 22 I used this command line string to create **temporary** database connections: 

dbeaver-cli.exe -reuseWorkspace -con "name=<USER>@<server>|driver=PostgreSQL|host=<server>|port=5432|database=<USER>|user=<USER>|password=<PASS>|connect=true"

Temporary means, those connections were not persisted, were gone after a restart of DBeaver. I like this feature, because DBeaver does not become polluted with old, too many configured connections. It clenas itself up in a way.

With the newest release those connections are persisted. How can I prevent this? Is there an additional attribute for the command line I miss?

**Comment by E1izabeth** [comment] 2022-05-11 06:00
Thank you for report. Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/16441

**Closed as completed by E1izabeth** 2022-05-11 06:00 UTC
Labels: duplicate, xf:cli
