### ISSUE TITLE
"select current_timestamp;" in dbeaver show wrong time

### ISSUE THREAD

**Issue by quartoq** [dbeaver/dbeaver#12249] opened 2021-04-26 12:55 UTC
Hi, "select current_timestamp;" in dbeaver show wrong time.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DBeaver Version 21.0.3.202104181339
Release date: April 19, 2021
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PostgreSQL server:
PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1)
PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

PostgreSQL server timezone - 'Europe/Moscow'.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

---------------------------------------------- check results -----------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Assume it is 15:00 now at time zone 'Europe/Moscow'.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

====================== -Duser.timezone=Europe/Moscow ======================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
set timezone = 'UTC';
show timezone;

TimeZone|
-------------------|
UTC     |

select current_timestamp;

current_timestamp  |
-------------------|
2021-04-26 15:00:00| <----------------------------------- must be 12:00:00
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
set timezone = 'Europe/Moscow';
show timezone;

TimeZone     |
-------------------|
Europe/Moscow|

select current_timestamp;

current_timestamp  |
-------------------|
2021-04-26 15:00:00| <------------------------------------------------ true
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

====================== -Duser.timezone=UTC ================================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
set timezone = 'UTC';
show timezone;

TimeZone|
--------|
UTC     |

select current_timestamp;

current_timestamp  |
-------------------|
2021-04-26 12:00:00| <------------------------------------------------ true
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
set timezone = 'Europe/Moscow';
show timezone;

TimeZone     |
-------------------|
Europe/Moscow|

select current_timestamp;

current_timestamp  |
-------------------|
2021-04-26 12:00:00| <----------------------------------- must be 15:00:00
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by uslss** [comment] 2021-04-27 08:03
@quartoq cannot reproduce it against 21.0.3.
What version do you use?

**Comment by quartoq** [comment] 2021-04-27 09:08
@uslss this  version is given in my post
DBeaver Version 21.0.3.202104181339
Release date: April 19, 2021

**Comment by quartoq** [comment] 2021-04-27 16:26
@uslss, we tried to reproduce it on several PCs, it is reproducible

**Comment by uslss** [comment] 2021-06-02 11:49
please, check Disable date/time formatting option in Data formats settings
![image](https://user-images.githubusercontent.com/31996417/120475204-ba783580-c3b1-11eb-9853-240905d66093.png)

**Comment by Matvey16** [comment] 2021-06-03 12:50
Duplicate of #12239

**Closed as completed by Matvey16** 2021-06-03 12:50 UTC
Labels: duplicate

**Comment by quartoq** [comment] 2021-06-08 12:54
> please, check Disable date/time formatting option in Data formats settings
> ![image](https://user-images.githubusercontent.com/31996417/120475204-ba783580-c3b1-11eb-9853-240905d66093.png)
Thanks, it works!
