### ISSUE TITLE
After upgrade to 7.2.2 - [Edited] Cannot dump table

### ISSUE THREAD

**Issue by Xyenia** [dbeaver/dbeaver#9983] opened 2020-10-06 11:33 UTC
#### System information: 
Operating system (distribution) and version: Windows 10
DBeaver version: 7.2.2
Additional extensions: No

#### Connection specification:
Database name and version: MySQL 5
Driver name: MySQL 5
Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
I hope I filled in the details correctly above. I upgraded from DBeaver 7.2.1 to 7.2.2 and there was a problem.  I have been frequently using DBeaver all week with no dumping problems. I encountered the issue explained below. I then rolled back and installed version DBeaver 7.2.1. Everything works perfectly. I can dump tables with no issues.

#### Steps to reproduce, if exist:
The problem? Cannot dump my database locally as backup. Right click on the remote database table inside the UI. Select "Tools > Dump Database". I cannot dump the table.

#### Include any warning/errors/backtraces from the logs
Errors: Got a mysql dump error: 1405. Failed to execute: code 2.

#### [Edit]

I misunderstood the "invalidated" popup up when I refreshed connection. I was actually able to see my database remotely.
I did notice under v7.2.2, my live connection count was 1, but under v7.2.1, it is 2.

I have reinstalled Version 7.2.2 to recreate the dumping error and get screenshots for the issue.
<br/>
For the 1st screenshot below, I tried to dump at the time of 14:55. I checked my export folder. I have the file there, timestamped
at 14:55 but with filesize of 0kb. The .sql file is empty. All my previous dump attempts under v7.2.2 produced .sql files all with a size of 0kb.
<br/><br/>
 
![dump-table-fail](https://user-images.githubusercontent.com/68520136/95214173-88451280-07e7-11eb-99b4-3b1371794d9a.png)
<br/><hr/><br/>
![dump-table-fail02](https://user-images.githubusercontent.com/68520136/95214208-91ce7a80-07e7-11eb-83ec-b4dd017f4cf9.png)
<br/><hr/><br/>
<b>Driver Info (if useful)</b>
<br/>
![connection-test](https://user-images.githubusercontent.com/68520136/95214320-b32f6680-07e7-11eb-951e-055d39aa836a.png)

**Comment by uslss** [comment] 2020-10-07 08:35
Hi @Xyenia ,
unfortunately, cannot reproduce an issue.
It seems, from your screenshot, you have some problems with access.

**Comment by Xyenia** [comment] 2020-10-07 08:38
> Hi @Xyenia ,
> unfortunately, cannot reproduce an issue.
> It seems, from your screenshot, you have some problems with access.

Hi uslss,

Thanks for the reply.

I have not modified any settings. I install 7.2.2 - I cannot dump table. I rollback and install 7.2.1 without doing anything else, I can dump the table. So, I'm not sure what the issue is.

**Comment by uslss** [comment] 2020-10-07 08:40
Could you provide your dump configuration?
It will be helpful to reproduce an issue

**Comment by Xyenia** [comment] 2020-10-07 08:43
Please quickly remind me where to get this information?

**Comment by Xyenia** [comment] 2020-10-07 08:48
![image](https://user-images.githubusercontent.com/68520136/95308755-33a2a580-0882-11eb-8e73-a2c20dee7e9a.png)

**Comment by uslss** [comment] 2020-10-07 09:09
thanks for the clarification and for the bug report.
the issue is reproducible for non-root users.
Note: reproducible on db1, user uslss/uslss

**Comment by iambudi** [comment] 2020-10-09 23:13
This `Access denied` issue happen also on mac osx catalina (10.15.7).  It worked nicely before 7.2.2.

```bash
/usr/local/Cellar/mysql/8.0.21_1/bin/mysqldump --defaults-file=/var/folders/l3/njrjcqxn4x9cp4q044z_th2w0000gp/T/.dbeaver-temp17838210049753763955/my.cnf --single-transaction --add-drop-table --disable-keys --extended-insert --comments --host=localhost --port=3306 mydb test_table
Task 'MySQL dump' started at Sat Oct 10 06:06:59 WIB 2020
mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) when trying to connect

Task 'MySQL dump' finished at Sat Oct 10 06:06:59 WIB 2020
2020-10-10 06:06:59.820 - IO error: Process failed (exit code = 2). See error log.
2020-10-10 06:06:59.821 - java.io.IOException: Process failed (exit code = 2). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:208)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:188)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:248)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by da-anda** [comment] 2020-10-16 14:21
I also came across this issue. Odd thing is, it's working for one DB connection to the same server with also a restricted user but not the other. Both connect via a SSH tunnel.

**Comment by ShadelessFox** [comment] 2020-10-19 11:20
@Xyenia @iambudi @da-anda please note that starting with 7.2.2 external utilities like `mysqldump` are now using credentials set in connection's configuration rather than configuration file (my.cnf and etc.) derived somewhere in the host system. 

Also if you having trouble with LOCK TABLES error, change `Execution Method` in export configuration to `Online backup in single transaction` or grant required permissions for the user.

**Comment by iambudi** [comment] 2020-10-19 12:01
> ...starting with 7.2.2 external utilities like `mysqldump` are now using credentials set in connection's configuration...

I'm not clear about this since i've been using 7.2.2. Can you make it as a series of step i can follow in DBeaver until the sql file generated successfully?

**Comment by ShadelessFox** [comment] 2020-10-19 12:16
> I'm not clear about this since i've been using 7.2.2. Can you make it as a series of step i can follow in DBeaver until the sql file generated successfully?

1. Open `Dump database` dialog and proceed to the final page
2. Set `Execution Method` to `Online backup in single transaction`
3. Make sure in `Security` group there's no overridden credentials, otherwise this may be the reason why authorization fails

**Comment by Xyenia** [comment] 2020-10-19 12:32
I just installed 7.2.3. I still could not dump my remote table. I was about to uninstall and rollback when I did the following.

I went to dump the table, I hit next to get to export configuration dialog.


![authenticate before mysqldump](https://user-images.githubusercontent.com/68520136/96451425-74e66e00-120f-11eb-89bd-00078bed2c4a.png)


I selected the authenticate button (see Image attached) and filled in my remote login credentials for the database and selected "save password".

I was able to dump the table. I checked the output file and it was a non-0kb filesize, i.e. - it dumped the table correctly as an sql file. Things are now working for me.

My quick question is - this "save password" box on the authenticate dialog box - Are my credentials stored safely and encrypted or can they be found somewhere in a config file?

**Comment by Xyenia** [comment] 2020-10-19 12:48
Just had a look around my system and in the DBeaver subfolder of AppData folder, I seem to have a credentials config JSON file
created today. So, it looks like my credentials are stored safely.

**Comment by ShadelessFox** [comment] 2020-10-19 12:58
I'm glad you was able to solve the issue. Also thank you for very verbose explanation for the others.

Do you still have any questions left?

**Comment by Xyenia** [comment] 2020-10-19 13:00
No, thanks. I just wanted to comment with my findings to help others, Thanks for your assistance.

**Comment by iambudi** [comment] 2020-10-19 14:07
> I'm talking about `Authentication` group in connection's configuration. Native tools will use these credentials.
> 
> 1. Open `Dump database` dialog and proceed to the final page
> 2. Set `Execution Method` to `Online backup in single transaction`
> 3. Make sure in `Security` group there's no overridden credentials, otherwise this may be the reason why authorization fails

@Xyenia I tried both with and without overriden credentials before (reset to default). No luck, same empty sql file.

![image](https://user-images.githubusercontent.com/31809529/96461247-58b5f180-124e-11eb-849f-1c5ea6fc0521.png)

**Comment by Xyenia** [comment] 2020-10-19 14:14
I see you are doing this locally on your system. Most people do not set a password for local phpMyAdmin access.

Have you set a password for this? If not, try leaving password box empty.

**Comment by iambudi** [comment] 2020-10-19 14:18
@Xyenia Yes i set password for mysql locally.

**Comment by iambudi** [comment] 2020-10-19 14:20
Cli dump works nicely with password `mysqldump -u root -p -h localhost mydb > mydb-dump.sql`.
So it should work as well with DBeaver.

**Comment by Xyenia** [comment] 2020-10-19 14:23
Have you updated to 7.2.3? Is there an update for your OS?

**Comment by iambudi** [comment] 2020-10-20 00:46
@Xyenia I just upgraded to 7.2.3. It's still does not work on MacOS.

**Comment by da-anda** [comment] 2020-10-20 05:29
I have nothing configured in my.cnf and also had tried providing/overriding the credentials in the export dialog - nothing worked for me besides downgrading to 7.2.1. The odd thing is, I have a second connection to the same server but to a different DB (different DB credentials), and that one is working fine. Both of my connections require a SSH tunnel with the same credentials.

**Comment by KrzysiuJarzyna** [comment] 2020-10-20 08:51
Same problem here. Since update to 7.2.2 (and now in 7.2.3 as well) i can not dump my databeses due to "Access denied" error.
It looks like DBeaver do not transmits credentials to mysqldump.

1. I have credentials set in connection tab:
![Screenshot from 2020-10-20 10-44-54](https://user-images.githubusercontent.com/4620162/96563134-e54dc780-12c1-11eb-94ce-4dbf9ddffeb1.png)

2. I have trie to pass it during dump:
![Screenshot from 2020-10-20 10-45-10](https://user-images.githubusercontent.com/4620162/96563165-ec74d580-12c1-11eb-92b8-c94c3e857313.png)

But still have the error with wrong credentials (**in the error i can see other user than specified ealrier**):
![Screenshot from 2020-10-20 10-45-19](https://user-images.githubusercontent.com/4620162/96563180-f0a0f300-12c1-11eb-9cd0-c9a977e761e8.png)

The error occurs in local databases as well with servers connected via ssh.

**Comment by kseniiaguzeeva** [comment] 2020-10-20 08:52
The fix will be included in 7.2.4 release

**Comment by uslss** [comment] 2020-10-28 11:44
fix could be checked in EA version https://dbeaver.io/files/ea

**Comment by kseniiaguzeeva** [comment] 2020-10-30 11:37
verified

**Closed by kseniiaguzeeva** 2020-10-30 11:37 UTC
Labels: bug, xf:datatransfer
