### ISSUE TITLE
Pictures zoom on the Value panel doesn't work on macOS and Linux

### ISSUE THREAD

**Issue by Essentia-G** [dbeaver/dbeaver#19227] opened 2023-03-01 14:09 UTC
### Description

I tried to zoom in / zoom out pictures on the Value panel using mouse (and shortcuts CMD + + и CMD + - as well). The same situation is on Linux.
Seems like we have a bug, and for now this feature works only on Windows. 

### DBeaver Version

Ultimate Edition 22.3.0

**Comment by arhayka** [comment] 2023-03-01 14:34
This seems to be the same case as #19204

**Comment by flambchap** [comment] 2023-03-01 15:14
Yes, it's a duplicate of https://github.com/dbeaver/dbeaver/issues/19204.

**Closed as not planned** 2023-03-01 15:14 UTC
Labels: duplicate, xo:linux, xo:macos, xf:ui
