### ISSUE TITLE
Auto-update on MacOS

### ISSUE THREAD

**Issue by PatrickColborne** [dbeaver/dbeaver#11055] opened 2021-01-20 07:06 UTC
**Is your feature request related to a problem? Please describe.**
It is extremely frustrating that DBeaver requires you to uninstall the old version of DBeaver and then re-install the new updated version of DBeaver in MacOS. Everytime there is an update I get an annoying window asking me to upgrade. When click upgrade it installs an entire new instance of DBeaver. Not only are the notifications irritating but the new installation does not overwrite the old installation.

**Describe the solution you'd like**
 Pleeeeeeasee may you create an installer for DBeaver on MacOS that deletes the old version of DBeaver upon installing an updated version. What would be even better is if DBeaver could update itself instead of showing requesting the user to do it manually.

**Comment by uslss** [comment] 2021-01-20 08:05
thanks for suggestion
closed as a duplicate of #6558

**Closed as completed by uslss** 2021-01-20 08:05 UTC
Labels: duplicate
