### ISSUE TITLE
After the last update, an error with local database appeared

### ISSUE THREAD

**Issue by kleyber-ribeiro** [dbeaver/dbeaver#6605] opened 2019-08-23 13:11 UTC
#### System information: 
- Windows 10 64 bits
- DBeaver 6.1.5

#### Connection specification:
- Database name and version: Mysql 5.6
- Driver name: 
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
After this new update (6.1.5) this message appears when I try to use my local database:
"The server time zone value 'Hora Padr�o de Buenos Aires' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support."

#### Steps to reproduce, if exist:
Just trying to connect my local database

**Comment by serge-rider** [comment] 2019-08-24 13:59
Duplicate of #6553
This bug was fixed in 6.1.5 hotfix version. 
You can just re-download 6.1.5.

**Closed by serge-rider** 2019-08-24 13:59 UTC
Labels: bug, duplicate, x:mysql
