### ISSUE TITLE
Improve Dark Theme

### ISSUE THREAD

**Issue by lewis1277** [dbeaver/dbeaver#18279] opened 2022-11-21 11:49 UTC
**Is your feature request related to a problem? Please describe.**
The current dark theme is good, but lacking in various areas, resulting in an ugly look when using it compared to the default light mode. Areas like the context menu being white, the scrollbars being white and the colour of text being black in contrast to the current theme are frustrating.

**Describe the solution you'd like**
At current I don't believe these elements are customizable in the theming feature, therefore they are stuck with the default light theme colours. It would be great if they were added to make the dark theme more consistent.

**Additional context**
Below listed are the various areas of dbeaver contrasting with dark theme:
![image](https://user-images.githubusercontent.com/76098413/203042290-eadc67d2-4b10-400a-ad3b-b30ef2a988f8.png)
(above) white context menu

![image](https://user-images.githubusercontent.com/76098413/203042511-c7c84744-98e7-4761-98af-93cae6787c26.png)
(above) white scrollbars

![image](https://user-images.githubusercontent.com/76098413/203043795-000b0563-0bcf-43ed-aa31-ab85877824c5.png)
![image](https://user-images.githubusercontent.com/76098413/203042586-37448a29-fe83-4d27-af86-cdd8743488ab.png)
(above) white window frame/toolbar

![image](https://user-images.githubusercontent.com/76098413/203042662-b24804f2-95a5-42fc-b518-d09143b0a3c0.png)
(above) white border in database navigator search bar

![image](https://user-images.githubusercontent.com/76098413/203042790-038e1487-d36d-434c-8bcd-73cd51383a45.png)
(above) white border in table data tabs

![image](https://user-images.githubusercontent.com/76098413/203042877-baeb55cd-d86e-4f95-8eac-580da464f063.png)
(above) white borders in table properties tabs

![image](https://user-images.githubusercontent.com/76098413/203043213-99699300-0c53-4ecb-9c0e-32fce0c67fc1.png)
![image](https://user-images.githubusercontent.com/76098413/203043620-fe1451df-47b5-4854-b3ed-1800ef8fe97f.png)
(above) selected text colour (applies all across the app, text shown as black)

**Comment by hozdenoren** [comment] 2022-11-21 12:38
Related to #17787

**Comment by ShadelessFox** [comment] 2022-11-22 00:10
Hello @lewis1277,

White components are mostly native ones, so they match the OS theme. Are you using the dark theme in your OS?

**Comment by lewis1277** [comment] 2022-11-22 00:12
> Hello @lewis1277,
> 
> White components are mostly native ones, so they match the OS theme. Are you using the dark theme in your OS?

yes, for Windows 11 (Update 22H2)
my issue is most likely related to the one quoted by @hozdenoren above

**Comment by ShadelessFox** [comment] 2022-11-22 00:15
I see. Thanks for providing extra information.

Indeed, it looks like the same issue, and I will close this one as a duplicate then.

Duplicate of https://github.com/dbeaver/dbeaver/issues/17787

**Closed as not planned by ShadelessFox** 2022-11-22 00:15 UTC
Labels: duplicate, xo:windows, xf:dark theme, xf:ui
