### ISSUE TITLE
Countless issues after upgrading from (very) old version #2 - Saving scripts

### ISSUE THREAD

**Issue by GreatEMU** [dbeaver/dbeaver#15199] opened 2022-01-17 14:59 UTC
Because of problems on an older version I skipped upgrading for many years. Now after upgrading to the current version I can't count the issues anymore. What happend to this usefull tool?

This is issue #2:
I created a new script a assigned a database.
After saving the script the assigned database and catalog are vanished.

#### System information: 
- Operating system: Win 10
- DBeaver: 21.3.2
- Additional extensions

#### Connection specification:
- Database name: DB2 iSeries
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment] 2022-01-19 09:30
seems the issue is related to the incorrect installation of the new version.
will be investigated in the scope of #15198

**Closed as completed by uslss** 2022-01-19 09:30 UTC
Labels: can't reproduce, duplicate
