### ISSUE TITLE
date=CURRENT_DATE filter lost on restart despite saving

### ISSUE THREAD

**Issue by ffalcon31415** [dbeaver/dbeaver#15322] opened 2022-01-28 02:03 UTC
#### System information: 
- Windows 10 Professional x64 - CCW1064V64
- DBeaver version 21.3.1.2021122130652
- Additional extensions: none

#### Connection specification:
- Database name and version: sqlite3

#### Describe the problem you're observing:
I use dBeaver to work on a sqlite3 database with a single table called bailPositions.
I want the bailPositions table to always open with a filter on the date field, date=CURRENT_DATE.
Other column settings persist across sessions, but not the filter on the date field.

I'm aware of issue #4166, but this is different because all my column settings (order, formatting, pinning, etc.) are being preserved, just not the filter.

#### Steps to reproduce, if exist:
I input that filter in the filter box like so:

![image](https://user-images.githubusercontent.com/77492177/151473213-0dcd9c2f-5b77-496a-9a5a-809a50f2792a.png)

It filters the table properly. Then I click "Save filter settings", and a notification says "data filter was saved".

But when I close out then open dBeaver again, the table is not filtered by date=CURRENT_DATE (and no filter in the filter box).

My saved-data-filter.xml _does_ show the filter:
`<filter objectId="positions.sqlite3@@/@@bailPositions" anyConstraint="false" where="date=CURRENT_DATE">`

#### Include any warning/errors/backtraces from the logs

This is the only message in the logs that reads like maybe an error:
`!MESSAGE Column '"pkNumber" AUTOINCREMENT' not found in table 'bailPositions' for PK 'bailPositions.BAILPOSITIONS_PK'`

pkNumber is a field in my table that autoincrements. Everything in the table works fine so I don't know what this means.

**Comment by uslss** [comment] 2022-01-31 12:47
@ffalcon31415 thanks for the report.
Unfortunately, I cannot reproduce it. Could you provide table DDL?

**Comment by ffalcon31415** [comment] 2022-01-31 13:56
Thanks for reviewing this. 

      CREATE TABLE "bailPositions" (
      "name" TEXT NOT NULL,
      "disclosure" TEXT,
      "ready" INTEGER DEFAULT 0,
      "bailBriefReady" INTEGER DEFAULT 0,
      "scopeNumber" TEXT,
      "date" TEXT DEFAULT CURRENT_DATE,
      "charges" TEXT,
      "onus" TEXT,
      "record" TEXT,
      "outstanding" TEXT,
      "releases" TEXT,
      "grounds" TEXT,
      "orders" TEXT,
      "position" TEXT,
      "524" INTEGER DEFAULT 0,
      "notes" TEXT,
      "flag" TEXT DEFAULT 'Arrest date and time: ',
      "pkNumber" INTEGER NOT NULL UNIQUE,
      "bailBrief" TEXT,
      "scopeId" TEXT,
      "uploaded" INTEGER DEFAULT 0,
      "dcNotified" INTEGER DEFAULT 0,
      "bailBriefSent" INTEGER DEFAULT 0,
      "dob" TEXT,
      "lastname" TEXT,
      "firstname" TEXT,
      "bail524brief" TEXT,
      PRIMARY KEY("pkNumber" AUTOINCREMENT)
      );

**Comment by uslss** [comment] 2022-01-31 14:48
Thanks for the clarification.
The issue will be fixed in future milestone

**Closed as completed** 2022-04-27 10:56 UTC
Labels: xf:data, sp:1
