### ISSUE TITLE
custom folding with --region

### ISSUE THREAD

**Issue by 4dd4m** [dbeaver/dbeaver#36190] opened 2024-11-07 13:51 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I work with a big file. Folding everything manually is a pain.

**Describe the solution you'd like**
Support --region and --endregion like VS Studio does, to make a custom folding between this area:

![image](https://github.com/user-attachments/assets/b9e23421-2872-4d94-8ffb-7d247d204b1f)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by E1izabeth** [comment] 2024-11-13 14:25
Thanks for the idea.
I'm closing this issue as a duplicate of #23137
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.

**Closed as not planned by E1izabeth** 2024-11-13 14:25 UTC
Labels: duplicate, xf:sql editor
