### ISSUE TITLE
Add ability to auto-format json-like strings

### ISSUE THREAD

**Issue by wvolkov** [dbeaver/dbeaver#8378] opened 2020-04-08 12:49 UTC
Current version of dbeaver auto format in value viewer panel only json / jsonb values for postgres db. Sometimes jsons are stored like strings and currently it necessary to cast type from string to jsonb in order to see auto formatted result in the value panel. It would be great if dbeaver could auto format strings that is actually jsonbs. Thanks

**Comment by uslss** [comment] 2020-04-08 14:13
seems to be duplicate of #7994 .
anyway, thanks for suggestion

**Closed by uslss** 2020-04-08 14:13 UTC
Labels: duplicate, feature request
