### ISSUE TITLE
Crash when reading a table

### ISSUE THREAD

**Issue by ncastrog** [dbeaver/dbeaver#17958] opened 2022-10-18 17:51 UTC
### Description

When opening a 3.8 GB table with 6 columns on data tab, dbeaver crashes, 
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/9813781/dbeaver.log)

### DBeaver Version

Version 22.2.2.202210092258

### Operating System

macOS Monterrey 12.6

### Database and driver

Postgresql 14.4 and 14.5.
JDBC Driver 42.2.20

### Steps to reproduce

Opening data tab, table size, 3.8 GB, 7 columns

index   |DATE      |ID                                                                             |EMPLOYEE|TIME|TRIGGER                                     |EXTERNAL                                                                 |
--------+----------+-------------------------------------------------------------------------------+--------+----+--------------------------------------------+-------------------------------------------------------------------------+
13890387|2020-12-14|AAQkAGM4NTFjYzcxLTEzMzItNGQ1MS1hODhiLWU3MDQ2MDAzOTdjNAAQAIw2tAD2i0CfpAvnewMb-C0|E153    |   2|Outlook: Read Email | True | normal | False |                                                                         |

**Comment by E1izabeth** [comment] 2022-10-18 17:53
Could you try this workaround https://github.com/dbeaver/dbeaver/issues/17865#issuecomment-1273928373 ?
Please, let me know if it helps.

**Comment by ncastrog** [comment] 2022-10-18 20:17
Thanks works as usual now.

**Comment by E1izabeth** [comment] 2022-10-18 20:19
The fix will be available in the next release. I'll close this issue as a duplicate of #17865

**Closed as not planned** 2022-10-18 20:19 UTC
Labels: x:postgresql, duplicate, xf:data, performance
