### ISSUE TITLE
Postgres Data Types

### ISSUE THREAD

**Issue by aschoijett** [dbeaver/dbeaver#34938] opened 2024-07-22 15:33 UTC
Hi, 
I noticed that DBeaver does not support the creation/edition of Postgres Data Types.   Is there any plan to support that functionality in the future? 
TBH, at this point I only care for ENUMs, but I imagine that you may want to have this functionality for all data types.  

During the database design, it's rather annoying to have to go back and forth with pgAdmin to do the work.   (I'm very new at Postgres, so I'm not familiar with the command lines yet.)

**Describe the solution you'd like**
In an ideal world, when creating the ENUM options, one should be able to add options, rename them, delete them, and very importantly, reorganizing them (because comparisons are done on a position basis)

**Describe alternatives you've considered**
As said, I used pgAdmin to generate the enums.  pgAdmin is very inflexible and does not let you massage the enum once created. 
So, what I do is to look at the DDL produced by pgAdmin, copy it, and past it on a DBeaver SQL editor, where I drop the enum, edit it, and save it.   It's a bit cumbersome, because I have to redo the columns and the functions that use the enum, though.

Many thanks in advance and thank you for a great product!!

Alex

**Comment by E1izabeth** [comment] 2024-07-23 10:57
Thank you for idea.

**Comment by E1izabeth** [comment] 2024-07-23 10:58
Probably, connected with #72

**Comment by LonwoLonwo** [comment] 2024-07-24 06:13
Hello @aschoijett 

I found a duplicate of your ticket at https://github.com/dbeaver/dbeaver/issues/3936 (also #72), so I will close your ticket as a duplicate.
You can subscribe and vote for the original ticket.
Thanks for the request.

**Closed as completed by LonwoLonwo** 2024-07-24 06:13 UTC
Labels: x:postgresql, duplicate, xf:metadata, xf:ui
