### ISSUE TITLE
Display Arrays of complex data types (Postgres only?) in Value section as table

### ISSUE THREAD

**Issue by Karlodun** [dbeaver/dbeaver#15801] opened 2022-03-10 22:50 UTC
We're using Postgres 13, soon upgrading to 14.
Right now we're using JSONB to store arrays of small objects. While querying JSONB is OK, using arrays of complex data types has some clear advantages (type safety and predefined attributes).

The issue in our case is that the natural key is quite big, and the arrays of complex data types are so small (few columns and normally just a couple of lines, normally 1-3) that it literally makes no sense to "outsource" them into dedicated tables.

Querying the data is a bit tricky right now, since I have either to unnest the arrays or call them by number. Its simple enough to stick to it, but I'd love DBeaver to handle it a bit better.

The "Record" view is already perfect.

However "Grid" view shows only one row and you can only see / edit the values in "value" of this single column.
I'd expect a simple text view in table cell (see bellow) or some icon for complex data type. And a table view in value. A double click on the cell with such sub-table could open an extra editor.

Example:

CREATE TYPE cbm.gcr AS (
  pin geometry(Point, 4326),
  osm_type varchar,
  osm_id bigint,
  addr jsonb
);

ALTER TABLE cbm.gc_res ADD COLUMN gcr cbm.gcr[];

INSERT INTO cbm.gc_res (relation_path, gcr)
  VALUES ('gcr_testdrive'
, ARRAY[(40.7561342, -73.9982421,'node',2709493895,'{
      "city": "New York",
      "road": "10th Avenue",
      "state": "New York",
      "county": "New York County",
      "suburb": "Manhattan",
      "country": "Vereinigte Staaten von Amerika",
      "postcode": 10018,
      "country_code": "us",
      "house_number": 475,
      "neighbourhood": "Hudson Yards"
    }')::cbm.gcr,(40.7561342, -73.9982421,'node',2709493895,'{
      "city": "New York",
      "road": "10th Avenue",
      "state": "New York",
      "county": "New York County",
      "suburb": "Manhattan",
      "country": "Vereinigte Staaten von Amerika",
      "postcode": 10018,
      "country_code": "us",
      "house_number": 475,
      "neighbourhood": "Hudson Yards"
    }')::cbm.gcr]
  );

![Record view](https://user-images.githubusercontent.com/11210115/157768119-90b8db97-6183-4bbf-b620-7b073c42a4f9.png)
![Grid view](https://user-images.githubusercontent.com/11210115/157768122-c8ac04fe-9293-4144-8e0a-1ca8a41d562d.png)

**Comment by Karlodun** [comment] 2022-03-15 00:31
License ID: DB-381MQZ8P-Z91W (Hopefully my company will purchase additional licences soon)

**Comment by ShadelessFox** [comment] 2022-03-16 13:44
Hello @Karlodun,

Is your request the same as described in #12148?

**Comment by Karlodun** [comment] 2022-03-16 20:56
Yes! The descriptions differ too much, so I couldn't identify it. But yes, this is exactly the same issue.
How should we proceed with this topic? Close? Relink?

**Comment by ShadelessFox** [comment] 2022-03-17 00:48
I have renamed the mentioned issue a bit, so it now sounds more general.

Yes, I will leave a link and close this issue as a duplicate.

That doesn't mean we will not fulfill your initial request. We refer to all linked issues to be sure that we didn't miss anything.

**Comment by ShadelessFox** [comment] 2022-03-17 00:49
Duplicate of #12148

**Closed as completed by ShadelessFox** 2022-03-17 00:49 UTC
Labels: duplicate, xf:data, AS
