### ISSUE TITLE
DBeaver shut down on a query

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#11958] opened 2021-04-01 12:17 UTC
DBeaver 21.0.1
Postgresql 12

This SQL query to any column with string type leads to crash DBeaver

![изображение](https://user-images.githubusercontent.com/61137576/113292526-110fb780-930e-11eb-9ee8-a8b6b804d9b8.png)

**Comment by detkliff** [comment] 2021-04-01 12:17
no problem with this query in another ide

**Comment by ShadelessFox** [comment] 2021-04-01 14:32
Hello @detkliff,

Can you please post this query as plain text?

Looks like a bug in @JSQLParser library.

**Comment by detkliff** [comment] 2021-04-02 04:26
SELECT unnest(regexp_split_to_array(trim( 
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			replace(
			thav.value, 
			' ==', ' = '),
			'>', ' > '),
			'<', ' < '),
			'>=', ' >= '),
			'<=', ' <= '),
			'+', ' + '),
			'-', ' - '),
			'/', ' / '),
			'*', ' * '),
			'(', ' ( '),
			')', ' ) '),
			'if', ' ЕСЛИ '),
			'then', ' ТО '),
			'else', ' ИНАЧЕ '),
			'!==', ' != '),
			'min', ' min '),
			'max', ' max '),
			'||', ' ИЛИ '),
			'&&', ' И '),
			'prev_period_formula', ' Пред.период '),
			'null', ' Пусто ')),
			E'\\s+')
			) val, 
			thav.top_h_id,
			ta.template_id,
			case when thav.header_attr_id = 24 then 1
			else 2
			end as ftype
		FROM form.top_h thav

**Comment by detkliff** [comment] 2021-04-02 06:25
when trying to just make edits to the query, DBeaver freeze
with this procedure
![изображение](https://user-images.githubusercontent.com/61137576/113387605-102a6480-93a6-11eb-8513-5c3ec27d430b.png)

**Comment by ShadelessFox** [comment] 2021-04-02 08:29
Thanks for the feedback.

Unfortunately, that's indeed the third-party issue.

**Comment by detkliff** [comment] 2021-05-05 10:51
very sadly

**Comment by serge-rider** [comment] 2021-05-05 12:50
The problem is in JSQLParser library.
Actually it is a duplicate of #10704
Hopefully will be fixed in the new version of https://github.com/JSQLParser/JSqlParser

**Closed as completed by serge-rider** 2021-05-05 12:50 UTC
Labels: duplicate, third party issue
