### ISSUE TITLE
Autocommit with smart commit is changed to manual commit after non-SELECT statement

### ISSUE THREAD

**Issue by ahill-qim** [dbeaver/dbeaver#34471] opened 2024-06-25 20:59 UTC
### Description

Basically what the title says - when using autocommit with smart commit, the setting is changed to manual commit (with smart commit still checked) after executing a non-SELECT statement.

Existing, preferred setting:
![image](https://github.com/dbeaver/dbeaver/assets/114944838/ed9399df-5c49-4560-b11f-adc8ec429be7)

After executing a DELETE (followed by a rollback, but the same happens with commit as well):
![image](https://github.com/dbeaver/dbeaver/assets/114944838/8fbff1c6-ff7b-45d0-9f13-c4f0f9f7e5c2)

### DBeaver Version

Community Edition 24.1.1

### Operating System

Windows 10 -- 10.0.19045 Build 19045

### Database and driver

MariaDB 10.11 and 10.3, JDBC 3.3.2

**Comment by E1izabeth** [comment] 2024-06-26 08:33
Thank you for report. It's a duplicate of #22313

**Closed as not planned by E1izabeth** 2024-06-26 08:33 UTC
Labels: duplicate, xf:sql execution
