### ISSUE TITLE
This issue after DBeaver 24.2.

### ISSUE THREAD

**Issue by NunoOliveira03** [dbeaver/dbeaver#35444] opened 2024-09-03 08:32 UTC
### Description

The dump database Maria dont work to restore database after. 

### DBeaver Version

24.2

### Operating System

Windows 10

### Database and driver

Maria DB

**Comment by df-romain-francois** [comment] 2024-09-03 11:53
https://github.com/dbeaver/dbeaver/issues/35428

**Comment by E1izabeth** [comment] 2024-09-03 13:31
Thanks for the bug report.
This is a duplicate of #35421. Please track the progress on the issue there.

**Closed as not planned by E1izabeth** 2024-09-03 13:31 UTC
Labels: x:mysql, duplicate, xf:native clients
