### ISSUE TITLE
Unable to run new editor in a specific project from git

### ISSUE THREAD

**Issue by wvolkov** [dbeaver/dbeaver#6358] opened 2019-07-27 06:36 UTC
#### System information: 
- Windows 10 1903
- CE 6.1.3
- Built-in JRE with installer  
- Git Integration

#### Describe the problem you're observing:
After I transfer my project to gitlab on my work PC it impossible to run new editor, after ctrl+] or selecting new editor button nothing happens and the error occured (further in message).

#### Steps to reproduce, if exist:
1. Clean Install of DBeaver
2. Installing Git Extension
3. Pulling project from gitlab repository
4. Trying to create new script

In the meantime, other projects are working fine. Cleaning cache, xsi file and complete reinstall didn't helped.

#### Include any warning/errors/backtraces from the logs
org.eclipse.core.commands.ExecutionException: Error executing 'org.jkiss.dbeaver.core.sql.editor.create': java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:238)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 32 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at org.jkiss.dbeaver.registry.ProjectMetadata.loadMetadata(ProjectMetadata.java:230)
	at org.jkiss.dbeaver.registry.ProjectMetadata.setResourceProperty(ProjectMetadata.java:190)
	at org.jkiss.dbeaver.ui.editors.EditorUtils.setFileDataSource(EditorUtils.java:223)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorUtils.createNewScript(SQLEditorUtils.java:227)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.OpenHandler.openNewEditor(OpenHandler.java:137)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.OpenHandler.openNewEditor(OpenHandler.java:162)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.OpenHandler.execute(OpenHandler.java:96)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 36 more

**Comment by serge-rider** [comment] 2019-07-27 16:00
Thanks for the bug report.
This seems to be the same problem as in #6321 but now e have a stacktrace which is very helpful.
The problem is in corrupted `project-metadata.json` file. Is is json and I still can't realize how can it be corrupted. 
By default it is file  %APPDATA%\DBeaverData\workspace6\General\.dbeaver\project-metadata.json 
Could you send it to me (serge@jkiss.org or just attach here)? It doesn't contain any valuable user data, only project script names and connection ids.
Thank you.

**Comment by wvolkov** [comment] 2019-07-28 06:53
@serge-rider , Thank you for quick response. Mentioned file in attachment.
[project-metadata.zip](https://github.com/dbeaver/dbeaver/files/3438903/project-metadata.zip)

**Comment by wvolkov** [comment] 2019-07-28 06:59
Also when I try to create a new script at scripts folder of a project - it creates a file, but is unable to open the editor window itself:
![image](https://user-images.githubusercontent.com/49549154/62003340-731e1f80-b11e-11e9-8209-f27b9886ebb2.png)

**Comment by serge-rider** [comment] 2019-07-28 09:11
Thank you for testing this.

I've pushed the fix and new Early Access version is ready (https://dbeaver.io/files/ea). 
Please test does it fixes the problem with scripts.
If not please check error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by wvolkov** [comment] 2019-07-29 06:17
@serge-rider, version 6.1.4 fixed that issue, thank you. But After I've installed 6/1/4 over the 6/1/3 the git extension for dbeaver disappeared and I installed it again (but all the configs remained)

**Comment by serge-rider** [comment] 2019-08-02 10:08
@wvolkov Thanks for the info.
Yes, unfortunately you need to install all extensions again after version upgrade. We are working on this problem as well.

**Closed by serge-rider** 2019-08-02 10:08 UTC
Labels: bug
