### ISSUE TITLE
Map is empty for specific points

### ISSUE THREAD

**Issue by Wroud** [dbeaver/dbeaver#11763] opened 2021-03-17 12:47 UTC
![image](https://user-images.githubusercontent.com/811729/111469513-d74c8780-8737-11eb-94d8-5ecf8e911cd3.png)

If I select some points wich one of them is `POINT (766456911 13.5639657)` empty map is displayed

**Comment by ShadelessFox** [comment] 2021-03-17 12:50
Looks like a duplicate of #11021 :)

**Closed as completed by ShadelessFox** 2021-03-17 12:50 UTC
