### ISSUE TITLE
do not open big table

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#17891] opened 2022-10-12 08:30 UTC
### Description

![image](https://user-images.githubusercontent.com/61137576/195290781-081fb4ea-35d0-423b-bc0b-f0dadbd27811.png)

### DBeaver Version

22.2.2

### Operating System

windows 11 64bit

### Database and driver

Postgresql 12.8

### Steps to reproduce

1. Create table with data with size 600Mb +
2. Click on table in object tree
3. Bbeaver show message with Fetch table data, local processor download for 100%, local RAM up to 2-3Gb and computer is freezes and computer  does not answer.

Version 21.3.0 have no this problem.

**Comment by jurekbal** [comment] 2022-10-12 09:05
I confirm this problem with version 22.2.2.202210092258.
Error when fetching table data. After a few minutes of fetching:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
...
Caused by: java.lang.OutOfMemoryError: Java heap space
Postgresql 12.11, Win 11, 64bit

**Comment by Schtailian** [comment] 2022-10-12 09:06
Can confirm, for me it also happens with big postgres tables.
No problem with a big oracle Table.

Drivers are all up-to-date.

When Downgrading do DBeaver 22.2.1 this problem does not exist.

**Comment by LonwoLonwo** [comment] 2022-10-12 09:06
Hello. Thanks for the bug report.

You can read more about this problem here (with a workaround): https://github.com/dbeaver/dbeaver/issues/17865

I'm closing this ticket as a duplicate.

**Closed as not planned by LonwoLonwo** 2022-10-12 09:06 UTC
Labels: x:postgresql, duplicate
