### ISSUE TITLE
SSH tunnel auth fail

### ISSUE THREAD

**Issue by konstantin-klima** [dbeaver/dbeaver#3284] opened 2018-04-08 00:23 UTC
Hey there!

I've got a problem with SSH tunneling with public RSA key auth.
If I establish SSH through shell
`ssh IP -l user -p 2247 -L 3307:localhost:3306` 
DBeaver connects to DB normally.

This is a real drag for me, so I decided to try out the tunnel through DBeaver.
I've set everything up,  but on testing connection or trying to connect I get a password prompt.
If I leave it blank like you suggested at other Auth threads (w/ or without Save Password), I get: 

> Can't initialize tunnel
  Cannot establish tunnel
    Auth fail
    Auth fail

I'm using DBeaver 5.0.2 on ubuntu 17.10.

edit:
from the DBeaver debug:
2018-04-08 02:38:22.789 - SSH INFO: ssh_rsa_verify: signature true
2018-04-08 02:38:22.791 - SSH INFO: Host is IP known and matches the RSA host key
2018-04-08 02:38:22.794 - SSH INFO: SSH_MSG_NEWKEYS sent
2018-04-08 02:38:22.795 - SSH INFO: SSH_MSG_NEWKEYS received
2018-04-08 02:38:22.799 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2018-04-08 02:38:22.832 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2018-04-08 02:38:22.876 - SSH INFO: Authentications that can continue: publickey
2018-04-08 02:38:22.884 - SSH INFO: Next authentication method: publickey
2018-04-08 02:38:23.168 - SSH INFO: Disconnecting from IP
2018-04-08 02:38:23.177 - Connection failed (mysql5-162a2b08d7b-1d679e479ada54e)

**Comment by serge-rider** [comment] 2018-04-09 11:52
Can't reproduce. Perhaps the problem is in RSA key itelf.
Could you try SSHJ tunnel implementation? (https://github.com/dbeaver/dbeaver/wiki/Optional-extensions#advanced-ssh-tunnel-libraries)

**Comment by konstantin-klima** [comment] 2018-04-09 16:25
I tried with SSHJ, but I get Host unreachable (when I switch back to JSch I get Auth fail instead).

From the debug:
2018-04-09 18:23:16.752 - Connect with 'MySQL - localhost' (mysql5-161f0accbb1-7dfd396a37b5f901)
2018-04-09 18:23:17.025 - Connection failed (mysql5-161f0accbb1-7dfd396a37b5f901)
2018-04-09 18:23:17.080 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:740)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.jkiss.dbeaver.DBException: Cannot establish tunnel
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:88)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:125)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:61)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:738)
	... 3 more
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:126)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:117)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:67)
	... 6 more

**Comment by serge-rider** [comment] 2018-04-10 19:53
Weird. No ideas so far.
Could you provide a bit more information about your server/key? This must be not so standard config because usually everything works fine.
You could send more info on serge@jkiss.org.

**Comment by koreymacdougall** [comment] 2018-04-11 19:58
I'm hacing what I think is the same issue.  Running the DB on Mac OSX, and client machine running Parabola GNU/Linux.  DB adaptor is mariaDB.

**Comment by serge-rider** [comment] 2018-04-12 21:02
Please post full debug log - starting from `Connect with '...'` line and till the end of log. 
Just cut any private info (IP) from it.

Looks like something is wrong with auth. I can reproduce such issues only with wrong user name/ip.

**Comment by koreymacdougall** [comment] 2018-05-08 15:05
I am having the same issue using SSH with a password login.  I can login with the same credentials via a terminal or through a different GUI, so I don't think it is a database configuration issue.

**Comment by shawinder** [comment] 2019-03-21 16:21
> 
> 
> Hey there!
> 
> I've got a problem with SSH tunneling with public RSA key auth.
> If I establish SSH through shell
> `ssh IP -l user -p 2247 -L 3307:localhost:3306`
> DBeaver connects to DB normally.
> 
> This is a real drag for me, so I decided to try out the tunnel through DBeaver.
> I've set everything up, but on testing connection or trying to connect I get a password prompt.
> If I leave it blank like you suggested at other Auth threads (w/ or without Save Password), I get:
> 
> > Can't initialize tunnel
> > Cannot establish tunnel
> > Auth fail
> > Auth fail
> 
> I'm using DBeaver 5.0.2 on ubuntu 17.10.
> 
> edit:
> from the DBeaver debug:
> 2018-04-08 02:38:22.789 - SSH INFO: ssh_rsa_verify: signature true
> 2018-04-08 02:38:22.791 - SSH INFO: Host is IP known and matches the RSA host key
> 2018-04-08 02:38:22.794 - SSH INFO: SSH_MSG_NEWKEYS sent
> 2018-04-08 02:38:22.795 - SSH INFO: SSH_MSG_NEWKEYS received
> 2018-04-08 02:38:22.799 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
> 2018-04-08 02:38:22.832 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
> 2018-04-08 02:38:22.876 - SSH INFO: Authentications that can continue: publickey
> 2018-04-08 02:38:22.884 - SSH INFO: Next authentication method: publickey
> 2018-04-08 02:38:23.168 - SSH INFO: Disconnecting from IP
> 2018-04-08 02:38:23.177 - Connection failed (mysql5-162a2b08d7b-1d679e479ada54e)

I had a similar issue with locally generated `RSA key` and Dbeaver was showing `Invalid key`. Then I converted `RSA` to `PPK` and it works like a charm!

**Comment by klimov-gett** [comment] 2019-03-25 15:46
> I had a similar issue with locally generated `RSA key` and Dbeaver was showing `Invalid key`. Then I converted `RSA` to `PPK` and it works like a charm!

same here, although in my case @serge-rider 's advice helped - sshj worked even with locally generated rsa key.

@serge-rider any chances sshj is becoming the default implementation used in Dbeaver? Thanks!

**Comment by serge-rider** [comment] 2019-03-25 15:52
@klimov-gett I hope so. Currently it is not included because of bug size of BouncyCastle package.

**Comment by tati-kru** [comment] 2019-09-17 16:35
It is included to DBeaver EE by default. But for CE version the package is too big. Perhaps it will be included later, but we cannot give any promises.

**Closed by tati-kru** 2019-09-17 16:35 UTC
Labels: question

**Comment by stevenjlho** [comment] 2021-01-18 03:31
DBeaver CE is not include sshj package now?

**Comment by tati-kru** [comment] 2021-01-18 09:29
It is optional extension. You can install it from marketplace: https://github.com/dbeaver/dbeaver/wiki/Optional-extensions.
