### ISSUE TITLE
Export to SQL insert statement not working with selected columns

### ISSUE THREAD

**Issue by woeterman94** [dbeaver/dbeaver#12606] opened 2021-05-26 08:41 UTC
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.0.5
- Additional extensions: none

#### Connection specification:
- Database name and version: MS SQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

![image](https://user-images.githubusercontent.com/5755057/119631352-19690800-be10-11eb-812d-82c12261c610.png)

#### Describe the problem you're observing:
When selecting columns and rows and choosing export data -> export to SQL insert statements the mapping of columns is messed up. It seems like a column is skipped, causing the values to be in the wrong column.

(for example I select column 1,2,3,4), my sql insert statement has column 1,2,3,4 but data from column 1,2,4,5.

#### Steps to reproduce, if exist:
Select some columns and rows
![image](https://user-images.githubusercontent.com/5755057/119629801-a57a3000-be0e-11eb-8914-2329e6abdc17.png)

Choose export data -> export to sql insert

![image](https://user-images.githubusercontent.com/5755057/119629701-8da2ac00-be0e-11eb-948d-5a66d7e8a3a3.png)
Selected columns and rows only.

Sql script looks like this

![image](https://user-images.githubusercontent.com/5755057/119630024-d65a6500-be0e-11eb-950b-22c01e7708ca.png)
The "nameFr" column is somehow skipped.
(I tried to explain with some arrows etc)

**Comment by Matvey16** [comment] 2021-06-04 06:40
Hello, thank you for the report. I was not able to reproduce it. Are "NameFr" and "NameNl" columns in your example the same or is there something different in their metadata?

**Comment by woeterman94** [comment] 2021-06-04 06:57
Nope, they are the same. Did you try reordering the columns?

**Comment by Matvey16** [comment] 2021-06-04 09:36
Yes, and it still exports them normally. I see that you have checked a box to include generated columns. Are any of those columns computed and if not, have you tried the same export with this option unchecked?

**Comment by uslss** [comment] 2021-06-09 13:44
probably duplicates #9252

**Comment by Matvey16** [comment] 2021-06-09 14:59
Sorry for the late response. As mentioned above, it is probably caused by reordering of columns, because export doesn't respect that and uses the original ordering. So it is probably a duplicate of another issue that we can't fix right now.

**Comment by woeterman94** [comment] 2021-06-18 08:10
Hmm, any ideas how I can work around this ?

**Comment by Matvey16** [comment] 2021-06-21 06:56
For now you can try reordering columns to original order and select them using ctrl button. Original ordering can be seen in the properties tab of the table
 
![2021-06-21_09h51_55](https://user-images.githubusercontent.com/82543000/122719456-debf8780-d276-11eb-9c83-16884ef19fd7.png)

**Comment by uslss** [comment] 2021-07-07 09:19
will be fixed in the scope of #11843

**Closed as completed by uslss** 2021-07-07 09:19 UTC
Labels: duplicate, wait for response
