### ISSUE TITLE
Greenplum 4.3 - Expanding list of tables in schema gives the following error - SQL Error [42703]: ERROR: column x.urilocation does not exist   Position: 44

### ISSUE THREAD

**Issue by MrOsito** [dbeaver/dbeaver#5568] opened 2019-03-24 22:17 UTC
**Operating system (distribution) and version**
- Windows 10

**DBeaver version**
- v6.0

**Greenplum Server**
- v4.3

**Greenplum drivers**
- org.postgresql:postgresql:RELEASE [42.2.5]
- net.postgis:postgis-jdbc:RELEASE [2.3.0]
- net.postgis:postgis-jdbc-jtsparser:RELEASE [2.3.0]

**What's the issue?**
When I try and and expand the list of tables in a schema I get an error saying:
- SQL Error [42703]: ERROR: column x.urilocation does not exist
- Position: 44

The last working version of dBeaver was dBeaver CE 5.3.1 x86-64

**Comment by serge-rider** [comment] 2019-03-25 13:00
Please post error stacktrace (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by mnt1979** [comment] 2019-03-25 14:28
I have the same issue.  I am using version 6.0.0 and Greenplum drivers on Macbook.

**Comment by mnt1979** [comment] 2019-03-25 14:51
I have migrated my connection to PostgreSQL from Greenplum and it is working for me.  Greenplum drivers has some issues.


!ENTRY org.jkiss.dbeaver.model 4 0 2019-03-25 09:16:30.107
!MESSAGE SQL Error [42703]: ERROR: column x.urilocation does not exist
  Position: 44

!ENTRY org.jkiss.dbeaver.model 4 0 2019-03-25 09:22:57.648
!MESSAGE SQL Error [42703]: ERROR: column x.urilocation does not exist
  Position: 44
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-03-25 09:22:57.649
!MESSAGE ERROR: column x.urilocation does not exist
  Position: 44
!STACK 0
org.postgresql.util.PSQLException: ERROR: column x.urilocation does not exist
  Position: 44
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:260)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:204)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:70)
	at org.jkiss.dbeaver.model.impl.AbstractObjectCache.getTypedObjects(AbstractObjectCache.java:80)
	at org.jkiss.dbeaver.ext.greenplum.model.GreenplumSchema.getTables(GreenplumSchema.java:51)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:824)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:805)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:885)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:421)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:206)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:593)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by gcorboz** [comment] 2019-03-26 22:10
Hi Serge is the log that mnt1979 provided fit for purpose or do you need me to provide a log as well.

**Comment by MrOsito** [comment] 2019-04-02 07:12
This issue is duplicated by issue: https://github.com/dbeaver/dbeaver/issues/5464

**Comment by iMchxx** [comment] 2019-04-03 01:50
win10 pro.
greenplum 4.2
my dbeaver is 6.0.1 , and it may has the same error since 5.4.

**Comment by serge-rider** [comment] 2019-04-03 16:32
Duplicate of #5464
See fix in 6.0.2

**Closed by serge-rider** 2019-04-03 16:32 UTC
Labels: bug, can't reproduce, duplicate, x:greenplum
